### ISSUE TITLE
expose language setting

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#1088]
Currently Lantern doesn't allow the user to change the language it's in, but rather just uses the language the system is set to (like most other desktop software). Some users have requested the ability to set Lantern's language independently.

**Comment by atavism** [comment]
@myleshorton and @oxtoacart, you should be able to toggle languages in developer mode on 0.0.12 now.

**Comment by myleshorton** [comment]
Nice thanks!

On Fri, Jan 16, 2015 at 2:40 PM, atavism <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> and @oxtoacart
> <https://github.com/oxtoacart>, you should be able to toggle languages in
> developer mode on 0.0.12 now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1088#issuecomment-70334407>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
