### ISSUE TITLE
peers/dots not showing up in Lantern UI Browser on OS X (WebView)

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#1294]
Notice the green dot in Singapore is missing in the Lantern UI Browser, but correctly shows up in Chrome (behind and right):

![screen shot 2014-01-07 at 12 06 07](https://f.cloud.github.com/assets/475147/1861133/f9ca09cc-77bd-11e3-8257-b36d5ebcf180.png)

**Comment by atavism** [comment]
We aren't using WebView anymore so I'm pretty sure we can close this out.
