### ISSUE TITLE
prompt to switch from Get to Give mode when location changes from censoring to non-censoring country

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#1364]
We currently detect when the user's location changes from a non-censoring country to a censoring country, and if the mode was Give Mode, we change it to Get Mode (and don't allow changing back to Give Mode while in the censoring country). This is to prevent Lantern users trying to get uncensored access from being routed through users with censored connections.

We could similarly detect when the user's location changes from a censoring country to a non-censoring country, and ask if she wants to change from Get Mode to Give Mode. Note that we don't do this automatically because the change to Give Mode causes the user's internet connection to be shared, which the user should always explicitly opt into.

**Comment by myleshorton** [comment]
Very rare -- will handle if it comes up.
