### ISSUE TITLE
Change "Not yet connected" copy

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1371]
This has confused users, making them think their friend invite did not work. Could be something like "Invited" instead.

**Comment by atavism** [comment]
@myleshorton Since this has been referenced in multiple tickets recently, and it's trivial to change, we might as well get it out with the other UI improvements. What did we want to change the string to?

**Comment by myleshorton** [comment]
I think ideally it would reflect the status of that friend, such as
invited, installed, etc, but I don't think the front end currently gets all
that data.

On Monday, January 12, 2015, atavism <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Since this has been
> referenced in multiple tickets recently, and it's trivial to change, we
> might as well get it out with the other UI improvements. What did we want
> to change the string to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1371#issuecomment-69650641>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
It looks like the front end knows when a friend connected last based on the peer lastConnected stat. If that field is present and non-zero, in that scenario we could display "Installed" instead and replace "Not yet connected" with "Invited". Then leave the remaining messages the same. That could clear up some of the confusion.

**Comment by myleshorton** [comment]
So the real problem is that it's reflecting whether or not we've actually made a network connection with that user, which is largely irrelevant in many cases, such as a get mode friend with all get mode friends, because you'll never create a network connection. So I don't think lastConnected is what we want. It also look like that's never actually set in the code anymore, so definitely won't do the trick.

**Comment by oxtoacart** [comment]
Ideally, we would show whether or not your friend has friended you, but I'm not sure that we have that information available without making changes to the controller.

**Comment by atavism** [comment]
Ah, makes sense. Not familiar with the controller code, but it looks like that info could be exposed and sent to the front end fairly easily https://github.com/getlantern/lantern-controller/blob/master/src/main/java/org/lantern/friending/Friending.java#L406 -- the different status messages could be "Invited", "Installed", "Friends", and possibly "Connected"/"Online Now"?

**Comment by oxtoacart** [comment]
Yeah.  Since we already use that status field for a lot of stuff, it might be safer just to add a new field to indicate the reciprocal status.

**Comment by myleshorton** [comment]
> the different status messages could be "Invited", "Installed", "Friends"/"Offline", and possibly "Connected"/"Online"?

Yeah I think that sounds about right. Not sure where the reciprocal one fits in there, but maybe just "Friends"
