### ISSUE TITLE
'not enough disk space!' error on installing in Win8.1

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#1469]
Reported by a user.  Claims there are other people experiencing the same problem.

**Comment by myleshorton** [comment]
Hopefully not an issue with new installers.

**Comment by kenkangxgwe** [comment]
I meet the same problem, after I reinstall the windows 8.1.
The installer worked well on my previous win8.1 system.

**Comment by myleshorton** [comment]
I would try the betas up at https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions @kenkangxgwe 

They're not optimized for China yet, but it should still work pretty well.

**Comment by xing634325131** [comment]
I meet the problem.WIndows8.1
![qq 20150503122442](https://cloud.githubusercontent.com/assets/3675673/7443648/8935f30e-f18f-11e4-9f91-965e48d9ce16.png)
reinstall os...

**Comment by myleshorton** [comment]
I would try the beta linked from the home page - lots of improvements
including completely new installers.
