### ISSUE TITLE
Have to manually stop the Lantern.exe process to uninstall on Windows

### ISSUE THREAD

**Issue by scouttle** [getlantern/lantern#1687]
The Windows uninstaller doesn't auto-stop the Lantern.exe process, so I have to use the Task Manager to do it before the uninstaller can work. This honestly has more of an impact on us (because we're testing the from-scratch install a lot) than on users, but it will be very confusing/frustrating for users who aren't familiar with the Task Manager.

**Comment by myleshorton** [comment]
Hey I didn't notice if this is integrated in the latest NSIS installer @oxtoacart. Is it? If not it's an easy add.

**Comment by oxtoacart** [comment]
This is fixed in Valencia, yes.  We kill any existing lantern process on install and uninstall.

Note - this only works when upgrading from a Go-based release.  If you were running the old Java Lantern, you might still see this error.  Since we're not supporting that use case, we can close this.
