### ISSUE TITLE
Impossible to use lantern without signing in with google?

### ISSUE THREAD

**Issue by turbolego** [getlantern/lantern#1717]
I don't want to sign it with google.

How can i use lantern without signing in with google?

**Comment by myleshorton** [comment]
This is fixed in the Valencia release.

**Comment by ed2k** [comment]
what is valencia release, is there anywhere else mention that release name?

**Comment by atavism** [comment]
Hey @ed2k, it's a new version of get-mode Lantern that doesn't require logging in at all. We'll be announcing the first release on the mailing list very soon (probably next week!)
