### ISSUE TITLE
Receiving 409 error on some flashlight requests through CloudFlare

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1739]
I ran the flashlight client manually with these flags:

`-role client -addr localhost:10080 -server roundrobin.getiantem.org -masquerade cdnjs.com`

On testing with curl, some requests would fail, and the flashlight log would show this:

`2014/08/23 11:17:31 Unable to issue read request: Bad response status for read: 409 Conflict`

**Comment by myleshorton** [comment]
This is definitely still happening on devel and actually causes Google login to fail in some cases.

**Comment by myleshorton** [comment]
It does look like it's possible we're triggering CloudFlare's DDOS protection, as I'm seeing a lot of this type of thing in the logs:

```
155484 2015-02-03 09:08:32,976 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying cursecdn.com
155484 2015-02-03 09:08:32,976 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying lifehacker.com.au
155485 2015-02-03 09:08:32,977 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying oyunkolu.com
155485 2015-02-03 09:08:32,977 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying pelis24.com
155485 2015-02-03 09:08:32,977 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying www.okcupid.com
155902 2015-02-03 09:08:33,394 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying proxybay.info
156470 2015-02-03 09:08:33,962 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying lowendtalk.com
157153 2015-02-03 09:08:34,645 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying sergey-mavrodi.com
157262 2015-02-03 09:08:34,754 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying www.thingiverse.com
157457 2015-02-03 09:08:34,949 ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.handleLine (LoggingStreamHandler.java:125) - fronted: Timed out verifying thebot.net
```

**Comment by oxtoacart** [comment]
@myleshorton I think the 409 error has something to do with a problem in the DNS settings.  Looking into it now.

**Comment by oxtoacart** [comment]
So, I see the error quite a bit when running with fallbacks.getiantem.org.  However, if I point my flashlight.yaml at a specific fallback, I don't see the error.  So, perhaps something is wrong in the fallbacks rotation.

**Comment by oxtoacart** [comment]
For some reason, there are two fallbacks registered with the same ip `128.199.113.148`, fl-singapore-003-2 and fl-singapore-003-20.  003-20 doesn't even have an active droplet.  I'll try deleting it.

**Comment by oxtoacart** [comment]
@myleshorton I'm not seeing the 409 error at the moment.  Are you?

**Comment by oxtoacart** [comment]
@myleshorton I added a little program for checking duplicates in CloudFlare - https://github.com/getlantern/flashlight-build/commit/46122e3c39b9b974806c0b7e62c53827f314181f

**Comment by oxtoacart** [comment]
Weird, now I see

`enproxy: Dest: www.google.com:80    ProxyHost: fl-ara-002.getiantem.org    Unable to issue read request: Bad response status for read: 409 Conflict`

But I don't even see fl-ara-002 in DNS ...

**Comment by oxtoacart** [comment]
Well, its ip was in DNS as fl-newyork-001-1.  It looks like that IP got recycled, so we were sending traffic to a host that was reporting a new name but still in DNS under an old name.

**Comment by oxtoacart** [comment]
Okay, I deleted the fl-newyork-001-1 entry.  Might be good now (at least until this happens again).

**Comment by oxtoacart** [comment]
I think to be safe, the code in peerscanner that tests a host should make sure that the reported host matches the name under which the host is requesting to be registered.  If they don't match, we shouldn't add it into rotation.

**Comment by oxtoacart** [comment]
I just ran a test with boom making 250 requests and didn't get any 409's.

**Comment by myleshorton** [comment]
Fascinating @oxtoacart. 

> For some reason, there are two fallbacks registered with the same ip 128.199.113.148, fl-singapore-003-2 and fl-singapore-003-20. 003-20 doesn't even have an active droplet. I'll try deleting it.

Were both actually in the roundrobin as well? I wonder if the automatic restarts could cause something like that? Although I don't see fl-singapore-003-20 in any alerts at all.

**Comment by oxtoacart** [comment]
The only thing in the roundrobin is the ip, so by definition it can only appear once.  fl-singapore-003-20 is one that I think I removed manually a while ago because it was chronically overloaded.

**Comment by oxtoacart** [comment]
@myleshorton This is now fixed in the peerscanner branch.

**Comment by myleshorton** [comment]
I guess I don't understand how the conflict arises then. Everything is always referenced by domain name when hitting the same proxy for sticky routing right? Maybe they're just seeing that on their end and sending an error regardless? Odd.

**Comment by oxtoacart** [comment]
409 conflict is a bit of a misnomer.  We were proxying through a host that returned the name fl-ara but that was registered as fl-newyork.  So the request to fl-ara fails because CloudFlare doesn't know what to do with it.

**Comment by myleshorton** [comment]
Awesome @oxtoacart thanks!

**Comment by myleshorton** [comment]
I'm seeing this on the issue-2195 for the host:

fl-singapore-005-33.getiantem.org

**Comment by oxtoacart** [comment]
Interesting - the IP corresponding to that host is in roundrobin.getiantem.org with a gray cloud (should be orange) and it's not individually registered.  So, this is either a duplicate of or related to #2216.

**Comment by myleshorton** [comment]
OK I'm going to manually set those to orange in production for now.

**Comment by oxtoacart** [comment]
Thanks Myles.  Unfortunately, that didn't help because when there are
servers in rotation that don't have a corresponding entry of their own, we
still get 409 conflict.

I restarted peerscanner to deal with this.  On startup, peerscanner looks
for anything in rotation that doesn't have a matching individual entry and
removes it from rotation.

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by oxtoacart** [comment]
Fixed along with #2216.

**Comment by myleshorton** [comment]
Seeing this again.

**Comment by oxtoacart** [comment]
@myleshorton Can you include recent log snippets please?

**Comment by myleshorton** [comment]
Yeah looks like it's all the one host:

fronted: HTTP ERROR FOR MASQUERADE zemtv.com: Head http://www.google.com/humans.txt: Dest: www.google.com:80    ProxyHost: 2e293647f92bc9204609150c2980ba28.getiantem.org    Unable to issue read request: Bad response status for read: 409 Conflict
enproxy: Dest: www.google.com:80    ProxyHost: 2e293647f92bc9204609150c2980ba28.getiantem.org    Unable to issue read request: Bad response status for read: 409 Conflict
enproxy: Dest: live.github.com:443    ProxyHost: 2e293647f92bc9204609150c2980ba28.getiantem.org    Unable to issue read request: Bad response status for read: 409 Conflict

**Comment by oxtoacart** [comment]
Here's one recent snippet:

```
Mar 01 09:27:08.010 - fronted: HTTP ERROR FOR MASQUERADE addmefast.com: Head http://www.google.com/humans.txt: Dest: www.google.com:80    ProxyHost: 2e293647f92bc9204609150c2980ba28.getiantem.org    Unable to issue read request: Bad response status for read: 409 Conflict
```

This is a peer.  I think the root cause is likely different this time.

@myleshorton Have you seen this for anything other than peers recently?

**Comment by myleshorton** [comment]
I'm only seeing it for that peer right now @oxtoacart

**Comment by oxtoacart** [comment]
The peers rotation looks very messed up.  There are a bunch of ips in there that don't correspond to individual registered peers, and they all have the orange cloud off.

**Comment by myleshorton** [comment]
Oh wow.

**Comment by oxtoacart** [comment]
Okay, what happened here is that I deployed a peerscanner built from the valencia branch, but the latest peerscanner updates (which dealt with the orange cloud issue) were actually on devel.  I've now merged devel into valencia and rebuilt peerscanner from there.

**Comment by oxtoacart** [comment]
To clarify a little, the change that I made to track country-specific rotations was made in the valencia branch, which didn't have the most recent peerscanner updates from devel.  By merging devel into valencia and building from there, peerscanner now has the country-specific rotation tracking along with the most recent updates from devel.

**Comment by myleshorton** [comment]
Awesome!!

On Sun, Mar 1, 2015 at 11:33 PM, oxtoacart <notifications@github.com> wrote:

> To clarify a little, the change that I made to track country-specific
> rotations was made in the valencia branch, which didn't have the most
> recent peerscanner updates from devel. By merging devel into valencia and
> building from there, peerscanner now has the country-specific rotation
> tracking along with the most recent updates from devel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1739#issuecomment-76635383>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Still happening :(

**Comment by oxtoacart** [comment]
This most recent time it happened with fallbacks in the nl.fallbacks rotation.
