### ISSUE TITLE
Speed up flashlight/Lantern by making geography-sensitive server pools

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1763]
I noticed that browsing with flashlight from the U.S. is very slow, which is not surprising given that all of our servers are in Singapore.  For comparison, I launched flashlight server in the DO New York data center and pinned my flashlight client to that.  The difference was night and day.

Since clients can geolocate themselves, and we have full control over the dns settings in CloudFlare, I think it would be nice if we can figure out a way to have clients use flashlight servers that are geographically near them, either exclusively or at least preferentially.

**Comment by atavism** [comment]
@oxtoacart, I'm not sure how you were planning to implement this, but I started reading about this further and came across a library called [dns-clb-go](https://github.com/benschw/dns-clb-go) you may be interested in. It facilitates DNS-based service discovery in a Go application using SRV records. It has really nice flexibility: you can plug in a customized load balancer (it already supports round-robin) and/or caching strategy. The basic idea here would be to optimally sort available instances for serving a client using DNS queries according to SRV record priority field, similar to what (SkyDNS)[https://github.com/skynetservices/skydns] already does. Anyway, thought this might be a useful resource!

**Comment by oxtoacart** [comment]
@atavism That looks very neat, thanks!  The challenge that we have is that our client can't use DNS, as it is subject to poisoning by the censors, so I don't know that we could take advantage of this for domain-fronting.  What do you think?

**Comment by atavism** [comment]
@oxtoacart I hadn't thought about DNS poisoning making the proposition untenable. This is probably further down the road, but would one possible work around be to use this in conjunction with an encrypted DNS service like [DNSCrypt](https://github.com/opendns/dnscrypt-proxy) and OpenDNS?

**Comment by myleshorton** [comment]
Yeah the other theoretical issue outside of straight poisoning is DNS blocking at the IP level. I'm not sure that's happening or not, but it reflects the large issue of introducing another single point of control.

One thing we should look at is how some of these VNPs are staying up at all -- Astril in particular seems to do a pretty decent job of it and seems to have primarily been blocked just at the protocol level. My guess is they're rotating through IPs and servers super quickly along the lines of what we've talked about with on-demand instances, but it would be interesting to investigate further.

I do think SRV records can generally be handy, but I also agree DNS in general is something we more or less want to avoid because of the blocking issues.

**Comment by atavism** [comment]
> Yeah the other theoretical issue outside of straight poisoning is DNS blocking at the IP level. I'm not sure that's happening or not, but it reflects the larger issue of introducing another single point of control.

Yeah, I'm not sure if it's happening or not either. It appears OpenDNS servers have remain unblocked in China.

> One thing we should look at is how some of these VNPs are staying up at all -- Astril in particular seems to do a pretty decent job of it and seems to have primarily been blocked just at the protocol level. My guess is they're rotating through IPs and servers super quickly along the lines of what we've talked about with on-demand instances, but it would be interesting to investigate further.

[This thread](http://forums.whirlpool.net.au/archive/2268274) has some more information, but it sounds like Astrill has been able to stay unblocked in particular because most of their network uses VPNs automatically configured in [stealth mode](https://torguard.net/stealth-vpn.php) to disguise traffic. Then they probably quickly deploy and rotate instances as you said.

**Comment by myleshorton** [comment]
I just wanted to note here too that the key is really locating our data center **close to the CloudFlare data center** or other domain-fronted data centers that get traffic from the regions we're targeting. For China that's Hong Kong and not sure for Iran.

**Comment by myleshorton** [comment]
I keep saying "for China that's Hong Kong" -- just saw that in an old email too -- but that's actually incorrect. Most traffic through CloudFlare from China should go through South Korea.

**Comment by oxtoacart** [comment]
So, interestingly enough, I've run a couple of traceroutes from a VPS in China, and on both I see that the first hop outside of China is actually in western Europe.

```bash
traceroute geo.getiantem.org
...
11  218.30.54.162 (218.30.54.162)  158.268 ms  159.027 ms  158.604 ms
12  as4436.ip4.gtt.net (77.67.70.130)  146.704 ms  147.131 ms  147.115 ms
13  as13335.xe-8-0-0.cr1.sjc1.us.as4436.gtt.net (69.22.153.198)  151.725 ms vlan-73.ar1.lax1.us.as4436.gtt.net (69.31.125.241)  157.641 ms as13335.xe-9-0-2.ar2.sjc1.us.as4436.gtt.net (69.22.153.74)  180.126 ms
14  as13335.xe-11-0-6.ar1.lax1.us.nlayer.net (69.31.125.106)  136.513 ms 198.41.185.136 (198.41.185.136)  165.466 ms as13335.xe-9-0-7.ar1.lax1.us.nlayer.net (69.31.127.62)  144.870 ms
```

11 is in China, 12 is somewhere in Germany, France, UK region.

This raises a couple of questions:

1. CloudFlare has [data centers](https://www.cloudflare.com/network-map) in east Asia. Why don't we seem to be hitting these?

2. If we're not going to be hitting CF data centers in east Asia, perhaps our existing servers in Europe serve China just fine?

**Comment by oxtoacart** [comment]
So, using the Netherlands servers from China is definitely slow:

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	775.8472 secs.
  Slowest:	8.2593 secs.
  Fastest:	2.2859 secs.
  Average:	3.0894 secs.
  Requests/sec:	3.2210

Status code distribution:
  [200]	2499 responses

Response time histogram:
  2.286 [1]	|
  2.883 [963]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.481 [1087]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  4.078 [345]	|∎∎∎∎∎∎∎∎∎∎∎∎
  4.675 [65]	|∎∎
  5.273 [20]	|
  5.870 [12]	|
  6.467 [4]	|
  7.065 [0]	|
  7.662 [0]	|
  8.259 [2]	|

Latency distribution:
  10% in 2.5184 secs.
  25% in 2.6928 secs.
  50% in 3.0156 secs.
  75% in 3.3414 secs.
  90% in 3.7181 secs.
  95% in 4.0099 secs.
  99% in 4.9748 secs.

Error distribution:
  [1]	Get https://173.194.127.178/humans.txt: EOF
```

**Comment by myleshorton** [comment]
Cool. I still think Vultr seems like an interesting option to test -- https://www.vultr.com/locations/

**Comment by oxtoacart** [comment]
Yes, I'll try Vultr's Tokyo data center next.

**Comment by oxtoacart** [comment]
Here are the results of testing with the Singapore servers (for comparison).  Interestingly, they're worse than Netherlands, which gives us some idea of what our Chinese users have been dealing with.

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	890.3818 secs.
  Slowest:	11.7292 secs.
  Fastest:	1.4875 secs.
  Average:	3.5452 secs.
  Requests/sec:	2.8044

Status code distribution:
  [200]	2497 responses

Response time histogram:
  1.487 [1]	|
  2.512 [216]	|∎∎∎∎∎∎∎
  3.536 [973]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  4.560 [1221]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  5.584 [75]	|∎∎
  6.608 [6]	|
  7.633 [3]	|
  8.657 [0]	|
  9.681 [1]	|
  10.705 [0]	|
  11.729 [1]	|

Latency distribution:
  10% in 2.6685 secs.
  25% in 3.0185 secs.
  50% in 3.5762 secs.
  75% in 4.0141 secs.
  90% in 4.1863 secs.
  95% in 4.3799 secs.
  99% in 5.1669 secs.

Error distribution:
  [3]	Get https://173.194.127.212/humans.txt: EOF
```

**Comment by myleshorton** [comment]
Wow -- that's incredibly valuable. Also, we actually have access to the otf cloud now, which lets us set up data centers in both Hong Kong and Seoul, which would be super interesting for comparison. Credentials added to too-many-secrets, access at https://portal.otfcloud.org

**Comment by oxtoacart** [comment]
Here are the results using Vultr's Tokyo data center.  Much better overall.  However, it's still significantly slower than the 0.9459 seconds/request average that we saw when testing from Iran to Netherlands.

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	378.5310 secs.
  Slowest:	4.0847 secs.
  Fastest:	1.3134 secs.
  Average:	1.5040 secs.
  Requests/sec:	6.5992

Status code distribution:
  [200]	2498 responses

Response time histogram:
  1.313 [1]	|
  1.591 [2116]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1.868 [318]	|∎∎∎∎∎∎
  2.145 [47]	|
  2.422 [8]	|
  2.699 [2]	|
  2.976 [2]	|
  3.253 [1]	|
  3.530 [0]	|
  3.808 [1]	|
  4.085 [2]	|

Latency distribution:
  10% in 1.3920 secs.
  25% in 1.4251 secs.
  50% in 1.4637 secs.
  75% in 1.5204 secs.
  90% in 1.6892 secs.
  95% in 1.7783 secs.
  99% in 2.0146 secs.

Error distribution:
  [2]	Get https://173.194.127.180/humans.txt: EOF
```

**Comment by myleshorton** [comment]
Interesting. It seems like the Hong Kong and Seoul ones are the next
obvious candidates.

On Tue, Mar 10, 2015 at 3:08 PM, oxtoacart <notifications@github.com> wrote:

> Here are the results using Vultr's Tokyo data center. Much better overall.
> However, it's still significantly slower than the 0.9459 seconds/request
> average that we saw when testing from Iran to Netherlands.
>
> boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt
> 2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %
>
> Summary:
>   Total:    378.5310 secs.
>   Slowest:  4.0847 secs.
>   Fastest:  1.3134 secs.
>   Average:  1.5040 secs.
>   Requests/sec: 6.5992
>
> Status code distribution:
>   [200] 2498 responses
>
> Response time histogram:
>   1.313 [1] |
>   1.591 [2116]  |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
>   1.868 [318]   |∎∎∎∎∎∎
>   2.145 [47]    |
>   2.422 [8] |
>   2.699 [2] |
>   2.976 [2] |
>   3.253 [1] |
>   3.530 [0] |
>   3.808 [1] |
>   4.085 [2] |
>
> Latency distribution:
>   10% in 1.3920 secs.
>   25% in 1.4251 secs.
>   50% in 1.4637 secs.
>   75% in 1.5204 secs.
>   90% in 1.6892 secs.
>   95% in 1.7783 secs.
>   99% in 2.0146 secs.
>
> Error distribution:
>   [2]   Get https://173.194.127.180/humans.txt: EOF
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1763#issuecomment-78159349>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Here are the results using an otfcloud server in Hong Kong.  Slightly worse than Tokyo.

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	470.8731 secs.
  Slowest:	10.8694 secs.
  Fastest:	1.3044 secs.
  Average:	1.8792 secs.
  Requests/sec:	5.3093

Status code distribution:
  [200]	2500 responses

Response time histogram:
  1.304 [1]	|
  2.261 [2081]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.217 [323]	|∎∎∎∎∎∎
  4.174 [63]	|∎
  5.130 [15]	|
  6.087 [10]	|
  7.043 [3]	|
  8.000 [2]	|
  8.956 [1]	|
  9.913 [0]	|
  10.869 [1]	|

Latency distribution:
  10% in 1.4542 secs.
  25% in 1.5170 secs.
  50% in 1.6274 secs.
  75% in 2.0265 secs.
  90% in 2.5897 secs.
  95% in 2.9957 secs.
  99% in 4.3277 secs.
```

**Comment by oxtoacart** [comment]
And here are the results using an otfcloud server in South Korea. Slightly worse than Hong Kong.

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	489.0403 secs.
  Slowest:	16.0696 secs.
  Fastest:	1.4431 secs.
  Average:	1.9452 secs.
  Requests/sec:	5.1100

Status code distribution:
  [200]	2499 responses

Response time histogram:
  1.443 [1]	|
  2.906 [2431]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  4.368 [61]	|∎
  5.831 [3]	|
  7.294 [1]	|
  8.756 [0]	|
  10.219 [0]	|
  11.682 [1]	|
  13.144 [0]	|
  14.607 [0]	|
  16.070 [1]	|

Latency distribution:
  10% in 1.5876 secs.
  25% in 1.6671 secs.
  50% in 1.8210 secs.
  75% in 2.1137 secs.
  90% in 2.3867 secs.
  95% in 2.6463 secs.
  99% in 3.3163 secs.

Error distribution:
  [1]	Get https://173.194.127.20/humans.txt: EOF
```

**Comment by oxtoacart** [comment]
I don't think the otfcloud Hong Kong server was a good test platform for this.  I used [speedtest-cli](https://github.com/sivel/speedtest-cli) to check how fast the connections on the three test servers are, with the below results.  Notice the really slow upload speed on the otfcloud Hong Kong server.

If we can find a Hong Kong server with a good internet connection, that might prove to be the fastest in this test.  So far though, it looks like all of the east-Asian data centers are in the same ballpark.

### vultr Tokyo
```
./speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Choopa, LLC (104.238.160.157)...
Selecting best server based on latency...
Hosted by Too late (Ishikari) [853.90 km]: 33.689 ms
Testing download speed........................................
Download: 87.85 Mbit/s
Testing upload speed..................................................
Upload: 33.01 Mbit/s
```

### otfcloud Hong Kong
```
./speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from PowerNetIX Ltd (202.85.233.48)...
Selecting best server based on latency...
Hosted by STC (Hong Kong) [1.06 km]: 6.059 ms
Testing download speed........................................
Download: 47.84 Mbit/s
Testing upload speed..................................................
Upload: 0.75 Mbit/s
```

### otfcloud South Korea
```
./speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from BORANET (1.209.122.30)...
Selecting best server based on latency...
Hosted by China Unicom (Qingdao) [611.01 km]: 68.423 ms
Testing download speed........................................
Download: 198.23 Mbit/s
Testing upload speed..................................................
Upload: 35.93 Mbit/s
```

**Comment by myleshorton** [comment]
Looks like Rackspace has a Hong Kong data center. I'm having trouble finding others though.

EC2 in Tokyo might be worth a shot too.

**Comment by aranhoide** [comment]
Are the flashlight benchmarks using domain fronting?  IIRC for domain fronting we are hardcoding the IPs as resolved in Singapore.  Might this affect the results, anycast notwithstanding?

**Comment by aranhoide** [comment]
BTW if the location where the IPs are resolved does make a difference, one thing to try would be to introduce location-sensitive IPs in the configuration.  Those would be either specific to each datacenter or (harder to anticipate) to user location.

**Comment by oxtoacart** [comment]
@aranhoide That's a great point, it very well could.  I'll try running the test without the ips and see if that makes a difference.

BTW, what was the reason we hardcoded the IPs again?

**Comment by aranhoide** [comment]
@oxtoacart IIRC we conjectured that IPs were less likely to get blocked than the corresponding domains.

**Comment by aranhoide** [comment]
IIRC we fall back to domains though, so if you remove the IPs from the config yaml you should get more neutral benchmarks (I think that's what you meant by "running the test without the ips"?).

**Comment by oxtoacart** [comment]
@aranhoide Yes, that's what I meant by running the test without the ips.  I'll actually just hack the code to ignore the ip.

BTW, I've been generating the cloud.yaml from my local machine, so the IPs in circulation have not been Singapore-specific in a long time.

**Comment by aranhoide** [comment]
If masquerade IPs matter, that may explain a bias in favor of Amsterdam wrt Singapore.

**Comment by oxtoacart** [comment]
Yup.

**Comment by aranhoide** [comment]
A cheaper way to do (again, if IPs affect speed) would be to try resolving the domains first, and only using IPs as a backup.  That way we get location-sensitive IPs without complicating the code or our processes, and lantern keeps working (albeit slower) if the masquerade domains are blocked but the IPs aren't.  If we detect that condition in the field then we can worry about speeding up the IPs.

**Comment by oxtoacart** [comment]
I ran a test against our Tokyo server without IPs.  I did this by reducing the masquerades list to a handful of domains and removing their hardcoded IPs.  Results are below.  This doesn't look significantly different than the original run.

```
boom -allow-insecure -n 2500 -c 10 -q 10 -x http://localhost:8787 -disable-keepalive -t 20000 https://www.google.com/humans.txt 
2500 / 2500 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 

Summary:
  Total:	356.7599 secs.
  Slowest:	15.1102 secs.
  Fastest:	1.1976 secs.
  Average:	1.4189 secs.
  Requests/sec:	7.0019

Status code distribution:
  [200]	2498 responses

Response time histogram:
  1.198 [1]	|
  2.589 [2481]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.980 [11]	|
  5.371 [2]	|
  6.763 [1]	|
  8.154 [0]	|
  9.545 [0]	|
  10.936 [1]	|
  12.328 [0]	|
  13.719 [0]	|
  15.110 [1]	|

Latency distribution:
  10% in 1.2866 secs.
  25% in 1.3201 secs.
  50% in 1.3610 secs.
  75% in 1.4144 secs.
  90% in 1.5832 secs.
  95% in 1.7404 secs.
  99% in 2.2609 secs.

Error distribution:
  [2]	Get https://173.194.72.99/humans.txt: EOF
```

**Comment by oxtoacart** [comment]
@aranhoide I was hoping that linode had a Tokyo data center, since it's supported by Salt Cloud.  Sadly, after signing up, I found out that they're still rolling it out and it's not yet available.

Do you have an idea how difficult it would be to support configuring Vultr instances with Salt?

**Comment by aranhoide** [comment]
I don't have an idea about how hard it is to support a new provider with
salt-cloud.  I'll look it up.

Note, though, that the only operations we perform with salt-cloud are
provisioning and killing instances.  In a pinch, it shouldn't be hard to do
those directly via the Vultr API.  Once you run the salt-bootstrap script,
a Vultr Ubuntu 14.04 x64 VM shouldn't be any different from our other
instances.

**Comment by animesfunn** [comment]
helo can you help me,,,? singapore server in the philippines is block...like fl-sg......i only use for now is netherland server for flashlight...but its to slow compared to sg ....can u gave me some example of server like hongkong ..newyork?

**Comment by myleshorton** [comment]
Just chatted about this on our call and decided to do the following:

1. Include the user's country code in the cloud.yaml URL, so, for example from cloud.ir.yaml
1. If the user's specific country code 404s or does not return a 200, then the client requests the default such cloud.default.yaml

**Comment by atavism** [comment]
I was writing an LEP for this: https://github.com/getlantern/lantern-roadmap/blob/0013_pbss/lep/DRAFT/0013_Proximity_Based_Server_Selection.md

**Comment by aranhoide** [comment]
@atavism : yes, what @myleshorton is describing is a MVP of sorts; the quickest thing that will get Chinese users access to the newly launched Tokyo servers ASAP, without degrading service for countries where the Netherlands is faster.

I've just uploaded the following:

http://s3.amazonaws.com/lantern_config/cloud.default.yaml.gz  (which is the same as 2.0.0-nl)

http://s3.amazonaws.com/lantern_config/cloud.cn.yaml.gz (which points to the Tokyo chained and fronted servers).

Tomorrow I'll add the logic to the client.
