### ISSUE TITLE
Possible UI improvements: faster overlay detection, zoom & pan/drag functionality

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#1768]
Some nice new features with d3 TopoJson maps: http://techslides.com/demos/d3/d3-worldmap-boilerplate.html

**Comment by myleshorton** [comment]
It looks like there's a regression with the blur around get mode peers on the map:

![image](https://cloud.githubusercontent.com/assets/1143966/6025384/ec7d637e-ab86-11e4-9e04-3c080a8a7046.png)

**Comment by myleshorton** [comment]
Or maybe it's just more noticeable in get mode...

**Comment by atavism** [comment]
> It  looks like there's a regression with the blur around get mode peers on the map @atavism 

@myleshorton I'm seeing this too, but I don't think it's a regression. I think what's going on at that spot on the map: there are two adjacent or overlapping peers, and that's increasing the overall size/distortion of the dot, especially since the appearance of every other get-mode peer looks fine. Decreasing the gaussian blur standard deviation slightly seems to mitigate this.

**Comment by myleshorton** [comment]
I actually saw that for a few get mode peers through @atavism -- actually all the ones I saw were that way.

**Comment by atavism** [comment]
@myleshorton I think I resolved the issue. Do get mode peers on the map look better for you now?

**Comment by atavism** [comment]
@myleshorton I think I resolved the issue. Do get mode peers on the map look better for you now?

**Comment by myleshorton** [comment]
Yes looks great thanks @atavism!
