### ISSUE TITLE
Consolidate cloudmasters

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1792]
There's currently a fisk-cloudmaster that a lot of servers are tied to -- we should consolidate on main cloudmaster!

**Comment by aranhoide** [comment]
This is done.  The new production cloudmaster is called 'production-cloudmaster'.  The old ones have been killed, and all their minions have been relaunched or reparented to the new one.  The DNS entries of the old flashlight servers have been cleaned up.

**Comment by myleshorton** [comment]
Awesome @aranhoide!

On Thu, Feb 19, 2015 at 9:20 AM, aranhoide <notifications@github.com> wrote:

> Closed #1792 <https://github.com/getlantern/lantern/issues/1792>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/1792#event-238533021>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Fantastic!  The new servers are working great for me.
