### ISSUE TITLE
peerscanner - Test fallbacks and peers separately

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1836]
Fallbacks are tested multiple times before being taken out of rotation, which can theoretically take a while.  This would hang up the pace at which we can check peers, so it probably makes sense to do peers and fallbacks completely in parallel.

**Comment by myleshorton** [comment]
This still an issue with the latest round @oxtoacart?

**Comment by oxtoacart** [comment]
This is fixed.
