### ISSUE TITLE
Reduce size of natty binary

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#1847]
There's some command flags to pass gyp to remove the extraneous libraries.. just need to make sure natty still compiles with these dependencies stripped out.

gyp --depth=. -Dinclude_tests=0 -Denable_protobuf=0 -Denable_video=0 jingle.gyp

**Comment by myleshorton** [comment]
It would also be useful @fffw to update to the latest web rtc, which there should be scripts.
