### ISSUE TITLE
flashlight leaking file descriptors

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1879]
This appears to be happening fairly slowly, but it's happening.  flashlight is leaving some sockets in CLOSED or CLOSE_NOTIFY state.  This may be related to my recent fixes for #1850.

**Comment by myleshorton** [comment]
Any remaining signs of this @oxtoacart?

**Comment by oxtoacart** [comment]
I believe that with the changes to enproxy on the peerscanner branch, this is resolved.
