### ISSUE TITLE
Draft blog post to wrap up Indiegogo campaign

### ISSUE THREAD

**Issue by scouttle** [getlantern/lantern#1882]

**Comment by myleshorton** [comment]
Hey @carsonefv do you guys maybe want to give this one a shot?

**Comment by carsonefv** [comment]
This can be similar to the indiegogo thankyou e-mail text once we finish that, the draft can be found here" https://docs.google.com/document/d/1rO122-oQ6ZWfr0mMOx7YRj96Km1UM0620ZYBF9G34Hc/edit?usp=sharing
