### ISSUE TITLE
Draft thank-you emails to Indiegogo donors

### ISSUE THREAD

**Issue by scouttle** [getlantern/lantern#1883]
We can make slightly-modified versions for each group, but the bulk of the email will be the same across the board (and probably very similar to the blog post in #1882 as well).

**Comment by myleshorton** [comment]
And possibly this one too @carsonefv?

**Comment by carsonefv** [comment]
Yes, the draft is here but needs review: https://docs.google.com/document/d/1rO122-oQ6ZWfr0mMOx7YRj96Km1UM0620ZYBF9G34Hc/edit?usp=sharing

**Comment by myleshorton** [comment]
Cool thanks! @chipstehr can you review those?
