### ISSUE TITLE
Speed up Lantern

### ISSUE THREAD

**Issue by Jedshady** [getlantern/lantern#1888]
When I try to browse youtube and other website in China through lantern, I get this error from chrome SSL Connection Error. Is there anyone who knows how to deal with it? Thank you advance.

**Comment by animesfunn** [comment]
sir give me example of flashlight server...in new york or sanfrancisco...because singapore server is block by globe telecom in the philippines...the only working server is netherland but it is to slow compared to singapore.....help me sir pls

**Comment by animesfunn** [comment]
i am using fl-nl-2015226-012.getiantem.org
fl-sg is block in my country please help me to other server

**Comment by Nyooork** [comment]
hey please help us to get back the "LANTERN" IN OUR COUNTRY . The Globe Telecom in the PHILIPPINES blocked the lantern .
