### ISSUE TITLE
Pure golang auto-update

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1900]
See #21 for original auto-update ticket covering the Java application.

Once we have ported Lantern to Go, we can simplify and improve the auto-update.  In particular:

1. Use something like [go-update](https://github.com/inconshreveable/go-update) to have the app download and install its own updates

2. Use [equinox.io](https://equinox.io/) to manage the rollout of our updates (if we can make it blocking resistant)

3. Use something like [go-again](https://github.com/rcrowley/goagain) for zero downtime restarts, which would allow Lantern to update itself even if someone is browsing with it or serving other users with it.

**Comment by myleshorton** [comment]
See #21
