### ISSUE TITLE
waddell - Increase size of waddell server if necessary

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1944]
Our one and only waddell instance is currently running on a Digital Ocean 512MB VM (wd-001-1).  I suspect that in the near future, it will easily be able to handle our signaling traffic, but we should keep an eye on it and upgrade the size of that instance when necessary.

In theory, waddell is actually meant to scale horizontally, but that requires us adding the ability to assign different peers to different waddell servers.  So, in the short term, it's easier/cheaper just to beef up that box.

**Comment by xiam** [comment]
Not relevant anymore.
