### ISSUE TITLE
[bug] Disabling anonymous usage reporting during sign-in sequence hangs

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1951]
During the sign in sequence, we present the user with a model containing a checkbox that allows disabling anonymous usage reporting.  If I click on that checkbox, nothing happens.

**Comment by myleshorton** [comment]
Is this fixed now on your branch @atavism?

**Comment by atavism** [comment]
@myleshorton Yes! Marking this as pending merge.
