### ISSUE TITLE
The newest avast anti-virus report found virus when newest lantern installing and when lantern everytime run.

### ISSUE THREAD

**Issue by ASmallShrimp** [getlantern/lantern#1963]
more details of this issue.
     My computer installed the avast free anti-virus of version 9.0(china).
    My computer alway installed the avast anti-virus, I install lantern first time at 2014-06-27,but after I sign in google account ,I can't access google.com and other banned sit everytime. 
    yesterday I download latest Lantern for windows from github.com . when I install Lantern, the Avast anti-virus report found virus from software Lantern, the installation success but can't access any banned sites. I closed Avast anti-virus manual,and install Lantern again. This time I can access the google and youtube sites when running Lantern,but when avast start running, anti-virus will alway report found virus from Lantern and anti-virus try delete the infection files. 

virus description: Win32:Malware-gen 
![avast_anti-virus_version](https://cloud.githubusercontent.com/assets/9686932/5004094/beb492a2-6a52-11e4-814d-3d2feaacad47.png)
![avast_report_lantern_has_virus](https://cloud.githubusercontent.com/assets/9686932/5004096/c1771eb0-6a52-11e4-83e2-d1a56787d054.png)

**Comment by kamiyeye** [comment]
I have the problem too with the latest version downloaded earlier today, "The executable upnpc.exe has been detected as malware by 9 anti-virus scanners." according to http://www.herdprotect.com/upnpc.exe-4d54204dad9b1f5d1abc1faf30532d64d32e01f4.aspx
