### ISSUE TITLE
Salt configuration for Azure flashlight servers

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#1970]
While Azure is supported by Salt, currently some of the steps necessary to get a working flashlight server on an Azure VM need to be performed manually in the Azure management website.  Automating these steps with a script that uses the Azure API will help if we ever want to deploy many of these quickly (e.g. if Cloudflare gets blocked).

**Comment by myleshorton** [comment]
This one's done @aranhoide right? Might be a dup?

**Comment by aranhoide** [comment]
This is actually not doable because of limitations in the Azure API.  Creating CDN endpoints remains a manual process, since their API provides no way to do it.  Perhaps what we can do is check periodically for whether this has been fixed on their end.
