### ISSUE TITLE
[flashlight] Implement UDT-based proxying

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1983]
See https://github.com/jbenet/go-udtwrapper for a potential UDT transport implementation.

This needs to include both the client and server sides.

**Comment by myleshorton** [comment]
This could be a good to work on @fffw, as it's super important for the full go port to work. It's possible we could reuse https://github.com/jbenet/go-udtwrapper, but at least it would be a good starting point.

**Comment by fffw** [comment]
@myleshorton yeah, happy to work on it, though I don't fully understand how to fit it into existing code yet.

>  Could be in a library that supports chained proxying and TCP/UDP

**Comment by oxtoacart** [comment]
> yeah, happy to work on it, though I don't fully understand how to fit it into existing code yet.

Essentially, we'll want to be able to plug in udt instead of tcp here:

https://github.com/getlantern/flashlight-build/blob/peerscanner/src/github.com/getlantern/flashlight/client/chained.go#L49

**Comment by fffw** [comment]
@oxtoacart Thanks.

**Comment by fffw** [comment]
I grabbed latest udt source code from sourceforge, modified Makefile to generate static library, and put the workable code here: https://github.com/fffw/go-udtwrapper.




Maybe we can eliminate the Makefile and just `go build`.

**Comment by myleshorton** [comment]
Awesome @fffw! So it's basically ready to integrate is that right?

**Comment by fffw** [comment]
> So it's basically ready to integrate is that right?

We may need to run a simple benchmark against tcp dialer, and to check if it works on Windows and Linux.

**Comment by fffw** [comment]
I wrote a simple benchmark tool at https://github.com/fffw/go-udtwrapper/blob/master/benchmark/benchmark.go

I ran the server on my DO instance located at SF, ran UDT and TCP client simultaneously on my MBA, the 1 min result is fascinating, UDT has 6X speed than TCP, and may gain 10X+ if run it longer. 

Test result is also included in same folder.

UDT runs ok on Mac and Linux, I'm working on Windows and Raspberry Pi.

Cross-compilation might be a problem for platform dependent code like this one, we may have toolchain but don't have all headers and libs.

**Comment by myleshorton** [comment]
This is great @fffw! Yeah I've been amazed how much faster UDT is for larger files over long distances, but it's amazing you saw that much improvement over just 1 min. The one thing that's a little unfortunate in our case is just that files for web sites tend to be so small. For those smaller files I don't think there's much of an improvement, but I could be wrong.
