### ISSUE TITLE
[kscope] Implement server-side kscope

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1986]
See [LEP-005](https://github.com/getlantern/lantern-roadmap/blob/master/lep/APPROVED/005_KScope_Server.md) as a starting point.  However, the server should be implemented outside of app-engine, using [this library](https://github.com/getlantern/kscope) as a starting point. Note - that library probably needs some work.

For the short term, friend management will remain in the Lantern Controller app engine app.  However, the storage of friend relationships should be outsourced to the new kscope server and Lantern Controller should send over updates via a privileged channel.

**Comment by myleshorton** [comment]
Not clear we'll be doing kscope again any time soon...
