### ISSUE TITLE
[bug] Port mapping warning isn't displaying when first running lantern

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2030]
Do this with a router that doesn't support port mapping (or at least doesn't support port mapping a low port).

1. Clear ~/.lantern
2. Run lantern
3. Choose Give mode
4. Finish sign in sequence

Expected Result:

UI shows port mapping warning at top of screen

Actual Result:

No port mapping warning is displayed

**Comment by myleshorton** [comment]
This was fixed with work on #2164
