### ISSUE TITLE
[eventsource] - Test won't compile

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2054]

**Comment by myleshorton** [comment]
Can you take a look at this too @fffw?

**Comment by fffw** [comment]
Maybe we can just use this [more mature library](https://github.com/antage/eventsource), I found its interface more simple among others, just `http.Handle("/events", es)` and `es.SendEventMessage("hello", "", "")` in any goroutine.

Take a look at [the example](https://github.com/antage/eventsource/blob/master/examples/greeter.go).

**Comment by oxtoacart** [comment]
Sorry about the slow reply.  That example that you send looks like a pub/sub kind of model with multiple clients all getting the same message.  That's not necessarily always what we want to do.
