### ISSUE TITLE
[flashlight] Occasionally see 302 errors in enproxy

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2071]
```
 Dec 08 13:46:04 162.243.199.118-1 logger: Lantern Client (456cef8486e7d8b02197cc7df9aa0714 / US / Mac OS X / 1.5.14-SNAPSHOT-a4e22f8 / 1.6.0_65-b14-466.1-11M4716) - ERROR [LoggingStreamHandler-error-true] pt.BasePluggableTransport.run (LoggingStreamHandler.java:111) - enproxy: Dest: www.google.com:80 ProxyHost: Unable to issue write request: Bad response status for read: 302 Moved Temporarily 
```

Interestingly, the Dest is always www.google.com:80.

**Comment by myleshorton** [comment]
Have you had any insights into this one in your testing @xiam? I suspect @oxtoacart's observation is correct and that #2663 will help mitigate this but curious if you came across this and other similar non-200 level errors with masquerades. See #2404 and #2403

**Comment by myleshorton** [comment]
Closing in favor of #2485
