### ISSUE TITLE
[lantern] Support SOCKS4 or SOCKS5

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2075]
We've gotten a few requests for this. It's from folks wanting to use Lantern for stuff other than web browsing.

**Comment by 4781121** [comment]
+100

**Comment by oxtoacart** [comment]
If you run a recent lantern, it's already got SOCKS5 support.  The SOCKS5 proxy listens at `localhost:8788`.

**Comment by 4781121** [comment]
@oxtoacart Thanks!
