### ISSUE TITLE
[feature] [lantern-pi] Lantern ARM-compatible installer

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2080]

**Comment by myleshorton** [comment]
Awesome!

On Sun, Dec 28, 2014 at 6:58 PM, atavism <notifications@github.com> wrote:

> I ran into some issues running install4j on the Pi itself, and I tried
> running it locally instead, and pointing it to a packaged ARM-compatible
> JRE, but I found the documentation on how to update the install4j config to
> support this lackluster. I instead ended up using an alternative that I
> found much easier to work with.. jdeb <https://github.com/tcurdt/jdeb>.
> It's a plugin that automatically generates a Debain archive when a Java
> build finishes, and I updated pom.xml (branch 2080) to include it. Anyway,
> the ARM-compatible installer built from the latest release is available
> here: https://s3.amazonaws.com/bifurcate/pi/lantern_1.5.16-arm.deb -- I
> obviously verified this works! If this method is fine, I'll submit a PR
> with the changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2080#issuecomment-68229075>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@atavism Neat that you were able to cut Install4J out of the loop!

FYI - the debs built by Install4J include a postinstall script sourced from linux/configureUbuntu.txt.  I think that script has bit-rotted some, but you may want to check if there's anything from there that you need for the arm installer.

**Comment by atavism** [comment]
@oxtoacart Thanks for pointing out the post install script. It looks like it just creates the Lantern desktop icon and runs some backward-compatibility checks so probably not applicable/necessary for the ARM installer.

**Comment by oxtoacart** [comment]
@atavism Great!

**Comment by aranhoide** [comment]
This seems related to lantern-java.  There's already a ticket for building Lantern 2 for ARM, so closing this one.
