### ISSUE TITLE
[lantern-ui] On shutdown, close tab that's running the UI

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2094]
When the user triggers a shut down, or the back-end suddenly goes away, call window.close() from the UI to close the corresponding tab.

**Comment by scouttle** [comment]
Just noticed that this ticket is closed – @atavism should it be moved to devel?

**Comment by atavism** [comment]
@scouttle Thanks! Actually, I'll re-open and mark this pending merge since it depends on https://github.com/getlantern/lantern-ui/pull/78 anyway.
