### ISSUE TITLE
[feature] See if we can auto-identify the blocking page in Iran and auto-proxy when we see it

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2099]

**Comment by atavism** [comment]
@myleshorton Looking for some additional P1 tickets to assign to myself. Mind if I take this one?

**Comment by myleshorton** [comment]
Hey sorry for the delay @atavism but that would be awesome! As I think you saw in that article the tricky part is that http://peyvandha.ir only appears after 30 seconds or so. One approach would be to just detect that and redirect that first time and then thereafter -- that might be plenty good enough as a first pass. Might even be cool to show the user that page and then Lantern automatically bypassing it. Hey @collina do you know how we might detect that initial blocking prior to the redirect to http://peyvandha.ir/? Can you verify that the redirect only happens after 30 seconds or so?

**Comment by oxtoacart** [comment]
The other thing that may be tricky is doing this for HTTPS connections, since I don't know how we could detect the redirect.

**Comment by collina** [comment]
@myleshorton It's generally either:
* a 302 Redirect with a small HTTP payload that includes an iframe referencing 10.10.34.34;
* a DNS response redirecting to 10.10.34.34; or,
* a prematurely terminated SSL connection.

**Comment by collina** [comment]
The filter response does not reference peyvandha and peyvandha does not maintain that private address space IP – peyandha.ir is publicly accessible, the intermediate page is not. More here: http://arxiv.org/abs/1209.6398

When you encounter the HTTP filter, you receive a response like:

    <html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1256"><title>M3-5
    </title></head><body><iframe src="http://10.10.34.34?type=Invalid Site&policy=MainPolicy " style="width: 100%; height: 100%" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe></body></html>

The URL parameters `type` and `policy` will vary, as will the `<title>`, but the end result will be an intermediate page of links:

 ![10.10.34.34](https://lh4.googleusercontent.com/IgsIzJBxLrS64XYG3dKiA7oVPfTXENaN-1C_RQ5f3BqAg_rgZIWmnPen7DNLgh552CUgTJfC5dsQp_bpBB_hHeqyNGbEsW6LP-bJDWh0gpsFWJCoo0DlQA1Cyfdl6VjVlA)

Which then triggers a timer that redirects to the public peyvandha.ir after a certain amount of time.

**Comment by myleshorton** [comment]
This is great @collina thanks! So in terms of coming up with a general rule for identifying this redirect, would it be safe to say that we could look for any redirect with an iframe whose src is a non-public IP?

Also, how are redirects to HTTPS sites handled? Do they redirect you to an HTTP version of the HTTP filter? We're basically wondering if we can detect that purely on the Lantern proxy side without an extension, which is trickier for HTTPS as @oxtoacart mentioned above.

**Comment by collina** [comment]
I think it would be safe to hardcode 10.10.34.34 for now. The filter cannot handle HTTPS for all the obvious reasons so it relies on the TLS SNI, DNS manipulation, or IP/port blocking. In the first case, it will look like an abnormally terminated SSL connection.

**Comment by myleshorton** [comment]
Awesome thanks @collina

**Comment by fffw** [comment]
Below is the result of my test:

*  `curl -v www.bbc.co.uk`
Responds a 403 Forbidden with the content @collina mentioned.

* `curl -v twitter.com` or `curl -v www.facebook.com`
Resolves to 10.10.34.34 and returns 200 OK with content of http://peyvandha.ir.

* `curl -v https://twitter.com` or `curl -v https://www.facebook.com`
Resolves to 10.10.34.34 and times out.

* adds `/etc/hosts` entry for www.facebook.com manually, then `curl -v www.facebook.com`
Responds a 403 Forbidden with the content @collina mentioned.

* adds `/etc/hosts` entry for www.facebook.com manually, then `curl -v https://www.facebook.com`
Gets [`NSS error -12263 SSL_ERROR_RX_RECORD_TOO_LONG`](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslerr.html#1040406), not 100% sure if it's an symptom of being blocked or not.

* adds `/etc/hosts` entry for twitter.com manually, then `curl -v twitter.com`
Responds a 403 Forbidden with the content @collina mentioned.

* adds `/etc/hosts` entry for twitter.com manually, then `curl -v https://twitter.com`
Times out.

Take what @collina found into account, we can suspect the site to be blocked if:

1. remote address is 10.10.34.34

2. response is 403 with an iframe to 10.10.34.34

3. it times out

3. EPIPE or ECONNRESET

It's just a superset of GFW's detection rule.

**Comment by myleshorton** [comment]
Very interesting @fffw! Thanks. How well is your GFW detection working now in testing?

**Comment by fffw** [comment]
@myleshorton I'm using it day in and day out. I also give it to several friends and the feedback is good.

The tricky part is how to handle timeouts. Currently, if a site times out in any time, it will be put in a temporary list so will be dialed through enproxy next time. If no error occured till closing in next connection, it will be added to permanent whitelist.

If a site is really slow or accessing from an unstable network, it will time out often, and has the chance to leak into whitelist. We can't invalidate whitelist often to avoid it. May need to emulate it in tests for some extreme cases.

**Comment by myleshorton** [comment]
Very cool @fffw! Maybe look at some differential in loading times for the timeout case? I.e. if it times out, then time the dial through enproxy. If that succeeds but takes a long time, then we know it's close to timing out in general. If enproxy works right away, we know it's blocked.

**Comment by fffw** [comment]
Added detection for Iran at https://github.com/getlantern/flashlight-build/pull/114

I compiled a binary on CentOS VPS to test.

If someone have interest to try, you can
```sh
TRACE=detour /tmp/lantern_linux
```

then open another session
```sh
http_proxy=127.0.0.1:8787 https_proxy=127.0.0.1:8787 curl -v http://www.bbc.co.uk
```

**Comment by fffw** [comment]
Through simple benchmark, latency penalty for direct connections is < 10ms.

```
~ () $ boom -allow-insecure -n 1000 -c 10 -q 10 -x http://localhost:8789 -disable-keepalive -t 20000 http://www.baidu.com/robots.txt
1000 / 1000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:	100.1531 secs.
  Slowest:	1.3116 secs.
  Fastest:	0.1441 secs.
  Average:	0.1814 secs.
  Requests/sec:	9.9847

Status code distribution:
  [200]	1000 responses

Response time histogram:
  0.144 [1]	|
  0.261 [983]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.378 [7]	|
  0.494 [7]	|
  0.611 [0]	|
  0.728 [0]	|
  0.845 [0]	|
  0.961 [0]	|
  1.078 [0]	|
  1.195 [0]	|
  1.312 [2]	|

Latency distribution:
  10% in 0.1529 secs.
  25% in 0.1604 secs.
  50% in 0.1682 secs.
  75% in 0.1882 secs.
  90% in 0.2241 secs.
  95% in 0.2361 secs.
  99% in 0.2832 secs.
```

```
 ~ () $ boom -allow-insecure -n 1000 -c 10 -q 10 -x http://localhost:8789 -disable-keepalive -t 20000 http://www.baidu.com/robots.txt
boom -allow-insecure -n 1000 -c 10 -q 10 -disable-keepalive -t 20000 http://www.baidu.com/robots.txt
1000 / 1000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:	100.1632 secs.
  Slowest:	1.2838 secs.
  Fastest:	0.1385 secs.
  Average:	0.1754 secs.
  Requests/sec:	9.9837

Status code distribution:
  [200]	1000 responses

Response time histogram:
  0.139 [1]	|
  0.253 [979]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.368 [14]	|
  0.482 [4]	|
  0.597 [0]	|
  0.711 [0]	|
  0.826 [0]	|
  0.940 [0]	|
  1.055 [0]	|
  1.169 [0]	|
  1.284 [2]	|

Latency distribution:
  10% in 0.1475 secs.
  25% in 0.1553 secs.
  50% in 0.1619 secs.
  75% in 0.1815 secs.
  90% in 0.2190 secs.
  95% in 0.2300 secs.
  99% in 0.2692 secs.
```

**Comment by oxtoacart** [comment]
Nice!  I think that's totally fine.

**Comment by myleshorton** [comment]
Fixed in https://github.com/getlantern/flashlight-build/pull/114
