### ISSUE TITLE
[bug] Lantern not always starting on Windows 8

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2104]
See bug report from user on Facebook. Lantern doesn't start after install, and clicking the desktop link does nothing.

**Comment by atavism** [comment]
@myleshorton Testing this along with the UI changes on Windows 8.1. I can confirm after installation, double-clicking the desktop icon does nothing. Also, running Lantern from the command line I'm seeing this:

```
Copying from install/win/pt to src/main/pt/
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: c:\apache-maven-3.2.5
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: c:\Program Files (x86)\Java\jdk1.8.0_31\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "x86", family: "dos"
[INFO] Scanning for projects...
Downloading: https://s3.amazonaws.com/lantern-mvn-repo/release/org/getlantern/lantern-common/0.0.20/lantern-common-0.0.20.pom
Downloading: https://repo.maven.apache.org/maven2/org/getlantern/lantern-common/0.0.20/lantern-common-0.0.20.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.lantern:lantern:1.5.18-SNAPSHOT (c:\Users\atavism\Desktop\lantern\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.getlantern:lantern-common:pom:0.0.20 from/to aws-release (https://s3.amazonaws.com/lantern-mvn-repo/release): Access denied to: https://s3.amazonaws.com/lantern-mvn-repo/release/org/getlantern/lantern-common/0.0.20/lantern-common-0.0.20.pom , ReasonPhrase:Forbidden. and 'parent.relativePath' points at wrong local POM @ line 854, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Could not package
```

**Comment by atavism** [comment]
It appears the issue is when you close the UI window, and Lantern is relegated to a background process, double clicking the desktop link has no effect or ability to re-open the UI. If I terminate the Lantern process, the window opens fine once again.

**Comment by myleshorton** [comment]
Thanks for testing @atavism! This bug is actually for Lantern not starting at all after initial install (Lantern should run automatically after the installer runs), as posted by a user in a FB message. There's a separate bug for what you're talking about at #1691.

Did Lantern start automatically after the installer ran, or did you have to try the desktop link? There could also be a bug in the logic for checking whether or not to show the UI -- like it's not supposed to show on restart if Lantern's already set up, but there could be a bug in there somewhere where it thinks it's running on startup when it's not or something along those lines.

**Comment by atavism** [comment]
> Did Lantern start automatically after the installer ran, or did you have to try the desktop link?

It automatically started after the installer finished running. I just tried uninstalling and re-installing to confirm.
