### ISSUE TITLE
[bug] [flashlight] Get test to succeed consistently

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2108]
It fairly frequently times out, exhibiting the below error:

```
flashlight.client: About to start client (http) proxy at 127.0.0.1:19872
balancer: Dialing tcp://127.0.0.1:19874 with fronted proxy at 127.0.0.1:19871 using masquerade set cloudflare
2014/12/21 17:59:58 http: proxy error: dial tcp 127.0.0.1:19873: connection refused
domainfronted: About to start server (https) proxy at 127.0.0.1:19873
enproxy: Dest: www.google.com:80    ProxyHost:     Unable to issue write request: Bad response status for read: 500 Internal Server Error
domainfronted: Timed out verifying 127.0.0.1
SIGQUIT: quit
PC=0x42ea81
```

**Comment by myleshorton** [comment]
@fffw can you take a look at this too?

**Comment by fffw** [comment]
Oh the error disappears at commit [#cca8ca3](https://github.com/getlantern/flashlight-build/commit/cca8ca352b494fa03c2c11d75544c1e69f3e9d84), while introducing tcpproxying.

[Previous commit](https://github.com/getlantern/flashlight-build/commit/8c866d639fd4815f639c195c9d68d0949203752f) fails frequently on time out.

Safe to close?

**Comment by myleshorton** [comment]
Sounds great. Closing.
