### ISSUE TITLE
Save auto-start setting across runs

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2112]

**Comment by fffw** [comment]
A user complaints at [user forum](https://groups.google.com/forum/#!msg/lantern-users-en/nvCgzpGUFLc/TOCMu3zBiEAJ).

Because `~/Library/LaunchAgents/org.lantern.plist` has mod 644, we can't change it from Lantern process running as current user.

**Comment by fffw** [comment]
As per man page of `launchctl`

>  Note that per-user configuration files (LaunchAgents) must be owned by root (if they are located in
              /Library/LaunchAgents) or the user loading them (if they are located in $HOME/Library/LaunchAgents).

But we set it to 644 [during installation](https://github.com/getlantern/lantern/blob/devel/install/osx/configureOsx.bash#L94), is it on purpose?

**Comment by fffw** [comment]
Oh sorry I messed it up. What we need to do is 

> chown $USER $LAUNCHD_PLIST

in [configureOsx.bash](https://github.com/getlantern/lantern/blob/devel/install/osx/configureOsx.bash#L94), right?

**Comment by myleshorton** [comment]
That sounds great @fffw can you make that change?

**Comment by oxtoacart** [comment]
@fffw I just noticed that this is working for me now, and it was awesome!  Thank you.
