### ISSUE TITLE
[bug] Flashlight CPU and disk usage growing over time

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2117]
This was observed on all flashlight servers, and restarting solved it. Marking as p3 since restarting seems to solve the issue. Perhaps upgrading to a newer Go version would help?

**Comment by myleshorton** [comment]
Very related to #2121

**Comment by oxtoacart** [comment]
After restarting the whole 004 series, usage on this server went down.  I think perhaps we're seeing CloudFlare shifting around traffic to those machines that seem the most responsive.

To make sure we're not being penalized for old non-responsive machines, I'm deploying a recent build to all flashlight servers (it's been running fine on the 004 series).  This build includes logic that still alerts when 15 min load average hits 70% and now also restarts flashlight when load average hits 90%, just in case there is a leak of some sort.

**Comment by oxtoacart** [comment]
Note - once this deployment is finished, all flashlight servers will have memory profiling enabled.  If you ever need to investigate one, you can look in /home/lantern for files named mem_YYYYMMDD_HHMMSS.NANO.prof.  The timestamp corresponds to when flashlight process started, not when it finished, but the file is only written out when flashlight is stopped (i.e. using `sudo service flashlight stop`).

**Comment by oxtoacart** [comment]
Okay, I've updated all of the flashlight servers.  I'm browsing using flashlight to fallback.getiantem.org right now and will continue doing so throughout the day to see how the experience holds up.

**Comment by oxtoacart** [comment]
Oddly, even after bouncing all of the servers, load is not evenly distributed.  For example 003-19 is handling about 6mbps right now, while 001-30 is handling 50mbps.  It's not clear to me what's causing this sort of difference, but we need to either sort this out or figure out a way to get CloudFlare to not redirect new traffic to servers that are already heavily loaded.

**Comment by oxtoacart** [comment]
Another option is to use fewer larger servers.

**Comment by myleshorton** [comment]
Thanks for all of this Ox! To me that graph is a huge improvement, as it shows a direct correlation between bandwidth and CPU at high CPU, which is different from what we've seen before.

In fact, I think that might even be enough to close this ticket proper, with the only remaining issue really being that some servers get more load than others. The only thing I know that would cause that on our end is the sticky routing for SSL sessions that inherently need to send traffic to the same machines. Could that be enough to cause what we're seeing? I'm not sure.

To me it seems possible and even likely we might not be able to fully solve the uneven load distribution issue. However, we could also "solve" it through dynamically sizing instances based on load. I'm not sure how or if we can do this directly from Salt, but the API certainly supports it:

https://developers.digitalocean.com/v2/#resize-a-droplet

I believe it requires a power cycle, but we've been doing that all the time anyway. Ideally to me we'd both size droplets up as well as down when load drops.

What do you think @oxtoacart?

**Comment by oxtoacart** [comment]
> Thanks for all of this Ox! To me that graph is a huge improvement, as it shows a direct correlation between bandwidth and CPU at high CPU, which is different from what we've seen before.

Thanks, yes I do think we've improved things quite a bit.

> In fact, I think that might even be enough to close this ticket proper, with the only remaining issue really being that some servers get more load than others.

Logged #2146 for this.

> The only thing I know that would cause that on our end is the sticky routing for SSL sessions that inherently need to send traffic to the same machines. Could that be enough to cause what we're seeing? I'm not sure.

The weird thing is that we've seen high load persist even across server restarts, which would have severed those long-lived connections, so I don't think our sticky routing is the issue.

> To me it seems possible and even likely we might not be able to fully solve the uneven load distribution issue.

Agreed.  I do think it's worth some investigation to understand more about what's happening here.  For example server 001-30 has been consistently overloaded for days now, despite going through several flashlight process restarts, system reboots and even power cycles.  That seems really fishy.

> However, we could also "solve" it through dynamically sizing instances based on load. I'm not sure how or if we can do this directly from Salt, but the API certainly supports it:

> https://developers.digitalocean.com/v2/#resize-a-droplet

> I believe it requires a power cycle, but we've been doing that all the time anyway. Ideally to me we'd both size droplets up as well as down when load drops.

Interesting idea!  If each droplet had access to do that for itself, it could just scale up and down as necessary.

Another tack to take here is per-connection or per-client rate limiting.  Assuming that the overload is because of a few highly active connections/clients, rate limiting could help.

**Comment by oxtoacart** [comment]
The other thing to consider here is that if and when DO starts charging for bandwidth, that will be the limiting factor long before CPU.  We see current 1 core machines easily pushing 10-20mbps without breaking a sweat.  That comes out to 6.5 TB per month, which is 6.5 times what we get included in the droplet price.  We don't want to get into bandwidth usage charges as those are quite high.

What this means is we really do need to figure out a way to keep individual machines from becoming chronically overloaded, as that has negative consequences on cost.

One somewhat severe options is to retire machines that have become overloaded and replace them with a new, differently named, machine.  This would require deregistering it from CloudFlare DNS, for which we don't currently have a provision.  If we switched to using peerdnsreg to register, that would theoretically take care of it.

**Comment by myleshorton** [comment]
Good point @oxtoacart. DO claims that they'll give people a solid lead time before starting to charge for bandwidth, so we could just wait to see if and when that happens and make the appropriate adjustments then.

I regardless like the option of retiring and de-registering machines, and I think having those machines use peerdnsreg does make sense.

**Comment by oxtoacart** [comment]
So here's something interesting.  I went to CloudFlare to manually remove 001-29 from the fallbacks rotation and, guess what, it's not in there!  It is however in the round-robin rotation, and in the test_fallbacks rotation.  I'm going to remove it from those and see what happens.

**Comment by oxtoacart** [comment]
So, even after taking it out of all the rotations and power cycling the machine, it immediately jumps up to high load and has a bunch of connections from CloudFlare?!

**Comment by oxtoacart** [comment]
I've now taken the fl-singapore-001-29 entry out of CloudFlare, and I'm still getting traffic from there ?!  Maybe it just takes a really long time for those changes to propagate through CloudFlare's infrastructure?

**Comment by myleshorton** [comment]
Very odd on those CloudFlare connections. Will be interesting to see if
they're still there tomorrow.

On Wednesday, January 7, 2015, LeoK <notifications@github.com> wrote:

> Just a note on the user side, I run version 1.5.9 for a couple days and
> have not noticed high CPU usage yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2117#issuecomment-69126300>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Thanks @LeoK. We identified issues with Flashlight that affect both the
client and the server sides, and we should have a fix out soon.

On Wednesday, January 7, 2015, LeoK <notifications@github.com> wrote:

> Just a note on the user side, I run version 1.5.9 for a couple days and
> have not noticed high CPU usage yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2117#issuecomment-69126300>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton Unfortunately I got trigger happy and deleted those DO machines yesterday.  However, 001-20 is now getting slammed, so I've removed it from CloudFlare DNS settings and will leave the machine around for a few days to see what happens.

**Comment by aranhoide** [comment]
A DO flashlight server can unregister itself from Cloudflare.  We'd just need to call the register_domains.py script with the `unregister` command:

https://github.com/getlantern/lantern_aws/blob/master/salt/flashlight/register_domains.py#L69

Resizing a DO droplet can be done programmatically, but since it involves powering the machine off and on, it can't be done from the machine itself.  It wouldn't be hard to have the flashlight servers request that (e.g.) the cloudmaster resize them, though.

https://github.com/getlantern/lantern_aws/blob/master/bin/do_fps.py#L168

(The functions referenced above are never called automatically as of this writing, but I've used them every now and them by invoking them manually.)

**Comment by oxtoacart** [comment]
> A DO flashlight server can unregister itself from Cloudflare. We'd just need to call the register_domains.py script with the unregister command:

https://github.com/getlantern/lantern_aws/blob/master/salt/flashlight/register_domains.py#L69

Excellent!

> Resizing a DO droplet can be done programmatically, but since it involves powering the machine off and on, it can't be done from the machine itself. It wouldn't be hard to have the flashlight servers request that (e.g.) the cloudmaster resize them, though.

As discussed, I'm leaning heavily towards just destroying the droplet and launching a new one, just in case there's something overly "sticky" going on.

**Comment by oxtoacart** [comment]
> As discussed, I'm leaning heavily towards just destroying the droplet and launching a new one, just in case there's something overly "sticky" going on.

I should mention that "launching a new one" doesn't need to be coupled with "destroying the droplet".  In particular, launching new droplets is already based on overall capacity considerations, so we could simply destroy the old droplet and rely on our usual capacity management mechanism (currently manual) to launch whatever new droplets are necessary.

**Comment by aranhoide** [comment]
OTOH, destroying droplets automatically and only launching them manually makes me a bit uneasy.  In principle I'd rather have our automatons try and be neutral wrt scale (i.e., request a new instance to be launched when one is shut down), at least until we implement actual auto scaling functionality.

**Comment by myleshorton** [comment]
Sounds about right to me!

On Fri, Jan 9, 2015 at 10:54 AM, oxtoacart <notifications@github.com> wrote:

> As discussed, I'm leaning heavily towards just destroying the droplet and
> launching a new one, just in case there's something overly "sticky" going
> on.
>
> I should mention that "launching a new one" doesn't need to be coupled
> with "destroying the droplet". In particular, launching new droplets is
> already based on overall capacity considerations, so we could simply
> destroy the old droplet and rely on our usual capacity management mechanism
> (currently manual) to launch whatever new droplets are necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2117#issuecomment-69380265>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
That is to say, yes it would be tricky if we started getting cascading server shutdowns, so launching a new one would seem to make sense. In fact it's tempting to either start two new ones or to scale up the existing one to accommodate the CPU spike. I kind of like the starting two new ones approach, as it gives us super rudimentary auto-scaling.

**Comment by oxtoacart** [comment]
@aranhoide @myleshorton Yes, I see your point.  Makes sense to me!

**Comment by oxtoacart** [comment]
It occurs to me that managing the auto-scaling from peerdnsreg might make sense since it has a good understanding of the overall number of online fallbacks and peers.

**Comment by aranhoide** [comment]
Auto-scaling up when we have a not-totally-understood massive resource demand is a bit scary too :).  I'd sleep better if we at least put some kind of cap on it, past which we require human intervention to greenlight further scaling up.

**Comment by myleshorton** [comment]
> It occurs to me that managing the auto-scaling from peerdnsreg might make sense since it has a good understanding of the overall number of online fallbacks and peers.

Agreed @oxtoacart. If we can consolidate things there, that would be handy. I do think following the same rules for servers that we follow for peers exactly is a bit dangerous along the lines of @aranhoide's concern, i.e. if we kill everything that doesn't respond within x seconds for both peers and servers, we might end up with no servers if load really spiked! But generally though I really like the notion of adding and killing servers from peerdnsreg.

**Comment by oxtoacart** [comment]
Yes, this definitely requires some thought to make sure we get it right, and it sounds like we're on the right track.

**Comment by oxtoacart** [comment]
Something is still not quite right.  Here's a recent graph from fl-singapore-001-21:

![screen shot 2015-01-15 at 12 04 01 pm](https://cloud.githubusercontent.com/assets/5000654/5763274/b553df4a-9cae-11e4-93c8-8a740ea21d16.png)

**Comment by myleshorton** [comment]
I was glancing at that too. Early this morning we had a period where bandwidth spiked on some servers while other servers' bandwidth dropped to almost nothing at exactly the same time. It almost sounds like a Digital Ocean glitch to me, but I'll post some relevant bandwidth graphs.

**Comment by myleshorton** [comment]
We also definitely have some servers that just seem to not be in DNS -- something went wrong with the provisioning. See https://cloud.digitalocean.com/droplets/3673981 for example.

**Comment by oxtoacart** [comment]
> It almost sounds like a Digital Ocean glitch to me, but I'll post some relevant bandwidth graphs.

Yeah, I'm wondering about that too.  Either a digital ocean glitch, or perhaps (and more likely) peerdnsreg has an occasional hiccup where it takes a bunch of fallbacks out of rotation for some reason.

**Comment by oxtoacart** [comment]
Looks like 005-37 came out of rotation in early January for some reason and never got back in.  I think it's time for me to take a closer look at the registration enhancements we've been discussing :)

**Comment by myleshorton** [comment]
> Yeah, I'm wondering about that too. Either a digital ocean glitch, or perhaps (and more likely) peerdnsreg has an occasional hiccup where it takes a bunch of fallbacks out of rotation for some reason.

Well peerdnsreg doesn't take servers out of rotation, only peers. I actually think that's right for exactly this reason unless it's much more sophisticated about deciding when to take servers out.

**Comment by myleshorton** [comment]
Actually it looks like we're in another period right now where all of a sudden the load on most servers has dropped to almost nothing mysteriously. See, for example (one of many):

https://cloud.digitalocean.com/droplets/3674591

**Comment by oxtoacart** [comment]
I just ran highstate on the servers to see if that would help re-register them.  That's why load recently dropped.

**Comment by myleshorton** [comment]
![image](https://cloud.githubusercontent.com/assets/1143966/5763696/88da634c-9ca1-11e4-8119-619584047da0.png)

**Comment by myleshorton** [comment]
It looks like it dropped ~30 minutes ago though. Did you run high state that long ago @oxtoacart?

**Comment by oxtoacart** [comment]
Here's a record of fallbacks per peerscanner from the last several hours:

```
Jan 15 02:24:32 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:24:32 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:25:40 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:25:39 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:26:48 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:26:48 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:28:47 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:28:47 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:30:21 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:30:21 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:34:05 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:34:05 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:36:17 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:36:16 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:47:56 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:47:56 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 02:53:20 cloudflare-peerdnsreg app/clock.1:  2015/01/15 10:53:20 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 03:04:35 cloudflare-peerdnsreg app/clock.1:  2015/01/15 11:04:35 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 03:09:46 cloudflare-peerdnsreg app/clock.1:  2015/01/15 11:09:45 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 03:10:47 cloudflare-peerdnsreg app/clock.1:  2015/01/15 11:10:47 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 03:26:00 cloudflare-peerdnsreg app/clock.1:  2015/01/15 11:26:00 NUMBER OF FALLBACKS (verified / total): 1 / 160 
Jan 15 04:05:15 cloudflare-peerdnsreg app/clock.1:  2015/01/15 12:05:14 NUMBER OF FALLBACKS (verified / total): 10 / 160 
Jan 15 04:29:21 cloudflare-peerdnsreg app/clock.1:  2015/01/15 12:29:20 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 05:15:43 cloudflare-peerdnsreg app/clock.1:  2015/01/15 13:15:43 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 05:37:32 cloudflare-peerdnsreg app/clock.1:  2015/01/15 13:37:32 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 06:03:34 cloudflare-peerdnsreg app/clock.1:  2015/01/15 14:03:34 NUMBER OF FALLBACKS (verified / total): 15 / 160 
Jan 15 06:47:25 cloudflare-peerdnsreg app/clock.1:  2015/01/15 14:47:24 NUMBER OF FALLBACKS (verified / total): 139 / 160 
Jan 15 07:52:42 cloudflare-peerdnsreg app/clock.1:  2015/01/15 15:52:41 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 07:53:44 cloudflare-peerdnsreg app/clock.1:  2015/01/15 15:53:43 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 08:06:10 cloudflare-peerdnsreg app/clock.1:  2015/01/15 16:06:10 NUMBER OF FALLBACKS (verified / total): 107 / 160 
Jan 15 08:59:10 cloudflare-peerdnsreg app/clock.1:  2015/01/15 16:59:10 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 09:00:16 cloudflare-peerdnsreg app/clock.1:  2015/01/15 17:00:16 NUMBER OF FALLBACKS (verified / total): 141 / 160 
Jan 15 09:27:25 cloudflare-peerdnsreg app/clock.1:  2015/01/15 17:27:25 NUMBER OF FALLBACKS (verified / total): 142 / 160 
Jan 15 09:50:14 cloudflare-peerdnsreg app/clock.1:  2015/01/15 17:50:13 NUMBER OF FALLBACKS (verified / total): 6 / 160 
```

**Comment by myleshorton** [comment]
Wow -- crazy it drops to almost non being verified all of a sudden.

**Comment by myleshorton** [comment]
It also looks like we have ~175 actual fl servers in DO, so looks like some still just aren't making it to CloudFlare.

**Comment by myleshorton** [comment]
Yup so this recent drop looks like another example of a subset of the servers all of a sudden taking the bulk of the load while other servers stop serving almost anything at all. Here's a graph of one of the servers that picked up load during the stretch we're currently in:

![image](https://cloud.githubusercontent.com/assets/1143966/5764038/e2b511b2-9ca3-11e4-9514-32942da7dc93.png)

**Comment by myleshorton** [comment]
Interesting. So the clock peerndsreg process is having trouble. We need to remember to check that too during support day (I often forget to click over):

![image](https://cloud.githubusercontent.com/assets/1143966/5764085/40b929c4-9ca4-11e4-84f7-151967656845.png)

**Comment by myleshorton** [comment]
I just bumped up our dyno size, which seems to have fixed things for now. It's pricey, though, so we should figure out what's happening. Logged at:

https://github.com/getlantern/lantern/issues/2174

```
Jan 15 10:52:25 cloudflare-peerdnsreg app/clock.1:  2015/01/15 18:52:25 NUMBER OF FALLBACKS (verified / total): 151 / 169 
Jan 15 10:53:27 cloudflare-peerdnsreg app/clock.1:  2015/01/15 18:53:26 NUMBER OF FALLBACKS (verified / total): 152 / 169 
Jan 15 10:54:29 cloudflare-peerdnsreg app/clock.1:  2015/01/15 18:54:28 NUMBER OF FALLBACKS (verified / total): 152 / 169 
Jan 15 10:55:30 cloudflare-peerdnsreg app/clock.1:  2015/01/15 18:55:30 NUMBER OF FALLBACKS (verified / total): 152 / 170 
Jan 15 10:56:33 cloudflare-peerdnsreg app/clock.1:  2015/01/15 18:56:32 NUMBER OF FALLBACKS (verified / total): 152 / 170 
```

**Comment by oxtoacart** [comment]
Cool.  I'm making this my no. 1 priority.

**Comment by myleshorton** [comment]
As I mentioned on the call @oxtoacart, it looks like that peerdnsreg changed righted the ship on DO. The mysterious part to me is why? Unless there's a bug, peerdnsreg shouldn't be taking things out of rotation, although now I'm wondering about the TTL on the DNS registration itself -- have to look at that.

**Comment by oxtoacart** [comment]
@myleshorton I'm working on peerdnsreg as we speak.

BTW, I actually do believe that peerdnsreg should take unresponsive fallbacks out of rotation, since these are likely to be unresponsive to clients as well. I do think it needs a failsafe though in case there's an issue on the peerdnsreg side, which presumably would manifest as everything failing.

**Comment by myleshorton** [comment]
> I actually do believe that peerdnsreg should take unresponsive fallbacks out of rotation

I agree overall, but it just has to take the overall load across all machines into account somehow, which is difficult. If all machines are at 100% CPU, for example, killing any of them will only exacerbate the problem while killing all of them would be disastrous.

**Comment by myleshorton** [comment]
@oxtoacart also if you find any memory leak issues in there (possibly not closing connections?), that would be huge.

**Comment by oxtoacart** [comment]
> I agree overall, but it just has to take the overall load across all machines into account somehow, which is difficult. If all machines are at 100% CPU, for example, killing any of them will only exacerbate the problem while killing all of them would be disastrous.

Valid points. That said, today and on some past occasions I've observed that the network becomes basically unusable once it's overloaded, so even though all of the servers may be in rotation and still doing some meaningful work, the user experience is such that they might as well not be.   Also keep in mind that servers can come back into rotation once they become responsive again.  And, having been taken out of rotation, the server has a chance to recover.

So, I would say that we need to keep the pool of servers sized so that it can accommodate capacity.  If it's undersized, we're in trouble one way or the other.  When properly sized overall, we should see an equilibrium where individual servers will come in and out of rotation as they become overloaded, but overall most servers will be in rotation most of the time.

**Comment by myleshorton** [comment]
Yeah, so it just has to be pretty sophisticated, which seems like a significant amount of work. In terms of the issue immediately at hand, it seems like we're overall in decent shape outside of the memory problem.

**Comment by LeoK987** [comment]
Just noticing flashlight using high CPU intermittently when I was using
Google Maps.  It got 200% CPU (reported by top on Ubuntu 14.04 64bits) for
a few seconds and then off for a couple seconds and repeat that way.  It
goes on even when I dismissed Google Maps.  This is my first time noticing
it with Lantern 1.5.9.

**Comment by LeoK987** [comment]
Restarted both Lantern and Chrome.  Now flashlight seems to stick with 100%
CPU continuously.

**Comment by LeoK987** [comment]
Restarted both again and it looks normal now.

**Comment by myleshorton** [comment]
Thanks for the report @LeoK987! We fixed at least one CPU issue with the latest Lantern. Can you try taking 1.5.17 for a spin? It's at:

https://s3.amazonaws.com/lantern/lantern-installer.exe
https://s3.amazonaws.com/lantern/lantern-installer.dmg

**Comment by myleshorton** [comment]
It's also linked from the site..

**Comment by myleshorton** [comment]
We can actually close this right @oxtoacart?

**Comment by oxtoacart** [comment]
I was hoping to hear back from @LeoK987 to see if that build resolved the issue.

**Comment by LeoK987** [comment]
I have not noticed high CPU usage with version 1.5.17 in the past few
days.  Seems OK

**Comment by oxtoacart** [comment]
Thanks @LeoK987!
