### ISSUE TITLE
Flashlight CPU spiking to 100%

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2121]

**Comment by oxtoacart** [comment]
I've tried to reproduce this on a 64-bit Ubuntu VM in VMWare on an OS X host, using flashlight only, but with no luck so far.

**Comment by myleshorton** [comment]
It looks like we're seeing this on the production servers as well. See the following:

![image](https://cloud.githubusercontent.com/assets/1143966/5609116/87b0c52c-944c-11e4-90ed-52bf6cd22828.png)

**Comment by LeoK987** [comment]
This morning lantern has difficulty getting me access.  I had to kill it multiple times.  During this time flashlight got 100% CPU many times.  I now revert to version 1.5.9 and see what happens.

**Comment by myleshorton** [comment]
Thanks - we're seeing this on our end as well and are working on it.

On Sunday, January 4, 2015, LeoK <notifications@github.com> wrote:

> This morning lantern has difficulty getting me access. I had to kill it
> multiple times. During this time flashlight got 100% CPU many times. I now
> revert to version 1.5.9 and see what happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2121#issuecomment-68667718>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by LeoK987** [comment]
Thanks very much.  I can get this message via gmail so it means it still
works albeit very slowly.

**Comment by myleshorton** [comment]
OK, I've rebooted all the servers a couple of times now, and some still get pegged at 100% CPU when they come back up. My guess is there's something on the client side that's causing and a lack of appropriate checks on the server side to thwart what's effectively an attack, and the servers whose CPU spikes to 100% are getting hit by corresponding clients whose CPU is also spiking to 100%. We'll continue to work to fix the issue.

**Comment by oxtoacart** [comment]
The server-side manifestation of this problem only popped up after I deployed a new build of flashlight to the servers earlier today, so I don't think the server-side CPU spike is related to a client's CPU spiking.  Rather, there must be some shared code used by both clients and servers that causing this spike.

**Comment by oxtoacart** [comment]
I did some profiling on fl-singapore-004-1 using more recent code that exhibits the CPU spike behavior.  When running normally without spiking, the Top20 in pprof look like this:

```
Showing top 20 nodes out of 193 (cum >= 280ms)
      flat  flat%   sum%        cum   cum%
    2040ms  9.07%  9.07%     2040ms  9.07%  runtime.futex
    1990ms  8.85% 17.92%     2060ms  9.16%  syscall.Syscall
    1200ms  5.34% 23.25%     1220ms  5.42%  crypto/elliptic.p256ReduceDegree
     940ms  4.18% 27.43%     3320ms 14.76%  math/big.nat.divLarge
     840ms  3.73% 31.17%      840ms  3.73%  math/big.divWW
     750ms  3.33% 34.50%      750ms  3.33%  math/big.addMulVVW
     710ms  3.16% 37.66%      710ms  3.16%  runtime.usleep
     700ms  3.11% 40.77%      700ms  3.11%  runtime.cgocall_errno
     680ms  3.02% 43.80%      730ms  3.25%  runtime.mallocgc
     650ms  2.89% 46.69%      650ms  2.89%  crypto/sha1.block
     540ms  2.40% 49.09%      540ms  2.40%  math/big.mulAddVWW
     470ms  2.09% 51.18%      470ms  2.09%  scanblock
     420ms  1.87% 53.05%      420ms  1.87%  runtime.epollwait
     410ms  1.82% 54.87%      410ms  1.82%  ExternalCode
     360ms  1.60% 56.47%      360ms  1.60%  runtime.MSpan_Sweep
     340ms  1.51% 57.98%      340ms  1.51%  crypto/aes.encryptBlockAsm
     330ms  1.47% 59.45%      330ms  1.47%  math/big.subVV
     230ms  1.02% 60.47%     1010ms  4.49%  math/big.basicMul
     230ms  1.02% 61.49%      230ms  1.02%  runtime.siftdownTimer
     220ms  0.98% 62.47%      280ms  1.24%  runtime.deferreturn
```

When encountering a spike, the Top 20 look like this:

```
Showing top 20 nodes out of 80 (cum >= 5.55s)
      flat  flat%   sum%        cum   cum%
   129.41s 30.71% 30.71%    129.41s 30.71%  ExternalCode
    24.74s  5.87% 36.58%     24.74s  5.87%  runtime.xchg
    15.38s  3.65% 40.23%     15.38s  3.65%  runtime.newdefer
    14.43s  3.42% 43.66%     14.43s  3.42%  runtime.writebarrierptr
    14.32s  3.40% 47.05%     17.84s  4.23%  runtime.getitab
    12.92s  3.07% 50.12%     38.74s  9.19%  runtime.deferreturn
     9.46s  2.25% 52.37%    228.28s 54.17%  github.com/getlantern/idletiming.(*IdleTimingConn).Write
     8.69s  2.06% 54.43%      8.69s  2.06%  runtime.releasem
     8.36s  1.98% 56.41%    241.18s 57.24%  bufio.(*Writer).Write
     8.06s  1.91% 58.33%      8.06s  1.91%  sync/atomic.CompareAndSwapUint64
     7.87s  1.87% 60.19%     15.23s  3.61%  runtime.freedefer
     7.87s  1.87% 62.06%      7.87s  1.87%  sync/atomic.CompareAndSwapUint32
     7.43s  1.76% 63.82%     60.56s 14.37%  runtime.netpollSetDeadline
     7.14s  1.69% 65.52%      7.14s  1.69%  time.Time.Add
     7.03s  1.67% 67.19%     26.19s  6.22%  runtime.assertI2I2
     6.76s  1.60% 68.79%      6.76s  1.60%  sync/atomic.AddUint32
     6.59s  1.56% 70.35%     15.55s  3.69%  runtime.deferproc
     5.95s  1.41% 71.77%      5.95s  1.41%  runtime.deferproc_m
     5.78s  1.37% 73.14%     88.22s 20.94%  crypto/tls.(*Conn).Write
     5.55s  1.32% 74.46%      5.55s  1.32%  runtime.acquirem
```

**Comment by oxtoacart** [comment]
In the good output (no spike), we see that work is spread out over a bunch of functions, but that the bulk of the CPU time is spent doing crypto, which is not surprising.

In the bad output, we're seeing work being dominated by calls to ExternalCode, and in particular seeing a lot of time spent inside of IdleTimingConn.Write.  Amongst other things, this function sets write timeouts on an connection, which is a syscall to ExternalCode.  If the loop inside of there is encountering a condition that causes it to churn, that could explain the sudden spike.

**Comment by oxtoacart** [comment]
I have a tentative pull request that may fix the IdleTiming issue - https://github.com/getlantern/flashlight-build/pull/19

I created a version of the tcpproxying branch that incorporates the changes from that PR and am testing that on fl-singapore-004-1 now.  We'll see how it holds up.

**Comment by oxtoacart** [comment]
Just saw another spike, with similar pprof output:

~~~
Showing top 20 nodes out of 80 (cum >= 5.55s)
      flat  flat%   sum%        cum   cum%
   129.41s 30.71% 30.71%    129.41s 30.71%  ExternalCode
    24.74s  5.87% 36.58%     24.74s  5.87%  runtime.xchg
    15.38s  3.65% 40.23%     15.38s  3.65%  runtime.newdefer
    14.43s  3.42% 43.66%     14.43s  3.42%  runtime.writebarrierptr
    14.32s  3.40% 47.05%     17.84s  4.23%  runtime.getitab
    12.92s  3.07% 50.12%     38.74s  9.19%  runtime.deferreturn
     9.46s  2.25% 52.37%    228.28s 54.17%  github.com/getlantern/idletiming.(*IdleTimingConn).Write
     8.69s  2.06% 54.43%      8.69s  2.06%  runtime.releasem
     8.36s  1.98% 56.41%    241.18s 57.24%  bufio.(*Writer).Write
     8.06s  1.91% 58.33%      8.06s  1.91%  sync/atomic.CompareAndSwapUint64
     7.87s  1.87% 60.19%     15.23s  3.61%  runtime.freedefer
     7.87s  1.87% 62.06%      7.87s  1.87%  sync/atomic.CompareAndSwapUint32
     7.43s  1.76% 63.82%     60.56s 14.37%  runtime.netpollSetDeadline
     7.14s  1.69% 65.52%      7.14s  1.69%  time.Time.Add
     7.03s  1.67% 67.19%     26.19s  6.22%  runtime.assertI2I2
     6.76s  1.60% 68.79%      6.76s  1.60%  sync/atomic.AddUint32
     6.59s  1.56% 70.35%     15.55s  3.69%  runtime.deferproc
     5.95s  1.41% 71.77%      5.95s  1.41%  runtime.deferproc_m
     5.78s  1.37% 73.14%     88.22s 20.94%  crypto/tls.(*Conn).Write
     5.55s  1.32% 74.46%      5.55s  1.32%  runtime.acquirem
~~~
