### ISSUE TITLE
Track country of traffic on servers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2122]

**Comment by oxtoacart** [comment]
As part of this, I'm tracking both the client's country and the destination port.

To do this, I introduced a new stat:

bytesGivenTo

This reports bytes given to the respective country.

**Comment by oxtoacart** [comment]
I've also updated statshub to start archiving the destport dimension hourly.

**Comment by myleshorton** [comment]
Nice!

On Fri, Jan 2, 2015 at 9:19 AM, oxtoacart <notifications@github.com> wrote:

> I've also updated statshub to start archiving the destport dimension
> hourly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2122#issuecomment-68543707>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Thanks!  Once the PR is merged, I'll push to a couple of flashlight servers and if that looks good after a day, I'll push to all of them.

FYI - I ended up building this off the tcpproxying branch because I didn't want to have to touch the code twice, and the server-side API is a little different from devel.

**Comment by oxtoacart** [comment]
Merged and deployed to all flashlight servers.

**Comment by scouttle** [comment]
Just noticed that this ticket is closed – @oxtoacart should it be moved to devel?

**Comment by myleshorton** [comment]
I would just put it in devel just to keep things simple. I don't think anyone's going through our closed tickets closely enough to really get upset with this.

**Comment by oxtoacart** [comment]
Moved to devel.
