### ISSUE TITLE
java.io.FileNotFoundException: $HOME/Library/Logs/Lantern/java.log (Permission denied)

### ISSUE THREAD

**Issue by rngadam** [getlantern/lantern#2126]
Starting from the command-line:

```
/Applications/Lantern.app/Contents/MacOS/JavaApplicationStub 
```

I get:

```
Not on main line...
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /Users/rngadam/Library/Logs/Lantern/java.log (Permission denied)
```

Even if I create the file and give it all permissions:

```
$ ls -al /Users/rngadam/Library/Logs/java.log
-rw-rw-rw-+ 1 rngadam  staff  0  2 Jan 17:42 /Users/rngadam/Library/Logs/java.log
```

full logs:

https://gist.github.com/rngadam/26f6f76fb3ecd2c7138f

**Comment by oxtoacart** [comment]
@rngadam What version of Lantern are you running?  You can find the version string in the footer of the UI.

**Comment by oxtoacart** [comment]
@rngadam Check your path.  The file you created is in ~/Library/Logs, but Lantern is trying to log to ~/Library/Logs/Lantern.

**Comment by myleshorton** [comment]
@rngadam is it possible you already had a version of Lantern running?

**Comment by myleshorton** [comment]
This shouldn't be an issue with the new Lantern.
