### ISSUE TITLE
[flashlight] register_domains.py fails whenever I update an existing flashlight server

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2132]
~~~
2015-01-05 02:27:51,877 ERROR    uncaught top-level exception
Traceback (most recent call last):
  File "/home/lantern/register_domains.py", line 66, in <module>
    register()
  File "/home/lantern/register_domains.py", line 24, in register
    response = cf.rec_new(ZONE, 'A', subdomain, IP)
  File "/usr/local/lib/python2.7/dist-packages/pyflare/client.py", line 419, in rec_new
    return self._request(params)
  File "/usr/local/lib/python2.7/dist-packages/pyflare/client.py", line 512, in _request
    raise self.APIError(response['msg'], response.get('err_code'))
APIError: A record with these exact values already exists. Please modify or remove this record.
~~~

As part of fixing this, we might want to consider having the flashlight server ping peerdnsreg the way that peer servers do.  We'll need to port that code to Go eventually anyway, and treating our fallbacks the same way as peers would allow peerdnsreg to automatically take nonresponsive fallbacks out of rotation.

**Comment by oxtoacart** [comment]
@myleshorton FYI

**Comment by aranhoide** [comment]
IIRC the machine would keep a record of the registration details, both for
the purposes of eventually unregistering, and to avoid double registrations.

Feel free to reassign to me and I'll look this up.  This is low priority I
think, since this failure should have no other effects.

**Comment by oxtoacart** [comment]
@aranhoide The registration is just under the machine's hostname, so there shouldn't be a need to keep track of anything additional.

**Comment by oxtoacart** [comment]
Agree that this is low priority, that's why I marked it P3.

**Comment by aranhoide** [comment]
I may be misremembering, but I think we used to register the machine both as a subdomain and as one of the targets of the round robin.  Upon registering, cloudflare would give you some handle/cookie/id that you could use for unregistering.  That's what we're storing.  It's not strictly necessary, but it avoids some cloudflare queries every time we update the machine or when we unregister.

**Comment by oxtoacart** [comment]
Ah, we're talking about registering with two different services.  You're talking about registering with CloudFlare directly.  I was talking about registering with peerdnsreg, which takes care of registering with CloudFlare for us.  Any optimizations like storing a handle would be done by peerdnsreg.

**Comment by myleshorton** [comment]
I like the idea of having the servers use the same mechanism so we can
automatically take them out of rotation. Makes sense.

On Mon, Jan 5, 2015 at 7:50 AM, oxtoacart <notifications@github.com> wrote:

> Ah, we're talking about registering with two different services. You're
> talking about registering with CloudFlare directly. I was talking about
> registering with peerdnsreg, which takes care of registering with
> CloudFlare for us. Any optimizations like storing a handle would be done by
> peerdnsreg.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2132#issuecomment-68726623>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
