### ISSUE TITLE
some errors when starting up

### ISSUE THREAD

**Issue by LeoK987** [getlantern/lantern#2133]
$ lantern
sed: couldn't open temporary file /opt/lantern/sedaXQO3x: Permission denied
cp: cannot create regular file ‘/usr/share/applications/lantern.desktop’: Permission denied
mv: try to overwrite ‘/opt/lantern/jre/bin’, overriding mode 0755 (rwxr-xr-x)? 
mv: try to overwrite ‘/opt/lantern/jre/man’, overriding mode 0755 (rwxr-xr-x)? 
mv: try to overwrite ‘/opt/lantern/jre/plugin’, overriding mode 0755 (rwxr-xr-x)? 
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: log.txt (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at org.littleshoot.util.CommonUtils.<clinit>(CommonUtils.java:48)
	at org.lantern.Launcher.<clinit>(Launcher.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Not on main line...

**Comment by myleshorton** [comment]
Thanks @LeoK987 there are a few issues here, but the logging one (second error) is just a quirk of log4j startup that doesn't affect anything. The first is more of an issue. You could set permissions on the /opt/lantern directory to no require root, and in the future we'll handle this on the install side.

**Comment by scouttle** [comment]
Agree, thanks for reporting, @LeoK987! 

We expect that these errors will have minimal impact on Lantern when it's actually running; are you seeing anything that seems visibly off? 

Thanks again!

**Comment by LeoK987** [comment]
Thanks guys.  I don't know what problems these cause me.  It gets me access
albeit at times slow.  But I can not logon to google from the lantern
windows though, so I wonder if these caused it.

**Comment by myleshorton** [comment]
Does logging on to Google simply time out or what happens exactly? Are you
still seeing problems now?

On Mon, Jan 5, 2015 at 2:13 PM, LeoK <notifications@github.com> wrote:

> Thanks guys. I don't know what problems these cause me. It gets me access
> albeit at times slow. But I can not logon to google from the lantern
> windows though, so I wonder if these caused it.
>
> On Tuesday, January 6, 2015, scouttle <notifications@github.com> wrote:
>
> > Agree, thanks for reporting, @LeoK987 <https://github.com/LeoK987>!
> >
> > We expect that these errors will have minimal impact on Lantern when
> it's
> > actually running; are you seeing anything that seems visibly off?
> >
> > Thanks again!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/getlantern/lantern/issues/2133#issuecomment-68755282>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2133#issuecomment-68791604>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by LeoK987** [comment]
I have not changed permissions (not sure about the implications), so yes
the problems are still there.

As to logging into google, it simply hangs there (and eventually times out
I guess).  It has been like this for about a year.  After learning that
lantern can still be used without signing in, I simply leave it not signed
it.

**Comment by myleshorton** [comment]
Thanks @LeoK987! So you just manually point to 127.0.0.1:8787 is that correct? Have you heard of a lot of other people doing the same thing?

**Comment by LeoK987** [comment]
@myleshorton,

Actually, how lantern should be set to work is a mystery to me.  The
documentation (little) says that it sets the system proxy.  Firefox seems
to work with system proxy.  But if I use the system proxy in Chrome, it
doesn't work.  Chrome currently works for me because I have had
SwitchySharp which I set for automatic configuration to use lantern.  It
was set up that way when I could sign in to google on lantern years ago.
If I disable SwitchySharp then Chrome stops working with lantern, so I have
to keep SwitchySharp.  I read somewhere that I don't need to use an
extension in Chrome to use lantern, but that is not the case for me.

I tried to ask about in the user group and no one answered.  Also related
is how to use Thunderbird with lantern.  Using system proxy in TB does not
work.

So, no, I did not just point to 127.0.0.1:8787.  Should I better do that?
And I actually don't know anyone using lantern.

**Comment by myleshorton** [comment]
Thanks @LeoK987 and sorry for the delay! Any browser extension that sets a proxy will override the system proxy, so that could be related to what you're seeing. Chrome without any extension should always just use the system proxy, so maybe there's another extension that's affecting the proxy settings? Do you configure SwitchySharp to just point to 127.0.0.1:8787 for it to work with Lantern?

What platform are you on?

**Comment by myleshorton** [comment]
Closing since we've released a new Go beta where this could be solved -- can reopen if not.

**Comment by LeoK987** [comment]
What can I download to update the new change?  On github, the newest
lantern is still 1.5.17 of Jan 15.

**Comment by myleshorton** [comment]
Hey @LeoK987 sorry we haven't really made a formal announcement yet, but you can download it from the beta page at:

https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions

**Comment by LeoK987** [comment]
Great.  Thanks.  The new version appears to be faster?  At least Google
Maps works much better.

But I found the following messages at startup.  Seems improper.

flashlight.ui: Creating tarfs filesystem that prefers local resources at
/home/aranhoide/src/flashlight-build/src/
github.com/getlantern/lantern-ui/app
tarfs: Local dir /home/aranhoide/src/flashlight-build/src/
github.com/getlantern/lantern-ui/app does not exist, not using

**Comment by fffw** [comment]
@LeoK987 it’s just a debug message. You are seeing it from lantern.log file right?

**Comment by LeoK987** [comment]
I saw it in the terminal where I started lantern.  Not in the log file.

**Comment by myleshorton** [comment]
That does seem odd. Any ideas @aranhoide?

**Comment by aranhoide** [comment]
I'm not familiar with the tarfs thing, no.  I imagine @LeoK987 is using the ubuntu 64bit binary/installer, which were built in my machine.  I don't know why that would cause the binary to have these paths hardcoded.

**Comment by oxtoacart** [comment]
It's because flashlight/ui/ui.go uses [runtime.Caller](http://golang.org/pkg/runtime/#Caller) to determine the location of local resources.  This is based on the absolute path of the source file from which the program was compiled, which in this case was on @aranhoide's machine.

**Comment by LeoK987** [comment]
Yes, I installed it with the ubuntu 64bit binary/installer.

**Comment by myleshorton** [comment]
Thanks guys. So those machine-specific paths don't cause any issues right
@oxtoacart?

On Friday, March 13, 2015, LeoK <notifications@github.com> wrote:

> Yes, I installed it with the ubuntu 64bit binary/installer.
>
> On Saturday, March 14, 2015, aranhoide <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I'm not familiar with the tarfs thing, no. I imagine @LeoK987
> > <https://github.com/LeoK987> is using the ubuntu 64bit binary/installer,
> > which were built in my machine. I don't know why that would cause the
> > binary to have these paths hardcoded.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/getlantern/lantern/issues/2133#issuecomment-79883834
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2133#issuecomment-79903026>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
The only issue it causes is that if someone wants to use local resources while running with the binary, it won't work unless they happen to have the same username as whoever built the binary or manually set up the correct path.  Since this isn't a realistic use case, I don't think it's a big deal.
