### ISSUE TITLE
[bug] [flashlight] Figure out why CloudFlare seems to slow things down so much

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2141]
While testing the changes for #2121 by running a client against a specific flashlight server containing the #2121 changes, I noticed that CloudFlare was reporting a fair number of connection timeouts, and the browsing experience overall seemed pretty flaky.

I then tried testing against a flashlight server running locally, and the timeouts disappeared and the browsing experience was great.

I then tried hitting the remote flashlight server directly (by ip), and performance was still good and timeouts weren't a problem.

I then tried hitting it via CloudFlare.  For a while, it was responsive, but eventually it started timing out quit and page loads in the browser just hung.

I then configured the client to hit the server by IP again, and all was fine again.  So, it doesn't appear to be a problem with the server being overloaded or anything like that.

**Comment by myleshorton** [comment]
Interesting @oxtoacart. Adding this to short term.

**Comment by oxtoacart** [comment]
Okay, I have some idea of what's causing this.  Looking at one of our flashlight servers, I see that it's maintaining 10 times as many outbound connections as inbound from CloudFlare.  I implemented an optimization some time ago to stream responses as long as possible in a single response.  This ties up a connection.  If all of the connections from CloudFlare are busy streaming responses, requests from new clients will stack up behind them.

A couple of solutions come immediately to mind:

1. See if we can get CloudFlare to open more connections

2. Maintain enough flashlight servers so that the number of outbound connections is generally less than or equal to the number of CloudFlare connections

3. Terminate responses frequently.  This will introduce additional overhead because a single actual response will need to be encapsulated in multiple CloudFlare responses.

**Comment by oxtoacart** [comment]
Well, it turns out that we already limit each response to 1 MB and terminate it if idle for more than 35 milliseconds.  So, perhaps this is not the root cause ...

**Comment by oxtoacart** [comment]
Note, right now I'm running against fallbacks.getiantem.org with masquerading on.  I had recently updated and bounced all of the flashlight servers.  At the moment, the browsing experience is quite decent through CloudFlare.

**Comment by oxtoacart** [comment]
Just did some more testing on this, using https://en.wikipedia.org/wiki/Germany.  It looks like it's really just down to geography.

- With the default configuration (roundrobin + full masquerade set), the page takes about 35 seconds to load.

- Without flashlight (i.e. no proxying), the page loads in about 3.5 seconds.

- Using my own flashlight server hosted at home, accessed directly (no CloudFlare, but going over network), the same page loads in 5 to 5.5 seconds

- Using my own flashlight server, accessed via CloudFlare but without masquerading, the page loads in about 11 seconds

- After adding masquerading, the load time is still about 11 seconds

This is just one site, but for Wikipedia anyway, it seems that distance between client and proxy matters quite a bit (to the tune of 3x variation depending on proximity).

**Comment by oxtoacart** [comment]
Tested again with a Singapore site, http://www.dbs.com.sg/index/default.page

- No Proxy: about 2s
- Standard Proxy: 17-25s
- Home Proxy via CloudFlare (w Masquerade): 9s
- Home Proxy via CloudFlare (w/o Masquerade): 6.5-7s
- Home Proxy Direct: 2.5-3s

In conjunction with the Wikipedia test, assuming that my home proxy doesn't have any advantage over the roundrobin:

1. Having the proxy close the client seems to be more important than having it close to the destination server. The effect is quite large. Consequently, our Singapore-based servers should theoretically do well for Chinese users (assuming that connectivity between China and Singapore is good), but might do very poorly indeed for users far from SE Asia, for example Iran.

2. Including CloudFlare imposes about a 2x penalty

3. Including masquerading imposes an additional 1.5x penalty

**Comment by myleshorton** [comment]
Thanks Ox! That makes sense to me especially because most big destination
sites should themselves be running on CDNs. So it seems like having servers
closer to Iran would be huge. We also should be able to do better with
China - Japan or even better South Korea are significantly closer. Might be
worth testing EC2 in Japan.

On Saturday, January 24, 2015, oxtoacart <notifications@github.com> wrote:

> Tested again with a Singapore site,
> http://www.dbs.com.sg/index/default.page
>
>    - No Proxy: about 2s
>    - Standard Proxy: 17-25s
>    - Home Proxy via CloudFlare (w Masquerade): 9s
>    - Home Proxy via CloudFlare (w/o Masquerade): 6.5-7s
>    - Home Proxy Direct: 2.5-3s
>
> In conjunction with the Wikipedia test, assuming that my home proxy
> doesn't have any advantage over the roundrobin:
>
>    1.
>
>    Having the proxy close the client seems to be more important than
>    having it close to the destination server. The effect is quite large.
>    Consequently, our Singapore-based servers should theoretically do well for
>    Chinese users (assuming that connectivity between China and Singapore is
>    good), but might do very poorly indeed for users far from SE Asia, for
>    example Iran.
>    2.
>
>    Including CloudFlare imposes about a 2x penalty
>    3.
>
>    Including masquerading imposes an additional 1.5x penalty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2141#issuecomment-71343639>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton linode and vultr both have Tokyo datacenters as well.  vultr's $7 per month plan looks like the best deal for us, as it includes 2TB transfer per month.  But, linode is supported by salt-cloud, so it might be an easier place to start - http://docs.saltstack.com/en/latest/ref/clouds/all/.

IIRC, Amazon's bandwidth is much more expensive than DO, linode and vultr.

**Comment by oxtoacart** [comment]
@myleshorton I should have mentioned that based on what we've seen on our DO servers, bandwidth is our limiting factor rather than CPU or memory.

**Comment by fffw** [comment]
Linode Tokyo has very good reputation on its network performance accessing from China.

**Comment by oxtoacart** [comment]
@fffw Nice!  Sounds like that makes the choice easy.

@myleshorton Perhaps we should accelerate https://github.com/getlantern/lantern/issues/1763 ?

**Comment by myleshorton** [comment]
Nice! Yup I agree @oxtoacart let's make it happen.

On Sunday, January 25, 2015, oxtoacart <notifications@github.com> wrote:

> @fffw <https://github.com/fffw> Nice! Sounds like that makes the choice
> easy.
>
> @myleshorton <https://github.com/myleshorton> Perhaps we should
> accelerate #1763 <https://github.com/getlantern/lantern/issues/1763> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2141#issuecomment-71383696>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
@fffw you want to take a look at this?

**Comment by fffw** [comment]
@myleshorton you mean to try Linode deployment or to conduct more testing against CloudFlare?

Either way, it will be very helpful for me to understand the structure and usage of flashlight.

**Comment by myleshorton** [comment]
Yeah that's a good point @fffw. We might actually be able to close this ticket and focus on #1763. Let's actually wait for @oxtoacart to get back on this one so we can get some really good numbers on how much and if the Tokyo switch improves things.
