### ISSUE TITLE
Port system tray to go

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2143]

**Comment by fffw** [comment]
Proposed dynamic behaviours:

1. change icon
2. change hint when pointing to it
3. change menu item
4. callback or chan to receive menu item click event

**Comment by oxtoacart** [comment]
> Proposed dynamic behaviours:

Thanks for writing this up

> 1. change icon

Yes

> 2. change hint when pointing to it

Nice idea!

> 3. change menu item

Yes

> 4. callback or chan to receive menu item click event

Yes, and I prefer a channel, specifically a receive-only channel.  You can make a receive-only channel like this:

```go
func makeReceiveOnly(ch chan interface{}) <-chan interface{} {
    return ch
}
```

Or like this:

```go
var ch chan interface{}
rch := ch.(<-chan interface{})
```

> 5. specially, assign an url to a menu item, to open in default browser when clicked.

No. We should just handle this by responding to the message from no. 4.  Opening something in the user's default browser is a separate concern from managing a system tray menu, and so is best handled by a separate library.  There are some existing ones like https://github.com/skratchdot/open-golang that may work for us.

**Comment by fffw** [comment]
Thanks for you insights @oxtoacart.

I implemented direct callback from obj-c to go, so we can add an menu item and wait on an channel.

If we want dynamic behaviour, such as change icon, add/remove menu items, change menu item text, we should keep track of menu item handles, which makes interface complicated.

For now I'll keep it simple and port to Windows/Linux.

**Comment by oxtoacart** [comment]
> Thanks for you insights @oxtoacart.

You're welcome!

> I implemented direct callback from obj-c to go, so we can add an menu item and wait on an channel.

Great!

> If we want dynamic behaviour, such as change icon, add/remove menu items, change menu item text, we should keep track of menu item handles, which makes interface complicated.

Why bother with handles?  We could just provide an idempotent API like this:

```go
type MenuItem struct {
    id string
    label string
    icon []byte
}

type MenuManager interface {
    SetMenuItems(items []*MenuItem)

    OnSelectCh() <-chan string // sends ids of menu items as they're selected
}
```

When you want to change the menu items, just pass the whole list and have the implementation of MenuManager figure out what to add/remove based on the ids.

menu

**Comment by atavism** [comment]
@myleshorton and @oxtoacart, quick clarification on this: if we want to use a browser extension anyway, is there any reason why we need to port the system tray to Go? Why not just do that instead if this is going away anyway?

**Comment by myleshorton** [comment]
Interesting question. That could take care of some of the issues with showing Lantern. I do see few issues with that approach though:

1. We'd probably have to do it on both Chrome and Firefox
1. What do we do on other browsers?

Lantern is also always running in the background on startup by default. Do we want to convey that to the user in some way?

**Comment by atavism** [comment]
> 1. We'd probably have to do it on both Chrome and Firefox

Yes. @oxtoacart already did a lot of the work for the Chrome extension. We could bundle all the extensions together into a new "lantern-extensions" project?

> 2. What do we do on other browsers?

I believe we can create an extension for Safari too? Not sure about IE. https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html

> Lantern is also always running in the background on startup by default. Do we want to convey that to the user in some way?

The extension itself could convey that information. Perhaps the first time the user installs Lantern, and consequently the extension, it could show a little popup informing the user that Lantern is running in the background.

Anyway, I just wanted to bring this up because I don't want us to do extra work here unnecessarily. I think we're all in agreement a browser extension is preferable for a multitude of reasons: it's easier to manage windows, it would let us proxy sites on-demand, see real-time stats without having to open the entire map, the lantern icon could light up as a site is being proxied, etc. IMO, this would be a huge user experience improvement.

**Comment by myleshorton** [comment]
So just to be clear I definitely want to do an extension in any scenario, but I'm just not totally convinced an extension would really allow us to eliminate the system tray. 

1. If something's running the background, you kind of want to know and to be able to control it regardless of whether or not you have your browser up
1. It also allows us to provide more UI without the browser, such as changing slightly when you're connected, actively proxying, etc. I personally find the UIs for extensions often a bit cumbersome and non-obvious (which icon is it again?), and I think the system tray approach feels a little cleaner.

What do you think on this one @scouttle?

**Comment by atavism** [comment]
> So just to be clear I definitely want to do an extension in any scenario, but I'm just not totally convinced an extension would really allow us to eliminate the system tray.

Oh, alright. I misunderstood then. I thought the plan was to retire the system tray entirely in favor of using browser extensions. Regarding #1, that's a valid point. Would it really be undesirable if a user were only able to control Lantern from the browser? Most people always have a browser window open. With that said, do we plan to eventually show the system tray and browser extension? Should we show the system tray when the user closes her browser and hide it when the browser is re-opened? Or just always show both?

**Comment by myleshorton** [comment]
> I was under the impression the plan was to retire the system tray entirely in favor of using browser extensions.

I feel like that's been mentioned before but certainly never reached the "the plan" stage. I really see them as separate issues and tasks.

> Would it really be undesirable if a user were only able to control Lantern from the browser? Most people always have their primary browser open.

I just find extension UIs to be generally a little clunky while system tray UIs, especially on OSX, are generally pretty nice. But I'm also not sure we have to choose!

> With that said, if we keep the system tray, would we show it when the user closes her browser and hide it when the browser is re-opened?

I don't think so. Lantern would still be running, so I would think we'd just keep the system tray up.

> Or just always show both the system tray and the browser extension?

That's what I would think yeah.

**Comment by oxtoacart** [comment]
The other thing to consider here is Give versus Get usage.  If I'm running Lantern in Give mode, it probably wouldn't feel natural to interact with it from my browser.  If I'm running in Get mode, it would probably feel most natural to interact with it through the browser.

**Comment by oxtoacart** [comment]
We really should decide if we're doing the extension though, since it has other implications.  For example, if we have an extension that can manage the browser's proxy settings, we don't need to mess with the system proxy settings, which gets around the problem of user access control.  To me, that's a big win.

**Comment by fffw** [comment]
From my point of view, if we want to provide tool for the masses, it should just works. User need not turn something on and off, or distinguish blocked sites from others. It may be very tough to implement, but can we approach this way?




Furthermore, other desktop applications with browser embedded or using http suite, such as Gmail, Dropbox, etc., can also benefit from Lantern. Should we give user impression that we also support them?


Regards,Merlin

**Comment by oxtoacart** [comment]
> From my point of view, if we want to provide tool for the masses, it should just works. User need not turn something on and off, or distinguish blocked sites from others. It may be very tough to implement, but can we approach this way?

Yes!  Currently, we only send whitelisted sites through Lantern, for two reasons.  One is that we believe it looks less suspicious if the computer is seen accessing unblocked sites directly.  The other is that we don't want to spend resources proxying stuff that isn't blocked.  One of the main motivations behind the extension is that it would give us the access that we need to detect potential blockages and respond a little better.

> Furthermore, other desktop applications with browser embedded or using http suite, such as Gmail, Dropbox, etc., can also benefit from Lantern. Should we give user impression that we also support them?

You're right, we don't do a good job advertising that Lantern supports these.

**Comment by fffw** [comment]
>   Yes! Currently, we only send whitelisted sites through Lantern, for two reasons. One is that we believe it looks less suspicious if the computer is seen accessing unblocked sites directly. The other is that we don't want to spend resources proxying stuff that isn't blocked. One of the main motivations behind the extension is that it would give us the access that we need to detect potential blockages and respond a little better.

What I mean is, can we make whitelisting with less user intervention? Like syncing periodically from public lists per user location. Browser extension may has the sole responsibility to customize user's very own list with a single click( and submit to public database maybe), which is not strongly related to Lantern from user's point view.

>   You're right, we don't do a good job advertising that Lantern supports these.
I mean what our UI makes users feeling. Sorry I should say it more frankly.

**Comment by myleshorton** [comment]
> What I mean is, can we make whitelisting with less user intervention? Like syncing periodically from public lists per user location. Browser extension may has the sole responsibility to customize user's very own list with a single click( and submit to public database maybe), which is not strongly related to Lantern from user's point view.

Yeah we've been talking about that for a long time too, and I agree just a centralized config file per country is the easiest big win there. Do you frequently encounter a lot of sites that are blocked but not on the whitelist? If so, can you make a note of them so we can add them?

**Comment by myleshorton** [comment]
> We really should decide if we're doing the extension though, since it has other implications. For example, if we have an extension that can manage the browser's proxy settings, we don't need to mess with the system proxy settings, which gets around the problem of user access control. To me, that's a big win.

Yeah I think we all agree we should write at least a chrome extension and probably FF too. I agree the extension should also deal with proxy settings because that's the only way we can override the proxy settings of *other extensions*. I'm not totally sure that can fully replace the system proxy, though, as otherwise we'd be forced to implement extensions for all browsers unless we wanted to force the user to use a specific browser for Lantern to work. The code to port system proxying is also super easy, but I agree with you that at least on OSX the need for root is annoying. I'm curious if @fffw's recent changes still require root, but presumably they do. Would be sweet if not though!

**Comment by myleshorton** [comment]
Yeah looks like you can't get the preferences lock without root. Too bad!

**Comment by fffw** [comment]
As per [doc](https://developer.apple.com/library/mac/documentation/Networking/Conceptual/SystemConfigFrameworks/SC_Overview/SC_Overview.html#//apple_ref/doc/uid/TP40001065-CH202-CHDIFJAB), it does require root.

But why doesn't Mac request sudo password when accessing network preference GUI?

**Comment by fffw** [comment]
Maybe there are ways to eliminate root requirements through fine-grained right control through Authorization Services. I'm trying.

**Comment by fffw** [comment]
Tried but will prompt for user/password to access system preferences.

Maybe [what this thread said](http://www.cocoabuilder.com/archive/cocoa/2206-system-preferences-network-settings.html) is right.

>  I have found out that the System Preferences application actually uses a helper program which runs as root...

**Comment by fffw** [comment]
>  Do you frequently encounter a lot of sites that are blocked but not on the whitelist? If so, can you make a note of them so we can add them?




What annoys me most is those sites never expected to be blocked. Recent example is golang.org. Most popular list of blocked sites in China is maintained by AutoProxy. We can grab it through:




```sh


wget https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt


openssl base64  -d -in gfwlist.txt -out list.txt

```

It has thousands of records, but I think we can handle them through more efficient matching algorithm.




I don’t know if there are lists of other regions.

**Comment by myleshorton** [comment]
Yeah it looks like we're stuck with root @fffw. We probably could get it to prompt when it needs root, but then we'd be doing that on every Lantern run, which would get annoying.

I like the idea of just using AutoProxy's list! If we could just convert that to a pac file and just download it form a central location, we'd be in great shape for China at least. Can you add a ticket for that, including auto-updating the list on the server side periodically?

**Comment by myleshorton** [comment]
The root thing really isn't that terrible though too -- it just requires us to get root permissions once on install, and then we're good.

**Comment by myleshorton** [comment]
So just to be clear this should be a super simply go library that just does something like:

```go
func startProxying(url string) bool {
    // platform-specific code, maybe using compile flags
}

func stopProxying(url string) bool {
    // platform-specific code, maybe using compile flags
}
```

Those would all be for pac files at first but we could get more sophisticated later if an when necessary.

**Comment by fffw** [comment]
I'm working on the proxy library and discussion should go to getlantern/lantern#1902

Created getlantern/lantern#2177 for fetching AutoProxy list.

**Comment by atavism** [comment]
> Yeah I think we all agree we should write at least a chrome extension and probably FF too. I agree the extension should also deal with proxy settings because that's the only way we can override the proxy settings of other extensions. I'm not totally sure that can fully replace the system proxy, though, as otherwise we'd be forced to implement extensions for all browsers unless we wanted to force the user to use a specific browser for Lantern to work.

@myleshorton, I threw together a sample extension for Firefox [here](https://github.com/getlantern/firefox-extension). It didn't take long at all to implement so I don't think there would be that much extra work involved maintaining multiple browser extensions if we had to.

**Comment by fffw** [comment]
Curious enough that neither `gtk_status_icon` nor `App Indicator` works on my Ubuntu precise64 VM, even for other software packages I tried. Code runs without errors, but no systray displayed.

But `java.awk.SystemTray` works fine. Trying get its source code and check.

**Comment by myleshorton** [comment]
OK cool. If Ubuntu's a big pain we could probably punt on it initially too.

**Comment by fffw** [comment]
Now works on Debian through GTK+ API.

Still have problem showing on Ubuntu, in fact, my system menu bar is totally invisible after upgraded to Ubuntu 14.04. Will check later.

**Comment by myleshorton** [comment]
@fffw is there any way to just try out a demo of this?

**Comment by fffw** [comment]
@myleshorton new code and demo is under https://github.com/getlantern/systray/tree/issue-2143

**Comment by fffw** [comment]
Now works on Ubuntu and Debian. Also changes API to allow checked / disabled menu items. Seems enough to support our MVP.

Anyone have interest to review https://github.com/getlantern/systray/pull/1?

**Comment by myleshorton** [comment]
Awesome @fffw!! I think we can wait for @oxtoacart to review next week when he's back.
