### ISSUE TITLE
[flashlight] Disable memory profiling in salt flashlight.conf

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2145]
Right now, all of our flashlight servers are running with memory profiling on.  This imposes some overhead (though it doesn't seem to bad).  If we're no longer encountering what looks like memory-related issues, we should turn this off.

**Comment by oxtoacart** [comment]
Actually, the bigger impact of this is disk usage.  Bumping up to P1 short term because of that.

**Comment by myleshorton** [comment]
Pushing to medium term given comments in https://github.com/getlantern/lantern_aws/pull/32

**Comment by oxtoacart** [comment]
@myleshorton I was actually thinking of doing this sooner, since I'm not 100% clear on the performance impact of memory profiling.  If there's a chance we could improve subjective response times by doing this, I say we do it since it's a one-line change.

**Comment by oxtoacart** [comment]
> @myleshorton I was actually thinking of doing this sooner, since I'm not 100% clear on the performance impact of memory profiling. If there's a chance we could improve subjective response times by doing this, I say we do it since it's a one-line change.

That said, I appreciate that you're cleaning up the short-term bucket, so I can live with this being in medium-term :)

**Comment by oxtoacart** [comment]
> Actually, the bigger impact of this is disk usage. Bumping up to P1 short term because of that.

This makes me think that this needs to be P1 short-term.  If we just let it go, we'll eventually run out of disk space, with dire consequences.

**Comment by oxtoacart** [comment]
I went ahead and turned off the memory profiling to avoid disk space issues, and deployed to all flashlight servers.
