### ISSUE TITLE
[flashlight] Understand, and deal with, the fact that some flashlight servers seem to chronically get more traffic than others

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2146]
This came out of #2117.  Basically, some servers are chronically overloaded, almost as if clients are hitting them directly.  We do have sticky routing so that long-lived connections are all served by the same flashlight server, but we've seen high load persist even across server restarts, which would have severed those long-lived connections.

**Comment by myleshorton** [comment]
Since the CPU bugs have been fixed the alerts on flashlight servers have gone down to almost none. That combined with auto-restarts seem to have solved this well enough for now.

**Comment by oxtoacart** [comment]
Yes, after killing the couple of chronically overloaded machines, I haven't seen this come up again.
