### ISSUE TITLE
[feature] [flashlight] Track count of distinct client ips and sites visited by country

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2148]
We've had a huge increase in traffic from the Philippines, and it's not clear what's causing it.  In case it's an attack, or a few users taking advantage of the system, it would be nice to keep some counts by country:

- distinct ips
- distinct sites visited

We can do this using the "members" stat on statshub.

**Comment by oxtoacart** [comment]
Drats, this is going to require a change to statshub.  Currently, it only lets us submit one member at a time.  We'll need to submit multiple to accommodate this.

**Comment by oxtoacart** [comment]
I've already pushed this to statshub and deployed a flashlight build to 004-1 that's tracking these stats.  I'll watch it for a while and see how it goes.

**Comment by aranhoide** [comment]
Nice!

**Comment by oxtoacart** [comment]
@aranhoide Thanks! This is now live on all flashlight servers.
