### ISSUE TITLE
[feature] Track statistics on top sites per country by traffic

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2150]
We used to track statistics on all hosts, but that proved to be too expensive to archive to BigQuery.  Really, we only need to archive the top 10 per country at any given point in time, which would be much cheaper to do.  This just requires enhancing the archiving mechanism to be able to sort and take the top N on archiving.

This would help provide insight into questions like "why are users from the Philippines using a much larger amount of bandwidth per user than others?".

**Comment by myleshorton** [comment]
How does this relate to the top_sites_iran and top_sites_china views?

**Comment by oxtoacart** [comment]
> How does this relate to the top_sites_iran and top_sites_china views?

This is a reimplementation of the old feature.  The old feature tracked all sites for all countries, which became a prohibitively large set of data to handle.  The new ticket is about figuring out a way to track just the top X per period, which is much more feasible.

**Comment by myleshorton** [comment]
OK cool. And you just turned off archiving for the old feature, but the
queries nevertheless still work. Is that correct?

On Mon, Jan 12, 2015 at 10:29 AM, oxtoacart <notifications@github.com>
wrote:

> How does this relate to the top_sites_iran and top_sites_china views?
>
> This is a reimplementation of the old feature. The old feature tracked all
> sites for all countries, which became a prohibitively large set of data to
> handle. The new ticket is about figuring out a way to track just the top X
> per period, which is much more feasible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2150#issuecomment-69619167>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
That's right, I just turned off archiving.  You can still run queries agains whatever data was archived prior to me turning it off.
