### ISSUE TITLE
Setting system proxy taking up to 50 seconds in some cases

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2151]
This has been observed largely for Chinese users and is the cause the of the lag in showing the Google login screen. The cause seems to be a large number of network interfaces for VPNs that each take around 1 second to change proxy settings on in the current code. @fffw already submitted a PR for this.

**Comment by myleshorton** [comment]
See #2149

**Comment by myleshorton** [comment]
Hey @fffw do you have a windows machine or VM available? I'm wondering if you see a similar issue there.

**Comment by myleshorton** [comment]
Closing this @fffw -- I actually just released this as one of two fixed in Lantern 1.5.16 beta -- your first code made it into production pretty darn quick! If you're able to, it would be great to investigate the Windows issue too though.

**Comment by fffw** [comment]
Great thanks to @myleshorton and @oxtoacart for helping me find out it.

I’ll try Windows once I return home next Tuesday, as my laptop lacks of space for a VM.  

--  
Merlin Ran
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by myleshorton** [comment]
OK great @fffw. In the meantime I would feel free to tackle any other bug you see that looks like a good candidate for you. I did add #2143 that would largely be to continue the work you started before to create a more comprehensive and cross platform system tray library in Go that would get us further along in our Go port, so might be a good choice!

**Comment by fffw** [comment]
Yes, I did assign #2143 to myself. That would take longer as I have few knowledge on Objective C.

--  
Merlin Ran
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by myleshorton** [comment]
Sounds good @fffw. I know there was some feedback from the team on your earlier implementation, so hopefully we can dig that up and figure out the best path.
