### ISSUE TITLE
Either user data or country data is wrong

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2152]
There are numbers that contradict each other, making it appear we have issues with our data. For example, the following two queries return drastically different results:

SELECT STRING(DATE(SEC_TO_TIMESTAMP(FLOOR(TIMESTAMP_TO_SEC(_ts) / 60 / 60 / 24 / 7) * 60 * 60 *24 * 7))) AS week, MAX(gauge.userOnline) AS online
FROM statshub.country
WHERE _dim == 'total'
GROUP BY week
ORDER BY week DESC

SELECT STRING(DATE(SEC_TO_TIMESTAMP(week * 60 * 60 * 24 * 7))) AS week, count(*) as num_instances
FROM
(SELECT FLOOR(TIMESTAMP_TO_SEC(_ts) / 60 / 60 / 24 / 7) AS week, _dim AS instance
FROM statshub.user
WHERE gauge.bpsGotten > 0 AND _dim <> 'total'
GROUP BY week, instance) A
GROUP BY week
ORDER BY week DESC

**Comment by oxtoacart** [comment]
Here's at least part of the problem:

https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/simple/Give.java#L93
https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/state/InstanceStats.java#L214

The simple.Give proxy (which is what we use for fallbacks) uses InstanceStats, which in turn reports userOnline to statshub.

**Comment by myleshorton** [comment]
Interesting. I believe we still have 100 fallbacks right @aranhoide? So that would mean we're overcounting by 100.

**Comment by oxtoacart** [comment]
Yes, looks like we have 100 fallbacks.

In trying to account for the mysterious jump of 500 in early august, that leaves 400 unaccounted for.

**Comment by oxtoacart** [comment]
Ahh, found the 400 - it looks like we added a lot of United States Give-mode proxies in early August.  That was during our IndieGogo campaign, wasn't it?

**Comment by oxtoacart** [comment]
BTW, the 2nd query only counts Get mode, while the First query includes both Give and Get.

A more appropriate query is 

```sql
SELECT STRING(DATE(SEC_TO_TIMESTAMP(week * 60 * 60 * 24 * 7))) AS week, count(*) as num_instances
FROM
(SELECT FLOOR(TIMESTAMP_TO_SEC(_ts) / 60 / 60 / 24 / 7) AS week, _dim AS instance
FROM statshub.user
WHERE (gauge.bpsGotten > 0 OR gauge.bpsGiven > 0) AND _dim <> 'total'
GROUP BY week, instance) A
GROUP BY week
ORDER BY week DESC
```

By this query, the total numbers are still way off between these two queries, but the growth profile over time is much more similar.

**Comment by myleshorton** [comment]
@oxtoacart the jump in August was primarily our promotional activities in general, with the Fight for the Future email being the biggest. We also had the story in Le Monde that pushed up our numbers in France, Giga Om, WaPo, etc.

**Comment by myleshorton** [comment]
> BTW, the 2nd query only counts Get mode, while the First query includes both Give and Get.

**Comment by myleshorton** [comment]
> BTW, the 2nd query only counts Get mode, while the First query includes both Give and Get.

Oh that makes sense on @oxtoacart! So actually the updated query also likely really undercounts give mode because a lot of give mode users likely haven't given anything.

**Comment by oxtoacart** [comment]
> Oh that makes sense on @oxtoacart! So actually the updated query also likely really undercounts give mode because a lot of give mode users likely haven't given anything.

Yes, that makes sense!

**Comment by oxtoacart** [comment]
Another thing that accounts for the discrepancy is that the concurrent users number is actually concurrent Lantern instances (an approximation of users), whereas the bytesGotten/bytesGiven figure is actual users.  If users run multiple instance or (as is likely given some of the problems we've seen in the field) users don't have a user ID assigned to them, the user's figure will differ from the instances figure.

**Comment by oxtoacart** [comment]
Scratch the above comment, userOnline is driven by user GUID after all.

**Comment by myleshorton** [comment]
The other interesting wrinkle there is that still most of our traffic has been from users with no GUID! In our database there are no users who have ever logged in who have no GUID, so there doesn't appear to be a bug with GUID assignment.

**Comment by oxtoacart** [comment]
> The other interesting wrinkle there is that still most of our traffic has been from users with no GUID! In our database there are no users who have ever logged in who have no GUID, so there doesn't appear to be a bug with GUID assignment.

Just because the controller has assigned a GUID doesn't mean that the client has received and remembered it.  In fact, the GUID is communicated over XMPP, with which we've been seeing all sorts of issues.

**Comment by myleshorton** [comment]
> Just because the controller has assigned a GUID doesn't mean that the client has received and remembered it. In fact, the GUID is communicated over XMPP, with which we've been seeing all sorts of issues.

That's certainly true -- that discrepancy could be tied to users never getting that reply from the server. It would be odd if the XMPP client were disconnected each time after sending the XMPP message to the controller and before receiving a message back. In order for the client side not to get a GUID, the disconnect would have to happen precisely then *on every call to the controller on every run*, which doesn't seem likely.

**Comment by oxtoacart** [comment]
> That's certainly true -- that discrepancy could be tied to users never getting that reply from the server. It would be odd if the XMPP client were disconnected each time after sending the XMPP message to the controller and before receiving a message back. In order for the client side not to get a GUID, the disconnect would have to happen precisely then on every call to the controller on every run, which doesn't seem likely.

Probably not likely, but we just don't know.  We just need to trace the GUID all the way through and figure out where it's getting lost.

**Comment by oxtoacart** [comment]
One other cause for discrepancies - the first query is based on a statistic that's keyed to user GUID, the 2nd stat is based on a statistic that's keyed to instance id.

**Comment by oxtoacart** [comment]
So here's the likely main problem - the query from statshub.user is based on rollups using the user GUID.  Since we seem to be getting a lot of activity under a blank user GUID, it's likely that a lot of what are really distinct clients are rolling up to the same blank user GUID.

**Comment by oxtoacart** [comment]
> The other interesting wrinkle there is that still most of our traffic has been from users with no GUID! In our database there are no users who have ever logged in who have no GUID, so there doesn't appear to be a bug with GUID assignment.

Looking at the code, I see that the everSignedIn flag and the guid are both set by the XmppAvailableServlet.  So, everSignedIn = True and guid = NULL is impossible.

The corollary to this is that if there's a consistent problem communicating over XMPP and the XmppAvailableServlet.doPost() method is never invoked for a given user, the database will show everSignedIn = False and guid = NULL.

**Comment by myleshorton** [comment]
> Looking at the code, I see that the everSignedIn flag and the guid are both set by the XmppAvailableServlet. So, everSignedIn = True and guid = NULL is impossible.

Unless there's a bug of course.

> 
> The corollary to this is that if there's a consistent problem communicating over XMPP and the XmppAvailableServlet.doPost() method is never invoked for a given user, the database will show everSignedIn = False and guid = NULL.

Hmnn...yeah that makes sense. If the user ever gets there it works fine, but what if the user never gets there?

**Comment by myleshorton** [comment]
> Unless there's a bug of course.

I should say the fact the two match up indicates there's no bug however.
