### ISSUE TITLE
lantern can't get all contents on a page

### ISSUE THREAD

**Issue by LeoK987** [getlantern/lantern#2153]
I noticed this in various occasions.  Here I screen-captured what I saw on one page.  Note where a video is supposed to be is marked as Gateway Timeout.  Sometimes, a couple reloads get the missing contents, sometimes not.  

The page I saved is http://www.popsci.com/fast-orbiting-pulsar-no-longer-detectable-researchers

Wonder what problem it is.
![Uploading Screenshot.png . . .]()

**Comment by LeoK987** [comment]
seems my screen shot picture doesn't upload to here?

**Comment by myleshorton** [comment]
Thanks @LeoK987! If you're able to open the page with Chrome dev console open or something like that, it's possible there are some domains loaded on the site that are blocked but that we don't proxy. We can just add them to the whitelist on our end if you're able to see those. We really should just automate the process of identifying those, but we currently do not (basically it's tricky for HTTPS sites where we can't see the referer header).

I'll also try uploading a picture to this thread using Lantern to see if there's another bug there.

**Comment by myleshorton** [comment]
![image](https://cloud.githubusercontent.com/assets/1143966/5689665/bdf8b6be-981e-11e4-8698-0c4fc7c4ed4e.png)

**Comment by myleshorton** [comment]
So at least that one worked...

**Comment by LeoK987** [comment]
Thanks @myleshorton for answering.

Attached picture from GitHub web does not seem to show for some reason.
Here I attach it via email and see if it works.

**Comment by LeoK987** [comment]
![Uploading Screenshot.png . . .]()

**Comment by LeoK987** [comment]
Attaching picture here does not work for me either via email or via web.  Not sure why.

**Comment by myleshorton** [comment]
Interesting -- it could be some other blocked domain uploads happen to go
to that we're not whitelisting?

On Fri, Jan 9, 2015 at 5:03 PM, LeoK <notifications@github.com> wrote:

> Attaching picture here does not work for me either via email or via web.
> Not sure why.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2153#issuecomment-69428473>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by LeoK987** [comment]
I don't have to go through proxies to GitHub.  It might have to do with
permission issues?

**Comment by myleshorton** [comment]
We actually do have github.com on our list of sites to proxy, but maybe we should be taking it off since it's not blocked anymore.

**Comment by myleshorton** [comment]
Closing this in favor of #465
