### ISSUE TITLE
[bug] Some fallbacks failing to proxy

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2156]
See fallback-alarms Google Group.  These are old-school Java fallbacks.

**Comment by myleshorton** [comment]
Yup were also getting user reports of it running slowly - will forward.

On Saturday, January 10, 2015, oxtoacart <notifications@github.com> wrote:

> See fallback-alarms Google Group. These are old-school Java fallbacks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2156>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Spoke with @aranhoide about this, and we still need to update the alarms to check for multiple failures in a row. Right now it's a little chattier than would be ideal.
