### ISSUE TITLE
Chinese user reports "error opening media file" when trying to install Lantern after downloading it

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2159]
![error_opening_media_file](https://cloud.githubusercontent.com/assets/5000654/5707623/e2c0fffa-9a4f-11e4-82db-ecdebd56c6e3.png)

It's not immediately obvious what's reporting this error.  Could be Install4J.

**Comment by myleshorton** [comment]
@fffw can you possibly try to reproduce this or do you have any insight on this issue?

**Comment by fffw** [comment]
will try it now
2015年1月13日 上午2:14于 "myleshorton" <notifications@github.com>写道：

**Comment by myleshorton** [comment]
Closing with new installers.
