### ISSUE TITLE
[feature] Have flashlight manually pick flashlight servers instead of using roundrobin.getiantem.org

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2161]
The benefit to this is that flashlight could take servers that are unresponsive to it out of rotation, which should improve the overall flashlight experience.  We'd have to distribute the list of available flashlight servers through our cloud.yaml mechanism, which shouldn't be too hard to do.  We might even want to make cloud.yaml a dynamic endpoint somewhere.

**Comment by myleshorton** [comment]
I think the combination of the new peerscanner that takes servers out of rotation more quickly and the realization that users are targeting specific servers means we probably shouldn't do this @oxtoacart. Does that sound right?

**Comment by oxtoacart** [comment]
> I think the combination of the new peerscanner that takes servers out of rotation more quickly and the realization that users are targeting specific servers means we probably shouldn't do this @oxtoacart. Does that sound right?

The new peerscanner has lower latency than the old, but there's still latency, and I still see requests to the peers rotation failing sometimes.  Putting this in the hands of the client would help, but this is a complex and challenging change.  Our time is probably better spent on making true peer proxying a reality, so I would mark this ticket long-term.  If we eventually retire the domain-fronted peers scheme (which there are good reasons to do), then we can close this.
