### ISSUE TITLE
Whitelist ports 80, 443, 8080, and 8443 on outgoing traffic

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2162]
Applies to both flashlight and traditional servers.

**Comment by oxtoacart** [comment]
I'll take this.

**Comment by oxtoacart** [comment]
This has been deployed to all flashlight servers.

It occurs to me that we may be seeing bittorrent traffic through old-school Java fallbacks, in which case we'll need to update that code to restrict ports as well.  Let's see what kind of an impact this has an go from there.  Keeping ticket open pending empirical verification.

**Comment by myleshorton** [comment]
Sounds great thanks @oxtoacart!

On Mon, Jan 12, 2015 at 2:25 PM, oxtoacart <notifications@github.com> wrote:

> This has been deployed to all flashlight servers.
>
> It occurs to me that we may be seeing bittorrent traffic through
> old-school Java fallbacks, in which case we'll need to update that code to
> restrict ports as well. Let's see what kind of an impact this has an go
> from there. Keeping ticket open pending empirical verification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2162#issuecomment-69658825>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Well, our rate of traffic on ports other than 80, 443, 8080 and 8443 has slowed from 10 GB per hour to about 2 GB per hour.  That's a nice drop, but quite probably not enough to stop all of the DMCA take-down notices.

**Comment by myleshorton** [comment]
Wo! I thought all the traffic before was 14 GB total? Did I misunderstand
on the call? What was the 14 GB number?

On Monday, January 12, 2015, oxtoacart <notifications@github.com> wrote:

> Well, our rate of traffic on ports other than 80, 443, 8080 and 8443 has
> slowed from 10 GB per hour to about 2 GB per hour. That's a nice drop, but
> quite probably not enough to stop all of the DMCA take-down notices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2162#issuecomment-69679892>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
The number from the call was for ports 6881-6889.  The numbers I'm giving here are for all ports except 80, 443, 8080 and 8443.

```sql
SELECT _ts, SUM(counter.bytesGiven / 1024 / 1024 / 1024) AS GB_Given
FROM statshub.destport
WHERE _dim NOT IN ('total', '80', '443', '8080', '8443')
GROUP BY _ts
ORDER BY _ts DESC;
```

**Comment by oxtoacart** [comment]
It occurs to me that XMPP is on port 5222 ...

**Comment by myleshorton** [comment]
Ha! Great point. Yeah that's a problem. Sorry should have thought of that,

On Monday, January 12, 2015, oxtoacart <notifications@github.com> wrote:

> It occurs to me that XMPP is on port 5222 ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2162#issuecomment-69687590>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Pushing an update to include 5222 now.

**Comment by oxtoacart** [comment]
I've allowed port 5222.  Tested with fl-singapore-004-1, currently deploying to all other flashlight servers.

**Comment by oxtoacart** [comment]
Update for 5222 now deployed to all flashlight servers.

**Comment by myleshorton** [comment]
You're the man - thanks.

On Monday, January 12, 2015, oxtoacart <notifications@github.com> wrote:

> Update for 5222 now deployed to all flashlight servers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2162#issuecomment-69689530>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
We don't seem to be getting takedown notices anymore, so it appears to have worked.
