### ISSUE TITLE
[bug] Give mode peer not being registered

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2164]
Testing from the command-line on OS X, running from devel, I run Lantern in Give mode.  I've mapped port 443 on my firewall to port 44377 of the machine that's running Lantern.  I never see any traffic.  My peer isn't appearing in CloudFlare's DNS.

Note - this client started out running in Get mode and I switched to Give mode from the settings popup.

**Comment by oxtoacart** [comment]
I tried wiping out my lantern folder and removing the existing port mapping.  When I do that, Lantern doesn't prompt me to map the port the way that it used to.

**Comment by oxtoacart** [comment]
While looking at CloudFlare DNS, I noticed that the number of registered peers seems to fluctuate quite wildly, anywhere between half a dozen to several dozen or so.  This may not be a problem, but it looked kind of odd.  Probably worth looking into in relation to this.

**Comment by myleshorton** [comment]
Just tried this on my home network, and it's not registering because upnp is failing. upnpc from the command line is working fine but flashlight gives the following error:

Unable to map external port: Unable to map port with igdman 443: Unable to add port mapping: read udp 192.168.0.11:57965: connection refused

I'm not sure why it's trying to make a connection -- I think it might still have that logic to look up the local router and then explicitly connect to it for some reason, which isn't really necessary. You can just do upnpc -d then upnpc -a.

**Comment by oxtoacart** [comment]
But if it can't map a port, we should be displaying a warning and asking the user to map manually.  So irrespective of whether or not the mapping succeeded, if the port was manually mapped, Lantern should be registering with peerdnsreg.

**Comment by oxtoacart** [comment]
BTW, I'm pretty sure the error message you're seeing is generated from a failed attempt to map with NAT-PMP.  go-igdman will fall back to NAT-PMP if upnpc doesn't work for some reason.  You'll see INFO level log with the text "Unable to initialize UPnP IGD, falling back to NAT-PMP", and that message will give you the error from upnp.

But again, none of that explains why the client doesn't register with peerdnsreg if you've manually mapped a port.

**Comment by myleshorton** [comment]
Well so it sounds like there are multiple bugs then. One is upnp just failing (it isn't registering regardless of whether that message is from upnp or nat pmp) while the second is not registering with a manual port mapping.

**Comment by myleshorton** [comment]
And actually a third bug -- not displaying the message on port mapping failure.

**Comment by myleshorton** [comment]
So it looks like the startServer call at https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/proxy/pt/FlashlightServerManager.java#L163 never finishes, so the thread to register never starts. The culprit appears to be the infinite wait at https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/proxy/pt/BasePluggableTransport.java#L231

**Comment by myleshorton** [comment]
OK, I fixed the registration thread starting bug, which also fixed the messaging. Now it's just down to what's happening with upnp.

**Comment by myleshorton** [comment]
Wow, I don't think the peer registration has worked at all since moving NAT-PMP and UPnP into flashlight way back in August - c0984d6699725361e3b64ecc8b7e16fec9ccdcdb

**Comment by oxtoacart** [comment]
> OK, I fixed the registration thread starting bug, which also fixed the messaging. Now it's just down to what's happening with upnp.

Nice debugging!

> Wow, I don't think the peer registration has worked at all since moving NAT-PMP and UPnP into flashlight way back in August - c0984d6

Yikes!  That would explain why Give mode user numbers started dropping in August.

> Well so it sounds like there are multiple bugs then. One is upnp just failing (it isn't registering regardless of whether that message is from upnp or nat pmp) 

Did you ever find the error from upnpc?  I can't reproduce because my router won't let me map low ports.    If I run the unit test in go-igdman using a high port, upnp works for me every time.

**Comment by myleshorton** [comment]
Haven't found it no - nothing at error level in the logs. I can't try right
away but will in a sec.

On Tuesday, January 13, 2015, oxtoacart <notifications@github.com> wrote:

> OK, I fixed the registration thread starting bug, which also fixed the
> messaging. Now it's just down to what's happening with upnp.
>
> Nice debugging!
>
> Wow, I don't think the peer registration has worked at all since moving
> NAT-PMP and UPnP into flashlight way back in August - c0984d6
> <https://github.com/getlantern/lantern/commit/c0984d6699725361e3b64ecc8b7e16fec9ccdcdb>
>
> Yikes! That would explain why Give mode user numbers started dropping in
> August.
>
> Well so it sounds like there are multiple bugs then. One is upnp just
> failing (it isn't registering regardless of whether that message is from
> upnp or nat pmp)
>
> Did you ever find the error from upnpc? I can't reproduce because my
> router won't let me map low ports. If I run the unit test in go-igdman
> using a high port, upnp works for me every time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69747187>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
> https://github.com/getlantern/lantern/issues/2168

Thanks!

Found another issue while testing this - https://github.com/getlantern/lantern/issues/2168

**Comment by myleshorton** [comment]
Actually here's the error in the logs:

4146   2015-01-13 06:34:54,706 DEBUG [LoggingStreamHandler-error-false] pt.BasePluggableTransport.run (LoggingStreamHandler.java:113) - igdman: Unable to initialize UPnP IGD, falling back to NAT-PMP: Unable to call upnpc to get status: signal: trace/BPT trap

**Comment by myleshorton** [comment]
So this is what I get running the upnpc executable in go-igdman:

$ ./binaries/osx/upnpc -a 192.168.0.11 44377 443 TCP
dyld: Library not loaded: /usr/local/Cellar/miniupnpc/1.9.20141027/lib/libminiupnpc.10.dylib
  Referenced from: /Users/afisk/go/src/github.com/getlantern/go-igdman/./binaries/osx/upnpc
  Reason: image not found
zsh: trace trap  ./binaries/osx/upnpc -a 192.168.0.11 44377 443 TCP

**Comment by oxtoacart** [comment]
> $ ./binaries/osx/upnpc -a 192.168.0.11 44377 443 TCP
dyld: Library not loaded: /usr/local/Cellar/miniupnpc/1.9.20141027/lib/libminiupnpc.10.dylib
Referenced from: /Users/afisk/go/src/github.com/getlantern/go-igdman/./binaries/osx/upnpc
Reason: image not found
zsh: trace trap ./binaries/osx/upnpc -a 192.168.0.11 44377 443 TCP

Drats, looks like that upnpc is dynamically linked to something from homebrew.  Let me replace it with a statically linked version.

**Comment by oxtoacart** [comment]
@myleshorton This should take care of it - https://github.com/getlantern/flashlight-build/pull/29

Please let me know if it works for you.

**Comment by oxtoacart** [comment]
@myleshorton BTW, I confirmed that your fix to the registration issue works for me.  I started Lantern without a port mapped and got the warning message.  After manually mapping a port on my firewall, the message went away.  Eventually, I also started to see some traffic from across the world!

**Comment by myleshorton** [comment]
I have to run an errand but upnpc on that branch is working for me. For some reason setenv is failing but haven't had a chance to dig into that.

**Comment by myleshorton** [comment]
Awesome!!

On Tuesday, January 13, 2015, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> BTW, I confirmed that your
> fix to the registration issue works for me. I started Lantern without a
> port mapped and got the warning message. After manually mapping a port on
> my firewall, the message went away. Eventually, I also started to see some
> traffic from across the world!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69762657>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
> Wow, I don't think the peer registration has worked at all since moving NAT-PMP and UPnP into flashlight way back in August - c0984d6

I'm glad we figured this out. We should really be running tests with each new release to make sure this component is actually working, especially if it hasn't been working since August. If I wanted to check right now the last time a new peer entered rotation, how would I go about doing that? Is there any way to?

**Comment by myleshorton** [comment]
The big problem is that it's router-specific, so automated tests are
challenging.

On Tuesday, January 13, 2015, atavism <notifications@github.com> wrote:

> Wow, I don't think the peer registration has worked at all since moving
> NAT-PMP and UPnP into flashlight way back in August - c0984d6
> <https://github.com/getlantern/lantern/commit/c0984d6699725361e3b64ecc8b7e16fec9ccdcdb>
>
> I'm glad we figured this out. We should really be running tests with each
> new release to make sure this component is actually working, especially if
> it hasn't been working since August. If I wanted to check right now the
> last time a new peer entered rotation, how would I go about doing that? Is
> there any way to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69780688>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
> The big problem is that it's router-specific, so automated tests are
challenging.

Okay, if it's tricky to automate, maybe whenever a new release comes out, or even during a support day, one of us always registers a new give-mode user, verifies that peer enters rotation and CloudFlare's DNS, and eventually starts to receive traffic. Would that help? I don't mind taking on that responsibility and could incorporate it into my support day.

**Comment by myleshorton** [comment]
Yeah I think that should work, although you can still only manually verify
it if you're behind the right kind of router or can manually map a port.

On Tuesday, January 13, 2015, atavism <notifications@github.com> wrote:

> The big problem is that it's router-specific, so automated tests are
> challenging.
>
> Okay, if it's tricky to automate, maybe whenever a new release comes out,
> or even during a support day, one of us always registers a new give-mode
> user, verifies that peer enters rotation and CloudFlare's DNS, and
> eventually starts to receive traffic. Would that help? I don't mind taking
> on that responsibility and could incorporate it into my support day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69785092>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
> Yeah I think that should work, although you can still only manually verify
it if you're behind the right kind of router or can manually map a port.

Cool! I'll start doing that once this ticket is resolved. I manually mapped 443 to 44377 before, and it use to work. Anyway, I didn't mean to sidetrack the discussion. I just wanted to make sure we have a procedure in place in order to avoid a repeat.

**Comment by myleshorton** [comment]
No totally right on - we definitely need a better procedure. We have a QA
person starting in March, so she should be able to take it over then.

On Tuesday, January 13, 2015, atavism <notifications@github.com> wrote:

> Yeah I think that should work, although you can still only manually verify
> it if you're behind the right kind of router or can manually map a port.
>
> Cool! I'll start doing that once this ticket is resolved. I manually
> mapped 443 to 44377 before, and it use to work. Anyway, I didn't mean to
> sidetrack the discussion. I just wanted to make sure we have a procedure in
> place in order to avoid a repeat.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69788552>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
> We should really be running sanity checks with each new release to make sure this component is actually working

+1 We have a QA script that we used to use for this - https://github.com/getlantern/lantern/wiki/%5Bdevelopers%5D-QA-Scripts

I really like your idea of integrating this into support day.  If we update the existing script to cover the flashlight port-mapping stuff, that would be a pretty good smoke test.  I'm happy to start doing this on my support day irrespective of whether or not there's a new release.  If we all did it, we would get better platform coverage and more of a chance to find things like upnpc being dynamically linked to something that only I have on my system.

> If I wanted to check right now the last time a new peer entered rotation

Your best best will be the logs for cloudflare-peerdnsreg, which show stats on registered peers and fallbacks.  You can also see peers in the CloudFlare DNS settings under the A name peers.getiantem.org.  I recently witnessed some peers in here, so some peers have definitely been online, but likely only older clients.

**Comment by myleshorton** [comment]
Yeah I think support day makes sense except again for the fact that it's
only possible behind certain routers. As long as you can test with a
compatible router on support day, then by all means.

On Tuesday, January 13, 2015, oxtoacart <notifications@github.com> wrote:

> We should really be running sanity checks with each new release to make
> sure this component is actually working
>
> +1 We have a QA script that we used to use for this -
> https://github.com/getlantern/lantern/wiki/%5Bdevelopers%5D-QA-Scripts
>
> I really like your idea of integrating this into support day. If we update
> the existing script to cover the flashlight port-mapping stuff, that would
> be a pretty good smoke test. I'm happy to start doing this on my support
> day irrespective of whether or not there's a new release. If we all did it,
> we would get better platform coverage and more of a chance to find things
> like upnpc being dynamically linked to something that only I have on my
> system.
>
> If I wanted to check right now the last time a new peer entered rotation
>
> Your best best will be the logs for cloudflare-peerdnsreg, which show
> stats on registered peers and fallbacks. You can also see peers in the
> CloudFlare DNS settings under the A name peers.getiantem.org. I recently
> witnessed some peers in here, so some peers have definitely been online,
> but likely only older clients.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69793156>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton Updated flashlight build has been committed to Lantern master.  Smoke testing showed that I was able to get give mode traffic on OS X.

**Comment by myleshorton** [comment]
Sweet thanks!

On Wed, Jan 14, 2015 at 9:19 AM, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Updated flashlight build
> has been committed to Lantern master. Smoke testing showed that I was able
> to get give mode traffic on OS X.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2164#issuecomment-69953349>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Closed with https://github.com/getlantern/lantern/pull/2170
