### ISSUE TITLE
[flashlight/enproxy] User agent hangs when enproxy encounters a Bad Gateway response

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2165]
After implementing #2162, try the following:

`curl -x localhost:10080 https://www.google.com:444/humans.txt`

You'll see enproxy report an error like the following:

`enproxy: Dest: www.google.com:444    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway`

But curl just hangs.

**Comment by myleshorton** [comment]
This is done correct @oxtoacart?

**Comment by oxtoacart** [comment]
Yes, done.
