### ISSUE TITLE
Add press section to web site

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2166]
@fffw it would be great if you could tackle this one to get up to speed on the Lantern site. You can probably do this before the Go system tray port. This will get fleshed out with more information soon!

**Comment by carsonefv** [comment]
Here's the info for the Press Section that needs to be added to the site:

I've attached the final site design (see in e-mail, psd file type not supported on github) with the new press section, and all of the press logo images below

Also, here are the sites that each of the logos should link to:

Tech President: (we actually have two articles we could link to, but maybe we should just use the first one?)
http://techpresident.com/news/wegov/24444/state-department-funded-lantern-next-bigger-better-tor

http://techpresident.com/news/wegov/24455/why-remarkably-similar-circumvention-tools-uproxy-and-lantern-are-not-overkill

South China Morning Post:
http://www.scmp.com/news/china-insider/article/1372661/use-lantern-software-means-view-banned-websites-grows-china

The Washington Post:
http://www.washingtonpost.com/blogs/the-switch/wp/2014/08/21/using-peer-to-peer-technology-to-crowdsource-a-way-around-online-censorship/

Gigaom:
https://gigaom.com/2014/08/14/anti-censorship-app-lantern-wants-to-become-the-setihome-of-free-speech/

The Daily Dot:
http://www.dailydot.com/politics/lantern-online-censorship/

Le Monde:
http://www.lemonde.fr/pixels/article/2014/08/21/lantern-le-logiciel-qui-veut-eradiquer-la-censure-d-internet_4473868_4408996.html

Additionally, the text "South China Morning Post" underneath the quote should also link to the corresponding article: http://www.scmp.com/news/china-insider/article/1372661/use-lantern-software-means-view-banned-websites-grows-china

(See site design PSD in e-mail)

![gigaom](https://cloud.githubusercontent.com/assets/4400763/5713677/c48e5888-9a8c-11e4-92c5-f1662a0f1f8e.png)
![lemonde](https://cloud.githubusercontent.com/assets/4400763/5713680/c48f4766-9a8c-11e4-974c-ee3c6b5ba1fb.png)
![southchinamorningpost](https://cloud.githubusercontent.com/assets/4400763/5713681/c49072e4-9a8c-11e4-989f-7be5ed5e3137.png)
![techpresidentlogo](https://cloud.githubusercontent.com/assets/4400763/5713678/c48ef428-9a8c-11e4-9d88-4d8e8d3db71d.png)
![thedailydot](https://cloud.githubusercontent.com/assets/4400763/5713679/c48f3e42-9a8c-11e4-9941-b5f088945ff8.png)
![thewashingtonpost](https://cloud.githubusercontent.com/assets/4400763/5713682/c491716c-9a8c-11e4-9888-992ff4a9d6b8.png)

**Comment by myleshorton** [comment]
Thanks @carsonefv! @fffw the site is all at https://github.com/getlantern/www.getlantern.org/ -- I'll make sure you're added as a collaborator, and please let us know if you have any issues!

**Comment by myleshorton** [comment]
Closing!
