### ISSUE TITLE
You need to install the legacy Java SE 6 runtime

### ISSUE THREAD

**Issue by Hongbo-Miao** [getlantern/lantern#2171]
Every time use it, it shows: To open "Lantern Installer" you need to install the legacy Java SE 6 runtime. Please include old Java into it or support Java 8. Thanks!

**Comment by myleshorton** [comment]
Thanks @Hongbo-Miao that's a very annoying issue. What operating system are you using? It downloads and installs every single time correct? We're in the process of porting things to Go, which will obviate for this, but we'd love to fix it if possible.

**Comment by Hongbo-Miao** [comment]
I use OS X 10.10.1 before and now 10.10.2. SPSS 22 also needs Java SE 6. So at last I installed http://support.apple.com/kb/DL1572. It works then.
So now my system have both Java 6 (from Apple) and 8 (from Oracle).

**Comment by myleshorton** [comment]
OK thanks @Hongbo-Miao. So now Lantern doesn't force you to re-install every time you run it right?

**Comment by Hongbo-Miao** [comment]
Yeah, after installing old Java SE 6 from Apple, it works. @myleshorton
