### ISSUE TITLE
[www] Integrate Stripe Checkout to process donations

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2172]

**Comment by atavism** [comment]
Details here on specifying a variable amount: https://support.stripe.com/questions/how-can-i-use-a-variable-amount-with-stripe-checkout

**Comment by atavism** [comment]
@myleshorton and @oxtoacart, we could use Stripe Checkout to handle recurring donations and classify it a subscription service that comprises adopting a server in your name (essentially the same as https://github.com/getlantern/lantern/issues/2061). This would appeal to people that don't want to or are unable to run Lantern in give-mode themselves. To keep contributors engaged, we could send monthly reports about how much traffic was handled + the number of get-mode requests the server processed or whatever other stats we wanted to include. As mentioned, this seems like a great way to balance the give-mode side until we get the P2P functionality deployed.

**Comment by myleshorton** [comment]
Discussed with @chipstehr and realized there are a bunch of non-technical components to this like sending thank you letter to donors, tex deductible issues (reporting to the IRS), etc. So I think we need to push this out a bit unfortunately.

**Comment by myleshorton** [comment]
This could also work for the Lantern Pi.
