### ISSUE TITLE
[feature] Fetch AutoProxy list periodically and convert to pac file

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2177]
```sh
wget https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt
openssl base64  -d -in gfwlist.txt -out list.txt
```

This involves both configuration service and clients in get access mode.

**Comment by fffw** [comment]
Oh there's already a [neat tool exists](https://github.com/clowwindy/gfwlist2pac).
Just
```sh
pip install gfwlist2pac
wget https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt
gfwlist2pac -i gfwlist.txt -f lantern.pac -p localhost:8787
```

**Comment by myleshorton** [comment]
Very cool!!

On Monday, January 19, 2015, fffw <notifications@github.com> wrote:

> Oh there's already a neat tool exists
> <https://github.com/clowwindy/gfwlist2pac>.
> Just
>
> pip install gfwlist2pac
> wget https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt
> gfwlist2pac -i gfwlist.txt -f lantern.pac -p localhost:8787
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2177#issuecomment-70597803>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@fffw Are you thinking of doing this on a server and then distributing the list to the Lantern client, or were you thinking of having the client download the gfw list directly?  I only ask because we don't want to make Python a prerequisite for running Lantern.

**Comment by fffw** [comment]
@oxtoacart I prefer place the baked list on Amazon S3 and update it periodically, or, provide a simple service to return the list as per client ip address. Client can get the list and merge it with custom rules.

Through this, we can adjust the process without distributing new version, and avoid disruption caused by 3rd party.

**Comment by oxtoacart** [comment]
@fffw 

> I prefer place the baked list on Amazon S3 and update it periodically, or, provide a simple service to return the list as per client ip address. Client can get the list and merge it with custom rules.

> Through this, we can adjust the process without distributing new version, and avoid disruption caused by 3rd party.

That sounds great.

**Comment by myleshorton** [comment]
One easy approach would be to integrate this into the install script -- basically just fetch the updated AutoProxy list and post it on each new install.

**Comment by oxtoacart** [comment]
@myleshorton 

> One easy approach would be to integrate this into the install script -- basically just fetch the updated AutoProxy list and post it on each new install.

How about we bake the list into the binary and provide updates via cloud.yaml, the way that we already do with masquerades?

**Comment by myleshorton** [comment]
> How about we bake the list into the binary and provide updates via cloud.yaml, the way that we already do with masquerades?

I think the only problem is that it's country-specific. We could include separate country sections in there, however, as long as the whole file doesn't get insanely large.

**Comment by oxtoacart** [comment]
> I think the only problem is that it's country-specific. We could include separate country sections in there, however, as long as the whole file doesn't get insanely large.

This is a good use for a bitmap index.  We just create a matrix cross-referencing countries and sites that are on the whitelist in those countries.

**Comment by oxtoacart** [comment]
A bitmap index like the whitelist would likely lend itself well to compression, perhaps using something like this - http://zhen.org/blog/bitmap-compression-using-ewah-in-go/

**Comment by myleshorton** [comment]
Yeah cool idea!

On Wed, Jan 28, 2015 at 2:14 PM, oxtoacart <notifications@github.com> wrote:

> A bitmap index like the whitelist would likely lend itself well to
> compression, perhaps using something like this -
> http://zhen.org/blog/bitmap-compression-using-ewah-in-go/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2177#issuecomment-71927943>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Here's another compressed bitmap implementation: https://github.com/fzandona/goroar

**Comment by fffw** [comment]
Should we maintain one whitelist or two (system and custom) in client? What if customer removed one domain which happens in our baked list, if we have only single whitelist?

**Comment by oxtoacart** [comment]
> Should we maintain one whitelist or two (system and custom) in client? What if customer removed one domain which happens in our baked list, if we have only single whitelist?

The way we handle it today is that we publish additions to the whitelist as individual deltas.  These deltas are applied in addition to whatever the user has already customized, which allows us to respect anything that the user may have removed from the whitelist.

Here is the current Java code for managing that - 
https://github.com/getlantern/lantern/blob/b0cb5ba4b898c5b4c50d693b8e1811edbcd3cc0b/src/main/java/org/lantern/Whitelist.java

**Comment by atavism** [comment]
@fffw I opened a ticket to port the whitelist functionality to Go [here](https://github.com/getlantern/lantern/issues/2195) so feel free to add any relevant conversation there. Depending on the status of https://github.com/getlantern/lantern/issues/1902, we can obviously pair on it, but I was planning to do the initial implementation.

**Comment by louy2** [comment]
Kinda wondering which lists this feature is fetching, since I met a site not recognized today. The kinda commonly recognized GFW whitelist is this one: https://github.com/gfwlist/gfwlist

**Comment by fffw** [comment]
@louy2 We don't sync with any list now and reply on auto detection instead. Did you see a blocked site that Lantern failed to detect? Please post details here if you think it's worth inspection. Gonna close this case but feel free to comment!

**Comment by louy2** [comment]
I guess auto detection just jumps from time to time. It works now. Thank you!
