### ISSUE TITLE
[flashlight] Seeing occasional errors when proxying through fallbacks

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2179]
We see errors in the client's log like this:

```
enproxy: Dest: www.google.com:80    ProxyHost:     Unable to issue write request: Bad response status for read: 521 Origin Down
```

Ideally peerscanner should find out about downed fallbacks before CloudFlare does and update DNS accordingly.

**Comment by oxtoacart** [comment]
We're now running the new peerscanner that takes fallbacks out of rotation, and so far I'm not seeing this error anymore.

**Comment by myleshorton** [comment]
Should we close it?

**Comment by oxtoacart** [comment]
This is no longer happening for me with the peerscanner that's deployed, but let's keep the ticket open until we've actually done the PR - https://github.com/getlantern/flashlight-build/pull/34

**Comment by oxtoacart** [comment]
This problem seems to be resolved in the field, closing.
