### ISSUE TITLE
[flashlight] May be triggering CloudFlare DDOS protection

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2185]
I've been browsing with flashlight a lot recently.  After I turn off proxying, I've noticed that I'm occasionally getting CloudFlare's DDOS protection page when I browse to CloudFlare hosted resources.

![screen shot 2015-01-23 at 9 36 42 am](https://cloud.githubusercontent.com/assets/5000654/5877204/921e2824-a2e3-11e4-8a26-7fa03660b226.png)

It's not clear to me what exactly the impact of this is to flashlight, but it's probably not good.

**Comment by oxtoacart** [comment]
I tried turning off DDOS protection for getiantem.org in case that might help, but I can't :(

![screen shot 2015-01-23 at 9 40 28 am](https://cloud.githubusercontent.com/assets/5000654/5877259/ef56fe6c-a2e3-11e4-8b52-d151e8761e6e.png)

**Comment by oxtoacart** [comment]
One quick thing to try is turning off connection pooling.  CloudFlare may see us opening a bunch of connections that we then don't use, and see that as a red flag.

**Comment by oxtoacart** [comment]
I'm going to try running with a flashlight that doesn't pool and see how that goes.

**Comment by oxtoacart** [comment]
So far, running without connection pooling is working fine.  Perhaps conn pooling was a premature optimization :)

**Comment by oxtoacart** [comment]
BTW, I think the main reason I noticed this is that I left flashlight on overnight.  We should probably incorporate that in our tests.

**Comment by myleshorton** [comment]
Interesting, so it was continuously maintaining the pool all night long is
that right? I'd be cool with stripping the pooling out I think.

On Fri, Jan 23, 2015 at 11:13 AM, oxtoacart <notifications@github.com>
wrote:

> BTW, I think the main reason I noticed this is that I left flashlight on
> overnight. We should probably incorporate that in our tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2185#issuecomment-71247769>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
So, I ran for several hours with pooling turned off, then checked in a browser that wasn't configured to proxy, and I still get the CloudFlare DDOS protection page when accessing highcharts.com.

**Comment by oxtoacart** [comment]
Well, embarrassingly, due to a bug in fronted, I was never actually running with connection pooling enabled.

**Comment by myleshorton** [comment]
Well hey that simplifies things at least! Forgot to mention that a user on
FB reported the same issue with hitting that CloudFlare page.

On Friday, January 23, 2015, oxtoacart <notifications@github.com> wrote:

> Well, embarrassingly, due to a bug in fronted, I was never actually
> running with connection pooling enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2185#issuecomment-71293760>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
I believe the same guy who was running flashlight.exe directly from a bat
file!

On Friday, January 23, 2015, Adam Fisk <afisk@getlantern.org> wrote:

> Well hey that simplifies things at least! Forgot to mention that a user on
> FB reported the same issue with hitting that CloudFlare page.
>
> On Friday, January 23, 2015, oxtoacart <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Well, embarrassingly, due to a bug in fronted, I was never actually
>> running with connection pooling enabled.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/getlantern/lantern/issues/2185#issuecomment-71293760>
>> .
>>
>
>
> --
> --
> President
> Brave New Software Project, Inc.
> https://www.getlantern.org
> pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton I just checked out the page that this user was trying to access (symbianize.com).  When accessing it through flashlight, I see the DDOS protection go into a redirect loop.  That is, it shows the DDOS screen, then redirects, then shows the DDOS screen.  So whatever CloudFlare is doing to detect "real" browsers doesn't seem to work when running through flashlight.  Probably related to the fact that your proxy changes from one request to the next.

When I visit symbianize.com through an unproxied browser, I get the DDOS screen but after the redirect it works.

**Comment by oxtoacart** [comment]
If I set up flashlight to use only a single server, then I'm able to get past the DDOS protection screen on symbianize.

**Comment by oxtoacart** [comment]
One potential thing that could help is using more of our masquerade hosts.

**Comment by myleshorton** [comment]
Interesting @oxtoacart thanks great snooping. Why would using more masquerade hosts potentially help?

**Comment by oxtoacart** [comment]
Using more masquerade hosts might help prevent the client's computer from being flagged as DDOSing if CloudFlare is measuring the frequency of access by entry IP.  If they do it by host, that won't help since we're sending everything to our set of hosts.  It's really just a long shot.
