### ISSUE TITLE
[lantern] On OS X, the Lantern Menu Bar (a.k.a. System Tray) icon is not always visible

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2191]
If the menu bar is too full of other stuff, the Lantern icon may not appear:

![screen shot 2015-01-26 at 9 50 10 am](https://cloud.githubusercontent.com/assets/5000654/5902559/08f31ac2-a541-11e4-8653-df368a8c073a.png)

![screen shot 2015-01-26 at 9 50 20 am](https://cloud.githubusercontent.com/assets/5000654/5902561/0aa4e666-a541-11e4-8923-9185b61b8592.png)

It occurs to me that the menu bar icon only has two functions right now, show Lantern and quit Lantern.  This could potentially also be accomplished through a dock icon, perhaps using something like this - https://gowalker.org/github.com/cratonica/trayhost.

@fffw @myleshorton I know that you all are looking at system tray stuff right now, so I thought you might find this interesting.

**Comment by myleshorton** [comment]
This must just be a general issue with the menu bar that's not Lantern-specific right? Similar to how the system tray hides some of your tray items.

Does it still not become visible, or have an option to scroll to invisible ones, if you mouse over?

**Comment by oxtoacart** [comment]
> This must just be a general issue with the menu bar that's not Lantern-specific right? Similar to how the system tray hides some of your tray items.

Yes, it's not Lantern-specific.  However, since we don't offer any other way to get back into the application, I can see this generating confusion/questions.

> Does it still not become visible, or have an option to scroll to invisible ones, if you mouse over?

Not as far as I can tell, no.

**Comment by fffw** [comment]
I did checked trayhost before, and felt a little bit weird when seeing a dock icon without an application window.

A possible workaround would be to open the "Show Lantern" window when we launch the application again.

**Comment by oxtoacart** [comment]
> I did checked trayhost before, and felt a little bit weird when seeing a dock icon without an application window.

I agree.

**Comment by myleshorton** [comment]
Putting in long term since the solution would take a lot of thought, the number of users affected is likely pretty low, and other apps that use the menu bar don't implement other solutions that we know of (if it's good enough for DropBox it's probably good enough for us at this point!).

**Comment by oxtoacart** [comment]
> Putting in long term

Agreed

> if it's good enough for DropBox

Cool that you mentioned DropBox.  I like their UI, in particular how clicking on the menu bar icon shows a little summary window with the most important information (rather than just a drop-down menu) and how the settings button brings up a streamlined native window for adjusting settings.  We could probably learn something from the UX.

**Comment by myleshorton** [comment]
> Cool that you mentioned DropBox. I like their UI, in particular how clicking on the menu bar icon shows a little summary window with the most important information (rather than just a drop-down menu) and how the settings button brings up a streamlined native window for adjusting settings. We could probably learn something from the UX.

Yeah totally -- it's pretty slick. Would be nice to beef up the UI there in general, which hopefully some of @fffw's changes will help with!
