### ISSUE TITLE
Allow Lantern to bind to 0.0.0.0 instead of localhost 

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2192]
This would allow it to be used as a proxy server, for example. We have the functionality on devel, but it's not exposed to the user as a configuration option.

**Comment by oxtoacart** [comment]
@myleshorton What's the use case here?

**Comment by myleshorton** [comment]
A user brought this up awhile ago on the forums, but let's say you run a small business, for example, and want the whole company to be able to access blocked sites. Just set up a proxy server running Lantern and have the whole company auto-configured to go through that. Then you don't have to install Lantern on each machine. That's what the user's suggestion was.

**Comment by oxtoacart** [comment]
> A user brought this up awhile ago on the forums, but let's say you run a small business, for example, and want the whole company to be able to access blocked sites. Just set up a proxy server running Lantern and have the whole company auto-configured to go through that. Then you don't have to install Lantern on each machine. That's what the user's suggestion was.

I like it a lot!  For that matter, I could see people using it to run an open proxy for friends/family/etc.

This does raise the question of easing the distinction between Give and Get mode for me again.  We don't have to answer that question in order to implement this change, but it's one more thing that chips away at the distinction.  Something to keep in mind for whenever we redesign the UI.

**Comment by myleshorton** [comment]
Oh interesting. I was only thinking of it only for get mode, but you're saying any company with a proxy server might want to run Lantern instead and to also supply access, is that right?

**Comment by oxtoacart** [comment]
I was actually thinking more of individuals or groups in censored countries providing access for friends and family.  So just like I might want to run Lantern for everyone on my LAN, perhaps I also want to run Lantern as an open proxy for my friends.  That would actually be a quick and easy way to "support" mobile users, who would just need to configure their proxy settings to point to my Lantern.

More generally, at the level of language, I was just making the observation that "Give" and "Get" are not fully descriptive of the ways in which one might want to use Lantern and that in a future redesign, we may want to frame things in different terms.

**Comment by Youmoo** [comment]
Is this feature implemented yet? Can I set the bind ip from an external config file or from command line args?

**Comment by oxtoacart** [comment]
@Youmoo You can set the address from the command line using the `-addr` flag, like `-addr 0.0.0.0:8787`.  This ticket is for exposing this through the UI.

**Comment by Youmoo** [comment]
@oxtoacart Thanks.

**Comment by rxpsd3** [comment]
Hello! Is there any way to set up gateway and DNS to instead Port which devices do not have proxy option?
