### ISSUE TITLE
Port whitelist functionality to Go

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2195]

**Comment by atavism** [comment]
I still need to merge my changes with flashlight-build and add unit test coverage, but this is mostly working. 

To try it out:
```
- checkout the issue-2195 branch
- go get
- ./genassets.bash
- ./go-lantern
```
The UI should automatically open. Once you open the whitelist screen, the textarea will appear populated with your current list of proxied sites found in ~/.lantern/proxy_on.pac. By clicking "Continue", your whitelist will be updated and a new PAC file will be generated. "Reset" restores the "original.txt" list. I also added a new "Cancel" button to close the modal. Note: I also need to fix the search input so ignore that for now.

**Comment by oxtoacart** [comment]
I tried checking this out, but the submodule update gives me an error:

```bash
fatal: reference is not a tree: 06a7d3b2131362ccd96f538ddc63c08f4f0c0f1d
Unable to checkout '06a7d3b2131362ccd96f538ddc63c08f4f0c0f1d' in submodule path 'ui'
```

**Comment by oxtoacart** [comment]
@atavism When you integrate this into flashlight-build, can you please:

1. Store the whitelist information in the YAML configuration (flashlight.yaml)

2. Drive the whitelist from the configuration (e.g. follow the pattern established in existing packages like client, server, etc.)?  That way, we'll be able to modify the whitelist from the YAML just as we can modify other configuration.

3. Please also make the listen port for the HTTP server configuration, and maybe set up an independent http.Server rather than using the default one (since flashlight has some other HTTP servers and this'll make it clear that they're separate).

Thanks!

**Comment by atavism** [comment]
> I tried checking this out, but the submodule update gives me an error:
Not sure what's causing that. Can you try

```
git submodule foreach git fetch
git submodule update
```

Regarding all three of your points, that's the plan. I'm currently using original.txt (which contains the concatenated whitelists found in the lantern resources folder), but I planned to move that into flashlight.yaml next. I'll put the http server configuration in a next section in the config as well.

**Comment by atavism** [comment]
Also, I just tested everything out running a flashlight client and with pacon partially integrated. It's working great! When you modify your whitelist, that immediately updates your PAC file, but those changes aren't automatically detected by the browser so we'll have to toggle proxying on and off. Not a big deal though.

**Comment by oxtoacart** [comment]
@atavism 

Thanks, I'm past the submodule stuff.  After running ./genassets.bash and then go get && go build, I get the below:

```
➜  go-lantern git:(issue-2195) ✗ go get && go build
# github.com/getlantern/go-lantern
./bindata_assetfs.go:9: imported and not used: "strings"
./bindata_assetfs.go:12: imported and not used: "io/ioutil"
./bindata_assetfs.go:13: imported and not used: "path"
./bindata_assetfs.go:14: imported and not used: "path/filepath"
./bindata_assetfs.go:67: undefined: _bintree
./bindata_assetfs.go:68: undefined: Asset
./bindata_assetfs.go:68: undefined: AssetDir
```

bindata_assetfs.go is curiously empty - I would have expected it to have the UI resources(?).

**Comment by oxtoacart** [comment]
BTW, I forgot one other request for integrating into flashlight.  Can you please use a subtree for lantern-ui rather than a submodule?

**Comment by atavism** [comment]
Yeah that file shouldn't be empty. genassets.bash executes go-bindata-assetfs ui/app/...   - is that directory empty for you for some reason?

**Comment by atavism** [comment]
Yeah, I plan to make the ui a subtree instead of a submodule.

**Comment by oxtoacart** [comment]
ui/app is populated.

**Comment by oxtoacart** [comment]
Is `github.com/elazarl/go-bindata-assetfs` the right one to use?

**Comment by oxtoacart** [comment]
Oddly if I run go-bindata-assetfs ui, that generates some content in the bindata_assetfs.go file.

**Comment by oxtoacart** [comment]
Also, if I run `go-bindata ui/app/...`, that seems to work.  So I bet this is a bug in go-bindata-assetfs.

**Comment by oxtoacart** [comment]
It looks like go-bindata-assetfs is choking on ui/app/_css/app.css, which is larger than what bufio.Scanner seems to be able to handle.  Looking into it.

**Comment by atavism** [comment]
Yep, that's the version I'm using and the latest release. Weird you're having issues: I didn't run into a similar problem at all. I'm not at my computer at the moment--maybe it has to do with the version of Go I compiled with? Might have been using 1.3.

**Comment by oxtoacart** [comment]
Okay, I fixed the bug in go-bindata-assetfs in a fork of ours, and pull requested it:

https://github.com/elazarl/go-bindata-assetfs/pull/5

**Comment by oxtoacart** [comment]
@atavism A really cool feature would be being able to run using the local ui folder if available and only using the embedded assets for the production deployment.  That would help at development time by allowing us to modify resources without having to re-embed and restart.

**Comment by oxtoacart** [comment]
> Might have been using 1.3.

I'm using 1.4.  That could account for the difference.

**Comment by atavism** [comment]
Awesome, thanks for fixing that? Definitely agree about we should only embed the ui with production deployments! I'll add that to my TODO list.

**Comment by atavism** [comment]
thanks for fixing that!*

**Comment by atavism** [comment]
@oxtoacart I updated genconfig to include the original.txt whitelist in cloud.yaml http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz That gets coalesced with the client config when flashlight starts.

**Comment by oxtoacart** [comment]
Great!  Looking forward to code reviewing your changes.  Are you close to submitting a PR?

**Comment by atavism** [comment]
@oxtoacart Yeah, definitely. I'm still working on the unit testing (there's additional cases now that the whitelist is generated from the YAML configs, plus user customizations, and how those changes propagate to the PAC file, etc.). Should have it wrapped up shortly though.

**Comment by oxtoacart** [comment]
Awesome!  If you want, you can go ahead an integrate [tarfs](https://github.com/getlantern/tarfs) now.  I'm done with documentation/unit testing.

**Comment by myleshorton** [comment]
Hey @atavism actually let's just use this better whitelist that already uses our same format:

https://raw.githubusercontent.com/yinghuocho/firefly-blacklist/master/firefly-blacklist.txt

It's from Firefly, built by @yinghuocho and David Fifield. Let's just make sure the new one is a superset of ours and it, as the firefly list might not include some iranian sites.

That work?

**Comment by oxtoacart** [comment]
@myleshorton So are we preferring this new list over the autoproxy list mentioned in #2177

**Comment by myleshorton** [comment]
Not necessarily for all time, but for now the firefly list includes the autoproxy list and more, so it's more comprehensive and we might as well just use it. I think there's a larger task of figuring out how to keep that list up to date, making it country-specific, etc.

**Comment by oxtoacart** [comment]
Ahh, that's cool that it includes the autoproxy list.

I eyeballed the list and noticed quite a few sites under the .ir TLD on there.  Are those Iranian sites that are blocked in China?  Do we want them on the whitelist for Iranian users?  In fact, do we want to use a China-centric whitelist at all for this Iran-focused release?

**Comment by myleshorton** [comment]
Not sure about the .ir sites, but it just seems like if we're in the process of re-integrating a new whitelist we might as well take a moment to just integrate a better one.

**Comment by oxtoacart** [comment]
I dig it, I'm just asking some questions to make sure that it really is a "better" one.

**Comment by myleshorton** [comment]
Cool. Yeah, it's basically just much more actively maintained than our list, which we really update very rarely partly because we don't have a lot of insight into what's blocked.

**Comment by oxtoacart** [comment]
I understand.  So are you saying you're comfortable with those .ir sites being on the whitelist, even though some may potentially not need to be?

**Comment by myleshorton** [comment]
Yeah I think that's fine. If they're blocked in China, they're useful to have on their. If they're not blocked in Iran, it's not a huge loss. Your concern is that the .ir TLDs are less likely to blocked in Iran, is that right?

**Comment by oxtoacart** [comment]
Yeah, the likely scenario is that they're not blocked in Iran and we're needlessly slowing down access to them by forcing them through the proxy.  A worse scenario is that they're actually localized and may actually display differently because they're being accessed from foreign proxies.  The worst case scenario is that they're region-locked (think Hulu in America) and won't work at all because we're forcing them through our proxies.  In any scenario, we're degrading the user experience at least a little, and in the worst case scenario we're destroying it.

Ultimately, that's a problem inherent to managing a global whitelist without country-binding.  It's one that our own whitelist may have mitigated by virtue of us not adding Iranian sites and that may be exposed if we bring in a whitelist that wasn't managed similarly.

BTW - I did just check to confirm that our whitelist doesn't have any .ir sites on it.

For now, I would suggest that we merge the firefly list into our own and remove all .ir sites.

**Comment by myleshorton** [comment]
> A worse scenario is that they're actually localized and may actually display differently because they're being accessed from foreign proxies. The worst case scenario is that they're region-locked (think Hulu in America) and won't work at all because we're forcing them through our proxies.

I think those two are pretty unlikely, but certainly theoretically possible.

> For now, I would suggest that we merge the firefly list into our own and remove all .ir sites.

Sounds fine to me!

**Comment by atavism** [comment]
@myleshorton Sure, that's fine. I'm storing our default list of sites in cloud.yaml now so I'll just update genconfig to combine multiple *.txt files from a whitelist diectory into a single list. I'll also remove the *.ir sites from firefly-blacklist.txt before I commit it.

**Comment by myleshorton** [comment]
Nice!

On Wed, Feb 11, 2015 at 12:29 PM, atavism <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Sure, that's fine. I'm
> storing our default list of sites in cloud.yaml now so I'll just update
> genconfig to combine multiple *.txt files from a whitelist diectory into a
> single list. I'll also remove the *.ir sites from firefly-blacklist.txt
> before I commit it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2195#issuecomment-73958281>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
@oxtoacart I kept encountering an issue fetching cloud.yaml where the same set of domains were being appended to the whitelist array in flashlight.yaml. It looks like you ran into the same issue with the domain-fronted server list (in updateFrom() in flashlight/config/config.go). I think I'll just write a helper function to avoid replicating the same dedup logic?

**Comment by oxtoacart** [comment]
If you'd like.  Keep in mind that the logic will have to be different.  We overwrite the whole list of fronted servers with whatever comes from the cloud.yaml.  In the case of the whitelist, we actually need to respect whatever changes the user has made.  We came up with a scheme for this in the old Lantern, which you can see in [Whitelist.java](https://github.com/getlantern/lantern/blob/b0cb5ba4b898c5b4c50d693b8e1811edbcd3cc0b/src/main/java/org/lantern/Whitelist.java) and the accompanying [test](https://github.com/getlantern/lantern/blob/392431a144e64a785eb9556f07a6f4a245c17321/src/test/java/org/lantern/WhitelistTest.java).  The main requirement is not to add something that the user has already removed.

**Comment by oxtoacart** [comment]
BTW, there was some potentially relevant discussion on #2177.

**Comment by atavism** [comment]
@oxtoacart Yes, I'm already applying whatever customizations to the whitelist before it gets returned to the user. I store revisions in a separate array and merge the two sets. I'm just talking about synchronizing the global set of whitelisted domains. Whatever modifications the user makes, we still want that global set to always be available in the config, no? (In case the user wants to reset to the default list at any time).

**Comment by oxtoacart** [comment]
That's right!

**Comment by oxtoacart** [comment]
I'm not saying we do this now, but one simple thing we could do short of maintaining country-specific whitelists would be to maintain a mapping of countries to TLD and exclude domains from the whitelist whose TLD corresponds to country in which we're running.  So basically just a runtime automated version of what @atavism is doing.

**Comment by atavism** [comment]
@myleshorton I'm storing firefly-blacklist.txt now: https://github.com/getlantern/flashlight-build/blob/issue-2195/src/github.com/getlantern/flashlight/genconfig/cloud.yaml
The compressed version is ~ 52KB: http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz

**Comment by atavism** [comment]
Hey @oxtoacart, quick question: what's the best way to update a section of the yaml config on disk? I know I can start an HTTP config server to push updates, but I'm assuming there's an easier way. This is right before the customizations propagate to the PAC file. I ended up writing another function in config/config.go for this:
```go
func UpdateOnDisk(updated *Config) {
	updated.SetVersion(updated.GetVersion() + 1)

	b, err := yaml.Marshal(updated)
	if err != nil {
		log.Errorf("Unable to marshal updated to yaml: %s", err)
	}

	err = ioutil.WriteFile("flashlight.yaml", b, 0644)
	if err != nil {
		log.Errorf("Unable to save updated config: %s", err)
	}
}
```

**Comment by oxtoacart** [comment]
yamlconf already has an API for making updates, and in fact all updates need to be made through that API - http://godoc.org/github.com/getlantern/yamlconf#Manager.Update

The documentation for type Manager explains in more detail - http://godoc.org/github.com/getlantern/yamlconf#Manager

**Comment by atavism** [comment]
Ah, gotcha. I'm passing a mutator to the manager Update function now. Thanks!

**Comment by atavism** [comment]
When I go to create a PR with the whitelist changes, every subtree gets included in the diff. Would creating a separate PR that contains most subtree changes (mainly the UI) and merging that to master first be a sufficient workaround?

**Comment by oxtoacart** [comment]
Let's try it as-is. If it's too much of a pain to review, I'll ask you to do a separate PR for the subtree changes.  Thanks!

**Comment by atavism** [comment]
@oxtoacart Okay, cool. I'll actually list the relevant files in the PR comment to make it easier for you to find them too. It looks like "git subtree merge-squash" lets me condense a subtree commit history as well. BTW, do we actually need packages like freetype-go underneath src?

**Comment by oxtoacart** [comment]
I'm guessing something that we import depends on it.  Can you grep for it?  If it's a transitive dependency, we want to vendor it for stability.

**Comment by oxtoacart** [comment]
@myleshorton @atavism The UI for this is unusably slow with our full 7000+ proxied sites list.  Unless we're sure that we can get that part of it working today, I say we remove the button from the UI for now.

**Comment by myleshorton** [comment]
Sounds good.

On Friday, February 20, 2015, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> @atavism
> <https://github.com/atavism> The UI for this is unusably slow with our
> full 7000+ proxied sites list. Unless we're sure that we can get that part
> of it working today, I say we remove the button from the UI for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2195#issuecomment-75251455>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Nice work @atavism!
