### ISSUE TITLE
[lantern-ui] Something is making synchronous XMLHttpRequests on the main thread

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2200]
I see this warning from jQuery sometimes: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

It's not immediately clear to me what's doing this, but it could cause performance issues for sure.

**Comment by atavism** [comment]
I'd never seen that error before today, but I found out where it's originating from: [app/js/version.js](https://github.com/getlantern/lantern-ui/blob/master/app/js/version.js). I removed that code and moved it to the app run block in app.js -- it should no longer be an issue now.

**Comment by myleshorton** [comment]
This is all set @atavism correct?

**Comment by atavism** [comment]
Yeah, we can close this.
