### ISSUE TITLE
[bug] Caught exception using masqueradeHost

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2201]
This has been appearing a lot in Loggly recently. It's the top error for the past two days. Here's the full message:

```
Caught exception using masqueradeHost https://megafilmeshd.net:443, could mean that it's blocked: Connection to https://megafilmeshd.net:443 refused
```

I assume we just want to remove this masquerade host. Note: https://megafilmeshd.net is unreachable.

**Comment by myleshorton** [comment]
@xiam I thought this would be a good one for you to look at while you're getting more familiar with that section of the code.

**Comment by xiam** [comment]
@myleshorton Sure! I think that this masquerade should be removed from the YAML cloud configuration for the clients stop using it, but I also think that if I remove the host from `flashlight/genconfig/domains.txt` and regenerate `flashlight/config/masquerades.go` without this host it will work for new flashlight releases. Which option would be more appropriate?

**Comment by myleshorton** [comment]
I think both would be great! Actually, maybe this is a good moment to also put that cloud version on GitHub instead of Amazon since Amazon will have issues in China. Do you want to do that as well and to change the URL the client points to when it starts Flashlight to be a file on GitHub? It has to actually be checked into some repo as otherwise GitHub will just forward it to Amazon anyway. We could have a repo that's just the cloud config files perhaps?

**Comment by xiam** [comment]
The option about github sounds a lot easier to maintain and keep up to date, so I think it would be better moving our config files here and update our code accordingly. I actually have a [related issue](https://github.com/getlantern/flashlight-build/pull/36#discussion_r23657537) that I shall finish to fully understand cloud configuration, once I got that I'll be able to return and fix this more easily.

**Comment by myleshorton** [comment]
Sounds good @xiam

**Comment by oxtoacart** [comment]
> I think both would be great! Actually, maybe this is a good moment to also put that cloud version on GitHub instead of Amazon since Amazon will have issues in China.

We already access cloud.yaml via our own proxy, so from a blocking resistance perspective it doesn't matter where it lives.

**Comment by myleshorton** [comment]
> We already access cloud.yaml via our own proxy, so from a blocking resistance perspective it doesn't matter where it lives.

Good point!

**Comment by oxtoacart** [comment]
BTW, if we get binary diffs working with #21, we can get rid of the cloud-based YAML distribution and just use whatever is baked into the binary.  When we need to make a change, we can just push a new binary.  This has the advantage that we're always testing the code and the configuration together.  As it stands, when we push a new configuration, we end up with various versions of the codebase all using that new configuration, which we can't possible all test.

**Comment by myleshorton** [comment]
Love it!

**Comment by myleshorton** [comment]
Not sure about updates on Android though. Usually would be through the Play Store, but I think that's generally blocked. We can also just worry about that later though.

**Comment by atavism** [comment]
> Not sure about updates on Android though. Usually would be through the Play Store, but I think that's generally blocked. We can also just worry about that later though.

@myleshorton @xiam Yeah, Google Play is completely unavailable in China and Iran. We can still distribute the apk file (or a QR code actually) over the web though. The app itself could periodically check for and download the latest version as outlined [here](https://stackoverflow.com/questions/15213211/update-an-android-app-without-google-play).

**Comment by myleshorton** [comment]
Closing since this is on the java side.
