### ISSUE TITLE
error 34 from file i4j_nlog_4 trying to install Lantern

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2202]
Reported by a user in the English forums:

```
Hi

I am trying to install Lantern, but get an error 34 from the file i4j_nlog_4, which is located in C:\Users\Administrator\AppData\Local\Temp.

Can anyone advise me how to correct this?

Thanks.
```

**Comment by myleshorton** [comment]
Any idea @aranhoide which Windows version they're running?

**Comment by aranhoide** [comment]
I just asked

https://groups.google.com/forum/#!topic/lantern-users-en/lPsZmtX2Hpo

**Comment by aranhoide** [comment]
Windows 7 professional, user says.

**Comment by myleshorton** [comment]
Thanks @aranhoide! I just went ahead and responded directly on that thread.

**Comment by myleshorton** [comment]
Closing in light of new installers/go port.
