### ISSUE TITLE
New OSX installer

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2204]
Should be a draggable app bundle inside a dmg.

**Comment by oxtoacart** [comment]
We decided to punt on installers for now.  Most of the work for this was already done and is available here - https://github.com/getlantern/flashlight-build/tree/valencia-installers.

**Comment by myleshorton** [comment]
Oh I thought we were only punting on Windows since users of circumvention
tools are relatively used to that approach there. I think we still need a
drag and drop installer on OSX.

On Sunday, February 15, 2015, oxtoacart <notifications@github.com> wrote:

> We decided to punt on installers for now. Most of the work for this was
> already done and is available here -
> https://github.com/getlantern/flashlight-build/tree/valencia-installers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2204#issuecomment-74416606>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Ahh, good thing I clarified.  What about Linux?

**Comment by myleshorton** [comment]
I feel like we ultimately need one there too but can certainly punt for now.

On Sunday, February 15, 2015, oxtoacart <notifications@github.com> wrote:

> Ahh, good thing I clarified. What about Linux?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2204#issuecomment-74421458>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
