### ISSUE TITLE
Static HTTP serving in Go

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2205]

**Comment by atavism** [comment]
@myleshorton I ended up using the beego framework, and the current UI is being served from a static directory. How do we feel about adopting an MVC structure, or would that be overkill?

The whitelist component I'm putting into a separate module.

**Comment by oxtoacart** [comment]
@atavism Cool!  Can you please add [go-bindata-assetfs](https://github.com/elazarl/go-bindata-assetfs#readme) to put the static resources inside the binary?

**Comment by atavism** [comment]
> @atavism Cool! Can you please add go-bindata-assetfs to put the static resources inside the binary?

Sure.

**Comment by atavism** [comment]
@oxtoacart I don't see an easy way to use this with beego. Should we just use the standard http package instead?

**Comment by oxtoacart** [comment]
@atavism I'm not wedded to the implementation of go-bindata-assetfs, but bundling the resources into the binary one way or another is IMHO a requirement, since my plan is to make the whole app distributable in binary form (which will also ease upgrades/patching).

Regarding beego versus net/http, what are you hoping to get out of using beego?  And would something like [gorilla](http://www.gorillatoolkit.org/) give you what you need and still work with http.Filesystem?

**Comment by atavism** [comment]
> Regarding beego versus net/http, what are you hoping to get out of using beego? And would something like gorilla give you what you need and still work with http.Filesystem?

beego was recommended on the call. It's a full-fledged MVC framework which is probably overkill. I didn't see a super compelling reason to use it in particular, and I actually intended to use gorilla (which I've worked with before) originally. It has the advantage of being split up into a bunch of independent libraries already so we can pick and choose the features we want.

**Comment by oxtoacart** [comment]
+1 on Gorilla!

**Comment by oxtoacart** [comment]
Actually, +1 on net/http until and unless we need Gorilla.

**Comment by atavism** [comment]
Sounds good. Thanks! FYI, to update you: we created a new https://github.com/getlantern/go-lantern repo  -- I'll be committing a first version there.

**Comment by myleshorton** [comment]
Cool. Yeah I wasn't so much recommending it as much as mentioning it as an
option. I'm totally cool with straight net/http.

On Tuesday, February 3, 2015, oxtoacart <notifications@github.com> wrote:

> Actually, +1 on net/http until and unless we need Gorilla.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2205#issuecomment-72776584>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Nice work @atavism!
