### ISSUE TITLE
Port setup sequence backend to Go

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2207]
This will not include the Google login, the friends screen, or even choosing give versus get mode initially.

**Comment by atavism** [comment]
@myleshorton I suppose a related task would be to create a version of the UI with all of these components stripped out. Actually, maybe a version that strips everything out except for the server-sent events? We could make that a submodule of go-lantern.

**Comment by myleshorton** [comment]
Yeah totally @atavism. I'm also not wed to the SSE approach, but maybe for the purposes of the MVP it makes sense to keep using it.

**Comment by oxtoacart** [comment]
There is no setup sequence anymore.
