### ISSUE TITLE
Make the system proxy a Go proxy

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2208]

**Comment by oxtoacart** [comment]
@myleshorton What does this mean?  Are you talking about the proxy on port 8787?  If so, this is already done.

**Comment by myleshorton** [comment]
Yeah that's what I'm talking about. Does GetModeProxy.java really do nothing other than delegate at this point? So it probably shouldn't extend AbstractHttpProxyServerAdapter.java and should maybe have a new name, does that sound right?

**Comment by oxtoacart** [comment]
@myleshorton Yeah, GetModeProxy simply manages the lifecycle of flashlight at this point.  Since its days are numbered, I figured it's not worth messing with it too much.

**Comment by myleshorton** [comment]
OK cool closing!
