### ISSUE TITLE
New Ubuntu installer

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2209]

**Comment by oxtoacart** [comment]
We decided to punt on installers for now.  When we're ready to look at this again, this tool should be of great use - https://github.com/jordansissel/fpm

**Comment by oxtoacart** [comment]
Moving back to Beta 1 but leaving P2.

**Comment by atavism** [comment]
Do we plan to submit the package to the actual Debian repo this time? Would be great if new Ubuntu users only have to run ``yum install lantern``

**Comment by myleshorton** [comment]
Yeah we should add them if possible so they can be installed with aptitude
(I think we can skip yum for now probably right?). I've never done that
before though and have no idea where to add them.

On Mon, Feb 23, 2015 at 2:25 PM, atavism <notifications@github.com> wrote:

> Do we plan to submit the package to the actual Debian repo this time?
> Would be great if new Ubuntu users only have to run yum install lantern
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2209#issuecomment-75650923>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
In principle, distributing Lantern in the official Ubuntu repos means we get locked to the release schedule of Ubuntu.  What we could do is create our own repo that users could install via a ppa, but that is no more convenient for users than just downloading the .deb, so it doesn't make sense unless we're going to push updates to that repo, which would overlap with our auto-update functionality.

**Comment by oxtoacart** [comment]
Actually, the nice thing about in-app auto-update is that we could push a more or less arbitrary version to the official Ubuntu repos and it can just update itself automatically once it runs.

**Comment by aranhoide** [comment]
I don't think that is allowed in the official repos, that's what I meant.  IIRC the version of e.g. Firefox and Chromium is fixed and you can only get security updates for any given Ubuntu release.  You get version updates if you upgrade your Ubuntu version.

**Comment by aranhoide** [comment]
cf. https://wiki.ubuntu.com/StableReleaseUpdates

**Comment by oxtoacart** [comment]
Our auto-update has nothing to do with the Ubuntu repos.  We can put version 2.0.0 in the Ubuntu repo, and while it's running it might upgrade itself to 2.1, then 2.2, etc., all completely outside of the deb workflow (just like on our other platforms).

**Comment by aranhoide** [comment]
In theory Chrome could do that too, but that doesn't happen in Ubuntu's Chromium.  The closest thing that works like that AFAIK is flash, but that is not a package per se.  What you install is a plugin that downloads flash.

Also, I don't think we are likely to ever get into the official repo with statically built libraries, but I could be wrong.

**Comment by aranhoide** [comment]
Also, I think the earliest we could get this in the Ubuntu official repo would be in next Ubuntu release, so this would never make it to the Valencia version anyway.

My inclination would be to punt on submitting to the official distribution until the Go Lantern seems mature and stable enough that we'd feel comfortable to ship it even if we knew it would only get security updates thereafter.

**Comment by myleshorton** [comment]
Makes sense to me @aranhoide. I don't know much about this area. Are there
third party repos that a lot of people generally have set up?

On Thursday, February 26, 2015, aranhoide <notifications@github.com> wrote:

> Also, I think the earliest we could get this in the Ubuntu official repo
> would be in next Ubuntu release, so this would never make it to the
> Valencia version anyway.
>
> My inclination would be to punt on submitting to the official distribution
> until the Go Lantern seems mature and stable enough that we'd feel
> comfortable to ship it even if we knew it would only get security updates
> thereafter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2209#issuecomment-76137621>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Have you ever looked at https://build.opensuse.org/ @aranhoide? Looks interesting for supporting multiple Linux varieties.

**Comment by aranhoide** [comment]
Re: openSUSE, I hadn't seen it, no.  I'll give it a look.  This fpm tool we use also allow building various package types.

As for third party repos, those are usually added just to download a single package or related set of packages.  For example, this is how you'd install Oracle Java 7 on a fresh Ubuntu installation:
```
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer
```
While this is convenient for what it does, just downloading and installing the package is even shorter (one `wget` and one `sudo apt-get install`).

The main advantage of using apt packages from a repository, be it the standard one or a custom one, is that you get updates for the package whenever you update your system (which is usually done automatically daily, at least for security updates).  For us, using this functionality would overlap with automatic upgrades.
