### ISSUE TITLE
[peerscanner] Reduce attack surface for fake registrations and unregistrations

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2215]
@xiam Noticed that peerscanner accepts X-Forwarded-For and X-Peerscanner-Forwarded-For headers to identify a client's ip address on registration and unregistration.  This poses several problems:

1. On registration, anyone can fake an IP address. This won't cause them to get added to the rotation since we don't do that until we've confirmed that we can proxy through that IP address, however it does open the possibility of DOS'ing peerscanner by registering a bunch of fake addresses, which will cause peerscanner to run out of memory.

2. On unregistration, it effectively allows anyone to unregister any registered IP address.

We found these problems during the code review of the peerscanner refactoring.  Neither of these issues is new, and in fact the first issue improved slightly because we at least don't register the fake IPs in CloudFlare DNS anymore.

The solution to this is:

1. Give the new peerscanner server its own certificate and configure CloudFlare to direct traffic for peerscanner.getiantem.org directly to the digital ocean server.

2. Update `clientIpFor()` in web.go to only accept direct IP addresses.  To ensure that we don't run into problems with proxied requests, it should check for the presence of a proxy (e.g. a via header or X-Forwarded-For header) and deny registrations for such requests.

**Comment by aranhoide** [comment]
What does `direct IP addresses` mean for peerscanner, which is sitting behind Cloudflare?
