### ISSUE TITLE
Some nodes in CloudFlare's DNS not using CloudFlare's CDN

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2216]
This could be causing some of the issues we've been seeing with CloudFlare connectivity.

**Comment by myleshorton** [comment]
It's likely we have to retry on failures if the API call to set this fails. Could be related to the new peerscanner changes as well.

**Comment by oxtoacart** [comment]
@myleshorton Which nodes?  I just took a quick look and the only ones with the gray cloud are not proxies (all listed at the bottom).

**Comment by myleshorton** [comment]
I switched em all over.

On Tuesday, February 3, 2015, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Which nodes? I just took a
> quick look and the only ones with the gray cloud are not proxies (all
> listed at the bottom).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2216#issuecomment-72706739>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Gotcha.  Was it peers, fallbacks, items in rotations?

**Comment by myleshorton** [comment]
Both peers and fallbacks, but there was a higher percentage of peers
potentially because there's more churn but not sure.

On Tue, Feb 3, 2015 at 11:00 AM, oxtoacart <notifications@github.com> wrote:

> Gotcha. Was it peers, fallbacks, items in rotations?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2216#issuecomment-72711896>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton Thanks, that helps!  It's annoying that CloudFlare's API requires a 2nd call to activate the orange cloud.

**Comment by myleshorton** [comment]
Yeah agreed @oxtoacart -- makes the code more awkward for sure. I figured I'd just check 'em while I was in there in case it was causing production issues, even that 409 conflict bug. I'm seeing that a lot still though -- for some reason it's now appearing all the time -- #1739
