### ISSUE TITLE
[bug] Incoming traffic not appearing on the map in give mode

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2217]
When running in give mode, no incoming traffic appears on the map on devel even when there almost certainly is traffic. This shows up clearly when switching between devel and master, with traffic showing up almost immediately on master but with nothing on devel. DNS registration is happening properly in both cases.

**Comment by uaalto** [comment]
@myleshorton does this bug still apply?

**Comment by myleshorton** [comment]
Yeah for give mode.
