### ISSUE TITLE
MVP UI with unnecessary components stripped out

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2218]

**Comment by atavism** [comment]
There's a version of this ready in the issue-2218 branch. All the cometd, interaction servlet, and model-related functionality has been stripped out.

**Comment by atavism** [comment]
As of now, this reduced version of the UI basically displays the global map, the "About" and "Contact" links/modals, and a button/modal for managing your whitelist.

**Comment by myleshorton** [comment]
Awesome @atavism! That'll make that task of the whitelist API much easier.

**Comment by oxtoacart** [comment]
Nice work @atavism!
