### ISSUE TITLE
Web site mirror missing images

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2221]
https://s3.amazonaws.com/getlantern.org/index.html

This will likely be more of an issue when we roll out specifically to Iran and China where users need to access the unblocked version of the sites.

@fffw can you look into what's happening with these images? See:

https://github.com/getlantern/www.getlantern.org/blob/master/deploytos3.bash

**Comment by fffw** [comment]
Oh I mistakenly place images using absolute paths in index.html, corrected.

As I don't have credentials to push to s3, @atavism could you review https://github.com/getlantern/www.getlantern.org/pull/55 and push?

**Comment by myleshorton** [comment]
Nice! I just put the credentials in https://github.com/getlantern/too-few-secrets if you want to push directly (I think those are the correct credentials at least!)

**Comment by fffw** [comment]
Updated to http://getlantern.s3-website-ap-southeast-1.amazonaws.com and confirmed through `curl`, but https://s3.amazonaws.com/getlantern.org/index.html still not get updated after 1 hour. Additional action required?

**Comment by fffw** [comment]
https://s3.amazonaws.com/getlantern.org/index.html still not get updated.
@atavism @oxtoacart @myleshorton do you have any idea about it?

I tried a while on S3 console using my own account but didn't get any luck.

**Comment by myleshorton** [comment]
Hmnn I'm not sure unfortunately @fffw -- it should be picking up the change. Have you seen that @atavism?

**Comment by atavism** [comment]
Hey guys, this should be fixed now. We need to use "./images" instead of just "images" in the paths when serving the site from S3. I updated the scripts to reflect this. https://s3.amazonaws.com/getlantern.org/index.html should be good to go now.

**Comment by myleshorton** [comment]
Awesome thanks @atavism!

**Comment by fffw** [comment]
Thanks a bunch @atavism!
