### ISSUE TITLE
[peerscanner] tls: invalid ServerKeyExchange error registering server

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2225]
Appearing in Papertrail:

> Feb 01 19:44:42 cloudflare-peerdnsreg app/web.1:  2015/02/02 03:44:42 Unexpected error forwarding request: Post https://peerscanner.getiantem.org/register?name=219d1bbd95d8789afa7340c3714f0191&port=443: tls: invalid ServerKeyExchange message

**Comment by oxtoacart** [comment]
Strongly suggest bumping down to P3.  This happened once a few days ago on a system that gets over 100000 requests per day.

**Comment by myleshorton** [comment]
That's fine. I had no idea how common it was, and it's the type of error
doesn't tend to happen just once. If that's all it was feel free to close.

On Saturday, February 7, 2015, oxtoacart <notifications@github.com> wrote:

> Strongly suggest bumping down to P3. This happened once a few days ago on
> a system that gets over 100000 requests per day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2225#issuecomment-73389880>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Sounds good. Let's reopen if it starts happening more frequently.
