### ISSUE TITLE
[feature] Auto-updates without interrupting proxying/UI activity

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2226]
In the initial implementation, auto-updates will simply happen without user intervention, potentially momentarily interrupting browsing or interaction with the UI.

It would be slick to do these using a zero-downtime restart technique such that server sockets remain bound, which would prevent the user from noticing anything other than maybe a slight delay while the program restarts.

There are various techniques available:

* http://blog.nella.org/?p=879
* https://github.com/rcrowley/goagain
* https://github.com/amscanne/huptime

Most of these techniques are UNIX specific.  On Windows, we could potentially just have a supervisor program that uses [Windows Named Pipes](https://github.com/natefinch/npipe) (or maybe just TCP sockets) to proxy stuff to the program that would be restarting.

**Comment by oxtoacart** [comment]
Related to #21

**Comment by fffw** [comment]
I was originally thinking that asking user to restart application is enough, just like what OS update or Chrome do. But when silent services such as Lantern Pi or OpenWRT plugin comes into mind, an uninterrupted upgrade is definitely a must.

**Comment by oxtoacart** [comment]
> But when silent services such as Lantern Pi or OpenWRT plugin comes into mind, an uninterrupted upgrade is definitely a must.

Good point!

**Comment by myleshorton** [comment]
Yeah makes sense @fffw! We could auto-detect those platforms and always
auto-update and auto-restart.

On Monday, February 9, 2015, oxtoacart <notifications@github.com> wrote:

> But when silent services such as Lantern Pi or OpenWRT plugin comes into
> mind, an uninterrupted upgrade is definitely a must.
>
> Good point!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2226#issuecomment-73516212>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
> Yeah makes sense @fffw! We could auto-detect those platforms and always
auto-update and auto-restart.

I think we've already said that for our initial implementation we'll just auto-restart without prompting anyway, even if it's not seamless.

If we gain the ability to do it seamlessly, we might as well do it on platforms, right?

**Comment by myleshorton** [comment]
+1

On Monday, February 9, 2015, oxtoacart <notifications@github.com> wrote:

> Yeah makes sense @fffw <https://github.com/fffw>! We could auto-detect
> those platforms and always
> auto-update and auto-restart.
>
> I think we've already said that for our initial implementation we'll just
> auto-restart without prompting anyway, even if it's not seamless.
>
> If we gain the ability to do it seamlessly, we might as well do it on
> platforms, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2226#issuecomment-73533848>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
If by "uninterrupted" you mean without requiring user intervention, I
agree.  If you mean that ongoing connections can't be aborted, I think it's
a nice to have and not a must.

**Comment by myleshorton** [comment]
Agreed @aranhoide

**Comment by xiam** [comment]
The current implementation of self updating does not affect proxying at all, the updated program is used the next time Lantern is restarted. I'm preparing the LEP that will explain this in detail.

Should we keep this issue open? We'll need this for give mode.

**Comment by myleshorton** [comment]
I actually don't think this is a requirement for give mode either. Almost no software out there in general does this, and unless we introduce some incompatibility there's no harm in the give mode user updating the next time Lantern starts up (either via computer restart or manual startup). If we see a real need for it we can revisit though. Closing!
