### ISSUE TITLE
[feature] Automatically restart Lantern if it crashes

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2227]
We should make every effort to keep Lantern from crashing, but if it does, it would be nice for it to log the crash and then automatically restart.

**Comment by aranhoide** [comment]
As suggested by an example @myleshorton mentioned elsewhere, where Lantern would keep crashing on startup indefinitely, we may want to delay restarts with an exponential backoff schedule.

**Comment by oxtoacart** [comment]
> As suggested by an example @myleshorton mentioned elsewhere, where Lantern would keep crashing on startup indefinitely, we may want to delay restarts with an exponential backoff schedule.

+1

**Comment by oxtoacart** [comment]
One idea was suggested by @atavism  is using a library that implements Erlang-style supervisor trees:

* https://github.com/thejerf/suture
* https://godoc.org/code.google.com/p/gosup/supervisor

**Comment by oxtoacart** [comment]
Another option is using a supervisor process.

What I'm thinking when I say "supervisor" is actually a process.  This would be a very simple process that runs the actual lantern process as a child.  If the child process ever dies, or stops emitting a heartbeat, the supervisor would restart it.  The supervisor process would be given a higher priority (nice on UNIX) so that if the system is becoming resource constrained because of an ill-behaved child process, the supervisor will still have the resources it needs to terminate and restart the child.  This should help with the reliability side of things.

The supervisor would also own any server sockets (details of this need to be worked out) so that after an update, the supervisor can restart the child process to pick up the changes without interrupting any client connections.  This would allow for seamless auto-updates to a live system.  We'd have to work out how to update the supervisor, which should in practice happen rarely.  

The supervisor and the child process would use the same binary, just with a flag that tells it whether it's a supervisor or worker.  The supervisor would immediately enter into a very minimal code path that just handles the supervision stuff and is less likely to crash than the child worker.

**Comment by oxtoacart** [comment]
Just for dealing with panics, we could also consider putting in a global recover in our main method and then reinitializing the system without restarting the process.

**Comment by myleshorton** [comment]
Closing in favor of global recover on panics for now.
