### ISSUE TITLE
Add welcome screen

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2228]
This will appear when the UI first opens. 

Some notes:
> - The welcome screen will present links to popular censored sites users have probably heard of but have been unable to access until now (Twitter, Facebook, YouTube, Instagram, etc.)
- It should contain a link to the whitelist configuration screen
- Future possibilities: dynamic content that we control; recent trends from social media

**Comment by myleshorton** [comment]
Thanks for logging this @atavism! We can probably start with just a Facebook and Twitter link a la the post-download section on the web site, but the others certainly can't hurt if we've got the time. I marked this as p2 since it's really icing on the cake when we knock out all the other issues, but it would be awesome to get to it.

**Comment by atavism** [comment]
@myleshorton How often should this appear? Every time a new instance of the UI is opened?

**Comment by myleshorton** [comment]
I think probably just the first time, although for now every time would be
fine.

On Friday, February 20, 2015, atavism <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> How often should this
> appear? Every time a new instance of the UI is opened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2228#issuecomment-75318629>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by atavism** [comment]
@myleshorton It should only display once. I'm checking for a local storage key (or cookie where unsupported) before the welcome screen is shown. Also, clicking on 'Lantern' also shows it.

**Comment by oxtoacart** [comment]
Great idea on putting this state in the browser!

**Comment by myleshorton** [comment]
Sweet!

On Sat, Feb 21, 2015 at 7:34 AM, oxtoacart <notifications@github.com> wrote:

> Great idea on putting this state in the browser!
> On Feb 21, 2015 11:30 AM, "atavism" <notifications@github.com> wrote:
>
> > @myleshorton <https://github.com/myleshorton> It should only display
> > once. I'm checking for a local storage key (or cookie where unsupported)
> > before the welcome screen is shown. Also, clicking on 'Lantern' also
> shows
> > it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/getlantern/lantern/issues/2228#issuecomment-75382141
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2228#issuecomment-75382379>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
