### ISSUE TITLE
Make sure that proxying for oneself works

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2229]
Several times now we've gotten feedback from users that they tried installing Lantern on two different machines in order to use one as the proxy for the other.  Just like much of P2P, this often isn't working right now, which understandably raises questions.

When we revisit P2P, we should make absolutely sure that this use case works (as long as NAT traversal or port mapping are available).

**Comment by myleshorton** [comment]
+1

On Monday, February 9, 2015, oxtoacart <notifications@github.com> wrote:

> Several times now we've gotten feedback from users that they tried
> installing Lantern on two different machines in order to use one as the
> proxy for the other. Just like much of P2P, this often isn't working right
> now, which understandably raises questions.
>
> When we revisit P2P, we should make absolutely sure that this use case
> works (as long as NAT traversal or port mapping are available).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2229>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
I think we can also do better around the messaging here - opened #2230.
