### ISSUE TITLE
[feature] Make sure that the UI provides clear status about all my friends (including myself)

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2230]
Right now, users have a lot of confusion about whether they're friends are online and whether or not they should be able to proxy through them.  This confusion arises for several reasons:

1. The friends list uses the terms "connected" and "not connected" to indicate whether or not we're getting signaling traffic from a peer associated with that users.  That's confusing since this is not the same as actually being connected to a proxy.

2. We don't do a good job explaining the difference between a friend (which is an identity that can own peers which we trust) and peers (which are instances of lantern through which/for which we are proxying).

3. We don't explain why some peers are inaccessible

To reduce confusion amongst our users, and to help us troubleshoot, the UI should do the following (written from Get mode perspective, but we should think about similar from Give mode perspective):

1. List all friends that we have

2. For all friends, list all peers that they have.  In addition to showing them on a map, it would be helpful to list them under the friends (perhaps in a tooltip or an expando type control)

3. For each peer, clearly indicate: a) Whether or not the peer is currently online, b) Whether or not we're able to connect to it and c) if we're not able to connect to it, some more detailed explanation as to what went wrong (e.g. NAT traversal failed, no port mapped, etc.)

**Comment by myleshorton** [comment]
Also see #1371
