### ISSUE TITLE
Launch the UI in Go

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2231]

**Comment by atavism** [comment]
Is there anything stopping us from supporting IE moving forward? The UI looked fine on the latest version. This would simplify the task some: we'd always use the preferred browser as the default option. I ask because, IIRC, IE still owns a majority of the browser market in China (47.62% according to one estimate).

That said, the library I'm using for this makes it really easy to always choose Chrome/Firefox/etc in whatever order we want to -> see https://github.com/skratchdot/open-golang

**Comment by myleshorton** [comment]
I think that's fine as a starting point. The one tricky part is I think a
lot of the IEs in China are IE6, but let's just start with the default
browser and see where we are.

On Tuesday, February 10, 2015, atavism <notifications@github.com> wrote:

> Is there anything stopping us from supporting IE moving forward? The UI
> looked fine on the latest version. This would simplify the task some: we'd
> always use the preferred browser as the default option. I ask because,
> IIRC, IE still owns a majority of the browser market in China (47.62%
> according to one estimate).
>
> That said, the library I'm using for this makes it really easy to always
> choose Chrome/Firefox/etc in whatever order we want to -> see
> https://github.com/skratchdot/open-golang
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2231#issuecomment-73779105>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
+1

**Comment by fffw** [comment]
As per [realtime statistics](http://tongji.baidu.com/data/browser), IE6 and IE7 occupies less than 10% in total. We can safely take IE8 as minimum supported version.

**Comment by oxtoacart** [comment]
So what will we do in the case where someone is running an older, unsupported version of IE?

**Comment by myleshorton** [comment]
That's super useful @fffw thanks! I guess the big question is does it work in IE8? We could detect the default browser and version in the registry and message the user if they have an unsupported browser.

**Comment by oxtoacart** [comment]
We could also just do it in the UI.

**Comment by myleshorton** [comment]
Yeah the only annoying part about that approach is that the unsupported browsers are unsupported in part because they're a PITA to deal with in terms of making whatever messaging we put in there visually consistent.

**Comment by oxtoacart** [comment]
Simple is better in this case.  Just redirect to a very plain page that says "please get a better browser", with the Lantern logo, maybe a nice background (although white would be fine), and the closest approximation to our font that we can find.  Heck, we could even just make this a PNG and do the whole page as an image.

**Comment by myleshorton** [comment]
True -- just an html body with some text, a link, and embedded CSS for the font should work pretty globally.

**Comment by atavism** [comment]
I added a new openui flag to specify whether or not the UI should be automatically opened in the default browser. The current syntax is
```
flashlight -role client -addr localhost:10080 -uiaddr localhost:16785 -openui
```

**Comment by oxtoacart** [comment]
Great, thanks!  BTW, for Valencia, I'm updating flashlight so that it can
run without any command-line parameters by just defaulting them.  So role
defaults to client, address defaults to localhost:8787 and once I merge
your changes, I'll default uiaddr to localhost:16785 and openui to true.

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by myleshorton** [comment]
Perfect @oxtoacart!

**Comment by myleshorton** [comment]
What branch is the ui-opening stuff on @atavism?

**Comment by atavism** [comment]
The same branch as the whitelist functionality: issue-2195. You have to pass in "-uiaddr localhost:16785 -openui" to see it open.

**Comment by myleshorton** [comment]
Nice!

On Fri, Feb 13, 2015 at 1:23 PM, atavism <notifications@github.com> wrote:

> The same branch as the whitelist functionality: issue-2195. You have to
> pass in "-uiaddr localhost:16785 -openui" to see it open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2231#issuecomment-74329269>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Nice work @atavism!
