### ISSUE TITLE
Report Go errors to Loggly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2232]

**Comment by myleshorton** [comment]
This could be another great one to look at @fffw, @aranhoide, or @xiam. It's definitely not the most glamorous, but it is super important if someone wants to grab it.

**Comment by atavism** [comment]
https://github.com/pkar/plywood

**Comment by fffw** [comment]
I found https://github.com/segmentio/go-loggly on [official list](https://www.loggly.com/docs/loggly-libraries-catalog/) which is more coherent and well maintained.

POST to Loggly.com through proxy is tricky as the proxying code itself indeed requires reporting. If that is not the case, we can integrate it directly to https://github.com/getlantern/golog, and supply another Transport to it if we do need proxying later.

**Comment by oxtoacart** [comment]
This should be worked on along with #2238 since they're closely related.

**Comment by fffw** [comment]
I figured a new approach, which is to spawn a goroutine on startup, watch any additions to the log file, and write them to Loggly. It will record the last entry of successful send and send later entries if possible once network is available.

With it, we can have those errors when network is not reachable, or during startup/shutdown. I think it's important to us, as Lantern is a network utility.

It may requires golog to add log level to each line, as we may only send errors to Loggly. Or, it can maintain its own temporary file and not interfere with the rotated lattern.log. Or even better, we may switch to a more mature logging facility which supports hooks, such as [this one](https://github.com/Sirupsen/logrus)

**Comment by oxtoacart** [comment]
logrus looks interesting, but we don't have time to switch to it today.

Using the file as a buffer for log messages to Loggly is also interesting.  The only thing to be careful about there is that if the buffer gets too large, we probably don't want to flush the whole thing to Loggly.

**Comment by oxtoacart** [comment]
This is 99% done.  Just need to grab the country from @xiam's geoip work once that has been merged.

**Comment by oxtoacart** [comment]
Bumped up to P1 so we don't miss this.

**Comment by xiam** [comment]
Since @fffw is on holiday I think I can take a stab at this.

**Comment by oxtoacart** [comment]
@xiam I'm actually almost done with the integration.  PR coming soon :)

**Comment by oxtoacart** [comment]
@xiam I actually just realized that there's a big task here - we need to communicate with loggly via our proxy.  I'm assigning over to you.  I did manage to get the country information in there, it's on this branch - https://github.com/getlantern/flashlight-build/tree/issue2232-integrate.

**Comment by xiam** [comment]
@oxtoacart Sure! Looking into it.

**Comment by xiam** [comment]
Looks like I can provide an io.Writer to `golog.SetOutput()` in `logging.go`, this new writer will print its output (as it does today) and keep a buffer that will push the logs to Loggly through a proxy, when the proxy is available.

I would use https://github.com/segmentio/go-loggly.

And looks like we have some previous work in `logging.go`, but it does not buffer requests nor uses a proxy.

We are going to log error messages only, right? that is things that are written to `errorOut` and not `debugOut`.

**Comment by oxtoacart** [comment]
@xiam We're already logging to go-loggly from logging.go (see the branch).  go-loggly actually already buffers, so the only thing we need to do still is get go-loggly to use our proxy.

**Comment by xiam** [comment]
I'm having a problem here: the loggly client expected working over HTTPs and the proxy set up by `client.Configure()` could not communicate to it, I switched to plain HTTP and now the proxy communicates with a server but replies with this:

```
            <p>You've requested a page on a website (logs-01.loggly.com) that is on the <a data-orig-proto="https" data-orig-ref="www.cloudflare.com" target="_blank">CloudFlare</a> network. CloudFlare is currently unable to resolve your requested domain (logs-01.loggly.com). There are two potential causes of this:</p>
            <ul>
```

That happens only when the client uses the proxy client, when I use a normal `http.Client` it does not happen.

Does it sound familiar to you?

**Comment by oxtoacart** [comment]
You can't use the same client as you use for geolocation.  Geolocation is special because our geolocation server is actually registered with CloudFlare.  Loggly doesn't use CloudFlare, so you will have to proxy via the local proxy at port 8787.  Something like this:

```go
client := &http.Client{
    Transport: &http.Transport{
        Proxy: http.ProxyUrl(url.Parse("http://" + cfg.Addr))
}
```

**Comment by xiam** [comment]
Oh, right!

```
curl -H "Host: geo.getiantem.org" http://cloudflare.com/lookup
```

and

```
curl -H "Host: logs-01.loggly.com" http://cloudflare.com/
```

Got it.
