### ISSUE TITLE
[Desktop] Implement our own DNS resolution to bypass DNS poisoning

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2234]
The FireFly guys use a neat little trick: just use a custom host file to completely bypass DNS poisoning! That just works alone in a lot of cases. Pretty neat.

**Comment by oxtoacart** [comment]
@myleshorton How do they install it?

**Comment by myleshorton** [comment]
They actually just do it in software. So they get a request and just check
if they can route directly to the IP, and they load the ip out-of-band in
some fashion.

On Monday, February 9, 2015, oxtoacart <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @myleshorton <https://github.com/myleshorton> How do they install it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2234#issuecomment-73622973>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Ah, so they're not messing with the hosts file, they just have their own local DNS resolver (although it probably doesn't implement the DNS API I'm guessing).  It would actually be interesting to do an "unblocked DNS" project, that uses the same technique but actually just works as a local DNS server or something (or maybe plugs in with the OS's name resolution stuff, if that's even possible).

**Comment by myleshorton** [comment]
Yeah it would be nice to parcel out just that component.

On Wed, Feb 11, 2015 at 9:46 AM, oxtoacart <notifications@github.com> wrote:

> Ah, so they're not messing with the hosts file, they just have their own
> local DNS resolver (although it probably doesn't implement the DNS API I'm
> guessing). It would actually be interesting to do an "unblocked DNS"
> project, that uses the same technique but actually just works as a local
> DNS server or something (or maybe plugs in with the OS's name resolution
> stuff, if that's even possible).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2234#issuecomment-73927518>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Yeah, in general that's something to think about with all of these complimentary techniques.  On the one hand, there's a benefit to having lots of tightly focused solutions that people can install easily and that just work.  On the other hand, there's a benefit to having a single solution that employs a lot of techniques to stay unblocked.

In the case of a monolithic solution, one major problem that I see is that the user experience varies drastically from technique to technique.  We've already seen this to a certain extent with domain fronting versus direct proxies, and techniques like DNS unblocking up the ante even further.  The issue here is that the user experience when using the single monolithic product could vary wildly depending on destination site, the user's country, and even just what's going on at this point in time censorship-wise.  Managing the user's expectations around this and their perception of the production is a tricky UX challenge.

**Comment by myleshorton** [comment]
I just think each technique solves some particular slice of the problem, so deploying the best possible solution for each particular slice to give the user the best possible overall experience is about the best we can do.

**Comment by oxtoacart** [comment]
I think I agree, I'm just saying that we could do a better job messaging the user about what's going on.  For example, if we had an extension, we could have it change color to show what quality of service the user is getting (green, yellow, red) and provide more details if the user wants them.

So for example, we might show yellow if we're having to domain-front for the current site, and if someone clicks on the extension we can provide more explanation.  There can even be useful calls to action here, for example "go find more friends".

**Comment by myleshorton** [comment]
See https://github.com/yinghuocho/firefly-hosts/blob/master/firefly-hosts.txt

@yinghuocho remind me why it's IPv6 only again?

**Comment by myleshorton** [comment]
Yeah that would be super cool! It would also be super valuable for debugging on our end.

**Comment by yinghuocho** [comment]
@myleshorton: there are IPv4 hosts files maintained by Chinese programmers/users. But these public ones constantly become invalid. So I just integrated IPv6. The firewall of IPv6 seems not that aggressively updated.

**Comment by myleshorton** [comment]
Thanks @yinghuocho! I know China has great IPv6 deployment, but does it actually typically work end-to-end for most users (i.e. routers to ISPs to destination sites)? If so, that's extremely intriguing more generally. Do you have any experience with that @fffw?

**Comment by fffw** [comment]
@myleshorton I've not heard large scale deployment at home broadband.

**Comment by myleshorton** [comment]
Thanks @fffw. Are you personally able to load any sites over IPv6?

**Comment by fffw** [comment]
@myleshorton No. No any IPV6 route out by default.

**Comment by myleshorton** [comment]
Interesting thanks @fffw. If that's the case, what makes this valuable @yinghuocho?

**Comment by yinghuocho** [comment]
@myleshorton, @fffw, many universities in China support IPv6.

**Comment by myleshorton** [comment]
Interesting thanks @yinghuocho!

**Comment by myleshorton** [comment]
> @myleshorton: there are IPv4 hosts files maintained by Chinese programmers/users. But these public ones constantly become invalid. So I just integrated IPv6. The firewall of IPv6 seems not that aggressively updated.

They become invalid because of IP-based blocked, correct @yinghuocho? They just start blocking all the IPs in those lists in addition to poisoning the DNS?

**Comment by myleshorton** [comment]
This would be interesting to integrate into the auto-blocking detection @fffw

**Comment by fffw** [comment]
@myleshorton You mean load the hosts in Lantern and do a local lookup first?

In general I'm against embedding a universal volatile list, it needs efforts to maintain and update it, and IPV6 is not widely adopted at least in China.

As per [what Iran doing](https://github.com/getlantern/lantern/issues/2099#issuecomment-78015418), local lookup has little help if gov do want to block a site.

**Comment by oxtoacart** [comment]
A different way to conceptualize this is as a safe DNS service, for example an encrypting DNS proxy that sends queries to an out-of-country server like 8.8.8.8.

**Comment by myleshorton** [comment]
Yeah ignore the title of the bug @fffw -- I just changed it actually. It's just a matter of not using DNS to avoid DNS poisoning. One way would be to actually run a local DNS server, which might have ancillary benefits. A simpler way would be to just embed a map created from the config file that resolves that DNS locally.

**Comment by fffw** [comment]
One problem is that many IP addresses are still get blocked even we bypass DNS lookup, see last 4 result of [this test](https://github.com/getlantern/lantern/issues/2099#issuecomment-78015418).

In fact, for Iran's case, a site been DNS poisoned takes less time to be detected, as we can notice it by dialing and checking `RemoteAddr()`, rather than waiting for a read to be timed out.

**Comment by myleshorton** [comment]
Yes exactly @fffw, so this would have to still just be a layer in the auto-detection logic but would still have to fall back to everything you're already doing I think.

**Comment by myleshorton** [comment]
We decided in Valencia to punt on this because it would require auto-detection of blocking in the case where a site is both DNS poisoned and IP-blocked, but now that @fffw has implemented the auto-detection prototype this again becomes really compelling.

**Comment by fffw** [comment]
I still can't see much benefit of local DNS resolution. Are there many sites been DNS poisoned but not IP-blocked, especially for not well-known sites (well-known sites are in cooked whitelist anyway)?

I found https://github.com/txthinking/google-hosts which seems thorough and frequently updated, and I can open Google and YouTube actually. But we have to sync with it each day, and it's only for Google related sites.

If the purpose is to reduce the total traffic flows through Lantern infrastructure, a local lookup is meaningful, especially for YouTube. If it is not, I'm not sure.

We can also query out-of-country DNS servers, but should have DNS server knowing user's current IP address, to return most suitable IP for those not blocked sites.

**Comment by myleshorton** [comment]
> Are there many sites been DNS poisoned but not IP-blocked

People have anecdotally told me there are, but maybe we can measure it? For all the sites for which that is the case, then we can just go directly, which should overall be significantly faster while also reducing load on the overall Lantern infrastructure. Are you saying you don't think it'll be much faster? What's the difference between a site fully proxied through Lantern and one loaded directly? If I remember correct from @oxtoacart's measurements, the difference was significant.

**Comment by fffw** [comment]
Yeah I see.

So our goal is to find a reliable way to keep as less traffic through our infrastructure, to reduce cost / maintenance burden and, more importantly, let page loads faster.

**Comment by myleshorton** [comment]
Yeah it seems to me there should be a series of stages or even filters, with the overall system allowing us to use the lightest possible approach. Ideally this would be:

1. If we know a site is unblocked, go directly without any Lantern involvement
1. If we know a site is only DNS poisoned, resolve the correct IP locally and go directly. This could even mean running our own local DNS server, which would effectively put us back at #1 above
1. If a site is IP blocked, then actually proxy it.
    1. Use direct proxies if they're available
    1. Otherwise, use domain-fronted proxies

**Comment by fffw** [comment]
I made a rather simple page at http://fffw.github.io/roundtrip-page/ to take a look at the actual loading time inside browser.

For page loading, the difference with and without Lantern involved is significant, 346ms vs 150ms.

For AJAX calls, the time is about the same.

As dynamically changed PAC has no effect to a running browser, for point 1, maybe we can have browser extension to dispatch requests according to the list Lantern detected.

**Comment by myleshorton** [comment]
Awesome @fffw thanks!

> As dynamically changed PAC has no effect to a running browser, for point 1, maybe we can have browser extension to dispatch requests according to the list Lantern detected.

This is actually an issue in the current Lantern, i.e. when the user adds a site to the proxied sites list. Basically the solution is to turn proxying on and off to get the browser to pick up the changes.

**Comment by fffw** [comment]
> Basically the solution is to turn proxying on and off to get the browser to pick up the changes.
Ha it indeed works and will not affect established connections.

**Comment by myleshorton** [comment]
Nice @fffw! Another big part of this is of course actually coming up with the list of correct DNS resolutions. Or maybe we can just tunnel to a DNS server and cache the results? I'm not sure what the best solution is here. This might be a good moment to write an [LEP](https://github.com/getlantern/lantern-roadmap/tree/master/lep) for this feature. Would you be up for that? I feel like we can come up with a slick solution for finding the correct IP and maybe even to just detect DNS poisoning.

**Comment by atavism** [comment]
Maybe we could use something like [dnscache](http://cr.yp.to/djbdns/dnscache.html) to cache responses.

**Comment by fffw** [comment]
Yeah it's worth an LEP and thanks @atavism for the suggestion!

**Comment by fffw** [comment]
DNS poisoning can harm Lantern if both:
1. The request is not over HTTPS, or the user agent doesn't validate certificate.
1. There's valid web server running on the IP of poisoned DNS entry.

It is used massively by ISPs to show ads for unreachable sites, but can be easily perceived and bypassed for valid sites if employed by censors. There was reports that GFW basically DDoSed some random sites by (mistakenly) DNS poisoning censored sites to their IP address.

**Comment by oxtoacart** [comment]
We could:

1. Make requests to a DNS resolver that uses DNSSEC (Google supports this)
2. If that's blocked, tunnel the DNS request through our proxies

Given that DNS traffic is pretty light, we could potentially do DNS requests via direct domain fronting.

**Comment by myleshorton** [comment]
Yeah I generally like the DNSSEC idea. The only problem is I believe most Chinese DNS servers don't support it, and other DNS servers are blocked AFAIK. I think detour also already has some support for detecting poisoning. I wonder if we can just first detect it and then tunnel a DNS lookup in that case?

**Comment by oxtoacart** [comment]
To be clear, what I was suggesting is to send all traffic through the local proxy and have that proxy do DNS lookups securely (DNSSEC, tunneled, etc.)  For sites that are not blocked at the IP level, it would just proxy them directly, while for blocked sites it would proxy via a remote proxy server.

**Comment by myleshorton** [comment]
Oh gotcha. We really can just keep sending traffic through Lantern as we
are now, though, and just resolve the domain names when we get them. I
don't believe DNSSEC will work at that point unless it's tunneled just
because it'll be blocked.

**Comment by oxtoacart** [comment]
> We really can just keep sending traffic through Lantern as we
are now, though, and just resolve the domain names when we get them.

I was just saying that if we build in the ability to tunnel DNS lookups and build a DNS cache into the client-side proxy, we could bypass the server proxy for sites that are DNS poisoned but not IP blocked.  If there are a lot these, that would be a big speed and cost improvement over sending both kinds of blocked site through the server proxy.

**Comment by myleshorton** [comment]
> I was just saying that if we build in the ability to tunnel DNS lookups and build a DNS cache into the client-side proxy

Right, but we don't actually need to do anything special to get more DNS traffic to Lantern because we already get the domain names unresolved by the time they hit Lantern. I'm not sure exactly have the caching/lookup/whatever should work at that point though. Lots of options.

**Comment by myleshorton** [comment]
I think we should start with desktop-only for this, as I think doing this on mobile would also likely be interwoven with split-tunneling in general.

**Comment by fffw** [comment]
`detour` only checks the Iran-specific IP address for DNS poisoning detection, which can't be applied generally.

Without reliable way to check for poisoning, it would slow down the access to unblocked sites because of the longer round trip to DNS server.

**Comment by oxtoacart** [comment]
@fffw If the client caches DNS lookups, do you think the performance impact would be that bad?

**Comment by fffw** [comment]
@oxtoacart sounds acceptable. We can also limit the scope to, say, HTTP sites plus the blocked list.

**Comment by oxtoacart** [comment]
@fffw Cool.  Using HTTP keepalives and an optimized encoding, we can probably speed this up quite a bit too.

**Comment by oxtoacart** [comment]
Also, I don't know how typical this is, but just running a quick test on one of our Chinese VPS's showed DNS lookup to be quite slow:

```
ubuntu@VM-255-88-ubuntu:~$ dig www.rimuhosting.com | grep "Query time:"
;; Query time: 378 msec
```

If people's typical DNS servers are similarly slow, I wonder if we might actually be able to accelerate DNS lookups relative to what they're used to?

**Comment by p3rcya** [comment]
@oxtoacart local DNS provided by ISP shouldn't be this slow. 
@myleshorton @oxtoacart Firefly has stopped using host file because of maintenance burden. He is now using the DNS split tunneling as I mentioned before. Let's discuss this throughly before implementing anything

**Comment by joesis** [comment]
Google's [DNS over HTTPS]( https://developers.google.com/speed/public-dns/docs/dns-over-https) (Yeah, saw from Hacker News) seems a good solution than our own DNS proxy. It has `edns_client_subnet` option to get more accurate result. Lantern client just needs to know it's own public IP.

**Comment by oxtoacart** [comment]
@joesis That looks really cool. Note that the `edns_client_subnet` extension could also be queried through the DNS protocol. There's even a Go DNS library that supports it - https://godoc.org/github.com/tonnerre/golang-dns#hdr-EDNS0

**Comment by p3rcya** [comment]
I have to remind everyone that we're actively researching with the cachebrowser team on direct domain fronting. So we might want a host-file style layer to resolve some blocked sites to say akamai directly without ever going through us.  The "host file" can be remotely updated once in a while. Please take this into consideration when building the DNS layer

**Comment by myleshorton** [comment]
Those two are really not mutually exclusive @p3rcya -- the plan is to implement both.

**Comment by myleshorton** [comment]
This is very relevant:

https://github.com/shadowsocks/ChinaDNS

**Comment by myleshorton** [comment]
You might be interested in the above @joesis and @p3rcya

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #313](https://github.com/getlantern/lantern-internal/issues/313) via [**ZenHub**](https://www.zenhub.com/)
