### ISSUE TITLE
Continue to support cross-compilation of flashlight (go-lantern)

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2235]
Once we introduce the new systray support, go-lantern will have native dependencies and won't be cross-compilable using our existing mechanism.

Some options to consider:

* http://www.limitlessfx.com/cross-compile-golang-app-for-windows-from-linux.html
* https://github.com/karalabe/xgo

**Comment by oxtoacart** [comment]
@myleshorton I'm not sure whether this should be Phase 1 or Phase 2.  If it's Phase 2, that means several of us will need to set up VMs with build environments for go-lantern.  I'm spending a little time investigating whether we can make this happen easily enough to include in Phase 1 and save ourselves the headache.

**Comment by fffw** [comment]
We may consider always compile C code as libraries on each OS, and link it from anywhere using the [upcoming {SRCDIR} tag](https://github.com/golang/go/issues/7891) in cgo directive, which is already available if we compile go from newest source. 

It is based on the fact that
*  compiling C code is much slower, and
*  cgo code is relatively steady so we need not compile them each time, and
*  it usually depends on different headers and libraries on each OS which can't be easily setup.

Unfortunately, {SRCDIR} tag will not merge into release until go 1.5, but as a workaround, we can substitute it through build script.

**Comment by oxtoacart** [comment]
@fffw Interesting.  Are you saying that we can link to libraries (static or dynamic(?)) during cross-compilation without doing anything special?

**Comment by oxtoacart** [comment]
@fffw I guess at a minimum having these libraries precompiled wouldn't require us to have all of the headers (like windows.h) available.  That would be a big win.

**Comment by fffw** [comment]
Try github.com/fffw/go-udtwrapper

**Comment by fffw** [comment]
As an example, try `go get github.com/fffw/go-udtwrapper` and modify fd.go, substitute {SRCDIR} at L17 to the **absolute path** of `go-udtwrapper`, and try `GOOS=linux go build` / `gox -os="linux"`.

It doesn't work at this moment, as there's compilation error in go code.

**Comment by oxtoacart** [comment]
@fffw So, I've been playing around with this a little bit in systray, with the Linux version.  I tried building a static library and then linking the Go program to that.  Unfortunately, the static library has references to undefined symbols from the GTK and appindicator libraries.  To make this work, I think I will need to dynamically load those libraries instead.  I'll play around with that.

**Comment by fffw** [comment]
I'm also trying on systray ;-)

**Comment by oxtoacart** [comment]
Cool!  Are you also trying dynamic loading, or a different approach?

**Comment by fffw** [comment]
No clue yet. I'm just trying to understand how linking works on linux.

**Comment by oxtoacart** [comment]
Cool.  Good luck!

**Comment by fffw** [comment]
On Windows, each dll has a lib which acts as a stub, theoretically, we can just put this lib in repo and link to it, then the exe can run on any box which has dll with same binary interface. But on linux, we have to link directly to .so file, even though the only purpose is to consult the symbol table?

**Comment by oxtoacart** [comment]
Yeah, I spent a little time looking into stubs and didn't find anything particularly useful.  It seems like in theory though we should be able to do what you say.

**Comment by oxtoacart** [comment]
This article may be helpful - http://docs.oracle.com/cd/E23824_01/html/819-0690/chapter2-22.html

**Comment by myleshorton** [comment]
You should also be able to compile statically linked shared libraries. On Windows, keep in mind we ultimately support XP SP3, which means we need to build against the v90 platform toolset.

**Comment by oxtoacart** [comment]
@myleshorton How would a statically linked shared library help?

**Comment by myleshorton** [comment]
Oh yeah it looks like you already tried that on Linux. Ignore me. I think for Valencia we can do platform-specific builds but would be great to figure this out in general.

**Comment by oxtoacart** [comment]
I don't think I actually tried a statically linked shared library.  Was just trying to understand what you were thinking to see if we could implement.

**Comment by myleshorton** [comment]
Well theoretically with a fully statically shared shared library you shouldn't have any issues with missing symbols. It's unclear to me how much of the OS libs we'd have to suck in to make that happen though -- might make the libs too large.

**Comment by oxtoacart** [comment]
Ahh, gotcha.  Yeah, the big concern there too would be licensing.  I'm pretty sure we're not allowed to redistribute Windows libraries.  And for Linux, we can distribute them but then we have to abide by the GPL.

**Comment by myleshorton** [comment]
Good point! With the GPL it would probably be fine to license just that
component under the GPL, but I think overall that's probably a deal breaker.

On Tue, Feb 10, 2015 at 10:08 AM, oxtoacart <notifications@github.com>
wrote:

> Ahh, gotcha. Yeah, the big concern there too would be licensing. I'm
> pretty sure we're not allowed to redistribute Windows libraries. And for
> Linux, we can distribute them but then we have to abide by the GPL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2235#issuecomment-73750533>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
We're supporting c

**Comment by oxtoacart** [comment]
We're supporting cross-compilation targeting Windows, but Ubuntu is still outstanding.

**Comment by myleshorton** [comment]
https://github.com/getlantern/lantern-docker-builder is working overall great for me @xiam! Good stuff. The only issue I had is that the built binary for amd64 crashed because it couldn't find the locale. I *think* it's because we have to call genassets.bash to embed the UI with the locale files but not sure.

**Comment by xiam** [comment]
@myleshorton Great! I noticed an issue with the `genassets.bash`, it looks like it's not "remembered" by docker, that's expected, I need to think on it a bit more in order to propose a solution and include it in the build. Meanwhile, do you think we should go on and replace `gox` with `docker`? In a different branch, as part of the docker proposal, of course.

**Comment by myleshorton** [comment]
Interesting idea on replacing ```gox```. What do you see as the main advantage of replacing it? Just using a more vanilla go for the actual build?

**Comment by xiam** [comment]
I think the main advantage is being able to build the whole Lantern
binary for Linux/Windows whether you're on OSX or any Linux distribution,
the only requisite for building a binary that just works would be having
docker, no need to install Go or any -devel  packages by hand.

**Comment by oxtoacart** [comment]
@xiam So you'll run gox on the docker VM to build the OS X and Windows versions?

**Comment by xiam** [comment]
@oxtoacart Technically is not just gox, is a a Go distribution that is ready to create binaries for Windows and Linux, including cgo, that's simple but the interesting thing for Linux is having the systray dependencies (from gcc up to libappindicator and gtk+) in place, in fact, if it weren't for systray we would still be fine with gox as it handles simple cross compilation perfectly. 

The biggest downsize I see is the size of this docker image.

**Comment by oxtoacart** [comment]
I can live with the size thing.  I think doing it all on docker adds some nice repeatability to the build.

**Comment by myleshorton** [comment]
Yeah I agree Ox. Also since we already need Docker for Linux we're paying
that penalty regardless.

We still have to build OS X locally though right? It would be cool if we
could actually run these builds from a fully locked down server instead of
our laptops to minimize the attack surface.

On Monday, March 23, 2015, oxtoacart <notifications@github.com> wrote:

> I can live with the size thing. I think doing it all on docker adds some
> nice repeatability to the build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2235#issuecomment-85198688>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
Oh, good question myles.  Can we get the docker image to build OS X too?

**Comment by xiam** [comment]
@myleshorton We still require OSX to build the darwin version, I'm afraid supporting OSX would not be possible at this time, as systray's CGO bindings depend on libraries that are only available on the OSX world.

**Comment by oxtoacart** [comment]
@xiam Gotcha, thanks.  If we could get dynamically loaded libraries to work on all platforms the way that we already do on Windows, that would make this all a lot easier.

**Comment by xiam** [comment]
Regarding to the locked down server for building, sounds good, we can always use a mac mini!

**Comment by myleshorton** [comment]
> Regarding to the locked down server for building, sounds good, we can always use a mac mini!

Ha yes good point. We actually have one originally in part for this purpose, but it's having issues and needs some fiddling to get back up and running.

**Comment by oxtoacart** [comment]
We could also look at leveraging travis-ci.  Looks like they have an OS X build environment now - http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by myleshorton** [comment]
Ah that would be super cool @oxtoacart. So maybe the process is something like:

1. Auto-trigger builds on travis for every release
1. Have a script that fetches those builds and just signs them for OSX and Windows.

**Comment by xiam** [comment]
Maybe it's time to leave our current `gox` based cross-compilation and try our [docker builder image](https://github.com/getlantern/lantern-docker-builder) instead, I think it's now complete and it does not require installing any -devel dependency.

See https://github.com/getlantern/lantern/issues/2258

**Comment by xiam** [comment]
I created a new branch that will take care of our cross compilation issues: https://github.com/getlantern/flashlight-build/tree/features/make-and-docker

I'm still testing it but I already updated the docs so you may play with it a bit before it gets merged into the main branch.

**Comment by myleshorton** [comment]
Awesome @xiam! I haven't had a chance to play with it since I'm caught up in the proposal, but you want to just submit a PR when you think it's ready? Would be very cool to use this for releasing beta 5!

**Comment by xiam** [comment]
@myleshorton Sure! I've just completed my testing. I think this PR is ready for review: https://github.com/getlantern/flashlight-build/pull/154

**Comment by xiam** [comment]
Cross compilation is supported via Docker and merged into valencia.
