### ISSUE TITLE
Localization in Go app

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2237]
Required for:

#2231 
#2143

**Comment by myleshorton** [comment]
Great point. I get #2143 but why's it required for #2231

**Comment by oxtoacart** [comment]
It's required for #2231 because on Windows, if the user just has IE, we prompt her to please install Chrome.

**Comment by myleshorton** [comment]
Oh right!

On Tue, Feb 10, 2015 at 10:22 AM, oxtoacart <notifications@github.com>
wrote:

> It's required for #2231
> <https://github.com/getlantern/lantern/issues/2231> because on Windows,
> if the user just has IE, we prompt her to please install Chrome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2237#issuecomment-73753297>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
So basically, we want to detect OS display language at startup and show translated text in tray menu and dialog.

There's no standard way to detect display language.

* Mac
`defaults read .GlobalPreferences AppleLanguages`

* Windows
[`GetUserDefaultLocaleName`](https://msdn.microsoft.com/en-us/library/dd318136(VS.85).aspx) for Windows Vista + and [`GetUserDefaultLCID`](https://msdn.microsoft.com/en-us/library/dd318135(VS.85).aspx) for previous versions

* Linux
`locale`

**Comment by fffw** [comment]
I crafted some localisation code based on https://github.com/getlantern/go-lantern/tree/issue-2195. @myleshorton could you grant write permission to me so I can push a new branch?

**Comment by fffw** [comment]
https://github.com/getlantern/go-lantern/tree/issue-2237

```
go build
./go-lantern
```

**Comment by oxtoacart** [comment]
Cool!  Can you please factor the localization stuff into a library?  Also,
I found a library that claims to be able to detect the OS locale -
https://github.com/pivotal-cf-experimental/jibber_jabber.  Can you please
integrate that into your library?

As a side note, jibber_jabber shows a technique of dynamically loading DLLs
on Windows and calling methods on it without using any custom C code.  That
could be really handy for systray in order to support cross-compilation to
Windows.

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by oxtoacart** [comment]
Oh, btw, I've created [tarfs](https://github.com/getlantern/tarfs), which we'll use for embedding resources (including the language files) in our binary.  If you could structure the API of the localization library so that we can feed it data from tarfs, that would be helpful.  Maybe something like a lookup function that takes a locale and returns a byte slice with the corresponding data? `func (locale string) ([]byte, error)`

**Comment by fffw** [comment]
jibber_jabber works. Thank you @oxtoacart! I'd like to use it directly in 'main' as the api is very simple.

It's very neat that tarfs exposes `http.FileStream` interface. https://github.com/getlantern/i18n and maybe other libs can easily interoperate with tarfs now.

Dynamically loading is very useful, although it might not be easy to apply to systray as it has so many syscalls, even callbacks.

**Comment by oxtoacart** [comment]
On Thu, Feb 12, 2015 at 3:21 AM, fffw <notifications@github.com> wrote:

> jibber_jabber works. Thank you @oxtoacart <https://github.com/oxtoacart>!
>
I'm glad!  You're welcome.

> I'd like to use it directly in 'main' as the api is very simple.
>
Is there a reason that anything other than the localization library needs
to know the user's locale? If not, it might be easier just to include it in
your localization library.

> It's very neat that tarfs exposes http.FileStream interface.
> https://github.com/getlantern/i18n and maybe other libs can easily
> interoperate with tarfs now.
>
I'm glad it works. Thanks for code reviewing tarfs!

> Dynamically loading is very useful, although it might not be easy to apply
> to systray as it has so many syscalls, even callbacks.
>
I agree that it would be annoying to reimplement systray using dynamic
loading.  However, the interface to systray itself is relatively
straightforward, so if you provided systray itself as a DLL, we could
interface with that through dynamically loading it without too much trouble
(I think).  The callbacks might be a little hairy though ...

**Comment by fffw** [comment]
> Is there a reason that anything other than the localization library needs
to know the user's locale? If not, it might be easier just to include it in
your localization library.

Hmm you are right.

>  However, the interface to systray itself is relatively
straightforward, so if you provided systray itself as a DLL, we could
interface with that through dynamically loading it without too much trouble
(I think).

Then we have to distribute or embed and extract the DLL.

**Comment by oxtoacart** [comment]
I'll integrate this into flashlight-build to localize the system tray once #2205 has been merged.

**Comment by oxtoacart** [comment]
Nice work @fffw!
