### ISSUE TITLE
Send logs to system-specific locations

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2238]
Instead of sending logs to stdout and stderr, we need to send them to OS-specific locations.

OS X and Linux - use syslog
Windows - ??? (maybe just files, in which case we need to make sure to rotate them)

**Comment by myleshorton** [comment]
So on OSX and Windows we should just use what we're using now since those are the standard locations, i.e.

~/Library/Logs/Lantern
c:\Users\USER\AppData\Roaming\Lantern\logs (different on XP/Vista -- see https://github.com/getlantern/lantern/blob/devel/src/main/java/org/lantern/LanternClientConstants.java#L106)

**Comment by oxtoacart** [comment]
Okay, but if we do that we'll have to add log rotation logic.  My hope was that by using syslog on UNIX and maybe EventLog on Windows, we could avoid that.

**Comment by myleshorton** [comment]
Oh I see. Fine with me on first pass.

On Thu, Feb 12, 2015 at 1:00 PM, oxtoacart <notifications@github.com> wrote:

> Okay, but if we do that we'll have to add log rotation logic. My hope was
> that by using syslog on UNIX and maybe EventLog on Windows, we could avoid
> that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2238#issuecomment-74151657>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@fffw If you look in the valencia-mac branch, you'll find some changes to golog that allow configuring different streams for error and debug.  This is where you can plug in Loggly, so I recommend branching from valencia-mac.

I'm going to go ahead and add a file rotation library so that we can log to files, and then I'll assign this over to you to finish along with the Loggly changes.

**Comment by fffw** [comment]
For flexibility, the api might be something like
`golog.SetOutputs(golog.System, os.Stdout, loggly.New(token), golog.Rotator(dir, prefix, "10M"),...)`

**Comment by oxtoacart** [comment]
I don't think golog should have any dependencies on loggly, and I'm going to make file rotation a separate library.

This can all be handled by composing io.Writer's on top of each other, like this (pseudocode)

```go
outFile := filerotate.New(...)
logglyOut := loggly.NewWriter(...)
out := io.MultiWriters(outFile, logglyOut)
golog.SetOutputs(out, ...)
```

**Comment by fffw** [comment]
That's exatcly what I mean, except that I didn't know `io.MultiWriter` before.
[go-loggly](https://github.com/segmentio/go-loggly) is an `io.Writer`, and https://github.com/dogenzaka/rotator is a decent rotator, which is also an `io.Writer`.

As for Syslog or EventLog, end user might be not easy to submit them to support.

**Comment by oxtoacart** [comment]
[rotator](https://github.com/dogenzaka/rotator) looks perfect!  I was looking for something like that and couldn't find it.

Excellent that go-loggly is just an io.Writer!

I agree that syslog isn't the best option, so I will use files on all platforms.
