### ISSUE TITLE
Save space by not using custom fonts

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2244]
In #2240 we noticed that about half of our web resource weight is fonts (over 1MB compressed).  We should consider switching to a standard font-family like Helvetica to save space.  We need to make sure that works okay for RTL languages like Farsi.

**Comment by oxtoacart** [comment]
@carsonefv suggests "

*Droid Sans Mono* change to *Andale Mono*
*Roboto Thin* change to *Helvetica Light*
*Roboto Light* change to *Helvetica*
*Roboto* change to *Helvetica Bold*
*Roboto Medium* change to *Helvetica Bold*
*Roboto Black* change to *Helvetica Bold*
*Ligature symbols* - Delete?

"

**Comment by myleshorton** [comment]
Awesome! It does look like the ligature symbols are at least referenced in
the CSS but not sure if they're actually used.

On Wednesday, February 18, 2015, oxtoacart <notifications@github.com> wrote:

> @carsonefv <https://github.com/carsonefv> suggests "
>
> *Droid Sans Mono* change to *Andale Mono*
> *Roboto Thin* change to *Helvetica Light*
> *Roboto Light* change to *Helvetica*
> *Roboto* change to *Helvetica Bold*
> *Roboto Medium* change to *Helvetica Bold*
> *Roboto Black* change to *Helvetica Bold*
> *Ligature symbols* - Delete?
>
> "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2244#issuecomment-74905318>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
The ligature symbols appear to be used for our icons at the bottom right.

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by carsonefv** [comment]
Yeah I just realized that too we should keep that if we can

-Carson

**Comment by fffw** [comment]
After swept out Roboto family, Lantern.dmg shrinks from 4.3M to 3.2M.

I tested on OS X, Windows 8 (Chrome and IE 11), Windows XP and Ubuntu 14 and no significant difference found. More thorough visual inspection might be required though.

**Comment by myleshorton** [comment]
Awesome! Great stuff.

On Friday, March 20, 2015, fffw <notifications@github.com> wrote:

> After swept out Roboto family, Lantern.dmg shrinks from 4.3M to 3.2M.
>
> I tested on OS X, Windows 8 (Chrome and IE 11), Windows XP and Ubuntu 14
> and no significant difference found. More thorough visual inspection might
> be required though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2244#issuecomment-84033156>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
