### ISSUE TITLE
Don't use peers rotation

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2245]
Peers are currently still unreliable and they also have various security issues (they see your ip, the see your destination hosts, they see your unencrypted traffic).

I already removed peers from the default configuration - https://github.com/getlantern/flashlight-build/commit/01c9c69ef7fc0c46863c231bf63eea92f4e7628b#diff-51c0f46cacd391b79c1c92419364f220

We need to make sure to do the same for the cloud yaml.

**Comment by myleshorton** [comment]
Wait you removed all peers from the round robin? So no give mode peers get
any traffic again? We just fixed that not long ago. This is the type of
change that needs more discussion. What makes you say they're unreliable?
All the other factors have always been the case since originally adding
peers to domain fronting.

On Wednesday, February 18, 2015, oxtoacart <notifications@github.com> wrote:

> Peers are currently still unreliable and they also have various security
> issues (they see your ip, the see your destination hosts, they see your
> unencrypted traffic).
>
> I already removed peers from the default configuration -
> getlantern/flashlight-build@01c9c69#diff-51c0f46cacd391b79c1c92419364f220
> <https://github.com/getlantern/flashlight-build/commit/01c9c69ef7fc0c46863c231bf63eea92f4e7628b#diff-51c0f46cacd391b79c1c92419364f220>
>
> We need to make sure to do the same for the cloud yaml.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2245>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
> Wait you removed all peers from the round robin? 

No.  I changed the flashlight client to not connect to peers.getiantem.org (see the commit that I referenced).

> So no give mode peers get any traffic again?

No, see above.

> We just fixed that not long ago. This is the type of
change that needs more discussion.

That's why I opened this ticket.

> What makes you say they're unreliable?

Because sometimes when I run flashlight against just peers.getiantem.org I get lots of errors.  By their nature, peers are problematic because they come online and offline much more frequently than fallbacks.  

> All the other factors have always been the case since originally adding peers to domain fronting.

Yes, but that doesn't make them any less problematic.

**Comment by oxtoacart** [comment]
Here's a good example - I was just browsing with peers.getiantem.org.  For a few minutes, it was ducky and even faster than fallbacks because peers are geographically closer to me.  Then bam, stuff started failing:

```bash
enproxy: Failing on Dest: www.google.com:443    ProxyHost: a2703a2eb18acdc31729ac3fd6743add.getiantem.org    Unable to issue write request: Bad response status for read: 524 Origin Time-out
enproxy: Failing on Bad response status for read: 524 Origin Time-out
enproxy: Error reading: unexpected EOF
enproxy: Error reading: unexpected EOF
enproxy: Error reading: unexpected EOF
enproxy: Dest: upload.wikimedia.org:80    ProxyHost: a2703a2eb18acdc31729ac3fd6743add.getiantem.org    Unable to issue read request: Bad response status for read: 524 Origin Time-out
2015/02/18 12:02:08 http: proxy error: Dest: upload.wikimedia.org:80    ProxyHost: a2703a2eb18acdc31729ac3fd6743add.getiantem.org    Unable to issue read request: Bad response status for read: 524 Origin Time-out
balancer: Dialing tcp://clients2.google.com:443 with fronted proxy at peers.getiantem.org:443 using masquerade set cloudflare
```

**Comment by aranhoide** [comment]
From what I gather, this has only been committed to the valencia branch so far, and only affects the client behavior on first startup with no flashlight.yaml.  cloud.yaml will override this.  I think even if we don't go for this, peers should be given a tiny weight in the built-in configuration, so they won't be used for initial setup unless no fallbacks work.

**Comment by oxtoacart** [comment]
> this has only been committed to the valencia branch so far

Correct.  My understanding with the Valencia release was that we wanted to make an excellent first impression on our new Iranian users.  Sending traffic through peers.getiantem.org IMHO interferes with that, both from an actual usage perspective as well as our messaging to users (i.e. the censors can find out your ip and what you're browsing by running some Lantern peers).

**Comment by myleshorton** [comment]
> Wait you removed all peers from the round robin?
> No. I changed the flashlight client to not connect to peers.getiantem.org (see the commit that I referenced).

OK, so they're still in the roundrobin but not getting used, unless cloud.yaml overrides it. I think that's reasonable in the sense that we probably don't want clients essentially hard-coded to use peers.

> 
> So no give mode peers get any traffic again?
> No, see above.

So they won't get any traffic unless again we include them in cloud.yaml (which we currently still do).


> We just fixed that not long ago. This is the type of
> change that needs more discussion.
> That's why I opened this ticket.

OK. I think given that we can just override that in cloud.yaml, and given that we don't really want to use peers particularly during setup and even startup, it's fine.

**Comment by myleshorton** [comment]
> I think even if we don't go for this, peers should be given a tiny weight in the built-in configuration, so they won't be used for initial setup unless no fallbacks work.

Yeah I agree, and that's actually how it works with the QoS header now (i.e. they won't be used for critical services). Long term I think this will be a big area for further work. It's interesting, @oxtoacart that peers worked great for you for awhile -- could be that geographic optimizations for peers could be really useful.

**Comment by oxtoacart** [comment]
> So they won't get any traffic unless again we include them in cloud.yaml (which we currently still do).

Peers are getting traffic from Lantern Java clients.  That won't change no matter what we do with the new Lantern for Valencia.

Also, part of this ticket is to build a new cloud.yaml that doesn't include them.  If we put them in cloud.yaml, that will very quickly override whatever settings came out-of-the-box.  I'll stand by my assertion that if we want our Iranian users to have the best first impression of the Valencia release within the constraints of domain-fronting, we need to keep them away from using peers.

If we decide to keep using peers, we need to majorly fix the messaging on getlantern.org.  For example, right now we say "For users in censored regions itʼs extremely important that you only choose Lantern friends who you really trust. Your Internet traffic will run through those peers. If you add people who you donʼt trust, you run the risk of adding a user who could be monitoring you."

1. Valencia Lantern won't even have friends.

2. Your internet traffic actually runs through completely random peers, and in round robin fashion.  This allows the censors, over time, to monitor everyone like you, including your ip, what sites you access and even the content of all unencrypted sites that you access simply by registering some peers.  That's a really big deal, and right now we're effectively giving users no warning about it.  This is not new, but that doesn't make it right.

**Comment by myleshorton** [comment]
> Peers are getting traffic from Lantern Java clients. That won't change no matter what we do with the new Lantern for Valencia.

Of course, but old clients aside this change eliminates traffic to peers if we also change cloud.yaml.

> Also, part of this ticket is to build a new cloud.yaml that doesn't include them. If we put them in cloud.yaml, that will very quickly override whatever settings came out-of-the-box. I'll stand by my assertion that if we want our Iranian users to have the best first impression of the Valencia release within the constraints of domain-fronting, we need to keep them away from using peers.

This is a change we can make easily at any time, so let's discuss further in person.

> If we decide to keep using peers, we need to majorly fix the messaging on getlantern.org. For example, right now we say

The web team is in the process of redoing a bunch of the copy for the site.

**Comment by oxtoacart** [comment]
> Of course, but old clients aside this change eliminates traffic to peers if we also change cloud.yaml.

No, we would/should create a new version of cloud.yaml for the valencia release.  That doesn't affect old clients.

> This is a change we can make easily at any time, so let's discuss further in person.

My point is that I think we should do this prior to releasing/advertising the Valencia lantern so that people have a great experience from download through first time running.  If people download lantern, run it and get routed through some bad peers, they will have a negative first impression, which is something we can't undo by taking peers out of cloud.yaml at some later time.  As long as discussing further in person will happen before release, I'm cool with that.

> The web team is in the process of redoing a bunch of the copy for the site.

Yes, @chipstehr asking me questions to help with the copy is what got me thinking about this again.  I'm looking forward to reviewing the new copy.

**Comment by oxtoacart** [comment]
> As long as discussing further in person will happen before release, I'm cool with that.

Actually, now that I think about it, I realize that we need to decide this sooner rather than later so that we can QA with a configuration that matches what we'll be pushing to users.  If we're using peers, we should QA with peers.  If we're not, we should not.

**Comment by atavism** [comment]
> No, we would/should create a new version of cloud.yaml for the valencia release. That doesn't affect old clients.

I've been using this already: http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz

**Comment by oxtoacart** [comment]
@atavism Thanks!

**Comment by myleshorton** [comment]
> No, we would/should create a new version of cloud.yaml for the valencia release. That doesn't affect old clients.

Right. I understand that old clients will still exist, but over time as users upgrade this change eliminates all peer traffic. That's all I'm saying.

> My point is that I think we should do this prior to releasing/advertising the Valencia lantern so that people have a great experience from download through first time running. If people download lantern, run it and get routed through some bad peers, they will have a negative first impression, which is something we can't undo by taking peers out of cloud.yaml at some later time. As long as discussing further in person will happen before release, I'm cool with that.

I agree there are reasons to remove peers, but as of now traffic going to peers is a small overall portion of the total, and it's a system we've invested in significantly and have iterated quite a bit on improving through better checks from peerscanner. There's clearly room for improvement, but I do not think eliminating all peer traffic entirely is a requirement for this release.

> Actually, now that I think about it, I realize that we need to decide this sooner rather than later so that we can QA with a configuration that matches what we'll be pushing to users. If we're using peers, we should QA with peers. If we're not, we should not.

Peers are a part of the current Lantern using essentially the same exact overall technique, so if anything this would be a change from what we've already QAed in previous Lantern versions (i.e. it would be a new change with new QA). If we find in practice that peers are truly degrading the user experience, we need to quantify that and come up with a larger strategy before just eliminating them from the mix, but I don't think we should do that prior to discussing it in person.

**Comment by oxtoacart** [comment]
> Right. I understand that old clients will still exist, but over time as users upgrade this change eliminates all peer traffic. That's all I'm saying.

Last week when I asked about supporting upgrades from old Lantern clients, we all agreed that this was an unlikely use case that we wouldn't worry about supporting right now.

> If we find in practice that peers are truly degrading the user experience, we need to quantify that and come up with a larger strategy before just eliminating them from the mix, but I don't think we should do that prior to discussing it in person.

And you're not concerned about the marketability of Lantern once our website copy clearly explains the risks inherent in using it?

**Comment by myleshorton** [comment]
> Last week when I asked about supporting upgrades from old Lantern clients, we all agreed that this was an unlikely use case that we wouldn't worry about supporting right now.

We agreed that it was unlikely old clients in Iran would conflict with new clients in Iran because we don't have that many clients running in Iran.

> And you're not concerned about the marketability of Lantern once our website copy clearly explains the risks inherent in using it?

? We included the feature originally, so no.

**Comment by oxtoacart** [comment]
> We included the feature originally, so no.

We've never clearly explained the impact of it, so I doubt many (if any) users currently understand their exposure.  Unless I'm missing something ...

**Comment by myleshorton** [comment]
> We've never clearly explained the impact of it, so I doubt many (if any) users currently understand their exposure. Unless I'm missing something ...

That's true, although that was more because we just didn't get to it than anything else. Our current messaging describes accessing content through peers up to 4 hops away, however, which is essentially the same.

If we get feedback from users about it being problematic, we should respond to it, but we shouldn't do so preemptively.

**Comment by oxtoacart** [comment]
I've added peers back to the default set of fronted servers - https://github.com/getlantern/flashlight-build/commit/e722299bc8fc62e83a5705da41deca5c5f335e25

By default, there's a 4 to 1 mix of fallback to peer traffic (same as before in Lantern Java).  I strongly encourage you to run the new lantern, update your lantern.yaml to make fallbacks a minor part of the mix (on OS X it's in `~/Library/Application Support/Lantern/lantern.yaml`), point your browser at the proxy at localhost:8787 and spend an hour or more using it.  Then flip it and try browsing with fallbacks dominating the mix.  Meanwhile, look through your console output for `524 Origin Time-out` and other errors.  I'm genuinely curious if the peers experience will compare well with the fallbacks experience.  Do keep in mind that peers will have relatively low latencies for you because they're predominantly in North America and Europe.  They will have higher latencies in the Middle East and definitely in East Asia.

If you are surprised by the browsing experience, keep in mind that most of our testing with Java Lantern went through dedicated fallbacks and never even touched domain fronting unless you explicitly specified the command-line flag `--force-flashlight`.

Regarding the monitoring aspect of peers ...   A succinct statement of the security impact would be something like "If you use Lantern, assume that your national censors know that you're using Lantern, know about some of the sites that you visit with Lantern and can even read some of the content that you browse and post with Lantern."  That would be a clear and accurate warning to include in our FAQ.

Aside from being a boon from the perspective of discovering Lantern user IPs and observing their usage, the peers scheme is also helpful in that it provides censors the ability to see both ends of a portion of your Lantern traffic, which if properly used should allow them to discriminate some of users' Lantern traffic from their other traffic.  I haven't thought it fully through, but this seems like it could be beneficial for fingerprinting and algorithmically blocking Lantern.  Of course that level of sophistication probably isn't necessary since once they have your IP, they can just punitively block you completely for a little while, but it's handy for them to have the option of performing traffic analysis.

**Comment by myleshorton** [comment]
Thanks @oxtoacart! Just to be clear on my pushback -- I'm actually not completely against removing peers, but it's just a really big change in terms of our overall direction and strategy and so just can't be made unilaterally. Will test with just peers for sure!
