### ISSUE TITLE
[feature] Create an update server to replace Equinox

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2246]
Right now, we're using the Equinox.IO platform to distribute our releases.

Thinking on the long run, it may be safer to rely on an update server that we can control.

The Equinox.IO server is not open source, so if we want to deploy a server we have to create it first.

Given that we already have an API for auto-updates and a tool for signing and releasing binaries, creating this server should not be that difficult, as it only has to accept the information the release tool sends and serve data that can be consumed by the autoupdate package.

I guess the most complicated part of the server would be computing binary diffs, but we could use the `bsdiff` command line tool for that, we need a simple and reliable solution and not a full featured service.

This server would be a complementary solution for https://github.com/getlantern/lantern/issues/21

**Comment by oxtoacart** [comment]
One thing that we can do to simplify deployments is to actually just have the release server pull releases from GitHub.  The [GitHub API](https://developer.github.com/v3/repos/releases/) allows accessing releases.  And since these are public releases, the release server doesn't have to authenticate.  This way, we don't need a release tool and don't need to implement an authentication scheme for our update server.

In fact, if we wanted to start a competitor to equinox.io, all we have to do is make the GitHub repo configurable and slap a web UI around this thing :)

Here is a [Go Binding](https://github.com/google/go-github) for the GitHub API. I don't know if this is the best, but it's available.

**Comment by myleshorton** [comment]
Very cool idea on using GitHub releases! The ```GET /repos/:owner/:repo/releases/latest``` is particularly powerful for this.

**Comment by oxtoacart** [comment]
@fffw Here's a bsdiff C library that you could use if you want - https://github.com/mendsley/bsdiff

Never tried it, so I can't vouch for it.

**Comment by xiam** [comment]
Thanks @oxtoacart, I'll try first with bsdiff from command line, as it will allow me to deliver faster than if I wrapped that C library to be used with CGO.

Now, I have studied this problem through the day and compared it to what we already have in the autoupdate client, if we want to use Github to publish our releases we need to make sure we provide enough information, specifically the following details:

* We need a way to tell the release version and to distinguish a new version from an older one.
* We need a way to tell the actual package's target OS and architecture.

Right now [our releases](https://github.com/getlantern/lantern/releases) do not make an extensive use of tags (it seems we only have "latest" and "newer"), in order to be able to tell software versions we'll need to create releases in a very specific way: with each release a tag in the form `vX.Y.Z` must be created and associated to the release.

Also, every asset that is to be uploaded as part of the release must as well have certain information, we need to know the target operating system and architecture the asset was built for, the problem is uploaded files do not have tags, so we only have the file name to store information. In this case, I suggest that the uploaded assets are named under this scheme:

```
lantern-{windows|linux|darwin}-{x86,x64,arm}.{exe|deb|dmg}
```

If we have information on version, operating system and architecture we will be able to compare different versions and generate binary diffs to deliver.

Do you agree on the versioning and the naming scheme?

**Comment by oxtoacart** [comment]
> Thanks @oxtoacart, I'll try first with bsdiff from command line, as it will allow me to deliver faster than if I wrapped that C library to be used with CGO.

Sounds good.  If you want, you can use byteexec to embed the bsdiff program, that way the server program is self-contained.

> Now, I have studied this problem through the day and compared it to what we already have in the autoupdate client, if we want to use Github to publish our releases we need to make sure we provide enough information, specifically the following details:

> * We need a way to tell the release version and to distinguish a new version from an older one.
> * We need a way to tell the actual package's target OS and architecture.

> Right now [our releases](https://github.com/getlantern/lantern/releases) do not make an extensive use of tags (it seems we only have "latest" and "newer"), in order to be able to tell software versions we'll need to create releases in a very specific way: with each release a tag in the form `vX.Y.Z` must be created and associated to the release.

Makes sense.

> Also, every asset that is to be uploaded as part of the release must as well have certain information, we need to know the target operating system and architecture the asset was built for, the problem is uploaded files do not have tags, so we only have the file name to store information. In this case, I suggest that the uploaded assets are named under this scheme:

> ```
lantern-{windows|linux|darwin}-{x86,x64,arm}.{exe|deb|dmg}
```

> If we have information on version, operating system and architecture we will be able to compare different versions and generate binary diffs to deliver.

> Do you agree on the versioning and the naming scheme?

Thanks for asking!  Generally I agree, but there's one issue.  Our regular releases are installers (Windows installer program, Mac DMG, Ubuntu DEB).  For auto-updating, what we actually need are the binaries of the program itself.  Note - on Mac, I'm talking about the lantern executable, not the Lantern.app.

So, I think what actually needs to happen is that we keep our existing release process with the existing naming convention, but also add a parallel release process where we release tagged and properly named versions of the corresponding binaries, which is what the update server can then use to do the updates.

**Comment by xiam** [comment]
> Our regular releases are installers (Windows installer program, Mac DMG, Ubuntu DEB).

@oxtoacart Right, good point, I was missing that. I think we can still deliver `Lantern.{dmg|exe|deb}` installers along with `lantern-{windows|linux|darwin}-{x86,x64,arm}.{exe|bin}` files as assets on the same release, we just need to ignore the installers and that would be easy because they don't need to use the same naming convention. If we're concerned about users getting the binary instead of the installer and getting a poorer user experience we could use a `bin` extension `lantern-{windows|linux|darwin}-{x86,x64,arm}.bin` or some other extension that is not executable in windows/osx.

Using a parallel release is possible too, I think it all comes down at how do we think users will react to having two releases instead of one or different assets instead of just the installers, I prefer the latter option because everything would be tied to one release message and that would make sense to me as a user.

**Comment by oxtoacart** [comment]
+1 on single release with all artifacts. We can tailor the release description to include links to the artifacts that people want to download to help avoid any confusion with the other artifacts.  Naming those other artifacts well would help too, for example:

`autoupdate-binary-windows-x86`.

1. Don't use lantern in the name
2. Don't include an extension so that people can't run the thing (at least not on Windows)

**Comment by xiam** [comment]
The naming scheme without the `lantern` word and without extension sounds good to me!

**Comment by myleshorton** [comment]
One thing to keep in mind here is that our email invites actually link directly to that "latest" tag. So I think as long as we use the actual API call to /repos/:owner/:repo/releases/latest and not our own "latest" tag we should hopefully be in OK shape. Presumably that call sorts releases based on date, and we might have to do something sneaky to make that not always our own "latest" -- not sure.

Does that make sense? I'm just suggesting avoiding polluting our own "latest" tag and making sure that "single release with artifacts" is actually the versioned one that in fact corresponds with the GitHub API call for latest.

**Comment by xiam** [comment]
@myleshorton Makes total sense, I think than won't be a problem as I'll ignore everything that does not follow the naming convention, tags included.

A good thing about all this is that the "lantern" repo is actually separated from "flashlight-build", maybe we can publish releases for users in the "lantern" repo and releases for autoupdate in "flashlight-build", let's that about that after finishing the technical bits.

This is were I'm currently playing around with fake releases: https://github.com/getlantern/autoupdate-server/releases

**Comment by xiam** [comment]
@oxtoacart, @myleshorton I feel pretty confident with the business logic I pushed to the repo so far, I also wrote some tests and I think I've covered everything we need for this to work: signatures, checksums, binary diffs, version comparison, automatic generation of binary diffs based on two different assets, etc.

The last step is to create the http server that uses that business logic, I started using naked net/http but I was wondering if you have any preference for such services, for example http://www.gorillatoolkit.org/pkg/mux or any other package?

I'll only need two paths, /update and /patches, where /update is the endpoints that tells the client how to update (if needed) and /patches would be a standard file server.

**Comment by oxtoacart** [comment]
@xiam Awesome!  I'm looking forward to trying this out.

> I started using naked net/http but I was wondering if you have any preference for such services, for example using http://www.gorillatoolkit.org/pkg/mux or any other package?

I would say that if plain net/http gives you what you need, that's great.  If you need more sophisticated routing, gorilla/mux is a great choice and we already use gorilla/websocket in flashlight so it's consistent with past practice.

**Comment by xiam** [comment]
Yay, I'm ready for a review. 

Please see: https://github.com/getlantern/flashlight-build/pull/55/files

In order to test, you just need to follow these steps:

1. [Run the autoupdate-server](https://github.com/getlantern/flashlight-build/tree/feature/autoupdate/src/github.com/getlantern/autoupdate-server) with the example private key (it will bind to 0.0.0.0:9197).
2. [Run the example program](https://github.com/getlantern/flashlight-build/tree/feature/autoupdate/src/github.com/getlantern/autoupdate/_test_app), it's configured to connect to 127.0.0.1:9197. Updating through a proxy is also supported, but is disabled for this testing.

I would like you to help me reviewing the proposed system, so we can discuss it thoroughly before continuing integrating with flashlight.

Right now this is what we need to add to flashlight to make it work: https://github.com/getlantern/flashlight-build/blob/feature/autoupdate/src/github.com/getlantern/autoupdate/_test_app/main.go.

**Comment by xiam** [comment]
Closed by https://github.com/getlantern/flashlight-build/pull/55
