### ISSUE TITLE
UI not loading on Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2248]
@oxtoacart and @atavism the UI isn't actually loading for me at all on Windows, either on FireFox or Chrome. I've tried the websocket-ox-tweaks branch as well as issue2237

![image](https://cloud.githubusercontent.com/assets/1143966/6307045/87ce7f84-b8ed-11e4-8489-6f2ef4e33dd3.png)

**Comment by myleshorton** [comment]
We're calling the waitforserver utility before launching the browser correct?

**Comment by myleshorton** [comment]
Actually refreshing the browser doesn't bring it up even after Lantern's been running for awhile, so looks like it's something else.

**Comment by oxtoacart** [comment]
@myleshorton Looking into it now.  I bet its a file path issue.

**Comment by atavism** [comment]
@myleshorton I had the same issue. Does the UI code reside in src/github.com/getlantern/ui relative to your current $GOPATH (which should be set to the flashlight-build directory)?

**Comment by oxtoacart** [comment]
PR - https://github.com/getlantern/flashlight-build/pull/70
