### ISSUE TITLE
System tray call for opening Lantern on Windows is creating a command prompt window

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2249]
Need to tweak the arguments in

https://github.com/skratchdot/open-golang/blob/master/open/exec_windows.go

**Comment by oxtoacart** [comment]
@myleshorton It's possible that tweaking arguments may not do it, since it's relying on the shell built-in `start`, so it actually has to start a shell to get it (I think).

**Comment by oxtoacart** [comment]
This StackOverflow thread might provide some insights - http://stackoverflow.com/questions/3677773/how-can-i-run-a-windows-batch-file-but-hide-the-command-window

The vbscript option with wscript.exe seems attractive to me.

**Comment by oxtoacart** [comment]
To elaborate on the vbscript option, we could just have a string in our program that contains the vbscript, extract it temporarily and run it with wscript.exe (which is a gui program and doesn't get a command window).

Actually, in general, using VBScript for doing windows utility tasks seems attractive, as long as we're not doing anything performance critical.

**Comment by myleshorton** [comment]
Thanks for the links @oxtoacart. It actually looks like that build flag isn't working - running a simple test with just go build and flags on windows works with cmd /c start.

**Comment by oxtoacart** [comment]
> It actually looks like that build flag isn't working - running a simple test with just go build and flags on windows works with cmd /c start.

Sorry, don't know what you mean.  Can you please elaborate?

**Comment by myleshorton** [comment]
I'll fiddle with crosscompile to see if I can fix it.

**Comment by oxtoacart** [comment]
> I'll fiddle with crosscompile to see if I can fix it.

Fix what?  Are you seeing a console window when lantern runs?

**Comment by myleshorton** [comment]
Yeah I'm seeing it in both cases. Not you?

**Comment by oxtoacart** [comment]
Checking valencia branch now.

**Comment by oxtoacart** [comment]
Ahh.  What I see is a command prompt popping up briefly and disappearing when I run lantern.  I believe this is the window due to the cmd /S start trick.

What the `-H=windowsgui` linker flag does is prevent the lantern program from having its own persistent console window.  If you compile without that flag, you'll see that when you run lantern you actually get a console that shows the lantern output.

**Comment by oxtoacart** [comment]
@myleshorton 

BTW - here's an example of using a visual basic script to run a shell:

https://github.com/getlantern/flashlight-build/pull/74/files#diff-5e942261b43c8f4431a8248fdd19d520R41

**Comment by myleshorton** [comment]
Right. I'm saying that with that flag and straight go build on windows with a simple test program you don't get the temporary console.

**Comment by oxtoacart** [comment]
Ahh. That's very interesting.

**Comment by oxtoacart** [comment]
So what I'm finding is that if I build without the -H=windowsgui flag, I get the permanent console but not the temporary ones.  It doesn't matter whether I crosscompile from my Mac or build directly on Windows.

It looks like when lantern is built as a gui-mode program, it needs to open a shell to execute the cmd command.

**Comment by fffw** [comment]
Seems `ShellExecuteEx` does the [trick](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776886(v=vs.85).aspx), I'm trying.

**Comment by oxtoacart** [comment]
Implemented - https://github.com/getlantern/flashlight-build/pull/75

**Comment by oxtoacart** [comment]
@fffw - see getlantern/flashlight-build#75

**Comment by fffw** [comment]
@oxtoacart Oh I drafted [another version](https://github.com/getlantern/flashlight-build/commit/7e4cbe6415e878e67f0eb5b18f8f01b88d5be08f) which calls `ShellExecuteW` through lazy loaded dll. It also works. I'm not sure which one is better.

**Comment by fffw** [comment]
Unfortunately `ShellExecuteW` doesn't fit in the `exec.Cmd` model

**Comment by myleshorton** [comment]
That's not the case with straight go build - there it works as I described.
I'll investigate further when I have a sec but sounds like something with
gox.

On Friday, February 20, 2015, oxtoacart <notifications@github.com> wrote:

> So what I'm finding is that if I build without the -H=windowsgui flag, I
> get the permanent console but not the temporary ones. It doesn't matter
> whether I crosscompile from my Mac or build directly on Windows.
>
> It looks like when lantern is built as a gui-mode program, it needs to
> open a shell to execute the cmd command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2249#issuecomment-75349436>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
@myleshorton I've tried `go build` and it still opens command window. `open-golang` actually executes `cmd /C start ...` which will open a new window, only if there's already one it can attach. We got to eliminate it.

**Comment by myleshorton** [comment]
Turns out it wasn't the flag alone (sorry forgot to try all the combos). This is the one that works (look at the exec call):

```
go build -ldflags -H=windowsgui test.go
```

and test.go:

```go
package main

import (
	"os/exec"
)

func main() {
	cmd := exec.Command("rundll32", "url.dll,FileProtocolHandler", "http://www.getlantern.org")
	//cmd := exec.Command("cmd", "/C", "start", "http://www.getlantern.org")
	cmd.Run()
}
```

**Comment by fffw** [comment]
@myleshorton Oh that's super cool. So we found 3 ways and this one is the simplest.

**Comment by myleshorton** [comment]
Yeah sorry I forgot I had switched to that and thought it was just the
linker flag that made it work when it was both.

On Friday, February 20, 2015, fffw <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Oh that's super cool. So we
> found 3 ways and this one is the simplest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2249#issuecomment-75354837>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton That's awesome!  In my testing it works with ./crosscompile too!

**Comment by oxtoacart** [comment]
@myleshorton and @fffw Great work!
