### ISSUE TITLE
detect os version in go

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2252]
We need it for error reporting to Loggly.
@oxtoacart has a great reference  https://groups.google.com/forum/#!topic/golang-nuts/NzEPGqlHIYQ

**Comment by silentmoose** [comment]
Fixed with pull request. the class  getLogInfo.java. This class uses the SystemProperties java util to record all usefull info for logging issues.

**Comment by fffw** [comment]
Thank you @silentmoose for submitting, but this issue is targeting the new go code, not java.

**Comment by silentmoose** [comment]
@fffw ah my apologies. If the formatting was the same couldn't the same file be used for both languages?

**Comment by myleshorton** [comment]
This would be a handy addition!

**Comment by uaalto** [comment]
@myleshorton what do you think about making this an independent library? I think this sort of project can be useful for other people, and this way we might also benefit from more extensive testing and usage by a wider developer base, eventually. Just adding it to https://github.com/avelino/awesome-go would give it some visibility.
We could call it something like __goos-version__, for example.

**Comment by uaalto** [comment]
I think the generic way of doing this resiliently would be to load OS-dependent system library that provides that information. That should be available in every major OS, just as the example provided in above's reference.

**Comment by uaalto** [comment]
I will start with this, as we can always redesign the approach without much effort.

**Comment by myleshorton** [comment]
Yeah that sounds good, and what you describe really matches the GitHub
project I came across that already does this. I can try to dig that up
again if you want.

On Wed, Aug 12, 2015 at 4:58 AM, Ulysses Aalto <notifications@github.com>
wrote:

> I will start with this, as we can always redesign the approach without
> much effort.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2252#issuecomment-130272479>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by uaalto** [comment]
That would be interesting, we might avoid re-inventing the wheel. Do you remember the kind of project it was? Maybe I can try to find it.

**Comment by uaalto** [comment]
I found this: https://github.com/matishsiao/goInfo
This one is using OS-specific command-line utilities. This has the advantage of not needing to load a library that will remain loaded the rest of the program life (although if it is a dynamic library it is probably already loaded).
The problem comes with mobile. On mobile, non-system libraries must be static (iOS at least, Android I think too). Running CLI commands on Android or iOS comes with its own share of problems too, like security policies avoiding you doing such thing.

I think we might need to roll our own solution and go for very specific OS code, trying to solve each case ad-hoc.

**Comment by uaalto** [comment]
I'm going to try first with system calls, which is the most lightweight option, and evolve from there.

**Comment by uaalto** [comment]
WIP [here](https://github.com/getlantern/osversion)

**Comment by myleshorton** [comment]
Nice. Yeah I don't see that library offhand now, but things like this
snippet look valuable too:

https://groups.google.com/forum/#!topic/golang-nuts/NzEPGqlHIYQ

On Wed, Aug 12, 2015 at 8:45 AM, Ulysses Aalto <notifications@github.com>
wrote:

> WIP here <https://github.com/getlantern/osversion>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2252#issuecomment-130348929>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
