### ISSUE TITLE
Map doesn't render in Firefox on OS X

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2254]
Using Firefox 35.0.1.

Chrome and Safari work.

![screen shot 2015-02-22 at 9 05 59 am](https://cloud.githubusercontent.com/assets/5000654/6318992/1ed4c8ea-ba72-11e4-8a39-4a845587ad15.png)

**Comment by oxtoacart** [comment]
This is in the valencia branch, btw.

**Comment by xiam** [comment]
I was about filling this too, it also does not work on Linux.

**Comment by atavism** [comment]
Taking a look now.

**Comment by atavism** [comment]
The map renders fine on the 0.0.12 branch so it's some new change we've introduced that's breaking it.

**Comment by atavism** [comment]
This is fixed here https://github.com/getlantern/flashlight-build/pull/88/files
