### ISSUE TITLE
Need to display Lantern version in footer of UI

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2256]
I just noticed that the UI footer isn't showing the Lantern version.  That'll be handy for debugging in the field.

**Comment by atavism** [comment]
Yeah, this is super simple to display this in the UI: we just need to set the version field in the model. To get the version number, (and any other Lantern configuration details we may need), we could send that over the websocket when it first opens?

**Comment by oxtoacart** [comment]
Sounds good to me.

**Comment by atavism** [comment]
Cool. How does auto-update affect the version number? Do we plan to hard-code the version number in a source file and just increment it whenever a new update is made available?

**Comment by oxtoacart** [comment]
@atavism The version and build date are compiled into the executable and are available here:

https://github.com/getlantern/flashlight-build/blob/valencia/src/github.com/getlantern/flashlight/flashlight.go#L33

On auto-update, we will get a new executable, which has a new version and build date built-in.  After restarting, when the UI connects it will be connected to a process that has that new version.

**Comment by atavism** [comment]
@oxtoacart Thanks!
