### ISSUE TITLE
 Windows Proxy Settings don't work with IE 8 on Windows XP

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2260]
Chrome works fine, but IE doesn't.

![screen shot 2015-02-24 at 9 26 44 am](https://cloud.githubusercontent.com/assets/5000654/6352411/14d989c4-bc08-11e4-9239-f07423392dfc.png)

![screen shot 2015-02-24 at 9 24 48 am](https://cloud.githubusercontent.com/assets/5000654/6352419/2015c258-bc08-11e4-9009-9080f89aaebe.png)

Interestingly enough, the pac url in Internet Settings is blank.

![screen shot 2015-02-24 at 9 27 51 am](https://cloud.githubusercontent.com/assets/5000654/6352409/122ed120-bc08-11e4-9b8f-41d25694ac87.png)

If I manually fill in the pac URL, then IE works.

**Comment by oxtoacart** [comment]
This could be a string encoding issue ...

**Comment by xiam** [comment]
They do work now:

![screen shot 2015-02-24 at 8 34 54 pm](https://cloud.githubusercontent.com/assets/385670/6363932/04cab2d0-bc65-11e4-9473-ff04b616f8d3.png)

Thank you @oxtoacart.

**Comment by oxtoacart** [comment]
@xiam. Thanks for reviewing!
