### ISSUE TITLE
Lantern UI doesn't display in Internet Explorer 8 on Windows XP

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2261]
I'm still on the fence as to whether or not we even want to support IE, but if we are then we'll need to fix this.

![screen shot 2015-02-24 at 9 34 34 am](https://cloud.githubusercontent.com/assets/5000654/6352462/762132a4-bc08-11e4-91a6-24b971f519fe.png)

Additional screenshots:
![screen shot 2015-02-24 at 8 29 20 pm](https://cloud.githubusercontent.com/assets/385670/6363956/7593e39c-bc65-11e4-887e-959033edda00.png)

![screen shot 2015-02-24 at 8 30 57 pm](https://cloud.githubusercontent.com/assets/385670/6363965/8ff1018e-bc65-11e4-88c1-a7fddb5d00c6.png)

**Comment by oxtoacart** [comment]
Duplicate of #2262

**Comment by oxtoacart** [comment]
Oops, not a dupe.

**Comment by oxtoacart** [comment]
Embedding the app folder instead of the dist folder yields some more useful console output.

![screen shot 2015-02-24 at 9 06 56 pm](https://cloud.githubusercontent.com/assets/5000654/6364262/2d4aa48c-bc69-11e4-9e73-c32c1935ef69.png)

If I'm interpreting this correctly, there's a lot of stuff that's going to need to be fixed to get this to run on IE 8.

**Comment by oxtoacart** [comment]
BTW, only 3.61% of the visits to getlantern.org were with Internet Explorer, and of those only 24% were IE versions below 11.  So, only 0.8664% of our visits are from IE versions prior to 11.  If we can get this thing working on 11, I think that might be good enough.

@atavism @myleshorton What do you think?

**Comment by atavism** [comment]
@oxtoacart Yeah, I agree. jQuery 2.0+ and AngularJS 1.1+ don't support IE8 at all which explains all the error messages. We should just try to ensure compatibility with IE 11 initially and definitely display an error message for older versions. I've been testing on 11 and haven't encountered any issues at all so far. I'm going to test on IE10 tomorrow.

**Comment by myleshorton** [comment]
Agreed @oxtoacart and @atavism let's skip IE8!!

**Comment by myleshorton** [comment]
closing!
