### ISSUE TITLE
UI missing resources running Lantern on Windows

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2262]
Steps to reproduce on the valencia branch:

Compile Lantern
```
➜  flashlight-build git:(valencia) ✗ ./crosscompile.bash
Generating UI resources for embedding
Not updating dist folder
Generating resources.go
Now embedding lantern.ico to windows executable
Icon  lantern.ico  ID:  5
fatal: no tag exactly matches 'e9a3560347d7c5d67d3f6a1ec31d37c0c2b0e7f3'
Building flashlight version e9a3560 (20150225.023223)
Number of parallel builds: 8

-->    darwin/amd64: github.com/getlantern/flashlight
Number of parallel builds: 8

-->     windows/386: github.com/getlantern/flashlight
```

Generate Windows executable:
```
Total size:                  4459825 / 12058747 bytes (36.9%)
Succeeded
Windows executable available at lantern.exe
Compressed executable archiveavailable at lantern-installer.exe
```

After running lantern-installer.exe, Lantern appears to install correctly, and the UI opens in my default browser (Chrome), but the UI fails to load certain resources and displays the following:

![image](https://cloud.githubusercontent.com/assets/6346213/6363936/7564cc8a-bc6d-11e4-9bc3-972704621f18.png)

**Comment by oxtoacart** [comment]
@atavism Have you pulled valencia recently?  Earlier today I noticed that we weren't always updating the dist folder when we should have been, so I committed this - https://github.com/getlantern/flashlight-build/commit/9bfdb1a7e9ca9a1f0a70d8df0d4a7d513b3db31b

If you run `UPDATE_DIST=true ./crosscompile.bash` it'll update the dist folder before embedding.  Does that help any?

**Comment by atavism** [comment]
Ah, yeah it does! Thanks. I pulled from valencia a few hours ago, but I'll be sure to run that command from now on while testing. This isn't an issue then. Closing.
