### ISSUE TITLE
User Feedback: Cannot access Google Scholar in Get mode

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#2266]
A user told us via twitter that Lantern was working fine in get mode except that google scholar could not be accessed.  I tried to replicate the problem, and even after inputing scholar.google.com into the proxied sites list, this is the screen i was shown.

![screen shot 2015-02-25 at 11 36 53 am](https://cloud.githubusercontent.com/assets/7864729/6375052/a12b03e6-bce2-11e4-8cf1-8df277d454ea.png)

**Comment by myleshorton** [comment]
This is related to a larger issue with Google flagging too much traffic through our proxies and is not specific to Google Scholar, so closing in favor of the more general issue.
