### ISSUE TITLE
Deceased Lantern systray icons pile up on Windows

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2267]
After stopping Lantern, the systray icon on Windows sticks around until and unless you hover over it.  If you stop and start Lantern multiple times, the icons pile up.

![screen shot 2015-02-25 at 5 55 54 pm](https://cloud.githubusercontent.com/assets/5000654/6383605/e6e855d4-bd17-11e4-94c6-a377678ee57e.png)

**Comment by fffw** [comment]
Oh we didn't remove trayicon while quiting. Let me try it.
