### ISSUE TITLE
Support previous user settings

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2268]
- Enable/disable anonymous usage reporting
- Run Lantern on system startup

This task also involves re-enabling the settings screen in the UI.

**Comment by myleshorton** [comment]
The anonymous usage reporting option should also really be in the setup sequence, so possibly a checkbox on that first page.

**Comment by myleshorton** [comment]
Making this p1 because especially the anonymous usage reporting option really needs to be in there ASAP

**Comment by atavism** [comment]
By first page, do you mean the welcome screen? We could activate the settings screen again and just always show it immediately after the welcome screen/first time the UI is open.

**Comment by atavism** [comment]
@myleshorton Here's what the settings look like on the "Welcome" screen:

![image](https://cloud.githubusercontent.com/assets/6346213/6731151/07853f70-ce19-11e4-92ca-080a3e52a7eb.png)

**Comment by myleshorton** [comment]
Hmn...that kind of seems like a lot of options. What do you think? I feel like it's a little too confusing and might be better in just a second screen.

**Comment by oxtoacart** [comment]
Yeah, I think the critical thing is that we need to ask the run automatically and anonymous usage reporting questions before the facebook and twitter call to action, otherwise the user might follow one of the links and forget to come back to these settings.

**Comment by atavism** [comment]
Yeah, it looks crowded to me. I think just showing the original settings screen after you hit "Continue" (the first time you see this "Welcome" screen) and re-enabling the settings icon would be sufficient?

**Comment by oxtoacart** [comment]
Oh, one other thing - we probably want to default both options to checked, but only actually apply that once the user hits Continue/Accept or whatever the button will be called.

**Comment by myleshorton** [comment]
Yeah that sounds right @oxtoacart. I think it also does make sense to include the settings screen first. In that case though, the naked settings screen as it exists probably won't cut it because we still want to "welcome" the user to Lantern. I saw put those options in the same existing Welcome screen without the Twitter and Facebook images/links and then just show Twitter and Facebook (and remove the settings) when the user hits continue.

How's that sound?

**Comment by atavism** [comment]
That works.

**Comment by myleshorton** [comment]
Hey I think we don't actually support running at system startup yet right @atavism? Fairly easy to add, but maybe we should just remove it for now and ticket it?

**Comment by myleshorton** [comment]
It also doesn't look like the checkbox from the welcome/intro screen is actually working -- only the one from the settings screen after initial startup.

**Comment by atavism** [comment]
> Hey I think we don't actually support running at system startup yet right @atavism? Fairly easy to add, but maybe we should just remove it for now and ticket it?

Yeah, it looked awkward with only one option, and I wasn't sure if we wanted to add an option for turning auto-detection on/off? I took it out for now and ticketed it [here](https://github.com/getlantern/lantern/issues/2344)

> It also doesn't look like the checkbox from the welcome/intro screen is actually working -- only the one from the settings screen after initial startup.

Should be fixed now.

**Comment by myleshorton** [comment]
We should also disable reset for now since that won't do anything, and I don't think we want it to.

**Comment by atavism** [comment]
> We should also disable reset for now since that won't do anything, and I don't think we want it to.

Okay, I removed the reset button also.

**Comment by myleshorton** [comment]
Awesome I'll give it a look thanks!

On Sunday, March 29, 2015, atavism <notifications@github.com> wrote:

> Hey I think we don't actually support running at system startup yet right
> @atavism <https://github.com/atavism>? Fairly easy to add, but maybe we
> should just remove it for now and ticket it?
>
> Yeah, it looked awkward with only one option, and I wasn't sure if we
> wanted to add an option for turning auto-detection on/off? I took it out
> for now and ticketed it here
> <https://github.com/getlantern/lantern/issues/2344>
>
> It also doesn't look like the checkbox from the welcome/intro screen is
> actually working -- only the one from the settings screen after initial
> startup.
>
> Should be fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2268#issuecomment-87454957>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Looking great @atavism! The only other detail I'm wondering about is whether or not it will report statistics before the user has made a selection and/or moved past the initial config setup screen. Does it handle that?

**Comment by atavism** [comment]
@myleshorton Now it does. I added a check to make sure the welcome screen has been seen before any analytics requests are actually sent to the backend. The option is still enabled by default.

**Comment by myleshorton** [comment]
Looking great overall @atavism! The only thing I noticed was that it looks like the checkbox is unchecked at the beginning now.

**Comment by atavism** [comment]
> Looking great overall @atavism! The only thing I noticed was that it looks like the checkbox is unchecked at the beginning now.

Is that after you delete the autoreport entry from lantern.yaml? If that isn't set, it should be enabled by default.

**Comment by myleshorton** [comment]
> Is that after you delete the autoreport entry from lantern.yaml? If that isn't set, it should be enabled by default.

You're right -- it's working. I'll merge. Thanks @atavism!
