### ISSUE TITLE
Add Google domains to whitelist

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2269]
If lantern hits the servers at DO Amsterdam, accessing http://www.google.com will 302 redirect to http://www.google.nl, which is not in our whitelist.

As a workaround, we can treat Google specially and add all its [supported domains](http://www.google.com/supported_domains) to whitelist.

**Comment by oxtoacart** [comment]
@fffw Great find!  Am I correct in saying that this was a problem with the old Lantern too since in Singapore Google redirects to www.google.com.sg?

**Comment by fffw** [comment]
Yes exactly.

**Comment by myleshorton** [comment]
Yeah I like the idea of just adding the supported domains @fffw. You want to add that?

**Comment by fffw** [comment]
Created at PR at https://github.com/getlantern/flashlight-build/pull/105

**Comment by myleshorton** [comment]
Looks like #2274 is blocking this.

**Comment by oxtoacart** [comment]
I merged and uploaded an updated yaml to Amazon.
