### ISSUE TITLE
Tunneling of cloud.yaml failing

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2274]
Mar 01 07:33:01.004 - yamlconf: Custom polling failed: Unable to read yaml from http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz: Unable to fetch cloud config at http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz: Get http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz: http: error connecting to proxy http://localhost:10080: dial tcp 127.0.0.1:10080: connection refused

**Comment by myleshorton** [comment]
Note this only fails on the first attempt. The successive ones succeed after the initial polling interval.

**Comment by myleshorton** [comment]
We need to wait for the proxy to actually be up.

**Comment by oxtoacart** [comment]
@myleshorton This sounds like a P2 at most then, yes?
