### ISSUE TITLE
pac file directing users to port 8787 where nothing's running

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2275]
This means proxying isn't working at all!

**Comment by oxtoacart** [comment]
Port 8787 is the port on which Lantern runs unless you specify a different command-line parameter.  Since users won't be running Lantern from the command-line, I'm bumping this down to a P3.

@myleshorton Sound OK?

**Comment by myleshorton** [comment]
That's not working for me. I get connection refused trying to hit 8787 on 127.0.0.1 after running flashlight with no command-line parameters.

**Comment by oxtoacart** [comment]
@myleshorton Your lantern.yaml probably has a port from a previous time that you can with the command-line parameter.  If you wipe out your lantern.yaml and run again, it should work.

**Comment by myleshorton** [comment]
Yup works! Thanks @oxtoacart

**Comment by oxtoacart** [comment]
@myleshorton I'm reopening as a P3 since this is a little annoying if you do use a different port for whatever reason.  Sound good?

**Comment by myleshorton** [comment]
Yeah that works.
