### ISSUE TITLE
Firewall issue (Lantern 1.5.17-c3feb51)

### ISSUE THREAD

**Issue by zebulon303** [getlantern/lantern#2279]
Althought my UPnP service is on 
![image](https://cloud.githubusercontent.com/assets/1409706/6484185/d7edc8f4-c279-11e4-8a9e-d4385d49d8fd.png)

and that I configured my NAT
![image](https://cloud.githubusercontent.com/assets/1409706/6484222/32ffbb1c-c27a-11e4-9497-84313b8bf86d.png)

I still get the following message
![image](https://cloud.githubusercontent.com/assets/1409706/6484142/860bbbfe-c279-11e4-9593-0bb9a754db38.png)

**Comment by myleshorton** [comment]
Thanks @zebulon303! What version of Lantern are you using? Do you see any traffic on your machine (on the Lantern map)?

**Comment by zebulon303** [comment]
The beta version (which in the title of the issue).
I believe this error came from the windows firewall.
After recreating the rules with the correct port, the message  has
disapeared and everything seems to run fine.

**Comment by myleshorton** [comment]
Whoops sorry missed the title. Very glad it's now working. Lantern should be dynamically adding a firewall rule to allow incoming traffic, but it sounds like that didn't work. Do you see a rule for Lantern in your incoming rules?

**Comment by zebulon303** [comment]
Everything seems to work fine if you install Lantern on a clean system.
In my case I have deleted the firewall rules from previous install, and
when I reinstall lantern it offers me to recreate the rule.

So to answer your question, yes I see the incoming rules.

**Comment by myleshorton** [comment]
Ah I see - that makes sense. We only add the rules at install, so if you deleted them they would only come back after re-install. I'm going to close for now, but feel free to open if there's some nuance I'm missing!

**Comment by zebulon303** [comment]
What you might miss, is IF  the port change between installs, then you
should delete the previous rules. (But I do not know if port changing is a
possibility)
I HAD to delete the rules so they were recreated.

**Comment by myleshorton** [comment]
Thanks @zebulon303. The incoming rules we're adding are for the executable itself and aren't port-specific, so I think we're in good shape there. Thanks again.
