### ISSUE TITLE
Build 32-bit Ubuntu version of Lantern 2.0.0

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2281]
Then add it back to https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions

**Comment by xiam** [comment]
I think that if I continue working on the Docker image for building Lantern for Linux we should be able to close this easily, should I open a new issue for this Docker image?

**Comment by oxtoacart** [comment]
@xiam Yes, a new ticket for the docker stuff sounds good.

**Comment by oxtoacart** [comment]
Done.
