### ISSUE TITLE
Re-enable modified UI for managing proxied sites

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2282]
There's already a UI in place, but:

1. It's currently disabled because it's too slow when displaying all sites

2. To simplify, we want to change it so that users only manage their own proxied sites and the default proxied sites are just taken as a given.

**Comment by myleshorton** [comment]
One thought on this ticket: it might actually be handy to still have a UI here that does two things:

1. Allows manual override
1. Shows the sites the @fffw's getlantern/detour has identified

If we treat "give mode" as just running with nothing on the whitelist, this will give us an interesting debugging tool for our developers living in uncensored regions: i.e. if things appear on our whitelist, it'll signify something's up. As @aranhoide mentioned, false positives are not that big a deal, but having some UI could be handy in terms of providing more transparency into what's going on.

Come to think of it, that's also a really sweet feature for give mode. I.e. most of the time you don't experience any blocking, but if you happen to find yourself on a WiFi network that filters, it'll just seamlessly route around and I think take you out of give mode at the same time! That would be sick. What do you think @oxtoacart, @fffw, @xiam, @atavism, @aranhoide? Would it still be valuable to have some UI here in part to just see which sites Lantern has auto-selected? Wouldn't show in the setup sequence of course, but users in give and get would still be able to access it.

**Comment by myleshorton** [comment]
Decided to skip this on our call. We'll know soon enough if it's something users want.
