### ISSUE TITLE
Seeing a lot of geolookup errors and a lot of ungeolocated instances

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2285]
```
flashlight.geolookup: Unable to get current location: invalid character '<' looking for beginning of value
```

Version 2.0.0-beta1 (20150303.164445)

**Comment by oxtoacart** [comment]
Interestingly this is reporting `clientHost` properties that seem to show flashlight server IPs, for example `128.199.140.127` which is a singapore flashlight server.

**Comment by oxtoacart** [comment]
Oh, the clientHost will always be a proxy server since the client is always connecting to Loggly via a proxy!  This error isn't necessarily an error, since we actually retry the lookup.  I'm just going to knock down the log level on this.

**Comment by oxtoacart** [comment]
I'm not seeing errors on the papertrail logs for geo.getiantem.org, so I'm guessing this error is actually coming from CloudFlare.  I've put in better logging, so whenever we deploy that we'll hopefully get a better idea of what's happening.

**Comment by oxtoacart** [comment]
Leaving open pending results of better logging.

**Comment by myleshorton** [comment]
Any better logging coming in for this @oxtoacart?

**Comment by oxtoacart** [comment]
Yes, the logging seems to be better.  For one thing, we're not seeing that many of these anymore.  For another thing, we're getting details.  Top causes of geolookup errors are:

- net/http: request canceled while waiting for connection
- An existing connection was forcibly closed by the remote host
- The specified network name is no longer available
- ConnectEx tcp: i/o timeout

**Comment by myleshorton** [comment]
I'm going to close this one actually. I think we do see versions of this, but they're so different that I think it makes sense to open a new ticket here.
