### ISSUE TITLE
Loggly not grouping by message

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2287]
For some reason Loggly appears to be unable to correctly interpret the structured data in order to extract and group logs by message. It's working for some logs but not others.

**Comment by oxtoacart** [comment]
I noticed that the messages end in a carriage return - not sure if that's causing it, but might be worth trying to remove that.

**Comment by myleshorton** [comment]
Yeah I noticed that too. The ones that are working have it too though -- I
was actually wondering if they were only working because they included it.

On Thu, Mar 5, 2015 at 4:08 PM, oxtoacart <notifications@github.com> wrote:

> I noticed that the messages end in a carriage return - not sure if that's
> causing it, but might be worth trying to remove that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2287#issuecomment-77379809>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
Is it simply because of length limit? Those messages appear in grouping panel are shorter than those not. In Java logging, `message` are shortened version of `fullMessage`.

To simplify, can we just group by tag (yamlconf, enproxy, balancer, ...) instead of message?

**Comment by myleshorton** [comment]
Yeah it's looks like that's it @fffw -- see https://github.com/getlantern/lantern-common/blob/master/src/main/java/org/lantern/loggly/LogglyMessage.java#L36

Why not just do the same thing? I.e. add a fullMessage field and cap message in exactly the same way?

**Comment by fffw** [comment]
Maybe we can do both. Grouping by the component is more meaningful sometimes. Same message with different remote hosts/ip addresses will result in different groups.

BR,Merlin
