### ISSUE TITLE
If Lantern is started while the network is down, it does not start successfully even after the network comes back up

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2291]
What happens is that all of the masquerade checks fail while the network is down, and when the network comes back up, we're left with no masquerades.

One way to solve this would be to continuously try the masquerades (with a back-off) until we get some that succeed.

**Comment by xiam** [comment]
Woah! This one triggers https://github.com/getlantern/lantern/issues/2357.

```
Jun 02 23:47:18.562 - DEBUG balancer: balancer.go:90 Dialing tcp://emzrprrmagxhtia:80 with (trusted) chained proxy at 188.166.58.16:443
Jun 02 23:47:18.583 - DEBUG balancer: balancer.go:93 Unable to dial tcp://10.4.4.210:443: Bad status code on CONNECT response: 403
Jun 02 23:47:18.584 - DEBUG balancer: balancer.go:90 Dialing tcp://10.4.4.210:443 with (trusted) chained proxy at 188.166.42.231:443
Jun 02 23:47:18.748 - DEBUG balancer: balancer.go:93 Unable to dial tcp://garrggxowpd:80: Bad status code on CONNECT response: 403
Jun 02 23:47:18.748 - DEBUG balancer: balancer.go:90 Dialing tcp://garrggxowpd:80 with (trusted) chained proxy at 188.166.54.156:443
```

Overall it *seems* to be working but some odd logs are showing up, I'm digging more into this one.

**Comment by myleshorton** [comment]
Nice!!

**Comment by xiam** [comment]
I did lots of tests and did not find anything wrong, even if Lantern starts without Internet connection it can recover quickly once the connection is restored.

I'm closing this one but please reopen if you have a new report or if you find a way to reproduce the error.
