### ISSUE TITLE
Re-enable TCP-based give mode peers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2293]
This should include registering them with peerscanner and mapping ports with NAT-PMP/UPnP.

**Comment by oxtoacart** [comment]
#2290 is a prerequisite for this.

**Comment by myleshorton** [comment]
#2290 will be on the other end, though -- i.e. on the get side.

**Comment by oxtoacart** [comment]
@myleshorton For sure.  I was just talking about the piece of actually honoring peer registrations again (which we currently don't do).  Should we open a separate ticket for that?

**Comment by myleshorton** [comment]
Within peerscanner correct @oxtoacart? If so yeah a separate ticket would be awesome.

**Comment by oxtoacart** [comment]
Done - https://github.com/getlantern/lantern/issues/2294

So is this current ticket for porting Give mode functionality to the Go app?  That presumably also needs UI changes (e.g. showing the Give/Get selection screen)?

**Comment by myleshorton** [comment]
On the UI side we could also just implement it in terms of the whitelist -- i.e. just make the whitelist blank for uncensored users. If they add sites to the list, we could then just stop registering them with peerscanner to keep things simple. Either way we need to show a different welcome screen for give mode though -- I'll add a ticket for that.
