### ISSUE TITLE
Don't log UI websocket disconnects or use of closed network connection as error

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2295]
We're currently seeing errors in Loggly like `flashlight.ui: Error reading from UI: websocket: close 1006 unexpected EOF`.  This will happen if the browser is closed, which really isn't an error.  Should change to debug to keep it from polluting the logs.

**Comment by oxtoacart** [comment]
Also `flashlight.ui: Error reading from UI: use of closed network connection`.

**Comment by aranhoide** [comment]
Are these the only scenarios in which these errors show up, or might we silence genuine problems by not logging these as errors anymore?

**Comment by oxtoacart** [comment]
@aranhoide It's always possible that there's a legitimate problem that would cause these, but given that we're talking about connections via the loopback interface, it's very unlikely.

**Comment by fffw** [comment]
Oh it was fixed at https://github.com/getlantern/flashlight-build/commit/f95292a575223d6303582b42b1592314bbef3c94 . Closing.
