### ISSUE TITLE
The first time that I run Lantern after installing on OS X, nothing happens

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2296]
After installing Lantern, I double click to run it. This gives me a message saying "Lantern is an application downloaded from the Internet. Are you sure you want to open it?". When I click "Open", nothing happens. If I double click the Lantern app again, then it runs.

I expect Lantern to run after I click "Open".

**Comment by myleshorton** [comment]
Wow -- big issue -- thanks for noticing/logging.

**Comment by chipstehr** [comment]
I'm getting the same thing from my friend whose downloaded it on Mac in
iran today. She says nothing happens.

**Comment by oxtoacart** [comment]
BTW, I think there are also issues with installing the new Lantern if you already had the old Lantern (and vice versa).  What I'm talking about in this ticket is a clean install.

**Comment by oxtoacart** [comment]
system.log shows

`Mar 11 08:40:36 percymba com.apple.launchd.peruser.502[448] ([0x0-0xf80f8].com.getlantern.lantern[86032]): Exited with code: 2`

**Comment by oxtoacart** [comment]
Interestingly enough, status 2 is not one that we're setting in flashlight.go.

**Comment by oxtoacart** [comment]
On first run, the only stuff that appears in the Lantern log is:

```
Mar 11 13:40:36.270 - i18n: Setting locale en_US
Mar 11 13:40:36.281 - flashlight: ---- flashlight version 2.0.0-beta1 (20150303.164445) ----
```

**Comment by oxtoacart** [comment]
The warning is controlled by the com.apple.quarantine file attribute.  The file attributes can be listed using `xattr -l Lantern.app` and for testing, the quarantine attribute can be set using `xattr -w com.apple.quarantine "0001;54ff06df;Google\x20Chrome;0533EB84-A2CC-43AF-BD10-BE6ACD26200D" Lantern.app `.

**Comment by oxtoacart** [comment]
When running with the quarantine flag, after allowing OS X to open the app, it's passing an extra command-line argument:

`Mar 11 14:22:53.081 - flashlight: Parsing flags from: [/Users/ox.to.a.cart/flbuild/Lantern.app/Contents/MacOS/lantern -psn_0_1122578]`

`flag.Parse()` fails on this and exits.

**Comment by myleshorton** [comment]
Great sleuthing!

On Wed, Mar 11, 2015 at 7:24 AM, oxtoacart <notifications@github.com> wrote:

> When running with the quarantine flag, after allowing OS X to open the
> app, it's passing an extra command-line argument:
>
> Mar 11 14:22:53.081 - flashlight: Parsing flags from:
> [/Users/ox.to.a.cart/flbuild/Lantern.app/Contents/MacOS/lantern
> -psn_0_1122578]
>
> flag.Parse() fails on this and exits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2296#issuecomment-78272523>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
This one's all merged in correct @oxtoacart?

**Comment by oxtoacart** [comment]
Yup.

**Comment by myleshorton** [comment]
For some reason this is happening for me again with beta 2. Adding to beta 3!

**Comment by oxtoacart** [comment]
Yeah, it's not working for me either.

**Comment by oxtoacart** [comment]
Hmm, it looks like the code that fixed this was wiped out by this merge commit - https://github.com/getlantern/flashlight-build/commit/5e87ef15ae8bd1120d9b17791c4c67c94cd24138#diff-f51f873318b593f0a492e1abb11a57c2

@aranhoide What's the background on that merge?
