### ISSUE TITLE
Lantern not starting on OSX 10.7.5

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2297]
Here's the syslog message:

com.apple.launchd.peruser.502[178] ([0x0-0xed0ed].com.getlantern.lantern[3208]): Job appears to have crashed: Segmentation fault: 11

**Comment by oxtoacart** [comment]
Could this be related to #2296?

**Comment by myleshorton** [comment]
Looks like its cocoasudo. This is from building and running on 10.7.

flashlight: Unable to set up pac setting tool: Unable to execute /Users/afisk/Library/Application Support/byteexec/cocoasudo: signal: illegal instruction

**Comment by myleshorton** [comment]
Where did the cocoasudo binary come from @oxtoacart?

**Comment by oxtoacart** [comment]
There's a link in the elevate README - https://github.com/kalikaneko/cocoasudo

**Comment by oxtoacart** [comment]
I think I just compiled it myself.  Perhaps I need to change some settings when compiling it to make sure it's backwards compatible.

Nice work, btw!

**Comment by myleshorton** [comment]
Cool. Looks like there's a link in the elevate README *in flashlight-build*. We have to figure out some way to start pushing this stuff upstream.

**Comment by oxtoacart** [comment]
Oh yeah, I meant to push upstream after our release.  Pushing now.

**Comment by oxtoacart** [comment]
Okay, the initial push got some packages, but failed on others.  The ones that failed are listed below.  I'll work through these and see if I can update gost to make pushing easier.

### bad object error
github.com/getlantern/buuid
github.com/getlantern/bytecounting
github.com/getlantern/chained
github.com/getlantern/cloudflare
github.com/getlantern/deepcopy
github.com/getlantern/fdcount
github.com/getlantern/go-loggly
github.com/getlantern/idletiming
github.com/getlantern/pathreflect
github.com/getlantern/peerscanner
github.com/getlantern/proxiedsites
github.com/getlantern/proxy
github.com/getlantern/systray
github.com/getlantern/tlsdefaults
github.com/getlantern/yamlconf

### branch tip is behind its remote or out of sync
github.com/getlantern/enproxy
github.com/getlantern/lantern-android
github.com/getlantern/lantern-ui

**Comment by oxtoacart** [comment]
Okay, everything has been pushed upstream.  I updated gost to make this a little easier by adding a `-u` option to `gost push`.  README explains it.

**Comment by myleshorton** [comment]
Awesome thanks Ox

On Wednesday, March 11, 2015, oxtoacart <notifications@github.com> wrote:

> Okay, everything has been pushed upstream. I updated gost to make this a
> little easier by adding a -u option to gost push. README explains it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2297#issuecomment-78343911>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
I'll take this ticket.
