### ISSUE TITLE
Investigate whether lantern is consuming unnecessary bandwidth and look into ways to reduce it

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2298]
An Iranian user using 2.0.0-beta1 indicated that Lantern seemed to use a lot of extra bandwidth even when idle, which is a problem for users with metered internet connections (apparently common in Iran(?)).  We should determine what, if anything, is causing this and see if we can improve on it.

Couple of initial things to look into:

- We have various things that run in the background periodically, for example checking for updated cloud.yaml, updating geolocation info, etc.  Perhaps some of these can be better optimized and/or run less frequently.

- The domain-fronting logic speculatively opens multiple connections to the CDN to serve future requests.  After the system goes idle, it stops doing this and only resumes when new traffic comes in from the user agent, but perhaps we're still being too aggressive here.

**Comment by myleshorton** [comment]
We haven't heard anything on this in awhile, so closing for now.
