### ISSUE TITLE
Support excluding sites from proxied sites list at generation time

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2304]

**Comment by myleshorton** [comment]
What's the user story here @oxtoacart?

**Comment by oxtoacart** [comment]
You had asked that we exclude the site `younggirls-sex.com` from the proxied sites list.  On the assumption that we are automatically grabbing updates from firefly, we need a mechanism that allows us to permanently excludes sites, hence the blacklist.

See https://github.com/getlantern/flashlight-build/pull/125

**Comment by myleshorton** [comment]
Makes sense thanks!

**Comment by oxtoacart** [comment]
Now that we're using detour, we no longer generate a proxied sites list.

**Comment by myleshorton** [comment]
Hey @oxtoacart, I think this is fine to close, but we actually do currently
also use a proxied sites list. The idea is that we have a list of sites we
know are blocked, at least in China, so we might as well use that knowledge
instead of incurring detours cost and delay.

**Comment by oxtoacart** [comment]
Thanks @myleshorton
