### ISSUE TITLE
[Refactor Detour] Stop using globals for geolookup and config changes

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2305]
That makes code clutter and difficult to maintain.

**Comment by oxtoacart** [comment]
@fffw I'm not sure I understand the bug.  Can you give an example please?  Is this talking about flashlight in general or just the new detour library?

**Comment by fffw** [comment]
It's not a bug indeed, just a refactor candidate. My comments [here](https://github.com/getlantern/flashlight-build/pull/114/files#r26382195) is the origin of this idea.

**Comment by oxtoacart** [comment]
Got it, thanks.

**Comment by myleshorton** [comment]
Ticketed elsewhere.
