### ISSUE TITLE
yamlconf error in lantern.log

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2307]
Function is not affected, but this error seems odd.

>  Mar 16 01:34:50.370 - yamlconf: Unable to read updated config from disk: Error reading config from /Users/fffw/Library/Application Support/Lantern/lantern.yaml: open /Users/fffw/Library/Application Support/Lantern/lantern.yaml: too many open files

**Comment by oxtoacart** [comment]
Bumping up priority, as too many open files error would also prevent process from accepting new network connections.

**Comment by fffw** [comment]
Seems not caused by Lantern itself.

Lantern opens 100-200 file handles, but `lsof | wc` is > 10000, approaches OS maxfiles limit.
```
 ~ () $ sysctl kern.maxfiles
kern.maxfiles: 12288
 ~ () $ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240
```

**Comment by oxtoacart** [comment]
Ahh, cool!  Bumping back down.

**Comment by fffw** [comment]
Close this one and focus on https://github.com/getlantern/lantern/issues/2330
