### ISSUE TITLE
Lantern 1.5.17 - Able to add invalid site to the proxy list manually

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2309]
![invalid site added](https://cloud.githubusercontent.com/assets/11394369/6670885/82e06102-cc27-11e4-960b-cafafc730fe3.png)

**Comment by atavism** [comment]
It looks like you were able to create an entry for an invalid site, but are you able to hit "Close" and have it saved?

**Comment by sheena3** [comment]
I created the entry, hit update and then closed the browser. Reopened lantern, opened the proxy list and the entry is saved.
