### ISSUE TITLE
Flashlight servers getting taken out of rotation seemingly erroneously

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2310]
This has been an issue off and on for awhile, possibly with a variety of causes, but flashlight servers still seem to be getting taken out of rotation seemingly randomly and aren't making it back in. See, for example:

https://cloud.digitalocean.com/droplets/4194920

**Comment by myleshorton** [comment]
That particular one is in CloudFlare as fl-sg-20150218-088 but nothing else.

**Comment by myleshorton** [comment]
It seems like this might have something to do with the pausing logic. In a random sampling of the following, they all seem to be taken out of rotation and never make it back in:

```
ps-singapore-001:/var/log# grep paused syslog
Mar 17 07:01:55 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-170 (128.199.122.225) paused
Mar 17 07:04:15 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-032 (128.199.130.65) paused
Mar 17 07:43:21 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-128 (128.199.166.58) paused
Mar 17 07:56:53 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-025 (128.199.130.252) paused
Mar 17 09:23:01 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-129 (128.199.103.116) paused
Mar 17 09:25:32 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-026 (128.199.167.245) paused
Mar 17 09:53:28 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-027 (128.199.97.251) paused
Mar 17 10:09:42 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-039 (128.199.211.178) paused
Mar 17 10:44:05 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-018 (128.199.155.166) paused
Mar 17 11:43:53 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-148 (128.199.142.62) paused
Mar 17 12:00:27 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-004 (128.199.155.205) paused
Mar 17 12:02:26 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-040 (128.199.155.215) paused
Mar 17 12:31:47 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-034 (128.199.205.15) paused
Mar 17 12:40:14 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-056 (128.199.122.203) paused
Mar 17 13:11:30 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-167 (128.199.140.127) paused
Mar 17 13:20:46 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-015 (128.199.149.138) paused
Mar 17 13:26:50 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-173 (128.199.134.230) paused
Mar 17 13:36:21 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-131 (128.199.98.29) paused
Mar 17 13:40:13 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-144 (128.199.180.203) paused
Mar 17 13:41:14 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-035 (128.199.89.10) paused
Mar 17 13:41:15 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-008 (128.199.94.146) paused
Mar 17 13:49:54 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-093 (128.199.162.41) paused
Mar 17 13:50:47 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-111 (128.199.205.113) paused
Mar 17 14:05:52 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-002 (128.199.116.72) paused
Mar 17 14:13:42 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-174 (128.199.122.132) paused
Mar 17 14:17:07 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-036 (128.199.89.82) paused
Mar 17 14:26:42 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-160 (128.199.209.175) paused
Mar 17 14:32:22 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-050 (128.199.93.145) paused
Mar 17 15:03:32 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-003 (128.199.244.135) paused
Mar 17 15:15:22 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-028 (128.199.123.91) paused
Mar 17 15:34:56 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-145 (128.199.90.123) paused
Mar 17 15:54:46 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-151 (128.199.148.75) paused
Mar 17 15:56:01 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150219-043 (128.199.89.116) paused
Mar 17 16:14:04 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-120 (128.199.115.139) paused
Mar 17 16:27:42 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-122 (128.199.154.152) paused
Mar 17 17:02:47 ps-singapore-001 peerscanner: peerscanner: fl-sg-20150218-076 (128.199.90.68) paused
```

**Comment by myleshorton** [comment]
Looks like this is the result of breaking out of our registration loop if there's ever a case where we couldn't register:

https://github.com/getlantern/flashlight-build/blob/valencia/src/github.com/getlantern/flashlight/server/server.go#L151

Once that happens and a pause has happened on peerscanner, we'll never get back in.

**Comment by aranhoide** [comment]
That will do it!  Apparently, the purpose of that `return` is to avoid nil reference in the rest of that one:

https://github.com/getlantern/flashlight-build/commit/6eb9a6883bfe4a716c8976eba29581d43920d3e6

So I guess we should just replace `return` with `continue`?

**Comment by myleshorton** [comment]
It looks like some version of this is still happening, but it's likely another version, so closing.

**Comment by myleshorton** [comment]
On second thought let's just keep the same issue open. This still looks like it's happening in some form. See, for example:

https://cloud.digitalocean.com/droplets/4196532
https://cloud.digitalocean.com/droplets/4196623

**Comment by oxtoacart** [comment]
@myleshorton The flashlight executable on both those droplets hasn't been updated since Mar 5, so they don't have @aranhoide's fix yet.  Hence, not surprising that they still exhibit the problem.

**Comment by myleshorton** [comment]
Interesting. Thanks @oxtoacart. So high state failed @aranhoide or what do
you think happened?

On Fri, Mar 20, 2015 at 4:09 PM, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> The flashlight executable
> on both those droplets hasn't been updated since Mar 5, so they don't have
> @aranhoide <https://github.com/aranhoide>'s fix yet. Hence, not
> surprising that they still exhibit the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2310#issuecomment-84181307>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
I've been restarting the flashlight service every two days or so to keep them up, but I hadn't deployed the fix.

As I told you last Thursday, I meant to release the fix from the valencia branch, thus including the multifronting changes too and effectively retiring the current devel branch.  But since that'll take more testing, I'll just make a release out of devel and deploy that.  I'll close this when done.

**Comment by myleshorton** [comment]
Oh cool thanks - forgot about the branching detail.

On Monday, March 23, 2015, aranhoide <notifications@github.com> wrote:

> I've been restarting the flashlight service every two days or so to keep
> them up, but I hadn't deployed the fix.
>
> As I told you last Thursday, I meant to release the fix from the valencia
> branch, thus including the multifronting changes too and effectively
> retiring the current devel branch. But since that'll take more testing,
> I'll just make a release out of devel and deploy that. I'll close this when
> done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2310#issuecomment-85033104>.
>


-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
All deployed.

**Comment by oxtoacart** [comment]
Nice!

**Comment by myleshorton** [comment]
Awesome!
