### ISSUE TITLE
Change peerscanner to make domain-fronted calls and to update cloud.yaml directly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2311]

**Comment by aranhoide** [comment]
[Moving from a comment elsewhere.]

I think checking domain fronting providers and the ratio of peers vs fallbacks could be done in a different service, the responsibility of which would be to update cloud.yaml (as opposed to the DNS/CDN registries, which this service would treat as read-only).

Either way, whoever checks fronting providers only needs test the round robin itself, to make sure that it can proxy through some server via each fronting provider. That would be way cheaper than peerscanner using domain fronting all the time, esp. if we switch to serving domain fronted requests through port 80.

**Comment by myleshorton** [comment]
All good points @aranhoide!

**Comment by myleshorton** [comment]
The other related optimization would be to attach peers to geographic server groups -- i.e. peers are groups with their closest data center or their own group if they're not within x distance from any data center, something like that.
