### ISSUE TITLE
Some users not able to download cloud.yaml

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2313]
Looks particularly prevalent for users in the Philippines, but randomly ".stop" appears to be appended to the cloud.yaml URL.

LogglyNotifications:
json:
extra:
language: en
logLevel: ERROR
country: PH
osName: windows
osArch: 386
version: 2.0.0-beta2 (20150318.205701)
timeZone: CST
fullMessage:
yamlconf: Custom polling failed: Unable to read yaml from https://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz.stop: Unexpected response status: 403
timestamp: 1426783557906
hostname: hidden
locationInfo: yamlconf
message: Unexpected response status: 403
http:
clientHost: 188.166.6.190
contentType: text/plain
Raw Message:

**Comment by oxtoacart** [comment]
LOL!  I bet someone manually updated their configuration file to stop applying cloud.yaml updates by changing the filename to ***.stop.  Removing the filename doesn't work because our code defaults it back.

**Comment by myleshorton** [comment]
Ha! I bet that's right. Hilarious. Interesting that RightsCon is about to start out there. I wonder if we can get people to ask around for us?

**Comment by oxtoacart** [comment]
As a side note, I find it kind of awesome that having an accessible config file format is allowing our users to hack Lantern.  Would be neat to think about ways to harness that for the good of everyone, including perhaps providing ways for people to share their hacks.

**Comment by myleshorton** [comment]
Yeah it's really completely fascinating. It's tempting to keep allowing it just to get a better glimpse into what's going on.

**Comment by myleshorton** [comment]
Looks like this is just those crazy Filipinos =).
