### ISSUE TITLE
Include a GUID in Loggly messages

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2314]
That way we'll be able to tell if a bunch of messages are from the same GUID.

**Comment by oxtoacart** [comment]
We don't have users.  Do you mean the instance id?

**Comment by myleshorton** [comment]
Let's just call it a GUID!

**Comment by oxtoacart** [comment]
Cool.  We already have an instanceid that we use for flashlight servers - https://github.com/getlantern/flashlight-build/blob/valencia/src/github.com/getlantern/flashlight/globals/globals.go#L13

We just need to auto-generate this and save it in the config file, and then we can add it to our Loggly data.

**Comment by myleshorton** [comment]
Oh nice!

**Comment by fffw** [comment]
Closed by https://github.com/getlantern/lantern/pull/2594
