### ISSUE TITLE
Filter duplicate Loggly messages

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2315]
We don't ideally want the client to flood Loggly with multiple copies of the same message.

**Comment by aranhoide** [comment]
Maybe this is getting too much on the fancy side, but what about doing this with some exponential backoff logic?  If something happens a lot that in itself might be useful information.

i.e., we could have a service that keeps a LRU cache of messages, so if a given message gets sent repeatedly, it will only actually forward a summary after the second, fourth, eight, 16th, 32th.... message, appending the count to the message itself.  E.g.

    ...
    error: Couldn't get config.yaml (2048 occurrences) 
    error: Couldn't get config.yaml (4096 occurrences)
    ...

**Comment by fffw** [comment]
Loggly already did a good job to group same message. I think if a message floods, we should either try
1. change our logic so it will not be reported so frequently, or
2. change level to Debug if it's not an error actually.

After that, we can see if we still need to de-duplicate or not.

**Comment by myleshorton** [comment]
If you look at the current logs at https://lantern.loggly.com under the "most recent version" link from the dashboard it's clear why this is a problem. Basically the top two most reported tickets are the same problem over and over again from the same two users, so it makes it very difficult to tell if there are just unique users on unique systems or if the problem is actually widespread.

If we filter duplicates on the client side, then we'll get a much more accurate picture of the actual breadth of problems.

In theory something like what you suggest would be cool @aranhoide, but I don't think we really have a need to do anything fancy here yet. I say we just filter duplicates on the client side and be done with it, as right now it makes our error reporting much less useful.

**Comment by fffw** [comment]
Oh I just found that the rank two message, "too many open files", is reported by my Lantern...

The rank 1 message, "Bad response status for read: 403 Forbidden", is reported for different masquerade host each time. That arises the question of why we test so many masquerades in a batch.

Once we have unique id reported to Loggly, we can quickly figure out if it's a general issue or just occurs for specific user.

**Comment by myleshorton** [comment]
> Once we have unique id reported to Loggly, we can quickly figure out if it's a general issue or just occurs for specific user.

Yeah the big problem with that approach though is that we have to manually check, and the ordering of the bugs will still be a mess. If we filter duplicate messages on the client side, neither one are issues.

**Comment by myleshorton** [comment]
Should be fixed in #2906
