### ISSUE TITLE
Add line number and file name to Loggly logs

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2316]
Not sure if it's possible, but it sure would be useful!

**Comment by atavism** [comment]
The log package has a constant called Lshortfile that can be used to prefix entries with "filename.go:<line_number>" and the runtime package also provides this functionality: http://golang.org/pkg/runtime/

**Comment by oxtoacart** [comment]
@atavism Good call!  Using [Caller](http://golang.org/pkg/runtime/#Caller), we can get the exact line number, and using [Callers](http://golang.org/pkg/runtime/#Callers) we can even get a stack trace if we want it (though I'm inclined to think that a single line number provides more usable output).

**Comment by myleshorton** [comment]
Awesome!

**Comment by myleshorton** [comment]
This is all set too @atavism right?

**Comment by atavism** [comment]
Yep, we can close this.
