### ISSUE TITLE
Lantern continues to download files that are canceled

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2317]
Based on user feedback in lantern-devel

**Comment by oxtoacart** [comment]
You can reproduce with this command:

```curl -x localhost:8787 http://download.thinkbroadband.com/512MB.zip > /dev/null```

Hit ctrl-c to cancel the curl and you'll see that the lantern process is continuing to receive a fair amount of data.

**Comment by xiam** [comment]
I can take a look at this.

**Comment by myleshorton** [comment]
I know @xiam is tied up with the auto-updater and docker issues @fffw if you want to take a stab at this one!

**Comment by xiam** [comment]
Hello @fffw! Were you able to replicate this? I just tested on a Linux box with iftop and it seems to stop downloading right after hitting Ctrl+C.

**Comment by fffw** [comment]
@xiam I can reproduce it occasionally, but not always. Maybe only occurs if we hit some type of servers?

I tried to create a local test environment but failed. From my impression, Lantern servers are not based on executable built from flashlight-build right? Are they running Lantern 1.5.17? @aranhoide

**Comment by aranhoide** [comment]
@fffw domain fronted servers are built from the `devel` branch of flashlight.  But most Lantern traffic in recent (post 2.0-beta3 IIRC) versions goes chained servers, which use the getlantern/lantern project (that is, the 1.x line).

**Comment by fffw** [comment]
Suspected root cause is that [`Close()`](https://github.com/getlantern/flashlight-build/blob/valencia/src/github.com/getlantern/enproxy/conn_intf.go#L266) will not close the enproxy connection and return until HTTP response completes.

A forceful close can resolve it.

**Comment by fffw** [comment]
Finally caught this little damn bug...

**Comment by fffw** [comment]
Reopen for clarification
