### ISSUE TITLE
Lantern 1.5.17 - Shows successful sent message when message is sent from Contact Lantern Developers screen without internet connection

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2318]
I turned off my internet connection. There was a message at the bottom saying that the user appears to be offline. 

I then used contact link and sent a message from the Contact Lantern Developers screen. I received the message "Message sent. Thank you for contacting Team Lantern".

This message is misleading. We either should not let the user to use contact link or should show up appropriate message like "check your internet connection"

![sent message](https://cloud.githubusercontent.com/assets/11394369/6755776/7825d1bc-cf4b-11e4-8cb8-d2e93985ca6b.png)

**Comment by myleshorton** [comment]
Thanks Sheena! I think we probably don't want to open these tickets actually for bugs that only apply to the old version, as all that code will be re-written. The old version is useful for getting a general understanding of Lantern, including what will likely be added back, but we don't want to be opening a bunch of bugs for it at this point.

**Comment by oxtoacart** [comment]
@myleshorton I think @sheena3 is also capturing these sorts of things in her test scripts, which will be helpful for the new version.  Agreed that we probably don't need to capture bugs as long as it's in the test script.
