### ISSUE TITLE
Re-enable Optimizely on the download page

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2323]
We're about to shoot Lantern out in a bunch of new ways, and it would be great to have Optimizely up and running in on the download page.

**Comment by atavism** [comment]
We still have Optimizely enabled on the homepage. So is this just to run some new experiments?

**Comment by myleshorton** [comment]
Yeah exactly!

On Mon, Mar 23, 2015 at 1:10 PM, atavism <notifications@github.com> wrote:

> We still have Optimizely enabled on the homepage. So is this just to run
> some new experiments?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2323#issuecomment-85172824>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
Closing in favor of #2730
