### ISSUE TITLE
Error building pac_cmd on yosemite

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2329]
./run.bash 
~/go/src/github.com/getlantern/flashlight-build/src/github.com/getlantern/flashlight ~/go/src/github.com/getlantern/flashlight-build
# github.com/getlantern/systray
../systray/systray_nonwindows.go:32:10: fatal error: 'errno.h' file not found

**Comment by myleshorton** [comment]
FYI @fffw -- can you take a look at this when you have a chance?

**Comment by fffw** [comment]
It's weird but I can't reproduce it.  `errno.h` is under `/usr/include`, which should theoretically be in the default include path.

**Comment by fffw** [comment]
It's weird but I can't reproduce it.  `errno.h` is under `/usr/include`, which should theoretically be in the default include path.

**Comment by myleshorton** [comment]
Yeah it is odd. Do you have yosemite by chance? For some reason I only got it running the ./run.bash script on yosemite.

**Comment by fffw** [comment]
My Macbook Air is running Yosemite, 10.10.2 (14C1514)

**Comment by myleshorton** [comment]
OK cool -- might be my version of xcode or something. Let's close it for now since it's working for you and presumably others, and I rarely use that particular machine.
