### ISSUE TITLE
UI not opening after install on Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2331]
The UI for beta 3 isn't opening after install on Windows 8.1 for me. The log also is a mess with just:

```
Mar 26 18:46:21.976 - Mar 26 18:46:21.977 - Mar 26 18:46:21.977 - Mar 26 18:46:21.977 - Mar 26 18:46:21.977 - Mar 26 18:46:21.977 - Mar 26 18:46:21.979 - Mar 26 18:46:21.979 - Mar 26 18:46:21.979 - Mar 26 18:46:21.979 - Mar 26 18:46:21.981 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:21.983 - Mar 26 18:46:22.026 - Mar 26 18:46:22.026 - Mar 26 18:46:22.026 - Mar 26 18:46:22.026 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.027 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:22.028 - Mar 26 18:46:2
```

**Comment by atavism** [comment]
It's opening fine for me on 8.1. Is this with Chrome set as your default browser? Did you install with a previous instance of Lantern already running? Does "Show Lantern" work?

**Comment by fffw** [comment]
Finally get my desktop drive repaired and tried. UI is also opening fine for me on 8.1, but the log is indeed messed up. I'll take a look at it.

**Comment by myleshorton** [comment]
Great thanks! I suspect the ui issue is unique to my machine.

**Comment by fffw** [comment]
Log is normal if '-Hwindowsgui' compiler option is removed, or if not using https://github.com/getlantern/wfilter to prepend timestamp to each line of log. It must be caused by some tricky points of handling '\r' and '\n' on Windows.

**Comment by myleshorton** [comment]
OK can u open a separate big for that?

**Comment by fffw** [comment]
@myleshorton Sorry you mean create another issue for the messed log on Windows?

**Comment by myleshorton** [comment]
Yeah exactly

**Comment by fffw** [comment]
Okay, logged a new ticket https://github.com/getlantern/lantern/issues/2354

**Comment by atavism** [comment]
@myleshorton I'm actually encountering the same issue now running the latest version on Windows 8.1: the UI won't open at all. This seems to happen when I try to overwrite a previous Java-based installation of Lantern.

**Comment by myleshorton** [comment]
Oh interesting, so maybe it's related to the old version. Weird. OK let's keep fiddling with it then.

**Comment by atavism** [comment]
This is actually happening when you upgrade to a new beta version as well. I tried overwriting a Beta 3 installation with Beta 5, and the UI stayed the same. I had to uninstall the old version first (by removing "Lantern" from Control Panel) to see the changes actually take effect.

**Comment by myleshorton** [comment]
I'm not getting this anymore -- let's reopen if it appears again.
