### ISSUE TITLE
Can't connect to Lantern

### ISSUE THREAD

**Issue by josh4765** [getlantern/lantern#2335]
i can't connect to roundrobin, fallbacks and peers servers two days ago? are these servers already block at my country(Philippines)?i read so many times in this site and i see this. fl-nl-20150226-018.getiantem.org. how to use that? but i like much roundrobin server for lantern. Can you help me? Please.

**Comment by aranhoide** [comment]
Servers listed as `frontedservers` in your flashlight.yaml (or lantern.yaml, in newer clients) won't work in uncensored countries like the Philippines.  The technique that these servers use was meant for special purposes and as a fallback for when the main techniques are blocked in censored countries, never to serve the bulk of traffic.

Servers listed as `chainedservers` should still work for accessing censored content.

**Comment by josh4765** [comment]
Sorry Sir for the delayed of my reply. 
i downloaded so many times the lantern installer but i can't connect to lantern.
i can't get access or give access. what is the problem here Sir. i hope you can help me

![aw](https://cloud.githubusercontent.com/assets/11416963/7109784/34280248-e15a-11e4-97d4-b9c7c1c6875e.jpg)
