### ISSUE TITLE
UI shows beta 2 instead of beta 3

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2336]
Downloaded the newer beta version. When Lantern opened, it shows beta 2 at the bottom.

![ui shows beta 2](https://cloud.githubusercontent.com/assets/11394369/6872833/d8208dc4-d4d1-11e4-8f50-8bdd74b44519.png)

**Comment by chipstehr** [comment]
For my download on MAC it says beta 3.

**Comment by sheena3** [comment]
This is in Windows

**Comment by myleshorton** [comment]
Thanks @sheena3 -- that was a glitch in our deploy scripts. Deployed on both OSX and Windows now!

**Comment by sheena3** [comment]
It is now changed to beta 3.
