### ISSUE TITLE
Lantern beta 3 is not proxying in case of DNS poisioning

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2337]
I changed the host file to block facebook.com. Unable to access facebook while running beta 3 but able to access the same when running beta 2

**Comment by myleshorton** [comment]
Interesting @sheena3 thanks. I *think* this is because you likely did the following:

1. Had Lantern running
1. Accessed Facebook successfully
1. Changed /etc/hosts
1. Tried to access Facebook again, but it was blocked

If that's correct, the reason is that once Lantern sees Facebook as unblocked, it will consider it unblocked for the rest of that session and won't try to proxy it. So, to run this test with beta 3 you need to:

1. Quit Lantern
1. Change /etc/hosts to DNS poison Facebook
1. Start Lantern
1. See if you can access Facebook (hopefully yes!)

You can also manually see what sites Lantern thinks it can access directly through going to:

http://127.0.0.1:16823/proxy_on.pac

**Comment by sheena3** [comment]
Followed your steps and still couldn't access it.

**Comment by sheena3** [comment]
FYI - I followed the same steps with beta 2 and could access it.

**Comment by myleshorton** [comment]
What does http://127.0.0.1:16823/proxy_on.pac give you?

**Comment by myleshorton** [comment]
I'm actually seeing that as well @sheena3. Any ideas @fffw? Shouldn't it be detecting facebook as blocked in the above sequence, or is it detecting poisoning in some different way?

**Comment by sheena3** [comment]
@myleshorton This is what I see in the proxy_on.pac file.

var bypassDomains = ['disqus.com', 'avatars2.githubusercontent.com', 'collector.githubapp.com', 'cm.g.doubleclick.net', 'fileinfo.disqus.com', 'ad.doubleclick.net', 'www.gstatic.com', 'plus.google.com', 'fileinfo.com', 'collector-cdn.github.com', 'pubads.g.doubleclick.net', 'cloud.githubusercontent.com', 'pixel.quantserve.com', 'tempest.services.disqus.com', 'glitter-services.disqus.com', 'fbstatic-a.akamaihd.net', 'avatars1.githubusercontent.com', 'referrer.disqus.com', 'match.rtbidder.net', 'api.adsnative.com', 'assets-cdn.github.com', 'platform.twitter.com', 'www.google-analytics.com', 'logs-01.loggly.com', 's3.amazonaws.com', 'rp.gwallet.com', 'gmtdmp.mookie1.com', 'clients4.google.com'];
		function FindProxyForURL(url, host) {
			if (host == "localhost" || host == "127.0.0.1") {
				return "DIRECT";
			}
			for (var d in bypassDomains) {
				if (host == bypassDomains[d]) {
					return "DIRECT";
				}
			}
			return "PROXY localhost:8787; DIRECT";
		}

**Comment by myleshorton** [comment]
OK cool thanks @sheena3! By the way, it's incredibly valuable to have you testing all of this. Thanks.

This will give me a good excuse to play with @fffw's nifty detour code, but a definitive answer on this might have to wait for @fffw to come back online.

Sounds like it's working great in Iran regardless though, so it's quite likely it's some glitch with the way we're testing.

**Comment by fffw** [comment]
@sheena3, thanks for testing.

> Change /etc/hosts to DNS poison Facebook

What exact IP address are you setting to DNS poison Facebook? Detection only works if the connection is timed out or reset, so if you are pointing it to, for example, localhost, it will not be detected as connection is just refused and is considered a normal situation.

I found `facebook.com` is listed in proxied sites of `lantern.yaml` but `www.facebook.com` is not, that is why it isn't whitelisted directly. @myleshorton previously we have a optimisation to match primary domain in pac file but what detour does currently is exact match. Should I make that change to detour, or we just cook a more compact but complete proxied site list only for those well known sites?

**Comment by sheena3** [comment]
#Facebook Start
0.0.0.0	5-pct.channel.facebook.com
0.0.0.0	api-read.facebook.com
0.0.0.0	api.facebook.com
0.0.0.0	apps.facebook.com
0.0.0.0	b.static.ak.facebook.com
0.0.0.0	b.static.ak.fbcdn.net
0.0.0.0	bigzipfiles.facebook.com
0.0.0.0	creative.ak.fbcdn.net
0.0.0.0	external.ak.fbcdn.net
0.0.0.0	c.facebook.com
0.0.0.0	chat.facebook.com
0.0.0.0	check4.facebook.com
0.0.0.0	connect.facebook.net
0.0.0.0	creativeupload.facebook.com
0.0.0.0	d.facebook.com
0.0.0.0	developers.facebook.com
0.0.0.0	error.facebook.com
0.0.0.0	facebook.com
0.0.0.0	fbcdn.net
0.0.0.0	fbcdn-profile-a.akamaihd.net
0.0.0.0	fbcdn-sphotos-a.akamaihd.net
0.0.0.0	graph.facebook.com
0.0.0.0	hphotos-ak-snc1.facebook.com
0.0.0.0	hphotos-ak-snc3.facebook.com
0.0.0.0	hphotos-ash4.fbcdn.net
0.0.0.0	hphotos-pao1.fbcdn.net
0.0.0.0	hphotos-snc1.fbcdn.net
0.0.0.0	hphotos-snc3.fbcdn.net
0.0.0.0	hphotos-snc6.fbcdn.net
0.0.0.0	hphotos-snc7.fbcdn.net
0.0.0.0	ldap.thefacebook.com
0.0.0.0	m.facebook.com
0.0.0.0	o.facebook.com
0.0.0.0	orcart.facebook.com
0.0.0.0	photos-ak-ash1.facebook.com
0.0.0.0	photos-ash1.facebook.com
0.0.0.0	pixel.facebook.com
0.0.0.0	profile.ak.facebook.com
0.0.0.0	profile.ak.fbcdn.net
0.0.0.0	s-static.facebook.com
0.0.0.0	s-hprofile-sf2p.fbcdn.net
0.0.0.0	s-static.ak.facebook.com
0.0.0.0	s-static.ak.fbcdn.net
0.0.0.0	secure-media.facebook.com
0.0.0.0	secure-media.fbcdn.net
0.0.0.0	ssl.facebook.com
0.0.0.0	ssl.connect.facebook.com
0.0.0.0	star.facebook.com
0.0.0.0	static.ak.facebook.com
0.0.0.0	static.ak.fbcdn.net
0.0.0.0	upload.facebook.com
0.0.0.0	vpn.tfbnw.net
0.0.0.0	vthumb.ak.fbcdn.net
0.0.0.0	vupload.facebook.com
0.0.0.0	www.connect.facebook.com
0.0.0.0	www.facebook.com
0.0.0.0	zh-CN.facebook.com
#Facebook End

This is what I used for DNS poisioning in the hosts file.  @fffw  Is this a right way to test this functionality?

**Comment by sheena3** [comment]
I used another method but I am not sure if it is right.

Steps:
1. Quit Lantern
2. Change the Preferred DNS server manually(something invalid) in Network and Sharing center in windows
3. After this change, I couldn't access facebook.
4. Now I added the alternate DNS server as 127.0.0.1 which is the Lantern server
5. After this change, I am able to access facebook without launching lantern.

Let me know if it is good to test DNS poisioning.

**Comment by fffw** [comment]
Lantern doesn’t have local DNS resolution feature yet, so the result of step 5 may not related to Lantern at all.




A test method I can think of, is to point all Facebook related domains to a non-existed IP address, such as 255.0.0.1,  in `/etc/hosts`, so it will be timed out rather than connection refused, which is one of the behaviour Lantern can detect.


BR,Merlin

**Comment by sheena3** [comment]
Cool! That works. Closing this issue now
