### ISSUE TITLE
Installer Version shows as beta 1 for Linux -64 bit

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2338]
![version shows as beta 1](https://cloud.githubusercontent.com/assets/11394369/6874721/c9fca846-d476-11e4-9e54-2b08a6e566a7.png)

**Comment by myleshorton** [comment]
Yes none of the linux versions have been updated since beta1.

**Comment by sheena3** [comment]
so shall I stop testing Linux then?

**Comment by myleshorton** [comment]
Yeah beta 3 is definitely more important. We might not update linux at all until beta 4.

**Comment by sheena3** [comment]
Then I guess it would be better if we can tell the user specifically that Linux is not updated since beta 1 because I downloaded beta 1 thinking it is beta 3. 

Anyways, beta 1 is not loading the UI properly when I ran lantern. Is that okay?

**Comment by sheena3** [comment]
![ui not loading in firefox](https://cloud.githubusercontent.com/assets/11394369/6875540/c2bcb0f2-d47c-11e4-92c4-b1f868c7a6b5.png)

**Comment by myleshorton** [comment]
Yeah good idea -- I just updated the Wiki at https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions

Yeah that's definitely a bug @sheena3 -- can you log that one for Linux? Thanks!!!

**Comment by sheena3** [comment]
Closing this issue and opened issue #2339 for Ui not loading in Linux-64
