### ISSUE TITLE
UI is not loading in Linux-64 (version beta 1)

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2339]
![ui not loading in linux-64](https://cloud.githubusercontent.com/assets/11394369/6875707/fedf9ca6-d4e6-11e4-85f3-d2d27716909c.png)

**Comment by fffw** [comment]
It's simply because `lantern-ui` assets didn't get built correctly. The whole `/dist` folder is under repository now, newer betas should not have this error.

**Comment by myleshorton** [comment]
Awesome thanks! I bet That'll also solve the docker problem @fffw.

**Comment by sheena3** [comment]
Is this ready to test now?

**Comment by myleshorton** [comment]
This might actually be fixed in beta 4 @sheena3 - not totally sure.

**Comment by fffw** [comment]
I just realised that the `/dist` directory of `lantern-ui` didn’t get updated at https://github.com/getlantern/flashlight-build/pull/149, so the same issue might recur if didn’t run `gulp build` under `lantern-ui` when build linux version.


BR,Merlin

**Comment by atavism** [comment]
Yes, that was the issue. I've been testing on Ubuntu, and this is working fine now. Assigning to you @sheena3 to verify once we build the beta 5 binaries.

**Comment by myleshorton** [comment]
Is this one still an issue @sheena3?

**Comment by sheena3** [comment]
Sorry @myleshorton, I couldn't check this as I have only Ubuntu 32 bit now. Can you please assign this to someone who has Ubuntu 64 bit?

**Comment by myleshorton** [comment]
Sure! I'll give it a look.

**Comment by myleshorton** [comment]
This works. There are still issues with the welcome screen, however.
