### ISSUE TITLE
Figure out why Lantern is getting flagged by so many AVs in virustotal

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2343]
Looks like miniupnpc itself is flagged inside our outside of Lantern. Does building it separately fix it?

**Comment by myleshorton** [comment]
@fffw this might be another good one to take a look at!

**Comment by myleshorton** [comment]
Would also be interesting to strip the entire whitelist to see if the names/strings in the whitelist affect the AV flags.

**Comment by myleshorton** [comment]
It would also be interesting to test Lantern 1.5.17 in virus total

**Comment by fffw** [comment]
1.5.17 passes [virustotal check](https://www.virustotal.com/en/file/337525011186ed8cd8fd2f616f0471928c4002157d9340e0512ab9baa1e3a291/analysis/1427761296/).

2.0.0-beta3 is reported suspicious by [4 AV software](https://www.virustotal.com/en/file/e3ba8db0e2f40ebd3fc2688f32817a92d84b523538dbd9892623e5e865ab257c/analysis/1427761541/).

After removing most sites from proxiedsites.go, it falls to [1](https://www.virustotal.com/en/file/229ad2a2ad2fa6a2f9c6dd9819da36e150b817c8beb692300c16ce796f098a93/analysis/1427761054/) `a variant of Win32/MiniUPnP.C potentially unsafe`.

@xiam you hit the spot. I'll try the UPnP thing now.

**Comment by myleshorton** [comment]
Awesome! Great insight @xiam!

**Comment by fffw** [comment]
I compiled [miniupnpc](https://github.com/miniupnp/miniupnp/tree/master/miniupnpc) from source, and  ESET-NOD32	still thinks it `a variant of Win32/MiniUPnP.C potentially`(see [report here](https://www.virustotal.com/en/file/03bfa63213aa0b96d74109f8d09d250c73cf88e4511efae1587024fae4dfe72b/analysis/1427766283/)), which is quite normal, as it is indeed MiniUPnP.C.

Maybe we can only leave it as is and document it in FAQ or somewhere else.

**Comment by aranhoide** [comment]
Removing the problematic sites from the whitelist looks like a maintenance burden because we'd need to check for, and fix, AV false alarms whenever we changed the whitelist.  One thing to try would be obfuscating it for installation (e.g. by encrypting it).

**Comment by myleshorton** [comment]
I like it @aranhoide.

On Mon, Mar 30, 2015 at 9:28 PM, aranhoide <notifications@github.com> wrote:

> Removing the problematic sites from the whitelist looks like a maintenance
> burden because we'd need to check for, and fix, AV false alarms whenever we
> changed the whitelist. One thing to try would be obfuscating it for
> installation (e.g. by encrypting it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2343#issuecomment-87934077>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
To keep our code base simple, I’d rather suggest only leave those well known sites and remove others.

Once we have the data of, say, top 100 visited sites from Lantern network, we can just use that list.




We can automate the process of checking against VirusTotal https://github.com/getlantern/lantern/issues/2353.




BR,Merlin

**Comment by myleshorton** [comment]
I think that generally sounds OK, @fffw, although are there any false positives on our current list that you know of? If not, encrypting the whole thing seems pretty darn simple no?

I could go either way on this one honestly, but encrypting it seems just about as easy as weeding through to find the top 100.

**Comment by xiam** [comment]
+1 on encrypting as keeping a list of allowed names would require
additional human time.

José Carlos

**Comment by fffw** [comment]
`Win32/MiniUPnP.C` has been suppressed by compressing the upnpc binary when running `go-bindata`.

But there are still [2 viruses](https://www.virustotal.com/en/file/6aafa593be20d7f2f1f317f16967cbb785c4b9e3cadf7fe3ac8a6359cf529fca/analysis/) reported for binary and [1 virus](https://www.virustotal.com/en/file/c32e77368e70bbe7fec626e8b227d725218732424dcea1cc974e092b5b3f5485/analysis/1428421830/) reported for installer (unsigned). I tried

1. remove most items from proxiedsites.go

2. base64 encode the list

But the result is always the same. So they might be caused by other part of the code base.

**Comment by myleshorton** [comment]
That's certainly a huge improvement @fffw! And go-bindata handles decompressing it no problem?

I think just those two errors might be acceptable actually, as those might be lesser used AV checkers not sure.

I would just submit a PR for the changes you've made so far. Maybe just base64 encoding the list is the simplest for now?

**Comment by fffw** [comment]
`upnpc.exe` is flagged by ~10 AV software, should update it.
