### ISSUE TITLE
Strip out systray code for headless build

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2347]
On Linux, if the box didn't have libappindicator3 package installed, Lantern can't be launched even if we pass `-headless` option to it. 
>  ./lantern_linux: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

Need an compile time option to build headless version.

**Comment by myleshorton** [comment]
Great point @fffw! So we need to build a separate headless binary with each release it sounds like huh?

**Comment by aranhoide** [comment]
I thought if you built lantern using `linuxcompile.bash`, as opposed to just `go build`ing it in the flashlight directory you'd get the libappindicator3 library statically linked into the executable.  Alas, that is not the case.

That library weights some 52KB (and that's the 64bit version), so if linking it statically is an option, I think we should do it by default, just to be on the safe side.  That would remove the need for a separate build.

A headless binary might be interesting if we ever need an even smaller size (we could remove the lantern-ui blob too), but considering that the linux 64bit binary can be compressed down to 2.5MB, it doesn't seem like a pressing issue.

**Comment by aranhoide** [comment]
Just out of curiosity, I tried to build a version with a static libappindicator3 by trying various forms of voodoo I got from a Google search.  Long story short, I couldn't get it to work; I always ended up with the same binary that depended on the .so.  I also suspect that a truly static build would be huge because it would need gtk3 libraries, which may be missing in some linux machines too.  So yes, it may be easiest to just try and make a headless build that strips (at least) systray.

**Comment by atavism** [comment]
@myleshorton Do we want a headless build regardless? It would be nice having an alternative command line version of Lantern that we submit to package repositories anyway. Adding a lantern formula to Homebrew and being able to install it on OS X with ``brew install lantern`` would be nice.

**Comment by aranhoide** [comment]
@atavism : can't you install anything with a UI via brew?

I think currently the main motivation for a headless Lantern is to install it in test boxes that we don't fully control and which don't have the required GTK/libappindicator libraries.

**Comment by xiam** [comment]
What if we include the requires libraries on the `.deb` bundle? Such as Chrome or Firefox do.

A headless build would still be useful, the systray feature only works on Ubuntu + Unity (and maybe XFCE) but it's [not working](https://github.com/getlantern/lantern/issues/2332) on my Fedora desktop (with GNOME3).

**Comment by atavism** [comment]
@aranhoide I think it's definitely rare but probably not prohibited. https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md That said, they also "don’t like tools that upgrade themselves" which would also disqualify us now.

**Comment by fffw** [comment]
I suspect that Homebrew is not been largely used but by programmers. Programmers who use Homebrew can always find a way out right?

I think we don't need to release it currently. Just adding a flag (or a target if we use Makefile) to build for our own use is enough.

Think freely, if we do want Lantern to have a cool look and feel on major OS, we may need to write (or encourage others to write) UI wrapper separately using native language and make the command line core headless. What if people are encouraged to write wrappers for Linux distributions, OpenWRT, XBMC, etc., in both get and given mode, a whole ecosystem around Lantern network. Oh I was thinking too far away...

**Comment by myleshorton** [comment]
Yeah I don't feel strongly either way regarding a separate build versus a flag -- it basically just has to work! The headless build option is kind of handy in that in makes things a little less tied to the specific OS. CentOS should just work, for example, even with the UI if the user knows what port to hit. So I guess I do have a slight preference for the headless option, although at the same time it does significantly increase the total number of builds we deploy. We can figure that side out though. We can close this as soon as https://github.com/getlantern/flashlight-build/pull/153 is reviewed and pulled in.
