### ISSUE TITLE
getlantern.org - The social network icons are not working in Blog page (Windows 7)

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2348]

**Comment by sheena3** [comment]
It doesn't work in Ubuntu too. Probably happens in all the platforms.

**Comment by sheena3** [comment]
verified in windows and Ubuntu.  I don't have access to my Mac now. Can someone check in Mac?

**Comment by atavism** [comment]
@sheena3 Yep, they working for me on Mac now too.
