### ISSUE TITLE
Not getting the Lantern welcome screen after installing and opening the beta 4 in Windows 7

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2356]
After launching lantern, the welcome screen is not displayed. It is taking directly to the main UI.

**Comment by sheena3** [comment]
I tried uninstalling all the versions and then installed the new version. And still I didn't get the welcome screen.

**Comment by myleshorton** [comment]
This is likely because you'd already gone through the welcome screen in a prior version. So it's a little odd in that the state for that is stored in the UI. The only way to get the welcome screen back is to open a new chrome incognito window.

**Comment by myleshorton** [comment]
If you do see it in the incognito window, I'd actually vote for closing this since Lantern's detecting the user has gone through the setup at least once. Then again, it is always nice to have another change to prompt them to post to Twitter/FB. What do you think @atavism?

**Comment by atavism** [comment]
@myleshorton We could set an expiration on the local storage (by storing it with a timestamp) or delete it after a number of sessions if we wanted to show the welcome screen more often. Clicking on "Lantern" in the footer causes it to appear again as well.

**Comment by fffw** [comment]
We can simply check the version against what we written to localstorage
before, and show welcome screen if it's not the same. But when it comes to
auto-update...

**Comment by sheena3** [comment]
I couldn't use the incognito window as the lantern launches a new window rather than opening in the incognito window that I have already opened. 

It works fine in Mac as I don't have older version in that.

 In Windows, I tried uninstalling all the versions and then deleted the Lantern folder under C:\Users\<Username>\AppData\Roaming. Then installed the newer version, still I didn't get the welcome screen. After deleting the folder, I hoped it will consider that I have not used Lantern previously but no luck.

**Comment by aranhoide** [comment]
Try copying the address you get in the window that Lantern launches (e.g.
http://127.0.0.1:16823/) and pasting it in the incognito Window (you may
want to close the one that Lantern opened, just in case; I don't know
whether we support two symultaneous browsers hitting the same backend).

**Comment by atavism** [comment]
> you may
want to close the one that Lantern opened, just in case; I don't know
whether we support two symultaneous browsers hitting the same backend

Yep, that's supported -- it shouldn't be an issue @sheena3 keeping the current window open.

**Comment by sheena3** [comment]
Yep, it works fine. I am able to open in two different browsers as well.

Just my two cents,
@myleshorton I usually get annoyed when I get a window often for rating/sharing in my iphone. Rather it would be nice if we just have an facebook and twitter icon just like we have in the getlantern.org page or as links in the footer . So it is up to the user to share. Also, the user cannot miss to see that.

And when clicking on Lantern in the footer, it would be nice if it takes to the getlantern.org page instead of the sharing screen. I would prefer to remove the link than to use it for displaying the sharing screen.

Closing this issue now.

**Comment by atavism** [comment]
@sheena3 I like your suggestions. I think we need a welcome screen initially, but we should link "Lantern" in our footer to the home page and place the social icons there. What do you think, @myleshorton?

**Comment by myleshorton** [comment]
Yeah that sounds like a great idea @atavism!
