### ISSUE TITLE
[bug] TCP lookups at random addresses

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2357]
I left a Lantern proxy ran overnight:

```
./lantern_linux_amd64 -headless true
```

After a while it started to register some odd TCP lookups at apparently random addresses. Not truly random since they're all appear to be lowercase characters.

```
Apr 03 17:01:01.274 - flashlight.config: Config unchanged in cloud
Apr 03 17:01:32.304 - detour: Dial initially to ojvsgjidmixmfoc:80 failed: dial tcp: lookup ojvsgjidmixmfoc: no such host
2015/04/03 11:01:32 http: proxy error: dial tcp: lookup ojvsgjidmixmfoc: no such host
Apr 03 17:01:32.460 - detour: Dial initially to yeyjkeksthopuhp:80 failed: dial tcp: lookup yeyjkeksthopuhp: no such host
2015/04/03 11:01:32 http: proxy error: dial tcp: lookup yeyjkeksthopuhp: no such host
Apr 03 17:01:32.494 - detour: Dial initially to cdsidvvlpect:80 failed: dial tcp: lookup cdsidvvlpect: no such host
2015/04/03 11:01:32 http: proxy error: dial tcp: lookup cdsidvvlpect: no such host
Apr 03 17:01:35.334 - detour: Dial initially to otbycrepo:80 failed: dial tcp: lookup otbycrepo: no such host
2015/04/03 11:01:35 http: proxy error: dial tcp: lookup otbycrepo: no such host
Apr 03 17:01:35.335 - detour: Dial initially to cqmplend:80 failed: dial tcp: lookup cqmplend: no such host
2015/04/03 11:01:35 http: proxy error: dial tcp: lookup cqmplend: no such host
Apr 03 17:01:35.438 - detour: Dial initially to vyaxvnenrou:80 failed: dial tcp: lookup vyaxvnenrou: no such host
2015/04/03 11:01:35 http: proxy error: dial tcp: lookup vyaxvnenrou: no such host
Apr 03 17:01:41.912 - Apr 03 17:01:41.928 - Apr 03 17:01:42.044 - detour: Dial initially to ztzurai:80 failed: dial tcp: lookup ztzurai: no such host
detour: Dial initially to ihgztngqahxyn:80 failed: dial tcp: lookup ihgztngqahxyn: no such host
2015/04/03 11:01:42 http: proxy error: dial tcp: lookup ztzurai: no such host
detour: Dial initially to psmxqxpaatvixv:80 failed: dial tcp: lookup psmxqxpaatvixv: no such host
2015/04/03 11:01:42 http: proxy error: dial tcp: lookup ihgztngqahxyn: no such host
2015/04/03 11:01:42 http: proxy error: dial tcp: lookup psmxqxpaatvixv: no such host
```

Will try to see if there's a way to trigger this odd reading...

**Comment by fffw** [comment]
It occurs to me when my network changes, e.g., just after connected or disconnected VPN. I guess we can check for invalid host name in client HTTP handler.

**Comment by fffw** [comment]
Below is the trace log
> May 06 02:45:15.117 - flashlight.client: handler.go:29 Reverse proxying HEAD http://nfpnlmilecfsvi/
> May 06 02:45:15.117 - flashlight.client: handler.go:29 Reverse proxying HEAD http://rdkovrmnngepz/
> May 06 02:45:15.117 - flashlight.client: handler.go:29 Reverse proxying HEAD http://gyspwtvqohwakdn/

**Comment by fffw** [comment]
We can't regex it as it can be a valid host actually. Maybe they are some random HTTP request  send by browser or OS to test network connectivity?

**Comment by fffw** [comment]
We can know for sure that it can be generated by Chrome browser. I found below at chrome://net-internals/#events, and dialling attempt to same random hosts in Lantern log about 4s later.

![image](https://cloud.githubusercontent.com/assets/10410437/7721783/e98f98a6-ff0c-11e4-8e9d-b11eb4cb9b6b.png)

**Comment by xiam** [comment]
That's interesting, will try if we can see those when Chrome is not open.

**Comment by xiam** [comment]
Confirmed as a Chrome feature/oddity:

https://isc.sans.edu/diary/Google+Chrome+and+%28weird%29+DNS+requests/10312

**Comment by myleshorton** [comment]
Interesting. That behavior would be somewhat different from what's described in that link though @xiam, as the link describes it purely for DNS. For this to be happening in Lantern Chrome would have to actually be trying to connect to those random addresses, as otherwise they wouldn't go through Lantern at all. It's perfectly possible and maybe even likely that's what's happening, but just to be clear.

**Comment by xiam** [comment]
You're right @myleshorton, the DNS query does not passes through Lantern so strictly speaking that's an unrelated problem. In order to complete relate that DNS problem to the log we were seeing we can analyse the network and see if a relation can be found.

This is the first interesting log is the random DNS request, the number we see at the leftmost column is the packet number and based on that value we can tell the order of the requests.

![screen shot 2015-06-03 at 12 01 25 pm](https://cloud.githubusercontent.com/assets/385670/7966298/c77b553e-09e8-11e5-95ae-d28b9b4cb6a1.png)

The second extract is the HEAD request that we were seeing in Lantern

![screen shot 2015-06-03 at 12 02 05 pm](https://cloud.githubusercontent.com/assets/385670/7966290/c1686cf4-09e8-11e5-9f86-29b63d565b33.png)

and which produces the following log:

```
Jun 03 17:00:55.613 - DEBUG detour: detour.go:131 Dial initially to accznase:80 failed: dial tcp: lookup accznase: no such host
Jun 03 17:00:55.613 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup accznase: no such host
Jun 03 17:00:55.628 - DEBUG detour: detour.go:131 Dial initially to xxeoaztw:80 failed: dial tcp: lookup xxeoaztw: no such host
Jun 03 17:00:55.628 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup xxeoaztw: no such host
Jun 03 17:00:55.880 - DEBUG detour: detour.go:131 Dial initially to sluwvkocntfpzk:80 failed: dial tcp: lookup sluwvkocntfpzk: no such host
Jun 03 17:00:55.880 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup sluwvkocntfpzk: no such host
```

I did a second capture just to be this was not a coincidence:

![screen shot 2015-06-03 at 11 59 54 am](https://cloud.githubusercontent.com/assets/385670/7966301/cdab8708-09e8-11e5-902c-7baa32b33da3.png)

![screen shot 2015-06-03 at 11 59 13 am](https://cloud.githubusercontent.com/assets/385670/7966303/d2d056f0-09e8-11e5-9d2a-9ac74d15f9be.png)

```

Jun 03 16:58:35.251 - DEBUG detour: detour.go:131 Dial initially to wojdwhvlyegd:80 failed: dial tcp: lookup wojdwhvlyegd: no such host
Jun 03 16:58:35.251 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup wojdwhvlyegd: no such host
Jun 03 16:58:35.273 - DEBUG detour: detour.go:131 Dial initially to askkkkx:80 failed: dial tcp: lookup askkkkx: no such host
Jun 03 16:58:35.273 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup askkkkx: no such host
Jun 03 16:58:35.297 - DEBUG detour: detour.go:131 Dial initially to bdivqkoiujtwkau:80 failed: dial tcp: lookup bdivqkoiujtwkau: no such host
Jun 03 16:58:35.297 - ERROR flashlight.client: reverseproxy.go:186 http: proxy error: dial tcp: lookup bdivqkoiujtwkau: no such host
```

Some other users have also reported weird DNS queries with Chrome:

https://productforums.google.com/forum/#!topic/chrome/dQ92XhrDjfk
https://code.google.com/p/chromium/issues/detail?id=363580

**Comment by myleshorton** [comment]
Very cool @xiam -- thanks for digging deeper on it. So it looks like Chrome is, in fact, trying to make an actual connection as well. That makes sense especially given that it's a HEAD request. Great sleuthing!
