### ISSUE TITLE
User destination is not shown correctly in map

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2359]
Accessing from India but displays Pakistan.

![shows pakistan in map](https://cloud.githubusercontent.com/assets/11394369/6986698/71df4ece-da5d-11e4-8219-d43d84133bc7.png)

**Comment by sheena3** [comment]
The issue is only with Windows. It is good in Mac.

![shows india](https://cloud.githubusercontent.com/assets/11394369/6987288/675ecd7a-da63-11e4-9ac9-2f772e123a4f.png)

**Comment by fffw** [comment]
Is that just because the IP address of your Windows box is considered in an network segment of Pakistan?Sometimes, the data is out-of-date.




To make sure, just visit http://geo.getiantem.org/lookup/<your IP address>


BR,Merlin

**Comment by myleshorton** [comment]
Yeah the data will just be wrong every once in awhile. We could upgrade to the actual maxmind city database instead of city light, but not sure how much that'll help:

https://www.maxmind.com/en/geoip2-city

I say we close for now, as we already have the most up-to-date free data we can get.

**Comment by myleshorton** [comment]
Although that is odd it's different on different OSes. Can you try this one more time and confirm that's still the case @sheena3? Re-opening.

**Comment by sheena3** [comment]
It is working fine now. Closing.
