### ISSUE TITLE
[refactor] Remove enproxy/conn_http.go from production code

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2361]
[enproxy/conn_http.go](https://github.com/getlantern/enproxy/blob/master/conn_http.go) is only used by its own test example, most of the code is copied to [flashlight/client/handler.go](https://github.com/getlantern/flashlight/blob/master/client/handler.go) in production.

It would better to move `conn_http.go` to the test example, as it is not relevant to enproxy's functionality.

**Comment by myleshorton** [comment]
Yup good catch @fffw. Any easy win to simplify enproxy we should do in my book! If you want to submit a quick PR we can make the change.
