### ISSUE TITLE
Can we consolidate flashlight and lantern mobile more

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2363]
Particularly the cloud.yaml.

**Comment by atavism** [comment]
@myleshorton @xiam I think it's important we get to this sooner (i.e. this week before we release FireTweet). We want to avoid maintaining two codebases that have the potential to diverge, and we especially want FireTweet synchronized with flashlight proper. Thanks to the improved modularity of  flashlight in the valencia release, there's a significant amount of duplicated code in the lantern android library (particularly shared packages like analytics, balancer, chained, fronted, client, etc.) we can consolidate and/or remove now. 

I took a first-pass at this in the firetweet branch, and it seems to be working fine so far. If there are no objections, I'll keep moving ahead with this and assign the PR to you, @xiam.
```
04-06 22:15:45.430    1268-1268/? V/DEBUG﹕ Attempt to run client proxy on :9192
04-06 22:15:45.437    1268-1286/? I/GoStdio﹕ flashlight.client: Configure() called
04-06 22:15:45.438    1268-1286/? I/GoStdio﹕ flashlight.client: Client configuration initialized
04-06 22:15:45.438    1268-1286/? I/GoStdio﹕ flashlight.client: Requiring minimum QOS of 0
04-06 22:15:45.439    1268-1286/? I/GoStdio﹕ flashlight.client: Adding 2 domain fronted servers
04-06 22:15:45.440    1268-1286/? I/GoStdio﹕ fronted: Verifying up to 20 masquerades
04-06 22:15:45.440    1268-1286/? I/GoStdio﹕ connpool: Starting connection pool with size 30
04-06 22:15:45.443    1268-1286/? I/GoStdio﹕ fronted: Verifying up to 20 masquerades
04-06 22:15:45.443    1268-1286/? I/GoStdio﹕ connpool: Starting connection pool with size 30
04-06 22:15:45.459    1268-1286/? I/GoStdio﹕ flashlight.client: Adding 75 chained servers
04-06 22:15:45.471    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:45.498    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:45.507    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:45.616    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:45.966    1268-1287/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:45.967    1268-1287/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.542    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.542    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.542    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.543    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.543    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.543    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.543    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.543    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.854    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.854    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.854    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.854    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.855    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.855    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.855    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:46.855    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.150    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.150    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.151    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.151    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.151    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.151    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.152    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.218    1268-1286/? I/GoStdio﹕ flashlight.client: Building dialer
04-06 22:15:47.471    1268-1285/? E/GoStdio﹕ fronted: HTTP ERROR FOR MASQUERADE goud.ma: Head http://www.google.com/humans.txt: Unable to dial proxy: Unable to dial proxy: Unable to dial masquerade goud.ma: x509: certificate is valid for ssl93578.cloudflare.com, *.allenviewturf.com.au, *.blakebrasher.org, *.cege.com, *.fresh.bz, *.geekslife.com, *.imghax.com, *.micromarketmonitor.com, *.on2url.net, *.primemmog.com, *.psychictoday.com.au, *.rentthegames.ca, *.sc-114.com, *.sizeitup.com, *.viralmo.com, allenviewturf.com.au, blakebrasher.org, cege.com, fresh.bz, geekslife.com, imghax.com, micromarketmonitor.com, on2url.net, primemmog.com, psychictoday.com.au, rentthegames.ca, sc-114.com, sizeitup.com, viralmo.com, not goud.ma=
```

**Comment by myleshorton** [comment]
I think that sounds wise @atavism. I haven't been as deeply involved in this code, though, so I'll defer to @xiam to weigh in as well. What do you think @xiam?

**Comment by myleshorton** [comment]
The main thing to be aware of @atavism, and the reason there's some duplication in lantern-android, is the fact that a number of libraries from flashlight proper complicate the android build. In particular things like upnp and nat-pmp need some re-working. Given that lantern-android is currently get mode only and like will remain get mode only for some time while lantern on desktops will not, that's just something to be cognizant of as we integrate lantern-android more with flashlight proper.

**Comment by atavism** [comment]
@myleshorton It hasn't been an issue since we're only building what we need from the client side. We aren't doing anything with go-igdman which embeds upnp and nat-pmp. A lot of the duplicated functionality (balancer, chained, etc.) doesn't touch any of that server-side code.

**Comment by myleshorton** [comment]
Oh wow I forgot that was all in there before even balancer and chained were merged in. Yeah I agree it would be good to get FireTweet running on that base architecture.

**Comment by xiam** [comment]
I recall my first attempt was fixing this with build tags on the same codebase, and we ended up ditching all that because it was becoming far too complex. But it was based on code for another branch.

Things may be easier now with the valencia branch, but we'll still have some problems derived from things we don't really need on Android, such as parsing flags, systray stuff, auto-updates (they won't even work), other thing was that flashlight required writing configuration files to disk and that was not trivially possible with Android. So it may be easier, but we'll probably end up adding a lot of conditional build tags again (and Go source files for supporting those build tags), just like my first attempt.

I think we should start thinking and working on this on this right now, but I don't think we can have this completely sorted by the end of this week, maybe we can make a proper list of problems, discuss them and devise a plan.

The good thing about lantern-android and FireTweet is that they're completely independent from each other and we could replace the lantern-android backend anytime without changing Android code.

I think releasing FireTweet would have a bigger impact than having a single codebase for flashlight-build, so we could keep on focusing on FireTweet and only add the things that are strictly required in lantern-android in order to make FireTweet faster. Having a single code base would definitely benefit us as Lantern developers, but it's not as easy as it may look and it would probably delay FireTweet for our users.

I'll start with this list, maybe the problem is not as big as it seems. In the meantime I suggest we keep using lantern-android for FireTweet, and just add the strictly required features from flashlight-build, such as logging with loggly and geolocation.

What do you think @atavism, @myleshorton?

**Comment by atavism** [comment]
@xiam Sounds good to me. Why do you think this will take awhile though? I already removed a lot of the duplicated functionality in the flashlight-build firetweet branch. Have a look here: https://github.com/getlantern/flashlight-build/tree/firetweet/src/github.com/getlantern/lantern-android/client  This builds the shared library successfully; it's working with the sample project and in FireTweet.

**Comment by myleshorton** [comment]
Great point on the parsing flags, systray, auto-updates, and config files fronts @xiam. I don't see your commits in the firetweet branch touching any of that, though, @atavism, and they still work? I'm surprised particularly that the systray code path doesn't cause some crash, so maybe everything's just a bit better setup now?

**Comment by xiam** [comment]
@atavism Awesome cleaning! I was thinking of a single codebase integrated into flashlight-build directly using build tags (no extra directory, and no code duplication at all). That would be a bit more difficult as we'll have to introduce a lot of conditional compilating tricks. If we keep lantern-android isolated into a different space (a directory or a different repo) that would allow us to keep on going while thinking on how are we going to create a single code base (if that's necessary).

**Comment by xiam** [comment]
I think we'll also need to do this code consolidation for Lantern PI, at some point. It won't be as difficult as with Android since we won't have the same restrictions the Linux for Android OS has.

**Comment by atavism** [comment]
@myleshorton Yeah, it's not touching any of that code, and I don't think we really need to. We're only building off of flashlight client. Everything was configured much cleaner with the Valencia release.

**Comment by myleshorton** [comment]
Cool let's just go with those minimal changes for now then. If there's deeper consolidation we need, we can tackle it later. That sound right?

**Comment by xiam** [comment]
Sounds good to me! @atavism, please feel free to assign me the future PR.

**Comment by myleshorton** [comment]
This is pretty much done @atavism correct? Or did we end up cutting a few corners for FireTweet?

**Comment by uaalto** [comment]
I see this issue is still open. What remains to be done exactly? I can take over this task.

**Comment by xiam** [comment]
> I see this issue is still open. What remains to be done exactly? I can take over this task.

I think we're fine with this but we'll probably need to experiment a bit more on iOS and on our next upcoming project which is related to mobile.
