### ISSUE TITLE
cloud.yaml should overwrite local config 

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2365]
It will currently append to it, which is not what we want.

**Comment by aranhoide** [comment]
I think a mix of both is required.  Settings from the command line etc. should be preserved unless explicitly overwritten by the cloud config.  I think this comes down to completely replacing masquerade sets, fronted and chained servers, and using the old merge behavior for everything else.

Proxied sites is trickier since the user may have added their own sites.  I'll leave it alone for now and we can revisit that in a different ticket.

**Comment by fffw** [comment]
For simplification, is it meaningful to separate cloud.yaml from lantern.yaml, and let cloud.yaml just be overridden at file level each time? Through that, we can separate the logic of retrieve cloud configuation from tracking local update. We can also store cloud.yaml in binary form locally to prevent it from being manually altered.

lantern.yaml can just store locally configurable parameters, such as role, listen addr, etc. For our own testing purpose, a section in lantern.yaml just disables everything in cloud.yaml.

**Comment by myleshorton** [comment]
I like that idea a lot @fffw. Separating out the purpose of each would be really nice.

**Comment by aranhoide** [comment]
@fffw : that assumes that there is a clear divide between the things we want to be configurable locally and those that we want to configure through cloud.yaml.  I'm not sure that's the case.  Recently I overrode `cloudconfig` for people downloading the cloud.valencia.yaml and cloud.2.0.0-beta3.yaml so they would from then on grab cloud.2.0.0-nl.yaml instead.  I couldn't have done that if that was only settable from the command line or a local config file.

**Comment by myleshorton** [comment]
Hey @aranhoide I think that's a good point. For that particular example, though, I don't think we'd ever want the user to be able to configure that. As developers we do want to be able to configure it, however. So maybe we just always make the local config override the remote one for settings like that?

In fact, at this point the only things that are user-configurable are whether or not to run at system startup and whether or not to report stats. I like the idea of putting those in a separate, human-readable config file and keeping everything else globally-replaced with whatever's in the cloud.

To me it seems like it makes sense to do the following:

1. Separate local from remote config files
1. Have local fields (in the local config file) always override remote fields, which at this point only applies to developer settings for which that's not really an issue (i.e. it doesn't have the problem of us not being able to apply global config to all users)
1. If a setting arises that does conflict in terms of global versus remote config for *users* (not developers), we can figure it out then.
