### ISSUE TITLE
Analytics tracking sessions as separate event from a normal page visit

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2367]
Not sure if there's any way around this, but it looks like sessions are being tracked as a custom event with the new backend analytics integration instead of as a normal session that show's up on the main dashboard in analytics. So it means that old clients and new clients are tracked separately.

**Comment by atavism** [comment]
Every event is supposed to be associated with a session. Are they not showing up in the dashboard? I guess we're tracking the former as a page view and the other as a custom event. We could definitely combine these.

**Comment by myleshorton** [comment]
Looks like this is working after all!
