### ISSUE TITLE
Auto-update issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2368]
While testing changes for https://github.com/getlantern/lantern/issues/2344, running Beta 4, I encountered an issue with auto-update. Here's what I'm seeing in the log file:
```
Apr 09 02:18:25.505 - flashlight.config: Merging cloud configuration
Apr 09 02:18:25.584 - yamlconf: Configuration changed programmatically, saving
Apr 09 02:18:25.742 - autoupdate: Problem checking for update: Problem fetching update: invalid character '<' looking for beginning of value
```

**Comment by myleshorton** [comment]
Is this because the upstream updates aren't activated yet @xiam?

**Comment by xiam** [comment]
Thanks @atavism. Yes @myleshorton, I put the auto-update server down but I think it's a good idea to keep this open, to make sure it will be up for beta-5.

**Comment by xiam** [comment]
Auto-update server is now pointing to getlantern/lantern.
