### ISSUE TITLE
Check .Lantern vs .lantern

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2376]
Need to check why are we using both directories and found a solution that leaves us with only one of them.

**Comment by xiam** [comment]
Guys, I could not find a reference to the `~/.Lantern` path @aranhoide mentioned on the mailing list. Is this still valid?

```
grep -R '\.Lantern' .
```

@sheena3 was also looking for that path.

**Comment by myleshorton** [comment]
It looks like it's created from config.go on line 159:

```
cdir = appdir.General("Lantern")
```

Then appdir_stub.go calls:

```
func general(app string) string {
     return inHomeDir(fmt.Sprintf(".%s", app))
 }
```

I think just making app lower case there would do the trick.

**Comment by xiam** [comment]
Thanks @myleshorton

**Comment by xiam** [comment]
Please see https://github.com/getlantern/flashlight-build/pull/174.
