### ISSUE TITLE
lantern doesn't work at all in my system!!

### ISSUE THREAD

**Issue by vahid5570** [getlantern/lantern#2380]
I have serious problem, the loading of lantern takes too much , and it doesn't work at all.besides I cannot connect to net by my browser because its proxy is changed. what can I do?
please help me

**Comment by aranhoide** [comment]
Does this problem still persist?  I know of some temporary condition that might have caused this, with some probability.

**Comment by myleshorton** [comment]
Also where are you accessing Lantern from @vahid5570?

**Comment by vahid5570** [comment]
@aranhoide  : yes, it does
@myleshorton : no, I acces by my gmail

**Comment by atavism** [comment]
Hey @vahid5570, what country are you accessing Lantern from?

**Comment by vahid5570** [comment]
Iran

**Comment by myleshorton** [comment]
Thanks @vahid5570! What version of Lantern are you using? We strongly
recommend Lantern 2.0.0 beta 4, available at:

https://s3.amazonaws.com/lantern/lantern-installer-beta.exe (Windows)
https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg (OSX)
https://s3.amazonaws.com/lantern/lantern-installer-beta-64.deb (Linux 64 bit)
https://s3.amazonaws.com/lantern/lantern-installer-beta-32.deb (Linux 32 bit)

On Tue, Apr 14, 2015 at 2:56 PM, vahid5570 <notifications@github.com> wrote:
> Iran
>
> —
> Reply to this email directly or view it on GitHub.



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
