### ISSUE TITLE
Raise our limit of CloudFront distributions

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2382]
We've hit our limit of CloudFront distributions, at 200.  This number is more or less OK for our current fleet of flashlight servers (hence the low priority) but may soon become too low as we need to ramp up our infrastructure.

**Comment by aranhoide** [comment]
Note that the reason why we hit our limit is because we were generating many of these for testing purposes and only manually cleaning them up every now and then, an issue that is reported at

https://github.com/getlantern/lantern/issues/2381

**Comment by myleshorton** [comment]
Request submitted, not much else we can do.
