### ISSUE TITLE
Use different analytics tracking code for FireTweet

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2383]

**Comment by atavism** [comment]
Do we want to use a different tracking code for FireTweet or Lantern Android? Ideally, we'd configure analytics to link every mobile session event to <some app powered by Lantern> (in this first instance to "FireTweet").

**Comment by myleshorton** [comment]
Yeah great question. I feel like we ideally want a completely separate tracking code for each one. Maybe we can handle that in the build process?

I suppose it could also be a separate event, but I feel like a completely different code would be nicer from the analytics UI perspective. What do you think?

**Comment by myleshorton** [comment]
moved to firetweet
