### ISSUE TITLE
Lantern not building on Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2388]
An issue with resources again:

```
github.com/getlantern/flashlight/ui
ui\ui.go:48: undefined: Resources
```

**Comment by myleshorton** [comment]
Any idea on this one @xiam?

**Comment by xiam** [comment]
The resources file is generated by genassets. Can you try running this before windows-386?

```
make genassets
```

Last week I added a conditional that would call genassets if the resource file could not be found, that was supposed to fix this, did you just called `make windows-386`?

**Comment by myleshorton** [comment]
I'm actually just trying to build normally from the flashlight folder. Would be cool if we can maintain the ability to just call ```go build``` while we're just developing, which I believe still works on OSX unless it's just working because I previously called make.

**Comment by xiam** [comment]
Indeed this not working out of the box:

```
make clean
source setenv.bash
go build github.com/getlantern/flashlight
# github.com/getlantern/flashlight/ui
# src/github.com/getlantern/flashlight/ui/ui.go:48: undefined: Resources
```

A workaround while we fix this would be calling `make genassets` just once, then the direct go build will work again with no need to call genassets before each build:

```
go build github.com/getlantern/flashlight
```

**Comment by xiam** [comment]
Hello @myleshorton,

Can you help me testing this? https://github.com/getlantern/flashlight-build/pull/178

Use `make clean` before.

Thanks,

**Comment by myleshorton** [comment]
Hey @xiam yes works great thanks!
