### ISSUE TITLE
How to uninstall beta 2

### ISSUE THREAD

**Issue by davidrhoderick** [getlantern/lantern#2392]
How do I uninstall beta 2 from Mac OS X Mavericks?  I am having no success with it; no Gmail log-in, no prompts, incorrect location display on map, and no pop-ups on countries showing users.  I will try to go back to the latest version and see if that works although I upgraded because that wasn't working.  I apologize if this is a dumb request and please just post a link if this is documented.  I have tried installing the old version and nothing changes; beta 2 still loads.  Thanks for your help.  If you need more information, please let me know.

**Comment by xiam** [comment]
Hello @davidrhoderick,

No worries, we're testing out a lot of new things with the betas. Can you open Finder and see if Lantern appears in your Applications folder? You should be able to delete the app from there.

**Comment by myleshorton** [comment]
@davidrhoderick we also have released a couple of betas since then with significant fixes in each. If you're up for it can you give beta4 a try? The direct link for OSX is:

https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg
