### ISSUE TITLE
"x509: certificate has expired or is not yet valid"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2396]
This is a fairly highly ranked complaint by Loggly.  This could be caused by certs in either our fallbacks or our flashlight proxies expiring.  I'll do a program that checks for this.

**Comment by myleshorton** [comment]
We're also seeing at least similar cert errors in FireTweet.

**Comment by aranhoide** [comment]
That one seems about missing CAs.  There are some logs to that effect in loggly too, so I'll just submit that one separately.
