### ISSUE TITLE
Errors upgrading websocket

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2400]
Possibly from older browsers?

flashlight.ui: Unable to upgrade /data to websocket: websocket: version != 13

**Comment by star8088** [comment]
Google

**Comment by fffw** [comment]
The error is reported [in gorilla/websocket](https://github.com/gorilla/websocket/blob/master/server.go#L96). Seems it only occurring on Windows.

Internet Explorer doesn't support WebSocket [until 10](http://caniuse.com/#feat=websockets). Maybe we need a check at JavaScript side.

**Comment by fffw** [comment]
Consider the UI display issue at https://github.com/getlantern/lantern/issues/2261, we can simply check if IE version is lower than 10 and display a message if so.

**Comment by fffw** [comment]
Fixed by https://github.com/getlantern/lantern/pull/2459
