### ISSUE TITLE
Errors fetching https://s3.amazonaws.com/lantern_config/cloud.2.0.0-nl.yaml.gz

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2402]
yamlconf: Custom polling failed: Unable to read yaml from https://s3.amazonaws.com/lantern_config/cloud.2.0.0-nl.yaml.gz: Unable to fetch cloud config at https://s3.amazonaws.com/lantern_config/cloud.2.0.0-nl.yaml.gz: Get https://s3.amazonaws.com/lantern_config/cloud.2.0.0-nl.yaml.gz: EOF

**Comment by xiam** [comment]
Also Get https://s3.amazonaws.com/lantern_config/cloud.2.0.0-nl.yaml.gz: Bad Gateway

**Comment by myleshorton** [comment]
Closing this since we're not seeing it anymore.
