### ISSUE TITLE
Chrome frequently ignoring proxy settings

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2419]
It sets the "effective" proxy settings to direct even though the system proxy settings are set correctly.

**Comment by fffw** [comment]
PAC related code is under `net/proxy` of `https://chromium.googlesource.com/chromium/src.git`. The repo is huge! ~3GB.

To start Chrome in full logging mode, run `/Applications/Google Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging --v=1`, Logs is under `Library/Application Support/Google/Chrome/Default`

**Comment by myleshorton** [comment]
I just experienced this again on OSX. I did the following:

1. Started Lantern from the command line
1. Opened whatismyipaddress.com and saw that it was not the expected proxy but my own address
1. Opened Chrome's proxy settings in the chrome://net-internals
1. Saw the following:

```
Effective proxy settings

Use DIRECT connections.

Original proxy settings

PAC script: http://127.0.0.1:16823/proxy_on.pac
Source: SYSTEM
```

I didn't do that at the time, but apparently it's possible to trace how Chrome decides the effective settings. You need to do this *before* all of the above, but you simply open chrome://net-internals to Events and filter for "PROXY_SCRIPT_DECIDER"

**Comment by myleshorton** [comment]
The above process is discussed at:

https://www.chromium.org/developers/design-documents/network-stack/debugging-net-proxy

**Comment by myleshorton** [comment]
I'm seeing this again where the proxy settings are starting as:

```
Effective proxy settings

Use DIRECT connections.
Source: SYSTEM
Original proxy settings

PAC script: http://127.0.0.1:16823/proxy_on.pac
Source: SYSTEM
```

and Lantern never seems to try to reset them on startup, or at least PROXY_SCRIPT_DECIDER never shows up in Chrome events.

**Comment by fffw** [comment]
Thanks @myleshorton for those great findings!

Follow your train of thought, just filtering by "proxy_on" in Chrome events will give us more information. Chrome is just switching between DIRECT and PAC back and forth.

**Comment by myleshorton** [comment]
I actually think what I keep seeing is just that CTRL-Cing out of Lantern during development often means it doesn't turn off the proxy settings. Then when I run again, it gets into the state described above.

At least that's my theory. I'll try to make a habit of opening the chrome://net-internals proxy screen before running each time to verify.

**Comment by fffw** [comment]
What I was frequently seeing is events like below. Chrome just switched to DIRECT and back to PAC in very short interval. It doesn't happen all the time. Lantern log was nothing special around this period.

![image](https://cloud.githubusercontent.com/assets/10410437/7720932/4d0fff22-ff05-11e4-9036-0ff2aeb6db8e.png)

![image](https://cloud.githubusercontent.com/assets/10410437/7720954/7f42689a-ff05-11e4-9762-2adff1a9e3da.png)

**Comment by myleshorton** [comment]
I think that rapid switching is from turning proxying on and off as detour adds sites to the pac file @fffw right?

**Comment by fffw** [comment]
Yes it is indeed...

**Comment by fffw** [comment]
I just encountered one occurence. Lantern get listed under `Recently failed proxies, marked as bad`.

![image](https://cloud.githubusercontent.com/assets/10410437/7798793/2156ab30-0331-11e5-8884-382d6592df6b.png)

Below is one sample event of Chrome before the `BAD_PROXY_LIST_REPORTED` event:
```
247200: CONNECT_JOB
ssl/ssl.gstatic.com:443
Start Time: 2015-05-25 22:48:58.895

t=24478744 [st=0] +SOCKET_POOL_CONNECT_JOB  [dt=1]
                   --> group_name = "ssl/ssl.gstatic.com:443"
t=24478744 [st=0]   +SOCKET_POOL_CONNECT_JOB_CONNECT  [dt=1]
t=24478744 [st=0]     +HOST_RESOLVER_IMPL_REQUEST  [dt=1]
                       --> address_family = 0
                       --> allow_cached_response = true
                       --> host = "localhost:8787"
                       --> is_speculative = false
t=24478745 [st=1]        HOST_RESOLVER_IMPL_HOSTS_HIT
t=24478745 [st=1]     -HOST_RESOLVER_IMPL_REQUEST
t=24478745 [st=1]     +HOST_RESOLVER_IMPL_REQUEST  [dt=0]
                       --> address_family = 0
                       --> allow_cached_response = true
                       --> host = "ssl.gstatic.com:443"
                       --> is_speculative = false
t=24478745 [st=1]        HOST_RESOLVER_IMPL_CACHE_HIT
t=24478745 [st=1]     -HOST_RESOLVER_IMPL_REQUEST
t=24478745 [st=1]   -SOCKET_POOL_CONNECT_JOB_CONNECT
                     --> net_error = -102 (ERR_CONNECTION_REFUSED)
t=24478745 [st=1] -SOCKET_POOL_CONNECT_JOB
```

**Comment by fffw** [comment]
We can ask Chrome to save network log to a file via launch options, see http://dev.chromium.org/for-testers/providing-network-details

**Comment by myleshorton** [comment]
Nice @fffw. I think we should just always add that flag if we detect we're running in dev mode.

**Comment by myleshorton** [comment]
I'm only seeing this when not shutting down correctly during development, so closing for now.
