### ISSUE TITLE
Add a config option to not change system proxy

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2422]
Requested by a user in [forum](https://groups.google.com/forum/#!topic/lantern-users-zh/sD1mO9H4gI8), but also applicable for other scenes.

*  using [cow](https://github.com/cyfdecyf/cow/blob/master/README-en.md) to manage several proxies.
*  causing a variety of Windows 10 Modern application access difficulties, needs to verify.
*  we don't want the test instance to interfere with system settings during testing.

We can support those advanced usage by adding a new config option.

**Comment by myleshorton** [comment]
This is addressed in #3626 and ##3363
