### ISSUE TITLE
"Error reading response from proxy: unexpected EOF"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2436]
Been getting this in Loggly intermittently.

**Comment by atavism** [comment]
Seeing this as a top reported issue in Loggly.

**Comment by xiam** [comment]
I think this `io.ErrUnexpectedEOF` error originates from this [http.ReadResponse](https://github.com/getlantern/lantern/blob/7e7772dbb777f86488e1c77e1044e1a3fb5fc569/src/github.com/getlantern/enproxy/conn_impl.go#L154) and it happens only in code that uses `enproxy.Dial`, like fronted requests for example. My understanding from reading the source of [http.ReadResponse](http://golang.org/src/net/http/response.go?s=3715:3782#L106) is that the server allows an initial connection but the connection is cut before allowing it to reply with a complete line or with a MIME header, `http.ReadResponse` does not close the connection by itself so it must be something within `enproxy`.

My current opinion is that `lantern/idletiming` is closing the connection. See our current [default timeout settings](https://github.com/getlantern/lantern/blob/7e7772dbb777f86488e1c77e1044e1a3fb5fc569/src/github.com/getlantern/enproxy/conn_intf.go#L31):

```
  defaultWriteFlushTimeout = 35 * time.Millisecond
  defaultReadFlushTimeout  = 35 * time.Millisecond
  defaultIdleTimeoutClient = 30 * time.Second
  defaultIdleTimeoutServer = 70 * time.Second
```

I will try to test this on a very slow connection and see if that triggers similar errors.

**Comment by xiam** [comment]
Got some errors while working on my simulated network:

![screen shot 2015-06-11 at 1 59 41 pm](https://cloud.githubusercontent.com/assets/385670/8115610/2f51caf8-1042-11e5-9357-ecc64fbf9712.png)

And some of the failed geolocation attempts also showed up:

![screen shot 2015-06-11 at 2 02 18 pm](https://cloud.githubusercontent.com/assets/385670/8115663/8c204ab6-1042-11e5-9f49-c759c43bac4e.png)

So it must be related to user's speed and our default timeouts. Should we try making them less aggressive?

**Comment by myleshorton** [comment]
Does making them less aggressive make the errors go away in your simulated network @xiam?

**Comment by xiam** [comment]
It seems like the mentioned errors go away, but then some others start to appear, like this one `Unable to dial masquerade: EOF`. I am wondering if this is what the [idleTimeout](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/fronted/dialer.go#L37) tried to prevent.

![screen shot 2015-06-11 at 3 15 32 pm](https://cloud.githubusercontent.com/assets/385670/8117386/5192024e-104d-11e5-8ece-2f26198c82a5.png)

I'm going to experiment with moving timeouts here and there and see what Lantern says.

**Comment by aranhoide** [comment]
A variation (?) of this is showing up at Loggly:  "flashlight.client: reverseproxy.go:186 http: proxy error: unexpected EOF".  If you're sure this is unrelated, please open a new issue for it.

**Comment by aranhoide** [comment]
Another one (?): "enproxy: conn_impl_reads.go:90 Error reading: unexpected EOF"

**Comment by myleshorton** [comment]
Closing this in favor of more current #5058
