### ISSUE TITLE
"Dial detoured to logs-01.loggly.com:443 failed"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2437]
Got this today in Loggly.  I also got the following warning in the Loggly web UI.  Maybe loggly is just rejecting connections once our daily quota is used up?

> Your daily log volume has been exceeded. No more log events will be indexed for the remainder of the day (UTC). Please review your subscription.

**Comment by aranhoide** [comment]
This has been reported last March 30.  That support entry doesn't mention this loggly warning.

**Comment by myleshorton** [comment]
I switched our loggly plan so closing for now.
