### ISSUE TITLE
Can't build lantern-amd64 nor lantern-darwin binaries

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2438]
I tried building the amd64 version from Ubuntu and the darwin version from OS X.  In both cases, I got the following:

```
Unable to find image 'lantern-builder:latest' locally
Pulling repository lantern-builder
FATA[0007] Error: image library/lantern-builder:latest not found 
make: *** [genassets] Error 1
```

**Comment by myleshorton** [comment]
This is working for me FYI @xiam and @aranhoide. I just deleted all local docker containers and images and built from scratch on OSX, and all was good.

You have boot2docker all set up and everything right?

**Comment by fffw** [comment]
@aranhoide Might because of the image naming? The images was called `flashlight-builder` previously. You can verify it through `docker images`. If no `lantern-builder` present, just `make docker` might resolve it I think.

**Comment by aranhoide** [comment]
Duh, yeah, `make docker` fixed it.  I forgot that step when making the `flashlight-build`->`lantern` move.  As I suspected, I was missing something very basic (*blush*).

If it is possible and quick to check whether docker has been initialized, I'd make the docker target a make dependency of all the binaries.  Anyway, this "issue" is bogus.  Sorry for the distraction!
