### ISSUE TITLE
ReverseProxy reports "No dialers left to try"

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2440]
> Apr 24 14:19:35.150 - detour: detour.go:139 Dial detoured to pki.google.com:80 failed
> 2015/04/24 22:19:35 http: proxy error: No dialers left to try

But at the same time, `Client.intercept()` can dial. Must be subtle differences between the way invoking `detour.Dialer`.

**Comment by fffw** [comment]
Should also set `ErrorLog` field, so the errors can write to `golog`, rather than print to stderr directly.

**Comment by myleshorton** [comment]
You saw this in loggly @fffw or in your own testing?

**Comment by fffw** [comment]
My own test. It will not appear in loggly as it is just printed to stderr.
2015年4月25日 上午12:52于 "myleshorton" <notifications@github.com>写道：

**Comment by fffw** [comment]
Moved the `ErrorLog` field issue to separate ticket https://github.com/getlantern/lantern/issues/2445

**Comment by fffw** [comment]
From [balancer.go](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/balancer/balancer.go#L74), only trusted server will be chosen to proxy HTTP traffic, but I found no trusted servers in my lantern.yaml. 

I tried removing lantern.yaml and all servers are still **untrusted** in generated file.

It's expected as per @xiam 's comment [here](https://github.com/getlantern/lantern/issues/2290#issuecomment-94918709), but we should change it before release 2.0.0-beta6 to public.

We can also add a workaround to proxy HTTP traffic through untrusted server if no trusted server available.

**Comment by xiam** [comment]
Sorry for the confusion @fffw, we should have released an updated `cloud.yml` file with trusted servers. @aranhoide do you think you could help us rolling an updated config file? Thanks!

**Comment by aranhoide** [comment]
Whoops, sorry, I intended to do just that when I merged that branch but forgot to.  I'll do that now.

**Comment by aranhoide** [comment]
@fffw @xiam I've just uploaded a `cloud.cn.yaml` and `cloud.default.yaml` with `trusted: true` in all servers.  As soon as @fffw's PR is merged (since it includes a fix to the .yaml template) I'll try and make the process of fetching the `fallback.json`s for both Amsterdam and Tokyo servers and creating the relevant .yaml's more streamlined.

**Comment by fffw** [comment]
@aranhoide the PR is rather simple now. If you can just review it, so you can make your changes for the process?

**Comment by xirang2014** [comment]
How to deal with the Proxy report like this"Unable to get a connection: No dialers left to try on pass 0"?

**Comment by wjf444128852** [comment]
close the lanter plugin.

**Comment by wjf444128852** [comment]
close the lantern plugin than it will be ok

**Comment by wjf444128852** [comment]
@xirang2014 close the lantern plugin than it will be ok
