### ISSUE TITLE
Email auto-responder

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2449]

**Comment by myleshorton** [comment]
We really need to make sure we have this working for the tech show! The best route is not entirely clear to me to be honest. I.e. we currently have an auto-responder with links to the installers. But this would mean setting up a custom responder that attaches the installers to an email.

Presumably there's some reason others didn't just include the links, so we could just follow their lead on it and go that route.

**Comment by myleshorton** [comment]
We're actually just going to include links in the response like we do now.

**Comment by myleshorton** [comment]
Re-opening because Google Groups for whatever reason won't send emails in auto-responses that appear right-to-left on Android. It also won't allow us to attach things like the APK, of course, so it seems like we need to set up our own auto-responder.

**Comment by myleshorton** [comment]
Tor and Phiphon both do this same thing, and their code is open source, although it's not immediately clear where the heck it is. Tor discusses it here however:

https://www.torproject.org/projects/gettor.html

**Comment by fffw** [comment]
MailChimp can send welcome letter to new subscribers, but can't include attachments. We need similar mechanism to push new release of APK to those subscribed users.

**Comment by fffw** [comment]
AWeber is the sole email marketing service I can find that supports attachments but [limited to 1MB](https://help.aweber.com/hc/en-us/articles/204030016-How-Do-I-Add-Attachments-To-Messages-). 

Psiphon uses an EC2 instance to send auto responses. Once we consider writing an application, the [Mailman gem](https://github.com/mailman/mailman) might be the simplest tool to employ.

**Comment by fffw** [comment]
During my testing using my personal gmail account, mailman gem can receive new mail through imap, and send back customized HTML content with `dir='rtl'` and attachment.

The obstacle is that it didn't receive mail when I test using accounts with custom domain.

**Comment by myleshorton** [comment]
oh interesting. does it receive emails at firetweet.io or is that considered a custom domain?

**Comment by fffw** [comment]
@myleshorton To be precise, it doesn't work if the account contains domain name.

**Comment by myleshorton** [comment]
Oh I see, so it only works with @gmail.com correct?

**Comment by fffw** [comment]
@myleshorton Yes I still didn't find a way to let it retrieve mails of accounts other than @gmail.com. 

I did find a workaround that can solve the RTL issue. It uses a Google Labs feature called [Canned Responses](http://gmailblog.blogspot.nl/2008/10/new-in-labs-canned-responses.html). To have a try, send me an email with title "manato" and you'll get a response which shows correctly on mobile phones.

It requires a new mail account that received messages sent to manato@firetweet.io. The steps:

1. Turn on RTL editing for the mail account, see https://support.google.com/mail/answer/40283?hl=en

2. Enable the labs feature and create a canned response. http://www.wikihow.com/Use-Canned-Responses-in-Gmail

3. Create a filter and use the canned response as action.
![image](https://cloud.githubusercontent.com/assets/10410437/7875194/706cdf7e-05ec-11e5-874b-a8c23ef335ae.png)

Unfortunately, it doesn't support attachments.

Google groups also have this feature, but it doesn't include subject, and can't set text direction, so we have to change to regular mail address to let it work.

**Comment by myleshorton** [comment]
Awesome!! I think that totally works. Let's skip the attachment and just do
that. You want to delete the google group and create a new "manoto" account?

**Comment by fffw** [comment]
It seems that admin account doesn't have admin privilege of Google Apps right? I can't create new account using it. A bit unfamiliar of Google Apps.

**Comment by myleshorton** [comment]
OK I just added the correct permissions for the admin account but will also just knock this out on my end. Thanks @fffw!

**Comment by myleshorton** [comment]
Awesome! I just set this up @fffw, and it's working great. Closing.
