### ISSUE TITLE
Different release share the same release page

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2452]
These releases are for different things, but they share the same release page:

![screen shot 2015-04-27 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/385670/7356051/750ca24a-eceb-11e4-8057-a4e19921f52c.png)

This does not confuse the auto-update server but it still needs to pull every release and see each assets to find matches, not a big deal but it could get confusing someday.

**Comment by aranhoide** [comment]
The 0.0.x releases are for the benefit of machines we deploy with Salt.  Ignorant question: can't you just filter out the 0.0.x series as a special case?  What if I mark those all as pre-releases; would that help?

**Comment by myleshorton** [comment]
Yeah the other thing that comes to mind is that all those releases are extremely close to client released versions. Maybe just include the client version with a commit id, or whatever the semver way to do do that is? Something like 2.0.0-die2244.

I.e. it might be handy to know what version it's linked to. That might screw up the auto-updates even more though.

**Comment by aranhoide** [comment]
Ox started that convention, but the main reason I continued with it is specifically so we're less likely to confuse them with releases sent to users.  I can change it to follow that scheme if you want, though.
