### ISSUE TITLE
Streamline the generation of country-specific `cloud.yaml`s

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2454]
Right now the process of generating and uploading 'cloud.cn.yaml' and 'cloud.default.yaml' is a multi-step process that requires a working checkout of the 'lantern_aws' project.  It should be possible to make it a one-command operation and only depend on 'too-few-secrets'.

**Comment by myleshorton** [comment]
I think this one's done @aranhoide correct?
