### ISSUE TITLE
enproxy sometimes uses an incorrect masquerade and gets certificate mismatches

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2461]
I'm trying to get more information. Leaving a log in the meantime:

```
Apr 30 16:00:09.469 - enproxy: conn_impl.go:96 Unable to dial proxy: Unable to dial masquerade lamido.co.id: x509: certificate is valid for www.peoplesearchnow.com, peoplesearchnow.com, not lamido.co.id
```

**Comment by myleshorton** [comment]
I feel like one of your recent changes may have solve this @aranhoide is that right?

**Comment by aranhoide** [comment]
Do you mean dialing masquerades by IP?  I don't remember whether that
predates this report or not.  IIRC we still validate that we get the right
host.

Anyway, does this still happen?  With many different masquerades, or mostly
the same bunch?  If there are a few masquerades that are prone to this, we
could just blacklist them.

**Comment by myleshorton** [comment]
I haven't seen this one in awhile actually. I suspect one of the config updates might have fixed it.

**Comment by myleshorton** [comment]
I'm seeing this now with beta 6.

**Comment by xiam** [comment]
Not valid anymore.
