### ISSUE TITLE
Things to do for tech show

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2464]
- [x] Add more servers to auto-responder
- [x] Test from more email providers/addresses
- [x] Build final installers
- [x] Build new web site
- [x] Translate new web site
- [x] Update template on Mandrill for email input on web site
- [x] How does video streaming work from Iran?
- [x] Identify why some users are unable to access blocked sites.
- [x] **Document how to do things like reboot the mail responders** https://github.com/getlantern/mail-responder (restart.sh)
- [x] Make sure everyone can log in to the responder

**Comment by fffw** [comment]
Changed it to real check list, just to look cool.

**Comment by myleshorton** [comment]
Nice thanks @fffw!
