### ISSUE TITLE
AWFUL connectivity

### ISSUE THREAD

**Issue by davidrhoderick** [getlantern/lantern#2465]
Let me preface this by saying I am a huge supporter of the Fight For the Future and this Lantern project.  It has certainly enhanced my life and I try to give access (I live in Serbia, so god knows who wants my access), as much as possible.  I run both Linux and Mac OS X versions of the software.

On Mac, I am version 1.5.17-c3feb51 (my Linux system is down right now but will update with version number later).  The issue is that connections last for apparently seconds, maybe minutes, to a target country.  For example, if I am using a proxied site, most of the time, it will not render correctly through lantern.  In order to "kick" the system into working, I have to switch from "Get access" to "Give access" and back again for a CHANCE at getting it to work.  Obviously, this is frustrating.

I at first (stupidly) assumed there was maybe some quota for receiving based on what I am giving, but the system used to work fine when I never gave access.  Now I leave one system giving access all the time.  How can I make Lantern work for me in a half decent fashion?  I checked my router for the settings listed and I was all set except I didn't have the port forwarding method chosen (it said one or the other correct?).

**Comment by myleshorton** [comment]
Thanks David. So get mode is the mode giving you problems correct? I would
try the new betas that are linked from the home page. Are those any better
for you? They're all get mode only but also auto - detect blocking. So they
don't support proxying all traffic and therefore may not work for your use
case.

Do you require support for proxying all traffic?

Thanks for your support, and we'll work hard on our end to ensure Lantern
works well for you.

-Adam

**Comment by davidrhoderick** [comment]
Thanks for the response, I just tried the beta on Mac and the tab in Chrome that it opened had no pop-ups and my location wasn't in the correct place.  I think I had this same problem before.  If there is anyway I can send you information to help fix the issue, I well.  Otherwise, I have to stick with the old version because at least it works, even if not well.  I will try the beta on Linux and let you know how that goes.

**Comment by myleshorton** [comment]
Thanks David. The location lookup is actually the same across both versions
and isn't always accurate simply because the databases for associating ip
addresses with locations aren't 100% accurate themselves.

I'm wondering if you can send us your logs? They should be in
~/.lantern/logs on windows and at ~/Library/Logs/Lantern on OSX. Can you
send them to team@getlantern.org?

**Comment by myleshorton** [comment]
I'm still unclear on exactly what your use case is here @davidrhoderick, but please reopen if we can narrow the scope a little bit.
