### ISSUE TITLE
Document port 8787 for endusers

### ISSUE THREAD

**Issue by halaei** [getlantern/lantern#2466]
I installed lantern via .deb file in Ubuntu 14.04. The only way that worked for me to know which port lantern listen to was `netstat lnptu`.
Should'nt be a better way to know about localhost:8787 or I've just hacked lantern? ;)

**Comment by myleshorton** [comment]
Thanks @halaei! Lantern should just auto-configure your system proxy to send HTTP traffic through Lantern on that port, which is why it's not documented anywhere. Perhaps it didn't do that for you, or perhaps you'd prefer to do it manually?

**Comment by halaei** [comment]
@myleshorton ; thanks for your concern. Lantern did not set system proxy and I prefer to manualy set proxy only for one application, say Firefox, and not any other, say Chrome.

**Comment by myleshorton** [comment]
Makes sense @halaei. Are you using the latest betas by chance? If not you might want to give one of these a try (depending on your architecture):

https://s3.amazonaws.com/lantern/lantern-installer-qa-32-bit.deb
https://s3.amazonaws.com/lantern/lantern-installer-qa-64-bit.deb

They're much smaller and auto-detect blocking if you're not already using them.

**Comment by halaei** [comment]
I installed this: [https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-64.deb ](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-64.deb ). The link was grabed from [https://getlantern.org](https://getlantern.org), where it says "Available for Mac, Windows, and *Linux*.". Is there any problem with that?

**Comment by myleshorton** [comment]
There's no problem with it no, but the latest betas include a lot of improvements including auto-detection of blocked sites, much smaller download (3.5MB), faster speeds, etc.

**Comment by myleshorton** [comment]
You can also use the betas linked from the home page @halaei -- the one I referenced above is beta 5 that's currently in QA.

**Comment by myleshorton** [comment]
Most users seem to have figured this out.
