### ISSUE TITLE
Improve detour logic to work well on flaky networks

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2470]
Forgot to log an issue. Basically, we can use parallel access to strip out the arbitrary 3s timeout.

**Comment by fffw** [comment]
Status update: totally rewrote detour to utilize parallel access, but still didn't get all tests passed.

**Comment by myleshorton** [comment]
Hey sorry I totally missed your comment here @fffw (my email filters are a bit aggressive), but great you're working on it! How's it working now? It would be great to get this in there!

**Comment by fffw** [comment]
That's ok @myleshorton . The ticket is mainly for my own logging before submitting a PR.

It's not as reliable as previous implementation yet and triggers [panic in balancer](https://github.com/getlantern/lantern/issues/2500) occasionally. I was trying to add more tests but didn't think clearly yet.

I think we can be more conservative as previous one works fine on most cases.

**Comment by myleshorton** [comment]
Sounds good @fffw. I still want to get to the bottom of why it's not working for that one user. I asked for logs, but maybe we can also get other users to try the same site.
