### ISSUE TITLE
Uninstalling beta 4, uninstalls beta 5 files too.

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2477]
Steps:
1. Install beta 5 without uninstalling beta 4.
2. Lantern automatically opens the browser.
3. Now uninstall beta 4. 
4. Lantern beta 5 stops working.
5. Lantern program is deleted from the system. Looks like all the files are getting deleted.

**Comment by fffw** [comment]
Yes, different versions of Lantern are installed at same location. Considering auto-update, putting them on version specific location might not be a good idea.

An more direct way would be to uninstall previous version automatically before installing new one.

**Comment by myleshorton** [comment]
Totally agreed @fffw

**Comment by fffw** [comment]
Ref http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new

**Comment by sheena3** [comment]
No, it is not uninstalling the previous version.
![uninstall prev version](https://cloud.githubusercontent.com/assets/11394369/7596005/2b087830-f908-11e4-98b8-1680e6ff20e1.png)

**Comment by myleshorton** [comment]
Weird. There's a "Detail" button you can press on the last installer screen. Can you press it, scroll up, and tell us what you see regarding uninstalling the old version if anything?

**Comment by myleshorton** [comment]
Actually this probably won't work if you have *two versions currently installed*. I would uninstall one before trying a new one.

**Comment by myleshorton** [comment]
Actually, I would uninstall both and start from scratch -- installing beta 4 and then beta 5 @sheena3

**Comment by sheena3** [comment]
I uninstalled all the versions of lantern.
Installed beta 4 and then beta 5.

It says that there is no previous version to uninstall. Could it be because I installed them on same day/time?

![image](https://cloud.githubusercontent.com/assets/11394369/7597041/f8bf1332-f90e-11e4-8d0f-b4f7923c0d4c.png)

**Comment by myleshorton** [comment]
Interesting. No that shouldn't do it. So after that install you have two versions sitting there correct?

**Comment by sheena3** [comment]
Yes, that's right.

**Comment by myleshorton** [comment]
Huh -- OK I'm looking at it.

**Comment by sheena3** [comment]
For your reference,

![image](https://cloud.githubusercontent.com/assets/11394369/7597211/95ac1794-f90f-11e4-9bef-aadf301911bc.png)

**Comment by myleshorton** [comment]
Hey I am able to reproduce this @sheena3 thanks! Looking closer at it now.

**Comment by myleshorton** [comment]
Hey so this one's actually an issue that's specific to beta 4/5. Basically beta 4 installed with admin privileges while beta 5 does not (in order for auto updates to work). That means, however, that beta 5 can't uninstall beta 4, but all future versions will be able to uninstall beta 5 and above.

If you still have that "beta 6" installer kicking around, you could verify it with that. Thanks @sheena3!

**Comment by myleshorton** [comment]
I'm going to close this @sheena3 but feel free to re-open if it still seems like an issue to you.

**Comment by sheena3** [comment]
I don't have the beta 6 installer now. Anyways, if a user has already installed beta 4(or any lower versions) and installs beta 5, then it is going to be an issue, isn't it? If at some point of time, the user uninstalls the lower version, it will uninstall beta 5 too. I presume it will be annoying for the user.

If we cannot uninstall the previous version while installing beta 5, we should at least give them a warning that it would be better to uninstall the previous version. @myleshorton @fffw What do you think?

**Comment by myleshorton** [comment]
> Anyways, if a user has already installed beta 4(or any lower versions) and installs beta 5, then it is going to be an issue, isn't it?

Yeah, but they're technically beta testers anyway. Bugs across beta versions like that aren't really worth dealing with I don't think. If they install 1.5.17 and then 2.0 final, they'll be fine.

> we cannot uninstall the previous version while installing beta 5, we should at least give them a warning that it would be better to uninstall the previous version. @myleshorton @fffw What do you think?

Same as above. These users know they're testing a beta, and part of the purpose of betas is to fix bugs like this.
