### ISSUE TITLE
Unpin lantern from taskbar when uninstalling lantern

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2478]
Steps:
1. Pin lantern to taskbar
2. Uninstall all the versions of lantern.
3. Lantern is still pinned in taskbar. When clicked, displays the message that the program has been removed.

It would be nice if we could unpin lantern from the taskbar and start menu when uninstalling.

**Comment by myleshorton** [comment]
This isn't new to beta5 correct?

**Comment by sheena3** [comment]
May be. This is the first time I used it. 

I will check with beta 4.

**Comment by sheena3** [comment]
Yeah the problem is there in beta 4 too.  It is unpinning from the start menu but not from the taskbar.  Updated the description.

**Comment by fffw** [comment]
FMPOV, an uninstaller should not revert anything it didn't done. Say, if a shortcut on desktop is created manually, uninstaller should not try to remove it. Pinning to task bar is just another way of creating shortcut I think.

**Comment by sheena3** [comment]
But I created shortcut in start menu too. While uninstalling, uninstaller removed lantern from start menu. So, we should either remove all the shortcuts to lantern or not at all.

**Comment by sheena3** [comment]
Oops, I checked it again and installer creates the lantern shortcut in start menu. I guess it works fine as you said. Closing this now.
