### ISSUE TITLE
Lantern is using a fixed user agent

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2481]
I got this by inspecting a pcap capture:

```
User-Agent: Go 1.1 package http\r\n
```

Lantern is using the default `User-Agent` for HTTP requests. It would be great having some sort of random using agent generator and changing this value.

**Comment by myleshorton** [comment]
This is for HTTP CONNECT requests to establish an SSL tunnel.

**Comment by myleshorton** [comment]
One question is what the User-Agent should be -- i.e. it's possible we should strip it entirely, but we could also mimic Chrome or another browser.

**Comment by myleshorton** [comment]
@xiam suggested just using the user's existing user-agent -- definitely the best solution.

**Comment by xiam** [comment]
This is an example of the plain text packet Lantern is sending. Here we can see the CONNECT and the User-Agent more clearly.

![screen shot 2015-05-07 at 10 38 56 am](https://cloud.githubusercontent.com/assets/385670/7519197/4d97de66-f4a5-11e4-91d4-866786329981.png)

**Comment by fffw** [comment]
The CONNECT request is assembled in [chained/dialer.go](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/chained/dialer.go#L75). We have to pass the 'User-Agent' header all the way to there.

**Comment by fffw** [comment]
To avoid the unnecessary coupling of code, maybe a hardcoded value mimic Chrome on Windows is enough.

**Comment by xiam** [comment]
Hello @fffw, I started writing some tests for this problem and now I think I'm pretty close to provide a solution, would you mind if I take a stab at it?

**Comment by fffw** [comment]
@xiam That would be great!

**Comment by myleshorton** [comment]
Looking at this a little bit more @xiam, I don't think your diagnosis is correct here. Were you possibly capturing packets on localhost/127.0.0.1? All outgoing connections to chained servers are themselves over TLS, and the HTTP CONNECT is passed through that TLS connection. See:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/chained.go#L52

**Comment by myleshorton** [comment]
I'm also not seeing any plain text traffic on the external network interface.

**Comment by xiam** [comment]
It was probably a mistake then, I'll check again and make sure I'm not
looking at the wrong interface.

**Comment by myleshorton** [comment]
OK cool. Yeah I don't actually see any HTTP traffic at all on the outgoing interface running Lantern. Closing for now!

**Comment by xiam** [comment]
Yeah, I tested again and this was a mistake on my side, this is only for *local* unencrypted connections.

**Comment by myleshorton** [comment]
Cool thanks for checking!

On Tue, Jul 14, 2015 at 11:58 AM, Carlos Nieto <notifications@github.com>
wrote:

> Yeah, I tested again and this was a mistake on my side, this is only for
> *local* unencrypted connections.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2481#issuecomment-121341899>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
