### ISSUE TITLE
Not connecting to Tokyo server when accessing lantern from India

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2487]
I believe now that we have Tokyo server running, lantern should connect to Tokyo server when accessed from India and not Amsterdam as the former is nearer. Or the Tokyo servers are only for users accessing from China?

Also in UI, Tokyo server is not shown.

**Comment by myleshorton** [comment]
It's not necessarily intended to access Tokyo in this case. Closing!

**Comment by aranhoide** [comment]
@sheena3 : feel free to reopen if you find Tokyo to be faster from India.

As for your last sentence in the description: only datacenters that you are using (or at least have used) are supposed to be shown in the map.
