### ISSUE TITLE
Lantern System tray icon didn't show up though lantern is proxying

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2489]
This could possibly because I let lantern running overnight on May 5th. I found this on May 6th so I let lantern running overnight again but it runs fine today. 

In the system tray, there is no lantern icon. But in the lantern browser, it started showing me the proxy server connections. So I checked in whatismyipaddress.com and it gave me the proxy server address. 
I couldn't come out of lantern. So I had to uninstall lantern and then install it again.

**Comment by myleshorton** [comment]
This is on Windows right @sheena3? Removing the Lantern 2.0 label since it's already in a 2.0.x milestone.

**Comment by sheena3** [comment]
yes, this is in windows

**Comment by fffw** [comment]
Maybe we can find some clue in logs? @sheena3 Could you send it over to me? It should be under C:\Users\<your user name>\AppData\Roaming\Lantern\logs

**Comment by sheena3** [comment]
I did so many installs and uninstalls after this issue. Next time, when I come across something like this I will try to take a copy of the log.

**Comment by sheena3** [comment]
If I ever see this again, I'll update it.

**Comment by myleshorton** [comment]
OK I'm closing this one for now. Please reopen if you see this again @sheena3
