### ISSUE TITLE
Lantern social sharing page not looking good on IE10

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2496]
![image](https://cloud.githubusercontent.com/assets/1143966/7543557/41b32a94-f57a-11e4-8d18-173580b537d7.png)

**Comment by myleshorton** [comment]
![image](https://cloud.githubusercontent.com/assets/1143966/7543553/348e64aa-f57a-11e4-8b60-5789a1957737.png)

**Comment by sheena3** [comment]
Adding - The number of users following in twitter is not displayed.

![welcome screen - sharing page](https://cloud.githubusercontent.com/assets/11394369/7571025/643fe1dc-f832-11e4-9aab-24eec832cf5e.png)

**Comment by sheena3** [comment]
Facebook sharing button takes long time to load and Twitter sharing is not loading at all though it shows the numbers. This is in IE 11.

And one more thing is, this is not welcome screen. This I opened using the Lantern link at the bottom.

![takes long time to load the sharing buttons](https://cloud.githubusercontent.com/assets/11394369/8089648/c6e6ddd0-0fc6-11e5-85ad-a343f5818912.png)
