### ISSUE TITLE
Add back proxy everything mode

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2497]
A number of users have requested this and are using the 1.5.17 version instead of 2.0 because it supports it. I think we should just add it back in!

**Comment by sheena3** [comment]
@myleshorton Will we remove auto-detection if we proxy everything?

**Comment by fffw** [comment]
@sheena3 I think we can just skip auto-detection(detour) when user checks a "proxy everything" option.

@myleshorton From your impression, were users requesting it because auto-detection didn't work well, or because of security concerns?

**Comment by myleshorton** [comment]
Hey sorry for the delay guys, but it's not totally clear why users keeps asking for it -- I've asked them those same questions without a clear or consistent response. In that one vk.com case it was because detour wasn't working though, although we still haven't discovered why.

**Comment by atavism** [comment]
Yeah, we discussed this before, but I think it would be great to make these different modes configurable from the settings screen. We'd have auto-detection (to turn detour on/off) and "proxy everything" options. The UI changes probably merit a separate ticket.

**Comment by myleshorton** [comment]
Agreed @atavism. To me initially it might just be proxy everything or not, with not just being detour, but not sure.

**Comment by fffw** [comment]
Added an yaml option in https://github.com/getlantern/lantern/pull/2524

For UI part, do you guys prefer place it in setting screen or tray menu? An tray menu item might be more convenient to user, though a bit more code is required.

@atavism Your thoughts about adding an auto-detection check option? I can't think of a situation when user want just fixed whitelist but no auto-detection.

**Comment by myleshorton** [comment]
Nice! Not sure on settings vs. tray menu. A check box in the tray could be challenging cross-platform but maybe not? In general it would be cool to move as much as possible into the tray. If you can get that working, that would be cool for sure.

**Comment by fffw** [comment]
Checked menu is not implemented in systray on Linux yet. Considering the priority of other issues, I'll add the option to setup page for now.

**Comment by fffw** [comment]
Resolved by https://github.com/getlantern/lantern/pull/2524
