### ISSUE TITLE
Lantern UI is not showing any connection, it is stuck when using Tokyo server

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2502]
![connecting to tokyo server](https://cloud.githubusercontent.com/assets/11394369/7569912/d11670c2-f829-11e4-9b0e-60e7c417c578.png)
![lantern is stuck](https://cloud.githubusercontent.com/assets/11394369/7569913/d12fdfee-f829-11e4-9d38-3d5ea954f324.png)

**Comment by myleshorton** [comment]
Do you still now get anything on the map if you keep refreshing the page in the browser @sheena3?

**Comment by sheena3** [comment]
No, it just stays the same way as in the screenshot.

**Comment by myleshorton** [comment]
That is very odd. But you see traffic on the map when not using the Tokyo data centers correct?

**Comment by sheena3** [comment]
Yes, that's correct.

**Comment by aranhoide** [comment]
I tested this locally, by just setting my cloudconfig temporarily to

    cloudconfig: https://s3.amazonaws.com/lantern_config/cloud.cn.yaml.gz

 and I get lots of `409 Conflict`s when trying to domain front.

Since @sheena3 started testing this last Saturday this is probably the cause of

https://github.com/getlantern/lantern/issues/2501

@fffw does this happen to you if you try beta5?

**Comment by aranhoide** [comment]
There are no jp.fallbacks.getiantem.org entries in Cloudflare.  That'll do it!  Looking into it...

**Comment by myleshorton** [comment]
Ha! Good catch @sheena3.

**Comment by aranhoide** [comment]
Updating the configuration of the production peerscanner and restarting it fixed this.  Could you please confirm, @sheena3 ?

So this was a failure on my end.  I must have missed some of the abovementioned steps when deploying this after testing on the test peerscanner.

**Comment by sheena3** [comment]
This works fine now. Closing!
