### ISSUE TITLE
Lantern is proxying using Tokyo server but unable to access a blocked website

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2503]
I have modified my hosts file to block alibaba.com. It worked fine when using Amsterdam server. When using Tokyo server, I am unable to access it.

![lantern is proxying using tokyo server](https://cloud.githubusercontent.com/assets/11394369/7570011/69058f26-f82a-11e4-9819-a25270af3c5c.png)
![unable to access blocked site](https://cloud.githubusercontent.com/assets/11394369/7570027/87ee841a-f82a-11e4-86e4-62cbdc62c635.png)
![connecting to tokyo server](https://cloud.githubusercontent.com/assets/11394369/7570062/b5f93058-f82a-11e4-9ac7-95c2bf3b0ea0.png)

**Comment by myleshorton** [comment]
Hmn... that's very interesting @sheena3 thanks! Can you email me the lantern.yaml you're using?

**Comment by sheena3** [comment]
@myleshorton  done.

**Comment by aranhoide** [comment]
@sheena3 : alibaba.com is not on the default list of blocked websites, so this particular issue may be a problem with detour not detecting blockage by hosts file?

**Comment by sheena3** [comment]
No Alan, it was not. I can say that because I was able to access it when I used Amsterdam server but couldn't when I used Tokyo server.

Anyways, this is now working after the new build. I am able to access the blocked site when connected to Tokyo server too.

**Comment by sheena3** [comment]
Reopening this issue as I am seeing the same problem in Ubuntu 32 bit. Probably in Mac and Ubuntu 64 bit too but haven't checked it yet.

**Comment by sheena3** [comment]
This may be related to #2514

**Comment by myleshorton** [comment]
Thanks @sheena3. And it definitely is not now happening again on Windows right? I'm wondering if there's been a reversion on the server side.

**Comment by sheena3** [comment]
It was working fine yesterday in Windows after the build you did around 1 AM IST. I didn't check with Tokyo server today.

**Comment by myleshorton** [comment]
Right yeah I'm just wondering if it's still working -- this should be affected by the specific build and is basically a server side issue.

**Comment by sheena3** [comment]
Give me few mins. I can check and let you know.

**Comment by sheena3** [comment]
Yes, this is still working fine in Windows. I am able to access the blocked website. When I try to access Google, it goes to google.co.jp. The only weird thing is, whatismyipaddress.com is showing my ip address. Yesterday it displayed the Tokyo server ip address.

**Comment by myleshorton** [comment]
That is very odd @sheena3 thanks. whatismyipaddress.com is definitely on the default list and should just be getting proxied. Can you send me your logs?

**Comment by myleshorton** [comment]
Can you also check to make sure chrome is actually still using the local proxy under chrome://net-internals?

**Comment by sheena3** [comment]
Sure @myleshorton

**Comment by myleshorton** [comment]
Thanks!

**Comment by sheena3** [comment]
Yes, I checked in chrom://net-internals too. Lantern is proxying.

**Comment by sheena3** [comment]
Effective proxy settings

PAC script: http://127.0.0.1:16823/proxy_on.pac
Source: SYSTEM

**Comment by myleshorton** [comment]
So weird. OK thanks. I'll enter a new ticket.

**Comment by sheena3** [comment]
I think we could close this as we have a separate ticket for this issue. What do you think @myleshorton ?

**Comment by myleshorton** [comment]
You're talking about #2516 @sheena3 correct? I agree they are kind of duplicates. I would rather actually close #2516 since there's more information in this ticket.

**Comment by sheena3** [comment]
Yep, that's right. I will now close #2516.

**Comment by myleshorton** [comment]
Cool thanks!

**Comment by sheena3** [comment]
Everything is working fine in Mac and Windows now. I will update for Ubuntu in #2514. Closing this now.

**Comment by myleshorton** [comment]
Awesome thanks @sheena3!
