### ISSUE TITLE
Headless build still not working 

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2504]
flashlight: flashlight.go:79 Running headless

and then:

flashlight: flashlight.go:88 Unable to start UI: Unable to listen at
localhost:16823: <nil>

followed by a program exit

**Comment by fffw** [comment]
By saying 'headless', does it mean not to serve PAC file? I think they are somewhat unrelated.

**Comment by myleshorton** [comment]
Closing this since we serve the PAC file over the UI's HTTP server, so we need to start it there.
