### ISSUE TITLE
Windows - 1.5.17 Lantern icon is displayed in Add/remove programs after installing the new build of beta 6 (

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#2507]
![lantern logo in add-remove programs](https://cloud.githubusercontent.com/assets/11394369/7595474/ef38af26-f904-11e4-9971-4830a55dcf91.png)

**Comment by sheena3** [comment]
This works fine when I uninstalled and installed it again. No idea why it showed up a different logo for the first installation.  Keeping this open just to keep an eye.

**Comment by myleshorton** [comment]
Cool thanks yeah that's just the generic windows logo -- it's effectively no logo. Weird. Relabeling this as P2.

**Comment by sheena3** [comment]
@myleshorton I think we could safely move this to beta 6 as this issue was raised for the wrong build.

**Comment by myleshorton** [comment]
Done! Actually moved all the way to beta 7.
