### ISSUE TITLE
请问chrome如何配置啊

### ISSUE THREAD

**Issue by lele2010lele** [getlantern/lantern#2510]
switchsharp怎么配置啊

**Comment by fffw** [comment]
请把情况描述清楚，到https://groups.google.com/forum/#!forum/lantern-users-en 或者https://groups.google.com/forum/#!forum/lantern-users-zh 提问。

**Comment by fffw** [comment]
Please describe your question clearly and post to https://groups.google.com/forum/#!forum/lantern-users-en or https://groups.google.com/forum/#!forum/lantern-users-zh, thanks.
