### ISSUE TITLE
Try InfluxDB for stats and perf data storage

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2511]
[InfluxDB](http://influxdb.com/) to store metrics, and [Grafana](http://grafana.org/) for reporting.

InfluxDB is a time series database written in Go which aims to "DevOps, metrics, sensor data, and real-time analytics”, a perfect match to our purpose. It’s unclear the performance when aggregating on dimensions other than time, but we can still rollup manually if it isn’t good enough.

Grafana is a dashboard which supports InfluxDB directly. Hopefully we can produce intuitive graphs by writing few or even no code.

**Comment by fffw** [comment]
[This slide](https://speakerdeck.com/pauldix/influxdb-at-nova-mamal) explains what InfluxDB can do briefly. 

I created a [repo](https://github.com/getlantern/influxdb-test) and launched a new DO server called influx-test to run InfluxDB v0.9, Grafana and a test sonar data emulator. The Grafana dashboard is publicly available at
http://192.241.211.121:3000/dashboard/db/site-load-time.

I'm also running a instance locally. It has 1M+ items and the count is continuously increasing. Query time and insert time wasn't affected. With cluster and backup support, I think it's ready for our usage.

InfluxDB has hosting plans, but only supports v0.8.2 rather than the latest v0.9. I inquired InfluxDB team through email.

**Comment by myleshorton** [comment]
Awesome @fffw! You could also ask them about any potential discounts for non-profits -- we're a registered 501c3 org.

**Comment by fffw** [comment]
v0.9 will be online in June, and they do offer us a discount.

**Comment by myleshorton** [comment]
Nice!

On Tue, May 19, 2015 at 8:38 PM, fffw <notifications@github.com> wrote:

> v0.9 will be online in June, and they do offer us a discount.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2511#issuecomment-103744928>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
Use this existing issue to track progress.

0.9.6.1 has an ever growing memory usage. I added crontab to restart it every 12 hours. Should revisit it if the InfluxDB team resolved that issue.

**Comment by myleshorton** [comment]
Should we close this @fffw?

**Comment by fffw** [comment]
Yeah sure. Thanks for checking it!
