### ISSUE TITLE
Lantern is not proxying in Ubuntu 32 bit

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2514]
Lantern browser shows that I am getting connected to Amsterdam server but whatismyipaddress.com shows my ip address.

To make sure, I checked google website. It goes to google.co.in instead of google.nl

![shows my ip address](https://cloud.githubusercontent.com/assets/11394369/7617719/dbf77ee4-f961-11e4-9609-ebb4ca7681a5.png)

**Comment by fffw** [comment]
@sheena3 Again, could you pack and send the logs under `~/.lantern/logs` to me so I can check what Lantern was doing during your test?

**Comment by sheena3** [comment]
@fffw I don't see logs under ~/.lantern but I see the log in ~/.Lantern. I believe that the former is beta 5 and the latter is beta 4 but it is getting updated when I use beta 5 Lantern. I have sent you the same.

The timestamp in the log is also incorrect.

**Comment by fffw** [comment]
I found only one occurrence of google.co.in in the logs Sheena sent to me. Browser tries to access www.google.nl, but less than 1 minute later, it accesses www.google.co.in instead. Both of them are in the whitelist.

```
May 13 18:47:23.564 - balancer: balancer.go:90 Dialing tcp://www.google.com:443 with (trusted) chained proxy at 178.62.218.162:443
May 13 18:47:25.822 - balancer: balancer.go:90 Dialing tcp://www.google.nl:443 with (trusted) chained proxy at 188.166.60.45:443
May 13 18:47:47.803 - flashlight.config: config.go:348 Fetching cloud config...
May 13 18:47:47.804 - flashlight.config: config.go:399 Checking for cloud configuration at: https://s3.amazonaws.com/lantern_config/cloud.in.yaml.gz
May 13 18:47:47.805 - balancer: balancer.go:90 Dialing tcp://s3.amazonaws.com:443 with (trusted) chained proxy at 128.199.63.206:443
May 13 18:47:50.231 - flashlight.config: config.go:393 Couldn't fetch cloud config for country 'in'; trying the default one
May 13 18:47:50.233 - flashlight.config: config.go:399 Checking for cloud configuration at: https://s3.amazonaws.com/lantern_config/cloud.default.yaml.gz
May 13 18:47:50.234 - balancer: balancer.go:90 Dialing tcp://s3.amazonaws.com:443 with (trusted) chained proxy at 178.62.197.103:443
May 13 18:47:52.975 - flashlight.config: config.go:421 Config unchanged in cloud
May 13 18:48:24.095 - detour: detour.go:283 Error while write 77 bytes to www.google.com:443 detoured: use of closed network connection
May 13 18:48:38.285 - balancer: balancer.go:90 Dialing tcp://www.google.co.in:80 with (trusted) chained proxy at 128.199.38.233:443
May 13 18:48:38.288 - balancer: balancer.go:90 Dialing tcp://www.google.co.in:443 with (trusted) chained proxy at 188.166.6.74:443
May 13 18:48:40.595 - balancer: balancer.go:90 Dialing tcp://clients1.google.com:80 with (trusted) chained proxy at 128.199.55.167:443
May 13 18:48:45.311 - balancer: balancer.go:90 Dialing tcp://www.google-analytics.com:80 with (trusted) chained proxy at 128.199.56.245:443
```

@sheena3 To make sure, what's the time zone of this Ubuntu system? If it's IST, logged time should be 5:42 in UTC, but I didn't found any such log. From the logs, access to whatismyipaddress.com happens between 19:11 to 19:17 UTC at May 13th.

**Comment by sheena3** [comment]
@fffw I will check the timezone and let you know. 

Also the log that I sent was from ~/.Lantern and not ~/.lantern. I think that is another issue. I sent you the log from the former as that was getting updated and there were no logs in .lantern folder.

**Comment by myleshorton** [comment]
Any word on if this is still an issue for you @sheena3?

**Comment by sheena3** [comment]
Sorry for the delay. Ubuntu is very slow for me as am using VMware. This works fine now. Works fine using Tokyo server too.

**Comment by fffw** [comment]
Thanks @sheena3

**Comment by myleshorton** [comment]
Awesome @sheena3. Beta 5 is now up on the beta page. Great work guys.

**Comment by sheena3** [comment]
Awesome!

On Wed, May 20, 2015 at 11:38 PM, myleshorton <notifications@github.com>
wrote:

> Awesome @sheena3. Beta 5 is now up on the beta page. Great work guys.
> On May 20, 2015 10:24 AM, "fffw" <notifications@github.com> wrote:
>
> > Thanks @sheena3
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/getlantern/lantern/issues/2514#issuecomment-103967427>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2514#issuecomment-103976945>
> .
>



-- 
Regards,
Sunshine
