### ISSUE TITLE
Installer overwrites previous settings

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2515]
If the user had modified lantern.yaml, a new installer will completely overwrite it.

**Comment by fffw** [comment]
If we want to overwrite lantern.yaml, we should show the welcome page for each new version, or user will confuse why their previous changes don't persist.

We can safely override if we already separated cloud and local config as described in https://github.com/getlantern/lantern/issues/2390

**Comment by myleshorton** [comment]
Yeah agreed @fffw. I think we should just do #2390 instead. I'm closing this.
