### ISSUE TITLE
Modify genconfig to upload to new bucket

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2519]
Related to #2517 , but it must be implemented separately because it must be done on an as-of-yet-unmerged [PR](https://github.com/getlantern/lantern/pull/2493).

In the interim, we could keep updating the old lantern_config bucket too, or just add a 'cloudconfig' entry to the cloud.yaml in the old URLs, pointing to the new ones.

**Comment by aranhoide** [comment]
For simplicity, I'll submit the PR for this as soon as #2493 and #2517 are merged.

**Comment by myleshorton** [comment]
Sorry @aranhoide I still need to get to #2493 -- will try to get to it tomorrow.

**Comment by aranhoide** [comment]
Nevermind, the config server made this one obsolete.
