### ISSUE TITLE
In Mac, Lantern UI shows connection but unable to access blocked websites

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2525]
I couldn't even access whatismyipaddress.com site

![screen shot 2015-05-15 at 8 27 00 pm](https://cloud.githubusercontent.com/assets/11394369/7655398/c8dfb1d8-fb40-11e4-86ed-df3af042154c.png)

**Comment by sheena3** [comment]
It works fine after I deleted the previous lantern.yaml file.
Seems like a problem with the lantern.yaml file. 

Possible steps:
1. Installed beta 4
2. Launched the application.
3. Installed beta 5. Mac let me replace the application. (I think lantern.yaml file was not replaced during the installation)
4. Launched the application.
5. Lantern UI shows connection to Amsterdam but unable to access blocked sites.

**Comment by sheena3** [comment]
It is not happening always but I couldn't figure out the exact reason. Let me know if you need the logs.

**Comment by fffw** [comment]
@sheena3 Yeah from the logs you sent to me, it is caused by the incorrect "trusted" field newly added to lantern.yaml in beta 5. You can visit https://whatismyipaddress.com/ instead of the plain http site to overcome it. Implementation of https://github.com/getlantern/lantern/issues/2515 can resolve it I thinlk.

**Comment by myleshorton** [comment]
Interesting @fffw. Good stuff. I missed what is incorrect in the trusted
field in beta 5. What's incorrect about it?

**Comment by fffw** [comment]
@myleshorton When user upgrades previous Lantern beta to beta 5, the `trusted` field defaults to `false` so there's no dialer available for plain http. Cloud config file doesn't have this field either.

I created https://github.com/getlantern/lantern/issues/2534 to update cloud config file.

**Comment by aranhoide** [comment]
I think the main problem here is that lantern stores the `cloudconfig` URL itself in the lantern.yaml and that overrides any built-in configuration, so when you install a new version of Lantern you'll still use the cloudconfig on disk, which for users that have ever used 2.0.0-beta(<5) is cloud.2.0.0-nl.yaml.gz (older cloud.*.yaml's point to this one).

Now that we have auto updates and that the config will be delivered by a server, I would just remove `cloudconfig` from the configuration and make it hardcoded, perhaps only overridable from the command line for testing.

**Comment by myleshorton** [comment]
@sheena3 can you try this one again? Should be fixed hopefully.

**Comment by myleshorton** [comment]
Related to #2534

**Comment by sheena3** [comment]
Yep, now the lantern.yaml file gets updated when I install beta 5 after replacing beta 4.

While opening lantern beta 5, it works fine now. Closing!

**Comment by myleshorton** [comment]
Awesome! What about #2503 and #2514? Are those still issues?

**Comment by sheena3** [comment]
I didn't see any problem related to #2503 today. Everything is working fine related to proxying in Mac. I will close that. 

Am working on #2514. I will update the ticket once I am done retesting it.

**Comment by myleshorton** [comment]
Awesome thanks @sheena3!
