### ISSUE TITLE
In Mac, I am not seeing connection to Tokyo server

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2526]
I changed the lantern.yaml file to connect to Tokyo server but it connects to Amsterdam server only.
![screen shot 2015-05-15 at 9 26 57 pm](https://cloud.githubusercontent.com/assets/11394369/7656611/2936944a-fb49-11e4-8dd4-8f45625426bd.png)

**Comment by myleshorton** [comment]
Can you send over your lantern.yaml @sheena3?

**Comment by sheena3** [comment]
@myleshorton - am sorry. It is my mistake that I didn't configure properly. 

I am getting connected to Tokyo server as well as able to access blocked site. But whatismyipaddress.com shows the country as China. Is that an issue?

![screen shot 2015-05-15 at 10 01 31 pm](https://cloud.githubusercontent.com/assets/11394369/7657297/656ec478-fb4e-11e4-92a1-bfd44ad975dc.png)

**Comment by myleshorton** [comment]
That's an issue @sheena3 but unfortunately not one we can really do anything about! No need to log it.

**Comment by sheena3** [comment]
Ok then, closing it.
