### ISSUE TITLE
Application is not launching automatically after installation in Mac as well as in Ubunut 32 bit

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2527]

**Comment by myleshorton** [comment]
Could be related to #2480

**Comment by fffw** [comment]
In fact, we didn't implement auto launch on Linux yet. We discussed it before at https://github.com/getlantern/lantern/issues/2344. What didn't mention in that thread is, a simple `ln -s` would [do the trick](https://www.liberiangeek.net/2013/05/heres-how-to-automatically-startup-programs-for-all-users-using-ubuntu-13-04-raring-ringtail/) but root privilege is required to make the change. I tested on Ubuntu 14.10.

**Comment by fffw** [comment]
@sheena3 As for auto launch on Mac, is it reproducible or not?

During my test, `~/Library/LaunchAgents/org.getlantern.plist` is always written with correct `RunAtLoad` value each time I tick/untick `Run Lantern automatically on system start` option. My Mac 10.10.3 can launch Lantern correctly after restart if the option was ticked.

**Comment by sheena3** [comment]
@fffw This issue is not about Lantern launching after system startup. This is about Lantern launching immediately after installation. In windows, if I run the installer, it will open lantern browser after installation but in Mac and Ubuntu it is not.  I have to go to the location where the application is and then launch it.

**Comment by myleshorton** [comment]
@sheena3 on OSX the installer isn't designed to open Lantern after you drag it to Applications. There's really no way to do that. Similarly on Ubuntu, we just don't support that functionality. Closing!
