### ISSUE TITLE
proxy option

### ISSUE THREAD

**Issue by frost-mage** [getlantern/lantern#2530]
please enable option to proxy all traffic

**Comment by fffw** [comment]
Duplicated with https://github.com/getlantern/lantern/issues/2497 .

@frost-mage Could you give us a hint why you want the "proxy all traffic" option?  It would help us understand your requirement more clearly.

**Comment by frost-mage** [comment]
when I load a website some off its images and css style sheets can'nt download beacause of their source are censored and lantern only proxy certain sites

**Comment by fffw** [comment]
Oh have you tried our beta release which can be downloaded at the bottom https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions @frost-mage ? It has the ability of auto detecting and proxying blocked sites even if it is not in the proxied sites list.

**Comment by frost-mage** [comment]
so what do about those blocked sites that cannt detect ?

**Comment by fffw** [comment]
It would be a great help to us if you can provide the exact url Lantern 2.0 beta failed to detect!

We are working on the "proxy all traffic" option, but auto-detection would work for most circumstances. As you may already know, proxied access to domestic sites will be significantly slowed down.
