### ISSUE TITLE
i just want to uninstall this

### ISSUE THREAD

**Issue by LetMeUninstallThis** [getlantern/lantern#2533]
for the love of god... This is REALLY pissing me off.

I have a mac. I tried uninstalling Lantern by simply deleting it from the Finder. Nope, that doesn't work. Then I try using CCleaner to uninstall but it says "I don't the permission", except it's my computer, there are no other users.

really irritated with this software right now and would like a fix.

**Comment by xiam** [comment]
Hello @LetMeUninstallThis,

Did you quit Lantern before trying to delete the Lantern icon from the Applications folder?

![quit lantern](https://www.evernote.com/shard/s209/sh/9308b039-b326-4160-b7d1-4f6f15c210a7/41fe4b0ebde601cb9ffd5d0ceb09a8c8/deep/0/Screen%20Shot%202013-08-16%20at%208.07.29%20PM.png)
