### ISSUE TITLE
2.0.0-beta5 启动的时候 修改了ie 自动配置使用脚本

### ISSUE THREAD

**Issue by lsq726** [getlantern/lantern#2536]
2.0.0-beta5 启动的时候 修改了ie 使用自动配置脚本：http://127.0.0.1:16823/proxy_on.pac

怎么样可以让 启动的时候不修改使用自动配置脚本？

**Comment by fffw** [comment]
@lsq726 Lantern doesn't have this feature for now. Why do you want to avoid changing it?

**Comment by lsq726** [comment]
@fffw 因为。。有个网页游戏的客户端 对这个过敏。。使用lantern后会登录不了。

浏览器使用chrome+swithysharp ，效果也挺好的。自动切换。
建议增加个参数。启动的时候要不要 使用pac。。方便需求的朋友。
也方便。。不想这用这个参数的朋友。

感谢制作了如此优秀的软件。。让我等被封禁的人。能找到光明。。

**Comment by xyuanmu** [comment]
我也很想知道怎么关闭，刚刚查了下源码，要改源码才能做到：https://github.com/getlantern/lantern/blob/9363758350d904e61753bc0e99a9f1edc49ec2b2/src/github.com/getlantern/flashlight/pac.go#L109

**Comment by fffw** [comment]
Duplicate with https://github.com/getlantern/lantern/issues/2559

**Comment by mystical1226** [comment]
还有，除了添加关闭PAC的设置之外，能不能不要打开lantern后自动打开网页？
