### ISSUE TITLE
启动lantern报错

### ISSUE THREAD

**Issue by xwj1003** [getlantern/lantern#2537]
![qq 20150518094222](https://cloud.githubusercontent.com/assets/1378332/7673263/504c090c-fd42-11e4-9916-01e69ae63fe3.png)

我的chrome版本 42.0.2311.82 beta-m (64-bit)

**Comment by fffw** [comment]
@xwj1003 Seems like an issue related to Chrome installation. Could you try Lantern beta version instead? It uses system default browser.

Please download it at the bottom of https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions.
