### ISSUE TITLE
Lantern server pegs one CPU

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2539]
I don't know when this started happening, but I noticed it in latest Valencia (1d38bf3d1ea582).

If I launch the same executable in a client role instead, CPU consumption is very low, barely noticeable.

I built Lantern by just using `go build` in the flashlight repo in Ubuntu 15.04 amd64.

**Comment by myleshorton** [comment]
The deployed versions in production don't seem to be pegging the CPU though
right @aranhoide? Seems like a little ```git bisect``` is in order!

On Sun, May 17, 2015 at 8:59 PM, aranhoide <notifications@github.com> wrote:

> I don't know when this started happening, but I noticed it in latest
> Valencia (1d38bf3
> <https://github.com/getlantern/lantern/commit/1d38bf3d1ea582e14fc3bf228575b122d0a2ef12>
> ).
>
> If I launch the same executable in a client role instead, CPU consumption
> is very low, barely noticeable.
>
> I built Lantern by just using go build in the flashlight repo in Ubuntu
> 15.04 amd64.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2539>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
No, the deployed versions don't do that, or we'd be drowning in fallback alarms.

I'll do a git bisect, and/or learn how to profile in go.

**Comment by myleshorton** [comment]
Are you still seeing this crop up @aranhoide?

**Comment by aranhoide** [comment]
I just pulled latest (7f03792e2b), run `go build -flags "headless"`, wiped my `~/.lantern` directory, and then run `./flashlight -role server -addr :8888 -headless`.

Surprisingly, this problem still happens.  I'll actually do a git bisect, sorry I'd forgot about this.

**Comment by aranhoide** [comment]
Well, first thing I'll try building from the Makefile.

**Comment by myleshorton** [comment]
=). Cool. I just added this to 2.0.1.

**Comment by myleshorton** [comment]
Any luck with this one @aranhoide?

**Comment by aranhoide** [comment]
Backend stuff got in the way.  I'll take a look at it now.

**Comment by aranhoide** [comment]
Dumb me, I should have tried this much earlier: the very binary that is deployed in our servers has this problem when run in any of my computers.  The major difference in both deployment environments is the Ubuntu version (14.04 in production vs 15.04 in my computer).

**Comment by aranhoide** [comment]
Conversely, I was able to build a binary in my computer that does *not* exhibit this issue by just calling `make linux-amd64` without a VERSION (!).  The HEADLESS flag doesn't seem to make any difference.  Now, if I upload this binary to a test machine and run it there, it *will* exhibit the problem.  I'm totally befuddled here...

**Comment by aranhoide** [comment]
Duh, the VERSION thing was a red herring.  I've found the bug.  I'll submit a PR for this.

**Comment by myleshorton** [comment]
Awesome!
