### ISSUE TITLE
Lantern not loading images on Facebook

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2542]
Reported by a user.

**Comment by fffw** [comment]
As this user is using beta 4 on Windows, there's no content in log file.
Sent him beta 5 link and requested him to send back logs if he would like
to help.

**Comment by fffw** [comment]
User confirmed that beta 5 can access Facebook and YouTube without any problem. Closing.

**Comment by myleshorton** [comment]
Sweet!

On Tue, May 19, 2015 at 7:59 PM, fffw <notifications@github.com> wrote:

> User confirmed that beta 5 can access Facebook and YouTube without any
> problem. Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2542#issuecomment-103736059>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
