### ISSUE TITLE
How to avoid automatic changing IE http://127.0.0.1:16823/proxy_on.pac

### ISSUE THREAD

**Issue by xyuanmu** [getlantern/lantern#2559]
Sorry for my bad English and I wanna know how to avoid automatic changing IE 'pac' mode when launch Lantern. I only use Lantern on Chrome, and it will make other software can not connect Internet when I reboot OS without Lantern.
Thank you for your reply!

**Comment by myleshorton** [comment]
Is this because you use ProxySwitchySharp? We could definitely add a
setting to turn that off.

On Thu, May 21, 2015 at 4:03 AM, xyuanmu <notifications@github.com> wrote:

> Sorry for my bad English and I wanna know how to disable automatic turn on
> IE 'pac' mode when start Lantern 2.0. I only use Lantern on Chrome and it
> will make other software can not connect Internet when I reboot OS.
> Thank you for your reply!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2559>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by xyuanmu** [comment]
@myleshorton  yes. Lantern is awesome, you really did a good job, thanks!

**Comment by TangBaohua** [comment]
中央军委发来贺电

**Comment by fffw** [comment]
There are also a few comments on Facebook requesting this feature.

**Comment by myleshorton** [comment]
We could easily just add a setting for this @fffw. That what you're thinking? The setting itself could also mention that Lantern is running at 127.0.0.1:8787 if people want to configure things like ProxySwitchySharp to use it.

**Comment by zmj1316** [comment]
Please Don't set the default system(IE) proxy, Because your pac isn't perfect,

**Comment by Chigogo** [comment]
How to config if I want that Lantern won't set global proxy on mac when launching? Because I have browser-level proxy plug-in.

**Comment by myleshorton** [comment]
This is fixed in #3626, with 2.1.0 due for release soon.
