### ISSUE TITLE
Unable to upgrade /data to websocket: websocket: key missing or blank

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2561]
Seeing this in Loggly for the new beta:

```
- flashlight.ui: ws.go:58 Unable to upgrade /data to websocket:
```

**Comment by fffw** [comment]
By inspecting Loggly messages, I suspect if they are reported by single or a few clients. Created https://github.com/getlantern/lantern/issues/2564 to group Loggly messages by unique instance id.

**Comment by myleshorton** [comment]
Agreed @fffw -- we should just implement #2564.

**Comment by myleshorton** [comment]
This is related to #2315 too.

**Comment by uaalto** [comment]
The root cause of this defect might be common to https://github.com/getlantern/lantern/issues/2721
