### ISSUE TITLE
"Error while setup detour: No dialers left to try"

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2562]
Seeing this in Loggly for the new beta:

```
detour: detour.go:233  Error while setup detour: No dialers left to try
```

**Comment by aranhoide** [comment]
This is maybe unrelated, but there's this problem that can cause these errors in a configuration update context: when the client configuration changes, it closes its old balancer.  That balancer may sill be in use by proxying goroutines that call balancer.DialQOS(), and it may be the case that, by the time the balancer actually gets to find a Dialer to use it has already released its list of dialers.

Although this error seems more specific to detour's lifecycle, maybe it would be worth fixing the one above and see whether this one goes away too.

**Comment by myleshorton** [comment]
Also see the comment in #2588
