### ISSUE TITLE
UI attempting to record analytics before backend service is up

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2575]
This is happening on pretty much every run for me:

```service.go:150 Message type Analytics belongs to an unknown service.```

I'm in that area so should be able to take care of it.

**Comment by myleshorton** [comment]
Although it does look like we get duplicates of this message later on so that analytics are actually recorded, so might be fine.

**Comment by atavism** [comment]
I think a recent change of ours from last week possibly broke this. Are you seeing this issue in https://github.com/getlantern/lantern/pull/2570? That's another reason I opened that PR: to only send the initial analytics request after the backend service is ready.

**Comment by myleshorton** [comment]
I'm actually seeing it in Valencia -- trying to fix #2480
