### ISSUE TITLE
Lantern not unsetting pac file on shutdown

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2577]
Observed on mac. Tracking PROXY_CONFIG_CHANGED in chrome://net-internals events, shutting down Lantern doesn't create a new event.

**Comment by myleshorton** [comment]
Not this is on the issue2497 branch and may not be happening on Valencia (in fact likely not)

**Comment by fffw** [comment]
It is resolved by https://github.com/getlantern/lantern/pull/2524 right? @myleshorton

**Comment by myleshorton** [comment]
Yes!
