### ISSUE TITLE
flashlight.client: http: proxy error: "No dialers left"

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2580]
This is the top event in Loggly the past two days, and this was discussed previously here: https://github.com/getlantern/lantern/issues/2440

As there's dialers left to try, we must be filtering out remaining dialers with too low QOS, and we end up with none frequently.

Here's the relevant code:
```go
	for {
		if len(dialers) == 0 {
			return nil, fmt.Errorf("No dialers left to try")
		}
		var d *dialer
		d, dialers = randomDialer(dialers, targetQOS)
		if d == nil {
			return nil, fmt.Errorf("No dialers left")
		}
		log.Debugf("Dialing %s://%s with %s", network, addr, d.Label)
```

**Comment by myleshorton** [comment]
Discussed this with @fffw, and he's experienced this when Lantern comes on and offline. I did a lot of testing with online/offline variations today and was unable to reproduce it.

**Comment by myleshorton** [comment]
It's worth noting that this error at "reverseproxy.go:186" is line 186 in go's built-in reverseproxy.go not our own. So it's the log from https://golang.org/src/net/http/httputil/reverseproxy.go, with the error typically being the error returned from our custom dial function.
