### ISSUE TITLE
http: proxy error: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2581]
Seeing this in Loggly now. Also,

```
flashlight.client: reverseproxy.go:186 http: proxy error: unsupported protocol scheme "ftp"
```

**Comment by myleshorton** [comment]
Moving to medium term -- we can't do much with other protocols at this point.

**Comment by atavism** [comment]
We're seeing a lot of variations of this in Loggly with the error: ``unsupported protocol scheme ""`` (with no protocol specified rather than what's indicated above)

**Comment by fffw** [comment]
We can reproduce it by `curl localhost:8787`(the proxy port)
