### ISSUE TITLE
detour doesn't appear to report bandwidth stats

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2584]
If you run this, for example, you'll see Lantern bandwidth stats reported as very low while curl reports higher bandwidth:

```
curl -O -x 127.0.0.1:8787 http://ftp.osuosl.org/pub/eclipse//technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-macosx-cocoa-x86_64.tar.gz
```

**Comment by fffw** [comment]
I think that's because Lantern access the site directly hence enproxy doesn't report it. Should we count these traffic? Only counting those passed through Lantern network is enough I think. We may add direct traffic to more detailed traffic report later though.
