### ISSUE TITLE
Who can add me as friends? Help!

### ISSUE THREAD

**Issue by leoliuxs29** [getlantern/lantern#2586]
Anyone who is not in China, pls add me as friends to create the bridge of Lantern. My email: leoliuxszjmi@gmail.com
Thanks!!

**Comment by fffw** [comment]
Hey, please don't ask for friends here, visit [English forum](https://groups.google.com/group/lantern-users-en) or [Chinese forum](https://lanternforum.greatfire.org/) instead.
