### ISSUE TITLE
${COUNTRY} not substituted in cloud config url

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2593]
Found in valencia but not in beta 5

```
May 29 12:29:18.823 - flashlight.config: config.go:348 Checking for cloud configuration at: https://s3.amazonaws.com/lantern_config/cloud.${COUNTRY}.yaml.gz
May 29 12:29:18.823 - fronted: dialer.go:234 Dialing s3.amazonaws.com:80 with direct domain fronter
May 29 12:29:19.021 - yamlconf: yamlconf.go:264 Custom polling failed: Unexpected response status: 409
```

**Comment by aranhoide** [comment]
Does this still happen if you clear the lantern.yaml?

As a workaround, I've just uploaded a copy of cloud.default.yaml.gz called cloud.${COUNTRY}.yaml.gz.  I'll leave this issue open as a reminder to make this point to the config server instead when that's up.

**Comment by fffw** [comment]
It stops happening. `cloudconfig` changed to config server url in the generated yaml

**Comment by myleshorton** [comment]
Yeah I'm not seeing this happen from old lantern.yaml or with deleting it. Closing. Feel free to re-open if I'm missing something.
