### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2605]
When running `make linux-amd64` on valencia

```
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:

         1. You have an upgrade for pkgconfig which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of pkgconfig of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude pkgconfig.otherarch ... this should give you an error
            message showing the root cause of the problem.

         2. You have multiple architectures of pkgconfig installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.

         3. You have duplicate versions of pkgconfig installed already.
            You can use "yum check" to get yum show these errors.

       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).

       Protected multilib versions: 1:pkgconfig-0.28-8.fc21.i686 != 1:pkgconfig-0.28-6.fc21.x86_64
```

**Comment by xiam** [comment]
Hello @fffw,

I could not reproduce the issue, I even removed the image and started again from scratch:

This is my docker and boot2docker versions:

```
boot2docker upgrade
docker is up to date (1.6.2), skipping upgrade...
boot2docker is up to date (v1.6.2), skipping upgrade...
```

Could you try deleting the image with `docker rmi`?

**Comment by fffw** [comment]
@xiam Sorry to cause you to rebuild the whole thing. I do think it can be resolved by a complete rebuild. Although I'm reluctant to do it often due to the lengthy time required.

We installed `pkg-config` package (can be an old version, `pkgconfig-0.28-6.fc21.x86_64` in this case) at L27, but due to recent change of L34, all following lines will be rerun, and L62 just tries to install a newer version of `pkgconfig.i686` (`pkgconfig-0.28-8.fc21.i686`), which triggers the conflict.

My PR fixes it temporarily, but to minimize the chance to happen, we can put those `yum install`s before more volatile commands, like `ENV`s, cloning go sources, etc. But we can leave it to next significant change to Dockerfile.

**Comment by xiam** [comment]
@fffw Don't worry!

I don't know if this was our problem, the `pkgconfig.i686` is the package we need and the `Dockerfile` does not try to install the `x86_64` version, do you think this could have been a temporary error on the Fedora repos? The fact that I ran everything from scratch and that it continued working makes me think it was something on their side.

**Comment by fffw** [comment]
Ok. It's just caused by versioning of dependent packages. As a rebuild from scratch can resolve it, I can close it.
