### ISSUE TITLE
Verify Lantern continues to work if either domain fronting or chained proxies stop working

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2608]

**Comment by xiam** [comment]
Opened one related issue for discussion: https://github.com/getlantern/lantern/issues/2622

**Comment by xiam** [comment]
Another one for discussion: https://github.com/getlantern/lantern/issues/2623

**Comment by xiam** [comment]
Also confirmed Lantern works with tcp port 80 closed (no chained proxies at all). Cool.

Also without port 53 udp but we should not rely on it anyways.

**Comment by xiam** [comment]
We should discuss this one too: https://github.com/getlantern/lantern/issues/2624

**Comment by xiam** [comment]
**Test 1**. Removing ALL chainedservers from `lantern.yaml`:

```
cloudconfig: "disabled-for-testing"
cloudconfigca: ""
chainedservers: {}
client:
  proxyall: true
  frontedservers:
    masqueradeset: cloudflare
    insecureskipverify: true
```

The rest of the `lantern.yaml` was omitted for clarity.

Result: I can browse the BBC and Facebook sites normally and even watch Youtube videos.

```
Jul 15 16:24:40.855 - DEBUG balancer: balancer.go:96 Dialing tcp://ichef.bbci.co.uk:80 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:24:40.855 - DEBUG balancer: balancer.go:96 Dialing tcp://ichef.bbci.co.uk:80 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:24:40.855 - DEBUG balancer: balancer.go:96 Dialing tcp://ichef.bbci.co.uk:80 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:24:40.856 - DEBUG balancer: balancer.go:96 Dialing tcp://ichef.bbci.co.uk:80 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
DEBUG balancer: balancer.go:96 Dialing tcp://ichef.bbci.co.uk:80 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
```

**Test 2**. Using a chained proxy that will not return a successful response.

```
  chainedservers:
    fallback-127.0.0.1:
      addr: 127.0.0.1:443
      pipelined: true
      weight: 1000000
      qos: 10
      trusted: true
```

Result: Some expected error messages about the chained dialer not rejecting connection, still able to browse Youtube, CNN, etc.

```
Jul 15 16:32:28.384 - DEBUG balancer: balancer.go:96 Dialing tcp://oauth.googleusercontent.com:443 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:32:30.581 - DEBUG flashlight.config: config.go:339 Checking for cloud configuration at: disabled-for-testing
Jul 15 16:32:30.581 - ERROR yamlconf: yamlconf.go:264 Custom polling failed: Unable to fetch cloud config at disabled-for-testing: Get disabled-for-testing: http: no Host in request URL
Jul 15 16:32:31.324 - DEBUG balancer: balancer.go:96 Dialing tcp://logs-01.loggly.com:443 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:32:33.297 - DEBUG balancer: dialer.go:138 Error testing dialer (trusted) chained proxy at 127.0.0.1:443 to humans.txt: Get http://www.google.com/humans.txt: Unable to dial server: dial tcp 127.0.0.1:443: connection refused
```

**Test 3**: Same as Test 2 but with packet dropping instead of rejection. Note that this rule makes the chained proxy (which in this case is 127.0.0.1) will not respond TCP connections from Lantern.

```
iptables -A INPUT -p tcp --dport 443 -j DROP
```

Result: Initial poor performance, nothing worked and even got expected i/o timeout messages. After a couple of  minutes Lantern recovered and I was able to watch a Youtube video. Still Lantern showed some of the i/o timeouts.

```
Jul 15 16:37:07.570 - DEBUG balancer: balancer.go:99 Unable to dial tcp://s.youtube.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 16:37:07.571 - DEBUG balancer: balancer.go:96 Dialing tcp://s.youtube.com:443 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:37:07.571 - ERROR flashlight.client: handler.go:116 Unable to respond OK: write tcp 127.0.0.1:50733: broken pipe
Jul 15 16:37:07.579 - DEBUG balancer: balancer.go:96 Dialing tcp://s.youtube.com:443 with (trusted) fronted proxy at issue-2184.getiantem.org:443 using masquerade set testflare
Jul 15 16:37:09.104 - DEBUG balancer: balancer.go:99 Unable to dial tcp://logs-01.loggly.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 16:37:09.115
```

**Test 4**:  Removing fronted servers:

```
client:
  frontedservers: {}
  chainedservers: // original list of chained servers.
```

Result: Able to browse normally, watch Youtube videos, CNN, etc.

```
Jul 15 16:42:42.042 - DEBUG balancer: balancer.go:96 Dialing tcp://de.realmediadigital.com:80 with (trusted) chained proxy at 188.166.123.90:443
Jul 15 16:42:42.045 - DEBUG balancer: balancer.go:96 Dialing tcp://de.realmediadigital.com:80 with (trusted) chained proxy at 188.166.123.90:443
Jul 15 16:42:43.477 - DEBUG balancer: balancer.go:96 Dialing tcp://optimized-by.rubiconproject.com:80 with (trusted) chained proxy at 188.166.123.90:443
Jul 15 16:42:44.967 - DEBUG balancer: balancer.go:96 Dialing tcp://de.realmediadigital.com:80 with (trusted) chained proxy at 188.166.123.90:443
Jul 15 16:42:44.967 - DEBUG balancer: balancer.go:96 Dialing tcp://de.realmediadigital.com:80 with (trusted) chained proxy at 188.166.123.90:443
```

**Comment by uaalto** [comment]
I'm trying to reproduce your tests, but often the lantern.yaml file gets overwritten, even after changing ```cloudconfig: "disabled-for-testing"``` (which I thought it would avoid contacting the config server).

**Comment by myleshorton** [comment]
Thanks @xiam! If I run your first test I actually get the "No trusted dialers" error -- https://github.com/getlantern/lantern/issues/2667

This looks like it's the result of masquerades not being considered trusted in the local config. So until Lantern's able to download the cloud config, it doesn't consider any fronted servers to be trusted. I ticketed that at #2737 and assigned it to myself.

So that's really a matter of what lantern.yaml you're basing your changes off of. It it's the cloud one, I think your test results hold up, but if it's the local one they won't. I'm going to fix #2737 for now and then circle back.

**Comment by myleshorton** [comment]
That's interesting @uaalto. I wonder what's up -- I'll play with it for a sec.

**Comment by myleshorton** [comment]
@uaalto I'm not seeing that on my end. I'm just modifying the lantern.yaml at ~/Library/Application Support/Lantern/lantern.yaml. Is that what you're doing too?

**Comment by uaalto** [comment]
Ok I found it. It overwrites the yaml config if there are __neither__ no fronted and chained servers. I was able to reproduce tests 1 and 2 however, so that was the strange thing. The config endpoint is hard-coded:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/config/config.go#L219

**Comment by uaalto** [comment]
I'm actually trying to make it fail, to observe also that behavior.

**Comment by myleshorton** [comment]
Makes sense @uaalto. It only hard codes the config if it's empty though -- if cfg.CloudConfig == ""

**Comment by uaalto** [comment]
It still updates the config with the -cloudconfig="http://localhost/fakeconfig", however. What's the highest priority config point? (yaml, command line flags, hard-coded, or any other).

**Comment by myleshorton** [comment]
You're talking about the command line flag -cloudconfig="http://localhost/fakeconfig"? I never use that myself so would have to look at the code, but I partly don't use it because it doesn't replicate anything that happens in production. In production Lantern will first look at the yaml but then does this verification step essentially when applying default, and then it will do the same when downloading the remote cloud.yaml.

**Comment by uaalto** [comment]
Yes, I thought I could override everything with the flag, so there is no overwriting of the yaml file.

**Comment by aranhoide** [comment]
My steps:

- remove my local ~/.lantern/lantern.yaml
- launch lantern with `flashlight -cloudconfig https://somebogusdomain.com`
- kill lantern
- remove all the (default) chained servers but one (128.199.48.56)
- launch lantern
- check whatismyipaddress.com to verify I'm proxying through 128.199.48.56
- open a long youtube video
- ssh into 128.199.48.56
- kill the lantern service there

Immediate effects:

- There was a short time in which trying to reload whatismyipaddress.com
gave me a blank page.
- The youtube window reported an error and prompted me to retry.
- A few of the following showed up in the local Lantern logs:

```
Jul 15 20:07:52.846 - DEBUG balancer: balancer.go:96 Dialing tcp://
encrypted-tbn2.gstatic.com:443 with fronted proxy at
nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jul 15 20:07:52.846 - DEBUG balancer: balancer.go:96 Dialing tcp://
encrypted-tbn3.gstatic.com:443 with fronted proxy at
nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jul 15 20:07:52.856 - DEBUG balancer: balancer.go:96 Dialing tcp://
encrypted-tbn0.gstatic.com:443 with fronted proxy at
nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jul 15 20:07:53.287 - DEBUG enproxy: conn_impl.go:45 Proxy connection to
s.youtube.com:443 via 162.159.240.99:443 idle for 10s, closing
Jul 15 20:07:53.448 - DEBUG balancer: balancer.go:96 Dialing tcp://
images-na.ssl-images-amazon.com:443 with fronted proxy at
nl.fallbacks.getiantem.org:443 using masquerade set cloudflare
Jul 15 20:07:54.148 - DEBUG fronted: dialer.go:231 Dialing
geo.getiantem.org:80 with direct domain fronter
Jul 15 20:07:54.993 - DEBUG balancer: dialer.go:138 Error testing dialer
(trusted) chained proxy at 128.199.48.56:443 to humans.txt: Get
http://www.google.com/humans.txt: Unable to dial server: dial tcp
128.199.48.56:443: connection refused
Jul 15 20:07:56.942 - DEBUG balancer: balancer.go:133 No dialers meet
targetQOS 0 or highestQOS 0!
Jul 15 20:07:56.942 - ERROR detour: detour.go:140 Dial detoured failed: No
dialers left
Jul 15 20:07:56.942 - ERROR flashlight.client: reverseproxy.go:186 http:
proxy error: No dialers left
```

After a short while (maybe 1-2 minutes):

- I could reload whatismyipaddress.com again, and I got a different
Amsterdam IP (ie. a fronted server).
- I could continue watching the youtube video.

So it's not as smooth as I expected/wished for, but Lantern eventually
recovers and carries on with domain fronting.

**Comment by uaalto** [comment]
Here is the thing. I don't know if I'm missing something, but I get this behavior:

* No fronted servers
* One single chained server that is fake (doesn't point to a real one). I've tried also with loopback.
* Proxy all

I can still browse Youtube/BBC, and getting these logs (depending on the bad chained server)
```
DEBUG balancer: balancer.go:96 Dialing tcp://ssl.google-analytics.com:443 with (trusted) chained proxy at 127.0.0.1:443
```
or
```
balancer: balancer.go:96 Dialing tcp://ssl.google-analytics.com:443 with (trusted) chained proxy at 8.166.27.173:443
```
which looks like works, but couldn't be possible working. Of course, afterwards it fails with timeout. My point is that these messages don't convey a successful proxying.

Also, how is this working?

**Comment by myleshorton** [comment]
Thanks @aranhoide! I *think* what you're seeing works because you're going to an https site, so you don't need trusted dialers. But it at least makes sense it would work in that case I think.

@uaalto I think we're just not reporting errors for failed attempts at hitting tcp://ssl.google-analytics.com:443, although it's odd it would still include those bogus chained proxies in the list at all -- i.e. how did they pass verification and get into the balancer at all? That sounds like a bug to me. 

The other thing it's useful to continually check is chrome://net-internals/#proxy, as it's possible chrome has bypassed Lantern altogether in a lot of these cases.

**Comment by myleshorton** [comment]
Oh also @uaalto you probably realize this but those analytics URLs are from Lantern hitting those directly internally, i.e. they're not coming from the browser. So they're just somewhat unique, but I still agree it looks like a bug that Lantern would even be trying to hit them with bogus chained servers.

**Comment by xiam** [comment]
I can confirm that if I comment out both `frontedservers` and `chainedservers` the `lantern.yaml` gets overwritten

**Comment by myleshorton** [comment]
On that front @xiam remember when users first start *there is no lantern.yaml*, so commenting both out effectively recreates that case.

**Comment by xiam** [comment]
@uaalto 

If I set no fronted servers and use a single chained server that does not work, Lantern shows a blank page instead:

```
client:
  frontedservers: {}
  chainedservers:
    fallback-127.0.0.1:
      addr: 127.0.0.1:443
      pipelined: true
      weight: 1000000
      qos: 10
      trusted: true
```

The log looks like this:

```
Jul 15 20:37:59.939 - DEBUG balancer: balancer.go:96 Dialing tcp://eluniversal.com.mx:80 with (trusted) chained proxy at 127.0.0.1:443
Jul 15 20:38:08.154 - DEBUG balancer: balancer.go:99 Unable to dial tcp://ssl.google-analytics.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:08.154 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:08.155 - DEBUG balancer: balancer.go:99 Unable to dial tcp://update.getlantern.org:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:08.155 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:08.156 - ERROR analytics: analytics.go:151 Could not send HTTP request to GA: Post https://ssl.google-analytics.com/collect: Bad Gateway
Jul 15 20:38:08.158 - ERROR autoupdate: autoupdate.go:97 Problem checking for update: Problem fetching update: Post https://update.getlantern.org/update: Bad Gateway
Jul 15 20:38:09.069 - DEBUG balancer: balancer.go:99 Unable to dial tcp://ssl.google-analytics.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:09.069 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:09.074 - ERROR analytics: analytics.go:151 Could not send HTTP request to GA: Post https://ssl.google-analytics.com/collect: Bad Gateway
Jul 15 20:38:11.156 - DEBUG balancer: balancer.go:99 Unable to dial tcp://www.youtube.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:11.156 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:12.684 - DEBUG balancer: balancer.go:99 Unable to dial tcp://clients1.google.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:12.685 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:13.021 - DEBUG balancer: balancer.go:99 Unable to dial tcp://logs-01.loggly.com:443: Unable to dial server: dial tcp 127.0.0.1:443: i/o timeout
Jul 15 20:38:13.021 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left to try
Jul 15 20:38:18.033 - DEBUG balancer: balancer.go:133 No dialers meet targetQOS 0 or highestQOS 0!
Jul 15 20:38:18.033 - DEBUG flashlight.client: handler.go:140 Responding BadGateway: Unable to handle CONNECT request: No dialers left
```

But I think that would not be too likely to happen naturally.

**Comment by xiam** [comment]
> On that front @xiam remember when users first start there is no lantern.yaml, so commenting both out effectively recreates that case.

Right! thanks @myleshorton

**Comment by aranhoide** [comment]
> Thanks @aranhoide! I think what you're seeing works because you're going to an https site, so you don't need trusted dialers. But it at least makes sense it would work in that case I think.

Indeed I was accessing both youtube and whatismyipaddress via HTTPS.

**Comment by uaalto** [comment]
I could reproduce the (expected) failures in an Ubuntu VM. You can't browse . But I couldn't reproduce the expected behavior on OSX. That is, it works in OSX while it shouldn't.

This is not the gist of the issue at hand, but I just wanted to mention it, since I'm not sure about the reason. I'm using Firefox on both OS and the settings are the same (those mentioned above).

**Comment by xiam** [comment]
@uaalto I tested this on OSX. This only happens to me if I manually add the bogus chainedserver to the `lantern.yaml` before starting Lantern:

```
Jul 16 18:26:58.628 - DEBUG flashlight: pac.go:135 Serving PAC file at http://127.0.0.1:16823/proxy_on.pac
Jul 16 18:26:58.658 - DEBUG balancer: balancer.go:96 Dialing tcp://ssl.google-analytics.com:443 with (trusted) chained proxy at 127.0.0.1:443
Jul 16 18:26:58.658 - DEBUG balancer: balancer.go:96 Dialing tcp://update.getlantern.org:443 with (trusted) chained proxy at 127.0.0.1:443
```

Which I think is expected, since after Lantern starts and adds the full list of chained and fronted proxies to the balancer all the proxies are considered "ready to use" until they're tested and marked as failed proxies.

**Comment by uaalto** [comment]
But then you would expect the lantern.yaml file to be overwritten, right? (which it isn't). What you mention happens to me when I remove all chainedservers and frontedservers. I've tried many times, so I wonder whether I'm doing something differently or there is any configuration peculiarity in my system.

**Comment by myleshorton** [comment]
> But then you would expect the lantern.yaml file to be overwritten, right?

I think you're responding to @xiam here right? If so, with the single chained server in the ```lantern.yaml```, it won't overwrite it. You're only seeing it overwrite the lantern.yaml if you remove all the servers right @uaalto?

**Comment by myleshorton** [comment]
> Which I think is expected, since after Lantern starts and adds the full list of chained and fronted proxies to the balancer all the proxies are considered "ready to use" until they're tested and marked as failed proxies.

Yeah I think that's exactly right. I think we arguably could preemptively test them, which we'd effectively be doing primarily to see if they're blocked, but it's not 100% clear what the best approach is.

**Comment by xiam** [comment]
@myleshorton 

> Yeah I think that's exactly right. I think we arguably could preemptively test them, which we'd effectively be doing primarily to see if they're blocked, but it's not 100% clear what the best approach is.

The good thing is that they'll be tested eventually. I think the current approach is good because it allows Lantern to have a fast start in most cases, if we had to test proxies before starting up that would add a delay to all users.

**Comment by xiam** [comment]
@uaalto Could you attach your yaml file? I think that way I will be able to reproduce your case.

**Comment by uaalto** [comment]
Yep. Attached.


Ulysses Aalto

**Comment by uaalto** [comment]
> I think you're responding to @xiam here right? If so, with the single chained server in the lantern.yaml, it won't overwrite it. You're only seeing it overwrite the lantern.yaml if you remove all the servers right @uaalto?

exactly, @myleshorton

**Comment by myleshorton** [comment]
I think we can safely say Lantern does keep working in this case. I just ran one final test, and I think we're in good shape.
