### ISSUE TITLE
trustedcas should be overwritten, not appended to, in config

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2612]
To prevent buildup of redundant CA entries which causes higher CPU usage, and so we can remove CAs we no longer trust or need.

**Comment by aranhoide** [comment]
Note that https://github.com/getlantern/lantern/issues/2390 would subsume this, but since this is a much smaller change I think it's worth doing in the interim.

**Comment by myleshorton** [comment]
agreed

On Fri, Jun 5, 2015 at 8:15 PM, aranhoide <notifications@github.com> wrote:

> Note that #2390 <https://github.com/getlantern/lantern/issues/2390> would
> subsume this, but since this is a much smaller change I think it's worth
> doing in the interim.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2612#issuecomment-109514069>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
