### ISSUE TITLE
Test are failing on Travis. "=== RUN TestFraming-32 fatal error: all goroutines are asleep - deadlock!"

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2619]
You can test with `make test-and-cover`:

```
ERROR balancer: balancer.go:83 No trusted dialers!
DEBUG balancer: balancer.go:157 No dialers meet targetQOS 0 or highestQOS 0!
ERROR balancer: balancer.go:83 No trusted dialers!
DEBUG balancer: balancer.go:157 No dialers meet targetQOS 0 or highestQOS 0!
ERROR balancer: balancer.go:83 No trusted dialers!
DEBUG balancer: balancer.go:157 No dialers meet targetQOS 0 or highestQOS 0!
```

**Comment by aranhoide** [comment]
I just pulled latest Valencia and tests pass for me.  I do get those logs printed out, but they don't cause any actual test failures.  I'll take a look at what's going on.

Do you actually get errors in your final report, or only these printouts while the tests are running?

**Comment by xiam** [comment]
You're right, it must be other completely different thing, Travis ends up with this:

```
PASS
coverage: 92.8% of statements
ok  	github.com/getlantern/fdcount	1.658s
=== RUN TestFraming-32
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
testing.RunTests(0x7b0f80, 0x89faa0, 0x3, 0x3, 0xc20803ae01)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20800a550, 0x8aacc0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/getlantern/framed/_test/_testmain.go:102 +0x291
goroutine 5 [semacquire]:
sync.(*WaitGroup).Wait(0xc20802e5e0)
	/usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/getlantern/framed.TestFraming(0xc208082000)
	/home/travis/gopath/src/github.com/getlantern/lantern/src/github.com/getlantern/framed/framed_test.go:98 +0x7f8
testing.tRunner(0xc208082000, 0x89faa0)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b
exit status 2
FAIL	github.com/getlantern/framed	1.611s
make: *** [test-and-cover] Error 1
The command "make test-and-cover" exited with 2.
Done. Your build exited with 1.
```

**Comment by xiam** [comment]
I ran the test locally and it passed beyond that part.

**Comment by aranhoide** [comment]
A comment in the source code of that test:

    // Do a bunch of concurrent reads and writes to make sure we're threadsafe

Apparently, we're not threadsafe. :)

The thing is, we're not using this code for anything yet, and it's not clear we'll ever use it.  I would:

- push any changes in framed and waddell upstream, and

- remove framed and waddell from the getlantern/lantern project.

**Comment by uaalto** [comment]
This is something that I can take into account when rebuilding directory structure for Gb.

**Comment by myleshorton** [comment]
I'm seeing a failure in balancer_test.go, below. I don't think that code has changed much, and it's definitely passing for me locally on OSX although the test runs forever on Ubuntu. I'll keep looking at it.

```
ERROR balancer: balancer.go:83 No trusted dialers!
DEBUG balancer: balancer.go:111 Dialing tcp://127.0.0.1:54294 with Dialer 4
ERROR balancer: balancer.go:83 No trusted dialers!
--- FAIL: TestAll-2 (1.25s)
	Location:	balancer_test.go:226
	Error:		No error is expected but got No dialers left
	Messages:	Dialing should have succeeded
		
FAIL
coverage: 93.0% of statements
exit status 1
FAIL	github.com/getlantern/balancer	2.778s
make: *** [test-and-cover] Error 1
```

**Comment by myleshorton** [comment]
Correction: balancer_test.go on Ubuntu only runs forever if you don't redirect the output to a file -- it's the logging to the console that takes forever, but the tests pass for me. Continuing to investigate!

**Comment by fffw** [comment]
Seems the test result is strongly related to running speed. [#1698](https://travis-ci.org/getlantern/lantern/builds/67333757) and [#1696](https://travis-ci.org/getlantern/lantern/builds/67328769) are for same commit, one failed whereas another passed.

![image](https://cloud.githubusercontent.com/assets/10410437/8228110/d7fe3db6-15de-11e5-9f03-22552500ebf8.png)

**Comment by myleshorton** [comment]
Closing since framed is no longer used.
