### ISSUE TITLE
Encounter errors when build docker/windows/linux pakage for lantern 2.0.0.6 beta

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2620]
Encounter errors when build docker/windows/linux pakage for lantern 2.0.0.6 beta

root@gary-ThinkPad-X240:/home/gary/lantern-2.0.0-beta6# make docker
fatal: Not a git repository (or any of the parent directories): .git
Missing "go" command.
Makefile:215: recipe for target 'system-checks' failed
make: *** [system-checks] Error 1

BTW : already installed golang1.4.2, GNU-Make,Docker, OS: Ubuntu 14.10

Pls help ,thx!

**Comment by fffw** [comment]
@yuan78 So you are building from the packaged source code? I guess it requires git repo to be built successfully but not sure.

**Comment by yuan78** [comment]
Yes, I'm building from the packaged source code,but cannot do it successfully. 

BTW : already installed golang1.4.2, GNU-Make,Docker, OS: Ubuntu 14.10

**Comment by fffw** [comment]
You can play around a bit with Makefile
`GO := $(shell which go 2> /dev/null)`

**Comment by yuan78** [comment]
Can you advise detailed procedures?
Go directory is /home/go 

and GO  environment  variant is configured as below:
~/.bashrc

export GOROOT=~/go
export GOARCH=386（或amd64）
export GOOS=linux
export GOBIN=$GOROOT/bin/
export GOTOOLS=$GOROOT/pkg/tool/
export PATH=$PATH:$GOBIN:$GOTOOLS

**Comment by yuan78** [comment]
~/.bashrc

export GOROOT=~/go
export GOARCH=amd64
export GOOS=linux
export GOBIN=$GOROOT/bin/
export GOTOOLS=$GOROOT/pkg/tool/
export PATH=$PATH:$GOBIN:$GOTOOLS

**Comment by fffw** [comment]
The instructions are all placed in `README.md`. Could you try `git clone` to local and `git checkout` to a specific branch or tag instead of download zip? That's how we work on Lantern so you may experience less pain.

If you just want a binary, you can download it from https://getlantern.org/ or the bottom of https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions

**Comment by yuan78** [comment]
But I just want to build a binary from 2.0.0-beta6 source code , which hv no git branch, how can I do?

**Comment by fffw** [comment]
Just `git checkout 2.0.0-beta6` as `2.0.0-beta6` is an existing tag.

**Comment by yuan78** [comment]
Hi, show errors when run git checkout:
git checkout https://github.com/getlantern/lantern/releases/tag/2
.0.0-beta6
fatal: Not a git repository (or any of the parent directories): .git

**Comment by fffw** [comment]
UTFG. Apparently you are still using the downloaded source code instead of `git clone` right?

**Comment by yuan78** [comment]
No, I just follow your instruction to git clone from remote branch,but fail.
Because I'm freshman  and not familar for git tools , need your help for
details

2015-06-11 8:51 GMT+08:00 fffw <notifications@github.com>:

**Comment by aranhoide** [comment]
@yuan78 try cloning the repository first:

```bash
git clone git://github.com/getlantern/lantern
cd lantern
git checkout 2.0.0-beta6
```

**Comment by yuan78** [comment]
Thanks a lot ,  I follow your instructions to hv done,and get below info.
Then how can I do for build a binary for windows package ?

E:\lantern\lantern>git checkout 2.0.0-beta6
Note: checking out '2.0.0-beta6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 95eff89... Merge pull request #2613 from getlantern/issue2612

2015-06-11 10:43 GMT+08:00 aranhoide <notifications@github.com>:

**Comment by fffw** [comment]
Please ref https://github.com/getlantern/lantern/#building-for-windows

**Comment by yuan78** [comment]
Hi ,
But still encounter below errors when build window binary:

gary@gary-ThinkPad-X240:~$ cd lantern
gary@gary-ThinkPad-X240:~/lantern$ make windows
Sending build context to Docker daemon
FATA[0000] Post
http:///var/run/docker.sock/v1.18/build?cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=lantern-builder:
dial unix /var/run/docker.sock: permission denied. Are you trying to
connect to a TLS-enabled daemon without TLS?
Makefile:189: recipe for target 'docker' failed
make: *** [docker] Error 1


2015-06-11 13:32 GMT+08:00 fffw <notifications@github.com>:

**Comment by aranhoide** [comment]
Try:

```bash
usermod -aG docker gary
```
Then log out of your session and back in.  If the problem persists, try:
```
sudo service docker restart
```

**Comment by myleshorton** [comment]
Closing unless this is still a problem for you @yuan78

**Comment by yuan78** [comment]
Thanks, but still show errorsd info when I run make docker(my OS is ubuntu 14.10 but not fedora or CentOS):

Step 9 : RUN yum -y update && yum clean all
 ---> Running in 0b1c49150456


 One of the configured repositories failed (Fedora 21 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable fedora

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=fedora.skip_if_unavailable=true

Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its path and try again
INFO[0050] The command [/bin/sh -c yum -y update && yum clean all] returned a non-zero code: 1 
Makefile:189: recipe for target 'docker' failed
make: *** [docker] Error 1
