### ISSUE TITLE
Lantern requires port 443 to work

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2624]
Lantern requires tcp port 443 to be open. If 443 is closed nothing works, even when port 80 is wide open.

You can test this by blocking all traffic on port 443

```
iptables -A OUTPUT -p tcp --dport 443 -j DROP
```

My test:

```
curl http://www.google.com/humans.txt
Google is built by a large team of engineers, designers, researchers, robots, and others in many different sites across the globe. It is updated continuously, and built with more tools and technologies than we can shake a stick at. If you'd like to help us out, see google.com/careers.

curl -x 127.0.0.1:8787 http://www.google.com/humans.txt
(timed out)
```

**Comment by aranhoide** [comment]
Do you mean Lantern running as server?  It's never even supposed to be able to be used as a vanilla HTTP proxy.  So I guess that test will fail even if you unblock 443.

Anyway, Lantern takes an `-addr` command line argument where you can specify the port.  Our flashlight servers run on port 62443 (we have ufw rules to redirect 443 to that).

Please reopen if I've misunderstood this.

**Comment by aranhoide** [comment]
Oh, I see you mean dropping *outgoing* packets to port 443.  I think this is actually OK.  The traffic between the Lantern client and any Lantern proxy, be it chained or fronted, needs to be encrypted, and I imagine chained servers taking encrypted traffic through port 80 would be fingerprintable.

**Comment by xiam** [comment]
Yeah @aranhoide, I tested Lantern as a client.

I understand your point on encryption but I am also thinking of an user on a restricted network where traffic through port 443 is not allowed but traffic through port 80 is. If this hypothetical user turns on Lantern she will not be able to browse at all, even though she was able to browse some unencrypted sites before. This user may not immediately realise what's really happening, the only thing she will know is that she was able to browse some sites before turning on Lantern and now she's completely blocked out because of it.

Probably Lantern should try direct access as a last resort and warn the user that her traffic is not being proxied. Anyways, Lantern is not showing any error at all, it just waits there for a timeout to happen. Maybe we can't proxy through plain HTTP but we probably can tell the user why Lantern is not working.

**Comment by aranhoide** [comment]
I think a user in that situation would just close Lantern, which is what they should do.  Why run Lantern if you're only getting direct access?  That can only cause confusion.

We could set up some servers accepting TLS connections on port 80.  But I don't recall ever having a single user requesting this.

**Comment by myleshorton** [comment]
Yeah that would be a very odd network that allowed outgoing TCP on 80 but not on 443. This is the type of thing we would have to actually see in the field. We shouldn't spend time fixing theoretical bugs that are unlikely to happen in the real world. Closing unless there's something I'm missing here @xiam.
