### ISSUE TITLE
Lantern proxying but unable to load the blocked page

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2627]
This happens only with certain sites though. 

I am able to access facebook and twitter. But I couldn't access www.alibaba.com.

Steps:

1. Modify the hosts file. I pointed it to Fake DNS server
104.131.168.238 alibaba.com
104.131.168.238 www.alibaba.com
104.131.168.238 www.twitter.com
104.131.168.238 www.facebook.com
2. I couldn't access alibaba.com alone. 

I am not sure if I am doing it right as it works with the other sites. Let me know

**Comment by sheena3** [comment]
This is in windows

**Comment by fffw** [comment]
That's because accessing directly to 104.131.168.238:80 results a
connection refused error, which is not considered as been blocked. But
sometimes, the same attempt results an i/o timeout, which is treated as
been blocked, hence "detoured". We can add connection refused error to
blockage detection rule, but it's somewhat useless in real world.

Twitter and Facebook are in proxied sites list, so access to them will
always be via proxy.

**Comment by myleshorton** [comment]
My understanding with this is that you need to modify the DNS server locally to point to 104.131.168.238. That's the address of our actual fake DNS server right @sheena3, @fffw, and @xiam? If you just set your hosts file to point to that address, you might as well just have it point to 0.0.0.0. I.e. I think the test you want is to just set your DNS server to 104.131.168.238 and not to modify /etc/hosts at all unless I'm misunderstanding something.

**Comment by sheena3** [comment]
@myleshorton Thanks! That worked like a charm. Yeah, I changed my DNS server to point 104.131.168.238 and it blocked all the sites including gmail. After using Lantern, I am able to access all the blocked sites. Closing!

**Comment by myleshorton** [comment]
Oh I'm glad @sheena3!

**Comment by myleshorton** [comment]
Interesting @sheena3 thanks! I'm actually having trouble getting that DNS server to work, but I'm still not sure exactly what it's supposed to do. What's it supposed to do again @xiam and @fffw? Its output appears normal to me:

```
 dig @104.131.168.238 twitter.com

; <<>> DiG 9.8.3-P1 <<>> @104.131.168.238 twitter.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19795
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		30	IN	A	199.59.148.82
twitter.com.		30	IN	A	199.59.149.230
twitter.com.		30	IN	A	199.59.149.198
twitter.com.		30	IN	A	199.59.150.7
```

**Comment by xiam** [comment]
Hey @myleshorton,

Not sure what's exactly happening on your end, but it is not supposed to do that:

```
dig @104.131.168.238 twitter.com

; <<>> DiG 9.8.3-P1 <<>> @104.131.168.238 twitter.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33201
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		0	IN	A	127.0.0.1

;; Query time: 177 msec
;; SERVER: 104.131.168.238#53(104.131.168.238)
;; WHEN: Mon Jun 15 17:53:26 2015
;; MSG SIZE  rcvd: 45
```

And `nslookup` too:

```
nslookup twitter.com 104.131.168.238
Server:		104.131.168.238
Address:	104.131.168.238#53

Name:	twitter.com
Address: 127.0.0.1
```

**Comment by myleshorton** [comment]
Interesting -- that is very odd. I'm seeing the same as you from one of our servers, so there must be something strange happening for me locally. Thanks @xiam!
