### ISSUE TITLE
Proxied through Netherlands server but goes to Google.ru

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2628]
It looks like an issue to me. 

I am getting connected to Netherlands server. When accessing google, it goes to google.ru instead of google.nl.

**Comment by myleshorton** [comment]
I actually don't think we care which version of Google it goes to.

**Comment by sheena3** [comment]
If the server is in Netherlands why would it access Google Russia. Last time when I was testing beta 5, it accessed Google Netherlands and for Tokyo servers, it went to Google.jp.

I just want to make sure that this is not an issue. If not, then I will close it.

**Comment by myleshorton** [comment]
It might just not be geolocating it correctly, but that's not a problem.

**Comment by sheena3** [comment]
Okay then, closing it now!
