### ISSUE TITLE
If IE is the default browser and lantern is running, then chrome browser is not recognizing lantern

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2629]
This happens only when IE is default browser. Firefox is proxying. The problem is just chrome. I noted this by opening whatismyipaddress.com in all the 3 browsers. Chrome browser alone displayed my ip address and the other two displayed the Netherland server details..

If Firefox or chrome is default browser, then the other two browsers recognize lantern.

**Comment by myleshorton** [comment]
I think this is probably a coincidence @sheena3. My guess is that Chrome is marking Lantern as a bad proxy but happened to do it in the scenario you described.

Did you noticed what Chrome's proxy settings were at the time under chome://net-internals?

**Comment by sheena3** [comment]
@myleshorton  I keep forgetting to check the proxy settings in chrome when something like this happens. Am sorry about that. I will try to make it a habit. However, I couldn't reproduce this now. And I don't remember the exact steps that I followed. So, I am closing this for now.
