### ISSUE TITLE
I am always gettting connected to only one server 188.166.123.90

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2630]
Shouldn't the servers be in rotation? Noticed this recently when I tested with different browsers.

**Comment by sheena3** [comment]
I even tried quitting and relaunching the application. Still the same.

**Comment by myleshorton** [comment]
That's how it should work.

On Wed, Jun 10, 2015 at 2:10 PM, sheena3 <notifications@github.com> wrote:

> I even tried quitting and relaunching the application. Still the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2630#issuecomment-110859569>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by sheena3** [comment]
Okay, but in beta 5 we were rotating the servers, right? Is this something new in beta 6?

**Comment by aranhoide** [comment]
Yep. ;)

**Comment by xiam** [comment]
Hello @sheena3, this is something we're trying out, we try to select the server that we think would be better suited for the user and then Lantern sticks with that server.
