### ISSUE TITLE
lantern-ui assets file name versioning

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2634]
To prevent incorrect caching.

We concatenated js and css but didn't rename it.

**Comment by fffw** [comment]
Should also rename partials

**Comment by myleshorton** [comment]
Yeah this is pretty important @fffw. We could also just add no cache headers to the HTTP responses.

**Comment by fffw** [comment]
By inspecting lantern ui from Chrome browser, `http.FileServer` sends back `Last-Modified` and respects `If-Modified-Since` correctly. Theoretically, web page should not be cached incorrectly. @myleshorton Could you find a clue on how to reproduce it?

**Comment by myleshorton** [comment]
It seems this is resolved.
