### ISSUE TITLE
Lantern doesn't seem to work in a virtual machine

### ISSUE THREAD

**Issue by LeoK987** [getlantern/lantern#2637]
It has been working for me getting access on Ubuntu 14.04 64bits.  Recently I installed it on the same OS installed on VirtualBox.  Lantern seems to run fine with printouts in a terminal, but it doesn't get me access through the browsers.  I tried the same virtual machine on both Ubuntu host and a OSX host and in neither case lantern gets me access.  I used NAT for networking for the virtual machine.  Is there anything I am doing wrong?

EDIT:  Lantern printouts in the terminal do not seem to reflect connection requests from the browser.  I also tried bridged network on VirtualBox and the results are the same.

**Comment by xiam** [comment]
Hello @LeoK987,

Which desktop environment are you using? Lantern should handle this on its own but can you try with manual configuration?

![screen shot 2015-06-12 at 9 10 14 am](https://cloud.githubusercontent.com/assets/385670/8131860/dd34b900-10e2-11e5-9a3f-df06c4e838ff.png)

**Comment by LeoK987** [comment]
Thanks very much Carlos.  With Firefox, your suggestion made it work.

I can't set proxy within Chrome's setting.  It gives me the following
message:

"When running Google Chrome under a supported desktop environment, the
system proxy settings will be used. However, either your system is not
supported or there was a problem launching your system configuration.

But you can still configure via the command line. Please see man
google-chrome-stable for more information on flags and environment
variables."

Starting Chrome using option --proxy-server="127.0.0.1:8787" works.

I use Xubuntu.  I am not sure how lantern sets system proxy on the system
(mysteriously Chrome on my main computer works).  Reportedly it should be
set in /etc/environment, but that file (both in my main computer and in the
virtual machine) does not have related settings.

**Comment by LeoK987** [comment]
I figured out how chrome on my main computer works.  It is because I have
SwitchySharp addon and in there I set the proxy to 127.0.0.1:8787.
Disabling that addon, proxy does not work.

So perhaps Lantern needs to correct settings for Xubuntu (I am not sure if
it got set correctly under Ubuntu).  As of now, it does not work by default.

**Comment by xiam** [comment]
Universal support for Linux is a medium term goal, right now we're testing on Ubuntu and Unity desktop only. In the meantime we'll create special documentation for Lantern from command line for Linux users, see https://github.com/getlantern/lantern/issues/2466
