### ISSUE TITLE
In Mac, I couldn't access gmail.com even after starting lantern

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2638]
Steps:

1. Modified the DNS server to block all sites.
2. Now start lantern without proxy all
3. Unable to access gmail.com but able to access facebook, twitter, github

I am sure gmail.com is in the default proxied list but still unable to access after launching lantern. When I tested the same in Windows yesterday, it was working fine.

I am able to access the same when I used proxy all traffic.

**Comment by sheena3** [comment]
I couldn't reproduce this issue. Closing this ticket.

**Comment by myleshorton** [comment]
Interesting @sheena3 thanks. Oddly gmail.com is not in the default proxied sites list. I believe it's a cname for mail.google.com, but nevertheless it should really be there.

That said, detour should also be able to detect it as blocked with the bad DNS server I believe right @fffw? Can you try to reproduce @fffw?

**Comment by fffw** [comment]
Sorry for the late response @sheena3 @myleshorton. I just tried. Resolving
any site to 127.0.0.1 will still get "connection refused" error, which is
not in blockage detection rule, so detour will not attempt to access it via
proxy. We can add this rule to avoid confusion. "connection
refused" rarely happens in reality and get such an error via proxy does no
harm I think.

**Comment by myleshorton** [comment]
Hey @fffw that makes a lot of sense. What does real world DNS poisoning actually do? Like what would gmail.com resolve to if anything? Can we make our own DNS server better simulate that?

**Comment by fffw** [comment]
Created a PR https://github.com/getlantern/lantern/pull/2655 to detect connection refused error. Once it's merged, @sheena3 's testing against gmail.com will work.
