### ISSUE TITLE
yamlconf: yamlconf.go:264 Custom polling failed: Unexpected response status: 522

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2640]
I got a single instance of this one in Loggly.  522 is "connection timed out".  This might have been @xiam testing beta6 with a VM tuned to simulate a very slow/unreliable network, but I'm logging it to keep an eye on it and to include the ticket in my support day report.

**Comment by atavism** [comment]
This appears to be showing up more often now (~118 times in the past two days)

**Comment by myleshorton** [comment]
I'm seeing this quite a lot in beta7 now too. I wonder if the config server had issues at one point @aranhoide?

**Comment by myleshorton** [comment]
Not seeing this anymore
