### ISSUE TITLE
"Bad response status for read: 502 Bad Gateway"

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2645]
We should have logged it earlier, as it not specific to beta 6. Lots of messages on beta 5 is like below:

>  flashlight.client: reverseproxy.go:186 http: proxy error: Dest: 10.10.34.34:80    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway

`10.10.34.34` is the IP address any blocked sites get resolved to in Iran. Need to investigate further to check if detour can fully detect DNS hijack.

It also occurs in https://github.com/getlantern/lantern/issues/2184

**Comment by oxtoacart** [comment]
I added logging to one server and see something interesting:

```
May 12 20:56:02.490 ERROR errorhandler: errorhandler.go:36 Responding with 502 due to read tcp <ip elided>:47834-><ip elided>:80: use of closed network connection: Error forwarding from <ip elided>:9831 to notify3.note.youdao.com
```

This seems to only happen with unencrypted HTTP connections, not HTTPS CONNECT connections.  I suspect that something somewhere isn't handling the Connection: Close header correctly.

**Comment by oxtoacart** [comment]
I'm hijacking this ticket for the 502 errors that @aranhoide noticed in checkfallbacks.  cc: @myleshorton

**Comment by oxtoacart** [comment]
We need to figure out why in some cases we're closing connections before we're done trying to read/write on them.

**Comment by oxtoacart** [comment]
If we're hitting the 30 second idle timeout, that could certainly cause this.

**Comment by oxtoacart** [comment]
Moving to http-proxy-lantern/issues#68
