### ISSUE TITLE
Add a "catch all" handler in case Lantern panics

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2648]
We can try to log the panic, and reset PAC setting if possible.

**Comment by myleshorton** [comment]
I like this idea @fffw. Feel free to tackle it if you like!

**Comment by uaalto** [comment]
I just saw this issue and decided to tackle it myself, because it may collide with the pending pull request where I added signal handlers. The changes I'm about to commit takes care of this and should play well with the code in the other branch.

**Comment by fffw** [comment]
Thanks @uaalto

**Comment by atavism** [comment]
Mentioned [panicwrap](https://github.com/mitchellh/panicwrap) in the related PR. Might be useful to integrate if we want to detect panics (without trying to recover from them) to forward the details to Loggly before crashing.

**Comment by uaalto** [comment]
Is panicwrap able to handle the panic() in all goroutines, so the panicked one is handled while the others run? I think we need this so the panicked one can still use the proxy run in other goroutines for logging to Loggly.

**Comment by atavism** [comment]
@uaalto Yeah, I modified the test program to confirm. Looks like it just watches stderr to capture any panic.

**Comment by fffw** [comment]
We can use panicwrap if logging is out-of-band, i.e., not depend on other
parts of Lantern. As Lantern rarely panics, I think we can mark this ticket
as lower priority.

**Comment by uaalto** [comment]
What I mentioned in the PR is that we might still be interested in the *PAC uninstall*. Even if we don't manage to solve the logging part, I think the PAC removal is worth doing. This might be the source of some issues experienced in IE/Windows.

**Comment by myleshorton** [comment]
I agree it's not super high priority @fffw but would be really nice to have. I agree on the PAC uninstall @uaalto too. It seems like it would be pretty easy to do the following:

1. Add panicwrap
1. Uninstall the PAC and log directly to loggly in our panicHandler

I'm reducing the priority to p2, but this is also marked for 2.0.3 regardless.

**Comment by uaalto** [comment]
I'll handle it! Thanks!

**Comment by myleshorton** [comment]
Sweet @uaalto thanks!
