### ISSUE TITLE
Encounter errors when build docker/windows/linux pakage for lantern 2.0.0.6 beta

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2654]
Hi,
I tried  "sudo usermod -aG docker gary"
but still show errors info when I run make docker(my OS is ubuntu 14.10 but not fedora or CentOS):

gary@gary-ThinkPad-X240:~$ cd lantern
gary@gary-ThinkPad-X240:~/lantern$ make docker
.....
.....
Step 9 : RUN yum -y update && yum clean all
---> Running in 0b1c49150456

One of the configured repositories failed (Fedora 21 - x86_64),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:

 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Disable the repository, so yum won't use it by default. Yum will then
    just ignore the repository until you permanently enable it again or use
    --enablerepo for temporary usage:

        yum-config-manager --disable fedora

 4. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=fedora.skip_if_unavailable=true
Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its path and try again
INFO[0050] The command [/bin/sh -c yum -y update && yum clean all] returned a non-zero code: 1 
Makefile:189: recipe for target 'docker' failed
make: *** [docker] Error 1

How shall I do next?

**Comment by fffw** [comment]
@yuan78 It's a yum related issue we didn't encounter, so we can't help much here. A quick [Google search](https://www.google.com/search?q=Cannot+retrieve+metalink+for+repository%3A+fedora%2F21%2Fx86_64&oq=Cannot+retrieve+metalink+for+repository%3A+fedora%2F21%2Fx86_64&aqs=chrome..69i57&sourceid=chrome&es_sm=119&ie=UTF-8) can give you some hints I think.

If your purpose is to use 2.0.0 beta 6, it is just released, see https://groups.google.com/forum/#!topic/lantern-devel/DTdgV_8lq3Q.

**Comment by yuan78** [comment]
Hi, but I use ubuntu， it shall not be with yum but shall be apt-get
install,that's the problem?

2015-06-18 10:45 GMT+08:00 fffw <notifications@github.com>:

**Comment by myleshorton** [comment]
I would completely delete all your docker images and start from complete scratch. It sounds like there's some sort of local corruption.

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```
