### ISSUE TITLE
How to configure Docker environment correctly when build lantern from source code 

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2657]
When I try to build lantern from source code , the most problems come from docker.

Obviously only install docker is far not enough, your need  configure it correctly to let make docker to work properly.  

How to setup Docker environment correctly when build lantern from source code? THX.

**Comment by aranhoide** [comment]
Installing docker is indeed enough.  You seem to have some problem downloading images.  Please use Google or docker-specific resources.
