### ISSUE TITLE
Unexpected response status: 409

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2658]
This is the top issue in Loggly for beta 6 as of this writing.

We've seen this caused by a beta6 client that has an old lantern.yaml around with a cloudconfig pointing to S3.  Lantern will try to use DDF to access that URL, which doesn't work for S3 URLs.

**Comment by myleshorton** [comment]
I'm going to close this one since those were all for my host, and we're not really seeing it outside of that.

**Comment by atavism** [comment]
@myleshorton, I think we're seeing a lot of occurrences for this beyond your host. It's still the top error in Loggly. For reference, the full message is ``yamlconf.go:264 Custom polling failed: Unexpected response status: 409``

**Comment by aranhoide** [comment]
I think the cause is likely to be the same one @myleshorton was experiencing: an old lantern config lying around and pointing to the wrong URL, and thus trying to access S3 through DDF.

I don't think we can do anything about this for beta6.  For beta7, I'd just ignore the `configurl` in `lantern.yaml`, and use the one provided in the command line or, if none, the hardcoded one.

**Comment by myleshorton** [comment]
This is another instance of where just using the remote config always would just solve it, as there would be no ambiguity between which URL to use. In this case that would also mean ignoring what's on disk completely unless it's the downloaded version, but then again I don't think we every really care about writing this to disk at all except for debugging. I'll have a look at @fffw's PR as soon as I'm freed up a little bit.

**Comment by myleshorton** [comment]
This is all set.
