### ISSUE TITLE
"lookup quotes.finance.21cn.com: no such host"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2659]
Seen at Loggly for beta6.  AFAICT that domain is not a masquerade.

**Comment by fffw** [comment]
From my experience, it happens mostly during when we are switching network, e.g., VPN is disconnecting. Any host name can not get resolved temporarily due to the incorrect route table (pointing to VPN, but it's disconnecting).

**Comment by xiam** [comment]
Not a problem anymore.
