### ISSUE TITLE
Beta 6 reports "balancer.go:75 No trusted dialers!"

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2667]
> {"extra":{"country":"CN","language":"zh","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"CST","version":"2.0.0-beta6 (20150619.163652)"},"fullMessage":"ERROR balancer: balancer.go:75 No trusted dialers!\n","hostname":"hidden","instanceid":"00fffdf682da","locationInfo":"ERROR balancer","message":"balancer.go:75 No trusted dialers!","timestamp":1435019020013}

**Comment by atavism** [comment]
Seeing a lot of this in Beta 7 too.

**Comment by myleshorton** [comment]
I think some of our recent changes should be able to fix this one.

**Comment by myleshorton** [comment]
This appears to be resolved in the latest beta 7.
