### ISSUE TITLE
Beta 6 reports "ConnectEx tcp: No connection could be made because the target machine actively refused it."

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2668]
> {"extra":{"country":"","language":"zh","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"CST","version":"2.0.0-beta6 (20150619.163652)"},"fullMessage":"ERROR fronted: masquerade.go:170 HTTP error for masquerade freebitco.in: Head http://www.google.com/humans.txt: Unable to dial proxy to www.google.com:80: Unable to dial proxy to www.google.com:80: Unable to dial masquerade freebitco.in: dial tcp 162.159.244.200:443: ConnectEx tcp: No connection could be made because the target machine actively refused it.\n","hostname":"hidden","instanceid":"c89cdcfd29ff","locationInfo":"ERROR fronted","message":"ConnectEx tcp: No connection could be made because the target machine actively refused it.","timestamp":1435023542274}

**Comment by myleshorton** [comment]
haven't seen this recently.
