### ISSUE TITLE
Flashlight doesn't exit cleanly when receiving SIGINT/TERM/HUP/KILL signals

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#2669]
The main visible consequence for the user is PAC left enabled:

![screen shot 2015-06-23 at 4 06 30 pm](https://cloud.githubusercontent.com/assets/12701448/8307924/de5a5e4c-19c1-11e5-8f20-1187e046b290.png)

**Comment by uaalto** [comment]
I can handle this as part of the Lantern Pi project, which exposed this bug since I required to register a function for execution at exit.

**Comment by myleshorton** [comment]
Yup this continually annoys me too! Will check out the fix.

**Comment by xiam** [comment]
This is causing problems in Windows and IE as well:

![screen shot 2015-07-22 at 10 40 18 am](https://cloud.githubusercontent.com/assets/385670/8829770/191e4af4-305e-11e5-8c20-0c35cab27032.png)

Chrome and Firefox still worked so I initially thought IE was failing, but it's Lantern which does not clean up before quitting.

I'm going to take a stab at this one on Windows.

**Comment by uaalto** [comment]
Does this happen when you force quitting Lantern? Normal exit should clean up PAC.

**Comment by myleshorton** [comment]
Closed via #2646

**Comment by xiam** [comment]
@uaalto This happens only when I force stop Lantern with ^C, which is not what a regular user would do. If I exit it from the systray menu, Lantern cleans up after itself without a problem and you still can use IE.

I tested again after the merge and this is still happening. Only with ^C.

**Comment by uaalto** [comment]
I see. Then it seems to be the same issue, but on Windows.

**Comment by xiam** [comment]
^C seems fine on OSX. Maybe this is something related to Cygwin.

**Comment by uaalto** [comment]
Does Cygwin have the `kill` utility?

**Comment by xiam** [comment]
Yeah, it does, @uaalto :

```
John@John-PC ~/projects/lantern
$ ps | grep fla
     3180    2924    3180       3184  pty1      197608 09:14:38 /home/John/projects/lantern/flashlight
John@John-PC ~/projects/lantern
$ kill -KILL 3180
```
![screen shot 2015-07-22 at 11 15 27 am](https://cloud.githubusercontent.com/assets/385670/8830667/120f909c-3063-11e5-97df-2899ef5233e9.png)

I also tried with SIGTERM:

![screen shot 2015-07-22 at 11 18 57 am](https://cloud.githubusercontent.com/assets/385670/8830742/8ca4e2b2-3063-11e5-8df9-4b8a8d390b29.png)

I'm working on it.

**Comment by xiam** [comment]
I think this is a problem with Cygwin, when testing with the Windows's cmd it behaves as expected:

![screen shot 2015-07-22 at 11 26 18 am](https://cloud.githubusercontent.com/assets/385670/8830910/85611dc6-3064-11e5-826b-00db7e821aaf.png)

So I guess this is not going to be problem for most users :-).

Just another thing, the https://golang.org/pkg/os/#Signal page says:

> The only signal values guaranteed to be present on all systems are Interrupt (send the process an interrupt) and Kill (force the process to exit).

Do you think it would be useful to add `os.Interrupt` and `os.Kill` to the list of signals?

```
signal.Notify(c,
     os.Interrupt,
     os.Kill,
)
```

**Comment by fffw** [comment]
From
https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx?f=255&MSPPError=-2147217396#code-snippet-2
> The SIGILL and SIGTERM signals are not generated under Windows. They are
included for ANSI compatibility.

**Comment by xiam** [comment]
Thanks @fffw! I'll try to help on that one.
