### ISSUE TITLE
Lantern's beta5 package thinks it is a beta6

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2671]
Looks like the beta5 package thinks it was a beta6 version. The build time is correct (around May) but the version isn't.

```
dpkg -i lantern-installer-2.0.0-beta5-64-bit.deb
(Reading database ... 125362 files and directories currently installed.)
Preparing to unpack lantern-installer-2.0.0-beta5-64-bit.deb ...
Unpacking lantern (2.0.0-beta6) over (2.0.0-beta6) ...
Setting up lantern (2.0.0-beta6) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1) ...
```

**Comment by myleshorton** [comment]
Interesting. Given that beta5 is no longer the released version, I'm not sure we should worry about it versus what beta6 itself does. Do you know if beta6 knows its correct version?

**Comment by xiam** [comment]
Yes I tested with both beta5 and beta6, beta6 knows its correct version. I wonder whether this was a parameter error that could have been prevented by the Makefile.

**Comment by myleshorton** [comment]
Yeah I'm guessing I passed the wrong TAG or something.
