### ISSUE TITLE
Balancer test failing

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2673]

**Comment by myleshorton** [comment]
This one is proving annoyingly elusive. After consistently getting the test to fail (in several different ways) on Valencia for awhile, I know haven't seen it fail in 80 consecutive attempts. Not sure if the state of the network is affecting it, but something sure is.

**Comment by fffw** [comment]
It fails again, see https://travis-ci.org/getlantern/lantern/builds/68287444

```
--- FAIL: TestAll-2 (1.25s)
	Location:	balancer_test.go:221
	Error:		Not equal: 6 (expected)
			        != 7 (actual)
	Messages:	Wrong number of check attempts on failed dialer
```

**Comment by myleshorton** [comment]
Thanks @fffw. I also fixed our travis badges on the front page README. I'll keep looking at this.
