### ISSUE TITLE
Docker 1.7 volume changes break makefile

### ISSUE THREAD

**Issue by dbshortt** [getlantern/lantern#2686]
Hello. It seems like the latest docker version (1.7) and its changes to the way docker handles volumes have broken the makefile.

Running make docker works fine, but the project fails to build at "make windows"

>make windows

>...

>Step 35 : WORKDIR $WORKDIR
 ---> Using cache
 ---> a463acf5fa0f
Successfully built a463acf5fa0f
Generating assets...
Error response from daemon: invalid mode for volumes-from: /lantern
Makefile:242: recipe for target 'genassets' failed
mingw32-make: *** [genassets] Error 1

Issue seems to be with the way the -v volume mounting flag is used to call the docker server:

>docker run -v $$PWD:/lantern -t $(DOCKER_IMAGE_TAG) /bin/bash -c 'cd /lantern && VERSION="'$$VERSION'" HEADLESS="'$$HEADLESS'" make docker-linux-amd64' && \

**Comment by uaalto** [comment]
I'm unable to reproduce it. I'm using Docker 1.7 on OSX. Step 35 is just the WORKDIR command , which doesn't specify any flags in the Dockerfile. It might be a configuration issue with your Docker installation.

**Comment by uaalto** [comment]
Upgrading to Docker 1.7 produced some weird errors. I got rid of them by just re-creating the images. At the moment make seems to work as we didn't get any report.
I will close for now, please reopen if the issue is still there.
