### ISSUE TITLE
Lantern UI traffic meter is always zero

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2687]
Latest code of valencia branch. I found it by chance after my Mac awoke from sleep mode.

Connection to `ws://127.0.0.1:16823/data` always in 'pending' state. `curl -v 127.0.0.1:16823/data` results `websocket: version != 13` error which is expected. Could be something related to the `onConnect` callback passed to `ui.NewChannel`.

**Comment by fffw** [comment]
Correction: The 'pending' state is pretty normal. What abnormal is that I didn't see any frames.

**Comment by uaalto** [comment]
We are not using this functionality any more, but the underlying problem probably remains. Should we close it?

**Comment by myleshorton** [comment]
Yeah the one place where it will crop back up is when we circle back to give mode for uncensored users, so let's keep it open for now. I'm also curious about the ```websocket: version != 13``` issue @fffw. Why are you saying that's expected?

**Comment by fffw** [comment]
@myleshorton Oh I mean `curl -v 127.0.0.1:16823/data` is expected to cause `websocket: version != 13` error. Let's keep it open.

**Comment by fffw** [comment]
No longer meaningful.
