### ISSUE TITLE
getlantern.org not loading on IE8 on Windows 7

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2693]
There are various certificate warnings, and the coinbase cookie is blocked. Not 100% sure why it's not loading, but it looks possible that Win7 doesn't include our CA.

**Comment by xiam** [comment]
I've just confirmed the error, trying to figure out what this "debugging message" means.

![screen shot 2015-07-08 at 11 16 24 am](https://cloud.githubusercontent.com/assets/385670/8576975/cec30c66-2562-11e5-9679-fca6f27e4812.png)

**Comment by fffw** [comment]
Maybe we can just skip this as the website will be replaced by new one in a
few days.

-- 
BR,
Merlin

**Comment by myleshorton** [comment]
Interesting thanks @xiam! Yeah it really depends on whether it's a cert error or the button error or both. If it's just the button, then we can probably skip it although theoretically we also want to include some way for people to donate with BitCoins on the new site as well. I *think* if you have visual studio installed you should be able to open up that error and get more info, but it's been awhile since I've been down that path.

**Comment by xiam** [comment]
Still broken, now it looks worse.

![screen shot 2015-07-21 at 5 11 42 pm](https://cloud.githubusercontent.com/assets/385670/8813780/a878741a-2fcb-11e5-8596-0ff4e9cd0d04.png)

**Comment by xiam** [comment]
I've found that the main reason of this failure is that IE 8 does not know how to handle SVG files.
 So we'll have to export everything to PNG and make IE 8 use them instead of trying with the SVG files.

**Comment by myleshorton** [comment]
Oh interesting thanks @xiam. I just double checked out our analytics on getlantern.org, though, and only 0.16% of our users is running on IE8 or below. So I think we can skip it for now! I know I opened this ticket -- I should have checked our numbers first.
