### ISSUE TITLE
IE8 not supported anymore

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2706]
I tested beta7 and it refuses to work on IE8/Win7. It asks the user to get another browser and it's unclear for the user how is he supposed to open Lantern again once she has Chrome installed.

![screen shot 2015-07-09 at 2 58 30 pm](https://cloud.githubusercontent.com/assets/385670/8607697/1ade7b0e-2652-11e5-8406-6ec0b4d370be.png)

**Comment by myleshorton** [comment]
Cool thanks @xiam. We actually haven't really ever supported IE8, but we
could start supporting it really easily with this new landing page.

**Comment by xiam** [comment]
I think it worths the effort! the UI has been simplified so I think it would not be that difficult.

**Comment by myleshorton** [comment]
Actually I forgot we can't actually support it because it doesn't include standards-compliant web sockets. We could always degrade, but currently IE 8 accounts for 0.5% of visitors to our site, so let's skip it unless we start hearing requests from a lot of users.
