### ISSUE TITLE
how to build binaries direclty from source code but not from git checkout tag

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2708]
Hi,
how to build binaries direclty from source code. 

What I mean is I don't want to use git clone&git check out tag to buid the binaries, because the git repo size will become bigger and bigger when the version continue upgrading, obviously it's a not good wise way to build the  the binaries.

How to build binaries direclty from source code? Such as I just only download the source code in tar.gz for 2.0.0.7 beta,  and then compile it into binaries, how can I do?

**Comment by atavism** [comment]
Hey @yuan78, the git repo would only increase in size if you actually pulled the latest changes. That said, you could clone a single branch instead of the entire repo using ``git clone -b valencia --single-branch git://github.com/getlantern/lantern.git`` (valencia is the branch Beta 7 is based on). Then just follow the instructions here: https://github.com/getlantern/lantern#building-lantern-binaries

**Comment by yuan78** [comment]
OK, thanks, But whether I still need to run git checkout for 2.0.0.0. beta7 or not?

**Comment by myleshorton** [comment]
If you want to build beta7 you would want to build from the beta7 tag, yes!

**Comment by aranhoide** [comment]
Try `--depth 1` too?

**Comment by yuan78** [comment]
Hi aranhoide, 
What you mean for "Try --depth 1", could you pls advise for the details of command operations ,THX!

**Comment by aranhoide** [comment]
Just add that to the command @atavism suggests, like so:

    git clone -b valencia --depth 1 --single-branch git://github.com/getlantern/lantern.git

**Comment by yuan78** [comment]
Hi aranhoide, 
Thanks ,  by add --depth it will bring what kind of effect? It will reduce the clone package size?

**Comment by aranhoide** [comment]
Yes.

**Comment by yuan78** [comment]
Hi aranhoide, Thanks , by add --depth it means only clone the latest tag, right? 
That means we can only git checkout only tag? Pls advise.THX
