### ISSUE TITLE
The Lantern link in the bottom of the page is not working

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2710]
In UI, the Lantern link at the bottom of the page is not working.  It is supposed to show the welcome screen with twitter and facebook pages for the users to follow.

As we already have the welcome screen now, are we still going to have this link? If not, then we should figure out a way to include the facebook and twitter logo which should be easy for the users to locate and follow.

**Comment by atavism** [comment]
I removed the link already in an unrelated PR. I opened a separate ticket to add the FB and Twitter share icons https://github.com/getlantern/lantern/issues/2729
