### ISSUE TITLE
Manoto fb page is opening each and every time Lantern is run in FF and chrome

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2712]
I suppose it should be opened only during the first run. Or is this the way it is supposed to work?

**Comment by sheena3** [comment]
This works fine now after the new changes. Closing!

**Comment by sheena3** [comment]
Reopening as this is still opening the manoto fb page each and every time lantern is open in FF. But moving this to P2 as this doesn't look like a major issue to me.

**Comment by atavism** [comment]
I think we want the Manoto page to open every time Lantern is run. We just don't want to show the Manoto page whenever you click "Show Lantern" -- is that right, @myleshorton?

**Comment by myleshorton** [comment]
Yeah I think that's the behavior we want yeah @atavism. We'll see if it annoys users.
