### ISSUE TITLE
If IE 11 is default browser, then opening Lantern using the desktop shortcut is not opening the browser

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2713]
Steps:

1. Make IE as default browser.
2. Now launch Lantern using the desktop icon.
3. It starts running as I can see it in the System Tray but it doesn't open the browser.

**Comment by sheena3** [comment]
This happens often but not every single time.

**Comment by myleshorton** [comment]
Lantern doesn't actually create a desktop shortcut by default. Are you maybe re-running the installer @sheena3?

**Comment by myleshorton** [comment]
I arguably think Lantern should create a desktop shortcut however.

**Comment by sheena3** [comment]
Oops, I am sorry. It is Start menu and not desktop shortcut.

**Comment by sheena3** [comment]
I don't think we need desktop shortcut. I am always using start menu. Do we have any request from the user about this? If not, then we could consider this as a Medium-term or Long-term milestone. 

If we have to do it, then I would suggest to give that as an option instead of making it default.

**Comment by uaalto** [comment]
Using Windows 8.1 and IE 11 here. These are my results:
* If IE *is not open*, running Lantern opens IE, *only with the Manoto Facebook page*.
* If IE *is open*, running Lantern opens *both* Lantern init page and the Manoto page.

**Comment by uaalto** [comment]
What do we **actuallly** want? Both pages always?

**Comment by atavism** [comment]
> What do we actuallly want? Both pages always?

Yes.

**Comment by uaalto** [comment]
I just tried https://github.com/getlantern/lantern/issues/2719 and seems to make it work. Could you please check that on your end, @sheena3?

**Comment by sheena3** [comment]
Yep @uaalto, it works. 

When there is a Lantern page already open and if I run it again from the start menu, it doesn't open a new page. It just opens the browser that is already open. This happens in all the browsers. I don't think it is a bug, just thought of letting you guys know.

**Comment by uaalto** [comment]
Good!
Yes, about that behaviour, I would say it's totally expected.
