### ISSUE TITLE
Chrome: Reduce the height of the footer in Lantern browser

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2720]
The footer is hiding a little of the links above them. It would be nice if the height is reduced.
![height of the footer](https://cloud.githubusercontent.com/assets/11394369/8639034/ff03bef8-28ea-11e5-952d-aaba41caec41.png)

**Comment by fffw** [comment]
In https://github.com/getlantern/lantern/pull/2718, we made the area above the footer vertically scrollable, so user can scroll down to view the full content if the browser window is not tall enough. It's an attempt to resolve this issue in another way.

**Comment by sheena3** [comment]
@fffw I am still seeing the same in my chrome browser without the scroll. Will this get updated in the latest version of beta 7?

**Comment by myleshorton** [comment]
This should be fixed now along with #2740. Should we close this @fffw and @atavism? We should have a build for you in a day or two @sheena3!

**Comment by atavism** [comment]
Yep I think we're good to close this.
