### ISSUE TITLE
Help users understand that they can access Lantern via the system tray

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2722]
This is what hola does:

![image](https://cloud.githubusercontent.com/assets/1143966/8639506/f89741c0-2890-11e5-9ded-fe8ba34609bd.png)

**Comment by myleshorton** [comment]
Here's a ticket for this specific aspect of UI updates @xiam.

**Comment by xiam** [comment]
Cool, I think that for windows we'll end up doing something like this if the OS does not support OSX-like notifications.

**Comment by oxtoacart** [comment]
@myleshorton @xiam What exactly is the goal here?

**Comment by xiam** [comment]
The goal is let users know that Lantern goes to the system tray at certain point and that you have to click it to bring it on again.

**Comment by oxtoacart** [comment]
Thanks @xiam, I've updated the title to reflect this.
