### ISSUE TITLE
Implement domain fronting with websockets

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2728]
See discussion at #2184. Note that not all CDNs will support it, but it would be very useful for those that do.

**Comment by uaalto** [comment]
I'm interested in taking a look at this now that I've been working with websockets. But @xiam was working on the related issue #2184 . What do you think, @xiam, @myleshorton ?

**Comment by xiam** [comment]
Actually I don't have any significant progress here, only did a few simple tests using github.com/gorilla/websocket. There is another library which also looked interesting but I didn't have a chance to check it out: https://godoc.org/golang.org/x/net/websocket

I'm rushed to finish my LEP this week, maybe you can start this one and I'll join you later.
