### ISSUE TITLE
Add share buttons to new UI page

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2729]
Twitter and FB, similar to what we had before on the welcome screen

**Comment by myleshorton** [comment]
I think this would be really useful @atavism and could improve growth quite a bit. Let's try to get this ready for when the ads get pushed out, as I think the ship has likely sailed on beta 8. That sound right @atavism? We can get @Derekf5 involved too.

**Comment by atavism** [comment]
@myleshorton I agree. It's not a major change so if we wanted to quickly add them this weekend before the show that's certainly doable. Basically, just the FB and Twitter icons next to the Lantern text in the footer, right? Might want to involve @Derekf5 for how it should look exactly though.

**Comment by Derekf5** [comment]
@myleshorton @atavism I can have a design of this over to you at some point tomorrow, hopefully early.
It will probably be best to keep it consistent with buttons on the site, do you all agree?

**Comment by atavism** [comment]
@Derekf5 Yes, that sounds good to me!

**Comment by Derekf5** [comment]
Here are screenshots of the design file, if you guys like them then ill send over the graphic resources.
@atavism do i need to design a popup window for this as well?

<img width="456" alt="screen shot 2015-07-18 at 2 39 52 pm" src="https://cloud.githubusercontent.com/assets/7864729/8763134/62632710-2d5d-11e5-818e-54b12cb09462.png">
<img width="458" alt="screen shot 2015-07-18 at 2 40 04 pm" src="https://cloud.githubusercontent.com/assets/7864729/8763135/6268ace4-2d5d-11e5-8c10-8fb1a15b71e8.png">

**Comment by myleshorton** [comment]
Nice! Is one of them on mouseover or are these alternatives? I like the
darker one.

**Comment by Derekf5** [comment]
@myleshorton they are alternative versions.  The dark color is so that it matches the footer of the new website.  I like that version better as well.  I will send over those icons now.

**Comment by atavism** [comment]
Darker version looks great.

**Comment by atavism** [comment]
@myleshorton PR is ready for this here: https://github.com/getlantern/lantern/pull/2764
