### ISSUE TITLE
Make sure old config files on disk aren't able to give bad config URLs

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2731]

**Comment by myleshorton** [comment]
Use the hard-coded URL unless it's overridden from the command line.

**Comment by aranhoide** [comment]
I'll do this unless someone else wants it.  Should be a quick one.

**Comment by myleshorton** [comment]
Hey I'm actually looking at this now @aranhoide and am considering making it a super small but I think effective change -- just changing the name of the lantern.yaml file to include the version number. That will basically ignore all old versions, which I think is what we want. What do you think? I'll create a branch, and we can discuss there.
