### ISSUE TITLE
regression: UI doesn't reflect that Lantern has quitted

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#2736]
Prior to the UI changes, the UI displayed that Lantern wasn't proxying (even if not very clear about it, but at least displayed that it was 'trying to connect'). I think this might be confusing for users.

**Comment by myleshorton** [comment]
Agreed @uaalto. It would be fairly easy for use to display something directly in the browser again reflecting that we've lost contact with Lantern.

**Comment by uaalto** [comment]
After experimenting with Lantern in different OSes and testing it from different angles, I also think it should display that "Lantern network is experiencing some issues, please wait a few seconds and try again" if things like chained proxies are lost and it has to resort to fronted. Since the time it takes is about 1 minute, that's more than enough to loose an user.

In my opinion, these two are important messages to communicate to the user.

**Comment by atavism** [comment]
It should be really easy to just enable what we had before actually (I
think it was just commented out!). I'll create a ticket for that.
