### ISSUE TITLE
Lantern doesn't consider fronted servers trusted by default

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2737]

**Comment by aranhoide** [comment]
I think we made it like this on purpose.  Why do you want it the other way?

**Comment by myleshorton** [comment]
The config returned from https://config.getiantem.org/cloud.yaml.gz considers them trusted. If we consider them untrusted, then we can't hit any http sites if chained proxies get blocked.

**Comment by aranhoide** [comment]
Ah, you meant the default fronted server should be trusted.  I agree.

I had interpreted this as meaning that if a fronted server didn't contain a trusted field we should default to assuming true.

**Comment by myleshorton** [comment]
Yes exactly @aranhoide!
