### ISSUE TITLE
[ui]IE and Firefox can't show sites completely on small window

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2740]
From top to bottom: Chrome, IE and Firefox. Scrolled to bottom. IE and Firefox still can't show completely. The impact is relatively small though.

![image](https://cloud.githubusercontent.com/assets/10410437/8710808/2c8bc866-2b7f-11e5-91a7-9ee1ce27ea8f.png)

**Comment by myleshorton** [comment]
I think this is worth fixing along with the screen resolution issue.

**Comment by myleshorton** [comment]
This one's all set @atavism right?

**Comment by myleshorton** [comment]
I think this is really an issue of the div the scrollbar is assigned to, as mentioned in #2800.

**Comment by atavism** [comment]
@myleshorton I think we can just fix the footer at the bottom and set the overflow to hidden without having to assign the scrollbar to another div. Do you want to check if https://github.com/getlantern/lantern/pull/2816 fixes it?
