### ISSUE TITLE
Enable auto-detect on Windows

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2746]
![image](https://cloud.githubusercontent.com/assets/10410437/8718216/2ade7df0-2bd5-11e5-9308-0f231c8aec7d.png)

When PAC URL can't be reached, IE can detect it and try to open a page directly. It is helpful for at least 2 situation.

1. https://github.com/getlantern/lantern/issues/2741 when IE have problem accessing PAC URL after system startup.

2. Lantern crashes or be killed during system shutdown, leaves the PAC URL there.

**Comment by myleshorton** [comment]
I think this sounds like a good idea @fffw. I'm actually not sure how to do it, but I guess we could programmatically use INTERNET_PER_CONN_AUTODISCOVERY_FLAG?

I also wonder if we're checking for errors well in our proxy code. Is it possible we're encountering some error but not recording it?

**Comment by fffw** [comment]
The option is PROXY_TYPE_AUTO_DETECT. I incorrectly built 64bit version
pac-cmd.exe yesterday, now the 32bit binary works as expected.

But it didn't resolve the problem! I still can't open any page with Lantern
running on startup.

My previous understanding of this option is wrong. From
http://blogs.msdn.com/b/ieinternals/archive/2013/10/11/web-proxy-configuration-and-ie11-changes.aspx

The settings in this dialog box are presented in the order of their
precedence. First, the *Automatically detect settings *option is consulted,
next the *automatic configuration script *option is evaluated.

It's still a myth why IE can't open anything while Chrome can. I'm trying
to let IE print some event log.

**Comment by myleshorton** [comment]
Yeah it's very odd. It does appear for me only sometimes, though, which definitely points to some sort of race condition. I was wondering if it could be a matter of opening the browser window so close to setting the pac file. As a test, I wonder if just opening the browser 5 seconds or whatever after setting the PAC URL would solve it. That would at least give us a clue, and possibly ultimately a solution, although 5 seconds is probably more than we would like.

As a variation on the above, we could also try setting the PAC 5 seconds *after* opening the browser. I have a feeling one of those could work.

**Comment by fffw** [comment]
I tried waiting 5 seconds before turning on PAC url and opening ui, no
luck. Will try more combination including your recommendation.

On Fri, Jul 17, 2015 at 11:41 AM, myleshorton <notifications@github.com>
wrote:

> Yeah it's very odd. It does appear for me only sometimes, though, which
> definitely points to some sort of race condition. I was wondering if it
> could be a matter of opening the browser window so close to setting the pac
> file. As a test, I wonder if just opening the browser 5 seconds or whatever
> after setting the PAC URL would solve it. That would at least give us a
> clue, and possibly ultimately a solution, although 5 seconds is probably
> more than we would like.
>
> As a variation on the above, we could also try setting the PAC 5 seconds
> *after* opening the browser. I have a feeling one of those could work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2746#issuecomment-122160629>
> .
>



-- 
BR,
Merlin

**Comment by myleshorton** [comment]
Does it make sense to close this in favor of the other IE tickets @fffw?

**Comment by fffw** [comment]
Yes it's totally irrelevant. Closing
