### ISSUE TITLE
Add analytics to email auto-responder

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2749]

**Comment by myleshorton** [comment]
This should be all set and linked up to GA, but I'm still waiting for data to show up...

**Comment by uaalto** [comment]
Where is the code for this?

**Comment by myleshorton** [comment]
It's just a GA tracking pixel in the canned response for manoto@getlantern.org, so it's in that response itself. You can see it if you look at the raw email body returned from manoto@getlantern.org, although I'm still not sure it's actually working.

**Comment by uaalto** [comment]
Sorry, I removed instead of editing the comment. I meant to say that I ran a search for GA-related code in mail-responder, but didn't find anything.

**Comment by myleshorton** [comment]
> Sorry, I removed instead of editing the comment. I meant to say that I ran a search for GA-related code in mail-responder, but didn't find it.

Gotcha -- yeah it doesn't exist.

**Comment by myleshorton** [comment]
Although theoretically we could add it...

**Comment by uaalto** [comment]
But actually the email brings an image with it, which probably is that one. It is not in the template.{html,txt} files, so I wonder where is it added.

**Comment by uaalto** [comment]
Probably @fffw knows about this.

**Comment by myleshorton** [comment]
> But actually the email brings an image with it, which probably is that one. It is not in the template.{html,txt} files, so I wonder where is it added.

Yeah that's what I'm saying -- it's added in the canned response directly in gmail in the manoto@getlantern.org account -- i.e. we're not using anything in the auto-responder code right now.

**Comment by myleshorton** [comment]
This is all set, with emails being recorded in the Manoto Autoresponder account in analytics.

**Comment by uaalto** [comment]
Ok, I see. Well, much easier to maintain.
