### ISSUE TITLE
Different platforms getting different minor version numbers during builds

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2753]
I just released an updated beta 7 version, but I realized just now different platforms build with different version numbers:

Windows: Lantern 2.0.0-beta7 (20150715.044244) 
OSX: Lantern 2.0.0-beta7 (20150716.215058) 

That's a pretty big issue for loggly, as they'll be grouped separately. Any thoughts on that one @xiam?

**Comment by xiam** [comment]
The last number (20150715.044244) is the build date and it's generated when the make job is invoked. What do you think about not sending it to loggly as part of the version? We could send it in a separate field, like `buildDate`.

**Comment by xiam** [comment]
I think it could be possible to check what was the date of the latest commit at the time of the build and use that date (in YYYYMMDDHHIISS format) regardless of which time the build was created.

Also, I think having the actual build date in a new `buildDate` field would be useful too.

What do you think @myleshorton?
