### ISSUE TITLE
When UI opens it is too large on small screens

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#2762]
Users should not have so scroll at all when presented with the UI landing page.  When I scale down to 80-90% it looks much better.  Attached is a screenshot of how it currently appears on my 13" Laptop retina display screen. 2560x1600
<img width="1267" alt="screen shot 2015-07-18 at 11 17 12 am" src="https://cloud.githubusercontent.com/assets/7864729/8762157/c109dba2-2d3e-11e5-8586-346b2cf52c00.png">

**Comment by myleshorton** [comment]
Looking at sample analytics data, the most common screen resolutions are generally on the lower side, so this seems important:

![image](https://cloud.githubusercontent.com/assets/1143966/8786578/d139a128-2ee3-11e5-8734-aab7c7d37fa0.png)

**Comment by myleshorton** [comment]
I think this one's all set right @atavism?

**Comment by atavism** [comment]
Yep, let's close this one!
