### ISSUE TITLE
Does lantern has a built in auto update feature?

### ISSUE THREAD

**Issue by OnionSalt** [getlantern/lantern#2767]
I am sure I didnt download the release beta8 version, but somehow lantern update itself to release beta8 a few hours ago. Anyone else encounter this??
Trying to make sure its not a virus infection or been hacked, any hint will be appreciated.
Thx

**Comment by fffw** [comment]
Yes, Lantern added auto-update feature. The main purpose is to continually
improve overall performance and block resistance without user intervention.

A runtime notice would avoid the confusion, but yet to be added.

**Comment by OnionSalt** [comment]
Thx for the answer :)
