### ISSUE TITLE
Windows logging doesn't use the proper EOL characters, appearing formatted in a single line.

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#2768]
This appears visible when opening logs with Notepad or any other simple Windows utility. Simple conversion to Windows formatting solves it, but at the cost of an extra step when dealing with Windows debugging.

**Comment by myleshorton** [comment]
I actually vote for closing this, as the logs appear fine in tools that any actual windows developer would typically be using to look at them, like Notepad++ or vim via Cygwin. Notepad++ is pretty handy for windows development in general.

Feel free to re-open if you feel strongly @uaalto!

**Comment by uaalto** [comment]
I ended up opening it with the browser (FF), which works well. Anyway most development happens in the host environment while using VMs.

**Comment by myleshorton** [comment]
Sounds good. Dude you know what, we should totally be using something like [vagrant](https://www.vagrantup.com/) to avoid the insane hassle of resetting up development environments especially on Windows!

**Comment by uaalto** [comment]
Definitely. Especially since the user base is on Windows and we have (reasonable) allergy to that OS. I think @xiam is using Vagrant for his own set up. I tried myself but ended up using Microsoft's testing images that have been working well for me. But unifying and automating this is a step forward. It is also related to the automated visual testing that we discussed. 

One thing to think about would be the approach regarding the development/release environments. Currently, we use mingw set up in an Ubuntu docker container that cross-compiles to windows. This set up is superconfortable for normal development and releasing (it allows complete automation, to begin with). I do that and then serve the binary in a webserver that allows me to grab it instantly from the Windows VM. But if we plan on compiling *within* a Windows instance, for testing and Windows-relatd bug hunting the story changes. We will then have to maintain two environments (__docker-powered__ which doesn't require setting up windows and __vagrant-powered__, which requires Windows running on a VM). I think we have to find the sweet spot, and see if we can avoid maintaining two parallel _environment automation_ scripts.

**Comment by fffw** [comment]
A side note about obtaining binary within VM. I added a shared folder in
VirtualBox and created a desktop shortcut to
\\VBOXSVR\vagrant\getlantern\lantern\lantern_windows_386.exe in Guest OS,
click to run.

**Comment by myleshorton** [comment]
For compiling within Windows what's wrong with good old ```go build```? That's what I use.

**Comment by uaalto** [comment]
Does `go build` perform also the lantern-ui and the most relevant tasks as if done with Make?

**Comment by uaalto** [comment]
Oh, @fffw that's definitely better than my way :dart: 
I'm always having issues with the shared folders though, but you save precious seconds that way. Thanks!

**Comment by myleshorton** [comment]
To me I would consider the make approach as primarily there for cross-compilation with docker and whatnot -- i.e. primarily for releases. To me in general during normal development we should just be using the standard go tooling. Lantern will just grab the lantern UI from app instead of dist in dev mode.

**Comment by uaalto** [comment]
In that case Vagrant makes more sense, IMO.
