### ISSUE TITLE
"GetAddrInfoW: The requested name is valid, but no data of the requested type was found."

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2770]
According to @fffw:

> Should not be an Lantern related issue, see https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx#WSANO_DATA

So feel free to close this if you agree.  I log it anyway so we know to refer to this report whenever we see this error in the field.

**Comment by oxtoacart** [comment]
No occurrences in 2.1.2, closing.
