### ISSUE TITLE
[ui] Layout messed up on IE 10

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2782]
![image](https://cloud.githubusercontent.com/assets/10410437/8801141/e7d6b0da-2fea-11e5-8392-68e3617a0a4e.png)

1. Logo is too large, pushes text down.
2. Share button too large.
3. Share text misplaced.

**Comment by myleshorton** [comment]
Wow crazy. We should fix that =). I think we should presize all of these graphics to their actual size for the most part and avoid resizing in the UI.
