### ISSUE TITLE
Lantern slow for many users

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2784]

**Comment by myleshorton** [comment]
Seems like there a few potential causes of this:

1. The user's Internet connection is slow, and Lantern gets blamed
1. The user's on a slow machine, and Lantern's having performance problems
1. Our servers get overloaded at peak times
1. More...

So far we've seen little evidence of #3

**Comment by uaalto** [comment]
I think the approach to take in this case is to provide better diagnosis. We could tackle different scenarios with different tools:

1. Slow internet --> internet speed detection (would require using a third-party service, like speedtest).
2. Slow machine --> measure machine load (would require OS-dependent access to this info -- like /proc for Linux)
3. We have server load detection in place, the only problem is matching this load with user's experience at a specific time. However, I think this could be tested locally with comparisons to requests to other (unblocked) sites through the proxy and without proxying.
4. For other "general type" causes like the ones above, I think we can invest in better diagnosing in general, as a way to improve the user experience in general.

None of these is trivial but they may be an improvement in the user experience direction. If we do have more specific information we could go down one route in particular.

**Comment by myleshorton** [comment]
Closing again -- seems to be working well for the vast majority of users.

**Comment by myleshorton** [comment]
I meant to say I agree on all those @uaalto, although I don't think it's quite at the top of the list at this point.

**Comment by uaalto** [comment]
No problemo!! If we come back to it we'll give it a second pass. You know I'm keen on diagnosis tools =)
