### ISSUE TITLE
Easy way for users to gather logs

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2785]
This was originally suggested by @atavism, I'm opening the issue for discussion. I think we have some options:
1. Add a "View logs" menu that will open a text editor showing the logs.
2. Create a .zip file with the logs in the desktop for the user to send.
3. Mail them directly to us with a button.

I like 2, because it's really easy to implement and it does not depend on any text editor, the only thing we need to know is the path of the Desktop directory in Windows/OSX.

Thoughts?

**Comment by atavism** [comment]
@xiam Thanks for opening this ticket! I know before we provided a feedback form (just a simple text area, no fancy editor) a user could click on to send us a message. I think we could restore that and automatically attach the user's logs. They could even leave the message blank, and we'd get e-mailed a copy of the logs with a simple click of the button. Along those lines, #3 appeals to me.

**Comment by myleshorton** [comment]
Yeah I would tend to agree @atavism. If we invest time in this, we might as well invest the time to make it truly dead simple and eliminate almost all the required steps.

**Comment by fffw** [comment]
Sina just mentioned this feature when comparing same feature provided by Psiphon. We need to add it to both desktop and mobile.

**Comment by fffw** [comment]
One possible 3rd issue reporting tool https://www.uservoice.com/, suggested by Sina.

**Comment by fffw** [comment]
Consider those user comments on FB and Twitter just saying that Lantern stops working, it's probably good to rise it to P1 so user will have a more direct way to report issue with all things we required.

**Comment by p3rcya** [comment]
I'm proposing a much more user friendly alternative here 
https://github.com/getlantern/lantern/issues/4869 desktop
https://github.com/getlantern/lantern/issues/4870 mobile

If you agree, please close this issue.
