### ISSUE TITLE
Lantern opens automatically after restart even when "Run Lantern automatically on Startup" is disabled - Windows 8.1, chrome

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2791]
I tried two different scenarios. One with Lantern running while restarting and the other is after quitting Lantern. 

In both these scenarios, Lantern started automatically after restart.

**Comment by atavism** [comment]
Thanks, @sheena3. Which OS is this happening on?

**Comment by sheena3** [comment]
This is in Windows 8.1. I haven't checked in my Mac and Linux systems.

**Comment by xiam** [comment]
Interesting, this does not happen to me on Windows, in fact that's the main reason of #2776.

**Comment by sheena3** [comment]
@xiam I forgot to mention the browser. I saw this when the default browser is chrome. I will check with other browsers now.

**Comment by sheena3** [comment]
More on this issue...

@xiam I tested all the browsers and all behaves in the same manner. 

And one more thing that I noticed is, fb manoto tv page is not opening while restarting (I made sure that the "Run Lantern automatically on system startup" is disabled). Could this be because of that?

FYI - I downloaded the beta 8 version from getlantern.org and tested this.

**Comment by myleshorton** [comment]
Thanks @sheena3! The Lantern version on the web site doesn't open Manoto.

**Comment by myleshorton** [comment]
I've got this one guys -- our code for deleting the registry key is just wrong.

**Comment by myleshorton** [comment]
This should be all set @sheena3 but please test when this goes to QA.

**Comment by sheena3** [comment]
This doesn't work as expected.

Lantern is still starting automatically after restarting. I have disabled 'Run automatically on system startup' option.

**Comment by myleshorton** [comment]
I think this is because you have old settings in your windows registry, @sheena3. I'll make a change to the installer that just deletes the old value. Thanks!

**Comment by sheena3** [comment]
Should I download an updated version to retest?

**Comment by sheena3** [comment]
@myleshorton Tried with the new Lantern. Still not working in windows but works in Mac.

**Comment by myleshorton** [comment]
Only the one I emailed about last week -- should say in the bottom:

```Lantern 2.0.0 (20150729.035956)```

**Comment by sheena3** [comment]
Yeah - that is the version I used to retest this issue and reopened.

**Comment by myleshorton** [comment]
Oh I think I just realized what's happening -- that version doesn't include a fix I added to overwrite old Lantern settings. Next one should fix it.

**Comment by sheena3** [comment]
Do we have a new version now that I can use for retesting?

**Comment by myleshorton** [comment]
Not yet. You could always test that last FireTweet build though if you're all set with Lantern. We should have a new version by the end of the day today.

**Comment by sheena3** [comment]
I tested this in Chrome browser in Windows 8.1. Lantern is running automatically on restart even when the option is disabled.

**Comment by xiam** [comment]
Hello @sheena3,

Could you try running the Start menu then typing regedit in the command input and look for the keys within the path `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`?

![screen shot 2015-08-06 at 12 56 31 pm](https://cloud.githubusercontent.com/assets/385670/9119121/9d6d1000-3c3a-11e5-8f48-2a86dd2056f0.png)

There should be only one key named Lantern, hows does that entry look to you?

**Comment by sheena3** [comment]
Yeah @myleshorton , there is only one entry. Attached the screenshot.

Should I try this after restarting with the option disabled?
![image](https://cloud.githubusercontent.com/assets/11394369/9119588/04d7c24e-3c95-11e5-8be7-387ffb1cdae9.png)

**Comment by myleshorton** [comment]
Yeah this is the same issue as #2802 really. Fix coming shortly.

**Comment by sheena3** [comment]
This works fine in windows. Tested in chrome, IE and Firefox. I will complete testing in Mac and Linux and then close this issue.

**Comment by sheena3** [comment]
Works as expected. Closing now.
