### ISSUE TITLE
Build FireFox extension for making sure proxy settings are correct when running Lantern

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2792]

**Comment by atavism** [comment]
BTW, we have this as a basis https://github.com/getlantern/firefox-extension that I created awhile back

**Comment by myleshorton** [comment]
Cool thanks @atavism. We also had an extension in Lantern 1.5.17 that did exactly this task, so I'm working on adapting it at https://github.com/getlantern/lantern-firefox-extension
