### ISSUE TITLE
Auto updates are not actually working

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2793]
I was expecting beta5 to update to beta8:

```
Jul 22 19:13:48.217 - autoupdate: autoupdate.go:97 Patching failed: "Updated file has wrong checksum. Expected: 472a3f73e7d66c80737c4eceefc693d5775d046b9b61b22bf02a892ae5d9ebb4, got: ec7bf6f3954442c6ce4ac65a38f09fea1f84985461713e48f5915d6d01740bdc"
```

**Comment by xiam** [comment]
@myleshorton 

Our published [beta5 dmg](https://s3.amazonaws.com/lantern/lantern-installer-2.0.0-beta5.dmg) has a lantern binary with this signature:

```
macbook-air-2:/Applications/Lantern.app/Contents/MacOS > gsha256sum lantern
d1d61cd6c69d601e6d53a78275575683a14ff5586ac6e78e4c456a7722094c9f  lantern
```

However, the expected signature is the same one as the [autoupdate binary](https://github.com/getlantern/lantern/releases/download/2.0.0-beta5/update_darwin_amd64.bz2) for beta5.

When I run this auto update binary directly it reports it's version correctly:

```
Jul 22 19:20:47.744 - flashlight: flashlight.go:163 ---- flashlight version: 2.0.0-beta5, release: 2.0.0-beta5, build date: 20150424.174603 ----
```

And after a few seconds it gets the update:

```
Jul 22 19:21:10.758 - autoupdate: autoupdate.go:89 Patching succeeded!
Jul 22 19:21:10.758 - flashlight.autoupdate: autoupdate.go:111 Got update.
```
 
But the beta5 that was installed from the dmg is different, besides the weird checksum it also thinks it is beta6:

```
Jul 22 19:28:29.644 - flashlight: flashlight.go:163 ---- flashlight version: 2.0.0-beta6, release: 2.0.0-beta6, build date: 20150512.174212 ----
```

And note that the two releases report a different build date, one month apart.

I think that the original beta5 was overwritten by this beta6. Chances are the confusion was produced because we have `TAG` and `VERSION` variables, maybe the current beta6 was built with a `2.0.0-beta6` `VERSION` and released under a `2.0.0-beta5` `TAG`. 

Would anyone mind if I just remove the `TAG` variable to avoid things like that happening in the future?

**Comment by myleshorton** [comment]
Yeah I saw that published beta 5 up there, and I actually have no idea how it got there. I think it might make sense to just remove it, and I also agree getting rid of TAG in favor of VERSION makes sense.

Is there any reason why current beta 6 users would not get updated to beta 8 now?

**Comment by myleshorton** [comment]
We also have seem at least some users automatically upgrading without any issue on the mailing list, so it at least appears to be working sometimes @xiam.

**Comment by xiam** [comment]
> Is there any reason why current beta 6 users would not get updated to beta 8 now?

Yeah, the reason is that we don't have a 2.0.0-beta6 release here: https://github.com/getlantern/lantern/releases, so the update server is not able to compute a binary diff between that one and the latest beta. Maybe we can just force a full binary download when the binary patch is not possible for some reason, any concerns on that? My biggest concern would be that QA versions would get updated for apparently no reason, even though they weren't ever officially released, but that would not affect real users actually, so maybe it isn't that bad. Developers who build Lantern by themselves might be affected too, but that's an hypothetical corner case and I'm sure they'll figure a way to turn off auto updates if they want.

An option to fix lantern installations that can't upgrade themselves would be adding each missing release manually by downloading each installer, grabbing the published lantern binary and uploading it to the release page, that would require some time.

> We also have seem at least some users automatically upgrading without any issue on the mailing list

I bet some beta5 users updated automatically as expected, they must have had downloaded beta5 before it got overwritten by beta6.

**Comment by myleshorton** [comment]
Makes sense @xiam thanks! I think it's OK to just fix this moving forward (i.e. beta 8 on) and not worry about old versions.

I think we're in a pretty unique situation right now in that most users on beta versions. I think it might actually be correct and what we want to only publish binary updates on release/stable versions, which I think would actually just work correctly going forward right? For example, I think 2.0.1 will likely be released as a stable version, and beta 8 users will get automatically updated to that no problem right?

So I'm wondering if maybe we're OK. What do you think?

**Comment by xiam** [comment]
Yeah, maybe we are OK and in absolute control of the autoupdates, we just need to take care of releases.

Either 2.0.1 or 2.0.0 will work, as 2.0.0 > 2.0.0-beta8 (this comparison is provided by [semver](https://github.com/blang/semver))

**Comment by xiam** [comment]
Closing this one as we already found the reason. Opening this issue https://github.com/getlantern/lantern/issues/2795 to keep track of the proposed preemptive fix.
