### ISSUE TITLE
Add more logs for debugging connection issues

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2798]

**Comment by uaalto** [comment]
Do you mean flashlight-wide? 
I can take over a project for making `errcheck` pass on all of our code (src/github.com/getlantern/...)

**Comment by myleshorton** [comment]
We just could have used more logs in that last round of debugging in a few key areas to make it easier to figure out what was going on. An ```errcheck``` pass separately would be awesome though.

**Comment by uaalto** [comment]
I can work on the errcheck part. Should I open a separate ticket for that?
For the other part, in order to tackle the deeper logging we would need to identify those areas. Do you have them in mind? Also, as I understand it, you mean extra logging for initializing/finalizing procedures.

**Comment by myleshorton** [comment]
I can take the logging part itself since there are a few specific parts, but if you want to create a ticket for the errcheck part that would be great @uaalto!

**Comment by uaalto** [comment]
Done.

**Comment by uaalto** [comment]
I've also added one for golint, I'll do that as well :)

**Comment by myleshorton** [comment]
Awesome on the golint front @uaalto!
