### ISSUE TITLE
Don't open web browser on automatic startup

### ISSUE THREAD

**Issue by Gigglelife** [getlantern/lantern#2802]

**Comment by fffw** [comment]
Lantern doesn't have "Don't open web browser" option anywhere. Could you take a screenshot?

**Comment by aranhoide** [comment]
@fffw: I think this is a feature request.

**Comment by myleshorton** [comment]
Actually that's the way it's supposed to work regardless -- we'll implement it @Gigglelife thanks.

**Comment by sheena3** [comment]
This is working fine in Mac. In windows 8.1, browser is still opening

**Comment by myleshorton** [comment]
Thanks @sheena3. You don't have it set to open on startup in settings correct?

**Comment by sheena3** [comment]
I did set it to open automatically on system startup.

**Comment by myleshorton** [comment]
OK of course that makes sense -- checking now thanks!

**Comment by myleshorton** [comment]
I can't reproduce this @sheena3. Are you sure you're using the latest installer that added this functionality?

**Comment by sheena3** [comment]
Does this need latest installer? I used the installer that you sent me as
an update. Should I download it again to test this?

On Tue, Aug 4, 2015 at 12:24 AM, myleshorton <notifications@github.com>
wrote:

> I can't reproduce this @sheena3 <https://github.com/sheena3>. Are you
> sure you're using the latest installer that added this functionality?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2802#issuecomment-127369444>
> .
>



-- 
Regards,
Sunshine

**Comment by sheena3** [comment]
I installed Lantern using the installer that I downloaded now. It is not working. Browser is opening with Lantern running irrespective of the settings.

**Comment by sheena3** [comment]
I tested this in Chrome browser in Windows 8.1. It is still opening the browser when running Lantern automatically on restart.

**Comment by myleshorton** [comment]
OK I think I see the problem -- I'm on it.

**Comment by sheena3** [comment]
This works fine in windows. Tested in chrome, IE and Firefox. I will complete testing in Mac and Linux and then close this issue.

**Comment by sheena3** [comment]
works fine. Closing
