### ISSUE TITLE
TestMulticastMessages failing

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2810]
```
=== RUN TestMulticastMessages
2015/07/24 15:05:43 {"Type":2,"Payload":""}
2015/07/24 15:05:43 {2 }
--- FAIL: TestMulticastMessages (0.01s)
	multicast_test.go:124: Multicast Hello message is incorrectly formatted
=== RUN TestMulticastAnnouncing
--- PASS: TestMulticastAnnouncing (1.10s)
FAIL
coverage: 64.2% of statements
exit status 1
FAIL	github.com/getlantern/multicast	3.335s
make: *** [test-and-cover] Error 1
```

I think this was mentioned already in https://github.com/getlantern/lantern/pull/2646, but I'm consistently seeing this test fail.

**Comment by myleshorton** [comment]
Thanks @atavism. It's failing locally for you, is that correct?

**Comment by atavism** [comment]
@myleshorton Yes.

**Comment by uaalto** [comment]
Very strange. I have to figure out how to reproduce it, because the tests pass in my machine and the code should be ok (obviously isn't, though!).

**Comment by uaalto** [comment]
I've just realized: tests pass in Travis.
Are your tests failing always or sometimes (this could be a hint towards concurrency issues, although I doubt it!).

**Comment by atavism** [comment]
That test is just always failing for me locally.

**Comment by uaalto** [comment]
Hey @atavism, can you test this code to see if it runs smoothly?
Thanks!

**Comment by atavism** [comment]
Yep, that passes for me now!

**Comment by uaalto** [comment]
Finally it makes sense :)
