### ISSUE TITLE
\Users\[redacted]\AppData\Roaming\Lantern\lantern-2.0.0-beta8.yaml: The system cannot find the file spec

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2811]
Found 4 different users with the same problem:

```
{"extra":{"country":"IR","language":"en","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"PDT","version":"2.0.0-beta8 (20150719.133131)"},"fullMessage":"ERROR yamlconf: yamlconf.go:214 Unable to read updated config from disk: Unable to stat config file C:\\Users\\[redacted]\\AppData\\Roaming\\Lantern\\lantern-2.0.0-beta8.yaml: GetFileAttributesEx C:\\Users\\[redacted]\\AppData\\Roaming\\Lantern\\lantern-2.0.0-beta8.yaml: The system cannot find the file specified.\n","hostname":"hidden","instanceid":"0071cc95c618","locationInfo":"ERROR yamlconf","message":"\\Users\\[redacted]\\AppData\\Roaming\\Lantern\\lantern-2.0.0-beta8.yaml: The system cannot find the file speci","timestamp":1437751064434}
```

**Comment by myleshorton** [comment]
Interesting @xiam thanks I'll take a look.

**Comment by myleshorton** [comment]
It looks like there's nothing that locks the reading and writing to this file on a first pass @xiam. I don't think this will have any really adverse affects as far as I can tell though, so pushing to next version. You want to take a peek at it? I think we might just have to add a mutex around reading and writing to the yaml file.

**Comment by fffw** [comment]
It may not related to locking. By looking at the occurrence of any specific
instanceid, we can conclude that they were always reported consecutively in
single period. For example, [this one](
https://lantern.loggly.com/search#terms=Unable%20to%20stat%20config%20file&from=2015-07-24T13%3A00%3A00.000Z&until=2015-07-24T16%3A00%3A00.000Z&source_group=&filter=json.extra.osName%3Bwindows&filter=json.instanceid%3B0071cc95c618)
reported 6363 times in less than 2 hours.

`yamlconf` will not attempt to create a file if it doesn't exist, so if
yaml gets removed during Lantern running, error will be continuously
reported. It can be easily avoided by follow @myleshorton 's suggestion
[here](
https://github.com/getlantern/lantern/pull/2680#issuecomment-115897265) to
simplify config.

**Comment by fffw** [comment]
Just a supposition: lantern.yaml gets removed by AV software?

**Comment by myleshorton** [comment]
Haven't seen this one in awhile
