### ISSUE TITLE
Multicast listening causing user warnings on OSX and Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2813]
We used to handle this through code signing on OSX and adding a firewall rule on Windows, but that's let's punt on that until the next release. Actually the code signing approach might still be working on OSX not sure.

**Comment by uaalto** [comment]
@myleshorton Do we have old code doing this for reference? I would like to get to this to make Lantern Pi available.

**Comment by uaalto** [comment]
This will be apparently solved by code signing, right?

**Comment by myleshorton** [comment]
On OSX it will be solved by code signing, but not on windows. Our old code that handled this one Windows is at:

https://github.com/getlantern/lantern-java/blob/master/install/win/Lantern.bat

We'll need to integrate something similar for give mode lantern in general actually. Would you mind ticketing that @uaalto?

**Comment by uaalto** [comment]
Done. I'll be adding more information there if necessary. I keep track of that issue as part of the P2P work.

**Comment by myleshorton** [comment]
Awesome!

On Fri, Aug 14, 2015 at 12:45 AM, Ulysses Aalto <notifications@github.com>
wrote:

> Done. I'll be adding more information there if necessary. I keep track of
> that issue as part of the P2P work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2813#issuecomment-131008849>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
This will be an issue again with IPFS.

**Comment by myleshorton** [comment]
Closing since we don't have this issue now.
