### ISSUE TITLE
stuck in buiding tags when build binaries from souce code (tag: 2.0.0.0, fca6eff)

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2833]
Hi,
It stuck in buiding  windows/386 tags when build binaries from souce code (tag: 2.0.0.0, fca6eff)

Detais as follow:

Step 37 : WORKDIR $WORKDIR
 ---> Using cache
 ---> f0b6909b18e2

Successfully built f0b6909b18e2
Generating assets...
Icon  installer-resources/windows/lantern.ico  ID:  5
OK
Building linux/386...
** VERSION was not set, using git revision instead (0d0e46b). This is OK while in development.
Build tags:
-rwxr-xr-x 1 root root 10868685 Jul 28 04:57 lantern_linux_386
-rw-r--r-- 1 root root  3627487 Jul 28 04:57 update_linux_386.bz2
Building linux/amd64...
** VERSION was not set, using git revision instead (0d0e46b). This is OK while in development.
Build tags:
-rwxr-xr-x 1 root root 12499644 Jul 28 04:57 lantern_linux_amd64
-rw-r--r-- 1 root root  3710698 Jul 28 04:57 update_linux_amd64.bz2
Building linux/arm...
** VERSION was not set, using git revision instead (0d0e46b). This is OK while in development.
Build tags: headless
-rwxr-xr-x 1 root root 10856096 Jul 28 04:57 lantern_linux_arm
-rw-r--r-- 1 root root  3589065 Jul 28 04:57 update_linux_arm.bz2
Building windows/386...
** VERSION was not set, using git revision instead (0d0e46b). This is OK while in development.
Build tags:

Stuck at this step and cannot go furthermore

**Comment by fffw** [comment]
@yuan78 What if you `make windows-386` directly?

**Comment by yuan78** [comment]
Hi , I run "make binaries"

**Comment by xiam** [comment]
Hello @yuan78,

I can't replicate your problem. When your system hangs is any process on top? How does your RAM and free disk space look like?

**Comment by yuan78** [comment]
Only my system hangs up when build latern, I run it on VPS (768M RAM ,15G HDD)，but I re-deploy the VPS with 1G RAM ,20G HDD，now it' OK.

Step 37 : WORKDIR $WORKDIR
 ---> Using cache
 ---> a7d91b762f02
Successfully built a7d91b762f02
Generating assets...
Icon  installer-resources/windows/lantern.ico  ID:  5
OK
Building linux/386...
** VERSION was not set, using git revision instead (b1d6ba6). This is OK while in development.
Build tags:
-rwxr-xr-x 1 root root 10868811 Jul 29 02:07 lantern_linux_386
-rw-r--r-- 1 root root  3628489 Jul 29 02:07 update_linux_386.bz2
Building linux/amd64...
** VERSION was not set, using git revision instead (b1d6ba6). This is OK while in development.
Build tags:
-rwxr-xr-x 1 root root 12499794 Jul 29 02:08 lantern_linux_amd64
-rw-r--r-- 1 root root  3708658 Jul 29 02:08 update_linux_amd64.bz2
Building linux/arm...
** VERSION was not set, using git revision instead (b1d6ba6). This is OK while in development.
Build tags: headless
-rwxr-xr-x 1 root root 10856222 Jul 29 02:08 lantern_linux_arm
-rw-r--r-- 1 root root  3592750 Jul 29 02:08 update_linux_arm.bz2
Building windows/386...
** VERSION was not set, using git revision instead (b1d6ba6). This is OK while in development.
Build tags:
-rwxr-xr-x 1 root root 11148288 Jul 29 02:08 lantern_windows_386.exe
-rw-r--r-- 1 root root  3757073 Jul 29 02:08 update_windows_386.bz2
Building darwin/amd64...
-> Skipped: Can not compile Lantern for OSX on a non-OSX host.

**Comment by xiam** [comment]
Thanks @yuan78, closing this as it was a local problem.
