### ISSUE TITLE
Setup Apache Traffic Server on test VPS

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2836]
Already up and running.

Documentation: https://docs.trafficserver.apache.org/en/latest/getting-started.en.html#introduction
Configuration file: /opt/ats/etc/trafficserver/records.config
Log directory: /opt/ats/var/log/trafficserver

**Comment by myleshorton** [comment]
Assigning this over to you @fffw with @atavism focusing on the client side...

Would be great to run some performance tests first.

Other necessary tasks include:

1. Make sure we use the existing python script to randomize certs
1. Use customized authentication

**Comment by atavism** [comment]
@myleshorton @fffw The ATS server is still running on the VPS I sent both of you, and you both shuld have access.

**Comment by fffw** [comment]
I can login to the server. Thanks @atavism !

**Comment by fffw** [comment]
ATS as a forward proxy [is open by default](https://docs.trafficserver.apache.org/en/latest/admin/forward-proxy.en.html#security-considerations). ssl support is [through configuration](https://docs.trafficserver.apache.org/en/latest/admin/security-options.en.html#client-and-traffic-server-connections), randomized certs should be not tough, but for customized authentication using HTTP header, we need to write a plugin, something like the [example](https://docs.trafficserver.apache.org/en/latest/sdk/header-based-plugin-examples/basic-authorization-plugin.en.html) ([c code](https://github.com/apache/trafficserver/blob/master/example/basic-auth/basic-auth.c)).

**Comment by myleshorton** [comment]
Sounds awesome @fffw! Let's do it.

On Wed, Aug 12, 2015 at 6:45 AM, fffw <notifications@github.com> wrote:

> ATS as a forward proxy is open by default
> <https://docs.trafficserver.apache.org/en/latest/admin/forward-proxy.en.html#security-considerations>.
> ssl support is through configuration
> <https://docs.trafficserver.apache.org/en/latest/admin/security-options.en.html#client-and-traffic-server-connections>,
> randomized certs should be not tough, but for customized authentication
> using HTTP header, we need to write a plugin, something like the example
> <https://docs.trafficserver.apache.org/en/latest/sdk/header-based-plugin-examples/basic-authorization-plugin.en.html>
> (c code
> <https://github.com/apache/trafficserver/blob/master/example/basic-auth/basic-auth.c>
> ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2836#issuecomment-130311384>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
Recorded repeatable build process at https://github.com/getlantern/ats. It uses the same tool as `gencert.py`, so it should be easy to integrate with salt. A few refactor or lantern-aws is required to keep DRY.
