### ISSUE TITLE
Unable to access blocked sites in Firefox - windows 8.1

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2837]
Firefox couldn't open the blocked sites. However, IE and chrome are able to open the same.

**Comment by myleshorton** [comment]
Do you have FF set to use system proxy settings?

**Comment by sheena3** [comment]
Yeah @myleshorton. I was using System proxy settings. After changing it to Auto-detect proxy settings, it worked fine. 

Shall I close it now? Do we have any ticket already open to tackle the settings automatically by Lantern?

**Comment by myleshorton** [comment]
No it should be set to 'Use system proxy settings", which is the default. What happens when you try to open blocked sites in FF with "Use system proxy settings" set?

**Comment by sheena3** [comment]
@myleshorton In my system, FF is already set to Use system proxy settings by default. I couldn't access blocked sites (I used fake DNS to check blocking). After changing the settings to 'Auto detect proxy setting', then I was able to access. 

Are you saying that I should be able to access with 'Use system proxy settings' and not with 'Auto detect proxy settings'?

**Comment by myleshorton** [comment]
Yeah you shouldn't have to change the defaults. I couldn't reproduce it on the first try, but I'll try again.

**Comment by xiam** [comment]
I could not reproduce this issue. Twitter is blocked on my system and I was still able to browse it using Lantern.

My Firefox's proxy settings:

![screen shot 2015-07-29 at 10 14 51 am](https://cloud.githubusercontent.com/assets/385670/8961415/ae59219e-35da-11e5-94df-572033adc4df.png)

My testing was as follows:

1. I tried first without Lantern, Firefox was unable to find Twitter (my blocked site for testing). Which is what I was expecting.
2. Then I fired Lantern and tried again with Firefox, it failed again even though Lantern was running, maybe the DNS address was cached, some browsers do that for speed reasons.
3. After a couple of seconds I hit refresh and I was browsing the blocked site.

**Comment by sheena3** [comment]
When I tried to reproduce this, I found out that FF is not remembering my settings regarding proxy. So when I select 'Auto detect proxy setting for this network' and clicked OK, it still reverts back to the default 'Use system proxy settings'. I have no clue why this is happening anyway.

So we are good now. Sorry about the confusion.

**Comment by xiam** [comment]
Cool, thanks @sheena3

**Comment by myleshorton** [comment]
Thanks guys!
