### ISSUE TITLE
http: proxy error: dial tcp [2001:67c:4e8:f002::a]:80: no route to host

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2844]
The error message isn't that helpful, but we're seeing this occasionally in Loggly so I'll just open a ticket to document it.

**Comment by uaalto** [comment]
Is IPv6 supported in Lantern through all the stack? I *think* I've seen some IPv4-specific code somewhere, which reminds me that tools that don't provide IPv6 support return similar errors when given such addresses.
It might be a long-shot, but seems the first obvious place to look at.
