### ISSUE TITLE
lantern server does not want to accept ^C and refuses to die

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2846]
Launched a headless Lantern server with the latest valencia code:

```
./lantern_linux_amd64 -role=server -addr=:443
```

After a while I sent `^C` expecting the process to die:

```
^CJul 29 17:58:45.463 - 0m5s DEBUG flashlight: flashlight.go:404 Calling exit func
DEBUG flashlight: flashlight.go:404 Calling exit func
DEBUG flashlight: flashlight.go:407 No exit func remaining, exit now
^C^C^C^C^C^C^C^C
```

Lantern server ignored my signal and kept working; I had to send it another signal to actually terminate it:

```
killall ./lantern_linux_amd64 -KILL
```

I suspect this is related to the changes we made to catch termination signals, but the odd thing is that it does not happen in client mode.

**Comment by uaalto** [comment]
I think the code to catch signals just exposed the issue, but we were probably failing to cleanup properly before as well, because the server function wasn't running on its own goroutine as the client function was. I just opened a PR with this patch, which seems to catch the signals properly now.
