### ISSUE TITLE
how to build lantern  binary for android from source code?

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2849]
Hi,
how to build lantern  binary for android from source code?

**Comment by uaalto** [comment]
You can build a library (libflashlight.aar) that can be embedded in an Android program. Currently the Firetweet uses this for accessing the Lantern backend. There is no Android app at the moment for system-wide proxying. We will be working on that in the near future, so stay tuned!
Does this solve your question?

**Comment by yuan78** [comment]
OK, will wait for Android app ,THX!
