### ISSUE TITLE
Proxy All Traffic option when disabled needs Lantern to be restarted

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2853]
Enabling Proxy All Traffic option neither needs restart nor a new Lantern browser. Whereas disabling Proxy All Traffic option needs restarting. 

I verified this only in Firefox. Will update here if it is the same in the other browsers too.

**Comment by myleshorton** [comment]
Oh interesting thanks @sheena3.

**Comment by myleshorton** [comment]
I'm actually going to move this to 2.0.1, as I doubt it actually a new issue and probably doesn't need to hold up 2.0.0. @fffw you mind taking a look at this when you have the chance?

**Comment by fffw** [comment]
@sheena3 Could I know what are your steps to reveal this issue?

I tested using Firefox and 2.0.0 QA version on Mac as follows:
1. Run Lantern, make sure "Proxy all" option is unticked.
2. Visit an IP address query site that fast enough and not in built-in whitelist, and make sure it shows my current city.
3. Tick "Proxy all", above site shows that I'm visiting from North America after significant delay.
4. Untick "Proxy all", it loads fast and shows my current city again.

**Comment by sheena3** [comment]
I couldn't reproduce. I retested this with the fake server to block and test proxy all option and it works fine. 

When I tried geoiptool.com and speedtest.net, it takes a little while to update which I noticed only today. Thanks for checking it at your end @fffw. Closing this now.
