### ISSUE TITLE
tlsdialer_test.go:224: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2858]

**Comment by uaalto** [comment]
This error was caused by an error that was handled and *should be ignored*. Fixed on the branch that introduced it.

**Comment by myleshorton** [comment]
https://travis-ci.org/getlantern/lantern/builds/74462953

**Comment by uaalto** [comment]
It was a different error, but we can use this issue. I'm going to rename issue to the error.

**Comment by uaalto** [comment]
Not reproducible locally, after 100 runs.
