### ISSUE TITLE
Can I build the latest binary synchronized with everyday's commit by add --depth 1 for git clone 

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2862]
Can I build the latest binary synchronized with everyday's commit by add --depth 1 for git clone ?

whole command as follow :
git clone -b valencia --depth 1 --single-branch git://github.com/getlantern/lantern.git

**Comment by uaalto** [comment]
All the code in valencia is reviewed and *should* compile fine,  if that's what you are asking.
Did this solve your question?

**Comment by yuan78** [comment]
What you me mean is I can build the latest binary at any time and will not wait you to post the newer tag? 
For example, if I want to build the latest lantern binaries according to today's newest commits, following command is enough?

git clone -b valencia --depth 1 --single-branch git://github.com/getlantern/lantern.git
cd lantern
make binaries

BTW: docker image was already ready.

**Comment by uaalto** [comment]
Yes, I tested and you shouldn't run into any problems. Only last commit in `valencia` will be available in your history. The only problem is that your logs won't be sent to us automatically (if you accept it in the config settings). However I think you are perfectly capable of sending us the logs if you run into any issue, or even check out possible causes yourself.
Docker image will be available, so you'll be fine on that side as well.
