### ISSUE TITLE
Windows 10 defender reports that 2.0.0-beta8 contains a trojan

### ISSUE THREAD

**Issue by Rany008** [getlantern/lantern#2865]
download last beta 2.8  windows Release，win10  defender Report Trojans.

**Comment by fffw** [comment]
Thanks @Rany008 . Could you provide a screenshot and/or which type of trojan it reported?

**Comment by Rany008** [comment]
![t1](https://cloud.githubusercontent.com/assets/6700578/9029717/fefbff74-39ca-11e5-89a5-441ae240076f.jpg)
![t2](https://cloud.githubusercontent.com/assets/6700578/9029718/ff2569cc-39ca-11e5-9b2d-1a09c6c3b54b.jpg)

**Comment by fffw** [comment]
It's a great help @Rany008 . Lantern's auto-update mechanism was considered as trojan by Win 10 defender! We will address it ASAP.

**Comment by Rany008** [comment]
Thanks！

**Comment by myleshorton** [comment]
@sunshine19090 can you test with Windows 10 defender?

**Comment by sunshine19090** [comment]
Sure @myleshorton, I can test it for 2.2.0.

**Comment by myleshorton** [comment]
All set in latest versions.
