### ISSUE TITLE
Couldn't install the newer version of Lantern 2.0.0 in Ubuntu 32-bit

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2869]
Getting the message "A later version is already installed"
![screenshot from 2015-08-03 10 14 08](https://cloud.githubusercontent.com/assets/11394369/9043280/34e851b6-39c9-11e5-9161-7ad981ddf075.png)

**Comment by xiam** [comment]
I'm going to take a look at this one too, as the resolution could affect https://github.com/getlantern/lantern/pull/2870

**Comment by myleshorton** [comment]
Great!

**Comment by xiam** [comment]
@sheena3 How are you testing this? I usually install .deb packages with the `dpkg` command and it does not complain:

2.0.0-beta8:

```
vagrant@vagrant:~$ sudo dpkg -i lantern_2.0.0-beta8+manoto_amd64.deb
(Reading database ... 127189 files and directories currently installed.)
Preparing to unpack lantern_2.0.0-beta8+manoto_amd64.deb ...
Unpacking lantern (2.0.0-beta8+manoto) over (2.0.0-beta8+manoto) ...
Setting up lantern (2.0.0-beta8+manoto) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
```

2.0.0

```
vagrant@vagrant:~$ sudo dpkg -i lantern_2.0.0_amd64.deb
dpkg: warning: downgrading lantern from 2.0.0-beta8+manoto to 2.0.0
(Reading database ... 127189 files and directories currently installed.)
Preparing to unpack lantern_2.0.0_amd64.deb ...
Unpacking lantern (2.0.0) over (2.0.0-beta8+manoto) ...
Setting up lantern (2.0.0) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
``` 

Are you using a graphical tool?

**Comment by xiam** [comment]
In fact, after installing `2.0.0` I can go back to `2.0.0-beta8` no questions asked:

```
vagrant@vagrant:~$ sudo dpkg -i lantern_2.0.0-beta8+manoto_amd64.deb
(Reading database ... 127190 files and directories currently installed.)
Preparing to unpack lantern_2.0.0-beta8+manoto_amd64.deb ...
Unpacking lantern (2.0.0-beta8+manoto) over (2.0.0) ...
Setting up lantern (2.0.0-beta8+manoto) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
```

**Comment by sheena3** [comment]
Yep..I go to the Downloads folder and click on the .deb file and it will
usually opens the Ubuntu software center and provides details about the
installation. And there will be an install button to proceed with.

But for 2.0.0, I am getting this message instead. I don't see the install
button at all.

On Wed, Aug 5, 2015 at 9:27 PM, José Carlos <notifications@github.com>
wrote:

> @sheena3 <https://github.com/sheena3> How are you testing this? I usually
> install .deb packages with the dpkg command and it does not complain:
>
> 2.0.0-beta8:
>
> vagrant@vagrant:~$ sudo dpkg -i lantern_2.0.0-beta8+manoto_amd64.deb
> (Reading database ... 127189 files and directories currently installed.)
> Preparing to unpack lantern_2.0.0-beta8+manoto_amd64.deb ...
> Unpacking lantern (2.0.0-beta8+manoto) over (2.0.0-beta8+manoto) ...
> Setting up lantern (2.0.0-beta8+manoto) ...
> Processing triggers for hicolor-icon-theme (0.13-1) ...
> Processing triggers for mime-support (3.54ubuntu1.1) ...
> Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
> Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
>
> 2.0.0
>
> vagrant@vagrant:~$ sudo dpkg -i lantern_2.0.0_amd64.deb
> dpkg: warning: downgrading lantern from 2.0.0-beta8+manoto to 2.0.0
> (Reading database ... 127189 files and directories currently installed.)
> Preparing to unpack lantern_2.0.0_amd64.deb ...
> Unpacking lantern (2.0.0) over (2.0.0-beta8+manoto) ...
> Setting up lantern (2.0.0) ...
> Processing triggers for hicolor-icon-theme (0.13-1) ...
> Processing triggers for mime-support (3.54ubuntu1.1) ...
> Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
> Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
>
> Are you using a graphical tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2869#issuecomment-128048859>
> .
>



-- 
Regards,
Sunshine

**Comment by xiam** [comment]
Got it! crazy.

![screen shot 2015-08-05 at 11 07 18 am](https://cloud.githubusercontent.com/assets/385670/9090833/2c4224fc-3b62-11e5-8e86-71bd2543bb98.png)


This sounds to me like an Ubuntu bug, dpkg (the tool that actually manages packages) works fine. I'll try the `2.0.0-final` suggestion from @aranhoide.

**Comment by xiam** [comment]
Both `2.0.0-stable` and `2.0.0+stable` work.

![screen shot 2015-08-05 at 12 15 57 pm](https://cloud.githubusercontent.com/assets/385670/9092422/c1ce0118-3b6b-11e5-8ec2-38f74deca973.png)

I also found that we can also [compare versions](https://debian-handbook.info/browse/stable/sect.manipulating-packages-with-dpkg.html) directly with `dpkg`.

```
dpkg --compare-versions "2.0.0" gt "2.0.0-beta8"; echo $?
1
```

So it's not a bug in Ubuntu, it's just that dpkg users a different standard for version comparison.

**Comment by xiam** [comment]
If we use `-`, then we must provide a word that is lexicographically greater than "beta8"

```
dpkg --compare-versions "2.0.0-c" gt "2.0.0-beta8"; echo $?
0
```

If we use `+` we can use anything.

```
dpkg --compare-versions "2.0.0+a" gt "2.0.0-beta8"; echo $?
0
```

We are going to have this problem with all our releases, I suggest we workaround this issue with the "+stable" *metadata* string because that does not have any effect for the semver standard. We'll have to do that each time we want to promote a beta version.

```
dpkg --compare-versions "2.0.1-beta1" gt "2.0.0+stable"; echo $?
0
dpkg --compare-versions "2.0.1+stable" gt "2.0.0+stable"; echo $?
0
 dpkg --compare-versions "2.0.1-beta1" lt "2.0.1+stable"; echo $?
0
```

What do you think @atavism, @myleshorton?

**Comment by myleshorton** [comment]
Yeah I think that sounds like a plan @xiam!

**Comment by sheena3** [comment]
Works fine now.
