### ISSUE TITLE
No rule to make target when build lantern binary (Docker image ready) 

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2878]
No rule to make target when build lantern binary (Docker image ready) and build fail

details as follow:

[root@vultr ~]# git clone -b valencia  --single-branch git://github.com/getlantern/lantern.git
Cloning into 'lantern'...
remote: Counting objects: 34820, done.
remote: Compressing objects: 100% (265/265), done.
remote: Total 34820 (delta 392), reused 275 (delta 254), pack-reused 34292
Receiving objects: 100% (34820/34820), 194.70 MiB | 24.57 MiB/s, done.
Resolving deltas: 100% (18746/18746), done.
[root@vultr ~]# cd lantern
[root@vultr lantern]# git checkout 2.0.0-beta11
Note: checking out '2.0.0-beta11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at a79c122... fix bug updating UI textarea
[root@vultr lantern]# cp /home/www/flashlight-noUI-150805 ./src/github.com/getlantern/flashlight/flashlight.go
cp: overwrite ‘./src/github.com/getlantern/flashlight/flashlight.go’? y
[root@vultr lantern]# make binaries
make: *** No rule to make target `binaries'.  Stop.
[root@vultr lantern]# make windows
make: *** No rule to make target `windows'.  Stop.

**Comment by yuan78** [comment]
I found the cause , the Makefile& docker is missing, but it still show below errors when I append the two files:
Generating assets...
/bin/bash: line 16: src/github.com/getlantern/flashlight/ui/resources.go: No such file or directory
Makefile:124: recipe for target 'docker-genassets' failed
make: *** [docker-genassets] Error 1
make: *** [genassets] Error 2

**Comment by fffw** [comment]
if you `git log`, you'll see that the tag `2.0.0-beta11` is really old,
might be mistakenly tagged. Branch `valencia` always contains current
production code.

**Comment by yuan78** [comment]
Hi, 
I re-git clone and add -depth 1，it's OK now.
