### ISSUE TITLE
OSX crashes on Sierra as a result of auto-update breaking code signing

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2888]
Not sure about Windows, but unfortunately on OSX auto-updates break our signature. This results in the OS prompting the user to allow Lantern to set the system proxy, and it looks like that's the extent of it pretty much. Not sure what the solution is.

After auto-update you'll see:

```
 spctl --assess /Applications/Lantern.app
/Applications/Lantern.app: rejected
```

and will get prompted to enter your password to allow it to set the system proxy.

**Comment by xiam** [comment]
I haven't see that prompt in my testing, how do you trigger it? What's the Lantern version you started with?

**Comment by myleshorton** [comment]
I started with manoto beta8. I *think* there might actually be two separate issues here:

1. I suspect there's something wrong with the signature of the new pac executable
1. There seems to be a separate issue with updates breaking our signature which may or may not be related to that specific prompt.

**Comment by myleshorton** [comment]
Also once you enter a password once, you don't see the prompt again on subsequent runs..

**Comment by myleshorton** [comment]
Yeah the system proxy password prompt is unrelated to the code signing issue for sure -- I get it with a fresh Lantern install on 2.0.0+stable.

**Comment by myleshorton** [comment]
So the consequences of this will be felt more in future P2P versions the allow incoming connections. OSX by default allows code-signed applications through the firewall, but otherwise will prompt the user.

**Comment by myleshorton** [comment]
Any luck reproducing this @xiam? It's basically just a matter of running spctl before and after the auto-update, so:

```
spctl --assess /Applications/Lantern.app
```

**Comment by xiam** [comment]
Hello @myleshorton,

Still no luck, I started with beta8 and after a while it received the update. Can you try this?

With beta8 manoto:

```
spctl --assess /Applications/Lantern.app
shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
e0997b393a6bc8d6e6e32865b6bf0ea127d3589f06eaf58039280d06743a5170  /Applications/Lantern.app/Contents/MacOS/lantern
```

With beta9 (our fake update):

```
spctl --assess /Applications/Lantern.app
shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
1f460a36d72944577455d6c52cfd75a02d9375257c8e0935d0ccacba0d258b8a  /Applications/Lantern.app/Contents/MacOS/lantern
```

**Comment by xiam** [comment]
Oh, our latest QA alpha for 2.0.0 did trigger the prompt. The `spctl` program does not say that it was rejected, do I need to pass some other argument to it?

```
spctl --assess /Applications/Lantern.app
shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
a1c2889cdcad5c340767f96ad6f9fe56eba6f0064037e67d9174950047ad775d  /Applications/Lantern.app/Contents/MacOS/lantern
```

**Comment by myleshorton** [comment]
The prompt is really 100% unrelated. So this is odd -- I'm seeing something different. This is with **manoto** beta 8, which maybe makes a difference not sure, all from the same run:

```
$ spctl --assess /Applications/Lantern.app
$ shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
e0997b393a6bc8d6e6e32865b6bf0ea127d3589f06eaf58039280d06743a5170  /Applications/Lantern.app/Contents/MacOS/lantern
$ open /Applications/Lantern.app
$ shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
1f460a36d72944577455d6c52cfd75a02d9375257c8e0935d0ccacba0d258b8a  /Applications/Lantern.app/Contents/MacOS/lantern
$ spctl --assess /Applications/Lantern.app
/Applications/Lantern.app: rejected
```

**Comment by xiam** [comment]
@myleshorton 

According to the checksums you have exactly the same binary that I started with and after a while you upgraded to the same one I was upgraded to. I'm going to try with `open` and without restarting Lantern to see if there is any difference.

**Comment by xiam** [comment]
Yeah, same thing. I'm using this script:

```
#!/bin/bash
spctl --assess /Applications/Lantern.app
shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern  /Applications/Lantern.app/Contents/MacOS/lantern
open /Applications/Lantern.app
sleep 10
shasum -a 256 /Applications/Lantern.app/Contents/MacOS/lantern
spctl --assess /Applications/Lantern.app
```

And I only got the checksums.

```
./test-2888.sh
e0997b393a6bc8d6e6e32865b6bf0ea127d3589f06eaf58039280d06743a5170  /Applications/Lantern.app/Contents/MacOS/lantern
1f460a36d72944577455d6c52cfd75a02d9375257c8e0935d0ccacba0d258b8a  /Applications/Lantern.app/Contents/MacOS/lantern
```

If you download the 2.0.0+manoto binary update from here https://github.com/xiam/lantern/releases/tag/2.0.0%2Bmanoto, do you have the same results?

```
bzip2 -d update_darwin_amd64.bz2
shasum -a 256 update_darwin_amd64
1f460a36d72944577455d6c52cfd75a02d9375257c8e0935d0ccacba0d258b8a  update_darwin_amd64
```

**Comment by xiam** [comment]
I did another test with regular beta8 from s3 and after a few seconds it got updated to 2.0.0+stable:

```
./test-2888.sh
c4477f5235b4c1afdccf833c4aaaef8d89f3da120d1c7dab5548eba681b22699  /Applications/Lantern.app/Contents/MacOS/lantern
a1c2889cdcad5c340767f96ad6f9fe56eba6f0064037e67d9174950047ad775d  /Applications/Lantern.app/Contents/MacOS/lantern
```

**Comment by myleshorton** [comment]
This is all using your server correct @xiam?

**Comment by myleshorton** [comment]
I.e. you put 2.0.0+stable on your server?

**Comment by myleshorton** [comment]
What does ```spctl --status``` give you @xiam?

**Comment by myleshorton** [comment]
Can you also try ```spctl --raw -a /Applications/Lantern.app```? I'm curious if you might have a cached local assessment before and after the update for some reason.

**Comment by myleshorton** [comment]
Also ```codesign --verify --verbose /Applications/Lantern.app``` before and after.

**Comment by xiam** [comment]
> This is all using your server correct @xiam?

@myleshorton Yes, this is all with my test server that uses releases listed at https://github.com/xiam/lantern/releases, I took the update binary from the 2.0.0+stable we currently have in QA.

This says nothing:

```
spctl --assess /Applications/Lantern.app
# (nothing)
```

But this one says "security disabled".

```
spctl --assess --verbose /Applications/Lantern.app
/Applications/Lantern.app: accepted
override=security disabled
```

This other one too:

```
spctl --raw -a /Applications/Lantern.app
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>assessment:authority</key>
	<dict>
		<key>assessment:authority:override</key>
		<string>security disabled</string>
	</dict>
	<key>assessment:error</key>
	<integer>-67023</integer>
	<key>assessment:remote</key>
	<true/>
	<key>assessment:verdict</key>
	<true/>
</dict>
</plist>
```

The codesign line complains:

```
codesign --verify --verbose /Applications/Lantern.app
/Applications/Lantern.app: invalid resource directory (directory or signature have been modified)
```

I don't think this was disabled by default, maybe I did and don't remember. I'm going to try to reenable this and see what happens.

**Comment by myleshorton** [comment]
I get:

```
 spctl --assess --verbose /Applications/Lantern.app
/Applications/Lantern.app: accepted
source=Developer ID
```

**Comment by myleshorton** [comment]
This is useful:

https://developer.apple.com/library/mac/technotes/tn2206/_index.html

**Comment by myleshorton** [comment]
Darn it looks like on Sierra this issue actually causes Lantern to crash completely -- Sierra won't even run it because the signature breaks @xiam. I wonder how Chrome gets around this?

**Comment by myleshorton** [comment]
We might just want to disable auto-update on OSX for now @xiam.

**Comment by myleshorton** [comment]
I should say I haven't 100% verified this is the cause, but it crashes with an error about the signature. See:

```
Process:               lantern [3736]
Path:                  /Applications/Lantern.app/Contents/MacOS/lantern
Identifier:            lantern
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        bash [843]
Responsible:           lantern [3736]
User ID:               501

Date/Time:             2016-12-16 08:12:44.091 -0800
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        190FFB73-96B8-4D13-1FB3-554C81D18B2E


Time Awake Since Boot: 540 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by p3rcya** [comment]
Tons of crash reports from users on OSX!

**Comment by orbancanon** [comment]
Example of user reported issues. Can be explained by this finding.
https://github.com/getlantern/forum/issues/2042
https://github.com/getlantern/forum/issues/2032

**Comment by myleshorton** [comment]
Hey @xiam you think you might have time to dig into this one?

**Comment by xiam** [comment]
I've been digging into this one, codesign documentation says:

> When you have qualified a new version of your product, sign it just as you signed the previous version, with the same identifier and the same designated requirement. The user’s system considers the new version of your product to be the same program as the previous version. For example, Keychain Services does not distinguish older and newer versions of your program as long as both are signed and the unique Identifier remains constant.

And that's something we currently don't do, we use a requirements file when signing. It seems like this file has a particular structure: https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html. I'll read more on the topic and try that.

**Comment by xiam** [comment]
@myleshorton I think I found a workaround. Could you help me confirm it works?

Create a special Lantern 2.0.99 version:

```
VERSION=2.0.99 make package-darwin
```

When you run this `2.0.99` version, it will get autoupdated and Lantern will crash on Sierra, `spctl`  will complain too:

```
spctl --assess /Applications/Lantern.app --verbose                               /Applications/Lantern.app/Contents/MacOS
/Applications/Lantern.app: invalid Info.plist (plist or signature have been modified)
```

Copy this file [Info.plist.txt](https://github.com/getlantern/lantern/files/662839/Info.plist.txt) (`5423e4043eea87771aa0521e5220e63bd06d9972`) into `/Applications/Lantern.app/Contents/Info.plist`. (this is the most recent `Info.plist` file)


Run `spctl` again:

```
spctl --assess /Applications/Lantern.app --verbose                               /Applications/Lantern.app/Contents/MacOS
/Applications/Lantern.app: accepted
source=Developer ID
```

Run Lantern again, it should work now.

It seems like we've signing the binary correctly all the time but if we touch any file within in the `.app` bundle then the signature is invalidated, in this case, OSX thinks we messed with the `Info.plist` file but the problem is that that `.plist` wasn't updated. The correct solution would be upgrading the whole `Lantern.app` package and not only the binary, which is doable but complicated, we can also try removing dynamic content from `Info.plist` and just ship the same file from now on, we don't really need to push the version string there (also, `CFBundleShortVersionString` and `CFBundleVersion` haven't been updated in a while, they still say `2.0.0`). This won't work for old versions but should work for new releases, and it's a pretty easy fix. Thoughts?

**Comment by myleshorton** [comment]
Hey this sounds great to me @xiam, and sorry it's taken forever for me to look at it!

**Comment by myleshorton** [comment]
Hey I think I waited too long on this and that now we're up to this newer version of Lantern (3.5.11).

The general approach looks good to me though @atavism and quite safe, so I'm going to pull it in.

**Comment by myleshorton** [comment]
Preemptively closing. Can re-open if we see issues.
