### ISSUE TITLE
How to build docker image by using proxy because GFW blockde the URL resources

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2894]
Previously I use VPS  to build docker image, but it's too inconvenient, everytime I need transfer back the finished binary to my local machine by FTP.
Then I want to build docker image in my local machine, but it show the below fail info  because China GFW blocked google and other download resources , how to build docker image by using proxy?

I tried to install tsocks (use shadowsocks as upstream proxy), and run "tocks make docker" ,but still fail.  Pls help.

Fail Info:

Step 12 : RUN (curl -sSL $GO_PACKAGE_URL | tar -xvz -C /tmp) &&   mv /tmp/go $GOROOT_BOOTSTRAP
 ---> Running in d52924e37091
curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by fffw** [comment]
@yuan78 It's a topic unrelated to lantern project. You can use VPN to circumvent. There are lots of free and paid VPN service provider.

To copy back binary from VPS to local machine, you can use `scp` if ssh works (On Windows, PuTTY has a similar tool called pscp).
