### ISSUE TITLE
encounter error of "Missing "go" command" when build docker image

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2904]
Hi,
I encountered error of "Missing "go" command" when build docker image as follow:

gary@gary-To-be-filled-by-O-E-M:~/lantern$ sudo make docker
Missing "go" command.
Makefile:236: recipe for target 'system-checks' failed
make: *** [system-checks] Error 1

But I acually installed golang1.4.2 already, and set correct PATH as below:
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

And run go version, it can show version correctly: 
gary@gary-To-be-filled-by-O-E-M:~/lantern$ which go
/usr/local/go//bin/go
gary@gary-To-be-filled-by-O-E-M:/usr/local/go/src$ go version
go version go1.4.2 linux/amd64

What's the reason? Pls help. 

BTW: My OS is Ubuntu14.10, I successfully installed docker image many times in my VPS,but fail in my local machine,but the procedure is the same

**Comment by aranhoide** [comment]
The issue tracker is not a support forum.  Please stop doing that.
