### ISSUE TITLE
Errors running pac-cmd on windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2905]
Getting this a fair bit in our logs.

```
ERROR flashlight: pac.go:169 Unable to unset lantern as system proxy: Unable to execute C:\\Users\\Administrator\\AppData\\Roaming\\byteexec\\pac-cmd.exe: fork/exec C:\\Users\\Administrator\\AppData\\Roaming\\byteexec\\pac-cmd.exe: Access is denied
```

**Comment by myleshorton** [comment]
You want to take a look @fffw? It seems like we should have gotten an earlier error too saying we couldn't set the permissions. We actually might have gotten those, but I haven't had a chance to check.

**Comment by fffw** [comment]
@myleshorton I haven't found the error setting pac-cmd permissions yet but will try to check more. It might be possibly blocked by AV software.

**Comment by fffw** [comment]
Reported Lantern version varies from beta5 to stable so they are not introduced recently. Top 5 instanceids contributed 85% to the total. `pac-cmd` are called frequently during Lantern running to notify browser that pac file changed, that explains the distribution.

While searching for "Access is denied" in Loggly, I found a few other similar errors.

> ERROR flashlight.ui: ui.go:101 Error opening page to `http://127.0.0.1:16823`: fork/exec C:\Windows\System32\rundll32.exe: Access is denied.

> ERROR launcher: launcher_windows.go:41 Error setting Lantern auto-start registry key: "Access is denied."

> ERROR launcher: launcher_windows.go:39 Error removing Lantern auto-start registry key: "Access is denied."

>  ERROR yamlconf: yamlconf.go:264 Unable to apply update from custom polling: Unable to write config yaml to file C:\Users\[filtered]\AppData\Roaming\Lantern\lantern-9999.99.99.yaml: open C:\Users\[filtered]\AppData\Roaming\Lantern\lantern-9999.99.99.yaml: Access is denied.

I guess all of them are caused by user's local security setting or AV software. The only way I can think of is to have user informed. Follow our discussion during team meeting, I'd suggest to, as a small step to improve UI, we can:

1. Pop out a balloon / tooltip notifying user that something unusual happened, like this one.

2. Flash the tray icon when feeding data back to browser, to give user a sense that Lantern is working. 

It does require a few code changes across components though.

**Comment by myleshorton** [comment]
Interesting thanks @fffw. I wonder if this is users who don't have admin privileges?

**Comment by myleshorton** [comment]
If so we could just handle that in the installer.

**Comment by fffw** [comment]
Unfortunately it's not, as lots of Loggly messages have user name "Administrator". The most possible reason is AV software I think.

By searching "fork/exec" in go source code, the error is triggered [here](https://github.com/golang/go/blob/release-branch.go1.4/src/os/exec_posix.go#L47), but it's not useful at all.

**Comment by myleshorton** [comment]
Hmn..thanks @fffw. Can you play around with installing a few AV tools to see if you can reproduce it?

**Comment by fffw** [comment]
Below is the prompt when Lantern installer is detected and removed by AV software 360safe. The text is exactly the description of E_ACCESSDENIED. `pac-cmd.exe` doesn't trigger this though.

![image](https://cloud.githubusercontent.com/assets/10410437/9697519/2fea97f0-53c3-11e5-8b6b-fd14c87dd770.png)

**Comment by fffw** [comment]
Seen similar entries from one user's log. User intentionally disabled PAC ability.

> Jan 10 03:45:27.556 - 0m0s ERROR flashlight: pac.go:163 Unable to set lantern as system proxy: Unable to execute C:\Users\<masked>\AppData\Roaming\byteexec\pac-cmd.exe: fork/exec C:\Users\<masked>\AppData\Roaming\byteexec\pac-cmd.exe: This program is blocked by group policy. For more information, contact your system administrator.

I suspect if the errors here are due to same reason.

**Comment by myleshorton** [comment]
Also see user report in #3833

**Comment by myleshorton** [comment]
See also #3883

**Comment by oxtoacart** [comment]
So with this bug, are we aiming to try and get pac-cmd to always work, or should we aim to warn the user appropriately if it doesn't?

**Comment by oxtoacart** [comment]
I'd vote for warning the user, since we can't prevent all situations in which it breaks (for example the group policy thing that @fffw reported).

**Comment by myleshorton** [comment]
I think the first step is to try to get a better feeling for why and when it doesn't work. If it's fixable, we should fix it. If it isn't, or if we just can't figure it out, then we can warn the user.

**Comment by myleshorton** [comment]
No longer used!
