### ISSUE TITLE
Lantern doesn't start on Mac OS 10.7

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2913]
Reported by one user named Aref Khandan on Facebook. He downloaded directly from website and installed correctly, but didn't see anything. No tray icon, no starting page. There's even no `lantern.log`.

We didn't explicitly state the minimum version required on website, but from previous mail, it should be 10.7 and above.

**Comment by oxtoacart** [comment]
We no longer support versions of OS X below 10.8, closing.
