### ISSUE TITLE
2.0 Beta8 aways use more than 4% cpu time

### ISSUE THREAD

**Issue by fishg** [getlantern/lantern#2918]
<img width="365" alt="qq20150811-1 2x" src="https://cloud.githubusercontent.com/assets/1423545/9192810/d476ab2e-4040-11e5-8afe-897330e80b42.png">

Because of temperature,when use OS X,cpu usage is sensitive.Hope there is some way to reduce lantern cpu usage.

**Comment by myleshorton** [comment]
Honestly the seems like very reasonable CPU use. Do other tools use less?

**Comment by fishg** [comment]
<img width="515" alt="qq20150814-1 2x" src="https://cloud.githubusercontent.com/assets/1423545/9265968/7a7a09ca-426d-11e5-9142-b13c3d9f2b3a.png">
Yes,Shadowsocks client cpu usage is lower even use global proxy model.

**Comment by myleshorton** [comment]
OK thanks @fishg. If we get more users mentioning this as a problem we'll look at optimizing it, but 4% CPU to me seems pretty reasonable honestly, and right now you're the only one who has mentioned it. I don't mean to dismiss it but more just mean to explain our process -- we have other issues that are higher priority (particularly getting Lantern running on Android, which thousands of users are requesting!) that mean we won't get to this right away.

**Comment by fishg** [comment]
@myleshorton Fine.Maybe I use MacBook and Windows Pad,care battery time more.

**Comment by myleshorton** [comment]
Honestly 4% CPU use should have relatively little effect on your battery.
Your screen will be much more.

On Fri, Aug 14, 2015 at 7:55 PM, fishg <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Fine.Maybe I use MacBook
> and Windows Pad,care battery time more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2918#issuecomment-131282096>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
