### ISSUE TITLE
Timeout while waiting for the update-server to generate a patch

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#2924]
This happens the first time a patch from version X to version Y is generated. bsdiff takes a while generating the patch (more than 10s) and the Lantern client gives up waiting.

This does not represent a critical problem: the second client that request the patch will use the one that was generated (but missed) by the first client, and the first client will try again after some hours.

**Comment by myleshorton** [comment]
This is basically just a matter of bumping up the timeout on the client side right? Might as well just bump it to 30 and close it out I would say.

**Comment by myleshorton** [comment]
I believe this one is all set right @xiam?

**Comment by myleshorton** [comment]
Just checking on this again @xiam

**Comment by xiam** [comment]
Yes, this was already fixed, thanks for the reminder @myleshorton!
