### ISSUE TITLE
Use idletiming in chained dialer

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2927]
Fronted dialer [uses `enproxy.Dial`](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/fronted/dialer.go#L169) which [returns `idletiming.Conn`](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/enproxy/conn_impl.go#L44), but chained dialer [didn't do it](https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/chained.go#L99).

It may be the cause of those CLOSE_WAIT connections to chained server. Server can close an connection by some reason, but without sending/receiving data, Lantern client will not notice it, hence leaves connection in CLOSE_WAIT state.

**Comment by myleshorton** [comment]
Yeah great catch @fffw!
