### ISSUE TITLE
Access to the Chinese site is sometimes not normal

### ISSUE THREAD

**Issue by DavidSuccess** [getlantern/lantern#2932]
Sometimes  access to the Chinese site is not normal，for example loading images or visiting weibo are extreme  slow.When I quit lantern the connection's speed is normal.(I am in China)

**Comment by fffw** [comment]
Yes occasionally if a non-blocked site is relatively slow, Lantern will try to proxy it to make it worse! We are actively working on it. Thanks for reporting!

**Comment by myleshorton** [comment]
Closing @DavidSuccess, as this will be fixed with new changes in that area (covered by other tickets). Thanks again for reporting it!
