### ISSUE TITLE
what's going on JP server?

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#2933]
Lantern began to connected EU server other than JP server since this morning in China
The connection speed extreme slow.

**Comment by jxmlhdf** [comment]
It is doubt that GFW began to interfered Lantern JP server results in Lantern connect EU server instantly . The connection speed now is extreme slowly

**Comment by fffw** [comment]
Let's just keep https://github.com/getlantern/lantern/issues/2931 and close this one.
