### ISSUE TITLE
Bad response status for read: 418 I'm a teapot

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#2939]
```
{"extra":{"country":"IR","language":"fa","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","timeZone":"IRDT","version":"2.0.0-beta8 (20150719.133131)"},"fullMessage":"ERROR flashlight.client: reverseproxy.go:186 http: proxy error: Dest: nfjbcdqbwdm:80 ProxyHost: Unable to issue write request: Bad response status for read: 418 I'm a teapot\n","hostname":"hidden","instanceid":"00ff9a758bbf","locationInfo":"ERROR flashlight.client","message":"Bad response status for read: 418 I'm a teapot","timestamp":1439483291878}
```

**Comment by myleshorton** [comment]
Thanks @uaalto. These all mean that our server was unable to resolve the domain name in DNS, so it's either Chrome doing its weird probes or the user actually entering a domain that doesn't exist. Looking at the logs for 2.0.0+stable, there doesn't appear to be anything that should actually resolve.

**Comment by uaalto** [comment]
Oh, thank you. I actually was reading your and @xiam's related conversation, but I thought it was a temporary test or something. Should we ignore these from now on? Anyway, it would come up all the time in support reports, so keeping it as a closed issue avoids it.

**Comment by myleshorton** [comment]
Yeah I think we can just ignore them going forward, but good to have the
documentation here.

On Thu, Aug 13, 2015 at 10:37 AM, Ulysses Aalto <notifications@github.com>
wrote:

> Oh, thank you. I actually was reading your and @xiam
> <https://github.com/xiam>'s related conversation, but I thought it was a
> temporary test or something. Should we ignore these from now on? Anyway, it
> would come up all the time in support reports, so keeping it as a closed
> issue avoids it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2939#issuecomment-130773358>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
With the pac file template updates days before, traffic to host like
`nfjbcdqbwdm:80`
will never be sent to Lantern. Hopefully it will reduce this type of error.

**Comment by myleshorton** [comment]
Great @fffw!

On Thu, Aug 13, 2015 at 8:40 PM, fffw <notifications@github.com> wrote:

> With the pac file template updates days before, traffic to host like
> `nfjbcdqbwdm:80`
> will never be sent to Lantern. Hopefully it will reduce this type of error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2939#issuecomment-130952188>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
