### ISSUE TITLE
如何在局域网中共享LANTERN来翻墙？

### ISSUE THREAD

**Issue by luckypoem** [getlantern/lantern#2940]
这里的局域网是指无线局域网，我想让我的智能手机利用电脑上的LANTERN来翻墙。我搞了一下，未成功。项目作者可否写篇WIKI文章，详细说明一下？
非常感谢！
PS:我在电脑上利用LANTERN来翻墙，没任何问题。

**Comment by XhstormR** [comment]
最好说英文

**Comment by fffw** [comment]
@luckypoem Your method is useful but somewhat limited because it requires
computer to keep running. We are working on Lantern mobile which is a
general circumvention tool on Android (iOS later), please stay tuned.

**Comment by luckypoem** [comment]
@fffw,actually I didn't succeed at all in this way.to keep the pc running is no problem for me,bcoz my mobile phone is in wireless lan.so can u write a wiki page explaining how to use lantern on pc for mobile phone to cross the gfw?

**Comment by daerdai** [comment]
我在局域网共享成功了，先运行lantern，用win+r运行%AppData%Lantern来找到.yaml的配置文件，用记事本打开，查找127.0.0.1（一共两处）修改第一处的为0.0.0.0。保存后，退出lantern。然后再重新运行lantern。现在局域网共享成功了。手机，平板或其他pc都可以通过配置来上网了！
具体配置方法：就是将手机连接同一局域网中的Wi-Fi，将代理设置改为手动，服务器地址改为你运行lantern的电脑的IP地址，端口为8787。done！！！，

enjoy！！！

**Comment by czmecho** [comment]
@daerdai 非常感谢~

**Comment by daerdai** [comment]
@czmecho 不客气，好东西大家一起分享！有问题希望大家一起探讨解决

**Comment by luckypoem** [comment]
hi.
我用win+r运行%AppData%Lantern出错，应为%AppData%\Lantern,不过打开了这个目录，我的为
C:\Users\Administrator\AppData\Roaming\Lantern\,未找到扩展名为.yaml的配置文件，怎么回事？
它是隐藏的文件？
谢谢。

**Comment by yasteora** [comment]
@daerdai 这是吧这台PC当作http 代理服务器来使用吧，我看到有lantern deb包 我想如果用Raspberry运行lantern  并且按照你的办法将其作为代理服务器使用或许也可以，而且不会改变原有网络结构。不过树莓派本身没有网口，不知道能不能移植到openwrt上面跑呢

**Comment by daerdai** [comment]
@luckypoem不好意思，写的时候没注意，少了\。关于你的问题，我还没遇到，你打开的文件夹里有哪些文件呢？

**Comment by daerdai** [comment]
@yasteora Hi，感谢你的提问，不过你说的方法，我还没尝试过，你可以自己尝试一下，如果可以的话，将教程与经验分享到这里来，让大家学习学习！谢谢！

**Comment by dac6acc4f** [comment]
I'm using OS X, and I couldn't find that yaml file. Anyone knows the location of that config file? Thanks. I'm using lantern 2.0.

**Comment by myleshorton** [comment]
~/Library/Application Support/Lantern/lantern-2.0.1.yaml

**Comment by Norra123** [comment]
@daerdai thank you so much !!!

**Comment by yasteora** [comment]
@daerdai 如果设置为代理服务器似乎  把 配置文件里的 addr 哪项 “127.0.0.1”改为“0.0.0.0 ”似乎是不行的，似乎设置为本机局域网IP地址 才可行。

**Comment by luckypoem** [comment]
@daerdai ,终于知道什么原因了，原来我用的是较老的1.5.7版，根本没有YAML文件。卸载后，安装最新版，就有YAML文件了，刚装好后，我看到的YAML文件为lantern-2.0.0-beta8.yaml，第二天后，发现多出现了一个lantern-2.0.1.yaml文件，这个文件也需要修改。

**Comment by ZJsnowman** [comment]
@luckypoem 不用，只用改最新的那个就可以了

**Comment by zruibin** [comment]
nice, very good!!!

**Comment by AnimaSting** [comment]
@daerdai but every time I reopened the YAML file, I would find the ip changed to 127.0.0.1 again....

**Comment by moonwater** [comment]
windows下已經清楚了.請問在linux下怎麼處理呢, 似乎沒有這樣的文件. 假設機器是 linux使用的是Ubuntu.

**Comment by fffw** [comment]
@moonwater It's under `~/.lantern`

**Comment by luckypoem** [comment]
@AnimaSting 
是的，每当你重启lantern,那个lantern-2.0.10.yaml里的2处0.0.0.0又变回了127.0.0.1，我试图把lantern-2.0.10.yaml设为只读属性，但是之后打开lantern.exe,lantern会退出（直接罢工了），只好去掉只读属性，这样启动lantern后，lantern才不会退出，不过lantern-2.0.10.yaml里的2处0.0.0.0又变回了127.0.0.1，所以如果想共享lantern给无线局域网里的设备使用的话，就必须在电脑中启动lantern后，每次都修改lantern-2.0.10.yaml里的2处127.0.0.1为0.0.0.0，且不要把lantern-2.0.10.yaml设为只读属性！

@daerdai ，“服务器地址改为你运行lantern的电脑的IP地址”应该写成“服务器地址改为你运行lantern的电脑在无线局域网中的IP地址”，免得让人误以为设为电脑的公网IP地址。

**Comment by luckypoem** [comment]
@myleshorton 
yudeMacBook-Air:contents write$ cat ~/Library/Application Support/Lantern/lantern-2.0.1.yaml
cat: /Users/yuming/Library/Application: No such file or directory
cat: Support/Lantern/lantern-2.0.1.yaml: No such file or directory
yudeMacBook-Air:contents brite$ cat ~/Library/Application Support/Lantern/lantern-2.0.10.yaml
cat: /Users/yuming/Library/Application: No such file or directory
cat: Support/Lantern/lantern-2.0.10.yaml: No such file or directory
yudeMacBook-Air:contents brite$

so where is the yaml file?in windows,i'm successful;in mac,not yet

**Comment by fffw** [comment]
@luckypoem Please escape the whitespace in folder. `ls ~/Library/Application\ Support/Lantern/`

**Comment by luckypoem** [comment]
@fffw
tks a lot.now i can cross gfw by using my mac as the proxy server

**Comment by lzlun129** [comment]
@daerdai @myleshorton Thx a lot!

**Comment by kashu** [comment]
I have been using Lantern for half a year.
This startup method always works for my Xubuntu 14.04.3.
```
/usr/bin/nohup sh -c "/bin/sleep 8 && /usr/lib/lantern/lantern.sh -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null
```
![](http://ww1.sinaimg.cn/large/9c4ddab1gw1f14xguqpk6j20qw0d17aq.jpg)

**Comment by kashu** [comment]
像我的笔记本电脑，配合这个脚本使用，爽YY
https://github.com/kashu/ap.sh

你懂的

**Comment by iliul** [comment]
@kashu 赞，笔记本做热点，手机，iPad都可以畅享网络喽～

**Comment by Babesun** [comment]
It does'nt work with the latest version 2.1.1. I can't find the IP address 127.0.0.1 in the lantern-2.1.1.yaml.

**Comment by Babesun** [comment]
Got it! You can add the string -addr 0.0.0.0:8787 to the TARGET of Lantern's shortcut, then restart Lantern. It will work!

**Comment by fffw** [comment]
We removed `addr` field from cloud yaml for sound reason. The only approach to share Lantern in LAN is to supply command line option as @Babesun described.

@myleshorton @oxtoacart Do we want to reintroduce it in `settings.yaml`, though only geeky user will benefit from it?

**Comment by kashu** [comment]
In my opinion, if reintroduce the addr field in settings.yaml, I think it will significant increase the network traffic of the Lantern and more load heavier.

**Comment by oxtoacart** [comment]
@fffw @kashu I think it's a good idea to let users control the addr through settings.yaml.  However, that's not what we used to have, it used to be in the lantern.yaml that could get updated from the cloud (including the addr).

To make this more user-friendly, we should include a field on the settings screen of the UI to let users change this address without having to manually edit settings.yaml.

**Comment by kashu** [comment]
@oxtoacart  I have a suggestion, could you add the sha256sum value behind the download link?

```
$ sha256sum lantern-installer-beta-64-bit.deb
d41a6eea3950a68d47a27dbdc240df3fb88e9bab7814efaaa2158d711351988b  lantern-installer-beta-64-bit.deb
```

**Comment by oxtoacart** [comment]
@kashu I opened #3925 for your request.

**Comment by joshatt** [comment]
@iliul  笔记本做了热点了, 但lantern没参与进来啊

**Comment by myleshorton** [comment]
The issue of allowing users to set whether to run on localhost versus the local network is logged at https://github.com/getlantern/lantern/issues/3290

**Comment by cousin1994** [comment]
I add the string -addr 0.0.0.0:8787 to the TARGET of Lantern's shortcut, then restart Lantern. It can't work,I change -addr 127.0.0.1:8787 I will work on computer but can't work on phone

**Comment by buzhiyun** [comment]
@cousin1994  change " -addr 0.0.0.0:8787"  to  "-addr [your ip address]:8787" ,  e.g.   -addr 192.168.11.22:8787  , then restart Lantern , It will work on your computer and your phone

**Comment by joshatt** [comment]
@buzhiyun  
>... e.g. -addr 192.168.11.22:8787 , then restart Lantern...
I tried but it does not work. My cell browser checked and said: proxy connecion failed.

**Comment by buzhiyun** [comment]
@joshatt Check your Lantern listening port 8787 , run  "netstat -ano| findstr 8787" on your command prompt . If  you can find   "TCP  192.168.0.100:8787  0.0.0.0:0  LISTENING" and your ip address is 192.168.0.100 , maybe your should check your firewall setting for port 8787.

**Comment by joshatt** [comment]
@buzhiyun Thanks, I can find "TCP 192.168.0.100:8787 0.0.0.0:0 LISTENING", and firewall of my Win7 is always OFF.

**Comment by spfa** [comment]
in my case it works " -addr [my local IP address]:8787";
run netstat returns more than 30 lines, bur every of them starts from "TCP 127.0.0.1:xxxx"

**Comment by butlerL** [comment]
in command line:
/Applications/Lantern.app/Contents/MacOS/lantern -addr=0.0.0.0:8787

**Comment by oxtoacart** [comment]
#3290 covers what needs to be done to make this easier for users, closing this ticket.

**Comment by smileblue** [comment]
不知道怎么用lantern,有谁会呀，上面的我有些看不懂，，，电脑糊涂虫我是个

**Comment by zhuziyi1989** [comment]
如果一打开lantern，请先关闭，然后在terminal里执行以下命令： 
`/Applications/Lantern.app/Contents/MacOS/lantern -addr=0.0.0.0:8787
`
并保持terminal窗口运行,仅适用于Mac吧...

**Comment by hsyan2008** [comment]
gentoo下找到/usr/bin/lantern，在最下面的后面加入-addr=0.0.0.0:8787也可以

**Comment by zhuziyi1989** [comment]
windows 下打开lantern，然后打开开启代理的 finder，设备连接finder的抓包代理（就像平时抓包一样，设置HTTP手动代理），也可以作为局域网代理，暂时没明白什么原理。

**Comment by ATcn** [comment]
@zhuziyi1989 好办法。昨晚刷安卓6.0怎么也没绕过开机的网络验证，网上给的IP都不给力，xxnet和lantern的改127.0.0.1为0.0.0.0也是刚刚知道。看到你说finder，顿时乐了，自己天天用的东西倒给忘了，应该是说fiddler吧，抓包工具，本身也是个局域网代理，可以拦截数据，再分发。

**Comment by decemer** [comment]
我这样做之后通过wifi共享做一次中转,(2 wifi),经常断反应慢速度不快
i do that my pc be a router form 2 wifi,but lag speed low

**Comment by VizXu** [comment]
thanks for sharing

**Comment by CharlotteZeng** [comment]
用 privoxy 共享lantern 很容易 我有一篇博文在csdn上 只需要简单几步即可实现

**Comment by iimagineer** [comment]
For mac users, just use this app (在mac可以用这个): https://github.com/iimagineer/Lantern-Share

**Comment by telwenshen** [comment]
吭吭哧哧地试了一下，发现是可以。为后来的、对电脑不够熟、英语也不够好的提供一下上面做法的整理版本。适用win10环境，日期2016-08-25：

> 打开lantern
> 在lantern的快捷方式属性目标栏最后加入字符串“-addr X.X.X.X:8787” 其中X.X.X.X为你的电脑在局域网内的IP，（设置例子：C:\Users\xxxx\AppData\Roaming\Lantern\lantern.exe -addr 192.168.0.100:8787
> Lantern的快捷方式：右键lantern图标“打开文件所在的位置”）
> 确定后，退出lantern。然后再重新运行lantern。现在局域网共享成功了。手机，平板或其他pc都可以通过配置来上网了！
> 具体配置方法：就是将手机连接同一局域网中的Wi-Fi，将代理设置改为手动，服务器地址改为你运行lantern的电脑的IP地址，端口为8787。
> 浏览器安装了switchysharp、switchyomega等插件的应注意插件设置里的代理服务器也应由127.0.0.1改为你的IP地址X.X.X.X，否则插件是失效的。

感谢@luckypoem  @buzhiyun  @Babesun

**Comment by RubberBoy** [comment]
mac下使用：
nohup /Applications/Lantern.app/Contents/MacOS/lantern -addr=0.0.0.0:8787 &!
作为后台独立进程运行，关掉窗口也可以

**Comment by majortian** [comment]
@zhuziyi1989   Is there a way to undo this command? It totally ruined my lantern now I can't visit Google at all...你说的这个mac的办法能取消吗？我在terminal输入之后，lantern完全失效了，更别说手机了。

**Comment by Vic-Wu** [comment]
I post here just to say "thank you"!

**Comment by CeeYang** [comment]
@zhuziyi1989 Thanks very much,It works very well.

**Comment by karasleegithub** [comment]
Does -addr command-line  work with android?

**Comment by nijia909** [comment]
@zhuziyi1989 非常感谢，我发过一个帖子 #2886 来了一个人消遣我，今天找到一篇CSDN 关于fidder的博客，照着操作，成功实现 nexus 6P 7.1.2系统 分享lantern代理 - -十分感谢

**Comment by tuzhao** [comment]
在ubuntu 14.04 LTS中使用 "lantern -addr [本机ip]:[端口]" 命令运行lantern,
在android wifi链接中设置网络代理填入上面的ip和端口,能成功使用.

**Comment by ss1028yy** [comment]
感谢，mark一下

**Comment by Hwatu** [comment]
thanks

**Comment by ThisIsMython** [comment]
这个方法可行，但是我在Linux虚拟机上没有享受到主机的全局代理功能，只能浏览网页。
`打开lantern
在lantern的快捷方式属性目标栏最后加入字符串“-addr X.X.X.X:8787” 其中X.X.X.X为你的电脑在局域网内的IP，（设置例子：C:\Users\xxxx\AppData\Roaming\Lantern\lantern.exe -addr 192.168.0.100:8787
Lantern的快捷方式：右键lantern图标“打开文件所在的位置”）
确定后，退出lantern。然后再重新运行lantern。现在局域网共享成功了。手机，平板或其他pc都可以通过配置来上网了！
具体配置方法：就是将手机连接同一局域网中的Wi-Fi，将代理设置改为手动，服务器地址改为你运行lantern的电脑的IP地址，端口为8787。
浏览器安装了switchysharp、switchyomega等插件的应注意插件设置里的代理服务器也应由127.0.0.1改为你的IP地址X.X.X.X，否则插件是失效的。`

**Comment by ziyezhang** [comment]
我写了一个蓝灯自启动的脚本，不用修改任何配置便能共享局域网

@echo off
title 蓝灯自启动脚本
taskkill /f /t /im lantern.exe
cd /Users/ziye/AppData/Roaming/Lantern
for /f "tokens=4" %%a in ('route print^|findstr 0.0.0.0.*0.0.0.0') do ( 
set IP=%%a
)
echo IP:%IP%  (LAN)
echo port:6508         (LAN)
start lantern.exe --addr %IP%:6508

pause

复制以上内容，在桌面创建txt文件，粘贴之后另存为bat文件
双击启动，打印在控制台的IP和端口，便是当前网络环境下共享在局域网内的IP和端口（手机连接请参考上面的其他内容）
需要注意的是：cd /Users/ziye/AppData/Roaming/Lantern   这一行的目录，应该改为你电脑中蓝灯的安装目录，端口我设置的是6508，事实上是可以自己随意更改的（取值范围：1024以后的任意端口）
