### ISSUE TITLE
Use country and IP headers returned from ordinary flashlight servers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2943]

**Comment by myleshorton** [comment]
Hey @aranhoide you didn't happen to deploy the server side of this yet did you?

**Comment by aranhoide** [comment]
Yes I did.  You asked this in a different ticket (maybe in the PR itself?)

**Comment by myleshorton** [comment]
Oh awesome! Sorry for the duplicate questions. Thanks.
