### ISSUE TITLE
Today,  the connection is bad  for a long time.

### ISSUE THREAD

**Issue by DavidSuccess** [getlantern/lantern#2950]
Today, many times unable to visit the site that are blocked.（such as  google）
Lantern‘s server has been interfered by GFW more violent？
Location: China  
System: Windows 10 professional.

**Comment by jxmlhdf** [comment]
Refer this issue to #2931

**Comment by DavidSuccess** [comment]
ISP ：Chinaunicom
type of the Network：LAN

**Comment by myleshorton** [comment]
Thanks @DavidSuccess. Has Lantern been any better for you since then?

**Comment by DavidSuccess** [comment]
Connection status is stable now,awesome work!

2015-08-26 9:51 GMT+08:00 myleshorton <notifications@github.com>:

**Comment by jxmlhdf** [comment]
I was shocked that the duration between 3rd and 4th comments can be 12 days !

**Comment by myleshorton** [comment]
Hey we've got a lot going on =).
