### ISSUE TITLE
Using lantern via mobile device?

### ISSUE THREAD

**Issue by chaiyanlin** [getlantern/lantern#2954]
Does anybody know how can we using lantern on mobile device like ios or andriod?
Thanks.

**Comment by myleshorton** [comment]
It's not currently supported, but we should have it for Android soon and iOS fairly soon after that. Android should definitely be available sometime this year.

**Comment by myleshorton** [comment]
You can follow this work at https://github.com/getlantern/lantern-mobile

**Comment by chaiyanlin** [comment]
This is awesome! Can't wait!
