### ISSUE TITLE
The beta version seems prevent Slack from connecting.

### ISSUE THREAD

**Issue by hlcfan** [getlantern/lantern#2955]
Version: 2.0.0+stable (20150807.013721)

**Comment by myleshorton** [comment]
THanks @hlcfan. Is this the desktop version of slack or the web page? If the desktop version, how did you configure it? If it's the web page, can you describe more about what happens exactly? What operating system and browser are you using?

**Comment by hlcfan** [comment]
It's the Slack desktop version, I didn't config anything, the new version lantern has no configuration, like proxy list.

OS: OSX 10.10.5

First, you have Slack installed, then you install a lantern, put your laptop into sleep, then wake it up, you'll find your Slack got disconnected and cannot get connected again.

**Comment by fffw** [comment]
So @hicfan the problem you are facing is that Slack can't reconnect via
Lantern when your laptop wake up? Does it work if you quit Slack and open
again? Does Slack web page work in the meantime?

**Comment by hlcfan** [comment]
@fffw It doesn't work if I quit and re-open. The the web version works perfect.
