### ISSUE TITLE
Allow users to configure Lantern to run as local network proxy

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2967]
Would be a minor variation on the existing Pi settings.

**Comment by uaalto** [comment]
Notes:

Most people just want to do this at home through their, PCs or something so may not be running in headless mode.

**Comment by rxpsd3** [comment]
@myleshorton 
Hello! Is there any way to set up gateway and DNS to instead Port which devices do not have proxy option?

**Comment by myleshorton** [comment]
Hi @rxpsd3. The best you can currently do is outlined in the wiki on setting up a headless server:

https://github.com/getlantern/lantern/wiki/Installation%3A-server

In 2.1.0, which is currently in testing, Lantern also includes a SOCKS proxy, so you should be able to hit the SOCKS proxy on 8788 instead of the HTTP proxy on 8787.

**Comment by rxpsd3** [comment]
@myleshorton Hey, thank you for help. This is a bit complicated for me. Do i need to install Linux for Docker enter HEADLESS=true make linux ?

**Comment by myleshorton** [comment]
We can easily make this an option in the UI for a future version @rxpsd3.

Can you tell us more about your use case? What is your device that doesn't have a proxy option? A phone?

**Comment by rxpsd3** [comment]
@myleshorton Ja. Like a tv or game console.

**Comment by myleshorton** [comment]
Oh cool interesting. So you only have access to a command line in that setting right @rxpsd3?

**Comment by rxpsd3** [comment]
@myleshorton That looks like im going evolve to robotiko. How to use commando?
