### ISSUE TITLE
lantern-installer-beta.exe was deleted by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by yoyogis** [getlantern/lantern#2970]
Some description show in Symantec dialog：
Signature：WS.Reputation.1

Malicious: There is strong evidence that this file is untrustworthy.

This file has been seen by fewer than 50 Symantec users.

Symantec has known about this file approximately 2 weeks.

**Comment by oxtoacart** [comment]
@sunshine19090 Do we test new releases with antivirus programs?  If we're succeeding with Symantec now, let's close this.

**Comment by sunshine19090** [comment]
Yes @oxtoacart, I always run both the installer and the executable in virustotal.com and so far I have not seen any problem with Symantec AV. We can close this.
