### ISSUE TITLE
s3.amazonaws.com is blocked 

### ISSUE THREAD

**Issue by tvvocold** [getlantern/lantern#2971]
In China.

**Comment by myleshorton** [comment]
Hmmmn...so it's inaccessible for you. Where did you see those links? Our GitHub links should still work @tvvocold. Do you have access to those?

**Comment by tvvocold** [comment]
In your home page: https://s3.amazonaws.com/lantern/lantern-installer-beta.exe
In Github releases page: https://github.com/getlantern/lantern/releases the download link redirect to s3 too.

**Comment by percyalpha** [comment]
@myleshorton You should use something similar to https://github.com/greatfire/z/raw/master/FreeBrowser.apk rather than using https://github.com/getlantern/lantern/releases/download/untagged-a5e2f4f7d29eda286635/newest.exe
this will be redirected to amazon s3

**Comment by myleshorton** [comment]
Thanks @percyalpha and @tvvocold. We're already doing effectively that. All the Lantern releases are available at

https://github.com/getlantern/lantern-binaries

Although maybe we could make that more obvious.

**Comment by tvvocold** [comment]
Nice job!

**Comment by myleshorton** [comment]
I just updated the README with that link as well. Thanks guys.
