### ISSUE TITLE
How to modify UI backgroud to worldmap if I build lantern binary by myself

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#2984]
How to modify UI backgroud to worldmap if I build lantern binary by myself?
Pls advise how I modify the source code to achieve it? I just want to get a customized binary version.
BTW: I am already  be able to build the normal lantern binary very skillfully.
Thanks!

**Comment by jxmlhdf** [comment]
This is also the question that I have been chasing and asking for, I did not see any drawback to use this geographic map, indeed it is extreme easier looking and contain many details such as speed , IP and so forth. I extremely confused that why would developer removed this map out instead to put some stupid website list over the start page! it is ridiculous. Bring this good feature back !!!!!!!!!!

**Comment by myleshorton** [comment]
Thanks for your feedback @yuan78 and @jxmlhdf! We may add back the option to show the map, or we may show it in the background.
