### ISSUE TITLE
osversion_linux not working on ARM

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2991]
Getting this error running make packages -- will just not build on ARM for now to get 2.0.1 out the door!

```
src/github.com/getlantern/osversion/osversion_linux.go:20: cannot use uts.Release[:] (type []uint8) as type []int8 in argument to int8SliceToString
```

**Comment by uaalto** [comment]
OK. I don't have a Pi at the moment to test it. It seems like a Go API mismatch within different architectures, though.
If we are going to move to Go1.5 ,it could be gone with that.
