### ISSUE TITLE
Improve the abilities to watch 1080P video from youtube

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#2993]

**Comment by DavidSuccess** [comment]
Report：
Previously used Japanese server watch video from youtube . Speed: 1M/s or higher
Now use Netherlands server watch video from youtube. Speed:100~200kb/s

**Comment by suuiii** [comment]
Me too.Very very slow to open google,and now the connection is very unstable,but the occasional fast,just sometime.The Japanese server was quickly and stable.

**Comment by myleshorton** [comment]
What server are you connecting through now?

On Sun, Aug 23, 2015 at 9:19 PM, suuiii <notifications@github.com> wrote:

> Me too.Very very slow to open google,and now the connection is very
> unstable,but the occasional fast,just sometime.The Japanese server was
> quickly and stable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2993#issuecomment-134027848>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by DavidSuccess** [comment]
Today <http://cn.bing.com/dict/search?q=Today&FORM=BDVSP6&mkt=zh-cn> is
<http://cn.bing.com/dict/search?q=is&FORM=BDVSP6&mkt=zh-cn> the
<http://cn.bing.com/dict/search?q=the&FORM=BDVSP6&mkt=zh-cn> American
<http://cn.bing.com/dict/search?q=American&FORM=BDVSP6&mkt=zh-cn> server,and
connection speed is fast.
But another problem :
Chrome <http://cn.bing.com/dict/search?q=Chrome&FORM=BDVSP6&mkt=zh-cn>
cannot <http://cn.bing.com/dict/search?q=You%20cannot&FORM=BDVSP6&mkt=zh-cn>
 use <http://cn.bing.com/dict/search?q=use&FORM=BDVSP6&mkt=zh-cn> the
built-in <http://cn.bing.com/dict/search?q=built-in&FORM=BDVSP6&mkt=zh-cn>(Internet
Explorer,http://127.0.0.1:16823/proxy_on.pac) agent
<http://cn.bing.com/dict/search?q=agent&FORM=BDVSP6&mkt=zh-cn>,
but Internet Explorer could.
If <http://cn.bing.com/dict/search?q=If&FORM=BDVSP6&mkt=zh-cn> the
<http://cn.bing.com/dict/search?q=the&FORM=BDVSP6&mkt=zh-cn> Certificate
Issue <http://cn.bing.com/dict/search?q=Issue&FORM=BDVSP6&mkt=zh-cn>?

2015-08-25 12:46 GMT+08:00 myleshorton <notifications@github.com>:

> What server are you connecting through now?
>

**Comment by DavidSuccess** [comment]
Today is the American server,and connection speed is fast.

But another problem :
Chrome cannot use the built-in(Internet Explorer,http://127.0.0.1:16823/proxy_on.pac) agent,
but Internet Explorer could.
If the Certificate Issue?

**Comment by myleshorton** [comment]
We pretty much are always just doing the best we can with this.

**Comment by DavidSuccess** [comment]
Thank you for your hard work to create a free internet! 😁

2016-03-08 5:43 GMT+08:00 myleshorton <notifications@github.com>:

**Comment by myleshorton** [comment]
You're very welcome @DavidSuccess! Glad it sounds like Lantern is working better for you.
