### ISSUE TITLE
Bring Google CDN server as default effective way speed up lantern

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#2996]

**Comment by myleshorton** [comment]
Google's CDN made much more sense when their plans were cheaper. Now
there's no reason to use them over any other CDN.

**Comment by dac6acc4f** [comment]
@jxmlhdf But I'm afraid that commies are also blocking Google sites in China, and using Google CDN may greatly affect Lantern users in mainland China.

**Comment by myleshorton** [comment]
Right @dac6acc4f -- Google's "CDN" is mostly blocked in China regardless.
