### ISSUE TITLE
How to add a domain which needs proxy go through?

### ISSUE THREAD

**Issue by simodorg** [getlantern/lantern#2997]
In Lantern 2.0, I can't find a setting page to add a domain as usual in the past version.

**Comment by myleshorton** [comment]
Lantern 2.0 auto-detects blocking, so it no longer has a page for adding or removing domains. Please let us know if it doesn't work for you!

**Comment by simodorg** [comment]
@myleshorton But in China, some foreign websites are very slow without proxy although it's not blocked.

**Comment by myleshorton** [comment]
Oh that's interesting @simodorg. So they're not blocked but the GFW just slows them down, is that right? So going through a proxy makes them faster? Is that your understanding too @fffw?

**Comment by simodorg** [comment]
@myleshorton Yes, the GFW slow these websites on purpose.

**Comment by myleshorton** [comment]
Interesting. Do you have any examples of sites that seems to be true for? We can test them.

**Comment by simodorg** [comment]
@myleshorton The network in China is very complex, different provinces different ISP will get different results. For example, AWS and GitHub is quite slow with China Telecom.

**Comment by myleshorton** [comment]
Thanks @simodorg. Are GitHub and AWS faster when going through a proxy?

**Comment by simodorg** [comment]
@myleshorton Yes of course.
