### ISSUE TITLE
Lantern is proxying all sites though "Proxy All traffic" option is disabled

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#2999]
Proxy all traffic option is disabled by default. I checked in geoiptool.com and speedtest.net, proxy address is being displayed. 

Have we added these sites to the default proxy list by any chance? If so, I will close this issue.

**Comment by myleshorton** [comment]
We haven't added them no.

**Comment by myleshorton** [comment]
I'm not able to reproduce this. You might have to hard-refresh on some of those pages to get the browser to truly reload the site. What browser and operating system? Working fine for me on OSX Chrome.

**Comment by sheena3** [comment]
I am using the new build in windows 8.1 - IE 11 & Chrome. I used the fake DNS to block sites and then tried speedtest.net (Proxy all traffic option is disabled). The page is successfully loaded using the proxy. It is the same in OSX and Linux. Should I try some other websites too? Or this is not a reliable test to check this?

**Comment by myleshorton** [comment]
I don't totally understand your setup. So you're using the DNS server to block speedtest.net? And then it still loads when proxy all is not checked? If that's correct, then that's how it's supposed to work. I.e. even without proxy all checked, Lantern should still auto-detect blocking and should load the page. What are you expecting to happen with your test?

**Comment by sheena3** [comment]
Previously whenever I used the fake DNS, I cannot access any sites when
Lantern is not running. When I use Lantern, it will proxy only those sites
that are in the default proxy list. So only after enabling the proxy all
traffic option, it will start loading the speedtes.net site in the previous
releases.

This time around the page is loading even when the option is disabled.  I
actually think that using the fake DNS is just like DNS poisioning and not
IP Blocking. So in that case auto-detect will not work. That is my
understanding. Please correct me if I am wrong.

On Tue, Aug 25, 2015 at 10:10 PM, myleshorton <notifications@github.com>
wrote:

> I don't totally understand your setup. So you're using the DNS server to
> block speedtest.net? And then it still loads when proxy all is not
> checked? If that's correct, then that's how it's supposed to work. I.e.
> even without proxy all checked, Lantern should still auto-detect blocking
> and should load the page. What are you expecting to happen with your test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2999#issuecomment-134665681>
> .
>



-- 
Regards,
Sunshine

**Comment by myleshorton** [comment]
Oh, the change is that detour/auto-detect will now detect and route around that case.

**Comment by sheena3** [comment]
Thanks @myleshorton - FYI: I just checked without using fake DNS. It still
displayed proxy address in speedtest.net but geoiptool.com didn't. And I
found that speedtest.net is added to our default proxy list now =)


Closing this now!


On Tue, Aug 25, 2015 at 10:38 PM, myleshorton <notifications@github.com>
wrote:

> Oh, the change is that detour/auto-detect will now detect and route around
> that case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2999#issuecomment-134672738>
> .
>



-- 
Regards,
Sunshine
