### ISSUE TITLE
Chrome blocked the download of the new installer

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3000]

**Comment by fffw** [comment]
It says "lantern-installer-qa (10).exe is malicious, and Chrome has blocked it." Might related to pac.exe

**Comment by myleshorton** [comment]
Asked more about this in forums at:

https://productforums.google.com/forum/#!topic/webmasters/lznNWFvQ0EQ;context-place=forum/webmasters

**Comment by myleshorton** [comment]
Turns out those previous changes didn't quite do the trick...
