### ISSUE TITLE
Settings icon doesn't work in IE11

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3001]
At least that's what user reports seem to indicate. @sheena3 can you confirm?

**Comment by sheena3** [comment]
It works fine for me @myleshorton . I am able to click on the settings icon and able to change the options too.

**Comment by sheena3** [comment]
Is this in Linux or windows?

**Comment by myleshorton** [comment]
I don't think IE11 runs on Linux does it?

**Comment by sunshine19090** [comment]
Yeah just figured out that IE11 can't run on Linux. Hope this is resolved now. @myleshorton  Shall we close this if we haven't got any other user complaints on this one?

**Comment by myleshorton** [comment]
yeah might as well thanks @sunshine19090!
