### ISSUE TITLE
Manoto build process should not rebuild binaries themselves and should upload signed binaries instead of unsigned

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3007]
The current Manoto build process also rebuilds the binaries themselves. This is problematic because those binaries are slightly different and don't have the same exact data. Instead, the Manoto build should purely take existing binaries and should repackage them.

**Comment by myleshorton** [comment]
Looks like there are actually additional issues here. The binaries that are uploaded to the releases page on GitHub are the **unsigned binaries**. All the binaries that users are actually using are signed, however, which modifies the binary itself at least on OSX and possibly on other platforms as well.

@xiam the diffs between updates are calculated based on the diffs between the binaries on the releases page correct? As far as I can tell at least on OSX the binaries that are actually distributed are different than those, but maybe we're just getting luck with the binary diff not touching the signed part? Not sure.

**Comment by xiam** [comment]
Hey @myleshorton,

> the diffs between updates are calculated based on the diffs between the binaries on the releases page correct? 

That's correct.

> As far as I can tell at least on OSX the binaries that are actually distributed are different than those, but maybe we're just getting luck with the binary diff not touching the signed part? 

That is not supposed to happen, the lantern binary **must be the same** as their uncompressed .bz2 update file. Maybe that was the reason why some Lantern installations were reporting different signatures.

**Comment by myleshorton** [comment]
> That is not supposed to happen, the lantern binary must be the same as their uncompressed .bz2 update file. Maybe that was the reason why some Lantern installations were reporting different signatures.

Right. The binaries we upload, however, are the [unsigned versions](https://github.com/getlantern/lantern/blob/valencia/Makefile#L306), which are different from the [signed versions](https://github.com/getlantern/lantern/blob/valencia/Makefile#L347) because signing changes the binary file itself.

I think basically code signing on OSX is pretty broken, but I'm unclear how our tests for updating from beta 8 to Lantern 2.0.0+stable and 2.0.0+manoto ever worked. Maybe they were downloading the whole binary?

**Comment by xiam** [comment]
The beta8 binaries I uploaded were extracted by hand from published installers, maybe that's the main reason why we didn't catch this bug it in our testing.

**Comment by myleshorton** [comment]
Gotcha. Makes sense.

**Comment by myleshorton** [comment]
I think I found a solution. This [doc](https://developer.apple.com/library/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG402) mentions changes that don't invalidate a signature, including changes to Resources/*.lproj directories in the app bundle. If we move our config file in there, the signature is OK (so the non-Manoto version just removes that file with no additional signing). I'll finalize those changes tomorrow, but they're working so far!

**Comment by xiam** [comment]
Not sure about that, according to this line moving our file will also affect the signature:

> Removing files from .lproj directories inside Contents/Resources will not invalidate the code signature, but adding or changing files will.

**Comment by xiam** [comment]
The main problem is that we are signing a `Lantern.app` directory, right? And the binary inside `Lantern.app/Contents/MacOS` changes after signing it, this signature depends on the contents of the whole `Lantern.app` directory...

Well, if removing a file from the .lproj directory does not alter the signature, we may as well sign a Manoto version with the config file, then remove that file from the .lproj directory and have a non-Manoto version with the same signature.

And, can Lantern read from this directory?

**Comment by myleshorton** [comment]
> The main problem is that we are signing a Lantern.app directory, right? And the binary inside Lantern.app/Contents/MacOS changes after signing it

Yes.

> Well, if removing a file from the .lproj directory does not alter the signature, we may as well sign a Manoto version with the config file, then remove that file from the .lproj directory and have a non-Manoto version with the same signature.

Yeah exactly. That's how my change works. So that solve the problem of making Manoto and non-Manoto the same binary, and that just leaves the problem of using the signed binaries for updates instead of unsigned. I'll just create a separate ticket for that.

> And, can Lantern read from this directory?

Yeah it seems to work no problem.
