### ISSUE TITLE
The SCMP newspaper has 'comments'' that infer this is a "Five Eyes"/NSA program. RSVP

### ISSUE THREAD

**Issue by andruskewicz** [getlantern/lantern#3012]

**Comment by xiam** [comment]
Thanks for the heads up but no, Lantern is not a spy program. Anyone can take a look at the source code of both client and server at our main repository. If you are still unsure you can always browse only HTTPs sites, in which content is encrypted from your computer to the destination server. HTTPs provides good enough security for everyday's communication.
