### ISSUE TITLE
Will lantern ru on Chromebook?

### ISSUE THREAD

**Issue by hellokitty111** [getlantern/lantern#3015]
Now lantern can run on Linux, Mac, Windows. Will it support Chrome OS? Thanks.

**Comment by myleshorton** [comment]
We don't have any current plans to support Chrome OS @hellokitty111, but if enough people want it we'll do it.

**Comment by zhengpenghou** [comment]
If it can run on Chomebook, that would be great.

**Comment by yakir-Yang** [comment]
Hi, the CPU of my Chromebook is RK3288 (ARM Architecture), and I see Lantern already can build the linux-arm binary, so I guess the "lantern_linux_arm" could run on my Chromebook directly (Not sure).

After login in the Chromebook shell, contained the root permissions, and change the "lantern_linux_arm" mode to 777, and then run it manually. But something wrong, the shell remind me that “No such file or directory”
localhost ~ # lantern_linux_arm 
-bash: /usr/bin/lantern_linux_arm: No such file or directory

Can some guys help here, guide me the right way to run "lantern_linux_arm"

**Comment by yakir-Yang** [comment]
Oh. this issue already be closed, I would created a new one.

**Comment by myleshorton** [comment]
We're just super tied up right now with other things @yakir-Yang, but it sounds like you're just typing the path wrong. Maybe ./lantern_linux_arm? You could also try `locate lantern_linux_arm` to see where it is, but you would need to have locate set up, which it probably isn't on Chromebook.

I haven't fiddled much with Chromebooks, but it sounds like you just need to figure out the actual path to the binary. It could be on your Desktop too, which is likely something like cd ~/Desktop (again I have little idea on Chromebooks -- that's a complete guess).

**Comment by yakir-Yang** [comment]
@myleshorton, thanks for your help.  Yeah, I have try to run that binary directly `./lantern_linux_arm`, but the error messages is the same. Hmmm... my Chromebook have contained the `whereis` command , I thought that command would share the same results with `locate`, here are they:
```sh
localhost ~ # whereis lantern_linux_arm
lantern_linux_arm: /usr/bin/lantern_linux_arm
localhost ~ # ls -al /usr/bin/lantern_linux_arm
-rwxr-xr-x 1 root root 8896467 Oct  2 20:58 /usr/bin/lantern_linux_arm
```

Besides, I have created a new issue #3223, if you got free time, wish you could help at here. :)

**Comment by gstone7** [comment]
@yakir-Yang,do you have any plan to build app(like lantern for chrombook)?

**Comment by mmppggxx** [comment]
It is really in need to have chromeOS version Lantern.
I tried Android version on R11, but it doesn't work.

Appreciated for your soon release.
