### ISSUE TITLE
[feature suggest] a chrome extension

### ISSUE THREAD

**Issue by zzz6519003** [getlantern/lantern#3017]
:beers:

**Comment by myleshorton** [comment]
What do you want the extension to do specifically @zzz6519003?

**Comment by celeron533** [comment]
I think SwitchyOmega + Lantern works well.

**Comment by zzz6519003** [comment]
thx man!  can switchproxy works with it too?

2015-08-27 8:57 GMT+08:00 Allen Zhu <notifications@github.com>:

> I think SwitchyOmega + Lantern works well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3017#issuecomment-135222803>
> .
>



-- 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/9510435/90252d3e-4ca6-11e5-8199-70cedd23a314.png)




IE: automatic configuration script


![image](https://cloud.githubusercontent.com/assets/3608762/9510458/d034a4e0-4ca6-11e5-9c72-64e25d0df4af.png)



Although I am using SwitchyOmega now, I remember SwitchProxy supports PAC files, too.


![image](https://cloud.githubusercontent.com/assets/3608762/9510469/01b36a4c-4ca7-11e5-8692-ce0151e2ce05.png)

**Comment by WispZhan** [comment]
use 8787 port.

add Proxy servers,set Protocol = HTTP ,Server = 127.0.0.1 ,Port=8787

**Comment by myleshorton** [comment]
As a first pass on this, let's use the extension as a debugging tool when things seem to go wrong with Lantern. The extension could be helpful in testing what the current proxy settings are, potentially if there's another conflicting extension, could test if Lantern's working at all, if the network is working at all, etc.

**Comment by oxtoacart** [comment]
The first version of this is covered by #4169

**Comment by oxtoacart** [comment]
@myleshorton This seems broader than the extension in the containing Epic.  Shall we close this or at least remove?

**Comment by oxtoacart** [comment]
Superseded by #4169 for now.
