### ISSUE TITLE
Fb manoto page is also opening when running Lantern

### ISSUE THREAD

**Issue by sheena3** [getlantern/lantern#3023]
Is that how it is supposed to work now?

Edit: I checked this in Mac and Linux.

**Comment by myleshorton** [comment]
Basically if you have previously installed the manoto version, it will open the manoto page even if you later install the non-manoto version. To prevent this, you have to delete the .packaged-lantern.yaml file at:

~/Library/Application Support/Lantern
c:/Users/YOUR_USER_NAME/AppData/Roaming/Lantern
~/.lantern

**Comment by sheena3** [comment]
yep that solved the issue. Thanks!
