### ISSUE TITLE
Use new Manoto links always

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3025]
Currently Lantern will use whatever Manoto links are configured in the package, but it won't override old links with new ones that track Lantern traffic. It should.

**Comment by myleshorton** [comment]
Should now open to https://www.facebook.com/manototv/app_128953167177144

**Comment by qcind** [comment]
Lantern  好像出了： 2.0.2 的Source 包，
有大神会编译 windows binary 的文件吗？
谢谢！
