### ISSUE TITLE
Make sure one can build Lantern successfully in a censored environment by using Lantern to circumvent blockages

### ISSUE THREAD

**Issue by maxadjsky** [getlantern/lantern#3026]
when building lantern for linux,there is an error as follows:

curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

my os is openSUSE 13.1,and I have a shadowsocks proxy,but I don't know how to set for building

**Comment by fffw** [comment]
The build process is running inside docker container, so it can't use
SOCKS5 proxies like Shadowsocks on your host. You can use VPN, or, build
Lantern on a VPS.

**Comment by maxadjsky** [comment]
ok,Thanks!

**Comment by yejingchen** [comment]
Personally I think lantern should avoid requiring downloading things from sites that's likely to be censored in some countries or regions. When I build lantern, I have to frequently switch VPN on and off to keep the build process running. And there are people who live in such regions without a way to get access to these sites, thus unable to build lantern (maybe some of them don't use ubuntu so no pre-built binaries for them).

**Comment by fffw** [comment]
@yejingchen You man know that even `golang.org` is blocked in China, and storage.googleapis.com is where go compiler resides. Anyone doing serious Go development in such areas has no way but through circumvention tools.

What interests me is why you need to "frequently switch VPN on and off" to build Lantern.

**Comment by yejingchen** [comment]
I switch VPN on and off because some downloads in a low speed with VPN 
and others unreachable without VPN.

在2015年12月7，上午 9:36，fffw <notifications@github.com> 
写道：

**Comment by oxtoacart** [comment]
I think it would be reasonable for Lantern to be able to build successfully in a censored environment if someone is running Lantern :)

**Comment by myleshorton** [comment]
Closing for now guys -- theoretically SOCKS in recent lanterns should solve this.
