### ISSUE TITLE
[config-server] HTTP 500 error

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3029]
Tens of "Exception with data nil" error printed per second, source should be web.clj#L124

**Comment by myleshorton** [comment]
@aranhoide can you take a look at this ASAP?

**Comment by aranhoide** [comment]
As I've just said in the dev list, this was most probably caused by our hitting quota limits in one of our VPS providers.

**Comment by fffw** [comment]
Error rate kept very low, or even zero, in the past week. Closing
