### ISSUE TITLE
Why did i can't connect to japan sever any more ?

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3037]
Lantern 2.0.0+stable (20150807.013721) 
I  always connected to japan sever until yesterday . Japan works very good on youtube for me , but now
i can only connet to netherlands and it's slow .

**Comment by myleshorton** [comment]
Interesting @zhanxiage233. I think this could be the result of some issues we've had with our configuration server architecture recently. Does that sound possible @aranhoide?

**Comment by jxmlhdf** [comment]
It is likely that the Lantern ignore JP server instead to connect server in other region. It is the one drawback that not provide manual option for user to choose the server

**Comment by fletchere** [comment]
i have the same issue, 2.0.1 can not connect jp sever, so i roll back to 2.0.0.

**Comment by myleshorton** [comment]
Hey @jxmlhdf, @fletchere, and @zhanxiage233 can you send me your logs at myles@getlantern.org? The log locations are described at https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by aranhoide** [comment]
@fletchere can you connect to JP servers with 2.0.0?

**Comment by fletchere** [comment]
@aranhoide occasionally connect to nl servers, but most time connect to jp servers.

**Comment by aranhoide** [comment]
@fletchere: could you please send us your `lantern.yaml`?  That configuration file should be close to where your logs are located (remove the 'logs' or 'Logs' part from the path in the link @myleshorton just sent).  Thanks for your feedback!

**Comment by fletchere** [comment]
@aranhoide which version? 2.0.1 or 2.0.0.

**Comment by aranhoide** [comment]
@fletchere Both would be best, esp. since you say one works for you better than the other one.  Thanks!

**Comment by fletchere** [comment]
@aranhoide @myleshorton i have sent both lantern-2.0.0.log and lantern-2.0.1.log file myles@getlantern.org.

**Comment by myleshorton** [comment]
Belated thanks @fletchere -- we're having a look.

**Comment by myleshorton** [comment]
Should be all set now @fletchere but please re-open if not!
