### ISSUE TITLE
Hope to add a new function

### ISSUE THREAD

**Issue by mikicomo** [getlantern/lantern#3040]
l hope to add a new function that users can force to use proxy on one page.(Don't need to use "proxy all  traffic")
thinks!

**Comment by celeron533** [comment]
If you are using Google Chrome, it is possible to use extension such as ProxySharp or SwitchyOmega to define specific rule.

**Comment by mikicomo** [comment]
@celeron533 l use SwitchyOmega ,but l don't know how to set up.( 127.0.0.1 &&16823  ？ )

**Comment by celeron533** [comment]
@mikicomo Please refer to:
https://github.com/getlantern/lantern/issues/3017#issuecomment-135236332

**Comment by mikicomo** [comment]
@celeron533 thinks !
