### ISSUE TITLE
Create new flashlight server pool in Tokyo

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3041]
For users in China, falling back to Flashlight is really slow.

**Comment by myleshorton** [comment]
I think this one's fairly important @aranhoide.

**Comment by aranhoide** [comment]
We do have a flashlight server pool in Tokyo, and those servers are getting
traffic.  Are Chinese users getting Amsterdam fronted servers?  That would
be an error.  Do we have any `lantern.yaml`s from Chinese users
experiencing this problem?

**Comment by myleshorton** [comment]
Oh sorry I didn't realize that @aranhoide! The embedded defaults point to nl though right? Maybe we could do something basic like detect the locale before our IP lookup and choose the embedded pool based on that. 

We're just getting quite a few reports of Chinese users connecting to NL. Thinking about it more, though, I suspect it's because for some reason they're unable to get the config from the config server and are falling back to the embedded config.

**Comment by aranhoide** [comment]
Yes, many users weren't able to get the embedded config yesterday, because we just run out of servers in Tokyo and the config server crashed trying to assign these users one.

**Comment by myleshorton** [comment]
> Yes, many users weren't able to get the embedded config yesterday, because we just run out of servers in Tokyo and the config server crashed trying to assign these users one.

Gotcha. What do you think about the idea of changing the embedded config based on locale?

**Comment by aranhoide** [comment]
It sounds easier to just have the config-server return a locale-specific "default" config when it errors trying to get a specific fallback for the user.

Then again, the cure may be worse than the disease in the case that our pool of JP servers just can't cope, overall, with the traffic of our Chinese population.  Until we have a good way to handle flashlight server quota overrun we may end up with a prohibitive traffic bill.  (It would have certainly been cheaper to just increase our VPS limit so we serve that traffic included in the monthly bill).  So I think we should implement a flashlight server 'retire' scheme before we channel more traffic into them.

**Comment by myleshorton** [comment]
Makes sense @aranhoide.

**Comment by myleshorton** [comment]
Linode definitely still not accepting new users right? Anyway to automate checks on that?

**Comment by aranhoide** [comment]
No news in

https://blog.linode.com/category/datacenters/

I could implement an automated check and we could probably get some VPSs launched every once in a while, but I don't expect we'll get enough to matter, at our current scale, until they expand the data center.
