### ISSUE TITLE
Russian localization - how to contribute

### ISSUE THREAD

**Issue by voltecrus** [getlantern/lantern#3044]
Hello,

Would like to volunteer to create a Russian localization. Browsed the docs, wasn't able to find instructions on how to contribute.

Any pointers would be helpful!

Thanks.

**Comment by fffw** [comment]
Glad that you want to give a helping hand @voltecrus! You can join the translation project at https://www.transifex.com/otf/lantern/language/ru_RU/. [This short description](https://github.com/getlantern/lantern/wiki/Translating-Lantern) might also be useful.

Will close this issue but feel free to add more comments!
