### ISSUE TITLE
lantern have two 2 processes on windows？

### ISSUE THREAD

**Issue by XhstormR** [getlantern/lantern#3045]
Before，lantern have only one processes. Now, i  notice lantern always have two process.Is that normal?
![01](https://cloud.githubusercontent.com/assets/10527522/9509543/8cf4f9e0-4c93-11e5-88b1-b359302c4893.png)

**Comment by celeron533** [comment]
@XhstormR, I also have two processes on windows 10.
v2.0.1
20150821.200810

**Comment by XhstormR** [comment]
lantern version
![01](https://cloud.githubusercontent.com/assets/10527522/9510159/3197fbe4-4c9b-11e5-8473-dba946989ea4.png)

**Comment by fffw** [comment]
It should not. You can show the executable location of the processes from
Task Manager following [this link](
https://www.raymond.cc/blog/determine-program-path-from-task-manager-for-each-program-in-windows-xp-windows-server-2003/
)

**Comment by XhstormR** [comment]
@fffw They are the same file.
![image](https://cloud.githubusercontent.com/assets/10527522/9512931/7cb60f38-4cbb-11e5-8fa0-9fae230dc502.png)

**Comment by fffw** [comment]
Ha sorry for the misleading. Lantern uses a panic wrapper to capture any
runtime error and exit gracefully. The panic wrapper will fork the process
itself and wait for the child process to exit. It's expected.

**Comment by XhstormR** [comment]
This doesn't seem like a big problem.
