### ISSUE TITLE
Uninstaller doesn't "unset" the IE proxy setting

### ISSUE THREAD

**Issue by mbrownnycnyc** [getlantern/lantern#3046]
The uninstaller doesn't "unset" the IE proxy setting.

Thanks,

Matt

**Comment by fffw** [comment]
Lantern unsets proxy setting when it quits. ["uninstall" section](https://github.com/getlantern/lantern/blob/valencia/installer-resources/windows/lantern.nsi#L125) uses `KillProcess` so Lantern never have a chance to close gracefully. Let's try if `CloseProcess` works.

**Comment by myleshorton** [comment]
Yeah good idea @fffw. I'll make that change for 2.0.2.

**Comment by myleshorton** [comment]
Should be all set.

**Comment by myleshorton** [comment]
@sheena3 we'll just want to make sure Lantern still successfully kills the old Lantern if we install when the old one is still running (windows only!).
