### ISSUE TITLE
Lantern becomes much less stable these 2/3 days

### ISSUE THREAD

**Issue by Centaur** [getlantern/lantern#3052]
Connections are lost randomly. Basically not usable. 
Guess the GFW has taken actions against it. 
Here is some error messages:

```
Lantern could not access the server at t.co.

There was an error accessing the page you are looking for.

    Did you make a mistake when typing the domain? Check the url and try again.
    Are you certain this domain address exists? It’s registration may have expired.
    Are you unable to browse other sites? Check your network connection and DNS server settings.
    Is your computer or network protected by a firewall or proxy? Incorrect settings can interfere with Web browsing.
    Does the error message No dialers left to try on pass 1 mean something to you?
```

**Comment by liugangnhm** [comment]
the same to me.

**Comment by johnwatsondev** [comment]
Me too. Mac version.

**Comment by hxx0215** [comment]
me too.
mac version 2.0.0 can use as past
but 2.0.1 can't

**Comment by myleshorton** [comment]
Hi @liugangnhm @johnwatsondev @Centaur and @hxx0215 we're working on resolving an issue the cropped up over the weekend and should have a fix soon.

**Comment by johnwatsondev** [comment]
@myleshorton Thanks for hard work!  Could you open a donate way for organization of lantern or main maintainer ?  
Thanks for advance!  Looking forward to your reply.

**Comment by fffw** [comment]
Hey @liugangnhm <https://github.com/liugangnhm> @johnwatsondev
<https://github.com/johnwatsondev> @Centaur <https://github.com/Centaur>
 and @hxx0215 <https://github.com/hxx0215> you wanna try 2.0.2 which has
several important fixes on block resistance and stability?

Mac OSX:

https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg
or
https://github.com/getlantern/lantern-binaries/blob/master/lantern-installer-beta.dmg?raw=true


Windows:

https://s3.amazonaws.com/lantern/lantern-installer-beta.exe
or
https://github.com/getlantern/lantern-binaries/blob/master/lantern-installer-beta.exe?raw=true

**Comment by Centaur** [comment]
Upgraded to 2.0.2.  So far so good.  Even have the illusion of a better speed. Looking forward to its long-term performance. Thank you.

**Comment by hxx0215** [comment]
upgraded to 2.0.2 it become more stable thank you

**Comment by myleshorton** [comment]
Thanks guys! Closing this.
