### ISSUE TITLE
what is installer-manoto in lantern's github download page???

### ISSUE THREAD

**Issue by jxmlhdf** [getlantern/lantern#3064]
It is noticed that the lantern download Link in github page has been changed to installer-manoto, which differ from the getlantern.org. What the difference between the version 2.0.1 and installer-manoto.
Many Chinese users has experience poorly connection speed recently when they use latest release.
Can team provide the specific update logs for each update version? 
It will provide clear outline for user to know what has been changed in each version. 
Can team add auto-update feature to new version? 
So the users no need to download latest version by themselves.

**Comment by myleshorton** [comment]
Nothing has been replaced or changed @jxmlhdf -- the manoto installer has been there for many weeks. It is an installer for our partnership with the manoto satellite TV station.

We are working on resolving the issues people are experiencing, although they are unrelated to this version versus the previous.
