### ISSUE TITLE
403 forbidden error in ubuntu 14.04

### ISSUE THREAD

**Issue by dzhwinter** [getlantern/lantern#3069]
First, thanks for this awesome repo!
Am I come encounter the same situation with #2915?
My host repeat 403 error again and again. The return message tell me that there virus or something else in my host.  But it should't be since the host is my develop machine.

version:
Aug 30 15:07:58.887 - 0m0s DEBUG flashlight: flashlight.go:218 ---- flashlight version: 2.0.1, release: 2.0.1, build revision date: 20150821.200810 ----

message:
            <h2 data-translate  what_happened>
            <p>The owner of this website (nl.fallbacks.getiantem.org) has forbidden your access based on malicious activity detected from your computer or your network (219.239.227.253). The most likely cause of this is a virus or malware infection on your machine. Please update your anti-virus software and run a full system scan.</p>
          </div>

end segment:

Aug 30 15:08:00.212 - 0m1s DEBUG enproxy: conn_intf.go:239 Failing on Dest: www.google.com:80    ProxyHost:     Unable to issue write request: Bad response status for read from fronting provider: HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Cache-Control: max-age=15
Cf-Ray: 21e1687853c51eb9-SJC
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Sun, 30 Aug 2015 15:07:55 GMT
Expires: Sun, 30 Aug 2015 15:08:10 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=da9d26b09b87aa3b7d6fb9b10764a02a41440947275; expires=Mon, 29-Aug-16 15:07:55 GMT; path=/; domain=.getiantem.org; HttpOnly
X-Frame-Options: SAMEORIGIN

ubuntu 14.04 desktop 64 bit
But my laptop works very well (window7) in the same vitrual subnet. LOL

**Comment by myleshorton** [comment]
Are you still getting this @dzhwinter? Should be fixed now.

**Comment by dzhwinter** [comment]
is it fix in new release? i will check it. Thanks.
