### ISSUE TITLE
config: not store etag until yaml sucessfully parsed

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3076]
In rare circumstance, config-server returned yaml might be malformed, which triggers below error:

```
Unable to unmarshal YAML for update: YAML error: line 2: mapping values are not allowed in this context
```

As etag already set, successive requests will always 304 not modified, hence leaves the default config unchanged.

**Comment by myleshorton** [comment]
That's a big deal. Let's fix this in 2.0.2 now @fffw. You want to look at this and I'll work on the final remaining Makefile issue?

**Comment by fffw** [comment]
Sure

**Comment by myleshorton** [comment]
We actually want to store the etag when it doesn't successfully parse @fffw because otherwise we'll continually fetch the unparseable config!

**Comment by fffw** [comment]
Oh I see. I totally forgot what ETag expected to do!
