### ISSUE TITLE
lantern can‘t connect any website these days

### ISSUE THREAD

**Issue by vzyw** [getlantern/lantern#3082]
I didn't do anything, lantern just don't work these days.

**Comment by fffw** [comment]
We just fixed several critical issues in 2.0.2. Could you try to see if it
works better for you?

Mac OSX:

https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg
or
https://github.com/getlantern/lantern-binaries/blob/master/lantern-installer-beta.dmg?raw=true


Windows:

https://s3.amazonaws.com/lantern/lantern-installer-beta.exe
or
https://github.com/getlantern/lantern-binaries/blob/master/lantern-installer-beta.exe?raw=true

**Comment by wuyongwen** [comment]
The downloaded files are detected as Trojan horse.

**Comment by myleshorton** [comment]
By what AV software @wuyongwen?

**Comment by wuyongwen** [comment]
360 Total Security @myleshorton  ,i use lantern 2.0.0+stable version,but i can't open google facebook...

**Comment by myleshorton** [comment]
@wuyongwen these issues should be fixed in 2.0.6, although we haven't had a chance to look at the trojan issue yet unfortunately.
