### ISSUE TITLE
302 error in Loggly: == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3088]
I'm not sure what this is about--and the actual message isn't helpful--but it's appearing frequently in Loggly. Here's some of the full output:

{"extra":{"country":"","language":"zh","logLevel":"ERROR","osArch":"386","osName":"windows","osVersion":"","sessionUserAgents":"HTTP Downloader: 1 requests; Xunlei@Http Download: 1 requests; Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E): 17 requests; WinHttpClient: 1 requests; Microsoft-CryptoAPI/6.1: 2 requests; ","timeZone":"CST","version":"2.0.1 (20150821.200810)"},"fullMessage":"ERROR fronted: masquerade.go:169 HTTP error for masquerade www.lostfilm.tv: Head http://www.google.com/humans.txt: Dest: www.google.com:80 ProxyHost: Unable to issue write request: Bad response status for read from fronting provider: HTTP/1.1 302 Moved Temporarily\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nContent-Type: text/html; charset=windows-1251\r\nDate: Wed, 02 Sep 2015 00:41:06 GMT\r\nKeep-Alive: timeout=10\r\nLocation: https://www.lostfilm.tv/\r\nServer: nginx\r\nX-Powered-By: PHP/5.3.27\r\n\r\n8000\r\n\u003c!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\"\u003e\n\u003chtml\u003e\n\u003chead\u003e\n\t\u003ctitle\u003e LostFilm.TV. \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd...","message":"' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n ","osversion":"Windows 7 / Windows Server 2008 R2, SP1","timestamp":1441154467473}

**Comment by myleshorton** [comment]
It looks like this is likely a masquerade that's failing, but we're now printing out the full HTTP response, which is huge, and our stuff is picking out that last analytics thing as the actual message from a much larger response body. So I think really this is the 302 error from a single masquerade.

**Comment by myleshorton** [comment]
I.e. I don't think this really has anything to do with analytics if you look at the full message (unfortunately, since we're still trying to figure out what the hell's going on with analytics!).

**Comment by atavism** [comment]
@myleshorton Ah, I see! Thanks. Looks like this is the same issue as https://github.com/getlantern/lantern/issues/2071 then. If the 302 is due to old masquerade hosts failing, are we not re-generating the config often enough? We disabled automatically doing that with every new build because of how long it takes, right?

**Comment by myleshorton** [comment]
Yeah we probably aren't generating it often enough. I actually aborted generating it before 2.0.2 because it never ended (or at least not within 30 mins) because non of the fallbacks were responsive at all.
