### ISSUE TITLE
Add option to disable certificate verification

### ISSUE THREAD

**Issue by felixphew** [getlantern/lantern#3094]
I am using lantern to attempt to bypass the Checkpoint web filter. This is an extremely anal firewall, accepting traffic on only a few ports and blatantly dropping most traffic it can't sniff. In my lantern.log, all my connections are being dropped. Most of these say simply "EOF" which is expected (Checkpoint dropping the connections) but many are saying "Server's certificate didn't match expected!", which I suspect may have something to do with Checkpoint intercepting these servers' SSL certificates. I was wondering - is there any way to disable verifying these certificates, in order to work out if this is really the issue?

**Comment by myleshorton** [comment]
you could try commenting out this block and compiling again:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/chained.go#L75
