### ISSUE TITLE
Antivirus application "360" detects trojans in installer

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#3096]
Multiple reports of this from users on Windows

**Comment by karanshh1** [comment]
I uploaded the file on to most online scanning sites, and these are the results that I obtained. 

1. https://www.virustotal.com/en/file/d30a3f15db531d3ccf2a654f8f72f04fd2efc64c8683fde08c5ede7c526c4f10/analysis/1444499335/

2. https://www.herdprotect.com/lantern-installer-beta.exe-1b8abcd22c6e2f4558e0824affa418f5c4e1c008.aspx

It seems that it has been tagged as "artemis" by McAfee which means that it is just generic malware detection, implying that it is a false positive. As it is with all false positives, it appears on a few AVs. So I suppose there is not much that can be done about it other than to include warnings that it may show up false positives.

**Comment by oxtoacart** [comment]
@sunshine19090 Another report of antivirus issues.

**Comment by sunshine19090** [comment]
@ox I was unable to contact 360 antivirus regarding this. I don't remember the exact reason now but I think there was no proper info on how to contact the support team. But I was able to get some of the other AV companies to proactively whitelist which are provided in detail in issue #3333. 


Regards,
Sunshine

**Comment by oxtoacart** [comment]
Thanks @sunshine19090!  Looks like there's a customer support email address now - support@360safe.com.  Worth another try?

**Comment by sunshine19090** [comment]
Yep, I will try emailing them tomorrow @oxtoacart. But should I send them 2.2.0 or 2.1.2?

**Comment by oxtoacart** [comment]
I would do 2.1.2.

**Comment by oxtoacart** [comment]
@sunshine19090 Did you mean to close this or the Symantec one?

**Comment by sunshine19090** [comment]
@oxtoacart I didn't mean to close this nor the symantec. Probably I did it by mistake. I guess we could just refer it to 4196 as it is a consolidated one. Another thing is, as posted in the previous comment by the user - McAfee is still showing as Artemis in red to indicate a false positive but I don't think all users can understand that. They probably might think it is red for malware.

**Comment by oxtoacart** [comment]
@sunshine19090 Can you show a screenshot of what you mean about Artemis?

**Comment by sunshine19090** [comment]
Refer to #4196
