### ISSUE TITLE
Document config process

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#3098]

**Comment by oxtoacart** [comment]
@uaalto Is there anything left to do here?

**Comment by uaalto** [comment]
Sorry, I just rediscovered this after looking for assigned issues. It is this PR: https://github.com/getlantern/lantern/pull/3102 which I think is outdated.

**Comment by uaalto** [comment]
@oxtoacart perhaps we can close it or, if the explanations still hold correct, I can very quickly add them to the current devel branch.

**Comment by oxtoacart** [comment]
I think the instructions in #3102 look correct.  @aranhoide do they look right to you?  If so, @uaalto please go ahead and add them to the latest README.

**Comment by aranhoide** [comment]
@oxtoacart @uaalto those instructions were probably correct at some point, but some parts of them are out of date.  I've added inline comments in that PR.

**Comment by uaalto** [comment]
We closed the PR.
