### ISSUE TITLE
Hello, I found another problem that after Lantern 2.0.2 had been running for several hours, the speed of loading webpages through Lantern proxy became very slow.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3099]
Hello, I found another problem that after Lantern 2.0.2 had been running for several hours, the speed of loading webpages through Lantern proxy became very slow. I upload my Lantern log file to Google Group Lantern Developers. 
https://groups.google.com/forum/#!topic/lantern-devel/LVpdwlKVulY
The speed of loading webpages through Lantern proxy was so slow that I couldn't log in my Gmail account through Lantern proxy. Could you please help me solve this problem in the next version of Lantern software? Thank you very much for your help. I really appreciate it.

**Comment by fffw** [comment]
@lixiaodongsql Could you try download the new version from repo's home page https://github.com/getlantern/lantern?
