### ISSUE TITLE
OMG! 2.0.2 was slow but 2.0.3 was like disconnect

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3100]
I think it's the special time in my country that make 2.0.2 slow ,but why did 2.0.3 was like disconnect ?
I can't open any site with 2.0.3.

**Comment by fffw** [comment]
@zhanxiage233 Can you send your logs to fffw@getlantern.org so we can take a look? It should be under c:\Users\<username>\AppData\Roaming\Lantern\logs on Windows and ~/Library/Logs/Lantern on Mac.

**Comment by zhanxiage233** [comment]
@fffw I have sent it to you ,please check.

**Comment by fffw** [comment]
Got it. Thanks. Basically it's a 3rd service Lantern relies on stopped
working as expected. Still trying to figure out details.

**Comment by fletchere** [comment]
hei, guys, where to download the 2.0.3 binary installer?

**Comment by myleshorton** [comment]
@fletchere and @zhanxiage233 2.0.6 should solve all of this. Please give it a try!
