### ISSUE TITLE
Emergency! Lantern 2.2 is martyred in west korea aka china!

### ISSUE THREAD

**Issue by pengfei24** [getlantern/lantern#3101]
Emergency! West korea aka china is crackdowns on all services related to access outside websites, we can't search and find any useful information on chinese websites because of the "ruling the country by shit law" of communist party. Most of the VPNs has martyred, now they try to use parade and block outside information brainwash all people of the country, the only saviour of chinese people is lantern and Github, please help us fuck GFW! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Please!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pengfei24** [comment]
My fault, the version is 2.0.2.

**Comment by myleshorton** [comment]
2.0.6 should work for you @pengfei24! Please let us know if it gives you problems and thanks for your patience.
