### ISSUE TITLE
Hello, Lantern 2.0.3 can't work in my network environment. I am a Lantern user in China.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3103]
Hello, Lantern 2.0.3 can't work in my network environment. I can't access Facebook through Lantern 2.0.3 proxy. I upload Lantern 2.0.3 log file to Google Group Lantern Developers. 
https://groups.google.com/forum/#!topic/lantern-devel/Oo1rswPAN50
Could you please help me solve this problem? Thank you very much for your help. I really appreciate it.

**Comment by superlucky8848** [comment]
Same here, manually update lantern to 2.0.3 today. the local screen shows up, but but no blocked website is accessible(TIME_OUT). However in my case, lantern didn't leave any log.

**Comment by AmyOrchid188** [comment]
Hi there, 
   Are you use lantern in a specific IP which you set for your computer? Could you try set your computer to get IP address automate?

**Comment by superlucky8848** [comment]
Yes, I am at least, but my upper router does not enable DHCP.

**Comment by fffw** [comment]
@lixiaodongsql @superlucky8848 @AmyOrchid188 Could you try download the new version from repo's home page https://github.com/getlantern/lantern?

**Comment by lixiaodongsql** [comment]
Yes. I downloaded Lantern 2.0.6 installation file from the URL below.
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe

**Comment by myleshorton** [comment]
And it's working fine right @lixiaodongsql?

**Comment by lixiaodongsql** [comment]
I can't open any HTTP URLs through Lantern 2.0.6 proxy.

**Comment by handelxh** [comment]
mac os ,in china , work well~~ Lantern 2.0.6 beta 5

**Comment by AmyOrchid188** [comment]
Win7 os in china, work well ~~ Latern 2.0.6
