### ISSUE TITLE
wish lantern developer go on shadowsocks maintenance

### ISSUE THREAD

**Issue by wangxj-nemo** [getlantern/lantern#3108]
shadowsocks need talented developr such as lantern's to go on maintain.

**Comment by myleshorton** [comment]
What's the most active shadowsocks repository at this point @wangxj-nemo? Do you know?

**Comment by oldk1331** [comment]
@myleshorton  There are a few backups for shadowsocks: https://github.com/Long-live-shadowsocks https://github.com/shadowsocks-backup https://github.com/FuckUpGFW

But according to [GitHub repo search](https://github.com/search?o=desc&q=shadowsocks&ref=searchresults&s=updated&type=Repositories&utf8=%E2%9C%93), seems no active repo at the time.

However, https://github.com/v2ray/v2ray-core with a description of "Building blocks for developing proxy servers in golang", and claims "compatible with shadowsocks and goagent" (to be done in 2016.01) and "modular design". It has 100 commits in 10 days. The author claims that he is not in China (has immigrated), and "disgusted by the force removel of shadowsocks and goagent, something has to be done". He can be contacted with love@v2ray.com .
