### ISSUE TITLE
Please Please have a look ！ I fixed the problem of lantern in china !

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3111]
Just need replace the lantern.yaml ，and you will fix the problem

**Comment by zhanxiage233** [comment]
@myleshorton

**Comment by zhanxiage233** [comment]
lantern 2.0.2 
 replace a lantern.yaml about 178kb

**Comment by zhanxiage233** [comment]
With a lantern.yaml about 314kb , I can only connect to NL sever and it was slow like disconnected .
After replace another lantern.yaml , lantern works very good and connect to JP sever

**Comment by fffw** [comment]
It seems that you replaced lantern.yaml with an old one which contains customized chained server. Thanks for your feedback! We also noticed it and will add it to next release.

**Comment by zhanxiage233** [comment]
@fffw  ok！just want you know this.

**Comment by jm0477** [comment]
Thanks, but where can i find the lantern.yaml that you've updated ?

**Comment by zhanxiage233** [comment]
@jm0477  sorry, I didn't upload anything . I just want they know this to help fix the problem.

**Comment by myleshorton** [comment]
Yes thanks @zhanxiage233! We actually just added an automated version of that, and as @fffw said it will go out with Lantern 2.0.4.

**Comment by jm0477** [comment]
Guys, thanks for your update, waiting for your next great version of Lantern 2.0.4 :)

**Comment by fishg** [comment]
...replace with which file?!

**Comment by zbww** [comment]
Where is the file？Could you please share it with us via pan.baidu.com?

**Comment by myleshorton** [comment]
This process is all automated in Lantern 2.0.6 @zbww, @fishg, @jm0477, and @zhanxiage233. Please let us know if it gives you issues, although we're already aware of the issue with HTTP sites (#3147)!
