### ISSUE TITLE
Add X-Forwarded-For header to GiveModeProxy and/or ATS

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3112]
We actually really need this for your initial IP address lookup. You said this was working in ATS right @fffw? Maybe we can just switch to ATS now? This actually bumps up the priority of that task @aranhoide probably even over the CloudFront stuff.

**Comment by fffw** [comment]
Yes. ATS will add X-Forwarded-For header for *plain HTTP* requests if configured. I tried visiting geo.getiantem.org via ATS and got correct location.

**Comment by myleshorton** [comment]
Ok and ATS is configured so all incoming traffic is always SSL right? I.e.
those HTTP requests will always be wrapped in SSL correct?

**Comment by fffw** [comment]
Yes the tunnel is always wrapped in SSL and terminated at ATS. But the
tunnelled traffic can be either HTTP or HTTPS (CONNECT request). ATS is
unable to add any header for the latter. So only HTTP request to geoserver,
config server, etc., can have the X-Forwarded-For header added.

**Comment by myleshorton** [comment]
OK cool that should work thanks @fffw!
