### ISSUE TITLE
Lantern 2.0.4 on linux doesn't start correctly 

### ISSUE THREAD

**Issue by jlamiel** [getlantern/lantern#3118]
Just try the lastet release and got blocked, previously i had the 2.0.2 installed 

DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app

(lantern:6412): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2:16: Theming engine 'adwaita' not found

(lantern:6412): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1443:2: Missing name of pseudo-class
DEBUG flashlight.logging: logging.go:50 Placing logs in /home/xxxxx/.lantern/logs
Sep 10 01:44:24.889 - 0m0s DEBUG i18n: translate.go:106 Setting locale fr_FR
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight: flashlight.go:222 ---- flashlight version: 2.0.4, release: 2.0.4, build revision date: 20150909.202918 ----
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:300 Using config dir /home/xxxxx/.lantern
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:122 Checking config path: /home/xxxxx/.lantern/lantern-2.0.4.yaml
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:85 File does not exist at /home/xxxxx/.lantern/lantern-2.0.4.yaml
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:122 Checking config path: /home/xxxxx/.lantern/.packaged-lantern.yaml
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:88 File exists at /home/xxxxx/.lantern/.packaged-lantern.yaml
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:97 File name does not match
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:122 Checking config path: /home/xxxxx/.lantern/bin
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:88 File exists at /home/xxxxx/.lantern/bin
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:97 File name does not match
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:122 Checking config path: /home/xxxxx/.lantern/logs
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:88 File exists at /home/xxxxx/.lantern/logs
Sep 10 01:44:24.894 - 0m0s DEBUG flashlight.config: config.go:97 File name does not match
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.config: config.go:378 Adding empty proxiedsites
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.config: config.go:384 Loading default cloud proxiedsites
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.config: config.go:180 Running first run setup
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.client: bootstrap.go:150 Opening externalUrl from: /home/xxxxx/.lantern/bin
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.client: bootstrap.go:103 Opening file at: /home/xxxxx/.lantern/bin/chained.yaml
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.client: bootstrap.go:107 Error reading file open /home/xxxxx/.lantern/bin/chained.yaml: no such file or directory
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.client: bootstrap.go:103 Opening file at: /home/xxxxx/.lantern/.packaged-lantern.yaml
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.client: bootstrap.go:114 Read bytes: startupurl:
Sep 10 01:44:24.895 - 0m0s DEBUG flashlight.config: config.go:191 Bootstrap settings has 0 chained servers

**Comment by fffw** [comment]
Yeah it's definitely a bug of lantern linux installer. Trying to fix it. Thanks @jlamiel !

**Comment by fffw** [comment]
@jlamiel https://github.com/getlantern/lantern/pull/3121 should have fixed this.

**Comment by myleshorton** [comment]
This should be fixed in 2.0.6 (the current main link) @jlamiel -- thanks for the report!
