### ISSUE TITLE
Hello, Lantern 2.0.5 is unstable.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3119]
Hello, thank you very much for developing Lantern 2.0.5 software. After I just installed Lantern 2.0.5 software in my system, Lantern 2.0.5 could work normally. But after a while Lantern 2.0.5 couldn't work. Error accessing page displayed in my browser. My browser showed that Lantern could not access the server at a URL. Currently, Lantern 2.0.5 can work normally again. I uploaded my Lantern log file to Google Group Lantern Developer.
https://groups.google.com/forum/#!topic/lantern-devel/QFvrN8Q4UPs
Could you please help me solve this problem? Thank you so much for your help. I really appreciate it.

**Comment by jxmlhdf** [comment]
where can you download 2.0.5???

**Comment by lixiaodongsql** [comment]
I downloaded the installation file of Lantern 2.0.5 software from the URL below.

https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe

**Comment by myleshorton** [comment]
That link (https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe) now has 2.0.6 @lixiaodongsql, which should fix the issue.
