### ISSUE TITLE
GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#3129]
{"extra":{"country":"","language":"","logLevel":"ERROR","osArch":"amd64","osName":"linux","osVersion":"","sessionUserAgents":"com.google.android.apps.plus/[edited] (Linux; U; Android 6.0; zh_CN; Nexus 5; Build/MPA44I; Cronet/45.0.2454.21) (gzip): 13 requests; com.google.android.youtube/10.28.60(Linux; U; Android 6.0; zh_CN; Nexus 5 Build/MPA44I) Experiment/2 gzip: 2 requests; com.google.android.talk/[edit] (Linux; U; Android 6.0; zh_CN; Nexus 5; Build/MPA44I): 3 requests; Apache-HttpClient/UNAVAILABLE (java 1.4): 16 requests; Android-GmailProvider/[edit] (sw360dp; ?density) (P117T21 IMM76D); gzip: 2 requests; Mozilla/5.0 (ABE, https://noscript.net/abe/wan): 2 requests; Dalvik/2.1.0 (Linux; U; Android 6.0; Nexus 5 Build/MPA44I): 63 requests; GoogleAuth/1.4 (hammerhead MPA44I); gzip: 32 requests; com.mxtech.videoplayer.ad/86: 1 requests; Cakemix/2.3.327.05.35 (hammerhead MPA44I) Google.Drive/2.3.327.05.35 (OS=Android;OSVer=6.0;Manufacturer=LGE;Model=Nexus 5) Mozilla/5.0 (Linux; U; Android 6.0; zh-cn; Nexus 5 Build/MPA44I) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2: 2 requests; Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome): 13 requests; Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; ZTE U960E Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 FacebookADsSDK/4.1.2 (AB/com.innologica.inoreader;AV/3.8.9;BV/136;LC/en_US): 92 requests; AndroidDownloadManager: 2 requests; Dalvik/1.6.0 (Linux; U; Android 4.0.4; ZTE U960E Build/IMM76D): 5 requests; Mozilla/5.0 (Android; Mobile; rv:40.0) Gecko/40.0 Firefox/40.0: 10 requests; Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MPA44I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.117 Mobile Safari/537.36 FacebookADsSDK/4.1.2 (AB/com.innologica.inoreader;AV/3.8.9;BV/136;LC/zh_CN): 24 requests; Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; ZTE U960E Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 (Mobile; afma-sdk-a-v7899000.6587000.1): 1 requests; AndroidDownloadManager/6.0 (Linux; U; Android 6.0; Nexus 5 Build/MPA44I): 12 requests; Android-GData/1.1 (hammerhead MPA44I); gzip: 3 requests; Mozilla 5.0 (Linux; U; Android 6.0; zh_CN; Nexus 5; Build/MPA44I); com.google.android.gms/8102438; FastParser/1.1; People/1.0; (gzip); sync-t: 1 requests; Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D201 Safari/9537.53: 4 requests; NewsWeather/2.4.2 (102607512) (P117T21 IMM76D): 1 requests; curl/7.44.0: 21 requests; Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; ZTE U960E Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30: 68 requests; Android-GCM/1.5 (hammerhead MPA44I): 1 requests; Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0: 706 requests; Android-GData-Contacts/1.3 (hammerhead MPA44I); gzip: 2 requests; Google - Dalvik/2.1.0 (Linux; U; Android 6.0; Nexus 5 Build/MPA44I): 2 requests; Twidere / 0.3.0 (dev 2015-09-03): 41 requests; com.google.android.apps.plus/[edited] (Linux; U; Android 6.0; zh_CN; Nexus 5; Build/MPA44I; Cronet/45.0.2454.21): 8 requests; Android-GmailProvider/55008625 (sw360dp; 480dpi) (hammerhead MPA44I); gzip: 7 requests; Android/com.google.android.gms/8102438 (hammerhead MPA44I); gzip: 12 requests; DroidGuard/8102000 (hammerhead MPA44I); gzip: 1 requests; Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MPA44I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.117 Mobile Safari/537.36 GSA/5.0.16.16.arm: 29 requests; Keep/3.2.354.00 (Linux; Android 6.0; zh-cn; Nexus 5 Build/MPA44I) Google-HTTP-Java-Client/1.16.0-rc (gzip): 1 requests; Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.102 Safari/537.36: 5 requests; unused/0 (P117T21 IMM76D); gzip: 24 requests; Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MPA44I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.117 Mobile Safari/537.36: 12 requests; Mozilla/5.0 BiliDroid/4.4.1: 3 requests; google/hammerhead/hammerhead:6.0/[edited] :user/release-keys:com.google.android.calendar:[edited] Google-HTTP-Java-Client/1.20.0-SNAPSHOT (gzip): 1 requests; unused/0 (hammerhead MPA44I); gzip: 94 requests; Mozilla 5.0 (Linux; U; Android 6.0; zh_CN; Nexus 5; Build/MPA44I); com.google.android.gms/8102438; FastParser/1.1; Drive Android SDK/1.0; (gzip): 2 requests; Crashlytics Android SDK/1.0.1.21: 1 requests; ","timeZone":"CST","version":"2.0.3 (20150904.204516)"},"fullMessage":"ERROR flashlight: pac.go:163 Unable to set lantern as system proxy: Unable to execute /root/.byteexec/pac-cmd: signal: trace/breakpoint trap (core dumped)\n\n(process:10309): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed\n\n\n","hostname":"hidden","instanceid":"c567400a-c659-4251-9855-0ecbbf5473b1","locationInfo":"ERROR flashlight","message":"GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed","osversion":"Gentoo/Linux kernel: 4.2.0-gentoo-r1","timestamp":1441897904394}

**Comment by uaalto** [comment]
Actually, I think this is a poweruser on Gentoo, probably using a local server to proxy all their traffic. The error seems related to something more of a typical Gentoo issue. I've been a Gentoo user for 10+ years, and in my opinion looks very much out of Lantern's responsibility.

**Comment by oldk1331** [comment]
@uaalto Hello, I think that is me: I run "Gentoo/Linux kernel: 4.2.0-gentoo-r1" and use https://github.com/cyfdecyf/cow as a http proxy server to my Nexus 5 on Android 6.0 DP3.

The problem is that I do not use and install gnome so
````
$ gsettings list-recursively org.gnome.system.proxy
No such schema 'org.gnome.system.proxy'
````

Another error before that is "pac-cmd: signal: trace/breakpoint trap (core dumped)", 
Running it under gdb gives:
````
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

(process:2274): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed


Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff6b74adb in g_logv () from /usr/lib64/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff6b74adb in g_logv () from /usr/lib64/libglib-2.0.so.0
#1  0x00007ffff6b74c57 in g_log () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff7b1a19f in ?? () from /usr/lib64/libgio-2.0.so.0
#3  0x00007ffff781e8c3 in ?? () from /usr/lib64/libgobject-2.0.so.0
#4  0x00007ffff78203d5 in g_object_new_valist ()
   from /usr/lib64/libgobject-2.0.so.0
#5  0x00007ffff7820719 in g_object_new () from /usr/lib64/libgobject-2.0.so.0
#6  0x0000000000400a7d in togglePac ()
#7  0x0000000000400ca5 in main ()
````

This seg fault seems like caused by the missing case of unavailable 'org.gnome.system.proxy', in [lantern/src/github.com/getlantern/pac-cmd](https://github.com/getlantern/lantern/tree/ce6b7a2e57a625a0902cbf1b6733e586e01b603d/src/github.com/getlantern/pac-cmd/linux.c#L14), not check the return value of `g_settings_new("org.gnome.system.proxy")`.

**Comment by oldk1331** [comment]
No offense, by the way, is [wiki: Privacy @ Jan 17, 2014](https://github.com/getlantern/lantern/wiki/Privacy/a004552f6a21b6b44fec100c072595388d398d87) still not outdated? I use lantern without ui, is there a command line option to disable "usage data sharing"?

**Comment by oldk1331** [comment]
@uaalto  Maybe it's my bad, I install gsettings-desktop-schemas and this problem goes away. Should close this issue.

**Comment by uaalto** [comment]
Hi @oldk1331. Regarding privacy, that's why I manually edited any personal information. I *think* there is no command line flag for that. We can add that option.
Thank you for your feedback!

**Comment by ustcscgy** [comment]
@uaalto  Thank you, best regard for lantern team.
