### ISSUE TITLE
Why not just make a lantern with different lantern.yamls and let the users choose the lantern.yaml?

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3134]
Technically,i am not a pro .But i think you guys think of the problem as a complex.
My experience was when you use different lantern.yaml,you get different sever.

**Comment by myleshorton** [comment]
That's not entirely the case @zhanxiage233 - basically a different yaml will work **if you were actually able to download a custom yaml with that version*. So the ones that work aren't the specific versions really but rather what you were able to do with those versions.

Basically 2.0.6 just takes care of it though.
