### ISSUE TITLE
Why no any commitments updated since 05Sep to now?

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3144]
Why no any commitments updated since 05Sep to now while tag 2.0.3& 2.04 still published?
Does it make sense?

Current latest commitment is still ce6b7a2 dated 05Sep
What happened to lantern developing team?

**Comment by oldk1331** [comment]
Check https://github.com/getlantern/lantern/tree/release-2.0.1 , just merged 2 hours ago.

**Comment by yuan78** [comment]
@oldk1331  Thanks a lot !
Hence It's OK for me to git clone this branch to build binaries?

**Comment by myleshorton** [comment]
I wouldn't do that just yet @yuan78, and thanks for the accurate information @oldk1331. We're extremely close but not 100% there. Sorry we haven't been communicating very well -- this particular blocking was tricky and a bit unexpected -- had nothing directly to do with the GFW at all. 

I would build when the 2.0.6 tag is final, but just to let you know our process, we will often shift the tag for a given version as we fix things in the QA process. We think the initial 2.0.6 tag will be close to final, but no guarantees!

Should happen within the next day or maybe sooner.
