### ISSUE TITLE
latest lantern cannot visit website: http://www.speedtest.net/, it show "ERR_TOO_MANY_REDIRECTS"

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3147]
latest lantern cannot visit website: http://www.speedtest.net/, it show  errors : "ERR_TOO_MANY_REDIRECTS"

What's the reason?
BTW: I built the binary based your latest code ,the last git log is 30e03f0b6a911cdcadb075441e3b59142101c89f

**Comment by fffw** [comment]
Yeah good finding @yuan78 . Visiting http://www.bbc.co.uk/ has the same result.

Seems ATS doesn't handle 301 or 302 correctly.

**Comment by yuan78** [comment]
@fffw  , yes, same result to http://www.bbc.co.uk/
But 2B11, 2.0.2 found no such issue, FYI
Meanwhile the lates lantern will modify the yaml file, it cause we only connect NL server while I originally can connec JP server. I need edit the yaml to specify the JP fallback chainserver IP, then I can connect JP server, hope you can fix this issue also.

**Comment by fffw** [comment]
It happens when the site redirects https to http. Use www.speedtest.net as an example. When requesting https, it will return `302 Found` with `Location:http://www.speedtest.net`, so browser can fetch the http version instead.

Unfortunately, ATS seems always fetching the https version, so the site returns `302 Found` again and again, causes `ERR_TOO_MANY_REDIRECTS` eventually.

**Comment by fffw** [comment]
@yuan78 Weird, your build should get JP server! Could you try turn on the "Proxy All" option, and download `http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz` directly to see if it gives you JP server correctly?

**Comment by yuan78** [comment]
@fffw  Thanks a lot! It works now, I can connect JP server.
Pls make your efforts to fix ATS issue (ATS doesn't handle 301 or 302 correctly. It show "ERR_TOO_MANY_REDIRECTS" when visit http website)

**Comment by fffw** [comment]
Oh gotcha! The request ATS got is https rather than http. We should tamper with the header somewhere.

Seen from ATS debug log.
```
+++++++++ Incoming Request +++++++++
-- State Machine Id: 29
GET https:///cloud.yaml.gz HTTP/1.1
Host: test-config-server.herokuapp.com
User-Agent: curl/7.43.0
Accept: */*
Proxy-Connection: Keep-Alive
X-Lantern-Auth-Token: 123
Accept-Encoding: gzip
```

**Comment by fffw** [comment]
What confirmed is that Lantern didn't send that `GET https:///cloud.yaml.gz` thing. It's ATS that determines to visit origin server via https. One trick might be to send `CONNECT` in `ReverseProxy` for plain HTTP requests, though that is not standard compatible.

**Comment by myleshorton** [comment]
Where's that ```Host: test-config-server.herokuapp.com``` coming from though @fffw? That seems like some sort of custom build.

**Comment by myleshorton** [comment]
Or is that what the CFR distribution resolves to?

**Comment by fffw** [comment]
@myleshorton It's a dummy server I set to just show http headers, unrelated to this issue.

**Comment by fffw** [comment]
To avoid confusion, below is the ATS debug output. The last line shows that ATS thinks the requested schema is https. Maybe some configuration can alter this behaviour, but didn't find it yet.

```
+++++++++ Incoming Request +++++++++
-- State Machine Id: 927
GET https:/// HTTP/1.1
Host: www.bbc.co.uk
User-Agent: curl/7.43.0
Accept: */*
Proxy-Connection: Keep-Alive
X-Lantern-Auth-Token: 123
Accept-Encoding: gzip

[Sep 15 08:48:06.470] Server {0x2b5ddb8c1700} DEBUG: (http_trans) [DecideCacheLookup] Will do cache lookup.
[Sep 15 08:48:06.470] Server {0x2b5ddb8c1700} DEBUG: (http_seq) [DecideCacheLookup] Will do cache lookup
[Sep 15 08:48:06.470] Server {0x2b5ddb8c1700} DEBUG: (http_trans) Next action SM_ACTION_CACHE_LOOKUP; __null
[Sep 15 08:48:06.470] Server {0x2b5ddb8c1700} DEBUG: (http) [927] State Transition: SM_ACTION_API_POST_REMAP -> SM_ACTION_CACHE_LOOKUP
[Sep 15 08:48:06.470] Server {0x2b5ddb8c1700} DEBUG: (http_seq) [HttpSM::do_cache_lookup_and_read] [927] Issuing cache lookup for URL https://www.bbc.co.uk/
```

**Comment by fffw** [comment]
There're still some edge cases ATS didn't handle correctly. One example is http://lowendbox.com/. When fetching http version via Lantern, it will return 301 with `Location: http://lowendbox.com/`, which causes infinite loop. The site returns 200 for direct connection. HTTPS via Lantern also works.

This is very interesting.

**Comment by fffw** [comment]
Another example, http://sourceforge.net/ !

**Comment by myleshorton** [comment]
Any clue on this one @fffw?

**Comment by fffw** [comment]
Didn't look into the details yet, but I don't expect the affected sites to
be many. Will pick this one once I created the PR of close connection for
mismatched token.

**Comment by fffw** [comment]
Ok, that's because we appended port in the "Host:" HTTP header somewhere and the site doesn't like it. Can verify by this:
```
curl -v sourceforge.net -H "Host: sourceforge.net:80"
```
Without the `-H` option, it will respond 200. Same for "lowendbox.com".

**Comment by myleshorton** [comment]
Oh interesting great find @fffw! I can look at this if you like. I also
really want to fix the issue of using domain fronted connections if
necessary for the config and updates, which I'll probably keep working on
today.

**Comment by fffw** [comment]
It's added by ATS I think @myleshorton. I'm checking
