### ISSUE TITLE
Hello, I can't access any HTTP URLs through Lantern 2.0.6 proxy

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3148]
Hello, thank you very much for developing Lantern 2.0.6 software to help Chinese netizens circumvent China's firewall. I really appreciate it. I can access Google, Facebook, Twitter and all the other HTTPS websites through Lantern 2.0.6 proxy. But I can't access any HTTP URLs through Lantern 2.0.6 proxy. For example, I couldn't open the URL below through Lantern 2.0.6 proxy.
http://www.nytimes.com/2015/09/15/world/europe/europe-migrant-crisis.html?_r=0

My Chrome browser showed " This webpage has a redirect loop    ERR_TOO_MANY_REDIRECTS "

I uploaded my Lantern log file to Google Group Lantern Developer.
https://groups.google.com/forum/#!topic/lantern-devel/-ZLnxFTx2zs

Could you please help me solve this problem? Thank you very much for your help again. I really appreciate it.

**Comment by fffw** [comment]
Thanks @lixiaodongsql. We are investigating. Will close this one and focus on https://github.com/getlantern/lantern/issues/3147 as a few discussions are already there.
