### ISSUE TITLE
no bz2 file generated when build lantern binary

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3153]
no bz2 file generated when build lantern binary, only exe file and linux binary directly generated.
It cause the file size very big, but I use VPS to build lantern, the FTP speed is limited by GFW, hence need small size bz2 file to save the FTP transfer time.
Could you pls modify the makefile to allow bz2 file also generated when build lantern binary?

**Comment by fffw** [comment]
Binaries are intermediate result of Lantern build process. The end product, lantern installers, are compressed and small enough (3~4MB).

@yuan78 It would be easy to add it to Makefile by yourself, or `tar cjvf ...` manually before transferring. It's not a general requirement though.
