### ISSUE TITLE
From China, 2.0.6 not guarantee JP server connection and proxy non-blocked sites  

### ISSUE THREAD

**Issue by Centaur** [getlantern/lantern#3156]
It often connects to NL servers , which is slow. And when this happens it seems proxying all sites even if  "proxy all traffic" is unchecked.

**Comment by fffw** [comment]
It should be assigned JP server if your country is China by checking IP address. Could you send you logs to fffw@getlantern.org so I can check in detail?

Currently a site will be considered as being blocked if it didn't response in 3 seconds, which is too arbitrary. That will be improved soon. It's mostly affected by your network condition and target site, but irrelevant to which server Lantern connected.

**Comment by fffw** [comment]
Thanks @Centaur ! From you logs, Lantern fetched new configuration successfully but didn't apply any changes locally. Investigating...

**Comment by Centaur** [comment]
Possible workaround: It seems work correctly after `rm -rf ~/.lantern` and this directory is not created any more.

**Comment by skytt2006** [comment]
Same problem here, China user, 2.0.2

**Comment by myleshorton** [comment]
@skytt2006 can you try 2.0.6?

**Comment by skytt2006** [comment]
2.0.6 completely does not work, China Telecom
still does not work after install back 2.0.2
