### ISSUE TITLE
Hello, I still can't open several HTTP URLs through Lantern 2.0.6 proxy.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3157]
Hello, currently I can open some HTTP URLs through Lantern 2.0.6 proxy, but I still can't open several HTTP URLs through Lantern 2.0.6 proxy. 
My Chrome browser showed " Could Not Connect
Description: Could not connect to the requested server host. "
I uploaded my Lantern log file to Google Group Lantern Developers.

https://groups.google.com/forum/#!topic/lantern-devel/zAV4AjilB5w

Could you please help me solve this problem? Thank you very much for your help. I really appreciate it.

**Comment by fffw** [comment]
Hey @lixiaodongsql you don't need to create a GitHub issue seeking for help. Posting on forum is enough I think.
