### ISSUE TITLE
ERROR yamlconf: yamlconf.go:260 Custom polling failed: Unable to open gzip reader: gzip: invalid header

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3159]

**Comment by fffw** [comment]
Ok here is what happens:

1. Lantern failed to contact the chained server for whatever reason.
2. Lantern tried to return 502 bad gateway [here](https://github.com/getlantern/lantern/blob/2.0.6/src/github.com/getlantern/flashlight/client/handler.go#L36), but this `respondBadGateway` function returned `200 OK` actually!

```
< HTTP/1.1 200 OK
< Date: Fri, 18 Sep 2015 07:30:42 GMT
< Content-Length: 148
< Content-Type: text/plain; charset=utf-8
<
HTTP/1.1 502 Bad Gateway
Content-Length: 0

* Connection #0 to host localhost left intact
Unable get outgoing proxy connection: Still unable to dial tcp://doesnotexist.com:80 after 3 attempts
```

We can fix this `respondBadGateway` function in `valencia` instead.

**Comment by myleshorton** [comment]
I think this one is actually an issue with trying to use cloudflare from old configs and it failing.
