### ISSUE TITLE
After I hit the control button and F5 button at the same time, I still can't open a HTTP URL through Lantern 2.0.6 proxy.

### ISSUE THREAD

**Issue by lixiaodongsql** [getlantern/lantern#3161]
Hello, after I hit the control button and F5 button at the same time in order to refresh my browser, I still couldn't access a HTTP URL through Lantern 2.0.6 proxy.
I uploaded my Lantern log files to Google Group Lantern Developers.

https://groups.google.com/forum/#!topic/lantern-devel/nxaCjqwaa1M

My Chrome browser still showed " Could Not Connect

Description: Could not connect to the requested server host. "

Could you please help me solve this problem? Thank you very much for your help. I really appreciate it.

**Comment by fffw** [comment]
Hey @lixiaodongsql can you stop creating issues? We saw your post on the forum. Plus, it would be better to reply existing thread than create a new one.

**Comment by lixiaodongsql** [comment]
I am really sorry for creating issues on Github. I apologize to you the most sincerely. Could you forgive me?
