### ISSUE TITLE
can not build lantern using latest docker on mac

### ISSUE THREAD

**Issue by liugangnhm** [getlantern/lantern#3162]
```shell
make darwin
```
get error
```shell
Missing "boot2docker" command
make: *** [docker] Error 1
```

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

**Comment by fffw** [comment]
You need that `boot2docker` thing to let docker work on Mac.

**Comment by liugangnhm** [comment]
@fffw the newest docker version has no `boot2docker` any more.  Must i uninstall the current docker and install an older one??

**Comment by fffw** [comment]
@liugangnhm `boot2docker` is not part of `docker`. We know that [it is officially deprecated](https://github.com/boot2docker/boot2docker-cli#deprecated) but we don't have a chance to migrate. `boot2docker` works well for the dev team. Pull request is welcome if you'd like to play with the Makefile.
