### ISSUE TITLE
latest lantern binary run fail on linux 

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3167]
latest lantern binary run fail on linux  (I build lantern by myself from git)
OS: linuxmint17.2 
last commit: 5f7d490

command lines:
git clone -b release-2.0.1 --depth 1 --single-branch git://github.com/getlantern/lantern.git
cd lantern
make windows && make linux-amd64

log as follows:

./lantern_linux_amd64
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app

(lantern_linux_amd64:5178): libappindicator-WARNING **: Unable to get the session bus: The connection is closed

(lantern_linux_amd64:5178): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: The connection is closed
DEBUG flashlight.logging: logging.go:50 Placing logs in /root/.lantern/logs
Sep 18 06:30:19.002 - 0m0s DEBUG i18n: translate.go:106 Setting locale zh_CN
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight: flashlight.go:227 ---- flashlight version: 5f7d490, release: 9999.99.99, build revision date: 20150918.041559 ----
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight.config: config.go:353 Using config dir /root/.lantern
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight.config: config.go:125 Checking config path: /root/.lantern/lantern-9999.99.99.yaml
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight.config: config.go:88 File does not exist at /root/.lantern/lantern-9999.99.99.yaml
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight.config: config.go:125 Checking config path: /root/.lantern/lantern-9999.yaml
Sep 18 06:30:19.052 - 0m0s DEBUG flashlight.config: config.go:91 File exists at /root/.lantern/lantern-9999.yaml
Sep 18 06:30:19.220 - 0m0s DEBUG flashlight.config: config.go:116 Found 100 chained servers
Sep 18 06:30:19.228 - 0m0s DEBUG flashlight.config: config.go:431 Adding empty proxiedsites
Sep 18 06:30:19.228 - 0m0s DEBUG flashlight.config: config.go:437 Loading default cloud proxiedsites
Sep 18 06:30:19.228 - 0m0s DEBUG flashlight.config: config.go:186 Running first run setup
Sep 18 06:30:19.228 - 0m0s DEBUG flashlight.client: bootstrap.go:153 Opening bootstrap file from: /home/gary/chained.yaml
Sep 18 06:30:19.228 - 0m0s DEBUG flashlight.client: bootstrap.go:103 Opening file at: /home/gary/chained.yaml
Sep 18 06:30:19.245 - 0m0s DEBUG flashlight.client: bootstrap.go:107 Error reading file open /home/gary/chained.yaml: no such file or directory
Sep 18 06:30:19.245 - 0m0s DEBUG flashlight.client: bootstrap.go:103 Opening file at: /root/.lantern/.packaged-lantern.yaml
Sep 18 06:30:19.245 - 0m0s DEBUG flashlight.client: bootstrap.go:107 Error reading file open /root/.lantern/.packaged-lantern.yaml: no such file or directory
Sep 18 06:30:19.245 - 0m0s ERROR flashlight.config: config.go:194 Could not read yaml: open /root/.lantern/.packaged-lantern.yaml: no such file or directory
Sep 18 06:30:19.245 - 0m0s ERROR flashlight.config: config.go:247 Error initializing config: Unable to perform first run setup: open /root/.lantern/.packaged-lantern.yaml: no such file or directory
Sep 18 06:30:19.245 - 0m0s DEBUG flashlight: flashlight.go:473 Calling exit func
DEBUG flashlight: flashlight.go:473 Calling exit func
DEBUG flashlight: flashlight.go:476 No exit func remaining, exit now
DEBUG flashlight: flashlight.go:190 Processed config
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x4063d0]

goroutine 9 [running]:
main.func·005()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:191 +0x1f0
created by main.doMain
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:211 +0x116

goroutine 1 [syscall, locked to thread]:
github.com/getlantern/systray._Cfunc_nativeLoop(0x0)
	github.com/getlantern/systray/_obj/_cgo_gotypes.go:42 +0x4b
github.com/getlantern/systray.nativeLoop()
	/lantern/src/github.com/getlantern/systray/systray_nonwindows.go:19 +0x1f
github.com/getlantern/systray.Run(0xa794e0)
	/lantern/src/github.com/getlantern/systray/systray.go:56 +0x98
main.runOnSystrayReady(0xa794e0)
	/lantern/src/github.com/getlantern/flashlight/systray.go:14 +0x28
main.main()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:132 +0x151

goroutine 5 [syscall]:
os/signal.loop()
	/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [runnable]:
main.doMain(0x0, 0x0)
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:213 +0x162
main._main()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:140 +0x27
github.com/getlantern/systray.func·001()
	/lantern/src/github.com/getlantern/systray/systray.go:53 +0x55
created by github.com/getlantern/systray.Run
	/lantern/src/github.com/getlantern/systray/systray.go:54 +0x91

goroutine 7 [chan receive]:
main.func·014()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:490 +0x52
created by main.handleSignals
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:493 +0x2d8

goroutine 8 [select]:
main.func·017()
	/lantern/src/github.com/getlantern/flashlight/systray.go:31 +0x10a
created by main.configureSystemTray
	/lantern/src/github.com/getlantern/flashlight/systray.go:39 +0x40c

goroutine 10 [runnable]:
main.func·004()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:182
created by main.func·005
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:189 +0x18c
DEBUG flashlight.config: config.go:353 Using config dir /root/.lantern
DEBUG flashlight.config: config.go:125 Checking config path: /root/.lantern/lantern-9999.99.99.yaml
DEBUG flashlight.config: config.go:88 File does not exist at /root/.lantern/lantern-9999.99.99.yaml
DEBUG flashlight.config: config.go:125 Checking config path: /root/.lantern/lantern-9999.yaml
DEBUG flashlight.config: config.go:91 File exists at /root/.lantern/lantern-9999.yaml
DEBUG flashlight.config: config.go:116 Found 100 chained servers
DEBUG flashlight.config: config.go:431 Adding empty proxiedsites
DEBUG flashlight.config: config.go:437 Loading default cloud proxiedsites
DEBUG flashlight.config: config.go:186 Running first run setup
DEBUG flashlight.client: bootstrap.go:153 Opening bootstrap file from: /home/gary/chained.yaml
DEBUG flashlight.client: bootstrap.go:103 Opening file at: /home/gary/chained.yaml
DEBUG flashlight.client: bootstrap.go:107 Error reading file open /home/gary/chained.yaml: no such file or directory
DEBUG flashlight.client: bootstrap.go:103 Opening file at: /root/.lantern/.packaged-lantern.yaml
DEBUG flashlight.client: bootstrap.go:107 Error reading file open /root/.lantern/.packaged-lantern.yaml: no such file or directory
ERROR flashlight.config: config.go:194 Could not read yaml: open /root/.lantern/.packaged-lantern.yaml: no such file or directory
ERROR flashlight.config: config.go:247 Error initializing config: Unable to perform first run setup: open /root/.lantern/.packaged-lantern.yaml: no such file or directory
panic: Error initializing config

goroutine 1 [running]:
main.logPanic(0xc208013200, 0x898)
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:91 +0xb3
main.func·001(0xc208013200, 0x898)
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:110 +0x32
github.com/mitchellh/panicwrap.Wrap(0xc2080310e0, 0x0, 0x0, 0x0)
	/lantern/src/github.com/mitchellh/panicwrap/panicwrap.go:189 +0xba7
github.com/mitchellh/panicwrap.BasicWrap(0xa794e8, 0xc2080a3f40, 0x0, 0x0)
	/lantern/src/github.com/mitchellh/panicwrap/panicwrap.go:72 +0x7e
main.main()
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:112 +0x2a

goroutine 5 [syscall]:
os/signal.loop()
	/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [runnable]:
github.com/mitchellh/panicwrap.func·002()
	/lantern/src/github.com/mitchellh/panicwrap/panicwrap.go:159 +0xfe
created by github.com/mitchellh/panicwrap.Wrap
	/lantern/src/github.com/mitchellh/panicwrap/panicwrap.go:165 +0x9a0

**Comment by fffw** [comment]
Yes @yuan78 it's expected because of code changes recently. You need to build with `make package-linux` and install the `.deb` if you don't have existing Lantern config file present.
