### ISSUE TITLE
Integrate obfs4

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3172]
It's written in Go, and we could just include the config in each server config to really improve lantern's blocking resistance at the transport level. Forked at:

https://github.com/getlantern/obfs4

**Comment by philogicrock** [comment]
the GFW bypass gateways will test have obvious characteristics of proxy IP agreement，It is very important to how to confuse its spying on，This is the report of the tor the development team.
https://blog.torproject.org/blog/learning-more-about-gfws-active-probing-system

https://zh.greatfire.org/blog/2015/9%E6%9C%88/gfw%E4%B8%BB%E5%8A%A8%E6%8E%A2%E6%B5%8B%E7%B3%BB%E7%BB%9F%E7%A0%94%E7%A9%B6%E6%8A%A5%E5%91%8A
