### ISSUE TITLE
Version 2.0.6 completely unable to visit blocked sites .

### ISSUE THREAD

**Issue by DavidSuccess** [getlantern/lantern#3174]
ISP: China uincom
Address: Beijing
Connection type: LAN

**Comment by myleshorton** [comment]
Can you send your lantern.log file to fffw@getlantern.org and to
myles@getlanyern.org?

**Comment by DavidSuccess** [comment]
I already send a email to them

**Comment by DavidSuccess** [comment]
@myleshorton  @fffw 

This looks like a solution to the problem, I don't know why but maybe you  can take a look：
https://groups.google.com/forum/#!topic/fqlt/TI-g9V6t7B4

**Comment by myleshorton** [comment]
Thanks for the log files @DavidSuccess. We're looking at it now.

So if you select "Proxy All" it works, is that correct? If you did that after the last set of logs, can you send your logs one more time? Thanks so much.

**Comment by DavidSuccess** [comment]
@myleshorton 
Thanks for reply!
But if I select "Proxy All" It still unable to connect, I already send a email with log files to you.
Please excuse my poor English.

**Comment by myleshorton** [comment]
Sorry @DavidSuccess what was the fix that made it work for you then?

**Comment by DavidSuccess** [comment]
@myleshorton  Repleace some files,I've sent you a email.

**Comment by myleshorton** [comment]
Hi @DavidSuccess sorry for the delay on this, but this should be fixed on the server side and with the latest Lantern versions. Is it working OK for you now?

**Comment by DavidSuccess** [comment]
The version 2.0.9 is still very stable so far!
Thank you for your awesome work!

2015-10-10 4:18 GMT+08:00 myleshorton <notifications@github.com>:

**Comment by myleshorton** [comment]
Great! Please let us know if you have any issues.
