### ISSUE TITLE
How to solve this problem in Lantern 2.0.6.

### ISSUE THREAD

**Issue by fhzheng** [getlantern/lantern#3178]
While using Lantern, my fireFox cannot connect to any website and show this message
HTTP/1.1 502 Bad Gateway
Content-Length: 0

Unable get outgoing proxy connection: Still unable to dial tcp://http://www.doesnotexist.com:80 after 3 attempts
I use fireFox version 40.0.3

**Comment by fanrangjun** [comment]
I also seem to have this problem. I'm in China. It seems that the DNS resolving part fails everytime.

**Comment by Centaur** [comment]
Same problem here, though happened just today.

**Comment by myleshorton** [comment]
Can you guys send your logs over @Centaur, @fanrangjun, and @fhzheng? Instructions at at https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs, and if could also copy myles@getlantern.org that would be great. We should be able to get Lantern working again for you soon.

Thanks so much, and apologies for the inconvenience.

**Comment by fanrangjun** [comment]
@myleshorton , I've sent the email with the log file, using fanrangjun880506@yeah.net
much obliged

**Comment by myleshorton** [comment]
Thanks guys. Are you all still having issues with 2.0.9, released earlier today @fanrangjun, @Centaur, and @fhzheng?

**Comment by Centaur** [comment]
Bad news. Yesterday after upgrade OS X to EL Capitan 2.0.2 could not start. So I installed 2.0.8 and it works fine. 2.0.9 just doesn't work. Not this issue but even if 'proxy all' is checked, none of the blocked site can be connected. Have tried restart Lantern and restart browser, no luck.

**Comment by fhzheng** [comment]
@myleshorton it works fine ;-)

**Comment by fhzheng** [comment]
@myleshorton oh no, it appears again! After using Lantern for a while, all connections tend to be badly slow. I've mailed my log file to you.

**Comment by myleshorton** [comment]
Interesting @fhzheng. Does Lantern appear to be using more CPU or memory after a long period of running by chance? I'm wondering if there's some sort of bug with resource usage in Lantern itself.

**Comment by fhzheng** [comment]
@myleshorton yes, the CPU usage of Lantern increased from around 4% to around 7% on my computer after using it for 20 minutes .

**Comment by Centaur** [comment]
Oops, this happened in 2.0.9 today.

**Comment by myleshorton** [comment]
OK thanks everyone. @Centaur you should hopefully see it working much better now. We're working on the CPU issue, but the primary issue appears to have been solved on the server side (we hope).

@Centaur and @fhzheng, and @fanrangjun is Lantern working any better for you now?

**Comment by Centaur** [comment]
Yes. Improvement confirmed.

**Comment by myleshorton** [comment]
Great thanks @Centaur!

**Comment by fhzheng** [comment]
@myleshorton yes, thank you!

**Comment by zengfenfei** [comment]
I have this problem too
