### ISSUE TITLE
When you can fix this issse that lantern run fail on linux?

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3180]
When you can fix this issse that lantern run fail on linux?
Currently lantern completely cannot work on linux while it can work well on windows on contrast.

**Comment by yuan78** [comment]
I fixed this issue by adding .packaged-lantern.yaml & lantern-9999.99.99.yaml manually.
It seems lantern works not very intelligently on linux.
Also it will show blank page when run 127.0.0.1:16823.

**Comment by myleshorton** [comment]
This should also be fixed in 2.0.9 @yuan78
