### ISSUE TITLE
Decentralized network node

### ISSUE THREAD

**Issue by philogicrock** [getlantern/lantern#3205]
Can let users use the lantern PC automatically become nodes volunteers, many-to-many P2P mode, like Bittorrent, Freenet, Emule kad and VPNGATE, strong encryption while maintaining the network traffic load balancing and much harder to block. Every time start software can automatically update the network node and search a software update, And suggested that reduction before the map interface.
Thank you have been trying to maintain project developers.

**Comment by myleshorton** [comment]
Thanks @philogicrock! This type of thing is very much on our radar and will almost definitely make it into future versions of Lantern. Stay tuned!
