### ISSUE TITLE
How could I run "lantern_linux_arm" on my Chromebook (ARM Architecture)

### ISSUE THREAD

**Issue by yakir-Yang** [getlantern/lantern#3223]
Hi, the CPU of my Chromebook is RK3288 (ARM Architecture), and I see Lantern already can build the linux-arm binary, so I guess the "lantern_linux_arm" could run on my Chromebook directly (Not sure). According to the READ.me remind "sudo make docker" & "sudo make linux-arm", and then I got the "lantern_linux_arm" binary.

After login in the Chromebook shell, contained the root permissions, and copy the "lantern_linux_arm"  to "/usr/bin/" dir, and change the mode to 777, then run it manually. But something wrong, the shell remind me that “No such file or directory”.

localhost ~ # file lantern_linux_arm 
lantern_linux_arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, not stripped
localhost ~ # lantern_linux_arm 
-bash: /usr/bin/lantern_linux_arm: No such file or directory

Can some guys help here, guide me the right way to run "lantern_linux_arm".

**Comment by fffw** [comment]
I guess you can run './lantern_linux_arm'? ARM is not officially supported
though so you may run into other issues.

**Comment by yakir-Yang** [comment]
Thanks for your reply, I have try that way "./lantern_linux_arm", the error message is the same.
localhost ~ # ./lantern_linux_arm 
bash: ./lantern_linux_arm: No such file or directory 

--------------------------------
And I guess pasting the kernel version of Chromebook would be useful here:

localhost user # uname -a
Linux localhost 3.14.0 #1 SMP Wed Sep 9 13:35:14 PDT 2015 armv7l Rockchip (Device Tree) GNU/Linux
localhost user # cat /proc/version 
Linux version 3.14.0 (chrome-bot@build68-m2) (gcc version 4.9.x-google 20150123 (prerelease) (4.9.2_cos_gg_d86e6bd_4.9.2-r105) ) #1 SMP Wed Sep 9 13:35:14 PDT 2015

**Comment by uaalto** [comment]
Yakir-Yang, the project is not ready yet, although it is possible that with some fiddling you get it working already. The issue you are having has nothing to do with the build process or Lantern itself, but rather with your OS. The current binary is ready to run in Raspberry Pi, although unsupported. Since we are not supporting Chrome OS at the moment and the ARM support is being tracked in a different issue, I'll close this one.

**Comment by yakir-Yang** [comment]
Okay, I would like try more ARM linux platform, see what I can found, thanks for your reply.

**Comment by duchengyao** [comment]
1. `sudo ln -s /lib/ld-linux-armhf.so.3  /lib/ld-linux.so.3`
2. .`/lantern`

**Comment by yakir-Yang** [comment]
@duchengyao ,Oops, great, it works.

Just for study, how did you find the error point. lantern_linux_arm seems isn't a dynamic executable, and also didn't found lantern want to open some file with the strace debug log. Could you share your debug method ;)

**Comment by yakir-Yang** [comment]
root@kiwi:/tmp# readelf -a lantern_linux_arm |grep ld
  [24] .note.go.buildid  NOTE            00010fb4 000fb4 000038 00   A  0   0  4
      [Requesting program interpreter: /lib/ld-linux.so.3]
   02     .note.go.buildid 
   03     .text .plt .interp .note.go.buildid 
   593: 008dce98     8 OBJECT  GLOBAL DEFAULT   20 archive/tar.ErrFieldTooLo
  1478: 005d1480     4 OBJECT  GLOBAL DEFAULT    3 encoding/json.equalFoldRi


Aha,

**Comment by rezad1393** [comment]
you can compile lantern for arm.
