### ISSUE TITLE
lartetn can not work with Proxy SwitchyOmega

### ISSUE THREAD

**Issue by xiexiaodong** [getlantern/lantern#3225]
when I use lantern,If my Chrome browser installed proxy [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega).At the same time I use it's system agent。lantern can not work,Is this lantern's fault?

**Comment by crysislinux** [comment]
It's better to post a screenshot about your configuration of SwitchOmega

Lantern setup a http proxy on your system: 127.0.0.1:8787

Recheck and ensure you have done right.

**Comment by xiexiaodong** [comment]
Are you sure that the lantern proxy port is 8787?,I set this up, but I can't work.

**Comment by xiexiaodong** [comment]
![qq 20151013132024](https://cloud.githubusercontent.com/assets/5906306/10446114/6e85759a-71ad-11e5-8cb6-58d716776e2e.png)This is SwitchOmega's configuration screenshot

**Comment by fffw** [comment]
To further isolate the cause, does Lantern work for you if you disabled the SwitchyOmega extension and let Chrome respect system proxy setting (plus, there should not be any HTTP/HTTPS/SOCKS proxy configured in system)? If it works, then it could be related to SwitchyOmega configuration but we don't have any knowledge about it.

**Comment by xiexiaodong** [comment]
I think it's my fault.i do not know what errors have happend in my system.i will check it.thank you!

**Comment by xiexiaodong** [comment]
Solve the problem, Chrome browser version 45 is no problem. unknown origin

**Comment by fffw** [comment]
Glad you solved it!

**Comment by telwenshen** [comment]
请教一下您找到原因是什么？我也是有一样的问题。@Yaccc
