### ISSUE TITLE
Lantern failed to run on OS X EI Captain (10.11)

### ISSUE THREAD

**Issue by iSeaSoul** [getlantern/lantern#3226]
My old version Lantern cannot run normally at first, so I reinstall a new one downloaded from Github. Unfortunately, it still failed to run.
Is there any problem?
(It's too late to know you shouldn't upgrade your system as soon as it released, so many unpredicted issues are just waiting for you T_T)

Thank you very much anyway, for this excellent software!

**Comment by handelxh** [comment]
i have the same problem... lantern run normally on OS X Yosemite（10.10) .

**Comment by Jichao** [comment]
No problem on my computer.

**Comment by iSeaSoul** [comment]
Somehow it works fine right now, though I haven't tried anything for fixing this.
Close the issue.

**Comment by myleshorton** [comment]
Yeah I experienced the same exact thing. It didn't work at first but now
works fine.

On Wed, Oct 21, 2015 at 7:59 PM, Li Yan <notifications@github.com> wrote:

> Somehow it works fine right now, though I haven't tried anything for
> fixing this.
> Close the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3226#issuecomment-150092267>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
