### ISSUE TITLE
Lantern ignore domains in  /etc/hosts

### ISSUE THREAD

**Issue by crysislinux** [getlantern/lantern#3228]
system: OSX El Captain
lantern version: 2.0.9

I have some local sites that are under development.

 \# /etc/hosts
127.0.0.1 example.dev

I can access local sites via 127.0.0.1, but cannot via example.dev

example.dev should go DIRECT but it seems go through the PROXY now.

Thanks.

**Comment by LukyHugh** [comment]
I have same problem. How to fix this error.

**Comment by kcloze** [comment]
Me too

**Comment by wonderffee** [comment]
The same problem, could someone give a solution?

**Comment by royaso** [comment]
ding!!

me too!

is there a way to bypass these local hosts domains?

**Comment by oxtoacart** [comment]
Duplicate of #3472.
