### ISSUE TITLE
lantern works better on China Unicom than China Telecom 

### ISSUE THREAD

**Issue by zhanxiage233** [getlantern/lantern#3229]
I had tested a lot,lantern works much better on China Unicom than China Telecom . 
I know a few people ,they told the same problem,if they use china unicom,it's ok for lantern ;but if they use china telecom,lantern is very slow.

**Comment by myleshorton** [comment]
Thanks @zhanxiage233 we've anecdotally heard similar reports, but I'm not sure there's too much we can do about it unfortunately.
