### ISSUE TITLE
Urgent info! Lantern chainserver IP hv been published & exposed to public by some abominable guys!

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3230]
Urgent info! Lantern chainserver IP hv been published & exposed by some abominable guys!
These guys open yaml file to search lantern domain& and ip range such as  cloudfront.net, and then they scan the IP range to get low ping value IP, and they post these chainserver IP to public!

Below is the refenrence link, basically thousands of people at least already knows this way to scan the lantern IP:

http://www.gochrome.info/lantern-finally/
http://www.gochrome.info/lantern-chainedservers-886/

This beast behavior will destroy all your efforts!
I don't know whether it will cause GFW to block these published IP and cause lantern cannot be accessed completely finally !

Hence I need lantern developing team's highest attention for this bad case. Pls try to hide the chainserver IP into yaml to avoid it exposed again in the future.

THX!

**Comment by myleshorton** [comment]
OK thanks @yuan78 we're on it -- thanks very much for letting us know.

**Comment by ertcds** [comment]
@myleshorton will you block it like GFW？

**Comment by myleshorton** [comment]
@yuan78 and @ertcds really these guys aren't exposing much, if anything, as they're only talking about the lantern bootstrap chained servers, which are quite easy for anyone, including the GFW, to find. The cloudfront.net domains are also not a secret, but the key with those is that it's unlikely the GFW would choose to block all of them. Lantern uses *a lot*.
