### ISSUE TITLE
Possible simultaneous connection issues with ATS

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3237]
I'm currently only able to get connections sporadically to 178.62.215.188, but the actual load on the server looks reasonable: https://cloud.digitalocean.com/droplets/7721758#actions-graphs

It seems like over time ATS might start to have issues.

**Comment by aranhoide** [comment]
I've observed something like this a lot in Vultr lately.  I just run a job to reboot all fallbacks and the problem was gone.  Maybe we should pick the time of the day where each datacenter is the least busy and just have a cron job in fallbacks to reboot themselves at that time?

**Comment by myleshorton** [comment]
Yeah that sounds interesting @aranhoide. You haven't seen it in DO though? I'm actually wondering if this could be the cause of a lot of what we're seeing. I'm basically seeing a DO server and a Vultr server that both have very low load but that both have a lot of trouble accepting new connections.

I'm wondering if there's something completely wrong with our ATS config, but I think restarting at less busy times sounds like a very good idea.

**Comment by myleshorton** [comment]
hey what if I wanted to manually restart a server @aranhoide? What's the best way to do that?

**Comment by aranhoide** [comment]
Actually I just logged into that machine and I was greeted with a `*** System restart required ***` notice.  Our automatic-upgrades config used to restart machines when they were upgraded, but that's apparently not the case anymore?  I'll reboot all DO fallbacks manually just in case, then take a look at the config.

**Comment by aranhoide** [comment]
@myleshorton : `ssh <ip> "sudo reboot"`

**Comment by myleshorton** [comment]
Nice thanks @aranhoide -- rebooting one of these now to see if it solves anything. I think rebooting everything daily is an excellent idea though.

**Comment by aranhoide** [comment]
@myleshorton : OK, I'll reboot all servers in DO, then add that to the config.

**Comment by myleshorton** [comment]
Cool -- I think now is a decent time to do it actually. I think I noticed the upgrade check itself taking a lot of CPU/memory on one box actually.

**Comment by myleshorton** [comment]
We're over on slack BTW too @aranhoide
