### ISSUE TITLE
Seeing lots of no auth token failures on servers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3243]
In error logs many times:

20151008.00h01m01s host to visit: www.google.com
20151008.00h01m07s no X-LANTERN-AUTH-TOKEN field

I wonder if we're doing some check here, possibly from peerscanner? Any thoughts @fffw or @aranhoide?

**Comment by aranhoide** [comment]
You mean fallback checking?  We no longer have a peerscanner.

The fallback checker does set the header:

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/checkfallbacks/checkfallbacks.go#L157

and we also check that we get the right body for humans.txt

https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/checkfallbacks/checkfallbacks.go#L182

**Comment by fffw** [comment]
I checked fp-jp-20150924-012, fp-jp-20151001-006 and fp-jp-20151001-007, all 3 have similar repetitive entries in `/opt/ts/var/log/trafficserver/errors.log`. Each server logs different client ip from China.

> 20151013.05h52m16s no X-LANTERN-AUTH-TOKEN field
> 20151013.05h52m16s client ip: <masked>
> 20151013.05h52m16s host to visit: www.google.com
> 20151013.05h52m22s no X-LANTERN-AUTH-TOKEN field
> 20151013.05h52m22s client ip: <masked>
> 20151013.05h52m22s host to visit: www.google.com
> 20151013.05h52m28s no X-LANTERN-AUTH-TOKEN field
> 20151013.05h52m28s client ip: <masked>
> 20151013.05h52m28s host to visit: www.google.com

As the interval is always 6s and the [`maxTimeout`](https://github.com/getlantern/lantern/blob/release-2.0.1/src/github.com/getlantern/balancer/dialer.go#L52) of `balancer.dialer.defaultCheck` is 5s (the 1s difference is unexplainable though), I guess it is some (maybe old version, say, 2.0.7?) Lantern instance that always fail to test the chained server assigned to them.

**Comment by myleshorton** [comment]
I like that theory @fffw -- makes a lot of sense. To be clear for the record, @fffw is referencing a bug in older versions of Lantern where retesting a previously-failed chained server would always fail itself because it wouldn't include the auth token for the server.
