### ISSUE TITLE
Fail to load resource when visiting a site for first time on El Capitan

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3248]
Visiting same group of sites, including blocked and not blocked ones.

Chrome reports "Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED"
Safari reports "Failed to load resource: The network connection was lost."
Firefox doesn't report any errors.

Reload page and most error disappears. Browsers on Windows doesn't face this issue.

Guess it only happens on El Capitan, but have no previous OS X versions to test.

**Comment by fffw** [comment]
Forget it. One SOCKS proxy crashed and left an unreachable proxy addr in system settings.

**Comment by myleshorton** [comment]
I actually was not even able to run Lantern on El Capitan - probably some issue with code signing depending on your settings.
