### ISSUE TITLE
Lantern starts using more memory when used for long time

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3251]
Memory usage was initially 80 MB but increased upto 260 MB when let it run and being idle for about 4-5 hours. And when started using again, the usage came down to 200 MB which is still higher.

**Comment by fffw** [comment]
Which OS is Lantern running on? I run Lantern 2.0.10 on both OS X 10.11 and Windows 7 for 6 hours or so, didn't see significant memory increment (checked from Activity Monitor and Task Manager, respectively).

**Comment by myleshorton** [comment]
Have you seen this one with 2.1.0 @sunshine19090? I think we fixed it in an earlier version actually.

**Comment by sunshine19090** [comment]
No @myleshorton, I haven't seen this after the oct-nov release. I think we can close it.

**Comment by myleshorton** [comment]
Awesome thanks @sunshine19090!
