### ISSUE TITLE
2.0.9 not work but 2.0.2 is good

### ISSUE THREAD

**Issue by sjc2000** [getlantern/lantern#3256]
2.0.9 log file says 

ERROR balancer: balancer.go:102 Unable to dial via (trusted) chained proxy at 104.238.161.204:443 to connect://ssl.gstatic.com:443: Unable to dial server (trusted) chained proxy at 104.238.161.204:443: dial tcp 104.238.161.204:443: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 0...continuing

what can i do for this or how can i prevent 2.0.2 to auto upgrade? thanks!

**Comment by fffw** [comment]
Unfortunately, this server is just blocked. We are working on ways to overcome this.
