### ISSUE TITLE
Fail to open Wifi login portal when Lantern is running

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3258]
Automatically opened page will show "Still unable to dial tcp://doesnotexist.com:80 after 3 attempts"

**Comment by lixiaodongsql** [comment]
Hello Respectful Sir, Have you received my ping results which I sent to your email address? Thank you very much for your help. I really appreciate it.

**Comment by b-z** [comment]
i have the same problem while loading the login page

**Comment by myleshorton** [comment]
Closing in favor of #4104 just because it's a little more general.
