### ISSUE TITLE
Can  not work in chrome while other browsers are well

### ISSUE THREAD

**Issue by baicy** [getlantern/lantern#3262]
Firefox and IE work well，while chrome not. Really want to know why. :sob:

**Comment by lucifarlee** [comment]
I use windows installer version

**Comment by hitrust** [comment]
chrome is working well

**Comment by lucifarlee** [comment]
Yeah，except for me ,chrome works well. Really hard t understand...

**Comment by myleshorton** [comment]
It's possible Chrome has marked Lantern as a bad proxy. Can you go here within chrome @lucifarlee?

chrome://net-internals/#proxy

**Comment by wang1988ming** [comment]
@myleshorton  is there  a solution? 
![error](https://cloud.githubusercontent.com/assets/572393/10708763/b5a9c002-7a45-11e5-8a3c-d65e270ff0fc.png)

**Comment by lucifarlee** [comment]
@myleshorton my picture is as same as @wang1988ming . I didn't find the words about marking as a bad proxy :sob: 
And, can the picture below make some help?
![default](https://cloud.githubusercontent.com/assets/7036854/10709358/cd87075e-7a5c-11e5-84cc-8805ab96a963.png)

**Comment by y11022053** [comment]
mark.
i have the same problem.

**Comment by YaoDanLiu** [comment]
Mark

**Comment by myleshorton** [comment]
Hi everyone, and sorry for the delay. Can you all just specify which operating system you're on to help us narrow down the problem. Does it fail for you always in Chrome or just sometimes? Thanks @y11022053, @YaoDanLiu, @lucifarlee, @wang1988ming, and @hitrust

**Comment by lucifarlee** [comment]
@myleshorton  I have 2 device2, both of them have this question. One is Windows 7, the other is Windows8.1.
From the day before yesterday, my firefox on win7 seems not work too. = = 
Thanks a lot.

**Comment by y11022053** [comment]
hi,
I have tested on win 10 & win xp,
both have this problem, IE works fine with lantern, but Chrome doesn't(version 44, 45, 46)。
the only way to fix it (temperately) is uninstall Chrome, then restart system, install Chrome, then Chrome works again.
BUT when I sign in my gmail account to Chrome on settings page, it is suddently that Chrome lost the connection with Lantern, very strange!
I suspect the extensions of Chrome, then I disable all of them, but it seems no help.
ALL. please help me.



y11022053@gmail.com
 
From: myleshorton
Date: 2015-10-29 06:44
To: getlantern/lantern
CC: Michael Yuan
Subject: Re: [lantern] Can not work in chrome while other browsers are well (#3262)
Hi everyone, and sorry for the delay. Can you all just specify which operating system you're on to help us narrow down the problem. Does it fail for you always in Chrome or just sometimes? Thanks @y11022053, @YaoDanLiu, @lucifarlee, @wang1988ming, and @hitrust

**Comment by hkvsak** [comment]
我也有这个问题，但是卸载淘宝的软件亲淘后就好了。。。^^;英语差！

**Comment by y11022053** [comment]
我靠←_←，我回头试试发自网易邮箱大师
            在2015年11月03日 23:13，hkvsak 写道:我也有这个问题，但是卸载淘宝的软件亲淘后就好了。。。^^;英语差！

**Comment by yannxia** [comment]
I also too, I'm use windows 7 x64 SP1,

**Comment by yannxia** [comment]
@y11022053 我删了也不起效果···难道要重启
