### ISSUE TITLE
Why lantern use a large virtual memory? 

### ISSUE THREAD

**Issue by xuedong09** [getlantern/lantern#3264]
I use htop and found that lantern's VIRT item is  138.6G

**Comment by fffw** [comment]
Oh it's terrible. Can you remember how long has Lantern running before you saw this huge vm usage @xuedong09 ?

**Comment by xuedong09** [comment]
I found it not related to how long  the lantern ran, every time I open it, it cost such a huge virtual memory.
My OS: osx 10.10.5
kernel: Darwin localhost 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

Below is my "ps aux" result about lantern.

USER              PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
BJ                773   0.0  0.7 145303372  56388   ??  S     9:44AM   0:01.70 /Applications/Lantern.app/Contents/MacOS/lantern -startup
BJ                710   0.0  0.1 145216024  10940   ??  S     9:44AM   0:00.09 /Applications/Lantern.app/Contents/MacOS/lantern -startup

**Comment by fffw** [comment]
Okay it's not that terrible. It's just the space OSX reserved for the process. When you view Activity Monitor, the memory usage is only tens of Megabytes. Perhaps some linker parameters can reduce it, but it's safe to be ignored for now.

Look the HUGE `VM_ALLOCATE` region in following command output.

```
> vmmap 7657
==== Summary for process 7657
ReadOnly portion of Libraries: Total=214.6M resident=0K(0%) swapped_out_or_unallocated=214.6M(100%)
Writable regions: Total=27.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=27.5M(100%)

                                VIRTUAL   REGION
REGION TYPE                        SIZE    COUNT (non-coalesced)
===========                     =======  =======
Activity Tracing                  2048K        2
Kernel Alloc Once                    4K        2
MALLOC guard page                   32K        7
MALLOC metadata                    356K        9
MALLOC_SMALL                      8192K        2         see MALLOC ZONE table below
MALLOC_TINY                       3072K        4         see MALLOC ZONE table below
STACK GUARD                         12K        4
Stack                             10.0M        6
Stack Guard                       56.0M        3
VM_ALLOCATE                      136.1G        7      <================== here
__DATA                            21.0M      178
__IMAGE                            528K        2
__LINKEDIT                        88.4M        4
__TEXT                           126.1M      179
__UNICODE                          552K        2
shared memory                       12K        4
===========                     =======  =======
TOTAL                            136.4G      399
```

**Comment by xuedong09** [comment]
OK! Thanks for your help.
