### ISSUE TITLE
Selecting proxy all in one window isn't reflected in other Lantern windows.

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3267]
Selecting "proxy all" and likely other settings is not reflected in other existing Lantern windows. This was on Mac.

**Comment by myleshorton** [comment]
Actually it looks like this is only an issue with multiple windows -- i.e. if you select "proxy all" in one window, other Lantern windows don't properly reflect that state.

**Comment by sunshine19090** [comment]
I hope this is only in Mac. For me, it worked fine with windows 8.1. Also @myleshorton , are you saying that the settings are getting back to default if Lantern is open more than once?

**Comment by myleshorton** [comment]
I only saw it on Mac on existing Lantern windows @sunshine19090 (i.e. changing the setting would not change it in other, already open windows).

**Comment by sunshine19090** [comment]
Ah, I think that is how it worked all time. If you already have open Lantern windows and if you change the settings in one of them, you need to refresh in other windows or you have to open a new instance. Did you try that @myleshorton ?

**Comment by myleshorton** [comment]
I didn't try that, but I would definitely expect that to work @sunshine19090 . I agree it's not much of an issue, so closing!
