### ISSUE TITLE
209以后的版本在SwitchySharp里怎么设置？

### ISSUE THREAD

**Issue by OnionSalt** [getlantern/lantern#3276]
SwitchySharp里以前一直好用的“手动配置”的HTTP代理127.0.0.1:8787在升级到2.0.9以后突然不好用了，听说必须改用“自动配置”，就是那个什么.pac文件，“自动配置的URL”项应该怎么填？完全搞不清楚这个.pac在什么位置，有人知道应该在什么地方找吗？或者网上有相关教程什么的？

我用的win7, 浏览器是chrome

**Comment by xieyingli** [comment]
停用SwitchySharp就行吧，不用卸载。

**Comment by kirning** [comment]
http://127.0.0.1:16823/proxy_on.pac
填写这个试试

**Comment by OnionSalt** [comment]
http://127.0.0.1:16823/proxy_on.pac
还是不行，chrome左下角一直提示正在尝试连接代理服务器，然后会卡大概1分钟，最后提示连接不上

另外，这个proxy_on.pac文件保存在什么位置，能查看这个.pac文件的内容吗？

唉，又开始用xx-net了，每天扫ip，烦不胜烦啊

**Comment by fffw** [comment]
@OnionSalt 这个PAC的内容是根据你访问的情况动态更新的。直接用浏览器打开就可以看到。

Chrome识别代理遇到问题，可以访问chrome://net-internals/#proxy看。
