### ISSUE TITLE
Stop using javascript from facebook and twitter in lantern UI please...

### ISSUE THREAD

**Issue by hnlq715** [getlantern/lantern#3281]
Version: 2.0.10 
Location: China

```
connect.facebook.net/en_US/sdk.js
platform.twitter.com/widgets.js
```

**Comment by fffw** [comment]
Did it cause any issue to you @hnlq715?

**Comment by hnlq715** [comment]
Everytime I launch lantern, I failed to get the javascript resouces listed above in my chrome. Maybe they are blocked in China also...

**Comment by fffw** [comment]
Yes they are blocked in China, but when Lantern is launched, browser will
access them via Lantern, hence unblock them. Does Lantern work for you in
general?

**Comment by hnlq715** [comment]
Actually it works at the beginning, but it fails to work recently... I do not quite understand the reason

**Comment by hnlq715** [comment]
Oh my god, I solved this problem!!!
After adding lantern into Windows firewall allow list, I find everything works fine for me...
Maybe at the last time I update Windows, it automatically launched firewall function.

Thanks for your reply, you guys are doing an awesome job.

**Comment by fffw** [comment]
Great! The Windows firewall thing is very helpful as other users may also
run into it.

**Comment by uaalto** [comment]
Hey @fffw @myleshorton we have a PR pending that may help in this situations too. Users won't need to update the Firewall by hand. The review probably will take some time though because it is large and has a lot of C code.

**Comment by myleshorton** [comment]
Interesting thanks guys. @hnlq715 what version of Windows are you running? Did the firewall seem to be blocking outgoing connections as well?

**Comment by hnlq715** [comment]
@myleshorton Windows 7, I think the firewall would just block the programs not in its allow list :-)

**Comment by fffw** [comment]
It would be better to detect this and prompt user (or simply add it in self
help troubleshooting guide) than deal with it in Lantern, as user may use
3rd party firewall (in particular, 360safe in China) which we are unable to
change programatically.
