### ISSUE TITLE
我有遇到几个问题

### ISSUE THREAD

**Issue by Dannywanxyz** [getlantern/lantern#3287]
lantern 版本 2.0.10
os 版本 win10 64位 + chrome 46.0.2490.80 m
遇到的问题
1.公司的能使用，速度很快，电信宽带，chrome，edge与IE均可使用
2.家里的同样的环境，也是电信宽带，chrome和edge浏览器均无法使用，ie使用正常，所以应该不是代理插件的问题（我的代理插件是switchysharp），chrome 登陆谷歌时请求一直停留在 正在等待代理隧道的响应，大约前一个星期还使用正常

**Comment by z007** [comment]
重装系统 卸载QQ 国内杀毒软件 https://github.com/chengr28/RevokeChinaCerts

**Comment by z007** [comment]
重装纯净系统  少用 .GHO 封装系统
驱动 使用电脑原装驱动
软件 小众推荐
http://love.appinn.com/

禁用 QQ  聊天类软件
禁用  墙内杀毒软件  
CNNIC
https://github.com/chengr28/RevokeChinaCerts

https://kenengba.com/post/3336.html
https://qdan.me/list/VRIio9hA0FujGWYP
http://www.williamlong.info/archives/4125.html

**Comment by fffw** [comment]
@Dannywanxyz it should be caused by blocked server or bad network quality to the server. Do you still experience it?

**Comment by godvmxi** [comment]
1、只要lantern和迅雷在，lantern必挂
2、卸载迅雷，立马OK

**Comment by Dannywanxyz** [comment]
@godvmxi 不知道没试过，不过都是P2P客户端，多多少少会有点影响吧

**Comment by godvmxi** [comment]
刚试了，要么是服务冲突，要么就是呵呵了。。。

**Comment by Dannywanxyz** [comment]
那应该是是P2P服务冲突了

dandan <notifications@github.com>于2016年6月17日周五 上午10:48写道：
