### ISSUE TITLE
Add self help page to Lantern UI

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3288]
Users keep asking similar questions on forums, Facebook, Twitter, or even create GitHub issues, and may not get prompt response. It would be good to have a page on Lantern UI to show a few common tips on configuration (for example, proxy address and PAC url) and troubleshooting steps, say, [this Windows firewall issue](https://github.com/getlantern/lantern/issues/3281#issuecomment-151344623). And, if the problem is still not resolved, show instructions to send logs.

https://github.com/getlantern/lantern/issues/2785 can still be useful, but user may check the help page more carefully if it requires addition steps to send logs.

Hopefully, we can make users happier and reduce the amount of support requests.

**Comment by fffw** [comment]
Instead of a page of tips, it can be a diagnostic program running from both browser and backend. Many home routers has such feature.

1. ping well known not-blocked site to ensure that the Internet connection is ok.
2. HTTP GET well known not-blocked site.
3. AJAX GET well known not-blocked site from browser (through Lantern).
3. AJAX GET blocked site through Lantern.

We give suggestions when certain step fails. Then, as the finally step, user can download diagnostic results together with logs and email to us.

**Comment by fffw** [comment]
It may help to find the cause of https://github.com/getlantern/lantern/issues/3359 and others.

**Comment by fffw** [comment]
Specifically, conflicting browser extensions can be detected by fetching an artificial site hosted by Lantern backend.

**Comment by myleshorton** [comment]
The main three cases are:

1) Xunlei
2) Conflicting extensions
3) Your server not working for reason.

**Comment by louy2** [comment]
Before UI, I guess it is probably easier to just update the Github Wiki for now. And since it's Markdown we may actually generate it into UI later. The current wiki seems way outdated, referring to the original beta UI.

**Comment by myleshorton** [comment]
Work on this will be closely related to #3017 and will likely build on the error page UI in the newsfeed.

**Comment by oxtoacart** [comment]
@myleshorton Per discussion with @fffw and @aranhoide we decided that the self-help page wasn't part of MVP for this extension.  Are you saying that you want to make it part of MVP?

**Comment by myleshorton** [comment]
Closing -- I think we can handle this in an extension ultimately but let's handle that in a new, updated ticket as necessary.
