### ISSUE TITLE
Hope you add these features.

### ISSUE THREAD

**Issue by Chigogo** [getlantern/lantern#3292]
For a stable connection through firewalls, lantern updates the yaml file from time to time. But for a better user experience, I wish that users can customize these settings:

Share the free connection over LAN(say, with iOS devices).
Users choose to use Pac or the HTTP mode.

Developers should use yaml file to upgrade the connection configuration, and use another configuration file for user themselves.

Thanks for the excellent app, and we expect a better one!

**Comment by fffw** [comment]
Both were added.

1. With the `Manage system proxy` option, the user can choose use PAC or not.
2. With the separation of `settings.yaml` and `config.yaml`, user specific options will  not be overridden.
