### ISSUE TITLE
Lantern got high CPU usage when offline (WINDOWS platform).

### ISSUE THREAD

**Issue by Gigglelife** [getlantern/lantern#3300]
![](https://i.imgur.com/ihJqKHY.png)

**Comment by myleshorton** [comment]
What version of Lantern are you using @Gigglelife?

**Comment by Gigglelife** [comment]
@myleshorton 2.0.10 (20151009.024157)

**Comment by myleshorton** [comment]
Wow that's very interesting @Gigglelife thanks. What version of Windows? Does it happen all the time or just sometimes? @sunshine19090 it might be interesting to test with taking your machine offline.

**Comment by Gigglelife** [comment]
@myleshorton I'm use Win10 pro (10240). Sometimes when I made my PC to sleep then wake it up when offline, the lantern process got high cpu usage. That's all.

**Comment by sunshine19090** [comment]
Sure @myleshorton, I will check and update.

**Comment by sunshine19090** [comment]
I couldn't reproduce @myleshorton. I tried both running Lantern while online and offline for several hours.

**Comment by fffw** [comment]
I believe we fixed it a while ago.
