### ISSUE TITLE
it doesn't work well in LinuxMint with KDE

### ISSUE THREAD

**Issue by angela0** [getlantern/lantern#3302]
1. whatever browser the default is, lantern will open the Firefox

2. if Firefox is running, Firefox will pop a pop-up with `Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.`

3. when it work in Firefox well,  another browser can't use it

**Comment by kashu** [comment]
1. It just like a "welcome page", doesn't matter.

This startup method always works for my Xubuntu 14.04.3 and I think you will like it.
```
/usr/bin/nohup sh -c "/bin/sleep 8 && /usr/lib/lantern/lantern.sh -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null
```

manually start Lantern
```
$HOME/.lantern/bin/lantern -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null
```
![](http://ww1.sinaimg.cn/large/9c4ddab1gw1f14xguqpk6j20qw0d17aq.jpg)

**Comment by fffw** [comment]
@angela0 You can also add `-headless` option to avoid pop-up Lantern page at all.

If Lantern fails to set system proxy in some Linux system, you can always point you application to user `127.0.0.1:8787`, either through application specific options, or the standard `http_proxy` or `https_proxy` environment variable.
