### ISSUE TITLE
Lantern eats a lot of memory

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#3303]
I'm using Lantern 2.0.10 (20151009.024157), it suddenly becomes a big memory eater these days and seems to make my browser run much slower sometimes.

![lantern-memory](https://cloud.githubusercontent.com/assets/4662568/11015128/b113c98c-858c-11e5-8ea3-630fae877d6f.png)

**Comment by myleshorton** [comment]
Thanks @renkun-ken. Does it start using that much memory immediately, or does it build up over time?

**Comment by renkun-ken** [comment]
It only occasionally happens, not every time. I restart the computer and it no more happens for a few days.

**Comment by myleshorton** [comment]
OK thanks. Do you see any correlation with when it occurs? Like downloading large files maybe?

**Comment by fffw** [comment]
@renkun-ken Did you still see it occasionally with latest version?

**Comment by renkun-ken** [comment]
Sorry, it looks like it only rarely happens. I cannot reproduce this.

**Comment by fffw** [comment]
Please feel free to open new issue if that happens.
