### ISSUE TITLE
Wish lantern can Work on OpenWRT Router

### ISSUE THREAD

**Issue by qq254963746** [getlantern/lantern#3304]
Now , lantern only work on my MacBook, but iPhone, iPad, and other android device can not use it, So I was originally thinking that If it can work on my OpenWRT router , it's perfect .

**Comment by fffw** [comment]
Community contribution is welcome, but the resource is tight to work on it now.

**Comment by fffw** [comment]
BTW: Lantern Android is released and can be downloaded from https://getlantern.org
