### ISSUE TITLE
how to check whether a domain has been redirected by lantern ?

### ISSUE THREAD

**Issue by ppLorins** [getlantern/lantern#3306]
My mail app on max OSX cannot receive or send any mails (occasionally) after I install lantern.
I wanna check if the imap and smtp servers has been redirected.

**Comment by fffw** [comment]
Currently Lantern on desktop only ask supported applications to redirect HTTP/HTTPS traffic to it. IMAP and SMTP use different protocol and port, which should not be affected.

**Comment by ppLorins** [comment]
@fffw  thanks for the response , but Im afraid not . My mail app cannot connect to gmail's imap and smtp server before I install lantern , and it's reachable after install that , i'm pretty sure about this , and it must be influenced by lantern .    

If I was wrong, is there way to check lantern's log to see which request has been redirected and which are not ?

**Comment by fffw** [comment]
Lantern desktop can only handle HTTP(S) requests. Is it possible that your mail client access Gmail through it's HTTPS API? It can be the case if the client has a separate option to add Gmail account.

**Comment by ppLorins** [comment]
@fffw  yes , my gmail use a https connection because its ssl option is selected. 
Anyway , I think I need a log to check what request are redirected ..

**Comment by fffw** [comment]
Lantern does write logs, the location varies per OS, you can see it on this page https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs
