### ISSUE TITLE
Leaked connections to 8787 port

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3312]
Lots of following errors in logs. Should be HTTP requests of config update, geolookup, etc.

> ERROR flashlight.client: server.go:1777 http: Accept error: accept tcp [::]:8787: too many open files; retrying in 1s

And pairs of connections from `lsof`.
```
lantern_l 10698 lantern 1018u  IPv4 492836932      0t0       TCP 127.0.0.1:38809->127.0.0.1:8787 (ESTABLISHED)
lantern_l 10698 lantern 1020u  IPv4 492837714      0t0       TCP 127.0.0.1:38816->127.0.0.1:8787 (ESTABLISHED)
lantern_l 10698 lantern 1022u  IPv6 492836934      0t0       TCP 127.0.0.1:8787->127.0.0.1:38809 (ESTABLISHED)
lantern_l 10698 lantern 1023u  IPv6 492837717      0t0       TCP 127.0.0.1:8787->127.0.0.1:38816 (ESTABLISHED)
```

**Comment by fffw** [comment]
Found on Iran VPS, version 2.0.10

**Comment by myleshorton** [comment]
Did you restart Lantern on that machine @fffw?

**Comment by myleshorton** [comment]
Never mind @fffw I see the restart now.
