### ISSUE TITLE
lantern is not woking with chrome browser while the firefox is ok!

### ISSUE THREAD

**Issue by ninesun127** [getlantern/lantern#3323]
The other day! the chrome browser go smoothly! however, two days ago, it appears that chrome can not access the website from abroad,while the firefox still ok.
I  can not work out!please help me

**Comment by yannxia** [comment]
Me too, reinstall chrome will Ok for this time, but next you need reinstall agin. so .....

**Comment by yannxia** [comment]
@ninesun127  #3279 , uninstall thunder will Ok. it's work

**Comment by hitzhangjie** [comment]
I have same problem. My operating system is Fedora 21 x64.

**Comment by ninesun127** [comment]
@yannxia  I have already uninstall the thunder download and reinstall the chrome......the outcome is a tragedy! i burst into tears! Now every time i view abroad website,i can use any browses except chrome! i am confused !

**Comment by ninesun127** [comment]
@hitzhangjie i have gotten to say you are professional! i am sorry but i am low~~~~~i even don't know how to do by your instruction

**Comment by moitoi** [comment]
@hitzhangjie that solved my problem, thanks
