### ISSUE TITLE
Lantern didn't work anymore on my computer......

### ISSUE THREAD

**Issue by pjzhong** [getlantern/lantern#3324]
My System is Windows 10 pro, I still can used it a month ago.
but now, lantern always connecting................always connecting............. connecting

**Comment by ZhaoMiing** [comment]
same here

**Comment by wunshine** [comment]
after configed cacheBrowser,it's not work on my mac any more..

**Comment by wunshine** [comment]
after uninstall cachebrowser ,it's work now

**Comment by chenyvehtung** [comment]
so do I, although my OS is Ubuntu14.04.

**Comment by lanffy** [comment]
It's work good on my mac with chrome.:-)

**Comment by aranhoide** [comment]
We've had some problems in some of our proxies.  If your problems persist, could you send your logs to us, as described in https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs ?  Thanks!

**Comment by aranhoide** [comment]
@wunshine : thanks for your report about incompatibility with cachebrowser.  Running more than one circumvention tool at the same time may cause trouble in general.

**Comment by wuyongwen** [comment]
我也遇到这个问题了,原来是周末装过迅雷的网游加速器,卸载掉就可以用lantern了 ,应该是网络代理软件有冲突.  may be this can help u. uninstall others proxy software except lantern.

**Comment by pjzhong** [comment]
......Lantern waiting for proxy tunnel and then connecting, connection..............................
 I didn't install others proxy software except lantern
