### ISSUE TITLE
Lantern never use direct connection for non-CONNECT requests

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3325]
Detour uses whichever connection made first and ignore another, but [reverseproxy.go#L55](https://github.com/getlantern/lantern/blob/3a907ed76aeb50aeb948997f485727c668f1c7d6/src/github.com/getlantern/flashlight/client/reverseproxy.go#L55) returns detour connection immediately, so direct connection will always be late.

**Comment by myleshorton** [comment]
Good catch @fffw. I would think we'd actually want detour to determine the success or failure of a request based on receiving an actual response. Does it currently just rely on getting a connection? That will frequently result in incorrect results if so, as we'll often get a connection to our proxy prior to getting a connection to the destination site even with this fixed.

**Comment by fffw** [comment]
Sounds good to me. Will make the changes.

**Comment by myleshorton** [comment]
Awesome!

**Comment by fffw** [comment]
Oh the current `detour` structure is based on time differences of making connections, non-trivial to make this change. I also tried to change the behaviour of `balancer`, no luck.

As a workaround, we can set a 200-500ms `DelayBeforeDetour`. The performance penalty is small comparing to unconditionally proxy all non-CONNECT requests. I can add it to the ongoing refactor of `detour`.

**Comment by myleshorton** [comment]
OK interesting @fffw. I'm not convinced that purely basing this on
connection times will create accurate results, as connecting to our proxy
should generally be comparably fast. Does it seem accurate to you in
practice (i.e. does it correctly identify blocked and unblocked sites?).

Another approach would be to compare the body returned from the proxied
request to the body returned from the direct request. If they're within say
80% of each other (whatever that means =), then we could consider it
unblocked.

On Tue, Nov 24, 2015 at 4:29 AM, fffw <notifications@github.com> wrote:

> Oh the current detour structure is based on time differences of making
> connections, non-trivial to make this change. I also tried to change the
> behaviour of balancer, no luck.
>
> As a workaround, we can set a 200-500ms DelayBeforeDetour. The
> performance penalty is small comparing to unconditionally proxy all
> non-CONNECT requests. I can add it to the ongoing refactor of detour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3325#issuecomment-159253986>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
Yeah I totally agree that an algorithm comparing the time of actual responses is more accurate. Comparing responses may not work as `detour` works at TCP connection level, and the site may also respond different content to different IP.

Current `detour` implementation is rigid or even flawed and it's hard to make that change. I was trying to find a simpler, cleaner and more flexible model, but it's subtle considering the highly dynamic nature of it.

1. Both direct and detour connection can be available at any time.

2. Read/Write can be called at any time.

3. Need to resend previous sent bytes to newly available connection, and reread from it.

4. Each call need to return asap.

The purpose of setting a 500ms or so `DelayBeforeDetour` is to reduce the false positives (i.e. adding a non-blocked site to detour list). It indeed works because:

1. 500ms is enough to successfully make a connection to most non-blocked sites.

2. The delay occurs only once for each not-whitelisted-but-blocked-site in the lifetime of a Lantern instance.

3. A small delay of those resources embedded in an HTML (assets from CDN or 3rd party sites, what `detour` mainly takes effect) hardly affects user's overall experience as the HTML page is already rendered on browser.

**Comment by myleshorton** [comment]
Interesting. So maybe the delay is the best solution for now? That's ok
with me.

On Sat, Nov 28, 2015 at 10:30 PM, fffw <notifications@github.com> wrote:

> Yeah I totally agree that an algorithm comparing the time of actual
> responses is more accurate. Comparing responses may not work as detour
> works at TCP connection level, and the site may also respond different
> content to different IP.
>
> Current detour implementation is rigid or even flawed and it's hard to
> make that change. I was trying to find a simpler, cleaner and more flexible
> model, but it's subtle considering the highly dynamic nature of it.
>
>    1.
>
>    Both direct and detour connection can be available at any time.
>    2.
>
>    Read/Write can be called at any time.
>    3.
>
>    Need to resend previous sent bytes to newly available connection, and
>    reread from it.
>    4.
>
>    Each call need to return asap.
>
> The purpose of setting a 500ms or so DelayBeforeDetour is to reduce the
> false positives (i.e. adding a non-blocked site to detour list). It indeed
> works because:
>
>    1.
>
>    500ms is enough to successfully make a connection to most non-blocked
>    sites.
>    2.
>
>    The delay occurs only once for each not-whitelisted-but-blocked-site
>    in the lifetime of a Lantern instance.
>    3.
>
>    A small delay of those resources embedded in an HTML (assets from CDN
>    or 3rd party sites, what detour mainly takes effect) hardly affects
>    user's overall experience as the HTML page is already rendered on browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3325#issuecomment-160382826>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
In addition to network latency across different route, the site to access can also increase false positives. Take douban.fm as an example. It quickly gets connected and responds an 400 Bad Request page (copyright restriction) when accessed from outside China, but connects after 1.5s and renders a complex player page when accessed from the Chinese box. Even a 500ms delay before dialing detour connection doesn't resolve it.

Lantern does accelerate those sites, which is pretty good. But in this particular case, it makes the site inaccessible.

One workaround would be having user supply a few sites to always access directly, but that impacts user experience.

**Comment by fffw** [comment]
Fixed in 07d9f08cd5230b1265ef4491d493c45e4c38c33e
