### ISSUE TITLE
My Lantern could no longer run after I reboot my computer~~~(Lantern 2.0.* @ windows7/2008)

### ISSUE THREAD

**Issue by antonywong** [getlantern/lantern#3327]
For the first time I install Lantern, everything is fine. After I reboot the computer, software can not open any longer, even I reinstall it.
I have tried on several computers(windows 7/2008), and always appears the same situation.

**Comment by fffw** [comment]
@antonywong Is it still true? Do you have Xunlei installed?

**Comment by myleshorton** [comment]
@sunshine19090 can you try to reproduce this one too?

**Comment by myleshorton** [comment]
This should be fixed in the latest version available on the web site @antonywong
