### ISSUE TITLE
How to prevent Lantern from auto starting upon computer starting up?

### ISSUE THREAD

**Issue by ivanhjc** [getlantern/lantern#3328]
I couldn't find where to configure this.

**Comment by wunshine** [comment]
when you show your lantern ,you can see a config icon right bottom your browser,it's it

**Comment by xiam** [comment]
Thanks @wunshine, yes, this is the settings dialog that you can access by clicking the gear icon at the bottom right of the Lantern UI:

![screen shot 2015-11-27 at 7 03 06 am](https://cloud.githubusercontent.com/assets/385670/11441780/07119038-94d5-11e5-83de-7be8976c4ccd.png)

Please don't open issues on GitHub to ask questions, you can reach us on Facebook (https://www.facebook.com/getlantern?fref=ts) and Twitter (https://twitter.com/getlantern).
