### ISSUE TITLE
Norton AV killed the installer immediately after download - Chrome, windows 7

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3333]

**Comment by RADiEnCe** [comment]
I know that at least China likes to add circumvention tools to AV databases.

**Comment by sunshine19090** [comment]
Norton AV now removed the false detection for the version 2.0.10. 

Submitted false positive form for DrWeb and a proactive whitelisting form for Norton Anti-virus.

**Comment by sunshine19090** [comment]
Though we can proactively whitelist which many AV companies are letting us do by just submitting a form, we still need to do this for every version that we release.

**Comment by sunshine19090** [comment]
Oh and I am submitting the for both the installer and the executables.

**Comment by myleshorton** [comment]
Oh wow so there's no automated process huh?

**Comment by sunshine19090** [comment]
As far as I have researched, the only way is to go to their websites and submit a form or follow the process that is mentioned. Some needs registration like kaspersky. And we have to wait for atleast 2 days it seems. And we have to do for every version that we release, this is not a one-time thing (I wish it is :) )

**Comment by myleshorton** [comment]
Is it possible to talk with someone at any of these companies to see if
there's any way around that?

**Comment by sunshine19090** [comment]
As in to make it a one-time thing?

On Mon, Dec 7, 2015 at 4:06 PM, myleshorton <notifications@github.com>
wrote:

> Is it possible to talk with someone at any of these companies to see if
> there's any way around that?
> On Dec 7, 2015 3:51 PM, "sunshine19090" <notifications@github.com> wrote:
>
> > As far as I have researched, the only way is to go to their websites and
> > submit a form or follow the process that is mentioned. Some needs
> > registration like kaspersky. And we have to wait for atleast 2 days it
> > seems. And we have to do for every version that we release, this is not a
> > one-time thing (I wish it is :) )
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/getlantern/lantern/issues/3333#issuecomment-162708337>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3333#issuecomment-162710689>
> .
>



-- 
Regards,
Sunshine

**Comment by myleshorton** [comment]
Yeah

**Comment by sunshine19090** [comment]
Okay @myleshorton , I will see if I could get in touch with someone who could provide us some help or more insight on this.

**Comment by sunshine19090** [comment]
For now, Symantec whitelisted our software for version 2.0.10. Kaspersky lets us register with them so that we just have to upload file everytime we update (this will reduce some work).

**Comment by sunshine19090** [comment]
DrWeb removed the detection. 
![virus scan clear](https://cloud.githubusercontent.com/assets/11394369/11668557/aaca2778-9dac-11e5-92ed-a001b23d05eb.png)

**Comment by myleshorton** [comment]
Awesome sounds promising. Do you have docs on the Kaspersky upload? I
wonder if we can automate it.

On Tue, Dec 8, 2015 at 12:36 PM, sunshine19090 <notifications@github.com>
wrote:

> For now, Symantec whitelisted our software for version 2.0.10. Kaspersky
> lets us register with them so that we just have to upload file everytime we
> update (this will reduce some work).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3333#issuecomment-163010475>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by Trickister** [comment]
Am US FBI. So stop now...

**Comment by sunshine19090** [comment]
I have submitted the register form in kaspersky. They have asked for more details. I have sent them yesterday along with our files. Waiting for their reply. As per the steps in their website, once we are registered and they find us clean, then they would send us a FTP site where we can upload our files everytime we update and then intimate them. It is just in words for now, we will know how it works once we really try it. I don't see any docs about this in their website.

**Comment by myleshorton** [comment]
Awesome!

On Wed, Dec 9, 2015 at 12:54 PM, sunshine19090 <notifications@github.com>
wrote:

> I have submitted the register form in kaspersky. They have asked for more
> details. I have sent them yesterday along with our files. Waiting for their
> reply. As per the steps in their website, once we are registered and they
> find us clean, then they would send us a FTP site where we can upload our
> files everytime we update and then intimate them. It is just in words for
> now, we will know how it works once we really try it. I don't see any docs
> about this in their website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3333#issuecomment-163388924>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by sunshine19090** [comment]
McAfee is now analysing our files and probably whitelist it if they don't find any detections. They have also provided me the location to upload the files to their FTP site whenever we have a new update. So we just have to upload the files (actually open the FTP site in windows explorer and then paste our files in the given location) and then send them an email with the filenames. I think it can be automated.

**Comment by sunshine19090** [comment]
Avast added us to their whitelist.

**Comment by sunshine19090** [comment]
MCAfee whitelisted. But still we have to send our files to them for every release.

**Comment by myleshorton** [comment]
OK. It would be great to setup some sort of checklist for things we have to
do to get whitelisted by every AV company for every release.

On Tue, Jan 5, 2016 at 11:38 AM, sunshine19090 <notifications@github.com>
wrote:

> MCAfee whitelisted. But still we have to send our files to them for every
> release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3333#issuecomment-169107228>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by sunshine19090** [comment]
I scanned our files of Lantern 2.0.11 in virustotal.com and the result is clean for both installer as well as the executable.

**Comment by fffw** [comment]
@sunshine19090 What did we get so far? We can automate executable submission or make a checklist for some of the AV vendors.

**Comment by sunshine19090** [comment]
yeah sure @fffw, I can organize the details and send it to you.
