### ISSUE TITLE
The Mail would 'connect error' if I open Lantern in Mac

### ISSUE THREAD

**Issue by ChenZhongPu** [getlantern/lantern#3338]
Once I open `Lantern` in my mac, the `Mail` would raise `cannot connect error`.

I thought It is a bug, or not compatible with `OS X`. (By the way, it is `10.11.1`).

**Comment by ChenZhongPu** [comment]
Other guys have reported the same problem.

**Comment by ppLorins** [comment]
yes , I encounter this issue too
