### ISSUE TITLE
Using the same google acount in two lantern instances in two pc

### ISSUE THREAD

**Issue by albertnetymk** [getlantern/lantern#3340]
Is it supported to have two PCs, one in uncensored region, the other in censored region, I log into them both using the same google account, and connection could be established?

Don't feel so good to create a dummy google account just to get lantern to work.

**Comment by fffw** [comment]
Could you describe the problem you are facing in detail? What blocked you from using same google account in different PCs simultaneously @albertnetymk ?

**Comment by albertnetymk** [comment]
I should have tried lantern before I opened this issue. Apparently, lantern has deviated a lot from the description on its wiki:

* no give vs get mode
* no need to login using google account

Seems to work out of the box. Thank you very much.
