### ISSUE TITLE
How to use lantern proxy from mac terminal?

### ISSUE THREAD

**Issue by Youmoo** [getlantern/lantern#3341]
I can access google.com from a browser , but from a terminal ping google.com results in timeout.

**Comment by fffw** [comment]
Please Google `http_proxy` for solutions. Will close it as it's not Lantern specific issue.

**Comment by Youmoo** [comment]
@fffw 
From terminal, I run `http_proxy=127.0.0.1:16823` and ping google.com still results in timeout.
I use max osx 10.11.1

**Comment by fffw** [comment]
Lantern is a HTTP(S) proxy on desktop rather than a VPN. It does nothing to ICMP packets (what `ping` sends out).

**Comment by superstar4** [comment]
curl www.google.com also failed.

**Comment by Youmoo** [comment]
@superstar4 `curl --proxy 127.0.0.1:8787 www.google.com` works.

**Comment by superstar4** [comment]
@Youmoo  thx . i got the wrong port
