### ISSUE TITLE
400 Bad Request accessing images at photobucket.com

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3344]
One example URL: 
 >http://i1382.photobucket.com/albums/ah245/PhotobucketMKTG/Gift%20Guide%202015/Product%20Photos/Photos%20With%20Text/Calendars.png~original

It respond correct file when accessing directly.

Server for this site is `ECSF (sea/554F)`. Could be caused by non-standard compatible server, but worth take a look.

**Comment by myleshorton** [comment]
Interesting @fffw. Sounds like this is probably an issue with the proxy no? Seems like it should be possible to reproduce locally too. You want to take a look @fffw or @uaalto?

**Comment by fffw** [comment]
Yeah I'll do it

**Comment by fffw** [comment]
Ok it's caused by https://github.com/getlantern/http-proxy/issues/70 because there are space character in the URL. Deploying newest `http-proxy-lantern` will resolve this.

**Comment by uaalto** [comment]
Thank you @fffw!

**Comment by myleshorton** [comment]
Awesome @fffw!

On Sat, Dec 12, 2015 at 4:20 AM, Ulysses Aalto <notifications@github.com>
wrote:

> Thank you @fffw <https://github.com/fffw>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3344#issuecomment-164145395>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by aranhoide** [comment]
Whoops, I missed this until now, sorry.  Do we need to deploy a new
http-proxy release?
