### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3348]
Lots of users reporting this. 

```Cannot retrieve metalink for repository: fedora/21/x86_64. Please verify its pat
h and try again
INFO[0040] The command [/bin/sh -c yum -y update && yum clean all] returned a no
n-zero code: 1 ```

**Comment by myleshorton** [comment]
It looks to me like just updating the Fedora version/link in the docker image should do it.

**Comment by xiam** [comment]
That's odd @myleshorton, I tried on a fresh boot2docker machine, `make docker` works until the end with no problems. Were you able to replicate the error somehow?

**Comment by myleshorton** [comment]
I've definitely seen a similar error before. It typically works eventually, although I'm unclear why @xiam

**Comment by xiam** [comment]
It sounds like a configuration error to me. At least according to the error message and this answer: http://unix.stackexchange.com/questions/140495/cannot-retrieve-metalink-for-repository-fedora-20-i386.

I don't think we can fix that by adding something to the `Dockerfile`.

**Comment by xiam** [comment]
Hmm @myleshorton  -- I tried on a different machine with Linux, `make docker` still works in our current valencia.

I'm closing this for now, please reopen if you find a way to replicate it.
