### ISSUE TITLE
proxy under safari bug

### ISSUE THREAD

**Issue by jerryshew** [getlantern/lantern#3349]
using lantern under safari, when page loaded the first time, Css/Js and some image files can not load, need to refresh page to fetch.

**Comment by zxl777** [comment]
Replace Safari by Chrome ,
I think the team of lantern just only use Chrome.

**Comment by fffw** [comment]
@jerryshew Can you give us a few example sites so we can try to reproduce?

**Comment by zxl777** [comment]
I think I should use Chrome.
The development team to focus on improving the speed and stability is most important.

For example, watch youtube of 720P, it is very necessary.

**Comment by jerryshew** [comment]
@fffw Take [http://ionicframework.com](http://ionicframework.com) for example, sometimes display like this, maybe it's Safari's fault:

![2015-12-16 21 05 33](https://cloud.githubusercontent.com/assets/5626417/11841525/e1cc63fc-a438-11e5-988e-7c065dffea0f.png)

**Comment by myleshorton** [comment]
Do you have Lantern set to proxy all traffic @jerryshew? I.e., are you sure loading that page is actually going through Lantern?

**Comment by Alihamzehzadeh** [comment]
پشتبانی نمیکند

**Comment by shukean** [comment]
在safari 下, 我也遇到了这个问题.  请问你解决了么?

**Comment by jerryshew** [comment]
@myleshorton it going through lantern. If not use lantern, some sites can be open correctly but only very slow. when using lantern, sometimes mac app store got the same problem. **First notice this problem is when I upgrade to El Capitan**, under Yosemite it works.

**Comment by jerryshew** [comment]
@shukean 问题依旧，一台 air 跟 pro 上都有问题(都是 10.11)。

**Comment by jerryshew** [comment]
![2016-01-03 15 58 39](https://cloud.githubusercontent.com/assets/5626417/12077844/f07a4da8-b232-11e5-95d6-48f806e86308.png)
@myleshorton like this shot.
@zxl777 under Chrome, lantern did not working.

**Comment by myleshorton** [comment]
I believe this is also a version of #3039
