### ISSUE TITLE
添加下载各个平台的安装文件的选项

### ISSUE THREAD

**Issue by masakapa** [getlantern/lantern#3353]
因为访问下载页面面需要翻墙。那么我想再mac 上下载 exe 文，但是没有这个选项
谢谢!

**Comment by Rice321** [comment]
您好，您可以发送邮件到 team@getlantern.org 接收我们的下载链接。

**Comment by faonecze** [comment]
有木有linux版的呢？

**Comment by callmepeanut** [comment]
https://github.com/getlantern/lantern/releases
@faonecze 既然都用linux了，github还不会用？

**Comment by fffw** [comment]
Close in favor of https://github.com/getlantern/www/issues/33
