### ISSUE TITLE
When we have multiple servers available, use the fastest one

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3358]
It's not 100% clear what the best approach is here, but when Lantern is assigned multiple servers for whatever reason, it would be good to have logic that always chooses the fastest server. One approach would be to have some process that periodically checks all servers and ranks them, possibly only as long as Lantern is active. 

The idea would be to bypass network congestion, overloaded servers, and servers with high latency.

**Comment by myleshorton** [comment]
@fffw can you take a look at this? I think we need it for pro.

**Comment by fffw** [comment]
I found it related to https://github.com/getlantern/lantern/issues/3127

My plan is to rank by real traffic data, or even maintain a routing table for frequently visited sites (overskill maybe). Balancer is where I want to make that change.
