### ISSUE TITLE
cann't not build for linux on fedora

### ISSUE THREAD

**Issue by HappyCodeDog** [getlantern/lantern#3366]
fatal: Needed a single revision
fatal: Needed a single revision
fatal: bad default revision 'HEAD'

**Comment by fffw** [comment]
@HappyCodeDog can you post your command and logs surrounding the error messages?

**Comment by HappyCodeDog** [comment]
@fffw 

$ sudo make linux-amd64
fatal: Needed a single revision
fatal: Needed a single revision
fatal: bad default revision 'HEAD'
Missing "go" command.
Makefile:240: recipe for target 'system-checks' failed
make: *** [system-checks] Error 1

I've googled these errors. The first three are about git, which I never use before. And their solutions didn't work for me. As for the fourth message, I've installed go and docker:

$ whereis go
go: /usr/local/go
$ whereis docker
docker: /usr/bin/docker /usr/libexec/docker

I don't know how to figure out these problem, so can you give me the "rpm" binary to me? Thank you!

**Comment by xiam** [comment]
Hello @HappyCodeDog -- we currently don't have an RPM build ready, only a `.deb`, you can try to convert it to RPM using [alien][1].

We're going to keep track of this other similar issues here: https://github.com/getlantern/lantern/issues/3367

[1]: https://wiki.debian.org/Alien
