### ISSUE TITLE
Add instructions to compile lantern from source, without docker

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#3367]
Users should not be required to install docker if they only want to compile and use Lantern. We need instructions in our README for them to be able to create a binary just by using `source setenv.bash` and `go build` (or a new target `make binary` that does that). They will have to look for git, go and libappindicator by themselves, we can't help a lot with that as every Linux distro has special ways of installing things.

Explaining how to extract the binary from our `.deb` package or converting it to `.rpm` with [alien][1] should be useful as well.

[1]: https://wiki.debian.org/Alien

**Comment by 1dot75cm** [comment]
Rpm in [here](https://github.com/FZUG/repo/blob/23524eabc8964fb3b1c90669aec035ece97aed9b/rpms/SPECS/lantern/lantern.spec).
Binary [Rpm](https://repo.fdzh.org/FZUG/free/23/x86_64/golang-github-getlantern-lantern-2.1.0-3.git273a629.fc23.x86_64.rpm) for Fedora23. It's compile lantern from source without docker.

**Comment by xiam** [comment]
Thanks @1dot75cm. I'm going to close this issue since we removed the docker dependency some commits ago and I opened another one to take care of the RPM package here https://github.com/getlantern/lantern/issues/3737.
