### ISSUE TITLE
Quite a lots of CLOSED connections to 8787

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3368]
Saw from a68fecce74605c20c77764925a3df74aa5bc3f16 on issue3296 branch, but should be caused by client/handler.go or util/http.go. It finally caused "too many open files" error.

    127.0.0.1:52829->127.0.0.1:8787 (CLOSED)
    127.0.0.1:52182->127.0.0.1:8787 (CLOSED)
    127.0.0.1:8787->127.0.0.1:52067 (CLOSE_WAIT)
    127.0.0.1:52082->127.0.0.1:8787 (CLOSED)
    127.0.0.1:51832->127.0.0.1:8787 (CLOSED)
    127.0.0.1:52594->127.0.0.1:8787 (CLOSED)
    127.0.0.1:53074->127.0.0.1:8787 (CLOSED)
    127.0.0.1:53821->127.0.0.1:8787 (CLOSED)
    127.0.0.1:54316->127.0.0.1:8787 (CLOSED)
    127.0.0.1:53396->127.0.0.1:8787 (CLOSED)
    127.0.0.1:54573->127.0.0.1:8787 (CLOSED)
    127.0.0.1:53334->127.0.0.1:8787 (CLOSED)
    127.0.0.1:57594->127.0.0.1:8787 (CLOSED)
    127.0.0.1:53828->127.0.0.1:8787 (CLOSED)
    127.0.0.1:54595->127.0.0.1:8787 (CLOSED)
    127.0.0.1:57847->127.0.0.1:8787 (CLOSED)
    127.0.0.1:58095->127.0.0.1:8787 (CLOSED)
    127.0.0.1:58329->127.0.0.1:8787 (CLOSED)
    127.0.0.1:58576->127.0.0.1:8787 (CLOSED)
    127.0.0.1:58824->127.0.0.1:8787 (CLOSED)
    127.0.0.1:59076->127.0.0.1:8787 (CLOSED)
    127.0.0.1:8787->127.0.0.1:64663 (CLOSE_WAIT)
    127.0.0.1:59322->127.0.0.1:8787 (CLOSED)
    127.0.0.1:50562->127.0.0.1:8787 (CLOSED)
    127.0.0.1:8787->127.0.0.1:53675 (CLOSE_WAIT)
    127.0.0.1:65124->127.0.0.1:8787 (CLOSED)
    127.0.0.1:50538->127.0.0.1:8787 (CLOSED)

**Comment by fffw** [comment]
It still the same even with version 2.2.0, and eventually results `too many open files` error.

**Comment by myleshorton** [comment]
Oh wow @fffw are you able to consistently reproduce it? I'm going to close this in favor of #3987 but will reference it from there.
