### ISSUE TITLE
Consider upgrading to Go 1.5

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3371]
Go 1.5 has improved garbage collection (does some collection concurrently now) and also better support for cross-compilation.

**Comment by xiam** [comment]
True @oxtoacart, I recall we had a problem running a binary built with go1.5 when it was still beta but I guess we can check again.

**Comment by oxtoacart** [comment]
Definitely not something I would consider high priority, just a thought that I didn't want to lose :)

**Comment by xiam** [comment]
@oxtoacart It looks like the latest go1.5 is working well on all platforms. See https://github.com/getlantern/lantern/pull/3395

**Comment by xiam** [comment]
https://github.com/getlantern/lantern/pull/3395

**Comment by oxtoacart** [comment]
@xiam That was quick!
