### ISSUE TITLE
可以支持socks代理吗？

### ISSUE THREAD

**Issue by YDEKQ** [getlantern/lantern#3372]
我有个程序只能通过socks来连接，请问lantern支持socks代理吗？

**Comment by callmepeanut** [comment]
支持socks的很多了，比如shadowsocks和https://github.com/v2ray/v2ray-core

**Comment by shawwokou123** [comment]
Buzhich不支持

**Comment by yfdyh000** [comment]
Duplicate of #2075.

**Comment by fffw** [comment]
The SOCKS5 proxy listens at localhost:8788.
