### ISSUE TITLE
lantern-mobile闪退

### ISSUE THREAD

**Issue by xubin990510** [getlantern/lantern#3373]
RT，设备是nexus5 官方未root 601，在打开开关后看到了请求VPN权限的对话框 还没来得及点OK就闪退了（FC）
![screenshot_20151230-105534](https://cloud.githubusercontent.com/assets/7804730/12045727/375db70c-aee4-11e5-97ad-45aa60c55f2e.png)

**Comment by xubin990510** [comment]
Anyone on this? I'm translating it into English below:
The app keeps FC-ing on my Nexus 5 with Marshmallow (Stock 6.0.1 no root). The FC dialog (prompting me to press OK to stop the program) came before the dialog asking for VPN permission, and 2 times after granting it the permission.
Haven't rooted and don't have access to a PC so can't get `logcat` currently.

**Comment by fffw** [comment]
@xubin990510 Have you tried latest version?
CC @atavism
