### ISSUE TITLE
please listen on 0.0.0.0 not 127.0.0.1

### ISSUE THREAD

**Issue by mcenroer** [getlantern/lantern#3374]
Only local host can access lantern now, because lantern services listen on 127.0.0.1,please let it use default interface or 0.0.0.0 when creating socket,so either local host or remote hosts can access lantern.

**Comment by xiam** [comment]
You can easily achieve this by using the -addr parameter like this:

```
/path/to/lantern/binary/lantern -addr 0.0.0.0:8787
```

**Comment by mcenroer** [comment]
No, I can not. Because what you said will let pac file return wrong proxy address as 0.0.0.0:8787 and break local and remote hosts using pac file. So I must designate the real IP address manually, if the host running lantern is multihomed, it can only be accessed from one subnet. The best way is using default interface or 0.0.0.0 when creating socket and generating pac file with the local address returned by getsockname(), then it will be fine in all cases including multi-homed host.
