### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by wlmqljj** [getlantern/lantern#3377]
Dear engineers,
I'm one of your product---lantern's user. I really        like your idea to hit against GFW, but the lantern      is more and more famous ,so there are more and more people use lantern to hit against with GFW  
so that some people use Ping to find what is the fastest IP,that make the server unbalanced and more slow. I would like engineers can hide the service's IPs.
2. I think you maybe used to hear 360,this company join the GFW plan,and his client will find  which software hit aginst GFW,and it will upload  the software's service's IPs.In China,many software use ie's core to connect the Internet ,but 360 can scan the IE connect which IP ,then upload to the GFW,so this IP will be blocked,I would like you can refuse IE to use lantern.
 Here are my some advices ,I wish you can accept    
 these advices.
 Have a good day!
                                                                              yours,one of the users

**Comment by wlmqljj** [comment]
Sorry I write heat wrongly,It should be hit

**Comment by iliul** [comment]
@wlmqljj 挺好的建议，翻墙的大部分都是程序员，程序员基本都在用chrome&Firefox，IE不支持也好，还有鄙视用360的程序员。

**Comment by Ive4** [comment]
还是放弃360吧，太坑爹了，就是你们这种成天360的人导致html要各种兼容，严重鄙视你

**Comment by HongkaiWen** [comment]
I hope lantern can always be available.
I use lantern on my pc and android phone for about a week, it's so great.
I've used onavo on ipone and ipad for more than 1 years, it's great and always avalible,but it not support windows and android.
I don't care about the politics ,  just want to study IT technology on the internet.

**Comment by fffw** [comment]
Thanks @wlmqljj we are trying hard to make Lantern service stable while keeping away from the censors, include hiding IPs to them.
