### ISSUE TITLE
how to start lantern on ubuntu14.04?

### ISSUE THREAD

**Issue by saintthor** [getlantern/lantern#3386]
i downloaded the deb file:
lantern-installer-beta-64-bit.deb
 
installed. run in terminal:
$ lantern

then firefox opens a page:
http://127.0.0.1:16823/

shows:
Welcome to Lantern! You can now access blocked sites.

but i can not access the blocked sites.

what should i config besides these steps?

**Comment by kashuorg** [comment]
![1. Chromium & SwitchyOmega](http://ww2.sinaimg.cn/large/9c4ddab1gw1ezmb4wq9hxj210p0g2tei.jpg)

![2. Chromium & SwitchyOmega](http://ww1.sinaimg.cn/large/9c4ddab1gw1ezmb6mgorxj211y0lcqci.jpg)

**Comment by saintthor** [comment]
thank you. it works.
