### ISSUE TITLE
why lantern can not use with windows10?

### ISSUE THREAD

**Issue by iller6** [getlantern/lantern#3387]
i am use the newest lantern and chrome with windows10.

**Comment by iliul** [comment]
@iller6 
我在使用Windows 10 没有问题呢，你可以尝试在chrome上执行：chrome://net-internals/#proxy，来检查代理是否生效了？下面是执行结果！

Effective proxy settings

PAC script: http://127.0.0.1:16823/proxy_on.pac
Source: SYSTEM

**Comment by geosmart** [comment]
chrome中输入chrome://net-internals/#proxy ，点击re-aplly setting后在别的浏览器可以访问墙外网站了，但是chrome中还是不行！@iliul  请教怎么解决

**Comment by iliul** [comment]
@geosmart "点击re-aplly setting后在别的浏览器可以访问墙外网站了，但是chrome中还是不行！"，额，奇怪了，chrome有什么特殊呢？是否按了别的代理插件如switchySharp类的呢，再者我知道的就是windows下迅雷会影响。其它不知道了。

**Comment by oxtoacart** [comment]
@geosmart Are you still having this issue?  Did you download Lantern from our website or did you build it yourself?  Are you using a proxy switching plugin like SwitchySharp?

**Comment by Rice321** [comment]
请问是不是在chrome里有去除广告的插件？或者电脑里有装迅雷吗？ @iller6 @geosmart

**Comment by geosmart** [comment]
@Rice321 @iliul  还没闹明白什么原因导致有近一周用不了，不过chrome这次升级后又可以顺利lantern了，谢谢！

**Comment by fffw** [comment]
Will close this @geosmart . Feel free to create new issue with more details!
