### ISSUE TITLE
What's the problem that some websites show "gateway timeout" but others work well

### ISSUE THREAD

**Issue by Larry-Liang** [getlantern/lantern#3390]
for example, I can't access pixiv, but google, youtube, twitter are OK

**Comment by RADiEnCe** [comment]
seeing the same problem.
site: moae.jp

**Comment by fffw** [comment]
@Larry-Liang @RADiEnCe `gateway timeout` just means Lantern proxy couldn't reach the site in reasonable time. It could be various reasons, e.g., Internet routing problem, network glitches, site temporarily overloaded, etc.
