### ISSUE TITLE
Lantern could not use in Microsoft Edge.

### ISSUE THREAD

**Issue by YohoYang** [getlantern/lantern#3393]
I have setup Lantern in my Windows 10 and I use Edge as my default browser. But Lantern could not use in Edge. I try it on IE and Chrome, and it works fine. I hope you will fix the issue.

**Comment by zhangzuizui** [comment]
I found it worked well on my surface pro3(with Edge).Though I don't know why the welcome page is not occur,Lantern still works.

**Comment by YohoYang** [comment]
As your comment, I found there are some logs build when I use Edge but could not open any page include welcome page.

**Comment by myleshorton** [comment]
This is fixed in 2.1.0
