### ISSUE TITLE
客户端通过linux server代理访问lantern

### ISSUE THREAD

**Issue by chenkete** [getlantern/lantern#3394]
由于公司网络无法访问外国ip地址，平时都是通过一台代理服务器上github等网站。
请问如何配置一台代理服务器将数据中转到lantern

**Comment by iliul** [comment]
@chenkete 在一台设备上部署lantern，配置代理IP为0.0.0.0，然后其它机器配置这台设备IP就应该可以了

参考下这里：
https://github.com/getlantern/lantern/issues/2940#issuecomment-169912117

**Comment by chenkete** [comment]
好的，非常感谢
看了下#2940，发现有一点危险性，因为我们的代理服务器是放在公网中，该做法可能会导致其他人也可以使用本服务器的代理，请问安全性该如何解决呢？

**Comment by fffw** [comment]
I should say it's out of the scope of Lantern. You can protect it the same way you protect your existing proxy server to GitHub etc. If your existing proxy server supports upstream proxy, you can run Lantern listen on localhost and pointing your existing proxy server to it.
