### ISSUE TITLE
Prompt user for key internal errors

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3398]
Inspired by [an user submitted log](https://groups.google.com/a/getlantern.org/forum/#!topic/team/N5sUrH7d0Pw). When Lantern is unable to set PAC, user doesn't know what happens. Other common errors include "no route to host".

> Jan 10 03:45:27.556 - 0m0s ERROR flashlight: pac.go:163 Unable to set lantern as system proxy: Unable to execute C:\Users<masked>\AppData\Roaming\byteexec\pac-cmd.exe: fork/exec C:\Users<masked>\AppData\Roaming\byteexec\pac-cmd.exe: This program is blocked by group policy. For more information, contact your system administrator.

**Comment by myleshorton** [comment]
Very interesting. That's another case where browser extensions would be
helpful.

**Comment by fffw** [comment]
Lantern can redirect to the diagnostic page (https://github.com/getlantern/lantern/issues/3288)

We are towards it (https://github.com/getlantern/lantern/issues/4024)
