### ISSUE TITLE
Only works on browsers?

### ISSUE THREAD

**Issue by dss886** [getlantern/lantern#3403]
I am in China, and ready to use Lantern to update my Android Studio (need to connect Google's server), but shows time out. Using terminal to ping google.com, also time out.

checked the "proxy all traffic" option does no help

**Comment by aranhoide** [comment]
Sorry, currently Lantern will only proxy HTTP/HTTPS traffic.  Ping is not supposed to work, and updating your Android Studio will only work if it's done via HTTP or HTTPS.  I imagine you can download a new Android Studio installer, but I realise this is probably not ideal for you.

The "proxy all traffic" option enables proxying of all sites, but it doesn't enable any other protocols.
