### ISSUE TITLE
chrome can't use lantern

### ISSUE THREAD

**Issue by itachi321** [getlantern/lantern#3404]
at first,it works,but when i reboot my computer,chrome can't use lantern any more

**Comment by looper1234** [comment]
did you just install the xpress version of thunder (迅雷)?
it seems to stop lantern from working.

**Comment by itachi321** [comment]
thank you

**Comment by lowzj** [comment]
when I enable chrome extension 'Proxy SwitchyOmega', the lantern can't work in chrome as well. It works well after disable SwitchyOmega.

**Comment by myleshorton** [comment]
This is related to #3017, #3040, #541, #2723, etc. Closing!
