### ISSUE TITLE
Lantern Mobile Crashes on Android 6.0

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3408]
When testing, I was able to get my build of lantern-mobile to run on my Nexus 5 phone with Android 5.1.1 (API Level 22), but when I tried running it on an emulator with Android 6.0 (API Level 23), it crashes with the below error:

```
01-19 10:18:46.043  1119  1156 E AndroidRuntime: Process: org.getlantern.lantern, PID: 1119
01-19 10:18:46.043  1119  1156 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/org.getlantern.lantern-1/lib/arm/libgojni.so: has text relocations
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at go.LoadJNI.<clinit>(LoadJNI.java:5)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:324)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:285)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at go.Seq.<clinit>(Seq.java:23)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at go.client.Client$Provider$Stub.<init>(Client.java:49)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at org.getlantern.lantern.sdk.Lantern.<init>(Lantern.java:44)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at org.getlantern.lantern.vpn.LanternVpn.<init>(LanternVpn.java:30)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at org.getlantern.lantern.vpn.Service.run(Service.java:52)
01-19 10:18:46.043  1119  1156 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

It looks like the Go binary has text relocations, which Android doesn't like, but prior to API Level 23 it just warned about this, whereas now it errors.

See https://github.com/golang/go/issues/9210 for some relevant discussion.

I'm building an emulator with API Level 22 to see if that works.

**Comment by oxtoacart** [comment]
I confirmed that it does work on an emulator running Android 5.1.1.  I'm pretty sure it's related to [this](https://github.com/golang/go/issues/12890).  It looks like we would either need to build using Go's tip (seems risky) or target and SDK older than 23.0.

@atavism @xiam Any reason we're targeting 23.0 or can we use something older?

**Comment by atavism** [comment]
Thanks, @oxtoacart! I actually resolved this (by downgrading the target SDK to 22, as you mention), prior to our release about 2 weeks ago, when it became clear Lantern wasn't working on Android 6.0 at all. I'll update the lantern-mobile branch with that change.
