### ISSUE TITLE
Consider eliminating stathub and associated RedisLabs subscription

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3410]
At the moment, we don't appear to be using statshub anymore.  It used to help feed the world map visualization in the UI, but since we're not using that, we could potentially get away without statshub anymore.  If the RedisLabs instance that's backing statshub is no longer in user, we could save a fair amount of money by retiring that.

**Comment by fffw** [comment]
@myleshorton @oxtoacart I think we no longer use statshub, right?

**Comment by oxtoacart** [comment]
The newest client code does not use statshub.  I think it's safe to turn it off (or at least reduce it to the smallest available dyno size).

**Comment by myleshorton** [comment]
Yeah agreed @oxtoacart!

**Comment by oxtoacart** [comment]
Okay, I've deleted the Redis instance and the Heroku application.  I'm leaving the BigQuery data around in case we ever want to query it.  The Redis data is backed up to S3 should we ever want to revive it.

**Comment by oxtoacart** [comment]
cc @uaalto
