### ISSUE TITLE
Stress test DO proxies, find what breaks first

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#3413]
The latest DO-hosted proxy to automatically split itself due to high load dates back to November 19.  From the github logs, that's around the time we deployed the golang-based http proxy (chalk one up for go!).

We haven't had many Vultr proxies split for this reason since, either; the vast majority of Vultr proxies were split because of high traffic usage (a check that we don't perform in DO).

Recently I've seen some DO proxies fail too often, often linked to a peak in traffic.  In a [recent case](https://github.com/getlantern/support/blob/master/backend-log.md#0059-split-fp-doams3-20151201-01118816610205-due-to-checkfallbacks-failures), we've had a peak of 21Mbps, so it was expected that some requests would be dropped.  The strange thing is that syslog shows that the machine's 15m load average never got past 0.5.  CPU peaked at some 37% and disk activity remained low, which indicates that the machine never had memory problems.

While we could just lower our load average thresholds for splitting and retiring machines, it would be nice to learn whether there is any other detectable thing failing.

[This should be done for Thursday so I somewhat arbitrarily chose a milestone due in the past.]

**Comment by uaalto** [comment]
@oxtoacart in case it may help, there is a history of tests performed to the http-proxy project in its issues.
I think `siege` may help for this, is what I used to find a leak that required tens of thousands of specific requests to be noticed.

**Comment by oxtoacart** [comment]
So, I hit that server from my laptop using lantern as a client and driving load with boom:

```
boom --disable-keepalive -allow-insecure -n 100000 -c 100 -x http://localhost:8787 http://speedtest.ams01.softlayer.com/downloads/test10.zip
```

`vnstat -l` reported traffic of about 15-40 Mbit/s during the test, usually staying in the low 20s.

The test initially ran fine for several minutes, during which time I monitored `top` and `lsof`.  For a while, the short term load average stayed below 0.5, but eventually it did creep up to 0.89. Resident memory for lantern stayed below 400 MB or so, and CPU usage was generally in the low double digits but showed very spiky behavior (sometimes jumping into the 80s and 90s).  I did not see anything that looks like a file descriptor leak, with the server processes' file descriptor counts staying in the hundreds.

However, after running for a while, the server system became unstable, in particular my ssh sessions started hanging and timing out.  A few of the boom requests hung and I had to manually terminate the test.  Results are shown below.  After stopping boom, the system did seem to recover.

Overall, this seems to back up the hypothesis that this is not a code problem with the lantern server but rather something with the OS, network interface, virtualization stack or network infrastructure at Digital Ocean.

```
➜  boom git:(master) ✗ boom --disable-keepalive -allow-insecure -n 10000 -c 100 -x http://localhost:8787 http://speedtest.ams01.softlayer.com/downloads/test10.zip
9985 / 10000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 99.85 % ^C
Summary:
  Total:	392.0246 secs.
  Slowest:	31.9038 secs.
  Fastest:	0.3062 secs.
  Average:	2.8582 secs.
  Requests/sec:	25.4703
  Total Data Received:	114821629952 bytes.
  Response Size per Request:	11499412 bytes.

Status code distribution:
  [200]	9953 responses
  [503]	32 responses

Response time histogram:
  0.306 [1]	|
  3.466 [8186]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  6.626 [732]	|∎∎∎
  9.785 [667]	|∎∎∎
  12.945 [60]	|
  16.105 [177]	|
  19.265 [67]	|
  22.424 [4]	|
  25.584 [29]	|
  28.744 [0]	|
  31.904 [62]	|

Latency distribution:
  10% in 0.6176 secs.
  25% in 1.1791 secs.
  50% in 1.7952 secs.
  75% in 2.1844 secs.
  90% in 7.9317 secs.
  95% in 8.7287 secs.
  99% in 17.1039 secs.
9986 / 10000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 99.86 %
```

**Comment by oxtoacart** [comment]
@aranhoide @uaalto @myleshorton Anything else you guys think we should test here or can I close this?

**Comment by myleshorton** [comment]
You can probably close it. Anything else you guys can think of that could
cause that outside if their environment other than memory, CPU, disk, and
file descriptors? Were the CPU spikes at all correlated with the ssh and
hanging issues?

**Comment by oxtoacart** [comment]
I can't say for certain that the CPU spikes correlated to the ssh timeouts.

**Comment by uaalto** [comment]
This behavior resembles that of TCP incast, which is a major problem in datacenter. Since it is a lower layer issue, is probably hard to test this possibility. One simple technique I know if is reducing timeouts. We can try reducing it and see if it changes the behavior. This is a long shot anyway.

**Comment by aranhoide** [comment]
That was very helpful, thanks!

I think this argues, mid term, for deploying 512MB instances, so either our machines become the bottleneck and our auto-scaling starts working again, or we get 2x bang for our buck.

As an immediate measure to make auto-scaling work in our existing setup, I'll lower split load averages to about 0.4, and retire machines at 0.5.

Another thing we could do is react on checkfallbacks failures.  That'd be a bit more involved, since we're running the checker on all production cloudmasters, and we need to somehow gather and interpret the results.  Not hard, but not something I'd feel confident about deploying today either.
