### ISSUE TITLE
mac os10.5上使用后，突然不使用lantern的时候，无法访问外网只能上qq？

### ISSUE THREAD

**Issue by weinierfei** [getlantern/lantern#3414]
mac os10.5上使用后，突然不使用lantern的时候，无法访问外网只能上qq，内网也是只能访问部分？

**Comment by enolate** [comment]
我遇到了同样的问题。你找到解决办法了吗？

**Comment by weinierfei** [comment]
最后没有解决,系统还原都不好使,最后全新安装系统

**Comment by fffw** [comment]
It's interesting that you can use Lantern on OSX 10.5 as Lantern officially supports 10.8+
Unfortunately, we don't have an environment to reproduce. It could be an unrecovered system proxy setting but not sure.
