### ISSUE TITLE
/bin/bash: make: command not found make: *** [genassets] Error 127

### ISSUE THREAD

**Issue by folgerhuang** [getlantern/lantern#3415]
Step 34 : RUN mkdir -p $WORKDIR
 ---> Using cache
 ---> dc94d7192ab7
Step 35 : RUN mkdir -p $SECRETS
 ---> Using cache
 ---> 5734ebc06c3c
Step 36 : VOLUME $WORKDIR
 ---> Using cache
 ---> 0724cc54b2f4
Step 37 : WORKDIR $WORKDIR
 ---> Using cache
 ---> 833a29de0b26
Successfully built 833a29de0b26
Generating assets...
/bin/bash: make: command not found
make: *** [genassets] Error 127

I don't know why promot this error, cause i have installed make. Guys,I do need your help!!!
[root@hadoopmaster lantern-valencia]# make -version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by fffw** [comment]
The error you got is reported from docker container. You can try following to verify if `make` is installed. If not, you may need to clean up relevant docker images and run `make docker` again.

```
docker run -t lantern-builder /bin/bash -c "make -version"
```

**Comment by folgerhuang** [comment]
@fffw 
I run your comand,and still got the message.
[root@hadoopmaster lantern-valencia]# docker run -t lantern-builder /bin/bash -c "make -version"
/bin/bash: make: command not found
What should i do next?

**Comment by fffw** [comment]
@folgerhuang Please refer Docker documentations to list and remove docker images. Basically, you can do below to fully clean them up.

```
docker rm `docker ps --no-trunc -aq` # remove all containers
docker rmi `docker images --no-trunc -aq` # remove all images
```

**Comment by folgerhuang** [comment]
@fffw 
hi, i find the problem  of '/bin/bash: make: command not found make', because i comment out line 72 and 73 @Dockfile when  i  got the following error. so ,how can i set the configurations to make the gem to install fpm from https://ruby.taobao.org/ rather https://api.rubygems.org?  

Step 30 : RUN gem install fpm
 ---> Running in 6e8bbe684d7a
ERROR:  Could not find a valid gem 'fpm' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/latest_specs.4.8.gz)
The command '/bin/sh -c gem install fpm' returned a non-zero code: 2
make: *** [docker] Error 1

**Comment by folgerhuang** [comment]
hi,@fffw , how to let the "make docker" install fpm from  https://ruby.taobao.org/ , I am in China. Thank you!
Step 17 : RUN gem install fpm
 ---> Running in 6ee842fe6e5f
ERROR:  Could not find a valid gem 'fpm' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/latest_specs.4.8.gz)
The command '/bin/sh -c gem install fpm' returned a non-zero code: 2
