### ISSUE TITLE
When I quit Lantern,I cannot connect to the Internet

### ISSUE THREAD

**Issue by geniusfhr** [getlantern/lantern#3417]
Mac OSX 10.9,When I quit Lantern,I cannot connect to  the Internet,How to solve this problem?

**Comment by wutaizeng** [comment]
`+1 `
- Mac OSX 10.11.3 
- Lantern 2.0.16 (20160219.041128)

**Comment by myleshorton** [comment]
Do you have any proxy setting in your network preferences after Lantern quits @geniusfhr or @wutaizeng?

**Comment by wutaizeng** [comment]
@myleshorton  No, but i have a proxy setting before Lantern first start.

**Comment by myleshorton** [comment]
This is almost certainly the same root cause as #3039. Closing in favor of that ticket.
