### ISSUE TITLE
Update manoto link from dashboard

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3420]
https://www.manototv.com/iran?utm_campaign=manotolantern

**Comment by oxtoacart** [comment]
@xiam Is this included in the build that you and @myleshorton are putting together right now?

**Comment by xiam** [comment]
@oxtoacart Yes, this one: https://github.com/getlantern/lantern/pull/3446

**Comment by myleshorton** [comment]
Closing.
