### ISSUE TITLE
如何设置全局代理

### ISSUE THREAD

**Issue by molixiaoge** [getlantern/lantern#3423]
windows系统下使用的软件被墙，如何设置lantern全局代理整个系统?

**Comment by houpe** [comment]
http://wenku.baidu.com/link?url=5Wb66TcG8jSBImBTIxriCUp6KaYd6sLZ20SS4emUgjyVs14GegIVKmGVlM7CSs56V7_vcJgfbewD2372Qd1hkUO4wI4JH5rbGxiP5DHN26K

**Comment by houpe** [comment]
gao duan dian a , yong english...tai low le..

**Comment by fffw** [comment]
Lantern will set system http(s) proxy automatically. You can also point SOCKS proxy to `localhost:8788`

**Comment by Jaggle** [comment]
@houpe ，who qinding ed you to say that ?too naive (just joking,:))
