### ISSUE TITLE
Lantern does not work on Debian

### ISSUE THREAD

**Issue by echaos** [getlantern/lantern#3430]
OS: Debian 8.2 jessie
Kernel: x86_64 Linux 3.16.0-4-amd64
When I run lantern, it says I can browser blocked site. And the end of google address changes to jp.But it just cannot load the page, other blocked sites are the same.
When I run lantern again by terminal.
OUTPUT:
Running installation script...
/usr/lib/lantern/lantern-binary: OK
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.logging: logging.go:50 Placing logs in /home/jin/.lantern/logs
Jan 25 04:46:26.477 - 0m0s DEBUG i18n: translate.go:106 Setting locale en_HK
Jan 25 04:46:26.480 - 0m0s DEBUG flashlight: flashlight.go:228 ---- flashlight version: 2.0.10, release: 2.0.10, build revision date: 20151009.024157 ----
Jan 25 04:46:26.481 - 0m0s DEBUG flashlight.config: config.go:286 Using config dir /home/jin/.lantern
Jan 25 04:46:26.481 - 0m0s DEBUG flashlight.config: config.go:128 Checking config path: /home/jin/.lantern/lantern-2.0.10.yaml
Jan 25 04:46:26.481 - 0m0s DEBUG flashlight.config: config.go:94 File exists at /home/jin/.lantern/lantern-2.0.10.yaml
Jan 25 04:46:26.610 - 0m0s DEBUG flashlight.config: config.go:119 Found 1 chained servers
Jan 25 04:46:26.718 - 0m0s DEBUG yamlconf: yamlconf_disk.go:52 Configuration changed on disk, applying
Jan 25 04:46:26.718 - 0m0s DEBUG yamlconf: yamlconf.go:152 Loading per session setup
Jan 25 04:46:26.756 - 0m0s DEBUG yamlconf: yamlconf_disk.go:86 Configuration changed programmatically, saving
Jan 25 04:46:26.883 - 0m0s DEBUG flashlight.config: config.go:217 Returning config
Jan 25 04:46:26.883 - 0m0s DEBUG flashlight: flashlight.go:191 Processed config
Jan 25 04:46:26.883 - 0m0s DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Jan 25 04:46:26.883 - 0m0s DEBUG flashlight: flashlight.go:205 Running proxy
Jan 25 04:46:26.894 - 0m0s DEBUG flashlight.config: bootstrap.go:140 Opening bootstrap file from: /home/jin/.lantern/.packaged-lantern.yaml
Jan 25 04:46:26.894 - 0m0s DEBUG flashlight.config: bootstrap.go:57 Opening file at: /home/jin/.lantern/.packaged-lantern.yaml
Jan 25 04:46:26.903 - 0m0s DEBUG flashlight.config: bootstrap.go:68 Read bytes: startupurl:
Jan 25 04:46:26.903 - 0m0s DEBUG flashlight: flashlight.go:355 Hitting local URL: http://127.0.0.1:16823/startup
Jan 25 04:46:26.904 - 0m0s DEBUG flashlight: flashlight.go:364 Got response from local Lantern: 200 OK
Jan 25 04:46:26.904 - 0m0s DEBUG flashlight: flashlight.go:481 Calling exit func
DEBUG flashlight: flashlight.go:481 Calling exit func
DEBUG flashlight: flashlight.go:484 No exit func remaining, exit now
DEBUG flashlight: flashlight.go:145 Lantern stopped
DEBUG flashlight: flashlight.go:148 Error closing log: invalid argument
ERROR flashlight: flashlight.go:143 Unable to start UI: Unable to listen at 127.0.0.1:16823: <nil>. Error is: listen tcp4 127.0.0.1:16823: bind: address already in use

**Comment by ayooby** [comment]
For me twitter or FB.com it doesn't work.

but 9GAG is open for me!

Ubuntu 15.10

**Comment by uaalto** [comment]
It seems like you have other software using the same port as the UI (16823). In order to confirm this, we would need you logs. Would you mind sending them? https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

Thank you!
