### ISSUE TITLE
Peerscanner test is failing

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3434]
cc: @aranhoide 

```
--- FAIL: TestCreateAndRefresh-2 (0.17s)
	Location:	cfr_test.go:47
	Error:		No error is expected but got Processing your request will cause you to exceed the maximum number of distributions allowed.
	Messages:	Should be able to create distribution
```

**Comment by myleshorton** [comment]
Yeah this is actually because @getlantern/greatfirebot is using our same bucket, and amazon won't increase our distribution limit. Tempting to just create a separate account, but also peerscanner isn't used ATM.

**Comment by oxtoacart** [comment]
Should I at least delete test distributions in the unit test?

**Comment by myleshorton** [comment]
yeah i think so -- one's the test itself creates? that would be great!

**Comment by oxtoacart** [comment]
Consider it done.

**Comment by oxtoacart** [comment]
Actually, it's probably safer just to skip the test for now :)
