### ISSUE TITLE
Run process that automatically updates the cloud masquerade configs daily

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3437]
Basically, do what we do manually right now with `genconfig.bash`.  We need this because CloudFront certificates go bad relatively quickly, so we need to update the configs pretty frequently.

**Comment by oxtoacart** [comment]
cc: @myleshorton

**Comment by myleshorton** [comment]
@aranhoide can you add this one to your list?

**Comment by aranhoide** [comment]
This is already working on the lantern_aws project.  I think this new setup calls for some changes in genconfig itself.  I've added them in the following PR:

https://github.com/getlantern/lantern/issues/3511

Feel free to close this issue as soon as that PR is merged or rejected.

**Comment by oxtoacart** [comment]
#3511 has been merged.
