### ISSUE TITLE
lantern not work on ubuntu

### ISSUE THREAD

**Issue by imasood** [getlantern/lantern#3441]
lantern isn't work for me on ubuntu 15.10
where is problem?

thanks

**Comment by SmilingNavern** [comment]
Could you please elaborate? what do you mean by don't work? How can i reproduce your problem?(provide required steps)

**Comment by imasood** [comment]
when i click on lantern icon, program runs correctly but when i try to open twitter or facebook I get an error in chrome.
thanks

**Comment by kashu** [comment]
Go to Chrome/Chromium --> Extentions --> SwitchyOmega --> PROFILES

![](http://ww3.sinaimg.cn/large/9c4ddab1jw1f14xshkt8nj20rw0lcgsk.jpg)

or 

![](http://ww1.sinaimg.cn/large/9c4ddab1jw1f14xsq79t2j20rw0lc0xb.jpg)

**Comment by uaalto** [comment]
Thank you for posting this instructions @kashu !
I'll be closing this because we have no more news from the op and there wasn't any information that we could use to actually identify a bug.
