### ISSUE TITLE
yamlconf: yamlconf.go:228 Custom polling failed: Unexpected response status: 503

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3443]
Seeing a bunch of instances of this in Loggly. 503 is "service unavailable". Sounds related to the dip in config server requests reported earlier.

**Comment by aranhoide** [comment]
The config-server app itself only ever returns `500 Internal Error in config server.` in case of errors.  Also, not many 5xx errors are reported in Heroku metrics.  So maybe this is something with Cloudflare/CloudFront?

**Comment by uaalto** [comment]
This sounds like a transient issue that was fixed. Should I close it @atavism @aranhoide ?
