### ISSUE TITLE
Does anybody have built lantern based on docker CentOS image? 

### ISSUE THREAD

**Issue by folgerhuang** [getlantern/lantern#3445]
[root@sy lantern]# ls
bin               installer-resources      LICENSE     prehook.sh     run.bash
doc               lantern_linux_386        Makefile    pre-push       setenv.bash
Dockerfile        lantern_linux_amd64      pkg         README-dev.md  src
envvars.bash.enc  lantern_windows_386.exe  pre-commit  README.md      testpackages.txt
[root@sy lantern]# ./lantern_linux_amd64 
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.settings: settings.go:69 Could not read file open /root/.lantern/settings.yaml: no such file or directory
DEBUG flashlight.ui: service.go:135 Accepting websocket connections at: /data
DEBUG flashlight.settings: settings.go:146 Sending Lantern settings to new client
DEBUG flashlight.ui: ui.go:52 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.settings: settings.go:69 Could not read file open /root/.lantern/settings.yaml: no such file or directory
DEBUG flashlight.ui: service.go:135 Accepting websocket connections at: /data
DEBUG flashlight.settings: settings.go:146 Sending Lantern settings to new client

(lantern_linux_amd64:30967): Gtk-WARNING **: cannot open display: 
[root@sy lantern]#

**Comment by uaalto** [comment]
Hi! Unfortunately, we are only supporting building from our own Docker scripts.
