### ISSUE TITLE
doesn't work in ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by CNairbird** [getlantern/lantern#3447]
I use .deb file installed lantern today afternoon successfully. But when I click it icon to start it.
It seems like doesn't work. Nothing have happened after i click it.
My ubuntu system has already installed chrome.

So, does anyone met this issue before? I'm waiting for the help.

**Comment by andydkcat** [comment]
Try to launch lantern in terminal:
`$ lantern`

In my ubuntu, it gives me the error info:

> error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

So I fixed it by installing `libappindicator3-1`:
`$ sudo apt-get install libappindicator3-1`

You can try to run it in terminal, then paste the error message here, that will be easy to fix by community.

**Comment by uaalto** [comment]
Thank you for the explanation @andydkcat! I hope you made it work @CNairbird

**Comment by program-dog** [comment]
Maybe we do not need **libappindicator3**. Here is a [solution](https://github.com/program-dog/lantern/releases)!  @CNairbird @uaalto

**Comment by xiam** [comment]
Thanks @program-dog! if you did any source code modifications please create a PR as we cannot test nor endorse third party binary files for security reasons.

**Comment by program-dog** [comment]
You can [do it yourself](https://github.com/getlantern/lantern#building-lantern-for-running-on-a-server) if you do not trust this for security reasons. @xiam

**Comment by kolenj** [comment]
@andydkcat nice thx
