### ISSUE TITLE
Lantern on IPad

### ISSUE THREAD

**Issue by zhpower** [getlantern/lantern#3449]
hi,
I use lantern on my PC and android device. It's really great software. but i cannot find the ios version for ipad/iphone.
Do you plan to develope a ios version? or is there a replaced method on ipad?
Thanks.

**Comment by muyufan** [comment]
Use ccproxy's Feature 'cascading ' in PC as a proxy, then setting proxy on your ios or android device.

**Comment by uaalto** [comment]
Hi @zhpower. We plan to builld Lantern in the future, but in the meantime you can do what @muyufan says.
