### ISSUE TITLE
lantern not work on OS X EI Capitan

### ISSUE THREAD

**Issue by Lillianmin** [getlantern/lantern#3450]
Safari 无法连接到代理服务器
“无法打开页面，因为 safari 无法连接到安全 web 代理服务器 HTTPS ”

or 
Unable to get a connection: Still unable to dial tcp://doesnotexist.com:80 after 3 attempts issue.

**Comment by mcjoeng** [comment]
有那么多国家有网络管制？为什么多数issues都是英文的  很多地方都有墙？

**Comment by myleshorton** [comment]
I believe this is unrelated to OSX version, @Lillianmin and @mcjoeng. Is it working for you now with Lantern 2.0.16?
