### ISSUE TITLE
The download link in the website should direct to Lantern-android-beta

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3460]
The link should be modified both in the welcome screen as well as in the Thanks! Tell your friends about Lantern Mobile pop-up screen.

![image](https://cloud.githubusercontent.com/assets/11394369/12662861/0cb72708-c5d8-11e5-8949-5e9ec91dea59.png)

**Comment by xiam** [comment]
Thanks @sunshine19090!

Hey @Derekf5, @atavism: we will not be able to modify this link once the version is published, so I suggest that the new beta is put on that same URL instead of changing the UI. What do you think?

**Comment by Derekf5** [comment]
Hey, @Xiam, that sounds good. My only concern is that the link says ...Lantern-PRO-beta.apk   and we are not launching Pro yet.

**Comment by Derekf5** [comment]
s3.amazonaws.com/lantern-android/lantern-android-beta.apk  This is the link we used when announcing mobile on social
