### ISSUE TITLE
Unable to get a connection: No dialers left to try on pass 0-lantern 2.11

### ISSUE THREAD

**Issue by An0nymous0** [getlantern/lantern#3461]
lantern 2.11 Open a webpage prompt Unable to get a connection: No dialers left to try on pass 0

**Comment by uaalto** [comment]
This is a very generic that could've happened for several reasons. Closing it until we can identify a more specific issue.

**Comment by JiaShiwei** [comment]
我也遇到了这个问题 ， 无法解决啊！
