### ISSUE TITLE
Mobile - Lantern thinks it's still on after restarting phone, but it isn't

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3462]
I restarted my emulated phone, and upon running Lantern, it showed the toggle as "On" but Lantern wasn't actually proxying any traffic.  Turning it off and on did enable Lantern.

Lantern should either recognize that it's actually off after a restart and reflect this in the UI, or it should actually properly turn on.  I think the former is easier to do and probably good enough.

cc: @atavism

**Comment by myleshorton** [comment]
Is this still an issue @atavism?

**Comment by atavism** [comment]
Yep, we fixed this a few releases ago. Closing.
