### ISSUE TITLE
The footer in the mobile Ad is little bigger that the link to download is not so clear

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3465]
It would be nice to have if there is some space between the footer and the link.

![image](https://cloud.githubusercontent.com/assets/11394369/12685278/47f3653e-c678-11e5-9977-9b7d38b66623.png)

**Comment by Derekf5** [comment]
good catch @sunshine19090 what screen resolution are you seeing this at?

**Comment by sunshine19090** [comment]
Full screen @Derekf5

**Comment by Derekf5** [comment]
oh im sorry @sunshine19090 i mean what resolution is your screen?

**Comment by sunshine19090** [comment]
That's 1366x768

On Fri, Jan 29, 2016 at 11:19 AM, Derekf5 <notifications@github.com> wrote:

> oh im sorry @sunshine19090 <https://github.com/sunshine19090> i mean what
> resolution is your screen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3465#issuecomment-176919587>
> .
>



-- 
Regards,
Sunshine

**Comment by Derekf5** [comment]
Thanks @sunshine19090.  @xiam to fix this we can make 

_.download-link {
        margin-top: 5px; }_
and

_#mobile-ad {
        height: 450px; }_

**Comment by sunshine19090** [comment]
If I resize the window, I was not able to see the link at all even if I scroll.

![image](https://cloud.githubusercontent.com/assets/11394369/12732887/7fca9722-c8ec-11e5-9084-dbdd94230108.png)

**Comment by xiam** [comment]
Not sure what we could do with this one, any ideas @Derekf5?

**Comment by Derekf5** [comment]
@xiam can we scale the ad image and container with the window, but keep button and links the same size?

**Comment by Derekf5** [comment]
@xiam lets scale the image and container on window resize.
You should be able to do this by using percentage values instead of px values for the image container size, and image size so it scales and makes room for the text on window resize.

You can also use percentage values for the text padding, so it is always seen (within reason).

**Comment by xiam** [comment]
Sounds good @Derekf5, let's try that.
