### ISSUE TITLE
make: *** No rule to make target 'docker-genassets'.  Stop.

### ISSUE THREAD

**Issue by Xiaoyuyexi** [getlantern/lantern#3470]
uname -a
Darwin bogon 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0

go version
go version go1.5.3 darwin/amd64

docker -v
Docker version 1.9.1, build a34a1d5

# git clone https://github.com/getlantern/lantern.git

# make darwin
Using /usr/local/bin/docker-machine
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM fedora:21
 ---> db9d08baf815
Step 2 : MAINTAINER "The Lantern Team" <team@getlantern.org>
 ---> Using cache
 ---> 96ba0d0028ed
Step 3 : ENV WORKDIR /lantern
 ---> Using cache
 ---> cd3ba0f989c0
Step 4 : ENV SECRETS /secrets
 ---> Using cache
 ---> b1bf35f114c0
Step 5 : RUN mkdir -p $WORKDIR
 ---> Using cache
 ---> 081ea566997c
Step 6 : RUN mkdir -p $SECRETS
 ---> Using cache
 ---> 3d27f62844bc
Step 7 : RUN yum install -y deltarpm && yum update -y && yum clean packages
 ---> Using cache
 ---> 465a98dd9654
Step 8 : RUN yum install -y git tar gzip curl hostname && yum clean packages
 ---> Using cache
 ---> 1866d5a9ab61
Step 9 : RUN yum install -y gcc gcc-c++ libgcc.i686 gcc-c++.i686 pkg-config && yum clean packages
 ---> Using cache
 ---> 1d9a6a228c24
Step 10 : RUN yum install -y glibc-devel glibc-static && yum clean packages
 ---> Using cache
 ---> b28cd043a817
Step 11 : RUN yum install -y glibc-devel.i686 glib2-static.i686 glibc-2.20-8.fc21.i686 libgcc.i686 && yum clean packages
 ---> Using cache
 ---> 4d6927275ca2
Step 12 : RUN yum install -y yum-utils &&   rpm --import https://copr-be.cloud.fedoraproject.org/results/lantw44/arm-linux-gnueabi-toolchain/pubkey.gpg &&   yum-config-manager --add-repo=https://copr.fedoraproject.org/coprs/lantw44/arm-linux-gnueabi-toolchain/repo/fedora-21/lantw44-arm-linux-gnueabi-toolchain-fedora-21.repo &&   yum install -y arm-linux-gnueabi-gcc arm-linux-gnueabi-binutils arm-linux-gnueabi-glibc &&   yum clean packages
 ---> Using cache
 ---> 284295ab67ea
Step 13 : RUN yum install -y mingw32-gcc.x86_64 && yum clean packages
 ---> Using cache
 ---> 88fd7aaa9710
Step 14 : RUN yum install -y gtk3-devel libappindicator-gtk3 libappindicator-gtk3-devel && yum clean packages
 ---> Using cache
 ---> dbbb36aa908f
Step 15 : RUN yum install -y pango.i686 pango-devel.i686 gtk3-devel.i686 gdk-pixbuf2-devel.i686 cairo-gobject-devel.i686   atk-devel.i686 libappindicator-gtk3-devel.i686 libdbusmenu-devel.i686 dbus-devel.i686 pkgconfig.i686 &&   yum clean packages
 ---> Using cache
 ---> d997506c3bbe
Step 16 : RUN yum install -y ruby ruby-devel make && yum clean packages
 ---> Using cache
 ---> 8ac61434ede0
Step 17 : RUN gem install fpm
 ---> Using cache
 ---> e1af513fd58f
Step 18 : RUN yum install -y osslsigncode mingw32-nsis && yum clean packages
 ---> Using cache
 ---> d8eba1d6eeeb
Step 19 : RUN yum install -y bzip2 && yum clean packages
 ---> Using cache
 ---> fe7a69216ab7
Step 20 : RUN curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -
 ---> Using cache
 ---> d57bb987f857
Step 21 : RUN yum -y install nodejs && yum clean packages
 ---> Using cache
 ---> ce5ff38af0d4
Step 22 : RUN npm install -g gulp
 ---> Using cache
 ---> f923240af914
Step 23 : ENV GO_VERSION go1.5.3
 ---> Using cache
 ---> 170c80a4b4c2
Step 24 : ENV GOROOT /usr/local/go
 ---> Using cache
 ---> 3b47aa32d6df
Step 25 : ENV GOPATH /
 ---> Using cache
 ---> b8b8208545a9
Step 26 : ENV PATH $PATH:$GOROOT/bin
 ---> Using cache
 ---> af47e582ffb1
Step 27 : ENV GO_PACKAGE_URL https://storage.googleapis.com/golang/$GO_VERSION.linux-amd64.tar.gz
 ---> Using cache
 ---> 2c31cc5b276d
Step 28 : RUN curl -sSL $GO_PACKAGE_URL | tar -xvzf - -C /usr/local
 ---> Using cache
 ---> dedfdc4335eb
Step 29 : VOLUME $WORKDIR
 ---> Using cache
 ---> 17e93ba6da72
Step 30 : WORKDIR $WORKDIR
 ---> Using cache
 ---> 915c2cc534c2
Successfully built 915c2cc534c2
Generating assets...
Using /usr/local/bin/docker-machine
make: *** No rule to make target 'docker-genassets'.  Stop.
make: *** [genassets] Error 2

but 
# make darwin-amd64
Building darwin/amd64...
** VERSION was not set, using git revision instead (90a55a2). This is OK while in development.
Build tags: 
is ok.

# cat Makefile 
docker-genassets: require-npm
	@source setenv.bash && \
	LANTERN_UI="src/github.com/getlantern/lantern-ui" && \
	APP="$$LANTERN_UI/app" && \
	DIST="$$LANTERN_UI/dist" && \
	if [[ ! -d $$DIST ]]; then \
		UPDATE_DIST=true; \
	fi && \
	DEST="src/github.com/getlantern/flashlight/ui/resources.go" && \
	\
	if [ "$$UPDATE_DIST" ]; then \
			cd $$LANTERN_UI && \
			npm install && \
			rm -Rf dist && \
			gulp build && \
			cd -; \
	fi && \
	\
	rm -f bin/tarfs bin/rsrc && \
	go install github.com/getlantern/tarfs/tarfs && \
	echo "// +build !stub" > $$DEST && \
	echo " " >> $$DEST && \
	tarfs -pkg ui $$DIST >> $$DEST && \
	go install github.com/akavel/rsrc && \
	rsrc -ico installer-resources/windows/lantern.ico -o src/github.com/getlantern/flashlight/lantern_windows_386.syso;

**Comment by myleshorton** [comment]
I think you need to run make assets with the latest Makefile on valencia.
