### ISSUE TITLE
Client proxy appears to be creating a new connection for every HTTP request

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3471]
See https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/handler.go#L30

The client used to have a single reverse proxy at a time (per Configure() call), which allowed it to reuse its transport, which in turn would reuse connections.  Now we create a new reverse proxy on every request, which breaks that.

cc: @myleshorton

**Comment by myleshorton** [comment]
This is all set.
