### ISSUE TITLE
Optimize connection handling by reusing ReverseProxy

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3473]
See https://github.com/getlantern/lantern/blob/151a104a1434f0bfdef5a5111b83e446e1689885/src/github.com/getlantern/flashlight/client/handler.go#L30

The Lantern client creates a new ReverseProxy for each request, which prevents it from reusing TCP connections.  We could improve client performance by only having one ReverseProxy.

**Comment by myleshorton** [comment]
Yeah this is a good one @oxtoacart. We would also have to enable keep alives for outgoing connections, however, but we should probably figure out a workaround for that regardless. See https://github.com/getlantern/lantern/blob/valencia/src/github.com/getlantern/flashlight/client/reverseproxy.go#L73

**Comment by oxtoacart** [comment]
@myleshorton In the case where we're proxying the request, the server is our own server, so the keep-alive thing is only a problem when dialing the destination servers directly, right?

**Comment by bobrannon1** [comment]
Man down brother man down how to color Broken Arrow lol
Sent from my Samsung Galaxy smartphone.-------- Original message --------

**Comment by myleshorton** [comment]
Yeah great point @oxtoacart -- we could probably remove that yeah.

**Comment by oxtoacart** [comment]
In trying to figure out why Manoto with Lantern seems slow, I ran a few experiments using boom as the test driver.

Results are here: https://docs.google.com/a/getlantern.org/spreadsheets/d/1OkIJ9PddojvFRpi4zxzcU3-qHJmWr8xOy2yhTs8H__g/edit?usp=sharing

I used variants of this command:

`boom -allow-insecure -readall -n 1000 -c 100 http://www.google.com/humans.txt`

`boom -allow-insecure -readall -n 1000 -c 100 -x http://localhost:8787 http://www.google.com/humans.txt`

The factors that I varied were:

* Whether or not to use the Lantern client at all (i.e. direct vs proxied)

* From the Lantern client, whether to use a remote proxy or connect directly to the destination site

* Whether to use a local http-proxy (eliminates effect of remote network) or a proxy in Amsterdam

* Whether to reuse the ReverseProxy instance inside of the client (and enable keep-alives).  The current valencia code creates a new one for each request, I wanted to see the effect of reusing it.

Interestingly enough, reusing a ReverseProxy worked when connecting the Lantern client directly to the destination site, but failed when using an http-proxy (use of closed network connection).  Presumably this is what the comment in reverseproxy.go was referring to regarding having to turn off keep-alives.

The results are interesting:

* As long as we reuse reverseproxy, the client itself doesn't introduce too much overhead vs direct requests

* Adding a local http-proxy doesn't introduce too much further overhead, even without reusing the reverse proxy.

* Performance when using the amsterdam proxy drops precipitously.

* However, using only the client but disabling connection reuse yields results very similar to the Amsterdam proxy.

From these results, it looks like the primary cost in using remote proxies for small requests like `humans.txt` is actually the TCP connection establishment, and that this cost is significant.  Also, it looks like the problem with not being able to use keepalives may be one of our own making, not that of the remote sites.

So, we definitely want to fix this.

**Comment by oxtoacart** [comment]
I tried running with a different back-end proxy based on https://github.com/elazarl/goproxy, and that also results in the "use of closed network connection" error in the Lantern client.

**Comment by oxtoacart** [comment]
Looks like there's a pending change that may address this - https://github.com/golang/go/commit/70ee525261f7d8adbcf58c2cf54efb7e7efb1c82.  Trying now.

**Comment by oxtoacart** [comment]
That version didn't seem to fix the issue.

**Comment by myleshorton** [comment]
I'm guessing we can't catch "use of closed network connection" and re-open because it's too internal to reverseproxy right @oxtoacart? Maybe a custom Transport?

**Comment by oxtoacart** [comment]
Okay, with reusing connections and allowing keep-alives, performance to Amsterdam is much better (3x improvement).  The spreadsheet has been updated.

I think the patch to Go 1.6 was successful - the error that I observed was due to something else.  So, I think it's safe for us to enable KeepAlives.

**Comment by myleshorton** [comment]
All set.
