### ISSUE TITLE
No internet connection message received even when the app is connected to internet

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3475]
Steps:

1. Go to Live video. 
2. Exit using the back button but quit to homescreen before the app could respond. At this instance, the homescreen looked like it is shown in the first image. Probably problem with the app itself.
3. I went back to app, tried to wait for the video to close but got the warning that the app is not responding.
4. So responded with OK option and the screen turned white. I think I tried to use the side menu to go back to the home screen but not sure. After this, I got the message "No internet connection". Anyway, as I said in the other issue, it loads the video after I tapped on the home side menu.

![first_homescreen](https://cloud.githubusercontent.com/assets/11394369/12729098/e9acf0b2-c8d9-11e5-93cc-b00108d7a68e.png)
![second_not responding](https://cloud.githubusercontent.com/assets/11394369/12729103/ed4c1e6e-c8d9-11e5-8013-4b6a28e594e3.png)
![third_blank screen](https://cloud.githubusercontent.com/assets/11394369/12729106/f11ea692-c8d9-11e5-84fe-28d0fc31cdd8.png)
![fourth_no internet conn](https://cloud.githubusercontent.com/assets/11394369/12729113/f7b9d3b4-c8d9-11e5-8a67-ca123bd64e4a.png)

**Comment by oxtoacart** [comment]
I think I've fixed this.  @sunshine19090 Mind trying this build?

https://github.com/getlantern/lantern/pull/3497

**Comment by sunshine19090** [comment]
Works fine now. Closing!
