### ISSUE TITLE
Publish Android app to Google Play Store

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3476]

**Comment by xubin990510** [comment]
Where is it? Maybe provide a link?

**Comment by wwqwwqwd** [comment]
Very appreciate that.

**Comment by uaalto** [comment]
Hey @atavism, I'm not currently aware of the plan for distribution channels of the app. Is this prioritary?

**Comment by atavism** [comment]
This is finally done! It's available [here](https://play.google.com/store/apps/details?id=org.getlantern.lantern)
