### ISSUE TITLE
Lantern unable to proxy when using proxy-all-traffic after getting a SSL connection error for that particular site which is not in the default list - Windows 7

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3477]
Steps:

1. Run lantern. 
2. Make sure proxy-all-traffic is unchecked. Go to a blocked site which is not in the default list(I used slack.com with fake DNS blocking). SSL connection error occurs.
3. Now, check proxy-all-traffic. The change doesn't impact on slack even if I refresh after few minutes of waiting time.
4. Open a new instance of Lantern by using Show Lantern. I couldn't open slack then too. But I was able to open other blocked sites which is not in the default list. I used chrome till here. I tried the site in Firefox and it was able to open that site without any problem. Looks like it is specific to the browser too.
5. After quitting lantern and running it again in chrome made it work.

After quitting, it looks like the new instance is able to identify it as a blocked site and starts proxying but the former didn't recognize..

**Comment by myleshorton** [comment]
Do you also see this with 2.0.10 @sunshine19090?

**Comment by sunshine19090** [comment]
Nope

On Tue, Feb 2, 2016 at 1:00 PM, myleshorton <notifications@github.com>
wrote:

> Do you also see this with 2.0.10 @sunshine19090
> <https://github.com/sunshine19090>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3477#issuecomment-178816003>
> .
>



-- 
Regards,
Sunshine

**Comment by sunshine19090** [comment]
While doing the same test in FireFox, it worked fine. It is just chrome which has this problem.

**Comment by oxtoacart** [comment]
@sunshine19090 

> I used slack.com with fake DNS blocking

How did you do the fake DNS blocking?

**Comment by oxtoacart** [comment]
I wonder if the proxy somehow ended up on Chrome's bad proxy list.

**Comment by oxtoacart** [comment]
Sorry, my PR shouldn't have auto-closed this.  Reopening.

**Comment by myleshorton** [comment]
Is this one still an issue @sunshine19090?

**Comment by sunshine19090** [comment]
No @myleshorton, Closing it now.
