### ISSUE TITLE
There's a PKGBUILD for lantern on AUR

### ISSUE THREAD

**Issue by xubin990510** [getlantern/lantern#3479]
Arch Linux now provides a `PKGBUILD` [here](https://aur.archlinux.org/packages/lantern/) for `lantern` hosted on `AUR`. Should update the `README`.

**Comment by myleshorton** [comment]
Very cool @xubin990510 thanks! Would you be up for making pull request to the README?

**Comment by xubin990510** [comment]
@myleshortom OK, doing it right away.

**Comment by uaalto** [comment]
Done.
