### ISSUE TITLE
Mobile Ad - IE issues

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3483]
1. Name the button is missing for "Get the app" button.
2. The text in the email text box is black and not shadowed.
3. Get the app button should be in red background color.
4. Lantern logo looks a little distorted. The border doesn't look smooth. 
5. A cross mark appears when entering the email address.
6. Copy link button doesn't have the name on it. It should have black background color

![image](https://cloud.githubusercontent.com/assets/11394369/12797961/ac2aeeee-ca7b-11e5-8bd0-f5425b58db19.png)

![image](https://cloud.githubusercontent.com/assets/11394369/12798511/ad57fa02-ca7e-11e5-9bb3-a15e59c4571f.png)

**Comment by xiam** [comment]
Thanks @sunshine19090!

1. Fixed.
2. Fixed.
3. Fixed.
4. @Derekf5 I think that's because we resized it, can you add a resized PNG or SVG for that one?
5. Could not reproduce.
6. Fixed.

**Comment by sunshine19090** [comment]
@xiam, I am able to reproduce it in my system. When I enter the email address, the cross mark appears on the right side. I use IE 11. It doesn't appear in chrome or Firefox.

![image](https://cloud.githubusercontent.com/assets/11394369/12856266/ebdf2ed2-cbf8-11e5-853a-f0c8d39ed6f5.png)

**Comment by xiam** [comment]
@sunshine19090 does it stay the same if you enter a full e-mail address?

**Comment by sunshine19090** [comment]
Yes @xiam

**Comment by myleshorton** [comment]
Closing.

**Comment by sunshine19090** [comment]
Except copy link button, all the other issues are still existing.

**Comment by myleshorton** [comment]
Was there an issue with the merge on this one @xiam?

**Comment by xiam** [comment]
@sunshine19090 this is closed, right?

**Comment by sunshine19090** [comment]
Yep, all of them are working good.
