### ISSUE TITLE
Mobile Ad shows up everytime Lantern is launched in IE

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3484]
In chrome and Firefox, once the user sends the app via email, the UI changes to normal and never displayed the mobile ad after that. But in IE, it shows up everytime lantern is launched though sent the app via email already.

**Comment by myleshorton** [comment]
Hmnn...great catch @sunshine19090! Probably an issue with local storage.

**Comment by xiam** [comment]
Could not reproduce this one @sunshine19090, the Ad should be away once you put your e-mail. Can you share your IE version?

This is what I have:

![screen shot 2016-02-05 at 7 25 14 am](https://cloud.githubusercontent.com/assets/385670/12847568/db8016c4-cbd9-11e5-867e-c449eb002b51.png)

I also tested using compatibility mode with IE 10.

**Comment by sunshine19090** [comment]
Sorry @xiam, I should have updated here after the meeting but I just forgot to do that. I too couldn't reproduce it yesterday. But I logged the issue only after checking it twice. I have no idea why it worked the way it did :) Sorry for the trouble again! I will close this now.
