### ISSUE TITLE
Fix on/off status when app is force stopped

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3487]
Reported by @sunshine19090.

When you force stop an app, it kills the process immediately. So there's no way to callback to the app, and, in our case, to clear shared preferences/update the state of the VPN connection. To account for this case, when Lantern first starts, in ``onCreate()``, we should check if Lantern is already switched on and switch it off.

**Comment by uaalto** [comment]
@atavism this sounds like it is fixed, right?

**Comment by atavism** [comment]
Yep, this is fixed now!

**Comment by uaalto** [comment]
Awesome thanks!
