### ISSUE TITLE
Mac OSX, Safari - Mobile Ad is not displayed

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3498]
It directly takes me to the usual Lantern browser page.

**Comment by sunshine19090** [comment]
chrome and firefox too

**Comment by myleshorton** [comment]
Hey @sunshine19090 it will only show the page the first time you run it but never again. On Chrome you can get around that by running in an incognito window, but you should also be able to clear local storage on Safari and IE. It's local storage @xiam and not a cache thing right? Do you know how to clear it on IE and Safari?

**Comment by sunshine19090** [comment]
@myleshorton, I didnt get the mobile Ad even once. I will try deleting the local storage.

**Comment by sunshine19090** [comment]
Yeah @myleshorton, I get it in chrome when I use incognito window. The issue is about the Ad not appearing even once when the user downloads the new version. If it works this way, then the old users will never see the mobile Ad unless they are using chrome - incognito window.

In windows, when I downloaded the version for the first time, it appeared until I submitted my email address in IE, Firefox and chrome.

**Comment by myleshorton** [comment]
@sunshine19090 yeah even if you've opened it with a previous version of Lantern it won't open with a new version. That's the way it's supposed to work (it will only open once across all versions of Lantern).

**Comment by sunshine19090** [comment]
Oh,I meant to say that I am not seeing the Ad even once when I downloaded this version 2.0.11.

**Comment by myleshorton** [comment]
@sunshine19090 you saw it with a previous version though right? I.e. you've seen the ad at some point on all of these browsers right?

**Comment by xiam** [comment]
That makes sense to me @sunshine19090! I am using the same value old versions of Lantern are using to tell if this is the first time it starts. I'm gonna use another one.

**Comment by sunshine19090** [comment]
But we didn't have mobile Ad in our previous versions @myleshorton. Do you mean previous build? Anyway, today is the first time that I am testing it in Mac with 2.0.11. So I expected to see the Ad but didn't. Does that make sense @myleshorton ?

**Comment by myleshorton** [comment]
@sunshine19090 yes any run of any 2.0.11 build of lantern

**Comment by myleshorton** [comment]
This should be all set with the latest merge from @xiam.

**Comment by xiam** [comment]
Should be closed by https://github.com/getlantern/lantern/pull/3525

**Comment by sunshine19090** [comment]
Works fine now.
