### ISSUE TITLE
Lantern heading below the lantern logo is incorrect - Safari

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3499]
It should be "Welcome to Lantern! You can now access blocked sites."

<img width="1389" alt="screen shot 2016-02-05 at 11 47 35 am" src="https://cloud.githubusercontent.com/assets/11394369/12857346/817cfafa-cbfe-11e5-889e-1fa3b7060163.png">

**Comment by xiam** [comment]
Should be closed by https://github.com/getlantern/lantern/pull/3525.

**Comment by sunshine19090** [comment]
Looks good now.
