### ISSUE TITLE
All the letters in the footer and setting screen (including the tooltip for settings icon) are in upper case - Safari

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3501]
<img width="1389" alt="screen shot 2016-02-05 at 11 47 35 am" src="https://cloud.githubusercontent.com/assets/11394369/12857499/62d886ea-cbff-11e5-86fe-27f21e2162ab.png">

**Comment by xiam** [comment]
See https://github.com/getlantern/lantern/pull/3525

**Comment by sunshine19090** [comment]
Looks good now.
