### ISSUE TITLE
Several issues - Lantern mobile Ad page doesn't have proper image and text - safari

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3503]
There are several issues.
1. No images
2. No button
3. There is a place for text box but it is not working. I couldn't input any values.
4. The link doesn't have the proper text
5. When clicked on the link, shows "500 Internal server error"
6. All the letters are in upper case

Update: I used Private Window option in safari

**Comment by sunshine19090** [comment]
<img width="1280" alt="screen shot 2016-02-05 at 12 56 51 pm" src="https://cloud.githubusercontent.com/assets/11394369/12859103/d7c8427a-cc08-11e5-8d14-f6e287d00f38.png">

**Comment by xiam** [comment]
See https://github.com/getlantern/lantern/pull/3525

**Comment by sunshine19090** [comment]
I am still seeing the same and I couldn't go to the normal UI too as the text box is not working.

**Comment by xiam** [comment]
Hello @sunshine19090, could you take a screenshot of the `Develop` -> `Show error console` dialog?

**Comment by sunshine19090** [comment]
<img width="1280" alt="screen shot 2016-02-09 at 2 11 09 pm" src="https://cloud.githubusercontent.com/assets/11394369/12932334/2abfc562-cf37-11e5-95dd-2505f1e2876d.png">

**Comment by sunshine19090** [comment]
Looking good now.
