### ISSUE TITLE
Autorun at system start does not work in Ubuntu 15.10

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#3505]
Lantern works perfectly in my ubuntu 15.10 but the setting "Run Lantern automatically on system start" seems not to work: it is checked but it does not run on the system start.

**Comment by kashu** [comment]
This startup method always works for my Xubuntu 14.04.3 and I think you will like it.
```
/usr/bin/nohup sh -c "/bin/sleep 8 && /usr/lib/lantern/lantern.sh -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null
```
![](http://ww1.sinaimg.cn/large/9c4ddab1gw1f14xguqpk6j20qw0d17aq.jpg)
