### ISSUE TITLE
安卓下lantern 提示：很抱歉 lantern已停止运行

### ISSUE THREAD

**Issue by lsq726** [getlantern/lantern#3512]
安卓下lantern 提示：很抱歉 lantern已停止运行

**Comment by gftvlie** [comment]
同出现这种情况

**Comment by lmj01** [comment]
有解决方案吗？还是Android版本低的原因？

**Comment by azgh** [comment]
android6.0.1也出现该提示

**Comment by uaalto** [comment]
Could any of you confirm if this issue still happens, please? Also, if you could provide any details it would be much appreciated. Thank you!
