### ISSUE TITLE
When installing the new version when the older version is already running, then launching the new version doesn't have any impact

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3515]
Steps:

1. Launch the old version 2.0.10
2. Install 2.0.11 and select the option to keep both while installing.
3. Now launch 2.0.11.  A new lantern browser is opened with version 2.0.10.

**Comment by myleshorton** [comment]
What OS @sunshine19090?

**Comment by sunshine19090** [comment]
Mac OS @myleshorton

**Comment by myleshorton** [comment]
Actually if Lantern detects an existing version of Lantern running -- any version -- it will just open the existing version. To open the new version, users have to first quit the first version. 

I don't think this is really much of an issue in practice, both with auto-updates and with users typically just installing Lantern over their first version (quitting Lantern in the process). Let's close and re-open if users ever have issues with this.

This is also definitely not new to 2.0.11.

**Comment by sunshine19090** [comment]
Sure, sounds good!
