### ISSUE TITLE
Copy link is not working in Firefox - Windows and Mac OS

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3520]
On clicking the copy link button in "Tell your friends" screen in mobile Ad, it says "Link copied" but it is not copying at all. When I tried to paste it in the browser address bar, it is blank.

**Comment by xiam** [comment]
Thanks @sunshine19090, we use a plugin for this copying and it only supports certain browsers, see "Browser Support" at https://sachinchoolur.github.io/ngclipboard/.

Hey @Derekf5, what do you think of this one?

**Comment by myleshorton** [comment]
What version of FireFox are you using @sunshine19090? If it's 41 or above it should work @xiam, but maybe it's an old version of the library.

**Comment by Derekf5** [comment]
Hey @xiam could you use this snippet? http://codepen.io/MyXoToD/pen/oXzWXq

**Comment by sunshine19090** [comment]
@myleshorton  I am using Verson 44 in both windows and Mac

**Comment by myleshorton** [comment]
Hmnn...OK so looks like that's not the issue after all @xiam, or we're just using an old version of the library. Thanks @sunshine19090

**Comment by xiam** [comment]
@Derekf5 I could, but does that work across all browsers? Can you try that @sunshine19090? 

@myleshorton I don't think so, we're using the most recent one. Can you try with this site? @sunshine19090 https://sachinchoolur.github.io/ngclipboard/ does any the examples work for you?

**Comment by sunshine19090** [comment]
No @xiam, the link that Derek provided is not working for me in Firefox but works fine in Chrome.

**Comment by xiam** [comment]
@sunshine19090 and the other one?

**Comment by sunshine19090** [comment]
just updating here @xiam  - I used copy, cut and the other example under usage. None of them are working in Firefox.

**Comment by Derekf5** [comment]
@xiam @sunshine19090  If this becomes too big of a headache to get to work in all browsers it may be ok to nix the copy button.   While it is a nice quick option for users, people are quite used to copy and paste.  @myleshorton does that sound ok to you?

**Comment by myleshorton** [comment]
Sounds fine to me yeah. Odd that library is documented to work on that
version of FF but clearly doesn't.

**Comment by sunshine19090** [comment]
@Derek @xiam and @myleshorton This functionality is not working in Safari(version 8) too. Are we going to have it for this release or remove it? If we are going to remove it in this release alone, then I will move it to next release or if we are not going to bring this functionality at all, then I will close it. Let me know.

**Comment by Derekf5** [comment]
@xiam @sunshine19090 lets just close this.

**Comment by sunshine19090** [comment]
Closing!
