### ISSUE TITLE
Add balancer prioritization strategy based on throughput

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3522]
Per suggestion by @aranhoide, we could just make a smallish file available for download directly from the proxy server and use that to measure throughput.

cc: @fffw

**Comment by myleshorton** [comment]
The server side of this is done correct @oxtoacart?

**Comment by fffw** [comment]
Yeah it's added as the `ping` filter in http-proxy-lantern. I'm writing a simple tool to measure and compare all relevant metrics among servers. Report should be out in 12 hours.

**Comment by oxtoacart** [comment]
@fffw Cool!

**Comment by myleshorton** [comment]
This one's effectively done and/or obsolete right @oxtoacart?

**Comment by oxtoacart** [comment]
Obsolete.
