### ISSUE TITLE
Size of installers increased by over 2MB

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3538]
Not sure why yet, but the combined dist javascript file is huge for one. This is a blocker.

**Comment by myleshorton** [comment]
We need to dig deeper into this one @xiam.

**Comment by xiam** [comment]
Hey @Derekf5, do you think you can try to reduce the size of the PNG or use a JPG instead? This is for the main mobile ad. Thanks!

**Comment by Derekf5** [comment]
Hey @xiam yes i will try to reduce.

**Comment by Derekf5** [comment]
Hey @xiam Just put optimized ad images in our shared dropbox under the folder name "Ad Images Smaller File Size".   Compressing all three images i was able to take the total file size down 75% or about 2mb for all three images.

**Comment by xiam** [comment]
Thanks @Derekf5, just updated the code.

**Comment by myleshorton** [comment]
Cool guys -- I just updated the qa builds. Thanks all!!!
