### ISSUE TITLE
Email address text box accepts invalid email address

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3546]
I am able to enter email addresses with two @ symbols, start with a number, with space, do not have @ symbol at all. After clicking on enter, it takes me to the pop up without any error messages.

**Comment by myleshorton** [comment]
Do we currently do any validation? We could probably ship without including
that.

**Comment by xiam** [comment]
Hey @myleshorton, @sunshine19090 how does this one look? Can we close it?

**Comment by sunshine19090** [comment]
Yes @xiam, it looks good.
