### ISSUE TITLE
Dialing timing out too quickly in some cases

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3550]
Seeing this in Iran in particular:

```
Feb 11 09:01:39.237 - 2m32s DEBUG fronted: direct.go:148 Dialing to &{www.cloudfront.net 54.240.129.249}
Feb 11 09:02:07.595 - 3m0s DEBUG fronted: direct.go:154 Could not dial to 54.240.130.90, Unable to dial masquerade cloudfront.net: tlsdialer: DialWithDialer timed out
```

**Comment by myleshorton** [comment]
This is for the 2.0.11 release. It's possible Valencia is OK, but this machine was unable to domain front at all, seemingly at least primarily due to this issue. You want to take a look at this if I don't get to it first @oxtoacart? I think it's a blocker for 2.0.11

**Comment by myleshorton** [comment]
Here's a more complete log -- it actually looks like they might be timing out in the expected 30 second time:

```
Feb 11 09:00:37.594 - 1m30s DEBUG fronted: direct.go:148 Dialing to &{cloudfront.net 54.239.192.230}
Feb 11 09:01:07.260 - 2m0s DEBUG fronted: direct.go:154 Could not dial to 54.240.130.52, Unable to dial masquerade cloudfront.net: tlsdialer: DialWithDialer timed out
Feb 11 09:01:07.260 - 2m0s DEBUG fronted: direct.go:148 Dialing to &{www.cloudfront.net 54.240.129.80}
Feb 11 09:01:07.594 - 2m0s DEBUG fronted: direct.go:154 Could not dial to 54.239.192.230, Unable to dial masquerade cloudfront.net: tlsdialer: DialWithDialer timed out
```

**Comment by myleshorton** [comment]
So this would indicate that Iran is blocking all connections to these CloudFront domains @oxtoacart...

**Comment by oxtoacart** [comment]
Looks like this may be TLS-level blocking, as I am able to connect to port 443, but not curl:

```
lantern@srv31846:~$ nc -vz 54.240.130.52 443
Connection to 54.240.130.52 443 port [tcp/https] succeeded!
lantern@srv31846:~$ curl --insecure -v https://54.240.130.52
* About to connect() to 54.240.130.52 port 443 (#0)
*   Trying 54.240.130.52... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
```

Curl hangs at this point.

**Comment by myleshorton** [comment]
Interesting @oxtoacart. From the logs it looks like some are timing out while others are eventually connecting, such as:

```
Feb 11 09:05:39.240 - 6m32s DEBUG fronted: direct.go:148 Dialing to &{cloudfront.net 54.239.192.116}
Feb 11 09:05:39.586 - 6m32s DEBUG fronted: direct.go:162 Got successful connection to: &{cloudfront.net 54.239.192.116}
```

Then `curl --insecure -v https://54.239.192.116` also works for that IP, but this hits up against https://github.com/getlantern/lantern/issues/3531, which it would be worth it to just fix probably -- I started a fix for it actually and could just submit a PR for it.

**Comment by oxtoacart** [comment]
Something's not right.  `curl -v http://blogfa.com` just hangs.  As does `curl -v http://yahoo.com`.

**Comment by oxtoacart** [comment]
`nslookup blofga` just hangs.

**Comment by myleshorton** [comment]
Hmnn...that's very weird @oxtoacart

**Comment by oxtoacart** [comment]
I think DNS is just hosed.  I can ping an ip for blogfa.com just fine:

```
➜  Downloads git:(master) ✗ nslookup blogfa.com
Server:		208.67.220.220
Address:	208.67.220.220#53

Non-authoritative answer:
Name:	blogfa.com
Address: 104.31.72.239
Name:	blogfa.com
Address: 104.31.73.239
```

**Comment by myleshorton** [comment]
Interesting @oxtoacart. It looks like there might be a few things going on. For example yesterday those IPs were timing out without touching DNS, but then also your TLS hanging would seem to not touch DNS.

**Comment by oxtoacart** [comment]
DNS also seems broken on the Windows VPS.  Are these in the same datacenter?

**Comment by myleshorton** [comment]
Yeah same data center unfortunately @oxtoacart

**Comment by myleshorton** [comment]
This is all set in latest 2.0.11 changes
