### ISSUE TITLE
Couldn't see the download link in IE

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3553]
![image](https://cloud.githubusercontent.com/assets/11394369/12985736/f2b36d72-d0a8-11e5-9413-d6944602aa86.png)

**Comment by sunshine19090** [comment]
If the zoom is just 75%, then the download link is visible.

**Comment by xiam** [comment]
Not sure what to do here, @Derekf5 what do you think?

**Comment by Derekf5** [comment]
@xiam under
**_#mobile-ad #get-the-app-via-email {_**
Change the margin from
**_margin: 20px 0 0; to margin: 2px 0 0;_**

and under
**_.download-link {_**
Change margin-top from
**_margin-top: 20px;  to  margin-top: 0px;_**

Then Change the Mobile ad container
from
**_Height: 473px  to  Height: 430px_**

Thanks!

**Comment by myleshorton** [comment]
Looks like this is the same as #3681. Good catch on that @sunshine19090. Closing!
