### ISSUE TITLE
Mobile Ad comes up for every new build

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3554]
I have checked only in windows - all the browsers.

**Comment by xiam** [comment]
@sunshine19090 does this Ad stay even if you input your e-mail address? I added a condition to show the Ad everytime we create a new build, typically users don't see those new builds that often.

**Comment by sunshine19090** [comment]
No @xiam, the Ad goes off once I provide my email address. But @myleshorton told me that the Ad shouldn't show up for every new build or release. @myleshorton what do you think?
