### ISSUE TITLE
Lantern is not loaded in the browser the first time when manually entered the address 127.0.0.1:16823  in chrome.

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3555]
Works fine when refreshed the page

**Comment by xiam** [comment]
Does this happen everytime @sunshine19090? I usually test the UI by using `-headless` and entering the address manually.

**Comment by sunshine19090** [comment]
Yes @xiam, I have to refresh the page once more to load. This is what I did to reproduce - Go to chrome browser, open a new tab, type 127.0.0.1:16823 in the address bar and enter. The page will be blank. Once I refresh, the page is loaded.

**Comment by xiam** [comment]
Never happened to me on chrome but I managed to reproduce it in Safari a few times.
