### ISSUE TITLE
Latest UI changes break Lantern in Safari 9

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3560]
I again can't even load the UI in Safari. Looks like some of the recent changes somehow broke web sockets:

```
[Error] Failed to load resource: The network connection was lost. (collect, line 0)
[Error] WebSocket connection to 'ws://127.0.0.1:16823/data' failed: WebSocket is closed before the connection is established.
	close
	onbeforeunload
```

**Comment by myleshorton** [comment]
Hey just FYI @sunshine19090 and @xiam see the description above..

**Comment by xiam** [comment]
Possibly related to https://github.com/getlantern/lantern/issues/3555, but I can't replicate it at will, it only happens sometimes and never with the web console open. Did you wait for the browser window to appear or used the address in the address bar?

**Comment by myleshorton** [comment]
It actually happened every time for me @xiam

**Comment by myleshorton** [comment]
Regardless of how I started Safari. I could probably figure out the cause fairly quickly with giy bisect

**Comment by xiam** [comment]
@myleshorton I could not replicate it as will but I catched an error message a couple of times and I think this might work, can you try? https://github.com/getlantern/lantern/pull/3563

**Comment by myleshorton** [comment]
I'll try it! Oddly I just tried git bisect. This now fails for me on two computers, but I couldn't get it to work in Safari going back 3 weeks on commits @xiam! So there's something slightly odd amiss I think, but I am seeing it on two machines with Safari 9.0.1.

**Comment by myleshorton** [comment]
I see the same thing on that branch @xiam. I both can't get Safari to load the UI and can't get it to proxy any page, to be clear.

**Comment by myleshorton** [comment]
OK, it also doesn't work with 2.0.10 @xiam..

**Comment by myleshorton** [comment]
Tempting to just leave this, ship, and revisit then.

**Comment by xiam** [comment]
@myleshorton exactly the same error on a closed websocket? I never got that, I catched a javascript error instead.

**Comment by myleshorton** [comment]
For some reason I now can't get anything to appear in the error console with those older versions @xiam...

**Comment by myleshorton** [comment]
I do have Safari set to my default browser, but I don't that impacts anything.

**Comment by myleshorton** [comment]
I'll be back in a bit, but I'm tempted to just ship what we have since it appears to be some change in Safari, and we can revisit.

**Comment by xiam** [comment]
This happens even if you reload? and with 2.0.10 compiled or the one from the website? Really odd, this was working before. The most strange thing is not having a log.

**Comment by myleshorton** [comment]
Yeah exactly, and on two machines!

**Comment by xiam** [comment]
This is what I catched, it does not happen that often but when happens is only the first time and disappears after reloading. This is fixed on https://github.com/getlantern/lantern/pull/3563 but perhaps that was a different problem.

![screen shot 2016-02-12 at 8 48 21 am](https://cloud.githubusercontent.com/assets/385670/13010046/6d06b162-d165-11e5-8857-3396038254b4.png)

**Comment by myleshorton** [comment]
Oh this is interesting...Safari's not opening any web page for me even without Lantern =). OK I think we can ignore this. How that's happening while my network is clearly fine (writing this in Chrome) I have no idea, but not to worry.

I have also seen the GA issue @xiam, so if your branch fixes that let's do that too.

**Comment by xiam** [comment]
Yeah, after a couple of tries I managed to reproduce the same thing about `ga` with 2.0.10, it also disappears after reloading.

**Comment by myleshorton** [comment]
ok cool. and your branch fixes it? sorry for the noise on this ticket!

**Comment by xiam** [comment]
Yes it does, @myleshorton.

**Comment by myleshorton** [comment]
Did you mean to re-open this one @xiam? I think it's all set -- now working for me after restarting my machine.
