### ISSUE TITLE
Separate global config from user-specific config

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3567]
And separate the per user config into a separate call.

**Comment by uaalto** [comment]
Issue review: agreed with the priority.

**Comment by myleshorton** [comment]
The global config endpoint is at http://config.getiantem.org/global.yaml.gz

We're going to start doing this as an experiment for using cache expiry on CDNs to offload traffic.

**Comment by myleshorton** [comment]
Per-user is at http://config.getiantem.org/proxies.yaml.gz

**Comment by myleshorton** [comment]
We could also move to s3 or somewhere else with a modification to this script: https://github.com/getlantern/lantern_aws/blob/master/salt/update_masquerades/genconfig.bash

**Comment by oxtoacart** [comment]
Mostly coded, just need to work through some integration testing issues.
