### ISSUE TITLE
For direct domain fronting, use IPs only and encrypt and/or sign our content

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3569]
The signing and/or encrypting gets around any potential MITM attacks.

**Comment by myleshorton** [comment]
I think this is a great idea @aranhoide and would dramatically simplify our task for direct domain fronting to our own content.

**Comment by aranhoide** [comment]
Sorry, I've missed the fact that this ticket was assigned to me.

@myleshorton:  To be realistic, there's lots of important work to do in the backend.  Most importantly, automating load balancing and the ops panel.  Coming back to the client side would be quite momentum-breaking and unnecessarily extending the need for manual balancing ops would be inefficient and, for me, demoralizing.  So, if at all possible, I'd prefer this ticket to be reassigned to whoever is working in related stuff.  I don't know who that is currently, so I'm tentatively reassigning to you for further dispatching.

**Comment by myleshorton** [comment]
That's totally fine @aranhoide. To be clear, though, a lot of the work for this would be on the server side. To more clearly elucidate the idea, we would do the following:

1) Only distribute IP addresses for masquerades to the client 
2) Completely ignore certificate validation
3) Encrypt the config file file our private key

Definitely some client changes involved, but it would mostly be stripping code out. It would basically be a workaround for the fact that CloudFront re-assigns the IPs associated with given domains very frequently. We just wouldn't have to worry about that as long as the IPs were still valid.

**Comment by myleshorton** [comment]
We should chat about key revocation. See:

https://www.imperialviolet.org/2014/04/19/revchecking.html

**Comment by oxtoacart** [comment]
Replaced by getlantern/lantern-internal#129
