### ISSUE TITLE
Windows installer doesn't quit and hugs one CPU

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3573]
Seen from 2.0.12 installer running on a Win 7 VM with 2 CPU. lantern-installer-beta.exe keeps using 50% CPU even Lantern quited. Also seeing from [Chinese Forum](https://groups.google.com/d/msg/lantern-users-zh/_NTIticCKNo/7M4nwW-LDgAJ).

My Mac crashed before posting the screenshot. I couldn't reproduce it either. It might be a rarely happen NSIS bug.

**Comment by myleshorton** [comment]
Interesting @fffw. Have you seen this @sunshine19090?

**Comment by sunshine19090** [comment]
Nope @myleshorton. I always keep an eye on CPU usage and Memory usage when testing. I have not seen this after the oct-nov release. I have tested our latest with large file downloads and videos running in the browser. It could be a specific scenario. Do you remember the steps @fffw? I can try reproducing it.

**Comment by myleshorton** [comment]
This is specific to the *installer* @sunshine19090 so wouldn't be impacted by videos or large file downloads, but sounds like you haven't seen any installer issues right?

**Comment by sunshine19090** [comment]
Yeah, no issues @myleshorton.

**Comment by fffw** [comment]
@sunshine19090 No exact steps. I tried several ways in hope to reproduce it, but no luck.

**Comment by uaalto** [comment]
Should we consider this closed until further notice? Being so hard to replicate we might have this bug stalled here.

**Comment by fffw** [comment]
Anyway it's not a bug of Lantern itself. Close it for now.

**Comment by uaalto** [comment]
Thank you @fffw !
