### ISSUE TITLE
-addr :flag provided but not defined

### ISSUE THREAD

**Issue by fliar** [getlantern/lantern#3577]
on this wiki page:
https://github.com/getlantern/lantern/wiki/Installation:-server
run:
lantern_linux_amd64 --addr 0.0.0.0:8787
terminal showed this: flag provided but not defined
is there an alternative?

**Comment by fffw** [comment]
@fliar It should work. What is the Lantern version? Or you can use single hyphen: `lantern_linux_amd64 -addr 0.0.0.0:8787`

**Comment by fliar** [comment]
@fffw i built lantern from source this morning, it's not working, the old one works.
the new one just said:
flag provided but not defined: -addr

**Comment by fffw** [comment]
@fliar Please build from `valencia` branch, or one of the release tags.

**Comment by fliar** [comment]
@fffw this is not helping
git status
On branch valencia
Your branch is up-to-date with 'origin/valencia'.
nothing to commit, working directory clean

**Comment by fffw** [comment]
@fliar Sorry for misleading you. Flag `-addr` is remove at d37831426989942c4613f2bab79c58bf94969226. Please run with `-help` to show the list of allowed flags.

**Comment by fliar** [comment]
@fffw i tried some flags, but still couldn't figure out which flag is alternative to addr
lantern is always listening on localhost:8787, i want to change the address and port
if there's an alternative?

**Comment by fffw** [comment]
Unfortunately there's no alternative

**Comment by myleshorton** [comment]
@oxtoacart is this still supported in any way on Valencia? I missed it in
my reviews, but it's pretty important for people running Lantern for
multiple machines on a local network.

**Comment by myleshorton** [comment]
@fliar you can also run from the release-2.0.1 branch.

**Comment by fliar** [comment]
@myleshorton @fffw thanks for the help, i'm now using the pre-built version from lantern-binaries, the flag works.
but i still hope the addr flag not removed in future version

**Comment by oxtoacart** [comment]
Sorry about that, I can add it back.

**Comment by oxtoacart** [comment]
Here's a PR - https://github.com/getlantern/lantern/pull/3579

**Comment by oxtoacart** [comment]
@fliar If you grab the latest from valencia, you should be able to provide the '-addr' flag again.

**Comment by fliar** [comment]
@oxtoacart yes valencia works again, thanks for the help
