### ISSUE TITLE
我使用Lantern（蓝灯）的秘密技巧

### ISSUE THREAD

**Issue by kashu** [getlantern/lantern#3578]
启动Lantern的命令如下：
nohup sh -c "/home/kashu/.lantern/bin/lantern -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null

1） 你不需要去更改Lantern的任何配置文件，这样启动后的效果是，Lantern会直接监听0.0.0.0这个地址，这意味着任何可以设置代理的软件，都可以指向Lantern并让网络流量都从Lantern走出去。

而且，其它电脑、手机等设备，都可指向这台电脑和对应的端口，从这里跳墙出去。但要注意，要让其它设备的流量也能够走这台开启了Lantern的电脑出去，Linux内核的转发功能得开启： /proc/sys/net/ipv4/ip_forward这个文件的内容是1才行，同时注意你的防火墙配置！

2） 这样启动后，不会看到Lantern软件弹出的那个“欢迎画面”，你使用时会感觉更加的方便和舒心。

3） 这样启动后， Lantern所有的日志输出信息全部会直接被扔到/dev/null，不会把日志文件写入到硬盘里，节省硬盘空间和不必要的写操作（当然，如若你想要那些日志，你也可把/dev/null换成一个别的路径以保存之）。

注：虽然是一行命令，但你不可以通过ssh远程来启动Lantern，请在当你用图形化界面登陆系统后，再执行。

如果你和我一样，用的是Xubuntu操作系统，那在Session and Startup里面设置为开机自启动的话，用下面的命令即可，从此，使用起来更加方便了。对我而言，我觉得现在不用Lantern上网都不叫上网了。
/usr/bin/nohup sh -c "/bin/sleep 8 && /usr/lib/lantern/lantern.sh -addr 0.0.0.0:8787 -startup=true -role=client &> /dev/null" &> /dev/null

很遗憾，上面的内容全部是针对Linux用户来写的，因为我手头现在没有Windows系统，也非常非常少用Windows系统了，基本(99.9%的时间)都是用的Xubuntu，所以Windows用户的设置我没写，其实，基本是一样的。其它网友可以稍微补充一下……

**Comment by kashu** [comment]
内容截图：
![](http://ww4.sinaimg.cn/large/9c4ddab1gw1f11616tkk4j20mn0ipqc8.jpg)

**Comment by fffw** [comment]
@kashu It should be very useful to Linux users. 
Do you mind moving this guide to [Chinese forum](https://groups.google.com/forum/#!forum/lantern-users-zh)? GitHub issues page is mainly for tracking bugs and development progress.

**Comment by kashu** [comment]
Of course, you do. Share anywhere will be welcomed.

**Comment by HuangHongkai** [comment]
你知道ubuntu在命令行下哪一个命令参数可以设置智能代理吗，就是中国的网站不需要代理直接访问
