### ISSUE TITLE
Leaked memory and goroutine

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3580]
Seen from binary built from latest valencia code (f5696ab42ae463ece522e05beb496efd61d56b41). A few user reported memory leak and performance degrade of 2.0.12 and 2.0.13, maybe related to this.

Memory is ever increasing and slows down proxy performance.
![image](https://cloud.githubusercontent.com/assets/10410437/13079281/70e35866-d4fe-11e5-9bc9-14fdeafbc36b.png)

Also seen increasing sleeping goroutines.

```
367 @ 0x4037fc3 0x4038084 0x40532d9 0x426c074 0x40682c1
#	0x40532d9	time.Sleep+0xf9						/usr/local/Cellar/go/1.5.2/libexec/src/runtime/time.go:59
#	0x426c074	github.com/getlantern/fronted.(*direct).vetSome+0x244	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/fronted/direct.go:97
```

**Comment by myleshorton** [comment]
This looks pretty important @fffw and @oxtoacart. If we can reproduce this on 2.0.13 we should release a fix!

**Comment by myleshorton** [comment]
Probably in a 2.0.14

**Comment by oxtoacart** [comment]
@myleshorton Agreed.  I'll take a look once I finish up the mobile work for Manoto (hopefully finishing this afternoon).

**Comment by fffw** [comment]
Ok the goroutines hung at direct.go:156, because looping through a channel will never end until the channel is closed. More testing coverage would help to catch such type of bug.
 
```
592 @ 0x4037fc3 0x4038084 0x400ef61 0x400e64b 0x426c97a 0x426bf0d 0x40682c1
#	0x426c97a	github.com/getlantern/fronted.(*direct).dialWith+0xfa	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/fronted/direct.go:156
#	0x426bf0d	github.com/getlantern/fronted.(*direct).vetSome+0xdd	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/fronted/direct.go:92

```

**Comment by oxtoacart** [comment]
@fffw Working on it now.

**Comment by oxtoacart** [comment]
@sunshine19090 Would you like to test this?

**Comment by myleshorton** [comment]
I think this is going to be very difficult to reproduce and to verify @sunshine19090, so I'm just going to go ahead and close it. We've verified the fix on our end.

**Comment by myleshorton** [comment]
Great work @oxtoacart!
