### ISSUE TITLE
Keep masquerades in only one place

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3587]
Right now, we have various tests (like util_test.go) that duplicate the masquerades configured in masquerades.go.  These tests have to be manually update when we updates masquerades.go, which is burdensome and error prone.  It would be better to have everything use a single configuration.

**Comment by myleshorton** [comment]
I believe you knocked this out right @oxtoacart?

**Comment by oxtoacart** [comment]
Yes, I think so.
