### ISSUE TITLE
Problem fetching update: Post https://update.getlantern.org/update x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3589]
Seeing this a lot in Loggly..

**Comment by myleshorton** [comment]
We can close this right @xiam?

**Comment by xiam** [comment]
I don't know @myleshorton, I think we should try using another CA instead of letsencrypt to see if this changes.

**Comment by oxtoacart** [comment]
Weird.  Are we being MITM'ed?

**Comment by myleshorton** [comment]
No - XP doesn't recognize the CA.

**Comment by oxtoacart** [comment]
@myleshorton Ahh.  Have we looked at this - https://community.letsencrypt.org/t/upcoming-intermediate-changes/13106/3?

**Comment by oxtoacart** [comment]
@myleshorton It occurs to me that this was a stupid question, as that announcement from letsencrypt is only 6 days old, so chances are that we have not looked at it :)

**Comment by xiam** [comment]
That's cool @oxtoacart! Good timing as I'm gonna renew them soon.

**Comment by myleshorton** [comment]
Nice @oxtoacart! No hadn't seen that.

On Wed, Mar 30, 2016 at 1:19 PM, José Carlos <notifications@github.com>
wrote:

> That's cool @oxtoacart <https://github.com/oxtoacart>! Good timing as I'm
> gonna renew them soon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3589#issuecomment-203614844>
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by fffw** [comment]
Wow it's great @oxtoacart ! With XP support and auto renewal via crontab we may just stick with LE for any service hosted on VPS.

**Comment by xiam** [comment]
We stopped getting this error after the certificate renewal.

**Comment by myleshorton** [comment]
Awesome! So you used the new XP-compatible intermediate cert @xiam?
