### ISSUE TITLE
Overloaded server drops TCP connections

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3591]
I noticed that I was having intermittent trouble connecting to one specific server.  Looking at `/var/log/syslog', I noticed entries like the below:

```
Feb 17 13:53:03 fp-doams3-20160127-001 kernel: [1255873.483233] net_ratelimit: 2193 callbacks suppressed
Feb 17 13:53:03 fp-doams3-20160127-001 kernel: [1255873.483244] TCP: drop open request from <ip elided>/16417
```

I saw a ton of the `drop open request` messages.

Some research based on the below articles led me to conclude that the `txqueuelen` on the network interface and the `tcp_max_syn_backlog` setting were too low.  `txqueuelen` was 1000 and `tcp_max_syn_backlog` was 128.

Increasing `txqueuelen` to 20000 and `tcp_max_syn_backlog` to 4096 made those errors go away, and my client is much happier with that server now.

### txqueuelen
* http://www.hep.ucl.ac.uk/~ytl/tcpip/linux/txqueuelen/datatag-tcp/
* http://www.cyberciti.biz/faq/gentoo-centos-rhel-debian-fedora-increasing-txqueuelen/

### tcp_max_syn_backlog
* https://www.acc.umu.se/~maswan/linux-netperf.txt
* http://e-mats.org/2010/01/tcp-drop-open-request-from/
* http://www.network-builders.com/help-kernel-tcp-drop-open-request-xxx-xxx-xxx-xxx-t53064.html
* https://tweaked.io/guide/kernel/

**Comment by oxtoacart** [comment]
This is now deployed to all servers.

**Comment by myleshorton** [comment]
Awesome @oxtoacart!

**Comment by aranhoide** [comment]
Great stuff!  I'm bookmarking this to take a look at those articles later.
