### ISSUE TITLE
Users get assigned to already retired proxy after their current proxy is retired

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3594]
An Iranian user was assigned to a proxy that appeared to be blocked.  I retired that proxy, which resulted in the user getting assigned to a new proxy.  That proxy didn't work either, and upon further investigation I saw that the new proxy had already been retired almost a month ago.

cc: @aranhoide @myleshorton

**Comment by oxtoacart** [comment]
Interestingly, the situation resolved itself eventually and the user got a different proxy assignment that works.

I tried deleting the user's AppData/Roaming/Lantern folder and running again.  What I observed was that the user got a lantern-2.0.14.yaml that contained the bad (retired) proxy.  After several minutes, the user got a new lantern-2.0.14.yaml with the good (not retired, not blocked) proxy.  So this seems to be somewhat repeatable.

cc: @uaalto

**Comment by oxtoacart** [comment]
@myleshorton Wondered if this might be due to caching at the CloudFront or CloudFlare level, but after some experimentation that doesn't appear to be the case.

**Comment by oxtoacart** [comment]
This same user has now reverted to a bad configuration, as the result of a fronted (CloudFront) cloud config fetch.

**Comment by myleshorton** [comment]
You're sure it was a CloudFront request that got the bad configuration right @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton Oh, you're right, I misread, looks like it was CloudFlare.

I see this in the log at the same time that we finish fetching the config:

```
Switching to chained fronter for future requests since it succeeded
```

I assume that means we fetched the config via a chained server.

**Comment by myleshorton** [comment]
Something appears seriously amiss here @aranhoide!

**Comment by oxtoacart** [comment]
Something promising that @myleshorton started looking into is whether some requests might have a wrong IP in the X-Forwarded-For (i.e. something else in the 1st position rather than the actual user's machine).

**Comment by aranhoide** [comment]
How did you identify that proxy as retired one month ago?  By IP?  Could it be the case that this IP has been reused? (Usual for DO).

Have we discarded caching on Cloudflare's end?  Even chained requests go through Cloudflare.

A wrong IP in the X-Forwarded-For would give the user a different proxy.  I can't see how a wrong client IP would make it more likely that the proxy is a bad one (barring geolookup problems, which doesn't seem to apply here).

**Comment by myleshorton** [comment]
No CloudFlare caching as far as we can see either from client tests or from CloudFlare analytics

**Comment by myleshorton** [comment]
We were looking at X-Forwarded-For for discrepancies between CloudFlare and CloudFront requests @aranhoide

**Comment by myleshorton** [comment]
On Valencia, for example, there's an extra 127.0.0.1 that messes things up, but that's not in production.

**Comment by fffw** [comment]
Can we construct `cURL` command to reproduce it?

**Comment by myleshorton** [comment]
I.e. X-Forwarded-For is different for CloudFlare versus CloudFront @aranhoide, but only on Valencia (so that doesn't appear to be the issue)

**Comment by oxtoacart** [comment]
@aranhoide I identified that the server was retired as follows:

1. Tried to ssh to the IP.  It accepted an ssh connection, but not my ssh key.

2. I then sorted the servers on the Digital Ocean list by IP, paged to the page where the IP should have appeared, and didn't see it.

3. I then searched for and found the IP in our backend-log.md along with a note saying that it had been retired, with a date in January.

**Comment by myleshorton** [comment]
That hasn't worked in my tests so far @fffw - we haven't been able to consistently reproduce it locally. It does appear that caching is not the problem, at least on CloudFlare or CloudFront (could be some other caching we don't know about).

**Comment by myleshorton** [comment]
On #2 above @oxtoacart you can also search in the DO UI by IP

**Comment by aranhoide** [comment]
@oxtoacart : I see.  It could have been retired more recently again, though.  The backend log doesn't have the IPs of the servers we retired because of blocking or overloading.

It's definitely possible that extracting the user IP from X-Forwarded-For is broken if there have been any changes recently on that regard.

**Comment by myleshorton** [comment]
We didn't find any actual issues in any X-Forwarded-For stuff @aranhoide on either the client of the server

**Comment by oxtoacart** [comment]
@myleshorton Thanks!  I could swear I tried that once before with no luck, but lo and behold it works!

@aranhoide So you're saying that we could have been assigned that same IP for a new proxy which then got retired again more recently?

**Comment by aranhoide** [comment]
@oxtoacart: that could be the case, but it doesn't seem likely.  In light of what we're discussing in the dev list, it would be a huge coincidence, and I think there's something else going on here.  Sorry to divert the discussion.

**Comment by myleshorton** [comment]
We still don't know why this is happening, but the cache busting in 2.0.15 fixes it.
