### ISSUE TITLE
Strip 127.0.0.1 from X-Forwarded-For

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3597]
Otherwise we'll bypass the requester IP logic on the config server. For older reference see:

https://github.com/getlantern/lantern/blob/release-2.0.1/src/github.com/getlantern/flashlight/client/reverseproxy.go#L27

**Comment by oxtoacart** [comment]
No longer necessary since we switched to fetching the config via HTTPS, which bypasses this.

**Comment by myleshorton** [comment]
This is actually necessary because using HTTPS to CloudFlare strips X-Forwarded-For!
