### ISSUE TITLE
   请问2.0.11  2.0.12  2.0.13  2.0.14 都更新了些什么？

### ISSUE THREAD

**Issue by qq205633** [getlantern/lantern#3598]
请问2.0.11  2.0.12  2.0.13  2.0.14 都更新了些什么？  
 先说说 2.0.14更新了啥也行，咋也没更新日志 更新说明呢？

**Comment by TodayChing** [comment]
# 笨蛋自己看嘛 Commit中写的很清楚

**Comment by ARwMq9b6** [comment]
好像是处理内存泄漏之类的问题： https://github.com/getlantern/lantern/commit/d419e9f8b9dcddc35bc40dc566a55b0fe4bf206e https://github.com/getlantern/lantern/issues/3580 。

**Comment by vgturtle127** [comment]
@qq205633 @TodayChing @ARwMq9b6 Uh, what's this about guys? :laughing: 

Something about a memory leak?

**Comment by ARwMq9b6** [comment]
@vgturtle127 The first guy is huntting for ChangeLog.

**Comment by vgturtle127** [comment]
@ARwMq9b6 Oh, OK. I was making sure Google translate wasn't being ridiculous again. :smile: 

Why isn't there a change log? The releases were tagged, but are they posted on the website or something?

**Comment by yfdyh000** [comment]
@vgturtle127 They are live on https://www.getlantern.org/ and auto updates.

**Comment by vgturtle127** [comment]
@yfdyh000 So you mean the changelog is provided with the installer, or when it auto updates it tells you the new changes?

**Comment by yfdyh000** [comment]
@vgturtle127 I don't insist, although it sounds good. At least it should have a list on https://www.getlantern.org/ and https://github.com/getlantern/lantern/releases.

**Comment by vgturtle127** [comment]
@yfdyh000 There isn't a list on either the website, nor do the releases have a changelog. No wonder why he is looking for a changelog. :laughing:

**Comment by uaalto** [comment]
These versions are deprecated, please download latest version.
