### ISSUE TITLE
Fail to load Fastly sites sometimes

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3609]
User reported that sites using fastly.net can be failed to load via Lantern in a period but can be accessed through VPN at the same time. From the logs, Lantern always connected to the site, but browser shows "Failed to load resource" or "net::ERR_CONNECTION_RESET". One such example is `travis-ci-org.global.ssl.fastly.net`.

**Comment by myleshorton** [comment]
This is interesting. I think thousandeyes installed on a machine in China could be very helpful for diagnosing things like this @fffw, @oxtoacart, @aranhoide, and @uaalto

**Comment by fffw** [comment]
Another example:

`curl -vLx localhost:8787 https://fast.wistia.net/embed/iframe/wg6nb5sqdq?autoPlay=true` results SSL handshake failure, but on the assigned proxy server, it can be fetched without problem.

**Comment by fffw** [comment]
Ok that's because of a flaw in  `detour.Detector`. Instead of returning `syscall.ECONNRESET`, sometimes it's `read: connection reset by peer`. It may also affect other sites.

**Comment by oxtoacart** [comment]
@fffw Is this ready for testing or is there any additional work needed?

**Comment by myleshorton** [comment]
This should be all set right @fffw?

**Comment by fffw** [comment]
Resolved by https://github.com/getlantern/lantern/pull/3726. I'm curious why it didn't close automatically after that PR merged.
