### ISSUE TITLE
500 Internal Server Error in Show Lantern page

### ISSUE THREAD

**Issue by Centaur** [getlantern/lantern#3610]
2.0.16  OS X El Capitan

![lantern](https://cloud.githubusercontent.com/assets/265524/13176632/ae7c284a-d74e-11e5-9860-f99bd1e7fc28.png)

But it seems the proxy works just fine.

**Comment by xiam** [comment]
Did you downloaded Lantern from the official site?

**Comment by Centaur** [comment]
@xiam Sure. https://github.com/getlantern/lantern-binaries 
![lantern2](https://cloud.githubusercontent.com/assets/265524/13180454/79e0d6c0-d763-11e5-90cd-b36c301cde32.png)

**Comment by Centaur** [comment]
Ooops. Problem disappears this morning.
