### ISSUE TITLE
希望能够不要自动设置全局 PAC 代理

### ISSUE THREAD

**Issue by Cat7373** [getlantern/lantern#3615]
很多东西会出问题，比如我用的 TGP 里的网页无法加载成功。
希望至少能有个选项来控制是否自动设置全局 PAC 代理。
我尝试过启动后手动设置为无代理，但过一小会后又自动设置回去了。

-------
系统: Windows 7 64bit
Lantern: 2.0.16 (20160219.041128)

**Comment by Cat7373** [comment]
Quick Google Translation↓
I do not want to be able to automatically set the global PAC agent
--------
A lot of things will go wrong, like I used TGP in the page can not be loaded successfully.
We are hoping at least to have an option to control whether to automatically set the global PAC agent.
I tried manually set to start after agentless, but after a little while and then automatically set back.

**Comment by Soys** [comment]
Lantern设置里有个全局代理,关掉就好了。但是建议要翻墙再开，不然多少会影响...像开着lantern的时候,Steam连接就会缓慢

**Comment by Cat7373** [comment]
@Soys 我一直都是关着的，但是代理依旧会被改。

**Comment by Soys** [comment]
请问你是用什么浏览器?如果有翻墙的浏览器插件的话,建议改为直连或禁用..如果是Internet选项里的话,关掉就好了

**Comment by Cat7373** [comment]
@Soys 我的问题里不是说了么，我尝试过在 Internet 属性 -> 连接 -> 局域网设置 里取消 Lantern 设置的 PAC 代理，但很快 Lantern 又自动设置回来了，我现在想取消的就是这个自动设置，与浏览器无关。

**Comment by yfdyh000** [comment]
@Cat7373 可以用这个方法: https://gochrome.info/lantern-no-pac/

**Comment by Soys** [comment]
有把这两个都点掉吗?
![1](https://cloud.githubusercontent.com/assets/8133994/13202070/ec31006e-d8c7-11e5-8130-4dc8989c323f.png)

**Comment by Cat7373** [comment]
@Soys 对啊我手动取消了这里的代理设置，然后在很快又设置回去了，具体时间没计算，应该在 3 分钟以内。
我有在设置页取消 代理全部流量 的选中。

**Comment by Soys** [comment]
我试了下  你开着蓝灯，它自己会把使用"自动配置脚本"里的地址写上,退出后自己没了

**Comment by Cat7373** [comment]
@Soys 对啊这不就是问题么，开着蓝灯就会影响我系统中一些程序的网络使用，所以我平时只能关掉 Lantern，但是关掉还怎么用？

**Comment by Cat7373** [comment]
@Soys 我找到了一个设置：
https://github.com/getlantern/lantern/blob/94f004884165deb0237c77a3157c7b249bd9cb8e/src/github.com/getlantern/flashlight/main/main.go#L42
这个似乎能避免自动设置 PAC 代理。
正在测试。

**Comment by Cat7373** [comment]
没有找到与这个有关的文档，所以不知道到底该怎么用这些东西，正在慢慢试- -

**Comment by Cat7373** [comment]
https://github.com/getlantern/lantern/issues/2776#issuecomment-126514935
我试图使用下面的命令行启动，但失败了↓
lantern.exe -startup -clear-proxy-settings
日志↓
Feb 21 10:50:08.153 - 0m0s DEBUG i18n: translate.go:106 Setting locale zh_CN
Feb 21 10:50:08.159 - 0m0s DEBUG flashlight: flashlight.go:229 ---- flashlight version: 2.0.16, release: 2.0.16, build revision date: 20160219.041128 ----
Feb 21 10:50:08.159 - 0m0s DEBUG flashlight.config: config.go:285 Using config dir C:\Users\Administrator\AppData\Roaming\Lantern
Feb 21 10:50:08.159 - 0m0s DEBUG flashlight.config: config.go:127 Checking config path: C:\Users\Administrator\AppData\Roaming\Lantern\lantern-2.0.16.yaml
Feb 21 10:50:08.159 - 0m0s DEBUG flashlight.config: config.go:93 File exists at C:\Users\Administrator\AppData\Roaming\Lantern\lantern-2.0.16.yaml
Feb 21 10:50:08.206 - 0m0s DEBUG flashlight.config: config.go:118 Found 1 chained servers
Feb 21 10:50:08.260 - 0m0s DEBUG yamlconf: yamlconf_disk.go:52 Configuration changed on disk, applying
Feb 21 10:50:08.260 - 0m0s DEBUG yamlconf: yamlconf.go:152 Loading per session setup
Feb 21 10:50:08.290 - 0m0s DEBUG yamlconf: yamlconf_disk.go:86 Configuration changed programmatically, saving
Feb 21 10:50:08.371 - 0m0s DEBUG flashlight.config: config.go:216 Returning config
Feb 21 10:50:08.371 - 0m0s DEBUG flashlight: flashlight.go:189 Processed config
Feb 21 10:50:08.371 - 0m0s DEBUG flashlight.statreporter: statreporter.go:84 Stat reporting turned off
Feb 21 10:50:08.371 - 0m0s DEBUG flashlight: flashlight.go:207 Running proxy
Feb 21 10:50:08.410 - 0m0s DEBUG flashlight: flashlight.go:427 Calling exit func

**Comment by Cat7373** [comment]
好吧，这个配置并不能避免设置 PAC，只是执行一个清理，然后退出 Lantern

**Comment by Cat7373** [comment]
找到启动 PAC 的代码了↓
https://github.com/getlantern/lantern/blob/94f004884165deb0237c77a3157c7b249bd9cb8e/src/github.com/getlantern/flashlight/main/main.go#L260
似乎是强制启动，没有相关的配置。

**Comment by Cat7373** [comment]
@yeahwu

**Comment by yeahwu** [comment]
自己编译去掉pac，或者用gray12编译的版本
或者用@kisesy的去pac，去弹窗小工具
或者可以直接提取俺的firefox-lantern里面的lantern单文件
编译方法：https://groups.google.com/forum/m/#!topic/fqlt/5w_cqIY-2EI

**Comment by Cat7373** [comment]
@yeahwu 
还是觉得给项目加个开关好些- -
不如我提个PR- -
但是我从没用过 Go 啊- -

**Comment by kuun** [comment]
我提交了这个pull request #3426, 但还没被merge.

I've created this pull request #3426, but  has not  been merged.

**Comment by myleshorton** [comment]
I just created a new PR that builds on what you wrote @kuun -- basically adds the UI and lets it be configured on the fly instead of only at startup. It's at #3628

**Comment by myleshorton** [comment]
This is in the pending 2.1.0 release.

**Comment by zhuziyi1989** [comment]
打开 http://127.0.0.1:16823/    
打开Settings
去掉选项钩：「Manage system proxy」
