### ISSUE TITLE
设置了迅雷代理后Lantern就废了...

### ISSUE THREAD

**Issue by Soys** [getlantern/lantern#3616]
使用迅雷下载东西没速度,于是设置lantern代理。代理后一样没速度就取消代理了,然后到现在都不能访问facebook和twitter那些网站..

**Comment by Rice321** [comment]
可以尝试卸载迅雷，看看是否能解决问题。

**Comment by uaalto** [comment]
We are aware of other software interacting with Lantern. The most we can do is show an alert for cases where we know there is such interaction.
I'll close this, but please feel free to open if you can provide more information so we can work with it.
Thank you!

**Comment by nsxq** [comment]
关闭迅雷的“多浏览器监控”可以用
