### ISSUE TITLE
Settings not preserved across runs on Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3622]
On the backend Lantern on valencia stores settings across runs. On Windows, however, the uninstaller is automatically run when you install a new Lantern version. That uninstaller currently removes all files in the install directory as well, also killing your settings. See #3607.

**Comment by myleshorton** [comment]
So this is all set right @sunshine19090?

**Comment by sunshine19090** [comment]
Is there a new build to verify this? or shall I use the one that I have now?

**Comment by sunshine19090** [comment]
oh sorry @myleshorton I thought this is #3702. Yeah this is good in windows 7. I will close this once I am done testing in all the systems.

**Comment by sunshine19090** [comment]
Working fine across all platforms.
