### ISSUE TITLE
Settings not sent to backend

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3625]
Running Version 9.0.3 (11601.4.4) on OSX, it looks like Lantern loses its websocket connection almost immediately, and the user is unable to set any settings.

**Comment by myleshorton** [comment]
Wow, it actually looks like this isn't just Safari. Also seeing it on Chrome Version 48.0.2564.109 (64-bit). Checking the release branch now!

**Comment by xiam** [comment]
Safari `Version 9.0.3 (11601.4.4)` is working fine here and it's storing settings, Chrome as well. Did you got any error log?

**Comment by myleshorton** [comment]
I think the problem was between the keyboard and the chair on this one -
more in a sec.

**Comment by myleshorton** [comment]
Yeah ignore this -- all good!
