### ISSUE TITLE
Allow users to configure Lantern to not automatically set the PAC file.

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3626]

**Comment by myleshorton** [comment]
This is a setting in the UI that you can toggle.

**Comment by myleshorton** [comment]
When you toggle the setting, it should change the system proxy setting.

**Comment by sunshine19090** [comment]
I am able to check that the toggle works with Chrome and IE as I could see the change in the proxy settings. In Firefox, it just stays at "Use System Proxy settings" even when I toggle. It never changes to "Automation proxy configuration URL". Is that the expected behavior? 

Also, I believe that the user wouldn't be able to visit blocked sites when they have disabled the "Manage System proxy" option. Am I understanding it correctly?

**Comment by oxtoacart** [comment]
@sunshine19090 Correct, when that option is disabled, you shouldn't be able to visit a blocked site.

I think the Firefox setting is okay.  As long as you can verify that it's not proxying traffic (i.e. check whatismyipaddress.com) then it should be okay.

**Comment by sunshine19090** [comment]
Thank you @oxtoacart!

**Comment by sunshine19090** [comment]
I enabled both proxy all traffic option and Manage system proxy option. Chrome and IE is able to proxy fine but I couldn't access the sites in Firefox.

**Comment by oxtoacart** [comment]
@sunshine19090 Does restarting Firefox help?

**Comment by sunshine19090** [comment]
Yes @oxtoacart, that worked but why I couldn't access it the first time? After restarting, I tried different scenarios and everything works.

**Comment by oxtoacart** [comment]
@sunshine19090 I think it might be related to #3689.

**Comment by oxtoacart** [comment]
@sunshine19090 The other thing that could be going on is that Firefox marked us as a bad proxy, and restarting cleared that flag.

**Comment by sunshine19090** [comment]
So it is really not an issue, is it @oxtoacart ? This setting is working fine in Windows 7 with all the browsers (for firefox after restarting). Once I am done testing in OSX, Linux and Windows 10, I will close it.

**Comment by oxtoacart** [comment]
@sunshine19090 Cool!

**Comment by myleshorton** [comment]
Yeah I agree on #3689 @oxtoacart. I'm going to do another 2.1.0 build fairly soon with that fix among others.
