### ISSUE TITLE
Add android build to Makefile packages target

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3630]
I was just going to quickly do this, adding `make android-release` to the packages target to make sure we always build new android versions every time.

Sound OK @atavism and @oxtoacart?

**Comment by oxtoacart** [comment]
Yes, though you'll want to make sure to clean first, otherwise make android-release just reuses the existing artifacts.

**Comment by myleshorton** [comment]
Hmnn...ok makes sense @oxtoacart. I might create a special target for that or something.
