### ISSUE TITLE
Add support for WebViews to Lantern mobile library

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3633]
It used to have this, see https://github.com/getlantern/lantern/blob/lantern-mobile/src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/sdk/Lantern.java#L139

**Comment by myleshorton** [comment]
Is this one all set @oxtoacart?

**Comment by oxtoacart** [comment]
No, @atavism worked around it by manually configuring that in Firetweet.  I don't know that this is super urgent, I just logged it as something we may want to add back at some point.

**Comment by myleshorton** [comment]
OK cool thanks @oxtoacart. @atavism do we need this for Alipay payments? Or are we assuming that endpoint will stay unblocked? That went through Lantern in one iteration I believe right?

**Comment by myleshorton** [comment]
Just checking on this one again @atavism -- how are we on Alipay payments here? That uses WebView as well right?
