### ISSUE TITLE
essichavoosh2015@yahoo.com

### ISSUE THREAD

**Issue by essichavoosh** [getlantern/lantern#3656]
Hi iam essi  because cheng my Email I can nat find my registering pege if possible for you to find that befor my Email is essichavoosh2013@yahoo.com.&now chavoosh2015@yahoo.comessi

**Comment by xiam** [comment]
Hey @essichavoosh, I'm afraid we can't help you with that. The current Lantern version does not require e-mail registration, you can just download and run it.
