### ISSUE TITLE
Lantern makes the Mac App can't connect to the Internet.

### ISSUE THREAD

**Issue by dozer47528** [getlantern/lantern#3665]
When I use lantern for about one hour, some of my apps can't connect to the Internet.
Even if I close the lantern, they can not connect to the Internet.
But not all of my apps has the problem.

Apps has this problem: Mails, Evernote, Calendar
Apps not has this problem: Chrome

After reboot, they will works well again.

**Comment by myleshorton** [comment]
Thanks @dozer47528. We're tracking this at #3039

You should be able to solve the problem without restarting by running this in Terminal:

```
sudo killall -9 networkd
```

Closing in favor of #3039
