### ISSUE TITLE
compile error when build linux binary

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3678]
Hi,
I encounter compile error when build linux binary。
It seems no need for docker now, but still encounter build problems, pls help diagnose and give your comments.THX!

issue details as follow:
________________________________________________________________________

[root@vultr lantern]#  make linux
** VERSION was not set, using default version. This is OK while in development.
Build tags:
Extra ldflags:
# runtime/cgo
In file included from /usr/include/features.h:399:0,
                 from /usr/include/errno.h:28,
                 from /usr/local/go/src/runtime/cgo/cgo.go:52:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
make: *** [linux-386] Error 2

**Comment by uaalto** [comment]
Hey @yuan78, this is caused by missing libraries in your system. Please refer to: http://stackoverflow.com/questions/7412548/error-gnu-stubs-32-h-no-such-file-or-directory-while-compiling-nachos-source
