### ISSUE TITLE
Lantern UI not showing send email button when window is resized

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#3681]
![cb2dde4d-2764-4e0a-a8c6-04212e2f7b7e](https://cloud.githubusercontent.com/assets/7864729/13404555/2207596a-dee8-11e5-9057-b52f15d85327.jpeg)
This seems to be affecting conversions

Lets change the .mobileadcontainter to 
400px wide
200px high
and the top padding to 130px

Also change "get the app via email" text to have
10px padding on the top.

This should make it so even if users scale their window below 550px they will still see the send email button.

We could also try dynamically scaling the whole thing again?
what do you think @xiam

**Comment by Derekf5** [comment]
@xiam actually i may just need to redesign completely because just scaling it down makes it look a bit off.    I will try to change the layout a bit by tomorrow afternoon.

**Comment by myleshorton** [comment]
Yeah I agree just making it a bit smaller seems like the way to go @Derekf5!

**Comment by xiam** [comment]
Thanks @Derekf5, try to consider different images and sizes for mobile and desktop as well. To avoid losing detail when scaling down.

**Comment by Derekf5** [comment]
@myleshorton so you think we should just try the scale as opposed to taking time redesigning the layout?

**Comment by xiam** [comment]
Does not have to be a complete redesign, I think that having different images and special sizes and positions for the elements that we already have should be enough.

**Comment by myleshorton** [comment]
Yeah agreed @xiam!

**Comment by Derekf5** [comment]
Cool @xiam and @myleshorton i will work on it this week.   when are you planning on sending out the next release?  and when would it be good to have the specs for these changes?

**Comment by myleshorton** [comment]
This next release could go out any time really, potentially even today. So if it doesn't make it into this one, it could just go into the next.

When you say specs is that something different than the screens themselves? I don't think this is a big enough change to warrant full specs if that's something different =).

**Comment by Derekf5** [comment]
@myleshorton  yeah i really just mean getting the graphic resources over to @xiam :)

**Comment by Derekf5** [comment]
i should be able to knock this out tomorrow though.

**Comment by myleshorton** [comment]
Awesome thanks @Derekf5!

**Comment by sunshine19090** [comment]
@Derekf5 - I see the "Get the app" button in windows in all the browsers. I tried resizing and it works fine. Atleast there are scrolls so I could see the button. The only thing that I noticed is that the footer looks odd. May I know what system you are using?

Chrome:
![image](https://cloud.githubusercontent.com/assets/11394369/13407808/2259148e-dedf-11e5-9ac4-b15080904cf4.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/11394369/13407814/2d5d1664-dedf-11e5-90aa-a0630d48d377.png)

IE:
![image](https://cloud.githubusercontent.com/assets/11394369/13407833/44121972-dedf-11e5-8a3e-8f9831e0751b.png)

**Comment by myleshorton** [comment]
Yeah the point is that the user shouldn't have to scroll @sunshine19090

**Comment by sunshine19090** [comment]
Oh okay, I thought Derek couldn't see it at all. Thanks for clarifying @myleshorton!

**Comment by Derekf5** [comment]
@xiam Im not sure different images and layouts for different browser resizes make sense after thinking it through a bit more.   Im wondering if we can scale everything, container sizes, images, elements, padding etc when the browser get below a certain size?  For instance if we detected the browser was below 675px high we could resize the ad container to 75% as well as the download button, and all of the padding between elements in the container.   When the window got so small it didnt make sense to continue to resize we could just show the get app via email text, and download button, and link.  

If you think this is suitable i can get you the window sizes that should trigger resize.
Let me know what you think.

**Comment by xiam** [comment]
Yes we can @Derekf5, that's the thing with media queries. We cannot scale buttons but we can change size and text. Having the window sizes and the triggered changes sounds great.

**Comment by Derekf5** [comment]
awesome thanks @xiam  i will play with the UI in dev mode on chrome, and figure out where we need to set the triggers.   on the button note, we have those in as images currently, can we still not scale them?

I will likely have this for you by tm morning when you get to work.

**Comment by Derekf5** [comment]
Hey @xiam Here are the changes to the mobile ad.   I will list the overall changes first, and then describe the trigger points for the media queries.

**Overall changes**
- "Welcome to Lantern" Text
   1. Change Font size to 18px
   2. Change Line height to 20px
- Mobile-ad container
    1. Change Top padding to 125px
    2. Change Height to 440px
- "Get App via email text": Change margin-top to 5px
- Android download link: Change margin-top to 5px

**Trigger Points, and Container resize**
These Trigger points should resize the Mobile ad container when _either_ the height _or_ width is hit when resizing the window.  Currently only width changes trigger resize.
   
1. When the Window Reaches 
750px width OR 620px height
Mobile ad container changes to 
500px width x 390px height

2. When the Window Reaches 
600px width OR 565px height
Mobile ad container changes to 
375px width x 325px height

3. When the Window Reaches 
400px width OR 500px height
The Main ad image should be deleted, but the email sign up form should remain, along with all the text in the ad container.  the ad container should then change to
300px width x 175px height

Let me know if you have any questions!
