### ISSUE TITLE
Improve flashlight unit test coverage

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3685]
Many of the packages used by flashlight have some unit test coverage, but a lot of the code inside flashlight itself isn't covered with unit tests right now.  Would be good to improve on that.

@myleshorton Let me know what you think is the priority on this.

**Comment by myleshorton** [comment]
Ha! Yeah I've been thinking about that too and just noticed you opened a ticket on it! Yeah things like main.go and config.go have really low coverage but a high line count. I think it would be really nice to improve that.
