### ISSUE TITLE
[2.1.0] Toggling "Proxy all traffic" option has no effect before restart Lantern

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3689]

**Comment by fffw** [comment]
Basically Lantern doesn't reconfigure anything except the logic embeded in settings.go when settings changed. Need to subscribe for changes in main.go

**Comment by fffw** [comment]
Ok I went to the wrong direction and added notifier structure to settings.go (the refactor is still useful), until finally found that the root cause is that we reuse `ReverseProxy`. As a workaround, we can reconfigure client each time `ProxyAll` option changed.

**Comment by myleshorton** [comment]
Makes sense @fffw great catch!

**Comment by sunshine19090** [comment]
I am testing in Windows 7 with all the browsers and Proxy all traffic option is working fine for me when toggling without restarting Lantern. But I remember seeing this problem in the previous releases where I had to use "Show Lantern" after enabling/disabling proxy all option.
