### ISSUE TITLE
Version 2.0.16 can hardly access blocked sites.

### ISSUE THREAD

**Issue by DavidSuccess** [getlantern/lantern#3692]
ISP: China uincom
Address: Beijing
Connection type: LAN

**Comment by can-can** [comment]
+!

**Comment by jxmlhdf** [comment]
plz released the 2.1.0>=version and to enable the p2p feature

**Comment by jxmlhdf** [comment]
.

**Comment by aranhoide** [comment]
Can you please send your logs, as indicated here?

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by aranhoide** [comment]
@DavidSuccess @jxmlhdf have you sent your logs, as per the previous comment?

We are considering that the problem may be that we've moved many of our proxies to a different provider in Singapore.  These may offer worse service to users of China Telecom (not sure about uincom).

If you are still having problems, can you please write me to aranhoide@getlantern.org?  If you do, I'll assign you to a server in Tokyo to test whether that's faster for you.

**Comment by jxmlhdf** [comment]
Hi, Thank you for the consideration.
The 2.0.16 seems like works normally in my region with the ip
139.59.255.199  at this moment.
My  ISP is chinxx union.
However, the speed is far less than the JP servers.
Keep in touch.

**Comment by aranhoide** [comment]
Thanks @jxmlhdf, I've assigned your IP to a server in Tokyo to see whether that helps.  You should notice the change in a few minutes (you may want to confirm by visiting www.whatismyipaddress.com with Lantern enabled).  Please let me know if that's any faster.

**Comment by myleshorton** [comment]
There is a general issue with some users getting poor connectivity to Singapore that we're gradually addressing.
