### ISSUE TITLE
Lantern stopped working on a test machine with error "Unable to dial any masquerades?"

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3698]
It looks like Lantern ran out of masquerades.  Restarting Lantern fixed the problem.  My best guess is that there was a transient network issue that caused us to run out of working masquerades from which we didn't recover successfully.

**Comment by myleshorton** [comment]
Interesting. That's a great point @oxtoacart - it would be good to test 2.1.0 with going on and offline.

**Comment by myleshorton** [comment]
No longer relevant.
