### ISSUE TITLE
Settings.yaml file is not updated when restarting the system(windows 7) without quitting lantern

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3702]

**Comment by sunshine19090** [comment]
@oxtoacart  Do you have a new build to verify this?

**Comment by oxtoacart** [comment]
@sunshine19090 Not yet.  I think @myleshorton is going to put out a new 2.1.0 build once everything we want in there is ready.

**Comment by sunshine19090** [comment]
Now the settings are saved each and every time a change is made in the UI. So the settings are saved even when restarting the system without quitting lantern. Closing this issue now.
