### ISSUE TITLE
Always run Lantern as background service

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3711]
Whenever we close the app from the open apps list, Lantern should stay running as a background service unless/until the user disconnects the VPN service. Re-opening the app should obviously reflect the correct on/off state.

**Comment by oxtoacart** [comment]
@atavism Isn't the VPN service already a background service?  What do we gain by running the rest of the app as a background service?

**Comment by myleshorton** [comment]
Is this one all set @atavism?

**Comment by atavism** [comment]
Yep, ticket is no longer relevant
