### ISSUE TITLE
Version number is displayed as "now" in the footer

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3712]
![image](https://cloud.githubusercontent.com/assets/11394369/13507501/ad7c2132-e137-11e5-8922-51093a47311d.png)

**Comment by xiam** [comment]
Hmm, this happened before and @oxtoacart send a patch for that that fixed it, here: https://github.com/getlantern/lantern/issues/3672. I also confirmed this is still happening on latest QA.

**Comment by myleshorton** [comment]
Yup good catch @sunshine19090. Happens on latest valencia too. I'll look into it.

**Comment by oxtoacart** [comment]
Sorry about that.  I know what happened, can fix quickly.
