### ISSUE TITLE
Automatically commit mobile version.properties with new releases

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3715]
src/github.com/getlantern/lantern-mobile/app/version.properties currently gets updated with releases, but not committed and so not incremented across versions.

**Comment by myleshorton** [comment]
I'd also be happy to take this one @atavism

**Comment by oxtoacart** [comment]
Alternately, to avoid having to mess with git, could we just auto-generate this version number from the current date and time, e.g. '201603070642`?

**Comment by myleshorton** [comment]
Yeah I'm not sure what it's actually used for internally. Is it just for display purposes @atavism or is there more stuff that relies on that value?

**Comment by oxtoacart** [comment]
I think we have to continually increase the version in the app manifest, otherwise the app fails to upgrade.

**Comment by myleshorton** [comment]
Makes sense. I'm totally fine with auto-generating it internally, although if it really has to be in the manifest isn't that inherently external?

**Comment by oxtoacart** [comment]
Yeah, if it's in the manifest it's external, but a user has to dig pretty deep to find it.  Plus, a date isn't a bad version number anyway.  @atavism Since I'm thinking about it now, I'm going to give this a crack.
