### ISSUE TITLE
Support use of Pushy.me in Lantern Mobile

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3720]
Initially this is needed to support notifying users when they receive referral bonuses, but longer term might be used for other things as well.

**Comment by oxtoacart** [comment]
Per discussion with @aranhoide, it seems like a good idea to add an endpoint on our backend where we can record the Pushy device registration ID and associate it with the client's userid.  This will allow the backend to notify all of a user's devices using those registration IDs.

This relies on changes that we're making for pro, such as having a userid.  @atavism Is there a branch in which Lantern Mobile already has these changes from which I can start?

cc: @uaalto @myleshorton

**Comment by uaalto** [comment]
As I've just explained on the Slack conversation, if Pushy doesn't allow for a cleaner background notification system that doesn't require spawning a new process, what do we really obtain from using it?
The notifications server that I explained yesterday in the check-in works in this use case, and wouldn't require more changes to the pro-server. Additionally, it supports multiple platforms, as long as they support websockets. I think the use of Pushy here doesn't buy us anything, and constrains us to their way.
Currently, the prototype works by just registering with your user-id in the notifications server (with any device), and we don't need to track any device per user in Redis and the pro-server.

**Comment by oxtoacart** [comment]
@uaalto I agree with you.  I was just going by an email thread that seemed to indicate we had chosen Pushy.  I'm glad you jumped in.

**Comment by oxtoacart** [comment]
Looks like we're going with custom websockets for notification, as implemented by @uaalto.

**Comment by uaalto** [comment]
Thanks @oxtoacart for all your comments, info and benchmarking!

**Comment by myleshorton** [comment]
Cool. I still think we should think about the websocket vs x issue a bit
more, but I agree with implementing our own solution.
