### ISSUE TITLE
Allow port 1883 on proxies and front-end

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3721]
Needed for us to use [Pushy](https://pushy.me).  Related to #3720.

**Comment by myleshorton** [comment]
Cool thanks @oxtoacart. I propose closing since it sounds unlikely we'll use pushy at this point right? Unless it's on the table just so we don't have to worry about scaling?

**Comment by oxtoacart** [comment]
It looks 99% certain we're not using pushy, closing this.
