### ISSUE TITLE
apk link bleeds into new line on edge

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3722]
Not sure this is actually edge-specific, but here's what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/1143966/13535964/ef8ff250-e1f1-11e5-8b44-8606ed8ac790.png)

**Comment by myleshorton** [comment]
Not I highlighted that text, so that's not part of the bug. FYI @Derekf5 and @xiam. Maybe just a smaller font there?

**Comment by Derekf5** [comment]
Yes @xiam @myleshorton  looks like edge is displaying the link text as bold, which is incorrect and probably messing up the size.

but if removing the bold attribute from the link text doesnt suffice we could just drop the size to 7pt.
*note the "android download link:" text should remain bold.

**Comment by xiam** [comment]
Sounds good @Derekf5

**Comment by myleshorton** [comment]
Cool thanks @Derekf5. Edge is only 1% of our users, so not urgent, but we'll knock it out either way.

**Comment by Derekf5** [comment]
@myleshorton @xiam yeah, seems edge specific to me after testing firefox chrome, and safari.

**Comment by xiam** [comment]
I don't see this happening anymore since we're using a short link now.
