### ISSUE TITLE
After installing Lantern in Mac, version is shown as 2.0.0 instead of 2.1.0 under applications folder

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3723]

**Comment by myleshorton** [comment]
Ha yeah you're talking about if you select "get info" on the app right @sunshine19090?

Looks like that's a longstanding bug, as those values are hard-coded in the Info.plist in the template. Good catch. I'm going to push it out of 2.1.0 because I don't think it should block release, but will fix.

**Comment by sunshine19090** [comment]
Yes @myleshorton, that's right!
