### ISSUE TITLE
这几天lantern失效了吗？

### ISSUE THREAD

**Issue by Lix1993** [getlantern/lantern#3725]
山西大同

联通网

lantern在windows和andriod都不能用了

**Comment by Neillll** [comment]
+1 我也不能用

**Comment by royaso** [comment]
kakade

**Comment by Leafney** [comment]
+1 我也不能用了

**Comment by libing8964** [comment]
北京联通也不能用

**Comment by Rice321** [comment]
请问各位可以查看一下打开Lantern之后你们的IP地址在哪里吗？谢谢。
@Lix1993 @Neillll @Leafney @libing8964

**Comment by bigtan** [comment]
新加坡digitalocean

**Comment by Rice321** [comment]
@bigtan  速度跟之前比，有不一样吗？

**Comment by bigtan** [comment]
@Rice321 前一段时间速度很好，最近几天几乎无法使用。

这个似乎和新加坡国际出口光缆挖断了有关吧

**Comment by Rice321** [comment]
@bigtan 新加坡国际出口光缆被挖断了？请问你的邮箱是bigtan@live.com吗？我等会给你写一封邮件，请查收。

**Comment by bigtan** [comment]
@Rice321 是的

**Comment by Lix1993** [comment]
@Rice321 
荷兰，
刚才上了一下，可以正常使用了

**Comment by Rice321** [comment]
@Lix1993 请问你人在哪个地理位置呢？

**Comment by LaoZhongGu** [comment]
好几天不能用了，不知道啥原因，难道是因为开会期间？坐标深圳。

**Comment by Lix1993** [comment]
@Rice321  山西 大同

**Comment by LaoZhongGu** [comment]
昨天刚说不能用的，今天又好了，不知道啥原因。

**Comment by Rice321** [comment]
@LaoZhongGu 请问现在打开Lantern之后你所用的IP地址是多少？请查看一下 www.whatismyipaddress.com

**Comment by aranhoide** [comment]
Please don't publish your own IP addresses, nor those of proxies, publicly.  If necessary, email that kind of data privately to @Rice321 or to team@getlantern.org.

**Comment by Rice321** [comment]
Thanks @aranhoide for the heads-up! Very interesting that @Lix1993 is in China and his IP with Lantern is assigned to Amsterdam. Is that normal?

**Comment by aranhoide** [comment]
Sometimes whatismyipaddress.com and similar sites will report the wrong location of a proxy, especially if it was launched recently, because VPS providers reuse IPs across data centers.

On the other hand, it's possible that our servers have made some mistake in geolocating @Lix1993's client.

To know for sure what's happening here, it would be most helpful if @Lix1993 could please send us his Lantern logs, as explained in

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

although in this case it may be fastest if they're emailed to aranhoide@getlantern.org instead of team@getlantern.org.

**Comment by LaoZhongGu** [comment]
128.199.248.85现在的IP地址 @Rice321 。

**Comment by yuzishui** [comment]
没有失效，只是你那里不稳定而已。

在 2016-03-11 10:56:58，"LaoZhongGu" <notifications@github.com> 写道：


128.199.248.85现在的IP地址 @Rice321 。

**Comment by LaoZhongGu** [comment]
Thanks。

**Comment by Lix1993** [comment]
@aranhoide  i've sent log file to  aranhoide@getlantern.org and hope that doesnt cause any inconvenience.

**Comment by aranhoide** [comment]
Thank you very much @Lix1993 !  The logs show that you've been correctly geolocated as being in China, and the server you've been assigned is in Singapore.  whatismyipaddress.com currently displays it correctly.

So I think what happened here is that this used to be the IP of an Amsterdam VPS run by Digital Ocean.  That VPS was destroyed, and then the IP was assigned to one in Singapore.  In general, it takes some time for geolocation databases to update, so whatismyipaddress would show the IP as being in Amsterdam for some time.

**Comment by aranhoide** [comment]
Is this geolocation error the main topic of this issue, or is there anything else that we need to address here?

**Comment by Lix1993** [comment]
@aranhoide 
thank you , 
Lantern works welland  the IP was assigned toSingapore now .

**Comment by aranhoide** [comment]
Thanks for your report!
