### ISSUE TITLE
新人求教在官网下载安卓APP安装后如何在手机上翻墙？

### ISSUE THREAD

**Issue by lihuayahaitang** [getlantern/lantern#3728]
我打开后就一个开关，打开后也不能翻墙，求教。。。。

**Comment by Lix1993** [comment]
这几天好像有问题，开了lantern也不能翻

**Comment by Lix1993** [comment]
应该是墙的问题

**Comment by Rice321** [comment]
@lihuayahaitang @Lix1993  请问两位是用设备的安卓系统是什么？使用的是哪家运营商？

**Comment by Lix1993** [comment]
@Rice321 
nexus5 安卓6.0.1

山西联通

**Comment by lihuayahaitang** [comment]
@Rice321 可以倒是可以就是速度太慢了根本无法看视频啊。。。请问能配置吗？怎么提速呢？

**Comment by Rice321** [comment]
@lihuayahaitang 请讲一下你所使用的手机品牌，型号，安卓系统及运营商

**Comment by lihuayahaitang** [comment]
@Rice321 我用的MX4，安卓5.01 移动的  但是我用的无线网啊。。。怎么能提速啊？

**Comment by Amosvista** [comment]
@lihuayahaitang 有可能是hosts的问题，可以看看是不是被限制了

**Comment by CHN008** [comment]
昨天手机版(Android)的不能用,今天可用了,手机网友版Youtube很流畅.
