### ISSUE TITLE
能手动设置地区吗，之前稳定版是日本的IP速度很快，而新加坡的巨慢

### ISSUE THREAD

**Issue by hhhaiai** [getlantern/lantern#3733]
能手动设置地区吗，之前稳定版是日本的IP速度很快，而新加坡的巨慢

**Comment by Rice321** [comment]
@hhhaiai  能否将你的email地址给我？我请我们团队的工程师看看能否帮你解决问题。

**Comment by hhhaiai** [comment]
@Rice321  sanbo.xyz@gmail.com多谢。

**Comment by hhhaiai** [comment]
看到后请跟我联系，多谢。麻烦了

2016-03-08 10:25 GMT+08:00 Rice321 <notifications@github.com>:

**Comment by Rice321** [comment]
@hhhaiai  已发送邮件，请查收并予以回复，谢谢。

**Comment by hhhaiai** [comment]
ok

2016-03-09 10:49 GMT+08:00 Rice321 <notifications@github.com>:

**Comment by hhhaiai** [comment]
get it,thx

**Comment by jimliang** [comment]
怎么设置的？同求。

**Comment by hhhaiai** [comment]
hi:
   不行的，貌似是google分流的问题。跟lant 服务器没关

2016-03-29 17:33 GMT+08:00 Jimliang <notifications@github.com>:
