### ISSUE TITLE
Cannot build headless linux version on 2.0.16

### ISSUE THREAD

**Issue by kendou** [getlantern/lantern#3736]
It works fine building 2.0.10, 2.0.14, but failed on 2.0.16.

After updating the source to latest 2.0.16, and run below command:
_sudo HEADLESS=true make linux_

It complains:
_/bin/bash: line 8: npm: command not found
make: *** [src/github.com/getlantern/flashlight/ui/resources.go] Error 127_

OS: Ubuntu 14.04.3 LTS
Go: 1.6.

**Comment by fffw** [comment]
Did you change anything in Dockerfile? Especially this line because `npm` is installed as part of `nodejs`:
> RUN yum -y install nodejs && yum clean packages

**Comment by kendou** [comment]
No. But I figured out something, below command runs fine:

_sudo HEADLESS=true make_

but this command fails with the error message mentioned in the ticket:

_sudo HEADLESS=true make **linux**_

Maybe this can give you some clue.

**Comment by xiam** [comment]
@kendou We recently changed our targets to not use docker by default, can you try `make docker-linux`?

**Comment by kendou** [comment]
@xiam Yes `make docker-linux ` works, thanks! I think the document needs to be updated: https://github.com/getlantern/lantern/wiki/Installation:-server?

**Comment by xiam** [comment]
@kendou done, thanks for the heads up.
