### ISSUE TITLE
Lantern is not proxying at times when Mac is started after a long time

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3742]
I didn't work with Mac for 2 days and lantern was not running. Today, when I started the system and launched lantern, it is not proxying.  Verified in whatismyipaddress.com that lantern is not proxying. When checked Chrome for proxy settings, it said Effective proxy settings as Direct and Original proxy settings as Lantern. So I reapplied the settings and then it started working. What does it mean?

This happened on friday too(just once) but I neither could figure out why it is happening nor could reproduce it intentionally.

**Comment by myleshorton** [comment]
Moving this to 2.1.1 @sunshine19090, as it's certainly not new. Basically if Chrome ever has trouble proxying through Lantern, it will mark it as a bad proxy and won't use it. So it sounds like for some reason Lantern didn't work right away when you started it, and Chrome marked it as a bad proxy. It's possible there's some sort of race condition on startup.

Do you have your logs handy? That could be helpful.

**Comment by sunshine19090** [comment]
Yeah sure @myleshorton, I will send the logs. Initially I started testing with safari and when it wasn't working, I checked in chrome. Of course, it could be the same reason. Just letting you know in case if you will find it different.

**Comment by fffw** [comment]
The logs look clear. It should be solely the bad proxy issue. Maybe we need to dig into Chromium code for clues.

**Comment by myleshorton** [comment]
Have you seen this one recently @sunshine19090?

**Comment by sunshine19090** [comment]
No @myleshorton, I am closing this.
