### ISSUE TITLE
Implement push notifications 

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3745]

**Comment by oxtoacart** [comment]
@atavism @myleshorton Shall we close this?

**Comment by myleshorton** [comment]
Yup!

On Mon, Mar 21, 2016 at 6:23 AM, oxtoacart <notifications@github.com> wrote:

> @atavism <https://github.com/atavism> @myleshorton
> <https://github.com/myleshorton> Shall we close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3745#issuecomment-199274367>
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
