### ISSUE TITLE
Add authentication to dashboard.getlantern.org

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3750]
Or some form of security...

**Comment by aranhoide** [comment]
I have temporarily powered this droplet off while this is fixed.  Although the dashboard doesn't show IP addresses, we probably don't want to let everyone access it.

**Comment by fffw** [comment]
So you'll find a "with GitHub" button on https://dashboard.getlantern.org. Only members of the core team are allowed to login via GitHub.
