### ISSUE TITLE
Mobile - Language in UI is not changed for Desktop version side menu, the switch as well as the message when the switch is flipped

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3751]
When I changed the language other than English, the language in Lantern UI for Desktop version didn't change. Also, the messages when the switched is turned ON/OFF is also displayed in English.

**Comment by myleshorton** [comment]
Seems like this is worth fixing for 2.1.0 @atavism

**Comment by myleshorton** [comment]
To be clear, not the on/off, but at least translations for Chinese and Farsi. It looks like Chinese is already in there. If we just add Farsi we can switch.

**Comment by myleshorton** [comment]
Seems like we'll need lots of translations for pro also @atavism correct?

**Comment by myleshorton** [comment]
OK this should be working for both Farsi and Chinese in the latest qa build @sunshine19090. Can you verify? @atavism I just added those strings directly to git -- still not sure what the best way to sync with transifex is =).

**Comment by atavism** [comment]
@myleshorton Yes, but all of those strings were already published to Transifex https://www.transifex.com/otf/lantern/viewstrings/#en_US/lantern-android

**Comment by atavism** [comment]
We should probably automatically pull in new translations whenever we do a new build. I can open a ticket for that.. @myleshorton I also opened a new PR with the latest translations: https://github.com/getlantern/lantern/pull/3763

**Comment by atavism** [comment]
@myleshorton Might as well, yeah. BTW, it looks like the desktop screen text was translated to Chinese but never to Farsi https://www.transifex.com/otf/lantern/viewstrings/#fa_IR/lantern-android/65157026

**Comment by sunshine19090** [comment]
@myleshorton and @atavism my mobile doesn't have chinese and Farsi option. So I tried Deutsch and Cestina, still the side menu "Desktop verson" and the screen for Desktop version too is shown up in English but all the other menus have changed to the respective language that I have selected. I will upload the screenshots soon.

**Comment by sunshine19090** [comment]
![screenshot_2016-03-10-10-30-53](https://cloud.githubusercontent.com/assets/11394369/13680063/bac3d8a2-e6ab-11e5-9ea9-f59d6c02547a.png)
![screenshot_2016-03-10-10-30-48](https://cloud.githubusercontent.com/assets/11394369/13680064/bac6cf1c-e6ab-11e5-8703-0fab30a22dd4.png)

**Comment by sunshine19090** [comment]
FYI @myleshorton @atavism - after changing the language (lantern running), I opened lantern app to check language and lantern switched off automatically. I had to turn it ON again. This happens only when I change the language because the system reloads everything. I am sure that this is not a normal scenario where a user keep changing their language.

**Comment by myleshorton** [comment]
Cool yeah we only really care about the language for Chinese and Farsi for the purposes of this release @sunshine19090, and those changes are in there, so going ahead and closing and releasing. Thanks!

**Comment by myleshorton** [comment]
Hmn...actually I'll update to the latest from transifex -- might as well. one sec.

**Comment by atavism** [comment]
@myleshorton I opened this too https://github.com/getlantern/lantern/pull/3765

**Comment by myleshorton** [comment]
Perfect -- I'll merge and rebuild. Thanks @atavism! What's the process for syncing the local version with Transifex (the other direction)?

**Comment by myleshorton** [comment]
OK @sunshine19090 the new build is up if you just want to try it one last time for mobile. I think switching to french should work, for example.

**Comment by sunshine19090** [comment]
@myleshorton is this working for you when you select the languages Chinese and Farsi? If so, shall we close it?

**Comment by atavism** [comment]
@sunshine19090 If some text shows up in English, that just means it hasn't been translated yet in whatever language you have selected.

**Comment by myleshorton** [comment]
Yeah TBC @sunshine19090 ON/OFF is an image that won't be translated in any language in the current version. I don't have Farsi or Chinese locales, but the translations are in there.

**Comment by myleshorton** [comment]
Yeah so we'll just continually be adding more translations as they come in...closing for now!
