### ISSUE TITLE
On first run on OSX, Lantern fails to set the system proxy

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3752]
I believe it's because it hasn't yet called setuid and made sure that succeeds. It'll then get 

`3/8/16 1:46:01.194 PM pac-cmd[21696]: pac-cmd failed to obtain PreferencesLock`

and won't try again after obtaining permissions.

**Comment by myleshorton** [comment]
This seems pretty significant @fffw, as it means Lantern won't successfully set the system proxy on the first run for first-time users.

**Comment by myleshorton** [comment]
Ignore more on this one for now @fffw - might be unique to my branch.

**Comment by louy2** [comment]
First run on Arch Linux fails to set system proxy as well. May I ask how is Lantern setting it?

**Comment by myleshorton** [comment]
Let's just make absolutely sure this one's not a problem.
