### ISSUE TITLE
Errors sending HTTP requests to analytics

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3753]
These logs are also filling up the disk space at /var/log/upstard/http-proxy.log. They seem to be sterr logs that don't have file size limits! I'll log a separate bug for that.

```
Mar 06 06:32:09.597 ERROR http-proxy-lantern.analytics: analytics.go:191 Could not send HTTP request to GA: Post https://ssl.google-analytics.com/collect: net/http: TLS handshake timeout
panic: runtime error: index out of range

goroutine 32 [running]:
github.com/getlantern/http-proxy-lantern/analytics.(*AnalyticsMiddleware).normalizeSite(0xc8200f0340, 0xc821f4e1c7, 0xe, 0x0, 0x0, 0x0)
        /Users/merlin/workspace/go/src/github.com/getlantern/http-proxy-lantern/analytics/analytics.go:144 +0x97a
github.com/getlantern/http-proxy-lantern/analytics.(*AnalyticsMiddleware).submitToGoogle(0xc8200f0340)
        /Users/merlin/workspace/go/src/github.com/getlantern/http-proxy-lantern/analytics/analytics.go:91 +0xa9
created by github.com/getlantern/http-proxy-lantern/analytics.New
        /Users/merlin/workspace/go/src/github.com/getlantern/http-proxy-lantern/analytics/analytics.go:62 +0x3f4

goroutine 1 [runnable]:
net.runtime_pollWait(0x7f51c27cc168, 0x72, 0xc820010120)
        /Users/merlin/.gvm/gos/go1.5.3/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820111e20, 0x72, 0x0, 0x0)
        /Users/merlin/.gvm/gos/go1.5.3/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820111e20, 0x0, 0x0)
        /Users/merlin/.gvm/gos/go1.5.3/src/net/fd_poll_runtime.go:78 +0x36
```

**Comment by myleshorton** [comment]
Just came across this @oxtoacart while snooping around our servers with @aranhoide

**Comment by oxtoacart** [comment]
It's this line that's failing:

```go
if name[len(name)-1] == '.' {
```

I guess this means there's an empty name.

**Comment by myleshorton** [comment]
Two things jump out at me here @oxtoacart:

1. Why are the line numbers so off? Is it possible this proxy was running an older version?
1. It looks like this was also running go 1.5.3, but I thought we had upgraded all servers to 1.6?

On the first point, "Could not send HTTP request to GA" is on line 206 in the current file, not line 191 as reported in the panic.

It seems like the fix is probably still correct, but we also might another issue with deploying old versions somehow.

**Comment by aranhoide** [comment]
@oxtoacart says he built the latest http-proxy-lantern release with go 1.5.3.  I don't know about the line numbers.

**Comment by myleshorton** [comment]
It looks like the http proxy deployed on that machine was old -- probably this version from Feb https://github.com/getlantern/http-proxy-lantern/blob/ca9a89d94d0de8dd84bdc745ceff71373ddf45ba/analytics/analytics.go

**Comment by myleshorton** [comment]
Actually scratch the above comment @oxtoacart and @aranhoide -- as @aranhoide astutely pointed out, it's just the log that's old and not the version of http-proxy on that machine! The log is from Mar 06 06:32:09.597, the day before the previous deployment, which likely indicates this problem was actually fixed in that deployment. Either way the associated PR does add more safety checks, so I'll go ahead and merge it.

Thanks guys.

**Comment by oxtoacart** [comment]
Thanks for the review @myleshorton.  FYI, we have to build the server with 1.5 right now because 1.6 introduced a change to the http package that breaks our Apache mimicry.  Specifically, it returns a 400 error if the request doesn't include a Host header, which is different behavior than Apache.
