### ISSUE TITLE
http-proxy standard error logs growing without bound

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3754]
logs in /var/log/upstart are filling up the whole disk!

**Comment by myleshorton** [comment]
I think this might be inherent to the log package @oxtoacart but not sure?

**Comment by oxtoacart** [comment]
Nice find @myleshorton and @aranhoide!

**Comment by aranhoide** [comment]
I think the problem with /var/log/upstart can be handled by redirection and logrotate in the lantern_aws end.  The problem remains that http-proxy is logging way too many "use of closed TCP connection" messages.  We can handle these with logrotate, but at the cost of throwing away more useful logs.

**Comment by oxtoacart** [comment]
@aranhoide Your suggestion of just redirecting stderr to stdout seems to have done the job.

**Comment by oxtoacart** [comment]
Upstart actually does cap the number of archived logs per process, the problem is that as configured and with the rate at which the http-proxy was logging those Google Analytics errors, we were ending up with a lot of logs on disk.

**Comment by aranhoide** [comment]
So this "use of closed TCP connection" was an issue with Google Analytics?

**Comment by oxtoacart** [comment]
Oh, maybe I misunderstood.  The Google Analytics issue was the panic on an empty name coming back from the reverse DNS lookup that we do.  The `use of closed TCP connection` error is unrelated.

**Comment by myleshorton** [comment]
Yeah exactly @oxtoacart. @aranhoide there were really two major issues. The first was the 'use of closed network connection' as the most common error going to syslog and the http-proxy log, with the daily syslog file growing without bounds (this was the biggest problem really), but the other was the syserr daily  http-proxy logs going to the upstart directory with all the analytics errors. Those files were hitting 4+ gbs themselves and we're basically only the analytics panics AFAICT.

**Comment by myleshorton** [comment]
All set.
