### ISSUE TITLE
windows   IE浏览器无法显示此页  chrome可以

### ISSUE THREAD

**Issue by impnote** [getlantern/lantern#3756]

**Comment by xtrabet** [comment]
我也碰到一样的问题 你系统版本是不是比较低啊。。。我升级到8以后就没出现过这个问题 Internet选项里有一个Intranet设置 应该打开。你去试一试。

**Comment by impnote** [comment]
我的就是windows 8.1

**Comment by impnote** [comment]
重装了个系统 问题依旧= =

**Comment by impnote** [comment]
我是这么解决的  IE设成默认，再把lantern设成开机启动

**Comment by impnote** [comment]
重启以后问题又出现了 = =

**Comment by Rice321** [comment]
@impnote  请问IE是无法显示UI还是根本无法使用Lantern? 电脑里有装迅雷吗？

**Comment by impnote** [comment]
@Rice321 现在好了把IE设成默认浏览器 lantern设为开机启动，但每次开机先别急着连网 等lantern开启后再连 就没问题了

**Comment by xiam** [comment]
This is probably related to https://github.com/getlantern/lantern/issues/4175 and we already tested a fix for that.

**Comment by sunshine19090** [comment]
Testing this fix in #4175. Closing this now.
