### ISSUE TITLE
Auto-update failure

### ISSUE THREAD

**Issue by fanrangjun** [getlantern/lantern#3757]
Bothered by someone.
I didn't get his log.
The user is in China.
His twitter account is @XiYanZi

**Comment by fffw** [comment]
The OS is Windows XP right? Verified on a Windows XP VM:

> Mar 10 01:48:04.404 - 0m10s ERROR autoupdate: autoupdate.go:97 Problem checking for update: Problem fetching update: Post https://update.getlantern.org/update: x509: certificate signed by unknown authority

**Comment by fffw** [comment]
Windows XP ranks 6 on the list of OS version on our loggly events. We probably want to provide solid support. Two options:

1. Switch to a cert provider that supports Windows XP SP3 (DST Root CA X3 is trusted, but [certain features is not](https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394)).

2. Add an option to use `InsecureSkipVerify` tls config when performing auto-update.

I prefer option 2 and make sure to always proxy requests to update server.

How do you think @xiam and @myleshorton ?

**Comment by myleshorton** [comment]
I actually need to get our wildcard cert soon anyway (actually started this today), so that would make option 1 pretty easy. It will probably take a week or two though.

**Comment by fffw** [comment]
Yeah if we can have the wildcard cert which has legacy OS support, that would be okay.

**Comment by fffw** [comment]
Related to https://github.com/getlantern/lantern/issues/3589

**Comment by xiam** [comment]
This should not be valid anymore.
