### ISSUE TITLE
a problem  with fedora 

### ISSUE THREAD

**Issue by weihai4099** [getlantern/lantern#3771]
when I  make lantern :
npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm WARN package.json gulp-minify-html@1.0.6 No repository field.
/bin/bash:行10: gulp: 未找到命令
Makefile:182: recipe for target 'src/github.com/getlantern/flashlight/ui/resources.go' failed
make: *** [src/github.com/getlantern/flashlight/ui/resources.go] Error 127 

what can I do ?

**Comment by bill363yang** [comment]
npm i gulp -g
It is in README
