### ISSUE TITLE
Share Lantern to my friends

### ISSUE THREAD

**Issue by 11hwu2** [getlantern/lantern#3791]
Lantern is installed on my Android phone. I wana share it to my friends, but they can't get lantern for Android, because the share link seems very old: https://github.com/getlantern/lantern/blob/lantern-mobile/src/github.com/getlantern/lantern-mobile/latest-builds/lantern.apk

**Comment by aranhoide** [comment]
Tentatively giving this a high priority and squeezing it into 2.2.1 because it seems a quick fix and it might impact growth, which is a current concern.  @xiam: feel free to change any of this (and/or reassign to something else) if you know better.

**Comment by atavism** [comment]
Thanks, @11hwu2 and @aranhoide. I actually didn't realize we were pointing to such an old build with the share messages. I went ahead and fixed this here: https://github.com/getlantern/lantern/pull/4132/files

**Comment by atavism** [comment]
We updated the share links a few releases ago. Closing this.
