### ISSUE TITLE
Lantern strips Host header, breaks sites that use virtual hosting

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3792]
In particular http://connect.ancestry.com and http://dna.ancestry.com.

Various resources at c.mfcreative.com return 404 errors, like http://c.mfcreative.com//SSS_NAV/1.0.1080/Content/2.1/header.css.

We need to understand what's going on here to determine if it's potentially a broader issue.

![screen shot 2016-03-16 at 11 19 53 am](https://cloud.githubusercontent.com/assets/5000654/13819865/0f132c16-eb69-11e5-8ef0-67f9caad42b7.png)

**Comment by oxtoacart** [comment]
I've confirmed that without Lantern, I'm able to load http://c.mfcreative.com//SSS_NAV/1.0.1080/Content/2.1/header.css okay.

If I manually curl that URL from the proxy server itself, it loads fine as well, so it looks like it's something in the proxying code of Lantern itself that's causing the problem.

**Comment by oxtoacart** [comment]
Furthermore, if I use HTTPS, it works even through Lantern - https://c.mfcreative.com//SSS_NAV/1.0.1080/Content/2.1/header.css

So, it must be something in how we're proxying HTTP traffic.

**Comment by oxtoacart** [comment]
Interestingly, if I send the traffic through the Lantern client but skip the server proxy and go directly to mfcreative.com, it still doesn't work.  So, it's something in the client-side reverseproxy.

**Comment by oxtoacart** [comment]
Okay, this seems to be failing because we're stripping out the HOST header somewhere along the way.  That's potentially a big problem because anything that uses virtual hosting requires the HOST header.

**Comment by oxtoacart** [comment]
Okay, fixed.  BTW, I checked with release 2.0.10 and this was a problem on there too, just less likely to manifest because we didn't used to send everything through the local proxy.

**Comment by aranhoide** [comment]
Any reason why we might have been stripping this on purpose, or does it seem clear this was accidental?

Sometimes these fixes cause regressions because there was an obscure, but somewhat valid, reason for the broken behavior.

**Comment by oxtoacart** [comment]
@aranhoide Good question.  It's not actually us who were stripping this, rather it's Go 1.6:

https://github.com/golang/go/commit/6e11f45ebdbc7b0ee1367c80ea0a0c0ec52d6db5#diff-b97af51863ce82bf2a13003b52034aa9R762

**Comment by oxtoacart** [comment]
The client fix fixed this only for direct traffic.  It looks like traffic proxied through our servers is still broken, so I guess we need to use the same trick on those too.

**Comment by myleshorton** [comment]
It seems like in practice this won't be a significant issue for direct traffic @oxtoacart because most direct traffic will bypass our proxy entirely..

On the http proxy side, we're also still running go 1.5.3, so I'm surprised this would still be an issue as long as we include the Host header in the client request. What am I missing?

**Comment by oxtoacart** [comment]
@myleshorton As I mentioned on IM, because of the Edge trick, as of 2.1.0 everything goes through the client proxy, so the client-side fix is indeed necessary.

I'm looking into the server side now.  I tried manually adding the host header, but that didn't fix this problem.

**Comment by myleshorton** [comment]
Everything went through the proxy before, though, @oxtoacart -- the domains to bypass are dynamically added to the pac as detour discovers they're directly accessible.

**Comment by myleshorton** [comment]
I don't believe any of that changed in 2.1.0

**Comment by oxtoacart** [comment]
@myleshorton Our server-side proxy appears to be consciously dropping the host portion of the URL - https://github.com/getlantern/http-proxy/blob/master/forward/forward.go#L178

I'm going to try removing that and see if it fixes this issue.  The next question is why we are dropping the host from the URL.

**Comment by myleshorton** [comment]
That url.Opaque handling looks like it was added to solve this:

https://github.com/getlantern/http-proxy/issues/70

**Comment by oxtoacart** [comment]
@myleshorton Sure enough, that took care of it.  It appears that this particular web host requires the host in both the URL as well as the Host header.  Absent either of those, it returns a 404.

**Comment by oxtoacart** [comment]
In particular, I'm doing this:

```go
outReq.URL.Opaque = req.URL.Opaque
```

**Comment by myleshorton** [comment]
Instead of this right?

```
outReq.URL.Opaque = req.URL.EscapedPath()
```

**Comment by oxtoacart** [comment]
@myleshorton Correct.

**Comment by myleshorton** [comment]
Does that still work with https://github.com/getlantern/http-proxy/issues/70 and https://github.com/getlantern/lantern/issues/3344 @oxtoacart?

Sorry I don't really know that Opaque even is =).

**Comment by oxtoacart** [comment]
Opaque seems to be the unparsed form of the URL, which gets used if present, otherwise ignored.  I think my fix worked because req.Opaque is empty and so it falls back to the usual, which includes the host.  That unfortunately won't help with #3344.
