### ISSUE TITLE
Support auto-updates on Android

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3797]
The UI has been created already.  What's left to do is to update our auto-update server to support updates to the APK (i.e. add Android support).  For MVP, we're not going to do binary diffs, we're just doing full APK updates.

**Comment by atavism** [comment]
Hey @Derekf5, I'm wrapping this up and wanted to remind you what the design for this looks like...

![image](https://cloud.githubusercontent.com/assets/6346213/15223307/9fc7648e-1828-11e6-9bc0-20f17a57ec9f.png)

Still look fine to you? The check for a new version happens periodically so the user will see this at some point during an active session (likely when they first open the app). I also thought we could include a side-menu option for users that press "Not Now". Not sure what icon we should use though. What do you think?

![image](https://cloud.githubusercontent.com/assets/6346213/15223311/a6c8e9d8-1828-11e6-9ba1-dd9c7a96cefb.png)

CC: @myleshorton

**Comment by Derekf5** [comment]
Hey @atavism thanks for the reminder.    This all sounds good, the only changes i would make visually would be to make the rounded corners have a radius of only 2dp.   and change the color of the buttons to the lantern blue #00BCD4

**Comment by atavism** [comment]
Updated side-menu icon:

![image](https://cloud.githubusercontent.com/assets/6346213/15230740/1b815ba2-184c-11e6-83c0-559b7dd03a28.png)

Additional screenshots:

![image](https://cloud.githubusercontent.com/assets/6346213/15230754/2f8a8d12-184c-11e6-856d-9c36c708268b.png)

![image](https://cloud.githubusercontent.com/assets/6346213/15230788/5bf543c4-184c-11e6-9852-2ea39b304e86.png)

**Comment by Derekf5** [comment]
@atavism just a reminder, just checked the version you sent out.   The only changes i would make visually would be to make the rounded corners have a radius of only 2dp. and change the color of the buttons to the lantern blue #00BCD4 

It also looks like the like on the outside of the "not now" button is making that button slightly larger

**Comment by atavism** [comment]
Thanks, @Derekf5. Just made those changes. I'll send you an updated build

**Comment by Derekf5** [comment]
@atavism Awesome, the update flow worked really well for me!
