### ISSUE TITLE
Send locale from all clients in user create and user update

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3810]

**Comment by myleshorton** [comment]
This will also apply to the desktop of course @xiam

**Comment by oxtoacart** [comment]
Not super-urgent for now as sending out non-localized notifications in English isn't the end of the world (per @fffw).

**Comment by xiam** [comment]
Please see https://github.com/getlantern/pro-server-client/pull/15, I also added the same functionality to desktop, although no real locale is being sent yet we're prepared for that.
