### ISSUE TITLE
Not always proxying config requests through CloudFlare

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3814]
$ heroku logs -t | grep x.x.x.x

2016-03-18T14:28:22.112577+00:00 heroku[router]: at=info method=GET path="/cloud.yaml.gz" host=hostname request_id=3416694a-6bad-4229-8304-1e73300dd871 fwd="x.x.x.x,54.240.147.55" dyno=web.4 connect=0ms service=16ms status=200 bytes=62153

The config server only sees the CloudFront but not the CloudFlare request!!

**Comment by oxtoacart** [comment]
@myleshorton Interesting.  I double-checked the CloudFlare configuration and it looks fine - it's set to Caching Level = No Query String, which means that it only serves from cache if URL doesn't include a querystring.  Ours does (from what I can see in the code).

**Comment by oxtoacart** [comment]
The CloudFlare requests go through the chained servers.  Perhaps they're stripping out the querystring somehow - I wonder if this could be related to the changes I made for #3792.

**Comment by oxtoacart** [comment]
I double checked, and Heroku will log the querystring as part of the Path if it's present.  So it looks like the request that came through CloudFront didn't have a querystring.

**Comment by oxtoacart** [comment]
BTW, regarding #3792.  I just ran a test with the old http-proxy and the new http-proxy, and both pass the request to config-server including the querystring, so I don't think the problem is there.

**Comment by oxtoacart** [comment]
Okay, the reason that I don't see a querystring for CloudFront is that CloudFront is configured not to pass querystrings to the origin server.

**Comment by oxtoacart** [comment]
So, I'm not sure what's going on for you @myleshorton .  In my case, the client is sending a query string for both CloudFlare and CloudFront.  The http-proxy is passing the querystring to CloudFlare.  Both CloudFlare and CloudFront are issuing requests to the config-server.  So I seem to be in okay shape.

Can you send me the ip of your proxy server that's handling the CloudFlare request?

**Comment by myleshorton** [comment]
Yeah I'm now on a new IP, @oxtoacart, but no matter what I keep getting assigned to 45.55.145.84.

Good find on CloudFront not passing the query string along. I'm now seeing both requests at least make it to the config server and am continuing to investigate!

**Comment by oxtoacart** [comment]
@myleshorton Okay, cool.

**Comment by myleshorton** [comment]
So this is odd @oxtoacart. Now the request is definitely making it through CloudFlare and is hitting the config server, but it looks like it might not be going through our proxy.

In the "fwd" field below, I would expect to see 3 IPs -- my own IP, the proxy IP, and a CloudFlare IP, but I only see two. Is that what you see?

```
2016-03-18T15:53:12.727972+00:00 heroku[router]: at=info method=GET path="/cloud.yaml.gz?77b74bb3-d546-4e90-b293-7084c1b2044c" host=host request_id=4bae4c60-2eb9-47d4-8734-1f0e8f3388e0 fwd="x.x.x.x,x.x.x.x" dyno=web.2 connect=0ms service=9ms status=304 bytes=117
```

**Comment by oxtoacart** [comment]
No, I see 3 - me, proxy, cloudflare.

**Comment by myleshorton** [comment]
Looks like this is likely caused by #3816
