### ISSUE TITLE
Apparent race condition loading and using masquerades on startup

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3815]
```
Mar 18 16:03:32.704 - 0m0s Mar 18 16:03:32.704 - 0m0s TRACE fronted: direct.go:73 Adding 2396 candidates for cloudfront
ERROR flashlight.util: http.go:110 Could not complete request with: http://xxxxxxx.cloudfront.net/lookup/, Get http://xxxxxxx.cloudfront.net/lookup/: Could not dial any masquerade?
Mar 18 16:03:32.704 - 0m0s Mar 18 16:03:32.704 - 0m0s DEBUG flashlight.util: http.go:205 Got an error: Get http://xxxxxxx.cloudfront.net/lookup/: Could not dial any masquerade?
```

**Comment by oxtoacart** [comment]
@myleshorton It's interesting that the error from flashlight.util doesn't have a timestamp.  That means it must have run before we even fully initialized logging.  What branch is this on?  devel or issue-3800?

**Comment by oxtoacart** [comment]
@myleshorton 

I was able to reproduce reliably on issue-3800 and devel by adding `time.Sleep(15 * time.Second)` to the beginning of `loadCandidates`.  I could not reproduce on master.  So, this looks like something that was broken on devel, which should help narrow it down.

**Comment by oxtoacart** [comment]
@myleshorton Never mind, was able to reproduce on master now as well.

**Comment by oxtoacart** [comment]
So what's happening is that geolookup is trying to dial with fronted before `fronted.Configure()` has been called.  From what I can tell, this shouldn't cause big problems because we just use geolookup for logging and Google Analytics, so I'm dropping to a P2.

**Comment by myleshorton** [comment]
Cool @oxtoacart. So `fronted.Configure()` is always called before the config lookup though right?

**Comment by oxtoacart** [comment]
@myleshorton Actually it looks like there might be a race condition there too.

**Comment by oxtoacart** [comment]
@myleshorton Take that back, the config has been initialized from disk and we've applied it to fronted before we start polling.
