### ISSUE TITLE
cloud yaml doesn't include latest proxied sites

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3816]
I'm not sure exactly how the cloud.yaml is regenerated, but I believe it's regenerating the masquerades at least daily. Some things, however, are not in sync with the client, particularly proxied sites, which do not include getiantem.org in the cloud version, for example. how is that generated @aranhoide?

**Comment by aranhoide** [comment]
Masquerades are regenerated daily, but the lantern_aws project has its own copy of the source files.  The daily update is meant to filter out obsolete masquerades.

We should probably refactor at least the genconfig source files into its own git repo, which we'd include as a submodule in lantern and lantern_aws.  That said, the manual step of deploying this to the cloudmaster would remain.  We can get increasingly fancy about this, but in the meanwhile we need to remember remember that any important change in these source files needs to be replicated to lantern_aws/salt/update_masquerades/ or it will be overridden by the cloud.yaml supplied by the config server.

**Comment by myleshorton** [comment]
OK I just made a clarifying note in the genconfig README.
