### ISSUE TITLE
No repository field

### ISSUE THREAD

**Issue by ngujdi** [getlantern/lantern#3821]
make lantern 
npm WARN package.json gulp-minify-css@1.2.4 No repository field.
npm WARN package.json gulp-minify-html@1.0.6 No repository field.
/bin/bash: line 10: gulp: The command was not found
make: *** [src/github.com/getlantern/flashlight/ui/resources.go] error 127

**Comment by fffw** [comment]
@ngujdi You may install nodes and try `npm install -g gulp` to overcome this. It reminds us that the README should be revised, thanks!

**Comment by aranhoide** [comment]
@fffw : tentatively assigning to you since you seem likely to know how to update the README.  Feel free to reassign or change priority if you know better.

**Comment by aranhoide** [comment]
Also setting 2.2.1 milestone to convey that this is not really tied to any release and could be fixed any time IIUC.

**Comment by fffw** [comment]
Ha README was already updated. Closing.
