### ISSUE TITLE
lantern last version for mac os 10.11.1 can't run

### ISSUE THREAD

**Issue by sungerk** [getlantern/lantern#3823]
I reinstalled lantern, it does not run  , I uninstalled it with AppCleaner2.0

**Comment by fletchere** [comment]
lantern version 2.1.1 really sucks.

**Comment by myleshorton** [comment]
Hey @sungerk are you using 2.1.1?

**Comment by sungerk** [comment]
yes,it's flash back

**Comment by sungerk** [comment]
the error log
16/3/28 下午8:03:19.478 amfid[292]: /Applications/Lantern.app/Contents/MacOS/lantern signature not valid: 0xfffefa2a


16/3/28 下午8:04:49.000 kernel[0]: proc 491: load code signature error 4 for file "lantern"

**Comment by sungerk** [comment]
@myleshorton 

this is the log:

Apr 01 13:09:02.496 - 0m0s DEBUG i18n: translate.go:106 Setting locale en_US
Apr 01 13:09:02.515 - 0m0s DEBUG flashlight: flashlight.go:151 ---- flashlight version: 2.1.1, release: 2.1.1, build revision date: 20160316.175552 ----
Apr 01 13:09:02.515 - 0m0s DEBUG flashlight: flashlight.go:78 Initializing configuration
Apr 01 13:09:02.515 - 0m0s DEBUG flashlight.config: config.go:274 Using config dir /Users/sunger/Library/Application Support/Lantern
Apr 01 13:09:02.517 - 0m0s DEBUG flashlight.config: config.go:122 Checking config path: /Users/sunger/Library/Application Support/Lantern/lantern-2.1.1.yaml
Apr 01 13:09:02.517 - 0m0s DEBUG flashlight.config: config.go:85 File does not exist at /Users/sunger/Library/Application Support/Lantern/lantern-2.1.1.yaml
Apr 01 13:09:02.517 - 0m0s DEBUG flashlight.config: bootstrap.go:140 Opening bootstrap file from: /Applications/Lantern.app/Contents/Resources/en.lproj/lantern.yaml
Apr 01 13:09:02.517 - 0m0s DEBUG tarfs: tarfs.go:57 Using local filesystem at /Applications/Lantern.app/Contents/MacOS/../Resources/en.lproj
Apr 01 13:09:02.700 - 0m0s DEBUG yamlconf: yamlconf_disk.go:52 Configuration changed on disk, applying
Apr 01 13:09:02.700 - 0m0s DEBUG yamlconf: yamlconf.go:152 Loading per session setup
Apr 01 13:09:02.782 - 0m0s DEBUG yamlconf: yamlconf_disk.go:86 Configuration changed programmatically, saving
Apr 01 13:09:03.144 - 0m0s DEBUG flashlight.config: config.go:211 Returning config
Apr 01 13:09:03.144 - 0m0s DEBUG flashlight: main.go:184 Got first config
Apr 01 13:09:03.144 - 0m0s DEBUG flashlight: pac.go:67 Saved icon file to: /tmp/escalatelantern.ico
Apr 01 13:09:03.145 - 0m0s DEBUG filepersist: filepersist.go:122 Warning - unable to chmod /Users/sunger/Library/Application Support/byteexec/pac-cmd: chmod /Users/sunger/Library/Application Support/byteexec/pac-cmd: operation not permitted
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight.config: bootstrap.go:140 Opening bootstrap file from: /Applications/Lantern.app/Contents/Resources/en.lproj/.packaged-lantern.yaml
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight.config: bootstrap.go:57 Opening file at: /Applications/Lantern.app/Contents/Resources/en.lproj/.packaged-lantern.yaml
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight.config: bootstrap.go:61 Error reading file open /Applications/Lantern.app/Contents/Resources/en.lproj/.packaged-lantern.yaml: no such file or directory
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight.config: bootstrap.go:57 Opening file at: /Users/sunger/Library/Application Support/Lantern/.packaged-lantern.yaml
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight.config: bootstrap.go:61 Error reading file open /Users/sunger/Library/Application Support/Lantern/.packaged-lantern.yaml: no such file or directory
Apr 01 13:09:03.145 - 0m0s ERROR flashlight: main.go:216 Could not read settings? open /Users/sunger/Library/Application Support/Lantern/.packaged-lantern.yaml: no such file or directory
Apr 01 13:09:03.145 - 0m0s DEBUG flashlight: main.go:222 Starting client UI at 127.0.0.1:16823
Apr 01 13:09:03.147 - 0m0s DEBUG flashlight.ui: ui.go:125 UI available at http://127.0.0.1:16823
Apr 01 13:09:03.147 - 0m0s DEBUG flashlight: flashlight.go:87 Preparing to start client proxy
Apr 01 13:09:03.147 - 0m0s DEBUG flashlight.geolookup: geolookup.go:68 Requested refresh
Apr 01 13:09:03.148 - 0m0s DEBUG geolookup: geolookup.go:133 Fetching ip...
Apr 01 13:09:03.148 - 0m0s DEBUG flashlight.util: http.go:98 Using dual fronter
Apr 01 13:09:03.148 - 0m0s DEBUG flashlight.util: http.go:248 Creating new HTTPClient with proxyAddrFN: 0x416a2a0
Apr 01 13:09:03.148 - 0m0s DEBUG flashlight.util: http.go:263 Waiting for proxy server to come online
Apr 01 13:09:03.149 - 0m0s DEBUG flashlight.util: http.go:133 Sending request via DDF
Apr 01 13:09:03.150 - 0m0s DEBUG fronted: direct.go:40 Configuring fronted
Apr 01 13:09:03.150 - 0m0s DEBUG fronted: direct.go:71 Loading candidates
Apr 01 13:09:03.151 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.211.73}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:85 Vetting 20 initial candidates in parallel
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.client: client.go:155 Configure() called
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.198.70}
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.util: http.go:248 Creating new HTTPClient with proxyAddrFN: 0x416a2a0
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.util: http.go:263 Waiting for proxy server to come online
Apr 01 13:09:03.153 - 0m0s Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.client: client.go:167 Client configuration initialized
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.client: client.go:168 Requiring minimum QOS of 0
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.client: client.go:170 Proxy all traffic or not: false
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.192.175.148}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.192.156.65}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{amgdgt.com 54.230.245.203}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.146.16}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{chatgame.me 54.192.225.203}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{pgastatic.com 54.230.226.167}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.193.133}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.192.206.128}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{nhlstatic.com 54.192.226.51}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.222.157}
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.195.109}
DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.192.233.45}
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.230.212.153}
Apr 01 13:09:03.153 - 0m0s DEBUG flashlight.client: balancer.go:34 Adding 2 chained servers
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.176.17}
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.215.65}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.201.35}
Apr 01 13:09:03.153 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.158.47}
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.203.133}
Apr 01 13:09:03.154 - 0m0s DEBUG fronted: direct.go:179 Dialing to &{cloudfront.net 54.182.144.234}
Apr 01 13:09:03.154 - 0m0s DEBUG flashlight: flashlight.go:117 Starting client HTTP proxy
Apr 01 13:09:03.154 - 0m0s DEBUG flashlight.client: client.go:92 About to listen
Apr 01 13:09:03.154 - 0m0s DEBUG flashlight: flashlight.go:109 Starting client SOCKS5 proxy
Apr 01 13:09:03.155 - 0m0s ERROR flashlight: flashlight.go:129 Error starting client proxy: Unable to listen: "listen tcp: lookup localhost: no such host"
Apr 01 13:09:03.155 - 0m0s DEBUG flashlight: main.go:331 Calling exit func

**Comment by myleshorton** [comment]
This issue should be fixed in 2.1.2 @sungerk - sorry for the delay. That version is in testing now.

**Comment by myleshorton** [comment]
You can get it at https://s3.amazonaws.com/Lantern/lantern-installer-qa.dmg

**Comment by sungerk** [comment]
thank you very much, i used shadowsocks to connect the  network ，and i can open Google.but i can't open you skydrive.
the website is:,
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9E585887F914E6D9</RequestId>
<HostId>
Spc8LtxfR/K+h5nq7u5B1WIAVxOp3SvQmltVjzS4McbIJMDc1WAqaLnfKlrnEMqcU4xn4+GBc9s=
</HostId>
</Error>

Would you like to send the dmg file to my gmail or any other way?
My email is kcjsunger@gmail.com

**Comment by misuqian** [comment]
Access Denied
Any help?
