### ISSUE TITLE
balancer_test fails randomly on TestLoadBalancing

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3831]
I'm not sure if this is a problem with the test or the logic in balancer itself, but it would be nice to clean this up so that we get consistently passing unit test runs.

**Comment by oxtoacart** [comment]
For example:

```
--- FAIL: TestLoadBalancing (0.73s)
        Location:       balancer_test.go:132
	Error:		Should be true
	Messages:	6 not within 180 of 200
```

**Comment by oxtoacart** [comment]
@fffw It's not clear to me how the QualityFirst strategy would result in any sort of load balancing.  Is there even any point in having the TestLoadBalancing test?

**Comment by fffw** [comment]
I introduced the test in hope to find a strategy to load balance in some way but forgot to remove. Sure we can remove / comment out that test @oxtoacart

**Comment by oxtoacart** [comment]
Cool, I'll take care of it, thanks @fffw!
