### ISSUE TITLE
[Soved after upgrade to 10.11.4]Lantern.app quit immediately after it is launched

### ISSUE THREAD

**Issue by doodle8866** [getlantern/lantern#3844]
lantern(2.0.16) suddenly stopped to work on my computer (Mac OS 10.11.3). It quit immediately after it is launched. 
lantern.log read:
`i18n: translate.go:106 Setting locale en_US`
`flashlight: flashlight.go:229 ---- flashlight version: 2.0.16, release: 2.0.16, build revision date: 20160219.041128 ----`
`flashlight.config: config.go:285 Using config dir ~/Library/Application Support/Lantern`
`flashlight.config: config.go:127 Checking config path: ~/Library/Application Support/Lantern/lantern-2.0.16.yaml`
`flashlight.config: config.go:93 File exists at ~/Library/Application Support/Lantern/lantern-2.0.16.yaml`
`flashlight.config: config.go:118 Found 2 chained servers`
`yamlconf: yamlconf_disk.go:52 Configuration changed on disk, applying`
`yamlconf: yamlconf.go:152 Loading per session setup`
`yamlconf: yamlconf_disk.go:86 Configuration changed programmatically, saving`
`flashlight.config: config.go:216 Returning config`
`flashlight: flashlight.go:189 Processed config`
`flashlight.statreporter: statreporter.go:84 Stat reporting turned off`
`flashlight: flashlight.go:207 Running proxy`
`flashlight: flashlight.go:427 Calling exit func`

Install latest version (2.1.1) does not work either. My guess is there's some bad configuration files or caches. I try to uninstall lantern completely and install again.  I clean everything lantern related in my home folder as following, and the issue remains.  Running in new account got same result.
/Applications/Lantern.app
~/Library/Application Support/lantern-2.0.16.yaml
~/Library/Logs/Lantern
~/Library/LaunchAgents/org.getlantern.plist
/tmp
/private/var/folders/

It happened once before, and I got lantern work again via restore system from time machine. I don't have backup this time.
Lantern asked for admin permission on first launch. I wonder what it did in system folder.  I use `find` command and got nothing. Any help?

**Comment by doodle8866** [comment]
Lucky for me Apple released new upgrade and the problem is gone now. I really hope lantern could print out more diagnose info.

**Comment by myleshorton** [comment]
Interesting @doodle8866 thanks. What OSX version were you using previously?

**Comment by doodle8866** [comment]
I upgrade from 10.11.3. But it's not the os version that lantern conflict with. It was some changes I made in /private/var directory causing the problem and they got repaired in an upgrade.

**Comment by sungerk** [comment]
i used osx 10.11.1,10.11.3,  10.11.4  .I had the same problem

**Comment by handelxh** [comment]
@doodle8866  how do u fix this bug?

**Comment by aranhoide** [comment]
Closing since this seems very specific to user's changes in `/private/var`.  If other people have similar issues, please open a new ticket describing your problem in detail.
