### ISSUE TITLE
recipe for target 'liblantern.aar' failed when buid lantern android

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3853]
All sdk and dependencies hv installed and hv set path for Android Sdk and Java 

But still show recipe for target 'liblantern.aar' failed when I  buid lantern android

#make android-lib
** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
gomobile: toolchain partially installed, run `gomobile init`
Makefile:514: recipe for target 'liblantern.aar' failed

How to fix it , THX !

**Comment by aranhoide** [comment]
Leaving milestone blank since this doesn't seem a bug with Lantern but at most some opportunity to improve documentation.   @atavism I assigned to you since I guess you're building this stuff all the time.  Feel free to reassign etc.

**Comment by myleshorton** [comment]
Did you run go `gomobile init` @yuan78?

**Comment by atavism** [comment]
Hi @yuan78, please re-open if this is still an issue.
