### ISSUE TITLE
slideshare can't access 

### ISSUE THREAD

**Issue by zqhxuyuan** [getlantern/lantern#3854]
hi, I'm chinese, so you know it. I can success access facebook and other wall site, but can't access 
 slideshare , when I hit http://slideshare.net on chrome ,  the url change to : 

https://www.slideshare.net/uas/login?trk=sentinel_org_block&session_redirect=https%3A%2F%2Fwww.slideshare.net%2Fuas%2Flogin%3Ftrk%3Dsentinel_org_block%26session_redirect%3Dhttps%253A%252F%252Fwww.slideshare.net%252Fuas%252Flogin%253Ftrk%253Dsentinel_org_block%2526session_redirect%253Dhttps%25253A%25252F%25252Fwww.slideshare.net%25252Fuas%25252Flogin%25253Ftrk%25253Dsentinel_org_block%252526session_redirect%25253Dhttps%2525253A%2525252F%2525252Fwww.slideshare.net%2525252Fuas%2525252Flogin%2525253Ftrk%2525253Dsentinel_org_block%25252526session_redirect%2525253Dhttps%252525253A%252525252F%252525252Fwww.slideshare.net%252525252Fuas%252525252Flogin%252525253Ftrk%252525253Dsentinel_org_block%2525252526session_redirect%252525253Dhttps%25252525253A%25252525252F%25252525252Fwww.slideshare.net%25252525252Fuas%25252525252Flogin%25252525253Ftrk%25252525253Dsentinel_org_block%252525252526session_redirect%25252525253Dhttp%2525252525253A%2525252525252F%2525252525252Fwww.slideshare.net%2525252525252F

looks like go to dead loop and finaly 404

**Comment by garyelephant** [comment]
Seems like it has been fixed.

**Comment by ChaosEternal** [comment]
@garyelephant  Hi can you share some details about how this issue been fixed
