### ISSUE TITLE
Could not find :sdk-debug when make android-debug for lantern

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#3858]
Could not find :sdk-debug when make android-debug for lantern

Details as follow:

# make android-debug

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find :sdk-debug:.
     Searched in the following locations:
         https://jcenter.bintray.com//sdk-debug//sdk-debug-.pom
         https://jcenter.bintray.com//sdk-debug//sdk-debug-.aar
         file:/home/yuan/lantern/src/github.com/getlantern/lantern-mobile/app/libs/sdk-debug-.aar
         file:/home/yuan/lantern/src/github.com/getlantern/lantern-mobile/app/libs/sdk-debug.aar
         https://repo1.maven.org/maven2//sdk-debug//sdk-debug-.pom
         https://repo1.maven.org/maven2//sdk-debug//sdk-debug-.aar
         file:/root/.m2/repository//sdk-debug//sdk-debug-.pom
         file:/root/.m2/repository//sdk-debug//sdk-debug-.aar
         https://maven.fabric.io/public//sdk-debug//sdk-debug-.pom
         https://maven.fabric.io/public//sdk-debug//sdk-debug-.aar
         file:/home/yuan/Android/Sdk/extras/android/m2repository//sdk-debug//sdk-debug-.pom
         file:/home/yuan/Android/Sdk/extras/android/m2repository//sdk-debug//sdk-debug-.aar
         file:/home/yuan/Android/Sdk/extras/google/m2repository//sdk-debug//sdk-debug-.pom
         file:/home/yuan/Android/Sdk/extras/google/m2repository//sdk-debug//sdk-debug-.aar
     Required by:
         lantern-mobile:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.328 secs
Makefile:578: recipe for target 'src/github.com/getlantern/lantern-mobile/app/build/outputs/apk/lantern-debug.apk' failed
make: *** [src/github.com/getlantern/lantern-mobile/app/build/outputs/apk/lantern-debug.apk] Error 1

Pls advise how to fix it,thx!

**Comment by atavism** [comment]
Hey @yuan78, thanks! This should be resolved now https://github.com/getlantern/lantern/pull/3894
