### ISSUE TITLE
lookup localhost: no such host

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3859]
Reported by user.

> Mar 23 06:30:57.769 - 0m1s ERROR flashlight: flashlight.go:129 Error starting client proxy: Unable to listen: "listen tcp: lookup localhost: no such host"

We can simply default proxy address to `127.0.0.1:8787` to avoid it.

**Comment by 2767321434** [comment]
or Open the program with ”lantern.exe -addr=x.x.x.x:dddd"

**Comment by fffw** [comment]
Yeah @2767321434 that can also resolve it but requires user to supply extra flag.

**Comment by 2767321434** [comment]
try add "addr: 127.0.0.1:8787" to  file "lantern-2.1.1.yaml", i have not try it. just guess it will work.because it worked on old version.
please forgive me poor english.

**Comment by myleshorton** [comment]
Yeah I don't see the point in ever using "localhost" instead of "127.0.0.1" for this reason @fffw. Tiny fix - I'll look at it.
