### ISSUE TITLE
doesn't work on Ubuntu 14.04 

### ISSUE THREAD

**Issue by junneyang** [getlantern/lantern#3861]
1. LOG:    
Mar 24 09:47:56.495 - 0m8s DEBUG chained: dialer.go:51 Sending CONNECT REQUEST
Mar 24 09:47:56.771 - 0m8s DEBUG balancer: balancer.go:106 Successfully dialed via (trusted) chained proxy at 188.166.228.26:443 to connect://logs-01.loggly.com:443 on pass 0
Mar 24 09:47:56.771 - 0m8s DEBUG flashlight.client: handler.go:160 Responding OK to //logs-01.loggly.com:443
Mar 24 09:47:56.771 - 0m8s DEBUG flashlight.client: handler.go:173 Responding 200 to //logs-01.loggly.com:443
Mar 24 09:47:59.947 - 0m12s DEBUG fronted: direct.go:279 Successfully passed HEAD request through: &{stage-www.lifelock.com 54.182.3.117}
Mar 24 09:47:59.947 - 0m12s DEBUG fronted: direct.go:200 Wrapping connecting in idletiming connection
Mar 24 09:47:59.947 - 0m12s DEBUG fronted: direct.go:207 Returning connection

2. screentshot:    
![qq 20160324174910](https://cloud.githubusercontent.com/assets/6802322/14013691/c6ff8a38-f1e8-11e5-8875-1675639faf94.png)    
![qq 20160324175045](https://cloud.githubusercontent.com/assets/6802322/14013722/faf7bedc-f1e8-11e5-9773-70bf17ab3c85.png)

3. startup log:    
[log.txt](https://github.com/getlantern/lantern/files/187559/log.txt)

thanks !

**Comment by aranhoide** [comment]
@junneyang : for one thing, Lantern is not supposed to proxy `ping`; it's purely a HTTP proxy.  Your logs suggest Lantern is successfully proxying to our logging infrastructure at least.  So I'll assume this is a misunderstanding and close this issue for now.

Have you tried browsing to Google?  What problem are you experiencing exactly?

Also, how did you install Lantern?  It seems to be installed to the `root` user.  Do you intend to run it as `root`?

Please reopen if I'm misunderstanding your problem.  If you do so, please email your Lantern logs (not the installing ones), as explained in:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs
