### ISSUE TITLE
Lantern UI doesn't show on Win 10 if Xunlei is installed

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3862]
The page spins forever for "Waiting for Lantern..."

On Chrome, lots of below errors:
> WebSocket connection to 'ws://ui.lantern.io/data' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

Edge uses CONNECT method to proxy WebSocket, and keeps showing "pending" state.
![image](https://cloud.githubusercontent.com/assets/10410437/14015625/59ef2900-f1f5-11e5-80b8-3fc03c1abe74.png)

**Comment by fffw** [comment]
Could reproduce on either 2.1.0 or 2.1.1

**Comment by fffw** [comment]
Okay Chrome also use CONNECT for Websocket.

```
t=32879 [st=    1]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                          --> CONNECT ui.lantern.io:80 HTTP/1.1
                              Host: ui.lantern.io:80
                              Proxy-Connection: keep-alive
                              User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
```

That means:

1. We don't need to explicitly allow `ws(s)` scheme in anywhere else other than PAC file.
2. We didn't rewrite correctly for CONNECT requests to ui.lantern.io.

```
Mar 24 11:54:24.854 - 0m53s TRACE flashlight.client: handler.go:29 Intercepting CONNECT //ui.lantern.io:80
Mar 24 11:54:24.855 - 0m53s TRACE flashlight.client: handler.go:103 Proxying CONNECT request for ui.lantern.io:80
Mar 24 11:54:24.855 - 0m53s TRACE flashlight.client: client.go:210 Rewriting ui.lantern.io:80 to 127.0.0.1:16823
Mar 24 11:54:24.856 - 0m53s DEBUG flashlight.client: handler.go:160 Responding OK to //ui.lantern.io:80
Mar 24 11:54:24.856 - 0m53s DEBUG flashlight.client: handler.go:173 Responding 200 to //ui.lantern.io:80
Mar 24 11:54:27.961 - 0m57s TRACE flashlight.client: handler.go:149 Error piping data from client to proxy: read tcp 127.0.0.1:51947->127.0.0.1:16823: read tcp 127.0.0.1:8787->127.0.0.1:51946: wsarecv: An existing connection was forcibly closed by the remote host.
Mar 24 11:54:27.961 - 0m57s TRACE flashlight.client: handler.go:156 Error piping data from proxy to client: read tcp 127.0.0.1:8787->127.0.0.1:51946: read tcp 127.0.0.1:51947->127.0.0.1:16823: use of closed network connection
```

**Comment by fffw** [comment]
Okay it only occurs if Xunlei is installed. That means Xunlei only has something to do with CONNECT requests.

**Comment by shilingluo** [comment]
11年3月24日：54：24.854  -  0m53s TRACE flashlight.client：handler.go：29拦截CONNECT //ui.lantern.io:80
11年3月24日：54：24.855  -  0m53s TRACE flashlight.client：handler.go：为ui.lantern.io:80 103代理功能连接的请求
11年3月24日：54：24.855  -  0m53s TRACE flashlight.client：client.go：210重写ui.lantern.io:80到127.0.0.1:16823
11年3月24日：54：24.856  -  0m53s DEBUG flashlight.client：handler.go：160回应确定//ui.lantern.io:80
11年3月24日：54：24.856  -  0m53s DEBUG flashlight.client：handler.go：173回应200 //ui.lantern.io:80
11年3月24日：54：27.961  -  0m57s TRACE flashlight.client：handler.go：从客户机到代理149错误管道数据：读TCP 127.0.0.1:51947->127.0.0.1:16823：阅读TCP 127.0.0.1:8787- > 127.0.0.1:51946：的WSARecv：一个现有的连接被强行关闭远程主机。
11年3月24日：54：27.961  -  0m57s TRACE flashlight.client：handler.go：从代理到客户端的156错误管道数据：读TCP 127.0.0.1:8787->127.0.0.1:51946：阅读TCP 127.0.0.1:51947- > 127.0.0.1:16823：采用封闭式网络连接

**Comment by xiam** [comment]
Does this still happen with latest QA? Could not produce with latest QA + Xunlei 7.9.
