### ISSUE TITLE
How to install lantern on server?

### ISSUE THREAD

**Issue by RoJoHub** [getlantern/lantern#3870]
I have a ECS Server.So i want to install lantern on server.
Now, i alerdy connect to my server by PPTP.
If server is run lantern,my any device can connect to my server to "FangQiang(chinese)".
Is it true?
If it work,How to install lantern on server?
 I'm novice~
Thanks for help!

my server：
CPU： 1核
memory ： 1024 MB
OS： Aliyun Linux 15.1 64位

**Comment by RoJoHub** [comment]
I know that

**
Building Lantern

Prerequisites

Git - brew install git, apt-get install git, etc
Go 1.6 or higher.
GNU Make
To build and run Lantern desktop, just do:

git clone https://github.com/getlantern/lantern.git
cd lantern
make lantern
./lantern**


when i Run "make lantern" ,my server show that
 "/bin/bash: line 8: npm: command not found
make: *** [src/github.com/getlantern/flashlight/ui/resources.go] Error 127
"

**Comment by fliar** [comment]
check this: https://github.com/getlantern/lantern/issues/3842
i've issued a pull request, but it's not merged

**Comment by RoJoHub** [comment]
@fliar  thank u very much！

**Comment by aranhoide** [comment]
@fliar's PR is merged now.
