### ISSUE TITLE
Lantern not working in China ZheJiang

### ISSUE THREAD

**Issue by Page-David** [getlantern/lantern#3872]
I used lantern for a long time. Weeks ago, when Lantern use Japan server to proxy my internet, all is well. However, now Lantern seems use Singapore server, I can not go across GFW anymore.

So can I switch the server from Singapore to Japan, or any other good method?
Here are some part of logs:

[logs removed by aranhoide]

**Comment by aranhoide** [comment]
Please don't paste logs in github issues.  Email them to us as explained here

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

Feel free to email yours directly to aranhoide@getlantern.org.

I see nothing wrong with the server that was assigned to you, but I've retired it anyway.  Please reopen if the new one doesn't work either.
