### ISSUE TITLE
error running pac-cmd.exe in windows：Unable to set lantern as system proxy.

### ISSUE THREAD

**Issue by adamlzy** [getlantern/lantern#3883]
In lanter version 2.0.1 and 2.1.1. It seems the argument that  passed to  “getlantern/pac/pac.go” 's function  func run(cmd *exec.Cmd)  is wrong.  I guess it is the pacUrl. Any answer is appreciated!

0m0s DEBUG flashlight: pac.go:146 Serving PAC file at http://127.0.0.1:16823/proxy_on.pac
Mar 28 03:04:46.393 - 0m0s ERROR flashlight: pac.go:163 Unable to set lantern as system proxy: Unable to execute C:\Users\yanluwei\AppData\Roaming\byteexec\pac-cmd.exe: open NUL: The system cannot find the file specified.
[lanterne.txt](https://github.com/getlantern/lantern/files/192742/lanterne.txt)

**Comment by myleshorton** [comment]
Duplicate
