### ISSUE TITLE
what't time we can see the ios version lantern

### ISSUE THREAD

**Issue by jackiezero** [getlantern/lantern#3886]
lantern mac version is used very fine ,we are expect ios version can released in recently

**Comment by atavism** [comment]
@jackiezero, we're planning to start work on it in the coming months. It'll likely be finished in the fall, towards the end of the year.

**Comment by xckevin** [comment]
good job

**Comment by code-artisan** [comment]
Good job, I'm waiting for iOS version. 😄

**Comment by iTofu** [comment]
Waitting ~

**Comment by KevinGong2013** [comment]
Can I contribute somehow ?
