### ISSUE TITLE
Can not open any website

### ISSUE THREAD

**Issue by Ailix** [getlantern/lantern#3893]
I just can't open any wensite after I quit lantern
```
MacOS 10.10.5
```

**Comment by fffw** [comment]
Please confirm following AFAICR:

1. Lantern is not hanging (should rarely happen, just in case). In Activity Monitor, make sure there's no process named "Lantern".

2. Proxy settings is cleared.
> System Settings -> Network -> Advanced -> Proxies

3. Try another browser.

**Comment by Ailix** [comment]
Neither Chrome nor Safari can open，，，
![snip20160331_1](https://cloud.githubusercontent.com/assets/6638398/14165912/df0af4f2-f740-11e5-8b14-0d008e6907ca.png)
![snip20160331_2](https://cloud.githubusercontent.com/assets/6638398/14165928/0914d998-f741-11e5-9990-dc684d619944.png)
![snip20160331_7](https://cloud.githubusercontent.com/assets/6638398/14165930/0f804e0c-f741-11e5-9fc9-92fbffa39ab0.png)

**Comment by fffw** [comment]
![image](https://cloud.githubusercontent.com/assets/10410437/14165947/4f8a1352-f741-11e5-8070-3bb1efd972da.png)

**Comment by Ailix** [comment]
got it , thx
