### ISSUE TITLE
Sending SMS gives "bad input"

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3895]
Just entering my phone number in both Chrome and Safari results in "bad input" displaying in the browser.

**Comment by myleshorton** [comment]
Not sure if this is the result of the server upgrade @uaalto or what. You getting this too @xiam? Running from pro repo

**Comment by uaalto** [comment]
It's probable that is part of the server, and it hasn't been caught by the integration tests in pro-server's go client.
I can't think of a reason at the moment, because I fixed already the similar issue caused by migrating to Aleph. I'll try to reproduce it.

**Comment by uaalto** [comment]
I've tested the endpoint manually and, given all required parameters, it will reply Ok.
These are the parameters:
* telephone
And HTTP header fields:
* X-Lantern-Device-Id
* X-Lantern-User-Id
* X-Lantern-Pro-Token

**Comment by myleshorton** [comment]
So it looks like it's actually responding with 200 OK but with a body of `{"status":"error","error":"bad_input"}`. It's possible the 200 OK is from the local Lantern client and not from the server, however. It would be useful to have a more detailed error message, even with a code if we're worried about revealing something. This should also be very reproducible from the client.

**Comment by uaalto** [comment]
That's the server's response to any of those listed fields missing, it is not used in any other case. There are many more errors, but in this case, it reports just that a field is missing. It doesn't provide more information to avoid mentioning the exact one, which is the only extra piece of data I think that could be useful. But given that the required input parameters/headers is documented, the client knows that it has to provide all, which I think is more practical than setting up a particular scheme that we will have to maintain in both client and server. What do you think?

**Comment by myleshorton** [comment]
Yeah I just think we've run into this exact same sequence way too much TBH @uaalto . There are a few approaches to solving that:

1. More detailed error messages so the client knows what's going on (is there really any useful information we reveal in those responses?)
1. Stepping out of silos a little bit and running both the client and the server
1. Using some better RPC system that makes these all non-issues

TBH my vote is all of the above, as in:

1. Return useful error messages from the server to make client-side debugging easier
1. Actually testing the client and the server live when making changes (yes, in theory automated tests should catch these, but they simply have not successfully done so. I've personally caught these issues probably 5 times just randomly running the client every once in awhile)
1. Using a framework that makes issues like this basically impossible -- in particular I honestly think we should be using http://www.grpc.io/ for all this stuff, including the automatically generated HTTP APIs if we really want to use HTTP for specific cases. That way you'd really have to go out of your way to get the client and the server out of sync because it's all generated code running on both the client and the server.

Perhaps most importantly, though, we should all be really running this stuff end to end -- it's the only way we know changes will work. Otherwise it really slows things up because things randomly break and hold up progress on one end or the other.

**Comment by uaalto** [comment]
I'll be happy to port it to GRPC if you consider it an improvement. It may actually help if it forces on an agreement client/server stronger than just following documentation.
My point regarding errors is that in this particular case, revealing more information is a security concern, as in many other endpoints. The errors describe the problem, but not the details. Of course, I can provide more information, the reasons for the current status are that we had more urgent matters and these security concerns.
I agree on testing it more end to end. On my side I've been doing, but certainly not immediately and thoroughly, which I will do from now on.

**Comment by myleshorton** [comment]
Is it really a security concern though @uaalto? Like `X-Lantern-Device-ID required` or something?

TBH I think #1 is actually the least important of those 3, so I'm not super worried about that one. I really mostly do think we should be using grpc for as much as we possibly can -- I think it's just awesome and would help us a lot moving forward. One of the biggest wins is that you can automatically generate an HTTP API in addition to docs as well as client and server side stubs in multiple languages. Perhaps more importantly, though, it allows us to just skip HTTP whenever we can and do things much more efficiently with protocol buffers. Check these out:

https://coreos.com/blog/gRPC-protobufs-swagger.html
https://www.youtube.com/watch?v=sZx3oZt7LVg

**Comment by myleshorton** [comment]
To be clear, though, I've actually been avoiding bringing this up too strongly because I don't want to distract us from the tasks at hand, but I think it's worth a good look over the medium term.

**Comment by uaalto** [comment]
I will open a ticket about this in the pro server. Definitely could improve things.
One clarification also about #1 is that those strings returned by the pro server are error codes. It was intended for the client to make them more "human readable". Now that I'll set up translations in the pro-server, we could actually provide more descriptive strings and translate them, if they are going to be used directly by the UI.

**Comment by fffw** [comment]
One alternative is to enforce JSON scheme on all parts include server parameter validation, API doc and client test. I had that in mind when I created an PR to pro server with initial api doc. It's only meaningful to open API though.

**Comment by myleshorton** [comment]
All set!
