### ISSUE TITLE
Windows 10,Ubuntu - Lantern is proxying all sites even when ProxyAllTraffic option is unchecked - All browsers

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3900]
I tried with geoiptool.com and accessing slack after blocking the sites.

**Comment by oxtoacart** [comment]
Okay, what's happening on Windows is that detour receives an error when reading from geoiptool.com directly (use of closed network connection).

cc: @fffw

**Comment by oxtoacart** [comment]
Interestingly, we don't see this issue on OS X, so it must be some subtle difference in the networking stack.

**Comment by myleshorton** [comment]
This seems like a huge issue @xiam if you want to look at it while you're in the area. @oxtoacart should I remove you as the assignee for this one and put it back in the backlog?

**Comment by oxtoacart** [comment]
@xiam - Note that there's a new detour coming - #3804.  It's not 100% ready yet, but I'm curious whether it maybe solves this problem on Windows.

**Comment by sunshine19090** [comment]
@oxtoacart I tried the scenario by unchecking proxyalltraffic option and manage system proxy checked. I still see the proxy address in geoiptool.com, I expect it to show my ip as I am not using DNS blocking. I can't think of any other way to test this functionality.

**Comment by sunshine19090** [comment]
Closing this as this now works fine in windows 10.
