### ISSUE TITLE
Windows 10 - Unable to open any pages in Edge(default browser) after restarting

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3901]
I checked all the options in settings screen and then restarted the system without quitting lantern. After the system restart, lantern started running. But when opened Edge browser, I couldn't open any sites including the lantern page (I tried "show lantern" from system tray too). Chrome and Firefox are working fine.

**Comment by fffw** [comment]
What's in the address bar? Is it http://127.0.0.1:16823? That's what I saw on my Win 10 VM with Edge 20.10240.16384.0 with all Lantern options checked. It should open http://ui.lantern.io instead in this case.

I found http://localhost:16823 also works on Edge, not sure if it's true for all Windows and Edge versions. If so, we can simply stick to http://localhost:16823 on Windows.

**Comment by fffw** [comment]
Nevermind, `localhost` works only because it's checked in `about:flags`, so we can't rely on it. What interesting is that option is checked by default (maybe only true for the [official Edge VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) I'm using?).

![image](https://cloud.githubusercontent.com/assets/10410437/14201558/4be96f9c-f825-11e5-91cf-94d44b6f2419.png)

**Comment by myleshorton** [comment]
Weird guys. I see "http://ui.lantern.io in" Edge with 2.1.2. I wonder what's up? The UI only appeared when I refreshed, however. This is a vanilla completely unmodified version of Windows 10 Enterprise N. Edge 25.10586.0.0.

Maybe older versions of Edge break for whatever reason?

![image](https://cloud.githubusercontent.com/assets/1143966/14220235/a22f5b12-f813-11e5-8a29-b740c18ccaab.png)

**Comment by myleshorton** [comment]
Oh wait sorry --- that was without any restart =). I think I know what's up -- we're not setting the registry entry to use ui.lantern.io if the default browser is Edge. This should be fairly easy to fix...

**Comment by myleshorton** [comment]
Hmnnn...scratch the above comment. On system startup we don't launch the browser of course, so there's no issue with the URL. I'm actually not experiencing this issue at all. The Lantern UI opened fine, and all sites are opening fine and are proxied. Weird.

**Comment by sunshine19090** [comment]
@myleshorton I am going to try this once again to see if I am able to reproduce. I will give an update soon.

**Comment by sunshine19090** [comment]
I am able to reproduce this each time I restart but able to access the sites once I restart my wifi. These are the steps I followed,

1. Launch lantern with Edge browser being default browser.
2. In settings screen, check the options Run lantern on system startup and manage system proxy.
3. Now restart the system without quitting lantern.
4. After system restarts, open the edge browser directly and try to access a site. The site cannot be accessed.

Microsoft Edge browser 25.10586.0.0

**Comment by myleshorton** [comment]
Weird. I'm following those exact same steps @sunshine19090. What version of Windows 10 are you using?

**Comment by fffw** [comment]
@sunshine19090 Did you wait for one minute or so and try again? Edge failed to open any pages but work normally afterwards without any manual intervention.

Please ignore my previous comments. That was because Lantern couldn't persist settings on my VM. I'll look at it closely and create issue if required.

**Comment by sunshine19090** [comment]
@fffw I didn't wait for a minute but I tried refreshing the page, quit and reopen the browser. However, after refreshing my wifi connection, it started working. Hope it helps.

**Comment by sunshine19090** [comment]
Unable to reproduce. so closing for now. I will reopen if I able to reproduce.
