### ISSUE TITLE
Windows 7 - When Proxy all traffic option is unchecked, lantern stops proxying 

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3902]
I couldn't even open gmail.

**Comment by myleshorton** [comment]
What browser @sunshine19090?

**Comment by sunshine19090** [comment]
@myleshorton I tried in all the browsers. Oh, I forgot to mention that I had manage system proxy checked.  So the settings to reproduce would be manage system proxy is checked but proxy all traffic option is unchecked.  

Regards,
Sunshine

**Comment by oxtoacart** [comment]
I am unable to reproduce.  I have Windows 7 with IE 10 and Chrome, running in VirtualBox.

**Comment by sunshine19090** [comment]
@oxtoacart I am able to reproduce it. I used DNS blocking and then started lantern. Unchecked Proxy All traffic and checked Manage System Proxy. After changing the settings, I couldn't open any sites even the ones which doesn't need proxy. When Proxy all traffic is checked, I am able to open all the sites.

**Comment by oxtoacart** [comment]
@sunshine19090 What browser?

**Comment by oxtoacart** [comment]
Weird, I just tried those exact steps running from devel, and still can't reproduce.  I wonder if something changed on devel that fixed this since the build that you're testing @sunshine19090.

Can you try deleting your log file, running the test again and sending me your log file?

**Comment by sunshine19090** [comment]
okay @oxtoacart.

**Comment by myleshorton** [comment]
Also @oxtoacart the build @sunshine19090 is running with is available at https://s3.amazonaws.com/lantern/lantern-installer-qa.exe or https://s3.amazonaws.com/lantern/lantern-installer-qa.dmg

**Comment by oxtoacart** [comment]
I just tried to reproduce with the QA build, but I still can't reproduce (btw. I'm using Chrome).

**Comment by oxtoacart** [comment]
@sunshine19090 Looking at the log that you sent me, I don't see any errors.  I also see a lot of successful proxying activity, for example:

```
Apr 11 20:45:37.784 - 0m55s DEBUG balancer: balancer.go:95 Successfully dialed via (trusted) chained proxy at 104.236.192.114:443 to tcp://whatismyipaddress.com:80 on pass 0
```

**Comment by oxtoacart** [comment]
This looks like another detour issue.  When Proxy All is disabled, but our fake DNS blocking is enabled, adds all the sites that we try to the bypassdomains list (even whatismyipaddress, which is in the default whitelist).
