### ISSUE TITLE
[Desktop] If payment fails during checkout, display a clear message to the user

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3905]
If stripe accepts the user's payment details, but then our /purchase endpoint fails, we don't currently display an error message to the user.  We need to display an error and at least let the user go back through the payment process.

**Comment by oxtoacart** [comment]
If this was intended for auto-renewal, let's not worry about it now.

**Comment by xiam** [comment]
I think we should have a generic way to display important error messages that need to be read and dismissed, something like this:
 
![disk-not-ejected-properly-mac](https://cloud.githubusercontent.com/assets/385670/15292482/e1e4ca50-1b48-11e6-8ebf-4d764c8881fc.jpg)

This message can appear anytime, AFAIK the actual payment verification process is asynchronous, right @uaalto?

cc @Derekf5

**Comment by uaalto** [comment]
Not anymore, with the blocking convention for the /purchase endpoint.

**Comment by Derekf5** [comment]
@xiam this is a good idea cc'ing @carsonefv since she is the primary owner for desktop.

**Comment by Derekf5** [comment]
@xiam do those types of notifications appear in a similar way on Windows?

**Comment by xiam** [comment]
> @xiam do those types of notifications appear in a similar way on Windows?

Definitely not, I was thinking more on doing something like that but inside the Lantern UI, which we can control and shape to our needs.

**Comment by Derekf5** [comment]
thanks @xiam, that sounds good to me.

**Comment by oxtoacart** [comment]
So to be clear, these types of notifications don't apply here because we'll actually know if the payment failed before leaving the modal, right?

On the notifications, material design, one way to do non-interrupting error notifications is with [snackbars](http://www.material-ui.com/#/components/snackbar).

**Comment by carsonefv** [comment]
@xiam @derekF5 to confirm, this will be a small notification in the UI that
is different from the existing payment error pop-up screen (see updated
spec sheet)? What other notifications will we be using in this format?

-c

**Comment by xiam** [comment]
![screen shot 2016-05-16 at 4 47 09 pm](https://cloud.githubusercontent.com/assets/385670/15304950/de831924-1b85-11e6-8701-1a446e94066a.png)

**Comment by myleshorton** [comment]
Let's just do the snackbar version of this for now.

**Comment by xiam** [comment]
Hey @uaalto, do we have any convention to force/simulate a failure on the `/purchase` endpoint?

Some card numbers trigger errors on stripe's side but those are already handled by the widget (and this is before sending data to `/purchase`):

![screen shot 2016-05-18 at 11 07 11 pm](https://cloud.githubusercontent.com/assets/385670/15382192/4fd86a0c-1d4d-11e6-88ea-bdad6e8c7190.png)

**Comment by uaalto** [comment]
Currently no @xiam, the endpoint will send an error primarily caused by errors in Strip (which are rare enough to encounter I suspect). What would you need?

**Comment by xiam** [comment]
I was thinking on an optional parameter for `/purchase`, the situation I want to simulate is Stripe letting me pass and the API telling me the payment actual failed. Can we accept such parameter?

**Comment by uaalto** [comment]
We could add a parameter like that, and make it available only in staging so it isn't even recognized in production.
Once we do this, we are introducing a fake behavior, and I we can do whatever fits best your needs that doesn't introduce too much noise in the codebase. I think is legit in staging, so, can you give me the exact combinations of parameters and the expected error response so I add it?

**Comment by xiam** [comment]
Perhaps `simulate_error=int`, where int can be an integer, let's say `1` for now, and the error would be a payment that was declined in the exact same format that the API would return when Stripe returns a payment failure. Thanks!

**Comment by uaalto** [comment]
You can try if the solution I pushed is what you are looking for now. The new parameter is `simulateError`, and the value for payment failure `payment-error`. Does that sound good?

`simulateError=payment-error`

I changed to camelCase because is the convention used for the rest in the Pro server. About the error code I thought a string would be more descriptive than a number. Can be changed if you have any other preference.

**Comment by uaalto** [comment]
I'll document this as soon as you give me feedback.

**Comment by xiam** [comment]
This will do! thanks.
