### ISSUE TITLE
when the lantern can run on iphon 4s、iphone 6s、ipad mini and so on? 

### ISSUE THREAD

**Issue by wuxiangege** [getlantern/lantern#3907]
a few days ago, I look for a vpn software on the internet. I find that lantern can run on the android device,pc device and linux system.But I don't find a version who can run on ios system.Could you answer my question?

**Comment by Rice321** [comment]
Hi @wuxiangege, sorry we don't have Lantern for iOS now, but our team will work on it soon! 
Thanks!
