### ISSUE TITLE
Cannot install Lantern on Kali Linux

### ISSUE THREAD

**Issue by Page-David** [getlantern/lantern#3911]
I am trying to install lantern on Kali Linux, after I installed lantern by:
`dpkg -i lantern*.deb`
I typed `lantern`, but I got:

> error while loading shared libraries:libappindicator3.so.1: cannot open shared object file: No such file or directory

Did I miss anything?

**Comment by BlackZ** [comment]
take “apt-get install libappindicator3-1”

**Comment by hitzhangjie** [comment]
Agree with BlackZ's suggestion.

**Comment by Page-David** [comment]
@BlackZ It is,thank you.

**Comment by BlackZ** [comment]
@Page-David buyongxie
