### ISSUE TITLE
As a primary programming learner, could anyone tell how to read the core source code of Lantern?

### ISSUE THREAD

**Issue by eric-meng** [getlantern/lantern#3912]
There are too many directories in the master branch and I don't know where to begin....

That is really a noob question.

I want to make a private edition lantern on mac or windows but not android or iOS etc,

so could anyone tell me which source files I should read?

**Comment by aranhoide** [comment]
Sorry, the issue system is meant to report problems with Lantern or to request features.  Please post this question in the developer mailing list:

https://groups.google.com/forum/#!forum/lantern-devel
