### ISSUE TITLE
How to install lantern in centos?

### ISSUE THREAD

**Issue by wodog** [getlantern/lantern#3913]
How to install lantern in centos?

**Comment by hitzhangjie** [comment]
You can download a *.deb package, then use 'alien' to convert *.deb to *.rpm, then use 'rpmrebuild' to edit the scripts within it.
After that, you can install it as a normal rpm package.

**Comment by iliul** [comment]
@hitzhangjie Good idea . 

Install lantern from source @wodog :
> [https://github.com/getlantern/lantern#building-lantern](https://github.com/getlantern/lantern#building-lantern)

**Comment by aranhoide** [comment]
Thanks for your help!  Currently only Ubuntu is officially supported.  Hopefully @hitzhangjie's and @iliul's suggestions have been of help.  If you intend to build Lantern on a server, you may want to pay special attention to this part too:

https://github.com/getlantern/lantern#building-lantern-for-running-on-a-server
