### ISSUE TITLE
No dialer left to try on pass 0

### ISSUE THREAD

**Issue by tongche** [getlantern/lantern#3915]
I am using lantern. Today it seems to have been blocked. For some sites like facebook, the connection cannot be established.  For other sites like Boxun.com, detour.go reports no dialer left to try on pass 0. 

I am currently in China.

Apr 05 17:57:43.735 - 6m15s DEBUG flashlight.config: fetcher.go:156 Fetched cloud config
Apr 05 17:57:44.136 - 6m16s DEBUG detour: detour.go:140 Dial initially to www.googleapis.com:443 failed, try detour: dial tcp 216.58.221.234:443: i/o timeout
Apr 05 17:57:44.137 - 6m16s ERROR detour: detour.go:146 Dial detoured failed: No dialers left to try on pass 0
Apr 05 17:57:44.137 - 6m16s DEBUG flashlight.logging: logging.go:232 Not logging duplicate: ERROR detour: detour.go:146 Dial detoured failed: No dialers left to try on pass 0

**Comment by fffw** [comment]
@tongche Could you send the full log to me at fffw@getlantern.org?

**Comment by medz** [comment]
@fffw 遇到了相同问题~貌似在中国已经大面积瘫痪了~

**Comment by bigtan** [comment]
上海电信家庭宽带，完全无法使用。

**Comment by tongche** [comment]
@fffw  I have sent. This problem has been reported by many users in China.

**Comment by kimiho** [comment]
me too

**Comment by fffw** [comment]
@tongche Could you also send ~/Library/Application Support/Lantern/lantern-9999.99.99.yaml to me?

**Comment by medz** [comment]
@tongche 我的操作系统版本是：
Windows 10 Home Insider Preview Build 14295.RS1版本~
Lantern版本是 2.11
额~github貌似传不了文件，可能是因为没翻墙的原因~我邮件吧log发给你吧~

**Comment by medz** [comment]
@fffw LOG上传了~

**Comment by sigongli** [comment]
Yes, I have also encountered this problem.

**Comment by 475555354** [comment]
the same problem, it works well yesterday. location: China.

**Comment by hitzhangjie** [comment]
fuck GFW, fuck!

**Comment by aranhoide** [comment]
Although the fix for this was committed two hours ago, it took until now to fix all existing servers.  This shouldn't be happening anymore.

**Comment by fffw** [comment]
@tongche @medz If you can check if Lantern works for you again in your convenient time, that would be appreciated. Other guys, Lantern probably will also work again for you.

**Comment by medz** [comment]
@fffw Think you.
Lantern 我在大多中国区域对客户端进行了代理测试，可以的使用，但是速度是比较慢的。但是有时候能打开google，有时候又打不开~最根本的原因还是没有找到可连接的地址。

**Comment by medz** [comment]
@fffw 出现了持续性的不可用和间歇性的可用状态~可能和地区和宽带运营商有关。最主要的是GFW有关。

**Comment by fffw** [comment]
@medz What we just fixed is specific to the `No dialer left to try on pass 0` error. If any of the tests still get that error in Lantern log even after running for several minutes, please send your log directly to me at fffw@getlantern.log to check.

**Comment by medz** [comment]
@fffw 好的~我明天开始给你发送log~

**Comment by fffw** [comment]
@medz Thanks!

**Comment by fffw** [comment]
This issue should be actually fixed just now.
