### ISSUE TITLE
lantern在60.19.*.* ip段下无法使用

### ISSUE THREAD

**Issue by OnionSalt** [getlantern/lantern#3920]
我用的是联通网，大概是4月5号左右开始，如果我的ip在60.19.*.*段，lantern就无法使用，连不上任何网站。

If my is 60.19.*.*, I cant connect anywhere with lantern, this problem started around April 5

Using lantern 2.1.1

**Comment by Tveek** [comment]
my  ip is 113.116.200.228,which can not  also connect any website.

**Comment by fffw** [comment]
We fixed just now an issue which affected a few newly launched servers. https://github.com/getlantern/lantern/issues/3915

@OnionSalt @Tveek You may try again and keep Lantern up for a few minutes to see if it works again for you.

**Comment by Tveek** [comment]
@fffw  great work

**Comment by kimiho** [comment]
@Tveek 你能用了？我这边还是不行。

**Comment by Tveek** [comment]
@kimiho  一切如初，我用的是Ubuntu14.04，卸载一些，再安装看看。或者你先有一下google hosts吧，[](http://laod.cn/hosts/2016-google-hosts.html)

**Comment by Tveek** [comment]
@fffw [](url)http://laod.cn/hosts/2016-google-hosts.html

**Comment by OnionSalt** [comment]
60.19.*.* is working again, ty so much!

**Comment by louy2** [comment]
If it is working could you please close the issue?

**Comment by aranhoide** [comment]
Please reopen if problem persists/reappears.
