### ISSUE TITLE
Windwows 10-Windows edge can't get access to any sites after quitting lantern

### ISSUE THREAD

**Issue by spartan116x** [getlantern/lantern#3922]
My edge just can't get access to any sites after quitting lantern while everything goes well with chrome(default explorer). I have to delete all the setting on HKEY_CURRENT_USERS\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections to make my edge work. And after restarting lantern, the problem just goes back. I have tried to change my proxy setting of the system and IE but none of them worked...
platform：
Lantern 2.1.1
Windows 10.0.10586
Windows edge 25.10586.00

**Comment by seLc7** [comment]
Maybe you can just shut down the net proxy button, in the net-configure, choose proxy in the left side

**Comment by hitzhangjie** [comment]
Maybe lantern changes Edge's proxy configuration. At least, it changes IE's proxy configuration. You can reset the proxy configuration manually.

**Comment by myleshorton** [comment]
We'll look closer at this @spartan116x

**Comment by xiam** [comment]
Thanks for your report @spartan116x, we found the problem and a solution for this is coming soon.

**Comment by xiam** [comment]
Hey @sunshine19090, this should be fixed as well in our latest QA. Can you confirm?
