### ISSUE TITLE
Desktop - Get Free Pro Credits button doesn't do anything

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3926]
I'm running the Alpha5 desktop build and the Get Free Pro Credits link doesn't do anything other than animate to show that it was clicked.

**Comment by xiam** [comment]
Here we want to open a dialog for entering a referral code and instructions on how the referral model works. Is this still accurate, @Derekf5?

**Comment by Derekf5** [comment]
@xiam @oxtoacart the get free pro credit link should go to the "free pro credits" pop up that displays a users referral code that they can then share with friends.    A user can only enter a friends referral code at checkout.    @carsonefv should have this popup design updated at some point today.

**Comment by carsonefv** [comment]
@xiam this "free pro credits" pop-up screen is now in the updated spec
sheet at the end of the document
