### ISSUE TITLE
Desktop - Account Verification - No option for "already have code"

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3928]
If I started the flow earlier, got interrupted and had to come back for some reason, I have to request a new code.  This is not a huge deal, but could be a minor annoyance if I don't happen to be able to get SMS's right at that moment.  It also causes us to potentially send more SMS's than we need, which isn't free (albeit quite cheap).

**Comment by sunshine19090** [comment]
NA anymore
