### ISSUE TITLE
Desktop - Enter Promo Code - Can I enter this code later?

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3929]
I believe that the answer is no, but there's no explanation in the UI.

![screen shot 2016-04-08 at 1 51 15 pm](https://cloud.githubusercontent.com/assets/5000654/14394264/0993eb10-fd91-11e5-855d-e5571a6402dd.png)

**Comment by myleshorton** [comment]
Yeah you can't enter it later. You want an explanation about whether or not you'll be able to enter one later @oxtoacart? What do you think @Derekf5?

**Comment by Derekf5** [comment]
Hmm, im not sure we need to explain that you cant enter it later @oxtoacart @myleshorton .  Most of the time Promo codes are one time use at checkout.  If they missed signing up with a code and still want some free time, they can always start inviting friends.

**Comment by oxtoacart** [comment]
Sorry for the slow reply.  I agree that it's quite standard to have referral codes that only apply at checkout.  I think the reason the question popped to mind in this case is because for the annual plan, I can and will probably check out again (in a year).  Will I be prompted for a promo code again at that point?  And could I use the one that I failed to use the first time around?

To take Dell as an example, if I buy a laptop and neglect to enter a promo code at that time, I can't retroactively request the credit.  However if I buy another laptop, I can use the promo code then.  Now, if I buy a third laptop, I may or may not be able to use the promo code depending on whether there's a per-person limit or something like that.

So, is renewing an annual plan like buying that 2nd or 3rd laptop?

**Comment by sunshine19090** [comment]
@oxtoacart @Derekf5 While I tried renewing the pro account, I saw that we are providing the user to enter the promo code. 

Is this okay or should we discuss this more?

**Comment by oxtoacart** [comment]
I also noticed that after renewing, we show the "welcome to pro" screen again.  Also interestingly, if I renew with a different email address, my account email address changes to the new email address.  That's pretty slick!  It seems like we're basically going through the same exact process as for the initial purchase?

**Comment by Derekf5** [comment]
@sunshine19090 im not sure if we want to provide users with that promotion when they are renewing, what do you think @myleshorton?

**Comment by Derekf5** [comment]
@oxtoacart yes basically the same process, i do think we should cut that welcome to pro screen, similar to how i think it should be cut here #4759 and just serve the user a snackbar after renewal saying it succeeded, i will ticket that change separately.
