### ISSUE TITLE
Desktop - Toggling Lantern is On/Off doesn't seem to do anything

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3931]
The toggle at the bottom right of the UI changes the text, but Lantern keeps proxying my traffic and when I look at the Lantern Preferences, it still shows "Manage System Proxy" as on even though the ui says "Lantern is OFF".

**Comment by xiam** [comment]
f I try to see things from the user's perspective, turning Lantern on/off does not have anything to do with marking it as system proxy, even though that's the easiest solution from our side. This currently works (on Pro) by altering the PAC file and letting everything pass when Lantern is off, and using the regular PAC file when it is on. No permanent system preferences are changed.

**Comment by oxtoacart** [comment]
@xiam Thanks for explaining what it's supposed to do.  From what I recall when I was testing this, it was actually still proxying my traffic even though I turned it off, so maybe there's a bug in the implementation?

When I see things from the user's perspective, we now have several similar-sounding settings across two different parts of the UI that all do slightly different things.

- Turn Lantern On/Off adjusts the PAC file as you said
- Manage System Proxy controls whether or not Lantern is even managing the system proxy
- Toggle Proxy All makes Lantern either proxy all or detour, and also affects the PAC file
- I can also quit Lantern via the system tray menu

If I'm using a proxy switching extension, things get even more weird.

In addition to being confusing to me the user, this also creates potentially weird/buggy states.  What happens in these sequences?

- Turn Lantern Off -> Enable Proxy All -> will Lantern proxy or not?
- Turn Lantern On -> Disable Manage System Proxy -> will lantern proxy or not?
- Turn Lantern Off -> Stop Lantern -> Start Lantern -> is Lantern still "off" even though I just turned it on?
- Point my proxy switcher at Lantern's IP address -> Turn Lantern Off -> is Lantern still proxying?

We could think of more weird states, these are just examples.

What was original the reason for adding this toggle to the UI?

cc: @Derekf5

**Comment by Derekf5** [comment]
I think the original reason for adding it was that some users were complaining that lantern was slowing down access to unblocked domestic sites, but i havent seen that complaint for a while, so we could potentially eliminate that function?  What do you think @xiam @oxtoacart

**Comment by oxtoacart** [comment]
Thanks @Derekf5.  It seems to me that what we really have is a 3 way toggle:

Proxy Everything | Proxy Intelligently | Don't Proxy

The default is Proxy Intelligently, but at least at some point for some people, that didn't fit the bill and they wanted to be able to turn off proxying.

I'd also recommend that we use the language "Proxy" rather than "On/Off" because it's more precise and probably still intelligible to the user.

I'd also suggest that we get rid of the "Proxy All" and "Manage System Proxy" options from the settings modal, as these are just another less user-friendly way of expressing the same thing.

In practice, those states map to the new 3-way toggle like this:

- Proxy Intelligently -> Manage System Proxy but Don't Proxy All
- Proxy Everything -> Manage System Proxy and Proxy All
- Don't Proxy -> Don't Manage System Proxy

**Comment by Derekf5** [comment]
Hmm I agree that proxy is more precise, but I dont know how many users/potential users would know what that means.  

For example A Chinese user tells their not so computer literate friend to download lantern and when it is running they can access the blocked sites they wish to go to.  If there is a toggle with the word proxy, and not simply on/off, it would require more of an explanation from the user who recommended it to their friend.

I could be wrong about how widespread the use of that word is, but i certainly have some friends who would be confused :) 

Perhaps @percyalpha's insight is needed here.

**Comment by Derekf5** [comment]
@oxtoacart  and on the 3 way toggle, I agree that seems like a more user friendly way to allow users to proxy all without going to the settings.   I Will need to think about how this will appear in the UI though.

**Comment by myleshorton** [comment]
Yup one big question here guys is what problem we're trying to solve exactly. We've had some more tech savvy users request the option to set Lantern to not manage the system proxy, which the current setting accomplishes. Then we've occasionally had users request the option to "pause" Lantern or turn it on and off, but not as frequently in my experience.

It seems to me we should either:

1. Kill the on/off feature
1. Kill the "Manage system proxy" option

When resolving conflicts merging devel to the lantern-pro repo I also actually made on/off just turn proxying on and off, which effectively accomplishes the same thing as before and also makes it identical to the "Manage system proxy" option.

**Comment by Derekf5** [comment]
@myleshorton I would personally vote for killing on/off (as it keeps the UI simple) and leave proxy all in the settings menu.

**Comment by myleshorton** [comment]
Works for me @Derekf5

**Comment by oxtoacart** [comment]
+1 on just ditching the on/off for now.  I do think that we can do something more user friendly than our current settings menu, it just doesn't feel urgent.

**Comment by percyalpha** [comment]
Autoproxy was the most popular circumvention extension on firefox and its setting menu is 
Proxy all
Proxy blacklisted sites (Default)
Off.

**Comment by percyalpha** [comment]
We can put this 3-way selection on the homescreen or setting

**Comment by xiam** [comment]
Closing because this button was removed.
