### ISSUE TITLE
Mobile - Need whitespace below text that explains on/off button

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3932]
See screenshot.  "Click the button to access blocked sites and services" has no whitespace between it and the blue area.  This is on a Nexus 4.

![whitespace](https://cloud.githubusercontent.com/assets/5000654/14396878/c8b8de48-fd9f-11e5-8085-009bc6ac5d11.png)

**Comment by atavism** [comment]
Screen no longer exists so this is no longer applicable.
