### ISSUE TITLE
Mobile - Checkout - CCV/CVC Code field is ambiguous

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3937]
After filling out all the other info, I'm left on this field.  There's only a somewhat cryptic icon, so I have to assume that this is the CVC field, but I'm just guessing.  Having a suggested value of CCV/CVC or something like that would be helpful.

![checkout](https://cloud.githubusercontent.com/assets/5000654/14397420/e4f0809a-fda2-11e5-83bb-d013056e3ff3.png)

**Comment by atavism** [comment]
I fixed this on the ``lantern-pro-mobile`` branch
