### ISSUE TITLE
Mobile - Checkout - Wrong total displayed

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3938]
I selected a monthly plan, but I see a total of 59.88.  This could be because I've already signed up for an annual plan from desktop with the same phone number (see #3936).

![checkout](https://cloud.githubusercontent.com/assets/5000654/14397462/1678df72-fda3-11e5-93b7-0bc4fdc011ad.png)

**Comment by atavism** [comment]
We no longer have a monthly plan, and the cost for the annual plan is still being decided on. Closing for now.
