### ISSUE TITLE
Encrypt configuration file

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3940]
Users are uploading their configuration files with Lantern servers to public sites. To get around this, we should encrypt it.

**Comment by Arthur2e5** [comment]
// PR: #3985

**Comment by oxtoacart** [comment]
@sunshine19090 The requirement to test is:

1. By default, the lantern.yaml should not be human readable
2. If you use the `-readableconfig` command-line flag, it should be human readable
3. You should be able to switch between using `-readableconfig` and not using it, and Lantern should still work
