### ISSUE TITLE
make android-lib fails on Linux

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern#3941]
Tested on both Ubuntu 14 LTS and Debian Jessie.

```
gomobile: sha256 for "gomobile-ndk-r10e-linux-x86_64.tar.gz": bacfed664a7b69b1b693f246ea49a85f04f502bd1ae723351c5345ab5b2ba850, want 709d96f5234c224e4b72254fd2e196d0e1486b8d943e972ed98cf14e3ca7bdde
```

**Comment by uaalto** [comment]
Seems to be an issue with gomobile with Go 1.6 on linux

**Comment by uaalto** [comment]
Issue in Go's project: https://github.com/golang/go/issues/15202

**Comment by myleshorton** [comment]
This is failing for me now on OSX @uaalto -- google gave me the bug you opened.

**Comment by uaalto** [comment]
@myleshorton I was using `master`. In `devel` it doesn't happen. It can be fixed by manually updating gomobile, though.

**Comment by aranhoide** [comment]
Is this related to #3853?

**Comment by aranhoide** [comment]
The upstream issue is closed, so I'm assuming this is resolved.  @uaalto please reopen otherwise.

**Comment by uaalto** [comment]
Yes it's fine. Thank you!
