### ISSUE TITLE
make mac osx package version failed

### ISSUE THREAD

**Issue by hhhaiai** [getlantern/lantern#3942]
hi:
    build release version failed. alert "no identity found", why? please help, thx.

failed log:

[~/code/lantern]VERSION=2.1.1 make package-darwin
Building darwin/amd64...
Build tags: 
Extra ldflags: -X github.com/getlantern/flashlight.compileTimePackageVersion=2.1.1
Generating distribution package for darwin/amd64 manoto...
Developer ID Application: Brave New Software Project, Inc: no identity found
make: *** [package-darwin-manoto] Error 1

**Comment by hhhaiai** [comment]
need which identity inc?

**Comment by aranhoide** [comment]
@xiam: please reassign if you think someone else may be more fit for this one.

**Comment by xiam** [comment]
Hey @hhhaiai, currently only we can generate signed packages for distribution. Please use `make darwin` to generate a binary for OSX.
