### ISSUE TITLE
A fake official website of lantern

### ISSUE THREAD

**Issue by hairuo** [getlantern/lantern#3944]
Recently if you use baidu to search lantern, the search result will give you a so called offical but seems fake website like this:
http://www.getlanternn.com/

And the true official website: https://getlantern.org/ is after the above address.

Many people have been cheated by this fake address, besides, honestly to speak, the website design is really very impressive with beautiful sky and slogans.

This is not a lonely example, if you search potplayer in baidu, it will also show you a fake address as:
http://www.potplayer.org/ just next under the official address as http://potplayer.daum.net/, and download from the site with .org, for example, my Nod32 will warn it contains  virus.

I write this issue to make sure if http://www.getlanternn.com/ is the right address. if it is not, I would suggest to add a statement on the official website of lantern to make people not be confused by Baidu.

Thanks for your attention!

**Comment by myleshorton** [comment]
Thanks @hairuo! You are correct that getlanternn.org is not the official site and is a pirated version. We are aware of the problem and are working on better ways to address it, but thank you very much for the report and please let us know if you see any other sites along these lines or have any other ideas for how we might solve the issue. I wonder how other software out there solves it?

**Comment by hairuo** [comment]
@myleshorton Thanks for your reply! By now I have no idea how to solve this, because this is a little different when comparing with other GFW-unrelated software.  I will comment here if I know any ways to solve this.

**Comment by percyalpha** [comment]
Getlanternn.com has been terminated

**Comment by hairuo** [comment]
Yeah, http://www.getlanternn.com/ can't be found when search "lantern" on baidu anymore, and this website isn't working either.

**Comment by percyalpha** [comment]
If you're aware of other fakes, please let us know. And we will deal with
it.

On Friday, May 13, 2016, Hairuo <notifications@github.com> wrote:

> Yeah, http://www.getlanternn.com/ can't be found when search "lantern" on
> baidu anymore, and this website isn't working either.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3944#issuecomment-219193136>
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by hairuo** [comment]
OK~
