### ISSUE TITLE
Kaspersky reports Lantern 2.1.1 as "Trojan-FakeAV.Win32.Onescan.vvc"

### ISSUE THREAD

**Issue by XSStudio** [getlantern/lantern#3945]
This is quite weird... After updating Kaspersky to 4/10/2016, the antivirus software recognized Lantern 2.1.1 as "Trojan-FakeAV.Win32.Onescan.vvc". According to the online interpretation by COMODO:

> Trojan.FakeAV is classified as a Trojan horse, it can be you will not knowingly infecting your computer, and you can spy on your computer data leakage, download and install the rogue program from the server. It is in many ways, such as from spam containing malicious links or attachments, blog or connect to pornographic websites into the computer. If you have visited pornographic sites or other malicious websites, your computer can easily be virus attacks.
> ......
> This Trojan is often used to spread malware or fake antivirus programs. Once it is downloaded, it will drop several malicious files and create several new folder in Application Data folder, allowing users to feel confused, and find how to distinguish legitimate system files. Therefore, to remove the virus has become more complicated. We recommend manually remove this stubborn Trojan.

Does anyone have similar issue with their AV?

**Comment by ZombieTerminator** [comment]
I encountered this issue last night.For now,lantern has been considered as a malicious software.And it will be deleted by Kaspersky automatically when you download it.

**Comment by Rogerlin2013** [comment]
I encountered this issue too.

**Comment by myleshorton** [comment]
This could be another cause of the drop in user numbers guys. Adding @oxtoacart, @atavism, and @percyalpha. @sunshine19090 weren't we at one point not seen as malicious software by Kaspersky? Do we need to contact them again?

**Comment by percyalpha** [comment]
Yeah, this could be. I'll also test with domestic anti-virus both on windows and android

**Comment by sunshine19090** [comment]
@myleshorton I was about to mail you regarding this yesterday but forgot to do the same. Kaspersky needs our company address to be on our website to process our application for proactively whitelisting our software.  Forwarded you the email. If we can put up our address in the website, then I can start working with them. Thanks!

**Comment by sunshine19090** [comment]
@myleshorton Anyway, when I ran our version 2.1.1 in virustotal.com, I didn't find any AV company giving a false positive. I believe it included Kaspersky too. May be should I try some other website for this purpose?

**Comment by myleshorton** [comment]
Seems like we can close this one @sunshine19090 right?

**Comment by sunshine19090** [comment]
Yes @myleshorton , I received email from kaspersky that they have removed the false positive detection for 2.2.1 for lantern.exe file. I am still waiting on the installer analysis. 

We will have to send the files everytime we release a new version to kaspersky, I think. I have asked them about it and waiting for their reply.

**Comment by myleshorton** [comment]
We automatically send new installers to kaspersky now.

**Comment by oncidiumluridum** [comment]
I'm guess that Kaspersky complains auto-download update package silently, and it is a competitor of Kaspersky Secure Connection component, Kaspersky always suggest me uninstall Lantern, so I'm hard to make a decision, who I should trust?
