### ISSUE TITLE
Disable Lantern in-app proxying when full device VPN is on

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#3948]
See #3939.  Basically, once the full device VPN is on, it's more efficient to disable the Lantern embedded inside the app.

**Comment by aranhoide** [comment]
@oxtoacart @atavism : please bump the priority if you think I'm underestimating (well, underguessing :) ) the efficiency impact of this.  Feel free to reassign too, of course.

**Comment by oxtoacart** [comment]
I think @atavism has already effectively implemented this.  Am I right?
