### ISSUE TITLE
google chrome can't use lantern to over the wall to  visit google.com、facebook.com or youtebe.com(win10)

### ISSUE THREAD

**Issue by 15757170756** [getlantern/lantern#3949]
google chrome can't use lantern to over the wall to  visit google.com、facebook.com or youtebe.com(win10)

**Comment by myleshorton** [comment]
Do you have any chrome extensions or xunlei installed? Try disabling them if so.

**Comment by 15757170756** [comment]
yes i've used google extensions switchyOmega to over the wall because the XX-Net needs it. but xx-net neeeds google appid and has a little flow(one appid for 1G).Do I close switchyOmega ,then I can use lantern to over the wall?

**Comment by 15757170756** [comment]
xunlei?It'll affect lantern?I Install the xunlei software,but not the chrome extensions xunlei.

**Comment by myleshorton** [comment]
Yeah, we actually still don't know why @15757170756, but for some reason xunlei interferes with Lantern.

**Comment by bigtan** [comment]
```
netsh interface tcp set global autotuninglevel=normal
```
xunlei will modify some system configuration, run the command may take effects.

**Comment by fffw** [comment]
Xunlei will install a driver at `C:\Windows\system32\drivers\xlwfp.sys`. Lantern works good if this driver is not loaded.

**Comment by 15757170756** [comment]
what if the xlwfp.sys is loaded in C:\Windows\system32\drivers? I should delete it?

**Comment by fffw** [comment]
@15757170756 The simplest would be to uninstall Xunlei. Or rename the file and restart OS.

**Comment by 15757170756** [comment]
OK. usually I use xunlei to download movie 、software and so on. So xunlei is necessary." Or rename the file"?  rename which file? is that xlwfp.sys file?

**Comment by myleshorton** [comment]
Yeah @fffw is talking about the `C:\Windows\system32\drivers\xlwfp.sys` file @15757170756 - you could temporarily move it somewhere else. We'll eventually figure out some solution though.

**Comment by weiweilinlin** [comment]
i think you should use the switchomega  and set the port 8787 ,and then you can pass the wall

**Comment by xiam** [comment]
Hello @15757170756, which version of Xunlei are you using?

**Comment by xiam** [comment]
The @weiweilinlin idea of setting address to `127.0.0.1` and port to `8787` should work, can you try and confirm?
