### ISSUE TITLE
Error building android-release

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3957]
Unfortunately make clean and manually removing all liblantern.aars did not fix this. The only way I could get gomobile to work, though, was to delete the gomobile directory and update it to the latest, so I suspect that could be part of the issue. Any ideas @oxtoacart and @atavism?

```
:app:compileReleaseJavaWithJavac
/Users/afisk/gopath/src/github.com/getlantern/lantern/src/github.com/getlantern/lantern-mobile/app/src/main/java/org/getlantern/lantern/vpn/Service.java:34: error: cannot find symbol
            Lantern.ProtectConnections(getDnsResolver(getApplicationContext()), new Lantern.SocketProtector.Stub() {
                                                                                                           ^
  symbol:   class Stub
  location: interface SocketProtector
```

**Comment by myleshorton** [comment]
Interestingly this earlier line succeeds, so looks like possibly something different with the release build.

```
:sdk:compileDebugJavaWithJavac UP-TO-DATE
```

**Comment by myleshorton** [comment]
Oh wait that's the sdk though...weird the sdk is building with debug!! That seems like an issue.

**Comment by oxtoacart** [comment]
Weird, I don't see that issue.  I'm running with Go 1.6 and building with this command:

```
SECRETS_DIR=~/git/too-many-secrets BNS_CERT_PASS="xxxxxxxxxx" VERSION=2.1.2 make clean android-release
```

**Comment by myleshorton** [comment]
Yeah it's very strange on a number of levels (ultimately worked with some
combination of deleting the built gomobile, making clean, etc) so closing
for now!

**Comment by oxtoacart** [comment]
I wonder if maybe an old gomobile was getting picked up from somewhere on
your path?  The makefile builds its own gomobile, and clean actually
deletes it to force a rebuild.

-- 
Cheers,
Ox

PGP Key - https://pgp.mit.edu/pks/lookup?op=get&search=ox@getlantern.org

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy
