### ISSUE TITLE
Android mobile---Can't open any web when enable lantern under mobile network(android)

### ISSUE THREAD

**Issue by shevilangle** [getlantern/lantern#3958]
Can't open any web when enable lantern under mobile network(android).
pre condition:
Operator: china telecom/china mobile
lantern: on

1. using wifi, it is ok to visit google/youtobe/baidu/, and so on
2. using mobile network(china telecom or china mobile, didn't test with china union sim card), can't connect to any web
3. if disable lantern, can connect to baidu but not google/youtobe

**Comment by shevilangle** [comment]
it should be network issue, sorry so much

**Comment by myleshorton** [comment]
No problem @shevilangle glad it's working
