### ISSUE TITLE
[ui] Feeds UI tunes

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3959]
- [x] Hide horizontal scrolling bar by default and show it on hover. Reference [this article](https://blogs.msdn.microsoft.com/kurlak/2013/11/03/hiding-vertical-scrollbars-with-pure-css-in-chrome-ie-6-firefox-opera-and-safari/). - Done
- [x] Add media query to feeds window. Breakpoints are TBD. -Done
- [x] Content preview text gets cut off when it is too long. cap the text length and if it goes over, show (...) 
- [x] Change the Mixed feed icon to just say "ALL" -Done
- [x] Show spinner before feeds loaded - Done
- [x] Fallback to bookmarks when error to load feeds - Done
- [x] Lazy load images #3965 -Done
- [x] Cross browser look and feel -Done IE/Edge/Chrome/Safari/Firefox
- [x] the "About" pop up screen reads "Lantern Version" at the top but doesn't have version number - Done
- [x] All of the dates on the Reddit feed are reading "Dec 31, 1" - data source
- [x] Post source only shows on first post from that source - data source
- [x] Scrollbar on Edge - Vertical scrollbar is still visible on Edge/IE
- [x] Some images look distorted, as if we're forcing all images to the same aspect ratio no matter what.
- [x] Double scrolling bar on Chrome 
- [x] Some translations "All" -> “所有内容” “CDT”->"中国数字时代" - Data source
- [x] Jandan Thumbnail blocked because Jandan doesn't allow images from outside sources. 
- [x] deutsche welle pulls in the same thumbnail ~~and incorrect date on the Farsi language feed~~
- [x] aljazeera feed is failing 
- [x] some thumbnails are not working: GIFs and from certain HTTPS sites

**Comment by Derekf5** [comment]
4.  Content preview text gets cut off when it is too long.   cap the text length and if it goes over, show (...)

**Comment by Derekf5** [comment]
4)  Content preview text gets cut off when it is too long.   cap the text length and if it goes over, show (...)

**Comment by Derekf5** [comment]
5) Change the Mixed feed icon to just say "ALL"

**Comment by fffw** [comment]
6) Show spinner before feeds loaded - Done
7) Fallback to bookmarks when error to load feeds - Done
8) Lazy load images https://github.com/getlantern/lantern/issues/3965

**Comment by fffw** [comment]
9) Cross browser look and feel

**Comment by fffw** [comment]
10) the "About" pop up screen reads "Lantern Version" at the top but doesn't have version number - Done
11) All of the dates on the Reddit feed are reading "Dec 31, 1" - *data source*
12) Post source only shows on first post from that source

**Comment by oxtoacart** [comment]
14) Some images look distorted, as if we're forcing all images to the same aspect ratio no matter what.

**Comment by percyalpha** [comment]
15) Double scrolling bar on Chrome
![image](https://cloud.githubusercontent.com/assets/7925929/14514547/90aa819a-01a6-11e6-91d7-4a6ec8aec38c.png)
16) Some translations "All" -> “所有内容” “CDT”->"中国数字时代"

**Comment by percyalpha** [comment]
17) Jandan Thumbnail blocked because Jandan doesn't allow images from outside sources. Consider cache+ fake referer

**Comment by fffw** [comment]
> 17)  Jandan Thumbnail blocked because Jandan doesn't allow images from outside sources. Consider cache+ fake referer

I don't think setting referer header would work inside browser. We'd better take it off as the content is not that consistent with other feeds.

**Comment by myleshorton** [comment]
I believe there's some trick with HTTPS, redirects, and referer @fffw but I'd have to double check.

**Comment by Derekf5** [comment]
18) deutsche welle also pulls in the same thumbnail and incorrect date on the Farsi language feed.

**Comment by xiam** [comment]
`11) reddit date` and `12) source missing` should be fixed now.

**Comment by percyalpha** [comment]
18) On android, feed tabs and contents mismatches. CDT tab shows Jandan, Jandan shows BBC, BBC shows CDT
19) On android, the scrolling, zoom on webview not very responsive. 
![screenshot_20160414-135536](https://cloud.githubusercontent.com/assets/7925929/14544177/adb13c2e-024c-11e6-9eea-8e44c35de855.png)

**Comment by fffw** [comment]
Cross browser check for the latest code of https://github.com/getlantern/lantern/pull/3982.

1. Vertical scroll bar is always shown, on all browsers.
2. In some cases, ellipsis is shown when text is not overflowed.
3. Firefox tends to add more entries (typically 30 instead of 10) to All tab. That won't be a problem.
4. Firefox doesn't show spinner as animation.
