### ISSUE TITLE
[UI] Feeds UI Tunes Mobile

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#3960]
@atavism dropping these here as well just to track.

1. Feed names and dividers should change to white when the lantern is on, this will look better on the blue background. 

2. The default feed should be "all" just like on desktop.  This option should be first in line.  

3.  Article preview text is often cut off. We should just move the article title up to be even with the top of each preview image.   This should solve the clipping problem.  If this doesnt solve it when preview text goes over allotted space use (...)

**Comment by atavism** [comment]
All fixed
