### ISSUE TITLE
Unfortunately Lantern has Stopped Working

### ISSUE THREAD

**Issue by FirstyxF** [getlantern/lantern#3989]
Lantern crashed when I try to turn it on. Android 5.0. Any suggestions?

**Comment by aranhoide** [comment]
Did it work for you before?  What's your Lantern version?

@atavism are you aware of any similar problems in the current or previous versions?

**Comment by atavism** [comment]
Hi @FirstyxF, have you tried installing the latest version? You can download it from [here](https://play.google.com/store/apps/details?id=org.getlantern.lantern) or [here](https://s3.amazonaws.com/lantern/lantern-installer-beta.apk). Please re-open this ticket or send an e-mail to ``support@getlantern.org`` if you're still having issues.
