### ISSUE TITLE
Some of the feeds doesn't have images

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3994]
![image](https://cloud.githubusercontent.com/assets/11394369/14616555/c23391ae-055f-11e6-809d-0121b05b9a09.png)

**Comment by myleshorton** [comment]
That particular screenshot seems to show images for all the feeds though right @sunshine19090?

**Comment by sunshine19090** [comment]
Sorry @myleshorton, I posted a wrong screenshot. Only Reddit and reuters has that problem. From @xiam explanation, I can understand that reddit couldn't fetch the images because they don't have a direct link to the images and some doesn't really have images on it. But I think reuters has images on all the articles as far as I have seen but still not displayed in our feeds. 

The below screenshot doesn't have images for reuters but if I go directly to reuters, I can see the images.

Here is the article as I couldn't open the articles from reuters,
http://www.reuters.com/article/us-macedonia-wiretap-idUSKCN0XC1PU

![image](https://cloud.githubusercontent.com/assets/11394369/14617976/452a2fbe-0565-11e6-846d-4c8d9a8bbdd2.png)

**Comment by xiam** [comment]
The source we're using for that reuters feed is http://feeds.reuters.com/Reuters/worldNews, and none of these links actually works, so the bot is not able to reach the original article that has pictures. Maybe we should remove that feed temporarily?

**Comment by myleshorton** [comment]
It will always be the case that some articles don't have thumbnails for some reason -- closing for now.
