### ISSUE TITLE
Reuters feed doesn't have images

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3995]
Logging it as P1 as none of the feed has the images under Reuters.

![image](https://cloud.githubusercontent.com/assets/11394369/14616613/fe20536e-055f-11e6-8f22-e7788d018038.png)

**Comment by xiam** [comment]
That will happen for some of the items. Some feeds do not have article images, in this case the feed reader uses a third party (diffbot) to get the articles's image. In this case diffbot is failing to load the article, and by consequence no image can be extracted from it.

**Comment by myleshorton** [comment]
Skipping reuters for now (until it comes back online).
