### ISSUE TITLE
Snapshot of video feeds are so wide

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#3997]
![image](https://cloud.githubusercontent.com/assets/11394369/14616766/a2df1ba6-0560-11e6-9169-0a43c1ea08f3.png)

**Comment by myleshorton** [comment]
Can we close this @sunshine19090?

**Comment by sunshine19090** [comment]
I see that the NYT video snapshots are good but none of the other channels has video today. Perhaps we can close this for now and then reopen if occurs again. Is that okay @myleshorton ?

**Comment by myleshorton** [comment]
Sounds good to me @sunshine19090
