### ISSUE TITLE
Phone verification SMS doesn't say what it's for -- just has the code

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3998]

**Comment by uaalto** [comment]
This error should be fixed now @myleshorton 
I will leave it open until you confirm it in your side, if you want.

**Comment by uaalto** [comment]
@sunshine19090 maybe you want to take a look at these :)
(I'm not sure if Pro is a priority for you right now)

**Comment by fffw** [comment]
@uaalto I received SMS with `SNY Lantern code: xxxxxx`. Should be ok to close.

**Comment by uaalto** [comment]
Thank you @fffw !
Just to make sure: You got "Lantern code: XXXXXX", right? I don't know what you mean by SNY there.

**Comment by fffw** [comment]
Hmm @uaalto `SNY ` is a prefix which also appeared in SMS sent by Stripe. I don't think it can be removed from Lantern side.

**Comment by uaalto** [comment]
Interestingly, I don't receive it. Well, that's a different issue anyway. Thank for testing Merlin!
