### ISSUE TITLE
In some channels, feeds with today's date alone are retrieved. 

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4002]
If the user reaches the end of the scroll, the page is not refreshed to load more feeds from previous days.

**Comment by xiam** [comment]
We're not currently storing historical data on feeds, so this is not possible right now.

**Comment by sunshine19090** [comment]
Okay @xiam but I couldn't understand why there is a difference in the number of feeds that we are showing across the channels. Below is the data that I am seeing,

BBC - 28 feeds - some articles from apr 17 
NYT - some from April 17 and one From feb 24 - 20 feeds. There are no feeds in between April 17 and Feb 24.
Al Jazeera - 25 feeds - Only today's feeds - If there is only today's feed then why we are not showing more than 25? whereas BBC shows 28 even from Apr 17. 
Buzzfeed - 20 feeds - only today's feeds
reddit - 25 feeds - one from apr 17

**Comment by xiam** [comment]
We're not limiting the number of articles from a source, and we cannot request more nor request from specific dates, we see whatever the source provides and these sources are static. See for instance BBC http://feeds.bbci.co.uk/news/world/rss.xml, and Al Jazeera http://www.aljazeera.com/xml/rss/all.xml

**Comment by sunshine19090** [comment]
Got it! Thank you @xiam.
