### ISSUE TITLE
The scroll should come back to top when moving from one channel to other channel

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4004]
I scrolled down in buzzfeed and then moved NYT and then came to buzzfeed but the scroll was in the same place. I would prefer it to be at the top when I move from one feed to other feed. @myleshorton @xiam what do you think?

**Comment by myleshorton** [comment]
I can see both sides, although I would argue the current behavior is overall probably better because it's easier for the user to go to the beginning of a feed manually than it is for them to figure out where they had previously scrolled to manually.

**Comment by sunshine19090** [comment]
I felt it little time consuming to go up and down everytime while testing :) So probably the user may not be using it that way. Closing it now.
