### ISSUE TITLE
Bad response code accessing config server

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4005]
Note the line number is off (as well as the more detailed comment) because I've been making local changes to debug it...

```
Apr 18 20:10:57.319 - 0m0s ERROR flashlight.util: http.go:128 Bad response code: 400 Bad Request accessing URL 'http://config.getiantem.org/cloud.yaml.gz?ad69346b-b9fc-405e-bc98-792491238195' and headers
HTTP/1.1 400 Bad Request
Connection: close
Content-Type: text/plain
```

I wonder if you're able to reproduce this @oxtoacart?

**Comment by oxtoacart** [comment]
I've been unable to reproduce on devel.  I set it up to fetch the config every 2 seconds and to always use both domain fronting and a chained proxy.  I left it running for several minutes and didn't see the error.

**Comment by oxtoacart** [comment]
Okay, I've had it running on 2.2.0 for about 15 minutes now and haven't seen the error either.  That's about 450 config fetches, so the error rate is less than 0.25% at most.

**Comment by myleshorton** [comment]
Weird. I saw it on every run and several times on each. Maybe something
with my yaml? I'll try to reproduce.

**Comment by myleshorton** [comment]
Yeah I'm able to reproduce it on a second network now @oxtoacart, and it happens even if I delete my yaml config file on startup. I shot over over my logs along with the config just in case, but if you still can't reproduce it I'll just keep digging into it on my end. I'm running straight from the release-2.2.0 branch.

**Comment by fffw** [comment]
@myleshorton Would it help to send your config file so we can check if it's related to that specific server?

**Comment by fffw** [comment]
There's no `Reverse proxying GET http://config.getiantem.org/cloud.yaml.gz?...` log entry, which indicates that the 400 error is responded by `http.Server` directly, and most likely, because the request is invalid. @myleshorton if you print out the request when 400 error is encountered, that will be the clue.

**Comment by oxtoacart** [comment]
@myleshorton I tried forcing my traffic through either of the chained proxies that I see in your log, but I still couldn't see the error.  If you can send over your YAML, I'll try running with that and see if it has any effect.

**Comment by oxtoacart** [comment]
@myleshorton Even with your config yaml, running from the release-2.2.0 branch, I cannot reproduce.  I'm running on OS X, built with `make lantern` using Go 1.6.  Do you have any code that I don't?  Are you building differently? Using a different version of Go?

**Comment by myleshorton** [comment]
Ha! Good idea @fffw. Looks like a blank user ID again.

On Tue, Apr 19, 2016 at 4:34 AM, oxtoacart <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> I tried forcing my traffic
> through either of the chained proxies that I see in your log, but I still
> couldn't see the error. If you can send over your YAML, I'll try running
> with that and see if it has any effect.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/4005#issuecomment-211868718>
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
@myleshorton What's in your settings.yaml?

**Comment by oxtoacart** [comment]
@uaalto Any insights?  It seems that if user ID in settings.yaml is set to something other than 0 (e.g. 20), the client seems to send an empty user ID header and the chained servers return a 400 error.

**Comment by myleshorton** [comment]
Oh interesting. I was assuming it was the config server, but maybe it's the
chained server?

**Comment by oxtoacart** [comment]
@myleshorton Good point, I'm not sure if it's the config server or the chained server.

**Comment by oxtoacart** [comment]
@myleshorton I guess if it was the chained server, none of your proxying would succeed.  Does any of your proxying succeed?

**Comment by myleshorton** [comment]
Yeah proxying generally works fine @oxtoacart

**Comment by oxtoacart** [comment]
@myleshorton Okay, then it's not the chained proxy that's the issue.

**Comment by myleshorton** [comment]
Yeah I think it's just the config-server arguably correctly returning an error on an invalid user-id @oxtoacart. Given that AFAIK there's no way for a currently released client to have a client-id in their settings.yaml, I'm not sure it's really an issue. Then again, it has arisen a couple of times just in testing now, so alternatively we could just have the config server just treat clients with invalid user IDs as free. Then again, though, if there really is a pro user out there with an invalid ID somehow, we definitely wan to know that right away in some fashion. The client failing probably isn't ideal, but some sort of logging or alert on the server itself would probably be useful. I'm going to move this out of this milestone though unless you think I'm missing something?

**Comment by uaalto** [comment]
The config-server doesn't currently test the validity of the user ID, as the pro server does. It will just try to find it and authenticate it, and otherwise treat it as a free user. If the config-server replies with `Bad request` is probably because of the format of the HTTP request. Perhaps is sent malformed?

**Comment by oxtoacart** [comment]
@myleshorton The release-2.1.2 branch does have the userID logic in settings.yaml.  I don't know if it would ever get populated, but at least part of the logic is already in production.

**Comment by myleshorton** [comment]
Right it has it in **settings.go** but there's no way for **settings.yaml** to be populated with a userid in production AFAIK @oxtoacart.

**Comment by myleshorton** [comment]
Yeah it looks like it actually is malformed @uaalto -- treating "20" as a space char or something I think. I believe on the pro-backend branch it's actually just treating it all as a string, which would fix this. Gotta look at that PR. Then again, this really isn't super pressing right now.

**Comment by oxtoacart** [comment]
@myleshorton @uaalto I'm not seeing this in the production logs for release 2.1.2, so I agree it's not high priority.

**Comment by fffw** [comment]
The cause of "400 bad request" is [fetcher.go#L115](https://github.com/getlantern/lantern/blob/release-2.1.2/src/github.com/getlantern/flashlight/config/fetcher.go#L115). We should use `strconv` instead of type conversion directly.

**Comment by myleshorton** [comment]
Yeah so this is the same issue we were discussing before @fffw. That code is never touched in production because no one has pro. It's also fixed on the pro branch though.

**Comment by myleshorton** [comment]
So without pro you don't have a User ID.
