### ISSUE TITLE
Some titles has more than 5 lines and the 5th line is not seen completely

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4006]
![image](https://cloud.githubusercontent.com/assets/11394369/14619911/c5bb407e-056e-11e6-9f96-80108b04809d.png)

**Comment by myleshorton** [comment]
Can we close this @sunshine19090?

**Comment by sunshine19090** [comment]
I don't see any article with title that are going beyond 2 lines. So I am assuming now that it has been fixed.

**Comment by sunshine19090** [comment]
I will reopen if I see this again.
