### ISSUE TITLE
Pin it button shows up when hovering on images - chrome 

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4007]

**Comment by fffw** [comment]
@sunshine19090 I didn't see any button when hovering. Can you take a screenshot or a photo? Is it possible that some Chrome extension showed it?

**Comment by sunshine19090** [comment]
![image](https://cloud.githubusercontent.com/assets/11394369/14622060/481f39be-057c-11e6-940c-c69dd0e9417d.png)

**Comment by sunshine19090** [comment]
Yes @fffw, I have the pin it extensions but never realized it before. So I thought it is weird that it is showing up in chrome :)

**Comment by sunshine19090** [comment]
@fffw I am still wondering if we should avoid the pin it button showing up on images. But I will leave the decision to you guys. You can close it if you think it is okay to show the pin it button.

**Comment by fffw** [comment]
So you are not alone to feel that button annoying, see http://www.askdavetaylor.com/stop-pinterest-pin-button-appearing-images-chrome/. Fortunately Pinterest knows it and has a solution https://help.pinterest.com/en/articles/prevent-pinning-your-site. Will do a quick fix!

**Comment by myleshorton** [comment]
Closed in #4014

**Comment by myleshorton** [comment]
Can we close this @sunshine19090?

**Comment by sunshine19090** [comment]
Yep, I don't see the button now.
