### ISSUE TITLE
Lantern logo in Chrome and IE browser has some white area

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4009]
![image](https://cloud.githubusercontent.com/assets/11394369/14621136/93926b5c-0575-11e6-9324-07008d9dcace.png)

**Comment by fffw** [comment]
The white area is by design so it's Firefox that doesn't show it correctly. Will tweak the SVG file a bit to make Firefox happy. Good catch @sunshine19090 !

**Comment by sunshine19090** [comment]
Thanks @fffw. BTW, if that is the case then you should change the logo in getlantern.org too.

**Comment by sunshine19090** [comment]
![image](https://cloud.githubusercontent.com/assets/11394369/14622564/9fb297ae-057f-11e6-85ae-848ed894efd9.png)

**Comment by fffw** [comment]
Ok so it's a bug of Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=353575

**Comment by sunshine19090** [comment]
@fffw Now the logo looks good on lantern desktop but the white part is still missing in getlantern.org page. Is the fix applied for this too?

**Comment by fffw** [comment]
@sunshine19090 I created a new issue for the site at https://github.com/getlantern/www/issues/51 as it requires a different image.

**Comment by myleshorton** [comment]
Can we close this one @sunshine19090?

**Comment by sunshine19090** [comment]
Yeah this looks good now.
