### ISSUE TITLE
Edge - The titles doesn't have the lower half of the lower case letters 'p','y','g'

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4019]
![image](https://cloud.githubusercontent.com/assets/11394369/14652042/6f09e4d8-0627-11e6-894d-afa338e33082.png)

**Comment by myleshorton** [comment]
Nice @sunshine19090. I noticed those are cut off by just a few pixels on OSX even as well and meant to ticket it.

**Comment by fffw** [comment]
I just realized that I didn't follow the design for the font-size and line-height of the title. Will do the quick fix.

**Comment by fffw** [comment]
Will be in next QA build

**Comment by sunshine19090** [comment]
@myleshorton @fffw I don't see any change in the UI. I am using the latest QA build version 20160419.165911.

**Comment by fffw** [comment]
@sunshine19090 new QA build isn't out yet. Continuous build would help this situation. I created https://github.com/getlantern/lantern/issues/4052 to discuss about it, low priority.

**Comment by myleshorton** [comment]
I'll do another build tomorrow morning first thing @fffw and @sunshine19090 to make sure I bring in all the latest changes.

**Comment by sunshine19090** [comment]
@myleshorton I still see a minute cut off in all browsers and platforms but not big enough for anyone to notice it. Shall I close it or assign it to @fffw ?

**Comment by fffw** [comment]
@sunshine19090 If you can still see the cut off please paste a screen so I can check what caused it.

**Comment by sunshine19090** [comment]
@fffw 

![letters are cut off](https://cloud.githubusercontent.com/assets/11394369/14828643/c1c34938-0b9c-11e6-9359-2c56b68d061f.png)

**Comment by sunshine19090** [comment]
Since this is a minor issue, please feel free to push this to next release or close it.

**Comment by fffw** [comment]
Thanks @sunshine19090 for catching it. So 16 px `line-height` is not sufficient on Edge, while 18px works for all browsers.

**Comment by sunshine19090** [comment]
@fffw Sorry, I forgot to mention that it happens in all the browser not only in Edge. The screenshot in my previous comment is from Chrome browser.

**Comment by fffw** [comment]
@sunshine19090 I adjusted the line height a bit. Could you try the latest QA build?

**Comment by sunshine19090** [comment]
yeah @fffw , it looks good now in Windows 7, all browsers. I will check in other platforms and close the ticket.
