### ISSUE TITLE
In some cases, there are extra dots(...) appearing in the article description

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4020]
![image](https://cloud.githubusercontent.com/assets/11394369/14652105/b0ca6b4a-0627-11e6-997b-157e1682e59d.png)

![image](https://cloud.githubusercontent.com/assets/11394369/14652117/bb637380-0627-11e6-9917-675b284a7050.png)

![image](https://cloud.githubusercontent.com/assets/11394369/14652148/df2d65dc-0627-11e6-97f2-c0f353c058f3.png)

**Comment by fffw** [comment]
@sunshine19090 Those dots are part of the description. Though Buzzfeed's RSS feed doesn't have the dots, the service we use to extract abstract from web link --- https://www.diffbot.com/, does return them.

CC @xiam

**Comment by xiam** [comment]
Could not find the extra dots in the feed, @fffw:

![screen shot 2016-04-20 at 12 50 28 pm](https://cloud.githubusercontent.com/assets/385670/14684622/84967c10-06f6-11e6-8065-3a898b4b6cee.png)

![screen shot 2016-04-20 at 12 50 02 pm](https://cloud.githubusercontent.com/assets/385670/14684630/896d3ddc-06f6-11e6-98d7-21ee98ba2963.png)

**Comment by fffw** [comment]
@xiam It only happened to Buzzfeed. Excerpt from feed.json:

```
    {
--> "title": "36 Reasons Why You Should Never, Ever Visit The Spanish Countryside",
      "link": "https://www.buzzfeed.com/beatrizserranomolina/avoid-northern-spain?utm_term=4ldqpia",
      "image": "https://thumbs.getiantem.org/u0hN88taZXDSxymfpd0VgqnD2nI=/290x176/smart/https%3A%2F%2Fimg.buzzfeed.com%2Fbuzzfeed-static%2Fstatic%2F2016-04%2F19%2F11%2Fca
mpaign_images%2Fwebdr11%2F36-reasons-why-you-should-never-ever-visit-the-sp-2-12908-1461078217-0_dblbig.jpg",
      "image_square": "https://thumbs.getiantem.org/RDuRhdgHa-adPIrWeEfEB7mB3Ck=/500x500/smart/https%3A%2F%2Fimg.buzzfeed.com%2Fbuzzfeed-static%2Fstatic%2F2016-04%2F19%2F
11%2Fcampaign_images%2Fwebdr11%2F36-reasons-why-you-should-never-ever-visit-the-sp-2-12908-1461078217-0_dblbig.jpg",
      "author": "Beatriz Serrano",
      "source": "www.buzzfeed.com",
      "meta": {
        "apple-itunes-app": "app-id=352969997, affiliate-data=at=10l3HP&ct=Buzz/SmartBanner, app-argument=buzzfeed://buzz/beatrizserranomolina/avoid-northern-spain",
        "article:publisher": "https://www.facebook.com/BuzzFeed",
        "article:section": "Travel",
        "article:tag": "Austurias",
        "author": "Beatriz Serrano",
        "bf:buzzid": "4210859",
        "bf:userid": "3885916",
        "copyright": "Copyright 2016 BuzzFeed, Inc. All rights reserved.",
----> "description": "Planning your next vacation? Well, stay away from Spain's northern coast...",
...
```

Oh I think I should use `meta.title` instead of `meta.description`. I didn't notice that field before.

**Comment by xiam** [comment]
I think the 3 extra dots are those appearing at the right bottom of the article far apart from the description, right @sunshine19090?

**Comment by sunshine19090** [comment]
Yes @xiam, that's right. Sorry for the confusion. Going forward, I will start highlighting in the screenshots for issues like this :)

Regards,
Sunshine

**Comment by fffw** [comment]
Interesting I didn't notice it. It didn't happen to me on Chrome or Safari. It should already be fixed in e5e0dafb054e3d056c50ebcc43892dd82f1fe38d, but let me check again on Edge.

**Comment by fffw** [comment]
I can't see it on Edge or IE. It's unlikely to be caused by css cache. @sunshine19090 did you see it all the time?

![image](https://cloud.githubusercontent.com/assets/10410437/14698721/10965c9e-07c4-11e6-992b-594a8d9fe282.png)

**Comment by sunshine19090** [comment]
Yep, I think it was fixed already. I don't see it now @fffw.
