### ISSUE TITLE
Windows 7, all browsers - When Manage System proxy is turned off and if the sites are blocked, then lantern shows only the spinner and not loading the page

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4022]
![image](https://cloud.githubusercontent.com/assets/11394369/14654475/bb06425e-0632-11e6-9145-17c431ee184e.png)

**Comment by sunshine19090** [comment]
Works fine in windows 10 - able to see the news feed.

**Comment by fffw** [comment]
I think it will fallback to bookmarks eventually but need to confirm . We probably only need to show alarm on home screen if Manage system proxy is off, so user know what caused trouble

**Comment by sunshine19090** [comment]
I agree @fffw

**Comment by myleshorton** [comment]
We'll handle this one with #4024
