### ISSUE TITLE
Windows 7, All browsers - Unable to access geoiptool and slack site when proxy all traffic option is turned off

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4023]
Note: I didn't do DNS blocking when testing this.

**Comment by sunshine19090** [comment]
In windows 10, it works fine. I will update here after testing in OSX and Ubuntu.

**Comment by myleshorton** [comment]
There was a similar issue in the last round of testing you and @oxtoacart did right @sunshine19090? What was the cause of that again?

**Comment by sunshine19090** [comment]
No @myleshorton, it doesn't look similar to me. Last time I was not able to open any sites(used DNS blocking) even after turning ON the proxy all traffic option. 

But this time I am unable to access the sites that were not in the default whitelist after turning off the proxy all traffic option. I didn't use DNS blocking while testing. So I expected to access the sites that doesn't need proxy. 

Regards,
Sunshine

**Comment by myleshorton** [comment]
I just tried running this on a fresh install of Windows 7 (old one was corrupted), and it's working fine for me with both proxy all and without proxy all @sunshine19090.

Is there an example site you're trying just to make absolutely sure we're doing the same thing? Are you seeing this @oxtoacart?

**Comment by oxtoacart** [comment]
I tested on Windows 7 with IE 10 and Chrome, using Lantern built from the release-2.2.0 branch.  Proxy all was disabled, no DNS blocking enabled.  I was able to access both geoiptool.com and slack.com.

**Comment by sunshine19090** [comment]
That's weird! @myleshorton @oxtoacart  I am able to access these sites today with proxy all disabled. I checked atleast four times before I logged the issue but now the issue is gone. I am going to close it now. I will reopen this if it happens again.

**Comment by myleshorton** [comment]
Thanks @sunshine19090!
