### ISSUE TITLE
If Lantern's not working, the newsfeed will never load

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4024]

**Comment by myleshorton** [comment]
@Derekf5 we need some design for this that should say possible reasons for it, including:

1) A conflicting Chrome extension (we can detect Chrome and only display it in that case)
2) Xunlei thunder downloader installed

**Comment by Derekf5** [comment]
OK @myleshorton i should be able to have something tomorrow AM.   What do you mean by Xunlei downloader installed?   What should that error message read?

**Comment by myleshorton** [comment]
We basically just need to tell them the various things that could be going wrong. If Xunlei downloader is installed, that will break Lantern.

**Comment by fffw** [comment]
@myleshorton @Derekf5 I think that should be a separate page with a link from the bottom of home page.

I think Lantern will fallback to bookmarks if newsfeed fails to load, isn't it true for you @myleshorton ?

**Comment by fffw** [comment]
Ok it just takes too long to time out and fallback.

**Comment by myleshorton** [comment]
If newsfeed fails to load though @fffw, then Lantern probably won't work at all.

**Comment by Derekf5** [comment]
@myleshorton how is this?
<img width="724" alt="screen shot 2016-04-20 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/7864729/14678305/22effce2-06e3-11e6-856a-6fbc9aeb6893.png">
I can add specs here if you all think this works!

**Comment by myleshorton** [comment]
Yeah cool. I guess one bottleneck will be translating, and honestly we probably want completely different messages depending on the locale here too -- i.e. I don't think many people use Xunlei outside of China.

We should also probably include suggested fixes, maybe in parentheses? In order these could be:

1. (Try disabling them or sending their traffic through lantern at 127.0.0.1:8787)
1. (Try uninstalling it for now)
1. (If your network seems to be otherwise working, let us know on Facebook, GitHub, or our forums. You can also email us your logs, which are found in 
Windows Vista/7/8:C:\Users\USERNAME\AppData\Roaming\Lantern\logs
Windows XP: C:\Documents and Settings\USERNAME\Application Data\Lantern\Logs
OSX: ~/Library/Logs/Lantern
Ubuntu: ~/.lantern/logs)

That last one is obviously long, so maybe we expand it if they click on "email" that's a link, something like that.

**Comment by Derekf5** [comment]
Thanks @myleshorton that all sounds good to me, heres what it looks like now.
<img width="484" alt="screen shot 2016-04-20 at 11 24 48 am" src="https://cloud.githubusercontent.com/assets/7864729/14680217/88c04584-06ea-11e6-80fe-a7cba4451ad8.png">
<img width="486" alt="screen shot 2016-04-20 at 11 24 53 am" src="https://cloud.githubusercontent.com/assets/7864729/14680218/88c20c8e-06ea-11e6-9500-372a6b5d403a.png">

**Comment by myleshorton** [comment]
Cool thanks @Derekf5! How set are you on some of the caps =)? Like "OOPS" and "Browser"? I feel like my 8th grade english teacher, Mrs. Hogan, would not be happy.

**Comment by Derekf5** [comment]
HA! yes copy can be changed no problem :)

**Comment by Derekf5** [comment]
Specs coming in a minute or so.

**Comment by Derekf5** [comment]
![error-lantern-feed](https://cloud.githubusercontent.com/assets/7864729/14680708/2a7d3f7a-06ec-11e6-8720-d01eb7c096ba.png)
@myleshorton let me know if you need any more info

**Comment by myleshorton** [comment]
Hey @fffw can you add this? It's maybe a first step towards your diagnostics page!

**Comment by fffw** [comment]
Sure. It can be a good start point.

**Comment by myleshorton** [comment]
@fffw I was hoping to make progress on this but didn't. You mind tackling it?

**Comment by fffw** [comment]
Will focus on it today.

**Comment by myleshorton** [comment]
Hey @fffw I implemented an initial version of this on the issue-4024 branch. Still having a few problems with capturing feed loading errors (doesn't look like hideNewsfeed() or showNewsfeed() are ever actually called from `on-feeds-loaded` or `on-error` in news.html) but just wanted to let you know the skeleton is in there.

**Comment by sunshine19090** [comment]
shall we close this @myleshorton?

**Comment by sunshine19090** [comment]
@myleshorton Any way to simulate this scenario?

**Comment by myleshorton** [comment]
Disconnect your network and clear local storage by going to chrome://settings/cookies#cont and 127.0.0.1

**Comment by sunshine19090** [comment]
@myleshorton Thanks! I can see the error page after disconnecting network and clearing the local storage but I am not sure if it is because lantern is not working or just because network is disconnected (the cached feed is not yet ready to test). Would you mind if I defer testing this issue until the cached feed is ready?

**Comment by myleshorton** [comment]
Wait, are you currently able to get the error page with only disconnecting the network (i.e. even with a cached version you loaded when it was connected)? Either way, Lantern is showing the error page because Lantern's not connected to the network, though, so I don't think this is related to the cached loading issue really @sunshine19090

**Comment by sunshine19090** [comment]
I can now see the error page by deleting the local storage and disconnecting the network.

**Comment by myleshorton** [comment]
Nice!

On Fri, May 6, 2016 at 12:39 PM, sunshine19090 <notifications@github.com>
wrote:

> I can now see the error page by deleting the local storage and
> disconnecting the network.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/4024#issuecomment-217539564>
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89
