### ISSUE TITLE
Desktop - <StripeCheckout> never retries when checkout.js fails to load

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4025]
Especially in `ReferralPromotion.react.js`, failing to "continue to checkout" forces user to start over again, which is quite annoying.

**Comment by oxtoacart** [comment]
As a side note, are we forcing this through our proxy?  Otherwise, potentially someone could MITM that content and get into our UI.

**Comment by fffw** [comment]
No it's not forcibly proxied, especially if "Manage system proxy" is off.

Are there bigger risk for us comparing to an normal site using Stripe checkout?

**Comment by oxtoacart** [comment]
Our main adversary is better equipped to compromise certificate authorities than the average adversary.  It might be old fashioned, but my habit has always been to serve JavaScript on secure sites locally.  `js.stripe.com` gets an [A+ from Qualys](https://www.ssllabs.com/ssltest/analyze.html?d=js.stripe.com) and uses HSTS pinning in the most popular browsers, so it's probably not a big deal.

**Comment by oxtoacart** [comment]
Stripe is very specific about loading the JS from their site, so I don't think we should mess with it.

**Comment by myleshorton** [comment]
Not as relevant anymore!
