### ISSUE TITLE
Add manoto feed for fa_IR

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4030]
https://www.manoto.news/rss/news/rss.xml

**Comment by myleshorton** [comment]
Hey @oxtoacart I figured this could be a handy entry point as you at the feed aggregator -- sometimes easier to get your hands dirty!

**Comment by myleshorton** [comment]
Also FYI @xiam

**Comment by oxtoacart** [comment]
@myleshorton Manoto News seems to use their english name as their title.  Is that okay or should we use a Persian translation?

**Comment by myleshorton** [comment]
Not sure @oxtoacart -- could just use english for now and change it if necessary I think.
