### ISSUE TITLE
Unknown message type from backend running 2.1.2

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4035]
Saw this on one of our VPSes, apparently after an auto-update to 2.1.2:

```
New websocket instance created [object Event]
2 Got unknown message type: undefined app.js:106
```

The user-facing result of this is that the version doesn't appear and that none of the settings appear checked even though they're clearly set in the settings.yaml

**Comment by myleshorton** [comment]
@sunshine19090 it would be great if you could try to run with 2.1.2 and see if you can reproduce this when it auto-updates. This was running on Windows server, but I would just try Windows 7. You can get it from https://s3.amazonaws.com/lantern/lantern-installer-2.1.1.exe

**Comment by sunshine19090** [comment]
Sure @myleshorton, I will update here after testing.

**Comment by sunshine19090** [comment]
I am not getting any message.  The auto-update works fine and the settings are set correctly while auto-updating but the UI looks weird in all the browsers.

Both 2.1.1 and 2.1.2 looks like the below screenshot.

Steps I followed to reproduce:

1. Uninstalled and removed all the lantern files 
2. Installed fresh version of 2.1.1.
3. Quit lantern and reopen.
4. Automatically updated to 2.1.2. Setting remained the same as I have seen in 2.1.1. 

![image](https://cloud.githubusercontent.com/assets/11394369/14721309/9c27bc4e-07ba-11e6-9d18-e15138026b44.png)

**Comment by sunshine19090** [comment]
@myleshorton can you please provide me the details? I will look further into this after finishing my test in Mobile.

**Comment by myleshorton** [comment]
Hey sorry for the delay @sunshine19090 but that's super weird on those untranslated messages in the UI. Hey @xiam this would be super useful to look at while you're in windows land as well.

**Comment by myleshorton** [comment]
Haven't seen this one in awhile.
