### ISSUE TITLE
UI shows Reuters and Reddit too when selecting a language that we don't support in browser settings

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4037]
![image](https://cloud.githubusercontent.com/assets/11394369/14692111/e73f6968-0709-11e6-8a3e-e4a0c4991700.png)

**Comment by sunshine19090** [comment]
In the above case, I selected Chines (traditional) in chrome. I see the same behavior in Firefox when selecting zh-hk for chinese hongkong.

**Comment by sunshine19090** [comment]
This also happens when toggling between languages

**Comment by myleshorton** [comment]
It should just show the English feed in that case

**Comment by sunshine19090** [comment]
Yeah @myleshorton, it shows the English feed but I see the Reuters and Reddit channels too when I change from en-us to zh-hk or vice-versa. 

@xiam removed those channels two days before as we had problems with those but these are appearing now in this particular case. 

Regards,
Sunshine

**Comment by myleshorton** [comment]
Oh interesting @sunshine19090 thanks. It should be ultimately hitting the same exact english feed as it normally does. Any thoughts on this @xiam?

**Comment by fffw** [comment]
If the feeds don't include newest articles then it must be some cache thing, either locally or by CloudFlare. Lantern desktop will cache feeds, but only for 5 minutes.

**Comment by myleshorton** [comment]
Caching on CloudFlare should be completely turned off, but we could add a query string as well to make sure. I'll take this one.

**Comment by xiam** [comment]
I think we have a problem with the feeds here as reuters is still included for some reason.

**Comment by xiam** [comment]
I think I deployed and old config.yaml which still had reuters on it, is this still happening @sunshine19090 ?

**Comment by sunshine19090** [comment]
Yes @xiam, it happens only when I change it to language that we don't support. For example, it happens when I change from en-us to zh-hk and also when changing from zh-hk to en-us.

I am using the build version 20160419.165911. Should I download a new one and check?

**Comment by sunshine19090** [comment]
Now the Reuters and the reddit channel appears even without changing languages. @xiam Have you added these channels now in our feeds or it is still a bug?

**Comment by xiam** [comment]
@sunshine19090 I was running a local feed combiner with an old version of the config file (with reuters on it) and that was messing things up... can you check again?

**Comment by fffw** [comment]
@xiam To avoid similar situation from happening again, we can turn `upload` to a command line flag and default to `false`.

**Comment by xiam** [comment]
@sunshine19090 we finally found what was happening here, should be working fine now, can you check?

@fffw the flag sounds good, maybe `-dry-run` could be better since it's more general.

**Comment by fffw** [comment]
@xiam The point is to avoid unintentional harm by making sure the default option do nothing to production environment. One could forget to supply `-dry-run` option during test/debug.

**Comment by sunshine19090** [comment]
Works fine now.
