### ISSUE TITLE
Proxy communications to the pro server over Lantern

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#4039]

**Comment by myleshorton** [comment]
This should generally be happening already right @xiam? I know the CORS stuff is hitting the local server, but isn't everything else already going through Lantern or no?

**Comment by xiam** [comment]
No, we we were using a plain `http.DefaultClient`, so that only happened when Lantern was set as system proxy. This is the related PR that should provide support for tunneling this over Lantern https://github.com/getlantern/lantern-pro/pull/5

**Comment by xiam** [comment]
The PR referred above is now merged.
