### ISSUE TITLE
Lantern Mobile newsfeed Button not centered

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4040]
Just noticed this...
looks like it needs to move right 15dp

<img width="359" alt="screen shot 2016-04-20 at 7 47 56 pm" src="https://cloud.githubusercontent.com/assets/7864729/14693854/dbb20f52-0730-11e6-93ed-3c6a825cab0f.png">
.

**Comment by atavism** [comment]
Thanks, @Derekf5! I just fixed this and sent you an e-mail with the updated version, if you want to take a look.
