### ISSUE TITLE
Error fetching feed: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4044]
I've been seeing this consistently the past few nights, always around the same time (midnight PST). The news feed never loads at all. Assuming this is unrelated, but I recently upgraded to ``go1.6.1`` and ``+e1840f9`` gomobile.

 I'm also seeing the same error as last week (and I experienced this around the same time):
``ERROR balancer: balancer.go:79 Unable to dial server (trusted) chained proxy at xxx:443 []: dial tcp xxx:443: i/o timeout on pass 0...continuing``

**Comment by atavism** [comment]
Now I'm also seeing the same error as last week (and I experienced this around the same time): 

``ERROR balancer: balancer.go:79 Unable to dial server (trusted) chained proxy at xxx:443 []: dial tcp xxx:443: i/o timeout on pass 0...continuing``

**Comment by myleshorton** [comment]
@atavism and @oxtoacart I really think this is the most important thing we're seeing right now, both in Everfeed and Lantern as a whole. If you guys are able to connect tonight, let's also jump on a call tomorrow @oxtoacart if that works and see how we might be able to tackle it.

**Comment by oxtoacart** [comment]
@atavism This seems to have been resolved by the DOS fix, right?

**Comment by atavism** [comment]
@oxtoacart Yes, it appears so. I haven't seen this at all since we deployed the fix.

**Comment by myleshorton** [comment]
Closing
