### ISSUE TITLE
Google Analytics Data for Lantern is missing OS and other client information

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4046]
Google Analytics gets this information from the user-agent, and our Go-based library populates a generic user agent that doesn't provide useful information to Google Analytics.

Things that would be useful to capture:

- Operating System
- Browser (although a user could be using multiple browsers in one session)
- Lantern Version

cc: @myleshorton

**Comment by sunshine19090** [comment]
@oxtoacart @myleshorton Will I be able to test this? If so, can you please provide me the details.

**Comment by myleshorton** [comment]
No it's not testable really @sunshine19090
