### ISSUE TITLE
Mobile - Some descriptions of articles in Chinese show invalid characters

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4049]
For BBC Chinese, there is some decoding issues. In the abstract, some characters are not decoded correct and shown as a questions mark within a square. (It's not a Chinese character, thank you very much )

![image](https://cloud.githubusercontent.com/assets/1143966/14720560/df8abdfa-07b6-11e6-8707-d97ad7f59e10.png)

**Comment by atavism** [comment]
This is an issue on the client side. I'm shortening article summaries to 150 characters, and that must be severing unicode characters towards the end.
