### ISSUE TITLE
Mobile - Lantern crashes when trying to send desktop version via email when there is no network connection

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4054]
![screenshot_2016-04-22-09-15-54](https://cloud.githubusercontent.com/assets/11394369/14747818/44f8722c-086b-11e6-979e-65bdb00c6d10.png)

**Comment by myleshorton** [comment]
What's the status of this one @atavism?

**Comment by atavism** [comment]
Just waiting for @sunshine19090 to verify its fixed

**Comment by sunshine19090** [comment]
Working fine now.
