### ISSUE TITLE
Mobile - Show a spinner while the feed loads

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4057]
In my phone, it takes about 4-5 seconds when I quit and reopen lantern. Meanwhile, I am not even sure if it is going to load or not.

**Comment by atavism** [comment]
Thanks, @sunshine19090. Good idea! Will add it now.

**Comment by atavism** [comment]
Ok, I opened a PR for this [here](https://github.com/getlantern/lantern/pull/4064/files). 

This is what it looks like.. Look good to you, @Derekf5?

![image](https://cloud.githubusercontent.com/assets/6346213/14758154/ce0647de-08b0-11e6-8c2c-2f2d496a5d57.png)

**Comment by Derekf5** [comment]
Yeah looks good @atavism the only think i would do is move the spinner to the middle of that section.

**Comment by sunshine19090** [comment]
@Derek, For me it looks like the spinner is centered but the ON/OFF button is not. But am not sure as I couldn't take a proper pic when it appeared. Please check and close the issue if it looks good to you.


![screenshot_2016-04-27-10-33-22](https://cloud.githubusercontent.com/assets/11394369/14861854/cd0def4c-0c63-11e6-94ae-0dad6a5ec069.png)

**Comment by atavism** [comment]
@sunshine19090 On/off looks off because I sent you a build without [this](https://github.com/getlantern/lantern/pull/4098) merged in. I will send you an updated version

**Comment by sunshine19090** [comment]
Now it looks good @atavism. But I see spinner whenever I open the lantern app on top of the feeds text. The look of the spinner is not so good on top of the text. May be it is just because the spinner is big compared to the text in the background. Will it look better if the spinner is little small? 

Anyway moving this to P3 as this works fine. 

![screenshot_2016-04-27-12-01-26](https://cloud.githubusercontent.com/assets/11394369/14864727/0d178682-0c70-11e6-9981-648af5fb4b42.png)

**Comment by myleshorton** [comment]
Is this one all set then @atavism and @sunshine19090?

**Comment by oxtoacart** [comment]
At this point, the remaining requirement is that when reentering the app and the feeds are already loaded, we shouldn't show a spinner over the existing content.  We should however automatically reload the content as we do today, just not show the spinner.

**Comment by myleshorton** [comment]
What's the status of this @atavism?

**Comment by atavism** [comment]
@myleshorton Showing a spinner while the feed loads is already deployed -- https://github.com/getlantern/lantern/issues/4003 will address the remaining requirement of the spinner not appearing over existing content. I'll mark this deployed and move that other ticket to 2.2.1.

**Comment by myleshorton** [comment]
Cool thanks @atavism

**Comment by sunshine19090** [comment]
This is working fine.
