### ISSUE TITLE
Mobile - Unable to access other blocked apps even when Lantern is turned on

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4060]
Apps like fb, path, twitter opens up and tries to load but only the spinner appears and it looks like never-ending. I waited for 2 mins to make sure.

**Comment by atavism** [comment]
@sunshine19090 I'm unable to re-produce this. I turned Lantern on and browsing with FB & Twitter works fine. Does this happen for you consistently? Could be an issue with the server you're being assigned to. Could you find out the server IP and let me know in Slack?

**Comment by sunshine19090** [comment]
@atavism I am not experiencing this issue in the new build. Closing for now.
