### ISSUE TITLE
Mobile UI - It will be nice if the menu channels background color remains same irrespective of Lantern running or not

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4061]
When Lantern is running, the menu turns blue and turns white when it is not. It will be nice to not change the background color based on Lantern's status.

![screenshot_2016-04-21-14-32-17](https://cloud.githubusercontent.com/assets/11394369/14757256/6466b282-08a6-11e6-8c98-2049a072560a.png)
![screenshot_2016-04-21-14-29-41](https://cloud.githubusercontent.com/assets/11394369/14757257/646c5ee4-08a6-11e6-80f2-1c65e2d0aa33.png)

**Comment by atavism** [comment]
It looks to me like from your screenshot the menu is white when Lantern is turned on and blue when its off though? The feed headers not turning white looks like an issue. When you turn Lantern on, they don't turn white?

**Comment by sunshine19090** [comment]
@atavism I am talking about the channel headers. It changes blue when lantern is turned ON and turns white when lantern is turned OFF. It looked odd to me to change the header colors like that. It is only a suggestion to keep the headers background color to remain the same like white background and black font(like in the second screenshot) even lantern is turned ON.

**Comment by atavism** [comment]
Right, I agree it looks weird. I'm saying the actual issue is that the headers aren't turning white (they're remaining black) after you turn Lantern on.

**Comment by atavism** [comment]
If you close/re-open the app and turn Lantern on, does the text stay black?

**Comment by atavism** [comment]
Here's what it looks like for me: 
![image](https://cloud.githubusercontent.com/assets/6346213/14757609/078a9f16-08aa-11e6-8133-e43c0c6eb16a.png)

**Comment by sunshine19090** [comment]
@atavism In the previous version that I used, the font color changed to black when Lantern turned ON. After installing the new build, the font color remains unchanged. But I still feel that the background color of the headers does not have to change when we turn on/off lantern.
