### ISSUE TITLE
在ubuntu16.04LTS中如何使用lantern

### ISSUE THREAD

**Issue by pokerWu** [getlantern/lantern#4065]
没有16.04版本的lantern，下载14.04的版本无法安装

**Comment by hufan-Akari** [comment]
`dpkg -i lantern-installer-beta-64-bit.deb`

**Comment by louy2** [comment]
如果成功了的话可以来把 Issue 关掉吗？

**Comment by yfszzx** [comment]
ubuntu16.04 32位，安装lantern-installer-beta-32-bit.deb没有报错，但运行lantern显示如下错误:
/usr/lib/lantern/lantern-binary: OK
DEBUG flashlight.ui: ui.go:50 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
DEBUG flashlight.ui: ui.go:50 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(lantern:7977): Gtk-WARNING **: cannot open display:
求指点

**Comment by louy2** [comment]
"Failed to connect to Mir" 中的 Mir 是 Ubuntu 的图形服务。默认的 Lantern 是带图形的，你运行 Lantern 的时候也要在图形界面下才行。如果想要不带图形的 Lantern 需要按[这里的指示](https://github.com/getlantern/lantern#building-lantern-for-running-on-a-server)自行编译。
