### ISSUE TITLE
Got different proxy servers from the config via DDF

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4068]
Mostly happen during peak time.

**Comment by fffw** [comment]
What Lantern want is not a typical usage of CDN, so it may lead to some unexpected effect. While consulting CloudFront docs to understand clearly what it promises, some of the below would help.

1. Having config-server serve on multiple paths, say, "/<device-id>/cloud.yaml.gz". CloudFront may fail to deal with query strings, but should never respond cached content of different path. It does not harm if requests from same device id get cached temporarily.

2. Having config-server add a few fields, such as the X-Forward-For header it sees and the timestamp it handles the request, to the zip file it returns, when responding 200 OK. It helps to troubleshoot at the client side.

**Comment by fffw** [comment]
@myleshorton @oxtoacart @aranhoide Ok response is surely cached by CloudFront. When Lantern got an incorrect server, there's always "X-Cache: Hit from cloudfront" header appeared in the response header. I double checked the code that cache buster is appended to fronted URL. That suggest point 1 above. We can also report error when the cache is hit.

Example below, from the log file I sent to dev:

> Apr 23 13:41:43.570 - 5m16s DEBUG fronted: direct.go:207 Returning connection
> Apr 23 13:41:43.927 - 5m17s DEBUG flashlight.util: http.go:115 Got successful HTTP call!
> Apr 23 13:41:43.927 - 5m17s DEBUG flashlight.util: http.go:140 Fronted request succeeded
> Apr 23 13:41:43.928 - 5m17s DEBUG flashlight.config: fetcher.go:141 Response headers:
> HTTP/1.1 200 OK
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: application/gzip
> Date: ...
> Etag: ...
> Server: ...
> Via: 1.1 vegur, 1.1 ....cloudfront.net (CloudFront)
> X-Amz-Cf-Id: ...
> **X-Cache: Hit from cloudfront**
> X-Lantern-Etag: ...
> 
> 
> Apr 23 13:41:43.928 - 5m17s DEBUG flashlight.config: fetcher.go:156 Fetched cloud config
> Apr 23 13:41:44.533 - 5m17s DEBUG flashlight.config: fetcher.go:76 Merging cloud configuration
> Apr 23 13:41:44.567 - 5m17s DEBUG flashlight.config: fetcher.go:81 Adding 1 chained servers
> Apr 23 13:41:44.567 - 5m17s DEBUG flashlight.config: fetcher.go:81 **Got chained server: \<masked\>:443**
> Apr 23 13:41:44.573 - 5m17s DEBUG yamlconf: yamlconf_disk.go:86 Configuration changed programmatically, saving
> Apr 23 13:41:44.613 - 5m17s DEBUG flashlight: flashlight.go:96 Applying updated configuration

**Comment by oxtoacart** [comment]
Updated CloudFront to pass through querystring.  This seems to have fixed the problem for @fffw.

**Comment by oxtoacart** [comment]
@fffw Great work finding and debugging this!
