### ISSUE TITLE
openSUSE can't be run "make lantern"

### ISSUE THREAD

**Issue by gaovv2000** [getlantern/lantern#4079]
**When i was run command "make lantern" in terminal,return the error message ：**

> _/bin/bash: line 8: npm: command not found
Makefile:191: recipe for target 'src/github.com/getlantern/flashlight/ui/resources.go' failed
make: *** [src/github.com/getlantern/flashlight/ui/resources.go] Error 127_

**and then ,i was copy file  'src/github.com/getlantern/flashlight/ui/resources_stub.go'  to 'resources.go', redo the command "make lantern", return a new error message**

> _Building development lantern
\** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
\# github.com/getlantern/flashlight/ui
src/github.com/getlantern/flashlight/ui/ui.go:59: undefined: Resources
\# pkg-config --cflags gtk+-3.0 appindicator3-0.1
Package appindicator3-0.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `appindicator3-0.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'appindicator3-0.1' found
pkg-config: exit status 1
Makefile:337: recipe for target 'lantern' failed
make: \*** [lantern] Error 2_

**Was I wrong？ what should I do？**

**Comment by houzihz** [comment]
you can use `sudo apt-get install libappindicator3-dev` to resolve the following problem:
> pkg-config --cflags gtk+-3.0 appindicator3-0.1
> Package appindicator3-0.1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `appindicator3-0.1.pc
> to the PKG_CONFIG_PATH environment variable`

**Comment by myleshorton** [comment]
Yeah unfortunately we only currently support ubuntu officially @gaovv2000, but the app indicator thing should be the primary issue if you want to submit a patch!

**Comment by banrieen** [comment]
I have the same trouble,opensuse has installed libgtk3.0, but the appindicator3-0.1 is ubuntu python3.0 API, so I can`t install the Lantern on opensuse ;

Will some one handle it

**Comment by auroua** [comment]
Ubuntu 16.04 have the same trouble.

**Comment by paperplane1230** [comment]
In Ubuntu 16.04, remember to use
`sudo apt-get install libgtk-3-dev`.

**Comment by halu126** [comment]
Package appindicator3-0.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `appindicator3-0.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'appindicator3-0.1' found
pkg-config: exit status 1
make: *** [lantern] Error 2


in centos linux7

**Comment by bearxidian** [comment]
There is a same trouble. @halu126

**Comment by wenbob** [comment]
Fix "No package ..." error:
`sudo apt-get install libgtk-3-dev libappindicator3-dev -y`

I got a problem in raspbian:
```
...
gcc -I . -fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/getlantern/systray/_obj/_all.o $WORK/github.com/getlantern/systray/_obj/_cgo_export.o $WORK/github.com/getlantern/systray/_obj/systray_nonwindows.cgo2.o $WORK/github.com/getlantern/systray/_obj/systray_linux.o -g -O2 -Wl,-r -nostdlib -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_arm/compile -o $WORK/github.com/getlantern/systray.a -trimpath $WORK -p github.com/getlantern/systray -buildid f1af81965eac72b4adfb45cd02a29f7bca3d4e6a -D _/home/pi/lantern/src/github.com/getlantern/systray -I $WORK -I /home/pi/lantern/pkg/linux_arm -pack ./systray.go $WORK/github.com/getlantern/systray/_obj/_cgo_gotypes.go $WORK/github.com/getlantern/systray/_obj/systray_nonwindows.cgo1.go $WORK/github.com/getlantern/systray/_obj/_cgo_import.go
pack r $WORK/github.com/getlantern/systray.a $WORK/github.com/getlantern/systray/_obj/_all.o # internal
Makefile:366: recipe for target 'lantern' failed
```

**Comment by wangmu0579** [comment]
sudo apt-get install libgtk-3-dev libappindicator3-dev
should fix the problem
