### ISSUE TITLE
Chrome UI - Some of the wordings are not translated to Chinese

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4082]
1. Welcome to Lantern! wordings are shown in English.
2. All the words in the footer are in English.
3. The header "All" in lantern feeds is in English. 

In Firefox all these are properly translated.

Firefox:

![image](https://cloud.githubusercontent.com/assets/11394369/14797315/ff50c3a4-0ae6-11e6-9623-0e886a8b66b5.png)

Chrome:

![image](https://cloud.githubusercontent.com/assets/11394369/14797329/13e300a2-0ae7-11e6-92c4-8901877b0786.png)

**Comment by myleshorton** [comment]
Are you seeing this too @fffw?

**Comment by fffw** [comment]
Oh I didn't see it but probably know what's the reason. Will check it tomorrow.

**Comment by fffw** [comment]
@sunshine19090 Could you post Chrome's language settings when you can see the untranslated strings? I tried several combination but still couldn't reproduce.

**Comment by sunshine19090** [comment]
@fffw I am using Chinese and not Chinese Traditional.

**Comment by fffw** [comment]
Thanks @sunshine19090 ! It will be fixed in next QA build.

**Comment by sunshine19090** [comment]
@fffw Is this already in the build 20160428.202307?

**Comment by fffw** [comment]
@sunshine19090 I don't think so. The latest build is not out yet

**Comment by sunshine19090** [comment]
Looks good now.
