### ISSUE TITLE
Use if-modified header for all newsfeed requests on mobile and desktop

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4085]

**Comment by myleshorton** [comment]
@fffw and @atavism this one would probably be worthwhile -- I can also look at it!

**Comment by fffw** [comment]
Browser will send relevant headers when refresh page or open new tab, but won't do so if browser is restarted. Need to persist last fetch time in local storage.

**Comment by myleshorton** [comment]
Oh sweet good point @fffw! So it's just a handy addition for mobile then @atavism.

**Comment by myleshorton** [comment]
I can take this one @atavism

**Comment by myleshorton** [comment]
This one's all set on mobile too. I verified that the internal `https://github.com/koush/ion` library @atavism caches responses when it's possible to do so. While we don't do this for the feed itself, requests for the full feed are rare enough that it doesn't seem necessary.
