### ISSUE TITLE
[desktop] integrate checkout.com

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4090]
Also has alipay integration. It also supports webhooks:

https://www.checkout.com/

**Comment by myleshorton** [comment]
@joesis and @uaalto this looks pretty darn easy:

http://docs.checkout.com/getting-started/checkout-js/charge-via-payment-token

You want to take a stab at just getting this up and running ASAP regardless of whether or not we have an account? Seems like the sandbox examples should hopefully work, then we can hit the ground running as soon as our account is approved.

**Comment by joesis** [comment]
Sure @myleshorton 

FYI @uaalto the pro-server counterpart is at https://github.com/getlantern/lantern-internal/issues/432

**Comment by joesis** [comment]
The example keys are invalid unfortunately, but we can prepare code beforehand.

The rough purchase flow can be as follows:

1. client calls a pro-server endpoint to generate the payment token via checkout.com, based on private key and selected plan.
2. client shows Checkout.js, and having it to process payment.

There're two options for post-payment process:

  3.1 client calls `/purchase` with the `cko-payment-token`, and having pro-server to poll for payment status. Client wait for response to become Pro. Similar to Stripe.

  3.2 pro-server receives event via [the webhook](http://docs.checkout.com/getting-started/webhooks). Client poll pro-server for `/user-data`. Similar to PW.

Option #2 looks simpler overall. cc @uaalto

**Comment by myleshorton** [comment]
Issue moved to [getlantern/lantern-internal #471](https://github.com/getlantern/lantern-internal/issues/471) via [**ZenHub**](https://www.zenhub.com/)

**Comment by p3rcya** [comment]
It no longer works because Alipay is not accepting this kind of payment. We should enable Stripe's Bitcoin payment system ASAP as it's decentralized and cannot be blocked.

**Comment by aranhoide** [comment]
What does no longer work exactly?
