### ISSUE TITLE
Newsfeeds - don't include BuzzFeed in All view

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4093]
Some of the content in BuzzFeed is a little edgy, so to avoid putting off some users with it, let's suppress it from the All feed.

**Comment by oxtoacart** [comment]
@sunshine19090 You should be able to continue seeing BuzzFeed on its own, but none of the BuzzFeed articles should show up in the All feed.

**Comment by xiam** [comment]
That requires a new build, I think.

**Comment by oxtoacart** [comment]
It does.  I was just leaving a testing note for whenever it's ready to test.

This raises an interesting question @xiam and @myleshorton.  How do we track what build something is in so that @sunshine19090 knows what to retest?

**Comment by sunshine19090** [comment]
Looking good!
