### ISSUE TITLE
Change plan or caching rules to cache thumbnails on CloudFlare

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4096]

**Comment by oxtoacart** [comment]
We have HTTPS enabled on CloudFlare for thumbs.getiantem.org, and with that Page Rule enabled, we're not allowed to configure any caching or anything else.

**Comment by oxtoacart** [comment]
Incidentally, given that we're using a self-signed certificate right now, HTTPS to our server doesn't buy us much.

**Comment by myleshorton** [comment]
I'll take this one.

**Comment by oxtoacart** [comment]
@myleshorton Cool.  I'd be curious how you solve it.

**Comment by oxtoacart** [comment]
This may help - http://stackoverflow.com/questions/26827185/control-caching-and-cdn-on-cloudflare-when-ssl-is-forced-on-via-a-page-rule.

Looks like maybe adding a 2nd rule could work.

**Comment by oxtoacart** [comment]
Oh, this is interesting.  Our page rule of "Always Use HTTPS" doesn't tell CloudFlare to talk to the origin server with HTTPS, it tells it to redirect clients that come in on HTTP to switch to HTTPS.  So, I think we're not actually talking to the origin with HTTPS ...

**Comment by oxtoacart** [comment]
@myleshorton I added a 2nd page rule and this seems to be working okay now.  The 2nd page rule also forces Full SSL to the origin server.  It's still somewhat meaningless because we're using a self-signed cert, but it's there.

**Comment by myleshorton** [comment]
Sounds good @oxtoacart. We just have to be careful here that the X-Forwarded-For header is still making it all the way to the config server.

**Comment by oxtoacart** [comment]
@myleshorton I didn't change any sitewide settings, I just added a new page rule that only applies to thumbs.getiantem.org.

**Comment by myleshorton** [comment]
Oh sweet @oxtoacart! I'm going to go ahead and close this then since I don't think it's possible to test in QA.
