### ISSUE TITLE
Add the hub address in bravenewsoftware.org

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4097]
As part of Kaspersky AV whitelisting, we need the address to be displayed somewhere in the website.

**Comment by oxtoacart** [comment]
@myleshorton Is this the right address?

```
830 Traction Ave #3a, Los Angeles, CA 90013
```

**Comment by myleshorton** [comment]
That's it @oxtoacart!

**Comment by oxtoacart** [comment]
@myleshorton If we can knock this out real quick, it would help @sunshine19090 whitelist us with Kaspersky.

**Comment by oxtoacart** [comment]
I just realized I have access, so I'll take care of this :)

**Comment by oxtoacart** [comment]
NM, I don't have access to WordPress.  Working on getting that.

**Comment by oxtoacart** [comment]
@sunshine19090 FYI, this is done.
