### ISSUE TITLE
Formatting Issue on New error page 2.2.0

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4105]
<img width="1440" alt="screen shot 2016-04-27 at 6 10 30 pm" src="https://cloud.githubusercontent.com/assets/7864729/14870668/d0a4fb5a-0ca9-11e6-951a-0c7f829d33e6.png">

The content block below "Oops, something went wrong" needs to be centered.  It is all currently to far left.

**Comment by sunshine19090** [comment]
@Derekf5 @myleshorton  Perhaps we should consider adding "Check your Internet connection" too. I tested with no internet connection to see this page and found that the reasons we specified doesn't make me think that there could be a problem with my connection.

**Comment by fffw** [comment]
List items are better to be left-aligned, so we need to make the content box a bit narrower, so the first line is visually centered.

**Comment by fffw** [comment]
We can also increase the space between "Oops" and the line after it. Larger space would look better in Chinese or probably other languages with shorter text.

![image](https://cloud.githubusercontent.com/assets/10410437/14882620/357609bc-0d6c-11e6-9de6-46b5e8fb63f2.png)

**Comment by myleshorton** [comment]
Yeah @sunshine19090 I think that's a good point, although in an ideal world I think we'd load a cached version of the feed in that case.

**Comment by myleshorton** [comment]
Ok added a little more space per your suggestion @fffw.

**Comment by myleshorton** [comment]
This will be in the next build @sunshine19090

**Comment by sunshine19090** [comment]
Looks good!
