### ISSUE TITLE
On clicking the Try Lantern Android link, the page appears with overlapped text in the background when there is no internet connection.

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4107]
![image](https://cloud.githubusercontent.com/assets/11394369/14875296/2d513576-0cbe-11e6-92ea-12059e28a9ee.png)

**Comment by myleshorton** [comment]
This one's ready to test @sunshine19090

**Comment by sunshine19090** [comment]
@myleshorton Is there any way that I can simulate the case of lantern not working?

**Comment by fffw** [comment]
@sunshine19090 I simulate by disabling my Wifi.

**Comment by fffw** [comment]
@sunshine19090 I simulate by disabling my Wifi.

**Comment by sunshine19090** [comment]
I tried that @fffw but I can see the cached feed now. I guess the self-help will now be displayed only if lantern doesn't work as per @myleshorton previous comment. I downloaded Xunlei but everything is in Chinese so I ended up not installing. Any other ways to simulate this scenario?

**Comment by fffw** [comment]
@sunshine19090 Next QA build will show the error page very soon if network is disabled. For now, you can open Lantern in Incognito window to avoid caching.

**Comment by sunshine19090** [comment]
@myleshorton I still see the error page after disconnecting the network instead of the cached feed. Is this really ready to test? or need a new build?

**Comment by sunshine19090** [comment]
oh, I read the wrong ticket. Sorry @myleshorton. This one is good now.
