### ISSUE TITLE
Articles in Chinese feed are mixed up

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4108]
I see Jandan.net, theinitium.com, chinadigitaltimes.com under a single channel and all other channels are also mixed up.

![image](https://cloud.githubusercontent.com/assets/11394369/14875760/c60c4b76-0cc2-11e6-83f0-ecff25093bbd.png)

**Comment by sunshine19090** [comment]
The english feed is also being affected when I change my Language settings from Chinese to English(US).

![image](https://cloud.githubusercontent.com/assets/11394369/14875785/121f1f52-0cc3-11e6-96ff-5450d1991be0.png)

**Comment by xiam** [comment]
Could not find any problem with feeds from desktop, is this issue reproducible?

**Comment by sunshine19090** [comment]
I was able to reproduce it twice yesterday. I will try it again today @xiam. 

Regards,
Sunshine

**Comment by xiam** [comment]
I finally ran into this problem, this is a client's caching issue that goes away when `localStorage` is cleared or the cache is emptied. Don't know how to reproduce it at will, any clues @fffw?

**Comment by myleshorton** [comment]
I'll grab this one guys.

**Comment by sunshine19090** [comment]
Working fine now.
