### ISSUE TITLE
Mobile - The abstract says "reddit: the front page of the internet" for almost all the articles in reddit

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4109]
Also some of the articles missing the image.

![screenshot_2016-04-27-21-41-58](https://cloud.githubusercontent.com/assets/11394369/14875849/da42fa12-0cc3-11e6-93d8-08fe13af5cd9.png)

**Comment by atavism** [comment]
@xiam @fffw Is this also an issue on desktop, or are we using a different field for article description for the reddit feed? I'm using the ``meta["description"]`` and ``contentText``. Should I use something else for reddit?

**Comment by fffw** [comment]
@atavism It's the same on desktop. There's no field containing any meaningful abstracts in feeds.json. It's not surprising as most Reddit pages are not articles at all. They are just links with discussion threads.

**Comment by xiam** [comment]
That's right, see this for instance: https://www.reddit.com/r/television/comments/4grxte/netflix_to_traumatize_whole_new_generation_with/

We don't have any "article content" there.

**Comment by xiam** [comment]
I am now manually removing those descriptions.

**Comment by sunshine19090** [comment]
@xiam @atavism Looks good in desktop. In Mobile, I still see that some of them has abstract that doesn't make sense. Screenshot attached.
![screenshot_2016-04-28-13-10-12](https://cloud.githubusercontent.com/assets/11394369/14899897/11565a38-0d43-11e6-89ef-1cb6a56b853b.png)

**Comment by myleshorton** [comment]
Is this still an issue @sunshine19090 and @atavism?

**Comment by atavism** [comment]
@myleshorton Looks like there's a super tiny discrepancy between desktop and mobile that's causing this. We're using the ``contentText`` instead of ``contentSnippetText`` when a meta description is missing. The latter field is the one the feed service updates. I fixed this [here](https://github.com/getlantern/lantern/pull/4181)

**Comment by sunshine19090** [comment]
@myleshorton I don't see any change. Looks same.

![screenshot_2016-05-02-21-52-12](https://cloud.githubusercontent.com/assets/11394369/14975075/b8340306-10b2-11e6-85e7-ef089a300911.png)

**Comment by sunshine19090** [comment]
Looks good now.
