### ISSUE TITLE
Put manoto news first in persian feed

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4117]

**Comment by xiam** [comment]
Hey @fffw, @atavism,

I've added a new `sorted_feeds` entry that contains the keys of the feeds object, but sorted:

![screen shot 2016-04-28 at 12 11 04 pm](https://cloud.githubusercontent.com/assets/385670/14894854/5347922a-0d3b-11e6-9c5c-7f68ace9ed6b.png)

Let me know if this change fits you, other options could be changing the feeds object into an array or add a new field "order_id" on feeds so you can use it to sort it client-side.

**Comment by myleshorton** [comment]
Can you take a look at this @fffw?

**Comment by sunshine19090** [comment]
Manoto is in the last.

![image](https://cloud.githubusercontent.com/assets/11394369/14933813/8afda9b0-0e4f-11e6-9dd4-147b2b67503e.png)

**Comment by fffw** [comment]
@sunshine19090 It's merged but the QA build is not sent out yet.
