### ISSUE TITLE
Each article is repeated twice in Jandan.net feed in both mobile and desktop

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4135]
![image](https://cloud.githubusercontent.com/assets/11394369/14897965/3f5586fc-0d39-11e6-9768-a5d953147e00.png)

**Comment by xiam** [comment]
Thanks, good finding. Confirmed on feed-combiner side.

**Comment by xiam** [comment]
Should be fixed now.

**Comment by sunshine19090** [comment]
yep, am seeing just one entry now.
