### ISSUE TITLE
Mobile - BBC chinese feed is blank

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4136]
It is working fine in desktop.

**Comment by atavism** [comment]
It's showing up for me. It's just totally blank for you?

![image](https://cloud.githubusercontent.com/assets/6346213/14898187/71cc471e-0d3a-11e6-9786-412b3d2692d7.png)

**Comment by sunshine19090** [comment]
It was like in the screenshot. I came across the same issue when I changed the language back to English feed but it went away after closing and reopening the app. 

![screenshot_2016-04-28-12-05-14](https://cloud.githubusercontent.com/assets/11394369/14898289/df3ad4b4-0d3a-11e6-9742-02f3b3c59b80.png)

**Comment by sunshine19090** [comment]
@atavism I was trying to reproduce in the chinese feed and this time all were blank except for one feed at the end. Also, I didn't see the spinner when it took time to load. After quitting and reopening, I was able to see them again and the spinner too.

**Comment by myleshorton** [comment]
Just a guess, but maybe just switching the language itself doesn't trigger a reload of the feed @atavism? If so that would be more of an issue in testing environments than in real world use.

**Comment by myleshorton** [comment]
Is this one still an issue @sunshine19090 and @atavism?

**Comment by atavism** [comment]
@myleshorton I opened a PR for this here: https://github.com/getlantern/lantern/pull/4176/files

**Comment by sunshine19090** [comment]
This is good now.
