### ISSUE TITLE
A pop-up and a screen needs translation in Chinese

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4141]
![screenshot_2016-04-28-12-32-30](https://cloud.githubusercontent.com/assets/11394369/14899542/6175ddd8-0d41-11e6-9a1b-9e34871d4d98.png)
![screenshot_2016-04-28-12-32-08](https://cloud.githubusercontent.com/assets/11394369/14899541/61733c18-0d41-11e6-8616-e2580980afbf.png)

**Comment by atavism** [comment]
These strings were never added to Transifex. I just did that and will open a PR once the new translations are available (@Derekf5, if you want to ping our translators about it?)

**Comment by Derekf5** [comment]
sure thing @atavism

**Comment by atavism** [comment]
This should be resolved with https://github.com/getlantern/lantern/pull/4150
