### ISSUE TITLE
Use cached feed if there's no network connection

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4143]

**Comment by myleshorton** [comment]
Ha! This should actually be fixed as a bi-product of the fix for #4108

**Comment by myleshorton** [comment]
There was a regression with this one -- see https://github.com/getlantern/lantern/issues/4107

**Comment by fffw** [comment]
I'm still confused @myleshorton . Wouldn't it be more natural to show error page if there's a network issue? Why bother showing cached feed if the article links can't be open?

**Comment by myleshorton** [comment]
Yeah good question. To me the answer is that not having an internet
connection is a normal thing, so Lantern should not show an error for
something normal like that. The problem is we'll be unlikely to ever show
the error page now, but maybe that's how it should be? The extension should
be useful for detecting real issues in a more fine grained way as well.
On May 3, 2016 6:39 PM, "fffw" <notifications@github.com> wrote:

I'm still confused @myleshorton <https://github.com/myleshorton> . Wouldn't
it be more natural to show error page if there's a network issue? Why
bother showing cached feed if the article links can't be open?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/getlantern/lantern/issues/4143#issuecomment-216717729>

**Comment by fffw** [comment]
If user knows that network is unavailable, she will unlikely open Lantern page, but if it's due to some subtle condition, e.g., PPPoE disconnected or bad network quality, or misconfiguration, user won't notice it and blame Lantern. We can just add an list item asking user to check network connectivity .
