### ISSUE TITLE
After changing the language to Persian in chrome, lantern is not loading the feeds

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4144]
I am seeing only the spinner.

![image](https://cloud.githubusercontent.com/assets/11394369/14900078/c7260016-0d43-11e6-94c2-4cabb733ea13.png)

**Comment by myleshorton** [comment]
And you refreshed the page right @sunshine19090? This is working for me on OSX.

**Comment by sunshine19090** [comment]
Oh, this is in Windows 7 @myleshorton . I did refresh the page. I even tried quitting the browser. I didn't check in Mac yet.

**Comment by sunshine19090** [comment]
Now the feeds are loading in Chrome in windows 7.
