### ISSUE TITLE
Persian language - Date on the articles for the iranwire.com are Dec 31,1

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4145]
![image](https://cloud.githubusercontent.com/assets/11394369/14900177/29af34f0-0d44-11e6-80b0-b517ec1fc609.png)

**Comment by myleshorton** [comment]
Let's just leave out the date if there's no date field @fffw

**Comment by xiam** [comment]
The `publishedDate` field is now completely removed when invalid, @fffw  and @atavism.

**Comment by sunshine19090** [comment]
It shows "null" now in the place of Date.

![image](https://cloud.githubusercontent.com/assets/11394369/14933804/4cca4da6-0e4f-11e6-8270-8caa6438d138.png)

**Comment by fffw** [comment]
@sunshine19090 QA build is not sent out yet

**Comment by sunshine19090** [comment]
looks good now.

**Comment by sunshine19090** [comment]
It shows null in Chrome, Windows 7.  It looks good in FF.

![image](https://cloud.githubusercontent.com/assets/11394369/14966632/522a2986-1068-11e6-82fb-cf833d1b1a65.png)

**Comment by fffw** [comment]
Attached is what I saw with the same version. @sunshine19090 I wonder if refreshing the page or a forced refresh (Ctrl + Shift + F5), or restarting browser would show the updated UI. 

 If simply refreshing page doesn't work, we may add something like https://www.npmjs.com/package/gulp-angular-templatecache to solve it and reduce roundtrips.

![image](https://cloud.githubusercontent.com/assets/10410437/14972206/5890685e-110c-11e6-9c20-c97f4d42246f.png)

**Comment by sunshine19090** [comment]
Yes @fffw, after refreshing I don't see the null value.
