### ISSUE TITLE
Translate the self help page in Chinese and Persian

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4147]
1. Self-help page.
2. The new link to switch between the feeds and the old look

**Comment by fffw** [comment]
Chinese translation is in Transifex. Asked help to translate Persian.

**Comment by sunshine19090** [comment]
I am not seeing any changes. 

![image](https://cloud.githubusercontent.com/assets/11394369/15407094/25054d38-1dbe-11e6-9f04-df07c38ee71b.png)

**Comment by fffw** [comment]
Oops, there are even a few new strings not in Transifex! I just pushed them. The translations of errors page are ready. Will wait for new translations and merge in batch.
