### ISSUE TITLE
image href problem with iranwire.com

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4148]
Looks like the URL just might be wrong. Here's the dev console:

![image](https://cloud.githubusercontent.com/assets/1143966/14901316/928475ee-0d49-11e6-89b0-f09b710bb7b9.png)

**Comment by xiam** [comment]
@fffw This is caused by iranwire's feed, they include images like:

![screen shot 2016-04-28 at 5 13 51 pm](https://cloud.githubusercontent.com/assets/385670/14903135/bba79b7a-0d64-11e6-97d1-d1c40402421f.png)

Since mobile is using `contentText`/`contentSnippetText` instead of the HTMLy `content`/`contentSnippet` could we use the same on desktop?

**Comment by fffw** [comment]
Sure I can switch to use `contentText/contentSnippetText` to avoid the console errors. The actual issue is an empty `image` or `imageSquare` field. I guess it's absent in RSS/ATOM right @xiam ?

**Comment by xiam** [comment]
@fffw I am seeing many `image`/`imageSquare` links filled up on this iranwire feed but I can check a particular entry if you want. Just to make sure, when those fields are empty the thumbnail is not supposed to be shown, right?

**Comment by fffw** [comment]
@xiam It's dw.com that lacks image links. If image link is empty, the whole thumbnail area is hidden on desktop.

**Comment by xiam** [comment]
Right @fffw! I renamed the issue, dw.com is not the origin of the problem described above, iranwire.com is. dw.com does not have images and that's because I am removing them by hand, which is something we want to do because dw.com images are repeated for some reason.

**Comment by sunshine19090** [comment]
@fffw @xiam I don't see images in dw.com. I don't understand the underlying problem with iranwire.com. Can you please explain what I am supposed to test?

**Comment by xiam** [comment]
@sunshine19090 dw.com images were removed on purpose, so that's OK. The problem with iranwire.com is that it was displaying bad images on the article's entry. After this change you should not see any images within an article entry, only text.

**Comment by sunshine19090** [comment]
This looks good now.
