### ISSUE TITLE
Show the feed name in each article of "All" tab

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4149]
Currently site domain is shown

**Comment by sunshine19090** [comment]
@fffw  Is this about introducing the feed name in the mobile alone? because we already showing it in desktop.

**Comment by fffw** [comment]
@sunshine19090 It's to replace the site url shown before the publish date
to the feed's title, e.g. Reddit for www.reddit.com

**Comment by sunshine19090** [comment]
Looks good now.
