### ISSUE TITLE
Specific sites have issues loading

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#415]
bittorrent.com
bloomberg.com
whatismyip.com
http://canyu.org/
chinainperspective.com
chinasmile.net
discuss.com.hk
dw.de
enghelabe-eslami.com
...
likely many more sites on the whitelist...that's just as far as we got!

All those periodically freeze up when loading in get mode. I believe all of these go through LAE proxy, and my guess it is has something to do with not following connection close rules correctly.

**Comment by qmhedging** [comment]
can not link to http://www.bloomberg.com again, please check
