### ISSUE TITLE
Use consistent word for 'email'

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4158]
From our great French translation coordinator.

> Across Lantern Transifex resources, we have 9 instances of "e-mail", and over 40 instances (for all resources) of "email". IMO the 9 should be corrected to "email".
> 
> In Lantern UI:
> 
> > key: LANTERN_MOBILE_ENTER_VALID_EMAIL
> 
> Unless we have a strict character limit (in which case it should be stated in the dev's instructions field), this should read "Please enter a valid e-mail address"

Put it to Pro milestone to have a fresh start. We should also check other inconsistent words.

**Comment by myleshorton** [comment]
I believe we do this with the new UI
