### ISSUE TITLE
HOW TO USE LANTERN IN Qubes OS? 

### ISSUE THREAD

**Issue by c12805** [getlantern/lantern#4159]
IN ORDER TO BE ANONYMOUS,HOW TO USE LANTERN IN Qubes OS WHONIX,I WANT USE LANTERN IN Qubes  OS Proxy VM,and the network is :sys-net ->sys-firewall->my Proxy VM->sys-whonix->anon-whonix.BUT sys-whonix can not connect my Proxy,i set up Lantern in my Proxy VM.HOW TO ACHIEVE THIS GOAL?Please help me ,if probably,write some tutorials for the public,especially to the newbie

**Comment by xiam** [comment]
Hey @c12805, we might experiment with Qubes OS in the future but we don't have any immediate plans to do so.

Please don't use Lantern as an anonymity tool:

> Lantern is not an anonymity tool. Lantern was built for fast and open Internet access. If you feel you need to be anonymous online (if you are posting something you think could bring legal action against you, for example) we recommend using Tor. Otherwise, Lantern will give you faster access to blocked sites.
