### ISSUE TITLE
Respect HTTP client caching in Mobile everfeed client

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4161]
We're setting pretty aggressive cache headers for images, but right now the Go-based mobile client doesn't respect them.  We could improve performance and dramatically reduce mobile bandwidth consumption by respecting them, especially considering that we reload the feeds every time someone comes back into the app.

This library may help - https://github.com/gregjones/httpcache

cc: @atavism @myleshorton

**Comment by atavism** [comment]
Cool, we are using https://github.com/koush/ion to handle the image caching already but this would be a useful change regardless!

**Comment by oxtoacart** [comment]
Oh, cool @atavism!  The Go client doesn't load the images, duh!  I think that's plenty good.
