### ISSUE TITLE
Add hash of binary to analytics

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4164]
This will help us verify if a lot of the Lantern users we're seeing in analytics are using versions we've built.

**Comment by oxtoacart** [comment]
The hash can be faked, so I think it's simpler (and more readable) to just have the client report its version.

**Comment by myleshorton** [comment]
Adding the Lantern version is ticketed at #4078. Both can be faked, of course.

**Comment by oxtoacart** [comment]
@myleshorton Cool.  For clarity, are you talking about generating the hash at runtime and submitting that, or grabbing the hash at build time and baking that into the binary itself?

**Comment by myleshorton** [comment]
I was talking about doing it at runtime @oxtoacart

**Comment by oxtoacart** [comment]
@myleshorton Okay, cool, that seems useful in case someone is just slightly tweaking our binaries.

**Comment by myleshorton** [comment]
Yeah or massively tweaking!

**Comment by fffw** [comment]
I'm wondering if it's useful to check the executable's signature, though there's not existing go lib to do so.

Reference: [Windows](https://support.microsoft.com/en-us/kb/323809), [OSX](http://stackoverflow.com/questions/1815506/how-to-obtain-codesigned-application-certificate-info)
