### ISSUE TITLE
End-to-End Monitoring Phase 2 - Chrome Extension MVP

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4169]
Following on to #4168, we will make a Chrome extension available that users can use to provide instant feedback on how well Lantern is working for them.  The extension will be as simple as we can possibly make it and provide the feedback to our monitoring system in the form of a scalar value that can be used for analysis.  The exact design should be determined in coordination with @Derekf5, but here's an example of the form that the extension could take:
- The extension icon changes shape/color/etc to indicate whether the current page is being proxied by Lantern
- Clicking on the extension reveals a small panel that prompts the user to rate how Lantern worked for this page, including the options "Perfect", "Broken", "Slow", "Completely Blocked" and "N/A" or something like that.
- If the extension detects that proxying seemed to fail for some reason, perhaps it proactively notifies the user and asks for feedback.
- The extension should include mechanisms to avoid overwhelming the user with requests for feedback

When reporting the user's feedback, the extension should include additional information that it can collect, for example:
- Is Lantern running?
- Is Lantern set as the system proxy?
- Is another extension overriding the system proxy settings and if so, which extension?

The extension should attempt to use the Lantern client to submit its reports, but it should fall back to using direct domain-fronting if the Lantern client is unable to submit for some reason.

**Comment by oxtoacart** [comment]
cc: @fffw @aranhoide @myleshorton

**Comment by myleshorton** [comment]
The extension could also automatically submit logs in theory.

**Comment by oxtoacart** [comment]
@myleshorton yes, the extension could automatically submit information, but we wanted to keep it simple for the MVP.  @aranhoide's suggestion of getting user feedback seems really powerful, as that's ultimately what we're trying to understand.  Given that Phase I gives us some useful automatically submitted telemetry that we can correlate with the user's feedback, I think there's potentially already a lot of value here without making the extension's code to complex.

**Comment by WolfLantern** [comment]
this is cool guys. @myleshorton auto idea is very cool too

**Comment by myleshorton** [comment]
Closing for now, although all of this is very relevant for any extension we ultimately provide, if any.
