### ISSUE TITLE
Create data collection server to front InfluxDB

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4170]
This should speak HTTP(S) to allow direct domain fronting.

Perhaps we can mimic the InfluxDB interface or even talk to it directly, but estimate is based on putting a layer in front of it.

**Comment by oxtoacart** [comment]
I'd estimate 8 or 13 story points for this, including building unit tests, getting it deployed and secured.

**Comment by myleshorton** [comment]
Hey it strikes me this could be a great use of gRPC @oxtoacart, especially the requirement to support an HTTP API for domain fronting from the client. That way other servers could just speak straight grpc to the server!

**Comment by oxtoacart** [comment]
I'll give it a shot!



-- 
Cheers,
Ox

PGP Key - https://pgp.mit.edu/pks/lookup?op=get&search=ox@getlantern.org

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by myleshorton** [comment]
Nice! Super curious to see what you think.

**Comment by myleshorton** [comment]
Will have the very cool property of allowing us to efficiently log from any server in any language (or many at least), all over PB.

**Comment by oxtoacart** [comment]
@myleshorton I started looking at gRPC and it looks like right now it only supports protocol buffers.  As discussed, we're trying to keep the layer around InfluxDB pretty light, and that particular data format is loosely typed (more like JSON), and @uaalto and I were planning to take advantage of that to send in arbitrary metadata.  I see that protocol buffers supports a map type, but it looks like that type doesn't support polymorphic values the way that JSON does.  Other than defining one map per data type (e.g. mapOfStrings, mapOfInts, mapOfFloats, etc.), do you know of a way to accommodate this with Protocol Buffers/gRPC?

**Comment by myleshorton** [comment]
Hey @oxtoacart! It seems like there are a few options here. First, it's very easy to add new values to PB messages in a backwards and forwards-compatible way. See, for example:

https://developers.google.com/protocol-buffers/docs/proto3#updating

That does require any those new fields to the .proto file and re-generating the code, but if any new value is going to be useful it also needs to be interpreted *somewhere*, so to some extent to me you might as well just define it in the .proto file and run the code-generation step because it takes no time. In that case, you also don't need to update the client or the server right away because they'll both still understand the old and the new messages. If you don't want to get into interpreting that data on the server, the server side could just effectively treat it as JSON-like in the sense that it could just convert types to their InfluxDB equivalent in the same way it would for JSON.

Another option would be to just enter strings or byte arrays into the map and to handle the typing on whatever end needs the typing.

**Comment by myleshorton** [comment]
Actually, when PB3 does JSON conversion, it uses that last technique -- converts all map values to strings:

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by myleshorton** [comment]
The any type is also interesting:

https://developers.google.com/protocol-buffers/docs/proto3#any

**Comment by oxtoacart** [comment]
Thanks for the tips @myleshorton!

I'm trying to build the service to be as agnostic as possible to the content of the messages.  Here's the idea:

client -> data collection server -> influxdb -> grafana queries (or other queries against influxdb)

The data model in influxdb is dynamically typed and so is the query language.  All the data collection server does is provide security, load balancing and potentially pre-downsampling of data prior to sending it to InfluxDB if that's needed to protect performance.  Adding static types for the messages just seems to add complexity and creates a need to constantly redeploy the data collection server and deal with potentially tricky API versioning issues.

I took a look at the any type, but doesn't seem to support scalar values, just message types, which isn't really what I need.

TBH I'm leaning towards JSON to RESTful services over HTTP.  Go already transparently supports HTTP/2 when using TLS connections as of Go 1.6, so that should help with overhead.  If the JSON overhead turns out to be too much, we can add support for the "application/x-msgpack" content-type and encode with Message Pack, which is very efficient and has basically the same API as JSON (namely, we represent the data as a map[string]interface{}).

For the use case at hand, what's the big thing that we would lose by not using gRPC + protobuf?

**Comment by myleshorton** [comment]
If want you want is no static typing what about the map of strings?

**Comment by oxtoacart** [comment]
I want dynamic typing like JSON, where values have runtime type information.  If we use strings, we have to figure out how to encode the information ourselves.  I'd rather use a serialization library that handles that for me.

**Comment by myleshorton** [comment]
Hey sorry I would just go with whatever works best then!

**Comment by oxtoacart** [comment]
@myleshorton gRPC sounds interesting, so I'm genuinely trying to figure out if there's a way we can try it out.  Theoretically it supports other encodings, not just protocol buffers, but I haven't figured out how/where to plug that in yet.  The other concern I have is how we would do this through CloudFront, since we need to be able to front requests to the server.  We could use the REST adapter, but then we're either just sending everything over REST anyway, or have the client follow two different paths depending on whether it's using a chained or domain-fronted server.

For now, I'm going to start with just JSON over HTTP to keep it simple, and see how it goes.

**Comment by oxtoacart** [comment]
@uaalto As I'm starting work on the server side of this and better understand InfluxDB, I'm realizing that the model you and I discussed won't quite work.  Here's a [first cut](https://github.com/getlantern/borda/blob/master/borda.go#L7) at what I think we should do. Not surprisingly, it actually ends up being very similar to the statshub data model that we used to use.

Rather than the whole thing just being a map of key/value pairs, this model makes a few distinctions, which is driven by two needs.

1. The data collection server needs to be able to downsample intelligently when we want to reduce load on InfluxDB. To do this, it needs to know the difference between numeric measurements and metadata  about those measurements (a.k.a. dimensions).  It also needs to know the difference between increments and regular counters so that it can aggregate increments rather than just taking the most recent value.

2. The server needs to be able to distinguish between indexed and unindexed dimensions to know where to store these in InfluxDB.  This distinction is important because we need to manage the tradeoff between being able to quickly query certain things and not blowing out the size of the database too much.  See [InfluxDB Schema Design](https://docs.influxdata.com/influxdb/v0.12/concepts/schema_and_data_layout/) for more discussion.

**Comment by oxtoacart** [comment]
@uaalto Actually, forget what I said about downsampling - InfluxDB can do that better than us, so I won't downsample in the collector.

**Comment by uaalto** [comment]
While I see the need to differentiate data so we know how to deal with it and perform things like aggregation, I think embedding each one of those qualities as different types is inflexible. I think it would be more elegant and extensible to use a model like:

```
{
 Key string,
 Timestamp time,
 [ Val {data interface{}, typeID int, tags [tagIDs...]}
  ...]
}
```
This would be a similar approach to what dynamic languages do: leaving the knowledge of the type for runtime. This way the model is simpler and extensible, at the cost of slightly lower performance (but probably fewer data transferred because we won't need to send empty fields in the JSON, but this would be minor).

By the way, we will be also doing some aggregation and downsampling in the client, to reduce the number requests.

**Comment by uaalto** [comment]
Those "tags" would identify things like Gauges, Unindexed...
And they could be combined, so we don't need UnindexedGauge ever in the struct (I know this combo doesn't make sense, but just to illustrate the point).

**Comment by oxtoacart** [comment]
@uaalto what is the reason for including the type id?

**Comment by oxtoacart** [comment]
BTW @uaalto, I simplified the model quite a bit since we don't need to downsample in the app - what do you think of it now?

**Comment by uaalto** [comment]
This last version looks much better to me, because it is more general and abstract. 
With the type id, you can have only one map (Values) and decide whether it is a dimension, a value, or any other concept we want to add, like out-of-band. I'm just advocating for a general and open model, more than trying to figure out a static interface client/server for this.

**Comment by oxtoacart** [comment]
@uaalto Gotcha.  Will this latest model for the server API work for you?

**Comment by uaalto** [comment]
Yes we can work with that

**Comment by oxtoacart** [comment]
@uaalto I simplified the model even further.  Clients shouldn't have to know which dimensions are indexed and which are not, so I'm making that part of the server's configuration.

cc: @fffw

**Comment by oxtoacart** [comment]
@fffw @uaalto @myleshorton Here is an initial integration test using InfluxDB that demonstrates how I imagine real metrics will work - https://github.com/getlantern/borda/blob/master/borda_integration_test.go

Some important things to note:

* All measurements go to the same key `health`.  Because InfluxDB doesn't allow joins, I believe that this is the only way that we can actually correlate different measurements like client errors to proxy errors to proxy load_avg.

* The interesting query logic happens in two places.
  1. [Downsampling and continuous queries](https://github.com/getlantern/borda/blob/master/create_database.sh#L10) do some initial aggregation
  2. [Additional queries](https://github.com/getlantern/borda/blob/master/query.sh) can then be run on the downsampled data to gain further insights

**Comment by oxtoacart** [comment]
Okay, I've made the simulation of errors much more comprehensive.  It will run for several minutes, but it gives richer data.

After running it, you can play with the data in the influxdb shell.  For example, you could find the 95th percentile client error rate and then get data for all proxies that fall at the 95th percentile and above. You'll notice in this example that all these proxies have a high load_avg, which in the simulation triggers connection errors in clients.

```sql
> select percentile(client_error_rate, 95) from "default".proxy_1m;
name: proxy_1m
--------------
time	percentile
0	0.3231685944619699

> select * from "default".proxy_1m where client_error_rate >= 0.3231685944619699;
name: proxy_1m
--------------
time			client_error_count	client_error_rate	client_success_count	dim_proxy	load_avg		proxy_error_count	proxy_success_rate
1462760820000000000	893			0.3271062271062271	2730			43.25.23.16	0.9995905936084938	351			0.12857142857142856
1462760820000000000	923			0.3252290345313601	2838			43.25.23.17	0.999994412146054	386			0.13601127554615927
1462760820000000000	922			0.3231685944619699	2853			43.25.23.0	0.9999667529425635	355			0.1244304241149667
```

**Comment by fffw** [comment]
@oxtoacart It feels to me that client library should know the dimensions anyway to pre-aggragate, so configuring indexed dimensions on server is unnecessary. The collection server should be thin enough to avoid configuring anything related to Lantern. I still reserve my opinion that if the purpose is to provide security and load balancing, InfluxDB already handled it very well, and [line protocol](https://docs.influxdata.com/influxdb/v0.12/write_protocols/line/) is concise and simple enough that if we do want to switch to another DB, only <100 lines of code is required to parse it.

Back to the schema design. As long as we have required data, we can do any join, aggregation, calculation, etc. It's pretty much like the data warehousing scenario that ETL and reporting are separated tasks, and use fact tables as connect points. I already have Kapacitor set up to [provide alerts for Heroku services](https://github.com/getlantern/misc/tree/master/kapacitor) so it won't be a blocker. If the collector can write to DB with clean schema in time/storage efficient manner, any reports can be derived afterwards.

If Lantern client only reports those problematic request_id (what it is expected to do), we can join them with the full list from proxy server in short interval, the result cardinality would be manageable. IMHO we can postpone it until the requirement from support field rises.

**Comment by uaalto** [comment]
The client can handle the events with a completely separate abstraction to InfluxDB. We don't need to know about the InfluxDB until the time to send it to the server frontend. We can handle aggregation at will in the client, without relying on concepts from InfluxDB.
What I mean by this is that I think is best to imagine event series sent from the client in whichever format and API you consider best, and the client should be able to adapt. Also, the data should be formed as we need in the last step of the client, when it is converted to be sent to our Influx fronter.
The primary reason for this is so we can use this library with other database backends too, not just with InfluxDB, and not only for client measurements, but for proxy measurements too.

**Comment by oxtoacart** [comment]
@uaalto I agree

@fffw The thing that I like about having the data available for correlation directly in InfluxDB is that it makes data exploration through the Influx shell really easy, as in the example that I gave.  The InfluxDB team even recommends putting multiple things in a single measurement if you need to correlate them - see [here](https://groups.google.com/forum/#!msg/influxdb/pVgl8mhoV2g/4mPMgoX7CQAJ) and "Don't differentiate with measurement names" in [here](https://docs.influxdata.com/influxdb/v0.12/concepts/schema_and_data_layout/).

Having a data collection server is already coming in handy because I can use it to do things like make dimensional values available both in a tag like `dim_mymeasurement` and a corresponding field like `mymeasurement` without the client having to worry about that.  This is useful because only tags can be used for grouping, but only fields can be used for aggregation.  Being able to define our own schema conventions with tricks like this will probably come in handy in the future too.

**Comment by uaalto** [comment]
@oxtoacart Looking at Measurement I think the current design is the cleanest and simplest. I like it better :)
One detail I'd suggest is naming it something more general than Measurement, although is not bad abstraction name either. Is this a concept of Influx or something that you see reflecting the notion of an "error supercharged with context" it well in English?

**Comment by oxtoacart** [comment]
@uaalto Measurement happens to be the term that InfluxDB uses, but I'm open to suggestions for more general names.  Measurements are not just errors, they're also metrics about servers like load_avg.  The thing that does unify Measurements is that they all have some quantitative component (e.g. count of errors, load_avg, amount of disk free, etc.) and they are time-based.  Without the quantitative and time components, InfluxDB would be the wrong place to store these.

**Comment by oxtoacart** [comment]
BTW @fffw @uaalto the reason that I think it's important to configure dimensions/tags on the server is that they have a big performance impact.  For example, I originally thought I wanted request_id to be a tag, but in practice its cardinality is too high and it would blow out our database.  If we were dependent on the client to control this, it would take us longer to fix such problems because we have to roll out new clients, plus we don't have full control, old/misbehaved clients could continue to make request_id a tag and bring our database to its knees.

**Comment by uaalto** [comment]
Naming is complicated. I'm pointing to this as the primary abstraction of the system. That Influx uses Measurement is not necessarily bad, on the contrary, it might represent the concept well enough because Influx aims at solving a problem very close to ours.
We can leave it as Measurement!

**Comment by oxtoacart** [comment]
Cool, we'll stick with that.  Is `borda` an okay name for the library/server?

**Comment by uaalto** [comment]
I need to know more of Influx to have an opinion on your last comment @oxtoacart. But what I can understand from it, the problem seems to be very close to how Influx is, so it might be better to solve it closer to the database. In other words, in "abstract" I see what you mean and I agree.

**Comment by uaalto** [comment]
Re: borda. Mathematician and Sailor. Fits well!

**Comment by oxtoacart** [comment]
@uaalto InfluxDB is a time-series database.  Like all databases, it optimizes for a particular problem.  The problem that InfluxDB optimizes for is having a large number of measurements with the same/similar dimensions (e.g. tags) that come in over time and being able to query those measurements using time-based queries (e.g. calculating rates, etc.).

**Comment by uaalto** [comment]
And with many fields having high cardinality it can't optimize well. Is that correct?

**Comment by oxtoacart** [comment]
@uaalto Yes.  Every unique combination of tags results in what InfluxDB calls a series.  There is overhead associated with series, and the number of series is one of the key [sizing](https://docs.influxdata.com/influxdb/v0.12/guides/hardware_sizing/) parameters.  By tracking every client, we automatically fall into the large sizing category of > 1 million series.  Of course our write and query rates could be much lower due to our pre-aggregation.

As mentioned in the original design, we won't start by tracking all clients, just a small percentage (perhaps even as small as 0.1%  ?).  This will give us some real data to play with, understand, tweak our schema design and data collection and then start rolling out to more clients.

**Comment by oxtoacart** [comment]
@fffw and I ran an experiment and confirmed that the total number of series is the same whether we store measurements separately or under one combined table, so we'll store them under one combined table to take advantage of the joining capability.
