### ISSUE TITLE
At important points in the Lantern code, submit errors to the data collection service using precise, structured error codes

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4172]
These error codes should be structured hierarchically and be precise.  For example, `PFCHDT` would be:

* PF - proxying failure
* CH - via chained proxy
* DT - dial timeout

Or `SPME` would be:

* SP - set system proxy issue
* ME - missing executable

We should come up with some scheme that reliably sets these codes without having to rely on parsing/matching text.

While not required at this point, we should use a data structure for this that allows us to add arbitrary fields in the future.

**Comment by oxtoacart** [comment]
I'd estimate 8 story points for this to really get in there and provide some good detailed reporting, which will have to include some changes to the underlying libraries that currently just provide text errors and/or pass through errors from the standard library.

**Comment by oxtoacart** [comment]
It might be worth introducing a basic error structure for use in all our libraries, like this:

```golang
type Lerror struct {
        Code string
        Text string
}
```

**Comment by myleshorton** [comment]
This one is all set guys or no?

**Comment by oxtoacart** [comment]
Yup.  We'll probably tweak what gets submitted as we see it in practice, but it's implemented.
