### ISSUE TITLE
it could not support  git clone  

### ISSUE THREAD

**Issue by xjspace** [getlantern/lantern#4177]
git clone https://github.com/creationix/nvm.git
正克隆到 'nvm'...
fatal: unable to access 'https://github.com/creationix/nvm.git/': Failed to connect to github.com port 443: link time out

**Comment by myleshorton** [comment]
Lantern is just an http proxy, although it also runs SOCKS on port 8788 on 127.0.0.1. So you'd have to set git to run through the local HTTP proxy or SOCKS.
