### ISSUE TITLE
Feed reader support for Pro

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#4183]

**Comment by oxtoacart** [comment]
@xiam Does this mean integrating the feed reader into the Pro UI?  Is this for both mobile and desktop?  Assuming the answer to all these is yes, I'd estimate this at 5 story points.

**Comment by xiam** [comment]
I was thinking on desktop only because we are using react there and we cannot reuse a lot of code, but yes, we should think of both platforms.

**Comment by xiam** [comment]
I'm closing because there has been no discussions on implementing this into the pro UI.
