### ISSUE TITLE
Add link to newsfeed

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4185]
Instead of throwing all users into the newsfeed, we'll add a link allowing them to try it out.

The main intent here is to avoid automatically showing content that some users might consider to be political in nature, which might make Lantern a bigger target for censors.

So instead, people will have to click on a link to open the newsfeed.

The UI should remember if someone has previously elected to view the newsfeed and automatically show it the next time they come into Lantern.

This change only applies to desktop.  Mobile will stay as is (we consider it private enough).

**Comment by Derekf5** [comment]
Hey @fffw or @xiam not sure who is implementing this, but here are the specs for the link.
![trynewsfeed](https://cloud.githubusercontent.com/assets/7864729/14968304/19feb6fe-108a-11e6-8547-a787ad9e206a.png)
![backtotheoldlook](https://cloud.githubusercontent.com/assets/7864729/14968310/1eea30bc-108a-11e6-8f4d-a8a9058e22ec.png)

**Link Text** 
- Font: Proxima Nova; Font Size: 14pt; Font Weight: 600; Color: #ffffff; 

**Link Box**
- Height: 36px;
- Width: should be 32px wider than the text, 16px on either side of the centered text.
- Color: #ff4081; 
- border-radius: 0px 0px 0px 3px

*note: the "try lantern for android link" in the footer should be present on both versions of the UI.

@myleshorton did i hear correctly that we are no longer implementing this on mobile?

**Comment by myleshorton** [comment]
Awesome thanks @Derekf5! I'm implementing this, and yeah I think let's hold off on mobile for now. I'll chat with Wolf and Chip about it.

**Comment by Derekf5** [comment]
@myleshorton just wanted to document our convo from the outreach call.  For mobile we decided to put the opt out/opt in in the menu.  Users should start on the feed.

**Comment by fffw** [comment]
@Derekf5 @myleshorton I have a design suggestion. An eye-catching "Check out the new Lantern newsfeed!" will encourage users to click it, which is good. OTOH, we'd better make "Take me back to the old look" less obvious, so the UI looks cleaner, and unless users do want to hide the feeds, they won't click it. A good place would be the far left or far right beneath the feeds content area.

Those with minor "obsessive-compulsive disorder" (like me) would be on tenterhooks with a pink box always sitting at the corner.

**Comment by myleshorton** [comment]
Yeah I tend to agree. Even just making it a smaller link in the same place without a pink background -- just something more subtle -- seems like it might be enough.

**Comment by Derekf5** [comment]
@myleshorton @ffww +1 on all of this guys!   I think keeping it in the same location but making the box background #ccc and text #000 should make it much more
Subtle.     Thanks!

**Comment by sunshine19090** [comment]
The link works fine.
