### ISSUE TITLE
Create UI design for Lantern Feedback Extension

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4186]

**Comment by oxtoacart** [comment]
@Derekf5 Looks like @myleshorton may actually want to do this extension sooner rather than later.  How many days worth of design work do you think it is?

**Comment by Derekf5** [comment]
@myleshorton @ox Should take 3-4 days of design work if i factor in realistic revisions etc. When i can start on it depends on if this is more important than adjustments to the designs of PRO/Feed integration.

**Comment by p3rcya** [comment]
Why are we doing this? The in app feedback is much better
