### ISSUE TITLE
Add facility to Lantern UI to support installation of Lantern Feedback Extension

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4188]

**Comment by oxtoacart** [comment]
This should just be a link to the Chrome app store, so I'd estimate this at 1 day.

**Comment by myleshorton** [comment]
I actually think we should just use the automatic installation for this when we install Lantern (i.e. just install it when we install Lantern). That'll save the user a step, and even if they uninstall it we can always just have a different extension in the app store for user-prompted installation if we ever want that.

**Comment by myleshorton** [comment]
So I would actually say there should be no UI for it at all..

**Comment by oxtoacart** [comment]
@myleshorton Unless something has changed since [this](http://blog.chromium.org/2012/12/no-more-silent-extension-installs.html) or [this](https://chrome.googleblog.com/2014/05/protecting-chrome-users-from-malicious.html), the only way for us to install the extension is through [inline installation](https://developer.chrome.com/webstore/inline_installation).

**Comment by oxtoacart** [comment]
Ah, I guess we can do it by updating the Chrome profile on disk - https://support.google.com/chrome/a/answer/188453

**Comment by oxtoacart** [comment]
@myleshorton So if we install the extension automatically, what do we do if someone removes the extension?

**Comment by oxtoacart** [comment]
BTW, the popular LastPass password manager uses the inline installation method, even though it comes with an installer that could theoretically mess with Chrome's profile.  I wonder why they chose that.

**Comment by oxtoacart** [comment]
@myleshorton It occurs to me that we've had this exact same discussion before, sorry for rehashing :(

FWIW, if we do the automatic install, I think it would be good to only do that initially and then provide a call to action in the UI to install the extension if the user uninstalls it (or the auto-install failed).  That said, I still think that for an MVP, especially when we're not sure yet whether the extension is even that valuable, it's good enough to use inline installation and it's certainly simpler and less error.  It may also leave us less likely to be flagged by people as malicious, as messing with other apps' settings files may come across as fishy to some.

**Comment by myleshorton** [comment]
> @myleshorton It occurs to me that we've had this exact same discussion before, sorry for rehashing :(

No worries!

> FWIW, if we do the automatic install, I think it would be good to only do that initially and then provide a call to action in the UI to install the extension if the user uninstalls it (or the auto-install failed).

Totally agreed, and I think we can do that with making the inline installation version just slightly different in the Chrome Store. I don't think we need that for MVP though.


> That said, I still think that for an MVP, especially when we're not sure yet whether the extension is even that valuable, it's good enough to use inline installation and it's certainly simpler and less error. 

Honestly for an MVP I'd go the other way because the automatic installation is significantly less work (this ticket wouldn't exist =). Even just the basic functionality of whether or not Lantern is proxying a given site I think would be useful, and people can always remove it. 

> It may also leave us less likely to be flagged by people as malicious, as messing with other apps' settings files may come across as fishy to some.

We're not currently planning on messing with other apps' settings are we? This is also an officially supported installation method, so I don't see people reporting as malicious as being very likely.

**Comment by oxtoacart** [comment]
> Honestly for an MVP I'd go the other way because the automatic installation is significantly less work

I think you must be thinking of a different approach than me :)  How exactly would you to the automatic installation?
