### ISSUE TITLE
Publish Lantern Feedback Extension to Chrome App Store

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4189]

**Comment by oxtoacart** [comment]
I'd estimate this at 2 story points since this will be our first time publishing to the app store (should consult with Percy for help as I think he's got some experience here).

**Comment by myleshorton** [comment]
It takes about 10 minutes to publish to the app store...

**Comment by oxtoacart** [comment]
@myleshorton Cool, there's no approval process required or special signing key hoops to jump through?

**Comment by myleshorton** [comment]
I can't remember all the details offhand, but it's quick. I'd be happy to just take this one too since I've been through the process.
