### ISSUE TITLE
No error message is shown when using Get the app via email feature when there is no internet connection

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4191]
Steps:

1. Disconnect network.
2. Click on "Try Lantern Android"
3. Enter the email address and click on the Get the app button.

No error message is shown at this point. It takes the user to the pop-up screen.

**Comment by myleshorton** [comment]
This is definitely an old issue, but I don't think we need to worry about it now. I'm going to close for now, as the ad also might be going away with pro.
