### ISSUE TITLE
Lantern doesn't proxy without Chrome installed on Windows 10

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4218]
QA version. 
Chrome preinstalled then install Lantern, the traffic is proxied. 
Then I uninstalled Chrome. Closed Lantern. Then open Lantern. The start page shows normally in Edge but traffic is not proxied. (The setting is already proxy all, but ip site will still return real IP)

**Comment by myleshorton** [comment]
Does this still happen with the latest version from last night @percyalpha? Also FYI @xiam

**Comment by percyalpha** [comment]
The newest QA (you sent 19 hours ago) can proxy on edge without Chrome

**Comment by myleshorton** [comment]
Cool thanks for the testing @percyalpha and nice work on that fix @xiam!
