### ISSUE TITLE
Iranwire articles are not translated to Persian

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4219]
I remember seeing everything being translated to Persian in the previous build. 

![image](https://cloud.githubusercontent.com/assets/11394369/15056880/e01d1188-12c8-11e6-9756-3d40b12c3a34.png)

**Comment by myleshorton** [comment]
This is content from Iranwire itself - i.e. we don't translate anything from them but rather just show their content @sunshine19090. Looks like some of their content is in english.
