### ISSUE TITLE
When showing the self-help page, the link in the top right corner is not changing to "Take me back to the old look"

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4229]
![image](https://cloud.githubusercontent.com/assets/11394369/15084485/a1e53e2a-1388-11e6-9624-d88c2cc70a20.png)

**Comment by myleshorton** [comment]
OK I'll have a fix for this soon @sunshine19090

**Comment by myleshorton** [comment]
Should be all set @sunshine19090!
