### ISSUE TITLE
Android notification center says Lantern is connected even when it's turned off

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4235]
Google Play release version.
Turn Lantern on and the notification says Lantern is connected. But it will not go away even when the Lantern is turned off

**Comment by sunshine19090** [comment]
Yeah I saw this in QA build too. I actually think that the notification is redundant as we already indicate the connection by the key sign at the top right corner. Is there any other use for this notification @atavism?

Regards,
Sunshine

**Comment by sunshine19090** [comment]
@atavism I forgot to mention that the notification cannot be deleted and it doesn't go away even after killing the app. The only way is to delete the app.

**Comment by atavism** [comment]
Agree it's redundant with the key already. I'll just strip it out
