### ISSUE TITLE
lantern was blocked since 8am today

### ISSUE THREAD

**Issue by spencerpomme** [getlantern/lantern#4236]
No access to the blocked sites

**Comment by MABIY** [comment]
Me too。
l using ubuntu 16.04

**Comment by kexul** [comment]
same here ,ubuntu 16.04

**Comment by YueminHu** [comment]
Shanghai, China seems okay. Im using 2.1.2 on win10. Connecting to Japan...

**Comment by spencerpomme** [comment]
Still have no access in Guangzhou, Windows 10, OS X 10.11，lantern 2.1.2。

发自我的 iPhone

**Comment by myleshorton** [comment]
Can you try 2.2.0 linked from GitHub?

**Comment by spencerpomme** [comment]
Tried new version yet still no access. Is there any prerequisites to use it or all I need to do is install it with the installer? Deeply worried for now even github is inaccessible.

发自我的 iPhone

> 在 2016年5月9日，11:38，myleshorton <notifications@github.com> 写道：
> 
> Can you try 2.2.0 linked from GitHub?

**Comment by myleshorton** [comment]
Can you email your logs to dev@getlanter.org?

**Comment by spencerpomme** [comment]
Of course. Where can I retrieve the log?

发自我的 iPhone

> 在 2016年5月9日，11:51，myleshorton <notifications@github.com> 写道：
> 
> Can you email your logs to dev@getlanter.org?

**Comment by spencerpomme** [comment]
System log sent.

发自我的 iPhone

> 在 2016年5月9日，11:51，myleshorton <notifications@github.com> 写道：
> 
> Can you email your logs to dev@getlanter.org?

**Comment by myleshorton** [comment]
Hey @spencerpomme sorry I should have mentioned instructions for finding the logs are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by myleshorton** [comment]
You can just send them to dev@getlantern.org though. Also, what browser are you using?

**Comment by MABIY** [comment]
then  lantern 2.12 is working,  l think server is not working before.

**Comment by spencerpomme** [comment]
I‘m using firefox on windows and safari on OS X. @myleshorton

**Comment by fffw** [comment]
@spencerpomme Your proxy server were blocked in China. Should work fine now.

**Comment by spencerpomme** [comment]
Problem solved, access to blocked sites restored.
