### ISSUE TITLE
Renew firetweet.io certificate

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4250]

**Comment by myleshorton** [comment]
Hey @atavism would you mind looking at this one?

**Comment by myleshorton** [comment]
Or you @fffw?

**Comment by atavism** [comment]
@myleshorton I'll take care of it! I already bought the new certificate a few weeks ago. Just need to install it

**Comment by myleshorton** [comment]
Sweet thanks @atavism!

**Comment by atavism** [comment]
Done!
