### ISSUE TITLE
中文help为什么要放到google group？

### ISSUE THREAD

**Issue by zippera** [getlantern/lantern#4255]
很多人用lantern是为了fq吧，中文help放到google group，无法访问啊，不合理

**Comment by Rice321** [comment]
你好，感谢你的反馈。
如果你遇到问题无法翻墙，也可发送邮件给我们 team@getlantern.org 直接跟我们联系。

**Comment by percyalpha** [comment]
欢迎到蓝灯(Lantern)官方论坛 https://github.com/getlantern/forum/issues/1
