### ISSUE TITLE
Missing "node" command. make: *** [require-node] Error 1

### ISSUE THREAD

**Issue by GeKirita** [getlantern/lantern#4256]
~/lantern $ make lantern
Missing "node" command.
make: *** [require-node] Error 1

**Comment by fffw** [comment]
@GeKirita Did you install all the [prerequisites](https://github.com/getlantern/lantern#prerequisites)?

**Comment by xiam** [comment]
Hello @GeKirita, please check the [Building Lantern](https://github.com/getlantern/lantern#building-lantern) part of the README and try again.
