### ISSUE TITLE
Fails to connect to any foreign sites with lantern on

### ISSUE THREAD

**Issue by spencerpomme** [getlantern/lantern#4258]
If lantern's on, unblocked foreign sites like github are fail to access, and once turned off lantern these sites can be accessed again.

Further more, those sites which are blocked(Facebook, twitter, google, etc) by GFW are inaccessible approximately around 16:10 UTC8.

Is it possible that GFW developed a way to detect traffics using lantern and just block it anyway?

I'll send the log files to dev@getlantern.org ASAP.

**Comment by spencerpomme** [comment]
And, if I tick **proxy all traffics**, even domestic sites in mainland China is inaccessible.
BTW, log file sent.

**Comment by myleshorton** [comment]
Thanks @spencerpomme we're looking at the issue. It looks like you're using a slightly older version of Lantern. Does this one work better for you (2.2.1)?

https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.dmg

**Comment by spencerpomme** [comment]
I’m using 2.2.1 and this morning access restored again. Guess what happened yesterday was just temporary? I’ll close the issue when you think it’s ok to close.

**Comment by myleshorton** [comment]
OK thanks @spencerpomme. We did identify one issue with help from your logs and actually just put out a 2.2.2 version because of it. Lantern should automatically update for you and should be running 2.2.2 the next time you restart it! I'll close this for now, and thanks again.

**Comment by spencerpomme** [comment]
Happy that helped!
