### ISSUE TITLE
Change the download link on getlantern.org from S3 to Github

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4264]
Currently, the site uses links like https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg should use https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg instead

**Comment by fffw** [comment]
During my test on the Chinese VPS, downloading from S3 is much faster than from GitHub. raw.githubusercontent.com resolves to github.map.fastly.net which may have issue visiting from China.

Do we differentiate beta and non-beta versions now?

**Comment by percyalpha** [comment]
Hmm. Could you test from a residential connection? data center might be
whitelisted for connection to S3. My experience is that the HTTPS to S3 is
throttled a lot.

On Friday, May 13, 2016, fffw <notifications@github.com> wrote:

> During my test on the Chinese VPS, downloading from S3 is much faster than
> from GitHub. raw.githubusercontent.com resolves to github.map.fastly.net
> which may have issue visiting from China.
>
> Do we differentiate beta and non-beta versions now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/4264#issuecomment-218996219>
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)
(202) 780-5619
www.percya.com   @p3rcya <https://twitter.com/p3rcya>
Independent Internet freedom researcher
Former co-founder of GreatFire

**Comment by myleshorton** [comment]
In practice beta and full release versions are only different in that only
full release versions are auto-updated.

On Fri, May 13, 2016 at 2:32 AM, fffw <notifications@github.com> wrote:

> During my test on the Chinese VPS, downloading from S3 is much faster than
> from GitHub. raw.githubusercontent.com resolves to github.map.fastly.net
> which may have issue visiting from China.
>
> Do we differentiate beta and non-beta versions now?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/4264#issuecomment-218996219>
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by percyalpha** [comment]
So we really don't need beta version at all.

**Comment by percyalpha** [comment]
But on the official site, the download address has beta in it?

**Comment by fffw** [comment]
I tested on three different ISP. The result varies but S3 is better in general. A quick ThousandEyes test shows the opposite: GitHub performs much better than S3 in both throughput and latency, for most of the PoPs. It is reasonable as S3 is not via CDN.

I guess the reason we put beta on official site is to have a small amount of user to reveal potential problems, before push to all users via auto-update. We probably want to stay with beta  (https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.dmg) instead.

**Comment by percyalpha** [comment]
@fffw Agree. Let's use the Github-beta on getlantern.org. 
@myleshorton Are  https://s3.amazonaws.com/lantern/lantern-installer.dmg always update date release version? I only see https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg being used ever.

**Comment by percyalpha** [comment]
I still don't understand why we need beta version. 
We can always release newer version for testing on getlantern.org but those users deserve to be auto-updated too. In other words, we can have the release version. However, we can release it on getlantern first without auto-updating older versions until it's proven stable

**Comment by p3rcya** [comment]
closed in favor of https://github.com/getlantern/lantern/issues/4884
