### ISSUE TITLE
[Desktop] Provide a clear indicator of how much time is left on user's pro plan and give user the option of adding credit

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4275]
This will allow the user to know when they need to add credit and then do something about it before Pro expires.  This accommodates users in China who are used to paying for services on a monthly basis without auto-renewal.

**Comment by oxtoacart** [comment]
We may only offer an annual option, which would buy us time.  Let's leave in the backlog but not worry about it yet.

**Comment by sunshine19090** [comment]
@oxtoacart Right now these details are provided in the account management screen and there is a renew pro button for the user to add credit. Shall I close this?

**Comment by oxtoacart** [comment]
Yes, this LGTM!
