### ISSUE TITLE
Auto-update behavior if app installed via Google Play

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4280]
Related to https://github.com/getlantern/lantern/issues/3797, we need to do some additional checks if an app is installed via Google Play

**Comment by percyalpha** [comment]
Google disallow auto-update. We can get around this by detecting whether Google Play is blocked and only self-update if Play is blocked

**Comment by atavism** [comment]
Yep. It looks like if I install an app via Google Play, and want to overwrite that installation with a newer version, outside the Play store, that actually works as long as the APK signatures match (and the ``versionCode`` is newer). So I think we can leave self-updates enabled whether the app was installed via Play or not.

**Comment by percyalpha** [comment]
@atavism No, we cannot allow auto-update on Play.  " An app downloaded from Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism" (https://play.google.com/about/privacy-and-security.html#malicious-behavior) 

As I mentioned in the last post, we can skirt this rule by detecting whether Play is blocked. But there is no way we can do self-updating in all situations.

**Comment by atavism** [comment]
We don't really have to check if Play is blocked. We can check if the user already has Play installed or if the app was installed via Play.

**Comment by percyalpha** [comment]
@atavism Yeah, obviously if the App is not installed by Play, we can do whatever we want. Check whether Play is blocked is to deal with the situation where users had a VPN to download it from Play then switched to Lantern. But Lantern is somehow blocked and he cannot use Lantern circumvent to access Google Play to update

**Comment by atavism** [comment]
Ok, makes sense! Thanks, @percyalpha.
