### ISSUE TITLE
无法翻墙求助

### ISSUE THREAD

**Issue by socalledPF** [getlantern/lantern#4284]
win8 移动网络无法使用lantern 翻墙 虽然弹出界面显示可以翻墙 但是还是无法访问被墙的网站

但是公司电信 同样win8可以正常使用

**Comment by CHN008** [comment]
如果懂一些相关基础用这个试试
https://github.com/XX-net/XX-Net

**Comment by percyalpha** [comment]
翻墙软件讨论请发到蓝灯论坛 https://github.com/getlantern/forum
