### ISSUE TITLE
balancer.go:79 Unable to dial via (trusted) chained proxy at 45.32.60.50:443

### ISSUE THREAD

**Issue by cannanlly** [getlantern/lantern#4285]
always show this message in log,How to deal with it?
Still unable to dial tcp://www.google.com.au:80 after 3 attempts

**Comment by afeilulu** [comment]
same issue here.

May 13 10:07:43.324 - 6m49s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 45.32.253.106:443 [] to connect://clients4.google.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.106:443 []: dial tcp 45.32.253.106:443: i/o timeout on pass 2...continuing
May 13 10:07:43.324 - 6m49s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 45.32.253.106:443 [] to connect://clients4.google.com:443: Unable to dial server (trusted) chained proxy at 45.32.253.106:443 []: dial tcp 45.32.253.106:443: i/o timeout on pass 2...continuing

May 13 10:07:43.324 - 6m49s ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial connect://clients4.google.com:443 after 3 attempts
May 13 10:07:43.324 - 6m49s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial connect://clients4.google.com:443 after 3 attempts

May 13 10:07:43.324 - 6m49s DEBUG flashlight.client: handler.go:121 Could not dial Still unable to dial connect://clients4.google.com:443 after 3 attempts
May 13 10:07:43.324 - 6m49s DEBUG flashlight.client: handler.go:174 Responding 502 to //clients4.google.com:443
May 13 10:07:43.376 - 6m49s DEBUG balancer: balancer.go:89 Dialing connect://clients4.google.com:443 with (trusted) chained proxy at 45.32.253.106:443 []
May 13 10:07:45.790 - 6m51s DEBUG flashlight: main.go:330 Calling exit func

**Comment by afeilulu** [comment]
Lantern works today
