### ISSUE TITLE
 这个是2015 还是 2016 出的啊，差了一年了

### ISSUE THREAD

**Issue by hongkonghot** [getlantern/lantern#4286]
蓝灯[Lantern]最新版本下载
@oxtoacart oxtoacart released this on 12 May 2015 · 1644 commits to valencia since this release

**Comment by skepts** [comment]
你的问题是什么。。。这软件一直有更新啊

**Comment by Rice321** [comment]
是一直在不断更新的。

**Comment by percyalpha** [comment]
这个是最新版本。下载地址是一样的
