### ISSUE TITLE
Websocket connection to 'ws://127.0.0.1:16823/data' failed: Invalid frame header

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4301]
Reported by a user. The spinner is always shown. Chrome browser.

![image](https://cloud.githubusercontent.com/assets/10410437/15277644/fad21574-1b3c-11e6-86ec-fa611e937c31.png)

**Comment by Droyk** [comment]
same issue as #4282

**Comment by xiam** [comment]
Thanks, this is a duplicate. Closing.
