### ISSUE TITLE
use lantern but can't open google

### ISSUE THREAD

**Issue by helloMyLover** [getlantern/lantern#4306]
I can not log on Google with lastest version of the Latern.     changed .log to .txt
[lantern.txt](https://github.com/getlantern/lantern/files/266287/lantern.txt)

**Comment by percyalpha** [comment]
Another user reported this as well

**Comment by percyalpha** [comment]
@fffw could you tell me where to find the GFW blacklist included in the Lantern? I want to take a look. Maybe country specific Google domains are not included. I wanna double check on other domains as well.

**Comment by fffw** [comment]
@helloMyLover There's no record of accessing Google from your logs. Could it be Xunlei, 3rd party browser extensions, or AV software preventing the browser from using Lantern as proxy?

@percyalpha The list is a combine of files under https://github.com/getlantern/lantern/tree/devel/src/github.com/getlantern/flashlight/genconfig/proxiedsites. AFAICT detour can detect those blocked sites even if they are not on the list, though there are false positives sometimes.

Does "Proxy all traffic" work? Sometimes if Google is temporarily reachable (e.g., when a previously connected VPN disconnected) Lantern will mark it directly accessible in http://127.0.0.1:16823/proxy_on.pac. Restarting Lantern would work in that case.

**Comment by percyalpha** [comment]
@fffw I'm assuming this list is active to China only? 
China as defined by language setting or IP?

**Comment by fffw** [comment]
No it's global list. There's no per country list.

**Comment by percyalpha** [comment]
But then say I'm in Iran and google is not blocked, it will be proxied?

**Comment by fffw** [comment]
Yes. That suggests the list to be short enough. Ideally we can always rely
on auto detection.

**Comment by percyalpha** [comment]
But ideally we should have per country list in the future. I'll open a ticket

**Comment by fffw** [comment]
Maintaining a set of dynamic list puts a burden on us. It's even impossible
to have accurate lists time to time.

**Comment by percyalpha** [comment]
Not a dynamic list. I mean just a basic per country list that updates every year or something. If google is not blocked in other countries, proxying google is just wasting bandwidth.

**Comment by helloMyLover** [comment]
I uninstall Xunlei, and can access google now ,thank you   @fffw @percyalpha  if you want to talk continue ,I close the question later? O(∩_∩)O

**Comment by percyalpha** [comment]
Our latest version should have solved the incompatibility with Xunlei
already. Which version are you using?

On Saturday, May 21, 2016, helloMyLover <notifications@github.com> wrote:

> I uninstall Xunlei, and can access google now ,thank you @fffw
> <https://github.com/fffw> @percyalpha <https://github.com/percyalpha> if
> you want to talk continue ,I close the question later? O(∩_∩)O
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/4306#issuecomment-220776768>
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by helloMyLover** [comment]
2.2.3 O(∩_∩)O

**Comment by percyalpha** [comment]
@myleshorton User report that 2.2.3 is incompatible with Xunlei. See log on by the user

**Comment by percyalpha** [comment]
@helloMyLover Is the newest release still incompatible with Xunlei?

**Comment by helloMyLover** [comment]
I download Thunder again, and both can work     ~~~~(>_<)~~~~ the lantern version still 2.2.3
