### ISSUE TITLE
ubuntu 16.04 is not work but win7 and mac is working

### ISSUE THREAD

**Issue by MABIY** [getlantern/lantern#4320]
l not  believe is proxy server problem ,this is why?

**Comment by MABIY** [comment]
sorry ,this is local machine problem

**Comment by orivil** [comment]
@MABIY 你是怎么解决的？我试了卸载 lantern 再重装还是不行，windows 到是能用

**Comment by MABIY** [comment]
偶尔会出现这种情况，最近一次我卸载之后重新安装还是上不去，我重启了一下电脑就好了，不过应该是当时日本那边代理服务器的问题 ？
（保持lantern最新版本）



2016-05-31 8:58 GMT+08:00 orivil <notifications@github.com>:

**Comment by krast** [comment]
如果我提供vpn服务，有多少人会用？
ps:lantern的限制太多，GFW其实很蠢，欺骗太简单了。

On May 31, 2016, at 9:08 AM, lh <notifications@github.com<mailto:notifications@github.com>> wrote:

偶尔会出现这种情况，最近一次我卸载之后重新安装还是上不去，我重启了一下电脑就好了，不过应该是当时日本那边代理服务器的问题 ？
（保持lantern最新版本）



2016-05-31 8:58 GMT+08:00 orivil <notifications@github.com<mailto:notifications@github.com>>:

**Comment by MABIY** [comment]
还有一种情况，我在公司的时候可以通过lantern 访问外网，在家里就不可以。


在 2016年5月31日 上午9:08，刘华 <jyfc7879@gmail.com>写道：

**Comment by orivil** [comment]
更新了v2.2.4就可以用了
