### ISSUE TITLE
Test custom packages of Lantern

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4329]
https://github.com/comeforu2012/truth/wiki/Chrome-Lantern%EF%BC%88%E8%93%9D%E7%81%AF%EF%BC%89

https://github.com/bannedbook/fanqiang/wiki/%E8%93%9D%E7%81%AFChrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

**Comment by ClydeChenT** [comment]
Invalid

**Comment by percyalpha** [comment]
We should do this https://github.com/getlantern/lantern/issues/4337
