### ISSUE TITLE
Seeing a normal windows icon instead of lantern logo in the appdata

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4331]
![image](https://cloud.githubusercontent.com/assets/11394369/15375350/7a7c69c4-1d03-11e6-8b2e-a72584051a09.png)

**Comment by ClydeChenT** [comment]
try reinstalling it before that close all of your security softwares

**Comment by myleshorton** [comment]
This is fairly common @sunshine19090, and I don't think we have a way to fix it really.
