### ISSUE TITLE
Facebook sharing message is displayed in Chinese though the language setting is in English.

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4336]
Looks like it is always displaying in Chinese. I tried reinstalling lantern and restarting the browser. 

![image](https://cloud.githubusercontent.com/assets/11394369/15406498/b4051ae8-1dbb-11e6-8213-8a8fd6016242.png)

**Comment by sunshine19090** [comment]
And this too @myleshorton. Doesn't come under 2.3.0?

**Comment by sunshine19090** [comment]
@myleshorton This still exists in Lantern Pro too. All my language settings are in English and still the facebook sharing page is always displayed in chinese.

![image](https://cloud.githubusercontent.com/assets/11394369/15848051/4a94177a-2c3f-11e6-86fe-7272ef8dcddd.png)

**Comment by p3rcya** [comment]
this function is removed
