### ISSUE TITLE
Not receiving an updated config after purchasing pro

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4340]
In my understanding, once I purchase pro I should get a new config the next time I request one. I continue to get `304 Not Modified` in that case.

**Comment by myleshorton** [comment]
Any idea on this one @uaalto or @aranhoide? How do I look at incoming request logs on the pro server?

**Comment by uaalto** [comment]
You can see the incoming requests via Heroku logs or Papertrail.
I personally prefer heroku logs. For that you only need to run:
`heroku logs -t` in your pro-server folder.

Best way to track this is to:
1. Check that requests are received and there is no exception in the Pro-server, via heroku logs for example
2. Connect to Redis via redis-cli or the Clojure REPL to see if all expected values are modified as expected. That is of course the more tedious part, the best way to learn about this would see to read the redis.clj file, specially the purchase task code.
3. If everything is fine in Redis, then we need to check if the config-server is picking up these changes properly. For that we can perform a manual curl request and see what happens.

In your particular case, so I can look into it, did you have a successful purchase and everything looked right?

**Comment by uaalto** [comment]
@myleshorton this seems to be caused by DO migration of config-server. We need to migrate staging config-server, because its redis configuration is outdated, so it's not picking up Pro users ATM.
