### ISSUE TITLE
panics for invalid config

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4357]
[User reported](https://groups.google.com/forum/#!topic/lantern-users-zh/JwQuQQJS9D0).

In [config.go#L108](https://github.com/getlantern/lantern/blob/release-2.2.0/src/github.com/getlantern/flashlight/config/config.go#L108) we didn't check if `cfg.Client` is empty.

**Comment by myleshorton** [comment]
This actually isn't possible on devel so should be fixed in 2.3.0.
