### ISSUE TITLE
Google.com asks for authorization code continuously

### ISSUE THREAD

**Issue by F-12** [getlantern/lantern#4368]
As mentioned [here](https://github.com/getlantern/forum/issues/52#issue-156649572), recently google.com often ask me to input an authorization code to continue my search request which is really annoying.

**Comment by fffw** [comment]
Thanks, @F-12, we are working a change which could possibly reduce the chance being classified as a bot.

**Comment by corehello** [comment]
Got the same result here, include YouTube

**Comment by myleshorton** [comment]
Duplicate of #2366. We'll look at this more carefully @corehello and @F-12
