### ISSUE TITLE
Add Pro Data cap snackbar notification

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4369]
@myleshorton here are the specs for the snackbar notification.

<img width="1068" alt="screen shot 2016-05-25 at 10 30 47 am" src="https://cloud.githubusercontent.com/assets/7864729/15543667/c8559e9e-2263-11e6-8d43-fac1d6ddf55d.png">

**Snackbar Specs*:**
  width : 400px;
  height : 60px;
  border-radius : 2px;
  Bottom padding : 56px

**"You have used your free monthly data" text specs:**
  font-family : Roboto Medium;
  font-size : 14px;
  line-height : 19px;
  color : #FFFFFF;
  left padding : 16px

**"UPGRADE" Button text specs**:**
font-family : Roboto Medium;
  font-size : 14px;
  color : #FF4081;

* This snackbar should persist until the user upgrades, or their monthly data is refilled 

** This button should take you to the payment plans popup

*** In this state the "Lantern is off..." Text should also read "You have no data left this month"

Ox brought this up in another ticket, but here is an example of snackbars in action 
http://www.material-ui.com/#/components/snackbar

**Comment by myleshorton** [comment]
Darn missed this one @Derekf5 -- I'll try to knock this out.

**Comment by myleshorton** [comment]
Just wanted to note it looks like this is already supported via something like:

```
this.props.dispatch(actions.showNotification(this.props.t("messages.datacap")));
```

**Comment by xiam** [comment]
Look like this is still pending, I'll take it over, sounds good @myleshorton?

**Comment by sunshine19090** [comment]
This works fine when the free data cap is over.
