### ISSUE TITLE
Limit HTTP ports to proxy

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4377]
We enforced `ProxiedCONNECTPorts` to match the same set on Lantern server, but there's no such thing for ReverseProxy. It's uncommon to host a production site on ports other than 80 and 8080, but just in case, especially if "proxy all traffic" is on.

BTW, we need to show a tip somewhere that "proxy all traffic" isn't actually "proxy all".

**Comment by oxtoacart** [comment]
@fffw Why do we need to enforce this for plain HTTP requests?  The reason that we do it for CONNECT requests is because this could be abused to access other services like BitTorrent, etc.

**Comment by fffw** [comment]
@oxtoacart As we limited the ports on proxy server, not limiting them on the client would just send them to proxy and be rejected. But actually we can change proxy server side to not limit ports for non-CONNECT requests.

**Comment by oxtoacart** [comment]
Oh, I see, the server is limiting outbound ports for all traffic, but the client is only doing so for CONNECT traffic?

**Comment by fffw** [comment]
Oh sorry the proxy server code only limit CONNECT requests. I forgot what pushed me to create this issue but there was something.

Close it for now. Thanks @oxtoacart
