### ISSUE TITLE
Change language on data cap indicator

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4383]
Currently reads:
"300MB used of your free monthly data"

Change to:
"200MB remaining of your free monthly data"

**Comment by myleshorton** [comment]
Wait @Derekf5 I just swapped your order above because I believe that's what you wanted. Really the current reads "200MB used of your free monthly data", though, so I just want to make sure I'm making the right change. Am I? Should it be the second above?

**Comment by Derekf5** [comment]
HA! yes thats correct @myleshorton good catch

**Comment by sunshine19090** [comment]
LGTM @Derekf5 . Assigning it to you for final verification.

**Comment by Derekf5** [comment]
Yes LGTM as well! @sunshine19090
