### ISSUE TITLE
Since May 24th Lantern doesn't work

### ISSUE THREAD

**Issue by sevenzhou1218** [getlantern/lantern#4386]
Hi, Lantern doesn't work ,  Since May 24th

win7, lantern version 2.0.10.

then i  try lantern 2.2.3 and 2.2.4 ,but no use

**Comment by myleshorton** [comment]
Thanks @sevenzhou1218. Can you send your logs please? Instructions are here, and please copy me directory (myles@getlantern.org):

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by sevenzhou1218** [comment]
It works fine now....
