### ISSUE TITLE
How to find iOS source code for iPhone 

### ISSUE THREAD

**Issue by about-bob** [getlantern/lantern#4387]
Hi,

Lantern is a very great tool for technology usage. 
Could you share the iOS source in Github, since Lantern can't be found in App Store from China.
We can build iOS App for testing usage, privately, and it will not be published to App Store.

Thanks.

**Comment by percyalpha** [comment]
We haven't developed an iOS version yet. But it is on our map

**Comment by about-bob** [comment]
Hi,

There is a link, that links to lantern in AppStore from US.
https://itunes.apple.com/us/app/lantern-golantern.com/id915708282?mt=8

Sorry, I misunderstand "golantern" and "getlantern".

Thanks,
Jacob

**Comment by percyalpha** [comment]
Yeah, that's not our app. We're planning on an iOS version though
