### ISSUE TITLE
Translate all pro strings via Transifex

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4397]

**Comment by uaalto** [comment]
Is this the backend strings?
They are set and ready to be translated in the Lantern Pro project in Transifex.

**Comment by fffw** [comment]
I guess it's about Pro UI. There are a few new strings. I just pushed them to Transifex.

**Comment by myleshorton** [comment]
Yeah pro UI @fffw thanks! We also need to pull the translations down from transifex at some stage

**Comment by percyalpha** [comment]
@Derekf5 
Per the email discussion, we need to have substantial change on the sign up page. And I need to make the translations more local than those generic translations
