### ISSUE TITLE
Make sure Lantern shows the UI from desktop shortcut on Windows

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4398]
...particularly when Lantern's already running. It looks like that functionality may have broken somewhere along the way.

**Comment by fffw** [comment]
@myleshorton In which environment and which version you saw this? I couldn't reproduce it with 2.3.0 on Windows 7, both IE and Chrome.

**Comment by myleshorton** [comment]
Does it show the UI for you even when Lantern is already running @fffw? When Lantern's already running, clicking the shortcut should make it open a browser.

**Comment by fffw** [comment]
@myleshorton Yes the UI of existing Lantern instance is shown each time when I click the shortcut.
