### ISSUE TITLE
lantern just bypass /etc/hosts file?

### ISSUE THREAD

**Issue by 1c7** [getlantern/lantern#4402]
### Problem

I am trying to debug **Third party login** on my local server
(Twitter, Facebook, Github)
so I run this:

```
echo 127.0.0.1  www.something.com >> /etc/hosts
```

when lantern not running. everything fine.
when I need lantern to enable my to visit Twitter/Facebook, clearly the /etc/hosts file not working.
Firefox just open a website that are not my local server
### What I want

when I am using lantern. and visit www.something.com I would get local server response.

---

I already search on Google
But I can't get any similar question&answer on Google, so only thing I can do is ask nice people here on Github

---

I use Lantern a lot, this software is very useful, Thank you Lantern Team :smile:

**Comment by crysislinux** [comment]
Please see this:  https://github.com/getlantern/lantern/issues/3472

You are not the first one who meets the problem actually. 😄

**Comment by lifeforfun** [comment]
Is there any clearly solution for this issue? #3472 does not have an exactly method.
