### ISSUE TITLE
Update the account management page

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4405]
currently, the yearly plan would be automatically renewed. Chinese users want a one time pay-off for any plan. 
![image](https://cloud.githubusercontent.com/assets/7925929/15635882/55343880-25a1-11e6-8d2d-07442fe12271.png)

**Comment by myleshorton** [comment]
Thanks @percyalpha. It doesn't actually auto-renew -- the screen just needs updating. We'll make the fix though.

**Comment by percyalpha** [comment]
In this case, I suggest removing the page completely. Because the updating billing info is not relevant and we won't support cancel account either. 

We can just have a renew page that is the same as the initial purchase page when the user plan is about to expire

**Comment by atavism** [comment]
Hey @Derekf5, we need an updated design for this on mobile assuming we're getting rid of the "Update Billing Info" button (users should still be able to cancel their account presumably). I think we can keep this screen and use it as general profile/settings page. See here: https://github.com/getlantern/lantern/issues/4390

**Comment by percyalpha** [comment]
I agree on keep this screen as account management. I do not think we need cancel account either as we will not issue refunds. We would need:
Log in(link device)  / Log out (Unlink)
Expiration date
Bonus earned (Break down to how many 3 months free + how many month free)

**Comment by atavism** [comment]
Yeah, that sounds good @percyalpha. I think we should also let the user edit his e-mail address and/or phone number from this screen too.

**Comment by percyalpha** [comment]
@atavism agree. (Email address is in the future right?)

**Comment by percyalpha** [comment]
You current Lantern Pro account expires at MM/DD/YY
To renew, click here. (Link to the selecting plan page)

**Comment by atavism** [comment]
@percyalpha Yep! 

Oh, one other thing, we wanted to add an easy way for users [to export and send their logs to us](https://github.com/getlantern/lantern/issues/2785). I'm thinking a simple "Send Logs" button if the user already has a valid e-mail (this could also be a separate side-menu option). There could also be a small textarea to optionally provide feedback. As you're already updating this screen, it might be a good place to add it, @Derekf5.

**Comment by percyalpha** [comment]
I think it's better put "Send Logs" in the button of account management rather taking space in the menu bar. Good idea.

**Comment by sunshine19090** [comment]
@atavism how do we auto renew the plan? Do we store the user's credit card details? If so, then we may have to provide the user an option to cancel/delete the account at any point of time. I wouldn't feel safe to leave my card details in some website which I am not using. If we store the credit card details, then should we provide them an option to change the card details?

Also, if we do auto renew then we should also provide the user an option to change their plan just in case if they have changed their mind.

**Comment by percyalpha** [comment]
@sunshine19090 We will not auto renew any plans. If users want to renew, they will go to account page and click renew and go through the payment process like the first time

**Comment by sunshine19090** [comment]
Okay @percyalpha The text in the current Account management page is misleading. We have to change the wordings then. It currrently says "Your account will automatically be charged for another year of Lantern Pro at the end of billing cycle".

Also, instead of saying "You currently have Lantern pro plans.annual account", we could say "You are currently using Lantern pro annual account plan" or "You are currently subscribed for Lantern Pro yearly plan"

**Comment by percyalpha** [comment]
@sunshine19090 I mentioned the text change in my previous reply already  https://github.com/getlantern/lantern/issues/4405#issuecomment-222824928

**Comment by Derekf5** [comment]
Just noting to myself that we need to show what devices are logged into that account

**Comment by Derekf5** [comment]
Hey @percyalpha @myleshorton @atavism how does these look?  The "change phone number button would take you to a screen that would be the same as the "authorize device for pro" screen, with the copy changed to reflect that you are changing your phone number.  
<img width="428" alt="screen shot 2016-06-01 at 11 44 44 am" src="https://cloud.githubusercontent.com/assets/7864729/15715966/807c3160-27ee-11e6-9346-31ef3e943e58.png">
<img width="932" alt="screen shot 2016-06-01 at 11 43 22 am" src="https://cloud.githubusercontent.com/assets/7864729/15715975/88d706c8-27ee-11e6-9dc9-1947ade6b065.png">

**Comment by percyalpha** [comment]
This looks fantastic!!

**Comment by percyalpha** [comment]
Two minor points though:
1. In Chinese, the date format should be YYYY年XX月XX日(year, month date).   Just making sure it can be handled correctly 

2. This includes xx bonus months from x two year plan referrals and  x one year plan referral. 
This way, users can easily counts his referral.

**Comment by Derekf5** [comment]
@atavism here is the spec for the updated Pro account management screen,
The only new graphic on this screen is the "x" to deauthorize a device, here is the link to its location in dropbox. https://www.dropbox.com/sh/16q561z7yyrmscx/AADGVotOHZ_VEpqKyusGxAR1a?dl=0
![pro-account-management-spec-sheet-update](https://cloud.githubusercontent.com/assets/7864729/15721115/88007e5c-2805-11e6-9872-490c1daae553.png)

**Comment by Derekf5** [comment]
@myleshorton Not sure who to assign this one to... here is the spec for the desktop version,
The only new graphic on this screen is the "x" to deauthorize a device, here is the link to its location in dropbox. https://www.dropbox.com/s/7go9rr9snb3tx8o/Xfordeauthorizedevice.svg?dl=0
![tempaccountmanagescreen](https://cloud.githubusercontent.com/assets/7864729/15721767/6c5d7f8a-2808-11e6-85e8-25f2fab43b48.png)

**Comment by atavism** [comment]
@Derekf5, what about seeing my current number and being able to add/edit an e-mail address?

**Comment by percyalpha** [comment]
I don't think we need to design the email option now. (We're gonna add email login later right?) But yeah, showing my current phone number is needed

**Comment by atavism** [comment]
@percyalpha Not to login with, just so that the user has the option to attach an e-mail address to his account. It gives us a way to respond directly when the user has a support request, sends us his logs, or leaves feedback. I guess we don't need it right away though.

**Comment by Derekf5** [comment]
Hey @percyalpha @atavism here is the updated spec sheet with phone number. @atavism some of the padding etc had to change to fit this in, but it is all noted on the diagram.
![account-management-specs](https://cloud.githubusercontent.com/assets/7864729/15726638/f87eccfa-281f-11e6-89e7-6ec10ac54746.png)
