### ISSUE TITLE
 horizontal scrolling bar is present and the template is off

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4410]
Chrome with windows 10

 the horizontal scrolling bar is present and the template is off. Making the windows larger won't help
![image](https://cloud.githubusercontent.com/assets/7925929/15655089/b5eb1632-264e-11e6-9127-6433b4dd67f8.png)

**Comment by Derekf5** [comment]
@percyalpha removing the design label because this is design implementation bug, rather than a design update.

**Comment by percyalpha** [comment]
This is still present on the new build June 2

**Comment by myleshorton** [comment]
This is interesting @percyalpha -- I don't get it on OSX but will check Windows. Do you also get that "free monthly data" in the top right spilling over to the next line like that?

**Comment by myleshorton** [comment]
ok I've got a fix for this that will go in tonight @percyalpha -- good catch!

**Comment by myleshorton** [comment]
Just committed it.
