### ISSUE TITLE
Present a way for users to log out

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4413]
If users want to use Pro temporarily on a shared computer/friend's computer, they want to be able to log off afterwards. Now even if users uninstall Lantern, the account is not logged off and will be back after reinstall

**Comment by percyalpha** [comment]
@Derekf5 I just realized, the account management UI https://github.com/getlantern/lantern/issues/4405#issuecomment-223133530 doesn't provide a way for users to log out, but only change phone number.

**Comment by Derekf5** [comment]
The X next to each device is the logout @percyalpha should this be more clear?  Users can also deauthorize from any of their other devices, similar to itunes.

**Comment by percyalpha** [comment]
@Derekf5  If I de-authorize all devices on iTunes, I'm still logged in to that iTunes account at that time. 

If I click x, the expected behavior is that the specific device will be removed from the account page with perhaps some animation but I would still be in the same account management page.  Perhaps we can replace the X for this own device to a log out.

**Comment by sunshine19090** [comment]
@Derekf5 @percyalpha Again, I feel login and logout is little misleading as we really don't have a pure login procedure like an user id and password. So my opinion is to keep the wordings as Authorize and de-authorize. The X may work pretty good but I believe not many users will understand what they do. If we gonna stick with X mark, then we could add an explanation that the user can de-authorize a device by clicking on it.

**Comment by percyalpha** [comment]
@sunshine19090 Phone number + SMS is a login in procedure for many apps. Perhaps authorize/deauthorize is more accurate but users are more familiar if you call it log in/ log out.

@Derekf5 For other devices, clicking x would mean de-authorize (but we never use that word, we just use the icon). For the current device, we should explicitly say log out

**Comment by Derekf5** [comment]
Yes @percyalpha it sounds like a good idea to just have a logout instead of an X next to the device the user is on.

**Comment by Derekf5** [comment]
Hey @p3rcya @atavism here is the updated account management with log out

Changes include current device was moved up above the authorized device lines,
Changed the x's for deauthorize device to "remove"
Added "Logout" text next to current device.
![account-management](https://cloud.githubusercontent.com/assets/7864729/15863313/862447ea-2ca0-11e6-9f2a-2e6b8f6dd92e.png)

**Comment by carsonefv** [comment]
Hey @p3rcya @myleshorton Here is the updated account management screen for Desktop with Phone number and Log out

Changes include: 
• Added Verified Phone Number line
• Current device was moved up above the authorized device lines
• Changed the X's for de-authorize device to "REMOVE"
• Added "LOG OUT" text next to current device.

![screenshot 2016-06-07 11 34 09](https://cloud.githubusercontent.com/assets/4400763/15864208/2e71f390-2ca4-11e6-86c6-50809ca805fd.png)

**Comment by carsonefv** [comment]
I'm creating a new ticket for this specifically for Desktop : https://github.com/getlantern/lantern/issues/4563

**Comment by Derekf5** [comment]
same but for mobile #4564   closing this now.
