### ISSUE TITLE
stuck at Pro main page 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4414]
On Windows 10 with Edge (Chrome not installed). 
Opening Lantern, it is stuck at this page

![image](https://cloud.githubusercontent.com/assets/7925929/15655345/2a507042-2651-11e6-952b-4939cab685d6.png)

**Comment by percyalpha** [comment]
The problem persists after Chrome is uninstalled and NOT set to default browser. But after setting Chrome to be default browser, the pages loads correctly in Chrome. It seems the page is incompatible with Edge
