### ISSUE TITLE
 If I entered the phone number first, then select the country code, it's not handled correctly.

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4416]
If I enter my phone number first, then change the country code, Lantern still uses the old country code. 

![image](https://cloud.githubusercontent.com/assets/7925929/15655589/49e1fd02-2653-11e6-8d52-014a07a332d6.png)

**Comment by percyalpha** [comment]
Still presents in 20160603

**Comment by myleshorton** [comment]
Thanks @percyalpha -- I'll take this one.

**Comment by p3rcya** [comment]
Phone number no longer used
