### ISSUE TITLE
Free users getting Pro time

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4417]
Currently, a free user can share referral code and get free Pro time. This is very good. But is this actually intended and handled correctly? Because free user won't need phone/email verifications, but we still need to tie the free time to the user.

**Comment by percyalpha** [comment]
@sunshine19090 We need to test for this situation. The expected behavior is the free Pro user can use it on his device only if he doesn't verify his phone number. When he does, he can use the Pro time in any devices he authorized

**Comment by Mjchae1** [comment]
I don't know which to be more frustrated by - the fact that 100's of thousands of us are being excluded from this offering, or the fact that you are discussing our exclusion, in our face, without any seeming regard - if I am wrong, forgive me, but that is the scene unfolding before me, here.
