### ISSUE TITLE
Copied text during referral 

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4418]
When copying the referral code, the copied text is "use my code xxx to earn 1 Pro credit". Per our conversation with Chip, we should use text like "Use my code xxx and get 3 months free when you sign up for two year plan or 1 month free when you sign up for 1 year plan".  NEVER use the word credit anywhere please. No one in China knows what credit means.

**Comment by carsonefv** [comment]
@myleshorton @atavism can we update the text copied during referrals as shown above?

**Comment by percyalpha** [comment]
This is still not changed in the latest build 0603

**Comment by myleshorton** [comment]
Closed via https://github.com/getlantern/lantern-desktop-ui/commit/0d93146a1a6d007b14ca1dfb390ec3c4e6c92547

**Comment by Mjchae1** [comment]
Dear Ghost,
If you're going to make broadly sweeping generalizations, more accurate language would be:   the term "credit" is not very well understood, among China's general population, especially in the context being used in this instance.  As it is written, personally, I find your comment insulting, and, realistically speaking, impossible.
