### ISSUE TITLE
Add a login option on the main page

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4420]
Existing Pro users won't immediately see an log in Option on the main page without going to the setting. 

I suggest moving the authorize device for Pro into our main screen, in the blank space at the button, say "if you have a Pro account already, please log in here"

![image](https://cloud.githubusercontent.com/assets/7925929/15655786/0b048cc4-2655-11e6-85eb-77f6c66eeefd.png)

**Comment by percyalpha** [comment]
@Derekf5 I'm not clear on this. Are we going to have this page showing by default on the index? If so, then we should have a log in option.

**Comment by Derekf5** [comment]
That makes sense to me @percyalpha , what do you think @WolfLantern and @carsonefv?

**Comment by WolfLantern** [comment]
i think that makes sense

**Comment by Derekf5** [comment]
@carsonefv assigning this to you, since i will be ticketing all the mobile issues. 

@WolfLantern @percyalpha does this mean we want this on the main page of mobile?   We really dont have any more space to add anything there, so i advise keeping the option in the menu...

**Comment by carsonefv** [comment]
Thanks for the suggestion @percyalpha 
@myleshorton do you think this is something we have time to implement now or should it be further down the line?

**Comment by carsonefv** [comment]
For Desktop we could just add some text near the bottom of the screen like: "Already have a Pro account? Log in here" and that would link to the login/authorize pop-up, what do you think @percyalpha @WolfLantern @Derekf5 ?

**Comment by Derekf5** [comment]
Yeah this is a good case for a text link @carsonefv

**Comment by percyalpha** [comment]
@carsonefv @Derekf5 Yeah, I agree it can just be a text link on desktop. 
We can leave mobile as before. As mobile users are more likely to click on the menu

**Comment by sunshine19090** [comment]
@percyalpha I agree but instead of login we could say "authorize device".

**Comment by percyalpha** [comment]
@sunshine19090 Most Chinese users are not familiar with authorizing a device. But they're familiar with logging in. Wechat/telegram and other apps use a phone number, but they still call it log in

**Comment by carsonefv** [comment]
@p3rcya @myleshorton Here are the specs for adding this text link to the Desktop main screen:

![screenshot 2016-06-07 11 59 46](https://cloud.githubusercontent.com/assets/4400763/15865100/766b3852-2ca7-11e6-82fc-393d5f81e2d1.png)

**Comment by myleshorton** [comment]
Just added to the backlog guys thanks.
