### ISSUE TITLE
UI: Header and Footer bar issues

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4426]
1. Header should be 46px high with no drop shadow
2. Footer bar should be the same color as the header #00838f
3. "lantern is on, you can access blocked sites" text is too far left. Right margin should be 16px. (see attached image)
4. Data cap bar and text should all be right aligned.
5. Data cap tab is too high. Should be 56px (see attached image)
     ![lantern-is-on](https://cloud.githubusercontent.com/assets/7864729/15679307/59766a74-271f-11e6-9679-3b7e43bb0868.png)
<img width="634" alt="screen shot 2016-05-31 at 11 04 18 am" src="https://cloud.githubusercontent.com/assets/7864729/15679342/87a8b35c-271f-11e6-85c9-81e6d48fc2bb.png">

**Comment by fffw** [comment]
One problem for 3 is that the text length varies among languages. We have to leave enough room for the longest text.

**Comment by fffw** [comment]
About 5, it leaves 56-13*2=30px for the progress bar and two lines of text, which should be insufficient

**Comment by Derekf5** [comment]
OK thanks @fffw , i would just ignore number 5 for now then!  thanks!
