### ISSUE TITLE
UI: Main page buttons issues (free user)

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4427]
1. Get Free Pro Credits, and Buy Pro Now buttons: Border Radius should be 4px
2. Buy Pro Now button wrong color:  Should be #ff4081
3. Padding between buttons should be 69px
4. On button click text is highlighted while button shows click:  Remove text highlight (see attached image)
![screenshot 2016-05-31 11 14 28](https://cloud.githubusercontent.com/assets/4400763/15679757/fe266cd0-2720-11e6-9a1f-92b5cdb329f0.png)

**Comment by fffw** [comment]
I ended up remove the background color of text area so the highlight still applies, but to the whole area.

![image](https://cloud.githubusercontent.com/assets/10410437/15744372/29749ae0-28fe-11e6-893d-89e08c6ca6b9.png)

**Comment by Derekf5** [comment]
Perfect thanks @fffw!
