### ISSUE TITLE
UI: Main page copy issue

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4431]
1. Under the pro benefits list , "Faster" should read "Faster Speed"
2. Remove period after "Better than a VPN"

**Comment by fffw** [comment]
@Derekf5 About point 1, I changed the font size from 24px to 18px to makes the feature list still fit in one line. The check mark looks a bit larger than text, I just don't know what the correct size should be.

![image](https://cloud.githubusercontent.com/assets/10410437/15744999/060ff758-2902-11e6-94d9-d59d2f9f75c9.png)

**Comment by Derekf5** [comment]
Thanks @fffw.  @carsonefv what do you think about this, should we drop the size of the check mark?

**Comment by carsonefv** [comment]
@fffw @Derekf5 the checkmark size looks fine to me, thanks!

**Comment by fffw** [comment]
Great I'll keep it as is
