### ISSUE TITLE
UI: Burger menu and Lantern header text highlights on hover

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4434]
This should be eliminated (for Free and Pro main screen), the mouse turning to a hand is enough of an indication to click.
![screenshot 2016-05-31 11 44 13](https://cloud.githubusercontent.com/assets/4400763/15680847/21cb7d8e-2725-11e6-845c-59236b4055d9.png)

**Comment by fffw** [comment]
Closed by getlantern/lantern-desktop-ui@fea6ff53f5f6adc18859e53cea2ab9070d17ba2b
