### ISSUE TITLE
UI: Update "About" pop-up screen with specs

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4441]
"About" Screen Specs: 

**Illustration (Lantern Logo):** Height: 113px; Width: 113px
     - Padding: left/right: centered; top: 117px
**Text: “Open Internet for Everyone”**
     - Font: Roboto Regular;
     - Font Size: 24px;
     - Color: #000000;
     - Padding top: 254px; Left/Right: Centered;
     **“Lantern is an application that delivers fast, reliable
and secure access to the open Internet”**
     - Font: Roboto Regular;
     - Font Size: 14px;
     - Color: #000000;
     - Padding top: 286px; Left/right: Centered
     **“QUESTIONS?
READ THE LANTERN FAQS”**
     - Font: Roboto Regular;
     - Font Size: 14px;
     - Color: #29bcd2;
     - Text Transform: Uppercase;
     - Padding top: 362px; Left/right: Centered;

![screenshot 2016-05-31 12 57 17](https://cloud.githubusercontent.com/assets/4400763/15683184/0e9485b2-272f-11e6-8ac6-6c7b275ef3a5.png)

**Comment by fffw** [comment]
The link color `#29bcd2` looks like below.
![image](https://cloud.githubusercontent.com/assets/10410437/15805215/d0bb87b0-2b55-11e6-8e38-6edeb65ad4e8.png)
