### ISSUE TITLE
UI: Lantern Pro Plans pop up issues

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4442]
1. Change "PRO" to "Pro"
2. "Faster" should read "Faster Speed"
3. Top cyan section should have a drop shadow 
4. Line between the two plans should be #767676
5. all of the plan text should have 87% opacity
6. "SELECT" yellow button text should be 100% opacity
7. Both buttons font should be Roboto Medium(500) 14pt
8. Top and bottom padding on price text should be 13px

**Comment by carsonefv** [comment]
Here is the updated Payment Plan screen for Desktop - these changes need to be completed in addition to the issues above that Derek listed:

1. Add Checklist Feature "Three Devices" and move all features up to accommodate

2. Add supported devices text: "For Windows, Android, Mac, Ubuntu. iOS coming soon"
Font: Roboto Light(300); size: 14pt; color: #FFFFFF; padding top: 230px;

3. Prices need to be updated to reflect: 1 Year Plan: $27 (USD); 2 Year Plan: $48 (USD)

updated should look like this: 
![screenshot 2016-06-02 11 12 20](https://cloud.githubusercontent.com/assets/4400763/15750055/e27b65a6-28b2-11e6-9425-86a7b76a79f2.png)

**Comment by fffw** [comment]
Didn't implement point 3 yet because I couldn't show shadow above the "best value" badge. Will try to find a way later.

**Comment by carsonefv** [comment]
This isn't appearing updated yet, should i see it in the latest version?

**Comment by myleshorton** [comment]
Which part @carsonefv? All of it?

**Comment by myleshorton** [comment]
I'm actually going to put this back in the backlog and break out the pricing change into a separate ticket here:

https://github.com/getlantern/lantern/issues/4573

**Comment by carsonefv** [comment]
@afisk the latest screen here shows what needs to be updated, should I make individual tickets for #1 and #2?

1. Add Checklist Feature "Three Devices" and move all features up to accommodate

2. Add supported devices text: "For Windows, Android, Mac, Ubuntu. iOS coming soon"
Font: Roboto Light(300); size: 14pt; color: #FFFFFF; padding top: 230px;

3. Prices need to be updated to reflect: 1 Year Plan: $27 (USD); 2 Year Plan: $48 (USD)

updated version should look like this: 
![e27b65a6-28b2-11e6-9425-86a7b76a79f2](https://cloud.githubusercontent.com/assets/4400763/15878056/f84c08e0-2ce5-11e6-8932-918a3f830396.png)

**Comment by myleshorton** [comment]
Yeah that's fine @carsonefv, but this is unlikely to make it into this version except for the pricing change.

**Comment by fffw** [comment]
@carsonefv The first 3 feature highlights also appear on the free screen. Should we add the 4th there too?

**Comment by ZonekWang** [comment]
是吗？

**Comment by carsonefv** [comment]
Hey @fffw, we're only going to include the 4th one on the price plan, thanks for checking
