### ISSUE TITLE
Add data cap indicator to Mobile designs

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4445]
Similar to the desktop version

**Comment by Derekf5** [comment]
Hey @atavism here is the design, and specs for the data cap indicator

**Background:** #FFFFFF

**"200/500MB Remaining of your free monthly data":** Roboto Bold(600), 10pt, #000000

**"Upgrade to Pro for unlimited data":** Roboto Light(300), 10pt, #000000

**Data Bar:**Width; 225dp, Height; 6dp, corner radius; 3dp, background color; #0297A7, indicator color; #FEE900, Inicator color within 100mb of cap; #FF4081
![datacap-specs](https://cloud.githubusercontent.com/assets/7864729/15718904/88a0dd8e-27fb-11e6-8469-bc5287fa23c4.png)

**Comment by atavism** [comment]
Thanks, @Derekf5! It looks really nice. What do you think about adding an "Upgrade" button in the bottom corner?

Do we only want to display the data usage summary on the side-menu or on the home screen also? We could possibly have it in both depending on how cluttered it looks, and it's easy enough to implement it that way. Only asking because this is what Tunnel Bear has for instance, and, to me, seeing it on the home screen would be a more prominent reminder I should upgrade? Anyway, I'll put it in the side-menu for now though!

CC: @WolfLantern 

![image](https://cloud.githubusercontent.com/assets/6346213/15724587/9a036d3e-27fc-11e6-9c9b-fd82c34b03e9.png)

**Comment by WolfLantern** [comment]
i guess your thinking Derek is that it clutters the home page and newsfeed? Have you tried a version of this Derek?

**Comment by Derekf5** [comment]
Hey @WolfLantern @atavism you hit the nail on the head Wolf.   I prefer to keep things as simple as possible, and am worried that it will clutter.    The reason it is successful in the image above IMO is that there is no real content to take away from.  

As far as an upgrade button in the menu, i think we should just change the language on the menu item from "get pro now" to upgrade to pro, and that would serve the purpose.  A button on the menu seems odd to me when we already have menu items.   

I will give the home screen ticker a shot and see what it looks like.

**Comment by WolfLantern** [comment]
cool and understood. great, would be awesome to see a version of the ticker on the home page with an upgrade button...lets see, you never know

**Comment by Derekf5** [comment]
Ok just another note on this @WolfLantern @atavism, we are planning on "pinning" an ad for pro in the feed, if we do both of these things, along with the header effectively only 50% of the screen will be the feed...

**Comment by atavism** [comment]
Yeah, I'm thinking the data usage summary would look nice on the home screen because we already have a header at the top for the toggle button that's a similar size. A footer would complement it nicely, with the newsfeed in-between.

**Comment by atavism** [comment]
What is the ad going to look like, could you send an example?

**Comment by atavism** [comment]
Another option is to put the data usage summary next to the toggle button above the newsfeed.

**Comment by Derekf5** [comment]
Hey @atavism @WolfLantern we dont have an example for the ad yet, bc we are trying to knock out all of the other changes we need, but im hoping to have something to show you by tm :).

Here is an example of how the layout could look based on that you all have suggested.
<img width="323" alt="screen shot 2016-06-01 at 4 59 57 pm" src="https://cloud.githubusercontent.com/assets/7864729/15725557/80df523c-281a-11e6-909b-3047a362d09a.png">

Perhaps what we could do is make the ad dynamic to start out, and display how much data the users has left inside of the ad, we could also pin that ad as a footer instead of a header kind of killing two birds... what do you all think?

**Comment by Derekf5** [comment]
I meant to say i think the above version limits the size of the newsfeed too much, which is why im advocating for the ad with data left info incorporated.

**Comment by atavism** [comment]
Yeah, I love making the data usage summary part of the ad for Pro and putting it in the footer. Looks great to me.

**Comment by Derekf5** [comment]
Cool @WolfLantern does that sound good to you?   @atavism i guess in that instance we would keep the data indicator in the menu also.

**Comment by WolfLantern** [comment]
thats a pretty awesome idea derek

**Comment by WolfLantern** [comment]
but does that mean we always need to pin an ad to the top of the feed?

**Comment by WolfLantern** [comment]
of sorry, i see what you mean, pin it as a footer @Derekf5. thats really interesting

**Comment by WolfLantern** [comment]
and yes, i guess it would be a good idea to keep the indicator in the menu also

**Comment by Derekf5** [comment]
cool, so lets implement the menu version @atavism , and i will design the ad tomorrow morning.  @WolfLantern i might ping you early tm if you have availability for a quick chat on this.

**Comment by WolfLantern** [comment]
sounds great @Derekf5

**Comment by myleshorton** [comment]
I like the footer

**Comment by Derekf5** [comment]
Hey @atavism, @WolfLantern  and I just spoke, and since the ad will be pretty permanent as the footer, and include the data indicator on the main page we are going to nix the data cap indicator in the menu.

Im going to close this ticket, all of the specs for the ad/dataticker will be in the ticket #4448
