### ISSUE TITLE
Change the text sent to users

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4447]
"Lantern code: xxx" -> "Pro code: xxx" 
Harder to filter

**Comment by carsonefv** [comment]
@atavism @myleshorton can we update the text message copy that gets sent to users as shown above?

**Comment by atavism** [comment]
Sure, @carsonefv! @uaalto assigning this one to you to make the change on the Pro server.

**Comment by uaalto** [comment]
Done here: https://github.com/getlantern/pro-server/pull/103

**Comment by percyalpha** [comment]
confirmed
