### ISSUE TITLE
IE - Only a blank blue screen is displayed after installing Lantern pro

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4449]
![image](https://cloud.githubusercontent.com/assets/11394369/15686882/fce886a4-2726-11e6-9bad-c8e6a1607078.png)

**Comment by xiam** [comment]
Confirmed and logged https://github.com/getlantern/lantern/issues/4446

**Comment by fffw** [comment]
But in this case, the URL is 127.0.0.1:16823, not ui.lantern.io. Can it be different reason?

**Comment by xiam** [comment]
Good catch @fffw, this may be a different thing, could we see the console's output @sunshine19090?

**Comment by sunshine19090** [comment]
@fffw @xiam 

IE console output in windows 7:

![image](https://cloud.githubusercontent.com/assets/11394369/15755705/e234e586-28b2-11e6-958d-8ac00512d74c.png)

Firefox console output in windows 10:

**Comment by sunshine19090** [comment]
Any updates on this @xiam @fffw ? I still have this problem. Safari also opens a blank screen.

**Comment by myleshorton** [comment]
Safari on OSX @sunshine19090 or Safari on Windows?

**Comment by myleshorton** [comment]
I'm seeing something similar on IE 11 in Win8 @sunshine19090, so we'll figure it out.

**Comment by xiam** [comment]
The original problem was fixed, this compression thing looks different. However, latest dev version works for me on Safari (osx) and Edge + Firefox (windows). Does current dev fail for you too @myleshorton?

**Comment by myleshorton** [comment]
It actually fails for me in *all browsers on win8* @xiam, including Chrome.

**Comment by myleshorton** [comment]
I've got a decent read on this @xiam -- looks like some incompatibility with jquery actually, but luckily we only use jquery in the TelInputField that we're no longer using!! Let me see if I can knock it out -- one sec.

**Comment by myleshorton** [comment]
Yeah it loads if we get rid of TelInputField @xiam, so it should just be fixed with your changes to use email verification instead!

**Comment by xiam** [comment]
The WIP is here: https://github.com/getlantern/lantern-desktop-ui/tree/issue-4679, I'll remove the special input field for phones. Did you test the master branch?

**Comment by myleshorton** [comment]
Yeah I tested against master running locally on win8 with just removing TelInputField @xiam, and it loads fine then.

**Comment by sunshine19090** [comment]
Just FYI @myleshorton -  I am using safari on OSX. Yeah, I was using a older version of FF for automation purpose but the latest FF works fine in both win 7 and OSX.

**Comment by myleshorton** [comment]
OK intersting @sunshine19090 thanks. Safari has always worked for me, but I'll be curious if @xiam's changes fix it for you when we get those out in a new build.

**Comment by xiam** [comment]
Just removed that input, seems to be working here. The branch is blocked, needs some stuff from server side, it can be tested, tho.

**Comment by myleshorton** [comment]
@sunshine19090 this should definitely be fixed FYI.

**Comment by sunshine19090** [comment]
@myleshorton @xiam it still looks the same to me. A white blank screen in both safari in OSX and IE 11 in win 7.

**Comment by myleshorton** [comment]
Weird. I'm run it hundreds of times on Safari, and it's working for me in Chrome and FF on Win7 and Edge on Win10. I'll install IE11 tomorrow.

Do you see any errors in the console @sunshine19090?

**Comment by fffw** [comment]
I got the same error as @sunshine19090 on IE10/Win 7. Will build a non-minified version to try.

> SCRIPT5022: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
bundle.js, line 1 character 1090

**Comment by sunshine19090** [comment]
I don't see any error message in win 7/IE 11 console but I got this in OSX/Safari.

<img width="1280" alt="screen shot 2016-06-22 at 12 15 33 pm" src="https://cloud.githubusercontent.com/assets/11394369/16280193/44411f36-3873-11e6-852a-5cabd389660f.png">

**Comment by myleshorton** [comment]
I was able to reproduce this on both Win7 and Win10 with IE11. It's definitely something with the minification, as it works with `npm start` no problem but breaks hitting at static server with output from `npm run build`

**Comment by fffw** [comment]
So the actual error is:

> ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React. 

The code triggers this error is `ReactMount._renderSubtreeIntoContainer: function(parentComponent, nextElement, container, callback)` at https://github.com/facebook/react/blob/9ba5668d1828148c019aaf40ff7662824611d17c/src/renderers/dom/client/ReactMount.js#L403

And the `nextElement` is
```
type	function I18nextProvider(props, context) {
...
```

**Comment by fffw** [comment]
I won't dig into the details as xiam has fixed it in https://github.com/getlantern/lantern-desktop-ui/issues/144. Leave it here for record.

**Comment by sunshine19090** [comment]
working fine now
