### ISSUE TITLE
After running a youtube video for 20 mins, the indicator shows 0 MB remaining even for free users when refreshed.

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4452]
It shows 0 MB when refreshed or reopened lantern but changes to 500 MB again. It keeps going back to 0MB when refreshed or reopened lantern.

**Comment by fffw** [comment]
https://github.com/getlantern/lantern-desktop-ui/pull/73 should partly fix it by not showing 0MB when Lantern page is initially open.

To consume Lantern traffic in uncensored area, "proxy all traffic" option should be ticked.
