### ISSUE TITLE
Complete purchase page whenever redirect fails

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4453]
Hey @Derekf5, this is the last design we need I believe. If the user is paying with Alipay via a browser redirect, and after Stripe has validated the payment info we're unable to redirect him back to the app, then we need a failover page that appears with a button to complete this action. I think our logo, some descriptive text, and a large button should suffice? In practice, users should rarely encounter this.

**Comment by Derekf5** [comment]
@atavism so the purpose of the button on the page is to bring the user back to lantern, correct?

**Comment by atavism** [comment]
@Derekf5 Yes, that's correct.

**Comment by carsonefv** [comment]
@atavism @Derekf5 This should be a full page design rather than some kind of pop-up, correct?

**Comment by Derekf5** [comment]
Correct @carsonefv

**Comment by carsonefv** [comment]
Hey @atavism @Derekf5 here is the design and specs for the post-payment redirect page

Top and Bottom Blue Stripe (same as App):
Width: 100%
Height: 4dp
Color: #00bcd4

Background: #FFFFFF

"Thanks for your purchase of Lantern Pro!": Roboto Medium(500), 16pt, #000000

Button (same as app buttons)- Background: #ff3f80, Text: #FFFFFF, Roboto Medium(500), 14pt

<img width="462" alt="screenshot 2016-06-01 14 11 55" src="https://cloud.githubusercontent.com/assets/4400763/15720868/47c24268-2804-11e6-976a-73a5af7dea64.png">

**Comment by Derekf5** [comment]
thanks @carsonefv LGTM.
