### ISSUE TITLE
UI: Pro Main page text issues

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4454]
1. Header text "Lantern PRO" Should read "Lantern Pro" with the word "Pro" not in all caps

2. Footer text (Version number, and Lantern is on notification) appear to be Helvetica or Arial, and too large: Should be Roboto Medium(500), 13pt

3. The text "Invite friends, get Pro credits" should be changed to "Invite friends, get Pro for free"

4. The text "Earn a free month for every friend that signs up." needs to be updated to read "When your friends purchase the two-year plan you will each get 3 months free, the one-year plan gets you each 1 month free"; text is the incorrect weight, and opacity: Should be Roboto Regular(400), 24pt, 100% Opacity

4. Text for "Your Referral Code" is wrong font size, should be Roboto Medium (500) 12pt

5. Small description text "When friends use your code to purchase Lantern PRO" should be deleted 

see image for correct appearance and copy:
![screenshot 2016-06-02 10 48 05](https://cloud.githubusercontent.com/assets/4400763/15749178/7eef95a0-28af-11e6-8cb8-0f8d21e47847.png)

**Comment by sunshine19090** [comment]
@carsonefv This looks good to me now. Assigning it to you for final verification and closing.

**Comment by Derekf5** [comment]
@sunshine19090 @carsonefv is out till tomorrow, but this LGTM!
