### ISSUE TITLE
Espresso Tests + use Wercker/Travis for Android testing

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4455]
Update Travis CI to automatically run any unit and instrumented tests for every new Android build: https://docs.travis-ci.com/user/languages/android

**Comment by myleshorton** [comment]
In `lantern-build` we currently only integrate with CI for the go code. Moving back to backlog for now.

**Comment by myleshorton** [comment]
Closing this for now -- can revisit with updated ticket.
