### ISSUE TITLE
Give users access to multiple servers

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4457]

**Comment by myleshorton** [comment]
Let's break this one up into smaller tickets.

**Comment by p3rcya** [comment]
We might not want to do this! Let's discuss internally first

**Comment by myleshorton** [comment]
Hey @aranhoide and @oxtoacart any more thoughts on how we can do this? Can we break this apart into simpler pieces?

**Comment by p3rcya** [comment]
@myleshorton I don't think we should focus on this yet or provide this to free users at all.

**Comment by myleshorton** [comment]
Care to elaborate @p3rcya? Feel free to discuss offlist if necessarry.

**Comment by p3rcya** [comment]
Lantern Free shouldn't have the UI to select country
