### ISSUE TITLE
Change Plans page to reflect recent changes in Plan costs/benefits MOBILE

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4462]
Plan information here:
https://docs.google.com/document/d/15btMgh7viSYp6JZccuTUd5q0TJgo27dPQTRteT_-BU4/edit?ts=574de1ac

**Comment by Derekf5** [comment]
@atavism the only change here is the padding noted in the attachment, and the prices, and upsell text
<img width="440" alt="screen shot 2016-06-01 at 3 10 16 pm" src="https://cloud.githubusercontent.com/assets/7864729/15722308/09aff0d6-280b-11e6-96b6-7f32d97aa33a.png">

**Comment by percyalpha** [comment]
Looks good. One thing I want to clear is about the 3 devices. We want to make it explicit that users can use desktop+ mobile, not just 3 mobiles. 
Maybe we can add another tick mark at the button center 
✓ Support Windows, Mac, Android and Ubuntu. iOS coming soon 

@chipstehr

**Comment by Derekf5** [comment]
Hey @percy @atavism @chipstehr here is the updated specs with percy's suggestion, i didnt add what we support as a feature, because that seems odd, so i just added it as a note.
![plansspecsheet](https://cloud.githubusercontent.com/assets/7864729/15726867/22a56948-2821-11e6-9e9b-fa97a6abb985.png)

**Comment by percyalpha** [comment]
Cool. 
Can you say "Windows, Android, Mac and Ubuntu. iOS coming soon"? Few ppl use Mac in China

**Comment by Derekf5** [comment]
Sure @atavism please note @percyalpha's ordering change.
