### ISSUE TITLE
The phone number in the error message is different from the phone number entered

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4464]
![image](https://cloud.githubusercontent.com/assets/11394369/15692668/97b4f678-2744-11e6-955c-a905a613ddb2.png)

**Comment by fffw** [comment]
Good catch. The `TelInputField` won't collect the phone number if the format is invalid. Need to give some visual clue to the user.

**Comment by sunshine19090** [comment]
NA
