### ISSUE TITLE
The example phone number should be in grey text and should go away when clicked on the phone number text box

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4465]
I think this problem exists only in Firefox. The example phone number isn't going away. It looks like hardcoded text.

**Comment by fffw** [comment]
Which OS and Firefox version you are using to test @sunshine19090 ? I'm trying to reproduce but no luck.

**Comment by sunshine19090** [comment]
@fffw I tried it by reinstalling and it looks fine now. Probably, it was a specific scenario. Closing this for now.
