### ISSUE TITLE
Always getting an error message when trying to use Promo code(referral code)

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4471]
![image](https://cloud.githubusercontent.com/assets/11394369/15693422/f5522062-2749-11e6-9718-9185a8a9a0a6.png)

**Comment by myleshorton** [comment]
I suspect this was the result of a database reset or something @sunshine19090. Where are you getting the referral code from? I'm not seeing this on my end.

**Comment by sunshine19090** [comment]
@myleshorton I get this error from day 1 I started testing pro. I used one pro account and got the promo code from there and tried to use it in another device with different phone number. I could never get past that error message.

**Comment by sunshine19090** [comment]
I will try with the new build today and let you know.

**Comment by myleshorton** [comment]
Can you try this promo code:

XLLLLX

**Comment by sunshine19090** [comment]
@myleshorton I tried the code that you have mentioned. I don't get error message but the Apply promotion is just disabled, I am not getting any message. I expected it to take me to the checkout directly after applying the promo code. 

When I continued to checkout after applying the promo code, I entered all the details and clicked on the submit button. It just came back to the referral promotion screen without any message.

**Comment by sunshine19090** [comment]
One more update - it eventually started showing the loading spinner when I clicked on the close button to go back to the main page.

**Comment by xiam** [comment]
The code input isn't working for me either but this does not seem to be a backend problem, working on a fix.

**Comment by sunshine19090** [comment]
Now the field accepts promo code and directs to checkout screen. I still get error at times for which I have raised a separate ticket.
