### ISSUE TITLE
Menu in Lantern pro UI is always displayed in Chinese even when the browser and system settings are in English

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4473]
![image](https://cloud.githubusercontent.com/assets/11394369/15698274/baae830a-2777-11e6-973d-a165b19e4d82.png)

**Comment by fffw** [comment]
So `asyncSetLanguage` is called to save "language" as a settings entry to Lantern backend, but backend doesn't handle it.

I think we should persist user's chosen language to `settings.yaml`, so the display language of Lantern UI in each browser, the systray, and any notification can be in sync. Your opinion @xiam ?

**Comment by xiam** [comment]
I think that's a good idea @fffw

**Comment by myleshorton** [comment]
It seems like something on the frontend might have fixed this independently, as you're no longer seeing it right @sunshine19090? Is the backend fix still necessary @fffw?

**Comment by sunshine19090** [comment]
Yes @myleshorton, I am not seeing this now.

**Comment by sunshine19090** [comment]
Shall I close this ticket now @myleshorton @fffw ?

**Comment by fffw** [comment]
@myleshorton There are still a few things that require the backend fix:
1. The language dialog always has English checked after refresh, though the display language has changed (i18next persisted its config in local storage).
2. Switching language doesn't affect other browsers / systray, or when accessing through another address. It should be true on Edge, where the UI address can switch between ui.lantern.io and 127.0.0.1:16823.

BTW @myleshorton @xiam The backend PR is ready for review at https://github.com/getlantern/lantern-pro/pull/33

**Comment by myleshorton** [comment]
Ok @fffw I'll get to it!!
