### ISSUE TITLE
Mobile page formatting off

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4474]
![image](https://cloud.githubusercontent.com/assets/7925929/15698412/4658092a-2779-11e6-842e-1adc593a1271.png)
The test under the button should be on one line

**Comment by atavism** [comment]
Hey @percyalpha, thanks for testing! I think you're using an older version because this screen no longer exists! Awaiting some final design changes from @Derekf5 and then I'll send out a new build, probably by the end of the week.
