### ISSUE TITLE
Pro mobile translation

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4476]
The translation is mostly correct but very very awkward and not that appealing to the users. Please let me translate (and re-translate the existing ones). Please guide me through the translation process. Are we doing it via https://github.com/getlantern/lantern/issues/4397 ? Do I need an account there to translate?

![image](https://cloud.githubusercontent.com/assets/7925929/15698448/8e140bec-2779-11e6-9d55-91a10ded6988.png)

**Comment by atavism** [comment]
Hey @percyalpha, yeah we're doing it via Transifex. I just sent you an invite and uploaded the latest strings there

**Comment by atavism** [comment]
Going to close this ticket for now as this screen is no longer applicable. Please feel free to just update the translations on Transifex and I'll pull in the latest

**Comment by percyalpha** [comment]
@atavism Thanks. I'm waiting for the new mobile build for translation.
