### ISSUE TITLE
Pro UI - Settings Options text in settings screen is repeated below the header

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4482]
![image](https://cloud.githubusercontent.com/assets/11394369/15699481/0cb43cc6-2782-11e6-9bba-ca1ca502ae8f.png)

**Comment by fffw** [comment]
Interesting. What shown is the `alt` attribute when browser can't display `/img/illustrations/settings.svg`. 

Firefox has no problem display SVG. It could be Firefox failing to load the file. Refreshing page would work @sunshine19090 , but anyway we can remove the `alt` attribute of all header illustrations.
