### ISSUE TITLE
Create new page for pro mobile for when the feed is turned OFF

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4484]

**Comment by Derekf5** [comment]
Hey @atavism @carsonefv  what do you think about when feed is turned off reverting to to old non pro non feed screen here?  we could still pin the same ad i am designing at the bottom..

**Comment by carsonefv** [comment]
@Derekf5 @atavism Yes i think that's the best way to do it for now

**Comment by atavism** [comment]
Yeah sounds good to me!

**Comment by Derekf5** [comment]
@atavism will this be implemented for launch?

**Comment by Derekf5** [comment]
this is completed.
