### ISSUE TITLE
Change Plans page to reflect recent changes in Plan costs/benefits DESKTOP

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4485]
Plan information here:
https://docs.google.com/document/d/15btMgh7viSYp6JZccuTUd5q0TJgo27dPQTRteT_-BU4/edit?ts=574de1ac

**Comment by carsonefv** [comment]
Here is the updated Payment Plan screen for Desktop:

1. Add Checklist Feature "Three Devices" and move all features up to accommodate

2. Prices need to be updated to reflect: 1 Year Plan: $27 (USD); 2 Year Plan: $48 (USD)

updated should look like this: 
![screenshot 2016-06-02 10 58 09](https://cloud.githubusercontent.com/assets/4400763/15749586/e974f2b6-28b0-11e6-8c19-e7c686f8c34a.png)

**Comment by carsonefv** [comment]
This issue has some duplicates with another payment plan issue: https://github.com/getlantern/lantern/issues/4442
