### ISSUE TITLE
Create toast/snackbar notification on mobile when users is nearing data cap

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4486]
@myleshorton at what points are we sending the notification on desktop?  is it 100mb, and again at 50mb before the user reaches the cap?

**Comment by atavism** [comment]
@Derekf5 @myleshorton : should I be displaying a toast and/or push notification whenever the user is nearing the data cap?

**Comment by Derekf5** [comment]
@atavism Yes, both if we can. as well as every so often after the cap has been reached. 
it can read the same way that it does on desktop.
"You have used your free monthly data"
"Upgrade to Pro to continue using Lantern"
The frequency of the reminders should be the same as desktop, @myleshorton how frequently do they occur now?

**Comment by myleshorton** [comment]
Right now it's just displayed once per run of Lantern when you hit your cap @Derekf5 and @atavism, but I agree it should use something like the algorithm you described.

**Comment by atavism** [comment]
Here's what this looks like on mobile 
![image](https://cloud.githubusercontent.com/assets/6346213/16316232/6e2023b6-393a-11e6-849a-82f93ad216a1.png)

**Comment by Derekf5** [comment]
LGTM, thanks @atavism
