### ISSUE TITLE
[Windows] [PRO] Problem checking for update

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#4487]
A local windows 10 build of pro seems to have this problem:

```
Jun 01 17:31:31.657 - 0m2s ERROR autoupdate: autoupdate.go:97 Problem checking for update: Problem fetching update: invalid character 'E' looking for beginning of value
```

Sounds like a missing parameter that makes the update server reply with an error. The client should be able to recognize this situation and display the error instead of trying to unmarshal it into JSON.

**Comment by xiam** [comment]
This fix is going to provide more data on the error: https://github.com/getlantern/go-update/pull/2

**Comment by xiam** [comment]
Hey @myleshorton, I haven't run into this error yet, does this still happen to you when cross-compiling? I provided a fix that displays the full message (https://github.com/getlantern/go-update/pull/2), that could help us debugging the issue.

**Comment by myleshorton** [comment]
I'll try to reproduce it @xiam thanks!

**Comment by myleshorton** [comment]
This only happens when building 64 bit versions in development because in the field we never deploy anything but 32 bit, so the update server doesn't have anything for us.
