### ISSUE TITLE
Always showing 0 MB remaining for free users even after a fresh installation - Windows 10

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4491]
Need to check again in Windows 7.

**Comment by xiam** [comment]
This limit should persist, even after a fresh installation. Right @myleshorton?

**Comment by myleshorton** [comment]
Yeah for sure.

**Comment by sunshine19090** [comment]
Oh @xiam , when I wrote this ticket, I actually meant for a new user who never used the new lantern yet. Anyway, this is working fine now. Closing it.
