### ISSUE TITLE
A user can end up with too many referral codes depending on the number of devices connected

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4493]
Steps:

1. I used windows 7 to buy pro. I got one referral code in there.
2. And then used windows 10 to authorize. Now I have two referral codes. 

So, the user will be able to share more than one referral code with friends. I couldn't test the referral code function yet as I always end up getting a error message when using it. If this will not cause any problem, I think it should be okay.

**Comment by percyalpha** [comment]
Yeah, the referral code should be tied to the account, not the device. Multiple referral code is confusing to users

**Comment by sunshine19090** [comment]
Now once the user is pro, the same referral code is displayed in all the devices.
