### ISSUE TITLE
[Windows] Unable to complete a purchase

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#4495]
Happens randomly on Edge:

![screen shot 2016-06-01 at 10 15 06 pm](https://cloud.githubusercontent.com/assets/385670/15732946/c16fb91e-2846-11e6-8435-abd2d48a8858.png)

It only happeds after completing a purchase, but sometimes the purchase does not have any problem at all.

**Comment by myleshorton** [comment]
Oh this is awesome @fffw and @xiam -- totally missed that you fixed this!

**Comment by myleshorton** [comment]
What was the solution for this one @xiam? Just curious.

**Comment by xiam** [comment]
A rather simple one, the origin of the problem is still not clear to me but after the checkout we needed to close a dialog and open another one, we were doing this on a callback:

wait for server response -> close & open

For some reason the closing of the first dialog was interferring with the opening of the first one. What I did here was closing all the dialogs while waiting for a server response instead of waiting for a server response and close and open a dialog.

close -> wait for server response -> open
