### ISSUE TITLE
Pay for Pro using in-app purchase if available

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4496]
While the vast majority of our users won't have this enabled, it's still really convenient to pay for Pro using an in-app purchase. If the user has Google Play In-app Billing enabled, for whatever reason, we use it as the default option and then proceed to alternative methods.

**Comment by percyalpha** [comment]
This is not a priority as in China most people won't have the IAP for Play. However, they probably have the IAP for Apple App Store. So we can consider add Mac App Store version with IAP

**Comment by Derekf5** [comment]
@atavism could we just add a a third tab on the payment screen?  It could say android pay and clicking that tab would show the android pay button?

**Comment by p3rcya** [comment]
@Derekf5 No one would use that in China though

**Comment by Derekf5** [comment]
OK, @WolfLantern just mentioned android pay to me saying some users were asking for it.

**Comment by p3rcya** [comment]
@WolfLantern I've yet to see a single request like it from China. Maybe @WolfLantern read "android paid" as android pay

**Comment by Derekf5** [comment]
Right even if it doesnt matter to Chinese users i still think it can be valuable for worldwide growth @p3rcya

**Comment by p3rcya** [comment]
Then I suggest the option be hidden by default in the Chinese UI. Otherwise, it's confusing

**Comment by Derekf5** [comment]
cool @p3rcya that sounds like a reasonable solution, as long as @atavism thinks its doable.

**Comment by p3rcya** [comment]
@atavism @Derekf5 As most sold in China have the entire Google framework removed, adding this function in the check out page might cause Chinese android to crash. So this would have to be rigorously tested on Xiaomi and other Chinese android phones if such payment method were to be implemented. 

This is definitely NOT a priority right now and might be counter-productive.

**Comment by Derekf5** [comment]
OK @p3rcya SGTM, CC: @WolfLantern

**Comment by atavism** [comment]
We can just hide it for Chinese users? Most aren't redirected to the checkout screen anyway.

**Comment by atavism** [comment]
But yeah not a priority right now

**Comment by atavism** [comment]
We just need to decide what UI changes on the checkout screen are necessary for this but its integrated otherwise, @Derekf5

**Comment by Derekf5** [comment]
Hey @atavism pretty simple screen here, it should go after the referral code input. Each button should link to the respective payment method.   In addition we should remove the selector at the top of the in app credit card checkout screen.    These graphics are found in our shared dropbox under the folder "payment method buttons"
<img width="389" alt="screen shot 2016-09-01 at 4 44 07 pm" src="https://cloud.githubusercontent.com/assets/7864729/18184615/d49d2d82-7067-11e6-9075-c00a7d75f6c9.png">

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #174](https://github.com/getlantern/lantern-internal/issues/174) via [**ZenHub**](https://www.zenhub.com/)
