### ISSUE TITLE
ubuntu14.04 lts lantern2.0.1不能翻墙

### ISSUE THREAD

**Issue by Chanran** [getlantern/lantern#4501]
难道是校园网的锅?4月份的时候,lantern是连校园网都可以穿透的.现在貌似不可以了

**Comment by cnfanhua** [comment]
win10  lantern最新版 也不行了

**Comment by xiumiao** [comment]
应该是某个节日要到了吧, 我也突然上不了了

**Comment by VizXu** [comment]
什么节日？我的win7的可以用的

**Comment by cnfanhua** [comment]
终于搞定了。我的原因是 在电脑的不同账户下安装了多个lantern
解决办法就是 只保留当前账户下的lantern 删除其他

**Comment by Chanran** [comment]
没有用ubuntu的朋友出来解答一下么...

**Comment by paperplane1230** [comment]
没试过新版本么？2.0.1已经不能用了

**Comment by Chanran** [comment]
最新版本貌似也不行T-T

**Comment by p3rcya** [comment]
这种帖子请发到 https://github.com/getlantern/forum

**Comment by giarld** [comment]
现在是2.2.3了吧
