### ISSUE TITLE
Data cap not really trigger throttling

### ISSUE THREAD

**Issue by percyalpha** [getlantern/lantern#4510]
I experience the same issue as @WolfLantern  After exhausting 500MB of data, I still have 10Mbits+ bandwidth

**Comment by WolfLantern** [comment]
Yeh mine is the same, seems like no throttle at all after data is finished.

**Comment by myleshorton** [comment]
Throttling is live in staging right @uaalto and @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton Yes, throttling is live.

**Comment by percyalpha** [comment]
Now I see my speed is nicely throttled to 440 Kbits/s. 

@oxtoacart @myleshorton I can reliably stream 480P videos. This is too much as most Chinese users won't be able to stream 720P without out restriction. I suggest we throttled to Edge speed. In China, in practice, this will be around 30KB. So I suggest that we trotted to 250Kbits/s

**Comment by oxtoacart** [comment]
Thanks @percyalpha, that's great that you're seeing speeds around 440 kilobits per second, as @uaalto set up the servers to throttle at 50 kilobytes per second (i.e. 400 kilobits per second).

@uaalto What do you think about lowering things to 28 kilobytes per second or so?

**Comment by uaalto** [comment]
Yes, we should do it. I actually meant to lower it for staging to make it more apparent, even if we use a higher throttling in production.

**Comment by uaalto** [comment]
Deployed.

**Comment by percyalpha** [comment]
confirmed
