### ISSUE TITLE
Started at 200MB Remaining (not 500MB)

### ISSUE THREAD

**Issue by WolfLantern** [getlantern/lantern#4511]

**Comment by percyalpha** [comment]
Perhaps you tested Lantern before and used 300MB already? We should make it clear in the UI, say you have 200MB remaining out of your 500MB quota per month rather than just stating the 200MB

**Comment by WolfLantern** [comment]
I started at 200MB remaining (not 500MB)
I watched 4 youtube videos at the same time and dropped about 10-22MB every 60-90secs 
it went red at 35MB remaining

**Comment by WolfLantern** [comment]
@percyalpha i was thinking that might be the case. maybe it recognised me from the last test?

**Comment by WolfLantern** [comment]
we were looking at TunnelBear which says "500MB remaining this month"

On Fri, Jun 3, 2016 at 4:26 PM, Percy <notifications@github.com> wrote:

> Perhaps you tested Lantern before and used 300MB already? We should make
> it clear in the UI, say you have 200MB remaining out of your 500MB quota
> per month rather than just stating the 200MB
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4511#issuecomment-223717696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AL0uSweDx7WYp0wlP-dRhlg57XaQuvx9ks5qILgqgaJpZM4It-75>
> .
>



-- 
*Wolf*

**Comment by percyalpha** [comment]
@WolfLantern  Probably. Because I see 500MB. 

Ok, I think either wording should be fine. I'll close it for now, unless this issue is reported by others as well.
