### ISSUE TITLE
Notification when it's 80% of the data cap 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4513]
Let's tell users that they're near the data cap.

**Comment by fffw** [comment]
Currently, Lantern desktop:
1. Pops up desktop growl at the top right corner if used data exceeds the cap.
2. Shows snackbar at the bottom of desktop UI if the remaining data is < 5MB.

I think we can show 2 when data exceeds 80%, but keep 1 as is.

**Comment by p3rcya** [comment]
Agree.

On Wednesday, June 22, 2016, fffw <notifications@github.com> wrote:

> Currently, Lantern desktop:
> 1. Pops up desktop growl at the top right corner if used data exceeds the
> cap.
> 2. Shows snackbar at the bottom of desktop UI if the remaining data is <
> 5MB.
>
> I think we can show 2 when data exceeds 80%, but keep 1 as is.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4513#issuecomment-227690600>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqWGDtnNM7PsP1sahV_tYdaSuDqldks5qOQAlgaJpZM4It_Re>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by atavism** [comment]
Sounds good to me too, @fffw! I'll display the snackbar on mobile whenever the user's remaining data dips below 5MB: https://github.com/getlantern/lantern/issues/4486
