### ISSUE TITLE
Add user interface to authorize and de-authorize devices

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4514]

**Comment by myleshorton** [comment]
@Derekf5 FYI we'll need designs for this on both desktop and mobile if we don't have them.

**Comment by Derekf5** [comment]
@myleshorton this is specified here #4563 and #4564 
Authorization is done in the "authorize device for pro" menu option.

**Comment by atavism** [comment]
@myleshorton the UI for this is finished on mobile already. I'm expecting the list of active devices from the ``/user-data`` call and we just need a "remove device" call.

**Comment by myleshorton** [comment]
Perfect thanks @atavism

**Comment by myleshorton** [comment]
We also need to send the device in the create-user call
