### ISSUE TITLE
china user can not use it, now.

### ISSUE THREAD

**Issue by XieXianbin** [getlantern/lantern#4516]
china user can not use it, now.

**Comment by XieXianbin** [comment]
Still unable to dial tcp://google.com:80 after 3 attempts

**Comment by myleshorton** [comment]
Can you send us your logs? Instructions are here, and you can also copy
support@getlantern.org if you don't mind.

On Fri, Jun 3, 2016 at 10:03 PM, Xie Xianbin <notifications@github.com>
wrote:

> Still unable to dial tcp://google.com:80 after 3 attempts
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4516#issuecomment-223736795>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABF0noLgaomtw06BRl4emC35WtxvMTTLks5qIQcZgaJpZM4IuDYc>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by IanSmith123** [comment]
u can **download** the last one, Then u can get google . I can't get google before use latern which download last year, then i re-download and it work!

**Comment by MarcSteven** [comment]
Yeah yesterday I cannot use it,I tought my internet was bad..I had confirmed cannot use it in China.......

**Comment by qq254963746** [comment]
can't   `telnet 107.170.204.179  443 ` 
`Jun 04 11:19:58.195 - 14m0s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 107.170.204.179:443 [] to tcp://config.getiantem.org:80: Unable to dial server (trusted) chained proxy at 107.170.204.179:443 []: dial tcp 107.170.204.179:443: i/o timeout on pass 0...continuing`

**Comment by qq254963746** [comment]
@myleshorton

**Comment by shendongdebing** [comment]
@qq254963746 @MarcSteven @XieXianbin Just try redial for few times. I can't using from yesterday, it tell me timeout. But suddenly I redial rightnow, it works.(ps: I'm Chinese in Jiangxi)

**Comment by shendongdebing** [comment]
Just try redial for few times. I can't using from yesterday, it tell me timeout. But suddenly I redial rightnow, it works.(ps: perhaps reinstall can be helpful)

**Comment by chensenmo** [comment]
+1, china telecom user can't use it aftering reinstall lasted one. but it still WORK under CERNET for edu institutes

**Comment by AlbertKidd** [comment]
Yesterday is 6.4, you know…

**Comment by darkbyteCn** [comment]
today is still not work in china

**Comment by SteveLuo9** [comment]
Still not now

**Comment by MarcSteven** [comment]
Open lantern ,it showed me these informations
1,A browser extension is preventing lantern from load….don’t install any extension …
2,Xunlei(Thunder Downloader) is installed.-Yeah I had installed Xunlei.But several days earlier I can use it well.I changed nothing .But now invalid ……
I cannot find related logs about the failure of lantern ...@myleshorton.........

**Comment by Jerry-goodboy** [comment]
@AlbertKidd 6.4, why? what happened on this day???

**Comment by hzk123** [comment]
because of 6.4

**Comment by louy2** [comment]
@AlbertKidd 
https://en.wikipedia.org/wiki/Tiananmen_Square_protests_of_1989

**Comment by TaoistKing** [comment]
Lantern is down for now, I can't access google as usual.

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。上传到Github需改后缀为txt，然后在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by MarcSteven** [comment]
I don't find log in logs about it.Weird

**Comment by MarcSteven** [comment]
Yeah now it's available,so you can shut down this issue...@myleshorton
