### ISSUE TITLE
data cap reset?

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4523]
My data cap again 500MB? Did you reset it @uaalto by changing the trotting?

**Comment by percyalpha** [comment]
And now the traffic meter is no longer going. I guess dev is doing some adjustment? @myleshorton

**Comment by uaalto** [comment]
No, this is something that was happening to me right before doing the thorttling adjustment. I thought it was only in my machine.  This might be caused by some proxies being assigned that for some reason are not updated, and now you also got one of those.

**Comment by myleshorton** [comment]
should be all set
