### ISSUE TITLE
Always triggers a verification code in google search

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#4526]
Previously, the proxy servers work fine with Google search here in China, but recently (maybe for more than half a month) whenever I do a Google search it triggers a verification code.

> Our systems have detected unusual traffic from your computer network. This page checks to see if it's really you sending the requests, and not a robot. Why did this happen?

**Comment by wfjsw** [comment]
Lantern automatically picks up the best DigitalOcean cloud server from its chained-server database. (See https://dashboard.getlantern.org )
The DigitalOcean chained-server your lantern chose to use had a heavy flow to Google in the past. (just like the exit nodes used by Tor)
The solution is to wait for a few days (approx. a week) till Lantern picks up new server.

**Comment by renkun-ken** [comment]
Thanks, @wfjsw. Hope it'll work :)

**Comment by fffw** [comment]
Same as https://github.com/getlantern/lantern/issues/4652
