### ISSUE TITLE
Lantern已经完全无法使用

### ISSUE THREAD

**Issue by Neillll** [getlantern/lantern#4529]
PC和android上Lantern都已经完全无法翻墙
广东深圳 中国电信

**Comment by fatwin** [comment]
最近的连接的确挺差，上海电信。

**Comment by xiemeilong** [comment]
江苏无锡  电信   完全无法使用

**Comment by middle6** [comment]
看来墙升级了，广州电信、广州移动，都不行了

**Comment by aixi** [comment]
湖北教育网也是

**Comment by VizXu** [comment]
上海的教育网还可以呀

**Comment by zhuziyi1989** [comment]
北京联通已挂，北京电信还正常。

**Comment by flyingfang** [comment]
同反应北京联通挂了……

**Comment by andudu** [comment]
青岛电信网络登不上

**Comment by maryjeck** [comment]
南电信，被网通都挂了啊

**Comment by nickle1106** [comment]
浙江电信、联通，无法连接。

**Comment by zouyee** [comment]
江苏 电信 已挂

**Comment by dou4cc** [comment]
去用赛风吧！

**Comment by flyyang** [comment]
北京联通无法使用

**Comment by sevenzhou1218** [comment]
5月24日开始，苏州电信开始挂，28号开始好了，然后昨天又挂了。但是家里的联通一直工作正常。

**Comment by krast** [comment]
封锁了亚洲节点，如果lantern服务器在欧美还可以用

新加坡也沦陷了
Sent from my iPhone

On Jun 7, 2016, at 11:22, sevenzhou1218 <notifications@github.com<mailto:notifications@github.com>> wrote:


5月24日开始，苏州电信开始挂，28号开始好了，然后昨天又挂了。但是家里的联通一直工作正常。

―

**Comment by Graychen** [comment]
昨天上不去，但是今天早上可以上了

**Comment by toiiggww** [comment]
墙加高了吧

**Comment by dou4cc** [comment]
赛风失效了！

**Comment by gy8958398** [comment]
上不去了。。。

**Comment by satchmo** [comment]
杭州电信无法连接

**Comment by pigletlkj** [comment]
广州移动宽带也上不了。。

**Comment by HongkaiWen** [comment]
今天下午下了一个最新版本的可用
windows版本，苏州联通

**Comment by yorkjun** [comment]
前几天开始苏州电信不能使用，移动网络可以。
今天一早苏州电信家里的网络又可以了。

**Comment by csitaylor** [comment]
移动的可以电信的非常难登录

**Comment by Yuefe** [comment]
北京联通已挂

**Comment by giarld** [comment]
请升级到2.2.3

**Comment by thinwind** [comment]
@xinshitn 
你用时候需要输入验证码吗?

**Comment by ascchrvalstr** [comment]
南京电信，2.2.4，一运行就崩

**Comment by xinshitn** [comment]
@thinwind
要的，大量代理连接过去，出发了谷歌等网站的防机器人策略

**Comment by liouvilles** [comment]
用tunnlo

2016-06-17 19:37 GMT+08:00 宁 <notifications@github.com>:

**Comment by ydfqsc** [comment]
挂了

**Comment by Rice321** [comment]
@ascchrvalstr 有没有试过换网络？

**Comment by ascchrvalstr** [comment]
@Rice321 现在电脑版正常，手机版还在崩，MIUI7.3稳定版

**Comment by windsome** [comment]
还有啥linux下免费翻墙软件？

**Comment by imhzr** [comment]
是时候放弃这个寻找新的替代品了，难怪这两天一直用不了

**Comment by fsxitutu** [comment]
一直都是秒连啊

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送，所以请稍安勿躁。

**Comment by KevinKernel** [comment]
四川电信挂了，四川联通正常

**Comment by p3rcya** [comment]
@KevinKernel 请去 https://github.com/getlantern/forum/issues/1152 申请内测，谢谢！

**Comment by decemer** [comment]
今天开始广东用不了

**Comment by kerecsenchen** [comment]
以前免费版用的挺好 后来就不行了 专业版也不行了

**Comment by p3rcya** [comment]
现在应该修复了

**Comment by chongqingfongdu** [comment]
lantern的网站都无法访问，买付费的也不行啊。哎

**Comment by p3rcya** [comment]
@chongqingfongdu 最新的3.2.6不行么？
