### ISSUE TITLE
Network very unstable 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4534]
Testing from a U.S network. Connection very unstable. 

When Lantern is on, most of the time I cannot even access anything.  
The newsfeed sometimes load, but sometimes not.

I don't know whether it's relevant. From the start, I only have 0MB data remaining.

**Comment by oxtoacart** [comment]
@percyalpha We were in the middle of migrating our redis servers.  How does it look now?

cc: @WolfLantern

**Comment by oxtoacart** [comment]
@percyalpha Oh wait, you're running with the early Lantern Pro build?  That would be hitting a different environment.

@uaalto Were you deploying anything to staging around this time?

**Comment by percyalpha** [comment]
@oxtoacart  Sorry I was not clear. Im testing @atavism 's build 0605

**Comment by oxtoacart** [comment]
@percyalpha Gotcha.  @atavism is that hitting staging or production?

**Comment by atavism** [comment]
It was hitting production, but it looks the migration is unrelated. I recently merged devel in, and it looks like mobile broke with the changes for bypassing disallowed ports: https://github.com/getlantern/lantern/pull/4409 I'm looking into it.

**Comment by WolfLantern** [comment]
@oxtoacart it's a lot better now. will start retesting now

**Comment by percyalpha** [comment]
I'm still experiencing very poor connection.

**Comment by oxtoacart** [comment]
@p3rcya Could you send me your logs please?

**Comment by atavism** [comment]
A new build is up (at the QA installer link) that should address the connectivity issues. The primary issue had to do with our udpgw service being stopped on our staging servers.

**Comment by atavism** [comment]
@p3rcya please feel free to re-open if you're still encountering this.
