### ISSUE TITLE
Order of items

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4535]
![image](https://cloud.githubusercontent.com/assets/7925929/15831078/92d66340-2bd0-11e6-9708-28dbaf34714b.png)
Current order is Sign in, Purchase, Check update, Get Free month. This doesn't make sense from a frequency perspective. I suggest we change to Purchase, Get Free month, Sign in, Check update.

**Comment by Derekf5** [comment]
Cool, @p3rcya changing this label to "android" for @atavism since this just needs implimenting, no design work needed.

**Comment by atavism** [comment]
Sweet, just wanted you to confirm, @Derekf5. This is done and will go out in the next build.
