### ISSUE TITLE
Get desktop version with links on the page

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4536]
![image](https://cloud.githubusercontent.com/assets/7925929/15848422/c750fe7a-2c41-11e6-8122-5d6e09032e25.png)

Since we're only emailing the download link to the users, it makes sense we provide the link directly on screen in addition to emails. We can have 

Please visit https://github.com/getlantern/forum/ on your desktop to download Lantern on desktop. 
Or you can email yourself the download link (The original email UI)

**Comment by p3rcya** [comment]
The URL has to be language, the above one is for Chinese. For English and other languages, we need to create separate pages. Perhaps you can even design a prettier page on Github than my current text based approach.
