### ISSUE TITLE
When applying promotion code, there's no indication of success or failure

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4541]
This is during checkout

**Comment by myleshorton** [comment]
This one's still open right @xiam and @fffw?

**Comment by xiam** [comment]
Yes, but I'll take it.

**Comment by oxtoacart** [comment]
Need design discussion.  @xiam to follow up with @Derekf5 and @myleshorton.

**Comment by carsonefv** [comment]
@oxtoacart @xiam @myleshorton @Derekf5 i mentioned this design issue here https://github.com/getlantern/lantern/issues/4577 with design suggestions from @sunshine19090

**Comment by xiam** [comment]
Closing in favour of https://github.com/getlantern/lantern/issues/4577
