### ISSUE TITLE
throttling to even less speed

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4543]
![image](https://cloud.githubusercontent.com/assets/7925929/15836268/d5ee6b60-2be8-11e6-96b6-1460aa00ed73.png)

Currently, if I download 2 files or watch multiple videos, the throttling is applied per connection.  It should be applied per users regardless of how many connections a user have. Is there any difficulty implementing per user device?

**Comment by percyalpha** [comment]
This cannot be applied to third party packages (or older version of Lantern). For those, we can only throttle per connection, but the per connection rate should be much lower, say 100 Kbits/connection

**Comment by myleshorton** [comment]
It's also potentially more resource-intensive and error prone that way @percyalpha

**Comment by percyalpha** [comment]
Ok, I understand. @myleshorton 
My estimated 250Kbit is based on per device. If it's per connection, I suggest we lower it further more to 20KByte/s. @uaalto

**Comment by myleshorton** [comment]
We also don't necessarily need to say exactly what we throttle it to @percyalpha -- as long as the speed is noticeably quite slow, we should be fine.

**Comment by percyalpha** [comment]
@myleshorton Sure, we won't say it in the software. But I think the current 30KB/s per connection is quite fast. That's why I suggested changing to 20KB/s

**Comment by myleshorton** [comment]
You actually notice this immediately when watching any video. Closing for now.

**Comment by p3rcya** [comment]
@WolfLantern and I think it should be even less. Currently, 240P video can play smoothly. 20KB/s will disrupt 240P video as well

**Comment by p3rcya** [comment]
@myleshorton @WolfLantern  you have to understand that the network condition in China and Free server can only support to 360P to begin with. Limiting to 240P is not a huge difference. Hence disrupting 240P is necessary. So I recommend for 20KB/s. 20KB/s is more than enough for Google, Wikipedia, and reading the news.

**Comment by WolfLantern** [comment]
@myleshorton what you think? can we get it to 20KB/s without major workload on dev? It seems to make a lot of sense what @p3rcya is saying
