### ISSUE TITLE
Lantern stops proxying after quitting from system tray but still connected

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4544]
Steps:

1. Quit lantern from system tray.
2. Use connect option from side menu. 

Lantern shows connection but when checked in whatismyipaddress.com, it shows my ip address. I have all the options checked in settings. Also, lantern turns off automatically after a minute or so (I have already raised it as a separate ticket).

**Comment by myleshorton** [comment]
Lantern will now show an alert in this case.

**Comment by sunshine19090** [comment]
@myleshorton what is the use of connect/disconnect?
