### ISSUE TITLE
Able to enter a future year such as 2050 for credit card payment

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4545]
Should we restrict the user to enter only till certain year for the expiry date?

**Comment by percyalpha** [comment]
Ha? I think this is because the test credit card. In production, obviously they can only use the real expiration date right?

**Comment by sunshine19090** [comment]
@uaalto Am I able to use 2050 as expiry date because it is in QA or it will be like this in production too?

**Comment by p3rcya** [comment]
No. I'm assuming you're using the 4242 credit card? That's for test only. I'm closing it for now.

**Comment by sunshine19090** [comment]
No @p3rcya , I am not using that. I am using a different one but still it just needs a valid credit card number and all the other details can be faked. I just want to make sure that this doesn't happen in prod too.  @uaalto Please reopen if it will happen in production too.

**Comment by uaalto** [comment]
All that is handled by Stripe @sunshine19090. You won't be allowed to use invalid expiration dates with a production account.

**Comment by sunshine19090** [comment]
Thanks @uaalto
