### ISSUE TITLE
Background image too small, creating blank spaces when tiled

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4549]
Background image is too small and should not be tiled, when tiled/repeated it is creating blank spaces

the svg should fill the entire screen like this:
![screenshot 2016-06-06 17 24 24](https://cloud.githubusercontent.com/assets/4400763/15838354/a35b0dd4-2c0b-11e6-9130-2d77b49a56d2.png)

it currently appears like this:
![screenshot 2016-06-06 17 19 45](https://cloud.githubusercontent.com/assets/4400763/15838364/afef05be-2c0b-11e6-9630-47709b1f12d0.png)

**Comment by carsonefv** [comment]
this is the case for Pro screen and Non-pro screen fyi

**Comment by myleshorton** [comment]
hmnn...ok thanks Carson!

**Comment by carsonefv** [comment]
Image is still appearing too small and tiled:
![screenshot 2016-06-07 19 20 45](https://cloud.githubusercontent.com/assets/4400763/15877927/f4bc9f7e-2ce4-11e6-99dd-bf0a007c64ea.png)

**Comment by myleshorton** [comment]
Should be all set

**Comment by carsonefv** [comment]
awesome

**Comment by sunshine19090** [comment]
LGTM. I am assigning this to @carsonefv for final verification.

**Comment by carsonefv** [comment]
looks great, closing
