### ISSUE TITLE
Snack bar menu text should be centered vertically and horizontally on Desktop

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4550]
text should be centered vertically and horizontally within the snack bar notification

should look like this:
![screenshot 2016-06-06 17 31 10](https://cloud.githubusercontent.com/assets/4400763/15838532/7f4edb54-2c0c-11e6-9a69-06e46748f5bc.png)

currently appears like this:
![screenshot 2016-06-06 17 28 09](https://cloud.githubusercontent.com/assets/4400763/15838460/22c29b3c-2c0c-11e6-851a-ecb32f4a8a5a.png)

**Comment by sunshine19090** [comment]
In windows 7 - Chrome and Firefox, the format is different. In Windows 10  -Edge browser, it looked fine except for the alignment. Have to check in other browsers and platforms. @carsonefv Should I log this as a separate ticket?

![image](https://cloud.githubusercontent.com/assets/11394369/15847797/984c87b0-2c3d-11e6-9148-c975ec88b54f.png)

**Comment by sunshine19090** [comment]
Ignore my previous comment. Didn't realize I was using the wrong build when I tested.

**Comment by oxtoacart** [comment]
@xiam states that this may be fixed already by one of his commits.
