### ISSUE TITLE
lantern-android.protected: protected.go:171 Could not connect to socket: no route to host

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4554]
Some change introduced on or after 0197842362b4c8ff21e32637a13a31954a6d62ee is creating a bunch of connection errors on mobile. It looks like it could be related to https://github.com/getlantern/lantern/pull/4322/files and connections unable to bypass the VPN but still investigating. 

In addition to the Redis migration earlier, this is the likely cause of  https://github.com/getlantern/lantern/issues/4534

**Comment by oxtoacart** [comment]
@atavism Interesting.  I tried building mobile from the regular lantern devel yesterday and it seemed to run fine on my Nexus 4 over Wifi.  What steps did you follow to get this error?

**Comment by atavism** [comment]
Hey @oxtoacart, yeah, I built using the latest from devel yesterday also. Here are the steps I followed:

- upgraded to latest gomobile (``gomobile version +d6153aa Mon Jun 6 18:19:59 2016 +0000 (android,ios); androidSDK=/usr/local/opt/android-sdk/platforms/android-23``) w/ go version: ``go1.6.2 darwin/amd64``
- built and installed a fresh mobile build from devel
- turned full-device VPN mode on
- it appears, around when balancer check dialers is called, the log suddenly fills with ``protected.go:171 Could not connect to socket: no route to host`` connection errors.

This continues, with connection requests sometimes succeeding, but I'm mainly unable to proxy anything or browse normally.

**Comment by atavism** [comment]
@oxtoacart Now I'm suddenly no longer seeing this. BTW, all of those ``protected.go:171 Could not connect to socket: no route to host`` errors had ``CloudFront`` IP addresses.

**Comment by myleshorton** [comment]
Very interesting @atavism. If you are able to consistently reproduce it, this sounds like a great use of `git bisect` to narrow down what commit introduced this.

**Comment by oxtoacart** [comment]
@atavism Is this resolved?

**Comment by atavism** [comment]
@oxtoacart Yes, I haven't seen this since we fixed that issue with the updgw service on staging.

**Comment by atavism** [comment]
Actually, @oxtoacart, I still am seeing this. It looks like it always happens after [here](https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/fronted/direct.go#L208). Do we need to call ``tlsdialer.OverrideDial`` before we call ``tlsdialer.DialForTimings`` here for mobile? Because I'm not sure any of the code fronted uses for vetting candidates is actually succeeding when full-device VPN mode is enabled. I keep seeing entries like the following over and over in an endless flood in the log: 

```
                         I  Jun 09 03:10:01.802 - 0m53s DEBUG fronted: direct.go:210 Dialing to &{pay.jp 205.251.251.7 0001-01-01 00:00:00 +0000 UTC}
                         I  Jun 09 03:10:01.878 - 0m53s DEBUG fronted: direct.go:215 Could not dial to 54.192.7.72, Unable to dial masquerade fifaconnect.org: x509: certificate is valid for *.zuus.com, zuus.com, *.zuus.com, not fifaconnect.org
                         I  Jun 09 03:10:01.892 - 0m53s DEBUG fronted: direct.go:191 Not re-adding candidate that failed on error 'Unable to dial masquerade fifaconnect.org: x509: certificate is valid for *.zuus.com, zuus.com, *.zuus.com, not fifaconnect.org'
                         E  Jun 09 03:09:31.215 - 0m22s ERROR lantern-android.protected: protected.go:171 Could not connect to socket: 216.137.33.164:443                         E  Jun 09 03:09:31.215 - 0m22s ERROR lantern-android.protected: protected.go:171 Could not connect to socket: 216.137.33.164
```

And it seems to be severely affecting performance. Would you be able to look into that further, @oxtoacart?

**Comment by atavism** [comment]
I'm also seeing this repeatedly: ``DEBUG fronted: direct.go:191 Could not perform successful head request: Unexpected response status: 403, 403 Forbidden``

**Comment by oxtoacart** [comment]
I'll take a look.

**Comment by oxtoacart** [comment]
This problem doesn't appear for me at all on devel.  I'm trying the lantern-pro repo now.

**Comment by oxtoacart** [comment]
So on the pro branch, I get a different issue.  The elided IP is a CloudFront IP address, so this seems like a similar issue.

```
Message: ERROR lantern-android.protected: protected.go:170 Could not connect to socket: 54.239.132.61%!(EXTRA int=443) [error=Could not connect to socket: xx.xxx.xxx.xx%!(EXTRA
                             int=443) error_type=errors.Error]
                         E  ERROR lantern-android.protected: protected.go:170   at github.com/getlantern/protected.Dial (protected.go:170)
                         E  ERROR lantern-android.protected: protected.go:170   at github.com/getlantern/tlsdialer.DialForTimings (tlsdialer.go:157)
                         E  ERROR lantern-android.protected: protected.go:170   at github.com/getlantern/fronted.(*direct).dialServerWith (direct.go:258)
                         E  ERROR lantern-android.protected: protected.go:170   at github.com/getlantern/fronted.(*direct).dialWith (direct.go:208)
                         E  ERROR lantern-android.protected: protected.go:170   at github.com/getlantern/fronted.(*direct).vetOne (direct.go:120)
                         E  ERROR lantern-android.protected: protected.go:170   at runtime.goexit (asm_arm.s:990)
```

**Comment by atavism** [comment]
Yep, that's the same issue I've been seeing! Sometimes I see ``no route to host`` instead of ``Could not connect to socket`` though.

**Comment by oxtoacart** [comment]
Interesting, now I see the error on devel as well.  Maybe because I upgraded my Android SDK?

**Comment by atavism** [comment]
Possibly. Did you test devel after upgrading gomobile? Could also be that.

**Comment by oxtoacart** [comment]
I've upgraded to the latest gomobile on devel, and it still works okay, so this must be something else.

**Comment by myleshorton** [comment]
This one's fixed right @atavism and @oxtoacart?

**Comment by atavism** [comment]
@myleshorton Yep!
