### ISSUE TITLE
Able to close all the pop up screens by clicking outside the screen including the payment screens

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4558]
This doesn't have impact on the side menu screens but it will have a huge impact in the Buy pro functionality.

If the user accidentally clicks outside the screen in the middle of the payment flow, then the user will have to start from the first step which will take a lot of time from a user's perspective.

**Comment by xiam** [comment]
This is also sounds natural to me, clicking outside a dialog usually dismisses it, but what do you think @carsonefv?

**Comment by carsonefv** [comment]
@xiam the only time I can see this being a problem is where @sunshine19090 is mentioning in the checkout flow, user could accidentally click outside screen and then have to go through checkout all over again

**Comment by xiam** [comment]
Thanks, I see the point, I'll remove that behaviour completely to be consistent.

**Comment by sunshine19090** [comment]
@xiam  Has this been deployed?

**Comment by xiam** [comment]
It was merged so it should be working @sunshine19090

**Comment by xiam** [comment]
Is this still happening to you @sunshine19090?

**Comment by sunshine19090** [comment]
working fine now.
