### ISSUE TITLE
can't use it in China!

### ISSUE THREAD

**Issue by halibobo** [getlantern/lantern#4560]
can't use it in China!

**Comment by matreex** [comment]
It's ture, v2.2.4 had been blocked, can't fuck the great wall of china. Fucking shit.

**Comment by Page-David** [comment]
Me too, v2.2.3 not working for me in Zhe Jiang.

**Comment by afeilulu** [comment]
Same here !!!

**Comment by EricGao2015** [comment]
2.2.3版本在 win7和andriod正常。 2.2.4版本在 ubuntu失效。

**Comment by Page-David** [comment]
@EricGao2015 我这里win7和Ubuntu都没法用了;)快活起来。。。

**Comment by matreex** [comment]
I had to install Hotspot Shield when lantern isn't working, because HSS is not secure, if u need HHS, download link: https://mydati.com/download/hss-win2/HSS-773.exe. It's working.

**Comment by DavidWhite99** [comment]
Me too, v2.2.4. Beijing . Unicom . LAN

**Comment by GesanTung** [comment]
me too for mac

**Comment by AnnatarHe** [comment]
I doesn't work T_T
v2.2.4
Nanjing Jiangsu Province China
China Telecom
Windows 10

**Comment by myleshorton** [comment]
Thanks everyone. We are working hard on a fix and hope to have something within 24 hours. Thank you so much for your patience while we work through these issues.

**Comment by myleshorton** [comment]
It should actually be sooner than that, and you might see it start working for you within an hour, but we can't guarantee that for everyone.

**Comment by hzk123** [comment]
Our National Cyber Security Division download your codes and analyse it, maybe you should encrypt it.

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。上传到Github需改后缀为txt，然后在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by matreex** [comment]
I see, i had uploaded log.

**Comment by matreex** [comment]
I see, i had uploaded log.

**Comment by matreex** [comment]
I see, i had uploaded log.
[lantern.zip](https://github.com/getlantern/lantern/files/304299/lantern.zip)

**Comment by matreex** [comment]
All logs
[logs.zip](https://github.com/getlantern/lantern/files/304367/logs.zip)

**Comment by TaoistKing** [comment]
How to get lantern log on Mac?

**Comment by matreex** [comment]
ok, v2.2.4 is working, i'm fucking the wall, thanks a lot. Done.

**Comment by halibobo** [comment]
nice
