### ISSUE TITLE
UI: Updated Account Management Screen with Logout and Phone number - Desktop Pro User

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4563]
Hey @p3rcya @myleshorton making a new ticket specifically for desktop design for the log out issue https://github.com/getlantern/lantern/issues/4413 

Here is the updated account management screen for Desktop with Phone number and Log out

Changes include: 
• Added Verified Phone Number line
• Current device was moved up above the authorized device lines
• Changed the X's for de-authorize device to "REMOVE"
• Added "LOG OUT" text next to current device.

![screenshot 2016-06-07 11 34 09](https://cloud.githubusercontent.com/assets/4400763/15864389/f05f4264-2ca4-11e6-80ac-7465ae005974.png)

**Comment by myleshorton** [comment]
Closing in favor of new designs.
