### ISSUE TITLE
UI: Updated Account Management Screen with Logout and Phone number - Mobile Pro User

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4564]
Hey @p3rcya @atavism here is the updated account management with log out

Changes include current device was moved up above the authorized device lines,
Changed the x's for deauthorize device to "remove"
Added "Logout" text next to current device.

![account-management](https://cloud.githubusercontent.com/assets/7864729/15864469/49a35996-2ca5-11e6-9da5-2ac965cecdfb.png)

**Comment by atavism** [comment]
@Derekf5 Thanks! I noticed the "Send us your Logs" text is kind of hard to click on. I'm going to make that bottom area into a button with a transparent border to expand the surrounding click area. I can do something similar with the "Log out" and "Remove" buttons.

**Comment by Derekf5** [comment]
Hey @atavism good idea, so it wont look different, it will just be easier to click on correct?

**Comment by myleshorton** [comment]
Wait guys we said for this version we wouldn't include the actual devices in the UI right? There's currently no support for that on the server side.

**Comment by Derekf5** [comment]
@myleshorton i thought we were, but if there is no server side support yet we shouldnt push it right?  Seems like that is a task that would push us back, and this doesn't seem absolutely necessary as long as it comes with the next version...

**Comment by atavism** [comment]
This is done. The "Devices authorized to use your Pro account" is hidden for now until https://github.com/getlantern/lantern/issues/4514#issuecomment-225647029 is finished
