### ISSUE TITLE
DNS led blocking

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4569]
According to multiple user reports https://github.com/getlantern/forum/issues/128 , if the default DNS in a particular city will lead Lantern being inaccessible. The Lantern will be working again after switching to a different DNS. I thought we use IP directly. How would this be influenced by DNS?

**Comment by myleshorton** [comment]
Shouldn't be affected by DNS @p3rcya. The only thing I can think of is that we do use some domains for the domain fronting/config-fetching stuff.

**Comment by p3rcya** [comment]
I've asked for logs and DNS for us to investigate. Stay tuned.

**Comment by p3rcya** [comment]
Users cannot confirm it's due to DNS
