### ISSUE TITLE
UI: "Free Pro Credits" Referral Promotion Pop up in Checkout Flow: copy needs updating with two options

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4574]
Copy in Promotion pop up should be updated to reflect current price plan/referral

• there are two screens here: 
-If you buy one year the copy should say "one month of Lantern Pro for Free"
-If you buy 2 years the copy should say "three months of Lantern Pro for Free"

One month free screen:
"Did a friend share their referral code with you? Enter the code to receive one month of Lantern Pro for free after checkout"
![screenshot 2016-06-07 18 57 53](https://cloud.githubusercontent.com/assets/4400763/15877442/cbf88844-2ce1-11e6-8a8a-ac38ceaf8032.png)

Three months free screen:
"Did a friend share their referral code with you? Enter the code to receive one month of Lantern Pro for free after checkout"
![screenshot 2016-06-07 18 58 01](https://cloud.githubusercontent.com/assets/4400763/15877446/d4359556-2ce1-11e6-8925-73778fd62941.png)

**Comment by p3rcya** [comment]
On the first screen, I suggest that we add the additional text, "Do you know? You can get 3 months free with the same code, if purchase a two year plan" (If user click anywhere within "purchase a two year plan", users should be redirected to the two year plan check out screen. )

**Comment by carsonefv** [comment]
@WolfLantern what do you think?

**Comment by p3rcya** [comment]
I have to be clear, users should NOT be redirected back to the select plan screen, but the check out screen. We don't want users to go through any unnecessary steps, especially the phone number verification step.

**Comment by WolfLantern** [comment]
i think thats a good idea, it's a great up sell, right?
