### ISSUE TITLE
UI: "Free Pro Credits" screen image needs updating

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4575]
Graphic is incorrect, change to this one: https://www.dropbox.com/s/4ko0gz15aj5sy62/Referrals_Credits-02.svg?dl=0 Height: 184px
Width: 345px Padding: left/right: centered; top: 53px

**Comment by myleshorton** [comment]
OK I updated the image for this one @carsonefv, but unfortunately the sizing is the same across all dialogs the way it's written, so getting the exact size would be a much more involved change. Just going to leave it for now and we can tackle it some other time!

**Comment by carsonefv** [comment]
lgtm @myleshorton

**Comment by sunshine19090** [comment]
Is this good to close @carsonefv ?

**Comment by carsonefv** [comment]
yep!
