### ISSUE TITLE
UI: Background Image doesn't show up until resizing browser screen

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4576]
Background image does not show up at all until i re-size my browser screen

pre re-size:
![screenshot 2016-06-07 19 18 37](https://cloud.githubusercontent.com/assets/4400763/15877882/a9cc7ec6-2ce4-11e6-8c14-b4f6eed56988.png)

post re-size:
![screenshot 2016-06-07 19 16 34](https://cloud.githubusercontent.com/assets/4400763/15877868/8e7202e0-2ce4-11e6-8c7f-109983f30046.png)

**Comment by xiam** [comment]
I could not reproduce this @carsonefv, does this happen every time? which browser/os?

**Comment by carsonefv** [comment]
This happens every time on my Macbook Pro OSX (Yosemite i think) Chrome browser (though I haven't checked the lastest lantern version on that device yet, will later today) but it's not happening on my i Mac OSX Yosemite Chrome browser

**Comment by myleshorton** [comment]
I don't think this is likely to happen with the latest build @carsonefv but please verify.

**Comment by myleshorton** [comment]
Changing this to deployed @xiam -- the screenshots are from before the `cover` change to background.

**Comment by carsonefv** [comment]
yeah it's not happening anymore with the latest build, closing this
