### ISSUE TITLE
UI: "Welcome to Lantern Pro" Pop-up screen in checkout - Update copy to reflect promotion

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4578]
"Welcome to Lantern Pro" Screen copy needs updating to reflect updated referral promotion:

The Description text should read: 
"Invite friends and you will each get 3 months free when they purchase the two-year plan, 
the one year plan gets you each 1 month free. Start inviting!"

text should break after "two-year plan"

updated screen should look like this:

![screenshot 2016-06-07 20 01 19](https://cloud.githubusercontent.com/assets/4400763/15878643/a65e0baa-2cea-11e6-9622-b5e438a677bf.png)

**Comment by myleshorton** [comment]
@xiam knocked this out in the latest build @carsonefv and @sunshine19090 but let us know if there are any issues!

**Comment by carsonefv** [comment]
@xiam @myleshorton the description copy isn't appearing updated for me on the latest version 

The Description text should read: 
"Invite friends and you will each get 3 months free when they purchase the two-year plan, 
the one year plan gets you each 1 month free. Start inviting!"

text should break after "two-year plan"

currently appears like this:
<img width="672" alt="screenshot 2016-06-08 10 53 50" src="https://cloud.githubusercontent.com/assets/4400763/15898860/d349a3cc-2d67-11e6-806b-017d86144dcf.png">
