### ISSUE TITLE
Cannot work on Windows

### ISSUE THREAD

**Issue by jindongwang** [getlantern/lantern#4580]
Lantern cannot work on windows 10 anymore, I don't know what happened. It just happens...

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。上传到Github需改后缀为txt，然后在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by jindongwang** [comment]
[lantern.txt](https://github.com/getlantern/lantern/files/304134/lantern.txt)
