### ISSUE TITLE
Desktop notification not using Lantern logo

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4581]
Silly path mistake.

**Comment by sunshine19090** [comment]
I am not seeing it. Where should it be?

![image](https://cloud.githubusercontent.com/assets/11394369/16208538/8c273eee-36e7-11e6-8a89-d87da8fd36f6.png)

**Comment by sunshine19090** [comment]
@myleshorton where the logo should be? I don't see it.
