### ISSUE TITLE
UI - Windows 10 - When clicked on a button, I see a growing circle in lighter shade on the button

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4582]
In the below screenshot, I hope you will be able to  notice that circle around the word update. It is not just the buttons, it appears when clicked on any side menus too.

![image](https://cloud.githubusercontent.com/assets/11394369/15883138/2a5cda9e-2cfa-11e6-862b-c9222d0df752.png)

**Comment by xiam** [comment]
Hello @sunshine19090, can you click on any of the buttons here http://www.material-ui.com/#/components/flat-button? is it the same behaviour?

**Comment by sunshine19090** [comment]
Yes @xiam, I see the same behavior when click on Primary and secondary.

**Comment by myleshorton** [comment]
Any thoughts on this one @Derekf5 and @carsonefv?

**Comment by Derekf5** [comment]
@myleshorton i dont think that is an issue?  it just shows that the button has been clicked.

**Comment by carsonefv** [comment]
@myleshorton yes i think the is just the style of the button click, unless I am mistaken?

**Comment by xiam** [comment]
This is material-ui's lib default behavoiur, so I'm closing this unless we have a strong argument against it.
