### ISSUE TITLE
UI - Edge - A bigger X mark appears when entering the email address (refer screenshot)

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4583]
![image](https://cloud.githubusercontent.com/assets/11394369/15883176/8e6c4876-2cfa-11e6-8e53-0d302e8560df.png)

**Comment by myleshorton** [comment]
Is this still an issue @sunshine19090?

**Comment by sunshine19090** [comment]
No @myleshorton , I don't see the X mark now.
