### ISSUE TITLE
I see error message for email address when I haven't even clicked on the Send button

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4584]
Steps:

1. Go to Get mobile version screen
2. Enter email address but do not finish. Change tabs or windows. 

Shows an error message at this point when the user has not even clicked on the send mobile version button.

![image](https://cloud.githubusercontent.com/assets/11394369/15883197/d4fdc13e-2cfa-11e6-94e4-f1dc4f1018fa.png)

**Comment by xiam** [comment]
Thanks @sunshine19090, this only happens when the input loses the focus, to me it does not feel unusual, some sites run validations as soon as the user finishes writing, but maybe I am wrong. What do you think @carsonefv, @Derekf5?

**Comment by Derekf5** [comment]
@sunshine19090 @xiam I think this error is OK.  Generally i think error text should only be shown after a user interacts with a field, and that is what is happening here.   

The only change i would make is to have the error/helper text go away once a legitimate email address is detected, currently the error stays in place when I finish inputing a valid email.
