### ISSUE TITLE
Lantern Pro UI is not displayed for the pro user in Chrome after disconnecting wifi

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4587]
Steps:
1. Become a pro user. Use edge.
2. Disconnect network connection.
3. Open lantern in chrome. It will show free user UI instead of Pro UI. It doesn't remember even if I close and reopen lantern in chrome but remembers in Edge.

I still have to check the behavior with different browser scenarios.

**Comment by fffw** [comment]
@myleshorton @xiam Do we need to cache more data locally to show correct UI without contacting Pro server? It does little harm if the local data is distorted: servers will reject unauthorized operation anyway. Normal client will always cache correct data.

**Comment by xiam** [comment]
I think that sounds good @fffw. The immediate problem, tho, was that if the UI failed to contact the API for some reason, it gave up and displayed the non-pro interface, regardless of whether the user was pro or not. I prepared a PR for that part of the problem. We also need to make some adjustments in the backend side, like caching and adding some timeouts.
