### ISSUE TITLE
After quitting lantern, if I try to access lantern by entering ui.lantern.io in edge, it just keeps showing the spinner instead of the error page

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4588]
I think we should keep the self help page. That will help in these cases.

**Comment by myleshorton** [comment]
Are you saying that Lantern is no longer running in this case @sunshine19090?

**Comment by sunshine19090** [comment]
Sorry for the delay, @myleshorton, the spinner appeared only after quitting lantern. So, I was saying that instead of the spinner, we should have shown the message.  I believe this has been fixed by the popup showing that the lantern is not running anymore. Anyway,  I don't rememeber testing this case in Edge after the change. I will see if this issue is still existing.

**Comment by joesis** [comment]
Lantern no longer use special domain for Edge
