### ISSUE TITLE
In free user UI - the referral code keeps changing when reopened lantern after a short interval of internet disconnection

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4589]
Steps:

1. Open lantern. Note the referral code.
2. Disconnect wifi and close the lantern UI page.
3. Open lantern without internet connection. There will not be any referral code under Get Free Pro credits. Close the page again.
4. Connect to wifi. Reopen lantern. Note the referral code. It will be different from the one seen at first.

I saw this behavior when following these steps but I think there might be an easier way to reproduce this.

**Comment by myleshorton** [comment]
Yeah this one's definitely a blocked @sunshine19090 good catch! @uaalto this is likely some issue on the server side huh?

**Comment by myleshorton** [comment]
Hey @fffw this one would be great for you to look at when you have a chance. Unless you're already working on this one @xiam?

**Comment by fffw** [comment]
So the existing `userid` and `usertoken` was cleared when Lantern page was open without Internet connection. https://github.com/getlantern/lantern-desktop-ui/pull/98 fixed it, but the referral code is still not shown if no Internet connection. Should either cache locally or prompt user in such case.

**Comment by fffw** [comment]
Created https://github.com/getlantern/lantern/issues/4619 to discuss if we want to cache referral code locally.

**Comment by uaalto** [comment]
@myleshorton @fffw  the server doesn't create referrals codes, it just derives them from the user ID. Most likely, we are requesting the server a new user when this happens, then receiving a new code. We should try to avoid creating a new user if possible in the client. In that sense, the referral code doesn't really need to be cached, but rather the user ID so the client doesn't create a new one.

**Comment by fffw** [comment]
@uaalto Caching referral code is not for this issue. It's to show referral code when there's no Internet connection or so.

**Comment by uaalto** [comment]
ah ok :)
