### ISSUE TITLE
Windows 10 - When clicked on the notification from lantern to upgrade to pro, it opens a pop-up

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4590]
We should take the user directly to the Buy pro screen flow or atleast open a new lantern UI page.

![image](https://cloud.githubusercontent.com/assets/11394369/15884564/5dd95814-2d06-11e6-9871-777cd1235e75.png)

**Comment by myleshorton** [comment]
Hey @sunshine19090 this should be deployed with the latest build from last night (20160608.045058).

**Comment by sunshine19090** [comment]
Yeah, now it takes the user to Lantern UI.

**Comment by sunshine19090** [comment]
@myleshorton Now, the user gets to the below page when clicked on the notification even when lantern is ON in Edge.  I think it is because it tries to open http://127.0.0.1:16823/ instead of http://ui.lantern.io/

![image](https://cloud.githubusercontent.com/assets/11394369/16430178/34fda128-3d2f-11e6-934c-a93ec5cba733.png)

**Comment by myleshorton** [comment]
Yeah makes sense @sunshine19090. That's really a different Edge-specific issue though. Do you mind opening a separate ticket for that?
