### ISSUE TITLE
Lantern doesnt work here. Please help.

### ISSUE THREAD

**Issue by wwqwwqwd** [getlantern/lantern#4592]
[GoLog.txt](https://github.com/getlantern/lantern/files/304391/GoLog.txt)

Looks like the proxy server is not correctly configured or is blocked by GFW.

And a pro version is mentioned in issues. How to get that?

**Comment by myleshorton** [comment]
Does it work for you now @wwqwwqwd?

**Comment by wwqwwqwd** [comment]
I cant check it today. Ill check it tomorrow.

**Comment by wwqwwqwd** [comment]
It works now, thanks very much. @myleshorton
