### ISSUE TITLE
Remove secondary icon from Desktop data cap notification

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4594]
there is a terminal icon or something before the header, would be great to remove if possible.
<img width="301" alt="screen shot 2016-06-08 at 10 38 21 am" src="https://cloud.githubusercontent.com/assets/7864729/15898269/985a73b0-2d65-11e6-977e-e672a4b0687b.png">

**Comment by myleshorton** [comment]
Not possible unfortunately without writing it from scratch.
