### ISSUE TITLE
User reported crashing after new protocols 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4603]
User1:
Log here https://github.com/getlantern/forum/issues/148

User 2: Crashes after June 9, Windows 10 Chrome
https://github.com/getlantern/forum/issues/151

Other users reporting it affecting Chrome

**Comment by p3rcya** [comment]
Crashes on android as well.

**Comment by myleshorton** [comment]
Hey sorry @p3rcya you think this was the result of deploying new protocols right? Are you still seeing this?

**Comment by myleshorton** [comment]
Closing.
