### ISSUE TITLE
Change link on the notice

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4604]
GetLantern.org是蓝灯唯一的官方网站。其他网站的下载链接都可能包含有病毒，并且盗取你的资金和个人信息。请从官网或GitHub(免翻墙)下载蓝灯软件。

Currently the word "Github" link to https://github.com/getlantern/lantern/releases/tag/latest, please change it to https://github.com/getlantern/forum

**Comment by fffw** [comment]
Should the link be https://github.com/getlantern/forum#蓝灯lantern最新版本下载 ?

**Comment by p3rcya** [comment]
sure. That works.

On Thursday, June 9, 2016, fffw <notifications@github.com> wrote:

> Should the link be https://github.com/getlantern/forum#蓝灯lantern最新版本下载 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4604#issuecomment-224876894>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqYYQbCCywEOezEt2hn7RWOSCVoH9ks5qKAPVgaJpZM4IxqGw>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by fffw** [comment]
Done
