### ISSUE TITLE
Cannot see versions or report logs if Lantern is inaccessible 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4610]
Reporting logs/version number is crucially important when the software doesn't work. But now, if user is stuck at 
![image](https://cloud.githubusercontent.com/assets/7925929/15949335/7ef6c224-2e5b-11e6-9e03-c9972a825331.png)

they cannot eporting logs/version number

**Comment by Derekf5** [comment]
@p3rcya are you saying we just need to make the version number visible on this screen?

**Comment by p3rcya** [comment]
@myleshorton When will the user be stuck at this screen? All of Lantern is entirely blocked? Would this screen be loaded locally?

**Comment by myleshorton** [comment]
> @myleshorton When will the user be stuck at this screen? All of Lantern is entirely blocked? Would this screen be loaded locally?

Yes it's loaded when Lantern is inaccessible, which by definition means the UI can't access the lantern version or tell it to report logs.
