### ISSUE TITLE
Refine the text in Welcome to Pro dialog

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4612]
Current text is not accurate.

> Invite friends and you will both get a free month of Lantern Pro when they sign up. Start inviting!

It depends on which plan the friend purchases.

**Comment by carsonefv** [comment]
@fffw this is a duplicate of issue https://github.com/getlantern/lantern/issues/4578

**Comment by fffw** [comment]
Thanks @carsonefv !
