### ISSUE TITLE
Mac - UI shows 0 MB remaining when downloaded for the very first time

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4614]
<img width="1280" alt="screen shot 2016-06-09 at 10 04 58 pm" src="https://cloud.githubusercontent.com/assets/11394369/15955097/625274d2-2e93-11e6-8465-2ac5ab1221c8.png">

**Comment by p3rcya** [comment]
same on android https://github.com/getlantern/lantern/issues/4571

**Comment by myleshorton** [comment]
this appears to be fixed.
