### ISSUE TITLE
If the user doesn't complete the checkout process then the buying pro flow isn't showing the phone verification screen as well as the promo code throws error message

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4615]
Steps:

1. Click on "Buy pro"
2. Enter a phone number and the verification code
3. Enter the referral code(XLLLLX) and click on apply promotion button. 
4. Close the check out screen (I actually did this accidentally). After closing, it goes back to the promo code screen.
5. Enter another promo code(GSLGS9) and it showed error message.
6. Closed the promo code screen to start a fresh payment flow.
7. Click on buy pro again. It directly took me to the promo code screen. Looks like it is expected behavior as the user is already verified but if the user wishes to use another phone number, then they will never get a chance to do so.

**Comment by xiam** [comment]
The user was verified in step 2 and we save a temporary status for that, so in step 7 the user is not asked again for verification. If the user refreshes the page or restarts Lantern the state is lost and she will be asked for verification again.

What's your opinion on this @carsonefv, @Derekf5?

**Comment by Derekf5** [comment]
@xiam If they have already verified in step 2 i cant really think of a reason they would want to use another number particularly in that session.   I think this behavior is generally good, as it doesnt make the user go thru an unnecessary step again.   In the next release we will give users the ability to change their number in the Account management screen.

**Comment by Derekf5** [comment]
@xiam so the only issue i really see here is that the promo codes are not working

**Comment by sunshine19090** [comment]
NA anymore.
