### ISSUE TITLE
Send the sms again feature for receiving verification code

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4616]
@myleshorton @carsonefv @Derekf5 In the current UI, considering a scenario where the user doesn't receive sms the first time after clicking on the send sms button, there is no way that the user could proceed without closing the screen. 

I think it will be useful if we give the option for the user to send the sms again in the form of a link/button just like gmail does for two-factor authentication. We could keep the send sms button disabled during this time and show the send sms again link or button only after clicking on the send sms button.

**Comment by p3rcya** [comment]
Also modify phone number if I entered it wrong  https://github.com/getlantern/lantern/issues/4415

**Comment by xiam** [comment]
This would also close https://github.com/getlantern/lantern/issues/3927

**Comment by p3rcya** [comment]
@Derekf5 @myleshorton Remember to allow users to edit the phone number for the resend

**Comment by sunshine19090** [comment]
NA now.

**Comment by p3rcya** [comment]
@sunshine19090 Please make sure the user can resend email and edit email without exiting the sign up process
