### ISSUE TITLE
When Alipay is selected as payment method, it directs to Enter the verification code screen (refer screenshot)

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4617]
Steps:

1. Click on continue to checkout.
2. Enter the email address and click on  Alipay
3. Instead of showing the User ID field on the same screen, it took me to the verification code screen. 

I came to know that there is a User ID field in the previous screen only after going back from the verification code screen.

<img width="1280" alt="screen shot 2016-06-09 at 11 14 37 pm" src="https://cloud.githubusercontent.com/assets/11394369/15955675/048fc58e-2e98-11e6-9f24-35e78b3e8fe7.png">

**Comment by sunshine19090** [comment]
Okay, I just saw my inbox and the verification codes are sent by email. Not sure why I am seeing the User ID anyway. It is little confusing to me as I do not have a alipay account.

**Comment by sunshine19090** [comment]
I figured that the User ID is asked after the verification. Doesn't make sense to me but looks like that is how stripe works.

**Comment by p3rcya** [comment]
@sunshine19090 I didn't see this verification screen. However, I encountered problem during check out too see below 

![image](https://cloud.githubusercontent.com/assets/7925929/15956234/f9a63744-2e9b-11e6-8e0e-24d491b1dbe8.png)

**Comment by p3rcya** [comment]
Actually, this is how Stripe works with Alipay, we cannot change it
