### ISSUE TITLE
ubuntu 16 build error,

### ISSUE THREAD

**Issue by Changgg** [getlantern/lantern#4618]
Here is what the terminal informed me :
`
Building development lantern
** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
# github.com/getlantern/systray
src/github.com/getlantern/systray/systray_linux.c: In function ‘nativeLoop’:
src/github.com/getlantern/systray/systray_linux.c:37:2: warning: ‘return’ with no value, in function returning non-void
  return;
  ^
'

I am sorry,I am not clear what caused this.please help me.:)

**Comment by lumen82** [comment]
I have the same issue!

**Comment by lumen82** [comment]
... I solved this problem with this:
modify the function 'nativeLoop' 
return 1;

**Comment by StephenBoyd** [comment]
Why is this issue closed? This bug is still in the code.

**Comment by xiaer1921** [comment]
yes,this is a bug , I have the same issue!
