### ISSUE TITLE
Invalid currency on credit card payments in China with test account

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4624]
After users entered the test credit card and completed the payment process, Lantern says invalid currency and kicks users back to the main screen.

![image](https://cloud.githubusercontent.com/assets/7925929/15981724/93495bf0-2f2e-11e6-81b3-3ad073a9d972.png)

**Comment by myleshorton** [comment]
Thanks @p3rcya. We'll put this at the top of the list! Any ideas on this one @uaalto?

**Comment by myleshorton** [comment]
I wonder if this is just the way it is with the test account?

**Comment by p3rcya** [comment]
No. When it was in USD, no such prompt was given.

On Friday, June 10, 2016, myleshorton <notifications@github.com> wrote:

> I wonder if this is just the way it is with the test account?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4624#issuecomment-225337605>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqffqNEt3pccAWBfEHT_W-U11sdiwks5qKkRogaJpZM4IzbF->
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by fffw** [comment]
https://github.com/getlantern/pro-server/blob/master/src/pro_server/plans.clj#L13 checks underscore separated locale, while the requested locale is `zh-CN`. We can normalize the locale in client.

**Comment by fffw** [comment]
It's caused by a bug, along with a few other bugs, in `ReferralPromotionDialog`. Have to go sleep but can fix them quickly in the morning.
