### ISSUE TITLE
[Desktop] Eliminate phone verification screen from checkout process

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4630]
Could we get away with that @uaalto?

**Comment by p3rcya** [comment]
That would be great! It reduces the friction of sign up a lot! We need to add an item account management page: I want to use Pro on more devices. When clicking it, it will redirect users to the SMS verification screen

**Comment by p3rcya** [comment]
In fact, this makes more sense from the backend prospective too. 
If a user is only using Pro on one device(either purchasing or buy getting free time from the referral code), no phone number is associated.
If a users want to use on more device, phone number or other authentication is needed

**Comment by p3rcya** [comment]
Please make the code extensible as later we might want to have verification enforced for all free users; but if Pro is purchased directly, no verification is needed; and if he wants to use Pro on multiple accounts, he can choose to use email+password without verification.

**Comment by uaalto** [comment]
@myleshorton , @p3rcya 
Verification is put in place for two purposes: validating new devices and recovering accounts. You can think of it as a login. If we remove it entirely in the single-device use case, we lose the ability to recover devices, including erased configuration data scenario.
I suggest removing it from the purchase steps, but adding a reminder pop up to link it *after* the purchase, reminding that without it, in case of data removal or lost device, the account cannot be recovered. That form of delayed validation would provide us the best of both worlds in my opinion.

On the other hand, we don't need any change in the backend in either case. Currently the phone configuration/validation steps are separate endpoints, so it's up to the client to force them before or not. Keep in mind that authentication is actually performed via token, so the phone is just used for recovery and new device linking, as mentioned above.

**Comment by p3rcya** [comment]
@myleshorton @uaalto 
Why do we need a phone number to recover the account if it's only used on a single device? Don't our backend log MAC addresses to enforce 3 simultaneous device? User should be able to recover account based on MAC address if he has never associated account with a phone number.

**Comment by p3rcya** [comment]
@myleshorton @uaalto As the situation where users losing the configuration file would be rare, we can add the recover from MAC address in the next release if we choose not to implement it now.

**Comment by myleshorton** [comment]
Thanks @uaalto and @p3rcya.

The other fascinating aspect of this is that the Alipay email *is already validated*, so for most of our users we have access to a validated email address already. So for the purposes of account recovery, we can already use that for all Alipay users (i.e. essentially all of our users!).

So it seems to me that this would work if we just only require it when you want to link devices (as in, when you want to link devices, you first have to validate your phone on the first device). Does that sound right?

**Comment by p3rcya** [comment]
@myleshorton Users don't need to enter the Alipay email for stripe (only the Alipay account). But I expect users to enter a real email address since they're paying. So I totally agree. We can use this email for recovery or MAC address recovery.

**Comment by uaalto** [comment]
This is something we've discussed in the past, and even implemented it in previous versions. I don't recall ATM why we decided that phone verification was better though. But in principle it sounds good to me. I however disagree in giving secondary priority to the fact that a user can remove her config data. When you have many users is something that is just going to happen, and handling it from the beginning is going to save us more time than manually validating the user and updating the token and manually providing the code or something along the lines.
MAC address recovery is not a secure method because it is not verified in any form. Anyway can modify his own address.

**Comment by uaalto** [comment]
@p3rcya we usually use P0 issues for something that would break code in production, this is just an enhancement, albeit might be considered important.

**Comment by p3rcya** [comment]
@uaalto Mac can be forged very easily. However, this is like a password user stored on his computer. Other users won't be able to guess his MAC addresses. I never said we should ignore it. Rather, we can always push out a newer version that allows users to recover from his MAC/email addresses

**Comment by myleshorton** [comment]
@p3rcya the point is that Alipay itself requires email verification when you create an Alipay account. As a result, we have access to that email whenever users pay. So we already have access to a verified email. 

They don't enter it during the Lantern checkout process, but we have it.

**Comment by p3rcya** [comment]
@myleshorton Oh, wow! I didn't know that. Then we don't need any verification at all, definitely not at sign-up. Maybe not even for device authorization (but we can discuss this point later)

**Comment by myleshorton** [comment]
Yeah agreed @p3rcya, and I'd be super interested to hear your thoughts on device authorization. Maybe we could automatically charge them $0 if we detect they've already paid, something like that?

**Comment by p3rcya** [comment]
@myleshorton What I have in mind is:
on the main screen, users click "already have Pro? log in here".
Then we email the user a verification code to this Alipay email and say "please check your email 1234567890@qq.com and enter the verification code below"

**Comment by myleshorton** [comment]
Nice @p3rcya.

**Comment by p3rcya** [comment]
@myleshorton In later version, users will be able to change this verification email. But we can discuss this later.

**Comment by p3rcya** [comment]
@myleshorton Also, if an existing user goes through the payment process again, we can alert them that they paid and ask whether they want to extend this for another year/two years

**Comment by p3rcya** [comment]
@myleshorton Using email from Alipay automatically shouldn't be a permanent measure. We should ask users to supply email during sign up and use that email in the future. Because this way, I can purchase plans for someone else. This is very important, enabling taobao resales.

**Comment by uaalto** [comment]
MAC is not the same as a stored password, because: 1) it is sent unprotected over the network 2) a user can't change it. So I think that method shouldn't even be considered.
Besides this, the email verification is a nice method, and as I mentioned, we already had this before. It can work just the same way as phone verifiction works, as you explained @p3rcya. Alternatively we can use Google Authenticator for this, which is even more secure, but probably not worth given that introduces another piece that might be blockable.

**Comment by p3rcya** [comment]
@uaalto Ok, let's agree on the email. But just for the record, in China all your password/text/email are transmitted in HTTP. MAC recovery is in fact more secure than password/text/email verification.

If we use google authenticator, we would have precisely, hmm, 0 Chinese user.

**Comment by uaalto** [comment]
How is it exactly more secure?
Email is transmitted over HTTP/S when using a web app, and only between the server and the client. But if that's the common case, and no HTTPS is used, then it is quite insecure (too).

**Comment by p3rcya** [comment]
MAC is only available to local network adversaries. Do you really think people on their local network would try to get a Lantern profile when virtually EVERYTHING is in plain text? Why do they even care about Lantern? No email provider in China use HTTPS by default and few even supports HTTPS to begin with. Please, please don't apply your security concept in China. In China, all browsers ignore HTTPS certificate error and load the page directly

**Comment by uaalto** [comment]
Thank you for the explanation. Then using email is not secure and we should stick to phone validation.
I actually think that local network is a factor to consider, but since I don't know how these things work in China, I won't insist on that.

**Comment by p3rcya** [comment]
@uaalto How is phone verification secure? Text is transmitted in plain text. Our product doesn't need to be more secure than a bank! Most banks in China use self-signed CAs or even HTTP.

**Comment by p3rcya** [comment]
@uaalto None of the method is secure. Only requiring email when authorizing device is much more beneficial to the sign up process.

**Comment by uaalto** [comment]
The code sent to the phone doesn't go through the wire until the moment the client sends it for validation. At that moment the attacker has only 20 minutes to do something with it, then the token can't be retrieved. We don't need more security than a bank, but at least protect our users from the most obvious attacks.

**Comment by p3rcya** [comment]
Weibo and virtually all serves use email for password recovery in China,
even services with the most sensitive information. Lantern account is the
least of user's concern for email security. We don't store any content
anyway. In China, your home address, national ID number all those are not
protected on by HTTPS.  Only large amount financial transfer is protected
by an SMS verification( even the wire-transfer page uses HTTP or HTTPS with
self-signed cert)

On Monday, June 13, 2016, Ulysses Aalto <notifications@github.com> wrote:

> The code sent to the phone doesn't go through the wire until the moment
> the client sends it for validation. At that moment the attacker has only 20
> minutes to do something with it, then the token can't be retrieved. We
> don't need more security than a bank, but at least protect our users from
> the most obvious attacks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4630#issuecomment-225685265>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqQAbfxH-R36bkea-4cX4CrTobETFks5qLbHPgaJpZM4Izeek>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment]
Hey @xiam and @fffw you cool with me taking this one?

**Comment by xiam** [comment]
No problem @myleshorton

**Comment by myleshorton** [comment]
You mind taking a look at the PR for this @xiam?

https://github.com/getlantern/lantern-desktop-ui/pull/115

**Comment by xiam** [comment]
That works @myleshorton, would you mind also removing the dialog's code and other references to it? like constants, etc.

**Comment by myleshorton** [comment]
Yeah I can do that @xiam.
