### ISSUE TITLE
where is the "MaxIdleTime"?

### ISSUE THREAD

**Issue by beautygirl001** [getlantern/lantern#4638]
when i use "make windows" to make lantern for windows today, the terminal tell me the error "MaxIdleTime is not defined" ("EnforceMaxIdleTime").The dir is "lantern/src/github.com/getlantern/flashlight/client/reverseproxy.go"
I find nothing in the "/usr/local/go/src/net/http/transport.go" in go1.7 or go1.6.
How to solve this problem ?please help me !

**Comment by wfjsw** [comment]
[Custom fork of Go](https://github.com/getlantern/go/tree/lantern) is currently required. You may build with the modified version of Go or use Docker ( `make docker-windows` ).
