### ISSUE TITLE
Referral screen is not updated

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4639]
The current screen is 
![image](https://cloud.githubusercontent.com/assets/7925929/15986084/b2674e9a-2fb3-11e6-9d0c-5e0c32768d90.png)

@carsonefv our final design uses "When your friends purchase the two-year plan you will each get 3 months free, the one-year plan gets you each 1 month free." and no fine print.  (I couldn't find the design anymore but please make sure dev use it)

**Comment by carsonefv** [comment]
@p3rcya this is the most updated copy as seen here https://github.com/getlantern/lantern/issues/4595, are you suggesting we replace the main text? any thoughts on this @WolfLantern @chipstehr ?

**Comment by p3rcya** [comment]
Yes. I found this shorter version on transfix, namely "When your friends
purchase the two-year plan you will each get 3 months free, the one-year
plan gets you each 1 month free.", much shorter and cleaner than the
current fine print. Fine print should be used when we don't want users to
read them. Our deal is really good and we want them to understand the
rules, namely sharing itself is not enough and you want to persuade your
friend to purchase, preferably two year plan.

Besides this cleaner text can fit in two line, so it's good to replace it.

On Saturday, June 11, 2016, carsonefv <notifications@github.com> wrote:

> @p3rcya <https://github.com/p3rcya> this is the most updated copy as seen
> here #4595 <https://github.com/getlantern/lantern/issues/4595>, are you
> suggesting we replace the main text? any thoughts on this @WolfLantern
> <https://github.com/WolfLantern> @chipstehr <https://github.com/chipstehr>
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4639#issuecomment-225397147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqdJ2ODLoeUp0DMSkfnRp6aRhq9y8ks5qKzHZgaJpZM4IzlQU>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by carsonefv** [comment]
@p3rcya sounds good to me

**Comment by chipstehr** [comment]
Yes @p3rcya that's the right text (although I made friend singular). "When your friend
purchases the two-year plan you will each get 3 months free, the one-year
plan gets you each 1 month free."

**Comment by chipstehr** [comment]
And agreed, that is the text that should go above.

**Comment by carsonefv** [comment]
Ok cool so we will replace "Share your code with friends to get free months of Lantern" with "When your friend purchases the two-year plan you will each get 3 months free, the one-year plan gets you each 1 month free." and remove the text at the bottom correct @p3rcya ?

**Comment by p3rcya** [comment]
@carsonefv Correct.

**Comment by carsonefv** [comment]
@fffw @xiam can you make text these changes?

We are replacing "Share your code with friends to get free months of Lantern" with "When your friend purchases the two-year plan you will each get 3 months free, the one-year plan gets you each 1 month free." and removing the small text at the bottom

**Comment by p3rcya** [comment]
@myleshorton @fffw this need to be fixed before beta

**Comment by fffw** [comment]
PR at https://github.com/getlantern/lantern-desktop-ui/pull/136

What it looks like now. I moved the code and button a bit lower to occupy the space, but you may have some other suggestions @carsonefv .

![image](https://cloud.githubusercontent.com/assets/10410437/16218295/72bc5288-37ae-11e6-9310-ad6c232b3668.png)

**Comment by myleshorton** [comment]
Awesome @fffw!
