### ISSUE TITLE
have to enter verification code

### ISSUE THREAD

**Issue by nanmuyao** [getlantern/lantern#4640]
when you use lantern for Google search and have to enter the verification code Every time,this can be deal?
@marcenuc 

![image](https://cloud.githubusercontent.com/assets/7760063/15988413/3e93a5de-3082-11e6-9271-123828ebff3e.png)

**Comment by junyuecao** [comment]
Same here

**Comment by fffw** [comment]
Close in favor of https://github.com/getlantern/lantern/issues/4562
