### ISSUE TITLE
use updated Pro sever string

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4643]
Update the string on transifix Pro-server

**Comment by fffw** [comment]
Updated at getlantern/pro-server@f981fbd. Will go live on next deployment.

**Comment by fffw** [comment]
Pushed a new batch of translations. Keep it open as a reminder there are new strings to push.

**Comment by myleshorton** [comment]
We can close this now right guys?

**Comment by p3rcya** [comment]
@fffw The mailed code is not in transfex yet I think

**Comment by fffw** [comment]
@p3rcya Ah yes, pro-server didn't have that string translated yet. We can either let the translation and code in the same pro-server repo, or switch back to email template to gain some freedom to beautify the email independently. @uaalto @myleshorton what's your preference?

**Comment by uaalto** [comment]
We are handling these things in the pro-server, we might as well handle the emails too, yes. If we are going to send a plain text email for a while, we can very easily add translation for that. Should I go on and do it?

**Comment by fffw** [comment]
Good to me @uaalto . It's simpler atm.

**Comment by p3rcya** [comment]
@uaalto Please mention me when uploaded to transifex

**Comment by uaalto** [comment]
I will @p3rcya
