### ISSUE TITLE
String not pushed to transifex

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4646]
![image](https://cloud.githubusercontent.com/assets/7925929/15989402/60c0cb3a-302a-11e6-9ddd-62cca9830a81.png)

The text "when your friends..." not pushed to transifex. The current Chinese translation is of the old English text.

**Comment by p3rcya** [comment]
![image](https://cloud.githubusercontent.com/assets/7925929/16187171/a79e0dba-3683-11e6-89e3-1c639d53ac70.png)
This is the page for email verification. The English translation is updated to replace text with email but the Chinese translation is still about text

**Comment by atavism** [comment]
Here's what it is now: ![image](https://cloud.githubusercontent.com/assets/6346213/16222431/d0f44fa2-374c-11e6-9d57-98eebf5ce6a6.png)
