### ISSUE TITLE
Copy referral code

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4648]
![image](https://cloud.githubusercontent.com/assets/7925929/15989458/ba8a5586-302b-11e6-9f51-b5dc7e36f770.png)

We should add a copy code above text invite. So it will be 
Copy code,
text invite
email invite

[The copied content should just be what we put in the other two buttons ]

**Comment by myleshorton** [comment]
Any thoughts on this @Derekf5 and @carsonefv?

**Comment by Derekf5** [comment]
Whats the purpose of the copy button @p3rcya?  there is supposed to be a social share button below the two there now as well.   i think due to space i would advocate for the referral code just copying on click of the code itself, and showing a snackbar that say code copied.  what do you think @myleshorton @carsonefv

**Comment by atavism** [comment]
Another thing we could do is just if the user taps on the referral code, it's automatically copied to the user's clipboard. That eliminates the need for a copy button.

**Comment by p3rcya** [comment]
If we have the social sharing button, then I agree with the one tap copy.

**Comment by p3rcya** [comment]
But not only is the referral code is copied, [The copied content should just be what we put in the other two buttons ]

**Comment by atavism** [comment]
@p3rcya you mean when the user clicks on "Text Invite" or "Email Invite", copy that text to the user's clipboard as well?

**Comment by p3rcya** [comment]
@atavism Sorry I meant when you copy the referral code, you not only copy "KFLKFQ" but also the full text. "Use my code KFLKFQ to get up to 3 additional months free after purchase Download Lantern https://.... "

**Comment by atavism** [comment]
Thanks! Latest build has this change.

**Comment by atavism** [comment]
@p3rcya I added a new string for this on Transifex. Once translated, I'll pull in all of the updated translations.

**Comment by p3rcya** [comment]
@atavism Done. But instead of using https://bit.ly/lanternapk for all of our links, maybe we can use a general download link. For Chinese, it will be https://github.com/getlantern/mirror (or short link to this )We can create such a page in English too
