### ISSUE TITLE
ensure lantern does not leak browsing to proxied domains

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#465]
1. user in get mode requests a page from a domain on the proxied sites list
1. request is encrypted and rerouted to a lantern peer, hiding its destination domain from intermediaries
1. page loads, references a resource on a domain which is not on the proxied sites list
1. browser requests the referenced resource with a `referer` header referring to the page that was just proxied

Lantern should proxy the request to the referenced resource, even though its domain is not on the proxied sites list, because its referrer was a proxied request. In other words, Lantern should proxy any request to a domain on the proxied sites list, or with a `referer` header whose domain is on the proxied sites list.

**Update:**

**Impossible with PAC files and for https requests. But we can and should strip `referer` headers referencing proxied sites from http requests.**

**Comment by myleshorton** [comment]
Hey @fffw we should really handle this within detour as well. It really only matters for HTTP since with HTTPS the Referer header is encrypted anyway.

**Comment by myleshorton** [comment]
This really hasn't been an issue in practice.
