### ISSUE TITLE
Quota progress bar not shown on FireFox

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#4654]
![screen shot 2016-06-13 at 11 39 51 am](https://cloud.githubusercontent.com/assets/385670/16015504/92b818dc-315b-11e6-96a2-d90b64f15bbe.png)

**Comment by myleshorton** [comment]
This is in free right @xiam?

**Comment by xiam** [comment]
Right and only on Firefox.

**Comment by myleshorton** [comment]
Oh FF -- gotcha missed that thanks @xiam.

**Comment by myleshorton** [comment]
Just added that to the description..

**Comment by xiam** [comment]
This is probably caused by a bad locale.

**Comment by xiam** [comment]
This is working fine now (after fixing locale handling in server side).
