### ISSUE TITLE
UI: Main screen header wrong color

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4655]
<img width="660" alt="screen shot 2016-06-13 at 12 38 58 pm" src="https://cloud.githubusercontent.com/assets/7864729/16015560/41ad9846-3164-11e6-98a4-507337f302eb.png">

**Comment by atavism** [comment]
Is this fixed now, @Derekf5?

**Comment by Derekf5** [comment]
yup! @atavism
