### ISSUE TITLE
UI: Prices show up as random characters in plans screen

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4658]
<img width="524" alt="screen shot 2016-06-13 at 12 50 06 pm" src="https://cloud.githubusercontent.com/assets/7864729/16015812/7508f4d2-3165-11e6-8e5e-a03a4d30df89.png">

**Comment by atavism** [comment]
@Derekf5 I'm always using default plans now (until the Pro server replies with the latest prices).

**Comment by atavism** [comment]
CC: @WolfLantern
