### ISSUE TITLE
Add email editing to account management page

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4665]
@carsonefv and @Derekf5 this will be required for this version, so users should be able to edit their email along with managing their devices I think.

**Comment by Derekf5** [comment]
OK @myleshorton will we keep the phone number?

**Comment by myleshorton** [comment]
Not for now @Derekf5 -- looks like we're eliminating phone verification for now.

**Comment by carsonefv** [comment]
@myleshorton @WolfLantern Are we eliminating phone verification for good or just testing? If we are eliminating for good there are some other screens that @Derekf5 and I need to redesign

**Comment by Derekf5** [comment]
Since we will always capture the users email whether it be thru stripe or alipay, we are cutting this option from MVP is that correct @myleshorton

**Comment by myleshorton** [comment]
Yes that's right @Derekf5

**Comment by Derekf5** [comment]
Actually @myleshorton i think we might still need this for users who get pro thru referrals.  SO we basically need a account management screen for unauthorized pro users that just asks them to give us an email address so that they can link devices.    AFAIK this is implemented on mobile (would just need to change from phone number to email)  i just have not been able to test getting an pro account thru referrals yet.  @atavism can you confirm the Pro account management for unauthorized pro users is already implemented?   cc: @carsonefv

**Comment by myleshorton** [comment]
Yeah that's one of the trickier flows for sure @Derekf5. The idea is that we need it **for non-paying pro users to link devices** right? I can't remember now -- how does that work currently @Derekf5 and @uaalto? How can non-paying pro users link devices, or can they?

**Comment by Derekf5** [comment]
for reference this is what that flow currently looks like.
<img width="907" alt="screen shot 2016-06-14 at 10 59 29 am" src="https://cloud.githubusercontent.com/assets/7864729/16047701/25970366-321f-11e6-9c81-a66c37b240ff.png">

**Comment by myleshorton** [comment]
You read my mind @Derekf5 =). Oh right -- so we just need to update that screen for email right? Is there an equivalent on desktop?

**Comment by Derekf5** [comment]
@myleshorton so basically for a non paying pro user those are the screens that would show up in lieu of the full account management screen.     once you have authorized your number (now email) this would show  up
![f87eccfa-281f-11e6-89e7-6ec10ac54746](https://cloud.githubusercontent.com/assets/7864729/16047828/a613da0a-321f-11e6-86c9-3cd7a841ddd1.png)

**Comment by Derekf5** [comment]
@myleshorton def. @carsonefv should have those, im just not sure if they have been implemented, because i have been unable to test getting pro by someone else checking out with my referral code.

**Comment by Derekf5** [comment]
I think it will be best if i just spec out this flow on another ticket...

**Comment by myleshorton** [comment]
> @myleshorton def. @carsonefv should have those, im just not sure if they have been implemented, because i have been unable to test getting pro by someone else checking out with my referral code.

What happens when you test it?
