### ISSUE TITLE
UI: Unauthorized Pro user account management email authorization

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4677]
<img width="1003" alt="screen shot 2016-06-14 at 11 45 18 am" src="https://cloud.githubusercontent.com/assets/7864729/16049430/b005fb1e-3225-11e6-895e-366f710bf0dc.png">

@atavism this is the screen that should show when a user that has obtained pro by referral clicks on the "Pro Account Management" Menu Item.   Since we wont have their email their email we have to capture it here before they can see the full Pro account management screen.   This is essentially the same screen as the old phone number verification, just please note the copy changes, and icon changes (which you should already have from the send desktop screen).

After the user goes thru this flow the Full Pro account management screen should open.

**Comment by p3rcya** [comment]
Add notice to users to check spam folder @Derekf5

**Comment by Derekf5** [comment]
@atavism Here is the enter verification code screen with the check spam folder copy added. same as #4678 
<img width="293" alt="screen shot 2016-06-14 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/7864729/16058106/cda7dec4-324a-11e6-9f0d-4e075933430b.png">
