### ISSUE TITLE
UI: Authorize device for Pro phone number to email change

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4678]
<img width="995" alt="screen shot 2016-06-14 at 11 57 53 am" src="https://cloud.githubusercontent.com/assets/7864729/16049925/8382d9fc-3227-11e6-921b-0608dfb5ad9a.png">

Essentially the same screen as #4677.  This is the screen users will see when they want to link their device.  Please note changes in copy and input fields. as well as icon changes.

after a user goes thru this flow they should return to the main screen, as a pro user.

**Comment by p3rcya** [comment]
@Derekf5  Add notice to users to check spam folder

**Comment by Derekf5** [comment]
@atavism Here is the enter verification code screen with the check spam folder copy added.
<img width="293" alt="screen shot 2016-06-14 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/7864729/16058083/bc63c22c-324a-11e6-92b4-281382f04ba6.png">
