### ISSUE TITLE
UI: Authorize Device for Pro screen, update to email verification

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4679]
![screenshot 2016-06-14 12 08 47](https://cloud.githubusercontent.com/assets/4400763/16050373/7224d30c-3229-11e6-94c2-b669b12d52b9.png)

@myleshorton This is the pop-up screen that should show when a user wants to authorize their device with their existing Pro account by clicking on the "Authorize Device for Pro" Menu Item. This is essentially the same screen as the old phone number authorization, just please note the copy changes, and icon changes (which you should already have from the send mobile screen). cc @Derekf5

**Comment by myleshorton** [comment]
Awesome @carsonefv thanks!!!

**Comment by myleshorton** [comment]
Where can I find those icons @carsonefv?

**Comment by carsonefv** [comment]
@myleshorton @xiam The only icon you need to change is the email icon, you can find it here: https://www.dropbox.com/s/tbyicc9t2ebxumg/Email.svg?dl=0

**Comment by p3rcya** [comment]
@carsonefv Add notice to users to check spam folder

**Comment by carsonefv** [comment]
@p3rcya does this work?

Change last bullet point to say: 

• Didn't receive a code? Please check your spam folder make sure your email address is entered correctly above

**Comment by p3rcya** [comment]
yeah. (I added the word and between two sentences )
• Didn't receive a code? Please check your spam folder and make sure your email address is entered correctly above

**Comment by carsonefv** [comment]
Ok thanks @p3rcya , @xiam can you make sure the last line gets changed to this text?

• Didn't receive a code? Please check your spam folder and make sure your email address is entered correctly above

**Comment by carsonefv** [comment]
@xiam please note padding changes to accommodate the new text:

![screenshot 2016-06-14 16 12 10](https://cloud.githubusercontent.com/assets/4400763/16058132/e6ea8238-324a-11e6-95e4-024c9dad87ef.png)

**Comment by xiam** [comment]
This is what we currently have now, fields are disabled but texts are in place, I'm waiting for an API update to complete this flow.

![screen shot 2016-06-14 at 6 16 19 pm](https://cloud.githubusercontent.com/assets/385670/16062949/25a64d84-325c-11e6-9a8a-bbbd11e692d0.png)

**Comment by myleshorton** [comment]
Awesome on this one @xiam. I'm hoping we can get the API updated today and can pull this in. Do you think that's feasible @uaalto? I can jump in on that as well.
