### ISSUE TITLE
UI: Pro Account management screen changes

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4680]
![menu-spec-sheet](https://cloud.githubusercontent.com/assets/7864729/16050619/5e2adc60-322a-11e6-9f43-c0488da2ffda.png)

@atavism only changes here were removing a button. and the phone number to email change. 
as well as some minor padding changes on the expiration text. cc @carsonefv

**Comment by Derekf5** [comment]
@atavism, @myleshorton said we are going to skip the send your logs feature for this release.  Please note updated padding from the bottom for renew pro account button, and updated padding for expiration text.
![menu-spec-sheet](https://cloud.githubusercontent.com/assets/7864729/16051635/8cfdac30-322e-11e6-9ed5-ed6148851869.png)

**Comment by atavism** [comment]
@Derekf5 @myleshorton Huh? Why would we remove "Send Logs"? It's already working and tested.

**Comment by Derekf5** [comment]
@atavism dont, know @myleshorton just mentioned it on the desktop version of this ticket. #4684

**Comment by atavism** [comment]
I think we should keep it, especially since mobile users have no other way to send us their logs currently! Is that fine, @myleshorton? Just leave it out of desktop for now?

**Comment by Derekf5** [comment]
cool yeah i could of been mistaken, @myleshorton never explicitly said to leave it out of mobile.  Sorry for any confusion!  In that case @atavism  just use the first spec sheet i sent at the top.

**Comment by myleshorton** [comment]
Yeah sorry I was only suggesting removing it from desktop @Derekf5 and @atavism
