### ISSUE TITLE
UI: When entering referral code give feedback that free months have been added

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4683]
@atavism this is basically a duplicate ticket of #4577, just want to make sure this gets knocked out on android too.  quoting @carsonefv 's changes here

"When entering Promo code there is currently no confirmation that free months have been added, can we make a notification saying "Three free months added!" or "One Free month added!" in place of the error text in #28BCD3 color text?"

**Comment by atavism** [comment]
Hey @Derekf5, when should this notification appear? On the welcome screen, after the user goes through checkout?

**Comment by Derekf5** [comment]
right after you hit apply promotion,  I was wrong above though.  this should be a shackbar and the text should be white and say "Your free months will be added for you and your friend once you finish checkout!"
