### ISSUE TITLE
UI: Pro Account Management for Authorized Pro user, update to email instead of phone number

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4684]
![screenshot 2016-06-14 12 29 00](https://cloud.githubusercontent.com/assets/4400763/16050937/9816e63e-322b-11e6-9b53-41ce506e2180.png)

@myleshorton this is the screen that should pop up when an Authorized Pro User clicks on the "Pro Account Management" menu Item - This user has either paid for Pro and we captured their email address that way, or they are on referral and authorized their account by entering their email address.  The only changes here from the most recent iteration of Pro Account Management is changing "Verified Phone Number" to "Verified email address" in copy, and removing the "Change Phone Number" button at the bottom. cc @Derekf5

**Comment by Derekf5** [comment]
@carsonefv can you right justify that email address?

**Comment by Derekf5** [comment]
and change it from verified email to just "email address" @carsonefv

**Comment by myleshorton** [comment]
I think we should also skip "Send us your logs" for now guys.

**Comment by Derekf5** [comment]
Cool in that case @carsonefv we should make the padding from the bottom the same as other buttons without a text link below..

**Comment by carsonefv** [comment]
here's the updated screen @myleshorton @Derekf5 : 
![screenshot 2016-06-14 12 45 36](https://cloud.githubusercontent.com/assets/4400763/16051468/fb1dd7fe-322d-11e6-96cf-03622aa9b810.png)

**Comment by myleshorton** [comment]
Thanks @carsonefv!

**Comment by Derekf5** [comment]
@carsonefv this button should be the darker blue, we only use the light blue for buttons when there are two buttons. this button should be #036165 with white text correct?

**Comment by carsonefv** [comment]
thanks @Derekf5, @myleshorton  here's another update with the button color as #036165 and button text as #FFFFFF

![screenshot 2016-06-14 14 40 43](https://cloud.githubusercontent.com/assets/4400763/16055182/3910b80a-323e-11e6-8dac-d6ffd1dbce8e.png)

**Comment by p3rcya** [comment]
The expiration date is not implemented for build 0618, correct?

**Comment by myleshorton** [comment]
Correct, although that is actually quite easy to add, although the months
data is not currently available.

**Comment by myleshorton** [comment]
This is implemented with a tweak or two.

**Comment by sunshine19090** [comment]
The phone number verificaiton is not seen anywhere now. So closing this. We can track the other issues separately.
