### ISSUE TITLE
UI: Pro Account Management for Unauthorized Pro user, update to email verification

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4685]
![screenshot 2016-06-14 12 32 14](https://cloud.githubusercontent.com/assets/4400763/16051039/0bf3d9e0-322c-11e6-87d0-2fb86bc1ef0a.png)

@myleshorton this is the screen that should pop up when a user that has obtained Pro by referral clicks on the "Pro Account Management" Menu Item. Since we won't have their email we have to capture it here before they can see the full Pro account management screen. This is essentially the same screen as the old phone number verification, except for the changes to email verification in copy and icon (https://www.dropbox.com/s/tbyicc9t2ebxumg/Email.svg?dl=0).

After a user has completed this screen the Authorized Pro User "Pro Account Management" screen should show up next in the flow (you can see that updated screen  here https://github.com/getlantern/lantern/issues/4684) cc @Derekf5

**Comment by myleshorton** [comment]
Perfect @carsonefv thanks

**Comment by p3rcya** [comment]
@carsonefv  Add notice to users to check spam folder

**Comment by carsonefv** [comment]
@myleshorton please note the following text changes as suggested by @p3rcya and adjust the padding as seen below

Change last bullet point to say:

**• Didn't receive a code? Please check your spam folder and make sure your email address is entered correctly above.**

![screenshot 2016-06-14 16 17 05](https://cloud.githubusercontent.com/assets/4400763/16058228/72b9037a-324b-11e6-9b2e-634191c7f577.png)

**Comment by myleshorton** [comment]
Thanks @carsonefv. FYI @xiam

**Comment by xiam** [comment]
This is basically the same interface here https://github.com/getlantern/lantern/issues/4679, just a different copy. I'll make sure we can reuse this code.

**Comment by sunshine19090** [comment]
@myleshorton I am not getting this screen when I click on the Account management.
Steps:
1. Get the referral code from the free user.
2. Use it in another device and become a pro user.
3. Now the free user becomes a pro user. (Note: There is no welcome screen. Just refreshing takes the user to pro UI).
4. Click on the account management. The screen has the bonus month detail and the system details. I am not getting the screen to enter the email address for verification.
![image](https://cloud.githubusercontent.com/assets/11394369/16283198/ba2b4eee-3880-11e6-9075-1ed040c2f0e1.png)

**Comment by myleshorton** [comment]
In the case you're talking about @sunshine19090, the second user is becoming a pro user through paying for pro right? And using the referral code while checking out? In that case we already have their email address, and they should see the normal account management page.

They should see the email verification page essentially when they're a pro user, and we don't have their email. If they purchase we have their email from Stripe. So the case where we don't have their email is when they become pro _because they refer someone, not when they get refered_.

**Comment by myleshorton** [comment]
Sorry I just re-read your message @sunshine19090 and realized that might have been exactly what you did. Hmnn. We'll test it!

**Comment by sunshine19090** [comment]
With the new build, I am getting the email verification screen but couldn't proceed which is ticketed separately. closing this now.
