### ISSUE TITLE
Mobile - Feeds are not loading

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4688]
I see only the spinner.

**Comment by atavism** [comment]
Thanks, @sunshine19090! @WolfLantern has been seeing this too. I'm going to e-mail you a custom build that makes it easy for you to e-mail me your log to debug this further. Sound good? BTW, are you testing this over WiFi?

**Comment by sunshine19090** [comment]
Yes, Sure @atavism. Yeah, I am using wifi to test.

**Comment by WolfLantern** [comment]
Yes i use wifi to test also

On Tue, Jun 14, 2016 at 1:40 PM, sunshine19090 <notifications@github.com>
wrote:

> Yes, Sure @atavism <https://github.com/atavism>. Yeah, I am using wifi to
> test.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4688#issuecomment-226008993>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AL0uS3mnvK3qpNdY4vBinNmghbCSOCjDks5qLxHGgaJpZM4I1ucG>
> .
>



-- 
*Wolf*

**Comment by sunshine19090** [comment]
@atavism I am able to see the news feed after I purchased pro. The app crashed in between after the purchase. I will see if I can reproduce it without the user signing for pro.

**Comment by atavism** [comment]
Is this still an issue w/ the latest build, @sunshine19090?

**Comment by sunshine19090** [comment]
No @atavism, I couldn't reproduce this on friday. I will try downloading once more today and see if it is still existing.

**Comment by sunshine19090** [comment]
@atavism I couldn't reproduce this is any of the newer builds. So I think it is working fine now. If I come across that again, I will send the logs.
