### ISSUE TITLE
Mobile UI - The toggle doesn't have any text to explicitly tell the user whether it is ON/OFF for everfeed or lantern

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4690]
I feel it is just not clear at first look. I initially thought it is for everfeed.

**Comment by atavism** [comment]
I feel like our toggle button is distinctive enough already the explicit on/off text is unnecessary. Thoughts, @Derekf5?

**Comment by Derekf5** [comment]
Yeah @atavism i agree, but we have both been looking at this for so long it may seem obvious to us for that reason, so I feel like we should consider @sunshine19090 's insight here.   Lets not change anything right now, but we can ask @p3rcya to see what our testers in the field think, and dependent on that we can make necessary adjustments.  What do you think @p3rcya?   Thanks @sunshine19090 for noting this!

**Comment by p3rcya** [comment]
We were discussing that whether we should have android feed by default off.
So that will resolve this issue as well.

On Thursday, June 16, 2016, Derekf5 <notifications@github.com> wrote:

> Yeah @atavism <https://github.com/atavism> i agree, but we have both been
> looking at this for so long it may seem obvious to us for that reason, so I
> feel like we should consider @sunshine19090
> <https://github.com/sunshine19090> 's insight here. Lets not change
> anything right now, but we can ask @p3rcya <https://github.com/p3rcya> to
> see what our testers in the field think, and dependent on that we can make
> necessary adjustments. What do you think @p3rcya
> <https://github.com/p3rcya>? Thanks @sunshine19090
> <https://github.com/sunshine19090> for noting this!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4690#issuecomment-226636338>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqWececr-aMzs4lZb1Uvv5rQfGu1sks5qMdNxgaJpZM4I1vEe>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by Derekf5** [comment]
@p3rcya whats the status on the feed being on or off by default?

**Comment by p3rcya** [comment]
@Derekf5 We haven't decided yet pending user responses. However, you should still design a better UI when the feed is turn off. Now it's mostly white space. (I think it was ticketed in another issue)

**Comment by Derekf5** [comment]
Yes its already designed @p3rcya its just the version with the larger button that we had pre feed.  @atavism just needs to drop that back in.
