### ISSUE TITLE
building error-unknown http.Transport field 'MaxIdleTime' in struct literal

### ISSUE THREAD

**Issue by churchillyik** [getlantern/lantern#4692]
[root@localhost lantern]# make lantern
Building development lantern
** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
# github.com/getlantern/flashlight/proxied
src/github.com/getlantern/flashlight/proxied/proxied.go:391: tr.MaxIdleTime undefined (type *http.Transport has no field or method MaxIdleTime)
src/github.com/getlantern/flashlight/proxied/proxied.go:392: tr.EnforceMaxIdleTime undefined (type *http.Transport has no field or method EnforceMaxIdleTime)
# github.com/getlantern/flashlight/client
src/github.com/getlantern/flashlight/client/reverseproxy.go:21: unknown http.Transport field 'MaxIdleTime' in struct literal
make: *** [lantern] Error 2

**Comment by fliar** [comment]
same issue here, may be caused by custom fork of go ?

**Comment by hongyang51** [comment]
what do we do ?

**Comment by TianYuwan** [comment]
This Error looks like the same with mine: "Type has no field or method", which discussed in issue #4715 and also decribed on the following webpages:
https://github.com/golang/go/issues/10700
https://github.com/golang/go/commit/d4bb72b485cc9aa790e3a176b2e728e2d28d52ed
https://socketloop.com/tutorials/golang-fix-type-interface-has-no-field-or-no-methods-and-type-assertions-example

**Comment by tyrael007** [comment]
@fliar  How can I use the custom fork of go ?

**Comment by myleshorton** [comment]
You need our custom go fork.
