### ISSUE TITLE
Mobile - After disconnecting Lantern via the notification center, turning ON lantern asks for permission to connect to VPN again

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4701]
Steps:

1. Turn ON lantern.
2. Click on the lantern notification.
3. Click on disconnect.
4. Go to the app and toggle the button to ON again.

It asks for permission.

**Comment by atavism** [comment]
This is expected behavior. When you disconnect a VPN from the notification center, you're also revoking its permission to even open a connection to begin with.
