### ISSUE TITLE
Lantern leads to some apps can't access the internet time by time on Mac

### ISSUE THREAD

**Issue by Yasashi** [getlantern/lantern#4703]
使用 Lantern 经常导致部分 app 无法正常上网
Always, it works well for a long time, and then, maybe severval hours after, it causes some apps' network disabled, such as Safari, Slack and the Email, but Chrome works well. 
And sometimes when I quit Lantern, it will causes the same problem above.
These problem has been for severval months at once I started using Lantern.
I must restart my Mac to solve this problem 1 or twice per day.
I'm using the lastest version.
Slack:
![image](https://cloud.githubusercontent.com/assets/12589575/16074702/59eb2cb4-331e-11e6-8f5b-0ea7b8aae4d6.png)
Email:
![image](https://cloud.githubusercontent.com/assets/12589575/16074724/7451e818-331e-11e6-9713-140d9468cbb6.png)
Safri:
![image](https://cloud.githubusercontent.com/assets/12589575/16074745/88a5652e-331e-11e6-87fe-450aaf645bd3.png)

**Comment by joefei** [comment]
有时候IE会无法上网，重置IE以后又可以了。有时切到自己的VPN也不能上网。

**Comment by Yasashi** [comment]
@joefei  貌似还会导致 qq 收不到图像

**Comment by joefei** [comment]
QQ无法收到图片，这个倒是没遇到过。

**Comment by fffw** [comment]
Try `sudo killall -9 networkd`? Similar issue at https://github.com/getlantern/lantern/issues/3039#issuecomment-221778260

**Comment by Yasashi** [comment]
thank you.

**Comment by fffw** [comment]
Does the trick work for you @Yasashi ?
