### ISSUE TITLE
I need your help! thanks! I can't be run "make android-sdk"  Mac OS X

### ISSUE THREAD

**Issue by hongyang51** [getlantern/lantern#4706]
May I  " make android-sdk"   && "make android-debug" && "make android-install" all  to
 
> gomobile: xcrun --show-sdk-path: exit status 1
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'

**Comment by hongyang51** [comment]
I  should  download the  xcode ?

**Comment by xiam** [comment]
Hello @hongyang51,

Yes you need XCode, `gomobile` requires it.

**Comment by hongyang51** [comment]
@xiam   
Thank you very match!  My English is bad ! Forgive me !  I will continue to learn
