### ISSUE TITLE
Get Mobile Version screen is redundant for pro users

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4720]
We already have the pro user's email address, so I don't think we need to prompt them for it again.  We could just send the email and show a toast saying we did it.

**Comment by Derekf5** [comment]
what if someone uses a specific email address for their stripe or alipay account but nothing else?

**Comment by Derekf5** [comment]
we could just prefill the field with the email we assume they would want to use, and allow them to hit send.   If they dont want it going to that address then they can change it.

**Comment by oxtoacart** [comment]
Prefilling sounds like a decent approach.  In practice, to add their phone to their pro account, they will need to be able to receive a verification code at the email address on file, so I think it would be okay to just automatically use that email address and just show a toast saying we sent them an email.  I don't have a strong feeling either way, but both are better than status quo.

**Comment by oxtoacart** [comment]
If we did just skip straight to the toast, we would want to make sure to include the address to which we sent the email as part of the message.

**Comment by p3rcya** [comment]
I created this ticket long time ago https://github.com/getlantern/lantern/issues/4561 I believe my solution is better than the current design. If you agree, please close this ticket.

**Comment by sunshine19090** [comment]
@oxtoacart @Derekf5 @p3rcya Why do we want the user to go back to their email for downloading? We can just provide them a download button to start the downloading or take them directly to our download site.  However, I agree with @oxtoacart to just show the email address in the message if there is any other specific reasons for this feature.

**Comment by p3rcya** [comment]
@sunshine19090 a button might not do because users probably want to download it directly and rather than download it then send it to mobile. But we can have a field asking users to input their phone number and we can send the download link. But the most basic version will just provide a clickable download link (not a button)

**Comment by Derekf5** [comment]
+1 on @p3rcya's solution here #4561   I will close this ticket unless anyone disagrees.

**Comment by oxtoacart** [comment]
@Derekf5 I see the approaches as complementary, i.e. show a QR code but also send an email automatically if we already have your email address.  The email is handy in those cases where I don't have my phone and computer together at the same time, for example if I'm asking my wife to send me the link while I'm traveling.  If we hadn't already built the email functionality, I'd see it as optional, but since we have it we might as well keep it.

**Comment by Derekf5** [comment]
Right, I think that makes sense. It also provides a fail safe if the links/qr code are blocked, @oxtoacart.  I will adapt the current design to provide all three options.

**Comment by oxtoacart** [comment]
Thanks @Derekf5 !

**Comment by Derekf5** [comment]
NP @oxtoacart , gonna close this since i just opened a design ticket for it #4755

**Comment by Derekf5** [comment]
@carsonefv here is the relevant info for #4755
