### ISSUE TITLE
[Desktop] Styling of FAQ link on About page seems off

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4722]
It's a blue that I haven't seen elsewhere in the UI.  @Derekf5 does the below look right?

![screen shot 2016-06-18 at 3 26 53 pm](https://cloud.githubusercontent.com/assets/5000654/16173543/5f46db8e-3569-11e6-8896-5bdbdc3fbc3a.png)

**Comment by Derekf5** [comment]
Thanks @oxtoacart ccing: @carsonefv since she takes care of most desktop issues.  @carsonefv what do you think?

**Comment by Derekf5** [comment]
Oh sorry @oxtoacart i misread the initial ticket, yes "QUESTIONS" and "READ THE LANTERN FAQS" should be color  #00BCD4.  Good eye!
