### ISSUE TITLE
[Desktop] Connect/Disconnect Toggle is Confusing

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#4723]
Note - this applies both to the link in the hamburger menu as well as clicking on the green/red indicator light at the bottom right of the screen.

I feel like we discussed this before, but I'm still seeing really confusing behavior here.

In the screenshot below, you'll see that I'm "disconnected" because I can click "Connect".  You'll also see that "Lantern is Off".  However, in the settings screen, you can see that "Manage System Proxy" and "Proxy All Traffic" are on.  So, is Lantern proxying my stuff or not?  It turns out that it's not, but that's not clear to me from the messages in the UI.

Another interesting combination is "connected" with "Manage System Proxy" off.  Can you guess what Lantern is doing there?  Turns out it is managing my system proxy anyway and happily proxying my stuff.

cc: @xiam @myleshorton @Derekf5

**Comment by Derekf5** [comment]
I think we should eliminate the ability to click on the indicator.  We decided this a while back, but i guess it was never ticketed and slipped thru the cracks.

**Comment by oxtoacart** [comment]
> I think we should eliminate the ability to click on the indicator

+1  That would include getting rid of the Connect/Disconnect entry in the hamburger menu too, right?

**Comment by Derekf5** [comment]
Hmm not Necessarily @oxtoacart.  Most Other vpns allow you to turn them on/off, and since we will have a cap for free users it might be nice to be able to switch it off without closing the program.  What do you think?

**Comment by Derekf5** [comment]
@myleshorton @xiam, @oxtoacart and I just had a brief chat on this, and both think the best option for now is to remove the connect/disconnect in the menu for this release.  In a later release I can come up with simpler more strait forward option for the 3 state issue that we have (Smart proxy, proxy all, off).   How does that sound to you all?

**Comment by xiam** [comment]
No problem @Derekf5!

**Comment by myleshorton** [comment]
works for me.
