### ISSUE TITLE
[Desktop] Opening Language settings does not show which language is selected

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4725]
When a user opens the language menu the language that is currently being used should be selected.
This is what currently appears.  CC: @xiam 
<img width="668" alt="screen shot 2016-06-20 at 12 03 30 pm" src="https://cloud.githubusercontent.com/assets/7864729/16201397/23fac884-36df-11e6-8d24-7ca76f81731e.png">

**Comment by sunshine19090** [comment]
That worked fine for me in both Chrome and Firefox @Derekf5. May I know in which system?

**Comment by sunshine19090** [comment]
Also @Derekf5 , I still have the question lingering in my mind. Why do we need to give user the option to change the language in UI (mobile and desktop)?

**Comment by Derekf5** [comment]
@sunshine19090 this is on Chrome, on a Mac.   Are you asking why dont we just rely on auto detecting the users language settings?

**Comment by Derekf5** [comment]
and is that currently done based on the users browser language setting?

**Comment by p3rcya** [comment]
@Derekf5 I'll say no Chinese users would need this selection. But there might be corner cases where foreigners use a Chinese public computer and want to use switch it to English. But I think if he is good enough to use a Chinese OS, he can use Chinese in Lantern

**Comment by Derekf5** [comment]
yeah so i think we should keep it for corner cases, also some users have asked for it in the past @p3rcya @sunshine19090

**Comment by myleshorton** [comment]
This will be fixed with the latest updates in what I think will be 3.2.0. (an incidental fix really).
