### ISSUE TITLE
Display information about the bonus months and when pro will expire somewhere in the UI

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4735]
Most probably in Account management. I remember discussing this in another ticket but looks like we haven't implemented it. I couldn't find that ticket. 

@Derekf5 @p3rcya

**Comment by p3rcya** [comment]
It should say
Your account will expire at ... including x bonus months.

**Comment by Derekf5** [comment]
Yes this is specified in ticket #4684 cc: @myleshorton @xiam

**Comment by myleshorton** [comment]
Yeah the time remaining is implemented in the latest build @sunshine19090, and the bonus months data still needs to come from the backend. That's ticketed at https://github.com/getlantern/pro-server/issues/135
