### ISSUE TITLE
Mobile - While authorizing by email verification, the processing request doesn't end at all

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4737]
I couldn't authorize my device as the processing request goes on indefinitely. Ticketed separately for desktop #4739

**Comment by myleshorton** [comment]
This worked for me just as an additional data point @atavism

**Comment by myleshorton** [comment]
Are you still able to reproduce this one @sunshine19090?

**Comment by sunshine19090** [comment]
@myleshorton I couldn't test this now as the checkout process fails with both the test cards as well as a  real card.

**Comment by myleshorton** [comment]
This should be fixed outside of the blocking issues we've seen.
