### ISSUE TITLE
Getting an error message "User link not configured" when entering an incomplete/invalid email address

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4740]

**Comment by sunshine19090** [comment]
![image](https://cloud.githubusercontent.com/assets/11394369/16212187/eecdd68a-36fa-11e6-926a-ae8c408e9797.png)

**Comment by sunshine19090** [comment]
FYI @myleshorton - I meant to say that the error message should be specific. It will be nice if we can change the "User link not configured" to some layman language like "Email address does not have a pro account" or something that is easy to understand for the user. I am sorry for not being clear in the ticket description.

**Comment by myleshorton** [comment]
Makes sense @sunshine19090

**Comment by p3rcya** [comment]
this is fixed
