### ISSUE TITLE
Change the main pro screen wording

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4743]
The current screen is 

![image](https://cloud.githubusercontent.com/assets/7925929/16221654/ded42f88-3748-11e6-861a-4e70b01620c7.png)

The wording should be 

Invite friends, get more Pro for free

When your friend purchases the two year plan you each get 3 additional months of Pro, the one year plan gets you each 1 month free.

[The issue is moved from the email thread]

**Comment by fffw** [comment]
I guess the text should be (removing the last "free"):
> When your friend purchases the two year plan you each get 3 additional months of Pro, the one year plan gets you each 1 month ~~free~~.

**Comment by p3rcya** [comment]
@fffw No. I meant change the title to (the text below should stay the same)

**Invite friends, get more Pro for free**

When your friend purchases the two year plan you each get 3 additional months of Pro, the one year plan gets you each 1 month free.

**Comment by fffw** [comment]
Ok @p3rcya . Just want to make sure the text reads correct.
