### ISSUE TITLE
Code not defined in sharing text

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4746]

**Comment by myleshorton** [comment]
I can't reproduce this @chipstehr from either the free page main page or pro main page. Which link did you click to copy the referral text?

**Comment by chipstehr** [comment]
![screen shot 2016-06-21 at 12 18 23 pm](https://cloud.githubusercontent.com/assets/10291424/16237398/4c144964-37aa-11e6-8e22-b7e253e77f43.png)

**Comment by chipstehr** [comment]
I just pushed copy your code.

**Comment by chipstehr** [comment]
Reset it and it worked! 
![screen shot 2016-06-21 at 2 11 36 pm](https://cloud.githubusercontent.com/assets/10291424/16241087/2203fe16-37ba-11e6-9ca9-e300533e7e82.png)

**Comment by myleshorton** [comment]
Nice thanks @chipstehr! Closing.
