### ISSUE TITLE
[desktop] after checkout not authorized snackbar appears, upgrade does not occur

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4748]
<img width="533" alt="screen shot 2016-06-21 at 11 08 12 am" src="https://cloud.githubusercontent.com/assets/7864729/16236172/694b2912-37a5-11e6-9e07-57928179decb.png">

**Comment by myleshorton** [comment]
I think this was just some intermittent issue on the server, but thanks for reporting @Derekf5!

**Comment by atavism** [comment]
Yeah, I just verified I'm still seeing this with desktop too.

**Comment by myleshorton** [comment]
Do you get this after clearing your lantern directory @atavism?
