### ISSUE TITLE
plan price showing up in USD and it's charging 27 yuan not USD

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4749]
![image](https://cloud.githubusercontent.com/assets/7925929/16238767/8e88e336-3796-11e6-8c10-f0d6bad497ca.png)

**Comment by p3rcya** [comment]
![image](https://cloud.githubusercontent.com/assets/7925929/16241594/308455b0-37a3-11e6-80fc-d16acb19631a.png)

The current plan is also charging 27 Yuan rather than 27 USD!

**Comment by atavism** [comment]
You're testing with an old build. The Pro server started returning a different data type for the user id which broke everything. Can you wait to retest after I send out a new version please?

**Comment by p3rcya** [comment]
Will do

Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by p3rcya** [comment]
It's happening again on 3.0.6 
![image](https://cloud.githubusercontent.com/assets/7925929/16702569/cc132760-451b-11e6-8b94-a6d16ffe5100.png)
