### ISSUE TITLE
Add Qr code and links to get mobile version pop up

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4755]

**Comment by Derekf5** [comment]
@carsonefv the specs can go here for this screen

**Comment by carsonefv** [comment]
@p3rcya @oxtoacart Does this design look ok? Let me know and I can write out the specs if approved

![screenshot 2016-06-29 11 18 10](https://cloud.githubusercontent.com/assets/4400763/16457989/75b8bd3a-3deb-11e6-94a9-9dab65f8bc8a.png)

**Comment by p3rcya** [comment]
1. Use android instead of mobile
2. The QR code should be of the raw.githubiswecontent.com/xxx link rather
than the tiny URL link. (So it won't be affected if tinyURL is blocked)
3. The button should be movie to the same line as email. And change text to
send download link to my email. 3 is to make explicit the button is only
for the email field.

On Wednesday, June 29, 2016, carsonefv <notifications@github.com> wrote:

> @p3rcya <https://github.com/p3rcya> @oxtoacart
> <https://github.com/oxtoacart> Does this design look ok? Let me know and
> I can write out the specs if approved
>
> [image: screenshot 2016-06-29 11 18 10]
> <https://cloud.githubusercontent.com/assets/4400763/16457989/75b8bd3a-3deb-11e6-94a9-9dab65f8bc8a.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4755#issuecomment-229390606>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqTvwPG4UdeNqynDX4bN0D4nSn_85ks5qQo2ZgaJpZM4I7I_3>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by carsonefv** [comment]
Thanks for the suggestions Percy, how does this look @p3rcya @oxtoacart ?

![screenshot 2016-06-29 11 51 43](https://cloud.githubusercontent.com/assets/4400763/16459198/0a86f374-3df0-11e6-8d32-46c6a3a525fb.png)

**Comment by p3rcya** [comment]
We should still use the short link for the link. I meant only for the
github link for the QR code. (I guess this is more of implementation than
design)

On Wednesday, June 29, 2016, carsonefv <notifications@github.com> wrote:

> Thanks for the suggestions Percy, how does this look @p3rcya
> <https://github.com/p3rcya> @oxtoacart <https://github.com/oxtoacart> ?
>
> [image: screenshot 2016-06-29 11 51 43]
> <https://cloud.githubusercontent.com/assets/4400763/16459198/0a86f374-3df0-11e6-8d32-46c6a3a525fb.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4755#issuecomment-229401061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqVFTEM4kFp16p7jnlEXCdvucVkrpks5qQpUugaJpZM4I7I_3>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by carsonefv** [comment]
Ah ok that makes more sense - see update below

![screenshot 2016-06-29 12 05 30](https://cloud.githubusercontent.com/assets/4400763/16459700/d2e54f68-3df1-11e6-850c-dc3244ef1c90.png)

**Comment by p3rcya** [comment]
Looks great!

**Comment by oxtoacart** [comment]
Nice!  Should we change the title of the window to "Get Lantern Android" too?

**Comment by p3rcya** [comment]
Yes, missed that

**Comment by carsonefv** [comment]
I was wondering the same, that means we'll have to change the menu item as well but that should be easy enough?

**Comment by p3rcya** [comment]
@carsonefv Yeah, that's just a text change. We should do it anyway

**Comment by Derekf5** [comment]
Yes that sounds good re: menu items and header change.   Just ticket the menu item change separately @carsonefv

**Comment by carsonefv** [comment]
Hey @myleshorton @fffw here are the specs for the new Mobile pop-up Screen:

![screenshot 2016-06-29 14 25 54](https://cloud.githubusercontent.com/assets/4400763/16463814/6cbe9e2e-3e05-11e6-9b04-17d88f319a4b.png)

**1.** Edit Top bar text to say "Get Android Version"

**2.** Description text: "Scan the code, use the link, or send yourself an email to get Lantern for Android"
Font:  Roboto Regular; Font size: 18px; Line-height: 24px; color: #000000

**3.** The QR code should be of the raw.githubiswecontent.com/xxx link rather
than the tiny URL link. (So it won't be affected if tinyURL is blocked)

**4.** Tiny url link: Font: Roboto Regular; Font size: 26px; color: #1BBCD3

**5.** Email Field and button are the same, just moved and the email field is shortened to 276px

**Comment by fffw** [comment]
Great! Start working on it.

**Comment by myleshorton** [comment]
Thanks @fffw I don't think is actually allocated for this sprint though. Any reason it should be?

**Comment by fffw** [comment]
Oh I thought it's a leftover of previous sprint. Ok I can leave it for now

**Comment by Derekf5** [comment]
hey @myleshorton any chance we can fit this into this sprint or next?  @p3rcya is seeing complaints of people not being able to get the desktop version because of email issues.

**Comment by p3rcya** [comment]
I propose in Chinese, we just use this link https://github.com/getlantern/mirror It's much shorter and we don't need the URL shortener. 

Other language should make their perspective repo mirrors

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #56](https://github.com/getlantern/lantern-internal/issues/56) via [**ZenHub**](https://www.zenhub.com/)
