### ISSUE TITLE
512 MB remaining free data in OSX

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4762]
I see 512 MB remaining in free user UI. Also, the data cap indicator is showing when I have not started using it. Shouldn't it be showing up only after the user has started using the data @myleshorton ?

<img width="1280" alt="screen shot 2016-06-21 at 4 59 39 pm" src="https://cloud.githubusercontent.com/assets/11394369/16250356/937b08ca-37d1-11e6-9e8e-abe50866e42a.png">

**Comment by p3rcya** [comment]
I think the data bar should show up from the very start. But yeah, it should be 500MB rather than 512MB

**Comment by myleshorton** [comment]
Yeah showing up at the beginning is fine @sunshine19090. @oxtoacart and @uaalto sounds like the proxy is returning 512 as the cap? Should be 500.

**Comment by oxtoacart** [comment]
500 MB (500,000,000 bytes) or 500 MiB (524,288,000 bytes)?

**Comment by myleshorton** [comment]
You're actually the only person I've ever spoken with who considers a megabyte to be 500,000,000 bytes, but yes I'm saying our limit should be 524,288,000 bytes, which has always been my understanding of a megabyte (and I thought everyone's understanding, but Google tells me otherwise - baffling!).

**Comment by oxtoacart** [comment]
For the record, I'm pretty sure I've never considered a MB to be 500,000,000 bytes :)

**Comment by myleshorton** [comment]
This one is all set right @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton It's deployed, but perhaps we should let @sunshine19090 verify?

**Comment by sunshine19090** [comment]
It looks good in mobile and win 7. I will close this after completing the test in OSX and windows 10.

**Comment by sunshine19090** [comment]
@oxtoacart Is there a way to make the free user to go back to 500 MB to test? In OSX, I already used some 10 MB data. So couldn't check this one.

**Comment by oxtoacart** [comment]
@uaalto Do we have an easy way to reset a free user's usage?

**Comment by sunshine19090** [comment]
Tested in production. The data cap indicator starts showing up only after the user starts using the data.
