### ISSUE TITLE
Able to use the same email id to buy again in another device and earn extra bonus

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4763]
I used my email address in both win 7(2 year plan) and OSX to buy one year plan. I used the referral code from win 7 to use it in OSX to get extra referral bonus and it worked. So the user now has 2 months bonus. If I have selected 2 year plan in OSX along with referral code, then I could have got 6 months of bonus. I hope no users will try this :)

I think this is one of the reason that we used phone number verification to have unique users. 

![image](https://cloud.githubusercontent.com/assets/11394369/16250480/8fe0c08c-37d2-11e6-8dbb-c93a0364cf43.png)

<img width="1280" alt="screen shot 2016-06-21 at 5 07 34 pm" src="https://cloud.githubusercontent.com/assets/11394369/16250577/438f1caa-37d3-11e6-9500-c4cce418acb0.png">

**Comment by p3rcya** [comment]
What's wrong with that? If the user is willing to pay double the price, obviously they should get bonus month.

**Comment by p3rcya** [comment]
Remember each user can have 3 linked device. But now he is paying double
