### ISSUE TITLE
build error for MaxIdleTime

### ISSUE THREAD

**Issue by yuan78** [getlantern/lantern#4764]
make linux-amd64
** VERSION was not set, using default version. This is OK while in development.

Build tags: 
Extra ldflags: 
# github.com/getlantern/flashlight/client
# make linux-amd64
** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
# github.com/getlantern/flashlight/client

src/github.com/getlantern/flashlight/client/reverseproxy.go:21: unknown http.Transport field 'MaxIdleTime' in struct literal
# github.com/getlantern/flashlight/proxied
src/github.com/getlantern/flashlight/proxied/proxied.go:391: tr.MaxIdleTime undefined (type *http.Transport has no field or method MaxIdleTime)
src/github.com/getlantern/flashlight/proxied/proxied.go:392: tr.EnforceMaxIdleTime undefined (type *http.Transport has no field or method EnforceMaxIdleTime)

**Comment by fffw** [comment]
Please read https://github.com/getlantern/lantern#prerequisites
