### ISSUE TITLE
Translation doesn't match with English 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4776]
![image](https://cloud.githubusercontent.com/assets/7925929/16322974/fa729882-395b-11e6-864e-a690a7649dde.png)

The log in screen still refer to SMS rather than email. The English copy refers to email though. Maybe the translation is not synced.

**Comment by p3rcya** [comment]
@myleshorton  It happened on mobile before but is not fixed. So @atavism probably know the problem

**Comment by Artoria2e5** [comment]
Looks like fixed on transifex: https://www.transifex.com/otf/lantern/translate/#zh_CN/lantern-new-ui/79938276?qt=%E9%AA%8C%E8%AF%81%E7%A0%81
