### ISSUE TITLE
51200000MB remaining 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4778]
![image](https://cloud.githubusercontent.com/assets/7925929/16324276/b41cac7c-3967-11e6-85c1-a4391f4b3932.png)
Later it becomes a normal number around 300MB

**Comment by myleshorton** [comment]
Yeah I got that too @p3rcya thanks. Any idea what's up with that @oxtoacart? It seems to tell us the cap is super high at the beginning. I can debug that too -- could be some weird client side logic affected by the recent data changes.

**Comment by oxtoacart** [comment]
@myleshorton That's the current cap in production.  You're probably seeing the cap reported by the baked-in fallback (which is from production) and once you get your staging fallback, you see what's reported by that.

The cap is high in production right now to prevent people from being throttled even though we've already enabled all the plumbing.

**Comment by oxtoacart** [comment]
Once we enable pro for real in production, this won't be an issue anymore.

**Comment by p3rcya** [comment]
But when pro is released, we still don't want to limit older version/3rd
parties till we implement the hijacking traffic to landing page.

On Thursday, June 23, 2016, oxtoacart <notifications@github.com> wrote:

> Once we enable pro for real in production, this won't be an issue anymore.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4778#issuecomment-228246867>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqYCzzmBiSWvKNfrANDfHTRX_VQYfks5qO0kWgaJpZM4I9XMe>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment]
That makes sense @oxtoacart. OK I'll add some client-side logic for handling that.
