### ISSUE TITLE
[Desktop]Cannot log out

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4780]
![image](https://cloud.githubusercontent.com/assets/7925929/16331271/f495cfcc-39a3-11e6-94c1-4cd9bcd68781.png)
After removing windows 10 in the account management page, I still have Pro. 
Build 0624

**Comment by sunshine19090** [comment]
https://github.com/getlantern/lantern-desktop-ui/issues/131 and also in 139 - This ticket is being discussed here. Closing.
