### ISSUE TITLE
[Desktop] Force caps on promotion input

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4784]
Currently when a user enters a code in the promotion screen before checkout if they put the code in lowercase it serves an error.  On mobile we are forcing caps so that this does not happen, could we also do that on desktop? @xiam @myleshorton

**Comment by myleshorton** [comment]
Sounds like a good idea @Derekf5 yeah sure.

**Comment by xiam** [comment]
See https://github.com/getlantern/lantern-desktop-ui/pull/174/files
