### ISSUE TITLE
[Mobile] Did not receive Pro when a friend used my referral code 

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4785]
As a free user on mobile i used my referral code to checkout with a different email address on desktop.   I received  the free months on desktop, but my free account on mobile was not converted to Pro.

*these devices have been linked before, not sure if this could be causing the issue, just wanted to make a note.

**Comment by myleshorton** [comment]
You made the purchase on _desktop_ right @Derekf5? Just making sure I understand.

**Comment by Derekf5** [comment]
thats correct @myleshorton

**Comment by atavism** [comment]
@Derekf5 I thought we ruled out that scenario though by saying a user has to purchase Pro to claim their free months (so no account would ever be automatically converted from free to Pro).

**Comment by Derekf5** [comment]
Oh @atavism it was my understanding that in this instance only  the person who was reffered has to purchase Lantern, is that your understanding @myleshorton

**Comment by myleshorton** [comment]
Yeah so basically the idea is that *someone has to buy* always, and in particular the person who was referred. If the person who was referred buys Lantern, then the originator of that referral code should become pro without purchasing @atavism.

**Comment by myleshorton** [comment]
And that's also reflected in the pro-server data - i.e. once the referral happens, you'll see the referer become pro data-wise even though they've never paid.

**Comment by atavism** [comment]
Oh, gotcha. I make that /user-data call periodically already so I'll just add a check to see if the user becomes Pro. Ideally, we'd do this via a push notification (so when a user purchases Pro with my referral code I immediately receive my free month). Hey @uaalto, what's the status of that actually?

**Comment by myleshorton** [comment]
Yeah right @atavism on the desktop side you currently have to refresh to see it, so similar problem.

**Comment by Derekf5** [comment]
@atavism yeah that notification is ticketed here #4758

**Comment by uaalto** [comment]
@myleshorton  When a code is redeemed the Pro server sends a push notification request, yes. 

https://github.com/getlantern/pro-server/blob/master/src/pro_server/redis.clj#L433

(I've ticketed the fact that it doesn't reflect the actual number of months awareded)

**Comment by myleshorton** [comment]
Oh sweet @uaalto! So maybe it's just a matter of something actually listening on the other end @atavism? That would be cool. We should connect desktop to the pubsub server as well.

**Comment by atavism** [comment]
This should be fixed now. Just needed to re-enable pubsub on the client side.
