### ISSUE TITLE
[Desktop] Pro account setting not showing up after buying pro 

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4786]
This has been repeatable for me. after i buy pro on desktop once the Ui changes to reflect the purchase everything looks good except i cant see pro account management in the menu until i refresh. @xiam @myleshorton

**Comment by myleshorton** [comment]
Thanks @Derekf5 this is a duplicate of https://github.com/getlantern/lantern-desktop-ui/issues/139
