### ISSUE TITLE
A big X mark appears when entering the email address for verification in IE11

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4788]
It looks really bad, so marking this as P1.

![image](https://cloud.githubusercontent.com/assets/11394369/16350146/de50a958-3a11-11e6-8a07-cca4ec498af0.png)

**Comment by myleshorton** [comment]
Ha! I'll give it a look thanks @sunshine19090

**Comment by fffw** [comment]
Same on IE 10. I suspect that `<TextField>` has some css effect that doesn't supported by IE.

**Comment by fffw** [comment]
Fixed. Will be in next build. @sunshine
