### ISSUE TITLE
Always getting "User link not configured" error message even for a  valid email address while verifying for an unauthorized pro user

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4789]
This happens for a free user who has been upgraded to Pro due to referrals.

When that user clicks on Account Management, we ask the user for her email address, since we don't have that on file yet.  When user enters her email address and clicks Send, she is presented with the below error.

Also, the language on the screen could be improved to indicate that what we're doing is email verification rather than account management.

This seems to be working on mobile

![image](https://cloud.githubusercontent.com/assets/11394369/16350253/9587ca5c-3a12-11e6-8cf9-d02ddb8cba87.png)

**Comment by fffw** [comment]
We can fix it by either have:

1. Client to check specific error and show user-friendly messages.
2. Pro server to respond user-friendly error message directly.

I feel 2 better as we already handled locale on Pro server, and both desktop and mobile client can benefit from it.

In this case, it'd be good if pro server responds something like "xx@aaa.com is not associated with any authorized Pro user". Per the [Pro server code](https://github.com/getlantern/pro-server/blob/master/src/pro_server/web.clj#L118), it's the only reason such error is responded.

 @atavism @xiam @uaalto your idea?

**Comment by uaalto** [comment]
We can change that in the Pro server, of course. Does everyone agree is the best solution?

**Comment by myleshorton** [comment]
Well it sounds like there's an actual bug here and that the user link should be configured correct @sunshine19090?

**Comment by Derekf5** [comment]
CC: @chipstehr could you take a look at the copy on this screen? Basically this is the screen that users will see when they get pro via referral without paying. Users will see this screen when they click on account management. This will then allow them to verify their email to link devices.   Perhaps we should change the menu item to "Email Verification" or "Device Linking"  the copy on the screen could also be clearer i think.   LMK what you think.

**Comment by fffw** [comment]
A more natural way would be to show up a "Welcome To Lantern Pro" dialog with email verification actions whenever the UI detects a Pro user without email. It gives user an Aha moment instead of interrupting the expected flow (opening Accout Management dialog in this case). Worth a separate ticket.

**Comment by Derekf5** [comment]
I like it @fffw. To be clear about what we are talking about... when a user becomes Pro because their friend has used their code at checkout, we will pop up a welcome to pro screen letting them know this change has occurred, and at that point we will make them put in an email address to continue.   Will we need them to confirm that email address, or can they just give us their email like they would at checkout?

**Comment by fffw** [comment]
Yeah, that's the point @Derekf5. Pro server depends on the decision to choose the implementation.

Without verificating email address, the only question is how to handle the case if user has a typo in provided email address, then want to recover the Pro account at some point. Manually handling those cases is quite anonying, even if there are only a few of them.

**Comment by Derekf5** [comment]
OK so we should do a verified email here @fffw,  Is this part of the current sprint?  If so i can have design and specs over for this today.

**Comment by fffw** [comment]
@Derekf5 this ticket is. The UI change was not on plan but should be a plus I think.

**Comment by Derekf5** [comment]
cool, i will design it @fffw and if @myleshorton thinks it is important enough to get in this build cool, if not then we will push to next release.

**Comment by myleshorton** [comment]
Wait, let's back way up here in this ticket. The ticket is not for a type in when the user enters his or her email AFAICT. It's for when the user enters his or her _actual email address_. So we should just fix that bug.

**Comment by myleshorton** [comment]
To implement a notification that you are now pro would require websockets, pubsub, whatever. That's a huge change.

**Comment by myleshorton** [comment]
Is the above correct @sunshine19090? You're not talking about a typo but about an error when using the actual correct email address correct?

**Comment by fffw** [comment]
Update: We agreed to not show this dialog ATM.

**Comment by sunshine19090** [comment]
Yes @myleshorton , that's correct. I have now changed the description to make it clear.

**Comment by p3rcya** [comment]
@fffw @myleshorton Just for the record: The email user sent during stripe check out is not verified by Alipay. Users can enter a totally random email separated from Alipay. (@ffww please confirm )

So I think most of our emails won't be verified. But this is not a problem as long as we allow users to change email directly in the account management page.

**Comment by fffw** [comment]
Yes, it's true, for both card and Alipay. Email verification at some point would be the easiest to avoid the problem it can cause. Even with the ability to change email, Users may not be aware of a typo or intentionally ignore it until they want to link device or recover their account.

**Comment by p3rcya** [comment]
I think we should not bother user about verification until it's needed, aka
when they need to link devices

On Saturday, July 2, 2016, fffw <notifications@github.com> wrote:

> Yes, it's true, for both card and Alipay. Email verification at some point
> would be the easiest to avoid the problem it can cause. Even with the
> ability to change email, Users may not be aware of a typo or intentionally
> ignore it until they want to link device or recover their account.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4789#issuecomment-230128615>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqYZmbRzqsVtcmKCgtaGqCk3i2w-Uks5qRwIFgaJpZM4I-HWf>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by fffw** [comment]
What tricky is that if user's PC/Phone with Pro account is broken, they can't recover the account if the attached email address has typo.
