### ISSUE TITLE
Able to use my own referral code and get extra 6 months for a 2 year plan

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4792]
![image](https://cloud.githubusercontent.com/assets/11394369/16350520/f5593b72-3a13-11e6-9505-5d0d4087def4.png)

**Comment by p3rcya** [comment]
@myleshorton This definitely needs to be fixed before release

**Comment by myleshorton** [comment]
FYI @uaalto

**Comment by Derekf5** [comment]
Error should read, "Cannot use your own code for promotion"

**Comment by fffw** [comment]
It looks like a regression because we fixed it long time ago (https://github.com/getlantern/pro-server/issues/26)

**Comment by uaalto** [comment]
There was code handling the issue, but not properly typed. Fixed here: https://github.com/getlantern/pro-server/pull/184

**Comment by sunshine19090** [comment]
Tested in production. Working fine.
