### ISSUE TITLE
Safari - The data cap indicator design looks off

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4795]
<img width="1280" alt="screen shot 2016-06-24 at 2 44 57 pm" src="https://cloud.githubusercontent.com/assets/11394369/16351441/814c0334-3a1a-11e6-8912-74cdef624c9f.png">

**Comment by myleshorton** [comment]
What version of Safari are you using again @sunshine19090?

**Comment by sunshine19090** [comment]
Version 8.0 (10600.1.25) @myleshorton

**Comment by myleshorton** [comment]
OK cool thanks @sunshine19090. I would just upgrade to Safari 9x, as Safari 8 is about 0.25% of our users.

**Comment by sunshine19090** [comment]
Thanks for letting me know @myleshorton. i will upgrade mine.
