### ISSUE TITLE
After applying promotion for a one year plan, I get the message that there will be 2 pro months will be added for free

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4796]
Change the wording to one free month.

<img width="798" alt="screen shot 2016-06-24 at 3 17 17 pm" src="https://cloud.githubusercontent.com/assets/11394369/16352019/3af30b8a-3a1f-11e6-9e66-f67c37c905e1.png">

**Comment by myleshorton** [comment]
Not sure when this was fixed exactly, but will definitely be fixed in this next build.

**Comment by carsonefv** [comment]
@sunshine19090 @myleshorton I received the same message when i added the promotion for the 2 year plan, but the two year plan should actually give you **3 months free** instead of 2

**Comment by sunshine19090** [comment]
@myleshorton Changing the wording from "one extra months" to "one extra month".

![image](https://cloud.githubusercontent.com/assets/11394369/16393265/ec0d08fc-3c64-11e6-8264-1e68020440ec.png)

**Comment by myleshorton** [comment]
What version are you guys using @carsonefv and @sunshine19090? That message was in there at one point, but it hasn't been there for some time.

**Comment by myleshorton** [comment]
no on the "months" versus "month" but on the 3 versus 2.

**Comment by sunshine19090** [comment]
@myleshorton I downloaded the new build today (20160627.183518) and the number of months is fixed for the one year plan.

**Comment by carsonefv** [comment]
yep it's fixed for the two year plan as well
