### ISSUE TITLE
Windows code signing certificate no longer working

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4797]
Could be expired, something in the signing process, etc.

**Comment by fffw** [comment]
Are there any error message?

**Comment by fffw** [comment]
The windows installer I just built is with a cert expired on Jun 12th.

**Comment by myleshorton** [comment]
Thanks -- I'll renew it.

On Fri, Jun 24, 2016 at 11:43 PM, fffw <notifications@github.com> wrote:

> The windows installer I just built is with a cert expired on Jun 12th.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4797#issuecomment-228516304>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABF0nhWYcRR3KYInklMRBbteTjt40p3dks5qPM4BgaJpZM4I-NoF>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
All set.
