### ISSUE TITLE
Chrome on OSX ignoring system proxy settings

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4799]
Lots of discussion on slack.

**Comment by myleshorton** [comment]
Here's more detail on Chrome seeming to cancel system proxy settings. This is searching for "PROXY_" in chrome://net-internals/#events:

![image](https://cloud.githubusercontent.com/assets/1143966/16354781/b292b17c-3a56-11e6-879c-9893a1dbe2b6.png)

**Comment by myleshorton** [comment]
Here's at least some of the relevant chromium code:

https://src.chromium.org/svn/trunk/src/net/proxy/proxy_script_decider.cc

FYI @fffw and @oxtoacart

**Comment by myleshorton** [comment]
Oh more notes -- Safari works, and Chrome on Win10 works.

**Comment by oxtoacart** [comment]
I was having this same issue.  I upgraded to OS X `10.11.5` and now things are working again for me.

**Comment by myleshorton** [comment]
That's interesting @oxtoacart. I'll try the same. We've also been discussing just pushing the beta out anyway given that Mac is only 10% of our users.

**Comment by myleshorton** [comment]
Seems to be fixed in latest OSX version.

**Comment by oxtoacart** [comment]
@myleshorton Cool!  Do we have a way to communicate this info to our users?  Maybe check if they're running a combo of OS X + Chrome that's problematic and show a warning?  Or is that overkill?

**Comment by myleshorton** [comment]
TBH I think it's almost just as easy to just do precisely that but in an extension @oxtoacart - i.e. run an actual check to see if Lantern's proxying along the lines of your WIP extension.

**Comment by oxtoacart** [comment]
Agreed, this would be yet another good use for an extension.
