### ISSUE TITLE
Implement Stripe check out flow in the android app

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4804]
Currently, users have to leave the app to complete the check out. The entire check out process should be completed in the app itself to provide a smoother experience. 

Currently, the check out opens a amazon-S3 page then redirect to Stripe. Both service are disrupted in China and building into the app itself means users don't need to turn Lantern on to complete the check out.

**Comment by p3rcya** [comment]
@atavism Almost everything is opened in the in-app-browser itself. Any reason why the stripe check out is using an external browser?

**Comment by atavism** [comment]
Because Stripe Checkout doesn't work in a webview.

**Comment by atavism** [comment]
Turns out we can do this after all!

**Comment by atavism** [comment]
@myleshorton @p3rcya Need to do some more testing, but the latest build I uploaded (at the same link) has this implemented if you want to check it out.

**Comment by myleshorton** [comment]
This is the 3.0.0 link not qa right @atavism?

**Comment by atavism** [comment]
@myleshorton yes

**Comment by atavism** [comment]
@myleshorton Now that we're able to load the checkout page directly in a webview, I'm also going to move it off of S3. I'll load it directly from the local assets directory.

**Comment by p3rcya** [comment]
This is awesome. I'll test it out

Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by p3rcya** [comment]
@atavism During check out, if you didn't enter the email, then click Alipay, you will get this. (probably the notification that the email address is not entered. )
![image](https://cloud.githubusercontent.com/assets/7925929/16440150/02a55b86-3d74-11e6-9809-eae6611f7afa.png)

**Comment by p3rcya** [comment]
@atavism Sometimes the page loads forever.

**Comment by atavism** [comment]
Thanks for testing, @p3rcya. So the page sometimes doesn't load at all for you? Interesting you're seeing just a blank space in that error dialog. I see "Invalid Email" every time (attached). Could you send your log file? 

![image](https://cloud.githubusercontent.com/assets/6346213/16441110/71967126-3d7c-11e6-8f7c-4e17795be53c.png)

**Comment by atavism** [comment]
@myleshorton Could you let me know how it works for you?

**Comment by p3rcya** [comment]
@atavism Log sent.  I'm on Android 6.0.1

Now I'm stuck at this screen, so I cannot really see the email pop up anymore.
![image](https://cloud.githubusercontent.com/assets/7925929/16441246/b75776dc-3d7d-11e6-899d-5cdf3b1e6640.png)

**Comment by p3rcya** [comment]
@atavism @myleshorton Please close this issue only when properly tested on major Chinese devices including Mi, Huawei, etc. (If you want a specific list based on market share, please let me know)
