### ISSUE TITLE
Show purchase page in a way that cannot be blocked

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4807]
Since we cannot use Stripe in webview https://github.com/getlantern/lantern/issues/4804 , and S3 and stripe are partially blocked in China, we should trigger Lantern to be on for purchasing. Otherwise, some users won't be able to access the purchase page before manually turning Lantern on

**Comment by myleshorton** [comment]
This is what it does.

**Comment by p3rcya** [comment]
@myleshorton @atavism I don't think on android it's turned on automatically?

**Comment by myleshorton** [comment]
It's not turned on in the sense of full device VPN mode, but the purchase requests are proxied.

**Comment by p3rcya** [comment]
@myleshorton  On Android, it opens in Chrome or other 3rd party browser. How can only the purchase request be proxied?

**Comment by myleshorton** [comment]
Because @atavism wrote it that way =). Not sure what the actual call is, but I believe you can just configure the proxy for a WebView upon launch.

**Comment by p3rcya** [comment]
But it's not going through webview! @atavism said stripe doesn't support
webview and now it's opening in Chrome,etc

On Monday, June 27, 2016, Myles Horton <notifications@github.com> wrote:

> Because @atavism <https://github.com/atavism> wrote it that way =). Not
> sure what the actual call is, but I believe you can just configure the
> proxy for a WebView upon launch.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4807#issuecomment-228871391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqaRKBP_9oBeJD304rXmpFDRvehb5ks5qQDfpgaJpZM4I-nrJ>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment]
It's proxying through what it's opened in.

**Comment by p3rcya** [comment]
@myleshorton So Lantern set the proxy setting for Chrome automatically? So we have split tunneling already?

**Comment by myleshorton** [comment]
It's just for that browser session I believe

**Comment by p3rcya** [comment]
@atavism Can you confirm?

**Comment by myleshorton** [comment]
You want confirmation of how it's implemented? Why?

**Comment by p3rcya** [comment]
@myleshorton Not how it's implemented. Just that the 3rd party browser during check out is proxied even though the VPN is off

**Comment by myleshorton** [comment]
Yup it is - confirmed again.

**Comment by p3rcya** [comment]
Thanks! This seems magical. So just making sure

On Monday, June 27, 2016, Myles Horton <notifications@github.com> wrote:

> Yup it is - confirmed again.
> On Jun 27, 2016 5:40 PM, "Percy" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @myleshorton <https://github.com/myleshorton> Not how it's implemented.
> > Just that the 3rd party browser during check out is proxied even though
> the
> > VPN is off
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/getlantern/lantern/issues/4807#issuecomment-228917115>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABF0nrbzYFTVyRc2nuBlPpRWeEGpoC7qks5qQG1igaJpZM4I-nrJ
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4807#issuecomment-228917530>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqbH2H5P-xQuZgHnK0KkpjW5TMPkdks5qQG4sgaJpZM4I-nrJ>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment]
Ha! Turns out you're right @p3rcya sorry about that -- when we switched from webview the behavior I described went with it. @atavism is looking into ways to load that page on localhost.

**Comment by myleshorton** [comment]
I just gave this 3 story points @atavism but feel free to change.

**Comment by p3rcya** [comment]
@myleshorton Ha, I knew it! If it were to implement as described, then it would be a major vulnerability in the android system.

**Comment by myleshorton** [comment]
> @myleshorton Ha, I knew it! If it were to implement as described, then it would be a major vulnerability in the android system.

Well, not really. Android 6 lets you set proxy settings per app, so we could do exactly what I described, but that wouldn't work for earlier version.

**Comment by p3rcya** [comment]
@myleshorton Yeah, I was discussing this with other circumvention tool authors. We should use tunneling based on IP rather than per app, which is very difficult to implement before android 6. (During purchase, we can set Stripe/S3 IP to go through proxy). In the future, we should allow users to only proxy non-China (China can be other countries) IP

**Comment by atavism** [comment]
@p3rcya @myleshorton I finally found a way to load the checkout page in a webview! 

![image](https://cloud.githubusercontent.com/assets/6346213/16435582/fc7efce4-3d4b-11e6-8967-574681855577.png)

Based on http://stackoverflow.com/questions/37104583/stripe-checkout-does-not-work-on-webview

**Comment by atavism** [comment]
Closing this in favor of https://github.com/getlantern/lantern/issues/4804

**Comment by myleshorton** [comment]
Awesome @atavism!!!
