### ISSUE TITLE
Getting 50% of free data used notification when it is around 230 MB

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4809]

**Comment by myleshorton** [comment]
Does the UI update soon thereafter @sunshine19090?

**Comment by sunshine19090** [comment]
No @myleshorton , it is still in 233 MB. I think it was 230 MB at the time I got the notification and not 236 MB.

**Comment by sunshine19090** [comment]
Sorry @myleshorton, I misread the indicator. It was 236 MB remaining which means the user has used 264 MB. Somehow, it made me think that I have not crossed 250 MB yet when I saw 236 MB remaining. 

Closing this ticket.
