### ISSUE TITLE
[desktop] Unauthorized pro user still getting data cap notifications

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4810]
As an unauthorized pro user i am still getting data usage notifications.

**Comment by Derekf5** [comment]
@sunshine is this duplicate to another ticket? i looked but couldnt find.

**Comment by sunshine19090** [comment]
No @Derekf5, this is new.

**Comment by sunshine19090** [comment]
I have updated the labels and milestones.

**Comment by Derekf5** [comment]
Thanks @sunshine19090 !

**Comment by myleshorton** [comment]
This is likely because the user-data call does not respond that the user's status is active @uaalto

**Comment by uaalto** [comment]
So, to be clear about the bug, what happens is that the user is Pro, but has no authorized email, right?

And we want it to be active or not yet?

**Comment by uaalto** [comment]
https://github.com/getlantern/pro-server/issues/186

**Comment by myleshorton** [comment]
Oh right I hadn't thought about whether they've registered their email or
not but presumably not @uaalto. Not sure what status we want them to have -
whatever you think really. Could be reflective of that actual state if you
want.

**Comment by sunshine19090** [comment]
@myleshorton @Derekf5 This occurs for authorized users too but only when the lantern page is being loaded. So the pro user gets this everytime they quit and open lantern.

**Comment by myleshorton** [comment]
Are you talking about desktop notifications @sunshine19090 or in-browser notifications?

**Comment by sunshine19090** [comment]
desktop notifications @myleshorton

**Comment by myleshorton** [comment]
hmn...that's strange. OK thanks @sunshine19090

**Comment by sunshine19090** [comment]
I totally forgot about the in-browser notification @myleshorton. Does the in-browser notification appear after 50% of data is consumed? or only when 100% is used?

**Comment by myleshorton** [comment]
Only at 100%

**Comment by sunshine19090** [comment]
@myleshorton I just saw that the notification appears not only when lantern starts but also when the pro user is already running lantern and the free data is crossed the 50%, 80% or 100%.

**Comment by myleshorton** [comment]
Assigning this to you @uaalto since there at a minimum needs to be a server side fix for this. If it's a new state we can change that on the client as well.

**Comment by myleshorton** [comment]
Not as important as things like the pro users getting mixed up with free server caps though.

**Comment by myleshorton** [comment]
@fffw added a client-side fix for this (making sure to include device ID with the call to get our status).

**Comment by sunshine19090** [comment]
I am not seeing the notifications now for both authorized user and unauthorized users. Closing!
