### ISSUE TITLE
Add CI to lantern-pro repo

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4812]
The goal here is simply to achieve parity with the existing lantern repo's Travis CI.

**Comment by myleshorton** [comment]
Hey I'm looking at this one @oxtoacart and am considering adding wercker, but our custom go build keeps making life a little difficult. How would you feel about just jumping to go 1.7 beta2 for now and using their new IdleConnTimeout in Transport?

**Comment by oxtoacart** [comment]
@myleshorton Can you use the same technique we use for http-proxy-lantern to deal with wercker - https://github.com/getlantern/http-proxy-lantern/blob/master/wercker.yml#L31?

**Comment by myleshorton** [comment]
Good idea! I'll try it.

**Comment by fffw** [comment]
I assume it is not in progress and take it instead.
