### ISSUE TITLE
Mobile - Getting validation errors when trying to checkout pro

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4813]
Steps:

1. Apply promotion.
2. Cancel the checkout .
3. Go again and select a plan.
4. Enter the details in checkout screen and proceed to buy. 

Getting error as in the screenshot.
![screenshot_2016-06-27-13-00-46](https://cloud.githubusercontent.com/assets/11394369/16394247/0a6f2dee-3c69-11e6-8aa2-c0f0489d47ca.png)

**Comment by atavism** [comment]
We weren't setting the publishable key properly. Whenever we send out debug and/or release builds, the correct Stripe key should be chosen automatically now.
