### ISSUE TITLE
2.2.5 marked as virus by Kaspersky

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4820]
The 2.2.5 is marked by Kaspersky and possibly other anti-virus too. In the future, we should submit to those anti-virus and tested that they're not marked before officially releasing them. 
@myleshorton

**Comment by fffw** [comment]
Uploaded whitelist request per the method in https://github.com/getlantern/lantern-internal/issues/18. @sunshine19090 do you know how can we check if the request is processed?

**Comment by fffw** [comment]
Okay got feedback from Kaspersky which is sent to support@getlantern.org
