### ISSUE TITLE
traffic 0MB remaining for a first time user

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4822]
![image](https://cloud.githubusercontent.com/assets/7925929/16427826/14f2ea10-3d24-11e6-8427-a7ca35d5ac8a.png)

reported by a tester

**Comment by sunshine19090** [comment]
@p3rcya I see that now in desktop too with the new build.

**Comment by sunshine19090** [comment]
It is actually taking a little bit more time to show the data cap indicator after refreshing.

**Comment by p3rcya** [comment]
User still encounter this problem https://github.com/getlantern/forum/issues/300

**Comment by myleshorton** [comment]
Let's see if this is still an issue in 3.1.0.
