### ISSUE TITLE
Edge - When clicked on desktop notification, it takes the user to the error page "Hmm..we can't reach this page"

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4826]
![image](https://cloud.githubusercontent.com/assets/11394369/16433198/da365b9a-3d3d-11e6-8e29-c4e5d3e0cb82.png)

**Comment by fffw** [comment]
The notification embeds `uiaddr` which is incorrect when default browser is Edge. It can't get the private preferred UI address in `ui` package.

`main` package should the ideal place of both Edge detection and desktop notification (both are OS dependent), but preferred UI address depends on "manage system proxy" flag, so we can:

1. Move Edge detection to `app` package instead.

2. Make preferred UI address as a non-persistable settings entry, so `main` package can access it.

2 seems better but needs more refactor.

**Comment by myleshorton** [comment]
I think the localhost changes might have fixed this @fffw. Did they?

**Comment by joesis** [comment]
I think so but needs quick verification
