### ISSUE TITLE
Mobile - The snack bar for promotion confirmation doesn't stay long enough to read the text

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4831]
After applying promotion, I was looking at the checkout screen. By the time I tried to read the text in the snack bar displayed at the bottom, it was gone.

Either the snack bar should be on top where the user can notice or it should stay for longer period than it is now. 

cc; @Derekf5 @carsonefv

**Comment by Derekf5** [comment]
Hey @sunshine19090 approximately how many seconds does it persist?     I think we should keep it in its current location but it should persist longer if you didn't notice it.   IMO the "code copied" snack bar persists long enough (about 5 seconds) and the promotion applied snack bar should be the same.

**Comment by sunshine19090** [comment]
Yes @derek, it stays for 5 seconds. But the problem is, 2 seconds passed before I even noticed it because it is in the bottom and not getting my attention immediately. If no else has noticed, we could close this. Maybe, I am just too slow :)
