### ISSUE TITLE
Mobile - Under blocked condition and lantern off - lantern stops working in the last step of the checkout process

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4832]
I used DNS blocking and lantern is turned OFF. 

Proceed to buy pro. After applying promotion and submitting all the details in the checkout screen, I get "unfortunately, lantern has stopped". And then goes back to the main screen.

**Comment by sunshine19090** [comment]
Oh! I forgot to mention that I used test card number.

**Comment by atavism** [comment]
Send me your logs, please. @sunshine19090

**Comment by sunshine19090** [comment]
@atavism Sent. Let me know if you have received it.

**Comment by myleshorton** [comment]
Can you verify @sunshine19090?

**Comment by sunshine19090** [comment]
@atavism @myleshorton I am getting this error.  I tried this scenario with 3 scenarios,

1. Blocked condition and lantern off - Getting validation error.
2. Blocked condition and lantern on - Getting validation error.  must be related to #4830 
3.  No internet connection - Getting validation error. 

The best way is to not let the user get into the payment flow when there is no internet connection.

![screenshot_2016-07-13-14-50-21](https://cloud.githubusercontent.com/assets/11394369/16822686/169be3f8-4913-11e6-84f5-dd461fcd38e7.png)

**Comment by sunshine19090** [comment]
@atavism What I was trying to say here is, we should display a proper error message instead of the ioexception in the cases when there is no internet connection detected. Or we could avoid this situation by letting the user know that there is no internet connection before proceeding to the payment flow.

**Comment by atavism** [comment]
@sunshine19090, this sounds like it could be a problem with your setup because we aren't really seeing this in general. What are the "blocked conditions" you're using?

**Comment by atavism** [comment]
It sounds related to your problem of never seeing a prompt to enable a VPN connection w/ Lantern. What kind of device are you testing with again? I will see if I can replicate the problem on testdroid..

**Comment by sunshine19090** [comment]
@atavism Samsung SM-N900V. Android version 5.0.

**Comment by atavism** [comment]
Thanks, @sunshine19090! Just tested with a Note 3 running Android 5.0 on testdroid. The key sign appears when I turn Lantern on, and I made sure my requests are being proxied (verified my IP address). Tried watching a YouTube video, and that worked fine too. So I'm not sure what issue you're having--is it possible there's some other app interfering? It's strange you never see a prompt anymore. Do you by any chance have another device to test with? Oh, could you also send me an e-mail detailing the configuration you're using to simulate blocking?

**Comment by myleshorton** [comment]
I'm going to close this for now, but let's re-open if there are issues.
