### ISSUE TITLE
Email referral code on Android doesn't work

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4835]
Says no app available

![image](https://cloud.githubusercontent.com/assets/7925929/16434570/9518b35c-3d45-11e6-83c6-3bb8457be1e4.png)

He used cyanogenmod.

**Comment by myleshorton** [comment]
I'm not sure how worried we are about cyanogenmod, but have you seen more reports of this @p3rcya?

**Comment by p3rcya** [comment]
We shouldn't worry about it now
