### ISSUE TITLE
How to make socks listen on non-local, on all interfaces (0.0.0.0)?

### ISSUE THREAD

**Issue by 2xiangzi** [getlantern/lantern#4838]
I've known that one can make http listen on non-local, on all interfaces (0.0.0.0) by running:
`lantern --addr 0.0.0.0:8787`

And according to #2075 lantern has supported socks5:

> The SOCKS5 proxy listens at localhost:8788.

So is it possible to make socks listen on non-local, on all interfaces (0.0.0.0)?

Thank you!

**Comment by myleshorton** [comment]
We don't have that now, but it would be fairly easy to add, starting in flags.go.
