### ISSUE TITLE
Nothing is showing up on XP+IE8

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4839]
User reported. Just a blank page when opening Lantern.

**Comment by p3rcya** [comment]
We can just ask users to use Chrome,etc.

**Comment by fffw** [comment]
Lantern 2.x including 2.2.5 shows a notice in such case.

![image](https://cloud.githubusercontent.com/assets/10410437/16441300/e04b66a6-3dfb-11e6-9d70-2bd4ae1b6db9.png)

What's the version user reported? Upcoming 3.0.0 won't show anything in IE < 10 ATM.

**Comment by p3rcya** [comment]
This is 3.0. Why did we stop supporting them? We should have this notice on 3.0

**Comment by fffw** [comment]
It should. Didn't add yet.

**Comment by fffw** [comment]
1.

**Comment by fffw** [comment]
Fixed by https://github.com/getlantern/lantern-desktop-ui/pull/154
