### ISSUE TITLE
Please help me..

### ISSUE THREAD

**Issue by magnet1215** [getlantern/lantern#4840]
root@openmediavault:~# dpkg -i lantern-installer-beta-64-bit.deb
Selecting previously unselected package lantern.
(正在读取数据库 ... 系统当前共安装有 45370 个文件和目录。)
正在解压缩 lantern (从 lantern-installer-beta-64-bit.deb) ...
正在设置 lantern (2.2.5) ...
root@openmediavault:~# lantern --addr 0.0.0.0:8787
Running installation script...
/usr/lib/lantern/lantern-binary: 确定
Jun 29 05:43:03.309 - 0m0s DEBUG flashlight: flashlight.go:49 ****************************** Package Version: 2.2.5
Jun 29 05:43:03.310 - 0m0s DEBUG flashlight.util: hash.go:14 Hashing file at path /root/.lantern/bin/lantern
Jun 29 05:43:03.876 - 0m0s DEBUG flashlight.ui: ui.go:59 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
Jun 29 05:43:03.882 - 0m0s DEBUG flashlight: settings.go:57 Loading settings
Jun 29 05:43:03.883 - 0m0s DEBUG flashlight: settings.go:70 Could not read file open /root/.lantern/settings.yaml: no such file or directory
Jun 29 05:43:03.883 - 0m0s DEBUG flashlight.ui: service.go:134 Accepting websocket connections at: /data
Jun 29 05:43:03.883 - 0m0s DEBUG flashlight: settings.go:99 Sending Lantern settings to new client
Jun 29 05:43:03.885 - 0m0s DEBUG flashlight: settings.go:109 Reading settings messages!!
Jun 29 05:43:03.940 - 0m0s DEBUG flashlight: flashlight.go:49 ****************************** Package Version: 2.2.5
Jun 29 05:43:03.941 - 0m0s DEBUG flashlight.util: hash.go:14 Hashing file at path /root/.lantern/bin/lantern
Jun 29 05:43:04.272 - 0m0s DEBUG flashlight.ui: ui.go:59 Creating tarfs filesystem that prefers local resources at /lantern/src/github.com/getlantern/lantern-ui/app
Jun 29 05:43:04.278 - 0m0s DEBUG flashlight: settings.go:57 Loading settings
Jun 29 05:43:04.278 - 0m0s DEBUG flashlight: settings.go:70 Could not read file open /root/.lantern/settings.yaml: no such file or directory
Jun 29 05:43:04.278 - 0m0s DEBUG flashlight.ui: service.go:134 Accepting websocket connections at: /data
Jun 29 05:43:04.279 - 0m0s DEBUG flashlight: settings.go:99 Sending Lantern settings to new client
Jun 29 05:43:04.279 - 0m0s DEBUG flashlight: settings.go:109 Reading settings messages!!
**# error: XDG_RUNTIME_DIR not set in the environment.**

(lantern:2762): Gtk-WARNING **: cannot open display: 

-----------------------------------------------------------------------------------------------------------------------

**# error: XDG_RUNTIME_DIR not set in the environment.**

(lantern:2762): Gtk-WARNING **: cannot open display: 

how to fix it?

**Comment by fffw** [comment]
You can either run with `-headless` option or [build a headless version](https://github.com/getlantern/lantern/#building-lantern-for-running-on-a-server)

**Comment by magnet1215** [comment]
@fffw  Thanks
