### ISSUE TITLE
[Mobile] Data cap numbers not showing on mobile

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4844]
![screenshot_2016-06-29-11-27-06](https://cloud.githubusercontent.com/assets/7864729/16458488/355bd86a-3ded-11e6-9ec5-e2097f7fcab2.png)

**Comment by atavism** [comment]
I'm not seeing the data cap summary on desktop either...

**Comment by Derekf5** [comment]
Interesting @atavism i see the numbers on desktop, they just arent moving for me, is their maintenance being done on the backend that could be affecting this?

**Comment by atavism** [comment]
Should be showing up now.

**Comment by atavism** [comment]
Actually, I keep getting back either a) Response missing XBQ header, can't read bandwidth quota b) the amount of bandwidth allowed I get back is > 50000000 so it's still not appearing.

**Comment by atavism** [comment]
@myleshorton @Derekf5 I'm not seeing data usage on desktop either. This looks like a server-side issue, nothing specifically related to mobile.

**Comment by myleshorton** [comment]
Yeah I'm going to look at this today @atavism thanks.

**Comment by atavism** [comment]
Showing up for me now

**Comment by atavism** [comment]
Assigning to you, @sunshine19090, to confirm.
