### ISSUE TITLE
[Mobile] Lantern Crashes on checkout

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4845]
Cannot upgrade to Pro because every time I go thru the payment process I get the "unfortunately lantern has stopped" error, and then the app closes. 

Could be the same #4833 but the behavior after the error seems different.

After this happened i sent my logs

cc: @atavism @myleshorton

**Comment by atavism** [comment]
Issue here is related to the progress dialog being displayed after the activity is destroyed. Should be fixed in the new build.
