### ISSUE TITLE
The data cap indicator doesn't have the yellow bar to indicate that the free data has been used

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4847]
I got the notification that the free data is over but the UI is shows up the indicator but not in yellow. 

![image](https://cloud.githubusercontent.com/assets/11394369/16466178/ffb27d40-3df6-11e6-82a0-e10e581132e5.png)

**Comment by myleshorton** [comment]
Should be all set @sunshine19090 -- server side change

**Comment by sunshine19090** [comment]
Looks good.
