### ISSUE TITLE
Desktop: User can input existing Pro user's email to authorize account 

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4851]
Passes UI, with no effect at all. The email is still not attached to the user (expected).

It can be fixed in conjunction with https://github.com/getlantern/lantern/issues/4789. Log it as separate ticket just in case.

**Comment by myleshorton** [comment]
This basically allows anyone to become pro by guessing pro user email addresses right @fffw? Don't they still have to enter the verification code though?

**Comment by fffw** [comment]
It's just a UI issue. The user won't becoming Pro. It should already been fixed by using new pro-server endpoints. Just need confirmation.

**Comment by fffw** [comment]
It's fixed with the current account management dialog for unauthorized user.
