### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by danperor** [getlantern/lantern#4857]
version 2.2.5 can't download in china。
it always show conetion timeout,please help me,think u

**Comment by myleshorton** [comment]
Can you email us your logs @danperor?

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by p3rcya** [comment]
@dancannon Please use this link https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe

@myleshorton @fffw Please switch our main download link from S3 to Github. Users repeatedly confirm that github link is more stable. This is my experience as well

**Comment by fffw** [comment]
Agreed. We can switch when we put 3.0.x to the main site.
