### ISSUE TITLE
Google Inbox, Loading... All the time.

### ISSUE THREAD

**Issue by zzhhbyt1** [getlantern/lantern#4858]
https://inbox.google.com/
When using Lantern, I can access this site's main page, but any further operation will receive "Loading..." pop-up on the left lower corner and nothing will happen.

**Comment by myleshorton** [comment]
Interesting @zzhhbyt1 -- we'll take a look thanks.

You might also want to try the new version available here for windows: https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.1.exe

and here for mac:
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.1.dmg

**Comment by zzhhbyt1** [comment]
Thanks for your reply!
And I'm concerned about whether you have recurred this problem now?
I tried Microsoft Edge and Google Chrome but both of them can't solve this.

Anyway, thank you for maintenancing such an amazing app which helps lots of
people (especially those lazy guys) to see the world so conveniently!

**Comment by myleshorton** [comment]
It looks like inbox.google.com doesn't support Edge:

![image](https://cloud.githubusercontent.com/assets/1143966/16534945/6b81517a-3f98-11e6-9c67-e68b0fd45833.png)

**Comment by myleshorton** [comment]
Chrome is working fine on that page for me @zzhhbyt1 

Can you send us your logs? Instructions are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by zzhhbyt1** [comment]
Already sent the `lantern.log` to team@getlantern.org. Please check it out.

Now changing to Gmail will also receive a notification:

> Error
> 
> Some Gmail features have failed to load due to an Internet connectivity problem. If this problem persists, try reloading the page, or using the basic HTML version. Learn More.

And sorry for the inconvenience that I didn't give you the log in time because of the 2-day-visiting of my grandparents... LOL

**Comment by zzhhbyt1** [comment]
Oops, I tired the beta version you provided before, which can solve this problem.
But I wonder that whether you are going to make lantern not an unlimited data usage tool for those who don't get paid? I thought it's an software based on P2P and will stay unlimited forever... If that's true, that will be a little frustrating thing... I mean, I can pay for it, but some people in developing countries and areas might not pay and more unwilling to use tools to see the outside world...

**Comment by p3rcya** [comment]
We will always offer Lantern for free as well.
