### ISSUE TITLE
[Mobile] "invalid-currency" when purchase

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4861]
It can happen in following sequence:

1. Select a plan when the price is shown in USD

2. Pays in USD

3. Call /purchase, with a changed locale, say zh-CN

4. The purchase will fail with "invalid-currency".

The error doesn't happen if the user waits for the locale to be stablized before purchasing.

**Comment by atavism** [comment]
How are you changing the locale in step 3?

**Comment by fffw** [comment]
@atavism It's automatically changed. After launching App for ~10 seconds

**Comment by atavism** [comment]
No, the locale isn't automatically changed. That's probably just how long it takes to start Lantern and fetch the dynamic plan prices. Are you hardcoding the prices on desktop in addition?

**Comment by fffw** [comment]
Yeah, it sounds like the reason. Desktop always fetches /plans before showing the page.

**Comment by atavism** [comment]
So we're fetching those plan prices right after Lantern starts but after we fetch the newsfeed. Just re-ordering these calls should mitigate this for now.

**Comment by fffw** [comment]
That'll do it. The newsfeed can possibly take a long time to fetch.
