### ISSUE TITLE
3.0.2 cannot connect to server while 2.2.5 is fine 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4868]
![image](https://cloud.githubusercontent.com/assets/7925929/16539305/c740c148-3ff3-11e6-83c5-20604b920691.png)

https://github.com/getlantern/forum/files/344453/3.0.2lantern.log.txt
https://github.com/getlantern/forum/files/344454/2.2.5lantern.log.txt

User reported on https://github.com/getlantern/forum/issues/264

**Comment by myleshorton** [comment]
Does proxying still work for them when they see this screen @p3rcya?

**Comment by myleshorton** [comment]
Also, does this happen in specific browsers @p3rcya?

**Comment by Rice321** [comment]
@myleshorton It also happens to our user, but proxying was actually working while that users saw this message.

**Comment by p3rcya** [comment]
My user is using XP+QQ browser( with chrome kernal)

On Saturday, July 2, 2016, Rice321 <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> It also happens to our
> user, but proxying was actually working while that users saw this message.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4868#issuecomment-230123388>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqbuZRfvV7feR3Yzvy3I2nuAQg6Wgks5qRtt7gaJpZM4JDoSR>
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by p3rcya** [comment]
I tried it myself and it doesn't work on Windows 10 with Chrome.

On Saturday, July 2, 2016, Percy Alpha <percyalpha@gmail.com> wrote:

> My user is using XP+QQ browser( with chrome kernal)
>
> On Saturday, July 2, 2016, Rice321 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @myleshorton <https://github.com/myleshorton> It also happens to our
>> user, but proxying was actually working while that users saw this message.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/getlantern/lantern/issues/4868#issuecomment-230123388>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AHjwqbuZRfvV7feR3Yzvy3I2nuAQg6Wgks5qRtt7gaJpZM4JDoSR>
>> .
>>
>
>
> --
> Percy Alpha(PGP
> <https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)
>
>
>

-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by myleshorton** [comment]
When you say it doesn't work what do you mean @p3rcya? We've run it many many times on Windows 10 with Chrome, and I just ran it on Chrome on Win10 with no issues.

Those log files are interesting, though. @oxtoacart and @aranhoide this user is definitely getting the same obfs4 proxy, and 2.2.5 is able to connect to it while 3.0.2 at least doesn't show any successfull connections (it doesn't show any failed ones either).

Can you guys think of any reason 2.2.5 would work with an obfs4 proxy while 3.0.2 would not? The proxy is 128.199.166.112

**Comment by p3rcya** [comment]
@myleshorton  Oh, my image was not posted. Here is the image I tested in Store. My personal PC works fine. 

![image](https://cloud.githubusercontent.com/assets/7925929/16544011/4eff5bd4-40a9-11e6-9202-f4f83e38bad8.png)

**Comment by myleshorton** [comment]
This is not nearly as prevalent now right @p3rcya?

**Comment by p3rcya** [comment]
@myleshorton Yeah, I very few or none. Some are still experiencing the spinning issue though but far less
