### ISSUE TITLE
Mobile referral screen still in English 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4872]
![image](https://cloud.githubusercontent.com/assets/7925929/16539440/569c53c6-3ff8-11e6-8aab-3f1dfcb6be15.png)

It's translated on transfex. Please update.

**Comment by p3rcya** [comment]
@atavism still not translated in 3.0.5

**Comment by atavism** [comment]
Well, a couple things: a) this isn't the purchase screen b) this screen just changed with https://github.com/getlantern/lantern/issues/4893 which is why I didn't push the translations to Transifex yet

**Comment by atavism** [comment]
Ok, new strings were pushed to transifex. As soon as those are translated, I'll put out an updated 3.0.5 build.

**Comment by myleshorton** [comment]
Building 3.0.5 now, but if you're translating Percy just let me know, and
I'll wait.

On Wed, Jul 6, 2016 at 2:02 PM, atavism <notifications@github.com> wrote:

> Ok, new strings were pushed to transifex. As soon as those are translated,
> I'll put out an updated 3.0.5 build.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4872#issuecomment-230905477>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABF0ni7jtQYrw-TLvZgi0O1yrG7wNyhbks5qTBfNgaJpZM4JDokY>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by p3rcya** [comment]
@myleshorton Just updated the translation. But the desktop version still use "data" rather than "high speed data"

**Comment by myleshorton** [comment]
Yeah "high speed data" didn't fit on that line

On Wed, Jul 6, 2016 at 2:59 PM, Percy <notifications@github.com> wrote:

> @myleshorton <https://github.com/myleshorton> Just updated the
> translation. But the desktop version still use "data" rather than "high
> speed data"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4872#issuecomment-230920107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABF0nhwJdF4tcydwJJNVE_Vod8Kkg8k5ks5qTCU9gaJpZM4JDokY>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by p3rcya** [comment]
@chipstehr We can change the wording to make it fit the line
