### ISSUE TITLE
Mobile check out screen not translated 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4873]
![image](https://cloud.githubusercontent.com/assets/7925929/16539456/b783054a-3ff8-11e6-9d25-63b73b21fd42.png)

Lantern Pro Checkout 蓝灯专业版购买
Lantern Pro 蓝灯专业版

**Comment by atavism** [comment]
@p3rcya Do you mind translating that "Lantern Pro Checkout" string on Transifex?

**Comment by p3rcya** [comment]
@atavism I finished all translations for mobile

**Comment by atavism** [comment]
![image](https://cloud.githubusercontent.com/assets/6346213/16697236/9b3aabc2-44fd-11e6-84fe-71795f05aa17.png)

**Comment by p3rcya** [comment]
@atavism In 3.0.6, this is still in English. What's more, the plan page is showing up plan in USD as well

**Comment by atavism** [comment]
Not for me. Are you sure you downloaded the updated [3.0.6 (20160708.184135)](https://github.com/getlantern/lantern-binaries/blob/master/lantern-installer-3.0.6.apk?raw=true)?

**Comment by p3rcya** [comment]
@atavism Yes but now it's showing CNY again and confirmed by another user here https://github.com/getlantern/lantern/issues/4976 Please use that issue instead.
