### ISSUE TITLE
User reported that Pro is still limited to 20KB/s

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4881]
Getting more info from the user https://github.com/getlantern/forum/issues/272

**Comment by p3rcya** [comment]
Log https://github.com/getlantern/forum/issues/272#issuecomment-230134635
System is windows 10

**Comment by p3rcya** [comment]
Both Firefox and IE are limited to 20KB/s

**Comment by p3rcya** [comment]
Mac users reported that they are also limited https://github.com/getlantern/forum/issues/278

**Comment by fffw** [comment]
Should be solved by https://github.com/getlantern/http-proxy-lantern/pull/111, but let's wait for users' feedback.

**Comment by p3rcya** [comment]
User confirm solved
