### ISSUE TITLE
DON'T DOWNLOAD THE NEW LANTERN

### ISSUE THREAD

**Issue by zhouzhiwen2000** [getlantern/lantern#4887]
lantern is a p2p software,they can't charge us for our bandwidth,if we all stay in our version,it will still work.

**Comment by zhouzhiwen2000** [comment]
We all need to clone the lantern as soon as possible.We all know that you can't charge people for a open source software.

**Comment by fffw** [comment]
@zhouzhiwen2000 Please take a look at https://getlantern.org/faq/index.html to see how Lantern works. Lantern Pro uses dedicated server resources and additional services to keep it working. You can still use Lantern as is if you don't want to benefits brought by Pro. The existing infrastructure is still functioning.

**Comment by zhouzhiwen2000** [comment]
why there is a limit of bandwidth?i believe all p2p bandwidth should be free.

**Comment by fffw** [comment]
@zhouzhiwen2000 Lantern is not a P2P software. It's a circumvention tool. As we said on the home page, "Lantern is an Internet proxy tool that lets you access blocked sites."

**Comment by zhouzhiwen2000** [comment]
you see,bandwidth brougt by p2p is actually broght btrafficy users,you can't make money from user's bandwifth.And why there is a traffic limit?

**Comment by zhouzhiwen2000** [comment]
"It uses a variety of techniques to stay unblocked, including P2P and domain fronting."
it's on your github page.

**Comment by zhouzhiwen2000** [comment]
It's not a circumvention tool.It doesn't play any tricks on the GFW,it just simply avoids GFW

**Comment by zhouzhiwen2000** [comment]
Also,how can you sell a open sourse software?It can be edited by anyone to avoid paying.

**Comment by zhouzhiwen2000** [comment]
How does it work?

**Comment by zhouzhiwen2000** [comment]
I wonder if it is not a opensource software now.If not,how can i trust it then?

**Comment by fffw** [comment]
@zhouzhiwen2000 Thanks for discussing it seriously. I'll try explaining a few details from the technical perspective.

1. Currently, Lantern mainly relies on server resources to provide access. It's a huge cost. You can verify that by analyzing the traffic.

1. P2P and domain fronting, etc, are just a few of the techniques Lantern was / is using. The techniques are changing rapidly to deal with real world issues.

1. Lantern is still providing free access to the Internet for many people, and will continue to. Users can freely choose to upgrade for the additional benefits, provided with additional costs.

**Comment by zhouzhiwen2000** [comment]
OK,then you have the right to charge for the server you provide.I misunderstood.

**Comment by fffw** [comment]
@zhouzhiwen2000 Thanks for your understanding.

**Comment by zhouzhiwen2000** [comment]
Thank you for providing free service for such a long time.

**Comment by zhouzhiwen2000** [comment]
But i can't afford to buy the pro version.I think i'll continue to search for a new proxy tool.BYE.
