### ISSUE TITLE
Desktop UI: "Free Pro Credits" Refferal Pop-up screen is confusing, update text and buttons

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4892]
Currently, users are getting confused with the referral code and process, update the screen with the following text and button change for clarification cc @WolfLantern @chipstehr @p3rcya @Derekf5  

List of Changes:

~~1. Change top bar text to "Invite Friends"~~

2. Add header text above description that says "Share your code with friends to earn free months!"
Font: Roboto Regular; Font size: 20pt; Color: #000000l; Opacity: 87%;

3. Change Description text and make it smaller: "When your friend purchases the two year plan you will each get 3 months free, the one year plan gets you each 1 month free"
Font: Roboto Regular; Font size: 16pm; Color: #000000; Opacity: 87%;

~~4. Change the text above the code to say "SHARE YOUR REFERRAL CODE"~~

![screenshot 2016-07-03 14 34 22](https://cloud.githubusercontent.com/assets/4400763/16547007/42a8b8bc-412b-11e6-90ba-afd947771475.png)

**Comment by Derekf5** [comment]
#1 and #4 are knocked out @myleshorton we just need #2 and #3 now.

**Comment by Derekf5** [comment]
closing in lieu of #4997
