### ISSUE TITLE
Mobile UI: "Referral Promotion" code entering screen is confusing, update text and formattin

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4893]
This is another change to help with the confusion users are experiencing with the referral process. Please update the screen with the following text and format changes for clarification.
List of Changes
1. Change header to "Referral Code"
2. Change description text to “If a friend shared their referral code with you, enter the code to receive X months of lantern pro free after checkout
3.  Change APPLY PROMOTION  button text to APPLY REFERRAL CODE
4.  Change APPLY REFERRAL CODE button to our pink outline button (same as the pink outline button on other screens)
5. Change CONTINUE TO CHECKOUT button text to SKIP TO CHECKOUT
6. Change SKIP TO CHECKOUT to a proper button. (the type with solid pink background)
7. If a user attempts to use their own code the error pop up should return "Cannot use your own code for promotion" 
8. Delete background card

minor spacing changes in image
![referral-code](https://cloud.githubusercontent.com/assets/7864729/16547246/9ff8e27c-4134-11e6-92dd-3bd9cf1186b7.png)

CC: @WolfLantern @chipstehr @p3rcya

**Comment by chipstehr** [comment]
Guys what do you think about dropping bullet in this page. *super tiny edit*

**Comment by p3rcya** [comment]
I agree. Since we only have one point

**Comment by Derekf5** [comment]
SGTM

**Comment by chipstehr** [comment]
Arsome.

**Comment by atavism** [comment]
Should go out with the next build!
