### ISSUE TITLE
Desktop UI: Update "Code Copied" snackbar text on Pro Main Screen for referral clarity

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4895]
Currently users are getting confused with the Referral code and process, change the text when pressing the "Copy Code" button on the Pro Main Screen to say "Code copied. Share it with your friends!" 
(Similar to https://github.com/getlantern/lantern/issues/4894 but for Pro Main Screen instead of Referral Pop-Up"
cc @WolfLantern @chipstehr @p3rcya @Derekf5

**Comment by Derekf5** [comment]
This change has been committed
