### ISSUE TITLE
Desktop UI: "Copy Your Code" button on Referral Pop-up should not close the pop-up

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4896]
When pressing "Copy Your Code" on the Referral pop-up screen, do not close the pop-up screen automatically. This prevents users from seeing the instructions and copying the code again if needed.

cc @WolfLantern @chipstehr @p3rcya @Derekf5

**Comment by p3rcya** [comment]
@carsonefv  Good catch! I remember feeling abrupt the first time the window is closed automatically

**Comment by carsonefv** [comment]
@myleshorton can we get this into the next sprint?
