### ISSUE TITLE
Desktop UI: "Referral Promotion" code entering screen is confusing, update text and formatting

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4897]
This is another change to help with the confusion users are experiencing with the referral process. Please update the screen with the following text and format changes for clarification. cc @WolfLantern @chipstehr @p3rcya @Derekf5 

List of Changes
~~1. Change header to "Referral Code"~~
~~2. Change text above Code Field to say "Enter your friend's Referral Code"~~
~~3. Change description text to “If a friend shared their referral code with you, enter the code to receive X months of Lantern Pro for free after checkout~~
~~3. Change APPLY PROMOTION button text to APPLY REFERRAL CODE~~
~~4. Change APPLY REFERRAL CODE button to our light blue button (same as the light blue button on other screens)~~
~~5. Change CONTINUE TO CHECKOUT button text to SKIP TO CHECKOUT~~
6. Change SKIP TO CHECKOUT to a proper button. (Darker Blue)

minor spacing changes in image
![screenshot 2016-07-03 15 31 09](https://cloud.githubusercontent.com/assets/4400763/16547224/01f430a4-4134-11e6-8b84-672719ad074b.png)

**Comment by chipstehr** [comment]
Should referral code heading say something indicating friend's referral code so that they don't confuse it with the other referral code page that has your individual code on it?

Maybe Input Friend Referral Code?
That's a little uncommon. Thinking

**Comment by Derekf5** [comment]
Closing in lieu of #4998
