### ISSUE TITLE
Desktop UI: Add Welcome Pop-up Screen 

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#4899]
When a (new or existing) user opens the new version of Lantern this screen should pop-up 
@myleshorton can we pop this up 3 times for new users in non-consecutive sessions? so three times over week? @WolfLantern can answer questions about the reasoning for this.

This is the same size and similar format to our other pop-up screens:
**All Menu Pop-up Sheets:**
Width: 650px
Height: 500px
Elevation:  @include shadow(3);
Font Family: Roboto
Padding: (from top of site) Top: 168px; Left/Right: Centered;
border-radius: 2px;

• Illustration can be found here: https://www.dropbox.com/s/hvtcca46ieswttb/WelcomeScreenWall.svg?dl=0

• Header: "Welcome to the new and improved Lantern!" (line break after "and")
Font: Roboto Medium(500); Font Size: 30px; Color: #000000

• Description text - two paragraphs with line breaks:

"You are now using the fastest and
 most stable Lantern to date.

To get unlimited data, ultimate speeds and even
stronger blocking resistance **UPGRADE** to Pro!"

Font: Roboto Regular(400) (except "Upgrade" which should be font weight medium 500px); Font Size: 16px; Line-height: 19px; Color: #000000

• Button is same as other buttons but #FF4081 color with white text.

• Spacing and sizing noted below:
![screenshot 2016-07-03 17 30 54](https://cloud.githubusercontent.com/assets/4400763/16547687/f06d0bd4-4143-11e6-888e-0d043ae551fd.png)

**Comment by oxtoacart** [comment]
@carsonefv Do you want this to show up only when users upgrade from 2.x to 3.x, or any time that they upgrade (e.g. 3.0.6 -> 3.0.7)?

**Comment by carsonefv** [comment]
@oxtoacart this should show up for users who we can assume are seeing this version for the first time, this should include new downloads and users upgrading from 2.x-3.x

**Comment by oxtoacart** [comment]
Cool, thanks!  So if the user already had a 3.x version installed, I won't show the message.

**Comment by carsonefv** [comment]
@oxtoacart that sounds correct to me, but @WolfLantern might have another idea, any thoughts @WolfLantern ?

**Comment by carsonefv** [comment]
would be great to implement this now that we have auto-updates going

**Comment by myleshorton** [comment]
This is now consumed by some of the latest onboarding work.
