### ISSUE TITLE
lantern开始收费了？

### ISSUE THREAD

**Issue by Jerry-goodboy** [getlantern/lantern#4904]
为啥收费啊，不是免费的吗

**Comment by p3rcya** [comment]
对。收费版速度更快更稳定

**Comment by Jerry-goodboy** [comment]
为什么？原理在哪？这和收费的VPN代理有啥区别，没想到lantern也走到了这一步，失望


发自 网易邮箱大师
在2016年07月04日 11:17，Percy 写道:

对。收费版速度更快更稳定

**Comment by longerxue** [comment]
真不给力啊。。。。。。最后还是收费了。。。。。为何又变成套路了
