### ISSUE TITLE
Allow users to purchase Pro even if free servers are blocked 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4905]
Many users are stuck at the spinning screen https://github.com/getlantern/forum/issues/285#issuecomment-230196913, probably because the server access is blocked. 

We should allow users to purchase Pro in this situation. In fact, this is the very situation users need  and want to purchase Pro

**Comment by p3rcya** [comment]
@Derekf5 @myleshorton @WolfLantern Users should also be able to see the version number or to send logs when free servers are blocked. Basically, the spinning icon should not overlay the pro main screen. We should indicate the loading differently. Maybe a spinning icon in the main UI

**Comment by myleshorton** [comment]
Yeah agreed @p3rcya -- we should probably use both domain fronting and chained servers to access the pro server TBH and also to relay critical logs.

**Comment by p3rcya** [comment]
Agree. Domain fronting should definitely used in this situation

**Comment by p3rcya** [comment]
@myleshorton  This is rather important because some Pro users purchased on other devices and are unable to use it on the device with this problem 
@atavism Android should implement this too

**Comment by p3rcya** [comment]
@myleshorton Can check https://github.com/getlantern/forum/issues/291#issuecomment-230283899 It might also be caused by cert issues?

**Comment by fffw** [comment]
On domain fronting, [CloudFront can access origin site in https](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/SecureConnections.html), so we can theoretically setup DDF the same way as config-server. I'll play with it.

**Comment by sunshine19090** [comment]
@oxtoacart Any ways to simulate this issue?

**Comment by oxtoacart** [comment]
You can run lantern from the command-line with the `-readableconfig` and `-stickyconfig` flag.  Then you can temporarily change one character on the certificates for all of the proxy servers in order to break them.  You'll need to restart Lantern after this.
