### ISSUE TITLE
3.0.3 -addr can't launch~

### ISSUE THREAD

**Issue by magnet1215** [getlantern/lantern#4906]

**Comment by myleshorton** [comment]
Thanks @magnet1215 do you get any errors? What OS?

**Comment by magnet1215** [comment]
win10 64bit  
I added -addr 0.0.0.0:8787 in lantern's shortcut. Double clicked it and no response. Deleted -addr 0.0.0.0:8787, it works

**Comment by myleshorton** [comment]
OK thanks @magnet1215 we'll give it a look - should be a fairly simple fix. Would you mind also shooting us your logs and copying me directly at myles@getlantern.org? Instructions are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by magnet1215** [comment]
because lantern didn't execute,so log is empty. @myleshorton

**Comment by hendeliao** [comment]
@magnet1215  很可能问题出在0000上，你试试cmd -> ipconfig /all 看看你的地址，然后你就写路由给你的那个地址+端口试试，以前用yaml的时候我遇到过一次这个问题，现在加参数没有问题的。win8.1 64b

**Comment by myleshorton** [comment]
This should be fixed in the latest versions @magnet1215
