### ISSUE TITLE
Google 403

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4911]
This is not the usual CAPTCHA issue. 
firefox 45
Screenshot and logs are included in https://github.com/getlantern/forum/issues/297#issue-163633592

**Comment by p3rcya** [comment]
Also reported by https://github.com/getlantern/forum/issues/304#issue-163720387 
He is a pro user. We should at least make sure Pro users server IP are not blocked by Google. 
We can limit Pro users per IP,etc.

**Comment by fffw** [comment]
Don't know the exact reason but a few possible ways to mitigate:

1. sticky server for frequently accessed sites.

2. access origin site through ipv4 for ipv4 clients https://github.com/getlantern/http-proxy-lantern/issues/97

**Comment by fffw** [comment]
The direct solution should be the latter one. The URL (https://ipv6.google.com/...) is the same as https://github.com/getlantern/lantern/issues/4562. I guess it's caused by some Google internal issue.

**Comment by ClydeChenT** [comment]
How to solve the CAPTCHA issue?@p3rcya

**Comment by myleshorton** [comment]
Duplicates https://github.com/getlantern/http-proxy-lantern/issues/97
