### ISSUE TITLE
Pro user stuck at log in screen. 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4913]
![image](https://cloud.githubusercontent.com/assets/7925929/16571687/90328eb0-4215-11e6-9072-8a859e054503.png)

Getting log from the user https://github.com/getlantern/forum/issues/306

**Comment by p3rcya** [comment]
Log:https://github.com/getlantern/forum/issues/306#issuecomment-230373034
Win 7SP1 + Firefox
