### ISSUE TITLE
Tray icon language

### ISSUE THREAD

**Issue by ifchen0** [getlantern/lantern#4914]
Right click tray icon on ver 3.0.3 & 3.0.4 it will show simple Chinese on Traditional Chinese system.

**Comment by myleshorton** [comment]
What do you think @fffw and @p3rcya?

**Comment by p3rcya** [comment]
But we have the language setting in the main UI already. So I don't think it necessary

**Comment by orbancanon** [comment]
The tray menu text is inconsistent with current translation somehow. Need to figure out

**Comment by orbancanon** [comment]
Oh it's not true. Weird it's only traditional Chinese doesn't work.

**Comment by p3rcya** [comment]
Oh, I misunderstood the issue.  Yeah, it's confirmed

**Comment by fffw** [comment]
@orbancanon It's caused by the difference `getlantern/i18n` and `react-i18next` handling locales: '_' versus '-'. Hyphen should be more standard way, but both Transifex and `getlantern/i18n` uses underscore.

I should update `getlantern/i18n` to support both.

**Comment by myleshorton** [comment]
Is this all set?

**Comment by joesis** [comment]
No longer exists on 3.3.9
