### ISSUE TITLE
"Bad response code: 504" when fetching cloud config

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4915]
Seen on Loggly for version 2.2.5.

Full message:
```
ERROR yamlconf: yamlconf.go:228 Custom polling failed: Unable to fetch cloud config at http://config.getiantem.org/cloud.yaml.gz: Bad response code: 504
```
or
```
ERROR flashlight.util: http.go:175 Fronted request failed: Bad response code: 504
```

**Comment by myleshorton** [comment]
We're seeing some similar stuff @fffw -- 500 errors currently.

**Comment by fffw** [comment]
504 means Gateway timeout. It's probably the fronted counterpart of https://github.com/getlantern/lantern/issues/4916. We can wait for a couple of days and see if it recur on Loggly.

HTTP 500 error doesn't seem related. How can I reproduce @myleshorton ?

**Comment by myleshorton** [comment]
I think the 500 error is actually this one @fffw:

https://github.com/getlantern/config-server/issues/57

I'm trying to figure out what's happening now

**Comment by myleshorton** [comment]
I'm not seeing this in the logs anymore @fffw. I see occasional 503s, but for the most part things look good.
