### ISSUE TITLE
Dedicated Pro Servers 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4923]
We need to make it prominent that Pro users can use Pro servers exclusively, hence make it much harder to block. 
Users already asked this question whether Pro just remove the restriction on speed/data. 

@chipstehr @Derekf5 @WolfLantern

**Comment by eianslight** [comment]
This suggestion would  just turn the Lantern to another common  VPN provider.  The charge is reasonable for more data, maintenance and better development of this excellent project , however , it is stupid to  treat your users respectively in any standards of quality.  Lantern is so prominent , hope it can keep its unique quality while achieving its business goals.

**Comment by myleshorton** [comment]
Thanks @eianslight. Just to be clear, you're saying we should just be sure to make Lantern great regardless of whether it's the free or the paid version right? That is definitely our intention. We will continue to make many, many improvements to free and are very focused on it. 

Pro is interesting in that the payment itself can add an additional guard against blocking in terms of censors having to pay to learn about things to block.

Thanks so much for the feedback, and please feel free to respond here or to correct me if I misunderstood your point.

**Comment by eianslight** [comment]
@myleshorton You just said what I wanted to say . I totally agree with your intention , and seriously believe that your behaviors here make Lantern valuable and different from those purely commercialized VPN providers. 

Pro helps make this project stable and ensure its sustainable development , it is technically and economically blameless.

**Comment by p3rcya** [comment]
@myleshorton Please make sure Pro and free servers are totally separated.

**Comment by louy2** [comment]
This issue is centered on the assumption that Pro servers should not be accessible by Free clients so that they are not blocked. Depending on the method of anti-blocking this assumption may not be true. Are we mostly using obfuscation by secret here? Or something more resilient?

**Comment by zhouzhiwen2000** [comment]
I personally think lantern is turning into a common VPN provider.There are a great amount of VPN providers in China.Some of them provide even lower price with better services.
Sorry to destroy your dreams,but I've  already seen it turning from a p2p software to a software based on private servers.I think with the PRO version going on,it will turn from a open source software into a commercial proprietary closed software.There will be no difference between lantern and any other VPN provider.

**Comment by myleshorton** [comment]
@zhouzhiwen2000 with Lantern we essentially do whatever we feel is most effective for users to create a resilient platform for staying unblocked. That will likely again include p2p elements in the near future, and it's also part of the reason we're adding a paid version (with the other part being making us able to continue building Lantern and making it as great as we possibly can make it).

What would you like to see in Lantern @zhouzhiwen2000? More of a focus on the overall vision of building a platform that can stay unblocked no matter what? That's certainly still our primary overall focus, but I'm curious about what direction you would prefer.

**Comment by p3rcya** [comment]
This issue is to discuss the outreach wording.

**Comment by myleshorton** [comment]
Hmnn...maybe a new repository then @p3rcya?

**Comment by eianslight** [comment]
@myleshorton  can't understand why this guy continuously pushes Lantern to become an other existed commercial VPN  provider. 

A commercial VPN deal is more suitable for you @p3rcya , and it's much easier for you to achieve your intention.

**Comment by myleshorton** [comment]
Hmnn...yeah we're not trying to be a commercial VPN @p3rcya, so we should definitely try to coordinate on making sure that's clear.
