### ISSUE TITLE
is lantern free version only 800Mbyte can use per month

### ISSUE THREAD

**Issue by FgoDt** [getlantern/lantern#4926]
I download the new version,find the ‘china-version’ only 800MByte can use per month ,if want more only buy the pro version（30$ 1 year or 50$ 2 year).
as i know lantern is always free,so i want know this 'china-version' is official version

**Comment by myleshorton** [comment]
Thanks @FgoDt yes as you've undoubtedly seen there are a lot of Lantern clones out there, and in this new version we are actually adding an 800MB cap on monthly data. That is the official version, and thanks for checking.
