### ISSUE TITLE
Bad input or missing argument for payment

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4933]
https://github.com/getlantern/forum/issues/353
After Alipay presents the green check check mark, Lantern reports 
![image](https://cloud.githubusercontent.com/assets/7925929/16642402/7b4fdcfe-43bf-11e6-85f1-8e139967b848.png)

The payment doesn't show up in Alipay either.
The missing payment was reported by many users.

**Comment by fffw** [comment]
It's rather critical

**Comment by p3rcya** [comment]
Log https://github.com/getlantern/forum/issues/353#issuecomment-230987164

**Comment by p3rcya** [comment]
@fffw I think this is the same issue users reported on Android as well.

**Comment by p3rcya** [comment]
The user said he retried with VPN and somehow did it

**Comment by fffw** [comment]
Change back to P1 as user reported that purchasing worked again, and I could also purchase.

May relates to the temporary Redis issue, though I have no idea how.

**Comment by p3rcya** [comment]
@fffw Many android users earlier reported this issue too. But many of them can purchase as well obviously.

**Comment by p3rcya** [comment]
More users complained they cannot complete the payment process https://github.com/getlantern/forum/issues/357#issuecomment-231245257

**Comment by p3rcya** [comment]
cc @uaalto  @myleshorton

**Comment by 1987phoenix** [comment]
I cannot sign in lantern for 3.0.4 edition ,would you tell me how to solve this question@p3rcya

**Comment by p3rcya** [comment]
@1987phoenix We've resolved this issue in 3.0.5. We will release it tomorrow

**Comment by uaalto** [comment]
This happens only if the server doesn't receive all the required parameters or in the correct format. There is an issue opened already to improve the message so it say exactly which ones is wrong, but it is considered a low-priority task. We could perhaps bump its priority so the server helps troubleshoot these issues.

**Comment by p3rcya** [comment]
@uaalto Many many users are complaining that they cannot pay after completing the payment process. This should receive very high priority! 

More reports here https://github.com/getlantern/forum/issues/430#issue-164642156

**Comment by p3rcya** [comment]
More user report https://github.com/getlantern/forum/issues/441
@uaalto @myleshorton This should be fixed as P0 as it prevents users who actually paid from paying

**Comment by myleshorton** [comment]
Just moved this to the top of the backlog - thanks @p3rcya

**Comment by myleshorton** [comment]
I would say with things that are in the "New Issues" pipeline @uaalto, especially ones that are new in "New Issues", that it's completely possible I just haven't had a chance to prioritize it yet. Just feel free to grab me on slack if you think that might be the case for ones like this, as it's just hard for me to catch all these via email.

**Comment by fffw** [comment]
Same error message appears when user links Pro account on PC https://github.com/getlantern/forum/issues/444#issuecomment-231519421 .
I finally reproduced it.

**Comment by fffw** [comment]
It definitely can be caused by DDF not forwarding Lantern specific headers! We should configure the distributions programatically.

**Comment by fffw** [comment]
The configuration did forwarded all headers with wildcard char. I just updated it to forward the same set of headers of config-server.

**Comment by uaalto** [comment]
I'm continuing comments in the related epic: https://github.com/getlantern/pro-server/issues/214
