### ISSUE TITLE
One additional month for Pro beta users

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4935]
To thank them for the feedbacks and go through bugs, we will give all users who purchase Lantern before the release an additional month.  No UI needed. I just need to announce in the forum. 
@WolfLantern @myleshorton

**Comment by aranhoide** [comment]
Another good news that may be good to throw in there to make things brighter is that we've just given everyone Linode Tokyo proxies.  That was in the plans from the beginning, but we had some trouble getting enough proxies.

We should be good for a while, but availability can't be guaranteed indefinitely.  Maybe that can be spinned as a reason to join Pro **now**?  :P

**Comment by p3rcya** [comment]
As specified by https://github.com/getlantern/forum/issues/426, the cut off time will be till when the Pro website is live. All users before then should receive this one month bonus in the database.

**Comment by uaalto** [comment]
Just to clarify: only users that paid, right? Or everybody? Note that we've already had 100k unique free users.

**Comment by myleshorton** [comment]
Yeah, really good question @uaalto. I think to start just paid users makes sense yes. Doing it for free is an interesting idea, but we can hold off on that for now.

Definitely in terms of giving everyone a free month, that's just pro. In the future we might want to be able to give anyone a free month of pro, including free, but the free part can wait for now.

**Comment by p3rcya** [comment]
@uaalto Just PAID! Notice this doesn't mean all Pro users, only PAID pro users. Pro users that got it from referral shouldn't be extended.

**Comment by uaalto** [comment]
Did my question just disappear from here or it was in a different place. Doesn't matter, the responses are more important :)
So this brings up something relevant: currently we don't have an "official" way to distinguish Pro users that got it from purchasing or by a referral. Of course there are a few indirect ways, but they will fail as soon as first paid users start to expire (in a year). To avoid that, we can use a solution similar to this: https://github.com/getlantern/pro-server/pull/190

But to the point at hand, I can handle this. We can run this as a two-step migration: make a list of beta pro users with an offline or secondary database, and then directly apply the increase in the production database, to alleviate it from a migration running over each single user (so many!).

What's the priority of this? Should we wait until the official release?

**Comment by p3rcya** [comment]
Yes, we can do this after the official release. That would be our cut off time for bonus month as well. 

(I slacked you about the question)

**Comment by uaalto** [comment]
Ok! I can then do a script and leave it ready with enough time for proper reviewing. We can dry-run it prior to a production migration anytime.

**Comment by uaalto** [comment]
This is ready in a closely related PR (uses the same internal code): https://github.com/getlantern/pro-server/pull/227

One remaining question: the script will give a month to all paying users, not to those that became Pro as a result of code redeeming. Is that what you had in mind or you think is more convenient to give this month to all Pro users regardless of supporting Lantern?

**Comment by uaalto** [comment]
I'm asking this in relation to this ticket: https://github.com/getlantern/lantern/issues/4980

**Comment by p3rcya** [comment]
@uaalto If it's easy to implement either way, we should only give one month extra to paying users. You shouldn't however run it now because we're still in beta and the cut off time is when we launch the official version

**Comment by uaalto** [comment]
It's implemented to give one month extra only to paying users already. It's not ran yet, but ready to do so when necessary.

**Comment by uaalto** [comment]
So, it's still under review, that's what I mean.

**Comment by oxtoacart** [comment]
Are we still waiting before doing this?

**Comment by p3rcya** [comment]
Yep. after this https://github.com/getlantern/lantern-internal/issues/207

**Comment by p3rcya** [comment]
The cut off time for the bonus month should be Sept 23, 2016 where 3.2 was released

**Comment by myleshorton** [comment]
@uaalto is going to look for the script for it.

**Comment by uaalto** [comment]
Create also a list of users that got a free month.

**Comment by uaalto** [comment]
The code is outdated, so I'll fix it and run it today.

**Comment by uaalto** [comment]
Re-implemented here https://github.com/getlantern/pro-server/pull/373
Ready to run

**Comment by myleshorton** [comment]
closing in favor or getlantern/pro-server#373
