### ISSUE TITLE
Still unable to dial tcp://www.google.com.hk:80 after 3 attempts

### ISSUE THREAD

**Issue by werther0331** [getlantern/lantern#4940]
Jul 08 01:20:26.984 - 1068m23s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 2...continuing
Jul 08 01:20:26.984 - 1068m23s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 2...continuing

Jul 08 01:20:26.984 - 1068m23s ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial connect://clients1.google.com:443 after 3 attempts
Jul 08 01:20:26.984 - 1068m23s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial connect://clients1.google.com:443 after 3 attempts

Jul 08 01:20:26.984 - 1068m23s DEBUG flashlight.client: handler.go:121 Could not dial Still unable to dial connect://clients1.google.com:443 after 3 attempts
Jul 08 01:20:26.984 - 1068m23s DEBUG flashlight.client: handler.go:174 Responding 502 to //clients1.google.com:443
Jul 08 01:20:27.057 - 1068m23s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 0...continuing
Jul 08 01:20:27.057 - 1068m23s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 0...continuing

Jul 08 01:20:27.057 - 1068m23s DEBUG balancer: balancer.go:89 Dialing connect://clients1.google.com:443 with (trusted) chained proxy at 139.59.250.39:443 []
Jul 08 01:20:45.867 - 1068m42s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to tcp://config.getiantem.org:80: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 2...continuing
Jul 08 01:20:45.867 - 1068m42s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to tcp://config.getiantem.org:80: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 2...continuing

Jul 08 01:20:45.867 - 1068m42s ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial tcp://config.getiantem.org:80 after 3 attempts
Jul 08 01:20:45.867 - 1068m42s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR detour: detour.go:146 Dial detoured failed: Still unable to dial tcp://config.getiantem.org:80 after 3 attempts

Jul 08 01:20:45.867 - 1068m42s ERROR flashlight.util: http.go:185 Chained request failed Bad response code: 503
Jul 08 01:20:45.867 - 1068m42s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR flashlight.util: http.go:185 Chained request failed Bad response code: 503

Jul 08 01:20:45.867 - 1068m42s DEBUG flashlight.util: http.go:219 Ignoring error on second response
Jul 08 01:20:47.175 - 1068m43s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 1...continuing
Jul 08 01:20:47.175 - 1068m43s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 1...continuing

Jul 08 01:20:47.175 - 1068m43s DEBUG balancer: balancer.go:89 Dialing connect://clients1.google.com:443 with (trusted) chained proxy at 139.59.250.39:443 []
Jul 08 01:20:47.238 - 1068m43s DEBUG balancer: balancer.go:89 Dialing connect://clients1.google.com:443 with (trusted) chained proxy at 139.59.250.39:443 []
Jul 08 01:20:49.484 - 1068m45s DEBUG balancer: balancer.go:89 Dialing connect://safebrowsing.google.com:443 with (trusted) chained proxy at 139.59.250.39:443 []
Jul 08 01:20:57.057 - 1068m53s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 1...continuing
Jul 08 01:20:57.057 - 1068m53s DEBUG flashlight.logging: logging.go:234 Not logging duplicate: ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 139.59.250.39:443 [] to connect://clients1.google.com:443: Unable to dial server (trusted) chained proxy at 139.59.250.39:443 []: dial tcp 139.59.250.39:443: i/o timeout on pass 1...continuing

**Comment by fffw** [comment]
It just means a blocked server. The server is retired. Closing.
