### ISSUE TITLE
蓝灯收费了

### ISSUE THREAD

**Issue by lipangit** [getlantern/lantern#4941]
开发团队貌似失去了信念，迷失了方向，新版竟然收费了，还依然不能正常使用。群众表示非常伤心非常悲痛非常惋惜，所以我决定卸载Lantern并取消本项目的star，啥时候好用了我还会回来的。

此致
Nathen

**Comment by dianerdianer** [comment]
旧版本也不能使用了？

**Comment by kingwrcy** [comment]
下了新版本也不能用了,旧版本也挂了?

**Comment by huweikkk** [comment]
已经不能使用两三天了 什么情况！！

**Comment by jxmlhdf** [comment]
#4942

**Comment by Ben07** [comment]
这就尴尬了。没法翻墙，写代码都没激情了

**Comment by AlbertKnag** [comment]
一直loading   取消star从我做起

**Comment by p3rcya** [comment]
请看精华帖 https://github.com/getlantern/forum/issues/362

**Comment by TheLostXianXian** [comment]
收费无所谓啊，但是至少能让我连上去付个费啊。装了3.0.4连首页都看不到了。求解决方法。

**Comment by p3rcya** [comment]
3.0.5解决了这个问题。现在还在内测，明天发布

**Comment by Ben07** [comment]
@p3rcya 可以增加季度收费的选项吗？我上一个翻墙的软件付费之后被gfw搞了之后，就没然后了

**Comment by p3rcya** [comment]
@Ben07 现在暂时没有。但是你可以通过邀请你朋友购买，来免费获得3个月专业版

**Comment by XieXianbin** [comment]
开始垃圾了

**Comment by lcdtyph** [comment]
收费才是正常的吧，楼上几个取消star的刷什么存在感？免费的时候不知道感恩，收费了就开始嘲讽？

**Comment by samuel072** [comment]
now, i'm very sad. what happened?

**Comment by zhsngq** [comment]
3.0.7，我是可以正常使用登录google的，感觉快了许多！

**Comment by colalan** [comment]
不管是因为什么样的原因，收费都是极为愚蠢的作法，你可以搞捐助，但不应收费。别以为有了用户数量就可以为所欲为了。

**Comment by huiyu998** [comment]
输入我的邀请码 Y745HS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
