### ISSUE TITLE
No logs appearing from flashlight/main logger

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4946]
I'm also not seeing any logs appear from the logger in flashlight/logger. It seems like maybe something's not quite wired up correctly yet right at startup.

FYI @oxtoacart and @fffw.

**Comment by myleshorton** [comment]
Oh, I completely forgot to mention I can only get this to happen with installed versions, but I have no idea why. Could possibly be related to panicwrap or something.

**Comment by myleshorton** [comment]
One theory: the reason it only seems to happen with installed versions is that in development we often redirect standard out and err, as in `&>`

**Comment by oxtoacart** [comment]
I don't redirect anything during dev, and on OS X 10.12.2 I am seeing log output in ~/Library/Logs/Lantern/lantern.log

**Comment by myleshorton** [comment]
I just verified it does appear to be specific to production. To to be clear this is effectively just a bug with early logs not appearing. So, for example, when I run 3.5.12 I don't get any logs from `flashlight.ui` at all.

**Comment by myleshorton** [comment]
@oxtoacart do you get logs with things like this from production builds:

```
****************************** Package Version
```

**Comment by oxtoacart** [comment]
@myleshorton No, I don't see that in my logs from production builds. I also don't see it in ~/Library/Logs/Lantern/lantern.log even when running from a development build. I do see it on stdout, but that's it.

The reason for this is that this particular log statement is inside the `init()` function in flashlight.go. It looks like flashlight's `init()` is running before flashlight.logging's `init()`. I think I can fix that.
