### ISSUE TITLE
Cache global config in CloudFlare and CloudFront for 24 hours

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4947]
This will allow us to protect our servers and redis from the vast majority of traffic and to even poll more frequently.

**Comment by myleshorton** [comment]
We could also do something similar with CloudFront.

**Comment by myleshorton** [comment]
Might involve client side changes for the etag.

**Comment by myleshorton** [comment]
Make it easy to turn off completely to go back to our current setup

**Comment by myleshorton** [comment]
This is where the action is on retiring:

https://github.com/getlantern/lantern_aws/blob/master/salt/cloudmaster/retire.py

**Comment by aranhoide** [comment]
We probably want to invalidate configs on offloading too.

**Comment by myleshorton** [comment]
This is the page on CloudFlare just for reference:

https://www.cloudflare.com/docs/next/#zone-purge-individual-files-by-url-and-cache-tags

**Comment by myleshorton** [comment]
The comments here are also useful:

https://github.com/getlantern/config-server/issues/32
