### ISSUE TITLE
bad input or missing arguments

### ISSUE THREAD

**Issue by hitzhangjie** [getlantern/lantern#4950]
I purchased Pro version and I registered with my email "username@gmail.com" in which ${username} contains a dot ".". When I register with this email address, lantern UI doesn't prompt anything about invalid ${email}, but when I login with the same email, it always prompt "bad input or missing arguments"!
Sometimes, it doesn't prompt and I receive the verification code, but after I input this verification code, it prompt "bad input or missing arguments", too.
And it is too slowly to login Pro version with registered account!

**Comment by p3rcya** [comment]
@hitzhangjie 3.0.7 fixed this issue. Please download here https://github.com/getlantern/forum/issues/611
