### ISSUE TITLE
Virus detected after installation

### ISSUE THREAD

**Issue by ivanhjc** [getlantern/lantern#4951]
My antivirus reported a severe virus named "Trojan:Win32/Rundas!plock" after installing the latest version (3.0.4). Is it safe to keep it?

**Comment by hitzhangjie** [comment]
You can the anti-virus software temporarily and installed the lantern, then exclude the installed lantern path from anti-software.
After this, start the anti-virus again.
I don't know why virus diagnose lantern as unsafe software, but you can do this to keep it.

**Comment by ivanhjc** [comment]
So there's no virus?

**Comment by p3rcya** [comment]
There is no virus as long as you download from our official sources. https://getlantern.org
