### ISSUE TITLE
 The service seems down :-(

### ISSUE THREAD

**Issue by rootchina** [getlantern/lantern#4953]
I found that I couldn't access the blocked websites by GFW. My latern version installed is 2.2.3. Meanwhile I can NOT study the training videos on YouTube. That's a big pity ! Any suggestion guys ? Could you please give me a hand ? Thanks in advance.

**Comment by Insofan** [comment]
东北能用，有土鳖很流畅
BTW: Do you know how to use lantern for mac terminal?

**Comment by windsome** [comment]
@rootchina  same problem. fuck  GFW times by times.

**Comment by PegasusWang** [comment]
also doesn't work, dont know why.

**Comment by chucklu** [comment]
2.2.5 and 3.0.4 can not work

**Comment by myleshorton** [comment]
We are working on several fixes now @chucklu, @PegasusWang, @windsome, @Insofan, and @rootchina.

The links at https://github.com/getlantern/lantern are now updated to 3.0.6 as well, so you could try that version.

**Comment by chucklu** [comment]
finally,I got this info
"Sorry, we're having trouble contacting the Lantern servers. Please check your internet connection and try again."
@myleshorton  thank you

**Comment by myleshorton** [comment]
OK thanks @chucklu. Actually can you send me your logs? Instructions are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs 

and you can send them directly to me -- myles@getlantern.org. Just include in the subject "@chuklu from GitHub!" or something so I know it's you.

**Comment by rootchina** [comment]
@myleshorton Thank you. It works now.

**Comment by myleshorton** [comment]
Great @rootchina! Please let me know if you guys have issues.

**Comment by chucklu** [comment]
@myleshorton  sorry,forgot to tell you that the lantern works again
maybe you can close this issue

**Comment by myleshorton** [comment]
Awesome @chucklu! Please feel free to open a new issue if you have any problems.

**Comment by nelsonruwa** [comment]
Sorry, we're having trouble contacting the Lantern servers. Please check your internet connection and try again.

I just purchased Lantern Pro 2-year license yesterday. Today in the morning it shows me this message. I am stranded.
