### ISSUE TITLE
Bad input or missing arguments when logging in to Pro

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4955]
https://github.com/getlantern/forum/issues/409 purchased pro and wanted to log in to another computer. He encountered this error

**Comment by p3rcya** [comment]
This user complained the same thing https://github.com/getlantern/lantern/issues/4950

**Comment by myleshorton** [comment]
This sounds like the same thing I was seeing with the user-data call @uaalto and @atavism

**Comment by myleshorton** [comment]
I'm on my phone so can't change the pipeline @uaalto but this seems very important

**Comment by p3rcya** [comment]
![image](https://cloud.githubusercontent.com/assets/7925929/16706641/ccda1dbe-4568-11e6-9a02-f866e360a945.png) with log https://github.com/getlantern/forum/issues/444#issuecomment-231519421

**Comment by p3rcya** [comment]
More user complaint screenshot + log https://github.com/getlantern/forum/issues/485#issuecomment-231591683

**Comment by p3rcya** [comment]
More complaints with log https://github.com/getlantern/forum/issues/498#issue-164749518

**Comment by p3rcya** [comment]
This user cannot pay with credit card either https://github.com/getlantern/forum/issues/358#issuecomment-231641734

**Comment by uaalto** [comment]
I'm continuing comments in the related epic: https://github.com/getlantern/pro-server/issues/214

**Comment by fffw** [comment]
pro-server just added detailed error message. The test result on XP is quite interesting: `Bad input: request missing Email`, though the email is present in the request. Investigating.

**Comment by uaalto** [comment]
I suspect all these errors about missing arguments come from the same underlaying issue.

**Comment by fffw** [comment]
Yeah I have that feeling too. The error message of failed Purchase is "Bad input: request missing Stripe Token". They share something in common: the first parameter being checked which is passed as form parameter instead of HTTP header. See https://github.com/getlantern/pro-server/blob/master/src/pro_server/web.clj#L126 and https://github.com/getlantern/pro-server/blob/master/src/pro_server/web.clj#L334 respectively. @uaalto Did we log the form parameters?

**Comment by fffw** [comment]
Never mind @uaalto . I can experiment with `curl`

**Comment by fffw** [comment]
So it's still something with CloudFront, as same `curl` command succeeded on Mac but failed on XP. The only difference is https access to pro-server always fail because of getlantern/lantern-pro#59. Seen from pro-server logs, all failed requests during my test on XP are via CloudFront.

**Comment by fffw** [comment]
I've been unable to reproduce for 12 hours but now I can reproduce it again on XP. It's really hard to tell what's going on but hopefully I can dump the request via a test server.

**Comment by fffw** [comment]
Created test distribution (ID E3SYQGGW1WK57Q)

**Comment by p3rcya** [comment]
https://github.com/getlantern/lantern/issues/5003 might be caused by this ticket, please take a look

**Comment by fffw** [comment]
So the root cause is that `ParallelPreferChained` doesn't copy the body when making requests through fronted. What we should do:

1. Change `ParallelPreferChained` to fail soundly if the request is potentially non-idempotent.
2. In `pro/proxy.go`, use `ParallelPreferChained` only for GET requests, and `ChainedThenFronted` for the rest.

**Comment by fffw** [comment]
There's another error when requesting through fronting. Need to fix too.
```
Jul 13 17:56:25.855 - 1m13s DEBUG flashlight.proxied: proxied.go:327 Result of fronting: http: invalid Read on closed Body [fronted_url=http://xxx.cloudfront.net/user-create http_method=POST http_proto=HTTP/1.1 op=dualfetcher origin=api.getiantem.org proxy_type=fronted root_op=chainedandfronted]
```

**Comment by myleshorton** [comment]
So @fffw in theory we should be able to reproduce it every time through only using fronted, is that right?

**Comment by p3rcya** [comment]
Another user reported it just now on windows https://github.com/getlantern/forum/issues/728#issue-166477299 I'm verifying whether he is using 3.0.7 and getting log
