### ISSUE TITLE
Devices authorized list is blank after verifying the email address of unauthorized pro user

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#4957]
![image](https://cloud.githubusercontent.com/assets/11394369/16700950/c5007bd0-4511-11e6-9f84-808b538495b9.png)

After linking in windows 10,

![image](https://cloud.githubusercontent.com/assets/11394369/16701459/ccf316ec-4514-11e6-96e9-643498a4d2fc.png)

**Comment by p3rcya** [comment]
This is the same issue as https://github.com/getlantern/lantern/issues/4956

**Comment by sunshine19090** [comment]
Yeah, thanks @p3rcya.

My scenario is when the free user becomes pro by referral, then the device list is blank immediately after verification.

**Comment by myleshorton** [comment]
Both are the same as https://github.com/getlantern/pro-server/issues/210
