### ISSUE TITLE
Lantern not routing around failed proxies

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4967]
In my case I have multiple proxies, and one is failing. Lantern does not seem to be successfully routing around that failure.

**Comment by myleshorton** [comment]
I should not I have not fully verified this, but it seemed to be the case, and I wanted to make sure to flag the issue.

**Comment by NAVrasZ** [comment]
this happened to me too,but I found they occupy the same place(pac),so when I run another one,lantern's pac got replaced

**Comment by fffw** [comment]
Current balancer strategy only counts the consecutive success / failure of dialing a proxy. It's possible that client sticks with a blocked proxy if censor intentionally cut off after connected. 

It's pretty normal if timeout errors to same proxy showing up consecutively. That doesn't mean Lantern failed to route around that proxy. It's just multiple requests are issued at nearly the same time, hence time out at the same time. That explains the log file you send @myleshorton.

**Comment by myleshorton** [comment]
Closing this in favor of #5075 and #5076
