### ISSUE TITLE
3.0.6 shows the old start page rather than the new UI 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4972]
![image](https://cloud.githubusercontent.com/assets/7925929/16711104/632f5ba8-45ff-11e6-8e6c-4465f3861739.png)
Getting log from the user https://github.com/getlantern/forum/issues/463

**Comment by p3rcya** [comment]
https://github.com/getlantern/forum/issues/465#issue-164692783 Another user

**Comment by hitzhangjie** [comment]
Uninstall the old release and delele all the relevant configuration files from install path, then install the new release.

**Comment by p3rcya** [comment]
@hitzhangjie Thanks! I've instructed the users who encountered this problem to do so. However, this should also be solved on our end.

**Comment by myleshorton** [comment]
Any particular OS @p3rcya or all OSes?

**Comment by p3rcya** [comment]
So far only one user. OS unknown

**Comment by myleshorton** [comment]
Should be fixed in 3.1.0.
