### ISSUE TITLE
Change log extension to .txt

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4974]
Currently, I have to manually instruct users to change the extension name to txt to upload to github. Even if our log reporting system is up, I expect a substantial portion of users report issues via forum. Changing this will reduce friction for uploading logs (and also a lot of my time)

**Comment by myleshorton** [comment]
Why do they have to change it?

**Comment by p3rcya** [comment]
Github doesn't support .log upload.

On Sunday, July 10, 2016, Myles Horton <notifications@github.com> wrote:

> Why do they have to change it?
> On Jul 9, 2016 11:30 PM, "Percy" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Currently, I have to manually instruct users to change the extension name
> > to txt to upload to github. Even if our log reporting system is up, I
> > expect a substantial portion of users report issues via forum. Changing
> > this will reduce friction for uploading logs (and also a lot of my time)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/getlantern/lantern/issues/4974>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABF0nnWuNzJwqfZ0C9svZUKrSGlmsJAEks5qUJF3gaJpZM4JIxnn
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/issues/4974#issuecomment-231596165>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqVTNPgiu3v0GsNb2XBEWvD6gC6M0ks5qURbCgaJpZM4JIxnn>
> .
>


--
