### ISSUE TITLE
Main UI messed up

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4975]
![image](https://cloud.githubusercontent.com/assets/7925929/16712003/23920ba2-462d-11e6-97ef-fe5c8e5833bd.png)

log https://github.com/getlantern/forum/issues/457#issuecomment-231573079

only one report so far

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/826#issuecomment-235049737
The user tried on Chrome and firefox too. Same problem

**Comment by p3rcya** [comment]
This is probably caused by the same issue 
https://github.com/getlantern/lantern/issues/5025

**Comment by myleshorton** [comment]
This could easily be the result of caching -- fixed in 3.1.0
