### ISSUE TITLE
Plan showing up in USD in China 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#4976]
It happens to me personally 
![image](https://cloud.githubusercontent.com/assets/7925929/16712068/8c9a11f2-462e-11e6-85d9-fbc4d71e2359.png)
![image](https://cloud.githubusercontent.com/assets/7925929/16712069/b0575a8c-462e-11e6-9312-e17da458c7e3.png)

**Comment by NAVrasZ** [comment]
（me too）

**Comment by p3rcya** [comment]
I tested again today and now the price is showing up correctly in CNY
