### ISSUE TITLE
User supposedly  purchased two year with referral but only got 3 months 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#4977]
![image](https://cloud.githubusercontent.com/assets/7925929/16712215/065ae0ec-4635-11e6-8c4a-e108a4a01ed0.png)

log https://github.com/getlantern/forum/issues/481#issuecomment-231574893

We first need to confirm that his payment went through. You can see his account email in the screenshot

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/707

**Comment by myleshorton** [comment]
This one seems important @uaalto and could point to other related bugs.

**Comment by myleshorton** [comment]
maybe easy to unit test this case?

**Comment by uaalto** [comment]
Referrals and payments are handled separately in different tasks and they both add, so if one of them wasn't applied is becausej it failed. Given the episode we've experienced with payments, it can totally be the case that payment went through and we didn't process it.
However, this user has no attempted purchase, which means we never charged him. Stripe doesn't

It is extremely unlikely that we charged him with no records at all, not even an attempt to purchase in the logs.

**Comment by p3rcya** [comment]
@uaalto Ok, it might be that seeing all other complains, he was trying to trick us. I've asked him to upload a screenshot of Alipay transaction ID with Alipay account

**Comment by uaalto** [comment]
Thank you @p3rcya. We have better ways now of avoiding these lost operations again.

**Comment by p3rcya** [comment]
@uaalto @myleshorton Did you see "It is extremely unlikely that we charged him with no records at all, not even an attempt to purchase in the logs."?  Well the user just uploaded the transaction number with screen shot here https://github.com/getlantern/forum/issues/481#issuecomment-233812876

**Comment by p3rcya** [comment]
Oh, the user said the log he uploaded is not the one on the computer with original purchase. I've asked him to upload the original logs. He is away for a few days and but will upload once he gets home

**Comment by uaalto** [comment]
Since this is an open repo, I won't comment on the details here to avoid anyone else believing that can get Pro for free.

There is a particular reason for this to happen. And that's why it is "extremely unlikely", not impossible.

**Comment by uaalto** [comment]
Ok, I've reviewed the logs again, and we get this user logged with the last batch where I used all our history of archived logs.
I've just awarded him 2 years as he paid for, plus the 3 months he got from referrals.
I apologize for the annoyance to the user.

**Comment by p3rcya** [comment]
@uaalto The user has uploaded the log in the machine where he made the purchase. You might find it helpful to debug
[log.zip](https://github.com/getlantern/lantern/files/375349/log.zip)

**Comment by uaalto** [comment]
I think we can mark this as closed.
