### ISSUE TITLE
lantern不能正常访问

### ISSUE THREAD

**Issue by strongant** [getlantern/lantern#4982]

**Comment by wangcheng911** [comment]
最新版的可以的，但是Google需要输入验证码

**Comment by XieXianbin** [comment]
同问

**Comment by guizhenwei** [comment]
3.0.6  Pro 不能正常访问了。 Win10 ＋ Android都不行了。

Google, wikipedia, facebook, twitter, youtube.... 都不行了。

我今天还在我的一个500多人的微信群里推广，有些朋友已经付费购买了。
我可能让他们失望了。

请求开发团队赶紧修复吧！！！！

**Comment by myleshorton** [comment]
Please send your logs if you can all. Instructions are here:

https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢。 请去论坛发帖 https://github.com/getlantern/forum 谢谢
