### ISSUE TITLE
2.x erases 3.x settings

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4983]
It's my bad by changing `settings.yaml` from lower cased to camel cased. 2.x doesn't recognize those entries. 3.x can load yaml in both form, so we can simply change it to lower cased again. @myleshorton Sorry I messed up the feature you implemented correctly.

It's unlikely that users purchased Pro and purpusely launch 2.x again, but if user launch it incidently, the Pro account will be cleared. Could be the reason of https://github.com/getlantern/forum/issues/428 but not quite sure.

**Comment by myleshorton** [comment]
Doesn't really matter any more.
