### ISSUE TITLE
你们的收费计划是早有了吗？还是带宽费用承受不了才开始做收费版？

### ISSUE THREAD

**Issue by FrankZhang002** [getlantern/lantern#4987]
开发者们，你们好，我从大概一年多之前开始使用蓝灯，并且把这个软件推荐给我很多朋友，我跟他们说你们这个软件是免费、开源、多平台、易用、不限流量，谷歌做后盾进行支持（我现在存疑）......反正就是把你们说的非常好非常好。我记得你们之前的这个软件是鼓励“你和你国外朋友之间”这种P2P模式进行科学上网的，这种P2P模式不做了吗？只卖流量了吗？还有你们的收费计划是早有了吗？

**Comment by p3rcya** [comment]
请看精华帖 https://github.com/getlantern/forum/issues?q=is%3Aopen+is%3Aissue+label%3A%E7%B2%BE%E5%8D%8E 里面已经做了详细说明，谢谢

**Comment by FrankZhang002** [comment]
你们的精华帖没有回答我的问题

**Comment by FrankZhang002** [comment]
你们和国内那些“放水养鱼，抽水杀鱼”先养用户群再进行收费的国内软件有什么区别么

**Comment by p3rcya** [comment]
@FrankZhang002 
首先说明，蓝灯3永远会提供免费版。我们希望蓝灯成为最稳定的免费翻墙软件。对于翻墙网络有更高要求的用户我们提供专业版。蓝灯和VPN的区别请点这里

下面时专业版和免费版的区别

免费版

免费版有800MB流量限制。免费版流量使用完毕之后会限速到20KB/s，限速是每个连接20KB/s，所以对浏览网页是基本没有影响的。
对稳定性和速度不太有要求的人，看看网页用免费版完全可以。

**Comment by p3rcya** [comment]
国内那种会一直提供免费么？ 收费版出了后肯定停掉免费版啊。我们会永久提供免费版

**Comment by FrankZhang002** [comment]
限速限时间，国内软件提供的免费版跟你们模式一样。

**Comment by FrankZhang002** [comment]
你们之前是鼓励P2P方式进行翻墙的，现在跟那些卖VPS、卖VPN的有什么区别？

**Comment by wangcheng911** [comment]
确实有些过分，感觉被你们骗了，作为一个程序员，深深感到800M根本不够，而且速度也不够。

**Comment by ssy341** [comment]
用了那么久免费，现在也有免费版，没有强制缴费，不过分吧，前面用的爽的时候没有得到一点好，现在一说要收费就被骂成狗，作为程序员，我们不是应该要互相理解么？

**Comment by p3rcya** [comment]
@FrankZhang002 P2P 墙外用户不够多，没用
@wangcheng911 作为程序员power user买个专业版不过分吧。而且程序员可以直接搭SS啊。
@ssy341 谢谢理解。我们现在也努力把免费版搞好。前面因为免费版被封了，有人认为我们故意封免费版，来卖专业版，实在令人寒心。

**Comment by wangcheng911** [comment]
你们收费，我很不爽，但是我还会付钱买的。。。
因为不付费不行。。。

**Comment by FrankZhang002** [comment]
@ssy341这不算骂成狗吧？

**Comment by wangcheng911** [comment]
我今天还给朋友介绍了，我大言不惭的说开源、免费、网速可以达到带宽
这大嘴巴把我抽的，啪啪的

**Comment by ssy341** [comment]
@FrankZhang002 没有针对你，因为外面有好多骂声，交了费感觉就是上帝，我们要超好的方向想，毕竟这个东西在天朝能存活也很不容易，持有一颗感恩的心，世界变得更美好

**Comment by p3rcya** [comment]
@wangcheng911 不好意思。我们正在解决速度问题。你是程序员可以看看我们的issue tracker，都正在全力解决。

**Comment by FrankZhang002** [comment]
@p3rcya 我觉得你们不至于封免费版，但是现在你们经营这个项目的方式，让我真的觉得跟那些卖VPSVPN的没什么本质区别。

**Comment by wangcheng911** [comment]
@FrankZhang002 就是就是，跟国内的一模一样，特别不仗义

**Comment by p3rcya** [comment]
@wangcheng911 原来一直提供免费版，以后也会永久提供免费版。 您再说不仗义，那我们也没什么办法。。。我们也需要支付服务器成本的啊。 而且免费版GFW特别容易封

**Comment by FrankZhang002** [comment]
@p3rcya 情怀毕竟不能当饭吃，你们也没打算一直做公益。你也不要寒心，从你们决定Lantern开始收费之后，你们就不要怕被别人说。希望你们好吧，毕竟国内还有那么多不会付费的用户，免费版可能是他们唯一会使用的版本，希望你们的免费版可以更稳定一些。如果有可能，希望你们对维基百科这类非商业或者其他纯学术网站不限速，方便国内的学生和科研机构翻墙找资料。我目前不会再向其他人推荐Lantern了。

**Comment by p3rcya** [comment]
@FrankZhang002 https://github.com/getlantern/lantern/issues/4990
