### ISSUE TITLE
Mac OS Sierra beta 无法使用lantern

### ISSUE THREAD

**Issue by easonchina** [getlantern/lantern#4991]
在最新的MacOs 10.12 Sierra beta中，lantern2.2.5 无法使用，无法访问任何网络，需要手动关闭后台进程并且关闭网络代理选项才能正常上网。

**Comment by NAVrasZ** [comment]
加钱换3.0.6（手动滑稽）

**Comment by fujita-nozomi** [comment]
呵呵... 现在lantern收费了 还是用回shadowsocks吧

**Comment by p3rcya** [comment]
蓝灯一致可以免费使用的。 请看 https://github.com/getlantern/forum/issues/378

Mac beta等稳定下来我们才会支持

**Comment by just4id** [comment]
几个月过去了至今这个问题仍未解决。macOS Sierra正式版下lantern一启动便崩溃。

**Comment by p3rcya** [comment]
请看公告 https://github.com/getlantern/forum/issues/1364

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢各位的耐心等待！
