### ISSUE TITLE
Desktop UI: "Referral Promotion" code entering screen and formatting and button

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#4998]
This is another change to help with the confusion users are experiencing with the referral process. Please update the screen with the following format and button changes for clarification. 

In addition to the formatting changes shown on the image below please change SKIP TO CHECKOUT to a proper button. (Darker Blue)  This button used to be called "CONTINUE TO CHECKOUT" but was already changed in the JSON file.

![update](https://cloud.githubusercontent.com/assets/7864729/16743058/a449167c-4778-11e6-99ac-74c4542aad19.png)

@myleshorton These are leftover issues from #4897  the other issues from that ticket were changed here by @chipstehr and I here: https://github.com/getlantern/lantern-desktop-ui/blob/master/locale/en-US.json and just need to be pushed to transifex

**Comment by myleshorton** [comment]
All set
