### ISSUE TITLE
Bad input: request missing Email - Pro user unable to log in 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#5003]
OP: https://github.com/getlantern/forum/issues/531 with log. The user is able to request the verification email after turning on VPN

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/561#issuecomment-232260404

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/358#issuecomment-232333113

**Comment by fffw** [comment]
3.0.7 should fixed this too
