### ISSUE TITLE
qq邮箱无法收到验证代码

### ISSUE THREAD

**Issue by Natishen** [getlantern/lantern#5004]
如题，有没有国内小伙伴解决一下，看懂英文有点吃力

**Comment by p3rcya** [comment]
请上传截图和请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by p3rcya** [comment]
已经收集到此帖 https://github.com/getlantern/lantern/issues/5013
