### ISSUE TITLE
Lantern will block all internet access after sometime [Mac]

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5007]
Issue description on logs here https://github.com/getlantern/forum/issues/537

**Comment by p3rcya** [comment]
This is a duplicate of https://github.com/getlantern/lantern/issues/3039 But the original issue still hasn't be solved in 3.0.6

**Comment by fffw** [comment]
It's rather tricky as it doesn't look like a bug of Lantern itself. I never encountered the issue, but this post seems very interesting https://www.senia.org/2016/04/07/apple-os-x-el-capitan-networkd-pac-oddities/ . It even mentioned https://github.com/getlantern/lantern/issues/3039

**Comment by fffw** [comment]
More reference https://www.v2ex.com/t/174191 . Looks like something with PAC.

Lots of `kCFErrorDomainCFNetwork` should appear when searching through Console (the macOS log viewer).

**Comment by myleshorton** [comment]
Closing in favor of #3039 to avoid two conversations.
