### ISSUE TITLE
0.0 MB remaining of your free monthly data?

### ISSUE THREAD

**Issue by Bewolf2** [getlantern/lantern#5008]
Can't use lantern anymore, showing message "0.0 MB remaining of your free monthly data". Is that lantern is no longer free now?

**Comment by p3rcya** [comment]
You should still able to use Lantern after reaching the data cap, but only with a reduced speed. If you cannot, please upload log

**Comment by bash-horatio** [comment]
@p3rcya do you know whether lantern can reach max speed of my Internet bandwidth after upgrading to pro? If it can, I will consider to buy a account

**Comment by p3rcya** [comment]
@bash-horatio It depends on your network condition. But we're in the process of acquiring servers with better connections. So in the future, we can probably reach the maximum speed.

**Comment by bash-horatio** [comment]
@p3rcya Ok, thank you. I look forward to the release of pro version

**Comment by bash-horatio** [comment]
@p3rcya Ok, thank you. I look forward to the stable release of pro version
