### ISSUE TITLE
账户将在01/01/1970过期,如图

### ISSUE THREAD

**Issue by xusx1024** [getlantern/lantern#5012]
![image](https://cloud.githubusercontent.com/assets/9455259/16792954/d13b6bac-48ff-11e6-8013-7755ad71b4a5.png)

**Comment by xusx1024** [comment]
使用pro的邮箱去登录，提示如图：![image](https://cloud.githubusercontent.com/assets/9455259/16793070/9c79f590-4900-11e6-91f1-f9f3883a4d30.png)

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by p3rcya** [comment]
已经收集到此帖 https://github.com/getlantern/lantern/issues/5009
