### ISSUE TITLE
Distinguish verified and unverified email in account management and allow edit email

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#5013]
Currently, all user emails are not verified. The email during stripe check out can be entered wrong accidentally. So all new accounts have an unverified email. 

Users then can manually verify email in the account management page. 

If an email is not verified, users can change the email without verification of the older email. This is to solve accidental entering during checkout and @qq.com cannot receive the verification code. But the new email address has to be verified for the change to become effective.

If an email is verified, users complete the verification of older email to change the email address. The new email address has to be verified for the change to become effective.

**Comment by p3rcya** [comment]
This is a log that user unable to receive code @qq.com https://github.com/getlantern/forum/issues/593#issuecomment-232583305

**Comment by p3rcya** [comment]
https://github.com/getlantern/lantern-internal/issues/54
