### ISSUE TITLE
从开源到收费，官网为什么一直没有更新，给个解释撒

### ISSUE THREAD

**Issue by ShangXinbo** [getlantern/lantern#5014]
关于3.x版本，官网为什么一直没有放出消息，怎么证明你们是诚恳的

**Comment by farell** [comment]
跟VPN有区别吗？

**Comment by p3rcya** [comment]
@ShangXinbo 精华帖已经写明了收费原因了 https://github.com/getlantern/forum/issues/378
@farell 蓝灯和VPN的区别请点这里 https://github.com/getlantern/forum/issues/361

**Comment by tinyhare** [comment]
软件是开源的，服务是收费的
