### ISSUE TITLE
Stuck at verification screen 网易邮箱无法收到lantern，在github下载版本后登陆一直转圈

### ISSUE THREAD

**Issue by lym7851824** [getlantern/lantern#5016]
[lantern.txt](https://github.com/getlantern/lantern/files/363241/lantern.txt)

网易邮箱无法收到lantern，在github下载版本后登陆一直转圈

**Comment by yzlee** [comment]
一般来说，换个时间段，或者等一会儿就好了……

**Comment by p3rcya** [comment]
@lym7851824 请上传个截图

**Comment by p3rcya** [comment]
More user reported that they're stuck at the verification screen.
![image](https://cloud.githubusercontent.com/assets/7925929/16883913/61d27864-4a7b-11e6-87da-4c1ea60d5bb3.png)
log https://github.com/getlantern/forum/issues/643

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/646#issuecomment-233033287

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/670#issue-165957932

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/651#issuecomment-233162190

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/685

**Comment by p3rcya** [comment]
More log https://github.com/getlantern/forum/issues/689#issue-166007625

**Comment by p3rcya** [comment]
This user reported that he can only request and submit verification code with VPN on, log https://github.com/getlantern/forum/issues/711#issuecomment-233551324

**Comment by p3rcya** [comment]
@myleshorton This should be the top priority in the backlog, more than 0MB or 4th device authorization.

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/742#issuecomment-234151787

**Comment by myleshorton** [comment]
Hey @fffw have you seen this one?

**Comment by fffw** [comment]
I didn't see it since we switched to dual fetcher for pro-server. I suspect it's caused by https://github.com/getlantern/pro-server/issues/229

**Comment by fffw** [comment]
I'm still seeing following from user logs, though there are successful fronted calls. Maybe dual fetcher doesn't work as we expected. Digging.

```
Jul 21 03:34:32.028 - 6m9s ERROR flashlight.pro: proxy.go:66 Could not issue HTTP request? Post https://api.getiantem.org/user-link-request: Bad Gateway [error=Could not issue HTTP request? Post https://api.getiantem.org/user-link-request: Bad Gateway error_op=Post error_type=errors.Error http_method=POST http_proto=HTTP/1.1 op=chained origin=api.getiantem.org proxy_type=chained root_op=chainedandfronted]
ERROR flashlight.pro: proxy.go:66 Caused by: Post https://api.getiantem.org/user-link-request: Bad Gateway
```

**Comment by fffw** [comment]
Ok it is caused by multiple reasons:

1. `POST` requests to pro-server is via `ChainedThenFronted`.

2. It takes 30s for `ChainedThenFronted` to notice the failure of chained fetcher and switch to fronted.

3. `proxied` unconditionally switches to "chained only mode" when chained request succeeded, no matter how late it did. If a proxy is much slower than fronted, it's very likely the proxy fails next time.

How to solve:

1. Avoid retry same proxy in `balancer.Dial` #5075, which reduces the 30s to 10s.

2. Dynamically adjust dialer's timeout. #5073

3. Not switch to chained only mode if it's too slow #5076

**Comment by fffw** [comment]
@myleshorton I turned it to an epic, and probably will work on #5075 and #5076 first.

**Comment by lym7851824** [comment]
![default](https://cloud.githubusercontent.com/assets/20439999/17294401/338fd512-5829-11e6-9c98-9d249b1d3414.jpg)

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/909

**Comment by p3rcya** [comment]
no log yet https://github.com/getlantern/forum/issues/912

**Comment by p3rcya** [comment]
This user can access youtube but cannot log in https://github.com/getlantern/forum/issues/920#issue-169263929

**Comment by myleshorton** [comment]
Possibly the same cause as #5039. Could be fixed/improved in 3.1.0?

**Comment by p3rcya** [comment]
More description here https://github.com/getlantern/lantern-internal/issues/110 will monitor after 3.1

**Comment by fffw** [comment]
All 3 issues in this epic were closed
