### ISSUE TITLE
Telegram share button in mobile app and website

### ISSUE THREAD

**Issue by narimangharib** [getlantern/lantern#5019]
According to Iranian Android market,Cafebazaar, almost 18m android users are using Telegram inside Iran.

you can use this structure to spread the apk file among Iranian telegram users inside Iran.

href="https://telegram.me/share/url?url=https://www.manoto.news/news/rfly3j/news23227&amp;text=نظارت ۵ قایق تندرو سپاه بر عبور ناو جنگی آمریکایی در تنگه هرمز واکنش هایی را به همراه داشته است."
![screen shot 2016-07-14 at 11 24 38](https://cloud.githubusercontent.com/assets/3672889/16836558/085d8d0c-49b6-11e6-875e-2ed2eff9d080.png)

**Comment by alivazirinia** [comment]
Tnx Nariman use this code for share button in wordpress : 
`<a title="Share On Telegram" href="https://telegram.me/share/url?url=<?php the_permalink(); ?>" target="_blank">Share On Telegram </a>`
