### ISSUE TITLE
购买专业版速度慢的要死怎么办。。

### ISSUE THREAD

**Issue by logbird** [getlantern/lantern#5020]
购买专业版速度慢的要死怎么办。。
很多站都慢道无法忍受。。80%的情况是直接打不开。。这个该怎么处理呢？？

**Comment by logbird** [comment]
logbird@126.com
这个是我专业版的邮箱 可否 换一个快一点的服务器？？

**Comment by ssy341** [comment]
@logbird 更换邮箱的功能在开发，后续版本会有选择节点，能不能选择快点的就不知道了，速度应该是理想的，继续等待吧

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢 
我们正在获取更加快速的线路

**Comment by logbird** [comment]
已经上传
[lantern.log.txt](https://github.com/getlantern/lantern/files/365256/lantern.log.txt)

**Comment by p3rcya** [comment]
已经将log收集到了4885， 我们正在修复。

**Comment by logbird** [comment]
辛苦啦。。期待修复
