### ISSUE TITLE
没法输入验证码

### ISSUE THREAD

**Issue by xuwv** [getlantern/lantern#5021]
登录时点击发送电子邮件，邮箱短信已经收取到，网页上还一直转圈，没办法输入验证码

**Comment by orbancanon** [comment]
@xuwv 可以关了那个登录界面重试一次。

**Comment by xuwv** [comment]
@orbancanon 重试5次了

**Comment by orbancanon** [comment]
@xuwv 你用的什么浏览器？哪个版本的Lantern？

**Comment by xuwv** [comment]
@orbancanon Safari/Chrome @ Lantern 3.0.7 (20160714.225527)

**Comment by orbancanon** [comment]
@xuwv 很遗憾我们没办法重现这个问题。或许你可以帮助我们查找原因？用Chrome打开蓝灯的界面，按Command + Option + I（大写的i）调出开发者界面，按下图红框的标示，切换到网络那一页，左边输入"user-link"过滤，然后刷新页面正常登录，看出现的记录是不是跟下面第一张图一样。

如果不一样，请按第二幅图的标示看一下。可以按Control + Command + Shift + 4截图粘贴到这里。

<img width="1211" alt="user-link" src="https://cloud.githubusercontent.com/assets/20250571/16866341/f730c3f8-4a9d-11e6-83a6-15893a355aa3.png">

<img width="1210" alt="user-link-2" src="https://cloud.githubusercontent.com/assets/20250571/16866496/d1e56e86-4a9e-11e6-8233-d89ffd1f7751.png">

**Comment by xuwv** [comment]
@orbancanon  第二个请求错误了
<img width="894" alt="2016-07-15 3 32 22" src="https://cloud.githubusercontent.com/assets/5266673/16867062/4343492e-4aa2-11e6-8863-7273f0647c51.png">
<img width="891" alt="2016-07-15 3 32 43" src="https://cloud.githubusercontent.com/assets/5266673/16867102/825d807a-4aa2-11e6-9889-68ee03deba6b.png">
<img width="894" alt="2016-07-15 3 32 55" src="https://cloud.githubusercontent.com/assets/5266673/16867131/bb1620d4-4aa2-11e6-854c-0dcd4be16717.png">

**Comment by orbancanon** [comment]
@xuwv 那个一直显示pending吗？说明还没有返回。你再等等看最终结果是什么？

**Comment by xuwv** [comment]
@orbancanon 一直没反应，试了七八次，这下子可以了，谢谢

**Comment by orbancanon** [comment]
@xuwv 我估计是你的免费服务器被墙了，所以访问特别慢，最后超时导致的。你多用一下，如果没问题的话就关了吧。

**Comment by xuwv** [comment]
@orbancanon 每次都需要获取验证码吗

**Comment by orbancanon** [comment]
@xuwv 不用啊。登录一次，那台电脑就是专业版了，以后用就是了。

**Comment by xuwv** [comment]
@orbancanon 我刚刚退出了，还是让我登录输入电子邮件

**Comment by orbancanon** [comment]
@xuwv 出现欢迎界面了没？我检查检查

**Comment by xuwv** [comment]
@orbancanon 这个页面
<img width="822" alt="2016-07-15 4 13 55" src="https://cloud.githubusercontent.com/assets/5266673/16867916/31656804-4aa7-11e6-9d18-9e82d942de4f.png">

**Comment by xuwv** [comment]
@orbancanon 然后呢

**Comment by orbancanon** [comment]
@xuwv 你在大概什么时候购买专业版的呢？还是通过邀请别人购买得到的？数据有点奇怪。。。

**Comment by xuwv** [comment]
@orbancanon 今天买的

**Comment by orbancanon** [comment]
@xuwv 我们似乎找不到你的购买记录。

**Comment by xuwv** [comment]
@orbancanon 找不到我的购买记录还给我发验证码？难道支付宝还没有付钱给你们？

**Comment by xuwv** [comment]
@orbancanon 刚刚想登陆后截图，结果又不能登录了，pending的结果是(failed)::ERR_EMPTY_RESPONSE

**Comment by orbancanon** [comment]
@xuwv 不需要了。如果你在电脑上购买，专业版立即生效，并不需要登录。所以看起来中间出了啥问题……你在登录之前有在Lantern的其它地方输入过你的email地址么？

**Comment by xuwv** [comment]
@orbancanon 购买后返回去登录，然后出现pending的问题，你知道的，现在还有问题

**Comment by xuwv** [comment]
@orbancanon 现在怎么做？

**Comment by p3rcya** [comment]
@orbancanon "我估计是你的免费服务器被墙了，所以访问特别慢，最后超时导致的" 
但即使是免费服务器被墙，验证码界面也应该使用meek的，可以直接访问的。不然已经购买专业版的用户不是可能无法访问么？ 

这个可能导致了 https://github.com/getlantern/lantern/issues/5027

**Comment by p3rcya** [comment]
这个问题也是  https://github.com/getlantern/lantern/issues/5016

**Comment by xuwv** [comment]
@p3rcya  请问你是利益相关人员吗？能不能帮我处理一下退款问题啊，用的有点恼火。

**Comment by orbancanon** [comment]
@xuwv 抱歉一直在处理这个问题没及回应。现在应该是解决了吧？
