### ISSUE TITLE
[Android] Invite friend page height off

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#5026]
![image](https://cloud.githubusercontent.com/assets/7925929/16866385/6ef41d0a-4a20-11e6-8ba1-d1447253375e.png)
On my nexus 5. You see the bold Chinese characters are cut off.

This might be related to https://github.com/getlantern/lantern/issues/4537 which is still not fixed in 3.0.7

**Comment by atavism** [comment]
This one should also be fixed
