### ISSUE TITLE
Nothing happens when click "Continue to check out screen" 

### ISSUE THREAD

**Issue by ghost** [getlantern/lantern#5027]
log https://github.com/getlantern/forum/issues/549

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/611#issuecomment-232940677

**Comment by p3rcya** [comment]
More complaint https://github.com/getlantern/forum/issues/697

**Comment by myleshorton** [comment]
@fffw have you seen this one too? If so maybe you can try to tackle it? I've seen it on pretty much all the buttons at some point so happy to do it if you can't reproduce.

**Comment by fffw** [comment]
@myleshorton I logged the same issue at https://github.com/getlantern/lantern-desktop-ui/issues/153. Will close that one.

> Stripe Checkout page can take 5-10 seconds to load. Users may click multiple times or just don't know what's going on during that period. Showing the overlay would be sufficient.

**Comment by myleshorton** [comment]
Oh right @fffw -- yeah yours is more specific actually so we could keep that open too. I've definitely also seen it with other buttons too, but maybe they're related not sure.

**Comment by fffw** [comment]
`Checkout.js` makes tens of HTTP calls, which is the main reason why the Stripe dialog can easily take tens of seconds to load. On one of the China box, `time curl 'https://b.stripecdn.com/checkout/v3/checkout/inner-C.....js'` took 3-5s when fetching directly, and 15-20s through Lantern.

**Comment by fffw** [comment]
`GET /plans` took ~9s. The delay accessing any site is the main reason slows down the buttons.
For this specific button, we can make the UI more smooth by adding load animation.

**Comment by p3rcya** [comment]
We probably need to inform the users it take around half a minute. Even with a loading animation for 20s, most users would think it stuck

**Comment by p3rcya** [comment]
More user complaint. Is this deployed? 
https://github.com/getlantern/forum/issues/828

**Comment by fffw** [comment]
Oh it's a client side change that will available in next version. Ok to keep it open until next release.
