### ISSUE TITLE
付完款，发现gmail.com写成了gmai.com，怎么办？

### ISSUE THREAD

**Issue by J1Heng** [getlantern/lantern#5035]

**Comment by p3rcya** [comment]
以后会推出邮箱修改功能。已经登陆的设备可以直接修改邮箱

**Comment by carlzeiss1981** [comment]
哈哈哈哈哈！！！！郁闷的一笔啊！

**Comment by J1Heng** [comment]
现在没有设备登陆过，这个要怎么修改，有没有官方客服人员可以帮忙修改回来？

**Comment by p3rcya** [comment]
购买的设备应该会自动登陆的啊？ 
到时候我们会出工单系统，让我们能后台手动修改email

**Comment by J1Heng** [comment]
@p3rcya  麻烦看看，没有自动登陆，那我现在应该做什么？  付错邮箱，没有账号可以用。

<img width="688" alt="screen shot 2016-07-18 at 10 09 09 am" src="https://cloud.githubusercontent.com/assets/16010048/16904859/b8602d9c-4ccf-11e6-8d57-a4da8f4c9219.png">

**Comment by p3rcya** [comment]
@J1Heng 好，我们可以后台解决下

**Comment by J1Heng** [comment]
a

**Comment by p3rcya** [comment]
你为什么关闭了？ 我们还没解决呢？

**Comment by J1Heng** [comment]
@p3rcya  重开了，看你变成ghost了

**Comment by p3rcya** [comment]
我统一收集到这里 https://github.com/getlantern/lantern/issues/5045
