### ISSUE TITLE
无法用google！！！！！

### ISSUE THREAD

**Issue by carlzeiss1981** [getlantern/lantern#5041]
![2016-07-17 11 04 44](https://cloud.githubusercontent.com/assets/20150812/16898479/82fe689c-4c0e-11e6-9bd0-d8afb04c3a25.png)

**Comment by carlzeiss1981** [comment]
@p3rcya

**Comment by p3rcya** [comment]
这个是Google将流量误判为垃圾流量的原因。我们后台正在解决。你可以先用 https://www.startpage.com/ 代替，其搜索结果来自Google。
