### ISSUE TITLE
为什么每次退出后重登都需要获取验证码！

### ISSUE THREAD

**Issue by xuwv** [getlantern/lantern#5046]

**Comment by muller1108** [comment]
你仔细看就会发现根本没有登陆上去，免费的流量还是在走，你只要刷新登陆页面就发现又要让你登陆

**Comment by p3rcya** [comment]
这个问题这几天就可以解决了，是过期时间1970导致的

**Comment by p3rcya** [comment]
已经解决了，请见https://github.com/getlantern/forum/issues/705

**Comment by xuwv** [comment]
我的已经修改好了，虽然期间用着很烦，但还是谢谢你们 @p3rcya

**Comment by p3rcya** [comment]
之前麻烦你了不好意思。以后遇到任何问题，请反馈！
