### ISSUE TITLE
Lantern not compatible with macOS Sierra 10.12 Beta

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5048]
log here https://github.com/getlantern/forum/issues/703#issuecomment-233535346

**Comment by xieyingli** [comment]
。。。版主你终于开始重视这个问题了。。。

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/730

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/849

**Comment by p3rcya** [comment]
closed in favor of https://github.com/getlantern/lantern/issues/5254
