### ISSUE TITLE
Lantern displays the expiration date in Chinese even after changing the language to English

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#5050]
I used China VPS. So everything was in Chinese when I initially authorized pro. After changing the language to English, the expiration date is still shown in Chinese format. It should actually be displayed in the english format. 

![pasted image at 2016_07_19 10_36 am](https://cloud.githubusercontent.com/assets/11394369/16960987/715eac4e-4da0-11e6-966a-c47afd08b123.png)

cc: @p3rcya

**Comment by p3rcya** [comment]
This is due to the format setting in the Chinese VPS
