### ISSUE TITLE
User encounter payment error 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5054]
![image](https://cloud.githubusercontent.com/assets/20512438/16976773/304a418a-4e06-11e6-8e46-94fe25ac01b0.png)
In windows 10 with Edge, after entering Alipay info and green checks appears, the website will hang for a long time and eventually ask him to retry. 

log https://github.com/getlantern/forum/issues/726#issue-166407510

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/737

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/776

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/796

**Comment by p3rcya** [comment]
on android 
Log sent by 794005572@qq.com
screenshot here getlantern/forum#671 (comment)

**Comment by myleshorton** [comment]
Let's wait for better stripe errors to come online.

**Comment by p3rcya** [comment]
missing stripe token https://github.com/getlantern/forum/issues/904#issuecomment-237595008

**Comment by p3rcya** [comment]
more https://github.com/getlantern/forum/issues/1051
