### ISSUE TITLE
Able to authorize 4th device

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#5055]
![image](https://cloud.githubusercontent.com/assets/11394369/16993796/ba39320e-4e59-11e6-9dea-1394851e3f2c.png)

**Comment by myleshorton** [comment]
Thanks @sunshine19090 this one's interesting. FYI @uaalto

**Comment by uaalto** [comment]
Yeah we don't have a limit ATM. I know we discussed this, but I don't remember what happened with it and why remains undone. Should we then add this to the server with a limit of 3?

**Comment by p3rcya** [comment]
Yes, we should. Can you also comment on this https://github.com/getlantern/lantern-internal/issues/39

**Comment by uaalto** [comment]
I've opened the ticket in the pro-server, since this is entirely a Pro server issue. What's the priority of this @myleshorton ?

**Comment by p3rcya** [comment]
This should rank after 
Stuck at verification screen https://github.com/getlantern/lantern/issues/5016
Google403 https://github.com/getlantern/http-proxy-lantern/issues/97
Slow speed https://github.com/getlantern/lantern-internal/issues/36

**Comment by MarkdotT** [comment]
New Pro User here... (keep up the good work etc) by 

Have you considered the issue of concurrency? I have more than 3 devices all of which would benefit from Lantern when I am using them but I would never need more than 3 devices at any one time.

If you allow more than 3 devices to be authorised, could the usage be controlled imposing a limit of 3 concurrent authorised devices to save me having to deauthorise/reauthorise as needed?

Another alternative would be that Pro gets you 3 authorisations and you pay for additional authorisations.

Mark.T

**Comment by xiam** [comment]
Sounds like this is a related issue https://github.com/getlantern/pro-server/issues/286

**Comment by uaalto** [comment]
Should this be closed, since the limit is already enforced in the Pro server?
