### ISSUE TITLE
Couldn't remove/deauthorize a device

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#5057]
Looks like this is newly introduced.

After removing a device, I still see that device in the list. 

Steps:

1. Purchase in win7
2. Authorize in win 10
3. Remove win 7. 

Getting a confirmation that the device is removed but there is no change in the account management UI in both win 7 and win 10.

**Comment by p3rcya** [comment]
Users complained this too. He travels a lot and uses Pro on public computers but he cannot revoke it https://github.com/getlantern/forum/issues/893

**Comment by p3rcya** [comment]
Still not solved in 3.1.1

**Comment by fffw** [comment]
It can be done at the client side. Once client finds its device ID not in the device list return by `/user-data`, it removes user ID / token and call /user-create. 

It may mistakenly bring Lantern to free if the device ID changed somehow, but should be very rare.

cc @atavism

**Comment by p3rcya** [comment]
I recommend it to be marked as auto-update blocker. Many complaints on this

**Comment by joesis** [comment]
@fffw 's idea would lead to some unexpected problem, maybe rare, maybe not. If the device ID changed somehow (we didn't fully understand all the cases the device ID would change), the Pro client would turn back to free immediately, which is awful.

A few alternatives:
1. switch to more reliable device ID
2. have a removed devices list. Client only remove itself if the device ID is in it. It requires both client and server side change.

**Comment by joesis** [comment]
Another simpler client-only workaround would be a "log me out from this device" function, maybe on the same "account management" dialog. It is useful if the most scenario is to log out from a public computer.

**Comment by p3rcya** [comment]
Yeah, I think a simple "log me out from this device" for now is great!

**Comment by atavism** [comment]
On mobile, we had something similar on the "Pro Account Management" screen already. Do you still have the design for that, @Derekf5? Should be easy to add back.

**Comment by Derekf5** [comment]
yes @atavism currently we show what device you are using under devices authorized to use your pro account.   we should just change the "x" that allows you to deauthorize to say LOG OUT for the device the user is currently on.

**Comment by p3rcya** [comment]
@Derekf5 I think this design was produced by you months ago. Maybe you can find that ticket again.

**Comment by Derekf5** [comment]
@atavism @p3rcya here you go
CC: @carsonefv will you post the desktop version here as well?
![account-management](https://cloud.githubusercontent.com/assets/7864729/18489740/e7cfcbb2-79cc-11e6-8792-688b70520d22.png)

**Comment by carsonefv** [comment]
Here's the desktop version @joesis @p3rcya cc @Derekf5 

![screenshot 2016-09-13 16 40 03](https://cloud.githubusercontent.com/assets/4400763/18490734/4c5e17a6-79d1-11e6-9091-25e2bad45d7f.png)

**Comment by atavism** [comment]
I added a check on mobile to unlink the current device (and switch the UI to free) if the device name no longer appears in the list of active devices we get back from ``/user-data`` -- could we do something similar on desktop? Just end the current session (remove the user ID/token and call /user-create) if the device name is not present?

**Comment by joesis** [comment]
@atavism brought up a neat idea that Lantern client can turn to free only if both the device ID and name is absent from the device list. That would solve the changed device ID scenario. Will do both.

**Comment by p3rcya** [comment]
This kind be very good when combined with https://github.com/getlantern/lantern/issues/5056#issuecomment-242904150

**Comment by p3rcya** [comment]
@myleshorton @fffw The "LOT OUT" button is not implemented on desktop. It is already implemented on mobile

**Comment by atavism** [comment]
Hey @joesis, were you still working on this one? I notice when I unlink desktop from mobile, my session remains active regardless. I have to delete the settings file and re-install Lantern to unlink Pro which is pretty annoying.

**Comment by p3rcya** [comment]
Yeah. When I removed win10. It's not really removed and then Android is my last device. So I cannot log out of Android either.  Many users complain about this too

**Comment by joesis** [comment]
@atavism @p3rcya It's pending merge https://github.com/getlantern/lantern-desktop-ui/pull/188.

**Comment by sunshine19090** [comment]
Works fine
