### ISSUE TITLE
付款后不好用的反馈--（附自己尝试的解决办法）

### ISSUE THREAD

**Issue by iswhat** [getlantern/lantern#5060]
youtube之类的网站绝大多数时间不能访问，不管是重装还是重启，都没有用。
甚至https://getlantern.org/faq/index.html 这个官方的帮助网站都访问不了

自从开始收费之后，整个lantern都变得极其不稳定，原本是我推荐给周围朋友号称最好用的工具，现在却成了这个样子，真是打脸啊....

日志在下面

[lantern.zip](https://github.com/getlantern/lantern/files/375103/lantern.zip)

[lantern.TXT](https://github.com/getlantern/lantern/files/375107/lantern.TXT)

txt的后缀竟然严格要求是大写....这是什么鬼....

**Comment by iswhat** [comment]
请尽快答复，谢谢

**Comment by ErrorByError** [comment]
虽然我不是工作人员，但我还是想说，Here is not china lantern github project. 中文版Github project URL: https://github.com/getlantern/forum/issues .

**Comment by iswhat** [comment]
@ErrorByError 谢谢您的提醒，我没有注意到有提醒周围有关于中文project或者英文project的提示。
我做了一系列尝试，现在好了很多：包括，reset winsock 目录，恢复各个浏览器的初始设置，卸载lantern并删除AppData\Roaming\Lantern目录，后重启计算机，再重装Lantern，目前基本正常，我就不删了，留给其他走错的人看一下吧

**Comment by ErrorByError** [comment]
好的

**Comment by p3rcya** [comment]
我这里关闭了，以后请发到中文论坛，谢谢 https://github.com/getlantern/forum/issues
