### ISSUE TITLE
Not working continuously

### ISSUE THREAD

**Issue by jindongwang** [getlantern/lantern#5065]
It's not working for two days. I'm using pro! Where does all my money go?
[lantern.txt](https://github.com/getlantern/lantern/files/375539/lantern.txt)

**Comment by myleshorton** [comment]
Is it working for you now @jindongwang?

**Comment by jindongwang** [comment]
Works now in my home computer , I'll check it in the lab after vocation.Thanks for supporting.

--  
祝好  
王晋东


在 2016年7月24日 at 14:46:31, Myles Horton (notifications@github.com(mailto:notifications@github.com)) 写到:

**Comment by myleshorton** [comment]
OK great @jindongwang! Please let us know if you ever have issues with it.

**Comment by myleshorton** [comment]
Pro is also still very new, so we are improving it rapidly -- we should have a new version out quite soon, and you'll ultimately be auto-updated to that version.

**Comment by jindongwang** [comment]
Hi, I've checked lantern on my working computer, but it doesn't work well.


祝好
王晋东
开 2016/7/25 13:04:59, Myles Horton <notifications@github.com> 写到:
OK great @jindongwang [https://github.com/jindongwang]! Please let us know if you ever have issues with it.
