### ISSUE TITLE
Chrome encounters connection reset

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5072]
I've seen many users reports about this issue. They cannot use Chrome with Lantern but they sometimes can use other browsers. 

![image](https://cloud.githubusercontent.com/assets/20512438/17067375/4cf6bc4a-5000-11e6-86ec-25890d5d1177.png)

log
https://github.com/getlantern/forum/issues/754#issuecomment-234463138

The user reseted Chrome but still cannot use it

**Comment by p3rcya** [comment]
more log https://github.com/getlantern/forum/issues/762#issuecomment-234462346

**Comment by p3rcya** [comment]
More log

**Comment by myleshorton** [comment]
Interesting @p3rcya. Do they have any extensions installed? That's been the main issue in the past.

**Comment by myleshorton** [comment]
The only other thing that comes to mind is DNS prefetching. For these users, does Lantern fail all the time or just some of the time?

**Comment by p3rcya** [comment]
One said he uninstalled all extensions and still encountered this issue

**Comment by myleshorton** [comment]
on all sites or just some?

**Comment by p3rcya** [comment]
all in chrome. He said he disabled all extensions not uninstall. I just requested him to reset Chrome and see how it goes

**Comment by p3rcya** [comment]
I was looking through the old issues. This guy reset Chrome but still cannot access the Internet https://github.com/getlantern/lantern/issues/4404

**Comment by p3rcya** [comment]
Also this old conversation @myleshorton you participated https://github.com/getlantern/lantern/issues/3262

**Comment by myleshorton** [comment]
right but do all sites fail for him in chrome or just some @p3rcya? does he have xunlei installed?

**Comment by p3rcya** [comment]
Some have. I asked them to test more

**Comment by oxtoacart** [comment]
Could this be related to #4902?

**Comment by p3rcya** [comment]
It might be due to Xunlei. Investigating.

**Comment by p3rcya** [comment]
Confirmed. Users able to use Lantern after uninstalling Xunlei Speed. 
Closing in favor of https://github.com/getlantern/lantern/issues/4532
