### ISSUE TITLE
Balancer: adjust dial timeout based on metrics

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#5073]
Especially on multiple servers case, long timeout would slow down new connections if a server doesn't behave well. There is simply no one standard fits for everyone.

1. Start with a relatively large timeout.
2. Subsequently, use a relative timeout, say, `3*avgDialTime`, for each dialer.

**Comment by myleshorton** [comment]
I love the dynamic timeout idea @fffw -- moving this to TODO
