### ISSUE TITLE
Cannot disable auto-run on Mac system start up

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5074]
User reported that after de-selecting auto-run on start-up, Lantern will still auto-run

**Comment by oxtoacart** [comment]
What may be happening here is that when a new version of Lantern installs, it reenables auto-run for some reason (I've seen this happen to me before).

**Comment by p3rcya** [comment]
closed in favor of https://github.com/getlantern/lantern/issues/5087
