### ISSUE TITLE
proxied: not switch to "chained only mode" if chained is much slower than fronted

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#5076]
Say, if chained request takes more than 2x time than fronted request, we keep using current fetcher. It can make things much better when the network quality between client and its proxy is bad.

**Comment by fffw** [comment]
An alternative is to switch only after N successful requests from chained. It creates a lot of unnecessary calls via DDF.

**Comment by aranhoide** [comment]
As long as chained works at all I'd just use that, at least for stuff that is not latency critical, like config fetching.  DDF traffic costs us a lot more.

**Comment by fffw** [comment]
It does affect pro-server requests initiated from Lantern UI, which is sensitive to latency. I think @aranhoide you brought up an idea that we can switch config-server requests from using `ParallelPreferChained` to `ChainedThenFronted`, which would save a lot of DDF requests.

**Comment by myleshorton** [comment]
What's the status of this one @fffw?

**Comment by fffw** [comment]
@myleshorton PR available at https://github.com/getlantern/lantern-pro/pull/97
