### ISSUE TITLE
[mobile] Add Link to Lantern desktop screen

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#5078]
Since some users are not receiving the emails from this screen, we also need to provide them with a link that they can use to get lantern for desktop.  This is the mobile version of ticket #4755 

@percy how does this look to you?

@atavism just a note, we are removing the illustration on this page
![menu-spec-sheet_7-19-16](https://cloud.githubusercontent.com/assets/7864729/17068543/7d3894c2-501f-11e6-86df-e22122735af2.png)

**Comment by p3rcya** [comment]
In China, the link should be https://github.com/getlantern/mirror

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #55](https://github.com/getlantern/lantern-internal/issues/55) via [**ZenHub**](https://www.zenhub.com/)
