### ISSUE TITLE
Lantern专业版无法登录

### ISSUE THREAD

**Issue by spangrid** [getlantern/lantern#5080]
没找到客服邮箱，只能提交在这。大约两周前我购买了专业版，在今天重做系统之后，我发现我注册的邮箱账户不能被识别，显示用户未找到。

**Comment by hujianxin** [comment]
你好，请问问题解决了吗？

**Comment by Joshhzhao** [comment]
今天购买了专业版，登录的时候输入邮箱地址提交，下一步没法输入收到的密码，点了密码区域没有反应，如何解决？

**Comment by spangrid** [comment]
没有解决

**Comment by orbancanon** [comment]
@spangrid 你注册的邮箱是多少？我们查一下。如果是支付宝付款的话，还请给一下支付宝帐号。可以发邮件给我orbancanon@gmail.com，如果担心我是假的可以发给support@getlantern.org

@Joshhzhao 你是说密码区域没办法点是吧？关了重新试呢？如果每次都如此，请把你的浏览器版本号，还有Lantern的版本号告诉我。

**Comment by orbancanon** [comment]
@spangrid 已经回复你

**Comment by orbancanon** [comment]
@Joshhzhao 邮件已收到。暂时不能复现你遇到的情况，但我们会继续查找原因。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
