### ISSUE TITLE
使用代理repo init -u 总是time-out

### ISSUE THREAD

**Issue by xusx1024** [getlantern/lantern#5081]
Troubleshooting network issues

When downloading from behind a proxy (which is common in some corporate environments), it might be necessary to explicitly specify the proxy that is then used by repo:

$ export HTTP_PROXY=http://<proxy_user_id>:<proxy_password>@<proxy_server>:<proxy_port>
$ export HTTPS_PROXY=http://<proxy_user_id>:<proxy_password>@<proxy_server>:<proxy_port>

像代理这些id，pwd，server，port，怎么填写，从哪里可以得到。
谢谢。

**Comment by xusx1024** [comment]
一整天过去了，没有人回答我，付费之后，没有服务了吗？

**Comment by fffw** [comment]
@xusx1024 please set them to `localhost:8787`

**Comment by svhero658** [comment]
你看pac文件可以找到地址

**Comment by xusx1024** [comment]
@fffw <proxy_user_id>:<proxy_password> But  these 2 values, how can I get ? plz answer  as soon as you can .Thank you!

**Comment by xusx1024** [comment]
@svhero658 我并没找到pac文件，请问是在哪个文件夹下呢？谢谢。

**Comment by fffw** [comment]
@xusx1024 no user_id nor password is required. Search "HTTPS_PROXY lantern" would give you lots of instructions shared by other users.

**Comment by xusx1024** [comment]
@fffw it worked.you're right,there are many answers on Google.Thanks you.
