### ISSUE TITLE
支付宝付款不成功

### ISSUE THREAD

**Issue by hujianxin** [getlantern/lantern#5083]
There was an error in the payment process

**Comment by hujianxin** [comment]
上面的是出错信息

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
