### ISSUE TITLE
Allow device linking via QR codes

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5086]
Device linking has proven to be one of the most fraught aspects of Lantern. Using QR codes will make this significantly easier on mobile.

**Comment by myleshorton** [comment]
This library looks promising:

https://davidshimjs.github.io/qrcodejs/

**Comment by atavism** [comment]
This looks promising for Android https://github.com/zxing/zxing

**Comment by myleshorton** [comment]
Not implementing for now.

**Comment by p3rcya** [comment]
@myleshorton Hmm? I think this is a good idea and we should definitely implement it in the future. What do you think?

**Comment by myleshorton** [comment]
I think with the short code it's not really necesarry @p3rcya -- would probably take longer to scan the code than to just type it in. We originally added this when the code was going to be much longer.
