### ISSUE TITLE
[mobile] remove "share" menu option

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#5093]
@p3rcya raised this here in #4871 but it was closed in favor of opening separate tickets for desktop and mobile.

Referral system is a sharing system, and we would prefer users share that way, removing this option will make things less confusing for users.

**Comment by p3rcya** [comment]
The button doesn't work on 3.1.4. So please remove it before release  @atavism

**Comment by myleshorton** [comment]
Was this working in earlier 3.1.x versions @p3rcya?

**Comment by fffw** [comment]
@myleshorton @atavism tried 3.1.3 from Google Play. "Share" menu doesn't bring up anything.

**Comment by p3rcya** [comment]
@myleshorton I don't remember it. But this should be removed completely anyway

**Comment by myleshorton** [comment]
cool thanks @fffe and @p3rcya

**Comment by p3rcya** [comment]
This is removed on mobile
