### ISSUE TITLE
[desktop] remove "share" menu option

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#5094]
@p3rcya raised this here in #4871 but it was closed in favor of opening separate tickets for desktop and mobile.

Referral system is a sharing system, and we would prefer users share that way, removing this option will make things less confusing for users.

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #898](https://github.com/getlantern/lantern-internal/issues/898) via [**ZenHub**](https://www.zenhub.com/)
