### ISSUE TITLE
too many open files apparently with obfs4

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5095]
While I haven't looked at all the logs, all the ones I've seen are hitting too many open files when running the client side of obfs4:

```
Unable to dial via (trusted) chained proxy at 139.162.8.110:48476 [obfs4] to connect://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 139.162.8.110:48476 [obfs4]: dial tcp 139.162.8.110:48476: socket: too many open files on pass 0...continuing
```

**Comment by myleshorton** [comment]
FYI @oxtoacart this is the top error in loggly right now.

**Comment by fffw** [comment]
@myleshorton It's caused by one single client

**Comment by myleshorton** [comment]
yeah just seeing that too -- logging that issue actually @fffw -- looks like there was a regression with the borda stuff and filtering duplicate messages to loggly.

**Comment by myleshorton** [comment]
Logged here:

https://github.com/getlantern/lantern/issues/5096

**Comment by myleshorton** [comment]
Moving this one to the backlog.

**Comment by myleshorton** [comment]
Should be all set.
