### ISSUE TITLE
No longer filtering duplicate errors sent to loggly

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5096]
Looks like there was a regression here. This significantly throws off the log counts but also dramatically increases the traffic to loggly. The top error right now, for example, is too many open files, but there are 3 total IPs experiencing that error!

FYI @oxtoacart and @fffw

**Comment by myleshorton** [comment]
Yeah this is pretty bad. Here are the error counts by IP for 3.0.7:

![image](https://cloud.githubusercontent.com/assets/1143966/17202088/d9dbf982-544b-11e6-850d-48936fe96a10.png)

**Comment by p3rcya** [comment]
probably causing https://github.com/getlantern/lantern/issues/5058 which is a major complaint

**Comment by fffw** [comment]
I commented at https://github.com/getlantern/lantern/issues/5089#issuecomment-235770491 that we can introduce rate limiting (like 1 event per 5 min) at client to avoid such problem. Deduplication is sensitive to format change.

**Comment by myleshorton** [comment]
I doubt it's related to #5058 @p3rcya but definitely an issue. I don't quite understand why deduplication is so hard @fffw. We used to just do it on the message itself. Can't we still do that?

**Comment by fffw** [comment]
@myleshorton we need to make sure the messages don't have unique content, such as proxy IP or origin site, but the logging code is scattered over all packages. If errors are interleaved, say, error A triggers error B, then another A followed by another B, then we need a cache to deduplicate.

**Comment by oxtoacart** [comment]
I'll work on this today.
