### ISSUE TITLE
Testdroid: Generate automatic report summary for new builds

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#5100]
In addition to uploading and running the app via Testdroid, a report summary will be generated that lists screenshots from a group of predetermined devices (using Appium).

**Comment by atavism** [comment]
This may put us over, but I'm going to add this as a task for myself to the current Sprint since I only had a few UI tickets to work on already.

**Comment by myleshorton** [comment]
Sounds good @atavism!
