### ISSUE TITLE
[mobile] Get lantern desktop screen changes

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#5101]
Hey @atavism this is semi related to the new token stuff.  we are eliminating the email delivery of the link.   So we will add back the graphic since we have room now, and just include the link, copy has changed too.  
![newlantern-desktop](https://cloud.githubusercontent.com/assets/7864729/17227365/f8f4ec62-54db-11e6-9ea3-9566150b498f.png)

**Comment by p3rcya** [comment]
In China, the link should be https://github.com/getlantern/mirror

**Comment by Derekf5** [comment]
@atavism @myleshorton can we get this change into the next sprint as well?

**Comment by Derekf5** [comment]
hey @atavism @myleshorton, @joesis is implementing the desktop version of this change, so would be good to knock this one out soon if possible.

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #896](https://github.com/getlantern/lantern-internal/issues/896) via [**ZenHub**](https://www.zenhub.com/)
