### ISSUE TITLE
[Desktop] Get Android Version screen update

### ISSUE THREAD

**Issue by carsonefv** [getlantern/lantern#5102]
Remove email field from this screen, and adjust formatting and sizing:
See the end of the ticket

**Comment by p3rcya** [comment]
In china, the URL should be https://github.com/getlantern/mirror

**Comment by Derekf5** [comment]
@myleshorton same as #5101 would be great to get this knocked out in the next sprint

**Comment by p3rcya** [comment]
@joesis  I just saw the comment on https://github.com/getlantern/forum/issues/2019#issuecomment-265083901 it's probably good just to implement this rather than fix the email delivery

**Comment by joesis** [comment]
When scanning a QR code via WeChat, user needs to copy the link and paste it to the browser. Probably still better than email.

**Comment by p3rcya** [comment]
@joesis I think maybe we just do without the QR code as most users will just scan via wechat. Link only would be better.

**Comment by carsonefv** [comment]
@joesis @p3rcya let me know if it would be better to redesign this screen without the qr code

**Comment by p3rcya** [comment]
@carsonefv Yes, please do. QR code is more complicated than useful from we chat scanning.

**Comment by carsonefv** [comment]
ok here's an updated design without the QR Code @p3rcya @joesis 

Question - are we still planning to use the github link https://github.com/getlantern/mirror? in China? What link are we using for other countries?

<img width="924" alt="screenshot 2016-12-06 16 05 08" src="https://cloud.githubusercontent.com/assets/4400763/20943691/9e056f66-bbce-11e6-9d95-17db5ab53a22.png">

**Comment by p3rcya** [comment]
@carsonefv For China, yes. 

@carsonefv @Derekf5 Remember a few weeks back, I request translation of this page https://github.com/getlantern/forum/issues/1748  into all languages? I'll create new pages once the translation is done. Every country will get his own page

**Comment by carsonefv** [comment]
@joesis Actually for the screen we can just add the new text and link underneath the illustration thats on the current screen that's already implemented - I can't find that file right now but will update with those specs soon

@p3rcya yes, we can have this on the lantern wiki section right? https://github.com/getlantern/lantern/wiki/download

**Comment by p3rcya** [comment]
@carsonefv I think it's better we directly have specific country links in the software rather than requires one more click from the users (especially considering github can be extremely slow to load in some areas.)

**Comment by carsonefv** [comment]
@joesis here's the updated screen with illustration:
<img width="679" alt="screenshot 2016-12-07 10 40 22" src="https://cloud.githubusercontent.com/assets/4400763/20974254/966b69f4-bc69-11e6-982e-19ed6fc79629.png">


@p3rcya Yes - my idea was to have separate pages on the Lantern wiki for each language, for instance this is the english page: https://github.com/getlantern/lantern/wiki/welcome, 

- @Derekf5 can you help with getting this text into transifex?
- I just created a page for Chinese, https://github.com/getlantern/lantern/wiki/Chinese-Download-Page can you edit this page @p3rcya?  

- For any region that we do not have a page for we should send them here for now: https://github.com/getlantern/lantern/wiki/download

**Comment by p3rcya** [comment]
@carsonefv 

1.Please see the version here https://github.com/getlantern/forum/issues/1748 it has alternative download and cloud drive download which are important. Can you translate that as well?

2. Chinese version has a forum. So I'd rather promote the forum link directly, rather than this URL that is 50% long and impossible to remember.

3. Agree

**Comment by carsonefv** [comment]
ok thanks @p3rcya we will get the text from getlantern/forum#1748 translated

**Comment by Derekf5** [comment]
@carsonefv @p3rcya the file is up on Transifex now.  I will keep an eye on it, and let you know whenever we get a new language done.

**Comment by myleshorton** [comment]
I'm a little vague on what we're trying to accomplish with this one guys. Just promote the mobile version from desktop?

**Comment by p3rcya** [comment]
No. we have this screen since forever. But now the screen is email users,
which is sometimes blocked not delayed. A link won't have this problem.

**Comment by carsonefv** [comment]
@myleshorton can we get this into the next sprint?

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #897](https://github.com/getlantern/lantern-internal/issues/897) via [**ZenHub**](https://www.zenhub.com/)
