### ISSUE TITLE
180买的pro 请问这是什么问题

### ISSUE THREAD

**Issue by liushanqwe** [getlantern/lantern#5103]
速度从来就没超过150kb/s       国内速度6 7M/s     电信用户    不知道是软件问题 还是我网络的问题   
 如果只有这速度   真心180 可以打水漂了

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送，所以请稍安勿躁。
