### ISSUE TITLE
 i/o timeout when a blocked site is not detected as blocked 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5109]
When accessing g.e-hentai.org,   「read tcp 192.168.1.114:2426->139.59.232.170:12608: i/o timeout」 https://github.com/getlantern/forum/issues/866

and template broken when accessing scmp.com because of CSS files on i-scmp.com

**Comment by myleshorton** [comment]
That's an IO timeout to one of our proxies @p3rcya not to g.e-hentai.org. I just added i-scmp.com to the default list of proxied sites. That will go out the next time we update the cloudmasters.

**Comment by p3rcya** [comment]
@myleshorton User still reported the same problem

**Comment by p3rcya** [comment]
And users reported that it solved by enabling proxy all

**Comment by myleshorton** [comment]
The user may be having an issue, but at the very least the description is wrong. Again, that site will be added to the default list the next time we update the cloudmasters.
