### ISSUE TITLE
请问付费了专业版，但是为什么邮箱内收不到验证码？

### ISSUE THREAD

**Issue by qianshuiyu** [getlantern/lantern#5113]

**Comment by godxkey** [comment]
你已经付费了吗？
这么豪华，关于墙的问题，你付费也许没成功，
然后邮箱的邮件的验证码被墙了，然后就没收到了，
关于国外的这个的墙的问题，很头痛，基本上失败的几率很高，
所以这个类型的东西，最好要有一个国外的邮箱，然后跨越墙的距离，我这个东西也没试过，
具体的原因可以找付费的时候的提示看看有没有客服或者沟通的邮箱的地址。

**Comment by Jianghao** [comment]
我也遇到同样的问题，无法接收到验证码

**Comment by p3rcya** [comment]
这个是国内邮箱的问题，我们会支持修改邮箱

**Comment by watchzerg** [comment]
我购买了专业版，故意没有使用gmail，而用了hotmail。
现在是：输入邮箱之后，邮箱收到了多份验证码，但是chrome一直在转圈圈，无法输入验证码。

**Comment by p3rcya** [comment]
@watchzerg 请上传截图并请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by zuoxd7749** [comment]
我用的qq邮箱，没有收到验证码
