### ISSUE TITLE
DNS answer is fucked, wish lantern could provide a dns proxy service, please.

### ISSUE THREAD

**Issue by wwqwwqwd** [getlantern/lantern#5115]
Look at this:

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40301
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         2274    IN      A       37.61.54.158

;; AUTHORITY SECTION:
google.com.             27128   IN      NS      ns3.google.com.
google.com.             27128   IN      NS      ns2.google.com.
google.com.             27128   IN      NS      ns4.google.com.
google.com.             27128   IN      NS      ns1.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.         199924  IN      A       216.239.32.10
ns2.google.com.         200504  IN      A       216.239.34.10
ns3.google.com.         201096  IN      A       216.239.36.10
ns4.google.com.         202110  IN      A       216.239.38.10

;; Query time: 6 msec
;; SERVER: 61.177.7.1#53(61.177.7.1)
;; WHEN: Tue Aug 02 17:11:40 CST 2016
;; MSG SIZE  rcvd: 195

ANSWER SECTION is obviously fucked whereby the additional section is correct.

Will lantern provide dns proxy service someday so I can use it on debian?

**Comment by myleshorton** [comment]
To be clear @wwqwwqwd you're saying the ANSWER section is DNS poisoned right:

```
;; ANSWER SECTION:
www.google.com. 2274 IN A 37.61.54.158
```

Lantern runs as an HTTP proxy, so the DNS resolution part happens on the proxy not on the client. So if you actually try to browse to google.com, it will bypass the DNS poisoning because there's no client-side DNS resolution.

**Comment by wwqwwqwd** [comment]
Thanks for replying @myleshorton.

I'm currently using dnscrypt-proxy and unbound to fight against dns poisoning, see https://dnscrypt.org/.

The thing is that free dnscrypt-proxy servers perform bad visited form mainland china, some are blocked and others will be blocked sooner or later I'm afraid.

I will be grateful if lantern pro can provide dns service, by running a dns server at 127.0.0.1 and get actual dns data through custom protocol which will not be poisoned. 

Maybe not together with lantern pro, but another non-free feature.

**Comment by wwqwwqwd** [comment]
It turns out to be a chrome problem.

Found solutions here:
https://www.chromium.org/developers/design-documents/network-stack/socks-proxy
https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy

I didn't figure out the detail of dns resolution, sorry~
