### ISSUE TITLE
[mobile] Switch link code sequence to have pro user perform the linking

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5117]

**Comment by atavism** [comment]
I ended up improvising some of the UI changes for this so it would be good to review with @Derekf5 tomorrow when he's back from vacation.

**Comment by myleshorton** [comment]
Cool yeah I did the same on desktop @atavism

**Comment by Derekf5** [comment]
Hey @myleshorton @atavism let me know where i can see these new changes.

**Comment by Derekf5** [comment]
Here are the two screens that are required with this change. @myleshorton @atavism 
![new-linking-code](https://cloud.githubusercontent.com/assets/7864729/17378650/afe59174-598c-11e6-877f-744555a12ee9.png)
![link-input](https://cloud.githubusercontent.com/assets/7864729/17378673/d79d5a62-598c-11e6-96c6-cc24af9aae05.png)

**Comment by atavism** [comment]
Thanks, @Derekf5! That "authorize device for Pro" text looks wrong. It's on the 'Authorize Device for Pro' screen *on your existing* Pro device, right?

**Comment by Derekf5** [comment]
correct! thanks @atavism
