### ISSUE TITLE
error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leslie5803** [getlantern/lantern#5118]
lantern/bin/lantern: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by fffw** [comment]
@leslie5803 You can either install the `libappindicator3` package (preinstalled on Ubuntu) or build headless Lantern manually via `HEADLESS=true make ...`

**Comment by leslie5803** [comment]
I installed the `libappindicator3` and the lantern is running well.

**Comment by leslie5803** [comment]
@fffw Thanks ! I installed the `libappindicator3` and lantern works well

**Comment by fffw** [comment]
Cool @leslie5803

**Comment by kolenj** [comment]
@fffw nice

**Comment by syncher-bin** [comment]
Install the ``libappindicator3``
* step 1
```
$  apt-cache search libappindicator3  gir1.2-appindicator3-0.1 - Typelib fi
gir1.2-appindicator3-0.1 - Typelib files for libappindicator3-1
```
* step 2
```
sudo apt-get install -y libappindicator3-1
```

done!
