### ISSUE TITLE
专业版根本连不上网

### ISSUE THREAD

**Issue by wongzhichao** [getlantern/lantern#5122]

**Comment by wongzhichao** [comment]
偶尔连接上速度也是很慢，怎么破啊

**Comment by CPCer** [comment]
积极反馈。。他们还在公测，估计困难不少

**Comment by Jianghao** [comment]
很遗憾，我用了专业版的，买了一年的账号，结果发现反而上不了google了。
之前免费阶段还可以上Google。
我也不知道原因是什么？

**Comment by p3rcya** [comment]
@wongzhichao @Jianghao 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by jindongwang** [comment]
Same problem here

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by p3rcya** [comment]
已经修复了。请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢各位的耐心等待！
