### ISSUE TITLE
How to quit lantern on Mac OS?

### ISSUE THREAD

**Issue by playgithub** [getlantern/lantern#5125]
As title.
Way to disable lantern in Mac OS is an alternative.
Thanks.

**Comment by fffw** [comment]
@playgithub Doesn't `Quit Lantern` work?

![image](https://cloud.githubusercontent.com/assets/10410437/17462431/7b957a64-5cdf-11e6-9cc8-54738a554679.png)

**Comment by playgithub** [comment]
How can ignore it?
Really new to MacOS.
Thanks.
