### ISSUE TITLE
Change the words in the first bullet point from "Authorize Device for Pro" to "Add Device"

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern#5132]
The user has to click on "Add Device" link in the pro account. So change the words of the first point accordingly in the below screen.

![image](https://cloud.githubusercontent.com/assets/11394369/17493077/9e0b0ddc-5d63-11e6-9c2b-b55c8fcd9540.png)

**Comment by p3rcya** [comment]
@sunshine19090 Hmm? If a device is already in Pro, it should be "Add device". While if it's not in Pro, it should be "Authorize device" as in the screen.

**Comment by p3rcya** [comment]
According to https://github.com/getlantern/lantern-internal/issues/77, I guess we're using "Add Device" in free device as well.

**Comment by myleshorton** [comment]
Yeah that seems wrong to me @p3rcya -- do you agree?

**Comment by p3rcya** [comment]
@myleshorton @sunshine19090 Only Pro should change

**Comment by sunshine19090** [comment]
@myleshorton @p3rcya I wasn't talking about the title. I was saying that the check point wording is wrong. Since we have "Add device" side menu in the pro UI and not "Authorize device for pro", we should change the first bullet point to indicate that.

**Comment by myleshorton** [comment]
Should be all set @sunshine19090!
