### ISSUE TITLE
我的专业版怎么显示没有该用户？

### ISSUE THREAD

**Issue by shjanken** [getlantern/lantern#5133]
昨天重装系统之后安装了蓝灯，登录专业版的时候，输入邮箱显示没有该用户？
我买了一年的专业版啊

**Comment by p3rcya** [comment]
请问邮箱是否错误？注意大小写

**Comment by orbancanon** [comment]
@shjanken 你的邮箱是多少呢亲？我们后台给查查。

**Comment by Christophashjz** [comment]
同样的问题

**Comment by orbancanon** [comment]
刚刚后台修复了。@shjanken @Christophashjz 你们再试试

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
