### ISSUE TITLE
专业版无法多设备登录

### ISSUE THREAD

**Issue by TomCat2011** [getlantern/lantern#5134]
购买时号称账号可以最多支持3个设备，但在第二台电脑上使用专业版账号登录时，在点击发送验证码后网页上就一直有转圈圈的动画（最新版的IE跟Chrome都试过），实际上我的网易邮箱早已收到了验证码。（第一台电脑此时已经退出lantern了）。需要等待动画自动超时，但是还是无法输入验证码。

**Comment by TomCat2011** [comment]
补充下，我用的lantern版本是最新的3.0.7

**Comment by p3rcya** [comment]
第一台设备还是在登陆状态么？如果是的话，请不要退出

**Comment by TomCat2011** [comment]
你好！按照你的说法，又试了下。

在第一台电脑已登录专业版的情况下，在第二台电脑上登录专业版账号，还是在邮箱已经收到验证码的情况下，无法输入验证码。

请问在网页上点击“发送电子邮件”按钮后弹出的旋转动画满足什么条件才会消失？（除了自动超时外）在消失后需满足什么条件才允许我输入验证码？

P.S.在网页发送验证码的过程中（也就是旋转动画一直持续的过程中）我的网易邮箱会收到多条不同的验证码。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢 

我们会发布新版解决这个问题

**Comment by TomCat2011** [comment]
[lantern.txt](https://github.com/getlantern/lantern/files/408171/lantern.txt)

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
