### ISSUE TITLE
专业版连不上，主界面转圈圈，北京联通（已解决）

### ISSUE THREAD

**Issue by watchzerg** [getlantern/lantern#5136]
之前一直在用免费版，最近免费版连不上了。家里多台电脑，都是免费版lantern，都显示“本月剩余0MB”且连不上。

昨天（8月8日）在公司的网络里（会自动对部分网站翻墙）用mac购买了lantern专业版。
为了方便收验证码，购买时输入的是hotmail邮箱。

回到家里拿其中一台PC做实验（所以肯定没超过专业版lantern的机器数量限制的）：在win10中，使用lantern3.0.7打开”专业版登录“，输入hotmail邮箱，然后就无限转圈圈了。
然后发现我的hotmail里反复收到了很多个验证码，但是因为lantern主界面里面一直在转圈圈，所以我无法输入验证码。
怀疑是邮件发成功了，响应的时候被掐了（但这个时候即使没有收到“验证码发送成功”的响应，我觉得也应该留个兜底口子让我把验证码输入到lantern才对吧？）是不是北京联通把我给干掉了？

我表示一点也不着急，希望留给维护团队足够的时间去排查问题。
（不过，如果万一最终发现真的是我被北京联通屏蔽了，能不能给我退款捏……因为我一天都没用上……）

---
### 场景一：家里（北京联通）
8月8日，无法使用lantern-pro
显示“本月剩余免费流量0MB”，点击“登录专业版”之后输入邮箱，主界面变暗进入“转圈圈”状态。
邮箱收到多个验证码，但是无法在lantern主界面输入。
日志如下：

> Aug 08 22:25:30.893 - 6m22s DEBUG flashlight.client: handler.go:100 Could not dial Still unable to dial connect://www.google.com.sg:443 after 3 attempts [error=Could not dial Still unable to dial connect://www.google.com.sg:443 after 3 attempts error_op= error_type=errors.Error op=proxy origin_host=www.google.com.sg origin_port=443 root_op=proxy user_agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36]
DEBUG flashlight.client: handler.go:100   at github.com/getlantern/flashlight/client.(*Client).intercept (handler.go:100)
DEBUG flashlight.client: handler.go:100   at github.com/getlantern/flashlight/client.(*Client).ServeHTTP (handler.go:41)
DEBUG flashlight.client: handler.go:100   at net/http.serverHandler.ServeHTTP (server.go:2087)
DEBUG flashlight.client: handler.go:100   at net/http.(*conn).serve (server.go:1474)
DEBUG flashlight.client: handler.go:100   at runtime.goexit (asm_386.s:1585)
DEBUG flashlight.client: handler.go:100 Caused by: Still unable to dial connect://www.google.com.sg:443 after 3 attempts

[lantern.TXT](https://github.com/getlantern/lantern/files/408330/lantern.TXT)
---
### 场景二：公司网络环境（自带部分网站翻墙）
8月9日，可以正常使用lantern-pro
（因为就是在公司购买的，所以默认就登录了lantern-pro）

1，试着traceroute了下www.google.com.sg：DNS正常，卡在了联通的一个IP上
![lantern-traceroute](https://cloud.githubusercontent.com/assets/1014217/17506685/941327ee-5e3d-11e6-9a58-562043310142.png)

2，pro界面，一切正常
![lantern-pro-ui](https://cloud.githubusercontent.com/assets/1014217/17505265/a89e2796-5e32-11e6-91a6-652443f34e55.png)

3，尝试访问twitter正常，而且根据lantern日志可以看到确实是走了lantern的通道。
![lantern-log](https://cloud.githubusercontent.com/assets/1014217/17505297/eae8365a-5e32-11e6-886f-8b5be2ed7513.png)

所以结论是在公司网络环境下使用lantern-pro是没问题的。

另外发现一点：
即使在公司网络环境下，如果我不开lantern-pro，那么我编辑这个issue的时候，也无法上传任何文件（txt/png等），打开lantern-pro就能上传了（观察流量，也确实发现又部分github的子域名的流量走了lantern）

---
### 场景三：家里（北京联通）
8月10日，今天又突然可以了，是这样的：
今天早上7点钟打开lantern（依然是免费版，还未登录），突然发现chrome的gmail图标亮了。仔细一看，免费版lantern提示“本月剩余流量793MB”，twitter也可以打开了。
然后我赶紧登录专业版，成功，目前使用良好。

---
### 猜测
之前显示“本月免费流量用尽”，就完全连不上，我连登录专业版的机会都没有。
现在有了一点免费流量之后，登录专业版成功（后续使用是否正常，我会观察下）。

@getlantern团队： 建议可以排查一下“免费流量用尽之后，尝试登录专业版”这种场景——或者是否考虑把“登录lantern-pro”相关的域名设置到lantern白名单里，不占用流量配额，不使用20KB的流控。
@其它跟我一样登录不上专业版的朋友： 我这次也是莫名其妙好的，建议等一下“免费流量重置”的日子，然后赶紧尝试登录专业版试试。

**Comment by p3rcya** [comment]
lantern主界面里面一直在转圈圈 能上传截图下么？

**Comment by p3rcya** [comment]
另外请放心，我们一定会解决你的问题的。

**Comment by TomCat2011** [comment]
跟我反映的问题是一样的，无法多设备登录使用。

**Comment by watchzerg** [comment]
@p3rcya 多谢多谢，白天上班不方便，我晚上回去截，顺便ping/tracert一下www.google.com.sg把结果发上来。

@TomCat2011 貌似不一样哦，我的日志里主要是连不上“www.google.com.sg:443”，应该还没到鉴权的步骤。
