### ISSUE TITLE
重装系统后专业版邮箱无法验证？

### ISSUE THREAD

**Issue by Christophashjz** [getlantern/lantern#5137]
重装系统后，登陆专业版，输入邮箱后显示“Bad input: request missing Email”

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by Christophashjz** [comment]
一月前购买的全年专业版，可以正常使用，昨天我的电脑重装系统后，再用lantern专业版尝试登陆时显示missing email,截图如下，
![image](https://cloud.githubusercontent.com/assets/10382069/17546065/eb18154c-5f12-11e6-863a-d3db9d4c83fe.png)
[lantern.txt](https://github.com/getlantern/lantern/files/410537/lantern.txt)

**Comment by orbancanon** [comment]
@Christophashjz 从日志里看不出来你用的版本，但如果是3.0.7以下的话，请在[这里](https://github.com/getlantern/forum/#蓝灯lantern最新版本下载)下载最新版。之前版本有个BUG会导致这个问题。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
