### ISSUE TITLE
user link not configured?

### ISSUE THREAD

**Issue by hitzhangjie** [getlantern/lantern#5141]
I bought a Pro version, but when I input email, the page says "user link not configured", but why?

lantern version: 3.0.7-2.x86_64
os: CentOS 7

**Comment by p3rcya** [comment]
What's your email?

**Comment by hitzhangjie** [comment]
@p3rcya my email is hit.zhangjie@gmail.com

**Comment by orbancanon** [comment]
@hitzhangjie should be fixed. Please try again.

**Comment by tsintian** [comment]
I have the same problem. my email is： tsintian@hotmail.com , please help me solve it, thanks!

**Comment by myleshorton** [comment]
what version of lantern are you using @tsintian? are you sure that's the email address you entered when you purchased?

**Comment by p3rcya** [comment]
@tsintian Can you use the latest version https://github.com/getlantern/forum

**Comment by tsintian** [comment]
Yes. mine is 3.0.6. I have been always using the email to accept the identify code before I update it to version 3.1.x and it works well.  But now I have tried many times and failed to use it.@myleshorton

**Comment by tsintian** [comment]
I can use the latest version, but I can not authorize my device for pro.@p3rcya

**Comment by tsintian** [comment]
My operating system is ubuntu 16.04

**Comment by uaalto** [comment]
@tsintian can you please send me your logs of the device you want to authorize? https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
