### ISSUE TITLE
link new device via old devices, it's a bad design

### ISSUE THREAD

**Issue by hitzhangjie** [getlantern/lantern#5145]
I really don't know which computer I will use in my School, Linking new device via old devices, it's a bad design.

**Comment by p3rcya** [comment]
I totally agree with you.

**Comment by cattingdale5** [comment]
Yes ! I have to have old device to link new device ??? And input some code ??? So STUPID. Why does Lantern not use username, password like every other service.

**Comment by p3rcya** [comment]
@myleshorton Can you check this?

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
