### ISSUE TITLE
Pro can not work

### ISSUE THREAD

**Issue by jindongwang** [getlantern/lantern#5147]
I'm using lantern pro, but it cannot work a bit on my Win 10 desktop...I've tried the pro version and normal version, but it doesn't work.
Here is the log file:
[lantern.log.txt](https://github.com/getlantern/lantern/files/412632/lantern.log.txt)
It's been like this for many days...

**Comment by myleshorton** [comment]
Hi @jindongwang I assume you've shut off all extensions and removed Xunlei? If not, can you try those. What browser are you using?

Finally, have you tried the latest 3.1.1 version just released yesterday (most of the improvements were in 3.1.0 released just one day prior)? That's available from the links here:

https://github.com/getlantern/lantern

**Comment by myleshorton** [comment]
Never mind -  I can see in your logs that you're using the new version.

**Comment by myleshorton** [comment]
It definitely looks like there's some traffic successfully passing through Lantern from your logs. What happens when you try to visit blocked web sites @jindongwang?

**Comment by jindongwang** [comment]
Thank you @myleshorton for your kind support.
I'm using QQ browser(with chromium as its core) and firefox right now. And I have not uninstalled Xunlei, but will that be a problem? I remember Lantern works out fine last month with Xunlei.

**Comment by jindongwang** [comment]
And there is another major problem: I cannot log in. Same problem is in #5146

**Comment by jindongwang** [comment]
Is there version 3.1.1? Because I can only find 3.1.0 on the same page.

**Comment by jindongwang** [comment]
I‘ve tried 3.1.1, but it has the same problem: I cannot access all the blocked sites

**Comment by myleshorton** [comment]
Thanks @jindongwang. It's very odd because from the logs it looks like it's working. You see the exact same thing in FF and in QQ? Would you mind trying Chrome and just seeing if that happens to work? Otherwise Xunlei is the only known issue that could conflict -- otherwise this might be something new.

**Comment by jindongwang** [comment]
You know what, it doesn't work during working hours, but it does after work. I honestly doest get it. Right now the main problem seems the log in

**Comment by myleshorton** [comment]
Hey sorry @jindongwang can you describe the login issue in more detail? Are you trying to link devices?

You're saying it works fine for you in non-peak hours, but during peak hours it starts failing -- is that right? Would you mind sending logs from right after it starts failing for you?
