### ISSUE TITLE
能做就做，不能做就退款！

### ISSUE THREAD

**Issue by user-evan-chen** [getlantern/lantern#5155]
两个月以来一直在尝试更新各种授权方式，而对于通畅性，稳定性却没有任何提升。号称是可以3设备，然后实际结果是同期只有某一连接勉勉强强可连接，而速度又慢得几乎打不开。到也一直回复有说会更新，会处理，会升级服务器，然后时间过去了这么久，不停更新的只有各种验证方式，各种授权尝试，可讽刺的是这些授权也一直没能正常可用。更加不负责任的是，每一次更新完全不考虑用户之前刚刚掌握的操作方式，每一次都是重新来过。用户是来用产品的，还是被你玩的？你要是能做你就好好做，不能做在这儿胡玩骗钱就给我退款！

**Comment by p3rcya** [comment]
无法登陆的情况请报告到汇总贴 https://github.com/getlantern/lantern/issues/5146 ，我们集中解决

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
