### ISSUE TITLE
请大家留意，服务用不了，但官方不会给退款！

### ISSUE THREAD

**Issue by user-evan-chen** [getlantern/lantern#5156]
如果你是看了某些网文找到了这个软件，请你冷静下来，并且不要图便宜去尝试。实际上服务看起来便宜，但是你买了2年，但其最终能用的也许只有2个月，你以为会是3终端，其实能有一个可连就已经很不错了，软件的创新只在如何授权以保证他们的利益上，对于连通性，稳定性上长久以来没有得到任何更新。与其他SS，VPN服务商不同，Lantern的服务和支持非常中国特色，你不会跟官方有任何方便的沟通渠道，并且侥幸找到一个人，但态度也是极其恶劣的。所以，请你谨慎选择。因为一旦选择，实际的结果是钱你白白交了，但是你没有得到任何服务，你以为免费的限制和慢是因为没付费，但我可以负责任的告诉你，付了费也是一样。速度和多设备一样是没有的。至于流量，连都连不通，通又慢到死，给你再多所谓的不限流量又有何意义？与君共勉，以我为戒。

**Comment by p3rcya** [comment]
请问你怎么用不了？
问题报告后我们都会解决的

**Comment by user-evan-chen** [comment]
@p3rcya 真的？解决什么了？Android的专业版到现在都登录不了，花了钱却用不了，这叫解决了？

**Comment by norikohxb** [comment]
反正我是表态我是不会交钱的。你本身开发目的是借助全国不同的蓝灯用户做跳板。（这个本来就和bt一样是必须免费的）。现在却收费，是在可耻

**Comment by p3rcya** [comment]
@user-evan-chen 无法登陆的情况请报告到汇总贴，https://github.com/getlantern/lantern/issues/5146 我们集中解决

**Comment by EdwardAutumn** [comment]
@norikohxb 蓝灯2.0以后就不是p2p，是走代理服务器了，代理服务器的的租金和维护费用谁出的？用了那么久免费现在骂别人收费是谁无耻啊？
这楼主我就更懒得说了，无脑黑子一个，爱用用不用滚

**Comment by p3rcya** [comment]
@user-evan-chen 无法登陆的情况请报告到汇总贴 https://github.com/getlantern/lantern/issues/5146 说明详情，并发邮件到myles@getlantern.org 我们集中解决。

**Comment by user-evan-chen** [comment]
@EdwardAutumn 大人说话，你跑这儿舔什么沟。同样的网络，SS，VPN都是极速流畅。反馈不只一次了Lantern慢。收费时承诺说付费用户速度会快。付费的结果速度没上来，反而各种登录不了专业版。一问就说下个版本会好，结果下个版本出来的时候发现更新的永远是授权方式。速度没提升，专业版也还是登录不了你妈逼的。

**Comment by user-evan-chen** [comment]
@p3rcya 我最后再给你讲一遍，你集中注意力给我看懂了！

Android 手机版更新到3.1.1之后，手机登录专业版需要另外的设备来授权。我另外的设备是苹果电脑，我在苹果电脑上打开烂灯“授权其他设备使用专业版”，输入手机上给出的动态授权码，提交以后显示：“设备已授权
授权成功。请等待您的设备自动成为专业版。”但是，等几天了也没专业版，并且手机上还提示了：“验证错误，获取动态授权码错误！请稍候重试。：输入错误：硬件ID应该是整数”。

我不愿意陪你们再折腾了。退款吧

**Comment by p3rcya** [comment]
@user-evan-chen 你骂我和 @EdwardAutumn 没有用。我不是开发者，也没有权限退款。所有要求请反馈到 https://github.com/getlantern/lantern/issues/5146 并发邮件到myles@getlantern.org，他是主要负责人，你找他解决。

**Comment by user-evan-chen** [comment]
@p3rcya 是那个贱人先说我的，我只是回击。

**Comment by p3rcya** [comment]
@user-evan-chen 请按照上贴说的去那里反馈，你和我说没有用，我没办法给你解决

**Comment by norikohxb** [comment]
哦，那我要认错了，原来不是p2p了，我建议保留我们一个p2p的版本。你官方爱怎么用自己的服务器的版本就卖自己的，有竞争更好嘛。

**Comment by EdwardAutumn** [comment]
楼主我舔了你妈妈的沟，她很满意。

**Comment by norikohxb** [comment]
p2p的方式挺好的，继续保留一个免费的，大家爱用不用看网速。你要集中精力搞你什么优质服务器，不要把p2拍这么优越的方法给埋没了。我已经买了vultr的服务的vpn了。自己建设了vpn。两台路由器家里是已经可以不用任何客户端翻墙了。还保留蓝灯主要是因为结合chrom的swtichyomega偶尔补充一下。
所以我表示最好还能保留p2p的。

**Comment by norikohxb** [comment]
而且我觉得只有一个所谓的优质服务器不行啊，有的网页会屏蔽蓝灯的服务器。因为对他们来说代理量太大了。所以嘛我觉得p2p还是保留吧。

**Comment by Christophashjz** [comment]
还是保持些耐性给时间排除bug吧

**Comment by lzw2009** [comment]
耐性是要看蓝灯现在的动作和表态的，没出来给我们解决问题怎么有耐性啊？我们都是付了费了用户？花钱为了什么？

**Comment by huchiwen** [comment]
退款吧~一大推问题 都解决不了 搞毛啊~！~~~

**Comment by huchiwen** [comment]
我忍了很久了

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by Engrtao** [comment]
蓝灯真的很无耻啊，我交了钱反而比以前免费版的还难用

**Comment by Frozensunshine** [comment]
今天刚升级了专业版，交了2年的钱，可感觉速度比免费版的还慢，而且只能在一台设备上用，另外一台设备上的动态验证码根本不显示，也升级不了，能退款吗？跟谁联系呀？

**Comment by ilakeYC** [comment]
用别人的产品，花钱是天经地义的事儿，不想花钱的自己去搞啊。

**Comment by qimengke** [comment]
不能用了，为什么不可以退钱呢

**Comment by nabu888** [comment]
我也是发了很多邮件，根本不回复，手机根本用不了，PC不流畅，环境相同。
