### ISSUE TITLE
实在搞不懂蓝灯现在的状况

### ISSUE THREAD

**Issue by ivanbirth851230** [getlantern/lantern#5158]
看到蓝灯开发新的3.10 赶紧下载了现有的 并卸载了之前的版本 装上后 没地方登陆 不知道现在是什么状况 
难道蓝灯现在不是该集中精力在速度上面吗？

我也知道工作团队很辛苦 但我想能不能开发点对我们来说 有点改变的呢 这个新的版本 真的不怎样 速度没提升 登陆还麻烦 这是我目前的感受 让我用一个礼拜后 看看那个时候 会不会有不同的体验

对于已经购买了lantern的用户 咋就不用喊着 骂着了 有事说事 任何时候 不要失去理智和应有的素质 这是做人的底线 用的好 我们支持 用的不好 可以提出意见 可以组团提 但别喊爹骂娘 与你们一起在前行的路上

**Comment by user-evan-chen** [comment]
@ivanbirth851230  我的本意也是这样，但是事情不停的反馈都快两个月了，除了越来越难的登录，你看不到对服务和速度的任何提升。现实的状况已经逼迫你只能没素质，因为有素质的反馈和需求根本得不到响应。弄个@p3rcya论坛里回应挨骂，其它的人都躲在背后骗钱。一个号称Google赞助的团队怎么可能是这种效率和服务。所以，退钱才是一切的重中之重了，不用幻想了，这个软件没希望，无非是N多个因GFW而获利的小作坊中的一个吹得比较响的。退钱吧

**Comment by ivanbirth851230** [comment]
嗨 怎么说呢 兄弟 因为之前有一段时间 我用了lantern的免费版 感觉很好 而且它给我带来了很大的冲击 原谅我没有用过别的翻墙软件 我从小的概念就是 滴水之恩 当以涌泉相报。。。我相伴随lantern到最后 就算lantern团队最后什么都不是 但我依然会感恩它曾经所做过的 它就像孩子 需要你我的呵护 让我们耐心一点好吗 至于@p3rcya 没必要太较真 不是吗 毕竟他也尽力了 我认为他超出了他尽责的范围 要知道在国内的各种售后服务。。。。
最后 我只想说 这个真的是我们时代的悲哀 也是我们民族的悲哀 试想没有防火墙 会怎样 试想我们有民主 自由 加上勤劳的百姓 我们会怎样。。。对于这个不幸的时代 我们都对彼此 对他人 多一些宽容 多一些理解 好吗
还有啊 不知道你发现没 lantern的速度快在凌晨到早6点多左右 那一段。。。

**Comment by komajunjun** [comment]
现在用不了了吧？请问有什么替代品呢？

**Comment by gy8958398** [comment]
什么都没弄好，就开始收钱。满脑子全是钱，钱，钱，钱，钱！

**Comment by cgpeter96** [comment]
希望少些免费久了变成理所当然的人

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
