### ISSUE TITLE
关于蓝灯的收费做法。

### ISSUE THREAD

**Issue by norikohxb** [getlantern/lantern#5159]
蓝灯收费并且说，现在已经不是p2p了是专用服务器。
容我说句话，蓝灯发源于谷歌goagent不能用的时候。那个时候是p2p，速度比据说后面取消p2p以后专用服务器没有收费阶段还快

你官方想要赚钱无可厚非，但是之前p2p的并不影响你们的投资，没有必要让那个版本作废。
还有我买的付费服务是vultr的服务，是一个月一个月一付费用比蓝灯贵，但是可以做进路由器里面，用2台可管理路由器做手机电脑完全不用客户端的自由翻墙。

我个人意见你要赚钱还是有一个月一个月一付的，不要一年一付，蓝灯从开始到现在都还没有一年，就从p2p的快速变化到现在的烂速，谁知道缴费一年以后会怎么样？

另外p2p我觉得思路就是好就是该坚持。你租用服务器你能一直变更ip吗？当你的某个ip被某个站点列如黑名单，你的收费用户就完全用不了。而p2p的是大家互相借路，这个才是根本，gcd封杀不了。

**Comment by norikohxb** [comment]
做好收费服务（做大做强，最好客户端方便一点）我现在买的vultr的费用比蓝灯一年服务费贵咯。但是设置在路由器里面，手机不需要装app，电脑不需要用switchomege，我觉得方便。希望将来的蓝灯的收费版本能不要搞什么劳什子授权这个授权那个，（我是没有研究）但是我觉得消费者如果觉得太烦了也不好。

第二，希望能保留之前可以用的p2p，草根嘛，就好像现在很多软件都是收费和免费一起，免费用来扩大影响，大家都p2p效果好不好看运气听天由命，就好像迅雷一样，你要免费我也给你用，我不会提供服务器加速给你，你要速度快的，付费我也给你用。

**Comment by Page-David** [comment]
兹瓷你的看法，我觉得现在的免费版（哪怕限流量）的确比不上2.5左右版本的时候的速度了，那个时候是秒开谷歌。（我从1.*版本快结束的时候开始用的）我觉得国内（可能一部分是由于FW的原因吧）对开源和免费的认识没有全面，我们很多人对免费的东西太过疯狂，能不付钱就不付钱，从不想开发者的汗水，因此靠donate肯定lantern是做不下去的。更迅雷比的话，我只想说人家有广告，人家有全家桶啊。所以我还是兹瓷蓝灯收费的，毕竟软件开源但是服务器要$$$$啊。
对于取消篇p2p我只想说为什么要取消多样化的代理模式？这样才更稳定吧？直观上我是这么觉得的。

文笔极烂，敬请原谅，希望蓝灯做的更好。

**Comment by norikohxb** [comment]
p2p的好处就是支持更多的ip，全世界的人，（每个认的国家因为自己政府的政治利益肯定有给屏蔽的网站）好像国内的优酷或者是爱奇艺什么的也屏蔽国外ip呢？因为版权问题等等。所以，如果保留p2p，蓝灯不管怎么样，至少不会灭掉。goagent是免费，但是貌似不是p2p，所以给灭了，蓝灯搞自己的服务器，说白了，如果gfw灭了你的服务器ip，你能开的下去？你蓝灯的服务器能比谷歌的ip地址还多？

**Comment by danperor** [comment]
下一个goagent，看看现在lantern的速度，之前还能用，现在根本用不了了都。
废掉p2p就是自宫一刀。

**Comment by cvsyun013** [comment]
主要不是付费的问题，mac开机自动启动lantern 然后卡死任何网页都打不开。。。强制退出居然没有lantern。。。怎么做到的哈哈。

**Comment by norikohxb** [comment]
同意danperor的观点，废掉p2p就是下一个goagent，你如此大规模的收费而去是用固定服务器，说白了。gfw如果真正要封杀你，只要废掉你的固定ip你就彻底挂了，然后所有所谓的交了一年两年服务费的客户因为gfw的封锁ip也跟着钱打水漂了。当然从道理上不是蓝灯公司违约，你仍然提供服务，但是大陆的客户上不去，你可以理直气壮的说我并没有停止服务。强烈建议之前的p2p版本仍然开放着让大家用。

**Comment by Page-David** [comment]
@norikohxb 说的很有道理，这才是坠吼的。

**Comment by cainiaowu** [comment]
goagent又没死，现在不是叫啥XXnet了吗

**Comment by norikohxb** [comment]
goagent 没死那么相关论坛在哪里？

**Comment by norikohxb** [comment]
好，开始研究xxnet。呵呵，看到了。蓝灯只是我的备用，不过我是很反感也走服务器道路。就是还是要p2p 共产党就无能为力了。

**Comment by p3rcya** [comment]
我们以后会加入P2P的

**Comment by chengdong0421** [comment]
我在评论里看到XXnet了，不说了，我要去“研究研究”了
