### ISSUE TITLE
刚买了，填写了邮箱，也没收到什么邮件，重新启动让我授权

### ISSUE THREAD

**Issue by 130lin** [getlantern/lantern#5161]
……
之前就没登陆过
现在怎么登陆啊
还怎么授权……

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。
