### ISSUE TITLE
Hotmail无法接收邮件验证码

### ISSUE THREAD

**Issue by ashboneC** [getlantern/lantern#5170]
hotmail接收不了验证码，专业版无法登陆啊，什么情况，填了4 5次邮箱，邮箱里就是没有验证码的邮件。收件箱、垃圾箱都没有。

**Comment by DengZhengyuan** [comment]
我也默默填的Hotmail，也是没收到

不过，现在系统是MacOS，打开lantern就无响应了。更不说登录了。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by ashboneC** [comment]
头痛医头啊，我现在出现新问题，我之前的电脑系统崩溃，系统重新安装了，购买了专业版的，那我又该怎么登陆？

**Comment by ashboneC** [comment]
我系统重新安装了，显然之前的软件信息也没了，那我现在要重新登陆，并且给其他设备使用，那现在怎么操作？

**Comment by orbancanon** [comment]
@ashboneC 重装后应该会自动成为专业版。如果没有的话，请把你的帐号告诉我，我查一查。

**Comment by ashboneC** [comment]
mac7903@hotmail.com

________________________________
发件人: Orban Canon <notifications@github.com>
发送时间: 2016年8月29日 16:12:25
收件人: getlantern/lantern
抄送: ashboneC; Mention
主题: Re: [getlantern/lantern] Hotmail无法接收邮件验证码 (#5170)


@ashboneC<https://github.com/ashboneC> 重装后应该会自动成为专业版。如果没有的话，请把你的帐号告诉我，我查一查。

―

**Comment by orbancanon** [comment]
@ashboneC 我看到你的帐号下只有一台Windows 7的设备，如果是从那台设备上是可以自动成为专业版的。你是今天重新安装的Lantern吗？

**Comment by seeWorldByCode** [comment]
@ashboneC 同样也是，重新装了之后，没有自动成为专业版本，而且重新用qq邮箱登陆页收不到邮件
