### ISSUE TITLE
Lantern can't work on macOS Sierra

### ISSUE THREAD

**Issue by brilliance-boy** [getlantern/lantern#5171]
I'm a user of Lantern Pro, but it can't work on macOS Sierra. When the new version will be released?

**Comment by DengZhengyuan** [comment]
Me, too. = =
I have bought the Lantern Pro just now. Waiting for the solution.

**Comment by p3rcya** [comment]
closed in favor of https://github.com/getlantern/lantern/issues/5254

**Comment by StevenGardnerGMJ** [comment]
now   I have  the same  problem , how to fix it?

**Comment by p3rcya** [comment]
Please use the 3.2. Download here https://github.com/getlantern/lantern

**Comment by StevenGardnerGMJ** [comment]
thank you!


发自我的 iPhone
