### ISSUE TITLE
Scan for successful linking code continuously

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5173]
We should probably just do this outside of the device linking screen. With exponential backoff, it shouldn't be that bad, and autoupdates can always push us away from it if necessary.

Discussed this with @carsonefv and @Derekf5, @fffw. We can be somewhat smart about it and only do it if you have an active, unexpired code from opening the screen, but I think we should get this change in ASAP before doing auto-updates.

FYI @atavism I believe this is more or less what you already do on mobile, that right? If not I think we should probably just do the same thing there, and again only if the user has an active, unexpired code.

**Comment by myleshorton** [comment]
Hey @fffw you up for implementing this one?

**Comment by fffw** [comment]
Yeah sure @myleshorton. My next thing is to grab it. 

Personally, I don't prefer UI transitions not triggered directly by user actions, even the trick already implemented in 3.1.1, as it makes user surprise. I can be totally wrong, though, it's probably a good surprise.

**Comment by fffw** [comment]
Again, I think account recovery is much more important than this one. Almost all recent user complaints are about that.

**Comment by myleshorton** [comment]
I agree the account recovery is more important @fffw -- I moved that into TODO also if you want to tackle that first -- https://github.com/getlantern/pro-server/issues/242

**Comment by myleshorton** [comment]
@sunshine19090 in 3.1.2 you should be able to see a free device become linked once even if the user closes the linking screen on the free device (on desktop at least - I think this is also implemented on mobile too right @atavism?).

**Comment by atavism** [comment]
Hey @myleshorton, actually, on mobile it's still a requirement the user stay on the linking screen, but I'll have a fix for that shortly.

**Comment by myleshorton** [comment]
Awesome @atavism thanks! Just let me know whenever it's up!

**Comment by atavism** [comment]
Hey @myleshorton, this should be good to go already! Just double checked and we're already running this as a background timer task, even after the user navigates away from the screen. Closing.
