### ISSUE TITLE
Move "Manage system proxy" to advanced setting

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#5178]
Seen from https://github.com/getlantern/lantern/issues/4988#issuecomment-240386408, 2 out of 6 users who couldn't circumvent was due to this issue.

Maybe show the alarm at the status bar to replace the "Lantern is ON" text? We can slide up each alarm at the same place if there are more than one in the future.

![image](https://cloud.githubusercontent.com/assets/10410437/17759879/d1e99930-652d-11e6-84ec-36af0f5ee5c7.png)

I suggest we add it in next release. How do you think @myleshorton @carsonefv @Derekf5 ?

**Comment by Derekf5** [comment]
Interesting @fffw if it is an issue that often, could we think about removing "manage system proxy" as an option, and just always having it on?

**Comment by carsonefv** [comment]
@fffw I agree that removing it if possible would be best, how often is this setting necessary?

**Comment by p3rcya** [comment]
Maybe the setting to be not on is caused by software rather than user de-selecting it? 

I agree we should remove it

**Comment by fffw** [comment]
I saw user action to de-select it from the logs, but not sure why they did so. IIRC it's added to respond user request, for those who user 3rd party proxy switcher in front of Lantern.

**Comment by myleshorton** [comment]
Yeah it's in there because a lot of users wanted it. I'm guessing they de-selected it because Lantern wasn't working, and they thought that might make it work.

What about a warning for that particular setting just double-verifying that's what the user wants to do? In theory that should be in a separate "advanced" setting section too, but right now I think that would be the only setting in there.

**Comment by fffw** [comment]
Sounds good. An "Advanced" submenu folded by default is also ok, though reducing font size is required to leave enough room for the submenu and warning.

**Comment by Derekf5** [comment]
The advanced submenu sounds good to me, hidden by default but click "advanced" to unfold.

**Comment by p3rcya** [comment]
advanced sounds good

**Comment by carsonefv** [comment]
agreed

**Comment by myleshorton** [comment]
Works for me!

**Comment by carsonefv** [comment]
it can look like this:
![screenshot 2016-08-29 11 34 30](https://cloud.githubusercontent.com/assets/4400763/18057157/d1e6a128-6ddc-11e6-809b-78d76a9a9e77.png)
"Advanced Settings" 
Font: Roboto Medium (500); 
Size: 14pt; 
Color: #29BCD2; 
Transform: Uppercase;

When you click on "Advanced Settings", "Manage System Proxy" setting appears underneath:
![screenshot 2016-08-29 11 34 41](https://cloud.githubusercontent.com/assets/4400763/18057163/d5f02a3c-6ddc-11e6-89ed-1c68290834db.png)

**Comment by fffw** [comment]
A nice UI trick would be to always expand the advanced settings if "manage system proxy" is checked, so the user can notice it.

**Comment by p3rcya** [comment]
@fffw I'd say if it's unchecked, then it should always expand?

**Comment by fffw** [comment]
Ha, correct! nice catch @p3rcya
