### ISSUE TITLE
好评也Issue一下好不好

### ISSUE THREAD

**Issue by yueqianzhang** [getlantern/lantern#5180]
最近公司网略提速，最近在公司使用lantern pro速度很快，好评一个，
可以关掉了 =。=

**Comment by EdwardAutumn** [comment]
你可以自己关掉。然而我这里经常断。官方人员也是给个回复就没下文了。

**Comment by p3rcya** [comment]
@EdwardAutumn 不是没下文了，是我们正在测试和购买更好的线路。
