### ISSUE TITLE
收费版本来的太仓促，但是我还愿意耐心等待

### ISSUE THREAD

**Issue by imhao** [getlantern/lantern#5183]
虽然前两周蓝灯一直处于不稳定甚至完全连不上状态，但是能够感受到一直在改进，本周无论mac还是Windows都已能正常连接。
对于收费后不能提供正常服务的这段时间，蓝灯团队应该会给大家一个说法。
总体上我还保持信任，也会耐心等待，等蓝灯恢复正常。

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by norikohxb** [comment]
这些以后再兑现的保障先放一边，看人品，你们是如何防止gfw封杀ip的。有能力防止吗？
谷歌的goagent的ip，最后是给gfw灭掉了。一个不留。那么你们的呢？

**Comment by Guoooooo** [comment]
确实有些仓促了。换了好几个设备，觉得设备管理还是很乱。而且新设备没办法使用账号登陆，哪怕让其它设备自动失效。希望加油

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢各位的耐心等待！
