### ISSUE TITLE
专业版(android)无法使用已一周

### ISSUE THREAD

**Issue by kurobahz** [getlantern/lantern#5184]
已多次上传log 升级到3.1.3（817beta） 无效
是技术问题还是线路问题 最近能不能解决？
如果短期不能解决能否提供退款通道？

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by kurobahz** [comment]
已多次在app里提交日志
最近偶尔上午可以连接一小段时间 速度不快 但下午或晚上再尝试连接时 一直失败
购买专业版的初衷是获得一个稳定高速的上网环境 以及支持蓝灯团队 但现在看非常遗憾 
连提交日志都要使用别的vpn才能成功
希望维护人员除了固定话术外 可以给用户多提供一些有效信息

**Comment by p3rcya** [comment]
请去这里申请下内测 https://github.com/getlantern/forum/issues/1152

**Comment by milin411** [comment]
[lantern.txt](https://github.com/getlantern/lantern/files/465478/lantern.txt)
[lantern1.txt](https://github.com/getlantern/lantern/files/465479/lantern1.txt)
[lantern2.txt](https://github.com/getlantern/lantern/files/465482/lantern2.txt)
[lantern3.txt](https://github.com/getlantern/lantern/files/465483/lantern3.txt)
[lantern4.txt](https://github.com/getlantern/lantern/files/465480/lantern4.txt)
[lantern5.txt](https://github.com/getlantern/lantern/files/465481/lantern5.txt)

mac专业版网络慢求解决。

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
