### ISSUE TITLE
无法接受lantern收费的事实

### ISSUE THREAD

**Issue by SFLS-FRC** [getlantern/lantern#5185]
我其实是lantern的忠实粉丝，从lantern1.几的时候就一直在用并且还推荐给周围的人。就是因为lantern速度快而且又免费。现在升级到3.0以上的版本却突然收费一时有点接受不了。。。而且60美元足以自己搭一台服务器了。还望官方协调好收费与免费的平衡吧。

**Comment by p3rcya** [comment]
年付180人民币，60美元是两年啊

**Comment by p3rcya** [comment]
而且蓝灯永远可以免费使用。免费版每个月有800MB流量限制，但免费版流量用完之后还是可以继续使用，只是会限速而已，但浏览网页没有问题。

**Comment by cgpeter96** [comment]
为什么免费的那800MB流量无法使用  一直不能翻墙

**Comment by tim-hub** [comment]
和cgpeter96问题一样，无法使用，3.06版本

**Comment by Huang-Libo** [comment]
自己到vultr买个日本服务器，5刀每月，可以几个朋友一起用，速度很快，每月1T流量，根本用不完。

**Comment by p3rcya** [comment]
请使用最新的3.1.4 版本 https://github.com/getlantern/forum
