### ISSUE TITLE
when i launched lantern(3.1.1),browser rolled for a long time but did not successfully open , why?

### ISSUE THREAD

**Issue by q54528** [getlantern/lantern#5189]
I downloaded this new version of lantern(3.1.1) , and installed it . when i launched it , my web browser showed that localhost port is http://127.0.0.1:16823/?1 , then it rolls always the time .
![image](https://cloud.githubusercontent.com/assets/14799855/17845110/e0ce8ba8-6871-11e6-8d6d-39e7ca960f81.png)
what`s wrong with it ? how can i fix it ?

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by q54528** [comment]
this is my lantern.log
[lantern.txt](https://github.com/getlantern/lantern/files/429491/lantern.txt)

**Comment by q54528** [comment]
跳过UI，可以直接翻，但是一直在转圈

**Comment by q54528** [comment]
现在已经不转了
