### ISSUE TITLE
升级到专业版依然无法翻墙

### ISSUE THREAD

**Issue by veetase** [getlantern/lantern#5190]
今天发现免费版不能正常使用，一口气充值了两年的专业版。无奈的是专业版也同样不能翻墙，希望官方给个明确的恢复时间或者维护声明什么的。支持lantern，免费版已经给我们带来了很多便利，正常间断性无法正常使用可以理解，如果长时间无法恢复，建议给个退款通道吧，毕竟我开通后还没有正常使用过。

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by orbancanon** [comment]
@veetase 不能使用有多种原因，最常见的有：1. 勾掉了Lantern的"设置系统代理“选项，忘了勾选回来；2. 安装了迅雷或者第三方浏览器插件。如果检查都没有问题，请按https://github.com/getlantern/forum/issues/358的说明上传日志。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by veetase** [comment]
@orbancanon 确实是我勾掉了了设置系统代理。
