### ISSUE TITLE
付费后没有任何反应，未收取到任何邮件。

### ISSUE THREAD

**Issue by hawkinswoo** [getlantern/lantern#5192]
8/22下午付费1年专业版，支付宝扣款成功，至今未收到任何反馈信息，点击专业版按钮后仅有分享代码，未有任何其他反应，注册邮箱为hawkinswoo@163.com，也未收到任何邮件，支付宝账号为hawkinswoo@googlemail.com，望予以解决。谢谢！
[lantern.txt](https://github.com/getlantern/lantern/files/430337/lantern.txt)

**Comment by orbancanon** [comment]
@hawkinswoo 日志里面你使用的是2.2.5，并没有购买专业版的功能。通过后台查看，你在一台Windows 8.1的设备上购买了专业版。请问你发的日志是同一台设备吗？

购买之后Lantern的界面会立即变成专业版，并没有邮件确认。

**Comment by hawkinswoo** [comment]
是同一台设备的，确实是8.1的设备，我也很奇怪，昨天明明已经安装了3.1.1，今天再次打开lantern图标还是2.5.5的。请问我现在如何做才能打开正确的lantern？

**Comment by orbancanon** [comment]
可能是你后来不小心又安装了2.2.5。本周内会解决因为重装之类的原因造成帐号丢失的问题，请稍等两天，见谅。

2016-08-23 13:53 GMT+08:00 hawkinswoo <notifications@github.com>:

**Comment by lifeforfun** [comment]
我是刚刚付款后电脑死机重装了系统，我以为使用付款账号邮箱就可以登录，谁知道没有此功能，只能通过已授权客户端向其他客户端授权，那我这个付款账号岂不是永久丢失了！

**Comment by orbancanon** [comment]
@hawkinswoo @lifeforfun 新功能已经上线，你如果在那台设备上购买了专业版，重装系统后就会自动恢复帐号。

如果你的Lantern已经变成了免费的，请删除下面的文件，重启Lantern即可。

1. Windows XP C:\Documents and Settings\<用户名>\Application
Data\Lantern\settings.yaml
2. Windows 7 - Windows 10
C:\Users\<用户名>\AppData\Roaming\Lantern\settings.yaml
3. Mac /Users/<用户名>/Library/Application Support/Lantern/settings.yaml

在 2016年8月24日 上午11:34，lifeforfun <notifications@github.com>写道：

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
