### ISSUE TITLE
Upgrade Lantern to Go 1.7

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5193]
Now that Go 1.7 is final, upgrading will allow us to stop using our own fork while also reducing our binary size by ~20%!

**Comment by oxtoacart** [comment]
Let's upgrade all our apps, including:

1. Lantern Client
2. http-proxy
3. tlsproxy
4. borda
5. ???

**Comment by 07d6** [comment]
Is this done? If it is, please update README.md.
