### ISSUE TITLE
Change HTTP user-agents on desktop and mobile for client requests to backend server

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5196]
This would help distinguish them when debugging http calls.

**Comment by oxtoacart** [comment]
For:

1. Pro server
2. Config server
3. Geolocation

We'll assume for the estimate that the Go http client allows us to set our own user agent header.

**Comment by oxtoacart** [comment]
Could potentially hook this in at the proxied package.

**Comment by joesis** [comment]
Done
