### ISSUE TITLE
[desktop] Design for surveys on desktop

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5197]

**Comment by myleshorton** [comment]
FYI @Derekf5 I couldn't remember if we created a ticket for this or not.

**Comment by Derekf5** [comment]
@myleshorton it is right here https://github.com/getlantern/lantern-internal/issues/140

**Comment by xiam** [comment]
We won't be using a custom design, see: https://github.com/getlantern/lantern-internal/issues/138#issuecomment-242821121
