### ISSUE TITLE
也不能用，也不退钱，我只想说一句：操你妈！

### ISSUE THREAD

**Issue by user-evan-chen** [getlantern/lantern#5198]
你妈了个逼，我操！Android 版到现在都不能授权专业版，我操你妈的都死了吗？你妈了个逼的，要么做，要么退钱。我操你妈的！

**Comment by user-evan-chen** [comment]
听说官方都假装看不懂？

OK，fuck you mama! is ok？

**Comment by liruqi** [comment]
换 shadowsocks 吧。推荐一个商家 http://bill.xiami.la/aff.php?aff=210

**Comment by ziqidonglai** [comment]
什么素质啊？  跟泼妇骂街是的。 天气还有刮风下雨呢 你能保证天天有太阳啊。

**Comment by ziqidonglai** [comment]
我作为局外人 别人都说用的挺好的。。有问题解决问题  这样骂人 素质这么低下恶劣 。你用的不好使就等于全世界人民都不好使呗。

**Comment by user-evan-chen** [comment]
@ziqidonglai 去看看有多少人验证不了专业版。我和风细雨的反馈过啊。事情过去两个月了，两个月内不停的反馈有什么结果？是没人解决问题的，这个软件就是个骗局。骂不是低素质，而是遇到骗子的一种无奈的发泄。

**Comment by user-evan-chen** [comment]
@fffw 把钱退给我！你们又不解决问题。操你妈的。

**Comment by user-evan-chen** [comment]
@fffw 关闭的时候有你，解决问题的时候怎么没有你？！操你妈的。

**Comment by p3rcya** [comment]
@user-evan-chen 本星期解决。请勿人身攻击，再犯就ban了

**Comment by user-evan-chen** [comment]
@p3rcya 本星期这种说法光是你都说了几次了。别再骗人了。退款吧
