### ISSUE TITLE
Add instructions to recover Pro account on UI

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#5199]
Temporarily in the next release.

@p3rcya mentioned that the user who doesn't know Lantern forum have no chance to know the sequence to recover the Pro account.

By showing instructions user can at least do it by themselves. @myleshorton your idea?

**Comment by elaurensx** [comment]
@fffw Hey, would you mind posting a link to the instructions here? Thx! :)

**Comment by fffw** [comment]
@elaurensx Thanks for you patience. The feature is not online yet, so there's no instructions at this moment.

**Comment by elaurensx** [comment]
@fffw Thx for the quick response. I'm sure you've noticed that quite a few ppl are waiting for this. Good luck with the implementation ;)

**Comment by p3rcya** [comment]
closing in favor of https://github.com/getlantern/lantern-internal/issues/150
