### ISSUE TITLE
一直用的不怎么顺利，希望按剩余天数退款！！！

### ISSUE THREAD

**Issue by linmonsv** [getlantern/lantern#5201]
买了两年的，用了一个多月，期间断断续续的，速度也一直不稳定，希望可以可以按剩余天数比例退款！！！平时用的太多，这样下去实在是影响工作学习，，，╮(╯▽╰)╭

**Comment by user-evan-chen** [comment]
他会说本星期解决。然后就是无数个本星期之后再也不退款。

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。
