### ISSUE TITLE
Use native vendoring support

### ISSUE THREAD

**Issue by xiam** [getlantern/lantern#5202]
Now that we have had vendor capabilities in Go for a long time I think it's time to stop using the submodules-like approach and custom tools we currently use. We probably want to wait on this after merging `lantern-pro`, tho.

**Comment by oxtoacart** [comment]
I'd vote for using Glide to manage the dependencies.  It's worked well for http-proxy-lantern, amongst others.

**Comment by oxtoacart** [comment]
BTW, I think switching to Go native vendoring is a good idea, especially now that the Lantern client isn't changing as rapidly anymore.

**Comment by myleshorton** [comment]
I agree on Glide and this ticket. I'll move this into the top of the backlog, and feel free to tackle it if anyone feels so inclined.
