### ISSUE TITLE
Dynamic linking code not working 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5206]
This ticket only collects users who uses the code currently. Getting more info, @fffw 

https://github.com/getlantern/forum/issues/1086
https://github.com/getlantern/forum/issues/1091
https://github.com/getlantern/forum/issues/1212

**Comment by myleshorton** [comment]
how often are you seeing this error @p3rcya?

**Comment by p3rcya** [comment]
More https://github.com/getlantern/forum/issues/1229#issuecomment-245471443

**Comment by p3rcya** [comment]
I'd say it's often when taking account into that most users don't (know how to) use this authentication method at all. 
Not a priority though because they can log in with email in next version
