### ISSUE TITLE
lantern在 长城宽带 提供的网络下不能正常使用

### ISSUE THREAD

**Issue by 5alamander** [getlantern/lantern#5211]
在公司电信的网可以用，
会到宿舍的长城宽带的网不行

**Comment by normalhh** [comment]
上海长城宽带，前天可以正常使用。今天未知

**Comment by xiefangzhenz** [comment]
今天上了下，可以使用。。。。

**Comment by 5alamander** [comment]
公司与宿舍唯一的不一样就是，公司是电信的，宿舍是长城宽带的，
找不到原因在哪里，而且也没有个流量监控的显示，也不能选择其他节点，
求解到底是什么原因导致的

**Comment by cupidmomo** [comment]
福建廈門，長城寬帶，win10系統，Lantern 3.0.7 (20160714.225529)免費無VIP，可用，800M到目前剩下19M~

**Comment by 5alamander** [comment]
Lantern 3.1.1 (20160811.054944)，OSX 10.11.6
有vip ，看不到流量，选不了节点，
电信的网可以，长城宽带不可以，

**Comment by cupidmomo** [comment]
要不然打电话叫长城宽带看有没有办法重置一下你的帐号？类似恢复或者还原设置之类的？

**Comment by 5alamander** [comment]
搞不定额~ 还是没有定位到原因，

会不会和dns之类的有关系，怎么破额~~ ， 有点后悔了

**Comment by cupidmomo** [comment]
sorry,帮不到你~呼叫官方人员~

**Comment by Eric404** [comment]
我也是深圳的长城宽带，用不了

**Comment by p3rcya** [comment]
可能是长城宽带的原因。我们正在为专业版购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by 5alamander** [comment]
@p3rcya 
账号：471073043@qq.com
[lantern.txt](https://github.com/getlantern/lantern/files/446223/lantern.txt)

**Comment by Eric404** [comment]
hi~ 这样讲，一年一百多的费用，没多少 工作和自身学习还有更高的追求，需要自己扯个VPN，之前都是自己搭ss的，也是长宽出口的问题。蓝灯付费之前表现很好，付费之后表现异常，这让我不是很舒服。 之前从事过CDN行业，长宽出口至联通有时会被限制跨网访问，同时目前各家长宽服务器资源不足。 按我之前积累的部署经验 南方放一台在湖北， 北方河南 西南的庐州都是不错的 单台128G内存大设备对于页面的访问大概能抗500M的带宽。对于下载能抗2G左右，开了万兆网卡能抗4G。之前遇到过最高情况，十分钟十万链接数没有问题。 我技术水平不高，班门弄斧了 祝愿蓝灯越来越好 也期盼对于付费之后能给我会员或者付费者应有的心里预期，两个月的额外时间，没那么重要。 毕竟我付费的目的是买了就用，而不是为了后期的优惠，您想是不是这个道理？ 祝好！ wechat:naivezian 发自网易邮箱大师

**Comment by p3rcya** [comment]
@Eric404 感谢你的回复。如果你对数据中心速度由什么内情，欢迎直接联系我。 percy[at]getlantern.org 我们正在添加更多的数据中心，你可以去 https://github.com/getlantern/forum/issues/1152 申请下内测。

**Comment by GD-HBX** [comment]
@Eric404 建在国内不怕被抓？

**Comment by yummy222** [comment]
我的是广州 长城宽带 ，专业版也是经常不能用
[lantern.txt](https://github.com/getlantern/lantern/files/453761/lantern.txt)

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
