### ISSUE TITLE
无法授权！！！！！！

### ISSUE THREAD

**Issue by carlzeiss1981** [getlantern/lantern#5215]
用mac 的收费chrome版本，给win的chrome 授权，提示成功 ，但是windows就是不自动跳到pro界面，搞什么鬼，明明之前的邮箱获取验证码是可以的，现在又搞一个『『从其他专业设备获取授权码』』？？？？？？

**Comment by p3rcya** [comment]
请等新版，会解决这个问题

**Comment by BlueSoraSky** [comment]
@p3rcya 您好，我是手机授权PC端的，但输入授权码后一直没有响应，求大神帮助：）

**Comment by BlueSoraSky** [comment]
@p3rcya 我起初是在另一台PC上购买的，通过另一台PC授权手机的过程是很顺利。现在手机来授权新的PC就遇到了困难，不知是什么原因。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
