### ISSUE TITLE
新版本的登录完全是反人类的设计啊

### ISSUE THREAD

**Issue by caik13** [getlantern/lantern#5216]
我之前用的老版本用邮箱账号登录的然后购买了一年的专业版，后来我重做系统了，然后lantern也更新了，结果登录你要我授权，你来告诉我怎么授权！！！

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
