### ISSUE TITLE
电脑重装后登录不了

### ISSUE THREAD

**Issue by Aphions** [getlantern/lantern#5221]
8月1日购买的一年，在手机和电脑上使用。
8月26日重装系统，然后安装lantern，但是点击登录的时候一直都是授权码，我只在自己的手机和电脑上使用，电脑登录不了，手机没有‘’授权使用其他设备‘这个’选项，然后一直登录不了。
8月28日也就是今天中午一点三十多又在电脑上购买了一年，用的是同一个邮箱，这样才登录上来了。
但是显示到期的时间确实2017年8月28。这个怎么解

**Comment by p3rcya** [comment]
@orbancanon 请看看这个

**Comment by orbancanon** [comment]
@Aphions 你手机上可能是没有升到最新的版本，所以没有那个选项。重新买到的是完全独立的帐号，所以到期时间就是8月28号了。用同一个邮箱应该是重新买不了的，请你对比一下手机和电脑上的显示。如果邮箱确实是一样，请发给我查一下 orbancanon@gmail.com

**Comment by Aphions** [comment]
Hi  Orbancanon:

     很抱歉这么晚才回复，8月1日和28日用的是同一个邮箱:Aphions@Gmail.com
，因为我用在手机上老版的时候似乎会给邮箱发送验证码，而我邮箱保存着8月1日及28日验证时的邮件，如附件所示，还请帮忙看下，谢谢。

Regards，

Aphions

在 2016年8月29日 下午1:29，Orban Canon <notifications@github.com>写道：

**Comment by orbancanon** [comment]
@Aphions 我回复更晚更不好意思~

查了一下，两个帐号，先买的那个用的Aphions@gmail.com，另一个用的aphions@gmail.com。。。

cc @p3rcya

**Comment by p3rcya** [comment]
@Aphions 请按照这个教程试试 [蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by p3rcya** [comment]
@orbancanon 那是大小写的问题，我们应该把大小写看成同一个帐号

**Comment by Aphions** [comment]
@p3rcya 已经按照教程试过，但是还是无法登录，等待一段时间后没有自动变成专业版，点击后显示授权码。
@orbancanon 我把截图及log以及其他信息发送过去了，还请帮忙再看下。

谢谢，

**Comment by imuutiQAQ** [comment]
这里借一下楼，@orbancanon 我之前是有购买专业版的，电脑系统重装后专业版全失效了，注册的邮箱是13184801648@163.com，购买的时间最少是在半个月前，具体时间我忘了，很抱歉。登录设备是一台Android手机和一台win10的电脑，重装前是win10，现在也是，希望你能帮我解决问题，谢谢！

**Comment by orbancanon** [comment]
@imuutiQAQ 根据你邮箱查到帐号下只有一台小米手机，没看到Windows 10电脑啊！

在 2016年9月2日 下午5:33，imuutiQAQ <notifications@github.com>写道：

**Comment by imuutiQAQ** [comment]
@orbancanon  我的手机是小米没错，当时我是在win10电脑(重装前)上购买的lantern，也是在电脑上先使用的，然后手机才用的专业版，为什么记录上会没有啊，说到手机，当时覆盖安装上去之后就不能使用专业版了，希望你们能给我提供帮助

**Comment by p3rcya** [comment]
@imuutiQAQ 用这个教程试试 [蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by imuutiQAQ** [comment]
@p3rcya  试了不行啊

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
