### ISSUE TITLE
只想知道如何退款

### ISSUE THREAD

**Issue by laole918** [getlantern/lantern#5222]
没付款之前，偶尔链接不稳定可以理解，为什么购买了专业版还是不稳定。我同时还买了shadowsocks有鲜明的对比。蓝灯收费又贵质量又差，没有做到那么稳定就不要急着收费。

**Comment by whysoslow** [comment]
我也要知道怎么收费

**Comment by p3rcya** [comment]
我们正在为专业版购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by p3rcya** [comment]
请勿重复发贴 https://github.com/getlantern/forum/issues/1140
