### ISSUE TITLE
[Mobile] Screen color stuck when turning app on an off.

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern#5232]
In addition the button is showing up too low for pro users, but i think @sunshine19090 is ticketing that somewhere.
![screenshot_2016-08-30-10-15-42](https://cloud.githubusercontent.com/assets/7864729/18094621/28288572-6ea2-11e6-87d9-d4a76a3025ea.png)
![screenshot_2016-08-30-10-31-22](https://cloud.githubusercontent.com/assets/7864729/18094620/2825ec9a-6ea2-11e6-974c-2a1b77b043e1.png)

**Comment by Derekf5** [comment]
Closing this because now that the button has been moved back to the correct position, it cannot be reproduced.

**Comment by atavism** [comment]
Cool, thanks @Derekf5!
