### ISSUE TITLE
linking code not shown in the UI

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5236]
https://github.com/getlantern/lantern/issues/5234#issue-174173673

![image](https://cloud.githubusercontent.com/assets/20512438/18118525/3c2b64dc-6f0a-11e6-8243-00a2eaa25417.png)

**Comment by p3rcya** [comment]
@sunshine19090 @Derekf5 @fffw I hope this is not caused by too many text in the Chinese instruction. I cannot test this because I cannot revoke Pro on win10 and it will automatically becomes Pro even if I manually remove yaml.

**Comment by Riririrororo** [comment]
I got this issue on the 3.1.4 of phone in English, it seems the code appears  on 3.1.2 after I tried to install another version.

**Comment by myleshorton** [comment]
Are we seeing any errors on that endpoint @uaalto?

**Comment by uaalto** [comment]
There is a fair amount of `wrong-link-code` errors logged in the `/link-code-redeem` endpoint. In principle these would be caused by sending a wrong code.

**Comment by sunshine19090** [comment]
@p3rcya https://github.com/getlantern/lantern-internal/issues/158  I came across this in mobile once but after that it started worked fine.

**Comment by fffw** [comment]
It may be caused by timeouts calling `/link-code-request`, especially if the free proxy is blocked or inaccessible.

**Comment by p3rcya** [comment]
more https://github.com/getlantern/forum/issues/1232#issue-175654498
