### ISSUE TITLE
email should be case insensitive 

### ISSUE THREAD

**Issue by p3rcya** [getlantern/lantern#5237]
Multiple users reported before their email is not recognized if they accidentally entered some upper case during sign up. This is not expected. I recommend we only use lower case to comply with the convention. 

There are also users who purchased twice with the Aphions@gmail.com then aphions@gmail.com. Those accounts need to be manually merged with the Pro time added together.  
https://github.com/getlantern/lantern/issues/5221#issuecomment-243756234

**Comment by myleshorton** [comment]
Yeah we should just lowercase everything for sure @uaalto

**Comment by fffw** [comment]
pro-server does normalize emails (trim spaces and turn to lowercase) in some cases, but it doesn't seem to do so in purchase calls.

We probably can change the code to normalize email in each web handler which accepts email, instead of scattered in service logic. A relevant piece is a script to make sure emails in the database are all lowercased and handle duplications if any.

**Comment by myleshorton** [comment]
Sounds like a good idea @fffw.

**Comment by uaalto** [comment]
At the moment, the only place we input emails is in the purchases endpoint. Emails are actualy being normalized there: https://github.com/getlantern/pro-server/blob/master/src/pro_server/tasks.clj#L273
However, that email was used before we started normalizing. So the steps would be:

1. Make sure all endpoints do normalize (as I mentioned, I think only the purchases does, but just to double-check).
2. Create a script to find and merge duplicates.

I'll be happy to take care of this, unless you were already set to do it @fffw.

**Comment by fffw** [comment]
No I didn't do anything on this issue @uaalto.

**Comment by myleshorton** [comment]
I actually wonder if case normalization could be an issue with device IDs too. Like I could imagine some OSes using uppercase will others use lower, which could explain the different device IDs with OS installs thing.

**Comment by fffw** [comment]
@myleshorton The `NodeID()` is in binary form. The representation of MAC address should be irrelevant.

**Comment by myleshorton** [comment]
Don't we store it in base64 or something though @fffw?

**Comment by fffw** [comment]
Yeah, `deviceID` is `base64` encoded, but the encoded string should be the same given same input bytes.

**Comment by myleshorton** [comment]
Right good point @fffw makes sense.

**Comment by uaalto** [comment]
Ok, I've reviewed the code and we had normalization in place. There are 6 users that might be affected by this, 3 of them are trivially fixable, and the other 3 I have to do it manually.
I was thinking on merging on the latest created, adding on it the plan purchased in the other. But this isn't necessarily the best approach. What if the user purchased in two different devices? One of them is going to stop working and should recover from the other one.

@fffw you can review the code here if you like: https://github.com/getlantern/lantern_aws/pull/324
I haven't run the trivial merge in production for those 3 users yet until you check it.

**Comment by p3rcya** [comment]
"One of them is going to stop working and should recover from the other one." I think that's acceptable to the users

**Comment by uaalto** [comment]
Ok. I think it would be best to look into each one of the users in details. Maybe we can keep the desktop device, for example.

**Comment by fffw** [comment]
Thanks @uaalto I'll take a look. Yeah, for such a few users, we can handle them one by one and  email them about this change with instructions.

**Comment by Artoria2e5** [comment]
Note that the forced case-insisitivity is not technically correct per [RFC 5321](https://tools.ietf.org/html/rfc5321), but just a *de facto* agreement among service providers:

```
   Local-part     = Dot-string / Quoted-string
                  ; MAY be case-sensitive
```

**Comment by p3rcya** [comment]
@Artoria2e5 Thanks. To reduce user confusion, we have now forced email to be lowercase
