### ISSUE TITLE
Has lantern (version 2.2.5) been disabled?

### ISSUE THREAD

**Issue by komajunjun** [getlantern/lantern#5239]
I cann't use it to access youtube today, but I can yesterday.

**Comment by myleshorton** [comment]
It should still work @komajunjun, but all active development is happening on the 3.1.x versions, so I would recommend trying that instead.

**Comment by komajunjun** [comment]
Thanks for your suggestion @myleshorton, but it is not very stable. Is it?

**Comment by myleshorton** [comment]
It's definitely much more stable than it was during our initial release @komajunjun, but we've put out probably 5 or 6 updates since that first version. It also shouldn't impact proxying/raw functionality -- on that level it is very similar to 2.2.5.

**Comment by komajunjun** [comment]
thank you @myleshorton

**Comment by myleshorton** [comment]
You're welcome @komajunjun -- please let us know if it continues giving you problems.

**Comment by komajunjun** [comment]
OK.

2016-09-05 10:38 GMT+08:00 Myles Horton <notifications@github.com>:

**Comment by komajunjun** [comment]
OK myleshorton

**Comment by p3rcya** [comment]
I'm gonna close this for now. @komajunjun you can always download the latest version of Lantern 3 on https://github.com/getlantern/lantern
