### ISSUE TITLE
PC 专业版本  授权手机端后 打不开GOOGLE 也不能上网？？？？

### ISSUE THREAD

**Issue by 10418418** [getlantern/lantern#5243]
PC 专业版本  授权手机端后 打不开GOOGLE 也不能上网？？？？  原来手机能上免费送的流量

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。

**Comment by 10418418** [comment]
那我应该使用什么版本，不会只能使用电脑吧  手机都不能共享

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。
