### ISSUE TITLE
为什么没法购买？

### ISSUE THREAD

**Issue by ImbaSilencer** [getlantern/lantern#5244]
1913398708@qq.com
支付宝付款，付款后下方显示一个空的框框，旁边有“重试”
之后登录专业版，邮箱能收到验证码，能登陆，但是没法用，显示到期时间是1970年。。。。。。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。

@orbancanon 请看看，又是1970

**Comment by fffw** [comment]
Duplicated with https://github.com/getlantern/forum/issues/1185
