### ISSUE TITLE
如果没有很多的peer，那么国内上网还是会很卡的。

### ISSUE THREAD

**Issue by csrgxtu** [getlantern/lantern#5245]
这种模式依赖于其它的lantern安装，但是大部分安装这个都是国内的，国内的客户端相互代理还是不能达到实质性的翻墙，而国外的lantern安装估计会很少。那么商业版本的lantern会不会自建国外的代理呢。

**Comment by p3rcya** [comment]
商业版本是有国外专用数据中心的，请放心
