### ISSUE TITLE
youtube有的视频播放不了

### ISSUE THREAD

**Issue by Jason4774** [getlantern/lantern#5247]
youtube有的视频播放不了，比如下面这部剧：
https://www.youtube.com/watch?v=GFyL73wIZMU
不知道有人知道什么原因吗？

**Comment by p3rcya** [comment]
这个是他视频本身的原因

**Comment by Jason4774** [comment]
那我用其他的代理软件可以看是为什么。只有蓝灯不行。

**Comment by p3rcya** [comment]
你确认现在还可以么？ 我看到好像整个频道都被Youtube限制了

**Comment by Jason4774** [comment]
肯定啊。我天天都在用其他的代理软件看，只是上次测试蓝灯的时候偶然发现蓝灯对于这个视频播放不了。

**Comment by Jason4774** [comment]
整个频道都被Youtube限制了，但是其他代理软件可以，所以我才会问这个问题，不知道可以解决吗？

**Comment by Jason4774** [comment]
整个频道都被Youtube限制了，但是其他代理软件可以，这个应该就说明是蓝灯的问题吧

**Comment by p3rcya** [comment]
可能是Youtube对代理IP的限制。能访问Youtube，就说明蓝灯翻墙是没有问题的。

**Comment by Jason4774** [comment]
能解决吗？
