### ISSUE TITLE
安装蓝灯最新版3.1.4后，chorme和IE主页均被修改。

### ISSUE THREAD

**Issue by ziyudii** [getlantern/lantern#5248]
被修改成http://ptraleplanty.ru/。修改注册表仍无法修复。查看了蓝灯安装目录下的文本文档，里面有这个网址。请问是否正常。

**Comment by p3rcya** [comment]
你可能是下载了假的版本。请问在哪里下载的？ 请认准官方下载地址 https://github.com/getlantern/forum

**Comment by ziyudii** [comment]
我现在重装系统试下。查杀病毒什么的都没解决。

**Comment by StephenGiant** [comment]
我也是一样的问题唉，这个是不是有病毒啊？

**Comment by p3rcya** [comment]
你是在哪里下载的？

**Comment by StephenGiant** [comment]
getlantern上下载的

在 2016-09-23 10:44:08，"p3rcya" <notifications@github.com> 写道：


你是在哪里下载的？

**Comment by StephenGiant** [comment]
右键chrome快捷方式 打开文件位置 会发现安装了一个莫名的应用，卸载他，即可
