### ISSUE TITLE
macOS Sierra Public Beta 7 Lantern 闪退  附日志

### ISSUE THREAD

**Issue by zhangtianyu2012** [getlantern/lantern#5254]
### 环境 ###

>MacBook Pro (Retina, 15-inch, Mid 2014)
>macOS Sierra 10.12 Beta(16A313a)

### 请开发者关注 ###

* macOS Sierra已经出到第7个Public Beta了，但是3.0.6依旧闪退，最新的3.1.4也是闪退，买了专业版，升级Public Beta后就没有好使过。
* 北京时间9月8日凌晨1点是苹果发布会，估计正式版也即将推出了，请问这个bug何时能修复？
* 专业版的钱已经浪费了几个月了，而且目前市面上的APP对Public Beta支持都很好，你们也可以通过官网直接获取Public Beta的版本，不需要Apple Developer账号的，完全有条件对此做兼容。

**麻烦开发者们对此事重视一下，毕竟现在收费了，并不是免费在用了。最后附上3.0.6与3.1.4的log，麻烦排查下，谢谢。**

### 日志 ###

[lantern_3.0.6.txt](https://github.com/getlantern/lantern/files/458365/lantern_3.0.6.txt)
[lantern_3.1.4.txt](https://github.com/getlantern/lantern/files/458366/lantern_3.1.4.txt)

**Comment by Artoria2e5** [comment]
> [Go 1.7 Release Notes](https://golang.org/doc/go1.7):
> 
> Go 1.7 adds support for macOS 10.12 Sierra. This support was backported to Go 1.6.3. Binaries built with versions of Go before 1.6.3 will not work correctly on Sierra.

Perhaps it's time to move to Go 1.7 (build failure -- there are more changes in the fork than documented in the README), or at least to rebase the fork to 1.6.3.

* * *
Crash as found in 3.0.6 log:
```
Sep 07 05:28:00.857 - 0m14s ERROR flashlight.app: app.go:59 fatal error: fault
unexpected fault address 0x7a343f70d6e6
unexpected fault address 0x7a34a21c593b
[signal 0xb code=0x1 addr=0x7a343f720f0b pc=0x7a343f720f0b]
```
(didn't notice anything meaningful in the 3.1.4 log)

**Comment by myleshorton** [comment]
Thanks @Artoria2e5 - yes the next Lantern version will use 1.7.

**Comment by p3rcya** [comment]
@myleshorton I've receive dozens of complaints on this one. Considering that macOS Sierra will be released on Sept 20, we probably should address this soon.

**Comment by brilliance-boy** [comment]
apply for refund....

**Comment by zhangtianyu2012** [comment]
@p3rcya I build Lantern on my macOS, but the home page of Lantern looks like the version of 2.x. So how can I build the pro version for myself?

**Comment by myleshorton** [comment]
Again @p3rcya the next Lantern version should fix this.

**Comment by gxsjtu** [comment]
when the next version released?

**Comment by p3rcya** [comment]
this month

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！

**Comment by myleshorton** [comment]
The current version should work for you if you re-download
