### ISSUE TITLE
Lantern using Edge even when Chrome is the default browser

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5257]
This was reported by a user on Windows 10. Even with Chrome set as the default, Lantern tried and failed to open its UI in Edge.

**Comment by myleshorton** [comment]
We have been unable to reproduce this so far -- reported on a Surface.

**Comment by p3rcya** [comment]
No one uses surface...

**Comment by Artoria2e5** [comment]
Not reproducible on Windows 10 build 14915 (not Surface). Perhaps it's best to test this problem by assigning different browsers to the HTTP protocol, the HTML format, etc.

**Comment by oxtoacart** [comment]
Not reproducible at the moment.

**Comment by joesis** [comment]
I could consistently reproduce it on Win 10 with Lantern 3.2.0

**Comment by joesis** [comment]
Oops I misread the title. It's totally unrelated to what I found.
