### ISSUE TITLE
我要退款！！！

### ISSUE THREAD

**Issue by syjml** [getlantern/lantern#5261]
蓝灯是我见过的第一个把付费用户体验做的不如免费用户体验的应用！！！！

**Comment by syjml** [comment]
@p3rcya 退款！！！！！！！！！！

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by syjml** [comment]
@p3rcya  我这是中国电信百兆企业专线，用蓝灯后能有多慢有多慢！！！！！还不如我用的XX-NET！！！！

**Comment by syjml** [comment]
@p3rcya 我要退款！！！

**Comment by XieXianbin** [comment]
支持

**Comment by syjml** [comment]
@p3rcya  退款！！！！！！

**Comment by p3rcya** [comment]
@syjml 内测线路正在逐渐发放

另外，请不要刷版，不然只能ban了

**Comment by syjml** [comment]
@p3rcya 不刷版可以啊，你把钱退我不就得了。
