### ISSUE TITLE
lantern 专业版 从前几天开始 就用不了

### ISSUE THREAD

**Issue by tartyphoenix** [getlantern/lantern#5263]
show lantern 显示蓝灯已经开启了   但是google什么的都是上不了，求解决问题

账号：18509280793@163.com

[Uploading lantern.txt…]()

**Comment by p3rcya** [comment]
日志没有上传成功，请重新上传试试

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。
