### ISSUE TITLE
以前手机丢了，现在新手机上安装蓝灯没有登录选项怎么办

### ISSUE THREAD

**Issue by svhero658** [getlantern/lantern#5270]
在安卓发送报告一个星期也没有人回复我

**Comment by p3rcya** [comment]
新版会修复，本月会出

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
