### ISSUE TITLE
An empty `global.yaml` causes Lantern desktop to crash

### ISSUE THREAD

**Issue by orbancanon** [getlantern/lantern#5276]
Seen from logs at https://github.com/getlantern/forum/issues/1282. Reproducible in 3.1.4 and latest.

An empty `proxies.yaml` doesn't cause same issue.

**Comment by joesis** [comment]
Adding to backlog too.

**Comment by myleshorton** [comment]
Seems good @joesis. I wonder why global.yaml was ever empty though?

**Comment by joesis** [comment]
No idea @myleshorton  . Looks like a rarely happen bug.
