### ISSUE TITLE
My account disappeared.It says that 'User link not configured".(549217411@qq.com)

### ISSUE THREAD

**Issue by SOSDAN** [getlantern/lantern#5277]
WHY.I bought an account about two months ago. The email address is 549217411@qq.com.
Now I can not log in. so the money I spent just make nonsense?/?????

**Comment by myleshorton** [comment]
Thanks for the report @SOSDAN and apologies for the issue you're seeing. @uaalto and @joesis do you guys have any insight into anything that might have changed here?

**Comment by myleshorton** [comment]
We will figure this out @SOSDAN, and our apologies for the inconvenience. Lantern Pro also should become much faster for you very soon.

**Comment by uaalto** [comment]
Not present in our database. I need more info to manually verify, fix and diagnose the issue, @SOSDAN.
Can you please send your logs to uaalto@getlantern.org? Please follow these instructions: https://github.com/getlantern/lantern/wiki/Emailing-lantern-logs
In that email, can you also send me this info:
- The plan you purchased
- The payment method you used
- The devices that you were using Lantern from (OSX, Windows, Android or other operating system).
- Did you recall adding any referral in the purchase process?

I apologize for the inconvenience @SOSDAN, we'll try to figure this out ASAP.

Thank you

**Comment by p3rcya** [comment]
@SOSDAN 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。

**Comment by SOSDAN** [comment]
I have used Alipay to  purchase one year plan, costing 180 yuan. I 

[lantern.txt](https://github.com/getlantern/lantern/files/473293/lantern.txt)

**Comment by SOSDAN** [comment]
I have used Alipay to purchase one year plan, costing 180 yuan. 
[lantern.txt](https://github.com/getlantern/lantern/files/473300/lantern.txt)
This is my log file.

**Comment by oxtoacart** [comment]
The user has managed to recover their account.

**Comment by uaalto** [comment]
On reviewing this issue, this one was solved manually by me, just for the record, @oxtoacart. There is a similar one that was solved by the user.

**Comment by oxtoacart** [comment]
Thanks @uaalto.
