### ISSUE TITLE
Errors piping global config through chained proxy

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5278]
I see this every time in the logs:

```
Sep 14 18:18:07.215 - 0m1s DEBUG flashlight.client: handler.go:132 Error piping data from proxy to client: short write [op=proxy origin_host=globalconfig.flashlightproxy.com origin_port=443 root_op=proxy user_agent=Go-http-client/1.1]
```

@oxtoacart could there be a bug with BidiCopy and larger files? I wonder if a quick unit test could reproduce this?

**Comment by oxtoacart** [comment]
I just tried curling it through our proxy, as well as downloading via chrome, and it worked fine.

```
➜  ox.to.a.cart curl -x localhost:8787 https://globalconfig.flashlightproxy.com/global.yaml.gz > /tmp/global.yaml.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 45293  100 45293    0     0  10421      0  0:00:04  0:00:04 --:--:-- 10424
```

I gunzipped and viewed the yaml, and it seemed complete.

**Comment by oxtoacart** [comment]
I do see the short write error in the logs, but not when I'm manually requesting the file.

**Comment by myleshorton** [comment]
This one's all set and a non-issue. The cause is dual-fetching. Whenever the chained response arrives second, proxied.go will close the response body. In that case, handler.go will see the connection appear to close prematurely, but that is intended. Thanks for the digging @oxtoacart!
