### ISSUE TITLE
手机重新刷机无法登陆

### ISSUE THREAD

**Issue by MrOne1981** [getlantern/lantern#5286]
专业版本注册邮箱6112214@qq.com,只有一部手机注册过，烦请处理

**Comment by MrOne1981** [comment]
动态授权码274688，为什么不能用账户密码方式登陆？还要做的这么麻烦

**Comment by p3rcya** [comment]
新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。
