### ISSUE TITLE
Add borda data visualizations to ops panel

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5288]
Some borda data would likely be very powerful to visualize and useful to have in the ops panel.

**Comment by oxtoacart** [comment]
We'll start by making a list of what we'd like to see and time box this.

It would be good to focus this on helping us get through support days faster.

1. Identify failing proxies

2. Dig into health of specific proxy

**Comment by oxtoacart** [comment]
Borda API for this is ready. @aranhoide Anything I can do to help on the front-end side?

**Comment by myleshorton** [comment]
FYI @aranhoide was just chatting with @uaalto about this one

**Comment by aranhoide** [comment]
@myleshorton If you want this to be done this sprint, I'm happy to do it; just move it to To Do.  I had already started research on this in the previous sprint before delayed-christmas-vacation. I had experimented with [some React-friendly visualization library](https://github.com/FormidableLabs/victory). I think the task I'm in will not take long, so I can do this next.

**Comment by aranhoide** [comment]
@myleshorton If you want this to be done this sprint, I'm happy to do it; just move it to To Do.  I had already started research on this in the previous sprint before delayed-christmas-vacation. I had experimented with [some React-friendly visualization library](https://github.com/FormidableLabs/victory). I think the task I'm in will not take long, so I can do this next.

**Comment by myleshorton** [comment]
Yeah let's do it @aranhoide!

Sorry the State grant got me off my ticketing game this sprint a bit -- just moved to TODO.

**Comment by myleshorton** [comment]
FYI @oxtoacart might be useful to think about the top borda queries it would be nice to have at our fingertips every day!

**Comment by myleshorton** [comment]
Other pieces that would be very useful:

1. Reading of data usage by percentile for free desktop devices
1. Reading of data usage by percentile for pro desktop devices
1. Reading of data usage by percentile for free android users
1. Reading of data usage by percentile for pro android users

**Comment by myleshorton** [comment]
It would also be very cool if we could see:

1. A breakdown of all free devices (Windows, OSX, Android)
1. A breakdown of all pro devices (including linked)

**Comment by myleshorton** [comment]
FYI @joesis a lot of this is stuff you've worked on - would be interesting to just always add things like that to the ops panel whenever we're doing repeated visualizations.

**Comment by uaalto** [comment]
Thanks @myleshorton. I'll work on those right after the heatmaps.

**Comment by oxtoacart** [comment]
Our next focus should be on datacenter health so we can detect things like our recent failed deployments. This could include, amongst other things, graphs of daily throughput per datacenter.

@uaalto and I should collaborate on this.

**Comment by aranhoide** [comment]
@uaalto's new visualizations have been finally merged and deployed. Closing this generic ticket; we can open more specific ones for future improvements in this area.
