### ISSUE TITLE
之前反馈了chrome无法登录lantern，一直转圈。现有新发现

### ISSUE THREAD

**Issue by lym7851824** [getlantern/lantern#5294]
因本人使用超极本，只能用wifi。而向朋友推荐安装此软件后，发现笔记本电脑通过有线上网可以解决（双方均使用chrome，网络为中国移动）。望开发人员能处理此情况。me：联想yoga11s。    friend：神州战神系列。
在通过安卓版已登录的lantern向我的邮箱发电脑版软件时，也不能收到，已反复尝试多次（不同时间段），本人使用163邮箱。

**Comment by p3rcya** [comment]
直接去论坛主页下载 https://github.com/getlantern/forum

**Comment by lym7851824** [comment]
:),已解决

**Comment by p3rcya** [comment]
好。请收藏下载页面，方便以后更新
