### ISSUE TITLE
是又被墙了还是怎么回事  这几天G家全线都上不去

### ISSUE THREAD

**Issue by JasonDarkness** [getlantern/lantern#5303]
一直提示Still unable to dial tcp://xx:80 after 3 attempts

**Comment by wanteracc** [comment]
我一直可以用啊

2016-09-21 21:29 GMT+08:00 LittleDarkOrz <notifications@github.com>:

**Comment by hinext** [comment]
欢迎测试shadowsocks.

www.note.pw

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
