### ISSUE TITLE
部分网络无法使用

### ISSUE THREAD

**Issue by zhengjieyuan** [getlantern/lantern#5304]
我下载的最新版本，在公司电信网络可以使用，家里的电信却用不了。难道有时段限制？

很奇怪的问题，帮忙看看什么问题呢？
[lantern.zip](https://github.com/getlantern/lantern/files/485171/lantern.zip)

**Comment by wanteracc** [comment]
需要我的版本不

在 2016年9月21日 下午9:50，zheng <notifications@github.com>写道：

**Comment by zhengjieyuan** [comment]
这个和版本有区别？你那是什么版本？

**Comment by wanteracc** [comment]
你电脑是不是安装迅雷了

2016-09-21 22:00 GMT+08:00 zheng <notifications@github.com>:

**Comment by zhengjieyuan** [comment]
嗯 装了啊 这个有影响？  我卸载试试

**Comment by wanteracc** [comment]
迅雷极速版装了很可能用不了 得设置一下

2016-09-21 22:22 GMT+08:00 zheng <notifications@github.com>:

**Comment by wanteracc** [comment]
你把迅雷极速版卸载了试试

2016-09-21 22:23 GMT+08:00 wanter <wanteracc@gmail.com>:

**Comment by zhengjieyuan** [comment]
卸载了  没有效果  还是不行     但是我在公司的网络可以用

**Comment by wanteracc** [comment]
重新安装一下蓝灯啊

2016-09-21 22:52 GMT+08:00 zheng <notifications@github.com>:

**Comment by wanteracc** [comment]
把IE里面的连接设置一下

2016-09-21 22:54 GMT+08:00 wanter <wanteracc@gmail.com>:

**Comment by p3rcya** [comment]
对，和迅雷极速版有冲突。

**Comment by ibrucekong** [comment]
把迅雷极速卸载后，可以了

**Comment by p3rcya** [comment]
好。那我关闭了
