### ISSUE TITLE
升级了macOS Sierra之后lantern假死，重装无效

### ISSUE THREAD

**Issue by watchzerg** [getlantern/lantern#5305]
刚才手贱升级了macOS Sierra，然后lantern pro就一直占CPU很高，连不上任何网站（不管有没有被墙），机器发烫。
重新下载并安装lantern也无法解决此问题。
100%确认与macOS Sierra有关，因为就在十几分钟前没升级macOS Sierra之前是一切正常的。
（版本：专业版）

<img width="813" alt="screen shot 2016-09-21 at 22 57 49" src="https://cloud.githubusercontent.com/assets/1014217/18716413/592da40e-804f-11e6-847b-6003b74961b6.png">

<img width="554" alt="screen shot 2016-09-21 at 22 57 56" src="https://cloud.githubusercontent.com/assets/1014217/18716486/96c4ee80-804f-11e6-9bcb-438c6515f885.png">

**Comment by p3rcya** [comment]
这个是已知问题，新版会兼容

**Comment by PanPanda** [comment]
新版什么时候发布

**Comment by brilliance-boy** [comment]
@p3rcya 新版本什么时候发布？

**Comment by lsiuhen** [comment]
各位问题解决了没有，新版本出来吗

**Comment by dongweiq** [comment]
同问

**Comment by p3rcya** [comment]
新版本月发布

**Comment by zRich** [comment]
我升级到sierra之后不能用，然后买了专业版，装了3.1.4，然后使用了半天，不是很稳定，经常断，现在有彻底不能用了，要么打不开，要么打开后很快就退！

**Comment by just4id** [comment]
看来花钱也不是办法啊...

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
