### ISSUE TITLE
[Mobile] Error prompt is different from server responded error message

### ISSUE THREAD

**Issue by joesis** [getlantern/lantern#5316]
The Chinese text means "Please input correct recovery code". Not a big deal.

![unnamed](https://cloud.githubusercontent.com/assets/22091642/18833460/51f428de-8423-11e6-9976-37f3e0101409.png)

**Comment by p3rcya** [comment]
So this error message is actually inaccurate. It should just return device limit reached. This is causing confusing among some users.

**Comment by atavism** [comment]
@p3rcy, okay, should be fixed. I added a new string to Transifex for this error whenever you're able to translate it! Thanks.

**Comment by p3rcya** [comment]
translated

**Comment by p3rcya** [comment]
@atavism just to confirm, the new error should be Device limit reached and say nothing about wrong recovery code

**Comment by joesis** [comment]
It was fast! Thanks @atavism !
