### ISSUE TITLE
卡巴斯基一直报毒

### ISSUE THREAD

**Issue by JDynamic** [getlantern/lantern#5323]
从这里下载了win最新版，安装之后卡巴斯基直接报毒清除。
之前用旧版一直没问题，最近这是怎么了？

**Comment by JDynamic** [comment]
还有个问题，现在只要蓝灯被清除或者被卸载，Chrome就无法联网，这是什么新的防卸载手段？

**Comment by p3rcya** [comment]
请加入白名单。

**Comment by lautis0503** [comment]
未完全卸载，系统代理设置未恢复，导致Chrome无法联网

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
