### ISSUE TITLE
Make some progress on securing secrets required by servers

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#5329]

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #266](https://github.com/getlantern/lantern-internal/issues/266) via [**ZenHub**](https://www.zenhub.com/)

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #267](https://github.com/getlantern/lantern-internal/issues/267) via [**ZenHub**](https://www.zenhub.com/)

**Comment by oxtoacart** [comment]
Thanks @p3rcya
