### ISSUE TITLE
Lantern 3.2.0 (20160922.022149)购买了2年现在变成1970/1/1 过期

### ISSUE THREAD

**Issue by yxwmok** [getlantern/lantern#5341]
Lantern 3.2.0 (20160922.022149)购买了2年现在变成1970/1/1 过期
[lantern.zip](https://github.com/getlantern/lantern/files/517603/lantern.zip)

**Comment by p3rcya** [comment]
请提供邀请码以及支付宝账号。请及时提供，否则我们无法调查。

**Comment by yxwmok** [comment]
你说的是动态授权码么？
动态授权码：384847
支付宝账号：youxiangwomeng@sina.com

**Comment by p3rcya** [comment]
处理了，请重新安装最新版 https://github.com/getlantern/forum 后登录。
