### ISSUE TITLE
Capture the error output of `pac-cmd` to Lantern logs

### ISSUE THREAD

**Issue by orbancanon** [getlantern/lantern#5349]
In case it fails, there's no clue what happened. Ref https://github.com/getlantern/forum/issues/1465

On Windows, the output of `pac-cmd` is disabled to prevent command window from popping up. Need a workaround to capture the content.

**Comment by joesis** [comment]
Resolved by https://github.com/getlantern/pac-cmd/pull/3 and https://github.com/getlantern/pac/pull/5
