### ISSUE TITLE
Free

### ISSUE THREAD

**Issue by anxiaokai** [getlantern/lantern#5350]
Is lantern free now ???

**Comment by p3rcya** [comment]
蓝灯永远可以免费使用。免费版每个月有800MB流量限制，但免费版流量用完之后还是可以继续使用，只是会限速而已，但浏览网页没有问题。

**Comment by wangcheng911** [comment]
我也发现我的流量超过了800M，但是还可以上网

**Comment by anxiaokai** [comment]
我的lantern很长世间都不能用了，一直连不上，即使偶尔连上，网速也非常非常的差。

**Comment by p3rcya** [comment]
@anxiaokai 请问你是什么网络？ 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。

**Comment by CHN008** [comment]
@p3rcya  蓝灯永远可以免费使用。免费版每个月有800MB流量限制，但免费版流量用完之后还是可以继续使用，只是会限速而已，但浏览网页没有问题。**只是会限速而已** 一般会限制在多少呢?

有一个# 问题是:Android版开启后,如果退出应用再上网会出现打不开网页的情况,必须要重启手机才好.
