### ISSUE TITLE
3.2.0 opens 127.0.0.1:abcd though default browser is Edge

### ISSUE THREAD

**Issue by joesis** [getlantern/lantern#5351]
I could consistently reproduce it on the Windows 10 VM. It has the following sequences:

1. Edge always fail to open the page.
2. Even if I open the correct *.lantern.io URL in Edge, Lantern backend refuses the request because it only accepts requests from `127.0.0.1:abcd`.

Adding to backlog directly as user just can't open the UI

**Comment by joesis** [comment]
One trick to avoid using `*.lantern.io` altogether would be to add Loopback exempt for Edge in the Lantern installer. The very same lines as https://github.com/qzind/qz-print/commit/b5defe8e7ad4e17f12bd4337c557d286dd9f6119. However, the URL should be `http://localhost:abcd/?1` instead of `http://127.0.0.1:abcd/?1`

Ref https://msdn.microsoft.com/en-us/library/windows/apps/Hh780593.aspx for the whole story.

**Comment by joesis** [comment]
Symptom: For some reason, Lantern opens `http://127.0.0.1:abcd` when the default browser is Edge. Edge fails to show UI at all.

Conclusions so far:

1. Per https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/how-can-i-debug-localhost/

    > Microsoft Edge **allows localhost access by default** but treats “localhost” as an Internet site, so Intranet features like single sign on are disabled.

2. For previous Win 10 versions, we need to do below in Lantern installer to allow Edge to access localhost ([ref](https://blogs.msdn.microsoft.com/msgulfcommunity/2015/07/01/how-to-debug-localhost-on-microsoft-edge/)). As Windows 10 auto-update is notoriously aggressive, we probably can skip that.

    ```
    CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe
    ```

3. We need to open `http://localhost:abcd/...` instead of `http://127.0.0.1:abcd/...` on Windows.

4. We can remove the Edge detection and the `*.lantern.io` alternative URL entirely next time to simplify the code.

Consider the impact of this issue, we may need to fix asap. @myleshorton @xiam your idea?

**Comment by myleshorton** [comment]
Huh strange. It's been working for me in general, but maybe there's an issue launching from the installer @joesis

**Comment by myleshorton** [comment]
When you say Lantern opens 127, from where are you talking about @joesis? On any run?

**Comment by joesis** [comment]
@myleshorton Yeah, whenever clicks "show Lantern" from the system tray. It's interesting there's no user reporting the same issue. Maybe something specific to my local environment (though it's a fresh Win 10 VM). Anyway, it's good if we can eliminate the issues related to `*.lantern.io`, say, the DNS hijacking, or when "set system proxy" is off.

**Comment by p3rcya** [comment]
I still cannot use Lantern at all on my windows 10 with edge

**Comment by myleshorton** [comment]
What versions of Windows 10? Just from the system tray for you @joesis right? There's actually an existing ticket for that one somewhere.

**Comment by myleshorton** [comment]
Hey @joesis our Edge detection logic is just a little broken, or at least that's one thing that's happening. Fix coming.

**Comment by joesis** [comment]
Thanks @myleshorton. Yeah I verified Lantern binary built with latest `edgedetect` opens correct "lantern.io" UI on Edge, though Edge can't show the page. I think it's an issue of Edge itself, as both Chrome and IE can open the same UI, and Edge can open blocked sites, whether they are https or http sites.

**Comment by joesis** [comment]
Ok, finally Edge can open the UI correctly. `glide up` always failed with following when I want to create PR in `flashlight` repo. Trying to find a workaroud.

```
[WARN]	Download failed.
[ERROR]	Update failed for gopkg.in/bsm/ratelimit.v1: Unable to update repository
[WARN]	Download failed.
[ERROR]	Update failed for gopkg.in/redis.v3: Unable to update repository
[ERROR]	Failed to do initial checkout of config: Unable to update repository
Unable to update repository
```
