### ISSUE TITLE
"-clear-proxy-settings" no longer works 

### ISSUE THREAD

**Issue by joesis** [getlantern/lantern#5354]
I forget if it was logged somewhere else. It's because `pac-cmd off <url>` won't clear PAC if `<url>` is different from current set one.

Ticket it as I'm playing with `pac-cmd` again for https://github.com/getlantern/lantern/issues/5346

**Comment by myleshorton** [comment]
We can solve this by just passing "" as the URL when turning off the proxy -- see windows.c

**Comment by joesis** [comment]
We match the old URL in `pac off` because of user complaints that Lantern
cleared proxy settings not set by Lantern. I made a simple change to
`pac-cmd` to match prefix instead.

**Comment by oxtoacart** [comment]
Even if we switch to using a system proxy instead of a PAC, we need to make sure that this still works.

**Comment by joesis** [comment]
The option still doesn't work with https://github.com/getlantern/pac-cmd/issues/3. Investigating.

**Comment by oxtoacart** [comment]
@joesis @myleshorton do you think this is a blocker for 3.2.3?

**Comment by joesis** [comment]
@oxtoacart @myleshorton It isn't. It only affects those Windows users who don't have Lantern start with the system.

But another issue the same PR solves, https://github.com/getlantern/lantern/issues/5346, is. Many users with the recent version of Windows 10 (not just the beta or insider review) reported the same issue and solved by updated `pac-cmd` binary.

**Comment by myleshorton** [comment]
Oh interesting, so it's affecting actually released Windows versions - ok
that changes things. I say we try to get it in then.

**Comment by myleshorton** [comment]
Hey @joesis what's the current status of this one?

**Comment by joesis** [comment]
Solved. Closing.
