### ISSUE TITLE
蓝灯是否同一个账号可在多台设备同时使用

### ISSUE THREAD

**Issue by Awent** [getlantern/lantern#5358]
意思是说我想同时在电脑和手机上使用蓝灯翻墙，那么用同一个账号是否支持电脑手机同时登陆

**Comment by p3rcya** [comment]
可以，最多3台同时使用

**Comment by hihell** [comment]
我在windows上装了lantern但是找不到登录的地方啊，有使用说明么？

**Comment by p3rcya** [comment]
@hihell 使用最新的3.2.5主界面用邮箱登陆。 下载地址 https://github.com/getlantern/forum

**Comment by cxyuyu** [comment]
如果多台同时登陆了会有什么后果呢

**Comment by chengshaohui** [comment]
可以，我同时在两台电脑上使用  不影响
