### ISSUE TITLE
OS X 10.11上无法启动lantern

### ISSUE THREAD

**Issue by smileDQYang** [getlantern/lantern#5361]
早上使用发现无法启动lantern，闪退
重启电脑后依旧
覆盖安装后依旧
卸载重新安装依旧

昨天还启动使用过，今天莫名其妙就挂了  =。=

**Comment by p3rcya** [comment]
卸载后，删除安装文件夹下所有文件，再重新安装试试

**Comment by smileDQYang** [comment]
是昨天早上更改过目录权限问题，修复后就可以正常使用了 谢谢~
