### ISSUE TITLE
dmg background image not appearing on OSX Sierra

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5375]

**Comment by myleshorton** [comment]
This is because svgexport/phantomjs keeps crashing for some reason and not generating the background png. Testable with things like:

```
svgexport installer-resources/darwin/dmgbackground_versioned.svg installer-resources/darwin/dmgbackground.png 600:400
```

**Comment by myleshorton** [comment]
I ended up solving this locally by modifying svgexport's package.json to point to the latest phantomjs, and that one doesn't crash on Sierra.

**Comment by myleshorton** [comment]
It seems there are actually multiple issues here. The first was the svgexport issue where that was failing to set the version in the svg. The second appears to be something up with appdmg where the background just doesn't appear regardless.

**Comment by myleshorton** [comment]
Hey @joesis, @oxtoacart, and @atavism does the background image appear for you in the dmg on Sierra?

**Comment by oxtoacart** [comment]
@myleshorton Nope. I think I noticed this with some other installer recently too.

**Comment by oxtoacart** [comment]
Here's a potential solution - https://github.com/LinusU/node-appdmg/issues/121#issuecomment-251730237

**Comment by oxtoacart** [comment]
More solution details here - https://github.com/LinusU/node-appdmg/issues/121#issuecomment-251154358

**Comment by oxtoacart** [comment]
The linked solution is just a perl script.

**Comment by myleshorton** [comment]
Nice find @oxtoacart -- I'll try it!

**Comment by myleshorton** [comment]
It's actually a shell script that also uses that perl script, but seems like it should theoretically work with a little work.

**Comment by myleshorton** [comment]
Hmnn...got stuck in perl module hell. Might keep banging away but the imports aren't currently building from 64 bit perl.

**Comment by myleshorton** [comment]
Apple fixed this.
