### ISSUE TITLE
代理全部流量 是什么意思？

### ISSUE THREAD

**Issue by Jerry-goodboy** [getlantern/lantern#5380]
<img width="651" alt="2016-10-30 13 57 02" src="https://cloud.githubusercontent.com/assets/9030784/19834789/790f004c-9ea9-11e6-94b6-2e429593912d.png">

**Comment by Jerry-goodboy** [comment]
@marcenuc @fuentesjr @michaelneale @robertkrimen @sdboyer

**Comment by michaelneale** [comment]
not sure if you meant to mention me @Jerry-goodboy  ;)

**Comment by StoneFu2015** [comment]
ios版本什么时候出啊？！
