### ISSUE TITLE
然后呢，要再下下个版本开能定端口是吧？

### ISSUE THREAD

**Issue by bdironbox** [getlantern/lantern#5382]
然后呢，要再下下个版本开能定端口是吧？
然后呢，要再下下个版本开能定端口是吧？

**Comment by p3rcya** [comment]
你先看看精华帖。现在需要设置的，请这里 https://github.com/getlantern/forum/issues/1674 下个版本会在用户界面显示

**Comment by p3rcya** [comment]
蓝灯3.3.5版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
