### ISSUE TITLE
Error: No trusted dialers!

### ISSUE THREAD

**Issue by kashu** [getlantern/lantern#5397]
Lantern Version： 3.3.4
OS：Xubuntu 14.04.5 LTS 64-bit

When I open a website, the browser displayed a sentence as following.

> No trusted dialers!

**Comment by myleshorton** [comment]
What version of lantern are you using? Can you send us your logs?

**Comment by kashu** [comment]
@myleshorton   Thank you for your reply.

I resolved it by myself and it works. I installed lantern **(**but I'm sure I had already uninstalled the old version of lantern before install the latest version of lantern, I usually do it like this when I'm going to update the lantern**)** and modified the startup parameters long time ago. I forgot it, but I'm still use the old startup parameters to try to launch the latest version of lantern, so this error occurred.

```
$ ll ~/.lantern/*
-rw-r--r-- 1 kashu kashu 1.2M Nov  5 22:28 /home/kashu/.lantern/global.yaml
-rw-r--r-- 1 kashu kashu 569K Feb 14  2016 /home/kashu/.lantern/lantern-2.0.10.yaml
-rw-r--r-- 1 kashu kashu 569K Feb 14  2016 /home/kashu/.lantern/lantern-2.0.12.yaml
-rw-r--r-- 1 kashu kashu 322K Feb 19  2016 /home/kashu/.lantern/lantern-2.0.13.yaml
-rw-r--r-- 1 kashu kashu 322K Feb 19  2016 /home/kashu/.lantern/lantern-2.0.15.yaml
-rw-r--r-- 1 kashu kashu 278K Mar 17  2016 /home/kashu/.lantern/lantern-2.0.16.yaml
-rw-r--r-- 1 kashu kashu 215K Apr 21  2016 /home/kashu/.lantern/lantern-2.1.1.yaml
-rw-r--r-- 1 kashu kashu 199K Nov  4 19:33 /home/kashu/.lantern/lantern-2.1.2.yaml
-rw-r--r-- 1 kashu kashu    2 Nov  4 20:29 /home/kashu/.lantern/lantern.yaml
lrwxrwxrwx 1 kashu kashu    9 Mar  7  2016 /home/kashu/.lantern/logs -> /dev/null
-rw-r--r-- 1 kashu kashu 1.2K Nov  5 21:12 /home/kashu/.lantern/masquerade_cache
-rw-r--r-- 1 kashu kashu  632 Nov  5 22:28 /home/kashu/.lantern/proxies.yaml
-rw------- 1 kashu kashu 1.7K Jan  9  2016 /home/kashu/.lantern/proxypk.pem
-rw-rw-r-- 1 kashu kashu 1.1K Jan  9  2016 /home/kashu/.lantern/servercert.pem
-rw-r--r-- 1 kashu kashu  292 Nov  5 22:28 /home/kashu/.lantern/settings.yaml
```

**Comment by myleshorton** [comment]
Glad it's working! I would recommend trying the new version too - 3.3.5 should be super fast in particular - https://github.com/getlantern/lantern for debian downloads.

**Comment by kashu** [comment]
Yeah, the new version is pretty fast! Thank you.

**Comment by myleshorton** [comment]
Oh good! Please let us know whenever you have any issues.
