### ISSUE TITLE
今天下载的最新版本无法支付，付款人在上海

### ISSUE THREAD

**Issue by datatechboost** [getlantern/lantern#5408]

**Comment by datatechboost** [comment]
支付页面一直打不开

**Comment by datatechboost** [comment]
尝试了好多次一直是正在加载支付页面，ie和google浏览器都不行

**Comment by aoqi521qwe** [comment]
输入我的邀请码 Y4K6T7M 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by hinext** [comment]
欢迎测试shadowsocks.

www.note.pw

**Comment by hinext** [comment]
欢迎测试shadowsocks.

www.note.pw

**Comment by cvsyun013** [comment]
楼上这个傻逼一个劲反麻痹啊

**Comment by datatechboost** [comment]
一个早上终于打开付款页面了，已经使用同事的邀请码购买了——
