### ISSUE TITLE
Error piping data to downstream: connection reset by peer

### ISSUE THREAD

**Issue by joesis** [getlantern/lantern#5413]
I saw the errors from basically every user logs I checked (3.3.5) . The sites including borda, pro-server and global config so far, but no user accessed sites.

I saw the same error when testing borda traffic reporting. Request to borda always failed.

> Nov 07 00:57:42.511 - 0m43s ERROR flashlight.client: handler.go:25 Error piping data to downstream: connection reset by peer [error=Error piping data to downstream: %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).connect (proxy_connect.go:116) error_op= error_text=Error piping data to downstream: connection reset by peer error_type=errors.Error op=proxy origin_host=api.getiantem.org origin_port=443 root_op=proxy user_agent=Go-http-client/1.1]
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).connect (proxy_connect.go:116)
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).(github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.connect)-fm (proxy_connect.go:46)
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/client.(*Client).ServeHTTP (handler.go:23)
ERROR flashlight.client: handler.go:25   at net/http.serverHandler.ServeHTTP (server.go:2202)
ERROR flashlight.client: handler.go:25   at net/http.(*conn).serve (server.go:1579)
ERROR flashlight.client: handler.go:25   at runtime.goexit (asm_386.s:1612)
ERROR flashlight.client: handler.go:25 Caused by: connection reset by peer

Adding to backlog as it looks like a bug

**Comment by joesis** [comment]
The https://github.com/getlantern/netx/blob/master/copy.go#L65. Here's the error when I added log printing there.

> Nov 07 11:27:59.449 - 5m54s ERROR netx: copy.go:72 read error from <proxy-addr>, connection reset by peer [error=read error from %s, %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/netx.doCopy (copy.go:71) error_op= error_text=read error from 104.199.213.52:35645, connection reset by peer error_type=errors.Error]
ERROR netx: copy.go:72   at github.com/getlantern/flashlight/vendor/github.com/getlantern/netx.doCopy (copy.go:71)
ERROR netx: copy.go:72   at runtime.goexit (asm_amd64.s:2086)
ERROR netx: copy.go:72 Caused by: connection reset by peer

**Comment by myleshorton** [comment]
I'm seeing this as well just running the client. This one is interestingly a connection from an app in my menu bar, so likely a long lived connection that was quite likely idle:

```
Nov 07 21:39:40.376 - 28m37s ERROR flashlight.client: handler.go:25 Error piping data to downstream: connection reset by peer [error=Error piping data to downstream: %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).connect (proxy_connect.go:116) error_op= error_text=Error piping data to downstream: connection reset by peer error_type=errors.Error op=proxy origin_host=secure.screenhero.com origin_port=443 root_op=proxy user_agent=Screenhero/2.3.10.0 Sparkle/1.13.1]
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).connect (proxy_connect.go:116)
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).(github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.connect)-fm (proxy_connect.go:46)
ERROR flashlight.client: handler.go:25   at github.com/getlantern/flashlight/client.(*Client).ServeHTTP (handler.go:23)
ERROR flashlight.client: handler.go:25   at net/http.serverHandler.ServeHTTP (server.go:2202)
ERROR flashlight.client: handler.go:25   at net/http.(*conn).serve (server.go:1579)
ERROR flashlight.client: handler.go:25   at runtime.goexit (asm_amd64.s:2086)
ERROR flashlight.client: handler.go:25 Caused by: connection reset by peer
```

**Comment by myleshorton** [comment]
Other incarnations of this also loosely look like idle connections that were closed.

**Comment by joesis** [comment]
That should be it!  KCP's `Close()` method may just reset all the streams, instead of io.EOF when reading from closed TCP connection. Still need to figure out why I only saw it when accessing Lantern internal services.

**Comment by myleshorton** [comment]
That totally makes sense @joesis and sounds like it could cause other issues. @oxtoacart just FYI on this one.

**Comment by joesis** [comment]
To be accurate, it's `smux` package caused the error. `smux.Stream.Close()` sends `cmdRST` to the remote end if it's not already closed (https://github.com/xtaci/smux/blob/master/stream.go#L105), and the remote end returns `errConnReset` when the flag is seen (https://github.com/xtaci/smux/blob/master/stream.go#L64). `cmdRST` is actually a flag for stream closing (https://github.com/xtaci/smux/blob/master/frame.go#L13), so it's a normal status rather than an error condition.

**Comment by joesis** [comment]
The simplest fix should be have `Stream.Read()` return `io.EOF` in this case. Created https://github.com/xtaci/smux/issues/6. We can fork it and do the change ourselves when required.

**Comment by joesis** [comment]
Fixed by https://github.com/xtaci/smux/commit/60c611f2ff7411e1493071745a7f3f89e25ac624. Net `glide up` should bring the change in.
