### ISSUE TITLE
Various Edge errors can be solved through switching our UI URL to "localhost"

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5415]
Seeing this fairly often in logs:

```
Nov 07 06:14:50.061 - 0m2s DEBUG edgedetect: edgedetect_windows.go:12 Error reading DefaultBrowserServer registry key: The system cannot find the file specified.
Nov 07 06:14:50.061 - 0m2s ERROR edgedetect: edgedetect_windows.go:46 Could not read FriendlyTypeName: The system cannot find the file specified. [error=Could not read FriendlyTypeName: %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/edgedetect.checkURLAssociations (edgedetect_windows.go:46) error_op= error_text=Could not read FriendlyTypeName: The system cannot find the file specified. error_type=errors.Error]
```

On at least one of these systems, however, there was also a permission denied error working with the registry for auto-start:

```
Nov 07 06:05:51.367 - 0m0s ERROR launcher: launcher_windows.go:38 Error setting Lantern auto-start registry key: "Access is denied." [error=Error setting Lantern auto-start registry key: %q error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/launcher.CreateLaunchFile (launcher_windows.go:38) error_op= error_text=Error setting Lantern auto-start registry key: "Access is denied." error_type=errors.Error]
```

**Comment by myleshorton** [comment]
The above was on 3.3.2.

**Comment by myleshorton** [comment]
One option here is to just switch our local URL to localhost, which is allowed in newer Edge versions. Let's do this!

**Comment by joesis** [comment]
To be clear, localhost is enabled by default in Edge since Windows build 10166, see [changelog](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/10166/?compareWith=10166).

**Comment by joesis** [comment]
We must carefully test in dual stack environment.

**Comment by joesis** [comment]
Interesting, even 127.0.0.1 works with Edge.

**Comment by joesis** [comment]
I'm downloading a fresh Windows 10 Pro edition to see if if 127.0.0.1 works by default.

**Comment by joesis** [comment]
Fresh Pro and Home edition can open localhost:xxx, but can't open 127.0.0.1:xxx reliably.

**Comment by oxtoacart** [comment]
@joesis The PR for this is ready to review, right?

**Comment by joesis** [comment]
Yeah @oxtoacart, ready to review now.

**Comment by joesis** [comment]
It's in production
