### ISSUE TITLE
Desktop shortcut tried to open Lantern on 127.0.0.1 when default browser was Edge

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5423]

**Comment by myleshorton** [comment]
Hey @joesis it looks like Lantern should be at least trying to use the correct Edge address in this line right?

https://github.com/getlantern/flashlight/blob/devel/ui/ui.go#L217

**Comment by joesis** [comment]
Oh sorry, I misinterpreted the title. What I saw is totally different. Logged at https://github.com/getlantern/lantern/issues/5425

**Comment by joesis** [comment]
This makes me come back to the idea of eliminating *.lantern.io altogether and stick with UI address of `localhost:abcd`. Newer versions of Edge allow access from localhost by default.

**Comment by myleshorton** [comment]
Yeah that sounds way better @joesis I agree.

**Comment by myleshorton** [comment]
Subsumed by https://github.com/getlantern/lantern/issues/5415
