### ISSUE TITLE
最新的专业版本，频繁崩溃啊

### ISSUE THREAD

**Issue by gfreewind** [getlantern/lantern#5426]
Win10系统，最新的lantern专业版本，每天都要崩溃个十几次。

**Comment by hinext** [comment]
欢迎测试shadowsocks.

www.note.pw

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892

**Comment by cunteng008** [comment]
为什么我支付宝账号输入完全正确了还一直提示"Alipay is unavailable currently."
