### ISSUE TITLE
2.2.5版不稳定？这几天经常用不了。

### ISSUE THREAD

**Issue by Jason4774** [getlantern/lantern#5427]
2.2.5版不稳定？这几天经常用不了。
有人知道怎么回事吗？

**Comment by p3rcya** [comment]
请用最新的版本 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
请用最新的3.3.7，下载 https://github.com/getlantern/forum

**Comment by Jason4774** [comment]
谢谢，请问最新的有流量限制吗？

**Comment by p3rcya** [comment]
蓝灯永远可以免费使用。免费版每个月有800MB流量限制，但免费版流量用完之后还是可以继续使用，只是会限速而已，但浏览网页没有问题。
