### ISSUE TITLE
lantern不工作了,无法登陆GOOGLE和youtobe,怎么解决,望帮忙

### ISSUE THREAD

**Issue by xuzy1966** [getlantern/lantern#5428]

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by xuzy1966** [comment]
登陆google时显示:Still unable to dial tcp://www.google.com:80 after 3 attempts
  #5240 








长春,联通
