### ISSUE TITLE
mac 10.12.1，lantern 3.3.5、3.3.6、3.3.7。只要一访问网络，就崩溃

### ISSUE THREAD

**Issue by 315301615** [getlantern/lantern#5432]
如标题所描述，只要一访问 google 就会崩溃，甚至什么也不做。
email：315301615@qq.com

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by 315301615** [comment]
[lantern.log.zip](https://github.com/getlantern/lantern/files/586996/lantern.log.zip)

**Comment by orbancanon** [comment]
@315301615 经确认是SOCKS代理部分的代码有点问题，正在查找原因。在修复前，请先使用HTTP代理。

**Comment by 315301615** [comment]
@p3rcya @orbancanon 
mac：10.12.1
lantern：3.3.5、3.3.6、3.3.7
firefox：49.0.2
1、只想让 firefox 翻墙于是就如下设置，但是一使用就崩溃了。
HTTP(S)代理服务器：127.0.0.1:50149
SOCKS代理服务器：127.0.0.1:50148
2、后来采用 firefox自动代理配置PAC, lantern就没有问题不会崩溃。
http://127.0.0.1:50135/proxy_on.pac?nocache=1479027416306132903&token=86eed0f07548a93526b56d50b39345f2
我没看源码，所以使用这种方法，token的有效性是多久？

**Comment by joesis** [comment]
@315301615 你只用HTTP(S)代理的话就不会崩溃。token每次Lantern启动会变

**Comment by orbancanon** [comment]
@315301615 你只用HTTP(S)代理的话就不会崩溃。token每次Lantern启动会变

**Comment by 315301615** [comment]
@orbancanon 多谢，按照指示操作已经能正常使用
