### ISSUE TITLE
lantern不工作了,2.2.5版,无法登陆google和youtube

### ISSUE THREAD

**Issue by xuzy1966** [getlantern/lantern#5435]
lantern不工作了,长春,联通宽带,登陆google显示:Still unable to dial tcp://www.google.com:80 after 3 attempts,toutubu也登陆不上,望帮忙解决,谢谢

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by p3rcya** [comment]
请用最新的3.3.7，下载 https://github.com/getlantern/forum
