### ISSUE TITLE
lantern4天不工作了2.2.5版

### ISSUE THREAD

**Issue by xuzy1966** [getlantern/lantern#5437]
lantern4天不工作了2.2.5版,长春,联通宽带,无法翻墙,无法登陆google和youtube,登陆时显示:Still unable to dial tcp://www.google.com:80 after 3 attempts,怎么解决,望能帮忙多谢

**Comment by p3rcya** [comment]
旧版容易被GFW流量指纹分析，比较容易封杀。
请用最新的3.3.7，下载 https://github.com/getlantern/forum

**Comment by xuzy1966** [comment]
3.3.3版是免费的吗

**Comment by Hardy5012** [comment]
我用3.3.7怎么也不用翻墙

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
