### ISSUE TITLE
Lantern 3.3.7 (20161112.005141)突然无法使用

### ISSUE THREAD

**Issue by woooool** [getlantern/lantern#5439]
无法访问受限制的网站，但是小几率能连上一下。

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by woooool** [comment]
谢谢，已恢复正常。

**Comment by p3rcya** [comment]
https://github.com/getlantern/forum/issues/1892
