### ISSUE TITLE
Expire CloudFront cache when we release new versions

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5440]
We currently don't expire the CloudFront cache for our sites that host Lantern installers, so they're not updated when we release new versions. This should be in the Makefile or in a script called from the Makefile.

**Comment by myleshorton** [comment]
Hey @atavism this one seems pretty important too -- the current script doesn't invalidate the old caches. @joesis you might want to take a look at this one too since you did it manually recently. pretty easy with boto at least.

**Comment by joesis** [comment]
`awscli` should do the trick.Trying

**Comment by myleshorton** [comment]
Awesome @joesis thanks
