### ISSUE TITLE
Recover account dialog can't transit to next dialog on IE

### ISSUE THREAD

**Issue by orbancanon** [getlantern/lantern#5442]
Reported by user at https://github.com/getlantern/forum/issues/1722

Reproduced it on IE 10 too. Console shows `Unknown dialog -- add it to the switch?[object Object]`.

**Comment by joesis** [comment]
Kinda critical as it affects even the latest IE users

**Comment by myleshorton** [comment]
Is this one still an issue @joesis?

**Comment by joesis** [comment]
Fixed by 6dadb12eb362d66bc820406849ff5f6446ac47b8

**Comment by myleshorton** [comment]
Perfect thanks @joesis!
