### ISSUE TITLE
android更新至最新版，一启动就闪退

### ISSUE THREAD

**Issue by atoper** [getlantern/lantern#5446]
目前根本无法使用，望修复
另外，这种情况下，付费用户的时间怎么处理？能顺延在增加吗？

**Comment by wiky1024** [comment]
我也是android 3.3.4版，专业版，开启后两秒闪退，没法用

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
