### ISSUE TITLE
Chrome frequently marks Lantern as bad proxy

### ISSUE THREAD

**Issue by joesis** [getlantern/lantern#5447]
Could be Lantern didn't respond within a reasonable time.

**Comment by joesis** [comment]
Saw it frequently in poor network condition. Chrome would not use Lantern again in several minutes. Can be a good candidate to figure out.

Here's one example entry of chrome://net-internals/#events on the test PC when it happens. It suggests that Lantern client should not response HTTP OK until it got the response of the  CONNECT request.

```
t= 86305 [st=    0] +HTTP_STREAM_JOB  [dt=41763]
                     --> alternative_service = "Uninitialized :0"
                     --> original_url = "https://www.google.co.jp/"
                     --> priority = "HIGHEST"
                     --> source_dependency = 824355 (URL_REQUEST)
                     --> url = "https://www.google.co.jp/"
t= 86305 [st=    0]   +PROXY_SERVICE  [dt=0]
t= 86305 [st=    0]      PROXY_SERVICE_RESOLVED_PROXY_LIST
                         --> pac_string = "PROXY 127.0.0.1:18345;DIRECT"
t= 86305 [st=    0]   -PROXY_SERVICE
t= 86305 [st=    0]   +HOST_RESOLVER_IMPL_REQUEST  [dt=0]
                       --> address_family = 0
                       --> allow_cached_response = true
                       --> host = "www.google.co.jp:443"
                       --> is_speculative = false
t= 86305 [st=    0]      HOST_RESOLVER_IMPL_IPV6_REACHABILITY_CHECK
                         --> cached = true
                         --> ipv6_available = false
t= 86305 [st=    0]      HOST_RESOLVER_IMPL_CACHE_HIT
t= 86305 [st=    0]   -HOST_RESOLVER_IMPL_REQUEST
t= 86305 [st=    0]   +SOCKET_POOL  [dt=29984]
t=116289 [st=29984]      SOCKET_POOL_BOUND_TO_CONNECT_JOB
                         --> source_dependency = 824366 (CONNECT_JOB)
t=116289 [st=29984]   -SOCKET_POOL
                       --> net_error = -118 (ERR_CONNECTION_TIMED_OUT)
t=116289 [st=29984]    PROXY_LIST_FALLBACK
                       --> bad_proxy = "127.0.0.1:18345"
t=116289 [st=29984]   +HOST_RESOLVER_IMPL_REQUEST  [dt=1]
                       --> address_family = 0
                       --> allow_cached_response = true
                       --> host = "www.google.co.jp:443"
                       --> is_speculative = false
t=116290 [st=29985]      HOST_RESOLVER_IMPL_IPV6_REACHABILITY_CHECK
                         --> cached = false
                         --> ipv6_available = false
t=116290 [st=29985]      HOST_RESOLVER_IMPL_CACHE_HIT
t=116290 [st=29985]   -HOST_RESOLVER_IMPL_REQUEST
t=116290 [st=29985]   +SOCKET_POOL  [dt=11778]
t=128068 [st=41763]      SOCKET_POOL_BOUND_TO_CONNECT_JOB
                         --> source_dependency = 824243 (CONNECT_JOB)
t=128068 [st=41763]   -SOCKET_POOL
                       --> net_error = -118 (ERR_CONNECTION_TIMED_OUT)
t=128068 [st=41763]    HTTP_STREAM_JOB_BOUND_TO_REQUEST
                       --> source_dependency = 824355 (URL_REQUEST)
t=128068 [st=41763] -HTTP_STREAM_JOB
```

**Comment by myleshorton** [comment]
Free or pro @joesis?

**Comment by myleshorton** [comment]
Why do you say it suggests making the connection first?

**Comment by joesis** [comment]
Actually, it's caused by the recent change of not responding 200 OK until got the response, and dialing proxies took > 30s to time out.

**Comment by joesis** [comment]
@myleshorton It affects both free and pro users, but only on poor network. Using `context.Context` across different layers could solve it and make a more flexible structure. I have some progress on this today.

**Comment by myleshorton** [comment]
Sounds great @joesis! I didn't realize we now don't respond with a 200 OK until the actual response comes in. I'll look at that as well.

**Comment by myleshorton** [comment]
FYI @oxtoacart

**Comment by oxtoacart** [comment]
@myleshorton 

> I didn't realize we now don't respond with a 200 OK until the actual response comes in. I'll look at that as well.

To be precise, we respond with 200 OK once we've successfully dialed the upstream proxy and it has successfully dialed the upstream server.

**Comment by oxtoacart** [comment]
It looks like the client has always waited for the OK response from the proxy server, but it used to be that the proxy server responded OK before even dialing upstream:

https://github.com/getlantern/proxy/blob/master/proxy_connect.go#L98

So the change is that we now wait to dial upstream before responding OK. In some sense, that seems more correct to me, because if the proxy has trouble dialing out but it's already responded OK, all it can do is drop the connection.

**Comment by myleshorton** [comment]
> It looks like the client has always waited for the OK response from the proxy server, but it used to be that the proxy server responded OK before even dialing upstream:

That code has changed a bunch of times, and we've done both at different points. At least this far back we would wait to hit our proxy only:

https://github.com/getlantern/lantern/blob/04dd91fd33d1847887952ba40470747820d85df4/src/github.com/getlantern/flashlight/client/handler.go#L94

> So the change is that we now wait to dial upstream before responding OK. In some sense, that seems more correct to me, because if the proxy has trouble dialing out but it's already responded OK, all it can do is drop the connection.

I definitely agree it's more correct -- I think that's actually how the spec requires it. But not if it means Lantern gets marked as bad proxy more often! It's just a matter of what works.

**Comment by oxtoacart** [comment]
> I definitely agree it's more correct -- I think that's actually how the spec requires it. But not if it means Lantern gets marked as bad proxy more often! It's just a matter of what works.

I think the downside to aggressively responding with 200 OK is that the browser loses the ability to bypass the proxy for sites that are unreachable by the proxy. As long as you don't turn on "Proxy All" that's not a big deal, since we're mostly going to only proxy stuff that's not reachable locally anyway. However, if "Proxy All" is on, it's entirely conceivable that there are sites that the client machine can reach that the proxy server can't reach. For that case though, we could potentially just fall back to dialing direct from our proxy.

**Comment by oxtoacart** [comment]
BTW, I agree that we should respond 200 OK immediately to avoid getting flagged as a bad proxy (sorry I didn't make that clear earlier). I'm just trying to understand all the implications.

**Comment by myleshorton** [comment]
> I think the downside to aggressively responding with 200 OK is that the browser loses the ability to bypass the proxy for sites that are unreachable by the proxy. 

So to be clear when this happens Chrome disables all traffic to Lantern and just goes directly for everything. I think the tricky aspect is that it makes it seem like Lantern's completely broken to the user.

Big picture, of course, if we fixed what was actually going wrong we wouldn't have this issue, but I think with the network flakiness we've seen that might be difficult to achieve in practice.

**Comment by oxtoacart** [comment]
> Big picture, of course, if we fixed what was actually going wrong we wouldn't have this issue, but I think with the network flakiness we've seen that might be difficult to achieve in practice.

Yeah, and this isn't entirely within our control. If there's a problem dialing the origin, that could cause issues too. We can mitigate that somewhat by making sure that we have an appropriate timeout on the dial to origin.

**Comment by joesis** [comment]
wip at https://github.com/getlantern/flashlight/pull/134
