### ISSUE TITLE
这玩意怎么好意思出来骗钱！有良心不？

### ISSUE THREAD

**Issue by jindongwang** [getlantern/lantern#5459]
付费版，自从付费后从来没正常用过，之前免费版还用的好好的。经历过各种调整加重装系统，仍然没法用。就这样的东西，还好意思出来骗钱？有同感的请顶这个帖子，让他们还钱！

**Comment by Neo-Lu** [comment]
我也是付费版呀，一直很流畅。。。我之前遇到过一次不能翻墙的情况，后来排查是chrome浏览器插件冲突造成的，你用隐私模式试试看。。。

**Comment by krast** [comment]
放弃lantern，自己搭的ocserv和spdy很稳定

On Nov 22, 2016, at 11:43 AM, 棒棒哒 <notifications@github.com<mailto:notifications@github.com>> wrote:


我也是付费版呀，一直很流畅。。。我之前遇到过一次不能翻墙的情况，后来排查是chrome浏览器插件冲突造成的，你用隐私模式试试看。。。

**Comment by basebase** [comment]
不会吧，我觉得付费升级专业版明显比免费的快了

**Comment by qdzxytt** [comment]
同觉得付费版比免费版还要难用，觉得180块砸了

**Comment by balabi0github** [comment]
顶，就是骗钱的。没一天好用

**Comment by p3rcya** [comment]
请使用程序内置的反馈功能，会上传日志。你这样发帖我们没法调查

**Comment by balabi0github** [comment]
@p3rcya  这个帖子为什么就被关掉了。我每次遇到翻不动就点击“报告问题‘’，我报告了不下十几次了，有时候还怎么都发送不出去！ 但是没有一次有回复的，石沉大海而已。            报告问题之后，我也没见变好用了，还是老样子，卡的时间比不卡的时间多得多。我所处的网络环境就那么几个，每个网络环境我都报告过，按理说早该修好了吧。

**Comment by p3rcya** [comment]
@balabi0github 已经在你的帖子里面回复

**Comment by basebase** [comment]
@p3rcya 建议做一个试用期，例如试用15天。这样的话觉得不错的用户可以进行购买，觉得不行的用户也可以不进行购买

**Comment by theratlesnake** [comment]
@krast spdy可以翻墙？

**Comment by krast** [comment]
@theratlesnake  可以，性能很赞
