### ISSUE TITLE
信用卡安全如何保证？

### ISSUE THREAD

**Issue by liuyuhang** [getlantern/lantern#5463]
今天本来想付款买个一年的，发现支付宝用不了，然后打开信用卡网页，这些敏感信息给你，怎么保证资金安全呢，又不是权威第三方支付，开发组要想一下付款的方式，这种方式是绝对不成的，以上建议

**Comment by JedLee** [comment]
同意，一看这信用卡付费界面就不对劲

**Comment by p3rcya** [comment]
信用卡这种问题早就解释过了。你是程序员，就应该能读明白
#335 (comment)

**Comment by weakish** [comment]
@p3rcya 你贴的链接点击会跳转到 https://github.com/getlantern/lantern/issues/335

**Comment by britainlondon** [comment]
Lantern - Better than a VPN - https://getlantern.org 
lantern payment code (for fanqiang):
Use my code X4RMBJ and get 3 months free when you sign up!
