### ISSUE TITLE
无法支付请问如何解决

### ISSUE THREAD

**Issue by moumura** [getlantern/lantern#5468]
我有两台电脑，一台3.4.2无法支付，点击购买后转了几圈又回到之前的“升级到专业版”页面；另一台电脑版本老点，可以到支付界面但支付宝提示暂时不可用，用信用卡试了三张：银联、银联JCB、银联美国运通，均提示支付被拒，请问怎么解决

**Comment by moumura** [comment]
刚刚支付又成功了。。。难道还分工作时间么。。。any way~请使用我的邀请码 YJ36WBT

**Comment by hhxjzyr** [comment]
请问你是怎么支付成功的呢？我的支付宝一直不行

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
