### ISSUE TITLE
为什么lantern自动更新了？

### ISSUE THREAD

**Issue by hitzhangjie** [getlantern/lantern#5470]
为什么lantern自动更新到新版本了，代理端口都变了，fuck！！！！！

**Comment by TPS404Error** [comment]
我的也自动更新了 安装目录多了个.lantern.exe.old 你的也是一样？= =

**Comment by helloworld3838** [comment]
@TPS404Error 你试试把.lantern.exe.old改成lantern.exe再打开试试？
------------------------------------------------------------------------------------------
[https://github.com/siyu1915/lantern](https://github.com/siyu1915/lantern)
我刚刚把Lantern整合了一下，你们可以解压再打开Lantern.exe文件（是2.2.5并且不会自动更新）

**Comment by p3rcya** [comment]
@helloworld3838 旧版会被GFW流量分析，请不要使用

**Comment by p3rcya** [comment]
@helloworld3838 请删除上述的repo，谢谢

**Comment by amoebaba** [comment]
@helloworld3838 你好，方便联系一下吗？amoebaba@163.com

**Comment by gfyond** [comment]
我也是啊
