### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#5474]
I'm using the latest release (pro). After a while of running (several hours), lantern seems to always come to a state where `socket: too many open files` in the log and no website can be open anymore, lantern page cannot be open either. I have to kill the process and relaunch it to make it work again.

Looks related to https://github.com/getlantern/lantern/issues/5095

**Comment by myleshorton** [comment]
Hey sorry for the delay in responding @renkun-ken, but this should hopefully be fixed in the latest versions. Are you still seeing this issue?

**Comment by renkun-ken** [comment]
It seems that this problem is gone in the latest release. Thanks!
