### ISSUE TITLE
为什么无法用支付宝付款？

### ISSUE THREAD

**Issue by water137780117** [getlantern/lantern#5477]
点击pay弹出提示：Alipay is current unavailable. Please select another payment method.

**Comment by ddkf2001** [comment]
可以用支付宝和银联卡支付购买了，只买了一年的使用权试试看。我的邀请码：输入我的邀请码 GCJHNN 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by water137780117** [comment]
@ddkf2001 已经买了，你应该增加了30天。

**Comment by ddkf2001** [comment]
哈哈，我用其他网友的邀请码购买后就是395天了，蓝灯笼速度还行
