### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by spencerpomme** [getlantern/lantern#5484]
No longer functional since approximately 10 days ago. Can't access to facebook, twitter, etc.
Also, the new version of latern homepage is failing, the functions including 'reporting issues'(报告问题) can not be accessed.
More strangely, when lantern is on, most accessible websites become inaccessible too, like github and codeacademy, etc.

The lantern install package I'm using is downloaded from [here](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe)

**Comment by p3rcya** [comment]
Maybe your proxy server is blocked. Are you using the free version or the pro version?

**Comment by spencerpomme** [comment]
I’m using free version.

**Comment by spencerpomme** [comment]
Somehow it recovered. I assume the server is reset or rearranged?
