### ISSUE TITLE
pro日本的服务器速度巨慢

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/lantern#5493]
每次给我切到日本服务器基本就没法用了，谷歌搜索都要10秒中左右，自从用了长城宽带一直是这样，能查查么？

**Comment by p3rcya** [comment]
正在调查

**Comment by p3rcya** [comment]
我们调查了下，发现是长城宽带的出国带宽的问题。请问你直接访问国外网站，不通过蓝灯是否质量也很差？

**Comment by EdwardAutumn** [comment]
但是你们美国的服务器速度并不慢啊

**Comment by p3rcya** [comment]
嗯，可能是选择服务器的问题。这个我们正在优化

**Comment by tina00luo** [comment]
我的也是日本的服务器，能更改服务器的选择吗？日本的很慢

**Comment by shuangy92** [comment]
电信的宽带也是这样，你起码还打得开，我这边日本的google根本打不开，暴风哭泣

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
