### ISSUE TITLE
手机版蓝灯3.5.5开启代理自动退出

### ISSUE THREAD

**Issue by yxwmok** [getlantern/lantern#5500]
手机版蓝灯3.5.5开启代理自动退出

**Comment by huiyu998** [comment]
手机版蓝灯3.5.5开启代理自动退出

**Comment by p3rcya** [comment]
蓝灯3.5.7发布，解决闪退问题 https://github.com/getlantern/forum/issues/2133

**Comment by huiyu998** [comment]
谢谢升级蓝灯3.5.7已经正常
