### ISSUE TITLE
Lantern consuming huge amounts of background data on mobile

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5512]
Might apply to desktop too.

**Comment by myleshorton** [comment]
FYI @atavism - from user reports

**Comment by p3rcya** [comment]
e.g 
![image](https://cloud.githubusercontent.com/assets/20512438/21362829/d1608096-c69e-11e6-8db2-03e737317db0.png)

**Comment by p3rcya** [comment]
Issue moved to [getlantern/lantern-internal #555](https://github.com/getlantern/lantern-internal/issues/555) via [**ZenHub**](https://www.zenhub.com/)
