### ISSUE TITLE
Lantern marked as a bad proxy after sleep

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5517]
Steps to reproduce:

1) Open chrome to chrome://net-internals/#events and enter "bad_proxy" in the search box
2) Open chrome in another window to, say, https://news.google.com
3) Run Lantern 
4) Put computer to sleep (might require a few minutes, not sure).
5) Open computer and try to browse again
6) You should see Lantern marked as a bad proxy

**Comment by myleshorton** [comment]
@joesis this might be worthwhile to look at too while you're in the general area.

**Comment by joesis** [comment]
@myleshorton I put my Mac to sleep for 13 minutes but didn't get Lantern marked as a bad proxy, though there's an error entry as below BEFORE I put my computer to sleep.

```
t=126870 [st=    6]   -HOST_RESOLVER_IMPL_REQUEST
                       --> net_error = -804 (ERR_DNS_CACHE_MISS)
t=126871 [st=    7]   +SOCKET_POOL  [dt=159]
t=127030 [st=  166]      SOCKET_POOL_BOUND_TO_CONNECT_JOB
                         --> source_dependency = 136561 (CONNECT_JOB)
t=127030 [st=  166]   -SOCKET_POOL
                       --> net_error = -111 (ERR_TUNNEL_CONNECTION_FAILED)
t=127030 [st=  166]    PROXY_LIST_FALLBACK
                       --> bad_proxy = "127.0.0.1:8787"
```

Maybe see how it performs in the field?

**Comment by myleshorton** [comment]
All set now in 3.5.12
