### ISSUE TITLE
android 专业版本竟然有广告！！！我可是付费了的

### ISSUE THREAD

**Issue by curtis2** [getlantern/lantern#5521]

**Comment by curtis2** [comment]
搞笑，免费版尽然没有广告

**Comment by p3rcya** [comment]
请问具体是什么版本的蓝灯？ 安卓什么版本，什么型号？

**Comment by What4me** [comment]
我也觉得好奇怪，之前都没有的，12月份开始就有了。
现在更新了3.6.1，Android 7.0，oneplus3
广告语：想赚钱吗？成为蓝灯的代理商吧。
之前还有开屏的游戏广告，无语了。
另，最近一直翻墙都很慢，简直就是没速度。求答。

**Comment by curtis2** [comment]
最新一直电脑版用google一直出现，机器人验证那个界面。 windown系统，最新版本

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
