### ISSUE TITLE
与win7不兼容导致电脑蓝屏，日志里面显示 tdx.sys 导致的

### ISSUE THREAD

**Issue by 5alamander** [getlantern/lantern#5522]
如题，

win7，开着蓝灯一天蓝屏两三次，（一直找不到原因，IT直接给我换了个主机，仍旧蓝屏）

关了蓝灯，到现在还没看到蓝屏，

o(╯□╰)o，害我传文件传半天，

不想吐槽，只求解决，要不我还是用不了google

**Comment by Incubator85653** [comment]
http://www.file.net/process/tdx.sys.html

Try to open an Administrator cmd shell and type in this command:
```
sfc /scannow
```
