### ISSUE TITLE
Normal websites occasionally become service unavailable

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#5525]
When lantern is turned on, some unblocked websites occasionally become service unavailable with the following response in my web browser.

```
HTTP/0.0 503 Service Unavailable
Date: Monday, 26-Dec-16 16:39:53 CST
Keep-Alive: timeout: 38

context deadline exceeded
```

Then I turn off lantern and the websites are normal again.

**Comment by jingmingcn** [comment]
Got through the same issue. It turns out that the unblocked data pass through the lantern agent.

**Comment by renkun-ken** [comment]
Problem is gone with latest version.
