### ISSUE TITLE
android 付费版 蓝灯一直在后台跑流量

### ISSUE THREAD

**Issue by zhoubo1205** [getlantern/lantern#5550]
一个小时跑了28m 提交了报告 但是没root发过去的数据好像都加密了（返回邮件上是这么写的）邮箱360206282@qq.com 忘蓝灯以后越来越好

**Comment by zhoubo1205** [comment]
还有不知道是不是绑定了两个手机原因 google和youtube访问不了 youtube客户端视频无法播放但可以加载出视频列表和其他的数据 这种情况是间断性的 有时候能访问有时又不行

**Comment by zhoubo1205** [comment]
但 google play又没有问题

**Comment by zhoubo1205** [comment]
刚才YouTube看的好好的，一集看完……就不能看了 google也用不了了

**Comment by zhoubo1205** [comment]
这种情况下 我点击蓝灯的查看更新提示检查新版本提示错误……很忧伤……今天下午入的 就是有点不稳定 外加跑流量 可否告知如何解决 还有能否出个bug库 方便自己出问题查询 免得每次都来来这里 谢谢

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请在本帖提供email, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by p3rcya** [comment]
已经提交的报告正在调查，请提交新的报告，谢谢

**Comment by zhoubo1205** [comment]
卸载重新下载安装以后好了 估计是我修改了应用权限 然后现在发现无法长驻后台 问题不大 提交希望蓝灯越来越好

**Comment by zhoubo1205** [comment]
卸载重新下载安装以后好了 估计是我修改了应用权限 然后现在发现无法长驻后台 问题不大 提交希望蓝灯越来越好
