### ISSUE TITLE
2017.1.15（连接服务器失败）

### ISSUE THREAD

**Issue by wgoodq** [getlantern/lantern#5555]
报错消息：“很抱歉，我们无法连接到蓝灯的服务器。请检查您的网络连接并重试。”
昨天还可以，今天就不行了，更新到最新版本依然不行。

**Comment by p3rcya** [comment]
请在本帖提供email, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by wgoodq** [comment]
抱歉，现已恢复，没有做什么特殊操作，怀疑网络不稳定问题。请关闭该问题。
