### ISSUE TITLE
别等iphone版了

### ISSUE THREAD

**Issue by ihaolin** [getlantern/lantern#5562]
今早收到云梯VPN的邮件，突如其来的iphone和mac客户端都有了，终于可以肆无忌惮地挂着VPN了，上图：

![cloud_vpn_mac](https://cloud.githubusercontent.com/assets/8662695/22005224/6a8f4f50-dc9c-11e6-85d6-85ec3d157755.png)

![img_1475](https://cloud.githubusercontent.com/assets/8662695/22005186/39870394-dc9c-11e6-9801-2787b2574060.PNG)

[分享链接](http://findti.com/?r=26cb7dcab539d77f)

**Comment by p3rcya** [comment]
请不要广告

**Comment by ihaolin** [comment]
这不是广告，这只是lantern的堕落。

**Comment by TheLostXianXian** [comment]
官网是哪个?

**Comment by ihaolin** [comment]
@TheLostXianXian ，官网就是这个，[http://findti.com/?r=26cb7dcab539d77f](http://findti.com/?r=26cb7dcab539d77f)

**Comment by sunhan521** [comment]
我也是付费版的， 用了很久了，想等ios版本的，等的花儿都谢了
