### ISSUE TITLE
如何 更改 蓝灯 lantern 的代理IP

### ISSUE THREAD

**Issue by Jerry-goodboy** [getlantern/lantern#5564]
如题，运行蓝灯，lantern，本机的代理IP就会更改，用百度搜索IP，会显示为其他国家的IP，如美国，日本的IP，并且有个IP地址，我想问一下，如何动态更改这些代理IP地址，如一小时更改一次代理IP的地址，蓝灯，lantern有没有这方面的设置？

**Comment by Hxs2fJKjYZ** [comment]
open and run lantern, go to advanced settings page when the browser page opens, take note of socks proxy port.
open tor browser, go to connection settings, when asked if you use a local proxy, click yes, choose socks 5 and input 127.0.0.1 and the port number given by lantern, accept and run tor.
Tor browser will open and will be proxied through lantern, now you can have regularly changing IP addresses if you want that level of privacy.

**Comment by Jerry-goodboy** [comment]
@Hxs2fJKjYZ not using any browser, just changing IP with command line, cause I wanna make a shell tool which fetches some data from other websites or servers but has to be changed IP frequently, then what should I do?
