### ISSUE TITLE
Cant access blocked websites

### ISSUE THREAD

**Issue by rshsm** [getlantern/lantern#5567]
For a last couple of days, I am not able to use lantern to access blocked website. When i tried submitting the issue, i got the following error : Post https://mandrillapp.com/api/1.0/messages/send-template.json: net/http: TLS handshake timeout

Attaching the log file

**Comment by rshsm** [comment]
[lanterrn.log.txt](https://github.com/getlantern/lantern/files/721621/lanterrn.log.txt)

**Comment by rshsm** [comment]
Hi @myleshorton . It's working now. Another VPN was the culprit.

A quick check for other users. If lantern is not working, please check if it is running along with some other some VPN services.

**Comment by rshsm** [comment]
Thanks for quick response Team lantern and @myleshorton

**Comment by oxtoacart** [comment]
Not clear what if anything we should be doing here. Should we try to auto-detect VPNs and warn about that? Or doe we need to make sure we work when running over a VPN?

**Comment by rshsm** [comment]
@oxtoacart it's a note to the **users** that if they find lantern is not working, first check if they are using some other VPN along with Lantern. Nothing else needed from Lantern's team side, maybe just a note on the instruction page.

**Comment by oxtoacart** [comment]
@rshsm Thanks!
