### ISSUE TITLE
蓝灯这几天用起来跟屎一样，说什么比VPN快，比VPN好，比VPN牛逼，我看是吹牛逼。还有就是IOS端呢，我们大家都是冲着有IOS端来的，现在搞的跟屎一样，还没有一个说法。

### ISSUE THREAD

**Issue by timifire** [getlantern/lantern#5571]
蓝灯这几天用起来跟屎一样，说什么比VPN快，比VPN好，比VPN牛逼，我看是吹牛逼。还有就是IOS端呢，我们大家都是冲着有IOS端来的，现在搞的跟屎一样，还没有一个说法。

蓝灯这几天用起来跟屎一样，说什么比VPN快，比VPN好，比VPN牛逼，我看是吹牛逼。还有就是IOS端呢，我们大家都是冲着有IOS端来的，现在搞的跟屎一样，还没有一个说法。

蓝灯这几天用起来跟屎一样，说什么比VPN快，比VPN好，比VPN牛逼，我看是吹牛逼。还有就是IOS端呢，我们大家都是冲着有IOS端来的，现在搞的跟屎一样，还没有一个说法。

重要的抗议写三遍！

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请在本帖提供email, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by ShiChenCong** [comment]
@p3rcya  你好，我想问下，我入了 专业版，不能下载视频吗，每次都是下载一点就断了

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
