### ISSUE TITLE
用着还不错，输入我的邀请码 2CD3UZ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by zhangyang5511** [getlantern/lantern#5577]
用起来挺流畅，希望赶快出ios端啊

**Comment by zhaorui** [comment]
我也分享一下我的邀请码😬，HN5XX7，同求iOS😭！想要优惠的，也可以找我哦！

**Comment by lessonnair** [comment]
最新邀请码 WLW9MM

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28964775-ca05255e-7940-11e7-80d8-3ef49b5681a8.png)

**Comment by ShimmerSummer** [comment]
输入我的邀请码 6MRSVV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
![qq 20170807185745](https://user-images.githubusercontent.com/27009726/29024040-cf7b8370-7ba2-11e7-9c5d-66f425a96e64.png)
