### ISSUE TITLE
2.10号之后  pc版本彻底被屏蔽  新疆乌鲁木齐

### ISSUE THREAD

**Issue by softkillu** [getlantern/lantern#5592]

**Comment by p3rcya** [comment]
免费版还是专业版？

请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
