### ISSUE TITLE
蓝灯最近巨慢无比

### ISSUE THREAD

**Issue by Vywh** [getlantern/lantern#5599]
Pro版本在Mac和windows上面都试了速度极慢而且不稳定
邮箱yuweihaobnds@gmail.com和weihaoyubnds@icloud.com
有的时候带宽只有50kb甚至连pro之前的速度都达不到

**Comment by Vywh** [comment]
@p3rcya

**Comment by orbancanon** [comment]
@Vywh 日志显示经常连不上服务器。请检查一下你本地网络是否稳定，尤其是访问国外的时候。

**Comment by Vywh** [comment]
没事了
