### ISSUE TITLE
无法浏览外网

### ISSUE THREAD

**Issue by mygod998** [getlantern/lantern#5603]
[Uploading lantern.zip…]()

**Comment by p3rcya** [comment]
没有上传完成，请重新上传

**Comment by mygod998** [comment]
[lantern_log.txt](https://github.com/getlantern/lantern/files/966174/lantern_log.txt)

**Comment by mygod998** [comment]
[lantern_log.txt](https://github.com/getlantern/lantern/files/966177/lantern_log.txt)
