### ISSUE TITLE
分享邀请码

### ISSUE THREAD

**Issue by ttian226** [getlantern/lantern#5607]
输入我的邀请码 HNVQF5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by ljlthebadass** [comment]
输入我的邀请码 YHWV3J 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by huadong2014** [comment]
我的邀请码 GNWUSZ，获得三个月的蓝灯专业版免费使用

**Comment by ruyisi** [comment]
输入我的邀请码 YX7PBDV 来获得三个月的蓝灯专业版！

**Comment by lessonnair** [comment]
最新邀请码 WLW9MM

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28964739-a5595234-7940-11e7-8db2-d3609a6ef3d9.png)

**Comment by ShimmerSummer** [comment]
![qq 20170807185745](https://user-images.githubusercontent.com/27009726/29024010-b0d6968a-7ba2-11e7-9064-bb8f21ec28de.png)

**Comment by ShimmerSummer** [comment]
输入我的邀请码 6MRSVV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by imxiaohui** [comment]
输入我的邀请码 YHQK3SM 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by LyneLiu** [comment]
输入我的邀请码 H248S9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Guo-Lianghua** [comment]
输入我的邀请码 5KQJP5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by fxczero** [comment]
输入我的邀请码 HLHGBG 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Jane2016** [comment]
输入我的邀请码 5SWBF9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by youngjy** [comment]
输入我的邀请码 YYXRFHS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by frogprincel** [comment]
输入我的邀请码 YPT5F8W 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by posanlang** [comment]
输入我的邀请码Y2B23TH 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by superevanzhu** [comment]
输入我的邀请码 66FCNB 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by iOSPractise** [comment]
输入我的邀请码 H2T685 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Jane2016** [comment]
输入我的邀请码 5SWBF9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by cindy888** [comment]
For a free month of Lantern Pro, use this referral code: 4U6F55 ; You can download it from here: https://bit.ly/1M8x04u
