### ISSUE TITLE
ios版 啥时候出呢

### ISSUE THREAD

**Issue by Jerry-goodboy** [getlantern/lantern#5629]
如题，期待iOS版的发布

**Comment by timifire** [comment]
不要期待，据可靠消息，IOS只是用来吊人胃口，让人购买的，实际上永远不会有IOS版本的。还不如买VPN了。

**Comment by t3573393** [comment]
自己在服务器上使用lantern，然后拉一个代理给自己的设备用， 其实很简单的

**Comment by CoderLJY** [comment]
@t3573393 请问这个有教程吗？

**Comment by SJTUboy** [comment]
2018年 主力程序员twitter上说了
