### ISSUE TITLE
挂了两天了, Ubuntu16.04LTS 蓝灯专业版

### ISSUE THREAD

**Issue by yungkcx** [getlantern/lantern#5633]
[lantern.log.zip](https://github.com/getlantern/lantern/files/841583/lantern.log.zip)
Ubuntu16.04LTS，Lantern Pro 已经两天不起作用了，开了 lantern 之后连 Github 都上不了，但使用同一个专业版账户和同一 WIFI 的两个手机都正常。本地 IP 是 115.155.115.8 的校园网。
希望尽快处理，否则请赔偿损失。

**Comment by p3rcya** [comment]
是你电脑无法访问任何国外网络的问题。请自查

**Comment by yungkcx** [comment]
那可能的原因呢？

**Comment by p3rcya** [comment]
你自己找到原因了么？

**Comment by yungkcx** [comment]
是时间的问题。win 和 ubuntu 差 8 小时，不调时间就只有一个系统可以用。
能解释一下是什么原理吗？

**Comment by p3rcya** [comment]
Protocol 需要验证时间

**Comment by evenardo** [comment]
v2ray是需要时间同步的

2017年3月15日 09:34，"p3rcya" <notifications@github.com>写道：

> Protocol 需要验证时间
