### ISSUE TITLE
LANTERN 上不去了

### ISSUE THREAD

**Issue by xuzy1966** [getlantern/lantern#5644]
LANTERN 从昨天就开始上不去了,2.2.5版本     无法访问此网站

网址为 https://www.google.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_TUNNEL_CONNECTION_FAILED

**Comment by p3rcya** [comment]
请用最新的3.6.3版本 https://github.com/getlantern/forum/issues/833
