### ISSUE TITLE
google人机身份验证问题

### ISSUE THREAD

**Issue by naiverain** [getlantern/lantern#5670]
最近用蓝灯上google，总是要进行人机身份验证，是蓝灯的问题还是google的问题？

**Comment by DemoJameson** [comment]
同样的问题

**Comment by clem109** [comment]
I also have this issue, what is causing it? 很麻烦

我觉得是Google的问题 @naiverain

**Comment by wy-z** [comment]
+1

**Comment by wy-z** [comment]
@naiverain 很频繁, 身边的很多同事也都有这个问题~自己推荐他们用的都不好意思了...

**Comment by SWDADWD** [comment]
无法解决，lantern使用公共代理服务器，一个IP给成千上百人使用，大量访问网站，造成对方网站判定异常！

**Comment by wy-z** [comment]
@SWDADWD 这种态度可做不好一个产品....

**Comment by SWDADWD** [comment]
@wy-z 你终于发现了？

**Comment by learnyoung1990** [comment]
@wy-z 我还买了个两年的，买着天天和女友玩人机验证。投诉都没法投

**Comment by wy-z** [comment]
@learnyoung1990 好惨...

**Comment by chuncui0207** [comment]
+1

**Comment by halsn** [comment]
+1

**Comment by kubiAye** [comment]
+1

**Comment by flyyang** [comment]
+1 , 47.74.3.30, always  blocked by google.

**Comment by flyyang** [comment]
有时，如果您使用的是自动程序普遍使用的高级条款或者正在快速连续地发送请求，则可能需要破解人机识别系统。

can we solve this?

**Comment by ModunZhang** [comment]
我这边前一整子经常出现人机验证，到今天为止，我这边现在已经完全不能使用Google了，提示如下：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?


IP address: 47.52.72.124
Time: 2017-05-09T08:23:06Z
URL: https://www.google.com.hk/search?q=%E4%B8%AD%E6%96%87&oq=%E4%B8%AD%E6%96%87&aqs=chrome.0.69i59j69i61l2j69i60j0l2.2685j0j7&sourceid=chrome&ie=UTF-8

希望开发人员认真对待，毕竟好多人都是付费用户，持续这样可不好。
PS：推荐了周围好几个同事使用，这下我是跳坑里去了。。。

**Comment by isbdnt** [comment]
无语了，每过1分钟再上google就要验证

**Comment by isbdnt** [comment]
但是访问其他网站都没有问题，我的怒火反而转向了google？！！

**Comment by isbdnt** [comment]
突然发现解决办法，出现人机验证时点击左上角的后退，会显示搜索结果！！！

**Comment by theratlesnake** [comment]
清理一下浏览器试试？我的蓝灯一直都没问题，好好的

**Comment by LunarisDream** [comment]
我的最近也是天天人机验证，只有谷歌和recaptcha。换网络也一样，我用手机流量和家里的网都会遇到人机验证。烦死了。怀疑是有用户拿蓝灯来干一些spam操作。

**Comment by leyou2018** [comment]
我的win7，也会有这个问题。退出 lantern，重新登录分配一个新的ip就没事了。

**Comment by raisezhang** [comment]
+1

**Comment by pythoncat1024** [comment]
已经被搞败了，天天身份验证。无法进行搜索了...........

**Comment by LNDDYL** [comment]
公共IP，會出現這樣的狀況很正常。

**Comment by theratlesnake** [comment]
我的基本没这样问题

**Comment by marxpayne** [comment]
IP 地址：47.52.58.9
时间：2017-07-24T12:02:07Z
网址：https://www.youtube.com/

今天一直用不了油管，怎么破

**Comment by yangzhilei** [comment]
这个是代理问题啊，自己搭的代理则不会有这样的问题

**Comment by fofofofoxier** [comment]
用谷歌账号登录的话 就不会有人机验证了，只要证明你自己不是一个robot

**Comment by SmShrimp** [comment]
我的也是，希望蓝灯开发给出解决方案啊？这毕竟都是付费用户呢。
