### ISSUE TITLE
没有信用卡应该如何付费？

### ISSUE THREAD

**Issue by Oathkitchen** [getlantern/lantern#5674]
如题

**Comment by nijia909** [comment]
支付宝-=0-

**Comment by Oathkitchen** [comment]
麻烦楼上可以告诉我支付宝付款界面吗？我只能找到信用卡付款界面，麻烦了

**Comment by p3rcya** [comment]
@Oathkitchen 请问你使用的是最新版本3.6.3么？ 不是的话，请去 https://github.com/getlantern/forum/issues/833 下载最新版。是的话，请上传下付款界面的截图，看看为什么支付宝不行。

**Comment by Oathkitchen** [comment]
@p3rcya 好的我这就下载最新版本试试

**Comment by Oathkitchen** [comment]
![qq 20170418213231](https://cloud.githubusercontent.com/assets/23115523/25133236/a97a21de-247e-11e7-84ff-f3e6a6a93214.png)
还是不行啊
@p3rcya

**Comment by p3rcya** [comment]
请在软件设置里面调整成中文。

**Comment by Oathkitchen** [comment]
@p3rcya 好的问题解决了，谢谢

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
