### ISSUE TITLE
操你妈逼，老子要退款。没有IOS版本的，速度也是垃圾的一笔！退款的留下你们的回复！

### ISSUE THREAD

**Issue by timifire** [getlantern/lantern#5675]
操你妈逼，老子要退款。没有IOS版本的，速度也是垃圾的一笔！退款的留下你们的回复！所谓的IOS版本只是用来炒作的，实际上垃圾根本弄不出来IOS版本的，超级贵的价格卖给消费者。想买的千万不要购买，买了后悔死你吧，不能退款，没有售后，没有诚信！想退款的，被IOS骗过来的，留下你们的回复!

**Comment by JasonPhone** [comment]
hey man. ul know how hard it is once u develop a software on ur own and.....r these chinese characters? my translator cannot give some of their meanings...

**Comment by NeoChow** [comment]
@timifire 请注意你的语言，本网站是全球最大的开源软件项目托管平台，所谓开源，是指对所有人免费开放源代码。如果你因为某个产品而被骗钱，请直接去找收你钱的商家反馈。这里全都是用于学习交流的项目。另外，本项目首页，并没写它适用于iOS平台。

**Comment by NeoChow** [comment]
@JasonPhone You could just ignore something like this. : )

**Comment by SWDADWD** [comment]
@NeoChow lantern3.X转向商业化模式运作，并向用户收取一定金额才可以使用完整的功能。getlantern.org宣传写到：“即将推出IOS版本”

lantern3.X 商业化闭源！

**Comment by b64406620** [comment]
@JasonPhone  u can treat he ( @timifire )  as  a Idiot or shaby.  (*^__^*)   haha

**Comment by hx804722948** [comment]
@NeoChow  头一次见到你这种睁眼说瞎话的人，你属于文明的流氓，有一段时间此网站说过会马上推出IOS版，现在自己把那句话删掉了，至少有一部分人是冲着ios版付费的

**Comment by miaomiaosoft** [comment]
@hx804722948 那你不知道等出了IOS版再买么   有些人真是  墙是翻过去了  素质还是一坨屎

**Comment by hx804722948** [comment]
@miaomiaosoft 你有语文老师交吗？看不懂中文意思？我说了我是冲着ios买的？当官方狗腿子当习惯了吧……我用的pixel 谢谢

**Comment by miaomiaosoft** [comment]
@hx804722948  那你傻逼真是活该 还没出就买完事就骂   你这种脑残活该一辈子墙内  别出来丢人
我说我马上要操你妈了是不是你现在就要砍我

**Comment by aold619** [comment]
价格说不上贵，速度也的确不慢，但以前的确是说过iOS即将推出的，总之冷静处理吧，言辞这么激烈对解决事情没有啥帮助也

**Comment by CM-Aug** [comment]
想付费来着，但是一直没有iOS版出来，现在准备将就着为了这软件买只Android手机？

**Comment by LisPerfect** [comment]
请注意你的言论，这是github

**Comment by psychopassor** [comment]
有多少人是冲着能出ios版本来的，至少我是，官方也没个明确的公告，之前看到一个issue有人说去年底接回开发出来，我也没多想就买了2年服务，等到现在也没个屁响，所以另一个ss在iPhone上用，糟心...

**Comment by zhangjia517** [comment]
言辞过激 但道理一个没错 什么时候出ios版本给个痛快话

**Comment by RazeSoldier** [comment]
为什么github有这种低素质的人

**Comment by p3rcya** [comment]
谩骂的帖子我关闭了
