### ISSUE TITLE
ios 版本大概什么时候出？

### ISSUE THREAD

**Issue by leyou2018** [getlantern/lantern#5689]
ios 版大概什么时候上线？

**Comment by gezhaoyou** [comment]
同问

**Comment by hx804722948** [comment]
不会出了，别想了

**Comment by Snowpee** [comment]
当初是信任蓝灯才买的，现在看来，吃相略难看了。永远没人正面回答这个问题，这是我用过的客服最屌的服务。

**Comment by CM-Aug** [comment]
就是假装会出iOS版，让用户先买，然后就不用说了吧

**Comment by psychopassor** [comment]
官网上写着“Lantern for iOS coming soon”，不出iOS版本不就是欺诈行为了？

**Comment by hitzhangjie** [comment]
赶紧出iOS版本吧，有那么困难吗。只是lantern支持pac配置的，专门给iOS配置一下不就可以了吗，lantern开发者们你们是有多渣！

**Comment by jinyingfeng** [comment]
什么时候出ios啊，我ios手机都买了，你们ios版还没出来，我买了4年的vip啊

**Comment by wglpd** [comment]
不要想ios版了，估计开发人员都没了，git上代码一年都没人维护了

**Comment by psychopassor** [comment]
@wglpd如果真如你所说，那准备买的赶紧打消念头了吧！

**Comment by psychopassor** [comment]
真不知开发者是如何想的，给个明确的答复不行吗？害得一个二个在这儿瞎YY，要求退款的，说垃圾的，求ios版的...这样下去只会越搞越臭额

**Comment by home5893** [comment]
我就是想出了ios版再买的 没想到 这一等…

**Comment by gezhaoyou** [comment]
mac 上倒是用着非常好用，也开了专业版，如果能有ios版本就更好了！

**Comment by p3rcya** [comment]
iOS版本2018年发布
