### ISSUE TITLE
2年账号变成1970/1/1过期

### ISSUE THREAD

**Issue by jerry16c** [getlantern/lantern#5696]
购买的2年账号现在变成了1970/1/1过期，且每次刷新都得重新登录，求解决。
邀请码：YGHJ3NB
账号：cyousiken@gmail.com

<img width="1280" alt="2017-05-25 1 15 18" src="https://cloud.githubusercontent.com/assets/28943478/26436874/3fab1a84-414c-11e7-830e-becdca7db125.png">

@p3rcya

**Comment by jerry16c** [comment]
时间仍然不对，购买的2年的时间变成了只剩下89天。
<img width="712" alt="2017-05-25 9 05 33" src="https://cloud.githubusercontent.com/assets/28943478/26451278/f66f95e2-418d-11e7-9240-63d23923d7c3.png">

@p3rcya

**Comment by p3rcya** [comment]
你这3个月是别人使用邀请码送的。你从来没有成功购买过专业版。如果你有付款证明，请上传

**Comment by jerry16c** [comment]
![img_3429](https://cloud.githubusercontent.com/assets/28943478/26479977/99160d14-4209-11e7-9802-b93d17c6f452.PNG)

@p3rcya

**Comment by p3rcya** [comment]
你购买时候可能用的不是这个email账号。

**Comment by p3rcya** [comment]
你给的cyousiken@gmail.com 账号下没有任何购买记录，你试试其他email

**Comment by jerry16c** [comment]
我确认当时购买专业版就是用的这个账户，除此之外别无可能。
而且当时使用paymentwall付款的时候也用的是这个账户，Gmail里仍然有当时的邮箱确认地址。
<img width="1280" alt="2017-05-27 1 14 44" src="https://cloud.githubusercontent.com/assets/28943478/26518246/1f6d8c0e-42df-11e7-819f-606b14d68eb5.png">

@p3rcya

**Comment by p3rcya** [comment]
好，我们正在调查

**Comment by orbancanon** [comment]
@jerry16c 根据你提供的订单号和时间，我们找到你购买时所使用的邮箱是 <jerrychao12016 在 icloud.com>
