### ISSUE TITLE
为什么一直提醒更新啊，更新不停

### ISSUE THREAD

**Issue by ZeroDeng01** [getlantern/lantern#5717]
现在是3.7.2 bate1更新完还提醒更新

**Comment by sunvim** [comment]
没有解决？ 我也是这样情况……

**Comment by WengHeng** [comment]
下载一个3.7.2正式版就不提示更新了.

**Comment by p3rcya** [comment]
用最新的3.7.3试试  下载地址 https://github.com/getlantern/forum/issues/3224

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
