### ISSUE TITLE
How to build and run Lantern server on Raspberry Pi??

### ISSUE THREAD

**Issue by just4id** [getlantern/lantern#5721]
Hi everyone, how can I build from source code and run Lantern server on Raspberry Pi? Thanks.

**Comment by just4id** [comment]
solution: https://github.com/EasyPi/docker-lantern-arm

**Comment by baimafeima** [comment]
@oxtoacart How would you evaluate the docker-lantern-arm project?

**Comment by just4id** [comment]
@baimafeima It's excellent and I've built lantern 4.4.0 successfully, but proxy dose not work properly on my Respberry Pi zero.

**Comment by oxtoacart** [comment]
Hi @baimafeima and @just4id, the open source version of Lantern doesn't work with the Lantern network anymore.
