### ISSUE TITLE
为什么更新版本(3.6.3以上)之后打不开？

### ISSUE THREAD

**Issue by fakeluke01** [getlantern/lantern#5726]
现在用的是3.3.1版本 下了3.7和3.6.3的装上之后就打不开了，现在装回3.3.1的才能用，why？

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
