### ISSUE TITLE
您的专业版账户将在 -17321 天后，即 ‎1970‎年‎1‎月‎1‎日 过期

### ISSUE THREAD

**Issue by senggugi** [getlantern/lantern#5729]
去年12月份购买的，之后一直出现这个问题，在lantern里报告问题，也没有得到回复，希望在这能得到你们的回复！

**Comment by p3rcya** [comment]
请上传当时收到的付款邮件里面的payment id

**Comment by senggugi** [comment]
![21312312314](https://user-images.githubusercontent.com/23204674/27463506-a2acc172-57fa-11e7-8d9e-d3aebfe799fe.jpg)

**Comment by senggugi** [comment]
@p3rcya

**Comment by p3rcya** [comment]
你绑定的邮箱是 senggugi28@gmail.com

**Comment by p3rcya** [comment]
请使用邮箱登陆

**Comment by senggugi** [comment]
不好意思，一直以为是支付宝账号邮箱是我的登录邮箱

2017-06-24 0:38 GMT+08:00 p3rcya <notifications@github.com>:
