### ISSUE TITLE
能否申请退款呢？

### ISSUE THREAD

**Issue by ss1028yy** [getlantern/lantern#5734]
是代朋友买，走的是我的支付账户，结果因为沟通问题，朋友使用需求不能完全满足，想退款，可行吗？
购买凭证

getlantern.org
Powered by Paymentwall
交易 ID	交易日期
w120844021	2017-6-25 上午12:34 (GMT-5)
交易日期	Price
一年套餐	216.00 CNY
Total 216.00 CNY
Charged amount: US $31.60
This payment is for getlantern.org
支付方式 AliPay

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
