### ISSUE TITLE
邀请码一枚哟YPNF9KD

### ISSUE THREAD

**Issue by xeex66** [getlantern/lantern#5736]
输入我的邀请码 YPNF9KD 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zgj224** [comment]
@xeex66 激活码是25位好不好，不要在这里误导众人了

**Comment by xeex66** [comment]
@zgj224 请看清楚是邀请码，谁告诉你是激活码了？你付费的时候用这个码能多送你最多3个月的使用时间。
