### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by shellj** [getlantern/lantern#5762]
我的windows电脑退出了专业版账号，然而退出后还是专业版，不过账号已经不是我的了，一个莫名其妙的账号。卸载后重装还是这个账号，而且退不了。我自己手机上显示windows设备还在，而且无法移除。图片上这个qq账号不是我的。

![_20170714111359](https://user-images.githubusercontent.com/1058220/28196802-8b765a36-6885-11e7-8ddd-ca3838063195.png)

**Comment by orbancanon** [comment]
@shellj 看来你的Windows是在虚拟机上装的。我后台处理了一下，你在虚拟机里登录你的专业版帐号再退出，应该就会回到免费版了。

你手机上移除不了Windows设备应该是另外的原因。请把你的帐号告诉我，我看看。

**Comment by shellj** [comment]
@orbancanon 不是虚拟机，是公司的电脑。而且现在登录不了我的账号，因为那个账号退不掉。

我的帐号是：xiejun.work@gmail.com

**Comment by orbancanon** [comment]
@shellj 手机上应该看不到Windows设备了吧……你的帐号下只有Mac和手机。

退不掉的问题，你可以在Windows下删除c:\users\<用户名>\AppData\Roaming\Lantern\settings.yaml，再重新打开Lantern，就变回成免费了。

**Comment by shellj** [comment]
@orbancanon 手机正常了，缓存问题？电脑上我又重新卸载了一遍也好了，但为什么会出现别人的账号？

**Comment by orbancanon** [comment]
@shellj 应该是的。别人帐号是个极小概率的遗留问题，很快会全部杜绝了。
