### ISSUE TITLE
我的邀请码是2Y7RT2，购买的时候大家可以填一下,双方都能获赠使用时间

### ISSUE THREAD

**Issue by WengHeng** [getlantern/lantern#5775]
输入我的邀请码 2Y7RT2来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

我最初遇到访问不畅的情况时，按照论坛说明把log上传，之后就好了，YouTube无法显示文字之类的问题可以把高级设置里的代理全部流量也选上

祝各位墙外愉快，enjoy new world！

**Comment by zhouyang8304** [comment]
阿里支付不了 怎么办
