### ISSUE TITLE
续费蓝灯专业版账户时,提示我邮箱已存在!

### ISSUE THREAD

**Issue by WengHeng** [getlantern/lantern#5780]
![image](https://user-images.githubusercontent.com/19686947/28408664-cbdc2468-6d6a-11e7-9963-e6bc92ce47cc.png)

完全没毛病,这个账户正是我要续费的账号,但是..我该咋给我的账号续费呢?

**Comment by maxxsun** [comment]
和我一样  无法续费

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
