### ISSUE TITLE
输入我的邀请码 Y4KQ358 来获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by vipbackup** [getlantern/lantern#5785]
输入我的邀请码 Y4KQ358 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
