### ISSUE TITLE
ubuntu版重启无法连接外网，直到清除所有设置后才恢复。

### ISSUE THREAD

**Issue by wierton** [getlantern/lantern#5797]
在清除设置之前，重启电脑，重装网卡驱动n次，但是不仅无线网卡，以太网卡也用不了，可以连得上网关，但没法发包（估计你们hook之后做了什么奇怪的操作），直到`lantern -clear-proxy-settings`之后重启才恢复，麻烦你们尽快修一下，这个问题很严重，如果我没有详细翻看lantern的参数，最坏情况估计就得重装系统了。PS:我下的是最新版。

**Comment by mikedchavez1010** [comment]
lantern默认管理系统代理，linux下是http_proxy环境变量。lantern开启时，echo $http_proxy应该显示lantern代理；lantern关闭后，应该为空。既然你是Ubuntu用户，相信你是电脑高手，完全有能力处理这些问题。

**Comment by wierton** [comment]
这是你们软件的漏洞啊，怎么还把问题摊给用户呢？？你的意思是这个bug就永远留着不修呢？？？

**Comment by mfp305629415** [comment]
@wierton 大兄弟，我lantern -clear-proxy-settings了，也重启了，还是无法上网，请问下你是怎么解决的，万分感激
QQ 305629415

**Comment by mfp305629415** [comment]
@mikedchavez1010 请问下这种情况需要怎么解决呢，可以告知下吗
