### ISSUE TITLE
Lantern "proxy all traffic" not working

### ISSUE THREAD

**Issue by sodabluesff** [getlantern/lantern#5809]
Lantern version:  3.7.4
Android version: 7.0  (not rooted)

When I tried to turn on "proxy all traffic" option on my phone,  it just toggled back immediately.

**Comment by p3rcya** [comment]
Please upload the log in the app and include your email here. Thanks

**Comment by alexwang58** [comment]
Same problem , and submit an issue : https://github.com/getlantern/lantern/issues/5817

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
