### ISSUE TITLE
Lantern Pro(3.7.4) Proxy all traffic Enabled, but it seems does`t work

### ISSUE THREAD

**Issue by alexwang58** [getlantern/lantern#5817]
Lantern Pro(3.7.4) on macOS Sierra(10.12.6)

Both "Proxy all traffic" and "Manage system"  is enabled. When I checked in speedtest.net it shows my real IP, but geoiptool.com shows the proxy IP.

How can I Proxy all traffic through Lantern Pro(3.7.4)

**Comment by p3rcya** [comment]
请下载最新版4.0.1 https://github.com/getlantern/forum/issues/4014 已经解决了这个问题
