### ISSUE TITLE
Mac 付费用户,两个月不能连接外网,请问有没有人负责的

### ISSUE THREAD

**Issue by anmac** [getlantern/lantern#5836]
Lantern内置报告问题提交十几次,还是没有任何反馈,请问官方连一封敷衍的邮件都舍不得发吗

**Comment by p3rcya** [comment]
请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。

**Comment by anmac** [comment]
都写了是 MAC 系统还给这个 window 解决办法,能不能专业点

**Comment by anmac** [comment]
https://github.com/getlantern/forum/issues/3871
