### ISSUE TITLE
我的邀请码JR6XP8，免费赠送三个月的会员

### ISSUE THREAD

**Issue by KeSenkai** [getlantern/lantern#5838]
邀请好友来获得更多的专业版使用时间。
好友购买两年套餐后，双方都赠送三个月的专业版使用时间；
好友购买一年套餐后，双方都会赠送一个月的使用时间。
这是您的邀请码：C4LLC4
大家互利互惠哦！

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
