### ISSUE TITLE
欢迎使用邀请码Y2FQHMV，成功后可以免费获得3个月专业版。

### ISSUE THREAD

**Issue by sixfeeling** [getlantern/lantern#5839]
输入我的邀请码 Y2FQHMV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
