### ISSUE TITLE
新鲜的三个月邀请码：YJJTMWQ

### ISSUE THREAD

**Issue by ding209** [getlantern/lantern#5849]
自己刚买了个两年的帐号，这是我的邀请码：YJJTMWQ，你用了后买一年的会给你加一个月，买两年的会给你加三个月。

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。

**Comment by ding209** [comment]
@p3rcya 你好，因为我来这里没看到相关的规定，所以才发了这违规贴的。赠送的时间是我买两年的时候填的别人的邀请码获得的，并不是别人填我邀请码获得的。我也不会再违规发帖。希望能返回我获得的时间。

**Comment by ding209** [comment]
@p3rcya 如果不能返回赠送的时间，那也不要多扣我一个月啊。。我8月28买的，显示2019/07/27到期。多扣了一个月。
