### ISSUE TITLE
退出蓝灯后 谷歌及IE浏览器 不能访问网络，火狐浏览器 和QQ正常使用

### ISSUE THREAD

**Issue by amenging** [getlantern/lantern#5873]
之前也出现过这种情况，解决办法是在Internet选项的连接里，把局域网设置中的代理去掉，并且结束蓝灯进程，现在不行，尝试过卸载蓝灯和用netsh winsock reset，都不行。

**Comment by fc662003** [comment]
好像是因为Chrome的代理设置是使用的系统的代理设置，而火狐浏览器自带代理设置。蓝灯最新版有bug，退出后无法关闭系统代理，所以Chrome实际上仍然在试图使用蓝灯代理上网，导致无法上网。

**Comment by amenging** [comment]
解决了，重新设置了一个宽带连接
