### ISSUE TITLE
恕我直言，蓝灯换不了地区真的垃圾

### ISSUE THREAD

**Issue by Garth90** [getlantern/lantern#5902]
我还买了专业版，但是不能换地区真的难受，一直都是日本日本，说实话挺讨厌日本的，上谷歌YouTube都是显示的日区的东西。看也看不懂，也不知道怎么有些网站还是加载慢，难受，只希望能选择地区。

**Comment by johnx7271** [comment]
日本乍了，日本不好，你用中国的么。

**Comment by Garth90** [comment]
用ss啊

**Comment by dantigone** [comment]
youtube可以手动换区，楼主需要提高姿势水平。

**Comment by ineondog** [comment]
既然你那么讨厌日本，建议你使用中国区网络，翻什么墙，不爱国。

**Comment by aelxsam** [comment]
實在想不通 那麼討厭日本 為什麼要翻牆。。。  在北方出口在那邊連到日本非常正常啊。我這都經常連到日本呢。。。

**Comment by ZhangDonghui001** [comment]
可能主要是因为日语看不懂吧，能看懂的英语肯定比日语多啊。

**Comment by lianyuxiuluo** [comment]
然而我想知道怎么调到日本节点...
