### ISSUE TITLE
蓝灯打开的话，不能正常的上国内网

### ISSUE THREAD

**Issue by xiguataida** [getlantern/lantern#5911]
打开蓝灯，不能正常的上国内的网站，加载不出，或者加载不出音频

**Comment by Z1Wu** [comment]
我的国内网倒是可以上，不过UWP应用都连不上网络

**Comment by xiguataida** [comment]
@Z1Wu 而且英文提问有人回答，中文提问连个人都没有

**Comment by johnx7271** [comment]
看这个 ：#5903。 关于 pac 文件，自己去搜搜，下一个，下完后，要根据自己的情况作适当编辑。
