### ISSUE TITLE
Cannot login on lantern homepage under Firefox 57 on macOS

### ISSUE THREAD

**Issue by renkun-ken** [getlantern/lantern#5918]
I'm testing Firefox 57b3. Lantern homepage cannot login due to websockets to `ws://localhost:51246/data` are refused but lantern still works in background and there's no problem having access to blocked sites. An error log says `NS_ERROR_CONNECTION_REFUSED` on lantern homepage.

**Comment by myleshorton** [comment]
Interesting @renkun-ken thanks. What operating system? We'll check on it.

**Comment by myleshorton** [comment]
Oh, also, what version of Lantern are you using @renkun-ken?

**Comment by renkun-ken** [comment]
macOS HIgh Sierra (10.13), lantern 4.0.1.

**Comment by renkun-ken** [comment]
I'm also trying Firefox 57b3 on Ubuntu 16.04.3 and no such problem found.

**Comment by eloib** [comment]
same problem but with Nightly. I had to change my default browser to edge to be able to get the url and make a shortcut in nightly. windows 10 and lantern at the latest update

**Comment by renkun-ken** [comment]
I also test with Safari and everything's ok.

**Comment by renkun-ken** [comment]
I'm testing with latest Firefox 57 and Lantern 4.4. The homepage still is not working.

**Comment by renkun-ken** [comment]
Firefox 57 is released. Lantern 4.4 homepage works fine with this release on Ubuntu 16.04 and 17.10, Windows 10, but not macOS High Sierra.

**Comment by agasbzj** [comment]
Same problem here, only appears on macOS 10.13, Firefox 57.0 stable.

**Comment by mgv5** [comment]
解决办法很简单，在系统偏好设置里面找到  网络-->高级-->代理，添加忽略:  localhost、127.0.0.1

**Comment by renkun-ken** [comment]
@mgv5's solution works great. Thanks!

**Comment by agasbzj** [comment]
@mgv5 谢谢。不过 恐怕这不是最终解决办法，因为不改系统设置chrome没有这个问题，希望开发团队还是关注下。

**Comment by renkun-ken** [comment]
I'd like to reopen this since each restart of lantern will revert the network config to the unsettled status.
