### ISSUE TITLE
无图形界面下安装lantern！！！！！！！！求回答

### ISSUE THREAD

**Issue by zach007** [getlantern/lantern#5942]
能不能举例，我在windows下用了一年，对于linux不是太熟悉，
我用的操作系统是ubuntu，无图形界面
官网的操作是：
HEADLESS=true make docker-linux or, if you're already running on Linux just HEADLESS=true make linux
但是不太清楚具体步骤，能否给出详细步骤，#5802也有一个这样的问题

how to make and install lantern, i have been use lantern in windows for a year, and today turn to ubuntu
without Graphical User Interface 
and the doc say
HEADLESS=true make docker-linux or, if you're already running on Linux just HEADLESS=true make linux
but i still been confused , please  help me with step by step~

**Comment by HuangHongkai** [comment]
latern -headless=true 就好了

**Comment by kaine1973** [comment]
**How to `make` and install lantern?**
I have been using lantern on windows for a year, and today turned to Ubuntu without Graphical User Interface
and the doc says

> HEADLESS=true make docker-linux or, if you're already running on Linux just HEADLESS=true make linux

but I am still confused , please help me Hand by Hand~
