### ISSUE TITLE
蓝灯为何能长期提供免费稳定的流量,服务器维护的资金从哪里

### ISSUE THREAD

**Issue by outofmemo** [getlantern/lantern#5959]
如题,蓝灯提供快速免费的流量,服务器和宽带估计得花不少钱.之前许多免费的vpn也是走的先免费后付费.蓝灯虽然有付费版,但从运营角度看收入应该不够免费的支出.那是有其它资金来源或支持吗

**Comment by gmvp3** [comment]
你问问迅雷免费版的资金哪里来

**Comment by snfh2014** [comment]
付费啊，专业版速度更快，这里是我的邀请码668B7R，填写邀请码买一年两年专业版会赠送额外3个月使用期限

**Comment by beboyss** [comment]
@gmvp3 一个是代理，流量要用钱买的。一个是p2p，流量就是别人传给你的，免费的，这两个不能类比。
迅雷的付费版本身用的也是免费的流量，只是他在中间拦截了一下。

**Comment by beboyss** [comment]
@gmvp3 百度网盘跟迅雷一样，你开着百度网盘看看他占用你多少上传带宽

**Comment by gmvp3** [comment]
@beboyss 网盘空间你出钱？

**Comment by beboyss** [comment]
@gmvp3 磁盘空间的钱真的是微乎其微，付费的一小部分就可以完全覆盖免费，没看现在动辄就给1tb，几百G，实际上每个人真正占用的物理空间可能就几十g，而且好多东西重复的东西占用的都是同一块空间，通过算法和优化可以让一tb的物理硬盘支持每个人号称拥有1tb的一百万人。

**Comment by gmvp3** [comment]
@beboyss 是的，对你这种土豪来说当然不值钱，带宽，服务器，机房电费，磁盘这些都不值钱。键盘侠老师。

**Comment by beboyss** [comment]
@gmvp3 诶呦，开始扣帽子了，小红卫兵，这就脱离了讨论了，估计你也没想讨论，只是认为你说的对，别人有异议了就是键盘侠，用你的标准，你怎么就不是键盘侠了呢？

**Comment by gmvp3** [comment]
@beboyss 哎哟，是你自己开始脱离讨论了吧，键盘侠土豪先生。

**Comment by beboyss** [comment]
@gmvp3 一会老师一会土豪你很了解我嘛？请继续意淫。。。我闪了，请不要顾及我的感受，反正我也看不到了，你高兴说啥都行

**Comment by aelxsam** [comment]
@gmvp3  其實呢 你會發現 現在虛擬設備上掛一個藍燈問題不是很大。 尤其是 GOOGLE 的服務器群已經不是一般人能想像的。 寬帶也是如此加上藍燈這服務其實建基於 GOOGLE 這個體制內，網絡內。真正外訪的數據量 沒你想像的那麼多。 完全是可以 內部路由上判斷好。

**Comment by gmvp3** [comment]
@beboyss 像你这样什么都不懂的键盘侠还少敲键盘为好，省得被笑话。

**Comment by gmvp3** [comment]
@aelxsam 你在和我说？用蓝灯访问谷歌对我来说只是其中一个用途。还可以加速访问所有国外网站。

**Comment by JerryChin** [comment]
could your guys be a little bit respectful to each other?

**Comment by wuyanlin** [comment]
免费每月有流量限制，资金当然是来源于付费用户啊
