### ISSUE TITLE
Windows Defender reports latest version of lantern.exe as Trojan

### ISSUE THREAD

**Issue by JohnCido** [getlantern/lantern#5961]
Defender reports both installer and lanter.exe as Trojan:Win32/Tilken.B!cl
I'm using the one downloaded from official site.
Is it a false alarm or another security risk similar to CCleaner malware hack?

**Comment by kaine1973** [comment]
的确有报毒。吓得我赶紧把windows卸了

**Comment by ziningluo** [comment]
so what's the solution?
