### ISSUE TITLE
续费之后刷新页面，仍看到续费请求，怎么回事？

### ISSUE THREAD

**Issue by lzhhhhhh** [getlantern/lantern#5971]
付费了，收据到了，但账号管理上仍显示即将到期的信息，并没有已续费的迹象，怎么回事？

**Comment by lancefee** [comment]
这个没关系，你只要重新启动，然后运行蓝灯菜单的账号管理，看里面的有效期就行了。

蓝灯最大的好好处就是开机自动运行，占用资源小。
付费的专业版不限流量，不限速度，还能看Youtube视频。

真心推荐给大家，推荐购买2年的朋友，购买时输入邀请码 M9YRPR
我们都能获得额外的三个月的蓝灯专业版使用期！
