### ISSUE TITLE
lantern is not work 

### ISSUE THREAD

**Issue by MABIY** [getlantern/lantern#5974]
ERROR balancer: balancer.go:187 Caused by: Unable to dial server fp-obfs4-doams3-20161119-006 (128.199.32.191:14071): dial tcp 128.199.32.191:14071: i/o timeout
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).dialInternal (dialer.go:190)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).doDial (dialer.go:176)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).Dial (dialer.go:131)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/balancer.(*Balancer).dialWithTimeout.func1 (balancer.go:217)
ERROR balancer: balancer.go:187   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:187 Caused by: i/o timeout
Oct 09 05:27:36.363 - 1m32s ERROR balancer: balancer.go:187 Unable to dial via fp-obfs4-doams3-20161119-006 (128.199.32.191:14071) to connect://clients4.google.com:443: Unable to dial server fp-obfs4-doams3-20161119-006 (128.199.32.191:14071): dial tcp 128.199.32.191:14071: i/o timeout on pass 2...continuing [error=Unable to dial via %v to %s://%s: %v on pass %v...continuing error_location=github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:187) error_op=dial error_text=Unable to dial via fp-obfs4-doams3-20161119-006 (128.199.32.191:14071) to connect://clients4.google.com:443: Unable to dial server fp-obfs4-doams3-20161119-006 (128.199.32.191:14071): dial tcp 128.199.32.191:14071: i/o timeout on pass 2...continuing error_type=errors.Error local_addr=128.199.32.191:14071 network=tcp op=dial_for_balancer proxy_host=128.199.32.191 proxy_port=14071 proxy_type=chained root_op=dial_for_balancer]
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:187)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/client.(*Client).getDialer.func3.1 (client.go:401)
ERROR balancer: balancer.go:187   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:187 Caused by: Unable to dial server fp-obfs4-doams3-20161119-006 (128.199.32.191:14071): dial tcp 128.199.32.191:14071: i/o timeout
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).dialInternal (dialer.go:190)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).doDial (dialer.go:176)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/chained.(*proxy).Dial (dialer.go:131)
ERROR balancer: balancer.go:187   at github.com/getlantern/flashlight/balancer.(*Balancer).dialWithTimeout.func1 (balancer.go:217)
ERROR balancer: balancer.go:187   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:187 Caused by: i/o timeout

**Comment by MagicJ23** [comment]
Me too

**Comment by NogizakaZ** [comment]
yeah again

**Comment by hardwigg** [comment]
what the hell is going on

**Comment by yorts52** [comment]
yes, me too

**Comment by iteratorlee** [comment]
what's going on... already twice this month

**Comment by Dobad** [comment]
的确，又不能用了

**Comment by RichardKuroshio** [comment]
又翻车了

**Comment by Bimbaloo** [comment]
这波是各大翻墙都挂了~~

**Comment by Resister** [comment]
估计和10月5号的情况一样，国际出口的物理层面故障，类似物理断网，他们真的能够不择手段呀

**Comment by yorts52** [comment]
beause of 19 > ？
amazing!!!

**Comment by SPINACHCEO** [comment]
Fuck Chinese government, fuck hard.

**Comment by xiguataida** [comment]
nineteen big?

**Comment by MABIY** [comment]
now it's working
