### ISSUE TITLE
刚才不能用了，我更新了最新版Lantern 4.1.2 (20171006.214359)，可以用了

### ISSUE THREAD

**Issue by wangyongzhi** [getlantern/lantern#5987]
我是付费专业版，https://github.com/getlantern/lantern/releases/tag/latest 下载最新版
我本机是Mac 10.11.6，地点杭州

说4.1.2版本更新后，收费版变免费版本的，刚开始确实是这样，不过等一下就好了

**Comment by windmaxiao** [comment]
然而还是不能用

**Comment by yungs2017** [comment]
@wangyongzhi 你是怎样做到的？

**Comment by NogizakaZ** [comment]
刚更新了可以用了，不知道这回能持续多久

**Comment by bgylxue** [comment]
怎么更新？

**Comment by lucasat7startent** [comment]
请问在哪里更新  小弟跪谢了

**Comment by wangyongzhi** [comment]
我是付费专业版，https://github.com/getlantern/lantern/releases/tag/latest下载最新版
反正我是可以了，不知道你们什么情况

**Comment by wangyongzhi** [comment]
我是付费专业版，https://github.com/getlantern/lantern/releases/tag/latest 下载最新版
反正我是可以了，不知道你们什么情况

**Comment by beboyss** [comment]
并不能

**Comment by bgylxue** [comment]
还是不行啊

**Comment by lzzoro** [comment]
没有找到新版本啊

**Comment by IFUBAR2018** [comment]
4.12版本更新后，还是收费版变免费版本的。没法用。

**Comment by xiguataida** [comment]
瞎说么这不是，不能用的

**Comment by fxyFlash** [comment]
咱能不逗么 那是beta版

**Comment by fxyFlash** [comment]
那是beta版

**Comment by tade0726** [comment]
更新了能用了,  坐标深圳

**Comment by wangyongzhi** [comment]
没有瞎说啊，我的是能用的，并且也有朋友说能用了，不能用的我也不清楚怎么回事

**Comment by wangyongzhi** [comment]
@xiguataida 没有瞎说啊，我的是能用的，并且也有朋友说能用了，不能用的我也不清楚怎么回事

**Comment by wangyongzhi** [comment]
@IFUBAR2018 等下就好了吧

**Comment by manchuriasun** [comment]
老哥现在你那里能用吗？

**Comment by wangyongzhi** [comment]
@manchuriasun 从我发出来，一直能用啊

**Comment by wanlerong** [comment]
更新之后可以用了，坐标上海

**Comment by manchuriasun** [comment]
@wangyongzhi  看来那应该是北方出口还不行 南方几位用户都说可以

**Comment by jianglijs** [comment]
还是不行，深圳

**Comment by bgylxue** [comment]
我在上海，付费版，更新后还是不行

**Comment by WhiteSoulss** [comment]
河北邢台也不能用

**Comment by wroy1005** [comment]
帝都悲催

**Comment by lucien0coder** [comment]
广州。win10/Android 运行lantern 后卡死。片刻后，服务器位置N/A

**Comment by shipeng-uestc** [comment]
四川成都也不能用

**Comment by WhiteSoulss** [comment]
聽說Mac能用

**Comment by anticpc** [comment]
仅限Mac. Win版是挂了

**Comment by yungs2017** [comment]
Mac版已經不能用了

**Comment by Bentmj** [comment]
手机的20170929也能用

**Comment by yangmei1235** [comment]
手机的20170929为什么我的不能用了

**Comment by Koiter0314** [comment]
ive just downloaded from here,well-done,impressive.
