### ISSUE TITLE
老郭在开会，开完会就好了。大家耐心等待。其他的VPN估计不能用了吧？ 现在可以用了

### ISSUE THREAD

**Issue by guoxiaoxu** [getlantern/lantern#5999]
哈哈哈哈哈哈哈，大家不要着急。不能怪蓝灯，真希望我们的明天不是朝鲜。不能上GitHub的先把蓝灯关了就可以了。

**Comment by manchuriasun** [comment]
都没关注他 我们中午就不好使了 就算预防健身也没必要这么早

**Comment by manchuriasun** [comment]
而且我另一个ss到现在都不行呢

**Comment by Jared1015** [comment]
老郭是谁

**Comment by 237974969** [comment]
开个会，网都停了。

**Comment by Resister** [comment]
![image](https://user-images.githubusercontent.com/12710414/31338456-eab32100-ad31-11e7-8ef7-4f7bf67f7a83.png)

**Comment by Jared1015** [comment]
还有这种操作？

**Comment by manchuriasun** [comment]
@Resister  自由门现在可以？

**Comment by Resister** [comment]
@manchuriasun 我十分钟前可以，

**Comment by Jared1015** [comment]
还是不行啊 老郭开完会没

**Comment by leyliu** [comment]
还能怎么办，当然选择原谅他（逃。。。

**Comment by r23456r** [comment]
被人利用还不自知，这墙你们是白翻了

**Comment by harper8228** [comment]
拜托，会赶快开

**Comment by manchuriasun** [comment]
@r23456r   那位健身教练说什么做什么是他的事情  墙是另外的事情

**Comment by zcj252** [comment]
昨天还能用，我昨天还用来着

**Comment by trokjin** [comment]
翻不了为什么我github都上不去了，你们怎么上的？

**Comment by zlong0825** [comment]
这要折腾到哪一天呀～～～

**Comment by Lather0519** [comment]
这傻逼跳这么久不就1千多人，国家这么怕怕不是郭全说中了？

**Comment by xiguataida** [comment]
因该不是吧，郭文归现在说的话和轮子好像啊，怎么想好多都是骗人的，能有这么多人信？国家至于怕这么个小人物？除了手里有个几百亿还有什么？好羡慕，不但有几百亿还能肉身翻墙

**Comment by Kelvely** [comment]
Gov does have the technology to prevent free internet access tools. This is the scariest stuff.
