### ISSUE TITLE
总结一下最近发生的问题

### ISSUE THREAD

**Issue by Vywh** [getlantern/lantern#6011]
看了一下issues,发现有很多问题有重复，在此总结一下重要的问题。
1、lantern不能用了
这个肯定还是主要的问题，不用多说
2、lantern服务差
不是黑，lantern提供的服务真的和专业的VPN没法比。主要体现在没有提供能**对应到个人**的服务,Forum **管理**不好（3000+个open的issue、版规**不明确**，**更新缓慢**，没用的issue一大堆有用的issue没人回），对用户的疑问回复**消极**且**不明确**、没有技术性的回复
3、对于以后的疑问/迷惑
以后lantern还能不能用：这次技术上是为什么，以后能不能避免，是否代表着lantern已经可以被GFW识别并针对等等

有理由相信，如果官方回复能更及时，就不会有现在这么多重复的issue和抱怨，如果官方能公布/说明 更多的技术细节，就不会有现在这么多对lantern能不能用的质疑
希望官方能认真对待用户的意见

**Comment by SolCheung** [comment]
官方可能看不懂中文

**Comment by DanielJJJ** [comment]
大部分人已经把github当成了贴吧和中文论坛，正是因为过多的中文用户发的东西消极且不明确并且没有技术性，有的甚至还滥用发布广告，官方根本不可能理会这些东西，开发团队是美国人，lantern只是在中国拥有大量用户，并不是中国式开发和管理的软件。

**Comment by chen83193093** [comment]
昨天用限流量的免费版还能翻，专业版反而不能。这是怎么回事？

**Comment by panrenjie366** [comment]
昨天是GFW升级了算法吧，很多V   ）屁 （恩都挂了吧

**Comment by rlsz** [comment]
我常用的vpn都挂了，只有一个平时不用的，现在还勉强能用

**Comment by VsterLong** [comment]
蓝灯吧都被灭了，用户要说问题，那只能上这说了，你还想让用户还会跟你讨论技术？

**Comment by bigsyw** [comment]
不要说lantern不做事，封网的不是他们，也不是服务器爆炸，没钱了，这几天是练时连时断，就说明了问题，兄弟你要明白这是共产党为了19大维稳搞得黑科技，不是什么翻墙软件，vpn，服务器的问题，是他直接把国内连国外的物理端口断了，说白了就是物理断网，拔你家网线了，什么时候恢复，你该去问习近平，最有可能的是19大之后，如果19大之后还要继续封，让我们彻底变成朝鲜，那就是最坏的结果了，可能你一辈子都翻不了墙了。

**Comment by guoxiaoxu** [comment]
之前4K妥妥的，现在了？断断续续的1080P都不行。这个中国政府的错，你怪蓝灯毛线

**Comment by SolCheung** [comment]
楼上不能这么说，中国政府有什么错？封锁在某些时刻是必要的，国乱了什么都没了，想象一下如果现在你生活在印度，当然可以随便上网，不用翻墙，但是国家动乱，生活水平不能保证质量，想要在这发帖回复，也就不存在了。

**Comment by Vywh** [comment]
开发者应该有能看得懂中文的，不过我会找个空翻译一下的

**Comment by rlsz** [comment]
@bigsyw 还没有拔螺丝，这次只是针对VPN而已，其他手段还是可以翻过去的

**Comment by Vywh** [comment]
看来并没有开发者关注，打算关闭问题，有想保持打开的说一声
