### ISSUE TITLE
The lantern pro flashback

### ISSUE THREAD

**Issue by lyksoleo** [getlantern/lantern#6034]
I installed lantern from debian package for ubuntu 16.04 (amd64), but flashback comes after several weeks. When I type "lantern" in the terminal, flashback occurs immediately and the error tips looks like:
**panic: interface conversion: interface {} is *ecdsa.PublicKey, not *rsa.PublicKey**
 I've never used the go language, and I've no ideas whether this mistake comes from a bug or my own fault.

**Comment by dawnft** [comment]
[lantern.log](https://github.com/getlantern/lantern/files/1371308/lantern.log)

**Comment by lyksoleo** [comment]
I tried to remove the .lantern forder in home dir and it works = =|||
