### ISSUE TITLE
刚刚找到一个应急的VPN，浏览速度也还不错。

### ISSUE THREAD

**Issue by Lather0519** [getlantern/lantern#6040]
[PlexVPN注册网站](https://www.plexplan.com/register?invite_code=ZN2EUD)
中文蓝灯看到的，最高速度没测试，稳定性（能撑到蓝灯能用就行了）准备问管理员。
也挺便宜的，也就十几块一个月，大家先用着吧。
![2](https://user-images.githubusercontent.com/32637838/31385822-2de145ea-adf7-11e7-8134-7764acbcc34a.jpg)
## 2017年10月10日 21:12:26
管理员回答
![2](https://user-images.githubusercontent.com/32637838/31388172-c5f9c3f4-adff-11e7-88ba-60c11d303777.jpg)

2017年10月10日 21:06:11
在google找到未经验证的方法，请大家自行尝试
由此可知也许是新版蓝灯的问题，大家可以重新下载旧版蓝灯
![3](https://user-images.githubusercontent.com/32637838/31387956-f08fa45e-adfe-11e7-8844-35eb66346ec6.jpg)

**Comment by 775405984** [comment]
昨天刚注册，今天就发广告推广？

**Comment by Jesseszhang** [comment]
https://www.plexplan.com/register?invite_code=ZND6U5

**Comment by Jesseszhang** [comment]
it's work !

**Comment by Lather0519** [comment]
@775405984 你不想用就滚，别一口一句打广告，老子买了不少2年，轮不到你BB

**Comment by zzz4457** [comment]
可以用 谢谢分享🙏。不能翻墙感到十分焦虑。

**Comment by chen83193093** [comment]
It's interesting. Why it can work but lantern not?

**Comment by LETGOBUDDY** [comment]
付费了，但貌似用不起来啊大哥

**Comment by Lather0519** [comment]
@chen83193093 i dont know. they all using Alibaba sever.

**Comment by Lather0519** [comment]
@chen83193093 just maybe, lantern got something worng

**Comment by manchuriasun** [comment]
说起来怎么有人说天行好使 是哪个天行？

**Comment by Lather0519** [comment]
@manchuriasun 不晓得，反正现在哪个能用用哪个

**Comment by zhaoxieluoke** [comment]
@Lather0519   广告狗无疑(10月9号才注册的号)，别人还说不得你了？真是可以,请不要污染github

**Comment by manchuriasun** [comment]
卡在登录中 软件都打不开

**Comment by Lather0519** [comment]
@zhaoxieluoke 穷逼真是可怜，连一个VPN都要去怀疑人家是不是打广告

**Comment by LilockTT** [comment]
下载都下载不了

**Comment by kiRinoi** [comment]
亲测可以用，能上推和油管，不过速度不是很理想，大图和视频加载要点时间

**Comment by cerutao** [comment]
说自己不是打广告那你把链接里的推广码去掉啊，别当了婊子还立牌坊

**Comment by Lather0519** [comment]
@cerutao 这TM搞笑了，这是我分享出来的我还不能加推广码？用不用你们自己选；真要注册来用的，跟有没有我的推广码有什么关系？何况这是网站给的推广福利我干嘛不要，我又不是傻哔。你以为你这穷逼注册了能给我什么东西？只有买的人一个月才能给我5天。圣母婊又穷又傻逼，别翻墙了，好好当满狗的奴隶乖乖舔脚，废物。

**Comment by HeadCow** [comment]
现在能用吗，OSX上登上去也上不了google和youtobe

**Comment by cerutao** [comment]
@Lather0519 那你就等于承认自己是在打广告发推广，打自己脸咯，婊子

**Comment by Lather0519** [comment]
@cerutao 对，我就是打广告，但是你爹逼你用了？儿子？非要逼我当你爹是吧？傻逼东西。没智商就别翻墙，自己搭服务器去，弱智儿

**Comment by cerutao** [comment]
@Lather0519 你早点承认你是发推广靠你野爹们牙缝里剩下的施舍给你5天的穷逼不完了？干嘛当婊子又立牌坊，学学你妈，大大方方的承认自己是婊子给你找野爹。
哦对了，弄了半天是个才注册几天的小号，换你大号再来回爹话。
