### ISSUE TITLE
我发现一个问题，就我刚刚推荐的plexVPN

### ISSUE THREAD

**Issue by Lather0519** [getlantern/lantern#6045]
我手机打不开蓝灯（之前可以打开只是上不了），一打开就秒退，连界面都见不到，后台也没有。
然后我现在开着plexVPN。我怀疑……这次蓝灯不能用……是有原因的

别的帖子有人说蓝灯被人攻击，我觉得有可能，plex用的也是阿里云的服务器，为什么他没事？
完啦，一不小心就当了“帮凶”

还想坚守蓝灯的，试试这个方法
![1](https://user-images.githubusercontent.com/32637838/31389426-9da80b96-ae03-11e7-8b5c-d3ac3596853c.jpg)

**Comment by Lather0519** [comment]
别的帖子有人说蓝灯被人攻击，我觉得有可能，plex用的也是阿里云的服务器，为什么他没事？

**Comment by Lather0519** [comment]
完啦，一不小心就当了“帮凶”

**Comment by LETGOBUDDY** [comment]
@Lather0519 被你猜对了，lantern的总部被外星人占领了。要么就是lantern的老板找到了失散多年的小兄弟（你懂的），然后跟小姨子度假去了。

**Comment by manchuriasun** [comment]
这个plex一安装之后打不开 死循环了

**Comment by Lather0519** [comment]
@manchuriasun 问问管理员吧，他回复挺快的
