### ISSUE TITLE
PlexVPN亲测可用！https://www.plexplan.com/register?invite_code=ZBQ3UT

### ISSUE THREAD

**Issue by godera** [getlantern/lantern#6060]
PlexVPN亲测可用！
https://www.plexplan.com/register?invite_code=ZBQ3UT

**Comment by hardwigg** [comment]
恕我直言，你的出發點很好，但是有可能帶來更多軟件的封殺

**Comment by godera** [comment]
谢谢朋友们的照顾，我的免费时长增加到 15天了

**Comment by godera** [comment]
@hardwigg PlexVPN官网注册页面打不开了。真被你说对了

**Comment by hardwigg** [comment]
低調行事吧，我覺得在這裡嚷嚷誰都沒有好的結果，畢竟git也被限制了
