### ISSUE TITLE
撑起无灯的日子：ExPressVPN 亲测可用！http://www.expressrefer.com/refer-friend?referrer_id=14223062&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard

### ISSUE THREAD

**Issue by godera** [getlantern/lantern#6061]
撑起无灯的日子：ExPressVPN 亲测可用！
光发自己的推广链接了。下面这个是优惠3个月的链接。
https://zh.vpnmentor.com/coupons/expressvpn/?with_code=2&coupon_id=73519

**Comment by provxy** [comment]
expensive

**Comment by Jared1015** [comment]
太贵

**Comment by KeborKing** [comment]
激活时没连接是什么情况？

**Comment by godera** [comment]
@KeborKing 激活后需要选择VPN服务器才能链接。一般我选香港的 Hongkong

**Comment by godera** [comment]
嫌贵的朋友用下面这个，PlexPlan凑合用，应该是正规备案过的，稍微慢一点点，挺好的。
https://www.plexplan.com/register?invite_code=ZBQ3UT
朋友帮我把使用天数拓展到15天了。原来翻墙的需求这么强烈啊

**Comment by KeborKing** [comment]
刚买的跟我说激活码错误，没法激活 @godera

**Comment by KeborKing** [comment]
不解释一下吗？ @godera

**Comment by godera** [comment]
@KeborKing https://www.expressvpn.com/setup 你的激活码是这里的么？

**Comment by godera** [comment]
我这边激活正常啊。晕死。不行你重启试试？

**Comment by KeborKing** [comment]
我TM重启好多次了

**Comment by godera** [comment]
@KeborKing 去网页的右下角，告诉他们你想 退款。I want to be refunded. 换用PlexPlan吧
https://www.plexplan.com/register?invite_code=ZBQ3UT
反正ExpressVPN是无条件退款的。
