### ISSUE TITLE
plexVPN邀请码~ 等灯亮

### ISSUE THREAD

**Issue by LionelDong** [getlantern/lantern#6103]
https://www.plexplan.com/register?invite_code=ZNK8UV

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3
