### ISSUE TITLE
Lantern挂了，shadowsocks也挂了，都用不了，PlexVPN竟然能用

### ISSUE THREAD

**Issue by xieHugo** [getlantern/lantern#6105]
亲自OK，安全没问题！推荐免费注册链接https://www.plexplan.com/register?invite_code=XWYVUZ 
  或者自己去官网注册，输入邀请码XWYVUZ

**Comment by baiking** [comment]
vpnexpress 有没挂？

**Comment by babytree** [comment]
真不知道工信部怎么想的，开放还是闭关自守

**Comment by beboyss** [comment]
钓鱼用的，哈哈

**Comment by johnx7271** [comment]
狗洞也钻不了了，彻底的享受到了人类命运的共同体。

**Comment by shangxinbo** [comment]
这个讨论区已被病毒感染，珍爱生命，远离这里

**Comment by anticpc** [comment]
ss稳如狗

**Comment by 1608637229** [comment]
自建ssr稳如狗，不要买这种，到时候跑路了，人都找不到。

**Comment by lyyx0000** [comment]
SS要不要在youtube飚4K？飚得起来吗？哈哈哈哈哈 当我隐身的
