### ISSUE TITLE
PlexVPN 能用， 其中韩国线路还算快

### ISSUE THREAD

**Issue by hexawp** [getlantern/lantern#6106]
用这个链接进或者使用邀请码送24小时， 可以去试试

https://www.plexplan.com/register?invite_code=ZGNAUC

我的邀请码：ZGNAUC

小缺点就是用起来没有以前蓝灯快，而且两台设备要收双倍钱

**Comment by flybywind** [comment]
为什么没法充钱。一直在旋转。。。

**Comment by shangzekai** [comment]
好像还是没法连接    一直超时错误

**Comment by hexawp** [comment]
我可以一直连着韩国首尔那个点， 别的老断开
