### ISSUE TITLE
YouTube 1080P 无卡顿~

### ISSUE THREAD

**Issue by zgxsg** [getlantern/lantern#6110]
https://www.plexplan.com/register?invite_code=XENZU8

首先 你要知道 只要是vpn 就不可能有隐私一说, 让官方审查了也没啥问题吧, 反正你又不干坏事~  官方是不反对正规使用VPN的~~~

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3

**Comment by toddwong** [comment]
有人能解释下这个动机吗？ 费那么大力气建设GFW， 只为挣这点小钱？ 
等我先观望观望。。。
