### ISSUE TITLE
没必要非要争来争去

### ISSUE THREAD

**Issue by zgxsg** [getlantern/lantern#6122]
你不干坏事 谁动你啊~~~   网络本身就是一个舆论市场 肯定要管控~  
还有人不知道 他们说的Plex是什么  那么我就发个推荐码~~

https://www.plexplan.com/register?invite_code=XENZU8

**Comment by zgxsg** [comment]
每个地方都有每个地方的规矩,不想遵守这里的 你们去其他地方去啊~~

**Comment by beboyss** [comment]
真是脑子被洗的已经没多少干货了，你同意网络需要监管你还翻什么墙，你要脱离监管么？

**Comment by zgxsg** [comment]
问题就是 又那么一些人翻墙 做坏事~~~   我翻墙也就是看看技术方面的东西~~     那些乱七八糟的你即便看了有什么用???   舆论本身就是 我说我对 他说他对 我说他错 他说我错~~~  
翻墙难道仅仅是为了脱离监管~~  这个说法太狭隘了~

**Comment by kevinsarch** [comment]
说客观的 为什么有那多人想做坏事呢？ 逻辑是这样的  有人在散布反动言论 煽风点火 所以大家都不用上了了 这样最好？  我觉得这个事情不该是这么个道理  难道作为一个人的权利就可以这么被随便控制吗   更恶心的是 没有官方承认 这就是欺负人

**Comment by zgxsg** [comment]
人无完人吧~ 任何事物都有缺点和优点~

**Comment by kevinsarch** [comment]
哎 其实根本没有人在乎我们说什么 就是 好气啊

**Comment by zgxsg** [comment]
发现问题是好的 解决方案什么的 都得做 没好的方案出来前 不可能一刀切  即便是 开始监管网络这件事 不也是闹了好些年才定下来~~  毕竟是一个国家  如果是自家的事 可能会说大不了错就错了 一个国家在决策上出错是灾难性的 历史上不上没出现过, 既然都希望中国越来越好~  那就迁就一些  一起改善他呗~
写项目还能出个bug呢~  是吧~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by littleguyy** [comment]
@kevinsarch 别听他放屁，周小平以前是个开黄网的，还被刁点名抬出来当5毛了，用一个开黄网的当全国人民的公知，这是学好还是学坏？傻逼都懂。

**Comment by yiweigang** [comment]
一群傻逼整天想着人权言论自由跟个小孩子似的，你想要别人顾及你的感受就让自己变得让别人不得不注意到你啊，本来翻墙目的就是为了进行必要的对外交流而不是去看那些国外主流媒体瞎扯淡的，你们喜欢看国外自由媒体的报道可以请求你们的爸爸收留你们

**Comment by manchuriasun** [comment]
@yiweigang  B站爱国宅男真搞笑 什么是必要的谁是瞎扯淡  你党妈妈允许你给人批发外国爹帽子了？

**Comment by toddwong** [comment]
@zgxsg 能不能用谷歌？能不能上 youtube？ Stackoverflow快不快？ 这些基本是我的核心需求。npm什么的都可以忍。

另外，别整么没用的， 你以为大伙不知道怎么回事？ 怕人翻墙干坏事？ 怕人翻墙看不该看的东西？ 怕人翻墙说不该说的话？ 胡扯！ 我就没有见过这么负责任的政府部门！ 无论是标榜自由的还是标榜经济的！
说到底还不是利益？ 一个GFW养活着多少大公司！ 保护着多少大公司！ 让多少所谓的精英占据知识至高点忽悠大众！但既然是利益问题，也就无可厚非了！

**Comment by Curriculu** [comment]
此贴鉴定，plexVPN和五毛是同一群人。共产党愚蠢野蛮残暴，真以为只有一群人不满啊。

**Comment by JohnFang** [comment]
@zgxsg 翻墙的人就是潜在的反华分子。不定哪天你就被西方邪恶势力不知不觉洗脑了。你现在翻墙不干坏事，谁知道你将来会不会干？网警就该抓你这种不稳定因素。

赶紧把翻墙软件全删了！还看什么技术资料？将来变成我这种天天翻墙干坏事的人后悔死你。
