### ISSUE TITLE
提供一个翻墙的办法非VPN

### ISSUE THREAD

**Issue by smnetres** [getlantern/lantern#6124]
原理是ipv6的暂时不可墙性
前提要有公网ip 虽然这一点就干掉一批人家
使用tunnelbroker

附赠一个不用公网ip的
6plat.org  46模块
同理

**Comment by smnetres** [comment]
懒得打字了，自己悟吧

**Comment by shown1985** [comment]
感谢思路，已通

**Comment by SJTUboy** [comment]
学生党表示感谢

**Comment by smnetres** [comment]
然而今天6plat宣布停止注册

此帖终结

**Comment by SJTUboy** [comment]
我刚刚

**Comment by SJTUboy** [comment]
发了一封，还是可以注册的好像

**Comment by smnetres** [comment]
提交注册
但不予以审核

**Comment by SJTUboy** [comment]
恩呢，学校有原生IPv6和IPv4地址支持，我先试试tunnelbroker

**Comment by smnetres** [comment]
有原生v6直接改dns就行了
tunnelbroker是在v4下访问v6的工具，而且要公网ip，你用不了的

**Comment by SJTUboy** [comment]
我在win上改好DNS已经可以成功用ipv6，但我的mac和手机不能正常用Google,所以希望有v4到v6转换，我现在两根网线交换机直出，一根用v6直连win，另一根连路由器供mac和iphone，但家用路由器NAT之后，mac和iphone用不上V6,比较头疼

**Comment by SJTUboy** [comment]
两根网线都有各自的V4和V6地址，不冲突的

**Comment by smnetres** [comment]
可以参考http://blog.sina.cn/dpool/blog/s/blog_130f5e21b0102wpml.html
在局域网内建立一个openvpn服务器，在手机上装客户端，通过win代理访问

**Comment by SJTUboy** [comment]
谢谢^_^

**Comment by SJTUboy** [comment]
弄了一波，公网IP要使用tunnelbroker的话，也是网线直连才行，家用路由器后面无法转发成功，支持41协议即IPv6的路由器可以使用局域网IP进行配置
心痛到不能呼吸

**Comment by SJTUboy** [comment]
windows的弄好了，改的DNS
刚在折腾的是路由器后面的MacBook，它是WIFI连接

**Comment by SJTUboy** [comment]
我现在想复原设置，不知道怎么弄le
<img width="541" alt="screen shot 2017-10-13 at 17 26 50" src="https://user-images.githubusercontent.com/13373715/31539818-6934b018-b03c-11e7-923c-4ad052a98084.png">
ifconfig命令看到多出几条有点不舒服

**Comment by SJTUboy** [comment]
<img width="507" alt="screen shot 2017-10-13 at 17 33 22" src="https://user-images.githubusercontent.com/13373715/31539913-a9772818-b03c-11e7-9913-2fcb535f5a5c.png">
这是ifconfig结果截图

**Comment by smnetres** [comment]
sorry我不懂

**Comment by SJTUboy** [comment]
还是谢谢您^_^

**Comment by smnetres** [comment]
你使用的tunnel broker?
