### ISSUE TITLE
Lantern 4.2.1-beta2 恢复正常

### ISSUE THREAD

**Issue by SJTUboy** [getlantern/lantern#6146]
如题，macOS 10.13 和 Windows 10 64bit下，Version 4.2.1-beta2恢复正常，可以观看YouTube 4K视频
![snipaste_20171014_101246](https://user-images.githubusercontent.com/13373715/31571592-7978df3a-b0c8-11e7-86ff-82de075661c4.png)

**Comment by rotencode** [comment]
什么地区，什么isp?我表示不行。

**Comment by ZhangQian261** [comment]
Windows 10  64bit 可以使用 。手机端不行。

**Comment by SJTUboy** [comment]
上海，电信与联通

**Comment by SJTUboy** [comment]
Lantern团队建议在精华贴下反馈，因此关闭 issue
