### ISSUE TITLE
Mac更新至4.2.2正式版已能用

### ISSUE THREAD

**Issue by Story5** [getlantern/lantern#6178]
https://github.com/Story5/Story5/blob/master/Gif/lantern.png

**Comment by GithubHiLeo** [comment]
Mac可以，只是YouTube网速很差，看视频最模糊的也需要缓冲好才可以看。
Windows的暂时不知道能不能用。

**Comment by ceeyang** [comment]
还是不行啊，快被世界隔绝了的赶脚。

**Comment by Story5** [comment]
@ceeyang 坐标上海,mac4.2.1beta2已可用

**Comment by ceeyang** [comment]
@Story5 好忧伤，一直提示连接中，请问您是的系统版本是多少？

**Comment by GithubHiLeo** [comment]
@ @ceeyang 把原来的卸载干净，从论坛首页code那里下载，然后安装就好了。

**Comment by myvary** [comment]
坐标北京,打开就可以用。没有更新

**Comment by ding209** [comment]
能用毛线啊。。。

**Comment by zerototoone** [comment]
mac4.2.1beta2 是下载哪个文件呢？

**Comment by Story5** [comment]
@ceeyang mac系统版本10.13.1 Beta (17B35a)

**Comment by Story5** [comment]
@zerototoone 这里https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg

**Comment by ceeyang** [comment]
依然无法使用，好无奈啊，好绝望啊，啊，Google。
![Uploading 1508121305774.jpg…]()

**Comment by GithubHiLeo** [comment]
@ceeyang 我一直很稳定，可以用。

**Comment by ypp188** [comment]
兄弟，还是不能使用。亲测不能

**Comment by xavierXing** [comment]
北京连不上,一直显示连接中,之后无响应...

**Comment by Story5** [comment]
4.2.2正式版已更新,不能连的再尝试更新到最新版看看https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg
