### ISSUE TITLE
蓝灯可以用了

### ISSUE THREAD

**Issue by zhaoweihaoChina** [getlantern/lantern#6193]
![tim 20171016143241](https://user-images.githubusercontent.com/25500786/31598234-0cec25ee-b27f-11e7-850c-ae8909bec791.png)
Lantern 4.2.2 (20171016.045111)可以使用，感谢灯为我们自由上网做出的努力

**Comment by iamthek** [comment]
蓝灯还是比较有信用的 我们要用行动支持它 
分享神秘代码 **JBK374**

**Comment by zhaoweihaoChina** [comment]
不过还是不稳定，时连时断

**Comment by himawari8** [comment]
邀请码 **LKUN98**

**Comment by zhaw8869** [comment]
twitter打不开
