### ISSUE TITLE
好友购买两年套餐后，会赠送双方3个月。 邀请码 YMUUGPJ

### ISSUE THREAD

**Issue by godera** [getlantern/lantern#6206]
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。
分享您的邀请码
YMUUGPJ

**Comment by iamthek** [comment]
请不要发只有邀请码没有其他内容的帖子

**# 优惠码JBK374**

**Comment by godera** [comment]
OK，thank you！
