### ISSUE TITLE
mac你们是怎么下载到最新的4.2.3的,为什么我下载下来一直是4.2.1-beta2

### ISSUE THREAD

**Issue by Story5** [getlantern/lantern#6219]

**Comment by tcloaa** [comment]
同问

**Comment by henryatman** [comment]
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-*.*.*.dmg

懂？

**Comment by Story5** [comment]
@henryatman 懂,但是不好使,下载下来只有15bytes

**Comment by SJTUboy** [comment]
我这里也是15bytes

**Comment by maosuyun2009** [comment]
同问，我下载下来的也都是4.2.1 beta版

**Comment by DEADGODImmathplus** [comment]
以下是lantern的最新版本
Android版：4.2.2
Windows：4.2.1 beta
iOS：未知

官网都下载不到4.2.3这个版本，应该是没有出来

**Comment by imkerberos** [comment]
你们被种木马了.

**Comment by Story5** [comment]
我看release已经到4.2.4了
