### ISSUE TITLE
lantern with bug to access to google scholar

### ISSUE THREAD

**Issue by pobingwanghai** [getlantern/lantern#6237]
google report:
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
test issues:
without lantern ,can access to scholar, with lantern, report error.
so it is not the problem of my internet or computer, it is a bug of lantern

**Comment by cryobeer** [comment]
The same problems. How to do?

**Comment by pobingwanghai** [comment]
@cryobeer no thing we can do, waiting for the official report

**Comment by pobingwanghai** [comment]
@marcenuc @fuentesjr @michaelneale @robertkrimen

**Comment by chengbian** [comment]
Lantern is bad now. I spent money to buy a professional version,But the lantern does not provide me with services.Hope that the United States friends can sue the lantern company.
