### ISSUE TITLE
你们谅解蓝灯不，19大

### ISSUE THREAD

**Issue by keyus** [getlantern/lantern#6251]

**Comment by ysffood** [comment]
因为19大，蓝灯不能用了？是暂时不能用，还是后面也不能用了，我刚买的一年的

**Comment by yang361** [comment]
我也是

**Comment by makotolove** [comment]
同问

**Comment by glasstr** [comment]
可能按照大家的想法，这是个商业原则吧？lantern 承诺翻墙，然后付了钱，后来不能翻了，这项服务不能用，就是卖方失约，一些同志要求赔偿或者退款也是应该的，不能说谈守信就变成谈政治了。lantern 似乎没有服务条款之类的东西，不过，反正是灰色地带，一说一听的事情。

19 BIG 算不可抗力吗，这是个很复杂的问题？（眯眯眼）

**Comment by watchzerg** [comment]
要求退款的童鞋们说的其实也有道理，完全可以理解，特别是有的刚买不久就不能用了。
我买了lantern已经快2年了，一直很稳定。虽然我的会员还有一年多才到期，但是我个人是完全理解19 BIG期间的服务不稳定的。

**Comment by blogrocks** [comment]
前几天百度搜"蓝灯"还能搜到有些人发的蓝灯不能用的消息的，今天一搜，空空如也。我也是买了2年不久。

**Comment by yangzhiyao** [comment]
要求别太高，到时候github打不开就不好了

**Comment by sjtutyx** [comment]
当然是选择原谅她呀
===
多年以后 
我的孩子看到 
我收藏夹里的这些 
他问我他们是什么 
我告诉他 
谷歌是一首歌 
推特是一只鸟 
脸书是一个面具 
游图比是一张地图 
因斯特格让木是一幅名画 
他问我为什么都打不开 
我说因为从未存在过 
只是西方古老的传说。 
by 楚襄

**Comment by ceeyang** [comment]
@sjtutyx  强势围观。Lantern 很给力了。【微醺】

**Comment by sjtutyx** [comment]
@ceeyang lantern的确给力，可是最近不能用啊。

**Comment by parsea** [comment]
我以前经常喜欢说，但是每次一说就被别人反对，现在我不愿意说了，因为说了会给自己引来灾难，我觉得人活一辈子很多时候都是很郁闷的

**Comment by Zonz-Ly** [comment]
當然支持燈燈啊，這陣子過了就好了嘛

**Comment by cyumeng** [comment]
大伙儿，作恶的不是蓝灯，对吧？！
对一些新用户来说，蓝灯最多算欺诈。

**Comment by BobbyBelieve** [comment]
可以用了

**Comment by XxxPbin** [comment]
@BobbyBelieve 你的是什么网络呢，电信吗，我的显示有脸上服务器，不过还是翻不了。。

**Comment by XxxPbin** [comment]
我觉得可以理解，前面半年一直在用，速度一直很快，看看这某大会开完了能不能完全的修复过来。。

**Comment by lua9520** [comment]
#6250

**Comment by work-chausat** [comment]
google用不了，太影响工作了，哎。。。

**Comment by bboym** [comment]
google.uulucky.com谷歌镜像啊

**Comment by lordcheng10** [comment]
蓝灯现在 还能用吗 19big结束了 怎么还不能用，一直显示 连接中

**Comment by keyus** [comment]
终结此话题时，正值遇到两会期间，所有蓝灯又开始不蓝了。

**Comment by sjtutyx** [comment]
其实还是可以蓝的，
