### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by unixzii** [getlantern/lantern#6253]
I've noticed that this repository hasn't been committed since June, and there are few collaborators to reply issues. I wonder whether this is still being maintained?

**Comment by hex-m** [comment]
There are [releases](https://github.com/getlantern/lantern/releases) being uploaded regularly but no code commits. There is also [another repository](https://github.com/getlantern/lantern-binaries) containing only binaries which was updated today. Is there another repository containing the latest source code?

**Comment by 4044ever** [comment]
There just a new android version a few days ago.

**Comment by unixzii** [comment]
Got it!
