### ISSUE TITLE
上海 Lantern 4.2.5已恢复，4K YouTube 视频无压力

### ISSUE THREAD

**Issue by SJTUboy** [getlantern/lantern#6291]
线路为移动，联通，4K视频可以流畅观看

**Comment by blogrocks** [comment]
听你这么一说，在公司试了一下，电信网，确实可以了。但不知道出租屋里的长城宽带怎么样。我前几天在长城宽带下用ss，用了一会儿就被封了，重建了个vps实例不同的IP地址才能翻墙了，但是最近是不敢在长城宽带下用ss了。晚上回去试试lantern，希望也是可以的，毕竟刚交了两年的钱。

**Comment by hfghgakjd** [comment]
你好，可以给个4.2.5的下载链接吗？

**Comment by Story5** [comment]
@hfghgakjd https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg

**Comment by hfghgakjd** [comment]
@Story5 你好，这个链接是4.2.2版本的，安卓依然用不了

**Comment by GithubHiLeo** [comment]
4K流畅是给力的。
我这只是1080可以流畅，估计跟我自己宽带有关。

输入我的邀请码 YMDFKFH 来获得三个月的蓝灯专业版！

**Comment by zuokanni** [comment]
我的也是YouTube 4K视频无任何压力。推荐个可以免费下载YouTube 4K视频的软件，Gihosoft TubeGet, [http://www.gihosoft.com/free-youtube-downloader.html](url)

**Comment by XxxPbin** [comment]
确认可以吗，成都电信，升级到新的客服端，显示能连上国外服务器，但是还是翻不了墙，

**Comment by XxxPbin** [comment]
需要改host什么的吗

**Comment by myhelloos** [comment]
@XxxPbin 
上海电信 同样无法使用

**Comment by chenggangcxy** [comment]
成都电信用不了

**Comment by XxxPbin** [comment]
@myhelloos 
@chenggangcxy
刚刚试了下，只要图标提示已连接了还是可以上，就是不太稳定，一会又重新在连接中了

成都电信，
好像移动联通是要好连一点的样子，前段时间回家用的就是移动，就没什么问题

**Comment by godera** [comment]
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。
**邀請碼 YMUUGPJ**
