### ISSUE TITLE
没有经过工信部备案就违法经营VPN业务，坑中国消费者的钱

### ISSUE THREAD

**Issue by reaIws** [getlantern/lantern#6333]

**Comment by zyczzh** [comment]
....还好我没花钱...不过想想你交的网费居然是局域网的费用是不是会觉得更坑呢？

**Comment by reaIws** [comment]
我能翻墙了，还是免费的！！！！

**Comment by beboyss** [comment]
哪个vpn在工信部备案了

**Comment by imzlspace** [comment]
同问。。。正在百度哪个VPN通过了

**Comment by reaIws** [comment]
没有呀，所以是违规经营，肯定要被查封，最后亏 的还是我们消费者；没有备案，竟然还在官网宣传，秒杀VPN，诱使我们购买服务，最后被查，靠，无良商家

**Comment by reaIws** [comment]
虽然没有备案的VPN，但是还有免费可用的VPN啊，而且速度秒杀收费VPN，我这个Issues的重点是，**没有备案却收费，收费了却没法使用，这是对我们消费者的不负责人，现在都像缩头乌龟一样，没有一个人来解释，并安抚大家的情绪**

**Comment by duke91** [comment]
为什么要备案？

**Comment by LunarisDream** [comment]
你觉得公安不断找新的方法封VPN是VPN的错？问题明摆着呢，你觉得不满去找政府啊

**Comment by reaIws** [comment]
上面的人。搞清楚点，政府没说禁止提供vpn服务，而是提供vpn服务的公司要获取，工信部许可，懂么

**Comment by aelxsam** [comment]
你們沒發現 麼？ 他這是釣魚。 上面回覆的都是 掉坑裏面了。

**Comment by reaIws** [comment]
他们在中国挣钱，就得遵守法律法规，不然就会搞成现在这样，一堆人说退钱

**Comment by reaIws** [comment]
钓你 妈

**Comment by atricfox** [comment]
靶子立错了！

**Comment by Danielshara** [comment]
智商捉急

**Comment by hhzhaoheng** [comment]
智商堪忧啊，兄弟

**Comment by reaIws** [comment]
@hhzhaoheng 我就随便喷喷，你就认真了，跟我讲智商了，哈哈，sb
