### ISSUE TITLE
有退款渠道么

### ISSUE THREAD

**Issue by Aragronsam** [getlantern/lantern#6366]
既然蓝灯不能用，官方也不给说法（注意到最新的公告是十几天之前），那么，有退款的渠道么，流程是怎样？@蓝灯@lantern

**Comment by beboyss** [comment]
只有收款通道 :1st_place_medal:

**Comment by the263** [comment]
同问，这个ISSUE请官方认真对待。

**Comment by Sum41forever** [comment]
这个问题 我是支持的

**Comment by chenggangcxy** [comment]
只进不出

**Comment by xuqin0224** [comment]
这个问题支持，要么退钱，要么什么时候处理好？都没人站出来说话的。
