### ISSUE TITLE
最新版 断断续续能用

### ISSUE THREAD

**Issue by devefx** [getlantern/lantern#6391]
最新版 断断续续能用

**Comment by devefx** [comment]
Mac、Android都他妈不能用（不用Windows系统）

**Comment by cappiewu** [comment]
2017年10月27日 23:36:35，广东电信宽带及广东电信4G，测试能用

**Comment by Xanthuim** [comment]
还是不能用

**Comment by draculaz** [comment]
坐标北京，最近一周，断断续续。昨天、今天，皆不可用。想退款！

**Comment by huadee001** [comment]
实测可以用。我在用小米国际版

**Comment by wang92bing** [comment]
手机非专业版可以用，win10不行

**Comment by yjdwbj** [comment]
今天，蓝灯4.3.2 debian9 ,广东，还是不能用。

**Comment by willshion** [comment]
广东2017年10月28日14:02:37不能 
不能 安卓 win不能

**Comment by webw3c** [comment]
不能用，大家有什么推荐 :-)

**Comment by Chester0720** [comment]
官方人呢？怎么退款啊？我日！

**Comment by bearlittle** [comment]
坐标广州上周开始联通Mac最新客户端就可以用了 但是经常无法连接而且网速不稳定，经常需要重启路由然后重新连接，这两天没有出现无法连接的情况。公司电信网络，windows之前无法使用（最新的客户端），今天突然想试一下，可以用了
![default](https://user-images.githubusercontent.com/23275517/32133073-240312b4-bc03-11e7-9819-18abe44e0507.png)

**Comment by devefx** [comment]
mac 4.3.2 打开lantern连正常网页都打不开，退出软件都要卡半天

**Comment by mengzawj** [comment]
不能用

**Comment by sn00wman** [comment]
能用，杭州移动
