### ISSUE TITLE
退款吧，怎么能这么无耻呢？

### ISSUE THREAD

**Issue by TroyRay** [getlantern/lantern#6445]
呵呵，翻不了墙还不退款，做人不能这么无耻！

**Comment by forestwanglin** [comment]
我也上不了了，能退款吗，还有一年呢

**Comment by AndroidZern** [comment]
我能说我还有两年吗？

**Comment by eggcn** [comment]
上不了啊~能连接看到一会印度，一会日本的，偶有打开但是马上就断了，受不了了。眼瞅着1个月过去了，能不能先退款，好用再买吧。
