### ISSUE TITLE
为啥我的都可以用？而你们的却不能用》坐标杭州

### ISSUE THREAD

**Issue by guoxiaoxu** [getlantern/lantern#6453]
不能用的请卸载掉你们的杀毒软件，请用chrome浏览器。还有卸载掉那些没用的国产软件。

**Comment by guoxiaoxu** [comment]
win4.2.5 安卓4.1.4/4.2.2/

**Comment by moondcr** [comment]
@guoxiaoxu 你用的版本是哪个？

**Comment by huadee001** [comment]
坐标广州，成功上线
需要最新蓝灯，顺便说不要安装国产。国产你懂的..
请用外国chrome浏览器
