### ISSUE TITLE
买了一年的会员却没法用，之前还给官方发过邮件咨询的其他问题也无回应

### ISSUE THREAD

**Issue by victorchen2045** [getlantern/lantern#6500]
这就是个骗子啊，我看帖子还说github不欢迎喷子，那github就是个开源社区你收费干什么？你既然收了钱为什么不解决问题？我几个月前就发邮件了从没收到回应，现在连用都用不了了？github不欢迎你们这些骗子，我要举报了

**Comment by asdio** [comment]
我也好久上不去了，还好我还买了多态，那个还能用

**Comment by victorchen2045** [comment]
@asdio 我刚又重新试了一下可以用了，我用之前那台电脑的授权码关联一下才行，目前来看，只有免费版的不能用了，此贴终结，我还是希望官方在售后方面能做好一点，买了一年的会员感觉毫无保障很不踏实
