### ISSUE TITLE
感谢lantern，已全面恢复，经测win和Android已使用两天未发现断开状况，随便分享下邀请码 YP37UQT

### ISSUE THREAD

**Issue by AnakinSkyW** [getlantern/lantern#6552]
之前一直是免费版可用，专业版各种不行，前天在反馈里提交了问题，下午就恢复了

**Comment by lxbboy326** [comment]
点击升级为专业版，为什么一直卡着不动呢？

**Comment by AnakinSkyW** [comment]
@lxbboy326 直接卸载 下载最新的包安装

**Comment by songxuangh** [comment]
## 输入我的邀请码

> # GY6S6C

## 来获得三个月的蓝灯专业版

**Comment by ZandEandV** [comment]
android google store上的app无法下载，不知道大家的怎样
