### ISSUE TITLE
灯上周已恢复正常，输入我的邀请码 YGV83WK 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by userfirstone** [getlantern/lantern#6563]
输入我的邀请码 YGV83WK 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
![eqhmq fruy i c xv](https://user-images.githubusercontent.com/32631032/32593607-7df8ad42-c563-11e7-9a2f-1abc274e68d0.png)
![gg7xr h60p mjr4e c 0 a](https://user-images.githubusercontent.com/32631032/32593672-bb8fd720-c563-11e7-8a49-7217408217e4.png)

**Comment by songxuangh** [comment]
输入我的邀请码

> **GY6S6C**

来获得三个月的蓝灯专业版
