### ISSUE TITLE
错误或者无效的设备关联码 ，请尽快帮我解决这个问题，我已近反馈好几次，等了很久了！！！！！！！！！！

### ISSUE THREAD

**Issue by zackfly** [getlantern/lantern#6571]
![image](https://user-images.githubusercontent.com/5593858/32686749-41582f28-c6e6-11e7-84e1-bc884bfb1ae5.png)

无法给我的pc授权
账号3996643046@qq.com
同时界面里目前有两台设备能用 但是只能看到一台

ps. 这个邮箱是我注册的时候写错了，能改成huxiaofan@outlook.com吗？

**Comment by zackfly** [comment]
@angelwithout @Ghostwithout @GLantern

**Comment by zackfly** [comment]
@angelwithout  please contract me

**Comment by songxuangh** [comment]
## 输入我的邀请码

> # GY6S6C

## 来获得三个月的蓝灯专业版

**Comment by zackfly** [comment]
@Ghostwithout
