### ISSUE TITLE
#BUG 关闭蓝灯后不会自动恢复代理服务器

### ISSUE THREAD

**Issue by DaGeger** [getlantern/lantern#6582]
关闭蓝灯后不会自动恢复代理服务器，打开国内网页会出现代理服务器错误，需要手动关闭internet选项的代理服务器才能恢复正常，这个问题在window和ubuntu平台都存在

**Comment by DaGeger** [comment]
问题出现场景，使用蓝灯后关闭软件，重启系统后代理服务器地址会改变为127.0.0.1:51979，这样会影响正常上网，必须手动关闭后才能访问网页，请修复！

**Comment by songxuangh** [comment]
## 输入我的邀请码

> # GY6S6C

## 来获得三个月的蓝灯专业版

**Comment by BroQiang** [comment]
## 我也有这个问题，只能自己写个脚本解决了

#### 在家目录下创建一个 bin 目录
```sehll
mkdir ~/bin
```

#### 然后在 bin 目录下新建一个 lantern_clear （名字随意起)，写入下面内容：

```shell
#!/bin/bash
#

if ps aux | grep 'lantern$' > /dev/null ; then
    killall -9 lantern
fi

gsettings set org.gnome.system.proxy mode 'auto'
```
#### 给脚本添加执行权限
```shell
chmod +x ~/bin/lantern_clear
```

## 然后执行脚本就可以将lantern结束了

#### 终端直接执行或者 `Alt+F2`执行 lantern_clear

#### 可以在 ~/.bash_logout 中执行脚本

这样可以在每次关机或者注销的时候检测一下lantern，如果存在就可以自动取消，下次登录就是正常的网络了。

编辑家目录下的 .bash_logout，再最后加上

```shell
# 目录根据实际的目录去配置
/home/bro/bin/lantern_clear
```

希望能帮助到遇到相同问题的人，这个是我的解决方案，虽然要手动搞一下，但是基本还是比较方便的。

**Comment by KingMario** [comment]
mac系统下，代理被设置成 127.0.0.1:61283，但系统设置里却没有，不知道去哪儿改，所有海外站点包括 github 都上不了了。
