### ISSUE TITLE
转手自己的Lantern账号

### ISSUE THREAD

**Issue by LeonDong1993** [getlantern/lantern#6587]
Lantern近期实在是太不稳定了，现在买了VPS自己搭了SS。
10.5号左右买的专业版，现在还剩12个月多，有谁要的么。
联系 LeonDong1993@qq.com

如果你不需要三台设备，50一台设备，整个账号拿走130

需要注意的是，这个专业版绑定就是我自己的邮箱，我不能把邮箱给你，你需要登录的时候，我实时提供登录码。

**Comment by 499504777** [comment]
你都知道不稳定我还要他作甚？笑哭......

**Comment by LeonDong1993** [comment]
@499504777  主要就是前段时间不稳定嘛，现在基本上已经稳定了。

只不过我买的时候刚刚好是最需要FQ但刚好它不稳定的时候，所以我也很无奈。。。。。

**Comment by songxuangh** [comment]
## 输入我的邀请码

> # GY6S6C

## 来获得三个月的蓝灯专业版

**Comment by hu369258147** [comment]
加我微信兄弟，给你发了邮箱你也没回，HU61989751

**Comment by hoctoboy** [comment]
你谁啊，别乱瞎发东西

2017-11-14 14:56 GMT+08:00 hu369258147 <notifications@github.com>:
