### ISSUE TITLE
android版本很卡，无法使用专业版

### ISSUE THREAD

**Issue by tomkluas** [getlantern/lantern#6625]
小米5，MIUI9.1.3系统，App运行卡顿，经常假死，授权专业版时没反应，不会跳到专业版界面，翻墙速度也很慢（怀疑是没连上），请保持更新

**Comment by huadee001** [comment]
换新版本

**Comment by ouhaochuan** [comment]
小米note3 miui9稳定版，运行正常，去下个最新版试试吧
