### ISSUE TITLE
怀疑蓝灯在收集用户数据

### ISSUE THREAD

**Issue by ljwzz** [getlantern/lantern#6656]
手机版，开启后上传网速飞快，然而我什么都没开，Google首页都打不开，电脑端好一点，不过一样在收集数据，莫名其妙的网就段一阵，

要求退钱，购买账户gljwzz@gmail.com

**Comment by ddkf2001** [comment]
你那点数据就是垃圾，有什么好收集的

**Comment by pinkApple** [comment]
有可能你在帮别人下载数据, 早期的蓝灯据说是P2P技术.

**Comment by ljwzz** [comment]
@ddkf2001 关键是我网速啊，大哥，900k的网速带来的流量消耗是看玩笑的吗，求问咋退款

**Comment by WellerQu** [comment]
这用得着怀疑? 打开代码看看不就完事儿了吗?

**Comment by songxuangh** [comment]
@WellerQu 不是每个人都能看懂代码的啊

**Comment by CNMEE** [comment]
国家领导人？数据这么值钱
