### ISSUE TITLE
超详细的自建梯子教程

### ISSUE THREAD

**Issue by moving3** [getlantern/lantern#6744]
[https://github.com](https://github.com/tonyflanc/BTGFW)

**Comment by lnet** [comment]
输入我的邀请码 YZD6NU 立即获得三个月的蓝灯专业版！

**Comment by skyaugust** [comment]
输入我的邀请码 283QUR 来获得三个月的蓝灯专业版！

**Comment by yuyanbing** [comment]
输入我的邀请码 YGTWUF8 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
