### ISSUE TITLE
Fix "Lantern Proxy Configurator" Firefox extension

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#678]
Lantern should remove the extension whenever it's not running.

Was:

Firefox has supported and defaulted to using system proxy settings like other browsers for several releases now, so we no longer need to install this extension on users' computers.

**Comment by vcarus** [comment]
Same problems here.
I've uninstalled Lantern, but can't remove the extension.
I ran Lantern in Get mode, too.

Mac OSX here. I can't find the AppData folder or something like that. Anyone can help me please.
@myleshorton @scouttle @FrogManBear

**Comment by myleshorton** [comment]
Hey @vcarus sorry for the delayed reply, but you can remove it manually from here:

/Users/your_user_name/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}

**Comment by vcarus** [comment]
@myleshorton Thanks for your reply.

I went to the about:config page of firefox and searched the key word lantern.
2 things found, and manually removed.
Done.

**Comment by myleshorton** [comment]
Great @vcarus! Yeah that's probably the easier route =).
