### ISSUE TITLE
出售lantern无限流量补丁,20出

### ISSUE THREAD

**Issue by aa3212689** [getlantern/lantern#6841]
window和android都有,联系q 1064404481

**Comment by LanternSS** [comment]
补丁这种东西，拿出来卖了就不可靠了。
蓝灯不会花20从你这里买了给把漏洞补上么？

**Comment by aa3212689** [comment]
说得很有道理,不应该在人家的地盘卖

**Comment by Doutianbao** [comment]
@aa3212689 你这种傻逼，拿别人的成果出来卖，要点碧莲吗
