### ISSUE TITLE
有没有注意蓝灯都一年没更新过了。

### ISSUE THREAD

**Issue by Xanthuim** [getlantern/lantern#6855]
蓝灯没人管了吗？都一年没维护了，那么新的版本从何而来啊？

**Comment by philipz12** [comment]
一直在更新啊

我的邀请码 X49M25 ，常年有效。

**Comment by kilimimi** [comment]
现在更新的那些都有后门，推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～ 
http://cp.dawangidc.com/aff.php?aff=523 
购买服务后请看配置教程 
https://fqjsjl.tumblr.com

**Comment by shuiRong** [comment]
@philipz12  Github仓库显示最近（代码）更新是一年前，哪来的“一直在更新”。除非在后续更新没有开源？
