### ISSUE TITLE
分享新型科学上网方法

### ISSUE THREAD

**Issue by lanterner** [getlantern/lantern#7014]
这是一个通过云主机建立科学上网服务的方法，
输入优惠码后年付18.79美元起，折合人民币120元，
教程很简单，几分钟就ok了，youtube 1080p无压力。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [教程链接](https://www.tbreak.top/kda/56/)

**Comment by richardfick** [comment]
<html>
<body>

自己搭太麻烦了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by lanterner** [comment]
你们这些圈钱就跑路的，滚一边去
