### ISSUE TITLE
tumblr速度很慢       邀请码 JWBMX4 你我都获得3个月 谢了

### ISSUE THREAD

**Issue by asdg-asdf** [getlantern/lantern#7016]
tumblr速度很慢       邀请码 JWBMX4 你我都获得3个月 谢了

**Comment by richardfick** [comment]
<html>
<body>

Lantern已经挂了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by asdg-asdf** [comment]
谁说的  lantern 我这用的  很好呀  就是 tumblr 比较慢 其他都很快   比如 facebook  ， ttwrite  ，
