### ISSUE TITLE
分享一键安装SS出墙教程，小白十分钟搞定，一年120￥成本 | 支持IOS

### ISSUE THREAD

**Issue by SS10minsetup** [getlantern/lantern#7069]
[搬瓦工](https://bwh1.net/aff.php?aff=24912)是美国一家稳定优秀的VPS提供商，最早支持支付宝支付和后台搭载一键式安装SS脚本。新手只需按照教程注册并购买最优惠的$19.9(折后120人民币)一年的[套餐](https://bwh1.net/aff.php?aff=24912&gid=1)，即可自由上网，全平台支持（含IOS），不限设备数，个人使用这个基础套餐非常合适。

**最新消息，$19.9套餐又断货了。**
大家可以买其他合适的套餐搭建私人VPN

[# **注册直达**](https://bwh1.net/aff.php?aff=24912&register=true)
[# **教程链接**](https://pan.baidu.com/s/1bqch8lx)

**Comment by lanterner** [comment]
这位大胸弟，你到底有多少马甲
