### ISSUE TITLE
10分钟搭建多人科学上网解决方案

### ISSUE THREAD

**Issue by ghostlantern** [getlantern/lantern#7094]
fq还是自己搭建好比较好，所有公众使用的都是以盈利为目的，
自己搭建的速度快，没那么容易被墙，而且不限设备，
多人共享，买个VPS，年付28.19美元，折合人民币180元，支持支付宝付款
然后自己搭建
教程很简单，几分钟就ok了，youtube 1080p无压力。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by guoxiaoxu** [comment]
哈哈，不会告诉你蓝灯4K妥妥的，8K微卡。还有你实在不想用蓝灯，建议你google下google clound搭VPN
