### ISSUE TITLE
新型科学上网方案V2ray值得一试，只需几分钟便可搭建

### ISSUE THREAD

**Issue by fkghostwithout** [getlantern/lantern#7106]
最近很多fq软件都挂了，fq还是自己搭建好比较好，
自己搭建的速度快，没那么容易被墙，而且没有任何设备限制，
买个VPS，输入优惠码后年付28美元起，折合人民币180元，多人合租分摊成本更低
然后自己搭建ssr或v2ray(最新模块化fq技术，支持多用户，集成kcptun)
教程很简单，几分钟就ok了，youtube 1080p无压力。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by wifoipx** [comment]
<a href="http://cp.dawangidc.com/aff.php?aff=523">you can try this way！</a>
