### ISSUE TITLE
How to configure Thunderbird to work with Lantern

### ISSUE THREAD

**Issue by SiqingYu** [getlantern/lantern#7110]
My system is Ubuntu 16.04.
I have tried:

- No proxy.
- Auto-detect proxy.
- Use system proxy.
- Manual proxy configuration.

None of above work.

![screenshot from 2018-02-07 19-37-10](https://user-images.githubusercontent.com/22290018/35914819-af36a31e-0c3f-11e8-8a70-14868c3813d7.png)

![fireshot capture 15 - lantern pro_ - http___localhost_38241_](https://user-images.githubusercontent.com/22290018/35914954-1c61815c-0c40-11e8-8dc1-b5b6c9e27999.png)

**Comment by guoxiaoxu** [comment]
Proxy all traffic  Checked，you can try other，Auto-detect proxy.
![snipaste_20180207_215542](https://user-images.githubusercontent.com/26244337/35920112-ebdbfdca-0c51-11e8-804c-636c2c7c2e3f.jpg)

**Comment by SiqingYu** [comment]
@guoxiaoyu Thanks, this worked like a charm.
