### ISSUE TITLE
蓝灯扑街了，来试试v2ray

### ISSUE THREAD

**Issue by dgdcg** [getlantern/lantern#7111]
教程很简单，几分钟就ok了，自己搭建没有任何设备限制，爱怎么玩，就怎么玩。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by hwp88110** [comment]
找到个能免费使用的 速度也还可以 https://www.binbinss.bid/auth/register?code=XW5xuATs4ELAmqTdWKUfYqqpbu785gOK
