### ISSUE TITLE
Lantern现在好不稳定

### ISSUE THREAD

**Issue by monkeyking** [getlantern/lantern#7173]
不知道什么情况 现在特别不稳定 还会掉线 （在网络状态很好的时候 显示 连接中）
然后速度特别的慢 奇慢无比 可能我用了假的专业版
所以开发者是要我们放弃lantern了吧

**Comment by shelldu** [comment]
我用的都很稳定啊，看看是不是网络本身的问题吧，或者是浏览器的问题。我之前用火狐也遇到问题，换了chrome现在稳定多了。

我的邀请码 2YYJBN

**Comment by asdg-asdf** [comment]
我访问 facebook 和 ttwriter  无问题  访问 tumblr 不太好  其他网址速度都还好

**Comment by monkeyking** [comment]
所以现在又恢复正常了
