### ISSUE TITLE
ios 版本啥时候出来啊

### ISSUE THREAD

**Issue by Twitchboy** [getlantern/lantern#7182]

**Comment by shelldu** [comment]
很困难，别等ios版的了，换android机吧。技术上估计是没太大问题的，但是Apple store上的应用都要经过审核的，根据我们的国情，所以你懂的。啥时候能出个越狱版的都不错了。

我的邀请码 2YYJBN，赠送3个月专业版，互惠互利。

**Comment by asdg-asdf** [comment]
ios 期待中

**Comment by Twitchboy** [comment]
@shelldu ios 软件 也有很多没有上store,通过描述文件来进行安装的~ 我早已开通专业版

**Comment by panxskn** [comment]
输入最新邀请码 58GG2S  ，会赠送3个月专业版；立即下载https://github.com/getlantern/forum

**Comment by IvanYue** [comment]
只能说蓝灯不想做，因为一年App Store开发者账号要699！！！可以不在国内App Store上架。现在谁没有个国外的Apple id。。。
