### ISSUE TITLE
输入最新邀请码 58GG2S 赠送三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by panxskn** [getlantern/lantern#7240]
输入最新邀请码 58GG2S 赠送三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by panxskn** [comment]
Enter the latest invitation code 58GG2S give three months of blue light Pro! Download https://github.com/getlantern/forum now

**Comment by JerrySir** [comment]
骗子，就送一个月
