### ISSUE TITLE
3.14，21：42 最新版可用

### ISSUE THREAD

**Issue by NearJiang** [getlantern/lantern#7323]
上了youtube，可以看到用的是湾湾的地址，国家对湾湾还是持着包容开放的精神啊！

**Comment by NearJiang** [comment]
21:45  又给换回日本的了，感觉没湾湾的快

**Comment by JeffcottLu** [comment]
怎么更新蓝灯呢？重新下载吗？好像没有一键更新的按钮

**Comment by NearJiang** [comment]
@JeffcottLu 嗯，重新下载安装即可，无需卸载之前的版本。
