### ISSUE TITLE
3.18  18:42 即使播报

### ISSUE THREAD

**Issue by NearJiang** [getlantern/lantern#7371]
更新了最新版，我这边给配的湾湾的代理地址。速度杠杠的，不知道等会儿会不会死。。。

**Comment by Michaelooo** [comment]
怎么配置代理地址，我默认是日本的……

**Comment by NearJiang** [comment]
@Michaelooo 这都是自动给配置的，现在的lantern没有自选选择的选项。强烈要求增加自行更改地址的选项！   
再来个即时播报：3.19 16：01 ，地址：湾湾，速度：youtube1080p无压力。
