### ISSUE TITLE
有没有一起搭车的 一人50rmb一年 5人开团  (人已满)

### ISSUE THREAD

**Issue by old2** [getlantern/lantern#7416]
![image](https://user-images.githubusercontent.com/16619095/37744745-cf62fd6c-2dab-11e8-838b-e1e151fbb3f2.png)

感兴趣的的留微信号 拉入群

**Comment by nanzihan** [comment]
wshcheng

**Comment by old2** [comment]
@nanzihan 收到~ 你可以把微信号删了

**Comment by liuxueliang111** [comment]
a745375757

**Comment by old2** [comment]
@liuxueliang111 收到~  你可以把微信号删了

**Comment by junedgar** [comment]
jun_edgar  算我一个

**Comment by old2** [comment]
@junedgar 好的 人齐了
