### ISSUE TITLE
推荐一个SSR翻墙服务商

### ISSUE THREAD

**Issue by 5d1f14gf1** [getlantern/lantern#7440]
最低月付10元
网址：
https://www.tkc.im/auth/register
船票：
OpDp8zWCpWlAT8XFqW5mz0ENXZbFU0Ma
3nUAc37a4Iui7vcehhMHJwp1jjaJQKbF
Fx1TQmc5f8Ahrn6mrQdxunPPUV7ldB0i
Il9P6uX5ptxAhfVVG5ZMGbXsdNVuFP4c
Ooqis8pNKxhRSDVMYkTO5eGaSn2sEOir

**Comment by hwp88110** [comment]
可以试一下这个，每个月都有10G的免费流量，速度也很块，注册一下就能使用
https://www.binbinss.bid/auth/register?code=ufn6BrFurD7Lt1GJ5CyvfxevPTfsrzzo

**Comment by xiaogu-space** [comment]
邀请码无效
