### ISSUE TITLE
合租自己的SSR, Ping值30ms, 账号试用，个人搭建稳定，分摊

### ISSUE THREAD

**Issue by optimus1009** [getlantern/lantern#7517]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限流量网速
2: pc 手机，ios ,mac 都能用

**# wechat: x-lin0914**

**# ping值，延时很低，也很稳定，没有跳ping**
![ping](https://user-images.githubusercontent.com/11548953/38145689-3057a0fa-347d-11e8-83e1-2c02a9402bad.png)

# **这是YouTube4K**

![youtube](https://user-images.githubusercontent.com/11548953/38145722-5bc770a8-347d-11e8-8798-8aa72f0fdc53.jpg)

**Comment by ivanleo** [comment]
你这是哪里的服务器？速度这么快？

**Comment by nanzm** [comment]
合租 多少钱 我是程序员

**Comment by optimus1009** [comment]
联系我微信， x-lin0914
