### ISSUE TITLE
合租SSR, Ping值30ms, 账号试用，个人搭建稳定

### ISSUE THREAD

**Issue by optimus1009** [getlantern/lantern#7534]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限网速
2: pc 手机，ios ,mac 都能用

# **wechat : x-lin0914**

![ping](https://user-images.githubusercontent.com/11548953/38203207-060cba78-36d1-11e8-9924-e02a83896a95.png)

# **YouTube 4K 超高清流畅**

![youtube](https://user-images.githubusercontent.com/11548953/38203227-17b61792-36d1-11e8-9a6e-be7a0c246edd.jpg)

**Comment by Richard-Choooou** [comment]
多少钱一个月

**Comment by goodjimli** [comment]
不怕查水表？

**Comment by ArthurRyan** [comment]
楼主请私信试用账号

**Comment by VincyChan** [comment]
求试用！

**Comment by yuanzhiTsuki** [comment]
多少钱合租？

**Comment by chooseworld** [comment]
请加下微信，我直接给出试用账号
