### ISSUE TITLE
邀请码 YGTWUF8 来获得三个月的蓝灯专业版

### ISSUE THREAD

**Issue by yuyanbing** [getlantern/lantern#7541]
输入我的邀请码 YGTWUF8 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by panxskn** [comment]
输入最新邀请码 58GG2S 赠送三个月的蓝灯专业版

**Comment by fateblessme** [comment]
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
购买一年，送一个月；购买两年，送三个月。
