### ISSUE TITLE
蓝灯注册大优惠

### ISSUE THREAD

**Issue by zhanggaoxiang001** [getlantern/lantern#7548]
输入我的邀请码 YG9KJ86 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by panxskn** [comment]
最新邀请码 58GG2S 获得三个月的蓝灯专业版！

**Comment by fateblessme** [comment]
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
购买一年，送一个月；购买两年，送三个月。
