### ISSUE TITLE
合租SSR, Ping值30ms, 账号试用，个人搭建稳定

### ISSUE THREAD

**Issue by chooseworld** [getlantern/lantern#7551]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，加下我微信，给试用账号体验下，
1: 不限网速
2: pc 手机，ios ,mac 都能用

# **wechat : x-lin0914**

![ping](https://user-images.githubusercontent.com/38099363/38357490-5d1b9f52-38f5-11e8-8d50-e0bc9b34bea2.png)

![youtube](https://user-images.githubusercontent.com/38099363/38357503-64d1221c-38f5-11e8-9f8e-779da4e50ca2.jpg)

**Comment by huaguang** [comment]
How much
