### ISSUE TITLE
合租SSR, Ping值30ms, 账号试用，个人搭建稳定

### ISSUE THREAD

**Issue by chooseworld** [getlantern/lantern#7559]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限网速
2: pc 手机，ios ,mac 都能用

# **wechat : x-lin0914**

![ping](https://user-images.githubusercontent.com/38099363/38467613-0c0731dc-3b6e-11e8-98db-4f8d0d33902b.png)

YouTube # **4K直接没压力**

![youtube_2](https://user-images.githubusercontent.com/38099363/38467617-17d8da4c-3b6e-11e8-9f2b-e1a6f2b69377.png)

**Comment by Mecds** [comment]
怎么联系

**Comment by chooseworld** [comment]
我的微信 x-lin0914

**Comment by fateblessme** [comment]
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
购买一年，送一个月；购买两年，送三个月。

**Comment by AndroidZern** [comment]
输入我的邀请码 H74NTR 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
