### ISSUE TITLE
合租自己的SSR, Ping值30ms，香港服务器，速度超快

### ISSUE THREAD

**Issue by algernonsmith** [getlantern/lantern#7625]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，
1: 不限网速
2: pc 手机，ios ,mac 都能用
3: 可以代理游戏，可以代理游戏

# **wechat: x-lin0914**

# **30ms多的延时，几乎是秒开**

![ping](https://user-images.githubusercontent.com/38640620/39105513-eaa50b1e-46e8-11e8-9f3c-76d112ada49a.png)

YouTube 4K

![youtube](https://user-images.githubusercontent.com/38640620/39105518-f35aec7e-46e8-11e8-8d37-8866c2835224.jpg)

**Comment by Kevinl7** [comment]
怎么卖的？
