### ISSUE TITLE
ssr合租，专线

### ISSUE THREAD

**Issue by algernonsmith** [getlantern/lantern#7685]
自己的服务器，严格控制人数，8个人一组网速稳定，基本没有出过问题，1080P的视频几乎秒开，平时的4g手机网大概2-3m/s 的网速，这基本就可以看任何视频了，
另外还搭建了一个 延时30ms的服务器， 可以代理游戏，比如韩服吃鸡基本不延时，我试过，这个服务器就比较极端了，4K也秒开

# **wechat ： x-lin0914**

![ping](https://user-images.githubusercontent.com/38640620/39739751-1ef1d414-52c5-11e8-967f-623b6c709d45.png)

# **YouTube 4K**

![youtube](https://user-images.githubusercontent.com/38640620/39739757-290714be-52c5-11e8-9c63-6a69201cfbb0.jpg)

**Comment by IronnMan** [comment]
ios 手机和 mac 电脑都可以一起连吗？

**Comment by zhumingzhe8888** [comment]
租lantern'账号 一个月10块 一季度20 有两个坑位可以租 方便大家试用一下再决定是否要买 wx 627909837
