### ISSUE TITLE
不想废话，俩个字：垃圾！什么狗屁速度，几分钟的视频他们几十分钟才能加载完

### ISSUE THREAD

**Issue by NearJiang** [getlantern/lantern#7771]

**Comment by ghostwith** [comment]
请提供如下信息，不提供无法调查。

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。
