### ISSUE TITLE
蓝灯屡次停止闪退无法正常使用闪退

### ISSUE THREAD

**Issue by yxh2467486898** [getlantern/lantern#7780]
为啥最近几个版本只要检查更新就会闪退啊。而且软件本身会自动检查更新根本没办法正常使用啊啊啊

**Comment by ghostwith** [comment]
请提供如下信息，不提供无法调查。

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

**Comment by yxh2467486898** [comment]
首先我是安卓版的。
这是我的邮箱：yxh2467486898@qq.com


vpn可以正常使用，但打开软件不出10s就会闪退，经测试可能软件自动检查更新导致闪退，猜测可能是软件冲突？不过我装了太多app，没办法一一排查


无法在应用里反馈，因为来不及发送就闪退了，

**Comment by yxh2467486898** [comment]
这是闪退视频  录屏神器_20180611_025819_20180611030244.mp4
https://pan.baidu.com/s/19C9jjR7f3MMyZM7ZQYaq3g

还需要我提供什么吗？？？

**Comment by yxh2467486898** [comment]
@ghostwith

**Comment by yxh2467486898** [comment]
4.7.5已解决
