### ISSUE TITLE
今天突然各种工具都失效了，电信和移动网络，各种方法试了一遍，全都翻不出去

### ISSUE THREAD

**Issue by yzr006** [getlantern/lantern#7781]
不止是蓝灯，还有自建SSR，也是失效，坐标广州，还有人同样情况么？

**Comment by aojie654** [comment]
用#7777 的方法试一下，打开orbot后开启蓝灯再试试😆

**Comment by yzr006** [comment]
@aojie654 求大哥发个安装包。。已经翻不出去了，无法下载了。。。
