### ISSUE TITLE
三个月了,还不能用.搞屁啊.

### ISSUE THREAD

**Issue by lihaibo123as** [getlantern/lantern#7790]
三个月了,还不能用.搞屁啊.三个月了,还不能用.搞屁啊.三个月了,还不能用.搞屁啊.三个月了,还不能用.搞屁啊.一直连接 HK ,连接了不能用还连接 HK ,哪个撒逼程序员写的匹配规则.摆明着骗钱啊.

**Comment by lihaibo123as** [comment]
连接 JP 完全没问题,有没胆量出个自己选择线路,不出这个严重怀疑是故意匹配到 HK 不能上网的,骗钱,这项目估计页要黄了

**Comment by ghostwith** [comment]
请提供如下信息，不提供无法调查。

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

**Comment by lihaibo123as** [comment]
lihaibo123as@163.com 就一直没法访问 youtube 连接 JP 都很快.坑爹的就要连接 HK完全打不开
