### ISSUE TITLE
SSR坑位合租，稳定不掉，算法工程师维护

### ISSUE THREAD

**Issue by halseycooley** [getlantern/lantern#7818]
合租一个自己的服务器，网速稳定，基本没有出过问题，1080P的视频几乎秒开，平时的4g手机网大概2-3m/s 的网速，这基本就可以看任何视频了，自己算法工程师，稳定维护，赚点外快

# **wechat ： x-lin0914**

# **这个一个服务器的ping值测试**

![ping](https://user-images.githubusercontent.com/40140829/41201143-ee674d76-6ce4-11e8-99f9-7ae01132d3ff.png)

# **4K 流畅看**

![youtube_2](https://user-images.githubusercontent.com/40140829/41201152-0f9629d6-6ce5-11e8-8b9b-c442138c59de.png)

**Comment by fonglaaaam** [comment]
价格几何
