### ISSUE TITLE
使用软件购买了2年专业版，但是无法登录，麻烦解决一下。（为什么故意关闭我的问题，这是第二遍）

### ISSUE THREAD

**Issue by wangyukun-hxb** [getlantern/lantern#7873]
购买了两年的专业版，但是无法登陆。  
商品说明：ebdfc5d0-785e-11e8-9dab-4af9fcf624a5    
订单号：2018062521001003620529421193   
注册的邮箱是：316336594@qq.com

**Comment by AibiTi** [comment]
就是要故意。

**Comment by amylmy** [comment]
你这样把信息都放出来是不是不安全。。。也许关闭是为了保护你的信息？

**Comment by RadditPig** [comment]
输入我的邀请码 WM2GRY 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lixialongch** [comment]
这个可以退钱吗，几乎70％的时间用不了

**Comment by tiantian040804** [comment]
去年买的专业版 两年的 买完两个月左右开始各种问题 但是从来没正常过 香港日本线路不停跳线  下载速度达不到100K 期间各种无法连接  虽然补偿了几个月 但是同样的相当于浪费了 真心无法支持 希望团队能够切实解决问题 更新了这么多版本 没有一版能够稳定可靠的 唉……绝对不会再续费了

**Comment by orbancanon** [comment]
抱歉@wangyukun-hxb 后台定位花了一些时间。现在你的帐号已经恢复正常了。
