### ISSUE TITLE
ExpressVPN30天的使用邀请码（刚才用十几dollar购买后赠送的，欢迎免费共享）

### ISSUE THREAD

**Issue by Renata456** [getlantern/lantern#7876]
可以免费用30天，随时可以live chat和客服取消，然后退钱。
建议购买一个月的，12.95$ 

https://www.expressrefer.com/refer-a-friend/30-days-free/?referrer_id=19368557&utm_campaign=referrals&utm_medium=email&utm_source=referral_dashboard

**Comment by RadditPig** [comment]
输入我的邀请码 WM2GRY 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
