### ISSUE TITLE
购买专业版一周后仍无法使用

### ISSUE THREAD

**Issue by jasonguo203** [getlantern/lantern#7891]
邮箱jasonguo203@gmail.com
商品说明：e44b1290-7695-11e8-9dab-4af9fcf624a5
订单号2018062321001003040548217936
商户订单号AliPayFX_1815297246935668_6068
登录显示无法找到对应邮箱账号，请帮忙尽快解决！！

**Comment by orbancanon** [comment]
@jasonguo203 支付服务那边有点问题，刚刚处理了，请再试一下。
