### ISSUE TITLE
TM!!!把我们大陆网民当免费提款机呢！

### ISSUE THREAD

**Issue by NearJiang** [getlantern/lantern#7922]
我们大陆网民基本都是买了2年的套餐，TM这每过俩月就瘫痪，每过俩月就瘫痪！！！！

拿钱供你们资本主义！
我cnm！！！！
当初免费吸了我们大陆大量的人流量（当初免费的时候还真好），现在付费给你们，你们拿去食屎啦！！！！！！！

**Comment by zzwar2009** [comment]
一两周不好使了  之前都是好好的

**Comment by AprilCat** [comment]
这两天确实又开始不好使了

**Comment by xiehuihui** [comment]
持续一个月了，JP、HK不断的切换服务器，白瞎了爸爸两年的会员

**Comment by free-vpn** [comment]
chrome开发版，直接当梯子
[https://free-vpn.github.io/chrome/](https://free-vpn.github.io/chrome/)
