### ISSUE TITLE
七月九号开始就无法翻墙

### ISSUE THREAD

**Issue by HBXSZ** [getlantern/lantern#7955]
无法访问google,代理地址为HK，期间修改了host文件绑定了127.0.0.1，同一专业账号下的安卓设备可以翻墙代理地址通为HK，跟我的设备不在一个省，我想知道这是暂时性的还是因为我所处的网段原因

**Comment by grasscase** [comment]
hk有的网站不能访问，有时候甚至amazon都会断，但是它又不自动切换到其他服务器

**Comment by HBXSZ** [comment]
@grasscase emmm 按照以往的使用经验 过十来个小时会切一个代理 现在一直都是HK 我表示这不能翻墙很伤

**Comment by HBXSZ** [comment]
已经解决了一半的样子   跟谷歌插件Host Switch Plus冲突，自己win10电脑修改的host文件不生效，于是用了这个插件 然后就翻不了墙= =
