### ISSUE TITLE
遇到问题请直接到lantern界面反馈，会根据日志调查

### ISSUE THREAD

**Issue by FreshMa** [getlantern/lantern#7966]
就是一个骗钱的东西，一交钱立马没法用，我已经在play商店一星加举报了，大家也都举报去吧。顺便问问能不能跟有关部门，比如消协，网信办等举报一下这个这个应用？

**Comment by funggtopp** [comment]
消协？网信办？哈哈。不知道这个是不允许的？

**Comment by Ghostwithout** [comment]
你好，如果使用遇到障碍请直接到lantern界面反馈，会自动上传日志以便调查。谢谢！@FreshMa
