### ISSUE TITLE
北京在开会，所以不让用

### ISSUE THREAD

**Issue by zwl1619** [getlantern/lantern#8044]

**Comment by zhaocy1217** [comment]
开什么会呢

**Comment by Alpha2049** [comment]
hehe

**Comment by yinhaofrancis** [comment]
呵呵

**Comment by pikachuusama** [comment]
开什么会？

**Comment by tbzqs** [comment]
今上刚刚出访，你说北京在开会，你啥意思？

**Comment by awt135** [comment]
龍龍刚刚出访，你说北京在开会，你啥意思？

**Comment by u2daye** [comment]
别每次软件有问题就自己帮他们找这种理由，我手机里几个免费的这两天一直都能用为什么就只有蓝灯用不了？

**Comment by plb1213** [comment]
别找理由，哪个免费vpn不是好好的，偏偏蓝灯这么娇气？

**Comment by grasscase** [comment]
为什么只能连接jp？ 可不可以换其他服务器？ 难道只有jp，hk服务器？ 最近自动连接只能自动连接jp，为什么不能换其他的服务器啊？因为jp很多网站断断续续打不开

**Comment by ookangzheng** [comment]
其他家express, vyper, 之類的top 10的幾乎都被封鎖了，等風波過去吧

**Comment by ddianxing** [comment]
移动宽带，从昨晚开始联接不上了！……

**Comment by ntr1989512** [comment]
我也是连不上，且总是日本的服务器，已经3天了
