### ISSUE TITLE
lantern-form repo 没有了（dismiss），为何不反思？

### ISSUE THREAD

**Issue by wpy007** [getlantern/lantern#8069]
一个悲伤的故事，刚才因为lantern 4.7.9 JP节点很慢，打开github搜索lantern-form，却发现没有任何搜索结果了。我不知道发生了什么，也只是一个猜测，国人实在不堪重负，关闭了form repo。之前常逛lantern论坛，是因为看到各位撕逼，喷lantern官方，觉得是挺好玩的一件事情。我保持着看客的身份，虽然我去年lantern也续了两年然后进入了无限翻墙 失败/不稳定/低速 阶段，很不开心，但是我懒得出售，懒得喷，因为比较内向，不希望刷存在感。
现在lantern论坛没了，打开lantern的issue，前几条全是直接骂人的，让我感到非常失落，我的确没有什么话语权，但我还是想说，为何不能克制一下自己？
- lantern的constructor只有少部分的国人，你们拿着普通话去喷官方，外国人看不懂，国人不知道分红几何，但是看到你们天天骂他们，都是人，凭什么要一直忍受？
- lantern是你们的个人选择，因为搭不起或者不会搭ssh，所以选择了lantern，那么你们为何直接把矛头指向了官方，而不为自己的选择买单？
- 如果想骂官方，为什么不去用英文问候一下google的外国人，非要用普通话，让那些看得懂的中国开发者去承受你们语言的重量？自己人伤害自己人？
希望大家将心比心，毕竟大多数来这里的都是程序员，何必呢。

以下是简陋的英文水平搭配有道词典的简陋英文翻译
A sad story, lantern-form repo dismissed. I know there are too much abuse && ads aim to lantern developer, it's really a pity. I hope everyone relfects on his own, reduce abuse，try to keep this repo peace.

**Comment by plb1213** [comment]
而且你也别自作聪明在此冷静分析，辽宁电信用ssr极不稳定，我连续买了3个服务器、换了各种混淆和节点依然无用(校园网却轻松连接)，在家只能选择vpn。
我不清楚哪里能问候到所谓谷歌的外国人，他们甚至都不出现在github？

**Comment by plb1213** [comment]
大家都不必忍受，蓝灯完全可以退钱结束，皆大欢喜，但蓝灯不愿意。

**Comment by wpy007** [comment]
close: so I real disguest trash people，close this issue.
