### ISSUE TITLE
lantern 4.7.9 macos10.13.6 总是掉线 灰色图标而且 打开lantern时有时候连百度都打不开

### ISSUE THREAD

**Issue by whsgzcy** [getlantern/lantern#8106]
我的pc macos10.13.6 macbook air，最近更新lantern到4.7.9，发现他老是掉线，有时候打开lantern时连百度都打不开或者打开很慢，退出之后百度打开就很快，有没有解决方案，或者有没有除了4.7.9最近的版本的dmg安装文件？我的邮箱whsgzcy@foxmail.com，thanks a lot，

**Comment by LeoDemon** [comment]
+1

**Comment by xuxu116** [comment]
+1

**Comment by amylmy** [comment]
+1

**Comment by liuxiyuan1018** [comment]
+1 windows系统一个症状，估计又一轮筑墙行动在展开。

**Comment by vespex** [comment]
+1

**Comment by zizikuang** [comment]
不能是政府搞的吧？我的情况和你完全一样，打开蓝灯百度贴吧都打不开了！！而且一直在连接中！连半天也连不上，连上就持续几秒就不行了，比我还弱！！！！是不是这个新版本有重大缺陷，管理人员快点回复解释下情况啊！！

**Comment by whsgzcy** [comment]
恢复了，再次下载最新版本，把之前的版本下载掉，重新装一次，南京，

**Comment by whsgzcy** [comment]
fixed #xxx
