### ISSUE TITLE
求推荐 付费 vpn 不要免费的 

### ISSUE THREAD

**Issue by zxb5102** [getlantern/lantern#8207]
求推荐 付费 vpn 不要免费的

**Comment by zxb5102** [comment]
这 lantern 最近真 的是难用

**Comment by xjr7670** [comment]
付费的SSR，还是可以有的

**Comment by skylar31** [comment]
红杏也不行...不能买服务了
我刚刚买了express
价格相对有点贵...我用github小伙伴的链接注册购买，可以互得一个月免费，也就是80元左右2个月。需要应急的小伙伴可以试试看。

https://www.expressrefer.com/refer-friend?referrer_id=20369219&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard

**Comment by mioopoi** [comment]
@skylar31 Express确实有点贵，用你的链接开了两个月，先试用看看。蓝灯的速度挺快的，就是不稳定
