### ISSUE TITLE
蓝灯不稳定完美解决方案！

### ISSUE THREAD

**Issue by jexooooo** [getlantern/lantern#8235]
自建节点，秒杀蓝灯！ 不稳定你可以提刀来砍我！ 丢个网站就跑 dtssr.xyz 
‘(*>﹏<*)′真刺激

**Comment by zhanning** [comment]
这个操作可以

**Comment by xxxvy88** [comment]
蓝灯替代，比蓝灯稳定很多..  10块100G一月
http://ssrss.ml/register?aff=376
