### ISSUE TITLE
大家试试ExpressVPN，点链接送30天时间

### ISSUE THREAD

**Issue by acuityce** [getlantern/lantern#8264]
大家试试ExpressVPN，通过介绍购买链接送30免费使用天时间
https://www.expressrefer.com/refer-a-friend/30-days-free/?referrer_id=18102368&utm_campaign=referrals&utm_medium=email&utm_source=referral_dashboard

**Comment by ivsall2012** [comment]
我已经帮你贡献了一个月:)
