### ISSUE TITLE
Send in-client notification to user when they get first friended by someone

### ISSUE THREAD

**Issue by cholmes** [getlantern/lantern#947]
I just approved an invite in the queue that was lanternfriend inviting my gmail. It went out, with the same copy as all our other invites. 

Things like this lead some users to be getting tons of invitations, feels like things are broken.

#1070 covers the immediate fix - don't send anything.

The improved fix is to email the user about another user on lantern wanting to be friends, and telling them what to do to approve / deny.

**Comment by rngadam** [comment]
@oxtoacart actually, I do hang out in the Lantern UI and would really expect the friends notification to popup there and be handled there (not through email or system notification).
